### ISSUE TITLE
ising slower than Fortran version

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1020]
The ising use case here:
http://matthewrocklin.com/blog/work/2015/02/28/Ising/
is 2x slower than an equivalent Fortran version (see Ondrej's posts in the comments).
Chances are investigating this would allow to improve performance generically. From a quick look, our generated assembly is much longer than gfortran's. There may be issues with:
- integer modulo
- signed vs. unsigned operations
- exp() performance
- poor code generation for range()

**Comment by stuartarchibald** [comment]
URL is http://matthewrocklin.com/blog/work/2015/02/28/Ising, no trailing slash.

**Comment by stuartarchibald** [comment]
All the comments appear to be missing from the blog too. If this is still an issue, please reopen.
