### ISSUE TITLE
bug when upgrade  numba 0.16   -> 0.17

### ISSUE THREAD

**Issue by brunomorvan** [numba/numba#1031]
this code compile in nopython mode with llvmlite 0.2.0 and numba 0.16.0 :

%timeit sortnumba(a)
1 loops, best of 3: 386 µs per loop

it doesn t work ater update : 

    llvmlite: 0.2.0-py34_0      --> 0.2.2-py34_1     
    numba:    0.16.0-np19py34_0 --> 0.17.0-np19py34_0

%timeit sortnumba(a)
1 loops, best of 3: 538 ms per loop

from pylab import zeros,random_sample

def sorti(a):    
  if len(a)>1: 
    h=50 #stack size, #ln(n)
    deb=zeros(h)
    fin=zeros(h)
    i=0 # stack pointer
    d0,f0=0,len(a)-1 
    while i>=0:
        d,f=d0,f0
        piv=a[(d+f)/2]
        while d<=f:
            while a[d]<piv : d+=1
            while a[f]>piv : f-=1
            if d<=f :
                a[d],a[f]=a[f],a[d]
                d+=1
                f-=1
        if d<f0:
            i+=1 #push
            deb[i],fin[i]=d,f0
        if d0<f:f0=f
        else: 
            d0,f0=deb[i],fin[i]
            i-=1 #pop
    return i

from numba import jit,__version__
print(__version__,"<= 16 !")
sortnumba=jit(sorti)

sortnumba (random_sample(1e4))

**Comment by gmarkall** [comment]
When I run your code with Numba 0.17.0 the output is as follows:

```
$ python s.py
0.17.0 <= 16 !
```

What happens when you run it?

**Comment by brunomorvan** [comment]
thanks for the answer. 
first my pardon for a bad copy (no indentation,some lines lacks) : 
here is the good code. 

###### beginning of the code

def sorti(a):    
   if len(a)>1: 
      h=50 #stack size, #ln(n)
      deb=zeros(h)
      fin=zeros(h)
      i=0 # stack pointer
      d0,f0=0,len(a)-1 
      while i>=0:
         d,f=d0,f0
         piv=a[(d+f)/2]
         while d<=f:
               while a[d]<piv : d+=1
               while a[f]>piv : f-=1
               if d<=f :
                      a[d],a[f]=a[f],a[d]
                      d+=1
                f-=1
        if d<f0:
            i+=1 #push
            deb[i],fin[i]=d,f0
        if d0<f:f0=f
        else: 
            d0,f0=deb[i],fin[i]
            i-=1 #pop
    return i

from numba import jit
sortnumba=jit(sorti)

a=random_sample(1e5)
sortnumba(a)

######## end of code

I just change the size of the array.
on my PC (Windows, python 3 / pyzo)
with numba 0.16,  this program take about 4 ms to run
but with numba 0.17 it need about 10s.

when evaluating sortnumba.inspect_types()
I see that variables are typed as int64 with  numba 0.16
and typed as pyObject  with  numba 0.17

but I am not  avanced enough to understand why.

Regards.

Bruno MORVAN.

**Comment by seibert** [comment]
Editor's note: I edited the above comment to add ``` before and after the code block so that it shows up correctly in Github Markdown

**Comment by brunomorvan** [comment]
Le 10/03/2015 17:02, Stan Seibert a écrit :
>
> Editor's note: I edited the above comment to add ``` before and after 
> the code block so that it shows up correctly in Github Markdown
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/numba/numba/issues/1031#issuecomment-78085302>.
>
thanks ! I search without success this marker :)

-- 
Bruno MORVAN.

**Comment by seibert** [comment]
OK, doing a little debugging with the nopython=True option, it seems you are running into a change that was made to drop support for indexing an array with a float.  In particular, you need to set the dtype for your `deb` and `fin` arrays to ensure they have an integer type:

```
deb = zeros(h, dtype=int32)
fin = zeros(h, dtype=int32)
```
(I am assuming that you have `from numpy import *` at the top of your program based on how your example code is written.  If not, then the dtypes are `numpy.int32` rather than just `int32`.)

**Comment by brunomorvan** [comment]
greats !  
with 
```
#piv=a[(d+f)/2]
piv=a[(d+f)//2]
```
all is correct.

now I will use int for indexing array  :)
numpy give you lazy practice !

**Comment by seibert** [comment]
As an additional note: We made this change because Numpy 1.9 has deprecated float indexing and prints a warning when it happens.
