### ISSUE TITLE
Type detection failing for function that takes an int64

### ISSUE THREAD

**Issue by ngoldbaum** [numba/numba#1032]
I'm playing around with numba using a toy example for Monte Carlo integration to calculate pi.

Here's the code I'm using:

```python

from numba import jit, int64, float64, boolean

import random
import math

@jit(int64())
def generate_point():
    x = random.random()
    y = random.random()
    return (x, y)

@jit(int64(float64, float64))
def validate_point(p1, p2):
    if math.sqrt(p1**2 + p2**2) < 1.0:
        return 1
    else:
        return 0

@jit(float64(int64))
def calculate_pi_numba(n_points):
    n_inside = 0
    n_outside = 0
    
    for i in xrange(n_points):
        point = generate_point()
        n_inside += validate_point(point)
        
    return 4*n_inside/(n_points)
```

When I try to call the `calcualte_pi_numba` function with any integer argument, I get the following error:

```
In [2]: calculate_pi_numba(1000000)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d127d5918f64> in <module>()
----> 1 calculate_pi_numba(1000000)

TypeError: No matching definition
```

I'm new to numba so it's very possible that I'm doing something dumb.  If I am, I'd very appreciate any pointers you might have.

This is using the latest stable release of numba: `0.17.0`.

**Comment by gmarkall** [comment]
The issue is that you are passing `point`, which is a tuple, to `validate_point`, which takes two `float64` values. If you change `n_inside += validate_point(point)` to `n_inside += validate_point(point[0], point[1])` then the code compiles.

**Comment by ngoldbaum** [comment]
Argh, thanks.  I'm closing the issue.

**Comment by gmarkall** [comment]
No problem. It's also worth mentioning that the feedback to the user in this case is something that's been improved recently in the Numba master branch. When Numba 0.18 is released, it will give an error like:

```
TypeError: No matching definition for argument type(s) (float64 x 2)
```

for your original code, which helped me see what the issue is more easily.

**Comment by pitrou** [comment]
As a side comment, it is generally not necessary to type Numba functions explicitly. The JIT is able to infer the argument types on the first function call.
