### ISSUE TITLE
Wrong type determination for the sum2d example

### ISSUE THREAD

**Issue by rth** [numba/numba#1040]
I tried to run the `sum2d` example from the front page with numba, and I'm not getting any speed-up at all compared to pure python (see below).   The problem probably lies that `N`, `M` and `result` variables  types are determined as  `pyobject` instead of  `int` and `float` respectively.

I am using Python 2.7, numpy 1.9.1, llvm 3.5.1, numba 0.17.0,  llvmlite 0.2.1  on Gentoo Linux.

    Python QtConsole 3.0.0
    Python 2.7.9 (default, Mar  3 2015, 17:03:10)
    Type "copyright", "credits" or "license" for more information.

    In [1]: from numba import jit
       ...: import numpy as np
       ...: 
       ...: x = np.random.randn(1000, 1000)
       ...:
       ...: def sum2d(arr):
       ...:     M, N = arr.shape
       ...:     result = 0.0
       ...:     for i in arange(M):
       ...:         for j in arange(N):
       ...:             result += arr[i,j]
       ...:     return result
       ...:
       ...: sum2d_numba = jit()(sum2d)

    In [2]: %timeit sum2d(x)
    1 loops, best of 3: 241 ms per loop

    In [3]: %timeit sum2d_numba(x)
    1 loops, best of 3: 306 ms per loop

    In [4]: sum2d_numba.signatures
    Out[4]: [(array(float64, 2d, C, nonconst),)]
    In [5]: sum2d_numba.inspect_types()
    http://pastebin.com/VWFTJ5t4

**Comment by pitrou** [comment]
The example uses range(), not arange().

**Comment by pitrou** [comment]
Note, of course, not supporting arange() is a current limitation of Numba. The reason is we add memory management facilities to supporting allocating arrays inside Numba-compiled functions. But, here, range() is really sufficient: the example is only iterating over the range, not accessing it as an array.

**Comment by rth** [comment]
@pitrou  Sorry, actually the same thing happens when using `range` instead of `arange` http://pastebin.com/tfGa2u32  I was just trying to see if that had an impact as `arange` is imported for some reason in the example.

**Comment by pitrou** [comment]
I see. Can you add `nopython=True` to the jit decorator call? It will raise an error for the operations that failed typing. See e.g. http://numba.pydata.org/numba-doc/dev/user/jit.html#compilation-options

(note I cannot reproduce the issue here)

**Comment by rth** [comment]
The error message  with `nopython=True` can be found at http://pastebin.com/EySG5RXB . Yes, maybe it's somehow specific to the software versions I'm using. Also here is the output `numba.test()` http://pastebin.com/JhpfznC6  There are quite a few failed tests, mostly related to `Untyped global name 'range'`

**Comment by pitrou** [comment]
What happens if you run the test suite from the command line? (e.g. `python runtests.py -m -b`)

**Comment by gmarkall** [comment]
Also try substituting `range` for `xrange` with `nopython=True` - does this compile without error?

**Comment by rth** [comment]
@gmarkall  `xrange` works and runs 170x faster then the pure python version.
@pitrou I'm using a packaged numba install, so I'm not sure where  `runtests.py` file is, however 

      nosetests -s /usr/lib64/python2.7/site-packages/numba/ 
returns similar errors + a few additional ones regarding cuda, which is normal since I don't have it.

**Comment by pitrou** [comment]
This is definitely weird. The same issue was reported as #972. What is the value of `range.__module__`?

**Comment by rth** [comment]
That runs as expected, 

    python -c 'print(range.__module__)' 
    __builtin__

**Comment by pitrou** [comment]
Let's hope one of us can reproduce this issue some day. Otherwise it's gonna be hard to diagnose any further.

**Comment by rth** [comment]
I  tried to install `numba` on a clean EC2 instance, using the same OS, software versions (see above), use flags and installation method but I am unable to reproduce this issue. There must be some subtle differences between this installation and my current system, but I don't see where it is. I never had any other problems related to my python install. It looks like this issue might be quite challenging to reproduce.

**Comment by gmarkall** [comment]
Looks like the problem may be the future package: https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/TQa9cwYZiIs

**Comment by gmarkall** [comment]
Just checked, installing the future package (`conda install future`) does break an existing working setup of Numba for me with a similar error message.

**Comment by rth** [comment]
Yes, that  makes sense. I do have the `future` module installed (although not with conda). Thanks for finding the issue!

**Comment by pitrou** [comment]
That's rather interesting. Does the ``future`` module monkeypatch the built-in ``range``? Or is something else happening?
