### ISSUE TITLE
len(tuple) causes failure to compile

### ISSUE THREAD

**Issue by David-OConnor** [numba/numba#1050]
len() is listed on the supported features page on builtin, but is causing code to fail to compile.

code: 'shape_size = len(shape)'

from inspect_vars:
            # --- LINE 225 --- 
            #   $0.3 = global(len: <built-in function len>)  :: pyobject
            #   $0.5 = call $0.3(shape, )  :: pyobject
            #   del shape
            #   del $0.3
            #   shape_size = $0.5  :: pyobject
            #   del shape_size
            #   del $0.5

Error output when using nopython=True:

TypingError: Failed at nopython (nopython frontend)
Undeclared len((int64 x 1),)
File "..\..\quick\quick\funcs.py", line 225

**Comment by gmarkall** [comment]
Taking the length of a tuple appears not to be supported. However, it looks like you're trying to find the number of dimensions of an array, for which you can use the `ndim` property.
