### ISSUE TITLE
Numba does not allow access to 2d arrays

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1057]
The following code fails in nopython mode, even though all I try to do is to access a 3d vector, stored in a 2d array:
```python
# -*- coding: utf-8 -*-
""" Using arrays as replacement for a struct. """
from numba import jit
import numpy as np

V_WIND = 8.0

V_wind           = 0 # (westwind, downwind direction to the east)
V_wind_gnd       = 1
Result           = 2

def getVec3():      
    vec3 = np.zeros((3, 3))
    vec3[V_wind, 0]        = 1.5 * V_WIND # (westwind, downwind direction to the east at 200m height)
    vec3[V_wind_gnd, 0]    = V_WIND       # (westwind, downwind direction to the east)
    return vec3
 
@jit(nopython=True)
def test(vec3):
    return vec3[Result]

def init():
    vec3 = getVec3()
    print vec3[V_wind]    
    print vec3[V_wind_gnd]
    print test(vec3)

init()
```

Error message:
TypingError: Undeclared getitem(array(float64, 2d, C, nonconst), int32)
In [71]: numba.__version__
Out[71]: '0.17.0'

**Comment by ufechner7** [comment]
The following example shows the same problem, but does NOT try to return a view to Python. It shows better, what I am trying to do.

```python
# -*- coding: utf-8 -*-
""" Using arrays as replacement for a struct. """
from numba import jit
import numpy as np

V_WIND = 8.0

V_wind           = 0 # (westwind, downwind direction to the east)
V_wind_gnd       = 1
Result           = 2

@jit(nopython = True)
def sub(a, b, result):
    """ Calculate the difference of two 3d vectors. """
    result[0] = a[0] - b[0]    
    result[1] = a[1] - b[1]
    result[2] = a[2] - b[2]  

def getVec3():      
    vec3 = np.zeros((3, 3))
    vec3[V_wind, 0]        = 1.5 * V_WIND # (westwind, downwind direction to the east at 200m height)
    vec3[V_wind_gnd, 0]    = V_WIND       # (westwind, downwind direction to the east)    
    return vec3

@jit(nopython=True)
def test(vec3):
    sub(vec3[V_wind], vec3[V_wind_gnd], vec3[Result])

def init():
    vec3 = getVec3()
    print vec3[V_wind]    
    print vec3[V_wind_gnd]
    test(vec3)
    print vec3[Result]

init()
```

Error message:
TypingError: Undeclared getitem(array(float64, 2d, C, nonconst), int32)

**Comment by gmarkall** [comment]
Your second example (I haven't tried the first) works for me with the master branch of Numba - I think this issue has already been addressed by #1047. This will be part of the Numba 0.18 release, which will be out fairly soon.

I'm curious about the use-case in general though - is there a reason for avoiding the use of structured types for the `vec3` structure, and instead using arrays (as noted in the docstring)?

**Comment by ufechner7** [comment]
Yes. Using structured numpy arrays is very slow. See the following code:
```python
# -*- coding: utf-8 -*-
""" Accessing record arrays with numba 0.17 is very slow (factor 7). """
from numba import jit
import numpy as np
import time

class Timer(object):
    def __init__(self, verbose=False):
        self.verbose = verbose

    def __enter__(self):
        self.start = time.time()
        return self

    def __exit__(self, *args):
        self.end = time.time()
        self.secs = self.end - self.start
        self.msecs = self.secs * 1000  # millisecs
        if self.verbose:
            print 'elapsed time: %f ms' % self.msecs

V_WIND = 8.0

def form(number):
    """ print a number with two decimal digits """
    return "{:5.2f}".format(number)

@jit(nopython = True)
def sub(a, b, result):
    """ Calculate the difference of two 3d vectors. """
    result[0] = a[0] - b[0]    
    result[1] = a[1] - b[1]
    result[2] = a[2] - b[2]  

def getVec3():      
    x_dt = np.dtype([('v_wind', np.float64), 
                     ('v_wind_gnd', np.float64),
                     ('result', np.float64)])
    buf = np.zeros((3, 3)) # initialize the record array with zeros                
    vec3 = np.recarray(3, dtype=x_dt, buf=buf)
    vec3.v_wind[0]     = 1.5 * V_WIND # (westwind, downwind direction to the east at 200m height)
    vec3.v_wind_gnd[0] = V_WIND       # (westwind, downwind direction to the east)    
    return vec3

@jit(nopython=True)
def sub_rec(vec3):
    sub(vec3.v_wind, vec3.v_wind_gnd, vec3.result)
    
@jit(nopython=True)
def sub_rec2(a, b, result):
    sub(a, b, result)    

def init():
    vec3 = getVec3()
    print vec3.v_wind
    print vec3.v_wind_gnd    
    sub_rec(vec3)
    sub_rec2(vec3.v_wind, vec3.v_wind_gnd, vec3.result)
    print vec3.result
    return vec3

vec3 = init()

if __name__ == "__main__":
    with Timer() as t0:
        for i in range(10000):
            pass
    print "time for empty loop ", t0.secs
    print
    with Timer() as t1:
        for i in range(10000):
            sub_rec(vec3)
    print "time for numba sub_rec  [µs]:     ", form((t1.secs-t0.secs)  / 10000 * 1e6)
    a = vec3.v_wind
    b = vec3.v_wind_gnd
    result = vec3. result
    with Timer() as t1:
        for i in range(10000):
            sub_rec2(a, b, result)
    print "time for numba sub_rec2 [µs]:     ", form((t1.secs-t0.secs)  / 10000 * 1e6)    
    
"""
Output:

[ 12.   0.   0.]
[ 8.  0.  0.]
[ 4.  0.  0.]
time for empty loop  0.000410079956055

time for numba sub_rec  [µs]:       1.92
time for numba sub_rec2 [µs]:       0.32    
"""
```
Using structured types reduces the speed by a factor of seven (!), compared to passing a list of arguments. But I do not want to pass 30 arguments to my functions.

**Comment by ufechner7** [comment]
I tried to install numba 0.18rc1 from git, but now I get the following exception:

```
  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1-py2.7-linux-x86_64.egg/numba/compiler.py", line 199, in run
    raise patched_exception

AttributeError: Failed at object (object mode backend)
'Module' object has no attribute 'get_global'
```
Any idea?

**Comment by gmarkall** [comment]
I'm not quite sure, because the original exception traceback has got lost (in Python 3 the original exception would be printed as well).

To try the most recent build of Numba master more easily, you can install a build from the Numba conda channel in another environment, e.g.:

```
conda create -n numbamaster python=2.7
source activate numbamaster
conda install -c numba numba
```

Do you still have the same issue with Numba from the Numba conda channel?

**Comment by gmarkall** [comment]
(Also, thanks for providing a demonstration of the speed issue with record arrays).

**Comment by ufechner7** [comment]
Is it possible to get numba 0.18.0.rc1 using conda?

**Comment by gmarkall** [comment]
Yes, you can use:

```
$ conda install -c numba numba=0.18.0rc1
```

to specifically install Numba 0.18.0rc1

**Comment by ufechner7** [comment]
Nice, this worked. I can confirm, that this issue is fixed with 0.18.0rc1. The speed issue with record arrays still remains, but that is a different issue. Perhaps it can be linked? I don't know how to do that.

**Comment by gmarkall** [comment]
Looking at the example demonstrating the speed of record arrays compared to normal arrays: these examples are both dominated by the time taken for the Numba dispatcher to call the jitted functions. The overhead of dispatching with record arrays is slightly higher, since it is more complicated to compare record types.

To put it another way, the amount of computation done in the `sub_rec` and `sub_rec2` functions is too small to measure the performance of the execution of the code inside the functions. For jitted functions with a longer execution time, the difference in execution times between the two functions should shrink, as the overhead of the dispatcher gets amortised. However, if there are examples of where this is not the case, please do open additional issues and we can look into those cases.

**Comment by gmarkall** [comment]
Closing as the original issue appears to be resolved.
