### ISSUE TITLE
Support simple array expressions in nopython mode

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1066]
Hello,

it would be nice if the support of simple vector operations
could be added to numba in nopython mode.

With simple I mean operations, that do not need to allocate
any memory. All linear combinations of vectors of the same
size would fall in this categorie.

Precondition:
result = np.zeros(3)
a, b = 2.2, 3.4 # any scalars of type float64 or of type integer
vec1, vec2: vectors of the same type and length as the vecotr result

Examples:
```python
1) result[:] = vec1 + vec2
2) result[:] = vec1 - vec2
3) result[:] = a * vec
4) result[:] = vec / a
5) result[:] *= a
6) result[:] /= a
7) result[:] = a * vec1 + b * vec2
8) result[:] = a * vec1 + vec2 / b
```
This could improve the readability of my code a lot.

Example for the currently used code:
```python
sub3(vec3[V_wind], v_kite, v_apparent)
mul2( K * scalars[ParamCD] * BRIDLE_DRAG * (1.0 + 0.6 * abs(rel_steering)), vec3[Drag_force])
```

This code is using the linear algebra library as shown here:
https://gist.github.com/ufechner7/98bcd6d9915ff4660a10

I would like to be able to write instead:
```python
v_apparent = vec3[V_wind] - v_kite
vec3[Drag_force] *= K * scalars[ParamCD] * BRIDLE_DRAG * (1.0 + 0.6 * abs(rel_steering))
```

I am using Python + numba for teaching MSc students with limited programming skills.
It is important that they can easily read the implement aerodynamic models.

Uwe Fechner, using numba 0.18

**Comment by pitrou** [comment]
This is now supported, closing.

**Comment by szym** [comment]
Any plans to support vector casting?

     result[:] = numpy.int32(vec)

The documentation says `numpy.int32` is supported but only for scalar arguments.

**Comment by pitrou** [comment]
If you look at the development docs (http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#other-functions), they say:

> The following constructors are supported, both with a numeric input (to construct a scalar) or a sequence (to construct an array): [...]
