### ISSUE TITLE
Support for debug information

### ISSUE THREAD

**Issue by markflorisson** [numba/numba#107]
Support for debugging numba code in gdb (and other debuggers) using the LLVM DWARF debug info.

**Comment by pitrou** [comment]
This is also tracked on the llvmlite side in https://github.com/numba/llvmlite/issues/10

**Comment by stuartarchibald** [comment]
@sklam can we close this since https://github.com/numba/numba/pull/2170 ?

**Comment by sklam** [comment]
Yes
