### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1071]
I had already asked this in the mailing list, but it seems to be lost there.  I had tried to use enums for some algorithms using lots of bit manipulation. For that I have to manage many integer constants, which I had tried to efficiently group with some well readable syntax like that:

```python
class SomeConstantsContainer:
    SOME_NAME = 0x1
    SOME_OTHER_CONSTANT = 0x2
    AND_ANOTHER_CONSTANT = 0x4
```
or that:

```python
@enum.unique
class SomeConstantsContainer(enum.IntEnum):
    SOME_NAME = 0x1
    SOME_OTHER_CONSTANT = 0x2
    AND_ANOTHER_CONSTANT = 0x4
```

Unfortunately both fails in nopython-mode. Both, the container and the value are only recognized as python objects. I suppose I would have to write something like this, to get full compiled speed:

```
SOME_STUPID_CONSTANT = np.int64(0x1)
ANOTHER_STUPID_CONSTANT = np.int64(0x2)
```

For usability and readability I don't like that. I have different constants with different meanings, which I'd like to group visibly together in any form. I'm also a big fan, when the IDE can help me autocompleting the names of the constants, by picking them from the enums. 

Right now, there seems to be now way to efficiently handle the grouping. Only one suggestion on stackoverflow, using closures, came somewhat close: http://stackoverflow.com/questions/28634652/best-way-to-handle-multiple-constants-in-a-container-with-numba So, support for enums would really be awesome!

**Comment by gmarkall** [comment]
I was going to suggest that you could do it with a constant record (which would have some drawbacks, including slower access from Python code), but in doing that I stumbled across issue #1081.

However, I do think that it makes sense for Numba to support enums.

**Comment by ml31415** [comment]
Cool, thanks for having a look into this!

**Comment by Maher4Ever** [comment]
Has there been any progress on this feature? If not, can you point me to some places within the Numba source where type conversion happens so that I can see if I can add support for it?

**Comment by ml31415** [comment]
Since some versions you have nametuple support, which serves quite well as an enum, too:

```python
class SomeConstantsContainer:
    SOME_NAME = 0x1
    SOME_OTHER_CONSTANT = 0x2
    AND_ANOTHER_CONSTANT = 0x4

def class_to_namedtuple(cls):
    newdict = dict((k, getattr(cls, k)) for k in dir(cls) if not k.startswith('_'))
    return namedtuple(cls.__name__, sorted(newdict, key=lambda k: newdict[k]))(**newdict)

class_to_namedtuple(SomeConstantsContainer)
>>> SomeConstantsContainer(SOME_NAME=1, SOME_OTHER_CONSTANT=2, AND_ANOTHER_CONSTANT=4)
```

So it may make sense, to have some thin wrapper around this and call it enum support, but closing this issue would also be fine for me.

**Comment by seibert** [comment]
I think we can support enums more directly, so I'd like to leave this issue open as a reminder.

**Comment by pitrou** [comment]
Indeed, direct support for enums of either kind (plain enums or integer-like enums) would be reasonable.

**Comment by ml31415** [comment]
Would this provide speedups compared to the namedtuple solution? In terms of just prettier code, this would also work:

```python
class EnumMeta(type):
    def __new__(cls, name, bases, cls_dict):
        new_dict = dict((k, cls_dict[k]) for k in cls_dict if not k.startswith('_'))
        return namedtuple(name, sorted(new_dict, key=lambda k: new_dict[k]))(**new_dict)

class EnumeratedStuff:
    __metaclass__ = EnumMeta
    VAL_1 = 0x1
    VAL_2 = 0x2
```

**Comment by Maher4Ever** [comment]
For a project I'm working on we had to support compilation of Python enums. I hacked Numba and added incomplete support that's sufficient for our requirements. The code can be found [here](https://gist.github.com/Maher4Ever/a24bb17312b7152aead2e218891597ea). Simply import the patch module and then you can use enums as follows:

```python
from enum import IntEnum
import add_enum_support

class MyType(IntEnum):
    X = 11
    Y = 22

class OtherType(IntEnum):
    X = 33
    Y = 44

@njit(int32(int32))
def has_enum(x):
    if MyType.X < x < OtherType.X:
        return MyType.Y
    else:
        return OtherType.Y
```

Note: you'll need the `wrapt` package for it to work as the code patches some internal Numba functions.
