### ISSUE TITLE
Trying out 0.18.1: AttributeError: 'Module' object has no attribute 'get_global'

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1072]
I have code like this that used to work before:
```python
import numpy as np
import numba as nb

HAYSTACK = np.array([1,2,3], dtype=float)
@nb.jit(nb.float64(nb.float64), nopython=True)
def findfirst(x):
    for i in range(len(HAYSTACK)):
        if x < HAYSTACK[i]:
            return HAYSTACK[i]
    return HAYSTACK[-1]
```
Now it fails with this error:
```
LoweringError: Failed at nopython (nopython mode backend)
Internal error:
AttributeError: 'Module' object has no attribute 'get_global'
```
Is this a regression or some incompatible change between 0.17 and 0.18? If so, how should this code look like for 0.18?

**Comment by dpo** [comment]
Same problem here with Numba 0.18.1 installed from PyPi.

**Comment by pitrou** [comment]
You should upgrade to the latest llvmlite. Numba 0.18.1 is using some new APIs that are not present in the llvmlite version contemporary to the 0.17 release.

**Comment by dpo** [comment]
`pip install git+https://github.com/numba/llvmlite.git` works. Thanks!

**Comment by pitrou** [comment]
Thanks for the report!

**Comment by ml31415** [comment]
Yes, that works. Thanks for the hint!
