### ISSUE TITLE
Integer overflow when using range provided with unsigned integers

### ISSUE THREAD

**Issue by smartschat** [numba/numba#1089]
I'm feeding range in a jitted function with integers taken from an unsigned int64 numpy array. When the numbers are sufficiently large (exceeding the maximum value of a signed int32 integer), an integer overflow happens.

Here is a minimal working example:

```python
import numpy
import numba

@numba.jit
def iterate_over_range():
    arr = numpy.array([2552764644, 2552764645], dtype='uint64')

    for val in range(arr[0], arr[1]):
        print(val)
```

When running `iterate_over_range()`, it prints -1742202652. I'm using numba 0.18.2 on a 64 bit Linux system.

**Comment by sklam** [comment]
I can confirm the problem.  Looks like bad coercion for uint64.  Works with int64.
