### ISSUE TITLE
Make vectorize threadsafe

### ISSUE THREAD

**Issue by cowlicks** [numba/numba#1096]
Blaze was crashing the LLVM by crashing calling vectorize in multiple threads.

**Comment by pitrou** [comment]
Thanks for the report. Would you have a simple reproducer?

**Comment by stuartarchibald** [comment]
Considerable work went into thread safety in https://github.com/numba/numba/pull/2627. `@vectorize` should now only have thread safe paths to access LLVM. Closing. If this is still an issue please reopen.
