### ISSUE TITLE
Iterating over two arrays with zip is twice as slow as using an index variable

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1111]
I've noticed that using `zip` with numba seems to produce code that is twice as slow as using an index variable:
```
@jit
def f1(x, y):
    s = 0
    for xi, yi in zip(x, y):
        s += xi * yi
    return s

@jit
def f2(x, y):
    s = 0
    for i in range(len(x)):
        s += x[i] * y[i]
    return s

x = np.random.randn(100000)
y = np.random.randn(100000)
%timeit f1(x, y)
# 10000 loops, best of 3: 187 µs per loop
%timeit f2(x, y)
# 10000 loops, best of 3: 95.2 µs per loop
```

The slow down here isn't just due to using the index variable -- without using zip, these functions are essentially the same speed:
```
@jit
def s1(x):
    s = 0
    for xi in x:
        s += xi
    return s

@jit
def s2(x):
    s = 0
    for i in range(len(x)):
        s += x[i]
    return s

%timeit s1(x)
# 10000 loops, best of 3: 92.2 µs per loop
%timeit s2(x)
# 10000 loops, best of 3: 93.9 µs per loop
```

I tested this on master (as well as the latest release) on OS X.

To give a little more context, my interest is in simultaneously iterating over multiple arrays that may have any number of dimensions. So ultimately I would like to write look something like `for xi, yi in zip(x.flat, y.flat)`, and I don't see any way to write that using accelerated Numba other than using `zip` if the dimensionality of `x` and `y` are not known ahead of time..

**Comment by pitrou** [comment]
``zip`` is more complicated as it has to compute two separate iterators, and Numba doesn't know that they have the same lengths (i.e. shapes).

> I would like to write look something like for xi, yi in zip(x.flat, y.flat), and I don't see any way to write that using accelerated Numba other than using zip if the dimensionality of x and y are not known ahead of time..

You can use numpy.ndindex() or numpy.ndenumerate().

**Comment by shoyer** [comment]
> zip is more complicated as it has to compute two separate iterators, and Numba doesn't know that they have the same lengths (i.e. shapes).

This is a fair point, though I wonder if I might be possible to shortcut for this common case.

> You can use numpy.ndindex() or numpy.ndenumerate().

Indeed, thanks!

Here are two more functions:
```
@jit(nopython=True)
def f3(x, y):
    s = 0
    for i in np.ndindex(*x.shape):
        s += x[i] * y[i]
    return s


@jit(nopython=True)
def f4(x, y):
    s = 0
    for i, xi in np.ndenumerate(x):
        s += xi * y[i]
    return s
```

On master, trying to run either of these currently raises `LowingError`. On 0.18.2, `f4` works, with about 33% overhead (`124 µs per loop`), but `f3` raises `NotImplementedError`:
```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-24-3c1508b4c534> in <module>()
----> 1 f3(x, x)

/Users/shoyer/miniconda/envs/flat-top/lib/python2.7/site-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    160         assert not kws
    161         sig = tuple([self.typeof_pyval(a) for a in args])
--> 162         return self.compile(sig)
    163
    164     def inspect_llvm(self, signature=None):

/Users/shoyer/miniconda/envs/flat-top/lib/python2.7/site-packages/numba/dispatcher.pyc in compile(self, sig)
    303                                           self.py_func,
    304                                           args=args, return_type=return_type,
--> 305                                           flags=flags, locals=self.locals)
    306
    307             # Check typing error if object mode is used

/Users/shoyer/miniconda/envs/flat-top/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    561     pipeline = Pipeline(typingctx, targetctx, library,
    562                         args, return_type, flags, locals)
--> 563     return pipeline.compile_extra(func)
    564
    565

/Users/shoyer/miniconda/envs/flat-top/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(self, func)
    297                 return self.stage_compile_interp_mode()
    298             else:
--> 299                 raise e
    300
    301         return self.compile_bytecode(bc, func_attr=self.func_attr)

NotImplementedError: offset=21 opcode=0x8c opname=CALL_FUNCTION_VAR
```

**Comment by pitrou** [comment]
I've opened a separate issue (#1118) for the ndenumerate() regression.

**Comment by pitrou** [comment]
The problems you had with ``f3`` and `f4` should both be fixed on master now.

**Comment by shoyer** [comment]
Indeed, they work now. Thanks! f4 is still about 30% slower than direct indexing, and f3 is even slower.

**Comment by pitrou** [comment]
Interestingly, it seems LLVM 3.7 has become much better at optimizing this. Now `f1`, `f2` and `f3` have the same speed (here on Linux). `f4` is still quite a bit slower.

**Comment by pitrou** [comment]
Still, if you encounter other cases where `zip` is too slow, don't hesitate to post them.

**Comment by shoyer** [comment]
That's great! Zip really helps for writing pythonic code.

**Comment by shoyer** [comment]
Actually -- maybe it's worth adding these examples to the benchmark suite?

**Comment by pitrou** [comment]
Yes. There's actually a comment about that here:
https://github.com/numba/numba-benchmark/blob/master/benchmarks/bench_iterating.py
Do you want to submit a PR?

**Comment by pitrou** [comment]
Note PR #1787 implements np.nditer(), which provides optimized multi-array iteration assuming you don't care about iteration order.

**Comment by pitrou** [comment]
Benchmarks added in https://github.com/numba/numba-benchmark/pull/5

**Comment by shoyer** [comment]
Thanks Antoine!
