### ISSUE TITLE
Support for np.zeros in nopython mode

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1112]
I'm just starting playing around with the support for allocating arrays in no-python mode (using master). It's very nice work!

The first thing I did was write my one equivalent of `np.zeros` to allocate and zero-out an array. It would be nice if numba came with this built in.

**Comment by seibert** [comment]
Agreed.  I think we can add the rest of the usual numpy array allocators now that the main PR has merged.

**Comment by pitrou** [comment]
This has been merged in.
