### ISSUE TITLE
np.empty fails with TypingError when dtype is provided using a keyword argument

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1113]
This function doesn't work (I'm running master here):
```
@jit(nopython=True)
def empty():
    return np.empty(10, dtype=np.float64)
```

It took me a little while to figure out that I could simply remove `dtype=` to make this expression work. Given that this is a common way to provide these arguments, it would be nice to support this.

**Comment by pitrou** [comment]
Yes, we currently don't support keyword arguments when calling into builtin or library functions. That's something we should figure out; I briefly took a look some time ago and it's bit more complicated than I assumed...

**Comment by shoyer** [comment]
A simple alternative ( for now) would be a more informative error message. TypingError is pretty unhelpful.

**Comment by pitrou** [comment]
This should now work, at least for the common cases.
