### ISSUE TITLE
NRT refct return leak

### ISSUE THREAD

**Issue by sklam** [numba/numba#1123]
(Tracking problem worked-around at https://github.com/numba/numba/pull/1122)

NPM function types.Dispatcher is returning new reference but the rest of the compiler is relying on variable binding for knowing when to incref.  This causes a extra incref on the returned value of a NPM call inside another NPM function.

**Comment by sklam** [comment]
#1192  implements another workaround to fix this problem for compile_internal() calls

**Comment by seibert** [comment]
Can we close this issue?

**Comment by sklam** [comment]
There are no leak problem anymore
