### ISSUE TITLE
Ufunc calls in the complex domain not properly lowered.

### ISSUE THREAD

**Issue by jriehl** [numba/numba#1125]
The LLVM code generator in `numba.targets.npyfuncs._dispatch_func_by_name_type()` appears to be improperly lowering function calls that return complex values.  Numba seems to be casting complex types and arguments to tuples (in part via `context.get_argument_type()`), which is not a supported means of specifying complex types in llvmlite.

Example:
```python
>>> import numpy as np; from numba import *
>>> @njit
... def mypow(x, y): return np.power(x, y)
... 
>>> X = np.ones(10, dtype=np.complex128)
>>> mypow(X, X)
Traceback (most recent call last):
[...]
  File "/home/jriehl/git/jriehl-numba/numba/targets/npyfuncs.py", line 98, in _dispatch_func_by_name_type
    builder.call(fn, call_args)
  File "/home/jriehl/.virtualenvs/numba3/lib/python3.4/site-packages/llvmlite/ir/builder.py", line 455, in call
    cconv=cconv, tail=tail)
  File "/home/jriehl/.virtualenvs/numba3/lib/python3.4/site-packages/llvmlite/ir/instructions.py", line 68, in __init__
    if arg.type != exptype:
AttributeError: 'tuple' object has no attribute 'type'
[...]
numba.lowering.LoweringError: Failed at nopython (nopython mode backend)
Internal error:
AttributeError: 'tuple' object has no attribute 'type'
File "<stdin>", line 2
```

Verified using the current master branch of llvmlite.

**Comment by pitrou** [comment]
There are no complex types in LLVM (nor llvmlite). Operations on complex numbers must be manually decomposed into operations on the real and imaginary parts.

**Comment by sklam** [comment]
npyfuncs.py needs to be updated to use the datamodel changes properly.  I am taking this one.
