### ISSUE TITLE
Documentation isn't building properly under Python 3

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1126]
Various highlighting and indentation is broken in the docs, and it seems to occur when building them under Python 3. This seems to have affected documentation since version 0.15.1. For example 

http://numba.pydata.org/numba-doc/0.15.1/CUDADevice.html

vs

http://numba.pydata.org/numba-doc/0.14/CUDADevice.html

(everything is pushed to the left in 0.15.1).

**Comment by pitrou** [comment]
It seems ok here:
http://numba.pydata.org/numba-doc/dev/cuda/device-management.html

I think it's simply different versions of the Sphinx theme.
