### ISSUE TITLE
UFunc error handling may differ `0 != -0`

### ISSUE THREAD

**Issue by sklam** [numba/numba#1131]
See https://github.com/numba/numba/pull/1130/files#diff-228207ff3c5703f16e69104cecc65257R1323

**Comment by pitrou** [comment]
Is this still an error? If so, can you post the symptoms more precisely?

**Comment by sklam** [comment]
Our ufunc may produce zero with the "wrong" sign when error occurs (e.g. divide-by-zero).  Remove the highlighted if-block in https://github.com/numba/numba/pull/1130/files#diff-228207ff3c5703f16e69104cecc65257R1323 in ``_is_acceptable_error`` to see the actual error.
