### ISSUE TITLE
Improve keyword argument support in nopython mode

### ISSUE THREAD

**Issue by seibert** [numba/numba#1154]
Two implementations of keyword argument support in nopython mode were proposed: PR #1115 and PR #1120.  PR #1120 was merged as a simpler solution, but has some limitations that #1115 addresses at the cost of much greater complexity.  We should see if there is a way to merge the benefits of the two approaches at some point.

**Comment by pitrou** [comment]
There are basically two technical issues embedded here:

1. we need a way to represent call site signatures when an argument is missing in the middle. Consider `numpy.eye(N, M=None, k=0, dtype=<class 'float'>)`: we want to be able to represent the signature of calling `numpy.eye(N, dtype=numpy.int16)`.

2. we need a way to declare implementations that are flexible enough to accept a variable number of arguments. Considering `numpy.eye` again, the current way of declaring implementations would have us write 8 separate implementations (one for each possible set of explicit arguments).

The first issue has several possible solutions. We could add keyword argument support to the whole pipeline (probably quite involved). We could add the argument names to the signature as in Siu's PR. We could define a new type "Omitted" for those omitted arguments (the implementation then has to somehow replace them). The latter may perhaps be merged with the current default argument support in the dispatcher.

The second issue could be solved by allowing to "overlay" library functions with jitted functions; however, this wouldn't work for many Numpy functions, where inferring the return type is too sophisticated to be handled by our current type inference phase.

**Comment by pitrou** [comment]
Other gotchas:

* Support for non-trivial default values. For example, take a typical `numpy.eye` implementation:

```
def eye(N, M=None, k=0):
    if M is None:
        M = N
    ...
```

We are not able to infer that after the `if` clause, M will always be non-None. Moreover, Optional is implemented as a special case in select parts of the code, it's not supported everywhere.

**Comment by ovillellas** [comment]
Uhm... There may be a candidate "optimization" pass that could be quite
useful in here. The idea being that it should possible to rewrite that is
based on conditionals based on types with the info from type inference. In
your example, as None is type-inferred to NoneType, the check for "is None"
can be removed while type-inferring.

If this is not done yet, it is a feature we should really be considering.

A question: in keyword support shouldn't we only generate code for the full
signature (including kwargs) and have the code dealing with boxing handle
missing values? I should look more deeply in those implementations :).

**Comment by pitrou** [comment]
Le 20/05/2015 16:20, Óscar Villellas Guillén a écrit :
> Uhm... There may be a candidate "optimization" pass that could be quite
> useful in here. The idea being that it should possible to rewrite that is
> based on conditionals based on types with the info from type inference. In
> your example, as None is type-inferred to NoneType, the check for "is None"
> can be removed while type-inferring.

Yes... Adding some partial evaluation to the type inference pass
complicates things quite a bit, though.

> A question: in keyword support shouldn't we only generate code for the full
> signature (including kwargs) and have the code dealing with boxing handle
> missing values? I should look more deeply in those implementations :).

That's we're doing right now (on the Dispatcher side).

**Comment by nunocalaim** [comment]
Hey guys,

Thanks for your work! Did this result in any improvement for Numba?

I am looking for a way to do exactly these types of things but I don't know if Numba supports this
def eye(N, M=None, k=0):
if M is None:
M = N

If not, are there plans?

**Comment by stuartarchibald** [comment]
Numba now has a branch pruning pass that checks things like `if X <condition> None` and prunes branches appropriately so this sort of thing works fine (0.47.0 is latest version):
```python
from numba import njit
import numpy as np

@njit
def eye(N, M=None, k=0):
    if M is None:
        M = N
    return np.ones(M) + k

eye(3)

eye(3, M=None)

eye(3, M=4)

eye(3, M=2, k=6)
```
I'm going to close this issue now with view that key word argument support has been around for a long while and if there are problems/limitations with the current implementation new tickets should be opened. Thanks for the input all.
