### ISSUE TITLE
Yielding a ndindex raises an error in nopython mode

### ISSUE THREAD

**Issue by nbedou** [numba/numba#1170]
```python
import numba
import numpy as np

@numba.jit(nopython=True)
def f():
    for ind in np.ndindex(5):
        yield ind[0]

for i in f():
    print(i)
```

This code raises the following error: `KeyError: "Failed at nopython (nopython mode backend)\n<class 'numba.types.NumpyNdIndexType'>"`.

It works in nopython=False mode.

Numba 0.18.2
Python 3.4.3, Windows 7 64 bits

**Comment by pitrou** [comment]
It compiles here but the generator never finishes.
