### ISSUE TITLE
generalized ufuncs with a constant output dimension

### ISSUE THREAD

**Issue by mcg1969** [numba/numba#1176]
I'd like to implement a generalized ufunc with this signature:

    '(n),(n),(n),(n),(n),(n)->(n,6)'

It's a coincidence that there are six inputs and six columns in the output; I just happen to have exactly six quantities to compute for each set of inputs. But this signature yields

    ValueError: bad token in signature "6"

So I tried pretending that I didn't know what the number of columns was:

    '(n),(n),(n),(n),(n),(n)->(n,m)'

This of course gives me

    NameError: undefined output symbols: m

Is it possible to extend Numba to support a case like this? I'm sorry I can't share the specific application, but here's a simple example: a function that simultaneously computes the minimum, maximum, and average of a set of values would have this signature:

    '(n)->(3)'

**Comment by pitrou** [comment]
I don't think this is supported by Numpy: http://docs.scipy.org/doc/numpy/reference/c-api.generalized-ufuncs.html#details-of-signature

**Comment by mcg1969** [comment]
Ah, fair enough. I've developed a workaround for now that accomplishes this precise goal. It's too bad though! I'll double check that NumPy doesn't accidentally support this ;-) and then close this.
