### ISSUE TITLE
numba 0.19 beta not work with cx_freeze

### ISSUE THREAD

**Issue by carmelov** [numba/numba#1177]
the only working version must be <= version 0.15.0

In anaconda, windows, I must use the old version with:
conda install numba=0.15.1

can you solve this problem?
Regards,
ing. Carmelo Viavattene

**Comment by stuartarchibald** [comment]
It would appear this was fixed in https://github.com/numba/llvmlite/pull/96, could you please confirm if this is still a problem? Thanks.

**Comment by stuartarchibald** [comment]
Closing assumed fixed, if this is not the case please reopen with new information, thanks.
