### ISSUE TITLE
numba 0.19: running this simple "calculate edge vectors" script twice creates a "type error"?

### ISSUE THREAD

**Issue by bmer** [numba/numba#1179]
Let us say one opens up a newly created IPython interpreter. Or a normal Python interpreter.

[Then, run this script twice.](https://gist.github.com/bmer/98ce624514e424558b39)

By twice, I mean, run it once. Then run it once again, in the same interpreter, without opening up a new one. I use Spyder, so I just hit the green run button twice.

The first run should be successful, but the second run results in the following error:

```javascript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "A:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)
  File "A:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "A:/cncell/experiment_storage/scratch.py", line 44, in <module>
    numba_calculate_edge_vectors(num_vertices, node_coords, result)
  File "a:\anaconda\lib\site-packages\numba-0.18.2+519.g8a37f7f-py2.7-win-amd64.egg\numba\dispatcher.py", line 203, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) int64, array(float64, 2d, C), array(float64, 2d, C)
```

I do not understand enough of the error to say anything more, but I would be happy to provide any information you think might be useful.

**Comment by pitrou** [comment]
This is because Spyder tries to reload all modules when running a script in an existing console. To fix this, go to the Spyder preferences, then "Console", then "Advanced Settings", there click the "Set UMR excluded modules" button, and add "numba" inside the text box that pops up. You will have to restart the kernel to see the setting take effect.

**Comment by bmer** [comment]
You are right! That fixes the issue.
