### ISSUE TITLE
Implement .ravel()

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1183]
Now that numba supports creating arrays in nopython mode, an extremely useful method to add would be `ravel`.

This would nicely solve two issues:
1. The ability to iterate in the fastest possible order (#841): use `array.ravel(order='K')`
2. Quickly iterating over multiple flattened arrays simultaneously (#1111): ravel each array separately, and then use scalar indexing.

**Comment by pitrou** [comment]
While it is possible to add support for ravel(), it won't be possible with the current infrastructure to support the `order` argument. The reason is that the return type (specifically, the layout) differs depending on that argument, but the type inference phase doesn't know about argument values.

**Comment by pitrou** [comment]
Also note that ravel() may create a copy of the array data if the desired order is not compatible (even with `order='K'`), which is undesired if the goal is improved performance.

**Comment by shoyer** [comment]
Hmm. I guess `ravel` is not the ideal fix for my use case, then :).

**Comment by pitrou** [comment]
`np.ravel()` is now supported.

**Comment by jzwinck** [comment]
@shoyer I know this is an old issue, but for what it's worth you should consider `array.reshape(-1)` instead of ravel().  It works, and according to the NumPy docs for `ravel()`:

> When a view is desired in as many cases as possible, arr.reshape(-1) may be preferable.
