### ISSUE TITLE
Memory leak when returning array from inner function?

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1189]
If you try the following (here under 64-bit Linux):

```
>>> import numpy as np
>>> from numba import jit
>>> def f(x): return np.ones(x)
>>> ff = jit(nopython=True)(f)
>>> %timeit f(1000000)
1000 loops, best of 3: 875 µs per loop
>>> %timeit ff(1000000)
The slowest run took 44.83 times longer than the fastest. This could mean that an intermediate result is being cached 
100 loops, best of 3: 3.09 ms per loop
```

you may find that the ``%timeit ff(...)`` line leaks a lot of memory (up to several gigabytes), while the ``%timeit f(...)`` line doesn't. Furthermore, if you replace `np.ones` with `np.zeros`, the issue disappears.
This leads me to postulate that there is a leak when an array is returned from an inner function (which is how np.ones() is implemented).

**Comment by sklam** [comment]
Also leak with no return
```
def f(x):
    np.ones(x)
```

**Comment by sklam** [comment]
Ok, this is not happening to ``np.zeros``.
