### ISSUE TITLE
Bring back prange

### ISSUE THREAD

**Issue by seibert** [numba/numba#1193]
Old Numba use to have a prange iterator that ran the body of the loop in parallel (similar to how OpenMP works).  Cython also has similar functionality:

http://docs.cython.org/src/userguide/parallelism.html#cython.parallel.prange

Now that Numba can release the GIL again, reimplementing this feature is possible.

**Comment by nippoo** [comment]
As of a couple days ago, clang 3.5 now fully supports OpenMP, which might be helpful...

**Comment by pitrou** [comment]
Perhaps this is a NumbaPro-specific feature?

**Comment by seibert** [comment]
Once we set ourselves up for generic "block-lifting" type optimizations (generalizing the current loop lifting idea in object mode), I think we could do something like prange again.

**Comment by rossant** [comment]
Would this new `prange` function use OpenMP? Are there deep technical reasons why OpenMP could not be used in Numba?

**Comment by seibert** [comment]
I'm not sure how we would leverage OpenMP for this.  (I guess we could leverage the thread pool management?)  Numba operates at a level below clang, emitting LLVM IR directly and compiling it with the MCJIT engine.

**Comment by rossant** [comment]
> I guess we could leverage the thread pool management

yeah that's what I had in mind

**Comment by seibert** [comment]
If we use the OpenMP runtime for handling the thread-pool, would that also allow Numba to interact better with other libraries that also use OpenMP?  (For example, so both Numba and other libraries aren't both spawning threads unnecessarily.)  I'm not very clear on how OpenMP is implemented at a low level.

The only constraint for us depending on OpenMP is cross-platform and backward compatible support.  Although we require a C++11 compiler to build llvmlite, Numba itself can be built and deployed with on platforms with much older compilers (or no compiler, if installing from prebuilt packages).

**Comment by stefanv** [comment]
Is this issue still relevant?

**Comment by stuartarchibald** [comment]
@stefanv I think not, well spotted. Closing!
