### ISSUE TITLE
Python crashes when running a script if a particular function is `jit`-ted

### ISSUE THREAD

**Issue by bmer** [numba/numba#1195]
Here is the script for reproducing the issue: https://gist.github.com/bmer/09c7a129e3fe80a97158

It is specific to causing the issue, and I have added some simple commenting.

It should run as is, printing out the correct results.

If line 103 (a `jit` type specification) is uncommented (it is currently commented, and has no effect), then the script will crash (on Windows: "python.exe has stopped working"). 

I do not know enough about `numba` to say more, but I would be happy to provide additional information.

**Comment by sklam** [comment]
Crash confirmed on OSX with python2.7 numpy1.9

**Comment by bmer** [comment]
Thank you!
