### ISSUE TITLE
Numba 0.20.x series meta issue

### ISSUE THREAD

**Issue by seibert** [numba/numba#1201]
The Numba 0.20.x series of releases will be for refactoring some of the internals of Numba in support of future planned features.  This issue will be updated periodically to link to the different individual issues that will be addressed by the refactoring.

Features we want to tackle *after* 0.20:
- More complete handling of keyword arguments
- Better debugging and performance diagnostics experience
- JIT classes
- Having a documented API for 3rd parties to add targets, lowerings, and rewrite passes.
- More advanced Numpy features (indexing, etc)
- Recursion
- Passing Numba functions as arguments
- Ahead-of-time compilation mode (like Cython)
- More significant optimizations in object mode (inlining? attribute caching? block lifting?)

Refactoring steps to get there:
### Numba 0.20.0
- Upgrade to LLVM 3.6
- Switch to NVVM library from CUDA 7 (brings IR support up to LLVM 3.4)
- Drop anything from Numba that is duplicated in llvmlite

### Numba 0.20.1
- Debug symbols in JIT
- Investigate autovectorization performance improvements with better IR generation
- Add bytecode->micro-bytecode translation step?

### Numba 0.20.2
- ???

**Comment by pitrou** [comment]
Presumably this issue should be fixed as obsolete? Or repurposed?

**Comment by seibert** [comment]
I think this issue is obsolete.
