### ISSUE TITLE
Please make _nrt an officially supported option 

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1204]
Using the option _nrt=False reduces the execution time of my code to about 60%.
Therefore it would be nice if this could be an officially supported and documented parameter.

Without it there is a large, unnecessary regression for people who upgrade from 0.18.2 to 0.19.1.

In addition, this option can cause segfaults (in rare cases), and I am not motivated to report them if this is not an officially supported option.

**Comment by pitrou** [comment]
IMO we'd rather fix the speed and stability issues than provide an official way to turn off features.
By the way, we should already have fixed at least some of the speed issues in the current master branch.

**Comment by Juanlu001** [comment]
Just for reference, the introduction of the numba runtime does seem to affect a couple of benchmarks:

http://numba.pydata.org/numba-benchmark/

**Comment by ufechner7** [comment]
I just checked the performance of numba 0.20. Execution time for my code:
28 us instead of 16 us with numba 0.18.2.
Yes, it would be nice if the speed issues could be fixed, but to make _nrt an officially supported option would help now and would be easy.

**Comment by pitrou** [comment]
Could you try to isolate the remaining speed issues and post a simple reproducer?

**Comment by ufechner7** [comment]
I posted some benchmarks at http://pastebin.com/j1SJaPZG .
Result:
"""
time for empty loop  0.000367879867554 numba 0.20

time for add2 with numba [µs]:   0.40 -> 1.6 times the time of numba 0.18.2
time add with numpy [µs]:        0.40
speedup of add2 with numba:      1.01

time for numba norm  [µs]:       0.28
time for linalg norm [µs]:       4.51
speedup of norm with numba:     16.24

time for numba dot [µs]:         0.39 -> 1.56 times the time of numba 0.18.2
time for numpy dot [µs]:         0.56
speedup of dot with numba:       1.43

time for numba cross  [µs]:      0.75
time for numba cross3 [µs]:      0.50 -> 1.67 times the time of numba 0.18.2
time for numpy cross  [µs]:     14.67
speedup of cross with numba:    29.21

time for azimuth_east [µs]:      0.30
time for calc_alpha [µs]:        0.41
time for numba normalize  [µs]:  2.17
time for numba normalize2 [µs]:  0.43 -> 1.48 times the time of numba 0.18.2
time for numpy normalize  [µs]:  6.88
"""

**Comment by pitrou** [comment]
Thanks! I'll take a look at it soon.

As a rule of thumb, though, try to JIT-compile longer running functions. Very short-running functions will never see a large benefit, due to the cost of calling the function itself and converting its arguments to a native form: http://numba.pydata.org/numba-doc/dev/user/faq.html#can-numba-speed-up-short-running-functions

**Comment by ufechner7** [comment]
You wanted to see a minimal example. The long example is here:
https://bitbucket.org/ufechner/freekitesim/src/b7257db70be5d6dce3f5f0693ebdb350fd6b9d30/KPS4P_v2.py?at=master

I had to write these minimal functions to get fast vector algebra with 3D vectors with numba 0.18.2, because it did not support any vector algebra.

This is the second re-write I did, because you are refactoring numba. The first version only worked with numba 0.11.2. Now I have a version, that works well with 0.18.2, but it took me two weeks just to rewrite it. I cannot do that for every new version of numba. I know, that numba did not reach version 1.0 yet, but to keep the features and the performance of older versions should be your goal already, inparticular if it is easy to achive as with this @jit option.

**Comment by pitrou** [comment]
Yes, the overhaul that took place somewhere in the 0.1x series produced a number of regressions that took some time to address. Sorry about that.
The good news, though, is that Numba now supports array expressions and allocations again, so you can write `x + y` where `x` and `y` are vectors.

You could also try to progressively add `nopython=True` to all the jit functions of the long example. My suspicion is that it wouldn't take much to get them working and ensure they run in the fastest mode Numba can provide.

**Comment by ufechner7** [comment]
All functions in the long example run with nopython=True. They call the short functions like dot and add. This should be inlined automatically. Only the method residual() cannot be compiled with numba. It creates array views, that are not supported by numba yet.

**Comment by stuartarchibald** [comment]
It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
