### ISSUE TITLE
Defintion order

### ISSUE THREAD

**Issue by hgrecco** [numba/numba#1205]
Is there any better solution for the following issue:

This does not work:
```python
import numba as nb

@nb.njit(nb.double(nb.double, nb.double))
def f1(x, y):
    return f2(x + y)

@nb.njit(nb.double(nb.double))
def f2(x):
    return x * x

f1(1., 2.)
```
Returns
```
numba.typeinfer.TypingError: Failed at nopython (nopython frontend)
Untyped global name 'f2'
```

Inverting the declaration order of f1 and f2 works.
```python
import numba as nb

@nb.njit(nb.double(nb.double))
def f2(x):
    return x * x

@nb.njit(nb.double(nb.double, nb.double))
def f1(x, y):
    return f2(x + y)


f1(1., 2.)
```

I understand why this is happening but I would the expect the order definition does not matter.

**Comment by hgrecco** [comment]
I guess this will be solved when registration and compilation are separated. (solving the recursion issue at the same time). Right?

**Comment by seibert** [comment]
Correct, although another way to solve your particular issue here is to rely on autojit:
```
import numba as nb

@nb.jit
def f1(x, y):
    return f2(x + y)

@nb.jit
def f2(x):
    return x * x

f1(1., 2.)
```
This has the effect of deferring compilation of `f1` until the first call (which is after `f2` has been defined), and the autojit mechanism will trigger the compilation of `f2` prior to `f1`.

**Comment by hgrecco** [comment]
I hit this when trying to use numpy.argsort from numba njitted function. When trying to implement my own version of argsort I hit this and then the recursion. Are you aware of any jittable implementation of argsort out there?

**Comment by seibert** [comment]
I haven't seen one, though with Numba 0.19, you can now allocate the temporary storage required to implement a non-recursive quicksort.

We definitely want to prioritize implementing the Numpy sort functions in the Numba compiler now that we can do memory allocation.

**Comment by hgrecco** [comment]
Thanks for your comments. I have created a very simple version of the method. It is slower than numpy's version but fits my needs. However, if you have any suggestions I will be happy to implement them.

https://gist.github.com/hgrecco/818705ad1eef70f5f6ab

I am closing the issue because the recursion is reported in #507 and others
