### ISSUE TITLE
guvectorize silently swallows exceptions

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1206]
```python
@guvectorize(["void(float64[:], float64[:])"], "()->()", nopython=True)
def test(source, result):
    raise ValueError('help')
    result[()] = -99  # this line is never reached
```
```
>>> test(1234)
4.8749457275155797e-320
```

**Comment by willfurnass** [comment]
The same is true for `@vectorize`  (using numba 0.20.0):

```python
@vectorize
def x_sec_area(diam):
    if diam <= 0.0:
        raise ValueError('Diameter must be strictly positive')
    return np.pi * (diam / 2.0)**2

x_sec_area(-4)
Out: 0.0
```

**Comment by pitrou** [comment]
When processing an array, there could be two possibilities here:
- raise the exception for good
- print out the exception and continue with the next values

**Comment by willfurnass** [comment]
The first of those options is more appealing to me and matches the behaviour you get when using  `np.vectorize`.

**Comment by shoyer** [comment]
Agreed. If a developer wants an exception to simply print output to the screen, they would issue a warning instead.

**Comment by teoliphant** [comment]
The challenge here is that ufuncs are run outside of the Python run-time (that's what makes them fast), unless the array has Python objects (which is the only thing np.vectorize produces).   As a result, you *can't* raise a Python exception.    What you *can* do is set hardware flags.   Then, the ufunc machinery will check those flags at various points and then do various things based on the np.errstate context.

**Comment by shoyer** [comment]
I'm actually entirely OK with the alternative of not allowing exceptions in vectorized functions at all. But if that's the case, Numba should raise an exception when compiling such a function rather than silently producing incorrect results.

**Comment by teoliphant** [comment]
Ah, yes, we should raise an error if we aren't doing something intelligent!

**Comment by pitrou** [comment]
Note this change will have the interesting effect of raising a ZeroDivisionError when dividing by zero inside a ufunc (right now the exception is probably "raised" indeed, but ignored).

**Comment by pitrou** [comment]
Also there's a small performance hit when a function can actually raise an exception, due to the cost of error checking (this is optimized away when the function can't raise anything).
