### ISSUE TITLE
Function definition inside conditional

### ISSUE THREAD

**Issue by hgrecco** [numba/numba#1227]
I have to choose between a set a functions depending on an index. Something like:

``` python
@nb.njit()
def f(n):
    if n == 1:
        myfun = fun1
    elif n== 2:
        myfun = fun2
    else:
        myfun = fun3

    # do something with myfun
```

fun 1, 2, and 3 are all njitted functions with the same explicity signature. It fails as if is not realizing that they all have the same signature. Any hints how to do something like this?

**Comment by seibert** [comment]
The only workaround I can come up with is to hide the branch in another function:
```
@nb.njit
def funX(n, a, b, c):  # replace a, b, c with whatever the signature is of fun1, fun2, fun3
    if n == 1:
        return fun1(a, b, c)
    elif n == 2:
        return fun2(a, b, c)
    else:
        return fun3(a, b, c)
```
And then use `funX` wherever you would use `fun1`/`fun2`/`fun3`.  It means you still have to carry around the `n` variable to pass into each call to `funX`, which is a little inelegant.

**Comment by seibert** [comment]
As a followup, LLVM inlining is likely to make this execute reasonably fast, though perhaps with a little bloat in the generated machine code.

**Comment by stuartarchibald** [comment]
As of 0.47.0 this is how the above can be done:
```python
from numba import njit, literally
from numba.extending import overload

@njit
def fun1(x):
    return x + 1

@njit
def fun2(x):
    return x + 2

@njit
def fun3(x):
    return x + 3

def f(x):
    pass

@overload(f)
def ol_f(n):
    predicate1 = n.literal_value == 1
    predicate2 = n.literal_value == 2
    def impl(n):
        if predicate1 is True:
            myfun = fun1
        elif predicate2 is True:
            myfun = fun2
        else:
            myfun = fun3

        return myfun(literally(n))
    return impl

@njit
def use_f(z):
    f(literally(z))

use_f(2)
```

**Comment by stuartarchibald** [comment]
@pearu is working on functions as first class types which I think might help here https://github.com/numba/numba/pull/4967

**Comment by pearu** [comment]
Yes, PR #4967 resolves the original problem as stated in the description. If fun1, fun2, fun3 would be `cfunc` decorated functions then the example would already work with the current PR state.

**Comment by stuartarchibald** [comment]
Closing, #4967 implements.
