### ISSUE TITLE
Accessing a multidimensional list of numpy arrays in nopython mode

### ISSUE THREAD

**Issue by arranger1044** [numba/numba#1239]
While trying to compute a co-occurrency table for N discrete variables in a data matrix I thought of storing the results in a 2d python list whose elements are 2d numpy arrays:

    _joint_freqs = [[numpy.zeros((_n_feature_vals, _n_feature_vals)) for j in range(_n_features)] for i in range(_n_features)]

However, when in nopython mode I cannot access them. For instance, a function like this:

```
@numba.njit
def gen_naive_joint_freqs(joint_freqs,
                          data,
                          n_instances):
    n_features = data.shape[1]

    for d in range(n_instances):
        for i in range(n_features):
            d_i = data[d, i]
            for j in range(i+1, n_features):
                d_j = data[d, j]
                joint_freqs[i][j][d_i, d_j]
                # saving for symmetry
                # joint_freqs[j][i][d_j, d_i] = joint_freqs[i][j][d_i, d_j]
    return joint_freqs
```

gives this type error:

    TypingError: Failed at nopython (nopython frontend)
    Undeclared getitem(pyobject, int64)

Is there a workaround for this? Not using nopython is not an option since it gives pretty poor performances.

**Comment by seibert** [comment]
Can you turn this into a 4D numpy array?  That would allow numpy mode to be used.

**Comment by arranger1044** [comment]
Thanks for your reply.
I forgot to mention that I used that solution for each inner 2d array can have different sizes from the others (this is not visible from the example where all of them have the same `_n_feature_vals`).

However, if you mean that I shall use a numpy array of objects instead of a list, it does not work either. Here is how I declare it, for example:

    _n_joint_freqs = numpy.empty((_n_features, _n_features), dtype=object)
    for i in range(_n_features):
        for j in range(_n_features):
            _n_joint_freqs[i,j] = numpy.zeros((_n_feature_vals, _n_feature_vals))

Using the same function or a slightly modified to use a single bracket access (`[i, j, d_i, d_j]`) always returns the same error:

    TypingError: Failed at nopython (nopython frontend)
    Undeclared getitem(pyobject, int64)

am I missing something?

**Comment by seibert** [comment]
The problem is that nopython mode does not support working with python objects inside data structures.  If you make a numpy array of numpy arrays, then the nested Numpy arrays are represented as Python objects, leading to the error you see in lowering.

Numpy does not have any really good way to represent ragged data structures like you describe, which limits our ability to generate compiled code for those cases.  (We are hopeful that [DyND](https://github.com/libdynd/libdynd) will help here, although Numba does not yet support DyND containers.)

In this situation, the best you can do is try to isolate an inner loop that operates on the 2D arrays and compile that with Numba.

**Comment by arranger1044** [comment]
I got that, I guess my best option here is to trade off memory and allocate inner arrays to be as large as the maximum size required.

Thanks for your insights, the issue can be marked as resolved.

**Comment by pitrou** [comment]
You can, however, use a tuple instead of a list if that can solve your use case.

**Comment by Stretch97** [comment]
Thanks for pointing out that a tuple of numpy arrays works.  That solved my problem.  

I suppose the mutability of lists causes issues for numba...

**Comment by seibert** [comment]
We have a solution for mutable lists of scalars that will come out in Numba 0.22 next week.  (This is an experimental feature that, in my view, is the first step to understanding whether we could reasonably support passing dictionaries into nopython mode.  Signs seem to point to "yes.")

The next release will not have support for lists of arrays, so the tuple workaround will continue to be required.
