### ISSUE TITLE
Simple piece of math code produces massive numbers as result when nopython=True

### ISSUE THREAD

**Issue by bmer** [numba/numba#1244]
Here's a small working example: https://gist.github.com/bmer/1e6b622f9a4bf154beee

It should run as is, showing what happens when the numba-fied nopython functions are run on the test inputs, and showing what happens when the python functions are run on the same test input.

I would be happy to provide more information as requested!

**Comment by bmer** [comment]
What is confusing to me (being a novice with Python) is that deleting lines 1 through 7 (Spyder generated auto introduction) actually raises an exception, that is related to numba: 

Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstrain object at 0x000000000B7B14E0>:
('EOF in multi-line string', (2, 0))
File "possible_numba_error.py", line 28

**Comment by seibert** [comment]
I'm getting the same output with Numba and Python using Python 2.7 and Numba 0.19.1 on OS X:
```
+++ Using numba (nopython=True) +++
test_vectors
[[ 0.33445724  0.71722354]
 [ 0.78890929  0.90252736]
 [ 0.16739775  0.02152926]
 [ 0.91892671  0.29242497]
 [ 0.29738445  0.73406855]
 [ 0.78110904  0.82245972]
 [ 0.97773752  0.72518695]
 [ 0.34772653  0.65154215]
 [ 0.83735624  0.46194026]
 [ 0.25384807  0.29937612]]
----------------
test_vectors_normalized
[[ 0.42262906  0.90630275]
 [ 0.65812553  0.75290822]
 [ 0.99183076  0.12756072]
 [ 0.95291403  0.30324057]
 [ 0.37547639  0.92683196]
 [ 0.68864394  0.72509966]
 [ 0.8031889   0.59572442]
 [ 0.47083846  0.88221944]
 [ 0.87559953  0.48303775]
 [ 0.64672852  0.76272028]]
+++ Using python alone +++
test_vectors_normalized
[[ 0.42262906  0.90630275]
 [ 0.65812553  0.75290822]
 [ 0.99183076  0.12756072]
 [ 0.95291403  0.30324057]
 [ 0.37547639  0.92683196]
 [ 0.68864394  0.72509966]
 [ 0.8031889   0.59572442]
 [ 0.47083846  0.88221944]
 [ 0.87559953  0.48303775]
 [ 0.64672852  0.76272028]]
----------------
```
Which Numba, Python, and operating system are you using?

**Comment by bmer** [comment]
I am using Python 2.7 (with Anaconda distribution) and the development version of numba (`conda install -c numba numba`). I am on Windows 8.1.

**Comment by pitrou** [comment]
"EOF in multi-line string" sounds like you forgot to completely remove the triple quotes (`"""`), leaving a string literal unbalanced.

**Comment by bmer** [comment]
@pitrou I think maybe something like that was happening. I am clear of that issue, but I still have the main problem of numbers "blowing up" (unlike @seibert):

```
+++ Using numba (nopython=True) +++
test_vectors
[[ 0.09524367  0.41334025]
 [ 0.47406863  0.76541789]
 [ 0.43513096  0.84736553]
 [ 0.60984144  0.2843297 ]
 [ 0.12754659  0.80403365]
 [ 0.62322453  0.35205619]
 [ 0.80542717  0.77141916]
 [ 0.66709991  0.07176163]
 [ 0.32112034  0.81341934]
 [ 0.79102161  0.22363943]]
----------------
test_vectors_normalized
[[ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]
 [ -9.86830992e+148  -9.86830992e+148]]
+++ Using python alone +++
test_vectors_normalized
[[ 0.22454045  0.97446477]
 [ 0.52654611  0.85014657]
 [ 0.45680245  0.88956817]
 [ 0.90633285  0.42256451]
 [ 0.15667433  0.98765032]
 [ 0.87068319  0.49184426]
 [ 0.72218908  0.69169569]
 [ 0.99426381  0.10695548]
 [ 0.36719993  0.93014204]
 [ 0.9622808   0.27205821]]
----------------
```

**Comment by pitrou** [comment]
This sounds like a memory management issue:

```
>>> struct.unpack("d", b"\xde"*8)
(-9.868309920863368e+148,)
```

(0xDE is the byte we write into memory when we deallocate it)

**Comment by bmer** [comment]
@pitrou Could you give some guidance as to how I could resolve this issue then?

**Comment by pitrou** [comment]
I'm not sure. I think reducing the number of function indirections may solve it. Or you can pass the output array as an explicit parameter to the main function, instead of calling np.empty().
In any case, it's a bug in Numba, so we'll have to solve it...

**Comment by sklam** [comment]
I have identified the problem and have a fix.  PR coming soon.

**Comment by bmer** [comment]
That does it!
