### ISSUE TITLE
Numba not recognizing "multiply by power of 2" as left shift idiom

### ISSUE THREAD

**Issue by seibert** [numba/numba#1245]
A function like this:
```python
@numba.jit(nopython=True)
def slow_left_shift(x, i):
    return x * (2**i)
```
and a function like this:
```python
@numba.jit(nopython=True)
def fast_left_shift(x, i):
    return x << i
```
should both compile to the same thing when `x` and `i` are integers.  However the former implementation results in this:
```gas
___main__.slow_left_shift$10.int64.int64:
	pushq	%r14
	pushq	%rbx
	pushq	%rax
	movq	%rcx, %rbx
	movq	%rdi, %r14
	movabsq	$LCPI0_0, %rax
	movsd	(%rax), %xmm0
	movabsq	$___powidf2, %rax
	movl	%r8d, %edi
	callq	*%rax
	cvttsd2si	%xmm0, %rax
	imulq	%rbx, %rax
	movq	%rax, (%r14)
	xorl	%eax, %eax
	addq	$8, %rsp
	popq	%rbx
	popq	%r14
	retq
```
whereas the latter version does this:
```gas
___main__.fast_left_shift$11.int64.int64:
	movq	%rcx, %rax
	movb	%r8b, %cl
	shlq	%cl, %rax
	movq	%rax, (%rdi)
	xorl	%eax, %eax
	retq
```

(This is almost certainly the cause of the performance issue in #1241.)

**Comment by pitrou** [comment]
The LLVM power intrinsics only seems to support float types as the first argument (see http://llvm.org/releases/3.6.1/docs/LangRef.html#llvm-powi-intrinsic), so our current implementation of int power first casts the integer to float. We could implement int power using the classical algorithm, but I don't know if 1) it would be faster than the float version 2) it would automatically allow LLVM to optimize the power-of-two exponentiation.

**Comment by pitrou** [comment]
Or this could simply be a FAQ entry.

**Comment by seibert** [comment]
If LLVM has no special power intrinsic for integers, then I think we would have to implement this kind of optimization as a rewrite pass on the Numba IR.  I don't think we want to go down that road just yet.

(As an aside, C++ compilers do not have to deal with this particular optimization because they don't appear to have a way to describe an integer being raised to an exponent.  The pow() function is only defined for floating point in the standard.)

**Comment by pitrou** [comment]
compiler-rt has the following simple implementation for powidf2:

```
COMPILER_RT_ABI double
__powidf2(double a, si_int b)
{
    const int recip = b < 0;
    double r = 1;
    while (1)
    {
        if (b & 1)
            r *= a;
        b /= 2;
        if (b == 0)
            break;
        a *= a;
    }
    return recip ? 1/r : r;
}
```

So we could simply rewrite that in Numba and avoid the float/int conversions as well as the external function call.

**Comment by seibert** [comment]
I did a quick test with different variations:
```python
@numba.jit(nopython=True)
def int_power(a, b):
    r = 1.0;
    while True:
        if b & 1:
            r *= a
        b /= 2
        if b == 0:
            break
        a *= a

    return 1/r if b < 0 else r

@numba.vectorize(nopython=True)
def ufunc_power_numpy_scalar(a, b):
    return np.power(a, b)

@numba.vectorize(nopython=True)
def ufunc_power_arithmetic(a, b):
    return a ** b

@numba.vectorize(nopython=True)
def ufunc_power_numba_scalar(a, b):
    return int_power(a, b)
```
They gave this result:
```
x = np.random.uniform(size=1000)
n = 3
%timeit np.power(x, n)
%timeit ufunc_power_numpy_scalar(x, n)
%timeit ufunc_power_arithmetic(x, n)
%timeit ufunc_power_numba_scalar(x, n)
---
10000 loops, best of 3: 37 µs per loop
10000 loops, best of 3: 34.7 µs per loop
100000 loops, best of 3: 5.86 µs per loop
100000 loops, best of 3: 4.63 µs per loop
```

I'm not sure why Numpy's underlying scalar C power function (also used by Numba when we call `np.power()`) is so much slower than what Numba generates for `a ** b`.  I assumed the latter would be a call to the libm `pow()`, which is also what I expect Numpy uses.

**Comment by pitrou** [comment]
`a ** b` calls the above __powidf2(a, b) when b is an integer.
Your code above uses float calculations (r is initialized to 1.0, x is a float array...). Also, you can probably replace `b /= 2` with `b >>= 1` (except for the negative case).

**Comment by seibert** [comment]
Oh, I see, we already have __powidf2 in Numba?  I somehow missed that part.
