### ISSUE TITLE
Cannot resolve setitem

### ISSUE THREAD

**Issue by Kerkil** [numba/numba#1246]
I get errors
```
TypingError: Cannot resolve setitem: array(complex64, 3d, C)[(slice3_type, slice3_type, int64)] = array(complex128, 2d, C)
File "test_jit.py", line 36

Failed at nopython (nopython frontend)
Cannot resolve setitem: array(complex64, 3d, C)[(slice3_type, slice3_type, int64)] = array(complex128, 2d, C)
File "test_jit.py", line 36
```
while running 
```
from numba import jit, complex64
import numpy as np

z_vec = np.arange(0, 200) * 300e-6
x_vec = np.arange(0, 400) * 300e-6 - 0.1

grids = np.meshgrid(x_vec, z_vec)
grids0 = grids[0]
grids1 = grids[1]

@jit([complex64[:,:,:](complex64[:,:])], nopython=True)
def test(data):
    result = np.zeros((200, 400, 5*10), dtype=np.complex64)

    for i in np.arange(5):
        for j in np.arange(10):
            result[:, :, i*4+j] = np.sqrt( (i * grids1)**2+ (j * grids0)**2) * data
    return result
```
with
```
a = np.random.random((200, 400)) + 1j*np.random.random((200, 400))
print(test(a))
```

What is causing the errors? Are complex numpy nd-arrays supported? I am new to Numba and am still learning what I should and should not do with Numba.

Thanks for the help in advance.

**Comment by Kerkil** [comment]
Removing the numpy slicing explicitly solved the issue.
```
@jit(['complex128[:,:,:](complex128[:,:])'], nopython=True)
def test(data):
    result = np.zeros((200, 400, 5*10), dtype=np.complex128)

    # M, N = result.shape

    for i in range(5):
        for j in range(10):
            for m in range(200):
                for n in range(400):
                    result[m, n, i*10+j] = np.sqrt((i * img_grids1[m, n])**2 + (j * img_grids0[m, n])**2 ) * data[m, n]
    return result
```

**Comment by pitrou** [comment]
Not yet, but we plan to support that in the future.

**Comment by andimarafioti** [comment]
I come from the future, it still not supported, am I right?

**Comment by seibert** [comment]
Hello future traveler!  This does work now (although you need to remove the explicit type signature in the decorator since the input array is complex128, not complex64).

**Comment by andimarafioti** [comment]
First, so cool that it is supported! 
But I can't seem to get it to work. I made a minimal example where it doesn't work for me, maybe you/someone has an idea why:

```from numba import njit
import numpy as np

@njit
def test_jit_numpy_slicing():
    diag = np.array([[1,0],[0,1]])
    zeros = np.zeros((3,3))
    return zeros[diag>0]```

The output is: 

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-34-d37f51e18613> in <module>()
----> 1 test_jit_numpy_slicing()

~/.local/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    349                 e.patch_message(msg)
    350 
--> 351             error_rewrite(e, 'typing')
    352         except errors.UnsupportedError as e:
    353             # Something unsupported is present in the user code, add help info

~/.local/lib/python3.5/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    316                 raise e
    317             else:
--> 318                 reraise(type(e), e, None)
    319 
    320         argtypes = []

~/.local/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float64, 2d, C), array(bool, 2d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/amarafioti/.local/lib/python3.5/site-packages/numba/typing/arraydecl.py:71
In definition 9:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/amarafioti/.local/lib/python3.5/site-packages/numba/typing/arraydecl.py:71
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-33-7dc37423919a> (5)

File "<ipython-input-33-7dc37423919a>", line 5:
def test_jit_numpy_slicing():
    <source elided>
    zeros = np.zeros((3,3))
    return zeros[diag>0]
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

Am I doing something wrong or should I open a new issue?

**Comment by seibert** [comment]
Ah, it looks like you are using slicing in a different way that isn't supported yet.  (NumPy array slicing has a *lot* of distinct modes.)  Can you open this as a new issue so we can track it?  Thanks!

**Comment by andimarafioti** [comment]
Cool, I opened a new issue. I still got my project to work today with numba! (https://github.com/tifgan/stftGAN/blob/master/data/pghi%20test.ipynb) So it was not a deal breaker, but I had to re-implement some logic.

**Comment by seibert** [comment]
Great!  Glad you were able to make it work.
