### ISSUE TITLE
simpler example of nopython decorated function returning different results than python implementation

### ISSUE THREAD

**Issue by bmer** [numba/numba#1251]
Previously, [I created an issue that might be related](https://github.com/numba/numba/issues/1249) (at the very least, the symptoms of the problem are the same), but it had a more complicated example script. Here, I present a much simpler example script: https://gist.github.com/bmer/9d3c445cc3cb3c65930f

The script generates a simple polygon, and then calculates "edge vectors", and prints a numpy generated comparison of both results. We see that the numba calculated results are different from the python calculated results, but only in the "y" column:

```
[[ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]
 [ True False]]
```

**Comment by seibert** [comment]
Which version of Numba are you using?  Have you tried the latest Numba build that fixed #1244?

**Comment by pitrou** [comment]
It seems tuple unpacking on array views is faulty. If you replace the inner assignment with:
```
        xA = node_coords[i,0]
        yA = node_coords[i,1]
        xB = node_coords[i_plus1,0]
        yB = node_coords[i_plus1,1]
```

then the problem disappears.

**Comment by bmer** [comment]
@seibert yes, I made sure to run `numba install -c numba numba` again

@pitrou yes, this is what I see too!
