### ISSUE TITLE
PYCC python module library may not have libc symbols

### ISSUE THREAD

**Issue by sklam** [numba/numba#1267]
Needs to update PYCC link step so that we have all the basic libc symbols available.
#1263 required "puts" from libc https://github.com/sklam/numba/commit/f644f57bdbb0acb5cd4dee3c7dc93203c0808a7c but it is available on python2 Linux and Mac

**Comment by pitrou** [comment]
That sounds weird. puts() shouldn't need any special linking, if I believe the man page.

**Comment by sklam** [comment]
I think I have misdiagnosed the problem.  See https://github.com/numba/numba/pull/1263#issuecomment-115744725
