### ISSUE TITLE
PYCC does not have _dynfunc.Closure

### ISSUE THREAD

**Issue by sklam** [numba/numba#1272]
The "python to nopython" call wrapper uses _dynfunc.Closure and the Enviornment object for certain operations: e.g. returning array, storing constant python objects, etc..  However, the PYCC does not emit the _dynfunc.Closure. When these features are used, we may get a segfault.  #1263 inserted a subtarget information to bypass the usage Closure as a temporary fix.

**Comment by pitrou** [comment]
This is for the "extension module" mode of pycc? I'm not extremely surprised :)
In my opinion, the question is still what we want to do with pycc. The "extension module" mode competes with Cython, and Cython is orders to magnitude better than pycc currently. We would need to devote a lot of time to it if we wanted to reverse that situation.

**Comment by sklam** [comment]
Yes, this is for extension module.  I am also not surprised and agree that we will need to make a lot of effort to make PYCC competitive with Cython.  This issue should remind us that we should not forget its usecases and should not implement something that is very difficult to be AOT compiled.

**Comment by pitrou** [comment]
Well, my opinion is that we should leave the "AOT extension modules" use case to Cython.

**Comment by pitrou** [comment]
This is now fixed :)
