### ISSUE TITLE
array.copy not working

### ISSUE THREAD

**Issue by hargup** [numba/numba#1283]
```python
@jit(nopython=True)
def copy(a):
    b = a.copy()
    return b[0]

a = np.arange(2)
print(copy(a))
```

If I run this code I get the error, `LLVM ERROR: Program used external function 'NRT_MemInfo_alloc_safe_aligned' which could not be resolved!` I used `git bisect` and found that issue was introduced in #1238. BTW `numba.tests.test_array_methods` also fails with same error on my machine.

Here's my system information:
```
$uname -a
Linux hargup-Lenovo-G580 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pitrou** [comment]
Have you tried recompiling Numba? I usually run `python setup.py build_ext --inplace`.

**Comment by hargup** [comment]
> Have you tried recompiling Numba?

Great it worked!
