### ISSUE TITLE
Memory leak in this small example script.

### ISSUE THREAD

**Issue by bmer** [numba/numba#1291]
Hi all,

Was able to trace down an issue I was finding in my simulation down to a small example:  https://gist.github.com/bmer/bc578a3b47911a574abe

This script quickly hogs huge amount of my system memory, but my system remains stable unless I try to do something else. Do others find the same? My numba version is: `numba: 0.20.0-np19py27_20`

Kind regards,
Brian

**Comment by bmer** [comment]
@seibert @pitrou @sklam are you able to reproduce the memory leak with the script?

**Comment by sklam** [comment]
@bmer, I can confirm it.

**Comment by bmer** [comment]
@sklam okay, good to know! I was worried about the lack of response indicating that it was a non-issue for others. Happy to patiently wait now, unless I can contribute in some way!

**Comment by bmer** [comment]
Fixed by: https://github.com/numba/numba/pull/1295
