### ISSUE TITLE
bug: addition of vectors adds only first elements 

### ISSUE THREAD

**Issue by nidleo** [numba/numba#1292]
This code prints 6, while it should print [6 4].
It happens both in object and nopython modes.
Note I used numpy.add since operator+ is apparently not supported.

        w = np.array([3,2])
        @nb.jit(nopython=True)
        def addvecs(w):        
            return np.add(w, w)
    
        print addvecs(w)

**Comment by pitrou** [comment]
Which Numba version are you using? The code works fine on Numba master, and so does the `+` operator.

**Comment by nidleo** [comment]
I'm using Numba 0.18.2 which comes with WinPython 2.7.9
Was it fixed in a later version?

**Comment by pitrou** [comment]
It should be ok with 0.19 and 0.20.

**Comment by nidleo** [comment]
Thanks, that fixed it.
