### ISSUE TITLE
Memory leak in small example script.

### ISSUE THREAD

**Issue by bmer** [numba/numba#1297]
Hi all,

@sklam another example script with a memory leak (I have updated to the latest numba version, so I have patch https://github.com/numba/numba/pull/1295). Are you able to reproduce? 

https://gist.github.com/bmer/753cac8ebde04b3472f0

**Comment by sklam** [comment]
I am reproduce this.  This is not related to #1295.

**Comment by sklam** [comment]
Here's a minimal example to reproduce the problem:

```python


@nb.jit(nopython=True)
def g(n):

    x = f(n)
    # y = None  # Uncomment this will "fix" the problem

    for i in range(n):
        y = x[i]

    for i in range(n):
        y = x[i]

    return 0


num_tsteps = 10000
for i in range(num_tsteps):
    g(10)
```

**Comment by sklam** [comment]
@bmer, thanks you so much!  The test cases you provided revealed some hard to find bugs.

**Comment by bmer** [comment]
@sklam Thank you so much for developing numba! I am using it for some simulation work, and it is coming in very handy. That's where the test cases are coming from too :)
