### ISSUE TITLE
Error when using np.arrange with an int created by a loop 

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1306]
I am using numba 0.20 with anaconda on osx 10.10.4
when running

	import numpy as np
	from numba import njit
	@njit
	def f():
	    variable = 0
	    for i in range(1):
	        variable = variable + 1
	    np.arange(variable)

	f()
We get the following error

	---------------------------------------------------------------------------
	TypingError                               Traceback (most recent call last)
	<ipython-input-7-5eab9c9b1522> in <module>()
	      8     np.arange(variable)
	      9 
	---> 10 f()

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
	    157         assert not kws
	    158         sig = tuple([self.typeof_pyval(a) for a in args])
	--> 159         return self.compile(sig)
	    160 
	    161     def inspect_llvm(self, signature=None):

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/dispatcher.py in compile(self, sig)
	    320                                           self.py_func,
	    321                                           args=args, return_type=return_type,
	--> 322                                           flags=flags, locals=self.locals)
	    323 
	    324             # Check typing error if object mode is used

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
	    592     pipeline = Pipeline(typingctx, targetctx, library,
	    593                         args, return_type, flags, locals)
	--> 594     return pipeline.compile_extra(func)
	    595 
	    596 

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_extra(self, func)
	    315                 raise e
	    316 
	--> 317         return self.compile_bytecode(bc, func_attr=self.func_attr)
	    318 
	    319     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
	    324         self.lifted_from = lifted_from
	    325         self.func_attr = func_attr
	--> 326         return self._compile_bytecode()
	    327 
	    328     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in _compile_bytecode(self)
	    579 
	    580         pm.finalize()
	--> 581         return pm.run(self.status)
	    582 
	    583 

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
	    207                     # No more fallback pipelines?
	    208                     if is_final_pipeline:
	--> 209                         raise patched_exception
	    210                     # Go to next fallback pipeline
	    211                     else:

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in run(self, status)
	    199             for stage, stage_name in self.pipeline_stages[pipeline_name]:
	    200                 try:
	--> 201                     res = stage()
	    202                 except _EarlyPipelineCompletion as e:
	    203                     return e.result

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in stage_nopython_frontend(self)
	    412                 self.args,
	    413                 self.return_type,
	--> 414                 self.locals)
	    415 
	    416         with self.fallback_context('Function "%s" has invalid return type'

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
	    708     infer.build_constrain()
	    709     infer.propagate()
	--> 710     typemap, restype, calltypes = infer.unify()
	    711 
	    712     if config.DEBUG:

	/Users/calaim/anaconda/lib/python3.4/site-packages/numba/typeinfer.py in unify(self)
	    412                 unified = self.context.unify_types(*tv.get())
	    413             if unified is types.pyobject:
	--> 414                 raise TypingError("Can't unify types of variable '%s': %s" % (var, tv))
	    415             typdict[var] = unified
	    416         retty = self.get_return_type(typdict)

	TypingError: Failed at nopython (nopython frontend)
	Can't unify types of variable '$39.4': $39.4 := {array(int32, 1d, C), array(int64, 1d, C)}

However with

	import numpy as np
	from numba import njit
	@njit
	def f():
	    variable = 0
	    variable = variable + 1
	    np.arange(variable)

	f()
No error is produced

**Comment by pitrou** [comment]
Does the `variable = np.int64(0)` workaround work for you?

This is an issue that make take time to resolve, as it's due to some peculiarities of our type inference mechanism.

**Comment by nunocalaim** [comment]
variable = np.int64(0) indeed works for me and now the problem is solved! Thank you!

**Comment by pitrou** [comment]
This is fixed in the latest Numba release, closing.
