### ISSUE TITLE
Support for numpy.select in nopython mode

### ISSUE THREAD

**Issue by richardotis** [numba/numba#1313]
It would be nice to support `numpy.select()` in nopython mode for piecewise-defined array computations.

``` python
def piece(x):
    condlist = np.array(x<3, x>5)
    choicelist = np.array(x, x**2)
    return np.select(condlist, choicelist)

result = piece(np.arange(10))
np.allclose(result, np.array([ 0,  1,  2,  0,  0,  0, 36, 49, 64, 81]))
```

**Comment by seibert** [comment]
Looks doable, though we would need to pass tuples instead of lists to the select function.

(Side note: `np.array(x<3, x>5)` doesn't seem to work on Numpy 1.9.  Is this a typo, or does this work on older versions of Numpy?)

**Comment by richardotis** [comment]
My mistake: The arguments to `np.array` should be wrapped in brackets or parentheses.

I can adapt to the use of tuples versus lists for my use case.

**Comment by asmeurer** [comment]
As per https://github.com/sympy/sympy/issues/9747, apparently old versions of numpy require lists here, not tuples, so numba will need to support them.

**Comment by luk-f-a** [comment]
@stuartarchibald, I can pick it up if no one has yet (apparently not as I cannot find any PR referencing it).

**Comment by stuartarchibald** [comment]
@luk-f-a sounds good, thanks v. much.
