### ISSUE TITLE
Homogenously-typed lists in nopython mode

### ISSUE THREAD

**Issue by seibert** [numba/numba#1316]
(This issue is mainly for discussion.  I don't have a concrete proposal for how this should work.)

Lists are useful (as are list comprehensions), and with NRT we could support mutating list contents and length.  However, to support lists in nopython mode we would need the elements of a given list to have a single type, and we would need to be able to infer this type.

We can certainly determine the element type for a non-empty list literal (like `[4, 3]`), but it would be less obvious for lists that start as an empty list, then have values appended to them later.  I don't know if our current type unification algorithm can handle that.

In cases where we cannot guarantee a consistent type for the list elements (for example, if two incompatible types are appended to the list in the function body), we would have to raise an exception in nopython mode.

There is the additional problem that list arguments need to appear to be passed by reference, which basically means that we can only reasonably support:

 * Lists from Python passed as arguments (i.e. lists with a Python interpreter reference): read-only
 * Lists created within nopython (i.e. lists with no Python interpreter references) mode: read-write

I think these are acceptable limitations, but we will need very clear exception messages to explain what is going on.

(A solution for lists would also open the possibility of homogenously-typed dictionaries, where a dictionary instance would have a fixed key type and a fixed value type.)

**Comment by pitrou** [comment]
> but it would be less obvious for lists that start as an empty list, then have values appended to them later. I don't know if our current type unification algorithm can handle that.

I think that would be possible. We need a special type to denote the absence of a type.

> There is the additional problem that list arguments need to appear to be passed by reference

That can probably be solved as well, although we would need additional machinery. The main issue in any case would be performance of passing or returning long lists.

**Comment by seibert** [comment]
I am OK with incurring the overhead of list wrapping and unwrapping since the goal is to only use this when you have to, and not as a substitute for Numpy arrays.

I expect a number of use cases to be temporary nopython lists that are never returned.
