### ISSUE TITLE
NotImplementedError: augmented slice assignment

### ISSUE THREAD

**Issue by jakeret** [numba/numba#1322]
An augment-assign (`+=`) on an array slice causes Numba to raise a `NotImplementedError`.
This can be reproduced with the following code:

```python
import numpy as np
import numba

@numba.jit
def func(buf):
    buf[2:8] += 10

buffer = np.arange(10)
func(buffer)
```
Executing this code produces the following error:
`NotImplementedError: offset=17 opcode=0x5 opname=ROT_FOUR`

I'm running on Python 2.7, Numba 0.20.0 on OSX

**Comment by pitrou** [comment]
I see. This happens only on Python 2.
