### ISSUE TITLE
Need to explain field access with structured dtypes more clearly

### ISSUE THREAD

**Issue by seibert** [numba/numba#1324]
It is not very obvious from http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#scalar-types that accessing a field with getitem syntax (`data[i]['f0']` or `data[i][0]`) will not work, but attribute access will work (`data[i].f0`), even on normal ndarrays where access by attribute is not supported by Numpy.

We should clarify this *and* call it out in the troubleshooting list.

**Comment by pitrou** [comment]
Obsolete as well :)
