### ISSUE TITLE
Implement np.where in nopython mode

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1326]
Hi, I am using Numba as much as I can, 

Is it possible to implement np.where in nopython mode?

This would be great as I frequently need to find all the argmax indices of an array. e.g.
    
    indmax = np.where((X == X.max())))[0]

**Comment by jsphon** [comment]
Perhaps this could help:
https://github.com/numba/numba/issues/1359

**Comment by seibert** [comment]
We have implemented np.where (and np.nonzero) in the PR (#1432) that was just merged to master.  Updated dev packages for numba with this feature should be appearing in our anaconda.org "numba" channel in a few hours.
