### ISSUE TITLE
Classes and class methods in Numba 0.20?

### ISSUE THREAD

**Issue by jsphon** [numba/numba#1336]
What is the current state of applying @jit to classes and class methods?

I can see some example code for 0.11 here: http://numba.pydata.org/numba-doc/0.11/examples.html

However, I can't find any examples in more recent documentation. And if I run that on 0.20 I get this error:

```
#http://numba.pydata.org/numba-doc/0.11/examples.html
from __future__ import print_function, division, absolute_import
from numba import jit, void, int_, double

# All methods must be given signatures

@jit
class Shrubbery(object):
    @void(int_, int_)
    def __init__(self, w, h):
        # All instance attributes must be defined in the initializer
        self.width = w
        self.height = h

        # Types can be explicitly specified through casts
        self.some_attr = double(1.0)

    @int_()
    def area(self):
        return self.width * self.height

    @void()
    def describe(self):
        print("This shrubbery is ", self.width,
              "by", self.height, "cubits.")

shrub = Shrubbery(10, 20)
print(shrub.area())
shrub.describe()
print(shrub.width, shrub.height)
shrub.width = 30
print(shrub.area())
print(shrub._numba_attrs._fields_) # This is an internal attribute subject to change!


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-ef45c1636e8c> in <module>()
      6 
      7 
----> 8 class Shrubbery(object):
      9     @void(int_, int_)
     10     def __init__(self, w, h):

<ipython-input-4-ef45c1636e8c> in Shrubbery(__locals__)
      7 
      8 class Shrubbery(object):
----> 9     @void(int_, int_)
     10     def __init__(self, w, h):
     11         # All instance attributes must be defined in the initializer

/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/types.py in __call__(self, *args)
    105     def __call__(self, *args):
    106         if len(args) == 1 and not isinstance(args[0], Type):
--> 107             return self.cast_python_value(args[0])
    108         return Prototype(args=args, return_type=self)
    109 

TypeError: 'NotImplementedType' object is not callable
```

**Comment by sklam** [comment]
The feature is being redesigned and it is disabled.  The previous implementation is limited and may not give better performance.

**Comment by seibert** [comment]
A better version of this feature is on our short-term roadmap, so hopefully in a few months you'll see the replacement.

**Comment by ericmjl** [comment]
Hey guys, just out of curiosity, is this near completion? Just heard about it from Travis at PyData today!

**Comment by seibert** [comment]
Our prototype PR needs to be updated and expanded to handle reference counted attributes (like numpy arrays) properly.  We are still hopeful to get this in soon, but our developers have not had as much time around other our other projects to work on this.

As a bit of new user-facing syntax (unlike a lot of what Numba does), we also wanted to move slowly to ensure we didn't make any interface decisions we would regret later.  :)

**Comment by ericmjl** [comment]
Woohoo! I'm cheering for you all :)

**Comment by datnamer** [comment]
@seibert Is that nrt ref counted attributes or cpython objects as well?

**Comment by bmer** [comment]
I'd like to join in with Eric in cheering you guys forward! Please work
overtime!

**Comment by seibert** [comment]
Supported attributes will just be scalars (like floats and ints) as well nrt reference counted objects, like Numpy arrays and JIT classes.  Since the point of JIT classes is to keep data in machine-native formats for nopython mode, Python objects will not be allowed.

(However, we might be able to relax things and allow object attributes that are simply not accessible from nopython mode methods, but no promises yet.  We want to keep the first draft of this feature as simple as possible.)

**Comment by ericmjl** [comment]
@seibert: Exciting stuff! I just wanted to clarify one little thing as well: I write agent-based models using Python objects, and most of the stuff I do uses Python data types (lists, strings etc.). The ABMs also use a ton of iteration. Using JIT compilation would help with the speed, if I'm understanding this correctly?

**Comment by datnamer** [comment]
Yes me too! But I use thick agents and want to have stuff like logistic regression and scipy distributions as fields and methods of these agents. That's why I'm worried that the numba 'compile hot loop' philosophy isn't compatible with our use case.

**Comment by seibert** [comment]
@ericmjl: If you do lots of iteration and branching, Numba has the potential to help a lot.  One caveat though is that string support in Numba is almost nonexistent at the moment.  This isn't a fundamental issue (strings are "machine native" containers for text, just like numpy arrays are for numbers), but rather a result of focusing primarily on the numeric use cases for Numba first.  Once we knock out some more of our high priority items, we fully intend to deal with strings.

@datnamer: This use case will be more tricky.  It might require JIT classes + a Numba extension that knows how to translate externally defined scipy types and functions for nopython mode.  Once we have our extension API formalized, Pandas will be our test case for a 3rd party project that extends the Numba type system.  If that goes well, we might get scipy on board as well.  The timeline for this is not short, however.

**Comment by ericmjl** [comment]
@seibert: Thanks for the clarification! Strings for me (right now) are merely labels, equally interchangeable with integer numbers instead. Exciting stuff you all are doing! :smile:

**Comment by datnamer** [comment]
@seibert 

Thanks very much for your thoughts on this. When you talk about an extended timeline, is that because the API has to be adjusted for every use case, or would it take a long time to get scipy on board? If so, would i be able to work with my own fork to massage the classes to be numba compatible for my own specific research, a bit sooner?  

@ericmjl  You might be interested in this python ABM package: https://github.com/projectmesa/mesa 

I think numba JIT classes would be a good PR for that.

**Comment by ericmjl** [comment]
@datnamer: Heard of it already! About ready to transition my code over, I haven't had the time to do so just yet.

**Comment by seibert** [comment]
The extended timeline is mostly because of the number of issues on our plate already.  :)  I don't want to overpromise.

**Comment by datnamer** [comment]
Understood!

**Comment by datnamer** [comment]
How will this PR interact with stuff like Dynd types/traits? It would be cool to dispatch Dynd functions on Numba structs of Dynd arrays and scalars by tagging with traits instead of messing around with multiple dispatch.

**Comment by ml31415** [comment]
Looks like this could be closed, since the classes are working again now for a while?
