### ISSUE TITLE
PIP install on Mac

### ISSUE THREAD

**Issue by izaid** [numba/numba#1337]
I'm having issues installing a new version of Numba (in particlar, Numba 0.20 and LLVMLite 0.20) on Mac OS X with pip. Is this supposed to work?

I have LLVM 3.5.2. I get a few errors, but the first one is:

assembly.cpp:25:17: error: use of undeclared identifier 'parseAssemblyString'; did you mean 'ParseAssemblyFile'?

**Comment by gmarkall** [comment]
Numba 0.20 depends on llvmlite 0.6.0, which needs LLVM 3.6.

**Comment by izaid** [comment]
Noted, will try with this. Thanks.
