### ISSUE TITLE
PyEval_SaveThread/PyEval_RestoreThread causing segfaults?

### ISSUE THREAD

**Issue by aldanor** [numba/numba#1338]
Not really a high-level numba question per se, but I would be very grateful if any numba/llvm gurus here could help me figure this out :)

I was playing around with `llvmlite` trying to use numba's helper classes to compile various snippets, and it all works great except for when I try to release the GIL via `PyEval_SaveThread` / `PyEval_RestoreThread` (sort of following the multithreaded example, or just by inspecting llvm of a simple function wrapped in `@numba.njit` with `nogil=True`). 

The example below segfaults however it works fine when the two PyEval calls are commented out:

```python
# test_llvm.py
from __future__ import print_function

import ctypes
from numba import typing
from numba.targets import cpu
from llvmlite import binding as llvm

mod = """
; ModuleID = 'test'

define i32 @f() {
  %thread = tail call i8* @PyEval_SaveThread()
  tail call void @PyEval_RestoreThread(i8* %thread)
  ret i32 42
}

declare i8* @PyEval_SaveThread()
declare void @PyEval_RestoreThread(i8*)
"""

typing_ctx = typing.Context()
cpu_ctx = cpu.CPUContext(typing_ctx)
codegen = cpu_ctx.jit_codegen()
library = codegen.create_library('lib')
module_ref = llvm.parse_assembly(mod)
module_ref.verify()
library.add_llvm_module(module_ref)
library.finalize()
func_ptr = library.get_pointer_to_function('f')
cfunc = ctypes.CFUNCTYPE(ctypes.c_int32)(func_ptr)
assert cfunc() == 42
```
```sh
$ python test_llvm.py
Fatal Python error: PyEval_SaveThread: NULL tstate
fish: Job 2, “python test_llvm.py” terminated by signal SIGABRT (Abort)
```

Is there anything else in particular that has to be done to release the GIL? And why would it return NULL for main thread's state?

Thanks!

**Comment by pitrou** [comment]
ctypes already releases the GIL: https://docs.python.org/3/library/ctypes.html#ctypes.CFUNCTYPE

**Comment by aldanor** [comment]
Got it! Thanks @pitrou and sorry for a stupid question :)
