### ISSUE TITLE
Make detect print optional

### ISSUE THREAD

**Issue by CJ-Wright** [numba/numba#1346]
It would be nice to make the printing function of detect optional.  I currently use it to check if the machine the code is running on has GPUs, otherwise it uses a slower CPU kernel, but it prints every time it checks for GPUs.

**Comment by sklam** [comment]
``cuda.detect()`` is for printing diagnostic.  You can always check with:

```python
>>> cuda.is_available()  # check for cuda driver
True
>>> list(cuda.list_devices())  # check for cuda devices
[<numba.cuda.cudadrv.devices._DeviceContextManager object at 0x10217ba90>]
>>> for d in cuda.list_devices():
...      print(d.compute_capability)
... 
(3, 0)
```

**Comment by stuartarchibald** [comment]
Closing as solution present.
