### ISSUE TITLE
Memory allocation issue?

### ISSUE THREAD

**Issue by hmgaudecker** [numba/numba#1352]
Two unrelated programs of mine keep failing on a Linux box (Ubuntu 15.04). One with CUDA (@gmarkall has all details on that one), the other with standard Numba.

Unfortunately, it is a bit hard to replicate. I simply call this bit of code:

```python
import numpy as np
from numba import jit


_norm_pdf_C = np.sqrt(2 * np.pi)


@jit()
def _norm_pdf(x):
    return np.exp(-x ** 2.0 / 2.0) / _norm_pdf_C

```

from a larger context and the Python run will break off with this error:

```
python: APFloat.cpp:272: void interpretDecimal(llvm::StringRef::iterator, llvm::StringRef::iterator, decimalInfo*): Assertion `(*p == 'e' || *p == 'E') && "Invalid character in significand"' failed.
Aborted (core dumped)
```

In isolation, the function runs fine. However, even in the larger context, not much memory is used. Versions:

```
numba                     0.20.0               np19py34_0  
llvmlite                  0.6.0                    py34_0  
```

I am happy to help in tracking this down further, but I have no clue on how to proceed myself...

**Comment by sklam** [comment]
I think this is related to the llvm bug (https://llvm.org/bugs/show_bug.cgi?id=12906).  It's a problem due to locale.  We have a workaround in llvmlite (https://github.com/numba/llvmlite/pull/81).  Can you try using the latest llvmlite by:
`conda install -c numba llvmlite`?

**Comment by hmgaudecker** [comment]
Yes, this does the trick on one of the projects - thanks! 

I cannot check on the other one because #1341 kicks in first.
