### ISSUE TITLE
Python crashes if the loop contains slices

### ISSUE THREAD

**Issue by seekiu** [numba/numba#1355]
I ran into this problem when I was modifying one of my scripts. I managed to reproduce it in the following code:

~~~
import numpy as np
from numba import jit

@jit
def foo(f):
    for i in np.arange(100)[1:99]:
        f[i] = 1

F = np.zeros(100)
foo(F)
~~~

I found that as long as I (a) have slice in the second line of function foo; (b) modify the array like the third line does, the python crashes.

I have reproduced this in both Python 2.7.10 (numpy 1.9.2, numba 0.19.1) and Python 3.4.1 (numpy 1.9.2, numba 0.20.0), in two separate machines.

**UPDATE**

I found that replacing `np.arange()` with `range()` does not cause crash. So I guess this is mainly numpy related.

**Comment by pitrou** [comment]
This is reproducible with 0.20.0 but does not crash anymore, so I'm closing the issue as fixed.
