### ISSUE TITLE
Adding numpy functions myself

### ISSUE THREAD

**Issue by jsphon** [numba/numba#1359]
If I wanted to try contributing to numba by making np.unique compatible with nopython mode, where would I begin? Is there any docunentation to help me get started?

**Comment by seibert** [comment]
The documentation for adding new functions is a little sparse, but for something like `np.unique`, I think you would want to see if you can write a nopython mode implementation of it.  We generally try to use nopython-mode Python for implementations (rather than LLVM IR) when we can, and it is a little easier to hook into the system.

The general steps are:

1. Investigate how Numpy implements the function.  We can be sure to learn any performance tricks they've discovered (though sometimes we choose to go a different way).
2. Decide what scope of functionality is reasonable for Numba to support.  Sometimes Numpy functions have really complicated options and semantics that we can't easily handle at this moment.  Generally speaking, we want to support as much as we can, and document what parts we can't.
3. Write an implementation of the function that can be compiled with `@jit` and test cases that verify the implementation gives the same answer as Numpy.
4. Insert the implementation and test cases into the Numba code base.  This is where you'll need more guidance from us, but starting with an `@jit` function streamlines this a bit.

For `np.unique` in particular, I assume that Numpy implements this with a sort, followed with a step that removes consecutive duplicates?   We do not have a sort implementation inside Numba yet (but we've wanted one).  If that's required, let us know, because it will bump up our priority to implement a sort.

Feel free to open a new issue specific to `np.unique` to write notes and get feedback.  When you get to step 4, we can talk you through the integration details.

**Comment by jsphon** [comment]
I've made a vague start, but have hit a problem and am understanding how painful it is to add these seemingly small functions ( all I want is the unique values and the inverse! ).

The Numpy code is at: https://github.com/numpy/numpy/blob/master/numpy/lib/arraysetops.py

My current hacked code is this:

    @nb.jit( nopython=True )
    def unique(ar, return_index=False, return_inverse=False, return_counts=False):
        """
        Find the unique elements of an array.
        Returns the sorted unique elements of an array. There are three optional
        outputs in addition to the unique elements: the indices of the input array
        that give the unique values, the indices of the unique array that
        reconstruct the input array, and the number of times each unique value
        comes up in the input array.
        Parameters
        ----------
        ar : array_like
            Input array. This will be flattened if it is not already 1-D.
        return_index : bool, optional
            If True, also return the indices of `ar` that result in the unique
            array.
        return_inverse : bool, optional
            If True, also return the indices of the unique array that can be used
            to reconstruct `ar`.
        return_counts : bool, optional
            If True, also return the number of times each unique value comes up
            in `ar`.
            .. versionadded:: 1.9.0
        Returns
        -------
        unique : ndarray
            The sorted unique values.
        unique_indices : ndarray, optional
            The indices of the first occurrences of the unique values in the
            (flattened) original array. Only provided if `return_index` is True.
        unique_inverse : ndarray, optional
            The indices to reconstruct the (flattened) original array from the
            unique array. Only provided if `return_inverse` is True.
        unique_counts : ndarray, optional
            The number of times each of the unique values comes up in the
            original array. Only provided if `return_counts` is True.
            .. versionadded:: 1.9.0
        See Also
        --------
        numpy.lib.arraysetops : Module with a number of other functions for
                                performing set operations on arrays.
        Examples
        --------
        >>> np.unique([1, 1, 2, 2, 3, 3])
        array([1, 2, 3])
        >>> a = np.array([[1, 1], [2, 3]])
        >>> np.unique(a)
        array([1, 2, 3])
        Return the indices of the original array that give the unique values:
        >>> a = np.array(['a', 'b', 'b', 'c', 'a'])
        >>> u, indices = np.unique(a, return_index=True)
        >>> u
        array(['a', 'b', 'c'],
               dtype='|S1')
        >>> indices
        array([0, 1, 3])
        >>> a[indices]
        array(['a', 'b', 'c'],
               dtype='|S1')
        Reconstruct the input array from the unique values:
        >>> a = np.array([1, 2, 6, 4, 2, 3, 2])
        >>> u, indices = np.unique(a, return_inverse=True)
        >>> u
        array([1, 2, 3, 4, 6])
        >>> indices
        array([0, 1, 4, 3, 1, 2, 1])
        >>> u[indices]
        array([1, 2, 6, 4, 2, 3, 2])
        """
        
        #ar = np.asanyarray(ar).flatten()
        l = ar.shape[0]
        for i in range( 1, len( ar.shape ) ):
            l *= ar.shape[i]
        ar = ar.reshape( ( l, ) ).copy()
    
        optional_indices = return_index or return_inverse
        optional_returns = optional_indices or return_counts
    
        if ar.size == 0:
            if not optional_returns:
                ret = ar
            else:
                ret = (ar,)
                if return_index:
                    ret += (np.empty(0, np.bool_),)
                if return_inverse:
                    ret += (np.empty(0, np.bool_),)
                if return_counts:
                    ret += (np.empty(0, np.intp),)
            return ret
    
        if optional_indices:
            #perm = ar.argsort(kind='mergesort' if return_index else 'quicksort')
            #aux = ar[perm]
            perm = sas.quick_arg_sort( ar )
            aux = ar# quick_arg_sort also sorts ar in place, though that is bad form
        else:
            #ar.sort()
            sas.quick_sort( ar )
            aux = ar
            
        #flag = np.concatenate(([True], aux[1:] != aux[:-1]))
        flag = np.empty( ar.shape[0], dtype=np.bool_ )
        for i in range( 1, ar.shape[0] ):
            #if aux[i]!=aux[i-1]:
            flag[i]=( aux[i]!=aux[i-1] )
                
        if not optional_returns:
            #print( 'no optional returns' )
            #print( 'flag is %s'%str(flag))
            ret = aux[flag]
        else:
            #print( 'Making ret' )
            ret = (aux[flag],)
            #print( 'ret is %s'%str(ret))
            if return_index:
                ret += (perm[flag],)
            if return_inverse:
                iflag = np.cumsum(flag) - 1
                inv_idx = np.empty(ar.shape, dtype=np.intp)
                inv_idx[perm] = iflag
                ret += (inv_idx,)
            if return_counts:
                uniques = ret[0]
                cnts    = np.zeros_like( uniques )
                c = 0
                j = 0
                for i in range( uniques.shape[0] ):
                    c+=1
                    if flag[ i ]:
                        cnts[j]=c
                        c=0
                        
                #idx = np.concatenate(np.nonzero(flag) + ([ar.size],))
                #ret += (np.diff(idx),)
                ret += ( cnts )
                pass
        
        return ret

I recieve this error message:

    Undeclared +((array(int64, 1d, C) x 1), (array(bool, 1d, C) x 1))

Which is from this line:

    ret += (np.empty(0, np.bool_),)

How can I overcome that?

The sorting functions are here: https://github.com/jsphon/NumericalFunctions/blob/master/numerical_functions/numba_funcs/sorting_and_searching.py

**Comment by seibert** [comment]
Awesome!  It looks like you have made significant progress, and this is often how we find missing functionality we need.  :)

The error you are running into appears to be a missing type promotion from bool to integer.  Temporarily you could switch that dtype to something like `np.int8`, but I think we will need to solve the bool casting problem before this task is finished.

**Comment by jsphon** [comment]
Unfortunately I then get this error on the same line:

    numba.errors.TypingError: Failed at nopython (nopython frontend)
    Undeclared +((array(int64, 1d, C) x 1), (array(int8, 1d, C) x 1))

Does the Undeclared cause issues?

**Comment by jsphon** [comment]
To help focus on this error, I wrote this function:

    @nb.jit( nopython=True )
    def ret( x ):
        z = np.empty(0, np.bool_)
        r = (x,)
        r+=(z,)
        return x

And this test:

        def test_ret(self):
            
            x = np.array([1,2,3])
            r = ret(x)
            
            print(r)

Which produces this error:

    numba.errors.TypingError: Failed at nopython (nopython frontend)
    Undeclared +((array(int64, 1d, C) x 1), (array(bool, 1d, C) x 1))
    File "../../numba_funcs/setops.py", line 14

**Comment by jsphon** [comment]
I have been playing around with the ret function from my previous post:

    @nb.jit( nopython=True )
    def ret( x, y=True ):
        z = np.empty(0, np.bool_)
        r =(z,)
        
        if y:
            r = ( x, z )
        else:
            r = ( x, )
    
        return r

When I compile that I get:

	======================================================================
	ERROR: test_ret (numerical_functions.tests.numba_funcs.setops_tests.Test)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/jon/Documents/LiClipseWorkspace/NumericalFunctions/numerical_functions/tests/numba_funcs/setops_tests.py", line 19, in test_ret
	    r = mod.ret(x)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/dispatcher.py", line 159, in _compile_for_args
	    return self.compile(sig)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/dispatcher.py", line 322, in compile
	    flags=flags, locals=self.locals)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 594, in compile_extra
	    return pipeline.compile_extra(func)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 317, in compile_extra
	    return self.compile_bytecode(bc, func_attr=self.func_attr)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 326, in compile_bytecode
	    return self._compile_bytecode()
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 581, in _compile_bytecode
	    return pm.run(self.status)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 209, in run
	    raise patched_exception
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 201, in run
	    res = stage()
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 414, in stage_nopython_frontend
	    self.locals)
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/compiler.py", line 710, in type_inference_stage
	    typemap, restype, calltypes = infer.unify()
	  File "/home/jon/anaconda/envs/py33/lib/python3.3/site-packages/numba/typeinfer.py", line 414, in unify
	    raise TypingError("Can't unify types of variable '%s': %s" % (var, tv))
	numba.errors.TypingError: Failed at nopython (nopython frontend)
	Can't unify types of variable '$60.2': $60.2 := {(array(bool, 1d, C) x 1), (array(int64, 1d, C), array(bool, 1d, C)), (array(int64, 1d, C) x 1)}

Does that error message mean that nopython numba functions must have the same number of output values?

If that is the case, what would be the recommended way of implementing np.unique, which can return 1, 2, 3 or 4 arrays, depending on the input parameters. My use case requires 2 arrays to be returned (the unique values plus the unique inverses).

**Comment by jsphon** [comment]
Well, I can't work out how to to make Numba return different sized tuples, so I have written a couple of unique functions instead of having parameters for defining optional outputs.

The working functions are:

    unique_idx
    unique_inv

They are in

    https://github.com/jsphon/NumericalFunctions/blob/master/numerical_functions/numba_funcs/setops.py

    https://github.com/jsphon/NumericalFunctions/blob/master/numerical_functions/tests/numba_funcs/setops_tests.py

**Comment by pitrou** [comment]
Hi,
I believe the new extension API should be able to better fulfill your needs, especially the `@overload` decorator: http://numba.pydata.org/numba-doc/dev/extending/high-level.html
You can see `@overload` in action for the `np.random.choice` and `np.random.binomial` implementations here: https://github.com/numba/numba/pull/1758/files#diff-fc10ff6a06bb8e957cd37bc735a32226R1201

**Comment by pitrou** [comment]
Closing for now. Feel free to reopen or open a new issue if there are insufficiencies.
