### ISSUE TITLE
Switch out Continuum logo

### ISSUE THREAD

**Issue by amenity** [numba/numba#1367]
Please update the Continuum Analytics logo on http://numba.pydata.org/.
![screen shot 2015-08-17 at 2 53 28 pm](https://cloud.githubusercontent.com/assets/1463708/9314644/c561d1e6-44ef-11e5-874d-f98306b9f6d1.png)

Assets available here: 
https://sites.google.com/a/continuum.io/wiki/marketing/public
(Click "Company Logos" to go here: https://drive.google.com/a/continuum.io/folderview?id=0B4LRrCKZqSrMfllwVmZibUJzc09DS0NqWEZ0VERKcnhyVlFIaHJFU043RGxjdW9MLVI3Wmc&usp=sharing)

Let me know if you need further help/info. Thank you!

**Comment by seibert** [comment]
Should be fixed now.  Thanks for the reminder!

**Comment by amenity** [comment]
Wonderful, thank you Stan!

*____________________________*

*Amenity Applewhite*
*Creative Technologist*

[image: Continuum Analytics] <http://continuum.io>
