### ISSUE TITLE
Performance Of MergeSort vs Numpy

### ISSUE THREAD

**Issue by jsphon** [numba/numba#1383]
Also posted here: http://stackoverflow.com/questions/32133597/how-to-improve-this-merge-sort

I have written a mergesort in Python/Numba:

```
import numba as nb
import numpy as np

@nb.jit( nopython=True )
def merge( x ):

    n = x.shape[0]
    width=1

    r   = x.copy()
    tgt = np.empty_like( r )
    while width<n:
        i=0
        while i<n:
            istart = i
            imid = i+width
            iend = imid+width
            # i has become i+2*width
            i = iend

            if imid>n:
                imid = n

            if iend>n:
                iend=n
            _merge( r, tgt, istart, imid, iend)

        # Swap them round, so that the partially sorted tgt becomes the result,
        # and the result becomes a new target buffer
        r, tgt = tgt, r
        width*=2

    return r

@nb.jit( nopython=True )
def _merge( src_arr, tgt_arr, istart, imid, iend ):
    """ The merge part of the merge sort """
    i0   = istart
    i1   = imid
    for ipos in range( istart, iend ):
        if ( i0<imid ) and ( ( i1==iend ) or ( src_arr[ i0 ] < src_arr[ i1 ] ) ):
            tgt_arr[ ipos ] = src_arr[ i0 ]
            i0+=1
        else:
            tgt_arr[ ipos ] = src_arr[ i1 ]
            i1+=1
```

I have written a test for it:

```
def test_merge_multi(self):

    n0 = 21
    n1 = 100

    for n in range( n0, n1 ):
        x = np.random.random_integers( 0, n, size=n )

        with Timer( 'nb' ) as t0:
            r = sas.merge( x )
        with Timer( 'np' ) as t1:
            e = np.sort( x, kind='merge' )
        #print( 'r:%s'%str(r))
        #print( 'e:%s'%str(e))
        print( 'nb/np performance %s'%(t0.interval/t1.interval ))
        np.testing.assert_equal( e, r )
```

I used this Timer class:

```
import time

class Timer:    

    def __init__(self,title=None):
        self.title=title

    def __enter__(self):
        if self.title:
            print( 'Beginning {0}'.format( self.title ) )
        self.start = time.clock()
        return self

    def __exit__(self, *args):
        self.end = time.clock()
        self.interval = self.end - self.start
        if self.title:
            print( '{1} took {0:0.4f} seconds'.format( self.interval, self.title ) )
        else:
            pass#
            #print( 'Timer took {0:0.4f} seconds'.format( self.interval ) )
```

The test results are:

```
nb/np performance 9307.846153856719
nb/np performance 1.1428571428616743
nb/np performance 0.7142857142925115
nb/np performance 0.8333333333302494
nb/np performance 0.9999999999814962
nb/np performance 0.9999999999777955
nb/np performance 0.8333333333456692
nb/np performance 0.8333333333302494
nb/np performance 1.0
nb/np performance 0.8333333333456692
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 0.8333333333456692
nb/np performance 0.9999999999814962
nb/np performance 1.0
nb/np performance 0.9999999999814962
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 1.0000000000185036
nb/np performance 1.2000000000044408
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 1.0000000000185036
nb/np performance 1.2000000000088817
nb/np performance 1.0
nb/np performance 1.1666666666512469
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 0.9999999999814962
nb/np performance 1.1666666666728345
nb/np performance 1.1666666666512469
nb/np performance 1.0
nb/np performance 1.0
nb/np performance 1.1666666666512469
nb/np performance 1.1666666666512469
nb/np performance 1.1666666666728345
nb/np performance 1.1666666666728345
nb/np performance 1.1666666666728345
nb/np performance 1.1666666666728345
nb/np performance 1.1666666666512469
nb/np performance 1.1666666666512469
nb/np performance 1.0
nb/np performance 1.1666666666728345
nb/np performance 1.3333333333456692
nb/np performance 1.3333333333024937
nb/np performance 1.3333333333456692
nb/np performance 1.1428571428435483
nb/np performance 1.3333333333209976
nb/np performance 1.1666666666728345
nb/np performance 1.3333333333456692
nb/np performance 1.3333333333209976
nb/np performance 1.000000000012336
nb/np performance 1.1428571428616743
nb/np performance 1.3333333333456692
nb/np performance 1.3333333333209976
nb/np performance 1.1428571428616743
nb/np performance 1.1428571428616743
nb/np performance 1.3333333333456692
nb/np performance 1.499999999990748
nb/np performance 1.2857142857074884
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857029569
nb/np performance 1.1428571428616743
nb/np performance 1.1428571428435483
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857233488
nb/np performance 1.2857142857029569
nb/np performance 1.1249999999895917
nb/np performance 1.2857142857029569
nb/np performance 1.2857142857233488
nb/np performance 1.4285714285623656
nb/np performance 1.249999999993061
nb/np performance 1.1250000000034694
nb/np performance 1.2857142857029569
```

graphed results (from a different run):

[![enter image description here](http://i.stack.imgur.com/TyNOU.png)](http://i.stack.imgur.com/TyNOU.png)

Graphed results from a longer run:

[![enter image description here](http://i.stack.imgur.com/OXMuo.png)](http://i.stack.imgur.com/OXMuo.png)

Please note that for n<=20, numpy uses an insertion sort when the mergesort is called: https://github.com/numpy/numpy/blob/master/numpy/core/src/npysort/mergesort.c.src

So you can see that for small values of n, the numba version of the mergesort beats the numpy version.

However, as n gets larger, numpy then consistently outperforms numba by a factor of 2.

Why is this? And how could I optimise the numba version to beat the numpy version for all n?

**Comment by pitrou** [comment]
Numpy also uses a top-down mergesort (recursive), while yours is a bottom-up mergesort. That may explain some of the difference.
Do you get different results with an array of int8 values? Your algorithm may not be very cache-friendly.

**Comment by pitrou** [comment]
But you should also try starting with an insertion sort for small sub-arrays (i.e. first insertion-sort runs of 20 items).

**Comment by pitrou** [comment]
You might also rewrite the `_merge` subroutine to avoid the multiple index checks inside the loop. There should be a first loop that runs until one of the two sub-arrays is exhausted, and then an epilogue which copies the non-exhausted sub-array.

**Comment by seibert** [comment]
It is also worth noting that @pitrou is experimenting with implementing Timsort (https://en.wikipedia.org/wiki/Timsort) for Numba.  :)

**Comment by jsphon** [comment]
Pitrou - it appears to be worse for np.int8 values.

Rewriting the merge function to avoid the multiple index checks results in a 10% improvement.

    @nb.jit( nopython=True )
    def merge2( x ):
        
        n = x.shape[0]
        width=1
        
        r   = x.copy()
        tgt = np.zeros_like( r )
        while width<n:
            i=0
            while i<n:
                istart = i
                imid = i+width
                iend = imid+width
                # i has become i+2*width
                i = iend
    
                if imid>n:
                    imid = n
                    
                if iend>n:
                    iend=n
                _merge2( r, tgt, istart, imid, iend)
    
            # Swap them round, so that the partially sorted tgt becomes the result,
            # and the result becomes a new target buffer
            r, tgt = tgt, r
            width*=2
            
        return r
    
    @nb.jit( nopython=True )
    def _merge2( src_arr, tgt_arr, istart, imid, iend ):
        """ The merge part of the merge sort """
        i0   = istart
        i1   = imid
    
        ipos = istart
        v0 = src_arr[ i0 ]
        v1 = src_arr[ i1 ]
        while i0<imid and i1<iend:        
            if v0<=v1:
                tgt_arr[ ipos ] = v0
                i0+=1
                v0 = src_arr[ i0 ]
            else:
                tgt_arr[ ipos ] = v1
                i1+=1
                v1 = src_arr[ i1 ]
            ipos+=1
            
        while i0<imid:
            tgt_arr[ ipos ] = src_arr[ i0 ]
            ipos+=1
            i0+=1
            
        while i1<iend:
            tgt_arr[ ipos ] = src_arr[ i1 ]
            ipos+=1
            i1+=1

**Comment by pitrou** [comment]
Now that I have experimented a bit on my side, I can add that:
- timsort will not be competitive with quicksort on quasi-random data; quicksort's inner loops are much tighter than timsort's, which is a complicated beast
- reimplementing Numpy's non-recursive quicksort with Numba also ends up roughly 2x slower than the original C version; I am not sure why but that gap may be hard to fill; at least with quicksort we may be able to read the generated code, though

This doesn't answer your question about mergesort but at least adds some light to the topic :)

**Comment by pitrou** [comment]
Ok, by using an insertion sort for small sub-arrays, Numba is only 1.15x slower asymptotically than Numpy, and is faster for n <= 500 roughly. See https://gist.github.com/pitrou/e12353a5839fb60d3fc1

**Comment by pitrou** [comment]
I'll note that the best results are obtained with an `int32` array here (Linux x86-64). With an array of `int64` or `int16` for example, Numba is 1.35x slower. This is unlikely due to any issues in Numba itself, rather code generation differences between gcc and LLVM.
