### ISSUE TITLE
Wrong trailing digits with unsigned integer?

### ISSUE THREAD

**Issue by szli** [numba/numba#1386]
I am using numba 0.19.1 and seeing something interesting.
If I define variable us as uint64, the trailing digits are wrong
```python
@numba.jit(numba.uint64(), nopython=True, nogil=True, locals = {'us':numba.uint64 })
def toEpoch2():
    us = 1234567 % 1000000 
    return (10**15 + us) * 1000
```
This function returns 1000000000234567040, note that the last three digits should be zero. 

But if I define us to be int64
```python
@numba.jit(numba.uint64(), nopython=True, nogil=True,  locals = {'us':numba.int64 })
def toEpoch4():
    us = 1234567 % 1000000 
    return (10**15 + us) * 1000
```
It actually works correctly: 1000000000234567000

Not sure what the reason is...

**Comment by seibert** [comment]
This is the result of the current way that integer type promotion is implemented in Numba

http://numba.pydata.org/numba-doc/dev/proposals/integer-typing.html#current-semantics

In your case `uint64` + `int64` was promoted to `float64`, which matches the behavior of Numpy scalars.

However, once we merge PR #1366, this bug should be fixed.

**Comment by szli** [comment]
I see, this makes perfect sense!

**Comment by pitrou** [comment]
Indeed, this is now fixed in the latest Numba.
