### ISSUE TITLE
Printing strings in CUDA is not supported

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1392]
Only printing of integers and reals (and arrays of these) is supported. Printing strings would be helpful for printf-debugging.

**Comment by seibert** [comment]
Was this fixed by #1391?

**Comment by gmarkall** [comment]
No, it supports printing integers and floats and arrays of these, but not strings.

**Comment by pitrou** [comment]
AFAIR, it's not supported in CPU mode either, unless you're thinking of fixed-length inside structured dtypes?

**Comment by pitrou** [comment]
But, yes, it would be extremely useful.

**Comment by gmarkall** [comment]
> AFAIR, it's not supported in CPU mode either

Ah, yes, that is true - I had mistakenly assumed that since the CPU target used the Python interpreter for printing (#1390) it could print arbitrary strings. But this is indeed not the case.

**Comment by Stretch97** [comment]
+1 to this enhancement

**Comment by gmarkall** [comment]
Fixed in #1961
