### ISSUE TITLE
cannot unify range_state32 and range_state64

### ISSUE THREAD

**Issue by sklam** [numba/numba#1394]
This script

``` python
from numba import njit

@njit
def foo(a):
    if a:
        for i in range(a):
            a += i
        i = 1.2
    return a, i


print(foo(1))

foo.inspect_types()

```

causes this error:

```
  File "/Users/sklam/dev/numba/numba/typeinfer.py", line 45, in add_type
    % (self.type, tp, self.var))
numba.errors.TypingError: Failed at nopython (nopython frontend)
cannot unify range_state64 and range_state32 for '$6.3'
```

**Comment by pitrou** [comment]
There are several issues here:
* the fact that the first `i` variable (the loop iteration result) is inferred as float due to the later assignment
* the fact range_state64 and range_state32 cannot be unified
* the fact that calling range(float64) is typed as returning a range_state32

**Comment by stuartarchibald** [comment]
This appears to work now (Numba 0.37). Closing. Please reopen if this is still an issue.
