### ISSUE TITLE
parallel-for support

### ISSUE THREAD

**Issue by nidleo** [numba/numba#1403]
Is it possible to bring back some sort of par-for support like the old prange?
Currently, as I understand it, it is only possible to parallelize multiple calls to jitted numba functions with nogil=True. However, there are no parallel constructs supported within a numba function.

I think an openmp like for-loop would be a very strong addition as it is possibly the most common parallel construct. Recently I found myself in need of this (a nested for-loop inside a large computation), and unfortunately had to rewrite in C++.

p.s.
Keep up the good work! Numba is an amazing tool that is changing the way I work and I'd love to see the extent to which it is applicable grow.

**Comment by seibert** [comment]
We are very interested in bringing back some kind of OpenMP style for loops to nopython mode.  We don't have an exact plan for how this would look yet, but it is definitely on our radar.  Some changes in the next few Numba releases will also make this easier for us.

**Comment by zonca** [comment]
Are there more concrete plans now? I think this is the only weak point of numba now.

**Comment by OndrejMarsalek** [comment]
I would also be interested in whether there is some progress or more specific plans in this area.

**Comment by seibert** [comment]
prange() was added to Numba thanks to the ParallelAccelerator compiler passes.  Closing.
