### ISSUE TITLE
Improving the warp-synchronous-programming

### ISSUE THREAD

**Issue by sklam** [numba/numba#1410]
For the warp synchronous segment at https://github.com/numba/numba/blob/master/numba/cuda/reduction.py#L60-L72
- Do we need memory fences (https://github.com/numba/numba/pull/1409)?
- We should consider using shuffle for newer arch (see http://devblogs.nvidia.com/parallelforall/cuda-pro-tip-kepler-shuffle/)

**Comment by gmarkall** [comment]
I think we should have memory fences - the reduction slides were written at the time prior to CC 2.0, which was when fences and volatile was introduced - prior to that, warp-synchronous operations were visible across all threads in a warp immediately (IIRC).

**Comment by gmarkall** [comment]
Shouldn't we be declaring sdata as volatile, instead of using thread fences? Looking at the SDK reduction example, it appears to me that thread fences are required for the implementation of a single-kernel reduction, but not for the warp-synchronous segment.

**Comment by pitrou** [comment]
Are fences required when a syncthreads() call is present? I would logically assume that syncthreads() entails a memory barrier, but perhaps not.
As for volatile, I think that's orthogonal. Your data can be volatile from the point of view of a single thread, but its changes still be propagated out of order to the local memories (?) of other threads.
In other words, "volatile" is an directive for the compiler to obey, while a fence is an instruction for the hardware.

**Comment by gmarkall** [comment]
I think no fence is needed if you use syncthreads to make updates in shared memory visible to all threads in a block, as the CUDA programming guide recommends its use for synchronising threads within a block for the purpose of sharing data with each other. However, I'm unclear if it makes global memory accesses synchronised within a thread.

I agree, volatile is orthogonal - but I think it's what's needed for the warp-synchronous segment highlighted in this issue.

**Comment by seibert** [comment]
syncthreads implies a block-level memory fence along with an execution barrier.

My understanding was that memory fences were introduced in order to avoid needing to use the volatile argument.  A fence will force the compiler to generate code that reload values from memory on the other side of the fence.  In addition, the fences also prevent instruction reordering across the fence.

**Comment by pitrou** [comment]
> syncthreads implies a block-level memory fence along with an execution barrier.

So it's good for shared memory but not enough for global memory, I guess?

> A fence will force the compiler to generate code that reload values from memory on the other side of the fence. In addition, the fences also prevent instruction reordering across the fence.

I see, in that sense it's stronger than the volatile keyword (the volatile keyword alone wouldn't do anything for ordering).

**Comment by seibert** [comment]
Correct, syncthreads was created just as a shared memory fence and block synchronization tool.  Back in the first days of CUDA, there was basically no primitive suitable for coordinating memory visibility between blocks.  Then came atomic operations, which are also implicitly volatile (as well as synchronized by the memory controller).

Now there are memory fence instructions for each level of visibility in the memory hierarchy: block, global (restricted to the device), and system-wide (other devices and the host in the case of host memory mapped into the device address space).

**Comment by seibert** [comment]
As an aside: I would say (based on questions in the CUDA forum) that many of the CUDA developers who use a memory fence are making a mistake, and should be using syncthreads.  The number of forum questions that were answered by "fences are not barriers" was staggeringly huge.  :)

**Comment by sklam** [comment]
As a note, I am working on `shuffle()` (https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/shuffle.html) for AMD HW and I want to provide that to CUDA as well.  I think `shuffle()` is harder to misuse and should be preferred over memory-fences for warp-synchronous programming.  It makes intra-warp (and even barrier-less intra-block) communication explicit.  No need for fences and barriers.

**Comment by seibert** [comment]
I was looking at the threadfence documentation again:

http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-fence-functions

And noticed that NVIDIA *is* still telling people to use the `volatile` keyword when wanting to ensure correct behavior for threads that need to observe changes in global memory after a `__threadfence()` call.  They don't show any usage of `volatile` with shared memory though.

**Comment by sklam** [comment]
I got a mistake:
> As a note, I am working on shuffle()(https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/shuffle.html) 

That shuffle is not the CUDA warp shuffle equivalent.  HSAIL has ``__hsail_activelanepermute``.

**Comment by seibert** [comment]
Now that warp-synchronous programming has been deprecated (dangerous with CUDA 9 and Volta), I'm closing this issue, but opening a new issue #2589 because the reduction kernel described above is not guaranteed to work going forward.
