### ISSUE TITLE
Can we have a pypi release for 0.21.0 ?

### ISSUE THREAD

**Issue by cournape** [numba/numba#1420]
Hi,

Would it be possible to have a pypi release for 0.21.0 for downstream packagers ?

**Comment by seibert** [comment]
Yes, we are definitely going to do that.  The release appeared in the conda package repo before we had finished the rest of the release process.  :)

**Comment by cournape** [comment]
I see. Having a conda package repo indeed does not really help me to package numba for Canopy :)

**Comment by seibert** [comment]
We've finished the release process, and the source tar file is now on PyPI:

https://pypi.python.org/pypi/numba/0.21.0

Note that this version requires llvmlite >= 0.7.0.  The version requirement didn't make it into the README, but we will fix that.
