### ISSUE TITLE
Bug in refct pruning

### ISSUE THREAD

**Issue by sklam** [numba/numba#1434]
Observed by ~~defining~~(edit: undefining) NDEBUG for "nrt.h" and running "numba.tests.test_tuples.TestNamedTupleNRT".
The pruning logic is incorrect for not considering potential aliasing.  As a result, a refcount can temporarily reach zero after pruning. ~~Without~~(edit: With) the NDEBUG, this causes a double-free error.

**Comment by sklam** [comment]
It is incorrect that the bug is observed in "numba.tests.test_tuples.TestNamedTupleNRT".
It seems to only affect my https://github.com/sklam/numba/tree/experiment/jitclasses branch. Have not determined if this is an implementation error of jit classes or if there is really a bug in refct pruning.

**Comment by pitrou** [comment]
Should this bug be left open?

**Comment by sklam** [comment]
This is resolved.
