### ISSUE TITLE
Integration with Yeppp! ?

### ISSUE THREAD

**Issue by datnamer** [numba/numba#1436]
Has the numba team seen this?

http://www.yeppp.info/ 

Supposed to be many times faster than openlibpm and faster than mkl.

**Comment by hiccup7** [comment]
The Julia language (http://julialang.org/) already has a package for Yeppp!  My comparisons between  MKL (in Python) and Yeppp! resulted in MKL being several times faster.  Multi-threading in MKL explains this.

**Comment by seibert** [comment]
Closing this in favor of adding SVML support (see #2351)
