### ISSUE TITLE
HSA: weird truncation error at implicit coercion

### ISSUE THREAD

**Issue by sklam** [numba/numba#1439]
With hsa backend,

``` python
curdata = uintp(data[dataid] if valid else 0)
```

When data is `uintp` (and 64-bit), the coercion causes a loss in precision in LSB.  The problem is "fixed" with:

``` python
curdata = uintp(data[dataid] if valid else uintp(0))
```

an extra explicit cast to `uintp`.

**Comment by stuartarchibald** [comment]
Closing, HSA replaced by ROC.
