### ISSUE TITLE
double * not supported with cffi or ctypes?

### ISSUE THREAD

**Issue by timothydmorton** [numba/numba#1443]
I'd like to call compiled function that takes an array as a one of the arguments from within nopython mode, but I can't get it to work by prototyping it either using ctypes or ffi.  It appears that numba doesn't support double * either with ctypes or ffi?  I've tried hack-ish fixes like the ones suggested [here](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/ITye9OXF8Qk) but they don't seem to work for me.  I'm using numba 0.21.   What I'd like to do is define the function prototype to take double *, and then pass it a "numpy array" in nopython mode and have that work.  Any suggestions?

**Comment by pitrou** [comment]
I'm not sure it will work, but have you tried passing `myarray.ctypes.data`?

**Comment by gmarkall** [comment]
Whilst it's possible to make this work (demonstrated in the branch at https://github.com/gmarkall/numba/commits/arrays_to_ptrs ), I'm not sure if this is desirable, because it seems to differ from the normal Python semantics. For example, when I pass a numpy array of float32 to a cffi function that takes a `float*` parameter, I get an error like:

```
TypeError: initializer for ctype 'float *' must be a cdata pointer, not numpy.ndarray
```

@timothydmorton is there an example of something like this working in normal Python code that you can share that Numba does not compile?

**Comment by gmarkall** [comment]
Just to help clarify any further discussion, here are examples of two versions of a function that I've been experimenting with, one which works in Python and one which works in a jitted function:

```python
from numba import cffi_support, jit
import numpy as np
import cffi

# Create the vectormaths module

defs = "void vsSin(int n, float* x, float* y);"
source = """\
void vsSin(int n, float* x, float* y) {
    int i;
    for (i=0; i<n; i++)
        y[i] = sin(x[i]);
}"""


ffi = cffi.FFI()
ffi.set_source('vectormaths', source)
ffi.cdef(defs, override=True)
ffi.compile()


# Import the compiled module

import vectormaths
cffi_support.register_module(vectormaths)
vsSin = vectormaths.lib.vsSin


# Method 1, works in Python, passes numpy arrays using casts.
# Pro: it actually works in Python
# Cons: it's a bit fiddly, may be difficult to support ffi.cast in Numba well

def python_version(x):
    y = np.empty_like(x)
    vsSin(len(x), ffi.cast('float *', x.ctypes.data),
        ffi.cast('float *', y.ctypes.data))
    return y

x = np.arange(10).astype(np.float32)
python_y = python_version(x)


# Method 2, works in Numba (depends on the arrays_to_ptrs branch):
# Pros: It can be made to work in Numba, code a bit cleaner
# Con: doesn't actually work without the @jit decorator

@jit(nopython=True)
def numba_version(x):
    y = np.empty_like(x)
    vsSin(len(x), x, y)
    return y

x = np.arange(10).astype(np.float32)
numba_y = numba_version(x)


# These two versions do produce the same thing
assert np.all(python_y == numba_y)
```

**Comment by gmarkall** [comment]
Upon a bit of further experimentation: a more generic (and possibly easier to support in Numba) version that works in Python is to use the `from_buffer` method:

```
# Method 3, works in Python, passes numpy arrays using a buffer.

def python_version(x):
    y = np.empty_like(x)
    vsSin(len(x), ffi.from_buffer(x), ffi.from_buffer(y))
    return y
```

**Comment by gmarkall** [comment]
I started a discussion on the python-cffi mailing list about implementing support for passing buffer objects to pointer parameters in cffi, so that potentially if we chose to implement passing arrays to `double*` arguments (for example), it could be consistent with uses of cffi in normal Python code: https://groups.google.com/forum/#!topic/python-cffi/xEz7OxjA1O8

**Comment by gmarkall** [comment]
According to the response I received on the mailing list, the solution that we should use is to construct arguments to pointers is to call `ffi.from_buffer(ary)` - so I will try to support that (i.e. Method 3 will work in both normal Python and Numba-jitted code, and Method 2 will not be supported).

I don't want to diverge from normal Python semantics in jitted code, even if it does allow the code to be written a bit more cleanly - we have one example where this is the case already (handling of members of structured arrays) and it's quite annoying to disable Numba's jit for debugging purposes only to find that the code doesn't run at all in normal Python.

**Comment by pitrou** [comment]
This is now fixed with support for cffi's `from_buffer()`.
