### ISSUE TITLE
Python list reflection

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1444]
We should investigate if we can accept Python lists as parameters to nopython functions, and reflect modifications done to the list by Numba when returning to the interpreter.

**Comment by gmarkall** [comment]
May not be necessarily useful, but a note: delaying side effects of functions to outside objects reminds me of Codeplay's Sieve-C++ language extensions, which were designed to simplify the semantics of C++ to make it easier to run loop iterations in parallel (as I remember it being described): https://www.codeplay.com/public/uploaded/publications/sievepaper-2columns-normal.pdf
