### ISSUE TITLE
np.where() fails in numba 0.21

### ISSUE THREAD

**Issue by josepm** [numba/numba#1449]
Session attached.
According to the docs np.where() is supported in numba 0.21
This simple test fails:

In [19]: numba.__version__
Out[19]: '0.21.0'

In [20]: v
Out[20]: array([ 2. , -1. ,  3. , -0. ,  4.2, -5.3, -7. ])

In [21]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:@numba.jit(nopython=True)
:def test(v):
:    return np.where(v > 0)
:--

In [22]: test(v)
---------------------------------------------------------------------------
UntypedAttributeError                     Traceback (most recent call last)
<ipython-input-22-e9acabab5d2e> in <module>()
----> 1 test(v)

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    169         assert not kws
    170         sig = tuple([self.typeof_pyval(a) for a in args])
--> 171         return self.compile(sig)
    172 
    173     def inspect_llvm(self, signature=None):

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/dispatcher.pyc in compile(self, sig)
    346                                           self.py_func,
    347                                           args=args, return_type=return_type,
--> 348                                           flags=flags, locals=self.locals)
    349 
    350             # Check typing error if object mode is used

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    635     pipeline = Pipeline(typingctx, targetctx, library,
    636                         args, return_type, flags, locals)
--> 637     return pipeline.compile_extra(func)
    638 
    639 

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(self, func)
    356                 raise e
    357 
--> 358         return self.compile_bytecode(bc, func_attr=self.func_attr)
    359 
    360     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.pyc in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    365         self.lifted_from = lifted_from
    366         self.func_attr = func_attr
--> 367         return self._compile_bytecode()
    368 
    369     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.pyc in _compile_bytecode(self)
    622 
    623         pm.finalize()
--> 624         return pm.run(self.status)
    625 
    626 

/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.pyc in run(self, status)
    248                     # No more fallback pipelines?
    249                     if is_final_pipeline:
--> 250                         raise patched_exception
    251                     # Go to next fallback pipeline
    252                     else:

UntypedAttributeError: Caused By:
Traceback (most recent call last):
  File "/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.py", line 242, in run
    res = stage()
  File "/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.py", line 455, in stage_nopython_frontend
    self.locals)
  File "/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/compiler.py", line 752, in type_inference_stage
    infer.propagate()
  File "/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numba/typeinfer.py", line 510, in propagate
    raise errors[0]
UntypedAttributeError: Unknown attribute "where" of type Module(<module 'numpy' from '/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numpy/__init__.pyc'>)

Failed at nopython (nopython frontend)
Unknown attribute "where" of type Module(<module 'numpy' from '/usr/local/anaconda-2.3.0/lib/python2.7/site-packages/numpy/__init__.pyc'>)

**Comment by pitrou** [comment]
np.where() will be supported in the 0.22 version, which will be released in a couple of weeks, but it is not in Numba 0.21.
