### ISSUE TITLE
Dynamic ufuncs seem to have a type inference bug with boolean arguments

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1456]
The results from a dynamic ufunc can depend on the types of the first argument with which it is called:

``` python
import numba
import numpy as np

@numba.vectorize
def where(condition, x, y):
    if condition:
        return x
    else:
        return y

print where(True, 1.0, 2.0)  # 1.0
print where(True, 1, 2)  # 1.0
print where.types  # ['?dd->d']


@numba.vectorize
def where(condition, x, y):
    if condition:
        return x
    else:
        return y

print where(True, 1, 2)  # 1
print where(True, 1, 2)  # 1
print where.types  # ['?ll->l']
```

I'm running Numba 0.21.0.

By the way: this `where` function generated with Numba is 5x (!) faster than NumPy's `where` in a simple benchmark:

```
x = np.random.randn(10000)
y = np.random.randn(10000)
cond = x > 0
%timeit where(cond, x, y)  # 100000 loops, best of 3: 9.97 µs per loop
%timeit np.where(cond, x, y)  # 10000 loops, best of 3: 49.2 µs per loop
```

**Comment by pitrou** [comment]
Answering a bit late here, but this is due to how Numba's dispatch mechanism tries to reuse existing signatures when they are "appropriate". The alternative is to compile more signatures.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
