### ISSUE TITLE
in-place vector divided by scalar failing

### ISSUE THREAD

**Issue by mcg1969** [numba/numba#1459]
```
NotImplementedError: No definition for lowering /?=(array(float64, 1d, C), float64) -> array(float64, 1d, C)
File "../../hexrd/build/lib.macosx-10.5-x86_64-2.7/hexrd/xrd/transforms_NUMBA.py", line 151
```

This is returned when I attempt to divide an array by a scalar in Numba 0.21...

**Comment by mcg1969** [comment]
It's not just in-place; this fails too.
```
@jit('(f8[:],f8,f8[:])', nopython=True)
def div3_(vec, val, out):
    out = vec / val
```

**Comment by pitrou** [comment]
As a work-around, you can probably `from __future__ import division` (or switch to Python 3 :-)).

**Comment by mcg1969** [comment]
Ooh, good point, thanks

**Comment by mcg1969** [comment]
Actually that isn't fixing the `div3_` case, which is returning ```NotImplementedError: Don't know how to create implicit output array with 'A' layout.```

**Comment by mcg1969** [comment]
Nevermind that, I see that was already fixed [here](https://github.com/numba/numba/pull/1421).

**Comment by seibert** [comment]
Closing as it sounds like this was fixed.
