### ISSUE TITLE
No CUDA application was profiled

### ISSUE THREAD

**Issue by samplesizeofone** [numba/numba#1465]
I'm unable to profile numba with nvprof. I'm able to profile the samples that came with the CUDA toolkit. I've also tried profiling all processes while running numba fizzix.py. I've listed the specifics below.

Command line:

```
nvprof --profile-child-processes numba fizzix.py
...
======== Warning: No CUDA application was profiled, exiting
...
```

```
export export NUMBA_DEBUG=1
numba fizzix.py > debug.log
more debug.log
...
target triple = "nvptx64-nvidia-cuda"
...
```

Code snippet:

```
@cuda.jit('void(float32[:], float32[:])')
def increment3(a, b):
    x = cuda.grid(1)
    if x < b.size:
        b[x] = a[x] + math.sqrt(a[x])
```

Config:

OS X 10.11
numba 0.21.0 np19py27_0
CUDA Driver Version: 7.5.20

**Comment by sklam** [comment]
Is the CUDA function executed in "fizzix.py"?  Is the code snippet all of fizzix.py?

**Comment by samplesizeofone** [comment]
Yes, the CUDA function is executed in fizzix.py . I should really have included the full source. Here's a gist with a stripped down version that has the same profiling problem: https://gist.github.com/samplesizeofone/27a7cf1438b68d0b971e

Let me know if I can provide more information. I'd also be happy to run a known good code snippet on my machine.

**Comment by sklam** [comment]
Becareful that numpy.float is not float32.  I'd suggest not providing the type signature so that the cuda kernel is just:

```python
@cuda.jit
def increment3(a, b):
    x = cuda.grid(1)
    if x < b.size:
        b[x] = a[x] + math.sqrt(a[x])
```

When the type signature is provided, the kernel dispatch does not check the array dtype.

As for `nvprof`, it works for me with `nvprof --profile-child-processes numba fizzix.py`.  My `nvprof` version is:

```
nvprof: NVIDIA (R) Cuda command line profiler
Copyright (c) 2013 - 2014 NVIDIA Corporation
Release version 7.0.18 (21)
```
I am using OSX 10.10.5.  I tested numba 0.21.0 np19py27_0 and master.  But I am using an older CUDA driver: 7.0.18.

Let me know if removing the type signature fixed the problem.

**Comment by samplesizeofone** [comment]
I removed the type signature, but still no luck. I tried installing a few of the previous versions from the repo, also no luck.

**Comment by sklam** [comment]
Does it work with your regular python interpreter?  I mean ``nvprof python fizzix.py``. 
Also, make sure CUDA simulator is not enabled accidentally:

``numba.config.ENABLE_CUDASIM`` evaluate to False.
```python
In [8]: import numba.config

In [9]: numba.config.ENABLE_CUDASIM
Out[9]: 0
```

**Comment by samplesizeofone** [comment]
I've confirmed the CUDA simulator is disabled. I get the same result when using the regular python interpreter. I've also verified that nvprof works on one of the CUDA toolkit samples.

Is there a mailing list I could post to asking if anyone else has a problem under OS X 10.11?

Also, I'm very comfortable with C and Python. If there's any easy way to add some useful logging, I can do that. I'm also happy to run a custom build on my machine and send back log results.

**Comment by gmarkall** [comment]
If you modify fizzix.py to call `cuda.profile_start()` before execution of CUDA code and `cuda.profile_stop()` at the end of execution, does this make any difference?

**Comment by samplesizeofone** [comment]
Unfortunately, cuda.profile_start() and cuda.profile_stop() don't seem to have an impact.

**Comment by sklam** [comment]
There is a numba mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/numba-users

**Comment by sklam** [comment]
I just tried nvprof from cuda7.5.  I got an error from nvprof about incompatible driver version:

```
==2050== NVPROF is profiling process 2050, command: python fizzix.py
======== Error: incompatible CUDA driver version.
```

```
$ nvprof -V
nvprof: NVIDIA (R) Cuda command line profiler
Copyright (c) 2012 - 2015 NVIDIA Corporation
Release version 7.5.14 (21)
```

**Comment by samplesizeofone** [comment]
I ripped out CUDA toolkit 7.5 by hand and installed 7.0. nvprof now works fine with numba. I had tried install 7.0 before, but I guess I wasn't thorough enough. Thank you for your help.

**Comment by samplesizeofone** [comment]
Do we want to open an issue about numba possibly being CUDA 7.5 incompatible?

**Comment by seibert** [comment]
Yeah that would make sense.  We're trying to decide in which release to switch over to CUDA 7.5, so this motivates us to jump a little sooner.

**Comment by seibert** [comment]
Closing as we've long since upgraded to CUDA 8 (and profiler seems to work).
