### ISSUE TITLE
Support nestedarray as dtype of Array

### ISSUE THREAD

**Issue by sklam** [numba/numba#1469]
This is not supported:

``` python
import numpy as np
import numba
qtype = np.dtype((np.float64,(4,)))
ntype = numba.types.Array(numba.from_dtype(qtype),2,'C')
```

and results in:

```
numba/types.py in __init__(self, dtype, ndim, layout, readonly, name)
    728         if isinstance(dtype, Buffer):
    729             print(type)
--> 730             raise TypeError("Buffer dtype cannot be buffer")
    731         if layout not in self.LAYOUTS:
    732             raise ValueError("Invalid layout '%s'" % layout)

TypeError: Buffer dtype cannot be buffer
```

Note that:

``` python
In [7]: numba.from_dtype(qtype)
Out[7]: nestedarray(float64, (4,))
In [16]: a = np.zeros(4, dtype=qtype)

In [17]: a.shape
Out[17]: (4, 4)

In [18]: a.dtype
Out[18]: dtype('float64')
```

**Comment by scootty1** [comment]
Any news on this? Using structured arrays (and record arrays as well) like `x = np.zeros((), dtype=[('x', 'float64', (5, 5)), ('y', 'float64', (10, 10))])` would be really helpful. :)

**Comment by ARF1** [comment]
For anybody who is looking for a struct-replacement containing arrays, the following code seems to work:

```
import numba as nb
import numba.types as types

@nb.jit
def ask(a):
    return a + 1

import numpy as np

state_dtype = np.dtype([
    ('a', np.int64, [1,2]),
    ('b', np.int64),
])

state = np.rec.array([(1, 2)], dtype=state_dtype)
state = state[0]

@nb.jit(nopython=True)
def test(state):
    b = 0
    for i in range(10000000000):
        b += ask(state.a[0,0])
    return b

test(state)
```

Obviously this only give a single "struct", not an array of structs. Also, accessing an record is about 4x slower than accessing a 0d or 1d record array. (Though the latter lack the nestedarray support at per OP.)

Currently this seems to be the only way to create something like a struct that can be used to carry state with variables of different types including arrays.

I would love to hear if somebody has found a better work-around.

**Comment by gmarkall** [comment]
Possible starter patch for this and #3158 

```diff
diff --git a/numba/core/types/npytypes.py b/numba/core/types/npytypes.py
index 25050f30c..e9da0249d 100644
--- a/numba/core/types/npytypes.py
+++ b/numba/core/types/npytypes.py
@@ -209,6 +209,10 @@ class Record(Type):
 
         return as_struct_dtype(self)
 
+    @property
+    def bitwidth(self):
+        return self.dtype.itemsize * 8
+
     def can_convert_to(self, typingctx, other):
         """
         Convert this Record to the *other*.
@@ -427,6 +431,10 @@ class Array(Buffer):
         if (not aligned or
             (isinstance(dtype, Record) and not dtype.aligned)):
             self.aligned = False
+        if isinstance(dtype, NestedArray):
+            tmp = Array(dtype.dtype, dtype.ndim, 'C')
+            ndim += tmp.ndim
+            dtype = tmp.dtype
         if name is None:
             type_name = "array"
             if not self.mutable:
@@ -553,6 +561,10 @@ class NestedArray(Array):
     """
 
     def __init__(self, dtype, shape):
+        if isinstance(dtype, NestedArray):
+            tmp = Array(dtype.dtype, dtype.ndim, 'C')
+            shape += dtype.shape
+            dtype = tmp.dtype
         assert dtype.bitwidth % 8 == 0, \
             "Dtype bitwidth must be a multiple of bytes"
         self._shape = shape
```

with this, the following:

```python
import numpy as np
import numba


qtype = np.dtype((np.float64, (4,)))
ntype = numba.types.Array(numba.from_dtype(qtype), 2, 'C')
print(ntype)


nested = np.dtype(
    (np.dtype((np.float64, (5, 2))), (3, 6))
    )


ntype2 = numba.types.Array(numba.from_dtype(nested), 3, 'C')

print(ntype2)
```

prints:

```
array(float64, 3d, C)
array(float64, 7d, C)
```

with the second output demonstrating that we've managed to sum the dimensions through the "nested nested" array.

As noted on #3158, the patch works around the issue, but a rethink of the design might be better. E.g. when discussing #7359, which fixes a lot of similar issues, it was suggested that maybe nested arrays should more generally just type as arrays.

**Comment by luk-f-a** [comment]
I finally managed some time to look into this issue. tbh, I'm not sure it needs fixing. Sure, full compability with Numpy would need this feature, but I fail to see the usefulness of this dtype. Please someone correct me if I'm wrong. Unlike #7359 there's no recordarray involved. Note the difference between `ntype1` and `ntype2` in the example below. 

```
qtype = np.dtype((np.float64,(4,)))
ntype1 = numba.types.Array(numba.from_dtype(qtype),2,'C')

rectype = np.dtype([('a', np.float64,(4,))])
ntype2 = numba.types.Array(numba.from_dtype(rectype),2,'C')
```
ntype1 seems to me like a 3d array under a different name. Am I missing something?

ntype2 is working since #7359

**Comment by gmarkall** [comment]
`ntype2` from your example works, but `ntype2` from my comment above gives:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/1469/repro.py", line 15, in <module>
    ntype2 = numba.types.Array(numba.from_dtype(nested), 3, 'C')
  File "/home/gmarkall/numbadev/numba/numba/np/numpy_support.py", line 112, in from_dtype
    return types.NestedArray(subtype, dtype.shape)
  File "/home/gmarkall/numbadev/numba/numba/core/types/abstract.py", line 66, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/types/npytypes.py", line 556, in __init__
    assert dtype.bitwidth % 8 == 0, \
AttributeError: 'NestedArray' object has no attribute 'bitwidth'
```

It does look like a special case of a multidimensional array. It might not be used in many use cases, but I'm curious if the above patch fixes it without too much effort. To that end I've opened https://github.com/numba/numba/pull/8120 to see if the suggested patch makes any tests fail. I agree that it's not high priority though so if the patch needs reworking to be maintainable / straightdforward, or makes existing tests fail, then time might be better spent elsewhere.
