### ISSUE TITLE
@jit caching in Ipython Notebook

### ISSUE THREAD

**Issue by hellpanderrr** [numba/numba#1471]
I am trying to use `cache=True` in `jit` in Ipython Notebook:
   
    from numba import jit

    @jit(nogil=True,cache=True)
    def f(x):
        # A somewhat trivial example
        return x
I get the following error:
```
WindowsError                              Traceback (most recent call last)
<ipython-input-1-febe72e66841> in <module>()
      2 from numba import jit
      3 
----> 4 @jit(nogil=True,cache=True)
      5 def f(x):
      6     # A somewhat trivial example

C:\Users\hellpanerrr\Anaconda\lib\site-packages\numba\decorators.pyc in wrapper(func)
    167                           targetoptions=targetoptions)
    168         if cache:
--> 169             disp.enable_caching()
    170         if sigs is not None:
    171             for sig in sigs:

C:\Users\hellpanerrr\Anaconda\lib\site-packages\numba\dispatcher.py in enable_caching(self)
    288 
    289     def enable_caching(self):
--> 290         self._cache = FunctionCache(self.py_func)
    291 
    292     def __get__(self, obj, objtype=None):

C:\Users\hellpanerrr\Anaconda\lib\site-packages\numba\dispatcher.py in __init__(self, py_func)
    504         self._data_name_pattern = '%s.{number:d}.nbc' % (filename_base,)
    505 
--> 506         self.enable()
    507 
    508     def __repr__(self):

C:\Users\hellpanerrr\Anaconda\lib\site-packages\numba\dispatcher.py in enable(self)
    511     def enable(self):
    512         self._enabled = True
--> 513         st = os.stat(self._source_path)
    514         # This may be a bit strict but avoids us maintaining a magic number
    515         self._version = numba.__version__

WindowsError:[Error 123] The filename, directory name, or volume label syntax is incorrect: '<ipython-input-1-febe72e66841>'
```

If I remove the brackets I get the following:
```
C:\Users\hellpanerrr\Anaconda\lib\site-packages\numba\dispatcher.py in enable(self)
    511     def enable(self):
    512         self._enabled = True
--> 513         st = os.stat(self._source_path.replace('<','').replace('>',''))
    514         # This may be a bit strict but avoids us maintaining a magic number
    515         self._version = numba.__version__

WindowsError: [Error 2] : 'ipython-input-1-febe72e66841'
```
I am using Win7x64, Python 2.7.10, numba 0.21.0, IPython 3.2.0.

Thanks!

**Comment by seibert** [comment]
Good catch!  This is a situation we haven't tested before.  We will take a look and see how we can workaround this.

**Comment by pitrou** [comment]
The problem is a notebook isn't backed by a well-known source file, so we can't check that our cached function is as recent as the latest modifications to the source code. Also we don't know in which directory to save the cached function...

Perhaps IPython exposes an API allowing us to get the information anyway?

**Comment by hellpanderrr** [comment]
I don't know Ipython internals and I can be wrong, but if code is run from Ipython it will have `get_ipython()` method in the `globals()` which returns an object with some info, it looks like this http://pastebin.com/cuKvnEVi and it has a cell code in the `get_ipython().parent_header['content']['code']` field.
Can we utilize this?

**Comment by pitrou** [comment]
I've proposed a way to do this in PR #1473. It works under Linux, and should probably work under Windows too.

**Comment by hellpanderrr** [comment]
Seems to work under Windows.
