### ISSUE TITLE
Document recarray vs structured dtype array field access syntax and note limitations

### ISSUE THREAD

**Issue by seibert** [numba/numba#1487]
Numba cannot yet handle field access with `__getitem__` (as in `x[0]['field0']`), forcing you to use the recarray syntax to access fields by attribute, regardless of whether the array is an ndarray or a recarray.  Until we fix this, we should document the situation more clearly in the Numba reference manual.

**Comment by pitrou** [comment]
This issue is now obsolete due to supporting dict access on structured arrays.
