### ISSUE TITLE
np.abs and np.fabs return incorrect output

### ISSUE THREAD

**Issue by jennolsen84** [numba/numba#1503]
The following program fails.

versions:

numba: master (currently at @c37d9e12f76f64977ab7a6e6857e4c979297759c)
numpy: 1.10.1
llvmlite: 0.8.0
python: 3.4.3

```
import numba as nb
import numpy as np

def fn(x):
    return np.abs(x)

@nb.njit
def nbfn(x):
    return np.abs(x)

x = np.array([-1, 0, 1])
assert np.all(fn(x) == nbfn(x))
```

**Comment by seibert** [comment]
We can't seem to reproduce this.  Which platform are you running this on?  (Mac/Win/Linux 32/64-bit?)

**Comment by seibert** [comment]
Also, can you show us what the output of both `fn(x)` and `nbfn(x)` are?

**Comment by jennolsen84** [comment]
I can't either... it is possible that I accidentally used the wrong tab and ran it in a different environment.  (I later went back and got the versions).  Next time, I will print the versions in my script to avoid this.

I will close this now as a non-bug
