### ISSUE TITLE
the content of return array created in jitted funtion is not correct

### ISSUE THREAD

**Issue by liuzhenhai** [numba/numba#1511]
test on numba 0.22.0, win64, python 64bit
```python
from numba import njit
import numpy as np
@njit
def f():
    a=np.ones(10,np.float64)
    b=np.ones(10,np.float64)
    #if put the defination of  a and b outside the function, then everything is fine
    return a,b[:]
f()  #if use print f(), it will crash python
```
here is the results:
(array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]),
 array([ -9.86830992e+148,  -9.86830992e+148,  -9.86830992e+148,
         -9.86830992e+148,  -9.86830992e+148,  -9.86830992e+148,
         -9.86830992e+148,  -9.86830992e+148,  -9.86830992e+148,
         -9.86830992e+148]))

**Comment by sklam** [comment]
Bug is reproduced and it is not platform dependent.
The problem is (again) traced to the reference count optimization pass inside numba.

**Comment by pitrou** [comment]
This has now been fixed. Thanks for reporting!
