### ISSUE TITLE
Ubuntu 15 No module named versioneer

### ISSUE THREAD

**Issue by sh1ng** [numba/numba#1513]
sudo pip install 

numbaCollecting numba
  Using cached numba-0.22.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-irezyR/numba/setup.py", line 14, in <module>
        import versioneer
    ImportError: No module named versioneer

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-irezyR/numba

**Comment by pm67nz** [comment]
Compared to the previous release the 0.22.0 tarball at https://pypi.python.org/pypi/numba/0.22.0 is missing versioneer.py along with AUTHORS, CHANGE_LOG, docs, examples, LICENSE, README.rst and runtests.py.

**Comment by jenshnielsen** [comment]
Confirming. This is in no way specific to Ubuntu. The 0.22 pypi package is not installable due to the missing versioneer.py file

**Comment by seibert** [comment]
ok, that is very weird.  Thanks for the report, and we'll post a 0.22.1 today.

**Comment by sklam** [comment]
Apparently, you can't sdist the sdist'ed package.  So, what I did is:
1) `python setup.py sdist` to build a source package
2) untar the source package and test it
3) then `sdist upload` from the source package (result of the first sdist)
Now that I check the tarball from step 3, the metafiles are all gone.

**Comment by sklam** [comment]
Ok, we should have included the MANIFEST.in file

**Comment by seibert** [comment]
Update: I think 0.22.1 will be posted tomorrow.  We had one other high priority bug fix to slip into this release.

**Comment by seibert** [comment]
I believe this should be fixed with the 0.22.1 release on PyPI.

**Comment by jenshnielsen** [comment]
Thanks Fixed for me
