### ISSUE TITLE
CUDA print test unreliable on python2

### ISSUE THREAD

**Issue by sklam** [numba/numba#1524]
The CUDA print tests are failing in our internal jenkins machines on Python2.  They work fine on Python3.  The error is not observed outside of the jenkins environment on the same machine.

Details:
The CUDA print tests are failing because the first stdout capture will see previously printed messages and not just the messages printed to stdout during the test.  This causes the error to fail.  Also note that the only the first print test will fail, the subsequent tests fine.  Perhaps, this is due to buffered data to the FILE.

**Comment by seibert** [comment]
This was resolved a while ago.
