### ISSUE TITLE
Compilation failure in WingIDE

### ISSUE THREAD

**Issue by seibert** [numba/numba#1541]
[Bug report from https://groups.google.com/a/continuum.io/d/msgid/numba-users/f3823e12-9dc6-4c03-813b-b6130209521e%40continuum.io?utm_medium=email&utm_source=footer]

This code fails to compile (assuming it isn't found in the cache) from inside WingIDE, but works in the normal python interpreter:
``` python
from numba import *
from numpy import *
import numpy

def stats(feld,weights=None,dim=None,lang='ger',mima=None,short=None):

    if weights is not None:
        if dim is not None:
            pass
        else:
            dim=0
    else:
        weights=numpy.asarray([0])
        if dim is not None:
            pass
        else:
            dim=0

    arr=feld.ravel()
    
#    t=time.time()
    s,sq=statcore(feld,arr,weights,dim)
#    print 'statcore: ',time.time()-t
    
    if short is not None:
        if mima is not None:
            smima='/%4.1f/%4.1f'%(numpy.nanmin(feld.flatten()),numpy.nanmax(feld.flatten()))
        else:
            smima=''
    
        return "%4.1f/%4.1f/%4.1f" %( s,math.sqrt(sq),math.sqrt(numpy.abs(sq-s*s)))+smima
    else:
    
        std=math.sqrt(numpy.abs(sq-s*s))
        if mima is not None:
            if std>10:
                smima=', Min: %3.0f, Max: %3.0f'%(numpy.nanmin(feld.flatten()),numpy.nanmax(feld.flatten()))
            else:
                smima=', Min: %4.1f, Max: %4.1f'%(numpy.nanmin(feld.flatten()),numpy.nanmax(feld.flatten()))
                
        else:
            smima=''
    
        if std>10:
            fs='Mittel: %3.0f, RMS: %3.0f, Sig: %3.0f'
        else:
            fs='Mittel: %4.1f, RMS: %4.1f, Sig: %4.1f'
            
        if lang=='ger':
            return fs %( s,math.sqrt(sq),math.sqrt(numpy.abs(sq-s*s)))+smima
        else:
            return "Mean: %4.1f, RMS: %4.1f, Sig: %4.1f" %( s,math.sqrt(sq),math.sqrt(numpy.abs(sq-s*s)))+smima

@njit(cache=True)
def statcore(feld,arr,weights,dim):
    s=0.
    sq=0.
    count=0.

    if weights.shape[0]!=1:

        stride=1
        for i in range(feld.ndim-1,dim,-1):
            stride*=feld.shape[i]

        k=0
        ki=0
        for i in range(arr.shape[0]):
            if arr[i]==arr[i]:
                s+=arr[i]*weights[k]
                sq+=arr[i]*arr[i]*weights[k]
                count+=weights[k]
            ki+=1
            if ki==stride:
                k+=1
                ki=0
                if k==weights.shape[0]:
                    k=0

    else:
        for i in range(arr.shape[0]):
            if arr[i]==arr[i]:
                s+=arr[i]
                sq+=arr[i]*arr[i]
                count+=1.0

    if count>0:             
        s/=count
        sq/=count

    return s,sq

def numbabug():
    x=linspace(0,1.,101)

    print stats(x)

if __name__ == "__main__":
    numbabug()
```

Error is:
```

File "/fio/srvx7/leo/python/numbabug.py", line 96, in <module>
  print stats(x)
File "/fio/srvx7/leo/python/numbabug.py", line 22, in stats
  s,sq=statcore(feld,arr,weights,dim)
File "/opt/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 172, in _compile_for_args
  return self.compile(sig)
File "/opt/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 350, in compile
  flags=flags, locals=self.locals)
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 644, in compile_extra
  return pipeline.compile_extra(func)
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 361, in compile_extra
  return self.compile_bytecode(bc, func_attr=self.func_attr)
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 370, in compile_bytecode
  return self._compile_bytecode()
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 631, in _compile_bytecode
  return pm.run(self.status)
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
  res = stage()
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 458, in stage_nopython_frontend
  self.locals)
File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 759, in type_inference_stage
  infer.propagate()
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 506, in propagate
  errors = self.constraints.propagate(self)
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 111, in propagate
  constraint(typeinfer)
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 324, in __call__
  self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 287, in resolve
  args = tuple(a.getone() for a in argtypes)
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 287, in <genexpr>
  args = tuple(a.getone() for a in argtypes)
File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 83, in getone
  assert self.type is not None

AssertionError:
```
Problem started appearing after Numba 0.20.

**Comment by AdamKaniaYui** [comment]
I would add, that it's easy to provide a minimal example, although with this issue active (which I also confirm) it happens on just about any Numba code (so even a trivial few-lines functions trigger that AssertionError on compilation).
This issue prevented me from developing using Numba since quite a few months.
Anybody has any insights as to possible causes of this error? Is it more Numba- or WingIDE-related?

**Comment by pitrou** [comment]
> Anybody has any insights as to possible causes of this error? Is it more Numba- or WingIDE-related?

Difficult to say. One of us will have to install a copy of WingIDE. Can you describe exactly what your workflow is, so we can reproduce it?

**Comment by AdamKaniaYui** [comment]
The issue was happening on all recent versions of Numba, including 0.22.1.
But a few hours ago I installed Numba 0.23 and it seems it's working correctly again.
Had no time to look closer, so let me test it a bit more and I'll confirm whether it's still happenning in 0.23.

Thank you very much!

**Comment by AdamKaniaYui** [comment]
I can now confirm that all my code using Numba runs correctly under WingIDE version 5.1.8-1 using last release of Numba 0.23 (Windows 64bit). So it appears as if the bug was somehow removed between 0.22 and 0.23. Thank you guys!

I'm curious if *seibert* confirms that too.

**Comment by AdamKaniaYui** [comment]
I can now confirm that really almost all of my code using Numba runs correctly under WingIDE version 5.1.8-1 using last release of Numba 0.23 (Windows 64bit). So it appears as if the bug was somehow removed between 0.22 and 0.23.

That said - I still experienced *one single time* the same bug using 0.23 Numba build - which I unfortunately cannot reproduce (might be data dependent or for other reasons difficult to reproduce). So it still somehow might not be 100% reliable, although for any practical purposes current state allows comfortable development.

I'm curious if **seibert** confirms that, although I run his example code and it also works perfectly with 0.23 Numba build under WingIDE.

So it seems that your work on issues between 0.22 and 0.23 accidentally fixed this bug. In my opinion, from my side - this issue could be considered closed, at least until another reproducible example of the bug is documented.
Thank you guys for your work!

**Comment by seibert** [comment]
I actually don't use WingIDE.  I was just transcribing a bug report from the mailing list to Github in the initial report.  If things look good for you, I think it is safe to declare this issue resolved.

Thanks for the verification!
