### ISSUE TITLE
New logo 

### ISSUE THREAD

**Issue by VictoriaODell** [numba/numba#1558]
<img width="399" alt="screen shot 2015-12-01 at 9 36 21 am" src="https://cloud.githubusercontent.com/assets/10767430/11512486/e402af52-9833-11e5-92cd-2577371fd851.png">

Previous attempts to do a logo for Numba were [unsuccessful](https://github.com/numba/numba/issues/254). 

@goanpeca: However, a new logo would give the "project a sense of identity" and can help the project become "more identifiable in the community"

@seibert: "the simplest idea to capture is 'Make Python go fast'." The previous [attempt](https://github.com/numba/numba/issues/254) "focused on the code translation, which is the technique, rather than the goal, which is speed"

**Comment by ahmadia** [comment]
Also cc @jaseg - who had some initial suggestions on the last go-around :)

**Comment by goanpeca** [comment]
I would add a word to what @seibert said and is..

>Make **Easy** for Python to go fast

Cause Numba is easier to use that, lets say, Cython

**Comment by electronwill** [comment]
This 2013 blog post comparing Numba and Cython was very helpful to my understanding of Numba. The highest level overview might be, it makes Python programs for number crunching and scientific computing faster. https://jakevdp.github.io/blog/2013/06/15/numba-vs-cython-take-2/

Stan jokingly suggested a snake riding a rocket for the idea of "faster Python", and I jokingly suggested having it wear a lab coat to indicate scientific computing. Maybe we could have a snake riding downhill in a race car or a roller skate instead to indicate speed.

A more detailed explanation of Numba would be that programmers can use the 'autojit' function to automatically use just-in-time (jit) compilation to make their code much faster, and this requires very little time or effort from the programmers, as well.

**Comment by pitrou** [comment]
So basically we need some kind of snake on steroids...

**Comment by VictoriaODell** [comment]
Dumping other open source logos for inspo and insight. 
<img width="161" alt="screen shot 2015-12-01 at 2 29 46 pm" src="https://cloud.githubusercontent.com/assets/10767430/11513314/00cd8978-9838-11e5-83cf-a92d873a3460.png">
<img width="190" alt="screen shot 2015-12-01 at 2 29 43 pm" src="https://cloud.githubusercontent.com/assets/10767430/11513315/00f8e3a2-9838-11e5-951b-bd80c83db124.png">
<img width="342" alt="screen shot 2015-12-01 at 2 29 39 pm" src="https://cloud.githubusercontent.com/assets/10767430/11513316/00fd2692-9838-11e5-991c-31dffe4a8efd.png">
<img width="552" alt="screen shot 2015-12-01 at 2 29 33 pm" src="https://cloud.githubusercontent.com/assets/10767430/11513318/010263aa-9838-11e5-8bbb-82b5a516ba9a.png">
<img width="823" alt="screen shot 2015-12-01 at 2 29 27 pm" src="https://cloud.githubusercontent.com/assets/10767430/11513317/00fedda2-9838-11e5-8b73-ef30eb34c31f.png">

**Comment by goanpeca** [comment]
We need Quetzalcoatl :-)

**Comment by seibert** [comment]
Most importantly, @VictoriaODell suggested an emoji mockup of a logo:

🐍💨

I think this captures the idea nicely.  :)

**Comment by goanpeca** [comment]
A farting snake :laughing:!

**Comment by electronwill** [comment]
@ahmadia helpfully mentioned his own 2013 blog posts on Numba, which help give an idea of what it does and how to use it. https://www.wakari.io/sharing/bundle/aron/numbapost https://www.wakari.io/sharing/bundle/aron/Accelerating_Python_Libraries_with_Numba_-_Part_2

**Comment by ml31415** [comment]
Have you considered to launch a competition for the logo at 99designs? I recently had fairly well experience with this, and also other tech startups like Docker refered to their services. In the end, we're programmers, graphics are usually not our main competence...

**Comment by seibert** [comment]
We have in-house graphics design expertise to help us now (yay, @VictoriaODell!), so we'll be looking to create a logo over the summer.

(Speaking personally, I'm also not a big fan of art contests.)

**Comment by VictoriaODell** [comment]
Hey~

Recently had a conversation with Michele. I'll be meeting with a couple of different project leads that need logos or updates and we'll work on coming up with a detailed design brief. From there we will decide what the best course of action for execution are. :)

**Comment by seibert** [comment]
New logo is live on the website.  Thanks @VictoriaODell!

**Comment by ml31415** [comment]
Congrats, looks good!
