### ISSUE TITLE
Consolidate array methods testing

### ISSUE THREAD

**Issue by sklam** [numba/numba#1562]
Test for various array methods are scatter across two files: : test_array_methods and test_array_manipulation.  We should consolidate them.

**Comment by pitrou** [comment]
Hmm, the point of splitting them was to make the test modules more readable (and also shorter to run when run individually).

**Comment by sklam** [comment]
Clarify: consolidate testing of the same array method into one place.  We are testing reshape, for example, in both file.

**Comment by pitrou** [comment]
Ah, right, sorry for the misunderstanding.
