### ISSUE TITLE
Support dtype=np.complex in np.zeros

### ISSUE THREAD

**Issue by MatthieuDartiailh** [numba/numba#1563]
The following code crashes : 
```python
import numpy as np
from numba import njit

@njit
def build_array(N):
    return np.zeros((2*N, 2*N), dtype=np.complex)

```
with the following error : 
Failed at nopython (nopython frontend)
                       Invalid usage of Function(<built-in function zeros>) with parameters ((int64 x 2), Function(<type 'complex'>))
                        * parameterized

I can work around that by doing : 
```python
@njit
def build_array(N):
    return 1j*np.zeros((2*N, 2*N))
```

But this is not super intuitive. 

This is on windows 10 x64 python 2.7.10 numpy 1.9 numba 0.22.1

**Comment by pitrou** [comment]
Just use `np.complex128`. `np.complex` is an alias to the built-in `complex` type.

**Comment by MatthieuDartiailh** [comment]
It does work ! Thanks
