### ISSUE TITLE
directory permission problem with static_temp_directory()

### ISSUE THREAD

**Issue by sklam** [numba/numba#1586]
The `static_temp_directory ` function in https://github.com/numba/numba/blame/620552284060ed5fe607b58c3fdee0993a39c6b0/numba/tests/support.py#L367-L380
creates a directory with a fixed name in `/tmp/<tempname>` in linux.  If the directory already exist when the function is called, it returns the existing directory without checking for permission.  It may result in error later like:

```
======================================================================
ERROR: test_pycc_bitcode (numba.tests.test_pycc.TestLegacyAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sklam/dev/numba/numba/tests/test_pycc.py", line 122, in test_pycc_bitcode
    os.unlink(bitcode_modulename)
PermissionError: [Errno 13] Permission denied: '/tmp/test_pycc/test_bitcode_legacy.bc'
```

The error is due to a pre-existing directory existed but it is owned by another user with permission 0775.

(CC @gmarkall )

**Comment by pitrou** [comment]
Surely we could add the current user id to the directory name.

**Comment by seibert** [comment]
Seems like this would be the best solution to avoid any weird race condition with parallel tests by the same user (like multiple build workers):

https://docs.python.org/3.5/library/tempfile.html#tempfile.mkdtemp

**Comment by pitrou** [comment]
No, we must re-use a well-known directory if we want to avoid proliferation of temporary directories on build machines.
