### ISSUE TITLE
struct performance very poor

### ISSUE THREAD

**Issue by d1manson** [numba/numba#1589]
```python
# python 2.7 32bit, windows 10
import numpy as np # version 1.10.1
import numba # version 0.22.1

numba.jit(nopython=True)
def sum_basic_array(a):
    ret = 0
    for aa in a:
        ret += aa
    return ret

numba.jit(nopython=True)
def sum_struct_array(a):
    ret = 0
    for aa in a:
        ret += aa['sub_0'] # or equally slow aa[0]
    return ret

x_basic = np.arange(2000*3, dtype=np.uint32)
x_struct = x_basic.view(dtype=np.dtype([('sub_0', np.int32),
                                        ('sub_1', np.float64)]))


%timeit sum_basic_array(x_basic) # 1.5ms
%timeit sum_struct_array(x_struct) # 22.0 ms
```

Both functions in the above code loop over the same chunk of data in memory, with the `sum_struct_array` version actually having 1/3 of the number of iterations (and using 1/3 of the actual data, although that's unlikely to be of much help).  However the struct version takes about 15x longer.

Is there another syntax I should be using to achieve the same result or is this simply something that hasn't been properly optimized for?

**Edit:** shortly after posting this I realized that the answer is to do some manual loop-invariant code motion:

```python
numba.jit(nopython=True)
def sum_struct_array2(a):
    ret = 0
    sub_0 = a['sub_0']
    for aa in sub_0:
        ret += aa 
    return ret
%timeit sum_struct_array2(x_struct) # 0.4ms
```

So, this version is indeed about 3x faster than the basic sum (and 45x faster than the naive struct version).  I guess that's the approach I will use for now, but surely numba could do this optimization automatically?  If not, then it's not really that helpful offering to support struct array types because you might as well just require that the caller passes each sub-view as a separate argument.

**Comment by pitrou** [comment]
Did you forget the `@` before `numba.jit` or is it just a copy/paste bug?

**Comment by pitrou** [comment]
Note that I can't reproduce here: `sum_struct_array` is actually faster, probably due to the fact there are less array elements to sum.

**Comment by d1manson** [comment]
OOOPS!

**Comment by d1manson** [comment]
Massive apologies for being such an idiot!  I've updated the title and the description.
