### ISSUE TITLE
Bug in box/unboxing of lists in JIT mode

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#1594]
This is the track the following. It appears that the use of lists in JITed functions is reliant on a boxing/unboxing mechanism that is not numerically consistent or safe.

Example:
```
import numpy as np
import numba as nb

d1=list([np.float64(1),np.float32(2),np.int64(3),np.complex128(4+5j)])
d2=list([np.complex128(4+5j),np.float64(1),np.float32(2),np.int64(3)])

def foo(items):
    acc = 0
    for k in items:
        acc = acc + k
    return (acc, items)

@nb.jit
def foo_jit(items):
    acc = 0
    for k in items:
        acc = acc + k
    return (acc, items)

def run(case, f, fjit, v):
    print("__Case ",case,"__\nInput:",v)
    print("\nWithout JIT:\nResult:", f(v), "\nInput vector: ", v)
    print("\nWith JIT:\nResult:", fjit(v), "\nInput vector: ", v, "\n")

run(1, foo, foo_jit, d1)
run(2, foo, foo_jit, d2)
```
Gives output:
```
$ python bug.py 
__Case  1 __
Input: [1.0, 2.0, 3, (4+5j)]

Without JIT:
Result: ((10+5j), [1.0, 2.0, 3, (4+5j)]) 
Input vector:  [1.0, 2.0, 3, (4+5j)]
bug2.py:23: ComplexWarning: Casting complex values to real discards the imaginary part
  print("\nWith JIT:\nResult:", fjit(v), "\nInput vector: ", v, "\n")

With JIT:
Result: (10.0, [1.0, 2.0, 3.0, 4.0]) 
Input vector:  [1.0, 2.0, 3.0, 4.0] 

__Case  2 __
Input: [(4+5j), 1.0, 2.0, 3]

Without JIT:
Result: ((10+5j), [(4+5j), 1.0, 2.0, 3]) 
Input vector:  [(4+5j), 1.0, 2.0, 3]

With JIT:
Result: ((10+5j), [(4+5j), (1+0j), (2+0j), (3+0j)]) 
Input vector:  [(4+5j), (1+0j), (2+0j), (3+0j)] 
```

It would appear that the lists, when used in the JITed functions, are considered homogeneous in the type of the first element in the list. This leads to unfortunate casting in the first case where a complex value has its imaginary part truncated (and the runtime warns). In the second case the first element is a `complex128` type and therefore all casts are safe in both domain and precision, although not necessarily desirable for performance. In the first case, due to the incorrect interpretation of the list the function returns an incorrect result. Further the JITed code is mutating an argument (the list) and it probably shouldn't be doing so as there are no stores made to the list in the function.

**Comment by ma-ba** [comment]
Issue #1544 deals with the first part, i.e. casting of elements and limitation to homogeneous lists. Also, the docs, namely "Build-in types / list"  in `pysupported.rst`, currently do not state the limitation to homogeneous types and need to be updated.

The second part, i.e. the parameter being mutated, is even worse. Here is a smaller example:
```python
from numba import njit

def is_homogeneous(items):
  return all(isinstance(x, type(items[0])) for x in items)

def do_nothing(items):
  return

d = [1, 2.0, (1+0j)]
assert not is_homogeneous(d)
do_nothing(d)
assert not is_homogeneous(d)
njit()(do_nothing)(d)
assert not is_homogeneous(d)  # throws "TypeError: can't convert complex to int"
assert not is_homogeneous(d)  # throws "AssertionError"
```

**Comment by pitrou** [comment]
PR #1605 fixes this issue by enforcing all lists to be homogenous.

**Comment by pitrou** [comment]
Oops, sorry, I closed this by mistake while the PR isn't merged yet.
