### ISSUE TITLE
Using math.degrees much slower than numpy.degrees inside jitted function

### ISSUE THREAD

**Issue by williamjshipman** [numba/numba#1617]
This is related to my previous issue. The math.degrees and math.radians functions get inlined in the generated assembler code, but are 3~4 times slower than the numpy.* equivalents that don't get inlined.

The code can be found here: [https://bitbucket.org/williamjshipman/pythonlearning/src/b27b2d51e458b31b92d10dffbb06636c62d6d04e/NumPyFuncsSpeedInNumba/?at=master](https://bitbucket.org/williamjshipman/pythonlearning/src/b27b2d51e458b31b92d10dffbb06636c62d6d04e/NumPyFuncsSpeedInNumba/?at=master)

Results are in the output folder.

The original mailing list post: [https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/zto-dKXat1w/hbQSYYn1BgAJ](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/zto-dKXat1w/hbQSYYn1BgAJ)

**Comment by seibert** [comment]
This may be fixed on Numba master now.  We rewrote the implementation of these inline functions to eliminate a floating point division, which would have made them quite a bit slower than any well-written implementation.

**Comment by pitrou** [comment]
Closing as fixed now. Thank you for the report!
