### ISSUE TITLE
np.dot does not work in nopython mode

### ISSUE THREAD

**Issue by arthurmensch** [numba/numba#1618]
This is probably not a bug, but I believe there is a lack of documentation on this point : np.dot does not seem to work in nopython mode, despite it being mentionned as a feature in the doc. 

Code :
```python
@jit('f8[:, :](f8[:, :], f8[:, :])', nopython=True)
def jit_mult(A, B):
    m, n = A.shape
    n, k = B.shape
    C = np.empty((m, k))
    return np.dot(A, B, C)

jit_mult(A, B)
```

fails with the error : 
```
UntypedAttributeError: Failed at nopython (nopython frontend)
Unknown attribute "dot" of type Module(<module 'numpy' from '/opt/anaconda/envs/main/lib/python3.5/site-packages/numpy/__init__.py'>)
```

Is this expected ? If it is, what is the recommedned way to perform matrix multiplication inside a nopython function ?

**Comment by pitrou** [comment]
`np.dot` is supported in the next release (which should come out in a few days at most). What you read was probably the docs for the development version ;-)

**Comment by mhlr** [comment]
I am seeing this error in a current anaconda install (numba-0.36.2)
