### ISSUE TITLE
Test selection doesn't always work

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1625]
Try `./runtests.py -l numba.cuda` or `./runtests.py -l numba.tests.npyufunc` and you'll see the selection is not respected: all tests are selected.

**Comment by pitrou** [comment]
@stefanseefeld

**Comment by stefanseefeld** [comment]
https://github.com/numba/numba/pull/1623 contains a fix for the above. With this, 

  `./runtests.py -l numba.cuda`

will report 0 tests (it won't search recursively), while

  `./runtests.py -l numba.tests.npyufunc`

reports 76 tests.

**Comment by pitrou** [comment]
Hmm... I've merged the PR, but I notice the behaviour is actually confusing and slightly unhelpful:

```
$ ./runtests.py -l numba.cuda | wc -l
1
```
(meaning there's no obvious way to run just the CUDA tests?)

```
$ ./runtests.py -l numba.tests | grep cuda | wc -l
315
```
(why are the CUDA tests selected while they're not under numba.tests?)

```
$ ./runtests.py -l 
0 tests found
```
(how do I run the whole test suite?)

**Comment by stefanseefeld** [comment]
That's indeed a point that has changed (had to change, to make this work with the least surprising UI, and to eventually enable us to use this test infrastructure in other projects, with other test suites). 
You have to specify a test suite explicitly. To list the entire test suite:

    $ ./runtests.py -l numba.tests

To list only the cuda test suite (which is located in a separate directory):

    $ ./runtests.py -l numba.cuda.tests

(Note that, even though the cuda tests are located elsewhere, the main test suite includes it.)

**Comment by pitrou** [comment]
Ok, closing now that it has been fixed.
