### ISSUE TITLE
xrange does not work on Python 2.7

### ISSUE THREAD

**Issue by seibert** [numba/numba#1627]
From mailing list:

"I recently encountered a problem when upgrading from numba0.22.1 to numba0.23.0 : the function xrange is not recognize.

This error arises for instance in the simple code below:"

``` python
import numba

@numba.jit(nopython=True)
def test():
    s = 0
    for i in xrange(2):
        s += i
    return(s)

if __name__=='__main__':
    print test()
```

**Comment by tinecidy627** [comment]
+1
