### ISSUE TITLE
numpy.random.binomial fails

### ISSUE THREAD

**Issue by deanpa** [numba/numba#1640]
numpy.random.binomial(n, p) does not complete the task when 'n' is large. For example, numpy.random.binomial(1600, 0.4) will not finish. Here is a trial script:

import numpy as np
from numba import jit
 
@jit
def testBinom(n, d):
    """
    random binomial test
    """
    for i in range(n):
        d_i = d[i]
        e = np.random.binomial(d_i, .4)
        print(d_i, e)
    return e
 
d = np.arange(1000, 1600, dtype = int)
n = len(d)
e = testBinom(n, d)
print('e', e)

**Comment by seibert** [comment]
This script seems to work fine on my system using an almost current version of Numba master.   What version of Numba are you using?

(Note that this example code will be compiled in object mode because of the `print` call.)

**Comment by jcrist** [comment]
On my mac, using the latest release:

```python
In [1]: import numpy as np

In [2]: import numba as nb

In [3]: @nb.jit
def foo(n, p):
    return np.random.binomial(n, p)
   ...:

In [4]: foo(1458, 0.4)
Out[4]: 564

In [5]: foo(1459, 0.4)
<stalls>
```

**Comment by deanpa** [comment]
Thanks for the very prompt reply. I am on Numba 0.23.0.

**Comment by deanpa** [comment]
I also stall at 1459 like jcrist.

**Comment by seibert** [comment]
OK, Jim's script locks up for me on my Mac.  Here it is reformatted without the prompt text for people who want to copy-paste:
``` python
import numpy as np
import numba as nb

@nb.jit
def foo(n, p):
    return np.random.binomial(n, p)

print foo(1458, 0.4)
print foo(1459, 0.4)
```

**Comment by seibert** [comment]
LLDB shows me that when it it is stalled, the code is running around in a loop near this fragment of code (apologies for the x86 assembly, but that's all we have in JIT code):
```
(lldb) disassemble --frame
->  0x1053db5f5: mulsd  %xmm2, %xmm3
    0x1053db5f9: ucomisd %xmm6, %xmm3
    0x1053db5fd: jne    0x1053db606
    0x1053db5ff: jp     0x1053db606
    0x1053db601: jmp    0x1053db72e
    0x1053db606: cvtsi2sdq %rdx, %xmm4
    0x1053db60b: mulsd  %xmm8, %xmm4
    0x1053db610: mulsd  %xmm1, %xmm4
    0x1053db614: repne
```

I'm not very good at using LLDB, but if I `NUMBA_DUMP_ASSEMBLY=1`, then I can match and locate the rest of the assembly:
``` asm
LBB2_16:
	ucomisd	%xmm0, %xmm1
	jae	LBB2_17
	incq	%rdx
	cvtsi2sdq	%rdx, %xmm2
	movaps	%xmm7, %xmm3
	mulsd	%xmm2, %xmm3 /* Above Fragment starts here */
	ucomisd	%xmm6, %xmm3
	jne	LBB2_15
	jp	LBB2_15
	jmp	LBB2_37
LBB2_15:
	cvtsi2sdq	%rcx, %xmm4
	mulsd	%xmm8, %xmm4
	mulsd	%xmm1, %xmm4
	subsd	%xmm1, %xmm0
	divsd	%xmm3, %xmm4
	decq	%rcx
	ucomisd	%xmm2, %xmm5
	movapd	%xmm4, %xmm1
	jae	LBB2_16
	jmp	LBB2_28
```
As near as I can tell, we are running around this loop forever.

**Comment by deanpa** [comment]
Brute force work-around on my system:

import numpy as np
import numba as nb

@nb.jit
def foo(n, p):
    d = 0
    for i in range(n):
        d += np.random.binomial(1, p)
    return d

print(foo(1458, 0.4))
print(foo(1459, 0.4))

**Comment by seibert** [comment]
OK, part of the answer is in the comments of the implementation:

https://github.com/numba/numba/blob/de51861a51e4aafbf0a5920ab9678dfdc10e9577/numba/targets/randomimpl.py#L754-L780

For very large `n`, `(1 - p) ** n` underflows to zero, and the loop will basically never accept a value.  However, if you fall out of the loop, then there is no explicit return value, and I don't know what happens.

So there are a few things to do:
* We should use "BTPE" for n*p >= 30, like NumPy, to avoid the underflow problem
* Should the compiler have caught the situation that there was a code path that exited this function without returning a value?  Can we fix that?
