### ISSUE TITLE
JIT class: Unknown attribute "array" of type Module(<module 'numpy' from ...

### ISSUE THREAD

**Issue by davidbrochart** [numba/numba#1646]
With numba v0.23.0, the following code:

``` python
from numba import jitclass, int32, float32
import numpy as np

spec = [
        ('x', float32[:]),
        ]

@jitclass(spec)
class Test:
    def __init__(self, x):
        self.x = np.array(x, dtype = float32)

t = Test([1, 2, 3])
```

gives the following error:

```
numba.errors.UntypedAttributeError: Failed at nopython (nopython frontend)
Failed at nopython (nopython frontend)
Unknown attribute "array" of type Module(<module 'numpy' from '/home/david/anaconda3/lib/python3.4/site-packages/numpy/__init__.py'>)
```

**Comment by seibert** [comment]
Since you are calling the numpy.array() function, the dtype argument needs to be a dtype that numpy understands, so np.float32, not the the float32 type imported from the numba module.

**Comment by davidbrochart** [comment]
```python
@jitclass(spec)
class Test:
    def __init__(self, x):
        self.x = np.array(x, dtype = np.float32)
```

gives the same error. Anyway, is numba's float32 the same as numpy's float32?
Not setting dtype gives the same error also.

**Comment by moble** [comment]
I'm having the same trouble.  Any resolution or workaround for this problem yet?

**Comment by moble** [comment]
It looks like it's not possible to use numpy's automatic conversion capabilities (where `x` could be a list, or have the wrong dtype, or whatever).  But if you are willing to input only a float of dtype `float32`, you can make it work:

```python
@jitclass(spec)
class Test:
    def __init__(self, x):
        self.x = x.copy()

t = Test(np.array([1.0, 2.0, 3.0], dtype=np.float32))
```

You could have a non-numba wrapper like this:

```python
def make_Test(x):
    return Test(np.array(x, dtype=np.float32))

t = make_Test([1.0, 2.0, 3.0])
```

And if you don't just want a straight copy of something, it looks like you have to construct the array first, using `np.zeros` or `np.empty`, and then fill the values as needed.

Of course, I guess there should be a more informative error.

**Comment by moble** [comment]
The example at the top of this issue now works.  Are you satisfied @davidbrochart?

**Comment by davidbrochart** [comment]
Yes, thanks!
