### ISSUE TITLE
Linear algebra support

### ISSUE THREAD

**Issue by MatthieuDartiailh** [numba/numba#1649]
Hi,

Support of np.dot open the road to support more linear algebra function using either BLAS or LAPACK. I am personally interested in seeing support numpy.linalg.inv and I am willing to work on this and make a pull request.
Looking at the implementation of np.dot, the first step in that direction would be to add the necessary LAPACK function to _helperlib.c and _helpermod.c to allow calling those functions from numba. 

Is there interest in the numba team for such support and would you welcome such a PR ? Should I start with extending _helperlib.c manually (or a different file to avoid crowding that one) or would an automatic method based on the function signatures be preferred ?

Best,
Matthieu

**Comment by stuartarchibald** [comment]
Hi Matthieu,

Thanks for your interest in supporting additional `numpy.linalg` functions, we would certainly welcome a PR for them or even for just stub work on such functionality. The PR relating to `dot` https://github.com/numba/numba/pull/1560, is certainly a good place to get ideas about the approach to use. Given that this would be the first LAPACK function exposed, adding it to `_helperlib.c` would be fine. In the future automating this would be good but working out the most efficient way of doing that will be greatly aided by the presence of a few manual entries. Finally, the symbols for any LAPACK functions used (in your case of `inv()`, probably just `[s,d,c,z]gesv`) must be exposed and available from scipy.

Thanks for your input :)

**Comment by MatthieuDartiailh** [comment]
I have opened a PR with my work so far (#1651). But I fear I will need some help about numba internal working.

**Comment by stuartarchibald** [comment]
That's great thanks. I'm going to close this and we'll track/support on #1651 .
