### ISSUE TITLE
User-controllable thread pool limits for parallel target to @vectorize and @guvectorize

### ISSUE THREAD

**Issue by seibert** [numba/numba#1655]
(As requested on the numba-users mailing list.)

Right now we always assume the number of threads for the parallel target is equal to the number of CPUs.  There are plenty of situations where this is not desirable (multiple processes, etc), and so it is important to have some mechanism to limit the number of threads.

At a minimum, it would make sense to check the value of `OMP_NUM_THREADS` at startup, in order to mimic the behavior of other parallel libraries like MKL.  We don't actually use OpenMP's thread pool (though maybe we could someday), but this variable is at least somewhat well known to users who want to control the number of threads.

We may also want an API in Numba to change the number of threads as well.

**Comment by stuartarchibald** [comment]
Environment variable implemented in https://github.com/numba/numba/pull/1932.

**Comment by seibert** [comment]
Fixed by #1932.  (We might further expand things to allow control per call as well.)

**Comment by jzwinck** [comment]
@seibert I agree it would be good to allow control per call; it's also worth noting that recently (at least in Numba 0.34), the thread pool is initialized as soon as you import a module that uses `numba.vectorize(target='parallel')` - even if the decorated function is never called.  That's surprising.

**Comment by jzwinck** [comment]
For reference, #2713 is to make the number of threads controllable at runtime.

**Comment by jcmgray** [comment]
``OMP_NUM_THREADS`` is a very common way of setting the level of thread parallelism in a program. How do people feel about letting ``numba`` check this upon import as well? ``NUMBA_NUM_THREADS`` would of course take precedent if set.
