### ISSUE TITLE
Incredibly strange and serious bug between numba and iPython plotting back end

### ISSUE THREAD

**Issue by FedericoV** [numba/numba#1656]
Hi,

I've ran into the strangest bug I've ever encountered while programming.  I'm still scratching my head.  Somehow, my analytical jacobian wasn't matching my numerical jacobian, but every time I tried restarting my iPython kernel the results changed.

After spending an entire morning checking for weird mistakes in my code, it turns out that setting the matplotlib backend to qt in iPython *in a previous cell* causes the sum function in numba to give the wrong answer.

http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/849cy9p9865x4p0/Bugged_Numba_iPython_1.ipynb?dl=0

http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/7wzzcx05gi67svp/Bugged_Numba_iPython_2.ipynb

http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/301srrbthfxx1d2/Bugged_Numba_iPython_3.ipynb

**Comment by seibert** [comment]
This sounds very, very much like code that is using uninitialized memory.  We will take a look.

**Comment by FedericoV** [comment]
More info.

- The error is always off by a factor of 10.
- If you comment out the %matplotlib qt line, there are no mistakes
- If you invoke the %matplotlib qt line on the same line as you do the calculation, there are no mistakes
- The error is in the multiplication by 0.5 - the squaring is correct.

**Comment by seibert** [comment]
This is very likely to depend on platform and package versions.  If you are using conda, can you paste the output of `conda info` and `conda list`?  If not, can you let us know what architecture, Python version, and NumPy version you are using?

**Comment by pitrou** [comment]
Can you try the workaround mentioned in https://github.com/numba/numba/issues/1569#issuecomment-163159164?

**Comment by pitrou** [comment]
Oops, I mean https://github.com/numba/numba/issues/1569#issuecomment-163176081

**Comment by seibert** [comment]
Oh, right!  I should have remembered the matplotlib/qt connection.

**Comment by FedericoV** [comment]
Manually setting the locale works and removes the bug for me.

**Comment by FedericoV** [comment]
Seibert - if you need it, I can dig up conda/numpy/matplotlib versions.  I use conda for everything except numpy and scipy, which I build myself from source and link to openblas.

**Comment by pitrou** [comment]
@FedericoV, no need for that, it's an LLVM bug. Right now I can't think of a better way to workaround than to ask users to manually override the locale...

**Comment by seibert** [comment]
Unfortunately, since LLVM still has not merged our patch, this means that this will still not be fixed in LLVM 3.7 (which will be used by the next Numba release).  At this point the LLVM 3.8 release candidate 1 was just put out, so I'm hoping we can prod someone into merging this before the final 3.8 release...

**Comment by FedericoV** [comment]
I will just use the inline back-end, it's not a big deal.  It was just the last thing I expected to cause a mismatch between a finite difference jacobian and an analytical one - I was just convinced I made a mistake in the formula.

**Comment by seibert** [comment]
@pitrou: Is there a workaround, or at least a warning we could print to let people know about this issue?

**Comment by pitrou** [comment]
Perhaps... It won't be perfect (as locale is a process-global setting and therefore prone to race conditions), but better than nothing I guess.

**Comment by pitrou** [comment]
I mean we can print a warning, by the way. Setting the locale from a library is actively hostile (even though matplotlib or Qt appears to be doing it).

**Comment by seibert** [comment]
I think we should put an FAQ in the Numba docs, and then put in a warning with a brief explanation and the URL to the FAQ.

**Comment by pitrou** [comment]
One additional possibility is to add the patch as part of our LLVM builds. The bug would still bite users that don't use our binaries, though.

**Comment by seibert** [comment]
It probably makes sense to do both, especially in case someone ignores (or doesn't see) the warning.  I'm all about defense in depth for a bug that results in getting the math silently wrong.

**Comment by pitrou** [comment]
Ok, the runtime detection has been added, and also the patch to our LLVM builds. We can now close this issue.

**Comment by michaelaye** [comment]
Is there an article somewhere for LLVM ignorants like me that explains how the hell matplotlib and/or locale choices can influence numerical results? That seems like 2 independent worlds to me.

**Comment by pitrou** [comment]
It's explained in the reported bug: https://llvm.org/bugs/show_bug.cgi?id=25788

**Comment by michaelaye** [comment]
I don't see any parsing happening in the above linked notebooks?

**Comment by seibert** [comment]
Text parsing happens internally when LLVM IR is being generated and consumed at various stages of the compilation pipeline.

**Comment by seibert** [comment]
Basically, be very afraid of using `atof()` in parsing code.

**Comment by michaelaye** [comment]
ah i see, so that's something about this LLVM magic works basically, thanks! I won't be parsing code anytime soon! Just a scientist happy about numba being almost as fast as Fortran! ;)

**Comment by seibert** [comment]
No prob.  This bug disturbed us as much as it disturbed you.  :)

(I just hope we can find who to poke to get our patch accepted upstream by the LLVM developers.  We have patched our conda package builds of LLVM, but that obvious don't fix it for everyone.)

**Comment by michaelaye** [comment]
I tried to support with my, admittedly small Twitter power, and poked them there.
