### ISSUE TITLE
Request np.ravel() implementation in NoPython mode

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1660]
Thank you and great work!

**Comment by pitrou** [comment]
Do you need the copying behaviour? Otherwise you may try `reshape(-1)` (which according to the Numpy docs is equivalent).

**Comment by pitrou** [comment]
It is true that `ravel()` would guarantee the result is seen as contiguous, though, which `reshape(-1)` would not.

**Comment by nunocalaim** [comment]
I, myself don't need the copying behaviour for now, So I will use reshape(-1) for now! Thank you

**Comment by pitrou** [comment]
Fixed in PR #1509.
