### ISSUE TITLE
Serious bug in numba 0.23.1 prevents numpy recarrays to be used

### ISSUE THREAD

**Issue by DavidLP** [numba/numba#1664]
In numba 0.23.1 the access of recarrays stopped working. 

Example:

```python
from numba import njit
import numpy as np

@njit
def test(a):
    a[0].x = 0

a = np.array([(1.0, )], dtype=[('x', float)]).view(np.recarray)
test(a)
```

Worked fine with numba 0.22.1. But now an exception is thrown:
```python
LoweringError: Internal error:
KeyError: 0
File "tmp.py", line 6 
```

I am using Miniconda Python 2.7 on Windows 7 64-bit.

**Comment by DavidLP** [comment]
The error also occurs under Ubuntu LTS 14.04 and Miniconda Python 2.7

**Comment by synapticarbors** [comment]
I can confirm this bug for the code @DavidLP provided as well as some other simple test cases on OSX using numba 0.23.1 as well.

**Comment by pitrou** [comment]
Uh, this is a regression indeed. In the meantime, a possible workaround is to reverse the lookup order (that is use `a.x[0]` instead of `a[0].x`). Another workaround is to pass the index as an argument (instead of the constant `0`).
