### ISSUE TITLE
how to get intermediate file.ll(LLVM IR)? I  

### ISSUE THREAD

**Issue by chenxinghao** [numba/numba#1666]

**Comment by chenxinghao** [comment]
how to get intermediate file.ll(LLVM IR)?

**Comment by pitrou** [comment]
Hi,
This is not a bug. Please ask this kind of questions on the mailing-list: http://numba.pydata.org/numba-doc/dev/developer/contributing.html#communication

In your case, the answer is http://numba.pydata.org/numba-doc/dev/reference/jit-compilation.html#Dispatcher.inspect_llvm
