### ISSUE TITLE
Improve internal debugging tools

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1670]
Right now there's a scarcity of tools for internal debugging: `TargetContext.debug_print()` only allows printing out a constant string. To debug non-trivial implementations such as `np.linalg.inv()`, it would be nice to enhance printout facilities.

**Comment by pitrou** [comment]
Ping @stuartarchibald

**Comment by stuartarchibald** [comment]
Indeed. `printf()` like functionality would be great! Perhaps some special capability for printing out arrays would be good too as observing intermediaries often aids in debugging more complicated algs.

**Comment by synapticarbors** [comment]
Beyond internal debugging, it would be very useful for the typical Numba user to be able to print formatted strings in nopython mode. I believe currently you can only print single scalar values. My workaround currently is to use CFFI and write a one-off print function in C for the specific formatted string I want to display. For example:

```C
#include <stdio.h>
#include "cutils.h"


void print_iter_update(long int curr_iter, long int tnf, double *coef, double *avcoef) {
    printf("%5ld ", curr_iter);
    for (int f = 0; f < tnf; f++)
        printf("%7.4f ", coef[f]);
    for (int f = 0; f < tnf; f++)
        printf("%7.4f ", avcoef[f]);
    printf("\n");
    fflush(stdout);
}
```

and then call it from a Numba jitted function like:

```python
# gd is a jitclass
print_iter_update(curr_iter, gd.tnf, 
                cutils_ffi.from_buffer(gd.coef),
                cutils_ffi.from_buffer(gd.avcoef))
```

This works but is rather cumbersome. Native support in Numba would be highly desirable.

**Comment by seibert** [comment]
Agreed.  We have discussed adding the ability to re-enter object mode from nopython mode, which would allow us to let the interpreter handle situations like print (which shouldn't be in critical code paths anyway, so we shouldn't bother to compile it).

**Comment by pitrou** [comment]
Note calling the C `printf()` is relatively easy. I have a helper in an upcoming PR.

**Comment by pitrou** [comment]
I was referring to https://github.com/numba/numba/pull/1724/files#diff-76fd867bea758e7aa376d2d50745ca05R693 (example use at https://github.com/numba/numba/pull/1724/files#diff-858fc566b6f4da1cad5bf1402c547e2fR592).

**Comment by stuartarchibald** [comment]
Context managed object mode blocks and `printf` support on the codegen context permit all this. Closing.
