### ISSUE TITLE
Results change if I print them before returning

### ISSUE THREAD

**Issue by pekapa** [numba/numba#1690]
I have a macports version of python-2.7 with llvm-3.6 and the pip version of numba 0.23.1 (everything is up-to-date)

Here is the code I'm using:

```
import pandas as pd
from numba import jit
from numpy import nan, full

@jit
def movingAverage(adj_close, maxMA):
    ma = full([len(adj_close), maxMA], nan, dtype=float64)
    ind = range( 1, len(adj_close)+1 )
    for d in ind:
        m = max( 0, d-maxMA-1)
        adj = adj_close[d-1:m:-1] if (m or d==maxMA+1) else adj_close[d-1::-1]
        cs = adj.cumsum()
        for i in range( len(adj) ):
            ma[d-1][i] = ( cs[i] / (i+1) )
        print ma
    return ma
```
I'm calculating a rolling mean for the input `adj_close` for up to `maxMA` days.

`adj_close` is a array of values, one value per day

I started by creating ma, a holder for the values that are going to be calculated. And work out the vaules for each day individually (note that the first day can only have an average involving 1 day, the second, 2 and so on up to the `maxMA`)

If I input something like `adj_close = array(range(5), dtype=float64)` and `maxMA = 3` get the right answer as follows:

```
array([[  0.,  nan,  nan],
       [  1.,   0.5,  nan],
       [  2.,   1.5,   1.],
       [  3.,   2.5,   2.],
       [  4.,   3.5,   3.]])
```
However, If I take out the `print ma` line, just before the return of my function, it returns only part of the answer:

```
array([[ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [  3.,   2.5,   2.],
       [  4.,   3.5,   3.]])
```

**Comment by pitrou** [comment]
Thank you for the report! This is an actual bug indeed.
