### ISSUE TITLE
DOCS: REQUEST: Add page detailing supported types and UN-supported types?

### ISSUE THREAD

**Issue by nickeubank** [numba/numba#1700]
Hi All,

Any chance of adding a simple table of supported and unsupported objects (for non-object-mode compilation)? There's a start [here](http://numba.pydata.org/numba-doc/0.23.1/reference/pysupported.html), but it's far from complete and a little hard to interpret. For example, no mention of string or set support (which, through experimentation, I've realized aren't supported). 

I think it'd be a nice quick reference, especially so people can keep an eye out for updates!

Thanks!

**Comment by pitrou** [comment]
By definition, things that are not listed there are not supported (unless we forgot to update the docs). I'm not sure what more we could do: listing all existing Python types would be unwieldy, and ultimately pointless.

**Comment by nickeubank** [comment]
OK – some things you don't support are explicitly listed, I guess I thought a slightly more complete list would be helpful. My sense is that it's not quite as clear what is and is not supported as it could be.

**Comment by pitrou** [comment]
We list things we don't support only when as an exception to a larger rule (such as "we support all syntactical constructs except..."). Listing all unsupported features would make a very long list, for no practical benefit.
