### ISSUE TITLE
Support for scipy.stats.distributions?

### ISSUE THREAD

**Issue by twiecki** [numba/numba#1707]
It would be great if distributions would work in `nopython` mode. The scipy implemenations, while flexible, are very slow. Is that at all feasible or would it be better to recode distributions for numpy and jit them?

**Comment by synapticarbors** [comment]
It's not a long term general solution, and there's the potential issue of the GPL license, but I recently got around this issue by using CFFI to wrap Rmath and just posted notes about it a few days ago:

http://nbviewer.jupyter.org/github/synapticarbors/rmath-cffi-example/blob/master/rmath-cffi-example.ipynb

**Comment by twiecki** [comment]
Thanks @synapticarbors, that looks really cool and quite relevant. I suppose it'd be quite simple to provide a numba library wrapping all of `Rmath` and providing python interfaces. Is that something you're considering?

**Comment by synapticarbors** [comment]
I had thought about packaging them up into standalone library, but I haven't started to put anything formal together yet. I imagine it wouldn't be terribly difficult to do just to provide the simple wrapping.

**Comment by twiecki** [comment]
Doesn't scipy.stats just wrap some fortran/c code that you could directly expose via cffi instead of using rmath?

**Comment by synapticarbors** [comment]
When looking through the `scipy.stats` source code, it did not look like the stats functions were as self-contained as Rmath, but it does look some of it comes from the cephes library, so that's a possibility. Actually @Juanlu001 up notes on using cephes from Numba just before I posted my notebook:

http://pybonacci.org/2016/02/07/como-crear-extensiones-en-c-para-python-usando-cffi-y-numba/

Someone with more knowledge of how `scipy.stats` is put together would probably have a better idea if a simple wrapper might be possible.

**Comment by Juanlu001** [comment]
Actually I would say that this change should come from SciPy: there's a mix of f2py, Cython and custom C wrapping code to interface with extensions and replacing that with CFFI would both simplify the work and make more parts of SciPy callable from numba. However, nowadays with CFFI one has to write all the wrappers manually, while in SciPy they have code generators for that. I suggest asking the SciPy devs if they would accept a pull request in this direction provided that we solve the wrapper generation issue too.

**Comment by jaehongyoon** [comment]
@synapticarbors Thanks for the great work. I was trying to implement your code and somehow get a error message saying undefined symbol: pnorm5. Did you have a same experience by any chance? Thank you.

**Comment by jaehongyoon** [comment]
@synapticarbors Nevermind, I was stupid to link the R headers instead of those from Rmath-julia. However, when I try to compile to build_rmath.py as written, due to the "@" symbol in Rmath.h the gcc compiler shoots an error. Anybody resolved this issue?

**Comment by seibert** [comment]
Related to #2109

**Comment by stuartarchibald** [comment]
See "scumba" discussion here: https://github.com/numba/numba/issues/4292

**Comment by stuartarchibald** [comment]
Closing this issue as it's not in scope for Numba itself, see https://github.com/numba/numba-scipy/ for SciPy related requests/support.
