### ISSUE TITLE
cuda for loop issues (skipping an iteration?)

### ISSUE THREAD

**Issue by da-woods** [numba/numba#1716]
Given the simple test code:

```
@cuda.jit("float64(float64)",device=True)
def f(a):
    x = 0
    for n in range(int(a)):
        x = n
    return x
    
@vectorize(["float64(float64)"],target="cuda")
def g(a):
    return f(a)
    
print(g(np.arange(1,5,dtype=np.float64)))
```

I always seen to get ```[ 0.  2.  3.  4.]```. I believe it should give ```[ 0.  1.  2.  3.]```  (as far as I can tell, no higher numbers get skipped).
If I give ```f``` the signature ```"float64(int32)"``` the problem goes away (but for for ```int64``` or ```float64```). If I don't give ```f``` a signature (i.e. ```@cuda.jit(device=True)```) the problem also goes away.

This is using Python 3.4 on 64-bit linux, Numba and LLVMlite versions

```>>> llvmlite._version.get_versions()
{'full': 'cb57c3dc90efd291822e07839caee2cfebfff5d4', 'version': '0.8.0'}```
```numba._version.get_versions()
{'full': '', 'version': '0.23.1-py3.4-linux-x86_64.egg'}```

with llvm-3.6.2 and cuda 7.5. (Numba, LLVMlite and LLVM compiled from source myself). I've not been able to test it on later versions.

**Comment by da-woods** [comment]
As an addendum - I can also fix the problem in all cases by changing the loop line to:

```for n in range(floor(a+0.5)):```

**Comment by gmarkall** [comment]
I can replicate this with the conda-packaged Python 3.4, Numba 0.23.1 and llvmlite 0.8.0, but the problem disappears with llvmlite and Numba master. If you build llvmlite and Numba from master does the issue disappear for you also?

Note that you will need LLVM 3.7 for Numba and llvmlite master.

**Comment by da-woods** [comment]
Yes - I agree. It seems to be fixed in the up-to-date version so I guess you can close the issue. Thanks for looking into it.

(although getting that version built was a bit of a nightmare: LLVMOProfileJIT seems to be skipped in the default build of LLVM. But that's an issue to be dealt with elsewhere I think)
