### ISSUE TITLE
Getting `raise LoweringError(msg, inst.loc) LoweringError: Internal error: AssertionError: ('i1', 'i8')`

### ISSUE THREAD

**Issue by bmer** [numba/numba#1722]
Hi all,

Could you explain what this error means? In particular, is it a "numba error" or is it due to some mistake I've made?

Kind regards,
bmer

**Comment by seibert** [comment]
Is there any more backtrace besides that?

**Comment by bmer** [comment]
```

  File "A:\anaconda\lib\site-packages\numba\lowering.py", line 183, in lower_function_body
    self.lower_block(block)
  File "A:\anaconda\lib\site-packages\numba\lowering.py", line 201, in lower_block
    raise LoweringError(msg, inst.loc)
LoweringError: Internal error:
AssertionError: ('i1', 'i8')
File "line_segment_intersection_test4.py", line 153

Failed at nopython (nopython mode backend)
Internal error:
AssertionError: ('i1', 'i8')
File "line_segment_intersection_test4.py", line 153
--%<-----------------------------------------------------------------

File "line_segment_intersection_test4.py", line 175]
```

Line 153: 
```

        if check_if_line_segments_intersect(a, b, polygon_coords[vi], polygon_coords[(vi + 1)%num_vertices]):
            return True

Line 175:

```
                    if check_if_line_segment_goes_through_polygon(coords_a, coords_b, this_poly_coords):
                        return True
```
```

**Comment by bmer** [comment]
I figured this one out -- it was an error on my part. I had a function which would return a boolean if one if-statement branch was taken, and would return nothing if the other was taken. I am guessing this confused numba as to what type the function had

**Comment by seibert** [comment]
Hmm, our error should be clearer on this.

**Comment by pitrou** [comment]
Thanks for the report! This is an actual bug, see PR #1740.
