### ISSUE TITLE
Support for higher order functions and lambdas

### ISSUE THREAD

**Issue by datnamer** [numba/numba#1730]
This would be very useful to open up a more flexibility with numba.

I understand a major issue is inferring the type of a function passed as an argument.  A solution suggested by @sklam what to explicitly type the function.

However, as shown here: https://github.com/JuliaLang/julia/pull/13412, it doesn't seem to be necessary for the user to manually type functions in order to generate very fast code.  

I wonder if Numba can get some ideas from that PR that would facilitate higher order programming.  

Here are some potential usecases:

https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/YE12tE2dIwY 
https://github.com/QuantEcon/QuantEcon.py/issues/216

@albop @jstac and @oyamad might be interested in this.

@pzwang a numbatoolz facilitated by resolving this issue could  help with this mailing mailing list topic that you participated in: https://groups.google.com/a/continuum.io/forum/#!searchin/blaze-dev/toolz/blaze-dev/4yElecF1URw/2tnKiX0aBgAJ

**Comment by sklam** [comment]
@datnamer, I have questions about the Julia PR and I don't have much experience with it.  Do you know if the example still works (with the same performance) if the functor to `map` is passed as an argument to `foo` in the first example, instead of declaring locally as an anonymous function?

**Comment by sklam** [comment]
In general, Julia has a very different type inference algorithm.  I am starting to study it.  I will see if I can learn something from it.

**Comment by datnamer** [comment]
I'm not sure, but I think so. Its fast enough with non lambda functions that they will be replacing magical vectorization by simply mapping functions over arrays: https://github.com/JuliaLang/julia/issues/8450

It's also being used for fast generator comprehensions.

**Comment by oyamad** [comment]
Has this issue been resolved by #2801?

Also shouldn't the answer to the question "[Can I pass a function as an argument to a jitted function?](http://numba.pydata.org/numba-doc/0.38.0/user/faq.html#can-i-pass-a-function-as-an-argument-to-a-jitted-function)" be "Yes you can" now?

```py
@jit(nopython=True)
def f(g, x):
    return g(x) + g(-x)

@jit(nopython=True)
def my_g_function(x):
    return x

result = f(my_g_function, 1)
```

**Comment by sklam** [comment]
Yes, numba can handle function as an argument now.  [We need to update the FAQ](https://github.com/numba/numba/issues/new).  Closing.

**Comment by sklam** [comment]
Actually, #2801 only handled passing top-level function as argument.  Inner-function/closures/inline-labmdas have minimal support (see https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#inner-function-and-closure).  Please open new issues regarding them for specific use-cases.
