### ISSUE TITLE
Support cache keyword in other decorators than `jit`

### ISSUE THREAD

**Issue by jcrist** [numba/numba#1737]
Currently the `cache` keyword is only available for `jit` functions. It would be nice to be able to cache numba compiled functions from other decorators as well, to help reduce load time.

**Comment by teoliphant** [comment]
Yes, this would be a great thing to have.

**Comment by mcg1969** [comment]
Yeah, this is proving to be a problem for us on a customer project... I would definitely like to know if there are significant technical hurdles that would  prevent this from happening. If so, we'll have to find an alternative approach to our code.

**Comment by seibert** [comment]
@pitrou, @sklam: Can you come up with a plan for how we could do this in the short term?

**Comment by seibert** [comment]
As a temporary workaround, could you encapsulate the logic in a nopython `@jit` function that you call from a guvectorize shell?  Hopefully LLVM will not attempt to inline the function into the gufunc.

**Comment by mcg1969** [comment]
@jcrist said that didn't help, but he might have been doing it wrong.

**Comment by seibert** [comment]
OK, I'll see if @pitrou and @sklam have some suggestions.

**Comment by seibert** [comment]
@sklam is working on a PR for this in #2190

**Comment by seibert** [comment]
Closed as this was implemented.
