### ISSUE TITLE
Standard library support (for the stuff written in c?)

### ISSUE THREAD

**Issue by datnamer** [numba/numba#1751]
IIRC, a fair bit of the standard library is written in C. Would  these parts be amenable to be wrapped with CFFI and usable in numba?

**Comment by pitrou** [comment]
Well, in general, anything written in C can be wrapped with ctypes or cffi. The only restriction is whether Numba supports the function's argument and return types: see http://numba.pydata.org/numba-doc/dev/reference/pysupported.html#cffi

By the way, please ask questions on the mailing-list. The issue tracker is preferred for reporting actual issues. Thanks!

**Comment by datnamer** [comment]
So mypy has a  (growing) statically typed standard library  and a pretty tight type system.

I wonder if at some point in the future Numba can be use to compile full typed mypy code so that we can distribute python programs on the web using web assembly LLVM backend. 

Relevant blogpost: http://mypy-lang.blogspot.com/2012/12/why-mypy-can-be-more-efficient-than.html
