### ISSUE TITLE
Strange Numba behaviour

### ISSUE THREAD

**Issue by nunocalaim** [numba/numba#1753]
I recently installed numba 0.24

I am seeing an error which I never encountered before
```

from numba import njit
@njit
def foo(c):
    @njit
    def bar(i):
        return 2 * i
    return bar(c + 1)
foo(1)
--------
    252             ts = "offset=%d opcode=0x%x opname=%s"
    253             tv = offset, opcode, dis.opname[opcode]
--> 254             raise NotImplementedError(ts % tv)
    255         if info.argsize:
    256             arg = self.read_arg(info.argsize)

NotImplementedError: offset=9 opcode=0x84 opname=MAKE_FUNCTION
```

But if I define bar outside foo then there is no error! Is this intentional? Is this a bug? Was this already in previous versions of numba or did it break only in 0.24?

**Comment by pitrou** [comment]
This was already in previous versions. Basically you can't define a function inside a JITted function.
