### ISSUE TITLE
llvmlite / numba compile: g++: error: unrecognized command line option ‘-Wcovered-switch-default’

### ISSUE THREAD

**Issue by xaverm** [numba/numba#1754]
Trying to compile llvmlite or numba from [https://github.com/numba](https://github.com/numba) I am getting

`g++: error: unrecognized command line option ‘-Wcovered-switch-default’`

any help on how to fix this would be most appreciated. -mark

(I'm sorry not to have realized this issue tracker before also posting to stackoverflow)

**Comment by pitrou** [comment]
Can you explain how you are trying to compile it, and what your system is?

**Comment by xaverm** [comment]
I try to compile with:

1) llvmlite
`python setup.py install --prefix=...testdir...`
2) numba
`pip install -r requirements.txt --install-option="--prefix=...testdir...."`
I don't get beyond any of those

my system is:
distro `openSUSE 13.1 (x86_64)`
kernel `3.11.10-34-desktop`
gcc version: 
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --program-suffix=-4.8 --enable-linux-futex --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.8.1 20130909 [gcc-4_8-branch revision 202388] (SUSE Linux) 

```

Anything else that would be of help?

**Comment by pitrou** [comment]
How was LLVM compiled? What does `llvm-config --cxxflags` say?

**Comment by xaverm** [comment]
llvm comes with the distro and says:
```
~>llvm-config --cxxflags
-I/usr/include  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -ffunction-sections -fdata-sections -O2 -g -DNDEBUG  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

```

**Comment by pitrou** [comment]
Ok, so the flag is what LLVM was compiled with. Probably your distro compiles LLVM with a different compiler than the C++ compiler it provides. You'll have to find out or ask them about that and use the same compiler, probably.

**Comment by pitrou** [comment]
Closing as there's nothing we (llvmlite) can do about that, probably.

**Comment by hughperkins** [comment]
just in case useful, in docker / ubuntu 16.04, following works ok: https://github.com/numba/numba/wiki/Build-0.33-on-ubuntu-16.04

**Comment by Chunde** [comment]
Same issue here, can't install llvmlite, error got:

```
g++: error: unrecognized command line option ‘-stdlib=libc++’
    g++: error: unrecognized command line option ‘-Wcovered-switch-default’
    g++: error: unrecognized command line option ‘-Wstring-conversion’
```

llvm-config --cxxflags:

` -stdlib=libc++  -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -fno-rtti -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
`
