### ISSUE TITLE
Regression concerning optional arguments with NumPy 1.10

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#1755]
I think I have detected a regression in numba 0.24.0 combined with NumPy 1.10: when a function is compiled with a explicit signature using `numba.njit`, optional arguments seem to be treated as `pyobject`.

The resulting args list:

https://travis-ci.org/poliastro/poliastro/jobs/113920659#L391

And the declaration:

https://github.com/Juanlu001/poliastro/blob/1d87f52/src/poliastro/iod/izzo.py#L252-L253

I fixed this by making these parameters non-optional. The error does not appear with numba 0.23. Both Python 3.4 and 3.5, with or without MKL, seem to be affected. I won't have time to provide a proper self-contained test case until next week.

**Comment by pitrou** [comment]
I would recommend you don't pass any explicit signature to `@jit`. Just let Numba do the typing.

**Comment by stuartarchibald** [comment]
I'm unconvinced this is still an issue so am closing. If this is still a problem then please reopen. Thanks.
