### ISSUE TITLE
Add support for as_buffer() to CUDA device allocations

### ISSUE THREAD

**Issue by seibert** [numba/numba#1770]
As proposed on the mailing list, it would be nice for CUDA device allocations to have an `as_buffer()` method, similar to PyCUDA:

https://documen.tician.de/pycuda/driver.html#pycuda.driver.DeviceAllocation.as_buffer

This would allow device allocations to be used outside of Numba.  (For example, possibly with PyCUDA or MPI.)

**Comment by gmarkall** [comment]
I guess this is resolved by the existence of the CUDA Array Interface?

**Comment by gmarkall** [comment]
I think the CUDA Array Interface provides for this requirement.
