### ISSUE TITLE
Numba cache should handle lack of write permissions

### ISSUE THREAD

**Issue by jcrist** [numba/numba#1771]
Currently numba's cache will fail if the user running the code lacks write permission for the directory that code is installed in. This has come up a few times with users installing library code using `sudo`, but then trying to import it with user privileges.

**Comment by seibert** [comment]
At a minimum, we should only produce a warning if a cache file cannot be written.  (In addition, we should then mark the function as uncached, so we don't attempt to repeatedly write cache files on every single call.)

If possible, it would be nice to also define a cache location in the user's home directory that could be used.

**Comment by thoth291** [comment]
Being one of those users who is affected I would like to say that the idea of the cache location - something like environment variable NUMBA_CACHE_DIR - would work perfectly in my case.
Then at my user's bashrc or in my lmod modules or in my batch scripts - I can define local cache and feel safe...

**Comment by pitrou** [comment]
Indeed we could define a fallback location for when the source code directories can't be written to.

**Comment by seibert** [comment]
Also should be clear about which location takes precedence when both are available.

This reminds me, can we have a message that prints (in NUMBA_DEBUG mode only) the full path when a cache file is loaded.  I don't recall if that is present already.

**Comment by thoth291** [comment]
Fallback might be dangerous.
Imagine that sys-admin X with default group XG and default permissions [g+rw, o+r] installs some package which is using numba.
Another user Y with default group YG and default permissions [g+rw, others - not allowed] runs that package for the first time. Assuming that he also belongs to group XG - he creates the cache folder.
Then user Z who belongs to the group XG, but not to the group YG, **can** get the package data, but **can't** get to the cache folder's content...

I had similar situation when I managed python distribution in the system location for a few users...

**Comment by pitrou** [comment]
> Then user Z who belongs to the group XG, but not to the group YG, can get the package data, but can't get to the cache folder's content...

I don't see how that's dangerous. User Z will then use the fallback location for cache files. What would be the problem?

**Comment by pitrou** [comment]
I've submitted a proposed fix in PR #1771.
