### ISSUE TITLE
Numba not compiling due to a constraint error

### ISSUE THREAD

**Issue by bennames** [numba/numba#1794]
I was hoping someone might be able to tell me why the following function is not compiling with nopython mode. I've read through the documentation and can't find anything that would indicate why it's still failing to compile:

```
@jit(nopython=True)
def calcAIC(M,kr,br,delta_x_vec,sweep_vec,l_vec,dihedral_vec,Xr_vec,Xi_vec,Xc_vec,\
    Xo_vec,symxz=False):
    # Initialize the number of panels
    numPan = len(Xr_vec)
    # Initialize the complex [D] matrix
    D = np.zeros((numPan,numPan),dtype=np.complex128)
    # For all the recieving panels
    for i in range(0,numPan):
        # For all the sending panels
        Xr = Xr_vec[i]
        gamma_r = dihedral_vec[i]
        for j in range(0,numPan):
            # Calculate average chord of sending box
            delta_x_j = delta_x_vec[j]
            # Calculate sweep of sending box
            lambda_j = sweep_vec[j]
            # Calculate the length of the doublet line on sending box
            l_j = l_vec[j]
            Xi = Xi_vec[j]
            Xc = Xc_vec[j]
            Xo = Xo_vec[j]
            e = 0.5*l_j*np.cos(lambda_j)
            gamma_s = dihedral_vec[j]
            eta_0 = (Xr[1]-Xc[1])*np.cos(gamma_s)\
                +(Xr[2]-Xc[2])*np.sin(gamma_s)
            zeta_0 = -(Xr[1]-Xc[1])*np.sin(gamma_s)\
                +(Xr[2]-Xc[2])*np.cos(gamma_s)
            r1 = np.sqrt(eta_0**2+zeta_0**2)
            # Calculate the Kernel function at the inboard, middle, and
            # outboard locations
            Ki = K(Xr,Xi,gamma_r,gamma_s,M,br,kr,r1)
            Kc = K(Xr,Xc,gamma_r,gamma_s,M,br,kr,r1)
            Ko = K(Xr,Xo,gamma_r,gamma_s,M,br,kr,r1)
            A = (Ki-2*Kc+Ko)/(2*e**2)
            B = (Ko-Ki)/(2*e)
            C = Kc
            # Determine if planar or non-planar I_ij definition should be used
            if abs(zeta_0)<1e-6:
                I_ij = (eta_0**2*A+eta_0*B+C)*(1./(eta_0-e)-1./(eta_0+e))+\
                    (B/2+eta_0*A)*np.log(((eta_0-e)/(eta_0+e))**2)
            else:
                I_ij = ((eta_0**2-zeta_0**2)*A+eta_0*B+C)*zeta_0**(-1)*\
                    np.arctan(2*e*abs(zeta_0)/(r1**2-e**2))+\
                    (B/2+eta_0*A)*np.log((r1**2-2*eta_0*e+e**2)/\
                    (r1**2+2*eta_0*e+e**2))+2*e*A
            D[i,j]=delta_x_j*np.cos(lambda_j)/(8.*np.pi)*I_ij

            if symxz:
                # Calculate sweep of sending box
                lambda_j = -lambda_j
                # Calculate parameters invloved in aproximate I_ij
                Xi[1] = -Xi[1]
                Xc[1] = -Xc[1]
                Xo[1] = -Xo[1]
                # Sending box dihedral
                gamma_s = -gamma_s
                eta_0 = (Xr[1]-Xc[1])*np.cos(gamma_s)\
                    +(Xr[2]-Xc[2])*np.sin(gamma_s)
                zeta_0 = -(Xr[1]-Xc[1])*np.sin(gamma_s)\
                    +(Xr[2]-Xc[2])*np.cos(gamma_s)
                r1 = np.sqrt(eta_0**2+zeta_0**2)
                Ki = K(Xr,Xi,gamma_r,gamma_s,M,br,kr,r1)
                Kc = K(Xr,Xc,gamma_r,gamma_s,M,br,kr,r1)
                Ko = K(Xr,Xo,gamma_r,gamma_s,M,br,kr,r1)
                A = (Ki-2*Kc+Ko)/(2*e**2)
                B = (Ko-Ki)/(2*e)
                C = Kc
                # Determine if planar or non-planar I_ij definition should be used
                if abs(zeta_0)<1e-6:
                    I_ij = (eta_0**2*A+eta_0*B+C)*(1./(eta_0-e)-1./(eta_0+e))+\
                        (B/2+eta_0*A)*np.log(((eta_0-e)/(eta_0+e))**2)
                else:
                    I_ij = ((eta_0**2-zeta_0**2)*A+eta_0*B+C)*zeta_0**(-1)*\
                        np.arctan(2*e*abs(zeta_0)/(r1**2-e**2))+\
                        (B/2+eta_0*A)*np.log((r1**2-2*eta_0*e+e**2)/\
                        (r1**2+2*eta_0*e+e**2))+2*e*A
                D[i,j]+=delta_x_j*np.cos(lambda_j)/(8.*np.pi)*I_ij
    return D
```

**Comment by seibert** [comment]
(FYI: I edited your comment to insert ``` above and below the code section so it would format better in Github.)

Can you post the error your are getting, or even better, a simple script that calls this function once that generates the error?  Without knowing what the argument types are, it will be hard to figure out what is wrong.

**Comment by bennames** [comment]
Awesome thanks so much. And duh... Here is the error:

'''Traceback (most recent call last):

  File "<ipython-input-1-37ed9c5638a9>", line 1, in <module>
    runfile('E:/Dropbox/Classes/Research/Hephaestus/V_021/AeroComBAT-Project/AeroComBAT-Project/validations/AeroValidation.py', wdir='E:/Dropbox/Classes/Research/Hephaestus/V_021/AeroComBAT-Project/AeroComBAT-Project/validations')

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/Dropbox/Classes/Research/Hephaestus/V_021/AeroComBAT-Project/AeroComBAT-Project/validations/AeroValidation.py", line 131, in <module>
    Xr_vec,Xi_vec,Xc_vec,Xo_vec,symxz=True)

  File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 171, in _compile_for_args
    return self.compile(sig)

  File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 349, in compile
    flags=flags, locals=self.locals)

  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 665, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 366, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)

  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 375, in compile_bytecode
    return self._compile_bytecode()

  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 652, in _compile_bytecode
    return pm.run(self.status)

  File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 251, in run
    raise patched_exception

TypingError: Internal error at <numba.typeinfer.CallConstraint object at 0x000000002E3CA978>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\numba\typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "C:\Anaconda\lib\site-packages\numba\typeinfer.py", line 284, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "C:\Anaconda\lib\site-packages\numba\typeinfer.py", line 311, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "C:\Anaconda\lib\site-packages\numba\typing\context.py", line 123, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "C:\Anaconda\lib\site-packages\numba\types.py", line 424, in get_call_type
    sig = template(context).apply(args, kws)
  File "C:\Anaconda\lib\site-packages\numba\typing\templates.py", line 280, in apply
    assert cases
AssertionError
--%<-----------------------------------------------------------------'''

**Comment by seibert** [comment]
(Note: the code block is delimited with three backticks, not three single quotes.)

OK, unfortunately that error is not explaining what is going on.  Can you tell us what the date types are for your input arguments?

**Comment by bennames** [comment]
Oh duh, thanks again. As you can tell I'm fairly new to GitHub.

Yeah absolutely, sorry about that:

M: float
kr: float
br: float
delta_x_vec: array of float64
sweep_vec: array of float64
l_vec: array of float64
dihedral_vec: array of float64
Xr_vec: array of numpy length 3 arrays ([np.array([0.,0.,0.]),np.array([1.,2.,1.]),np.array([3.,7.,-1.])]
Xi_vec: array of numpy length 3 arrays ([np.array([0.,0.,0.]),np.array([1.,2.,1.]),np.array([3.,7.,-1.])]
Xc_vec: array of numpy length 3 arrays ([np.array([0.,0.,0.]),np.array([1.,2.,1.]),np.array([3.,7.,-1.])]
Xo_vec: array of numpy length 3 arrays ([np.array([0.,0.,0.]),np.array([1.,2.,1.]),np.array([3.,7.,-1.])]
symxz=False (boolean obviously)

For clarities sake, all of the arrays I listed are of the same length.

**Comment by seibert** [comment]
No worries.  I have to use the "Preview" tab a lot to check that I'm using GitHub Markdown syntax properly.  :)

My suspicious is that the type inference is failing because of the `Xr_vec`, `Xi_vec`, `Xc_vec`, and `Xo_vec` arguments.  We do not yet support lists of numpy arrays.  However, Numba should have given you an actual error in the traceback to let you know what the problem was.

As a workaround in the meantime, is there any reason you can't convert those 4 arguments into 2D arrays?

**Comment by bennames** [comment]
Hmm... I converted ```Xr_vec```, ```Xi_vec```, ```Xc_vec```, and ```Xo_vec``` to purely 2D numpy arrays and that doesn't seem to have done the trick. Any other suggestions? Got any suggestions on how I can try debugging it myself such as getting more verbose error messages?

**Comment by seibert** [comment]
You can try setting some environment variables at the console, like `NUMBA_DEBUG`:

http://numba.pydata.org/numba-doc/latest/reference/envvars.html#debugging

However, I suspect that will flood you with information that may not be relevant or easy to interpret.  Most of the Numba developers are on vacation today, but knowing that the problem still happens with 2D array inputs, we should be able to investigate tomorrow.

**Comment by bennames** [comment]
Awesome thanks so much. I really appreciate all the help. In the mean time I'll keep trying different things.

**Comment by seibert** [comment]
Another thing that might help is breaking up the function body into smaller functions.  We allow LLVM to inline functions, so there isn't typically a performance advantage to having one giant monolithic function if you don't want to.  It looks like your kernel function calculation is copy-pasted in two places, for example.

(Splitting things up also has the advantage of letting you test the functions individually.)

**Comment by bennames** [comment]
Hey so I found the issue. I was using ```np.real()``` and ```np.imag()``` in my kernel function. I wasn't forcing ```nopython=True``` on my kernel function, so I imagine even though I was using the ```@jit``` decorator it was compiling normally. I don't know if that information is useful to you guys in the future bit if so there you go. Thanks for all the help again!

**Comment by seibert** [comment]
Closing and will track the `np.real`/`np.imag` issue in #2590.
