### ISSUE TITLE
'DataFlowAnalysis' object has no attribute 'op_LOAD_CLOSURE'

### ISSUE THREAD

**Issue by shampool** [numba/numba#1809]
```
    self.dispatch(info, inst)
  File "numba/dataflow.py", line 80, in dispatch
    fn = getattr(self, fname)
AttributeError: 'DataFlowAnalysis' object has no attribute 'op_LOAD_CLOSURE'

Failed at object (analyzing bytecode)
'DataFlowAnalysis' object has no attribute 'op_LOAD_CLOSURE'
```

**Comment by shampool** [comment]
I got the above errors when I tried the following code:

`
@jit
def train_lasso(Data,y, thresh_ = 0.000001, eps =0.0000001,lambda_ls = 0.1):
    
    Theta_0 = train_ls(Data, y, lambda_ls)      
    N, L = Data.shape
    @jit
    def get_z(theta_):
        z = np.sqrt(theta_*theta_ + eps)
        return z
    @jit
    def get_theta(z_):
        Z_diag = np.diag(z_/2)
        a = np.dot(Data.T, Data) +  lambda_ls * Z_diag
        b = np.dot(Data.T, y)
        theta = np.linalg.lstsq(a, b)[0] 
        return theta
    this_theta = Theta_0
    while 1:
        tmp = this_theta
        this_z = get_z(this_theta)
        this_theta = get_theta(this_z)
        diff = this_theta - tmp 
        print np.linalg.norm(diff,1)
        if np.linalg.norm(diff,1) < thresh_:
            break
    return this_theta
    
    `

**Comment by pitrou** [comment]
Hi,
The code above wasn't pasted properly: some indentation is bogus.
In any case, the answer here is that closures are not supported by Numba: you cannot declare a function _inside_ a JITted function.
