### ISSUE TITLE
Nested functions compile everytime enclosing function is called

### ISSUE THREAD

**Issue by smurn** [numba/numba#1810]
def outer():
        @jit(nopython=True)
        def inner(a, b):
            return a + b
        return inner(1,1)

Looking at the execution time of `outer`, it looks as if `inner` is recompiled everytime. 
I'm not sure how I can verify this, but if I move the inner loop out of the outer function, I get the same execuction time for the first call (a few hundreds of a sec) but after that it drops to zero. With the code as above, it always stays high. 
I found this issue with a somewhat more complicated function that took a few tens of a sec to compile and had the same behaviour.

numba-0.24.0
cpython 3.4 (amd64)
windows 7

**Comment by pitrou** [comment]
Well, yes, this is by design. If your inner function is not a closure, just put it at the toplevel.

**Comment by smurn** [comment]
Ok. Fair enough. I sometimes like them nested for readability. Since it is easy to check if a function has any closure variables, it would be a nice if numba would detect this to avoid recompilation. Come to think of it, even with closure variables, recompilation would not always be required, right? They essentially become part of the signature.

Anyway, thanks for the clarification!

**Comment by pitrou** [comment]
I'd rather avoid too much magic behaviour. Apart from closure variables there are also the changing values of global variables. Right now the behaviour is simple and easily understood. You can also put up some kind of caching system if you prefer defining nested functions but only want them compiled once; I just don't think there's any point in shipping such a system with Numba.

**Comment by smurn** [comment]
Naa, I prefer to avoid magic behaviour in my code too :) A hint in the documentation would be nice, though.

Having done some work on semi-automatic parallelization for python, I very much appreciate robusness. Numba is so great exactly because it doesn't constantly blow up (unlike my stuff)
