### ISSUE TITLE
How to access characters in string arrays

### ISSUE THREAD

**Issue by gabrielelanaro** [numba/numba#1814]
Hi, I would like to implement a "vectorized" hash map that operates on arrays of strings. To do that I would like to be able to implement a "vectorized" hash function:

```
@jit(nopython=True)
def vectorized_hash(keys):
    hashed_keys = np.zeros(len(keys), dtype='int32') 
    for k in keys:
         # hash function here
     return hashed_keys

keys = np.array(["Li", "Cl", "Li", "Li"])
vectorized_hash(keys)
# That would return a set of hashed values
```

The problem is that, while I can iterate over the strings, I can't iterate over the characters of the strings:

```
Failed at nopython (nopython frontend)
Invalid usage of getiter with parameters ([char x 2])
 * parameterized
File "<ipython-input-764-ce1caada3cb0>", line 4
```

Is there a way to iterate over characters?

**Comment by pitrou** [comment]
This is currently not possible. For that we should add general support for strings in Numba.

**Comment by cristipurdel** [comment]
I am also interested in adding general support for strings.
At least try to use a function that converts {a,e,i,o,u,space,b,c,d} to {1,2,3,4,5,6,7,8,9}
So, when we type any of the 9 characters, a function should generate a number based on the string values: 'ae bi' = int(12673) . As a workaround I find it much better to have at least 9 character support for comparison then not to have at all. If what I'm saying is doable, please make a feature request

**Comment by stuartarchibald** [comment]
As of Numba 0.47.0 this works:
```python
from numba import njit
import numpy as np

@njit
def vectorized_hash(keys):
    hashed_keys = np.zeros(len(keys), dtype=np.int32)
    for k in keys:
         print(k)
    return hashed_keys

keys = np.array(["Li", "Cl", "Li", "Li"])
vectorized_hash(keys)
```
Closing.

**Comment by imadki** [comment]
It doesn't work
