### ISSUE TITLE
pre-pr request: installation instructions

### ISSUE THREAD

**Issue by DSLituiev** [numba/numba#1820]
It took a bit time to figure it out, so I guess it may have value to add these lines to the `README`. 
I can do PR or maybe you  can just add them.

On MacOSX 10.10+
''''''''''''''''
First run (assuming `homebrew` installed):

::
    $ brew install llvm37
    $ export LLVM_CONFIG=/usr/local/opt/llvm37/lib/llvm-3.7/bin/llvm-config

**Comment by pitrou** [comment]
The official supported way to install Numba is to install the `conda` packages. We want to allow people to use other methods but we don't really want to encourage them.

**Comment by indera** [comment]
I have the same issue on RedHat

$ yum search llvm
Installed Packages
Name        : llvm
Arch        : x86_64
Version     : 3.4.2
Release     : 8.el7

$ python --version
Python 3.4.5

$ pip install numba


File "/tmp/pip-build-v85qmsc6/llvmlite/ffi/build.py", line 131, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-v85qmsc6/llvmlite/ffi/build.py", line 94, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config

**Comment by indera** [comment]
Now I have the wrong LLVM

$ sudo yum install llvm-devel.x86_64
$ locate llvm-config

> /etc/alternatives/llvm-config
> /usr/bin/llvm-config
> /usr/bin/llvm-config-64
> /usr/include/llvm/Config/llvm-config-64.h
> /usr/include/llvm/Config/llvm-config.h
> /var/lib/alternatives/llvm-config

$ LLVM_CONFIG=/usr/bin/llvm-config  pip install numba
RuntimeError: Building llvmlite requires LLVM 4.0.x. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

**Comment by seibert** [comment]
Closing in favor of adding pip instructions now that we have wheels: #2586
