### ISSUE TITLE
Add support for shared memory to the CUDA simulator

### ISSUE THREAD

**Issue by seibert** [numba/numba#1837]
CUDA Python kernels which use shared memory will fail if the CUDA simulator is enabled.

Supporting this properly probably also requires solving the syncthreads situation, which is tricky.

**Comment by maedoc** [comment]
(following up from the mailing list post)

It might be a good idea to indicate something to this effect in the docs, where shared mem is listed under the [supported features of the simulator](http://numba.pydata.org/numba-doc/dev/cuda/simulator.html).

What is the resolution required for the syncthreads situation? I didn't find an issue, but I am willing to try to help out.

**Comment by seibert** [comment]
Actually, upon inspection of the simulator code, I realized that it already handles syncthreads properly.  In that case, implementing shared memory is much easier.  @sklam: Ideas on how we would tackle this?

**Comment by maedoc** [comment]
While trying to reproduce the issue with a simple code, I see that it occurs when I split code across modules, e.g. I've got two files:

`numba_cudasim_shared_inner.py`
```python
from numba import cuda, float32
import math

def gen_inner(n, n_iter):
    @cuda.jit(device=True)
    def inner_fn(data):
        ti = cuda.threadIdx.x
        shm = cuda.shared.array((n, ), float32)
        shm[ti] = data[ti]
        for i in range(n_iter):
            shm[ti] = math.sin(shm[ti])
        data[ti] = shm[ti]
    return inner_fn
```

and `numba_cudasim_shared.py`

```python
import numpy
from numba import cuda, float32

from numba_cudasim_shared_inner import gen_inner

def gen_outer(inner):
    @cuda.jit
    def outer_fn(data):
        inner(data)
    return outer_fn


test_data = (numpy.random.rand(32) - 0.5).astype(numpy.float32)
kernel = gen_outer(gen_inner(test_data.shape[0], 100))
kernel[(test_data.shape[0],), (1,)](test_data)
```

which produces a stack trace ending with 

```
  File "numba_cudasim_shared_inner.py", line 8, in inner_fn
    ti = cuda.threadIdx.x
AttributeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: 'module' object has no attribute 'threadIdx'
```

If I place the shared memory declaration line first, in the inner kernel, I see `AttributeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: 'module' object has no attribute 'shared'`.

So, this is in fact an issue with using kernels across multiple modules, because, if I define it all in the same file, it works fine.

**Comment by sklam** [comment]
The code in `numba_cudasim_shared_inner.py` and `numba_cudasim_shared.py` works when they are in a single file.   Shared memory is implemented and worked.

**Comment by sklam** [comment]
I am looking into why it has the attribute error when the files are splitted.

**Comment by shaunc** [comment]
Still seem to get the problem with shared memory in cudasim when kernel split across multiple modules. Is there a workaround (for me the shared memory is in a device function called from various places, so hard to put in one module....)
