### ISSUE TITLE
Numba invalid pointer crash

### ISSUE THREAD

**Issue by alexpyattaev** [numba/numba#1840]
Hi! 
I am using a numba 0.25.0, with llvm  3.7.1-r and llvmlite 0.10.
I have compiled everything without errors on two identical Gentoo machines. On one everything works fine. On the other, the simplest example crashes: 
```
#!/usr/bin/python3.4
from numba import jit

@jit
def test(x):
    return x+5

print(test(5))
```

The crash log is messy, and therefore attached. In general it seems to be some sort of null-pointer dereference issue in LLVM. Any sort of advice on how to fix that would help. Make sure you only open it in a text editor you know will not crash due to messy control symbols.

[crash_log.txt](https://github.com/numba/numba/files/228248/out.txt)

I have tried so far:
- Other test examples - same issue
- Rebuilding LLVM and Python and numpy and every single package connected to Python - no effect
- Praying to gods, blood sacrifice - no effect...

Happy to provide more info.

**Comment by pitrou** [comment]
Indeed it seems crash inside LLVM. We have never witnessed this, so I'm assuming there is a problem in your compiled LLVM package. I would suggest you use our pre-compiled binaries, at least for llvmlite: http://llvmlite.pydata.org/en/latest/install/index.html#pre-built-binaries

**Comment by alexpyattaev** [comment]
Well the LLVM itself passes its own self-test process, which seems to be comprehensive. I'll try to rebuild the entire LLVM chain again with a different GCC, see if that changes anything.

**Comment by alexpyattaev** [comment]
WOW it seems to have been a GCC issue. **More specifically, x86_64-pc-linux-gnu-4.9.3 seems to be broken in some way.** 

Anyway, the issue does not persist after **rebuilding  llvm libffi clang and llvmlite with new GCC-5.3.0**. Hope this helps somehow.
