### ISSUE TITLE
Compilation of recursive function fails with `nopython=True`

### ISSUE THREAD

**Issue by forman** [numba/numba#1845]
Hi,

Compilation of recursive functions seem to fail reproducibly if `nopython=True`:

```
>>> @jit(nopython=True)
... def recursive_sum(a):
...     if a.size == 1:
...         return a[0]
...     else:
...         return a[0] + recursive_sum(a[1:])
...
>>> recursive_sum(np.array([1,2,3]))
```

Results in an AssertionError, see attached [Traceback.txt](https://github.com/numba/numba/files/232342/Traceback.txt)

**Comment by seibert** [comment]
Support for recursion is on our todo list.

**Comment by datnamer** [comment]
@seibert does that include general higher order programming and functions like map/reduce, or is there something special about a function calling itself?

**Comment by seibert** [comment]
We just need to be sure we handle the type inference properly.  General recursion (when the type signature of recursive calls could be different than the initial call, or you have mutual recursion between two functions) can make this tricky for the type unification implementation we have.  Short term, I think we'll fix it for direct recursion with a fixed type signature first, then worry about the more general cases.

**Comment by seibert** [comment]
Closing since Numba now supports recursion of the form described.
