### ISSUE TITLE
Print support in nopython mode

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#1848]
Jumping on this from the discussion list:

https://groups.google.com/a/continuum.io/d/msg/numba-users/-oqsIRkWZfA/tjK7o0UcAgAJ

Having a print function in nopython mode would be one of my most requested features as of late. As I've written some pretty complex algorithms using numba that use jitclasses and also call down through about a dozen numba jitted functions, debugging has gotten hairy.

I'd request:
- `printf` like functionality that would allow you to print formatted strings that are a mix of characters, integers and floats. This could use old-style python string formatting or new style `.format()` style. Either would be great.
- Basic printing of numpy arrays, although if I had the above bullet item, I could assemble the printing code myself. 

Currently I do something like `print(111111)` and then print one or more scalar variables that I need to look at in a nopython function. The `print(111111)` is just abusing integer printing to have a marker to identify where the print statement originated from if I'm printing in multiple functions. Then I `print(22222)`, `print(33333)`, etc. to mark other places. 

In some instances I've even gone as far as to use cffi to create a C function that calls `printf` to get nice formatting, but that is cumbersome.

**Comment by seibert** [comment]
I think we want the general capability to enter object mode from inside a nopython mode function (reacquire the GIL, rewrap values in Python objects, etc) in order to support things like real print statements.  Since print should never be part of a critical code path, we don't have to worry about performance.

**Comment by synapticarbors** [comment]
Being able to enter object mode from inside a nopython mode function would be useful and would more generally solve the problem. I'm not sure how difficult this is going to be to implement or on what time scale the devs think the capability will be added. If it is challenging compared to just exposing some minimally wrapped version `printf` that allows the printing of formatted strings from within numba, I'd prefer to see the latter as a stop gap measure until the general solution is implemented.

**Comment by seibert** [comment]
Yeah, our plan here is to do the minimal thing for print (functions that can't mutate their arguments or return values are easier), and then see about generalizing it later.

**Comment by fingoldo** [comment]
Hello, is percent style print formatting supported? Or which one is supported? Or when is it planned to start supporting? )

**Comment by RemyLau** [comment]
> Hello, is percent style print formatting supported? Or which one is supported? Or when is it planned to start supporting? )

Having the same issue, tried percent style print formatting and is not supported for njit.
