### ISSUE TITLE
Numba nopython mode returns incorrect results

### ISSUE THREAD

**Issue by fjanoos** [numba/numba#1850]
Python version: '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
Numba version: 0.25.0

I'm experiencing some errors with numba - below is an MRE.

This code (without jit) 

```python
from pylab import *
from numba import jit

mktarr = array([86])
styarr = array([100]);
indarr = array([150])
# @jit(nopython=True, nogil=True)
def factor_type(x):
    for a in mktarr:
        if x == a: 
            return 0
    for a in styarr:
        if x == a: 
            return 1
    for a in indarr:
        if x == a: 
            return 2
    return -1
factor_type( 86 )
```
returns as expected:
`0`

but
```python
@jit(nopython=True, nogil=True)
def factor_type(x):
    for a in mktarr:
        if x == a: 
            return 0
    for a in styarr:
        if x == a: 
            return 1
    for a in indarr:
        if x == a: 
            return 2
    return -1
factor_type( 86 )
```
returns `-1`. This problem persists with or without nopython.

Any suggestions ?

**Comment by sklam** [comment]
Something went wrong in the lowering of the constant array.

The ``mktarr`` is initialized as:

```llvm
@.const.array.data = internal constant [86 x i8] zeroinitializer
```

(`86` bytes of initialized to zero)

**Comment by sklam** [comment]
Actually, this maybe a numpy error:

```
>>> import numpy as np
>>> len(bytearray(np.array([86])))
__main__:1: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
86
>>> len(bytearray(np.array([1])))
1
>>> len(bytearray(np.array([2])))
2
>>> len(bytearray(np.array([3])))
3
>>> len(bytearray(np.array([4])))
4
```

**Comment by sklam** [comment]
This appears to be an open bug in numpy since numpy 1.6
https://github.com/numpy/numpy/issues/3147

**Comment by seibert** [comment]
How does the undecorated function pass, then?

**Comment by sklam** [comment]
During the lowering of constant array, ``bytearray(ndarray)`` is used to read the array data buffer as a sequence of bytes.  The numpy bug affects any code that gets the memoryview from a single-element numpy array.

**Comment by fjanoos** [comment]
So, what should I do as a work around in the interim ?

Thanks.

**Comment by seibert** [comment]
We've just merged a fix.  In several hours, our CI system should upload a new dev build of Numba to the `numba` conda channel.

**Comment by fjanoos** [comment]
can you point me to some instructions about how I can pull this build ?

**Comment by seibert** [comment]
you can do:
```
conda install -c numba numba
```
To revert back to the last release:
```
conda install numba
```
