### ISSUE TITLE
ufunc version of np.isnan

### ISSUE THREAD

**Issue by seibert** [numba/numba#1866]
We support the scalar version of `np.isnan`, but we don't support passing in arrays.

**Comment by pitrou** [comment]
Are you sure about that?
```
>>> from numba import jit
>>> @jit(nopython=True)
   ...: def f(x): return np.isnan(x)
   ...: 
>>> f(4.5)
False
>>> f(np.array([4.5]))
array([False], dtype=bool)
>>> f(np.array([4.5, float('nan')]))
array([False,  True], dtype=bool)
```

**Comment by seibert** [comment]
Oh, nuts.  I forgot I was using NumPy 0.23, because that ships with the Intel Python distribution.  Never mind.  :)
