### ISSUE TITLE
typedtuple does not implement comparison operators as expected

### ISSUE THREAD

**Issue by garrison** [numba/numba#188]
These comparisons do not seem correct:

    >>> import numba
    >>> numba.typedtuple(numba.int_, [0]) == numba.typedtuple(numba.int_, [0])
    False
    >>> numba.typedtuple(numba.int_, [0]) < numba.typedtuple(numba.int_, [0])
    True

**Comment by pitrou** [comment]
This is outdated. "typedtuple" doesn't exist anymore; instead, Numba supports regular tuples in jitted functions.
