### ISSUE TITLE
Add support for `as_strided` from numpy.lib.stride_tricks

### ISSUE THREAD

**Issue by wikiped** [numba/numba#1884]
With `numba.__version__ = '0.25.0'` trying this code:

    from numpy.lib.stride_tricks import as_strided
    @jit(nopython=True)
    def rolling_window(a, window):
        shape = a.shape[:-1] + (a.shape[-1] - window + 1, window)
        strides = a.strides + (a.strides[-1],)
        return as_strided(a, shape=shape, strides=strides)

Leads to:

    Failed at nopython (nopython frontend)
    Untyped global name 'as_strided'
    File "<ipython-input-100-5981db08376a>", line 6

My understanding is that `as_strided` needs to be added to supported numpy functions for the above code to work. Is that right or there is something that needs to be changed in the code for it to work?

**Comment by seibert** [comment]
That's correct.  We don't have support for `as_strided`.  I'm not sure if we support tuple concatenation, but we could work around that for the moment.

**Comment by pitrou** [comment]
Note tuple concatenation and slicing are supported. I've opened a PR for `as_strided` support.
