### ISSUE TITLE
Can't get Numba to work with CUDA

### ISSUE THREAD

**Issue by ColdFire87** [numba/numba#1898]
Hi, I'm trying the following code (`playground.py`):

```python
from numba import vectorize, float32
import numpy as np
import time

@vectorize([float32(float32, float32)], target='cuda')
def g(x, y):
    return x + y

def main():
    N = 32000000
    A = np.ones(N, dtype=np.float32)
    B = np.ones(N, dtype=np.float32)

    t0 = time.clock()

    C = g(A, B)

    t1 = time.clock()
    delta_t = t1 - t0

    print('g executed in {0} seconds'.format(delta_t))

if __name__ == '__main__':
    main()
```

and I get this error:

```
Traceback (most recent call last):
  File "playground.py", line 41, in <module>
    main()
  File "playground.py", line 33, in main
    C = g(A, B)
  File "C:\Anaconda3\lib\site-packages\numba\cuda\dispatcher.py", line 88, in __call__
    return CUDAUFuncMechanism.call(self.functions, args, kws)
  File "C:\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 290, in call
    dev_a = cr.to_device(a, stream=stream)
  File "C:\Anaconda3\lib\site-packages\numba\cuda\dispatcher.py", line 203, in to_device
    return cuda.to_device(hostary, stream=stream)
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py", line 257, in _require_cuda_context
    get_context()
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py", line 240, in get_context
    return _runtime.get_or_create_context(devnum)
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py", line 202, in get_or_create_context
    return self.push_context(self.gpus[devnum])
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py", line 40, in __getitem__
    return self.lst[devnum]
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 269, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 214, in __getattr__
    self.initialize()
  File "C:\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 193, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN:

```

If I change the `target` to `cpu` or `parallel` it works just fine

I also tried:

```python
from numba import cuda
import numpy as np
import time

@cuda.jit
def hello(data):
    data[cuda.blockIdx.x, cuda.threadIdx.x] = cuda.blockIdx.x

numBlocks = 5
threadsPerBlock = 10

data = np.ones((numBlocks, threadsPerBlock), dtype=np.uint8)

hello[numBlocks, threadsPerBlock](data)

print(data)
```

and I get the same error

Versions installed:

- Python 3.5.1 | Anaconda 4.0.0 (64-bit)
- CUDA toolkit 7.5
- I installed numba using `conda install numba`

GPU - GeForce GT 730M
OS - Windows 7 x64

Please help!

**Comment by seibert** [comment]
Hmm, since CUDA is failing to initialize, that suggests one of a few possible issues:

 * Since you are running Windows, your GPU is having to simultaneously handle both rendering your GUI desktop and compute.  I don't know how much memory the GUI requires, but that might not leave enough for CUDA to initialize.  This seems unlikely, since I believe the GT 730M has 2 GB of GPU memory.  Usually you only run into problems with cards that have < 1 GB.

* The NVIDIA driver that is currently installed is not new enough for CUDA 7.5.  I'm not sure if installing the toolkit on Windows also installs a new graphics driver as well (this has been a separate installer in the past).  Using the most recent NVIDIA driver from their website is generally a safe bet.

Can you run any of the examples that came with the CUDA toolkit?   Section 2.5.1 of this document should explain how to do it: http://developer.download.nvidia.com/compute/cuda/7.5/Prod/docs/sidebar/CUDA_Installation_Guide_Windows.pdf

**Comment by ColdFire87** [comment]
I had Visual Studio 2015 Community Edition installed and I couldn't build the CUDA samples.
So I've uninstalled VS 20015 and CUDA, then I've installed VS 2013 Community Edition, then I've installed CUDA Toolkit 7.5 and built the samples. However when I tried to run them I got some errors.

Apparently the graphics driver that came with CUDA toolkit doesn't work with it so I had to unninstall it and install the latest driver form NVIDIA's website.

Now I can run the CUDA samples and the python code that I pasted before works fine too.
Thanks for your help.

I do have one more question though:
when I run `nvprof python playground.py` I get the following output:

```
==4060== NVPROF is profiling process 4060, command: python playground.py
g executed in 0.8221035302425066 seconds
==4060== Profiling application: python playground.py
==4060== Profiling result:
No kernels were profiled.

==4060== API calls:
No API activities were profiled.
==4060== Warning: Some profiling data are not recorded. Make sure cudaProfilerStop() or cuProfilerStop() is called before applic
ation exit to flush profile data.
```

which looks a bit odd. Shouldn't there be some info about the kernel launched?

By the way I am using this video here for reference:
[https://developer.nvidia.com/how-to-cuda-python](https://developer.nvidia.com/how-to-cuda-python)

**Comment by sklam** [comment]
It is likely that the profile data is not being flushed.  Try adding `numba.cuda.profile_stop()` to the end of the program to flush it manually.

**Comment by stuartarchibald** [comment]
FTR I've added a note to this effect in the CUDA FAQ https://github.com/numba/numba/pull/1922 .

**Comment by ColdFire87** [comment]
Hi sklam, thanks for your suggestion! It worked!
