### ISSUE TITLE
Annotate tuple return type for AOT compilation

### ISSUE THREAD

**Issue by zhenruiliao** [numba/numba#1901]
I need to compile a function ahead of time. The function returns a struct (heterogeneous tuple). How do I annotate that in the @cc decorator?

**Comment by sklam** [comment]
You can either omit the return type and let numba infer it:

```python
@cc.export('foo1', '(f8, int32)')
def foo(a, b):
    return a, b
```

or, construct the function signature manually:

```python
from numba import types
retty = types.Tuple([types.float64, types.int32])

@cc.export('foo2', retty(types.float64, types.int32))
def foo(a, b):
    return a, b
```

**Comment by Juanlu001** [comment]
Could this be added to the FAQ?
