### ISSUE TITLE
Support for scipy.special functions?

### ISSUE THREAD

**Issue by mtrbean** [numba/numba#1902]
For example does numba recognize the ufunc `scipy.special.betaln` called inside a jit function?

**Comment by seibert** [comment]
We do not have any support for scipy functions at this time.

**Comment by stuartarchibald** [comment]
As an option you could perhaps construct one from `gamma`, `abs` and `log`?

**Comment by mtrbean** [comment]
Actually I found [lgamma function](http://numba.pydata.org/numba-doc/0.24.0/reference/pysupported.html?highlight=lgamma#math) support thank you so much!
