### ISSUE TITLE
Performance issue when calling a jitclass method inside a loop in a jitted function

### ISSUE THREAD

**Issue by YassineAbdelouadoud** [numba/numba#1912]
# First, I would like to thank the numba developpers for the awesome work they are doing. We have integrated jitted functions to great success in our simulation tool.

To go even further, we would like to use jitclasses, as this would help us improve the modularity of some parts of our code. Our use case will consist mostly of calling jitclass methods inside a loop in jitted function, as implemented in the code below : 

```
from numba import int32
from numba import jitclass, jit
import time

spec = [
    ('value', int32)
]


@jitclass(spec)
class TestClassNumba(object):

    def __init__(self, value):
        self.value = value

    def increment(self):

        self.value += 1


@jit(nopython=True)
def test_loop_numba(test_class_tuple, step_count):
    for i in range(step_count):
        for test_class in test_class_tuple:
            test_class.increment()


class TestClass(object):

    def __init__(self, value):
        self.value = value

    def increment(self):

        self.value += 1


def test_loop(test_class_tuple, step_count):
    for i in range(step_count):
        for test_class in test_class_tuple:
            test_class.increment()


if __name__ == '__main__':

    class_count = 100
    step_count = 10000

    test_class_numba_list = []
    for i in range(class_count):
        test_class_numba_list.append(TestClassNumba(0))

    test_class_numba_tuple = tuple(test_class_numba_list)

    start = time.time()
    test_loop_numba(test_class_numba_tuple, step_count)
    print 'elapsed for numba : ' + str(time.time() - start)


    test_class_list = []
    for i in range(class_count):
        test_class_list.append(TestClass(0))

    test_class_tuple = tuple(test_class_list)

    start = time.time()
    test_loop(test_class_tuple, step_count)
    print 'elapsed for python : ' + str(time.time() - start)
```

On my system (Windows 7 64 bits, python 2.7, numba 0.25), I obtain a timing of 3.59s for numba and 0.22 for python. A profiling of the execution (see attached file) shows that the test_loop_numba is effectively 10 times faster than test_loop, but that is dwarfed by the time taken for the compilation. This is a problem because the jitted function cannot be cached ( #1875 )

![jit_class_loop_profiler](https://cloud.githubusercontent.com/assets/10462548/15612536/7b55204c-242f-11e6-95a9-f2e68c5023bc.png)

**Comment by synapticarbors** [comment]
Just to be clear, the time difference you're seeing is due to the initial jitting of the numba code. When I insert:

```
test_loop_numba(test_class_numba_tuple, 1)
```

to run the numba code once (and thus jit it), before the timing loop, I get the following timings:

```
elapsed for numba : 0.0327341556549
elapsed for python : 0.219484806061
```

Without "warming-up" the code, the timings look like:

```
elapsed for numba : 2.42656898499
elapsed for python : 0.209844112396
```

The effect of caching is only going to be noticeable if the ratio of start-up frequency vs computational time is high.

**Comment by pitrou** [comment]
So the underlying problem here is that the function cannot be cached. I will just close this issue as duplicate since #1875 already exists.

**Comment by YassineAbdelouadoud** [comment]
Sorry to comment on a closed issue but caching is not the underlying issue. At best, caching would be a workaround. Please try the code above with increasing number of class instances and witness the compilation time increase exponentially. If this is the expected behaviour, it would seem difficult to use jit classes in real use cases, even with caching enabled.

**Comment by pitrou** [comment]
Ok, sorry for misunderstanding. It seems there is an issue when using tuples of jitclass instances, indeed.

**Comment by YassineAbdelouadoud** [comment]
This can be closed thanks to https://github.com/numba/numba/pull/2840 allowing the use of list of jitclasses.
