### ISSUE TITLE
the builtin function cmp is not recognized in numba njit

### ISSUE THREAD

**Issue by liuzhenhai** [numba/numba#1931]
``` python
from numba import njit
@njit
def f():
    return cmp(1,2)
f() #raise TypingError: Untyped global name 'cmp'
```

the cmp function can be recognized in njit by using the overload function:

``` python
from numba import types,njit
from numba.extending import overload

@overload(cmp)
def my_cmp(a,b):
   if isinstance(a, types.Number) and isinstance(b, types.Number):
       def cmp_impl(a,b):
            if a<b:
                return -1
            elif a>b:
                return 1
            else:
                return 0
       return cmp_impl
```

But I am not sure this is the right solution.

**Comment by seibert** [comment]
This is a great workaround.  We want built-in support for cmp() in nopython mode eventually, but we also encourage users to use `@overload` to extend the compiler for their needs.

**Comment by pitrou** [comment]
If you ever plan to switch to Python 3, though, I would recommend you don't use the `cmp()` function, which doesn't exist anymore.
