### ISSUE TITLE
Data for Numpy arrays are misaligned in LLVM IR

### ISSUE THREAD

**Issue by Maher4Ever** [numba/numba#1933]
Hi,

While converting the LLVM IR generated by Numba to Javascript using Emscripten I came across a bug that seems to originate from the way Numba handles Numpy arrays. I use Numba to generate LLVM IR for some functions that used matrices. These matrices are stored in `np.array` instances. Now consider the following code:

```python
from numba import njit, int32, double
import numpy as np

m = np.array([
    3.98, -98.765
])

@njit(double(int32))
def func(i):
    return m[i]/i
```

Here is the LLVM IR for it:

```llvm
; ModuleID = 'func'
target datalayout = "e-m:e-p:32:32-i64:64-f80:32-n8:16:32-a:0:32-S32"
target triple = "i686-pc-windows-msvc"

@.const.picklebuf.87005624 = internal constant { i8*, i32 } { i8* getelementptr inbounds ([68 x i8], [68 x i8]* @.const.pickledata.87005624, i32 0, i32 0), i32 68 }
@.const.pickledata.87005624 = internal constant [68 x i8] c"\80\04\959\00\00\00\00\00\00\00\8C\08builtins\94\8C\11ZeroDivisionError\94\93\94\8C\10division by zero\94\85\94\86\94."
@.const.array.data = internal unnamed_addr constant [16 x i8] c"\D7\A3p=\0A\D7\0F@)\5C\8F\C2\F5\B0X\C0"

define double @func({ i8*, i32 }** noalias nocapture %excinfo, i32 %arg.i) {
entry:
  %.75 = icmp eq i32 %arg.i, 0
  br i1 %.75, label %B0.if, label %B0.endif

B0.if:                                            ; preds = %entry
  store { i8*, i32 }* @.const.picklebuf.87005624, { i8*, i32 }** %excinfo, align 4
  ret double -1.0

B0.endif:                                         ; preds = %entry
  %.49 = icmp slt i32 %arg.i, 0
  %.50 = add i32 %arg.i, 2
  %.51 = select i1 %.49, i32 %.50, i32 %arg.i
  %.64 = getelementptr double, double* bitcast ([16 x i8]* @.const.array.data to double*), i32 %.51
  %.65 = load double, double* %.64, align 8
  %.74 = sitofp i32 %arg.i to double
  %.79 = fdiv double %.65, %.74
  ret double %.79
}
```

Emscripten generated incorrect static data in JS for this LLVM IR and after [reporting it](https://github.com/kripken/emscripten/issues/4388) I learned that the data in the byte array is not aligned. The load instruction for the double (` %.65 = load double, double* %.64, align 8`) tries to use an alignment of 8 with a byte array which has an alignment of 1. Here is a direct quote: 

> My guess is this is an alignment issue. unnamed_addr constant [16 x i8] is just an array of bytes, with alignment 1. But the double loads declare alignment 8. That works on x86, but will fail on arm and asm.js, and is nonportable.
>
> Try to make the alignment on the double loads 1, that could fix it. A better fix might be aligning the global constant.

Changing the alignment of the load call doesn't seem to solve my issue. How hard is it to have the generated byte array be aligned to the actual size of its elements (8 for `double`s in this case)?

**Comment by pitrou** [comment]
> Changing the alignment of the load call doesn't seem to solve my issue

This in itself sounds like an issue with Emscripten.

> How hard is it to have the generated byte array be aligned to the actual size of its elements

I think this is reasonably doable.

**Comment by Maher4Ever** [comment]
I completely agree, but still for me that means Numba will have to be modified to generate `load` instructions with correct alignment for the byte array.

For changing the alignment of the byte array, i might be able to implement this myself if you can point me to where I should look in the codebase.

**Comment by pitrou** [comment]
> For changing the alignment of the byte array, i might be able to implement this myself if you can point me to where I should look in the codebase. 

I think we first have to modify llvmlite to allow setting the alignment of a global variable.

**Comment by Maher4Ever** [comment]
Ok I'll dig into the code of llvmlite later today to see how easy that is to implement.

**Comment by pitrou** [comment]
See https://github.com/numba/llvmlite/pull/191 for the required llvmlite enhancement.

**Comment by Maher4Ever** [comment]
@pitrou Awesome man! Thanks for adding this to llvmlite since I still haven't had time to work on it.
