### ISSUE TITLE
nopython mode and endianness

### ISSUE THREAD

**Issue by MSeifert04** [numba/numba#1943]
If I try to pass some numba function an array with "endianess" dtype it crashes:

```
import numba as nb
import numpy as np

@nb.njit
def testfunc(arr):
    return arr

testfunc(np.ones((3, 3), dtype='>i8'))
TypeError: Failed at nopython (nopython frontend)
Arg 0 of pyobject is not legal in nopython mode
```

I don't know if it's planned to support these dtypes. If not, could unsupported dtypes raise a custom exception message? 

It's really hard to figure out such crashs if one doesn't know it's caused by the dtype.

**Comment by pitrou** [comment]
You're right, the error message is really bad here. 
As for supporting dtypes with a custom endianness, that's not in our short-term plans, but it would probably be doable some day.
