### ISSUE TITLE
List 2015 ACM paper as preferred way to cite Numba

### ISSUE THREAD

**Issue by seibert** [numba/numba#1944]
Now that we have a real paper out there on Numba, we should encourage academic users to cite it, rather than the website.

**Comment by MatthieuDartiailh** [comment]
I guess that answer my recent post on the mailing list. Thanks

**Comment by seibert** [comment]
This issue was opened because of your request to remind me to update the docs.  :)

**Comment by paragkulkarni** [comment]
@seibert 
I like to work on this. Please send me the link for this ACM paper, as it finds me easy.

**Comment by seibert** [comment]
The link is here:

https://dl.acm.org/citation.cfm?id=2833162&dl=ACM&coll=DL&CFID=1000256720&CFTOKEN=81397119

**Comment by seibert** [comment]
Actually, never mind.  We added the link to the FAQ already:

http://numba.pydata.org/numba-doc/latest/user/faq.html?highlight=acm#how-do-i-reference-cite-acknowledge-numba-in-other-work
