### ISSUE TITLE
Overlapping slice copy corrupts array data

### ISSUE THREAD

**Issue by mago876** [numba/numba#1960]
Hello.

I'm working in a Miniconda enviroment, using Python+Numpy+Numba code. I implemented a basic nearest-neighbors search in my study work. The fact is that the basic Numpy implementation is working well, but just adding the '@jit' decorator (compiling in Numba), the outputs are differents (it duplicates some neighbors in the end for some unknown reason...)

Here is the basic algorithm:

```
import numpy as np
from numba import jit

@jit(nopython=True)
def knn(p, points, k):
    '''Find the k nearest neighbors (brute force) of the point p
    in the list points (each row is a point)'''

    n = p.size  # Lenght of the points
    M = points.shape[0]  # Number of points
    neighbors = np.zeros((k,n))
    distances = 1e6*np.ones(k)

    for i in xrange(M):
        d = 0
        pt = points[i, :]  # Point to compare
        for r in xrange(n):  # For each coordinate
            aux = p[r] - pt[r]
            d += aux * aux
        if d < distances[k-1]:  # We find a new neighbor
            pos = k-1
            while pos>0 and d<distances[pos-1]:  # Find the position
                pos -= 1
            pt = points[i, :]
            # Insert neighbor and distance:
            neighbors[pos+1:, :] = neighbors[pos:-1, :]
            neighbors[pos, :] = pt
            distances[pos+1:] = distances[pos:-1]
            distances[pos] = d

    return neighbors, distances
```

For testing:

```
p = np.random.rand(10)
points = np.random.rand(250, 10)
k = 5
neighbors, distances = knn(p, points, k)
```

WITHOUT the @jit decorator, one gets the correct answer:

In [1]: distances
Out[1]: array([ 0.3933974 ,  0.44754336,  0.54548715,  0.55619749,  0.5657846 ])

But the Numba compilation gives weird outputs:

Out[2]: distances
Out[2]: array([ 0.3933974 ,  0.44754336,  0.54548715,  **0.54548715,  0.54548715**])

It seems (realized in discussion [here](http://stackoverflow.com/questions/38074352/differences-in-numba-outputs)) that there are problems with the overlapping slice. In Numpy it doesn't causes any problem, but may be Numba translates it to a different procedure.

Thanks you.

**Comment by seibert** [comment]
this does sound like an issue with overlapping slices.  @pitrou, can you take a look at this?

**Comment by pitrou** [comment]
Right, we don't detect overlapping memory copies. Numpy has some heuristics to make sure this doesn't happen (when it detects the source and destination may overlap, it first makes a private copy of the source).

**Comment by seibert** [comment]
I think we'll need to support those same heuristics since it looks like people do rely on this behavior.

**Comment by pitrou** [comment]
Yes, our current behaviour really is a bug. It seems Numpy is conservative and just checks the memory bounds (even though there may be "holes" due to slicing).
