### ISSUE TITLE
Weird behavior using `numba.jit` on a simple function. It seems casting is not correct 

### ISSUE THREAD

**Issue by kikocorreoso** [numba/numba#1979]
I'm getting a weird behavior/casting error when using the `numba.jit` decorator over a very simple function. 

Context:
* Python 3.5
* W7 32 bits
* All python related stuff installed using conda.

See this snippet:

```python
import numba
print("Numba version: ", numba.__version__)

def fn1(n):
    total = 0
    for i in range(n):
        total += i
    return total

def fn2(n):
    return sum(range(n))

fn1_numba = numba.jit(fn1)
fn2_numba = numba.jit(fn2)

n = 100000

print("Result of the sum of the first 100000 positive integers")
print(fn1(n))
print(fn2(n))
print(fn1_numba(n))
print(fn2_numba(n))
```

The results are:

```python
Numba version: 0.27.0
Result of the sum of the first 100000 positive integers
4999950000
4999950000
704982704
4999950000
```

However, this works as expected:

```python
@numba.jit(numba.int64(numba.int64))
def fn1(n):
    total = 0
    for i in range(n):
        total += i
    return total

```

Is this the expected behaviour when one doesn't define the types?

**Comment by pitrou** [comment]
Numba uses machine-width integers by default. On a 32-bit OS, this means arithmetic operations will be truncated to 32 bits.
`sum()` has a slightly different behaviour, mostly for accidental reasons.

**Comment by pitrou** [comment]
Out of curiosity, do you have a specific requirement to use a 32-bit OS?

**Comment by kikocorreoso** [comment]
> Numba uses machine-width integers by default. On a 32-bit OS, this means arithmetic operations will be truncated to 32 bits.

I can't find this documented.

> sum() has a slightly different behaviour, mostly for accidental reasons.

If you find the time could you expand on this?

> Out of curiosity, do you have a specific requirement to use a 32-bit OS?

Ask my bosses :disappointed: 

If it is not a bug and you think this is the expected behavior, please, close the issue. Maybe it could be added `Numba uses machine-width integers by default. On a 32-bit OS, this means arithmetic operations will be truncated to 32 bits.` to the docs.

Thanks

**Comment by pitrou** [comment]
> I can't find this documented.

You're right, we should mention it in the docs.

> If you find the time could you expand on this?

Sorry, it turns out sum() isn't implemented in nopython mode, which is why Numba falls back on the Python object system.

> Ask my bosses

Ha. I'm asking because we sometimes wonder if it's worthwhile for us to continue supporting 32-bit platforms. It would be good to know the reasons or constraints people have.

**Comment by pitrou** [comment]
By the way, instead of giving an explicit signature for the function, you can simply initialize your accumulation variable as `total = np.int64(0)`. This will propagate to computations involving the variable.

**Comment by kikocorreoso** [comment]
> Sorry, it turns out sum() isn't implemented in nopython mode, which is why Numba falls back on the Python object system.

Thanks.

> Ha. I'm asking because we sometimes wonder if it's worthwhile for us to continue supporting 32-bit platforms. It would be good to know the reasons or constraints people have.

I think it is not worth the effort. In our case it is just a matter of time but they (my company) are quite conservative changing some stuff...

Thanks again.

I close the issue.
