### ISSUE TITLE
Request: Support for np.linalg.det and/or slogdet

### ISSUE THREAD

**Issue by bashtage** [numba/numba#1980]
It is not uncommon for some code that benefits from numba and that uses linear algebra to require the determinant of the matrix (for example, many multivariate distributions have a determinant or log determinant in their kernel).  The expanded support for linear algebra has been a welcome addition, but currently computing the detminant requires a full eigenvalue calculation which is slower than just computing the determinant.

It woudl be beneficial if `np.linalg.det` and/or `np.linalg.slogdet` were available in nopython mode.

**Comment by seibert** [comment]
Thanks for the suggestion!  We'll put this on our todo list for the next release.

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/1987 queued for review.

**Comment by stuartarchibald** [comment]
Done, will be in the next release or for early access use the numba channel `-c numba` with conda.

**Comment by bashtage** [comment]
Thanks for the rapid response!

**Comment by stuartarchibald** [comment]
No problem, thanks for your support and the suggestion :)
