### ISSUE TITLE
dirty __version__ on Python 2 packages

### ISSUE THREAD

**Issue by danielballan** [numba/numba#1984]
Hi there. Just dropping in to report a minor problem noticed by one of my users in [this issue](https://github.com/soft-matter/trackpy/issues/381).

The `__version__` for numba 0.27.0 is dirty:

```
$ conda create -n numba-version python=2.7 numba
$ source activate numba-version
>>> import numba
>>> numba.__version__
'0.27.0+0.g6ca78ce.dirty'
```

This is on the Python 2.7 (official) conda package. The version string for the Python 3.5 package is correct. I have not checked 3.4.

**Comment by seibert** [comment]
OK, that's weird.  We'll take a look and rebuild the package.  Thanks for letting us know!

**Comment by seibert** [comment]
@sklam: Can you take a look at this?

**Comment by pitrou** [comment]
`'0.27.0+0.g6ca78ce.dirty'` seems to mean that the 0.27.0 changeset was built, but with local changes, which is a bit weird...

**Comment by seibert** [comment]
Right, so either versioneer did something weird after the CI system updated to the tagged release (the git hash is correct for the 0.27.0 tag), or something was left over in the working copy...

**Comment by sklam** [comment]
I am seeing the "g6ca78ce.dirty" added when building locally.

**Comment by pitrou** [comment]
Which command line are you using for building?

**Comment by sklam** [comment]
I using ``conda build``. 

I have identified the source of the modification--- `remove_unwanted_files.py`

**Comment by sklam** [comment]
So, due to https://github.com/numba/numba/pull/1925
and https://github.com/conda/conda-build/issues/1001

**Comment by pitrou** [comment]
Oh, I see. I'm not sure we can do anything until the conda-build bug is fixed, then.

**Comment by seibert** [comment]
This was fixed in subsequent releases.
