### ISSUE TITLE
'>>' applied to an unsigned number shall result in a logical shift

### ISSUE THREAD

**Issue by ukaluzhny** [numba/numba#1995]
Please, see 
[http://stackoverflow.com/questions/38486442/logical-right-shift-in-numba](http://stackoverflow.com/questions/38486442/logical-right-shift-in-numba)

Thanks

**Comment by pitrou** [comment]
I cannot reproduce your example. Which platform are you using?

**Comment by pitrou** [comment]
Ok, I can reproduce if I try `hex(foo(2**64 - 1))` instead.

**Comment by pitrou** [comment]
I've submitted a fix in PR #1995.
