### ISSUE TITLE
[FreeBSD] ImportError: /lib/libgcc_s.so.1

### ISSUE THREAD

**Issue by davidkallie** [numba/numba#2001]
When running in ipython, starting with one of the numba examples:

`from numba import jit`

the following error shows up:

`ImportError: /lib/libgcc_s.so.1: version GCC_4.6.0 required by /usr/local/lib/gcc48/libgfortran.so.3 not found`

Restarting ipython, an running:

`import numpy`
`from numba import jit`

Seems to fix the problem, and the example code executes correctly. I am assuming this is **not** an issue with Anaconda. However I am porting numba and llvmlite to Freebsd, and this seems to be an issue. Any help would be great!

**Comment by andrewkenny** [comment]
Is this consistant behaiviour?
I.E, do you mean to say that you can only import number after you have imported numpy?

**Comment by davidkallie** [comment]
Yes, that is correct. Unless I start with

`import numpy` or `import numpy as np`

I cannot do either `import numba` or `from numba import jit`

**Comment by seibert** [comment]
Just to be clear, you are encountering this error on FreeBSD, not Linux?

**Comment by davidkallie** [comment]
Yes, I am currently encountering this in FreeBSD 10.3, with numba 0.27 and llvmlite 0.12.1

**Comment by stuartarchibald** [comment]
Do you have scipy in the environment?

**Comment by davidkallie** [comment]
If I type
>$ ipython
>In [1]: import scipy
>In [2]: import numba

it works just fine as well, this seems like strange behaviour if it requires numpy or scipy. However, if I run
>$ ipython --pylab
>In [1]: import numba

Everything works fine, would it be wise to check the if scipy or numpy is within the environment and either import them or raise an Error?

**Comment by stuartarchibald** [comment]
Apologies, I'll clarify, do you have SciPy in your conda environment? `conda list` will tell you, if you dump the output of that into a comment that'd be v. helpful thanks (I'd like to see what else is in there!).

**Comment by seibert** [comment]
As a side point: you were able to install Anaconda on your FreeBSD system?  I didn't realize our binary packages would work with FreeBSD's Linux emulation layer.

**Comment by davidkallie** [comment]
Ah, I see some confusion has arisen due to me not being specific. 

I am not using Anaconda, as I assumed it would be more challenging to port over. However I just installed llvmlite-0.12.1 from source using LLVM 3.7, and documentation says LLVM 3.8 for v0.12+, but the 0.12.1 branch clearly wants LLVM 3.7 due to build error indication. llvmlite installed just fine no hiccups, then moved onto numba-0.27.0, everything installed just fine, just using the base packages provided by the FreeBSD ports system.

Fast forward to a few days ago, I decided to make an installable port for the FreeBSD ports system which allows for use of the native package manager, due to Anaconda not being present. All available packages aside from llvmlite were in the ports tree. However the default version of python in the ports tree is Python 2.7, and most scientific packages work just fine this way. This allows a user to either use
>$ cd /usr/ports/devel/py-numba
>$ make install

or 
`pkg install py27-numba`

to install numba on the system. Using numba however requires that the user input either
>import scipy
>import numba

or
>import numpy
>import numba

to use the features provided by numba, otherwise if you try to `import numba` first, you get:  
>[...]
>ImportError: /lib/libgcc_s.so.1: version GCC_4.6.0 required by /usr/local/lib/gcc48/libgfortran.so.3 not found

and all subsequent imports report the same error, unless you restart the interpreter.

Based on post by @stuartarchibald, it sounds like the conda environment pre-loads scipy in the environment when an interpreter is run? Correct me if I am wrong as I do not have Anaconda or use it.

Funny thing is last year it was a bit tricky to get numba working nicely on a Ubuntu system, however it installs quite effortlessly on FreeBSD. It is just odd that `import numpy` needs to be imported first, but everything works great, it just seems to me that numba requires numpy, or scipy, but doesn't check if they are loaded upon loading itself.  

Again, thanks for being patient with me on this, I appreciate all of the help.

**Comment by davidkallie** [comment]
Here is the error from python, note the `__init__.py` shows as `init.py` (markdown?)
>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/usr/local/lib/python2.7/site-packages/numba/types/__init__.py", line 5, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /lib/libgcc_s.so.1: version GCC_4.6.0 required by /usr/local/lib/gcc48/libgfortran.so.3 not found

**Comment by stuartarchibald** [comment]
If you `ldd` your ` /usr/local/lib/gcc48/libgfortran.so.3` does it find a `libgcc_s.so.1` with the right version? Do you have `/usr/local/lib/gcc48/` in `LD_LIBRARY_PATH` or on the path for the linker, if not, perhaps try it, could be that the system `libgcc_s.so.1` is too old to work with the port version?

**Comment by davidkallie** [comment]
>$ ldd /usr/local/lib/gcc48/libgfortran.so.3                                                                           
/usr/local/lib/gcc48/libgfortran.so.3:
	libquadmath.so.0 => /usr/local/lib/gcc48/libquadmath.so.0 (0x801717000)
	libm.so.5 => /lib/libm.so.5 (0x801952000)
	libgcc_s.so.1 => /usr/local/lib/gcc48/libgcc_s.so.1 (0x801b78000)
	libc.so.7 => /lib/libc.so.7 (0x80081d000)

However LD_LIBRARY_PATH is not set at all, seems to be a preference for FreeBSD. Setting 'LD_LIBRARY_PATH=/usr/local/lib/gcc48/` works just fine, however I need to find the BSD solution for this fix, which is to not set LD_LIBRARY_PATH. Thanks @stuartarchibald for helping and pointing me in the right direction. I will update once I determine the best course of action on my side and it is working.

**Comment by stuartarchibald** [comment]
Thanks for the info. Without creating up a replica of your set-up debugging this may be hard. There's a few things that may help though...

1. As far as I'm aware, numba itself does not depend on `libgfortran.so`.
2. Numpy `multiarray` is linked against BLAS/LAPACK, which in the case of using ATLAS or netlib would probably be what creates a dependency on `libgfortran`.
3. The questions about SciPy were down to trying to figure out where the `libgfortran` dependency came from, this trail can be ignored.
4. Binutils `readelf` is useful for checking symbol version requirements, the `-V` flag will produce this.
5. I would not expect `LD_LIBRARY_PATH` to be set. I suggested it to see if the problem was due to the `/usr/local/lib/gcc48/libgfortran.so.3` using the system `libgcc_s` for symbol resolution (which may have been older and therefore lack the `GCC_4.6`). The backtrace here: https://github.com/numba/numba/issues/2001#issuecomment-235345736 suggests that the `multiarray` import is using the port version of GCC for `libgfortran` at `/usr/local/lib/gcc48/libgfortran.so.3` but for some reason that `libgfortran` is then trying to resolve symbols in the system `libgcc_s` at `/lib/libgcc_s.so.1`. Setting (think it's `setenv` in BSD) `LD_LIBRARY_PATH` to `/usr/local/lib/gcc48/`, the port path, may force the use of the assumed compatible `libgcc_s` from the port location.
6. If possible, see if numba `.so`s are linked against the port `libgcc_s` or system `libgcc_s`. I think this may be happening.... If numpy is linked against the port then importing it first will mean there's the port `libgcc_s` in scope and so when numba loads there's already a `libgcc_s` in scope and as it is newer the symbols resolve and it's all fine. If however numba is loaded by itself, it uses the system `libgcc_s` (not sure why!) which is older , then when it tries to import numpy, numpy's `multiarray.so`, which is linked to `libgfortran`, tries to resolve the symbols in `libgfortran` using the system `libgcc_s`, as it is in scope from the numba load, but it is too old and fails with the version error.

**Comment by davidkallie** [comment]
Okay thanks! A manual fix for FreeBSD is for the user to map the libgcc_s.so.1 using the /etc/libmap.conf file as such:
`echo "libgcc_s.so.1    gcc48/libgcc_s.so.1" >> /etc/libmap.conf`

However, this is only a manual/temporary fix. I checked numba's .so's using 
`readelf -d /usr/local/lib/python2.7/sites-packages/numba/*.so` and got the following:

> File: _dispatcher.so
> 
> Dynamic section at offset 0x9058 contains 26 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc++.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libcxxrt.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.5]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib/gcc48]
>  0x000000000000000c (INIT)               0x2b78
>  0x000000000000000d (FINI)               0x7de8
>  0x0000000000000004 (HASH)               0x158
>  0x000000006ffffef5 (GNU_HASH)           0x580
>  0x0000000000000005 (STRTAB)             0x13b0
>  0x0000000000000006 (SYMTAB)             0x738
>  0x000000000000000a (STRSZ)              2811 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x209300
>  0x0000000000000002 (PLTRELSZ)           1776 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0x2488
>  0x0000000000000007 (RELA)               0x1fd8
>  0x0000000000000008 (RELASZ)             1200 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x1fb8
>  0x000000006fffffff (VERNEEDNUM)         1
>  0x000000006ffffff0 (VERSYM)             0x1eac
>  0x000000006ffffff9 (RELACOUNT)          24
>  0x0000000000000000 (NULL)               0x0
> 
> File: _dynfunc.so
> 
> Dynamic section at offset 0x2028 contains 23 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib/gcc48]
>  0x000000000000000c (INIT)               0xdc0
>  0x000000000000000d (FINI)               0x1868
>  0x0000000000000004 (HASH)               0x158
>  0x000000006ffffef5 (GNU_HASH)           0x240
>  0x0000000000000005 (STRTAB)             0x610
>  0x0000000000000006 (SYMTAB)             0x280
>  0x000000000000000a (STRSZ)              608 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x2021f8
>  0x0000000000000002 (PLTRELSZ)           624 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0xb50
>  0x0000000000000007 (RELA)               0x8e0
>  0x0000000000000008 (RELASZ)             624 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x8c0
>  0x000000006fffffff (VERNEEDNUM)         1
>  0x000000006ffffff0 (VERSYM)             0x870
>  0x000000006ffffff9 (RELACOUNT)          21
>  0x0000000000000000 (NULL)               0x0
> 
> File: _helperlib.so
> 
> Dynamic section at offset 0x15110 contains 24 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.5]
>  0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib/gcc48]
>  0x000000000000000c (INIT)               0x5460
>  0x000000000000000d (FINI)               0x10a38
>  0x0000000000000004 (HASH)               0x158
>  0x000000006ffffef5 (GNU_HASH)           0xac8
>  0x0000000000000005 (STRTAB)             0x2f60
>  0x0000000000000006 (SYMTAB)             0xfb0
>  0x000000000000000a (STRSZ)              3184 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x215370
>  0x0000000000000002 (PLTRELSZ)           4104 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0x4458
>  0x0000000000000007 (RELA)               0x3ee8
>  0x0000000000000008 (RELASZ)             1392 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x3e78
>  0x000000006fffffff (VERNEEDNUM)         2
>  0x000000006ffffff0 (VERSYM)             0x3bd0
>  0x000000006ffffff9 (RELACOUNT)          24
>  0x0000000000000000 (NULL)               0x0
> 
> File: _npymath_exports.so
> 
> Dynamic section at offset 0xa028 contains 26 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.5]
>  0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libthr.so.3]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000000f (RPATH)              Library rpath: [/usr/lib:/usr/local/lib]
>  0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib:/usr/local/lib]
>  0x000000000000000c (INIT)               0x55b0
>  0x000000000000000d (FINI)               0x7a28
>  0x0000000000000004 (HASH)               0x158
>  0x000000006ffffef5 (GNU_HASH)           0xa10
>  0x0000000000000005 (STRTAB)             0x2ab0
>  0x0000000000000006 (SYMTAB)             0xf50
>  0x000000000000000a (STRSZ)              2270 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x20a228
>  0x0000000000000002 (PLTRELSZ)           3336 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0x48a8
>  0x0000000000000007 (RELA)               0x3648
>  0x0000000000000008 (RELASZ)             4704 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x35d8
>  0x000000006fffffff (VERNEEDNUM)         2
>  0x000000006ffffff0 (VERSYM)             0x338e
>  0x000000006ffffff9 (RELACOUNT)          97
>  0x0000000000000000 (NULL)               0x0
> 
> File: mviewbuf.so
> 
> Dynamic section at offset 0x2028 contains 23 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.7]
>  0x000000000000001d (RUNPATH)            Library runpath: [/usr/local/lib/gcc48]
>  0x000000000000000c (INIT)               0xc20
>  0x000000000000000d (FINI)               0x17c8
>  0x0000000000000004 (HASH)               0x158
>  0x000000006ffffef5 (GNU_HASH)           0x230
>  0x0000000000000005 (STRTAB)             0x5a0
>  0x0000000000000006 (SYMTAB)             0x270
>  0x000000000000000a (STRSZ)              555 (bytes)
>  0x000000000000000b (SYMENT)             24 (bytes)
>  0x0000000000000003 (PLTGOT)             0x202200
>  0x0000000000000002 (PLTRELSZ)           528 (bytes)
>  0x0000000000000014 (PLTREL)             RELA
>  0x0000000000000017 (JMPREL)             0xa10
>  0x0000000000000007 (RELA)               0x830
>  0x0000000000000008 (RELASZ)             480 (bytes)
>  0x0000000000000009 (RELAENT)            24 (bytes)
>  0x000000006ffffffe (VERNEED)            0x810
>  0x000000006fffffff (VERNEEDNUM)         1
>  0x000000006ffffff0 (VERSYM)             0x7cc
>  0x000000006ffffff9 (RELACOUNT)          15
>  0x0000000000000000 (NULL)               0x0

It appears that numba is not linked with libgcc_s.so.1 or libgfortran.so.3

**Comment by davidkallie** [comment]
It seems as though even though the numba is being compiled with the correct libgcc_s, it still picks up the system libgcc_s which was pointed out to me here:
[https://lists.freebsd.org/pipermail/freebsd-ports/2016-August/104461.html](https://lists.freebsd.org/pipermail/freebsd-ports/2016-August/104461.html)

I am putting it here for record, I will be working on this to see if I can resolve it. It seems to have been a problem with fortran requirements, and was problematic with numpy at one point.

**Comment by pitrou** [comment]
@davidkallie are you using conda-build or your own build chain?

**Comment by davidkallie** [comment]
I am using the freebsd ports system to build. Conda is not ported to freebsd, and I don't have any desire to run through the linux compatibility layer on freebsd, since the rest of the python packages run on my system natively.

From what I gather it is an issue with rpath possible not being set correctly, but before I speculate this any further, I will look into it this weekend.

The bug report on freebsd can be seen here:
[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211347](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211347)

**Comment by davidkallie** [comment]
After looking in the wrong spot, I realized that numba is working as expected. The libgcc_s.so.1 loads as expected as a shared library. However it is llvmlite that is incorrectly loading libgcc_s.so.1 on FreeBSD. It turns out that llvmlite may not be setting rpath correctly?

I think this can be closed and a issue on llvmlite will be opened up.
