### ISSUE TITLE
arrayexpr `float32 ** const_int` yields float64 instead of float32

### ISSUE THREAD

**Issue by sklam** [numba/numba#2006]
```python
import numpy as np
from numba import njit


@njit
def bar(x):
     return x ** 3


x = np.arange(10, dtype=np.float32)
out = bar(x)
print(out, out.dtype)
```
prints
```
[   0.    1.    8.   27.   64.  125.  216.  343.  512.  729.] float64
```

**Comment by pitrou** [comment]
The problem comes from `np.can_cast` as used in `numpy_support.ufunc_find_matching_loop`. An int32 or `int64` cannot be cast to float32, so the float64 version of the loop is chosen instead.

**Comment by pitrou** [comment]
Numpy's ufunc resolution mechanism internally uses `PyArray_CanCastArrayTo`, which does *value-based* analysis on scalars(!):
```
>>> a = np.float32([0])
>>> a ** np.int64(33333)
array([ 0.], dtype=float32)
>>> a ** np.int64(333333)
array([ 0.])
```

**Comment by pitrou** [comment]
I think the main reason this is surprising is because of the mixed float-integer operation. Perhaps we should use different rules than Numpy in that case? What do you think?

**Comment by sklam** [comment]
> value-based analysis on scalars(!):

I didn't expect that at all.

> Perhaps we should use different rules than Numpy in that case? What do you think?

Do you mean keeping our current behavior?

**Comment by pitrou** [comment]
> Do you mean keeping our current behavior?

No, I mean decide that a `int32` parameter is allowed to be cast to `float32` if desired. I don't really know how to express that in a generic way, though.
