### ISSUE TITLE
Double star expansion of keyword arguments in jitclass __init__ regression

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#2009]
In testing Numba 0.27, I noticed the following code now fails, where it previously worked in the 0.26 release:

```python
import numba as nb

spec = [('a', nb.int64),
        ('b', nb.float64)]

@nb.jitclass(spec)
class TestClass(object):
    def __init__(self, x, y, z):
        self.a = x * y
        self.b = z

kwargs = {'y': 2, 'z': 1.1}
tc = TestClass(2, **kwargs)
```

In 0.27 I now get the following error:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    tc = TestClass(2, **kwargs)
  File "/Users/lev/anaconda/envs/test-numba/lib/python2.7/site-packages/numba/jitclass/base.py", line 99, in __call__
    return cls._ctor(*args, **kwargs)
TypeError: some keyword arguments unexpected
```

**Comment by synapticarbors** [comment]
I'm bumping this issue since it has persisted into Numba 0.28.1.

**Comment by sklam** [comment]
Review of #1865 has taken longer than expected. 
If we can't merge it by 0.29 release, I should submit a PR with just the fix for this bug.

**Comment by synapticarbors** [comment]
@sklam That would be great. I appreciate you continuing to keep tabs on this issue. Do you have a sense of when 0.29 might be released?

**Comment by seibert** [comment]
Our scheduled release tagging date for Numba 0.29 is Oct 12, with packages appearing a day or two after that.
