### ISSUE TITLE
Insufficient documentation build instructions.

### ISSUE THREAD

**Issue by jriehl** [numba/numba#203]
We need a README or similar in .../numba/docs/ that explains how to build Numba documentation.

I had to guess that I needed to `pip install sphinxjp.themecore`, and now still can't build:

```
numba/docs$ make html
sphinx-build -b html -d _build/doctrees   source _build/html
Running Sphinx v1.1.3
loading pickled environment... not yet created

Theme error:
no theme named 'basicstrap' found (missing theme.conf?)
make: *** [html] Error 1
```

**Comment by Juanlu001** [comment]
Was the docs README moved somewhere? I came here googling "numba basicstrap".

**Comment by pitrou** [comment]
@Juanlu001, Take a look at http://numba.pydata.org/numba-doc/dev/developer/contributing.html#documentation
