### ISSUE TITLE
cpu='parallel' on windows extremely slow after 0.23.1

### ISSUE THREAD

**Issue by slingyropert** [numba/numba#2053]
Prior to numba=0.23.1 I could get the attached benchmark 
[cpu_parallel_benchmark.zip](https://github.com/numba/numba/files/428952/cpu_parallel_benchmark.zip)
yielding best times of 49 milli-seconds.

As of numba=0.23.1 and all later, the benchmark runs at about 8590 mili-seconds or about 170x slower. I've tested all of the revisions from 0.23.1 to 0.27 and they all have the same behavior for me.

I am on Windows x64 so presumably this has something to do with #1634 and target='parallel'?

**Comment by slingyropert** [comment]
Apologies, my benchmark code referenced a module that was not included. Here is a fixed version which demonstrates the same performance degradation post 0.23.0: 
[cpu_parallel_benchmark2.zip](https://github.com/numba/numba/files/429112/cpu_parallel_benchmark2.zip)

**Comment by pitrou** [comment]
Thanks for reporting! It turns out your intuition was right. I've submitted a fix at PR #2055.
