### ISSUE TITLE
Vectorize and struct not working together

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [numba/numba#207]
I attempted to rewrite the hypot example to use vectorization. This is what I did:

@vectorize([double( record_type)])
def hypot(data):
    return np.sqrt(data.x_data.x + data.y_data.y)

This raises the following exception (0.8):

```
lstr    C:\Anaconda\lib\site-packages\numba\codegen\coerce.py   101 
```

KeyError: struct { double x, double y }

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
