### ISSUE TITLE
Generalize type inference to more kinds of analysis

### ISSUE THREAD

**Issue by seibert** [numba/numba#2075]
Need way to store and query more kinds of code analyses beyond type inference.

Examples: Does this function ever acquire the GIL?

**Comment by stuartarchibald** [comment]
The compiler pipeline consumes a `state` object that acts as a store for this sort of information, there's also a `.metadata` dictionary on this object that can be used by compiler pass writers to store additional information. As of Numba 0.54 each function being compiled has a set of flags that can be either set directly or inherited from the calling function, this allowing per-function fine grained control of features. Am going to close this and https://github.com/numba/numba/issues/2076 as I think the current compiler API can be extended as necessary to meet the described needs.
