### ISSUE TITLE
Partial evaluation pass during compilation for type-dependent code paths

### ISSUE THREAD

**Issue by seibert** [numba/numba#2082]
This will allow a more natural way to select alternate code paths with compile-time evaluation of functions like isinstance.

**Comment by sklam** [comment]
Branch pruning and support for Literal types helped in this direction.

**Comment by stuartarchibald** [comment]
Partial type-inference is also used in e.g. the `literal_unroll` pass to part-type the IR.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/7244 implements `isinstance`, closing.
