### ISSUE TITLE
Fast math and other optimization options

### ISSUE THREAD

**Issue by seibert** [numba/numba#2086]
LLVM could do additional math optimizations if we allowed functions to opt into fast math flags.  There may be other optimizations that are unsafe in general, but useful when the user can opt into them.

This needs further investigation and an NBEP.

**Comment by sklam** [comment]
[This ML post](https://groups.google.com/a/continuum.io/d/msgid/numba-users/def984e6-1579-43ef-8b20-bd2445b03f7d%40continuum.io) show that fast-math is necessary for LLVM autovectorization to kick in

**Comment by seibert** [comment]
Support for fast math was merged in #2267
