### ISSUE TITLE
Code generation improvements for better SIMD utilization

### ISSUE THREAD

**Issue by seibert** [numba/numba#2088]
It is quite likely that LLVM's autovectorizer is not fully taking advantage of SIMD instructions due to issues with the LLVM IR that Numba emits.  We may also need to reverse engineer the IR that clang emits.

**Comment by stuartarchibald** [comment]
Given all the work with `fastmath` etc, can this be closed now?

**Comment by sklam** [comment]
With the refcount improvement we are doing now, we are moving closer

**Comment by stuartarchibald** [comment]
Closing as this ticket has largely been addressed by https://github.com/numba/numba/pull/6266 and https://github.com/numba/numba/pull/3847. If new instances of specific missed SIMD optimisations are encountered please open new tickets with example code. Thanks.
