### ISSUE TITLE
try/except and try/finally in nopython mode

### ISSUE THREAD

**Issue by seibert** [numba/numba#2097]

**Comment by ehsantn** [comment]
Any updates on this?

**Comment by seibert** [comment]
None so far.  You can raise an exception in nopython mode with static arguments and it will propagate out to the Python interpreter.

**Comment by stuartarchibald** [comment]
Basic support for try/except was implemented in https://github.com/numba/numba/pull/4902 for version 0.47.0

**Comment by esc** [comment]
Not sure  when it was added, but the construct appears to work on current `master`:

```python
from numba import njit


@njit
def foo():
    try:
        x = 1
        raise Exception
    except Exception:
        pass
    finally:
        x += 1
    return x


print(foo())
```


```
 💣 zsh» python issue2097.py                                                                                                                                        :(
2
```

Hence I am closing this issue as the functionality requested has been implemented.
