### ISSUE TITLE
iterators should be passable between nopython mode functions

### ISSUE THREAD

**Issue by seibert** [numba/numba#2099]

**Comment by stuartarchibald** [comment]
Mainline for the upcoming 0.55 release has this working:
```python
from numba import njit
import numpy as np

@njit
def bar(z):
    return next(z)

@njit
def foo(y):
    x = iter(y)
    return bar(x)

foo(np.arange(5))
```
Closing, assuming that this was the behaviour requested, if not, please reopen with an example of the behaviour that is missing. Thanks.
