### ISSUE TITLE
Masked array support

### ISSUE THREAD

**Issue by seibert** [numba/numba#2103]
The would be handy in some cases, but not a high priority

**Comment by ml31415** [comment]
Side note, this was already asked for in #1834. I'd suggest to close one of them.

**Comment by zxdawn** [comment]
It seems still doesn't support.

**Comment by stephenworsley** [comment]
Just to mention masked arrays come up a bit in a meteorological context (Iris).

**Comment by stuartarchibald** [comment]
Closing as duplicate of https://github.com/numba/numba/issues/1834
