### ISSUE TITLE
numpy windowing functions

### ISSUE THREAD

**Issue by seibert** [numba/numba#2105]
Given various FFT use cases for Numba, these would also be helpful:

http://docs.scipy.org/doc/numpy/reference/routines.window.html

**Comment by stuartarchibald** [comment]
**Order statistics**

- [ ] amin
- [ ] amax
- [ ] nanmin
- [ ] nanmax
- [ ] ptp
- [ ] percentile
- [ ] nanpercentile

**Averages and variances**

- [ ] median
- [ ] average
- [ ] mean
- [ ] std
- [ ] var
- [ ] nanmedian
- [ ] nanmean
- [ ] nanstd
- [ ] nanvar

**Correlating**

- [ ] corrcoef
- [ ] correlate
- [ ] cov

**Histograms**

- [ ] histogram
- [ ] histogram2d
- [ ] histogramdd
- [ ] bincount
- [ ] digitize

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/4076, closing.
