### ISSUE TITLE
Document the `@intrinsic` decorator

### ISSUE THREAD

**Issue by seibert** [numba/numba#2106]
Added in #2019, the `@intrinsic` decorator is not documented yet while we try using it internally first.  This is a placeholder issue to remind us to document it.

**Comment by ehsantn** [comment]
I just ran into this trying to explain Numba code.

**Comment by stuartarchibald** [comment]
Added this to the 0.44 milestone as it's a relatively short task.

**Comment by stuartarchibald** [comment]
Closing, fixed in #4548
