### ISSUE TITLE
API for Numba IR rewrite passes

### ISSUE THREAD

**Issue by seibert** [numba/numba#2107]
There is currently no official API for adding rewrite passes to the compiler.  We should fix that, as external projects may want to add support for various optimizations or custom code transformations.

**Comment by stuartarchibald** [comment]
Can this be closed given there's [an API available to implement compiler passes, and also entirely new compiler pipelines](https://numba.readthedocs.io/en/stable/developer/custom_pipeline.html), this in general covering rewrites?

**Comment by stuartarchibald** [comment]
Closing as covered by the referenced link. Thanks for raising this.
