### ISSUE TITLE
"Scumba"

### ISSUE THREAD

**Issue by seibert** [numba/numba#2109]
Placeholder for a spin-off project that exposes SciPy functionality to Numba.  (There are various special functions with C symbols that we can take advantage of.)

**Comment by datnamer** [comment]
Would this include scipy distributions? http://docs.scipy.org/doc/scipy/reference/stats.html

**Comment by synapticarbors** [comment]
@datnamer In the short term, if you are looking for scipy distributions, you might be interested in https://github.com/QuantEcon/rvlib. The basic idea is that they wrapped the Rmath library using cffi and numba. I posited the idea previously in a [blog post](https://www.continuum.io/blog/developer-blog/calling-c-libraries-numba-using-cffi). Something similar was also proposed by [wrapping cephes](http://pybonacci.org/2016/02/07/como-crear-extensiones-en-c-para-python-usando-cffi-y-numba/).

**Comment by datnamer** [comment]
Thanks!

**Comment by stuartarchibald** [comment]
See "scumba" discussion here: https://github.com/numba/numba/issues/4292

**Comment by stuartarchibald** [comment]
Scumba started... https://github.com/numba/numba-scipy closing.
