### ISSUE TITLE
Automatically propose alternate function signatures when TypingError occurs

### ISSUE THREAD

**Issue by seibert** [numba/numba#2111]
If a function is known to Numba, but not with the types passed by the user, the TypingError should print a list of known function signatures to indicate to the user which types are allowed.

(Due to coercion rules, the list of accepted signatures will not be complete, but hopefully will be enough to give the user an idea of where the problem is if they try to take the square root of a set.)

**Comment by sklam** [comment]
This does happen for non-generic functions:

such as 

```python
>>> from numba import njit
>>> @njit
... def foo(x):
...     return math.sqrt(x)
... 
>>> import math
>>> foo(1.2)
1.0954451150103321
>>> foo(())

```

```
Invalid usage of Function(<built-in function sqrt>) with parameters (())
Known signatures:
 * (int64,) -> float64
 * (uint64,) -> float64
 * (float32,) -> float32
 * (float64,) -> float64
File "<stdin>", line 3
```

**Comment by seibert** [comment]
Closing, since we do this already, as mentioned above.
