### ISSUE TITLE
ValueError: cannot compute fingerprint of empty list

### ISSUE THREAD

**Issue by dickreuter** [numba/numba#2152]
```
from numba import jit
@jit()
def create_card_deck():
    values = "23456789TJQKA"
    suites = "CDHS"
    Deck = []
    for x in values:
        for y in suites:
            Deck.append(x + y)
    return Deck

create_card_deck()
```

**Comment by synapticarbors** [comment]
A work around is to create the list with an initial item of the same type as you are going to add and then throw it away before you return:

```python
from numba import jit

@jit
def create_card_deck():
    values = "23456789TJQKA"
    suites = "CDHS"
    Deck = ['x']
    for x in values:
        for y in suites:
            Deck.append(x + y)
    return Deck[1:]
```

**Comment by dickreuter** [comment]
Ok makes sense. Thanks

**Comment by stuartarchibald** [comment]
Related comments on what needs to happen to fix this are at the bottom of https://github.com/numba/numba/pull/2184

**Comment by Permafacture** [comment]
So, how does the closing of #2184 affect this issue?  Is it now intentional to disallow empty lists being passed into nopython jitted functions?

**Comment by stuartarchibald** [comment]
As of 0.42.0 the original sample works (updates have been made to type inference to help type empty lists). Closing.

**Comment by Mostro-Complexity** [comment]
When I use version 0.44.1 numba, the above problem still occurs.
my code:
`@nb.njit
def func(X, a, b):
    # X = np.zeros(shape=(10, 10))
    if len(a) > 0 and len(b) > 0:
        for i in range(X.shape[1]):
            X[:, :i] += i

    # F = np.array([foo(X[i, :]) for i in range(X.shape[0])])
    return np.empty(X.shape[0], dtype=np.float64)


func(np.zeros((10, 10)), [], [])
`
Error message:
```
Exception has occurred: ValueError
cannot compute fingerprint of empty list
```

**Comment by stuartarchibald** [comment]
@Mostro-Complexity reflected lists (what you are using) are in the process of being deprecated, please take a look at their replacement, `numba.typed.List`, [docs are here](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#typed-list). Thanks.

**Comment by shaunc** [comment]
I'm getting the equivalent error for `set`. There doesn't seem to be any equivalent to `numba.typed.List` for set? (At least, not in doc.) Should I open a tracking issue ... or is this otherwise in the works?

**Comment by esc** [comment]
> Upshot: typed set is at least documented as not yet implemented.

Yup it's on the wishlist. It is quite the undertaking and will require lot's of code to be written.It will however be reasonably well isolated from the rest of the code base, since the feature will be largely additive. And, in addition there are two existing typed container implementations, `List` and `Dict` that can be cribbed from. Essentially, it involves taking the `set` implementation from `cpython` and transplanting it into Numba (and it's runtime) and making it usable from there.
