### ISSUE TITLE
llvmlite 0.14 requirement

### ISSUE THREAD

**Issue by fabriziov** [numba/numba#2154]
Numba now requires llvmlite 0.14 (see requirements.txt) even if llvmlite 0.14 is still under development (even the 0.14-dev version is recognized as 0.13 by Numba at the moment).

**Comment by seibert** [comment]
We are in the middle of our release process today.  We typically synchronize our llvmlite releases with numba releases.  Both should come out at the same time.

**Comment by seibert** [comment]
llvmlite 0.14 and Numba 0.29 were released yesterday to PyPI and conda.  I think this should all be sorted out now.
