### ISSUE TITLE
0.29 _typeconv import issue

### ISSUE THREAD

**Issue by apiszcz** [numba/numba#2158]
Traceback (most recent call last):
  File "lib\testapp\testapp.py", line 2311, in <module>
    import numba
  File "C:\p\testapp\lib\numba\__init__.py", line 12, in <module>
    from .special import typeof
  File "C:\p\testapp\lib\numba\special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "C:\p\testapp\lib\numba\typing\__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "C:\p\testapp\lib\numba\typing\context.py", line 10, in <module>
    from numba.typeconv import Conversion, rules
  File "C:\p\testapp\lib\numba\typeconv\rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\p\testapp\lib\numba\typeconv\typeconv.py", line 3, in <module>
    from . import _typeconv, castgraph, Conversion
ImportError: cannot import name '_typeconv'

**Comment by seibert** [comment]
Is this an installation from source?  This looks like the C extensions were not built.

**Comment by apiszcz** [comment]
Windows, no not from source
​
http://www.lfd.uci.edu/~gohlke/pythonlibs/#numba​

**Comment by seibert** [comment]
Hmm, this sounds like this might be an issue with the Gohlke package build.  We are not involved with these builds, and it sounds like Gohlke isn't providing any support for these packages.  You could report the issue to him, but I don't know if he will have any time to fix it.

We build and test binary packages for Anaconda on Windows/Mac/Linux, so that's the only other suggestion we can offer.

**Comment by cgohlke** [comment]
Can't reproduce.

**Comment by seibert** [comment]
With our conda packages, we've sometimes seen a strange error like this if the binary package is installed while package files are open (due to how windows handles file locks).  You could try forcing a reinstallation when you are sure no other python instances are running.

**Comment by cgohlke** [comment]
While I can't reproduce this error, I get a `LLVM IR parsing error` in production code with llvmlite-0.14.0. Had to revert to previous numba/llvmlite for now.

```
X:\Python35\lib\site-packages\numba\targets\codegen.py in add_ir_module(self, ir_module)
    147         assert isinstance(ir_module, llvmir.Module)
    148         ir = cgutils.normalize_ir_text(str(ir_module))
--> 149         ll_module = ll.parse_assembly(ir)
    150         ll_module.name = ir_module.name
    151         ll_module.verify()

X:\Python35\lib\site-packages\llvmlite\binding\module.py in parse_assembly(llvmir)
     20         if errmsg:
     21             mod.close()
---> 22             raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
     23     return mod
     24 

RuntimeError: Failed at object (object mode frontend)
Failed at object (object mode backend)
LLVM IR parsing error
<string>:767:55: error: expected type
  %".600" = call i8* (i64) @"PyLong_FromSsize_t"(i64 (0, 0))
```

**Comment by seibert** [comment]
This looks very strange.  I'm going to open a new issue in the llvmlite repo to track the parser error.

**Comment by apiszcz** [comment]
This was an easy one, I download python 3.6 and needed 3.5. No issue.

**Comment by seibert** [comment]
OK, glad you figured it out.  The IR parse error will be tracked in the llvmlite repo.
