### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by seibert** [numba/numba#2160]
This issue is for tracking support for Python 3.6.

**Comment by seibert** [comment]
See #2142

**Comment by seibert** [comment]
More info:

In addition to #2142, it looks like the opcode for `CALL_FUNCTION_*` have changed:

https://bugs.python.org/issue27213

`CALL_FUNCTION_VAR` and `CALL_FUNCTION_VAR_KW` (which we didn't support) are no more, and now there is a `CALL_FUNCTION_EX` opcode.

**Comment by seibert** [comment]
BTW, here is my somewhat clunky recipe for getting a Python 3.6b3 conda environment from the conda-forge package:
```
conda create -n test_py36  # This creates an empty environment
source activate test_py36

# Install various C/C++ dependencies because the conda dependencies won't work below
conda install -c numba openssl=1.0 readline=6.2 sqlite=3.13 tk=8.5 xz=5.2 zlib=1.2 llvmdev=3.8

# Downloading and installing the package manually seems to work around some dependency issues
#   Change platform to linux-64 if you are using that
wget https://anaconda.org/conda-forge/python/3.6.0b3/download/osx-64/python-3.6.0b3-0.tar.bz2 
conda install python-3.6.0b3-0.tar.bz2

# Now install pip so we can build some packages from source
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

export MACOSX_DEPLOYMENT_TARGET=10.9
pip install numpy
pip install llvmlite

git clone git@github.com:numba/numba.git numba_py36
```

**Comment by seibert** [comment]
@sklam: Not sure what else is in your todo list, but we need to start looking at the Python 3.6 changes pretty soon to make sure we're ready by mid-December.

**Comment by sklam** [comment]
@seibert, I'm on it.

**Comment by sklam** [comment]
all opcodes now have a fixed size of 16 bits.
