### ISSUE TITLE
custom kernel names for profiling

### ISSUE THREAD

**Issue by Escapado** [numba/numba#2164]
Hello,
I'd like to propose a small enhancement for kernel names to improve readability when profiling performance of cuda kernels, something like:

```
@cuda.jit(pretty_name='awesome_kernel')
def awesome_kernel(x,y,z):
    ....
```

Because when profiling applications in nvprof I usually look at stuff like this: 

```
Time(%)      Time            Calls       Avg             Min            Max            Name

 36.46%      3.36205s        100         33.621ms        33.252ms       34.024ms       cudaPy_prog_2E_util_2E_cuda_5F_methods_2E_awesome_5F_kernel_5F_gpu_24_51_2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_array_28_float64_2C__20_1d_2C__20_A_29__2E_float64_2E_float64_2E_int64_2E_float64_2E_float64_2E_int64_2E_array_28_complex128_2C__20_5d_2C__20_A_29__2E_array_28_int32_2C__20_1d_2C__20_A_29__2E_array_28_int32_2C__20_1d_2C__20_A_29_
```

This is rather unreadable, especially when you have many kernels with many arguments. So it would be nice to just see:

```
Time(%)     Time           Calls      Avg            Min           Max           Name

36.46%      3.36205s       100        33.621ms       33.252ms      34.024ms      awesome_kernel
```

I raised this question in the numba google group a few months ago and there was a work-around mentioning replacing the string post-output but it would be nice to have a out of the box solution.

**Comment by seibert** [comment]
I agree this would be helpful.  @sklam: In addition to this, is there a way to make the name mangling more friendly (i.e. more C++ like) to nvprof?

**Comment by sklam** [comment]
we do have a minimal itanium mangler that should improve things.

**Comment by seibert** [comment]
With the improvements to name mangling that are now debugger-friendly, I think we can close this.
