### ISSUE TITLE
Problems with numpy array iteration

### ISSUE THREAD

**Issue by meowklaski** [numba/numba#2212]
I am getting bad behavior dealing with numpy-array iteration. The following shows an error when invoking `ndenumerate`. I get the same behavior when calling `.flat` on an array.  

## ndenumerate
```python
import numpy as np
import numba

def f():
    x = np.arange(6).reshape(2, 3)
    for index, item in np.ndenumerate(x):
        return index, item

jitted_f = numba.jit(f)
```
```python
>>> print(numba.__version__)
0.29.0

>>> print(f())
((0, 0), 0)

>>> print(jitted_f())
((0, 0), -2387225703656530210)
```

## flat
```python
def f():
    x = np.arange(6).reshape(2, 3)
    for item in x.flat:
        return item

jitted_f = numba.jit(f)
```
```python
>>> print(numba.__version__)
0.29.0

>>> print(f())
0

>>> print(jitted_f())
-2387225703656530210
```

This occurs in Python 3.5 for `numba 0.29.0`, and in Python 2.7 in `numba 0.29.0+0.gead0dd3.dirty`

**Comment by meowklaski** [comment]
Just curious - will this be in a 0.29.1 bugfix release? It seems like people who make use of `ndenumerate` and the like are in deep trouble, presently. It was fortunate that I tested it before making use of it!

P.S. Thanks for the light-speed fix!

**Comment by sklam** [comment]
There will be a 0.30 release in about two weeks.
There are also nightly builds at our dev channel at https://anaconda.org/numba/numba .  You can get it with `conda install -c numba numba`.
