### ISSUE TITLE
segfault when allocating arrays in multithreaded program

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#2213]
I wrote a very complex project based on dask. The dask operations are numba kernels interleaved with basic dask functions. My numba kernels all look more or less like this:
```
@jit(nopython=True, nogil=True, cache=True)
def kernel(input):
    output = numpy.empty_like(input)
    # skip: fill output
    return output
```
The dask arrays are chunked in a way that the same numba kernel will typically be applied 8 times in parallel (once per thread) to different chunks of the same dask array.

All kernels pass all unit tests, and even the end-to-end dask tree resolves fine as long as you have tiny data involved (e.g. 1 chunk). However, as soon as I move to production-scale data (8+ chunks per dask array and 8 threads), the Python interpreter starts randomly crashing with segmentation faults. Once it also crashed with a double free() error.

Things that make the issue disappear:
1. Commenting out the @jit decorators
2. Limiting the number of threads to 1
3. Rewriting all kernels as follows:
```
def kernel(input):
    output = numpy.empty_like(input)
    kernel2(input, output)
    return output

@jit(nopython=True, nogil=True, cache=True)
def kernel2(input, output):
    # skip: fill output
```
Alas I cannot _consistently_ reproduce the bug, and I am not 100% sure yet of fix n.3 above.

**Comment by crusaderky** [comment]
Running numba-0.29 and numpy-1.11.2 on Anaconda3 64 bit (latest) on Ubuntu.

**Comment by seibert** [comment]
Speculating based on similar sounding bugs in the past: This might be a race condition in LLVM compilation in multiple threads when unpickling? @sklam: Ideas how we could check that?

**Comment by seibert** [comment]
Or it is a threading bug in the memory management in the Numba runtime.

**Comment by pitrou** [comment]
Can you run your workload with the `PYTHONFAULTHANDLER` environment variable set? This will dump the tracebacks of Python thread on a crash.

Also, please enable core dumps with `ulimit -c unlimited`. Then you'll be able to use gdb on the core dump file produced by the crash.
The core dump file will probably be saved in `/tmp`. You can check this by looking at `/proc/sys/kernel/core_pattern`.

**Comment by sklam** [comment]
Could this be related to caching?  Also, which dask scheduler is being used?

**Comment by crusaderky** [comment]
Hello, sorry for the long silence.
I'm afraid I rewrote all numba functions in cython now - a decision mostly driven by project deadlines.
I still have the old numba logic at hand, so eventually I'll spend some time trying to reproduce the issue again - just I'm afraid I don't have time right now.

@sklam I'm using dask.threaded.get.

**Comment by pitrou** [comment]
I tried to reproduce using a heavily multi-threaded allocation workload, but failed. It may be that the original code is slightly incorrect and writes past array bounds, which could overwrite allocation-related structures in certain cases. Without a reproducer, it is difficult to investigate further.

**Comment by crusaderky** [comment]
Antoine,
My code being wrong was of course the first thing I checked. However if I
removed @jit, everything else being identical (including data) , I was not
getting any exceptions such as IndexError.

**Comment by pitrou** [comment]
@crusaderky, thanks for the answer. It would be really nice if you could devise some reproducer for us.

**Comment by sklam** [comment]
We received a similar report for this problem.  We are able to trace it to a problem with race condition during concurrent compilation with caching enabled.   The array allocation is likely just a red herring that increases the compilation time, making it more likely to cause a race condition.
