### ISSUE TITLE
Code that functions on numba 28.1 raises LoweringError on 29.0

### ISSUE THREAD

**Issue by Auerilas** [numba/numba#2222]
I just tried to run some old code:

```
#%% forward simulation
@jit
def ind_sim(temp, pred, D):
	x_init = 1				# initial body size
	simulated_sizes = np.zeros(t_max)
	simulated_u = np.zeros(t_max)
	simulated_sizes[0] = x_init
	dead_pred = 0						# starts out alive
	dead_starve = 0					# starts out alive
	total_cons = np.zeros(t_max)				# with nothing consumed
	for t in range(t_max-1):
		mass_idx = int(simulated_sizes[t])		# convert the mass to an integer index
		current_size = simulated_sizes[t]		# get the current body size
		u = D[mass_idx,t]				# get the optimal u
		simulated_u[t] = u 				# store optimal u
		p_m = prob_mort(pred, u, current_size,temp)	# calculate current probability of mortality
		if current_size==0:					# if dead, leave it dead			
			simulated_sizes[t+1] = 0
		random_predation = np.random.random()		# random number for predation
		if random_predation < p_m:				# if it dies, kill it
			simulated_sizes[t+1] = 0
			dead_pred = 1
			break
		else:
			consumption = np.random.binomial(R, u, 1)	# random variable of intake
			xp = current_size - metabolic_fmr(current_size, u, temp) + consumption	# new mass
			xp = np.maximum(xp, x_min)
			xp = np.minimum(xp, x_max)
			total_cons[t] = consumption
			if xp==0.0:
				dead_starve = 1
				dead_pred = 0
				break
			else:
				simulated_sizes[t+1] = np.round(xp)
	return simulated_u, simulated_sizes, dead_pred, dead_starve, total_cons
```

This works on 28.1 and 29.0. I understand that there is another issue related to this error #2159 

I was wondering if there is a workaround for the time being until 0.30 is released?

**Comment by seibert** [comment]
@sklam: Does 0.30 fix this bug as well?

**Comment by sklam** [comment]
It should if it is the same issue as #2159.  But, there are not enough info to check.

**Comment by Milfadic** [comment]
I am having the same problem. Has the issue been fixed?

**Comment by seibert** [comment]
The bug in this issue was likely fixed by Numba 0.30.  What version are you using?

**Comment by Milfadic** [comment]
I am using Numba version 0.30. I am trying to replicate  [this](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/linear_models/lss_solutions_py.ipynb) code from Quantecon

And get the following error
`LoweringError: Failed at object (object mode frontend)
Failed at object (object mode backend)
(<class 'numba.ir.StaticSetItem'>, x[(slice(None, None, None), 0)] = x0)
File "..\..\..\Anaconda3\envs\python3\lib\site-packages\quantecon\lss.py", line 48
[1] During: lowering "x[(slice(None, None, None), 0)] = x0" at C:\...\Anaconda3\envs\python3\lib\site-packages\quantecon\lss.py (48)`

**Comment by seibert** [comment]
I think your error is not related to this issue.  Can you open a new issue?  The problem appears to be triggered by this line of code:

``` python
x[:, 0] = x0
```

https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/lss.py#L48

**Comment by Milfadic** [comment]
Thanks for the fast reply. I will do so. Regards!

**Comment by sklam** [comment]
I think there is a logic error in the code:

```
x[:, 0] = x0
```

According to the docstring, `x0` is a `(n, 1)` array and `x[:, 0]` is a `(n,)` array.  Numpy doesn't allow broadcasting `(n, 1)` to `(n,)`.

**Comment by seibert** [comment]
Closing old issues.
