### ISSUE TITLE
Caching gufunc wrapper

### ISSUE THREAD

**Issue by sklam** [numba/numba#2225]
... to improve further reduce import time.

Extends https://github.com/numba/numba/pull/2190

**Comment by sklam** [comment]
Testcase: https://gist.github.com/sklam/fe5569992eab4a6ff0c17ef2d08b5870

A significant amount of time is spent building the wrapper.

**Comment by sklam** [comment]
I have a hack that would make cache the wrapper.  I will push a patch once I clean it up.

**Comment by seibert** [comment]
This was completed.
