### ISSUE TITLE
build with python 3.6

### ISSUE THREAD

**Issue by neok-m4700** [numba/numba#2233]
Hi, I've built numba 0.30.0 with llvmlite 0.15.0 and LLVM 3.8.1 together with python 3.6.0 on Ubuntu 16.10.

I get this error when I import the module. I had no issue with python 3.5.2 - numba 0.29.0 - llvmlite 0.14.0 - LLVM 3.8.1

```python
Traceback (most recent call last):
  File "<...>/run_test.py", line 1, in <module>
    import numba
  File "<...>/_t_env/lib/python3.6/site-packages/numba/__init__.py", line 23, in <module>
    from .decorators import autojit, cfunc, generated_jit, jit, njit
  File "<...>/_t_env/lib/python3.6/site-packages/numba/decorators.py", line 11, in <module>
    from .targets import registry
  File "<...>/_t_env/lib/python3.6/site-packages/numba/targets/registry.py", line 8, in <module>
    from .. import dispatcher, utils, typing
  File "<...>/_t_env/lib/python3.6/site-packages/numba/dispatcher.py", line 620, in <module>
    dict((str(t), t._code) for t in types.number_domain))
MemoryError
```

What could be triggering this ?

**Comment by s-m-e** [comment]
Hard to say whether or not this is related ... similar-ish scenario though.

System: Python 3.6.0 built with GCC 6.1.0 and CPython's new "--enable-optimizations" flag plus llvmlite 0.15.0 & LLVM 3.8.1 on an x86/32bit openSUSE Linux. Clean virtual environment with, next to the previously listed packages, numpy 1.11.3 (pre-build binary installed with pip) in it only. 

Problem: "import numba" apparently triggers a race condition. The python interpreter becomes completely unresponsive, running indefinitely while requiring 100% of one CPU core. No further output. Only SIGKILL sent from another shell stops it.

**Comment by seibert** [comment]
Due to overlap of the Python 3.6 and Numba 0.30 release, there was an issue we didn't find until after the release.  Current git master should work with Python 3.6, and Numba 0.31 (released in about 3 weeks) will as well.

**Comment by neok-m4700** [comment]
Thanks @seibert , so this commit cd2945f6519c423fa424d64d9f40bedf7a9ca91d is fixing the issue (after 0.31.0.dev).

@s-m-e 
just tried with gcc 6.3.0 - llvm 3.8.1 - python 3.6.0 (**with** --enable-optimizations) - llvmlite v0.16.0.dev - numba cd2945f - numpy 1.11.13

no issue with the (forced) python test suite 'test.regrtest', nor numba

does  `python -c 'import numpy as np; np.test()'` pass without failure ?
did you build all the dependencies (e.g. setuptools with this version of python ?)

**Comment by s-m-e** [comment]
@neok-m4700
Thanks for looking into this. Everything except numpy was built from scratch. The numpy test reports 6182 tests run, resulting in "OK (KNOWNFAIL=7, SKIP=4)" - so no (obvious) problem here. I'll check what happens if I build numpy myself and upgrade to numba cd2945f and report back with results.

**Comment by s-m-e** [comment]
@neok-m4700
numba cd2945f solves the issue for me. No need to build numpy from scratch.
