### ISSUE TITLE
Feature request: compilation caching

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [numba/numba#224]
I do not know if this fits at all with the design of numba, but it would be really great to have some form of compilation caching. Right now my compilation times are already close to a minute for some 200 lines of numba code, which really messes with my REPL workflow.

Id imagine this is hard to solve generally given numbas design, but is there a way to quickly hash the AST, and check for changes? Or if not, even just a manual flag to the jit decorator to force caching would be great, for functions which we know we havnt touched in ages. That is, as soon as a function is crystallized, flag it as such, and have a version read from disk afterwards.

Would this be easy to add, and would there be others with an interest in this? I don't know much about the LLVM backend stuff myself, but this is a feature I might try adding myself.

**Comment by jfemiani** [comment]
+1

**Comment by moble** [comment]
Looks like a `cache` flag has been added to [`numba.jit`](http://numba.pydata.org/numba-doc/dev/reference/compilation.html), evidently coming from PR #1051.  From that discussion, it looks like caching doesn't work on closures, functions with lifted loops, or functions calling ctypes/cffi function pointers.

**Comment by pitrou** [comment]
Indeed, this is now fixed.
