### ISSUE TITLE
Make threading interface between Numba and workqueue module more suitable for parallel for calls

### ISSUE THREAD

**Issue by anton-malakhov** [numba/numba#2245]
Currently, the interface provided by workqueue module and described in `workqueue.h` suggests the following interface:
* launch_threads(int count)
* add_task(void *fn, void *args, void *dims, void *steps, void *data)
* ready()
* synchronize()

and this https://github.com/numba/numba/blob/master/numba/npyufunc/parallel.py#L63  defines how these functions are called.
While it is possible to assume types of `add_task` pointers according to the comment: `char **args, npy_intp *dimensions, npy_intp* steps,`, it would be good to have these documented as part of `add_task`. That would allow to implementing splitting of the array(s) to tasks/chunks on the level of threading layer rather than inside `parallel.py` and remove or disable code-generation for this splitting. It is possible now to supply NPY_NUM_THREADS=1 to partially achieve this goal, but it'd be good to have clean interface instead.

Thus, intermediate solution would be adding missing types to `add_task()` and returning the number of threads from the module and if the number of threads == 1, do not generate any splitting in the kernel, but call `add_task()` once following by `synchronize()` immediately.

Complete solution would be to replace `add_task()`, `ready()`, and `synchronize()` with just one call to: 
`parallel_for(void *fn, char **args, int ndim, npy_intp *dimensions, npy_intp* steps, void *data)` which will split the work across dimensions by itself.

**Comment by sklam** [comment]
I like the idea here.

FYI, the `build_ufunc_kernel` (https://github.com/numba/numba/blob/master/numba/npyufunc/parallel.py#L63) is building something like the `double_logit` described in https://docs.scipy.org/doc/numpy/user/c-info.ufunc-tutorial.html which I pasted below.  

```C
static void double_logit(char **args, npy_intp *dimensions,
                         npy_intp* steps, void* data)
{
    npy_intp i;
    npy_intp n = dimensions[0];
    char *in = args[0], *out = args[1];
    npy_intp in_step = steps[0], out_step = steps[1];

    double tmp;

    for (i = 0; i < n; i++) {
        /*BEGIN main ufunc computation*/
        tmp = *(double *)in;
        tmp /= 1-tmp;
        *((double *)out) = log(tmp);
        /*END main ufunc computation*/

        in += in_step;
        out += out_step;
    }
}
```

The reason for the codegen was to avoid any dynamic allocation necessary in a monomorphic code to handle the variable number of arguments (length of `args` and `steps`).  And, in the gufunc case, the length of dimensions (see https://github.com/numba/numba/blob/master/numba/npyufunc/parallel.py#L319).   So, the `parallel_for` will need two extra arguments: `args_length` and `dimensions_length`.

**Comment by stuartarchibald** [comment]
@anton-malakhov I've added an implementation here: https://github.com/stuartarchibald/numba/tree/wip/parallel_for_1

The function signature for `parallel_for_1d` is found here: https://github.com/stuartarchibald/numba/blob/1e6afa4ccbf811cdea4483b0a3283686444cff3a/numba/npyufunc/workqueue.h#L41-L62

The Python side call site is here: https://github.com/stuartarchibald/numba/blob/1e6afa4ccbf811cdea4483b0a3283686444cff3a/numba/npyufunc/parallel.py#L320-L332

I'm not convinced by the implementation itself *yet* but it seems to work (unit tests pass).

**Comment by ehsantn** [comment]
@stuartarchibald will we have the same dependencies to Numpy's GUFUNCs as before?

**Comment by stuartarchibald** [comment]
In the current impl, yes, as it just shuffles where functionality exists between C library code and LLVM IR.

**Comment by anton-malakhov** [comment]
I've added the TBB layer for it: https://github.com/stuartarchibald/numba/pull/1

**Comment by stuartarchibald** [comment]
Work completed in https://github.com/numba/numba/pull/3202 closing.
