### ISSUE TITLE
Errors during bytecode analysis should result in user-comprehensible messages (with source location)

### ISSUE THREAD

**Issue by stefanseefeld** [numba/numba#2250]
I am running into this exception:
```
AttributeError: 'DataFlowAnalysis' object has no attribute 'op_LOAD_CLOSURE'
```
This isn't helpful to users. Instead, it would be useful to tell users

* that the error is caused by an as-of-yet unsupported Python construct
* which statement (Python source location) triggered this

such that they can attempt to change their code to work around the limitation.
(This is similar inspirit to https://github.com/numba/numba/issues/2112.)

**Comment by stefanseefeld** [comment]
https://github.com/numba/numba/pull/2251 improves the error messages substantially.

**Comment by sklam** [comment]
https://github.com/numba/numba/pull/2329 have addressed this.
Closing.
