### ISSUE TITLE
How can I inspect_types etc. for jitclass methods?

### ISSUE THREAD

**Issue by krey** [numba/numba#2257]
All I have to go on in this [stackoverflow question](http://stackoverflow.com/questions/39638721/is-there-something-like-inspect-types-for-a-numba-jitclass), which indicates that this probably wasn't possible in September.

**Comment by sklam** [comment]
You can use `numba --annotate yourscript.py` or equivalently `NUMBA_DUMP_ANNOTATION=1 yourscipt.py`.  That forces all compiled code to dump the type annotation.  

To do that selectively, you need to use internal API (that is not guaranteed to be stable).  For a jitclass `Foo`, it has a `.class_type` attribute to access the underlying numba type object.  All the methods are in `Foo.class_type.instance_type.jitmethods`, which is a dictionary of `method name => dispatcher`.  The dispatcher, which is the object for any `@jit`'ed function, has the `.inspect_types()`

Putting it all together:

```python
from numba import jitclass, types

spec = [
    ('a', types.int32),
    ('b', types.float32),
]
@jitclass(spec)
class Foo(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def bar(self):
        return self.a + self.b


foo = Foo(1, 2)
foo.bar()

Foo.class_type.instance_type.jitmethods['bar'].inspect_types()
```
