### ISSUE TITLE
Support `type` property for dtypes

### ISSUE THREAD

**Issue by ma-ba** [numba/numba#2259]
`numpy.dtype` instances have a property `type` which returns the corresponding scalar type.
This is currently not supported so that something like the following does not work directly:
```python
from numba import njit

@njit
def f(a):
    if a[0] != 1:
        return a[0]
    return a.dtype.type(0)
f(np.arange(2))
```
From mailing list: https://groups.google.com/a/continuum.io/d/msg/numba-users/x2_866BbQ0M/FyfEmeHuAwAJ

**Comment by ma-ba** [comment]
Duplicate of #2260, closing.

**Comment by sklam** [comment]
oops, I missed this issue.
