### ISSUE TITLE
fix the implementation of non math-related instructions

### ISSUE THREAD

**Issue by cpcloud** [numba/numba#227]
Allow users to declare an instruction that isn't a unary/binary mathematical function, e.g., `fcmp = declare_instruction(..., 'fcmp')` that takes an LLVM comparison type constant and the two values being compared. `isnan` functionality would come for free from this.

**Comment by pitrou** [comment]
Numba doesn't sound like the right target for this. Assuming the desired functionality isn't already exposed, llvmlite would be a better place for such low-level functionality.
