### ISSUE TITLE
Sum across single dimension bug

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#2270]
Numba returns wrong results for `sum()` across a single dimension. For example, the following program should return `array([ 3.,  3.])` but it returns `6.0`.

Also, it infers the output type for `sum()` as a constant. 
```
import numpy as np
import numba

@numba.njit
def sum_test(X):
    return X.sum(1)

A = np.ones((2,3))
print(sum_test(A))
```

**Comment by synapticarbors** [comment]
According to the docs, additional arguments are not supported for `sum` and other methods on `ndarray`s. My guess is it is just ignoring the argument:

http://numba.pydata.org/numba-doc/0.30.1/reference/numpysupported.html#calculation

It seems like it should fail though when it encounters something unsupported like this.

**Comment by stuartarchibald** [comment]
Just tested them all on `0.37.0.dev1`, the `calculation` functions all raise `TypingError`s with the exception of `nonzero` which doesn't take an axis arg and `sum` which is implemented as noted.

**Comment by stuartarchibald** [comment]
As of 0.47.0 this:
```python
import numpy as np
import numba

@numba.njit
def sum_test(X):
    return X.sum(1)

A = np.ones((2,3))
print(sum_test(A))
print(sum_test.py_func(A))
```
produces:
```
[3. 3.]
[3. 3.]
```
as `axis` and `dtype` kwargs are supported. Closing.
