### ISSUE TITLE
'TargetData' objects has no attribute 'add_pass'

### ISSUE THREAD

**Issue by DcoOo** [numba/numba#2276]
LLVM 3.9.1
LLVMLITE 0.15
numba 0.30.1
my python code:
`
from numba import jit
@jit
def sum(a. b):
      return a+b
print(sum(1.01, 2.001))
`

very simple code,i just want to try if i could use numba normally,then i get the output:

`
'TargeData' objects has no attribute 'add_pass'
`

**Comment by sklam** [comment]
You need to update llvmlite to use the current HEAD.  
There are development builds from `conda install -c numba llvmlite`, too.

**Comment by DcoOo** [comment]
Yeah,I have solved it.Thank you so much:)


发送自我的三星设备

-------- 原始邮件 --------
发件人： Siu Kwan Lam <notifications@github.com> 
日期: 2017-02-15  1:26 AM  (GMT+08:00) 
收件人： numba/numba <numba@noreply.github.com> 
抄送： 2014011451 <18510786796@163.com>, Author <author@noreply.github.com> 
主题： Re: [numba/numba] 'TargetData' objects has no attribute 'add_pass'
  (#2276) 

You need to update llvmlite to use the current HEAD.

There are development builds from conda install -c numba llvmlite, too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/numba/numba","title":"numba/numba","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/numba/numba"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sklam in #2276: You need to update llvmlite to use the current HEAD.  \r\nThere are development builds from `conda install -c numba llvmlite`, too."}],"action":{"name":"View Issue","url":"https://github.com/numba/numba/issues/2276#issuecomment-279775439"}}}
