### ISSUE TITLE
numba f.reduce : 'function' object has no attribute 'reduce'

### ISSUE THREAD

**Issue by ever4244** [numba/numba#2284]
Hi:
   Good Morning!
   I encounter a very strange error in my codes.
   I cut the piece of code to test and it is OK. In my larger program, however, it reports " 'function' object has no attribute 'reduce'"
   
test codes:
```
import numpy as np
from numba import vectorize, float64,float32

@vectorize([float32(float32, float32),float64(float64, float64)],nopython=True)
def add_vec(A,B):
	return A+B

def sum_avg(seq,seq_pre):
	
	print (seq_pre.shape)
	print (seq.shape)
	print (add_vec.reduce(seq,axis=0))
	

a=[float(i) for i in range(300)]
seq=[]
seq.append(a)
seq.append(a)
seq.append(a)
seq=np.array(seq)
sum_avg(seq,seq)
```

> (3, 300)
> (3, 300)
> [   0.    3.    6.    9. ...

larger program:

```
@measure_time
@vectorize([float32(float32, float32),float64(float64, float64)],nopython=True)
def add_vec(A,B):
	return A+B
	

@measure_time
#@jit(nopython=True)
def sum_avg(seq,seq_pre):
	#for debuging
	#--------------------------------
	a=[float(i) for i in range(300)]
	seq=[]
	seq.append(a)
	seq.append(a)
	seq.append(a)
	seq=np.array(seq)
	#--------------------------------

	print (seq_pre.shape)
	print (seq.shape)
	print (add_vec.reduce(seq,axis=0))
	
	if len(seq_pre)<=1:
		print ('liwei mark1')
		window_vector=add_vec.reduce(seq,axis=0)-seq_pre
	else:
		window_vector=add_vec.reduce(seq,axis=0)-add_vec.reduce(seq_pre,axis=0)
	window_vector=window_vector/(len(seq)-len(seq_pre))
	return window_vector
```

Can anybody tell me why it is like this?

> Using gpu device 5: Tesla M60 (CNMeM is enabled with initial size: 70.0% of memory, cuDNN 5103)
> Build model...
> zero3d padding ouput shape = (None, 402, 300, 12, 1)
> conv3d ouput shape = (None, 400, 1, 10, 120)
> /home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/site-packages/keras/backend/theano_backend.py:1550: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
>   mode='max')
> /home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/site-packages/keras/backend/theano_backend.py:1550: UserWarning: DEPRECATION: the 'st' parameter is not going to exist anymore as it is going to be replaced by the parameter 'stride'.
>   mode='max')
> /home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/site-packages/keras/backend/theano_backend.py:1550: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
>   mode='max')
> maxpooling3d 122 shape = (None, 200, 1, 5, 120)
> reshape shape = (None, 200, 600)
> LSTM shape = (None, 120)
> /home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/site-packages/theano/tensor/basic.py:2146: UserWarning: theano.tensor.round() changed its default from `half_away_from_zero` to `half_to_even` to have the same default as NumPy. Use the Theano flag `warn.round=False` to disable this warning.
>   "theano.tensor.round() changed its default from"
> Train...
> Build generator...
> save train dataset
> Epoch 1/1
> (1, 300)
> (3, 300)
> liwei mark1
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/wliax/Anaconda/Or/envs/myenv1/lib/python2.7/site-packages/keras/engine/training.py", line 433, in data_generator_task
>     generator_output = next(generator)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 338, in batch_generator
>     (Y_batch,X_batch)=preprocessing_pipline_efc(h5py_data,fileids_ls)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 283, in preprocessing_pipline_efc
>     X_spec_train=process_data(X_train)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 165, in process_data
>     spectrum_matrix=format_spectrum(X_sample)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 152, in format_spectrum
>     X_sample_win=map_seq(X_sample,window_size,pre_window_size)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 141, in map_seq
>     window_vector=build_window_vector(X_sample,window_size,pre_window_size,i)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 128, in build_window_vector
>     window_vector=sum_avg(seq,seq_pre)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 61, in timed
>     result = f(*args, **kw)
>   File "2_liwei_efc_spec_CNN_LSTM.py", line 116, in sum_avg
>     window_vector=add_vec.reduce(seq,axis=0)-seq_pre
> AttributeError: 'function' object has no attribute 'reduce'
>

**Comment by sklam** [comment]
What is the `@measure_time` decorator?  The `@vectorize` decorator returns a function-like object with methods.  The `@measure_time` decorator may not work on it.

**Comment by ever4244** [comment]
@sklam 

Thanks!  After I remove the measure_time and solve some issue on list append and list comprehension.  It is OK now. 

It seems that "list append" is not supported in nopython mode, while "list comprehension" is not supported in all modes.

Now I initialize a full sized all 0 matrix outside of the function which is to be @jit. I wonder if it is the proper way of doing it, since there are no way to alter the shape of the array in numba.

**Comment by sklam** [comment]
> It seems that "list append" is not supported in nopython mode, while "list comprehension" is not supported in all modes.

List-append works in limited cases.  It only works on simple types (e.g. numerics but not arrays) currently.   List comprehension doesn't work at all due to lack of closure/inner-function support.

> Now I initialize a full sized all 0 matrix outside of the function which is to be @jit. I wonder if it is the proper way of doing it, since there are no way to alter the shape of the array in numba.

Numba has some support for array stacking functions (e.g. ``numpy.stack``, ``numpy.vstack``, etc.) and `numpy.concatenate`.  You can grow an array.


Tips: you can use the [listing](http://numba.pydata.org/numba-doc/latest/developer/listings.html) to find supported numpy features.  But note that the actual name of the numpy function could be longer (`numpy.stack` is alias to `numpy.core.shape_base.stack`) .

**Comment by ever4244** [comment]
@sklam
Thank you very much!
I tried to modify the codes according to some of your advice last week, and it is faster now. 
I think this issue is solved now. Thank you.
