### ISSUE TITLE
Global fast math setting

### ISSUE THREAD

**Issue by seibert** [numba/numba#2289]
As per suggestion on the Numba mailing list:

It would be convenient to have a way to set all compilation to default to `fastmath=True`.  I assume this would be something in numba.config that takes a default value from the environment, but also can be overridden in the Python application itself.

**Comment by seibert** [comment]
Capturing email discussion from @sklam for posterity:

> The fastmath flag cannot be safely used in every case.  A global flag could be dangerous.  But inside your library, you can define `jit = functools.partial(numba.jit, fastmath=True)` and use that internally.

Going to close this issue.

**Comment by pitrou** [comment]
OTOH, a global flag would make it easy to run e.g. the benchmarks suite with it and see the differences :-)
