### ISSUE TITLE
does numba support lists

### ISSUE THREAD

**Issue by kirk86** [numba/numba#2292]
Hi, may I ask if numba supports lists. For instance:

```
def foo()
val = []
for file in files:
    val.append(file)
return val
```

can I use

```
@jit.numba()
def foo()
val = []
for file in files:
    val.append(file)
return val
```

Usually in the past I would get an error regarding the non allocated lists, and since then I haven't tested it.
I was wondering if there's been a change in that direction?

**Comment by sklam** [comment]
It is still limited to simple types (e.g. numbers, tuples) and the list must not contain multiple types.

So, these works:

```python
In [7]: @jit(nopython=True)
   ...: def foo(files):
   ...:     val = []
   ...:     for file in files:
   ...:         val.append(file)
   ...:     return val
   ...:

In [8]: foo([1, 2, 3])
Out[8]: [1, 2, 3]

In [9]: foo([(1,), (2,), (3,)])
Out[9]: [(1,), (2,), (3,)]`
```

This fails:

```python
In [14]: a = np.arange(10)

In [15]: foo([a])
...
LoweringError: Failed at nopython (nopython mode backend)
reflected list(array(int64, 1d, C)): unsupported nested memory-managed object
``

Anything that needs refcounting doesn't work.

**Comment by kirk86** [comment]
@sklam thanks a lot for the clarification. Hope to see someday in the near future fully implemented support. 😄
