### ISSUE TITLE
invert mapping b/w binop operators and the operator module

### ISSUE THREAD

**Issue by sklam** [numba/numba#2297]
Currently, operator functions in the `operator` module is mapped to the numba internal impl.  This makes it difficult to overload operators using `numba.extending.overload`.  It is probably better to invert the mapping and let binop (e.g. `+`, `*`) maps to their respective function in `operator`.

**Comment by jrbourbeau** [comment]
Can this issue be closed since #2983 was merged into `master`?

**Comment by jrbourbeau** [comment]
Thanks @sklam
