### ISSUE TITLE
Nopython mode should allow cfuncs to be called

### ISSUE THREAD

**Issue by seibert** [numba/numba#2311]
We should treat a function compiled with `@cfunc` as if it were a ctypes object and call it that way.

**Comment by FaustinCarter** [comment]
I think this is probably similar to my issue: https://github.com/numba/numba/issues/2247

**Comment by stuartarchibald** [comment]
This works on mainline (upcoming release is 0.55):
```python
from numba import njit, cfunc, types
import numpy as np

@cfunc(types.double(types.double))
def fptr(x):
    return x + 1

@njit
def foo(z):
    print(fptr(z))

foo(1.23)
```
