### ISSUE TITLE
Support for Bessel functions in nopython mode

### ISSUE THREAD

**Issue by nbedou** [numba/numba#2312]
Thank you for your good work on numba, this fantastic piece of software has been making my life so much easier (I code scientific tools).

It would be great to have support for Bessel functions in nopython mode. They are defined as ufunc in scipy.special. Thanks

**Comment by riwoodward** [comment]
I agree, this would certainly be a useful feature! Thanks.

**Comment by stuartarchibald** [comment]
See "scumba" discussion here: https://github.com/numba/numba/issues/4292

**Comment by stuartarchibald** [comment]
This now works if the Numba extension package `numba-scipy` is installed:
```python
from numba import njit
import numpy as np
import scipy

@njit
def foo(x):
    return scipy.special.j0(x)

print(foo(0.2))
```
See: https://github.com/numba/numba-scipy
