### ISSUE TITLE
Performance regression in 0.31 for older processors

### ISSUE THREAD

**Issue by jni** [numba/numba#2313]
## Brief description

Using an `njit`ted min function using `scipy.ndimage.generic_filter` [handily beats](https://ilovesymposia.com/2017/03/15/prettier-lowlevelcallables-with-numba-jit-and-decorators/) `scipy.ndimage.grey_erosion` using Numba 0.31 *and a newer Intel processor*, such as my Macbook's Core m3-6Y30 @ 0.9GHz. On my 2012 Macbook Pro (Core i7-3615QM CPU @ 2.30GHz), it's almost 3x slower! I'd already [shown](https://ilovesymposia.com/2017/03/12/scipys-new-lowlevelcallable-is-a-game-changer/) that it could be faster, so I knew something fishy was going on with my install. I'd done a `conda update --all` recently, so I tried to downgrade Numba to 0.30. This time, Numba again easily outperformed `grey_erosion`.

### JIT + LowLevelCallable decorator
(This first part can be replaced by `pip install llc` and then `from llc import jit_filter_function`):

```python
import numba
from numba import cfunc, carray
from numba.types import intc, CPointer, float64, intp, voidptr
from scipy import LowLevelCallable

def jit_filter_function(filter_function):
    jitted_function = numba.jit(filter_function, nopython=True)
    @cfunc(intc(CPointer(float64), intp, CPointer(float64), voidptr))
    def wrapped(values_ptr, len_values, result, data):
        values = carray(values_ptr, (len_values,), dtype=float64)
        result[0] = jitted_function(values)
        return 1
    return LowLevelCallable(wrapped.ctypes)
```

### Setup

```python
import numpy as np
from scipy import ndimage as ndi

image = np.random.random((2048, 2048))
fp = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]], dtype=bool)

@jit_filter_function
def fmin(values):
    result = np.inf
    for v in values:
        if v < result:
            result = v
    return result
```

### Timings

```python
%timeit ndi.grey_erosion(image, footprint=fp)
%timeit ndi.generic_filter(image, fmin, footprint=fp)
```

## Results

| Processor                  | m3-6Y30 | m3-6Y30 | i7-3615QM | i7-3615QM |
|----------------------------|---------|---------|-----------|-----------|
| Numba version              | 0.30    | 0.31    | 0.30      | 0.31      |
| erosion timing (ms)        | 165     | 164     | 126       | 123       |
| generic filter timing (ms) | 108     | 89      | 88        | 335       |

**Comment by seibert** [comment]
This is very interesting.  The main change that happened between those two releases was upgrading from LLVM 3.8 to 3.9.  Unfortunately, it is hard to tell what changes in various optimizations between releases, so it is possible there was a regression there.

We are getting ready to upgrade again to LLVM 4.0 (things are moving fast) in the next Numba release, so we may ping you to repeat the test when Numba 0.32.0rc1 comes out.

**Comment by jni** [comment]
@seibert please do, I'll be happy to give it another go then.

**Comment by ml31415** [comment]
This filter function also features a small loop, quite like already analyzed in https://github.com/numba/numba/issues/2196 . There are already two issues attached in the LLVM bug tracker, but they didn't get too much attention unfortunately:

https://bugs.llvm.org//show_bug.cgi?id=30452
https://bugs.llvm.org//show_bug.cgi?id=32022

**Comment by jni** [comment]
Just fyi, I just tried 0.32rc1 and didn't see a difference.

## Results

| Processor                  | m3-6Y30 | m3-6Y30 | i7-3615QM | i7-3615QM | i7-3615QM |
|----------------------------|---------|---------|-----------|-----------|-----------|
| Numba version              | 0.30    | 0.31    | 0.30      | 0.31      | 0.32.0rc1 |
| erosion timing (ms)        | 165     | 164     | 126       | 123       | 127       |
| generic filter timing (ms) | 108     | 89      | 88        | 335       | 330       |

Also interesting: I have a different MBP Retina 2012 at work, which was purchased in Australia instead of the US, at about the same time. The processor model string there is "Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz", and somewhat amazingly, it doesn't suffer from the regression at all. That might help narrow down the problem...

**Comment by jni** [comment]
@ml31415 thanks for the ref. Given that the regression happened in different version changes, I suspect that the regressions might be related, but are almost certainly not duplicates.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided for a while and the above relates to Numba from 3 years ago. Please reopen the issue if new information becomes available. Many thanks.
