### ISSUE TITLE
numbapro craches python on windows with prange-example parallel_sum()

### ISSUE THREAD

**Issue by MaxBo** [numba/numba#232]
On Windows 64bit with Anaconda (Python 2.7.4 |Anaconda 1.5.0 (64-bit))
i tried to execute the examples with prange and privatization_rules from http://docs.continuum.io/numbapro/prange.html
When executing the following code, 
the python interpreter craches.
import numpy as np
A = np.ones((10000000), dtype='f4')
@autojit
def parallel_sum(A):
    sum = 0.0
    for i in numbapro.prange(A.shape[0]):
        sum += A[i]

    return sum

return = parallel_sum(A)

I tried it with other dtypes and with jit instead of autojit, but without success.
When i execute
numbapro.test()

It returnes the following test report:

numbapro.test()
running numbapro.tests.test_basic_vectorize                          SUCCESS
running numbapro.tests.test_gufunc                                   SUCCESS
running numbapro.tests.test_mini_vectorize                           SUCCESS
running numbapro.tests.test_parallel_vectorize                       FAILED: 
 None

running numbapro.tests.test_stream_vectorize                         SUCCESS
running numbapro.tests.test_ufunc                                    SUCCESS
running numbapro.tests.issues.test_issue_23                          FAILED: 
 None

running numbapro.tests.issues.test_issue_6                           SUCCESS
running numbapro.tests.issues.test_issue_7                          
Traceback (most recent call last):
  File "C:\Program Files (x86)\Wing IDE 4.1\src\debug\tserver\_sandbox.py", line 1, in <module>
    # Used internally for debug sandbox under external interpreter
  File "c:\Anaconda\lib\site-packages\numbapro\__init__.py", line 97, in test
  File "c:\Anaconda\lib\site-packages\numbapro\__init__.py", line 35, in map_returncode_to_message
NameError: global name 'signal_to_name' is not defined

With numba.test() all but one test Succeed:
numba.tests.test_cstring                                               FAILED:
             

Best regards,

Max

**Comment by pitrou** [comment]
This issue is obsolete due to the fundamental changes that happened in Numba in the last 2+ years, closing.
