### ISSUE TITLE
numpy.random.multinomial support mislabeled in documentation

### ISSUE THREAD

**Issue by kentwait** [numba/numba#2321]
Based on #1758, `numpy.random.multinomial` is now supported but [latest](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html) and [dev](http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html) documentation do not show this. Docs state support for a method called `numpy.random.multibinomial` but this does not exist in numpy API.

**Comment by stuartarchibald** [comment]
Thanks for the report. Patched in https://github.com/numba/numba/pull/2326.
