### ISSUE TITLE
Allow CUDA device functions to also be called from host

### ISSUE THREAD

**Issue by seibert** [numba/numba#2335]
It is a common pattern to define helper functions which are useful both on the host and the device.  The `@cuda.jit(device=True)` decorator should also allow the function to be called from the host as well.  It probably makes sense to JIT the function for the CPU when called that way as well.

**Comment by sklam** [comment]
I have an alternative PR #2343.  Let `@jit` functions to used as cuda device function.

**Comment by sklam** [comment]
Closing due to #2343
