### ISSUE TITLE
generator error if bool yielded

### ISSUE THREAD

**Issue by complyue** [numba/numba#2340]
version 0.32
```
import numba as nb

@nb.jit(nopython=True)
def gf():
    yield 0, True

print(list(gf()))
```
will result in error:

> Traceback (most recent call last):
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/errors.py", line 243, in new_error_context
>     yield
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/lowering.py", line 210, in lower_block
>     self.lower_inst(inst)
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/lowering.py", line 256, in lower_inst
>     val = self.lower_assign(ty, inst)
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/lowering.py", line 426, in lower_assign
>     res = self.lower_yield(ty, value)
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/lowering.py", line 441, in lower_yield
>     self.call_conv.return_value(self.builder, val)
>   File "/fw/Anaconda/anaconda/lib/python3.5/site-packages/numba/targets/callconv.py", line 329, in return_value
>     (str(retval.type), str(retptr.type.pointee))
> AssertionError: ('{i64, i1}', '{i64, i8}')
>

**Comment by stuartarchibald** [comment]
Thanks for the report. I can replicate. It also fails for:

```python
def gen():
    yield True
```
and indeed seemingly anything yielding bools.

It seems to be that the `i1` isn't being handled correctly in the generator lowering.
