### ISSUE TITLE
Loop lifting in class method fails when loop is followed by call to another method 

### ISSUE THREAD

**Issue by ThomasAkam** [numba/numba#2368]
Updating Numba from version 0.25 to 0.33 caused code that was previously getting large speedups from loop lifting to no longer benefit.   The code was using @jit to speed up a class method.   It appears that loop lifting is blocked if any other method is called from within the jitted method after (but not before) the loop.  Below is a minimal example that reproduces the problem:

```python
from numba import jit

class summer():

    @jit
    def sum_1(self,a):
        'Loop lifting works fine in version 0.25 and 0.33.'
        s = 0
        for e in a:
            s += e
        return s

    @jit
    def sum_2(self,a):
        'Loop lifting works fine in version 0.25 but not 0.33.'
        s = 0
        for e in a:
            s += e
        self.do_nothing()
        return s

    @jit
    def sum_3(self,a):
        'Loop lifting works fine in version 0.25 and 0.33.'
        s = 0
        self.do_nothing()
        for e in a:
            s += e
        return s

    def do_nothing(self):
        pass
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can confirm.

**Comment by ThomasAkam** [comment]
I just tested and there is no speedup using jit on the sum_2 function in
numba 0.37 whereas there is on numba 0.26.

On Numba 0.26:

a = np.ones(10000)
s = summer()

%timeit s.sum_1(a)# 10000 loops, best of 3: 28.2 µs per loop

%timeit s.sum_2(a)# 10000 loops, best of 3: 29.6 µs per loop

%timeit s.sum_3(a)# 10000 loops, best of 3: 29.3 µs per loop

On Numba 0.37:

a = np.ones(10000)
s = summer()

%timeit s.sum_1(a)# 36.9 µs ± 4.79 µs per loop (mean ± std. dev. of 7
runs, 10000 loops each)

%timeit s.sum_2(a)# 1.82 ms ± 245 µs per loop (mean ± std. dev. of 7
runs, 100 loops each)

%timeit s.sum_3(a)#37.6 µs ± 5.69 µs per loop (mean ± std. dev. of 7
runs, 10000 loops each)

Please could you reopen the issue.

thanks,

Thomas
​

**Comment by stuartarchibald** [comment]
This is a minimal reproducer:
```python
@jit
def test(a, b):
    s = 0
    for e in a:
        s += e
    print(b.__class__)
    return s, b

print(test(np.ones(10000), object()))
```

**Comment by stuartarchibald** [comment]
This should be fixed in 0.38 RC. If possible, please could you test to confirm? The RC is on the Numba channel and can be installed with `conda` by doing:
```
conda install -c numba numba
```
I now see timings:
```
77.2 µs ± 88.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
77.4 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
77.5 µs ± 501 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
and signatures:
```
[(array(float64, 1d, C), int64)]
[(array(float64, 1d, C), int64)]
[(array(float64, 1d, C), int64)]
```

I've also added https://github.com/numba/numba/issues/2906 as a ticket for 2. above. Thanks.

**Comment by ThomasAkam** [comment]
On numba 0.38.0rc1+6.g8557f52 with numpy 1.13.3 I now get timings of :

a = np.ones(10000)
s = summer()

%timeit s.sum_1(a)# 10000 loops, best of 3: 86 µs per loop

%timeit s.sum_2(a)# 10000 loops, best of 3: 76.3 µs per loop

%timeit s.sum_3(a)# 10000 loops, best of 3: 78.8 µs per loop

So it looks like the loop lifting issue is fixed.  For all 3 functions the
new version does appear substantially slower than numba 0.26, where on the
same machine the above functions take ~30us.

**Comment by stuartarchibald** [comment]
Thanks for testing. I think the performance difference present is due to the error reporting enhancement patch (git bisect confirms) https://github.com/numba/numba/pull/2859. I think this means there is more to do in the jitted part that isn't lifted and as a result there is a performance hit in exchange for usability. Measuring the performance of the whole method vs the lifted loops across versions gives:
```
Numba version 0.26.0
Timing the whole method:
35.1 µs ± 873 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
35.1 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
35.7 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Timing the lifted loop:
10.7 µs ± 3.08 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.8 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.7 µs ± 7.38 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
and
```
Numba version 0.38.0rc1+6.g8557f52
Timing the whole method:
78.9 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
80.1 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
78.9 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Timing the lifted loop:
10.8 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.9 µs ± 160 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.8 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
this demonstrates that the lifted loops run at the same speed as before, it is just the part in object mode that is slower.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
