### ISSUE TITLE
boolean operations produce values incompatible with numpy

### ISSUE THREAD

**Issue by gdementen** [numba/numba#238]
On numba 0.8.1, comparisons produce boolean values which are incompatible with numpy: numba uses "255" to represent True, while numpy uses 1, this means that, for example, np.sum(boolean_result) is different. 

This could be considered a bug in numpy, but I guess this has more chance to be "fixed" here than in numpy.

I believe all operations producing boolean values are also affected, but I did not test them all.

```python
import numpy as np
from numba import autojit

def lt(a, b):
    result = np.empty(len(a), dtype=np.bool)
    for i in range(len(a)):
        result[i] = a[i] < b
    return result
lt_nb = autojit(lt)
    
a = np.arange(10)

r1 = lt(a, 5)
r2 = lt_nb(a, 5)

# workaround
# r2 = r2.astype(np.uint8, copy=False).astype(np.bool)

# this passes...
assert np.array_equal(r1, r2)

# but...
print r1.astype(np.uint8), r2.astype(np.uint8)
assert np.sum(r1) == np.sum(r2)
```

**Comment by pitrou** [comment]
This is currently fixed.
