### ISSUE TITLE
Python Subset Detection

### ISSUE THREAD

**Issue by alexbw** [numba/numba#2383]
I've been unable to find where in this project function syntax is checked to conform to numba's supported subset of Python. Could a dev guide me to the right place?

**Comment by seibert** [comment]
Numba operates on Python bytecode, not the Python AST.  As a result, the supported syntax is determined by which bytecodes Numba can handle, which translate back to Python code structures in non-obvious ways.  In most cases, the real limitation is what Python types, modules, and functions Numba supports in nopython mode.

Are you trying to automatically detect whether a function can be compiled by Numba?
