### ISSUE TITLE
Additional test samples for https://github.com/numba/numba/pull/2369

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2387]
First,  https://github.com/numba/numba/pull/2369 is fantastic :-)

I've added a load of test samples for https://github.com/numba/numba/pull/2369 here: https://github.com/stuartarchibald/numba/commit/10ff1fee888a9014c30828f66d120169f16725ce

Below, I've copied in the failing samples with their error output (excluding tests I think ought to fail due to unsupported features). This ticket is to promote discussion and decide on how to fix if required.

CC: @ninegua @sklam @seibert 

Case `outer3`:
```python
        def outer3(x):
            """ Test recursive inner """
            def inner(x):
                if x + y < 2:
                    return 10
                else:
                    inner(x - 1)
            return inner(x)
```
Expected fail cf. https://github.com/numba/numba/issues/2386
```
fail: <function TestVariousPR2369.test_many.<locals>.outer3 at 0x7fd9e884ca60>
'inner' is not defined in <path>/numba/tests/test_closure.py (214)
````
----------------------------------------------------------------------------------------------------------

Case `outer4`:
```python
        def outer4(x):
            """ Test recursive closure """
            y = x + 1

            def inner(x):
                if x + y < 2:
                    return 10
                else:
                    inner(x - 1)
            return inner(x)
```
Expected fail cf. https://github.com/numba/numba/issues/2386
```
fail: <function TestVariousPR2369.test_many.<locals>.outer4 at 0x7fd9e884cae8>
'inner' is not defined in <path>/numba/tests/test_closure.py (225)
```

----------------------------------------------------------------------------------------------------------
Case `outer8`:
```python
        _OUTER_SCOPE_VAR = 9

        def outer8(x):
            """ Test use of outer scope var, with closure """
            z = x + 1

            def inner(x):
                return x + z + _OUTER_SCOPE_VAR
            return inner(x)
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.outer8 at 0x7fd9e884cd08>
Failed at nopython (nopython frontend)
Invalid usage of + with parameters (int64, none)
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * (uint64,) -> uint64
 * (uint8,) -> uint64
 * (uint32,) -> uint64
 * (uint16,) -> uint64
 * (int64,) -> int64
 * (int8,) -> int64
 * (int32,) -> int64
 * (int16,) -> int64
 * (float32,) -> float32
 * (float64,) -> float64
 * (complex64,) -> complex64
 * (complex128,) -> complex128
 * parameterized
File "numba/tests/test_closure.py", line 269
[1] During: typing of intrinsic-call at <path>/numba/tests/test_closure.py (269)
```

----------------------------------------------------------------------------------------------------------
Case `outer10`:
```python
        def outer10(x):
            """ Test two inner, one calls other """
            z = x + 1

            def inner(x):
                return x + z

            def inner2(x):
                return inner(x)

            return inner2(x)
```
Fails as (Expected? cf. https://github.com/numba/numba/issues/2386)
```
fail: <function TestVariousPR2369.test_many.<locals>.outer10 at 0x7fd9e884ce18>
Failed at nopython (nopython frontend)
(<class 'numba.ir.Expr'>, make_function(name=$const0.7, code=<code object inner at 0x7fd9e8ac4150, file "<path>/numba/tests/test_closure.py", line 285>, closure=$0.5))
```
----------------------------------------------------------------------------------------------------------
Case `outer11`:
```python
        def outer11(x):
            """ return the closure """
            z = x + 1

            def inner(x):
                return x + z
            return inner
```
Fails as (I think expected):
```
fail: <function TestVariousPR2369.test_many.<locals>.outer11 at 0x7fd9e884cea0>
Failed at nopython (nopython frontend)
cannot determine Numba type of <class 'code'>
File "numba/tests/test_closure.py", line 297
```
----------------------------------------------------------------------------------------------------------
Case `outer12`:
```python
        def outer12(x):
            """ closure with kwarg"""
            z = x + 1

            def inner(x, kw=7):
                return x + z + kw
            return inner
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.outer12 at 0x7fd9e884cf28>
Failed at nopython (analyzing bytecode)
'NotImplementedType' object is not callable
```
----------------------------------------------------------------------------------------------------------
Case `outer14`:
```python
        def outer14(x, kw=7):
            """ outer with kwarg used in closure"""
            z = x + 1

            def inner(x):
                return x + z + kw
            return inner
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.outer14 at 0x7fd9e88630d0>
Failed at nopython (nopython frontend)
cannot determine Numba type of <class 'code'>
File "numba/tests/test_closure.py", line 318
```
----------------------------------------------------------------------------------------------------------
Case `outer15`:
```python
        def outer15(x, kw=7):
            """ outer with kwarg as arg to closure"""
            z = x + 1

            def inner(x, kw):
                return x + z + kw
            return inner
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.outer15 at 0x7fd9e8863158>
Failed at nopython (nopython frontend)
cannot determine Numba type of <class 'code'>
File "numba/tests/test_closure.py", line 326
```
----------------------------------------------------------------------------------------------------------
Case `list6`:
```python
        def list6(x):
            """ Test use of inner function in list comprehension """
            def inner(x):
                return x + 1
            return [inner(z) for z in x]
```
Fails as (Expected? cf. https://github.com/numba/numba/issues/2386):
```
fail: <function TestVariousPR2369.test_many.<locals>.list6 at 0x7fd9e8863488>
Failed at nopython (nopython frontend)
(<class 'numba.ir.Expr'>, make_function(name=$const0.2, code=<code object inner at 0x7fd9e8ac4db0, file "<path>/numba/tests/test_closure.py", line 353>, closure=None))
```
----------------------------------------------------------------------------------------------------------
Case `list7`:
```python
        def list7(x):
            """ Test use of closure in list comprehension """
            y = 3

            def inner(x):
                return x + y
            return [inner(z) for z in x]
```
Fails as (Expected? cf. https://github.com/numba/numba/issues/2386):
```
fail: <function TestVariousPR2369.test_many.<locals>.list7 at 0x7fd9e8863510>
Failed at nopython (nopython frontend)
(<class 'numba.ir.Expr'>, make_function(name=$const0.5, code=<code object inner at 0x7fd9e8ac4f60, file "<path>/numba/tests/test_closure.py", line 361>, closure=$0.3))
```
----------------------------------------------------------------------------------------------------------
Case `list19`:
```python
        _OUTER_SCOPE_VAR = 9

        def list19(x):
            """ Test list comprehension with outer scope as conditional"""
            return [i for i in x if i < _OUTER_SCOPE_VAR]
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.list19 at 0x7fd9e8863b70>
Failed at nopython (nopython frontend)
Invalid usage of < with parameters (int64, none)
Known signatures:
 * (bool, bool) -> bool
 * (int8, int8) -> bool
 * (int16, int16) -> bool
 * (int32, int32) -> bool
 * (int64, int64) -> bool
 * (uint8, uint8) -> bool
 * (uint16, uint16) -> bool
 * (uint32, uint32) -> bool
 * (uint64, uint64) -> bool
 * (float32, float32) -> bool
 * (float64, float64) -> bool
 * parameterized
File "numba/tests/test_closure.py", line 443
[1] During: typing of intrinsic-call at <path>/numba/tests/test_closure.py (443)
```

**Comment by stuartarchibald** [comment]
I've added a couple more samples relating to generators in https://github.com/stuartarchibald/numba/commit/822677a28e5c1dd8aad3b9d45e828a1ccd535646 (thanks @sklam for suggesting): 

Case `outer16`:
```python
        def outer16(x):
            """ closure is generator, consumed locally """
            z = x + 1

            def inner(x):
                yield x + z

            return list(inner(x))
```
Fails as (parameters shouldn't be `none`):
```
fail: <function TestVariousPR2369.test_many.<locals>.outer16 at 0x7f426a8bd1e0>
Failed at nopython (nopython frontend)
Invalid usage of Function(<class 'list'>) with parameters (none)
 * parameterized
File "numba/tests/test_closure.py", line 337
[1] During: resolving callee type: Function(<class 'list'>)
[2] During: typing of call at <path>/numba/tests/test_closure.py (337)
```
--------------------------------------------------------------------------------------------------------------
Case `outer17`:
```python
        def outer17(x):
            """ closure is generator, returned """
            z = x + 1

            def inner(x):
                yield x + z

            return inner(x)
```
Fails as:
```
fail: <function TestVariousPR2369.test_many.<locals>.outer17 at 0x7f426a8bd268>
Failed at nopython (nopython mode backend)
'NoneType' object has no attribute 'yield_points'
File "numba/tests/test_closure.py", line 344
[1] During: lowering "$19 = yield $0.3" at <path>/numba/tests/test_closure.py (344)
```

**Comment by seibert** [comment]
@ninegua: Feel free to pull Stuart's test cases into your PR as you go.

**Comment by ninegua** [comment]
@stuartarchibald `outer12,outer14,outer15` are [missing the argument to `inner`](https://github.com/IntelLabs/numba/commit/e4b2424de3873d8cadae281d5131cffb254eb581). If you are done with these tests, you are welcome to submit a PR to the [list-comprehension branch](https://github.com/IntelLabs/numba/tree/list-comprehension) so that I can merge them into PR #2369 

 But otherwise I've fixed the rest issues except generators in the latest commit to list-comprehension branch. The expected failures are now:

```
fail: <function TestVariousPR2369.test_many.<locals>.outer3 at 0x7f1eb97eb1e0>
fail: <function TestVariousPR2369.test_many.<locals>.outer4 at 0x7f1eb97eb268>
fail: <function TestVariousPR2369.test_many.<locals>.outer11 at 0x7f1eb97eb620>
fail: <function TestVariousPR2369.test_many.<locals>.outer16 at 0x7f1eb97eb8c8>
fail: <function TestVariousPR2369.test_many.<locals>.outer17 at 0x7f1eb97eb950>
fail: <function TestVariousPR2369.test_many.<locals>.list5 at 0x7f1eb97ebbf8>
fail: <function TestVariousPR2369.test_many.<locals>.list11 at 0x7f1eb97ebf28>
```
Namely: recursion, returning closure, generator, nested mem objects are not supported.

I'm not sure what is the story with generators that we want to make here. I don't think inlining is the right semantics for generators. Suggestions? Or we can just say it is not supported.

Also, `test22` would fail for Python 2.7. Since comprehension in Python 2.7 is not related to closures, I think it is a separate issue. The problem looks like a conflict in variable names. @stuartarchibald @sklam

**Comment by stuartarchibald** [comment]
@ninegua good catch on the missing args, I have to admit to doing a lot of copy-paste-mutate. I've formed up a patch and put in a PR as requested here https://github.com/IntelLabs/numba/pull/9. I thought of another couple of cases too last night so I've add them in. Regarding your comment about `list22`, I've just written a test around it for Python 2.7 to ensure it fails at present, but I'm inclined to say it is not related to this PR.

I agree with the summary of failure types. I think it's fine to say generators from closures are not supported for now, I'm also unconvinced inlining is the right thing to do too.



This https://github.com/IntelLabs/numba/pull/9/files#diff-69e01738577449bec5a17f54f5845f47R95 was needed to make `outer12` work on Python 3.6, it may not be the best way to fix it.

**Comment by ninegua** [comment]
Thanks @stuartarchibald. I've just merged it in.

**Comment by stuartarchibald** [comment]
@ninegua thanks. Closing this ticket.
