### ISSUE TITLE
bugs in numpy array resize for a numba object

### ISSUE THREAD

**Issue by gxlzj** [numba/numba#2392]
```
from numba import jit,int64,float64,jitclass
import numpy as np
spec_data = [
  ('H', float64[:])
]

@jitclass(spec_data)
class Data(object):
  def __init__(self):
    pass

data = Data()
data.H = np.ones(5)
print 'data.H\t',data.H
data.H.resize(10)
print 'data.H\t',data.H
```
this will output:

data.H	[ 1.  1.  1.  1.  1.]
data.H	[  1.72723371e-077  -2.68678326e+154   1.00000000e+000   1.00000000e+000
   1.00000000e+000]

but other times, it will output:

data.H	[ 1.  1.  1.  1.  1.]
data.H	[ 1.  1.  1.  1.  1.]

I guess: numpy has a memory operation on data.H (a ndarray), but numba object did not receive the change.

Can this be fixed? This would be important if user want to manipulate memory allocation of numpy array in numba object.

**Comment by gxlzj** [comment]
anyone would like to deal with this issue?

**Comment by stuartarchibald** [comment]
I believe this is an invalid use of `@jitclass`. http://numba.pydata.org/numba-doc/dev/user/jitclass.html#the-decorator-jitclass suggests

> The definition of the class requires at least a `__init__` method for initializing each defined fields. Uninitialized fields contains garbage data. Methods and properties (getters and setters only) can be defined. They will be automatically compiled.

but the class above does not initialize the `H` field, it just has `pass`.

Further:
 >  The data of a jitclass instance is allocated on the heap as a C-compatible structure so that any compiled functions can have direct access to the underlying data, bypassing the interpreter.

which would explain why a resize or an assignment would be invalid, essentially it's a fixed size block.
