### ISSUE TITLE
ParallelAccelerator needs to adhere to/check broadcast semantics

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2399]
Following on from this thread, https://github.com/numba/numba/pull/2379#discussion_r119620391, this issue is to note and track the need for compliance with broadcast semantics in ParallelAccelerator.

A motivating case is:
```python
@njit(parallel=True)
def test_2d():
    X = np.ones((10,12))
    Y = np.zeros((10,12))
    return np.sum(X[::2] + Y) # step 2 creates invalid arrays for addition
```
which at present behaves in an invalid manner.

@ehsantn, issue created as requested.

**Comment by ehsantn** [comment]
Thanks @stuartarchibald . The problem is that adding runtime checks to the IR can prevent optimizations significantly. We need to think about a way of adding minimal required checks based on the input code, while allowing aggressive optimization.

**Comment by ehsantn** [comment]
@ninegua @DrTodd13

**Comment by ninegua** [comment]
One way to do this is to insert assertions about dimension or size equality at the right places in the IR, which forms the basis for (and could potentially simplify) size equivalence inference. Then after the actual inference, remove assertions that are known to be always true (presumably after dataflow analysis). It is, however, not a quick fix.

**Comment by stuartarchibald** [comment]
Implementation in https://github.com/numba/numba/pull/2492.

**Comment by ninegua** [comment]
With #2492, the above example now produces an assertion error:

```
AssertionError: Size of $0.17, Y do not match
```

The error message would be better, had `X[::2]` been given a proper name.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/2492 is merged. Closing.
