### ISSUE TITLE
Problems with ctors for np.ones in ParallelAccelerator

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2401]
Tracking noted debt in https://github.com/numba/numba/pull/2379. Two cases give errors as follows, I suspect `np.zeros` and `np.random.ranf` may suffer from the same problem.

----------------------------------------------------------------------------------------------------------------------------
Case 02:
```python
def case02(v1, v2, m1, m2):
    return np.ones((1,))
```
gives:
```
Failed at nopython (nopython mode backend)
'int' object has no attribute 'name'
File "numba/tests/test_parfors.py", line 197
[1] During: lowering "[LoopNest(index_variable=parfor_index.36, range=0,1,1 correlation=0)]{1: <ir.Block at <path>/numba/tests/test_parfors.py (197)>}Var(parfor_index.36, <path>/numba/tests/test_parfors.py (197))" at <path>/numba/tests/test_parfors.py (197)
```
----------------------------------------------------------------------------------------------------------------------------
Case 07:
```python
def case07(v1, v2, m1, m2):
    return np.ones(1)
```
gives:
```
Failed at nopython (nopython mode backend)
'int' object has no attribute 'name'
File "numba/tests/test_parfors.py", line 212
[1] During: lowering "[LoopNest(index_variable=parfor_index.196, range=0,1,1 correlation=0)]{1: <ir.Block at <path>/numba/tests/test_parfors.py (212)>}Var(parfor_index.196, <path>/numba/tests/test_parfors.py (212))" at <path>/numba/tests/test_parfors.py (212)
```
---------------------------------------------------------------------------------------------------------------------------
@ehsantn thanks.

**Comment by stuartarchibald** [comment]
Full test patch is here: https://github.com/stuartarchibald/numba/commit/3d9c36bd2ca64141790619a468d1de58d5c312e8

**Comment by ehsantn** [comment]
The issue of handling constant sizes in these calls is already resolved in the prange #2391 branch. I added the test patch to #2391.

I think the current issue is that the created array's size is smaller than the number of threads. The backend should check for this and handle it appropriately.
@ninegua @DrTodd13

**Comment by ninegua** [comment]
I cannot reproduce this. The above `np.ones((1,))` runs fine for me in prange branch.

**Comment by stuartarchibald** [comment]
`Case 02` merged and working in practice https://github.com/numba/numba/blob/master/numba/tests/test_parfors.py#L311-L314

`Case 07` merged and working in practice https://github.com/numba/numba/blob/master/numba/tests/test_parfors.py#L323-L326

Closing as a result.
