### ISSUE TITLE
Numba does not provide any substantial speedup when calculating SVD. 

### ISSUE THREAD

**Issue by Garyfallidis** [numba/numba#2423]
I am looking for a suggestion on how to optimize this code snippet below (SVD inside 2 for loops). 

```
import numpy as np
from numba import jit
from scipy.linalg import svd

def test_speed(A, n):
    
    for i in range(n):
        for j in range(n):

            u, s, v = svd(A) 
        
    return u, s, v

@jit(nogil=True, cache=True)
def test_speed_jit(A, n):
    
    for i in range(n):
        for j in range(n):

            u, s, v = np.linalg.svd(A) 
        
    return u, s, v


A = np.random.rand(100, 100)
n = 100

from time import time

t1 = time()
u, s, v = test_speed(A, n)

t2 = time()
u2, s2, v2 = test_speed_jit(A, n)

t3 = time()

print(t2 - t1)
print(t3 - t2)
```
This outputs very similar timings.
15.322275638580322
15.243773460388184

My numba version is 0.30.1. I am in windows 10 with visual studio 15.
Thanks in advance.

**Comment by seibert** [comment]
The runtime of your function will be dominated by calls to the LAPACK SVD function, so you will see no benefit to using Numba.  If you are using Anaconda, you should be using the MKL version of LAPACK, so there is not much additional speed to gain.

**Comment by Garyfallidis** [comment]
Thank you @seibert.

**Comment by stuartarchibald** [comment]
@Garyfallidis, @seibert is spot on, Numba just does its best to get out the way and hit LAPACK as fast as possible for the `linalg` routines. There are some cases where Numba has algorithmic improvements, like in `np.linalg.norm`, which yield better performance.

For a performance gain in your case, you'd probably have to think about reducing the level of work. For example, do you necessarily need the SVD, could you use eigen routines instead, or perhaps you could get away with not computing the full matrices of singular vectors, which would save a small amount of time in some cases?

**Comment by Garyfallidis** [comment]
Thank you we will try to use eigenvalue decomposition and see what happens.

**Comment by Ryandry1st** [comment]
I noticed this during some investigation and am bringing it up as a potential feature request. Looks like a valuable feature would be for numba to support compute_uv=False. 

I found that I am getting roughly 3x faster performance using numpy with compute_uv=False compared to the default being true. I compared this with numba but did not see much speed up (as noted, mostly just going to ping the LAPACK routines). I even used a parallel jit with higher dimension (270, 32, 4) matrices and could not even come close to the numpy speed due to compute_uv=False. Might be a valuable flag to implement given how often singular values are needed without singular vectors.

**Comment by stuartarchibald** [comment]
@Ryandry1st please feel free to open a new issue with this a as feature request. It looks like `compute_uv` is boolean and the output is type stable if provided as a literal boolean. I think in the case of computing an SVD it's reasonably likely that the user knows whether they want `u` and `v` invariant of the data as it's typically a function of their algorithm, such that requiring them to writing `compute_uv=True/False` seems reasonable. Below is an example of what cannot be done as the return type depends on a runtime value:
```python
@njit
def foo(a):
    if len(a) > 7:
        pred = True
    else:
        pred = False
    # does this return an array or a tuple or arrays?!
    return np.linalg.svd(a, compute_uv=pred) 
```
