### ISSUE TITLE
`requirements.txt` fails when falling the build procedure

### ISSUE THREAD

**Issue by hughperkins** [numba/numba#2427]
Following procedure at https://github.com/numba/numba#custom-python-environments:
- I've installed llvmlite:
```
(env2) ~/git-local/llvmlite (master|…1) $ python -c 'import llvmlite'
(env2) ~/git-local/llvmlite (master|…1) $ pip freeze
enum34==1.1.6
llvmlite==0.19.0.dev0+18.g76191dc
```

However, when trying to install numba, it asserts that I dont have the appropriate versino of llvmlite installed/available:
```
(env2) ~/git-local/numba (master|✔) $ cat requirements.txt 
numpy>=1.7
llvmlite>=0.19
argparse
funcsigs ; python_version < '3.4'
singledispatch ; python_version < '3.4'
(env2) ~/git-local/numba (master|✔) $ pip install -r requirements.txt 
Collecting numpy>=1.7 (from -r requirements.txt (line 1))
  Using cached numpy-1.13.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting llvmlite>=0.19 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement llvmlite>=0.19 (from -r requirements.txt (line 2)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0)
No matching distribution found for llvmlite>=0.19 (from -r requirements.txt (line 2))
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is down to using the development versions. The `llvmlite` you've installed is the `0.19.dev` version which is the development tagged version for the pending `0.19` release. Assuming you are building `Numba` from the master branch, the `Numba` version is also a `dev` version and probably ought to refer to `llvmlite>=0.19.dev`, seems if you change the `requirements.txt` to:
```python
numpy>=1.7
llvmlite>=0.19.dev
argparse
funcsigs ; python_version < '3.4'
singledispatch ; python_version < '3.4'
```
it works fine. Perhaps try that?

In general this is a good point and something we should look at in future release cadences.

**Comment by hughperkins** [comment]
I simply commented it out for my own purposes, but as you say I think this should be fixed somehow in the source code for future versions?

On 26 June 2017 11:33:13 BST, stuartarchibald <notifications@github.com> wrote:
>Thanks for the report. I think this is down to using the development
>versions. The `llvmlite` you've installed is the `0.19.dev` version
>which is the development tagged version for the pending `0.19` release.
>Assuming you are building `Numba` from the master branch, the `Numba`
>version is also a `dev` version and probably ought to refer to
>`llvmlite>=0.19.dev`, seems if you change the `requirements.txt` to:
>```python
>numpy>=1.7
>llvmlite>=0.19.dev
>argparse
>funcsigs ; python_version < '3.4'
>singledispatch ; python_version < '3.4'
>```
>it works fine. Perhaps try that?
>
>In general this is a good point and something we should look at in
>future release cadences.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/numba/numba/issues/2427#issuecomment-311023016

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stuartarchibald** [comment]
Yes, I think it's just a question of making sure that releases of `Numba` refer to released versions of `llvmlite` and that the `dev` versions of `Numba` refer to the `dev` versions of `llvmlite`. A release is pending so I'll check both are ok for that and for future `dev` versions. Thanks again for reporting it.

**Comment by mcg1969** [comment]
Yes, PEP 440 versioning dictates that `0.19.dev<0.19`. So a version spec `>=0.19` will indeed exclude a dev version.

**Comment by hughperkins** [comment]
:+1:
