### ISSUE TITLE
Testing fails in `multiprocessing\pool.py` with pop from empty deque

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2436]
The test suite sometimes fails with:
```python
Traceback (most recent call last):
  File "<path_to_env>\lib\multiprocessing\pool.py", line 681, in next
    item = self._items.popleft()
IndexError: pop from an empty deque
```
a number of additional exceptions are in the chain, the most important of which is:

```python
multiprocessing.context.TimeoutError: Tests didn't finish before timeout (or crashed):
- numba.tests.test_threadsafety.TestThreadSafety.test_concurrent_mix_use
```
this test seems to cause the error most often, though other offenders including `test_funcs.py::TestLoopTypesComplexNoPython`.

This most commonly happens on 64 bit windows, the Numpy and Python version doesn't seem to influence the likelihood of it failing.

**Comment by stuartarchibald** [comment]
This is part fixed in #2449

**Comment by stuartarchibald** [comment]
and https://github.com/numba/numba/pull/2471 completes fix

**Comment by jakirkham** [comment]
This seems to have re-emerged as demonstrated by [this CI failure]( https://circleci.com/gh/conda-forge/numba-feedstock/355 ). Was using CentOS 6 with Python 3.6.7, NumPy 1.9.3, and building with GCC 4.8.2 (devtoolset-2).

**Comment by stuartarchibald** [comment]
@jakirkham thanks, I suspect the CI failure over on conda-forge is from a genuine timeout. The test:
`- 'numba.tests.test_parallel_backend.TestSpecificBackend.test_random_concurrent_mix_use_tbb'`
and the rest of the `numba.tests.test_parallel_backend.TestSpecificBackend` part of the suit is really CPU intensive, CI infrastructure has been struggling so https://github.com/numba/numba/pull/3544 has been added to skip them on public infrastructure (they'll still run on the internal build farm).
