### ISSUE TITLE
Please add np.argpartition implementation in nopython mode

### ISSUE THREAD

**Issue by ethen8181** [numba/numba#2445]
Hi, this is more of a feature request. I checked the documentation and found that `np.argpartition` is not supported at the moment, it would be great if this functionality is included!! Thanks for all the hard work.

**Comment by ethen8181** [comment]
Hi team, just wanted to check whether there's an update on this? Like in this in the works or something. Thanks!

**Comment by seibert** [comment]
No updates.  We'd happily accept a contributed implementation, but have not had time to do it ourselves.

**Comment by sleighsoft** [comment]
Would love to see this. What would I have to do to add support for this to numba?

**Comment by sleighsoft** [comment]
Would love to see this. What would I have to do to add support for this to numba?

**Comment by stuartarchibald** [comment]
@sleighsoft The use of Numba's extension API `@overload` decorator is strongly recommended for this task. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

**Comment by sharthZ23** [comment]
@sleighsoft Have you made any progress?

@stuartarchibald numba already has a partial sorting algorithm - [(L1212).](https://github.com/numba/numba/blob/ec6fa07c12c3703a52c2b4ac8a225a68539c3cc8/numba/np/arraymath.py#L1212) Do I need to try to extend it to the case of argpartition, or can I duplicate the functionality (`np.partition - _select_factory`, `np.argpartition - _select_factory2`)?

**Comment by sleighsoft** [comment]
I haven't had the time to pursue this any further

**Comment by rragundez** [comment]
Close by #8732

**Comment by stuartarchibald** [comment]
> Closed by #8732

Thanks for following up on this @rragundez. This was indeed implemented in #8732 with thanks to @rragundez. Closing as fixed, the functionality will be in the next version of Numba (0.57.x).
