### ISSUE TITLE
ndarray.sum() method silently ignores axis argument

### ISSUE THREAD

**Issue by fritzo** [numba/numba#2446]
On `numba==0.33.0`, `my_2d_array.sum(0)` is silently interpreted as `my_2d_array.sum()`.

**Comment by stuartarchibald** [comment]
Thanks for the report. I believe this is documented behaviour http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#calculation ? `The following methods of Numpy arrays are supported in their basic form (without any optional arguments): * sum()`

**Comment by sklam** [comment]
I think "silently ignores" is the problem here.  Numba should raise an error.  The axis argument changes the behavior too much.

**Comment by stuartarchibald** [comment]
I agree, the proposed fix is much better than relying on docs as it gives user feedback. Thanks @sklam.

**Comment by fritzo** [comment]
Thanks for the quick response, Siu! Numba has been a pleasure to use so far.
