### ISSUE TITLE
NotImplementedError: Use of unknown opcode STORE_GLOBAL

### ISSUE THREAD

**Issue by sebma** [numba/numba#2447]
Hi,

I added those two lines at the beginning of my script like the homepage example says :
```
from numba import jit
@jit
```
I have a global variable in a function.

When I run the script, I get this error message : 

`NotImplementedError: Use of unknown opcode STORE_GLOBAL at line xx of yyyyyy.py`

Can you help ?

**Comment by stuartarchibald** [comment]
Thanks for the report. What you see is I believe correct behaviour. Numba treats globals as compile time constants so the notion of writing to a global (the `STORE_GLOBAL` opcode) is invalid. [This entry in the FAQ](http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable) might help?

**Comment by sebma** [comment]
What must I do to make my Python script work ?

**Comment by seibert** [comment]
Numba doesn't let you modify global variables in compiled functions.  You need to use return values, or modify the contents of NumPy arrays.

**Comment by sebma** [comment]
Thanks, I'll have a look into my code if ever my internship is renewed :)

**Comment by p4jo** [comment]
By the way, a potential workaround is to replace `global` by `nonlocal` and to wrap everything in a `def` block.
