### ISSUE TITLE
python string add was not support in numba 0.9

### ISSUE THREAD

**Issue by liuzhenhai** [numba/numba#246]
``` python
from numba import jit
@jit()
def f():
  print "a"+"b"
```

**Comment by ssarangi** [comment]
Both the examples above work in 0.20.0

**Comment by pitrou** [comment]
That's because object mode is enabled. With `nopython=True` the example would fail.

**Comment by seibert** [comment]
Closing as string support was added in Numba 0.41.  (Python 3 only for now.)
