### ISSUE TITLE
ParallelAccelerator documentation clarification

### ISSUE THREAD

**Issue by kitizz** [numba/numba#2460]
I was super excited to see the new `parallel` option in the latest release notes. I admit that the documentation already clearly states what it can do. I think it could be useful to explicitly mention what it _doesn't_ do (yet?).

For example, after glossing over the notes and not RTFMing, I fired up the latest version to test the speedups for the an image-sampling type algorithm (minimal example at end). Of course, no speedup.

**Tldr;**
for clarity, perhaps mention that `parallel` does not yet support the parallelization of array reads and writes; and that `vectorize` and `gpuvectorize` are still the best tools for this sort of thing.

```python
width = 1000
x = np.random.randint(0, width, 10000)
y = np.random.randint(0, width, 10000)
im = np.random.uniform(0, 1, (width, width))

@njit(parallel=True)
def sample_image(x, y, im):
    N = len(x)
    result = np.empty(N)
    for k in prange(N):
        i = y[k]
        j = x[k]
        result[k] = im[i, j]
    return result

%timeit sample_image(x, y, im)
```

**Comment by ehsantn** [comment]
It's actually parallelizing this code properly I think. The amount of computation is just too little.

**Comment by stuartarchibald** [comment]
Augmenting your sample, this shows how you can check the parallel loop scheduler is working in the `assert` at the end.

``` python
import numpy as np
from numba import njit, prange

width = 1000
x = np.random.randint(0, width, 10000)
y = np.random.randint(0, width, 10000)
im = np.random.uniform(0, 1, (width, width))

@njit(parallel=True)
def sample_image(x, y, im):
    N = len(x)
    result = np.empty(N)
    for k in prange(N):
        i = y[k]
        j = x[k]
        result[k] = im[i, j]
    return result



sample_image(x, y, im)

irs = [(k, v) for k, v in sample_image.inspect_llvm().items()]
assert '@do_scheduling' in irs[0][1] # <--- checks that the parallel loop scheduler is compiled in
```

**Comment by kitizz** [comment]
Thanks for the heads up how to check for the necessary flags.
Although, I'm still not convinced that `parallel` is doing anything.

Here's a `guvectorize` version of the method:
```python
@guvectorize([(int64[:], int64[:], float64[:, :], float64[:])], '(),(),(h,w)->()', target='parallel')
def sample_image_guvec(x, y, im, result):
    result[0] = im[y[0], x[0]]
```

Setting `x` and `y` to have 1 million values, I get absolutely no change in timing when I enable `parallel=True` for `sample_image`. And a ~3x speedup for `sample_image_guvec`:
```
>> timeit sample_image(x, y, im)
15.1 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>> timeit sample_image_guvec(x, y, im)
5.88 ms ± 334 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by DrTodd13** [comment]
What kind of a machine are you on?  I tried this on a 12-core hyper-threaded machine.  For me, parallel=True just by itself was actually slower but that presumes NUMBA_NUM_THREADS=24 (12 cores X 2 hyperthreads).  However, if I used NUMBA_NUM_THREADS=7 then I get about 40% speedup.  Doing this automatically is very difficult though.  If this is for something you run frequently then you can control the number of threads for best performance in this way.

**Comment by kitizz** [comment]
Good call! I'm on a 2.8GHz Quad core i7. Setting NUMBA_NUM_THREADS=7, I get a noticeable bump in improvement. Thanks :)

```
>> timeit ParallelTest.sample_image(x, y, im)
6.66 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>> timeit ParallelTest.sample_image_guvec(x, y, im)
5.8 ms ± 180 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by stuartarchibald** [comment]
@kitizz this is also now in master http://numba.pydata.org/numba-doc/dev/user/faq.html#how-can-i-tell-if-parallel-true-worked and will make it into the next release.

**Comment by seibert** [comment]
Closing since it looks like this was resolved.
