### ISSUE TITLE
Create a way to either check `parallel` worked, or warn if it was specified and it failed

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2461]
This ticket https://github.com/numba/numba/issues/2460 has a valid sample that doesn't have much performance change under the `parallel` target likely due to lack of work. It raises the question more generally of:

> If a user has specified `parallel=True` how does the user know if the function was able to be transformed and executed in parallel, given fall back to `njit` scalar execution is silent.

Options to resolve this:

1. Provide a function to check if a function will execute using the parallel scheduler.
2. Add a warning if `parallel=True` is requested but the function could not be transformed for parallel execution.
3. Both of the above.

**Comment by seibert** [comment]
I like both, since option 1 is handy for unit tests, but option 2 is better for users

**Comment by stuartarchibald** [comment]
#2493 adds in a warning mechanism. Checking a function will execute with the parallel scheduler at present requires inspection of the IR for calls to `@do_scheduling`. Locally I've put in a `CPUDispatcher.is_parallel` property such that users could do:
```python
import numpy as np
from numba import njit
@njit(parallel=True)
def foo(A):
  return A + 1

B = np.ones((10,))
res = foo(B)
assert foo.is_parallel
```
but need to convince myself that a false positive can't appear.
