### ISSUE TITLE
scipy.sparse support

### ISSUE THREAD

**Issue by seibert** [numba/numba#2465]
Multiple votes (from the librosa developer and others) for scipy sparse (CSR format at least) support. This would likely go into "scumba", but just wanted to record it here for posterity.

**Comment by ehsantn** [comment]
Scipy CSR support would be great!

**Comment by stuartarchibald** [comment]
See "scumba" discussion here: https://github.com/numba/numba/issues/4292

**Comment by stuartarchibald** [comment]
Closing as https://github.com/numba/numba-scipy is now the place for discussing SciPy support, ticket https://github.com/numba/numba-scipy/issues/29 tracks `scipy.sparse`.
