### ISSUE TITLE
Wheels for numba and llvmlite on Win/Mac/Linux

### ISSUE THREAD

**Issue by seibert** [numba/numba#2467]
This is a meta-issue to track progress on automatically building wheels along side the conda packages.  I expect Numba will be straightforward, but llvmlite will be tricky due to the need to use a different compiler to build LLVM and llvmlite's C wrapper around it than was used to build Python.

For forward compatibility, we should build the wheels using NumPy 1.11.

**Comment by xoviat** [comment]
LLVM can be built with msvc 2015, which is also used for Python 3.6.

**Comment by seibert** [comment]
True, but we need to support making wheels for Python 2.7, 3.4, 3.5, and 3.6.  Our current strategy seems to work with conda packages, so we just need to make sure the right thing happens with the wheel build.

**Comment by seibert** [comment]
Closed.  This was completed for Numba 0.35 (note pending issue to fix a compatibility problem reported in #2555)
