### ISSUE TITLE
Dispatcher test cache failures.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2473]
@ghatwala reports the following in https://github.com/numba/numba/issues/2451#issuecomment-316605512, tracking in this ticket as the issue is separate to that reported #2451.

```
$ /home/amit/numba# ls -l /usr/local/lib/python2.7/dist-packages/ | grep llvmlite
drwxr-sr-x  6 root staff   4096 Jul 19 10:26 llvmlite
drwxr-sr-x  2 root staff   4096 Jul 19 10:26 llvmlite-0.19.0.dist-info

$ /home/amit/numba# python -m numba.runtests numba.tests.test_dispatcher.TestCache

........ipython version: 5.4.1
...FFE...
======================================================================
ERROR: test_non_writable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
OSError: [Errno 2] No such file or directory: '/tmp/numba-tests.0/test_cache-_knByx/__pycache__'

======================================================================
FAIL: test_non_creatable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_dispatcher.py", line 956, in test_non_creatable_pycache
    self._test_pycache_fallback()
  File "numba/tests/test_dispatcher.py", line 946, in _test_pycache_fallback
    self.check_pycache(0)
  File "numba/tests/test_dispatcher.py", line 644, in check_pycache
    self.assertEqual(len(c), n, c)
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']

======================================================================
FAIL: test_non_writable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_dispatcher.py", line 968, in test_non_writable_pycache
    self._test_pycache_fallback()
  File "numba/tests/test_dispatcher.py", line 946, in _test_pycache_fallback
    self.check_pycache(0)
  File "numba/tests/test_dispatcher.py", line 644, in check_pycache
    self.assertEqual(len(c), n, c)
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']

----------------------------------------------------------------------
Ran 16 tests in 5.865s

FAILED (failures=2, errors=1)
```
For the error shown above , seems like file creation is failing
```
OSError: [Errno 2] No such file or directory: '/tmp/numba-tests.0/test_cache-_knByx/__pycache__'
```
and failures are due to assertion errors
```
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']
```

**Comment by stuartarchibald** [comment]
I'm afraid I cannot reproduce this anywhere locally. To debug this we'll need to be able to reproduce it which will likely mean having to reproduce your set up. Please could you say more about your installation... Did you build from source? Are you using conda packages? Do you have write access to `/tmp`? Is there sufficient space/inodes to write to `/tmp`? Anything else you think is relevant?

I also note that both these tests that fail are using a `tmpdir`, rely on disk access and mutate permissions. The lack of a temporary `__pycache__` directory is suspicious given `os.mkdir` created it.

Thanks.

**Comment by ghatwala** [comment]
@stuartarchibald - thanks for the responsde ...  here are my set up details/installation step.

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Stepping:              1
CPU MHz:               2593.992
BogoMIPS:              5187.98
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1

```
steps followed to build numba from source - right from this github page

Building and installing llvmlite

See https://github.com/numba/llvmlite for the most up-to-date instructions. You will need a build of LLVM 4.0.x.

$ git clone https://github.com/numba/llvmlite
$ cd llvmlite
$ python setup.py install

Installing Numba

$ git clone https://github.com/numba/numba.git
$ cd numba
$ pip install -r requirements.txt
$ python setup.py build_ext --inplace
$ python setup.py install
$ python runtests.py -v ( which is failing )

Also i had to install llvm(4.0.1 )  from source taken here - http://releases.llvm.org/download.html and installed using cmake using steps from here - http://llvm.org/docs/CMake.html 
   
I have complete r/w access to "tmp" folder
# ls -l / | grep tmp
drwxrwxrwt  12 root root  4096 Jul 20 14:44 tmp

Btw , i am running the entire test suite as "root" user , can this be a problem ?

**Comment by stuartarchibald** [comment]
@ghatwala Thanks for the extra information, I'm slightly suspicious that this is due to the use of the `root` user, can you reproduce using a user with no elevated rights? Thanks.

**Comment by ghatwala** [comment]
@stuartarchibald : unfortunately i have moved on to other open source packages and "numba" is currently not in my bucket of "to-do" list . Won't be able to evaluate this on power for sometime now at least.

**Comment by nehaljwani** [comment]
@stuartarchibald I am able to reproduce this exact same error when running the test as root user. Running the tests as a normal user passes all tests on Linux

Basically, `os.chmod('path/to/__pycache__', 0o500)`, modifies the permissions, but has no effect for root, as it doesn't restrict the user to write any file inside that directory:

```
# As root:
[root@centos7-nwani tmp]# mkdir blah && chmod 500 blah && touch blah/a
[root@centos7-nwani tmp]# echo $?
0
# As a non-root user:
[nwani@centos7-nwani ~]$ mkdir blah && chmod 500 blah && touch blah/a
touch: cannot touch ‘blah/a’: Permission denied
[nwani@centos7-nwani ~]$ echo $?
1
```

The options that come to my mind:
- Use chattr to set the immutable flag (which relies on the existence of that command), or implement setting the immutable flag using something like: https://stackoverflow.com/a/36274086/1005215 (overkill? unreliable?)
- Run the tests as the 'nobody' user on Unix.
- Skip this test if run as root (hmm... that's sad, bad)

**Comment by stuartarchibald** [comment]
@nehaljwani thanks for a) reproducing and b) diagnosing, much appreciated. I believe your diagnosis is correct and have added #2831 in an attempt to fix it. If possible, please could you run with that patch and see if it has the desired effect. Thanks.
