### ISSUE TITLE
Search box in docs from RTD is failing

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2489]
Search box in docs from RTD is failing, basicstrap has a seemingly related error. Try different theme to see if it fixes it.

**Comment by stuartarchibald** [comment]
Adding in this theme https://github.com/ryan-roemer/sphinx-bootstrap-theme and rebuilding makes the search box work again, so it's probably something broken in the basicstrap theme. Any suggestions for a new theme?

**Comment by seibert** [comment]
The sphinx-bootstrap-theme seems like a good alternative, maybe with the `"paper"` `bootswatch_theme` option: http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html#theme-options
