### ISSUE TITLE
if statement inside a for loop fails to compile

### ISSUE THREAD

**Issue by alexbw** [numba/numba#25]
Putting an if statement fails inside of a for loop.
I was writing some "find the index of the closest vector" code which wouldn't compile, and found this to be the source of the problem.

This works:

``` python
    from numba.decorators import jit
    import numba
    @jit(arg_types=[numba.double], ret_type=numba.double)
    def is_five(some_value):
        if some_value == 5.0:
            return 1.0
        else:
            return 0.0
```

This fails:

``` python
    @jit(arg_types=[numba.double], ret_type=numba.double)
    def is_REALLY_five(some_value):
        for i in range(5):
            if some_value == 5.0:
                return 1.0
        return 0.0
```

This is how it fails:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-3b23f7331ceb> in <module>()
----> 1 @jit(arg_types=[numba.double], ret_type=numba.double)
      2 def is_REALLY_five(some_value):
      3     for i in range(5):
      4         if some_value == 5.0:
      5             return 1.0

/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numba/decorators.pyc in _jit(func)
     77                   "garbage collected!" % (func,))
     78         t = Translate(func, *args, **kws)
---> 79         t.translate()
     80         __tr_map__[func] = t
     81         return t.get_ctypes_func(llvm)

/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numba/translate.pyc in translate(self)
    926                     # Ensure we are playing with locals that might
    927                     # actually precede the next block.
--> 928                     self.check_locals(i)
    929 
    930                 self.crnt_block = i

/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/numba/translate.pyc in check_locals(self, i)
   1135                 else:
   1136                     assert next_locals is not None, "Internal compiler error!"
-> 1137             self._locals = next_locals[:]
   1138 
   1139     def get_ctypes_func(self, llvm=True):

TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by mvaladas2020** [comment]
Strange, works for me with numba 0.48.0 but fails with latest 0.51.1...

from numba.decorators import jit
import numba

@jit(arg_types=[numba.double], ret_type=numba.double)
def is_REALLY_five(some_value):
    for i in range(5):
        if some_value == 5.0:
            return 1.0
    return 0.0

**Comment by gmarkall** [comment]
> Strange, works for me with numba 0.48.0 but fails with latest 0.51.1...
> 
> from numba.decorators import jit
> import numba
> 
> @jit(arg_types=[numba.double], ret_type=numba.double)
> def is_REALLY_five(some_value):
> for i in range(5):
> if some_value == 5.0:
> return 1.0
> return 0.0

The `numba.decorators` module was removed, and you can import `jit` from `numba` instead. 

If you have any further issues, please start a thread on the Numba Discourse (https://numba.discourse.group) describing your issue / question.

**Comment by mvaladas2020** [comment]
> The `numba.decorators` module was removed, and you can import `jit` from `numba` instead.
> 
> If you have any further issues, please start a thread on the Numba Discourse (https://numba.discourse.group) describing your issue / question.

Thank you for your update.

**Comment by phanirohith** [comment]
I tried both versions numba 0.48.0, 0.51.1, still, the if loop is getting failed.

**Comment by esc** [comment]
> I tried both versions numba 0.48.0, 0.51.1, still, the if loop is getting failed.

@phanirohith thank you for bringing this to our attention. This seems like a regression. Can you please open a new issue and add the code your have as a reproducer. We will take a closer look then. Thank you!
