### ISSUE TITLE
Numba support for numpy.correlate()?

### ISSUE THREAD

**Issue by echavess** [numba/numba#2500]
Dear all, 

I was trying to @jit(nopython=True) one of my functions which runs numpy.correlate() and found that Numba still does not support it. Is there any idea of when this feature is going to be supported? May I request, please, support to this function and others like numpy.convolve() ?? These two functions are very important for digital signal processing.

Thanks very much in advance

**Comment by ThomasA** [comment]
I also ran into this issue just now.

**Comment by echavess** [comment]
Hi guys, any updates? Will appreciate if Numba provides support to numpy.correlate and numpy.convolve. 

Thanks in advance,

**Comment by stuartarchibald** [comment]
@echavess I was working on this last week but had to go and do some other things. Hopefully it'll be done soon! Also, out of interest, is there a desire for FFT calls to be accepted by Numba, e.g. `np.fft.fft` ?

**Comment by mbargull** [comment]
Sure, that would be nice. `numpy.correlate` will just be too slow for larger inputs. Hence something like `scipy.signal.fftconvolve`, or more flexible, `numpy.fft` would be nice.
Some time ago I started to write some (incomplete/special-purpose) wrapper around MKL/FFTW via `cffi` to be used with Numba. In the meantime https://github.com/IntelPython/mkl_fft came out -- that might be of interest to people looking to implement fast convolution/correlation (I have yet to check that out...).
