### ISSUE TITLE
Numba should flatten np.dot calls

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#251]
If np.dot is called from within a routine, compiled with numba, things become slow. Test program:

``` python
""" Compare the performance of np.dot and the performance of a flattened version of it. """
import numpy as np
import time
from numba import double, jit

def product(vec1, vec2):  
    res = double(0.0)  
    for i in range(100000):
        res = res + np.dot(vec1, vec2)        
    return res

def flat_product(vec1, vec2):  
    res = double(0.0) 
    for i in range(100000):
        res = res + vec1[0] * vec2[0] + vec1[1] * vec2[1] + vec1[2] * vec2[2]    
    return res

fast_product = jit(double(double[:], double[:]))(product)    
fast_flat_product = jit(double(double[:], double[:]))(flat_product)    

if __name__ == '__main__':
    vec1 = np.array((1.0, 2.0, 3.0))
    vec2 = np.array((2.0, 3.0, 4.0))
    t1 = time.time()
    print product(vec1, vec2)  
    t1 = time.time() - t1
    print "product, using np.dot: time without numba", t1
    t2 = time.time()    
    print fast_product(vec1, vec2)
    t2 = time.time() - t2    
    print "product, using np.dot: time using numba", t2    
    t3 = time.time()
    print flat_product(vec1, vec2)  
    t3 = time.time() - t3
    print "flat product: time without numba", t3
    t4 = time.time()    
    print fast_flat_product(vec1, vec2)
    t4 = time.time() - t4    
    print "flat product: time using numba", t4  
    print
    print "Relative speed, using numpy: ", t3/t1     
    print "Relative speed, using numpy + numba: ", t3/t2 
    print "Relative speed, using flattening + numba: ", t3/t4 
```

Example output:
2000000.0
product, using np.dot: time without numba 0.0772180557251
2000000.0
product, using np.dot: time using numba 0.0460867881775
2000000.0
flat product: time without numba 0.176540136337
2000000.0
flat product: time using numba 0.000229120254517

Relative speed, using numpy:  2.28625461596
Relative speed, using numpy + numba:  3.83060185616
Relative speed, using flattening + numba:  770.513007284

Numba should automatically replace calls to np.dot with the flattened version.

**Comment by mabl** [comment]
@jayvius:
While the posted benchmark code is far from perfect. I fail to  see how this is resolved. If I use np.dot, I'm forced back to object mode. The posted code also still gives comparable results:

```
Numba Version 0.20.0
2000000.0
product, using np.dot: time without numba 0.074413061142
2000000.0
product, using np.dot: time using numba 0.16571521759
2000000.0
flat product: time without numba 0.0851860046387
2000000.0
flat product: time using numba 0.000572919845581

Relative speed, using numpy:  1.14477221245
Relative speed, using numpy + numba:  0.514050585561
Relative speed, using flattening + numba:  148.687473991
```

I'm sure I'm not the only one, looking for painless small matrix dot products compatible to np.dot.

Do you have any advice?

**Comment by pitrou** [comment]
I don't think the benchmark code is correct. In the flat_product version, LLVM is probably able to detect that the product is the same at every iteration, and to optimize out the loop radically (explaining the 150x speedup).
