### ISSUE TITLE
njit(parallel=True) causes lost of array changes when array is passed in for both input&output purposes

### ISSUE THREAD

**Issue by jakenetdot** [numba/numba#2514]
numba version:

> *  0.34.0              np113py36_0  defaults   

 

code
 
```
from numba import jit, njit
import numpy as np  

@njit(parallel=True)
def test7(a):
    length = a.size
    for i in range(length):
        test8(i, a)
    return a

@njit(parallel=True)
def test8(i, a):
    if i>4:
        a[i] = i
    # print(a[i])  # comment or uncomment this line with have different output
    return 0
    
a = np.zeros(8, dtype=np.float64)
output = test7(a)
print(output)
```
comment `print(a[i])` will output:

> [ 0.  0.  0.  0.  0.  0.  0.  0.]

uncomment `print(a[i])` will output:

> [ 0.  0.  0.  0.  0.  5.  6.  7.]

I think print statement shouldn't alter the output in such a way

**Comment by ehsantn** [comment]
The array changes issue is already fixed in master branch. But I get an error when the print is enabled: `RuntimeError: missing Environment`.

This might be related to the runtime environment issue with prints @sklam

**Comment by seibert** [comment]
Closing since the array problem was fixed and the printing issue is being tracked in #2411.
