### ISSUE TITLE
How to acknowledge Numba in research work?

### ISSUE THREAD

**Issue by bmer** [numba/numba#2524]
Numba has been tremendously helpful in my research work, and we are about to publish a paper based on the simulation work Numb  helped speed up. I recall seeing some instructions regarding how to acknowledge Numba once upon a time (must be a couple of years ago now), but am having trouble finding it. Could someone link me to it, or perhaps add some documentation which clarifies this?

**Comment by seibert** [comment]
For academic usage, the best option is to cite our ACM Proceedings:

http://dl.acm.org/citation.cfm?id=2833162&dl=ACM&coll=DL&CFID=802557709&CFTOKEN=62303067

I'll leave this issue open to remind us to add this to the documentation.

**Comment by bmer** [comment]
Thank you!
