### ISSUE TITLE
support for warp vote functions

### ISSUE THREAD

**Issue by wpc009** [numba/numba#2530]
It seems that numba cuda does not support warp vote functions, like `__all`  `__ballot` `__popc` and so on.
Does there any plan for this?

**Comment by wpc009** [comment]
`warp vote functions` are crutial for some optimazation.
eg. https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-optimized-filtering-warp-aggregated-atomics/

**Comment by gmarkall** [comment]
Warp vote functions are implemented: https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html#warp-intrinsics - if any are missing, new issues should be opened for them.
