### ISSUE TITLE
support for fill function 

### ISSUE THREAD

**Issue by talkaminker** [numba/numba#2531]
`fill` function of arrays is a very handy way to zero out an existing array (like memset in C)
in regular python:
```
a = np.arange(10)
a.fill(0)
```
will zero out `a`
this is a very simple function to support and might save us from writing some unnecessary loops. 
Thanks!

**Comment by stuartarchibald** [comment]
Added as feature request. In the meanwhile would broadcast assignment help a bit?
```
a = np.arange(10)
a[:] = 0
```

**Comment by talkaminker** [comment]
I didn't realize this works.
Thanks!
