### ISSUE TITLE
SIGSEGV for cached, guvectorize functions compiled in object mode

### ISSUE THREAD

**Issue by jcmgray** [numba/numba#2554]
If caching a ``guvectorize`` function that is compiled in object mode, upon calling the cached function, the process is terminated with a SIGSEGV (or python.exe has stopped working etc.)

For example running the following script:
```python
from numba import double, guvectorize
import numpy as np

@guvectorize([
    (double[:], double[:]),
], '(n)->(n)', cache=True, forceobj=True)
def gufunc(x, out):
    out[:] = x + 1

if __name__ == "__main__":
    print(gufunc(np.array([1.0, 2.0, 3.0])))
```
The first time yields:
```bash
[ 2.  3.  4.]
```
But the second time yields:
```bash
... “python ...py” terminated by signal SIGSEGV (Address boundary error)
```

Tested on a couple of ubuntu 16.04 machines and windows, with numba 0.35.

**Comment by stuartarchibald** [comment]
Thanks for the report and minimal reproducing sample. I can reproduce locally, will take a better look shortly.

**Comment by stuartarchibald** [comment]
This does not reproduce on version 0.43.1. Closing.
