### ISSUE TITLE
List of memory-managed objects

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#2560]
Currently, creating a list of memory-managed objects like Numpy arrays in `nopython` mode throws this error: `unsupported nested memory-managed object`.

How difficult is it to support this?

**Comment by stuartarchibald** [comment]
For anyone looking, lists of `nested memory-managed objects` would include things like:
 * list of lists
 * list of sets
 * list of NumPy arrays (and extensions of/arrays like)

**Comment by hameerabbasi** [comment]
Is extending this issue's scope to include nested memory-managed objects in general, such as `set[list]`, `set[set]`, `list[set[set]]`, etc. better or would opening a separate issue be more appropriate?

**Comment by shilu1984** [comment]
looking forward to this feature being implemented in numba 0.38.  It is cumbersome to write linked list of jitclass.

**Comment by hameerabbasi** [comment]
Hello. Is this feature likely to make it into Numba 0.39? And will it have nested memory managed objects, or just lists?

I ask because it's a blocker for quite some things in pydata/sparse.

**Comment by jllanfranchi** [comment]
I, too, have encountered several instances where not having this (even just a single-deep list of numpy arrays) makes me have to jump through hoops and write ugly code to get something to work (if at all). This feature would be a huge boon to my using Numba (and this greatly broadens the scope of the kinds of problems that can be solved with Numba).

**Comment by shoyer** [comment]
> Is extending this issue's scope to include nested memory-managed objects in general, such as set[list], set[set], list[set[set]], etc. better or would opening a separate issue be more appropriate?

These aren't valid in Python -- do you mean set[tuple], set[frozenset], list[set[frozenset]], etc?

**Comment by stuartarchibald** [comment]
Closing, this was added in https://github.com/numba/numba/pull/2840 and is in the 0.39.0 release.
