### ISSUE TITLE
How to get CUstream object from numba cuda stream?

### ISSUE THREAD

**Issue by anshumang** [numba/numba#2567]
Usecase is -
s = cuda.stream()
SomeCfunc(... s)

**Comment by stuartarchibald** [comment]
The cuda steam is bound via `ctypes`, you can access a `c_void_p` to the stream from the instance's `handle` attr.
```python
from numba import cuda
s = cuda.stream()
print(s)
print(s.handle)
```
gives e.g.:
```
<CUDA stream 30338928 on <CUDA context c_void_p(30367744) of device 0>>
c_void_p(30338928)
```

**Comment by anshumang** [comment]
Thanks @stuartarchibald , closing
