### ISSUE TITLE
@guvectorize with target='cuda' ?

### ISSUE THREAD

**Issue by pbruneau** [numba/numba#2579]
Dear all, 

I've just started using numba, and investigating how to run code on my GPU using it.

The following minimal example runs successfully:

    import numpy as np
    from numba import vectorize, guvectorize, int32
    
    @vectorize([int32(int32)])
    def f(x):
        return x + 2
    
    vec = np.array([1, 2, 3, 4], dtype=np.int32)
    print(f(vec))
    [3 4 5 6]

I also found out about @guvectorize - one equivalent way to implement is then:

    @guvectorize(['void(int32[:],int32[:],int32[:])'], '(n),()->(n)')
    def g(x,y,res):
        for i in range(x.shape[0]):
            res[i] = x[i] + y[0]
    
    res = np.zeros(4, dtype=np.int32)
    a = np.array([1, 2, 3, 4], dtype=np.int32)
    b = np.array([2], dtype=np.int32)
    g(a,b,res)
    print(res)
    [3 4 5 6]

Now, if I try to use `target='cuda'` in both `@vectorize` and `@guvectorize`, the former succeeds, and the latter fails (even for such a trivial case) :

    [...]
    TypingError: Failed at nopython (nopython frontend)
    Invalid usage of Function(<DeviceFunction py_func=<function g [...]

Is this to be expected? 
I'm very interested in the flexibility offered by @guvectorize (e.g. tensor operations with spec such as `(m,n),(p,m,n)->(p)`) - even more if cuda-powered :)

**Comment by sklam** [comment]
There's definitely a bug here in the cuda target.  The scalar input (arg `y`) is mishandled.
