### ISSUE TITLE
Eliminate warp synchronous code from CUDA kernels

### ISSUE THREAD

**Issue by seibert** [numba/numba#2589]
Warp synchronous code has been discouraged for several CUDA releases, and now with CUDA 9 and Volta, threads in a warp are no longer guaranteed to execute together.  I found one place in Numba where kernels are generated that assume warp synchronicity:

https://github.com/numba/numba/blob/1a4cf39e982dd565be08ec5eae63989da3ce3aa1/numba/cuda/kernels/reduction.py

I don't know if there are others.  We need to change this kernel to work on Volta.

**Comment by gmarkall** [comment]
https://github.com/numba/numba/pull/6127 fixes the reduction for Volta+. I don't believe there are any other places in Numba where this assumption is made, so I think this issue should be closed once #6127 is merged.
