### ISSUE TITLE
Lowering error when removing element from the middle of linked list

### ISSUE THREAD

**Issue by chbrandt** [numba/numba#2606]
Hi

I am having a hard time trying to figure out an error when I reassign "element_0.next = element_1.next" of a linked list. I posted my error at stackoverflow: https://stackoverflow.com/questions/47232035/numba-lowering-error-when-reassigning-next-link-of-a-linked-list-element

I am creating this issue to make it closer to you.

I have visited most of your examples and documentation pages, no ideas whatsoever.

What am I missing?

I am using numba **0.35.0** (from Anaconda, python 3.6.2).

Thanks

**Comment by sklam** [comment]
I can confirm that this is an internal error in the compiler.
