### ISSUE TITLE
Wrong result with parallel flag on

### ISSUE THREAD

**Issue by dk1013** [numba/numba#2609]
Version info: Ubuntu 16.04, Python 2.7.13, numba 0.35.0, numpy 1.11.0.
I think a simple code that reproduces the bug better describes the issue:

``` python
@jit(nopython=True, parallel=True)
def get(n):
    return np.ones((n,1), dtype=np.float64)

print(get(40))
```
The result is
``` python
[[ -1.363e+57]
 [ -1.363e+57]
 [ -1.363e+57]
 [ -1.363e+57]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]
 [  1.000e+00]]
```

If I set parallel to False, the result will be correct.
Edit:
I found that if you run `print(get(30))`, the result will be correct. I guess it has something to do with threading, so the number of available cores (16 cores & 32 threads with hyper-threading) of my computer may be relevant here.

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm struggling to reproduce this and have juggled the code to run many different sizes and have run it many times. How often does this occur, every time or just sometimes? Thanks.

**Comment by dk1013** [comment]
Hi @stuartarchibald Thanks for testing it. I tried many times and it happens every time with exactly the same wrong result. Oh by the way, I am using the one comes with anaconda. May I know which version of numba are you using? Thanks.

**Comment by stuartarchibald** [comment]
Thanks for the extra info. I'm working off the development head so it's quite possible its already been fixed.

The code:
```python
from numba import jit
import numpy as np


for x in range(1, 100):
    print(x)
    @jit(nopython=True, parallel=True)
    def get(n):
        return np.ones((n,1), dtype=np.float64)
    np.testing.assert_allclose(get(x), np.ones((x, 1), dtype=np.float64))
```
reproduces for me using the package that is in the default channel (`numba 0.35.0 np113py36_10` for x85_64 linux, with `__version__` as `0.35.0+10.g143f70e90`, slightly strange you have a `.dirty` package?!?).

Also, the same with a `range` starting at zero hangs. As I can reproduce what you see in 0.35 but not on the development line for 0.36, please could you try using numba from the numba channel if you have the capacity to do so?
```
conda create -n foo -c numba numba
```
will create an environment `foo` containing the latest build of `Numba`.

Thanks again.

**Comment by dk1013** [comment]
Hi @stuartarchibald , I just installed numba v0.36 following your suggestion. The bug is gone with the new version. Just curious, what caused this error for numba v0.35? Cheers!

**Comment by stuartarchibald** [comment]
That's great, thanks for letting us know, I'm going to close this ticket.

As to what caused it, `parfor.py` is huge and experiencing a lot of churn at present including this large pull request/feature https://github.com/numba/numba/pull/2457 so I'm afraid I cannot quickly or easily highlight the fixing change. Thanks for your understanding and for using Numba.
