### ISSUE TITLE
Memory leak isssue

### ISSUE THREAD

**Issue by dk1013** [numba/numba#2614]
Environment: Ubuntu 16.04, Numba 0.36.0.dev.
I have some codes that extensively use Numba for acceleration and have to run for very long time.
I found that the memory usage of my process kept going up, which is quite serious as my 128GB RAM can be depleted in just one day.
I have been able to reproduce this problem with a minimal code snippet as shown below.
I also found that the issue was gone or at least much less serious if I set `parallel` to `False` and used `range` instead of `prange`.
So I guess this is probably related to the parallel feature.
``` python
from numba import jit, prange
import numpy as np

@jit(nopython=True, parallel=True)
def square(A):
    out = np.empty(A.shape, dtype=np.float64)
    for r in range(A.shape[0]):
        temp = np.empty(A.shape[1], dtype=np.float64)
        for c in range(A.shape[1]):
            temp[c] = A[r, c] ** 2
        for c in range(A.shape[1]):
            out[r, c] = temp[c] ** 2
    return out

for i in range(1000000):
    x = np.random.random((2000, 2000))
    square(x)
    print(i)
```
I found a workaround that might give the same result without this issue:
``` python
@jit(nopython=True, parallel=True)
def square(A):
    out = np.empty(A.shape, dtype=np.float64)
    temp = np.empty(A.shape, dtype=np.float64)
    for r in prange(A.shape[0]):
        for c in range(A.shape[1]):
            temp[r, c] = A[r, c] ** 2
        for c in range(A.shape[1]):
            out[r, c] = temp[r, c] ** 2
    return out
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I've run this using the first code sample with `for r in range` then `for r in prange`. For `range` I see <150Mb `RSS`. For `prange` I do see `RSS` per thread creeping up as time goes by, needs more investigation.

**Comment by dk1013** [comment]
Hi @stuartarchibald , may I know if there is any progress on this issue? Thanks!

**Comment by crisla** [comment]
Hi, I'm using numba 0.39 and the same issue happens to me too. I thought it was fixed in the 0.37 release?

**Comment by stuartarchibald** [comment]
@crisla This should be fixed, do you have a reproducer please?

I just ran this locally (Numba ~=0.40.0):
```python
from numba import jit, prange
import numpy as np
import threading
from psutil import Process
import time
import matplotlib.pyplot as plt

@jit(nopython=True, parallel=True)
def square(A):
    out = np.empty(A.shape, dtype=np.float64)
    for r in range(A.shape[0]):
        temp = np.empty(A.shape[1], dtype=np.float64)
        for c in range(A.shape[1]):
            temp[c] = A[r, c] ** 2
        for c in range(A.shape[1]):
            out[r, c] = temp[c] ** 2
    return out

def runtarget():
    for i in range(1000):
        x = np.random.random((2000, 2000))
        square(x)

if __name__ == "__main__":
    th = threading.Thread(target=runtarget)
    th.start()
    threads = Process().threads()
    print(threads)
    thread_proc = Process(threads[1].id)
    rss_stamps = []
    period = 0.05
    while(th.is_alive()):
        time.sleep(period)
        try:
            rss = thread_proc.memory_info().rss
        except BaseException:
            # timing delay, proc may be dead
            rss = 0.
        rss_stamps.append(rss)

    th.join()

    mb = 1 << 20
    rss_raw = np.array(rss_stamps) / float(mb)
    time = np.arange(rss_raw.size) * period
    plt.plot(time, rss_raw, '.')
    plt.grid()
    plt.xlabel('time(s)')
    plt.ylabel('RSS(Mb)')
    plt.savefig('memuse.png')
```
which  produced this:

![memuse](https://user-images.githubusercontent.com/907717/46210672-4bf19880-c329-11e8-8020-306ac42beecc.png)


Watching `htop` showed 175Mb RSS max too.

**Comment by crisla** [comment]
@stuartarchibald I ran your code and it works fine, the memory issue must be coming from somewhere else. Thanks!

**Comment by stuartarchibald** [comment]
@crisla thanks for confirming. If you do find it is something in numba that is leaking please do open a new issue. Thanks again.
