### ISSUE TITLE
Cannot call function under prange 

### ISSUE THREAD

**Issue by Melisius** [numba/numba#2616]
Hi,

I tried to use Numba parallel for a loop for which function calls are made inside (of the loop). I Have boiled the problem down to the following code:

    from numba import jit, prange, int64
    
    @jit(int64(int64, int64),nopython=True)
    def sum(a,b):
        return a + b
    
    @jit(int64(int64, int64),nopython=True)
    def run_program(N,M):
        total = 0.0
        for i in range(0, N):
            for j in range(0, M):
                total += sum(i,j)
        return total
    
    @jit(int64(int64, int64), nopython=True, parallel=True)
    def run_program_parallel_1(N,M):
        total = 0.0
        for i in prange(0, N):
            for j in range(0, M):
                total += i + j
        return total
    
    @jit(int64(int64, int64), nopython=True, parallel=True)
    def run_program_parallel_2(N,M):
        total = 0.0
        for i in prange(0, N):
            for j in range(0, M):
                total += sum(i, j)
        return total
    
    N = 1000
    M = 2000
    print(run_program(N, M))
    print(run_program_parallel_1(N,M))
    print(run_program_parallel_2(N,M))

I tried to run the code from the windows linux subsystem.  And got the error:

    AttributeError: Failed at nopython (convert to parfors)
    'Integer' object has no attribute 'dtype'

The functions run_program( ) and run_program_parallel_1( ) works fine, but the last function (run_program_parallel_2( )) gives the error.  Maybe Numba Parallel is not supposed to support this yet? Anyway I couldn't find any answer by the use of google, and though I would therefore report it as an issue.

**Comment by stuartarchibald** [comment]
Thanks for the report. This appears to be fixed on the master branch (I'm working from a branch based on master at present and get the following). The soon to be released version 0.36 will contain the fix.

```python
from numba import jit, prange, int64
import numba

@jit(int64(int64, int64),nopython=True)
def sum(a,b):
    return a + b

@jit(int64(int64, int64),nopython=True)
def run_program(N,M):
    total = 0.0
    for i in range(0, N):
        for j in range(0, M):
            total += sum(i,j)
    return total

@jit(int64(int64, int64), nopython=True, parallel=True)
def run_program_parallel_1(N,M):
    total = 0.0
    for i in prange(0, N):
        for j in range(0, M):
            total += i + j
    return total

@jit(int64(int64, int64), nopython=True, parallel=True)
def run_program_parallel_2(N,M):
    total = 0.0
    for i in prange(0, N):
        for j in range(0, M):
            total += sum(i, j)
    return total

N = 1000
M = 2000

print(numba.__version__)
print(run_program(N, M))
print(run_program_parallel_1(N,M))
print(run_program_parallel_2(N,M))
```
output:
```
0.36.0.dev+414.g75f8881
2998000000
2998000000
2998000000
```
