### ISSUE TITLE
LoweringError from tuple argument with `parallel=True`

### ISSUE THREAD

**Issue by oyamad** [numba/numba#2625]
The following script raises a `LoweringError`:

```py
import numpy as np
from numba import njit, prange

@njit(parallel=True)
def prange_test_tuple(t):
    s = 0
    for i in prange(t[0].shape[0]):
        s += t[0][i]
    return s
```

```py
prange_test_tuple((np.arange(3),))
```

```
TypeError

(Traceback skipped)

LoweringError: Failed at nopython (nopython mode backend)
scalar type (array(int64, 1d, C) x 1) given for non scalar argument #2
File "<ipython-input-7-4ed0d63d9692>", line 4
[1] During: lowering "[LoopNest(index_variable = parfor_index.64, range = (0, $6.7, 1))]{26: <ir.Block at <ipython-input-7-4ed0d63d9692> (4)>}Var(parfor_index.64, <ipython-input-7-4ed0d63d9692> (4))" at <ipython-input-7-4ed0d63d9692> (4)
```

This function works fine with `parallel=False`. Is a tuple argument not supported?

```py
numba.__version__
'0.36.0.dev+410.g9ed665e'
```

**Comment by stuartarchibald** [comment]
I think this is because the `gufunc` implementation does not support tuples and the `parallel=True`+`prange` combination uses `gufunc`-like functions to perform the executions across the iteration space in parallel. More details about the implementation can be found here: http://numba.pydata.org/numba-doc/dev/developer/architecture.html#stage-6b-perform-automatic-parallelization

**Comment by oyamad** [comment]
@stuartarchibald Thank you for your quick response. I will make it something like `func(tuple_element0, tuple_element1)` (which is possible in my use case).

**Comment by stuartarchibald** [comment]
No problem. For anyone else who hits this issue, we are aware of this limitation and considering options for working around this.

**Comment by flying-sheep** [comment]
Why is this bug closed? This is still an issue.

**Comment by Wandersalamander** [comment]
Hey, this error is resolved by converting t to a list
My numba version is 0.49.0.dev0+18.ge2dc1ae45-py3.7-win-amd64
~~~~
import numpy as np
from numba import njit, prange


@njit(parallel=True)
def prange_test_tuple(t):
    s = 0
    t = list(t)
    for i in prange(t[0].shape[0]):
        s += t[0][i]
    return s


prange_test_tuple((np.arange(3),))
~~~~

**Comment by flying-sheep** [comment]
Great, but that’s a workaround. @oyamad please open this again.
