### ISSUE TITLE
Numba Can't  work with CUDA 9.0？

### ISSUE THREAD

**Issue by zjrongxiang** [numba/numba#2629]
When i check numba with：`numba -s`
then I get this error:
```
__CUDA Information__
Error: CUDA device intialisation problem. driver missing function: cuInit.
Requires CUDA 7.5 or above.
Error class: <class 'numba.cuda.cudadrv.error.CudaDriverError'>
```
Versions installed:

Python 3.6.3 | Anaconda3(64-bit)
CUDA toolkit 9.0
GPU - GeForce 1080
OS - 16.04.1-Ubuntu

.bashrc file：

export NUMBAPRO_NVVM=/usr/local/cuda-9.0/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=/usr/local/cuda-9.0/nvvm/libdevice
export NUMBAPRO_CUDA_DRIVER=/usr/local/cuda-9.0/lib64/libcudart.so

I installed numba use ： conda install numba

Please help!

**Comment by stuartarchibald** [comment]
Thanks for the report. I think there are two problems here:
1. CUDA 9 is not yet supported, it is however planned, with dependency on updates to this https://github.com/numba/conda-recipe-cudatoolkit/
2. The `NUMBAPRO_CUDA_DRIVER` env var needs to hold reference to the driver DSO not the runtime, this is typically located somewhere like: `/usr/lib64/nvidia/libcuda.so.<version>`.

If can get by with the CUDA 8 tool kit you can get it with `conda install cudatoolkit=8`.

CUDA 9 support will need a load of code changes in Numba to probably adjust to new minimum SM/arch levels, deal with a new `libdevice` file layout and to fix a tests that look for certain strings in IR.

**Comment by zjrongxiang** [comment]
@stuartarchibald Thanks!
