### ISSUE TITLE
Optional automatic JIT of called functions

### ISSUE THREAD

**Issue by seibert** [numba/numba#2634]
(Based on discussion in #2630)

A good use case for Numba is transparent compilation of user-defined functions as part of a larger API.  This works if the user supplies a monolithic UDF that only calls functions Numba is already aware of, then you just wrap the UDF with `@jit`.  If the user has created helper functions that are called from the UDF, the only possible compilation mode for the main UDF would be object mode or do a lot of hackery to rewrite the UDF to call JIT compiled versions of the helper functions that are created on behalf of the user.

This would be vastly simplified if one could have Numba transform the function body to replace all calls to functions (not already known to the compiler) with JIT-wrapped versions of those functions.  For lack of a better name, this option to `@jit` could be indicated with `callees=True`.

Some design thoughts for discussion:
* I think `callees` should default to False: Compiling undecorated functions is unexpected behavior we only want to attempt if the user opts in.  Existing code would be unaffected by this change.
* The compilation of the callees should inherit the JIT options of the caller (nopython, error_mode, parallel, fastmath, etc).  This would include `callees=True` itself, which automatically makes the compilation recursive.
* To avoid accidentally trying to compile all of matplotlib (for example), we need to ensure that this can fail fast:
  - Make sure to do the recursive compilation depth first, so we can abort before consuming a ton of memory?
  - Should we only allow `callees=True` in conjunction with nopython mode?  This is going to be the primary use case (object mode is not going to do much at the moment), and being more restrictive, nopython mode is more likely to cut off a futile compilation attempt early. 
  - Should we have a max recursion depth for compilation?

**Comment by dhirschfeld** [comment]
Bikeshedding on the argument name, `recurse=True` seems more obvious to me. 

...or `recurse_depth=0` as a default and then the user could override that to allow recursive compilation of nested functions to any arbitrary depth.

**Comment by seibert** [comment]
Yeah, I initially avoided that name because I was afraid it would be confused somehow with support recursively callable functions, but in retrospect, that was silly on my part.

+1 for using `recurse`.   recurse_depth (if we do it at all) should be a separate option that hopefully most people don't ever need to modify.

**Comment by vnmabus** [comment]
This is marked as completed in #4331, but that PR does something completely different from this (it compiles all the functions in a module). In my case I want to compile a function that calls another which calls another and I want all of these compiled BUT I also want to keep the non-compiled versions to compare them in benchmarks. Currently I do that using a wrapper per function, that chooses between compiled and non-compiled version to call, but that is ugly and difficult to maintain.
