### ISSUE TITLE
[Temporary fix found] SyntaxError: unqualified exec is not allowed in function '_add_offset_to_slice' ...

### ISSUE THREAD

**Issue by samirelo** [numba/numba#2642]
When trying to `import numba` after having installed numba from source (v0.36.1) using pip ( installed using command `pip install git+https://github.com/numba/numba.git#egg=numba` ) on a virtualenv environment ( created using command `virtualenv env` in the folder named `Numba_venv` ), I encountered the following error:

`Traceback (most recent call last):`
    `File "<stdin>", line 1, in <module>`
    `File "/home/samir/Numba_venv/env/lib/python2.7/site-packages/numba/__init__.py", line 12, in <module>`
        `from .special import typeof, prange`
    `File "/home/samir/Numba_venv/env/lib/python2.7/site-packages/numba/special.py", line 4, in <module>`
        `from .parfor import prange`
    `File "/home/samir/Numba_venv/env/lib/python2.7/site-packages/numba/parfor.py", line 25, in <module>`
        `from numba import stencilparfor`
    `File "/home/samir/Numba_venv/env/lib/python2.7/site-packages/numba/stencilparfor.py", line 544`
        `exec(f_text, {}, loc)`
`SyntaxError: unqualified exec is not allowed in function '_add_offset_to_slice' it contains a nested function with free variables`

Ignoring this and trying `import numba` once again produced:

`Traceback (most recent call last):`
    `File "<stdin>", line 1, in <module>`
    `File "/home/samir/Numba_venv/env/lib/python2.7/site-packages/numba/__init__.py", line 9, in <module>`
        `from . import config, errors, runtests, types`
`ImportError: cannot import name config`

There doesn't seem to be any circular imports, and so I can't understand the second error. However, the first error seems to be (from what I found) a python version issue (since my python version in the virtualenv is 2.7.8) which i read [here](https://stackoverflow.com/a/41368813).

**Finally, installing the earlier version 0.35.0** ( using command `pip install git+https://github.com/numba/numba.git@0.35.0#egg=numba` ) **fixed the issue**.

Would love to know what really caused both errors,
Thank you!

EDIT: My sincere apologies if this issue isn't related to numba, I'll delete/close it myself.

**Comment by seibert** [comment]
Is this Linux 64-bit?

**Comment by sklam** [comment]
Looks like it is hitting [python issue 21591](https://bugs.python.org/issue21591).   The python bug is fixed in 2.7.9.

**Comment by samirelo** [comment]
Yes @seibert, I run it on a:
64-bit Ubuntu 14.04 (14.04.5 LTS Trusty)
gcc/g++ 4.9.4
clang-5.0.1-svn319952-1~exp1 (branches/release_50)
llvm-5.0.1

`pip freeze` returns:

`enum34==1.1.6`
`funcsigs==1.0.2`
`llvmlite==0.21.0`
`numba==0.36.1`
`numpy==1.13.3`
`singledispatch==3.4.0.3`
`six==1.11.0`
