### ISSUE TITLE
Parallel / prange - handling input arrays in Fortran order

### ISSUE THREAD

**Issue by rjenc29** [numba/numba#2656]
In the example below, the use of parallel / prange raises a LoweringError in the case that the input array is Fortran order (numba 0.36.1).

As a consumer, I can externally check and convert to C order where required, for example, so this is by no means a blocker.

However, I'm raising this issue in case the team feel some kind of change is merited - whether handling internally; raising a more specific Exception; guidance in the docs or anything else.

```python
from numba import njit, prange
import numpy as np


@njit(parallel=True)
def add_one_columnwise(A):

    n = A.shape[1]
    output = np.empty_like(A)

    for i in prange(n):
        output[:, i] = A[:, i] + 1

    return output


def main():

    # Scenario 1: this passes fine
    data = np.arange(4).reshape(2, 2)
    expected = np.arange(1, 5).reshape(2, 2)

    output = add_one_columnwise(data)
    assert np.allclose(output, expected)

    # Scenario 2: as above but input array in Fortran order
    data = np.asfortranarray(data)

    output = add_one_columnwise(data)  # -> raises LoweringError
    assert np.allclose(output, expected)


if __name__ == '__main__':
    main()
```

**Comment by stuartarchibald** [comment]
Thanks for the report and trying this out, the C-order restriction under parfors is a known limitation, labelling this as a feature request.

**Comment by stuartarchibald** [comment]
Closing as fixed in https://github.com/numba/numba/pull/5659.
