### ISSUE TITLE
Default Parameters in Class

### ISSUE THREAD

**Issue by ghost** [numba/numba#2661]
Using jitclass when functions have default parameters fails. 

Minimal working example:
```
spec = [
    ('a', numba.float32),
    ('b', numba.float32),
    ('c', numba.float32),
]     

@numba.jitclass(spec)
class Test:
    def __init__(self, a=1, b=2, c=3):
        self.a = a
        self.b = b
        self.c = c

test = Test()
```
Error message:
```
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    test = Test()
  File "/home/user/.local/lib/python3.5/site-packages/numba/jitclass/base.py", line 114, in __call__
    return cls._ctor(*args, **kwargs)
TypeError: not enough arguments: expected 3, got 0
```

```

**Comment by stuartarchibald** [comment]
Thanks for the report, I don't think this is currently supported.

**Comment by holmrenser** [comment]
Just ran into this, would love to see this working.

**Comment by donovanr** [comment]
same

**Comment by LifeWorks** [comment]
same

**Comment by GiorgioBalestrieri** [comment]
same

**Comment by GiorgioBalestrieri** [comment]
great to see this has been added to the Numba 0.40 milestone.
The more I use it, the more I realize not being able to rely on default values pushes me to write somewhat ugly code.
Not just this: it forces me to change my classes in ugly ways if I plan to decorate them with jitclass.
Thanks!

**Comment by GiorgioBalestrieri** [comment]
Hi @stuartarchibald, can I ask you the status on this? Is this available in [0.41.0dev0](https://github.com/numba/numba/releases/tag/0.40.0rc1)? Is there any chance you need some low level support on this? Thanks!

**Comment by stuartarchibald** [comment]
@GiorgioBalestrieri this will hopefully make it into `0.41.x`. As it is not implemented yet it won't be in dev builds. The 0.40.0 release ended up being large and very involved with complicated new features, which unfortunately meant that there simply wasn't sufficient time to work on this issue within that release cycle window.

You are of course more than welcome to go and work on this feature to get it done quicker, some effort has been put into https://github.com/numba/numba/pull/2894 which may be a good place to start? Pull requests etc are welcome.

**Comment by skirpichenko** [comment]
It looks like default values do not work at any jitclass method:
```
@numba.jitclass([])
class Test():
    def __init__(self):
        pass
    def Foo(self, param=1):
        print (param)

obj = Test()
obj.Foo()
```
fails with
```
LoweringError: invalid number of args: expected 2, got 1
```
would love to have it implemented.

**Comment by stuartarchibald** [comment]
This was fixed in https://github.com/numba/numba/pull/3852, closing. 0.44 has support for this.
