### ISSUE TITLE
Timestepping stencil only runs in serial 

### ISSUE THREAD

**Issue by jrt54** [numba/numba#2662]
I may be misunderstanding the combination of the parallel jit option with numba stencils, but so far I have not been able to parallelize any stencils successfully. I can run numba in parallel, though. My code returns the expected values of a finite difference time-stepping stencil for the isotropic model of seismic wave propagation. But it only runs in serial. Basically what I would like to calculate is: 

`next_array = 2*curr_array - prev_array + stencil(curr_array). `

At the very least, I'd like to parallelize the "stencil" operation. 

I'm running with the following versions  
Ubuntu 16.04 LTS
numba==0.36.0.dev0+431.gb1275ced8.dirty
llvmlite==0.21.0.dev0+22.g4c67d65

Here is the full program I'm running, which works (i.e. returns the right values), but will only perform in serial. The stencil I'm trying to parallelize is titled "laplace"

```
from numba import stencil, jit
from numba import njit, prange
import numba
import numpy as np
from matplotlib import pyplot

#setting constants
vel = 3000.0
f0 = 15
nt = 50
dt = .002
nx = 50
ny = 50
nz = 50
h = vel/(f0*5.0)
x_idx = nx//2
y_idx = ny//2
z_idx = nz//2
radius = 8
coeff = [-3.0548446, 1.777777, -3.1111111/10, 7.572087/100, -1.767676/100, 3.480962/1000, -5.180005/10000, 5.074287/(10*10*10*10*10), -2.42812/np.power(10, 6)]


#stencil runs in serial
@stencil(neighborhood = ((-radius, radius), (-radius, radius), (-radius, radius),), standard_indexing=("coeff",) )
#@jit(nopython=True, parallel=True)
@numba.njit(parallel=True)
def laplace(a, coeff):
        laplace = coeff[0]*a[0, 0, 0]*3
        for i in range(1, radius+1):
                laplace+= coeff[i]*((a[0, 0, -i] + a[0, 0, i]) + (a[0, -i, 0] + a[0, i, 0]) + (a[-i, 0, 0] + a[i, 0, 0]))
        return laplace

#source injection
def Ricker(t, f0):
        r  = (np.pi*f0 * (t-1./f0))
        return (1-2.*r**2)*np.exp(-r**2)

source = []
for i in range(nt):
        source.append(Ricker(dt*i, f0))

#setting up arrays
prev_timestep = np.zeros((nx+2*radius)*(ny+2*radius)*(nz+2*radius)).reshape((nx+2*radius, ny+2*radius, nz+2*radius))
curr_timestep = np.zeros((nx+2*radius)*(ny+2*radius)*(nz+2*radius)).reshape((nx+2*radius, ny+2*radius, nz+2*radius))
next_timestep = np.zeros((nx+2*radius)*(ny+2*radius)*(nz+2*radius)).reshape((nx+2*radius, ny+2*radius, nz+2*radius))
curr_timestep[x_idx+radius, y_idx+radius, z_idx+radius] += source[0]*(vel*dt)**2

#time_stepping scheme. each timestep should be calculated in parallel
def time_step(next_timestep, curr_timestep, prev_timestep, nt):
        for i in range(1, nt):
                next_timestep = 2*curr_timestep - prev_timestep + laplace(curr_timestep, coeff)*((dt*vel/h)**2)
                next_timestep[x_idx+radius, y_idx+radius, z_idx+radius] += source[i]*(vel*dt)**2
                prev_timestep = curr_timestep
                curr_timestep = next_timestep
                print(next_timestep[x_idx+radius, y_idx+radius, z_idx+radius])

        return next_timestep

#final result and plot
next_timestep = time_step(next_timestep, curr_timestep, prev_timestep, nt)

fig, ax = pyplot.subplots()
next_timestep = (next_timestep[:, :, z_idx + radius])
cax = ax.imshow(next_timestep, interpolation='nearest', cmap='hot')
ax.set_title('Heatmap of pressure')
# Add colorbar, make sure to specify tick locations to match desired ticklabels
min, max = np.amin(next_timestep), np.amax(next_timestep)
print ("min, max of pressure array are: %f, %f" %(min, max))
cbar = fig.colorbar(cax, ticks=[min,(max+min)/2.0, max])
cbar.ax.set_yticklabels(['%.2f' %min, '%.2f' %((max+min)/2.0) ,'%.2f' %max])
pyplot.savefig('run_pressure.png')

```

**Comment by thoth291** [comment]
Wow! 3D time stepping stencil!
Looks like what I've been trying to do on my side.
I wonder @ninegua, @DrTodd13 or @seibert is it possible to make this code work in parallel.
P.S. IMHO, examples like this are what missing in the original Numba.Stencil documentation...

**Comment by DrTodd13** [comment]
It looks like you have laplace with both @stencil and @njit.  The laplace function should have the @stencil but the @njit should be moved to the time_step function.

**Comment by jrt54** [comment]
So I've tried adding this line above time_step and received an error. I assumed parallelizing above "time_step" might cause the code to try to parallelize over time and space. For clarity, this is not my intent and would return the wrong result. I only want to parallelize over space. In other words, I want every line within "for i in range(1, nt)" to be completed before proceeding to the next line or exiting the loop. Maybe some kind of time-parallel behavior could be causing my error?

Anyway, I added this line above time_step and removed it from laplace:
 `@numba.njit(parallel=True)`

Here's the error code:

> /home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dataflow.py:379: RuntimeWarning: Python2 style print partially supported.  Please use Python3 style print.
>   "Python3 style print.", RuntimeWarning)
> Traceback (most recent call last):
>   File "stencil_serial_laplace.py", line 73, in <module>
>     next_timestep = time_step(next_timestep, curr_timestep, prev_timestep, nt)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 579, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 80, in compile
>     flags=flags, locals=self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 766, in compile_extra
>     return pipeline.compile_extra(func)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 362, in compile_extra
>     return self._compile_bytecode()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 725, in _compile_bytecode
>     return self._compile_core()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 712, in _compile_core
>     res = pm.run(self.status)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 248, in run
>     raise patched_exception
> numba.errors.LoweringError: Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 647, in stage_nopython_backend
>     self._backend(lowerfn, objectmode=False)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 602, in _backend
>     lowered = lowerfn()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 589, in backend_nopython_mode
>     self.flags)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 885, in native_lowering_stage
>     lower.lower()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 135, in lower
>     self.lower_normal_function(self.fndesc)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 176, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 201, in lower_function_body
>     self.lower_block(block)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
>     self.lower_inst(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 265, in new_error_context
>     six.reraise(type(newerr), newerr, sys.exc_info()[2])
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 259, in new_error_context
>     yield
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
>     self.lower_inst(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 365, in lower_inst
>     func(self, inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/npyufunc/parfor.py", line 67, in _lower_parfor_parallel
>     lowerer, parfor, typemap, typingctx, targetctx, flags, {})
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/npyufunc/parfor.py", line 602, in _create_gufunc_for_parfor_body
>     locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 780, in compile_ir
>     lifted_from=lifted_from)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 370, in compile_ir
>     return self._compile_ir()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 732, in _compile_ir
>     return self._compile_core()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 712, in _compile_core
>     res = pm.run(self.status)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 248, in run
>     raise patched_exception
> LoweringError: Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
>     self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 867, in type_inference_stage
>     infer.build_constraint()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 800, in build_constraint
>     self.constrain_statement(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 959, in constrain_statement
>     self.typeof_assign(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1021, in typeof_assign
>     self.typeof_global(inst, inst.target, value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1147, in typeof_global
>     literal_value=gvar.value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 866, in lock_type
>     tv.lock(tp, loc=loc, literal_value=literal_value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 72, in lock
>     assert not self.locked
> AssertionError
> 
> Failed at nopython (nopython frontend)
> 
> File "stencil_serial_laplace.py", line 63
> [1] During: lowering "[LoopNest(index_variable = $parfor_index_var.79, range = (8, last_ind.114, 1)), LoopNest(index_variable = $parfor_index_var.80, range = (8, last_ind.117, 1)), LoopNest(index_variable = $parfor_index_var.81, range = (8, last_ind.120, 1))]{165: <ir.Block at stencil_serial_laplace.py (32)>, 207: <ir.Block at stencil_serial_laplace.py (37)>, 335: <ir.Block at stencil_serial_laplace.py (38)>, 336: <ir.Block at stencil_serial_laplace.py (38)>, 337: <ir.Block at stencil_serial_laplace.py (63)>, 210: <ir.Block at stencil_serial_laplace.py (37)>, 187: <ir.Block at stencil_serial_laplace.py (36)>, 190: <ir.Block at stencil_serial_laplace.py (37)>}Var($parfor_index_tuple_var.123, stencil_serial_laplace.py (63))" at stencil_serial_laplace.py (63)
> 
> Failed at nopython (nopython mode backend)
> Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
>     self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 867, in type_inference_stage
>     infer.build_constraint()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 800, in build_constraint
>     self.constrain_statement(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 959, in constrain_statement
>     self.typeof_assign(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1021, in typeof_assign
>     self.typeof_global(inst, inst.target, value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1147, in typeof_global
>     literal_value=gvar.value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 866, in lock_type
>     tv.lock(tp, loc=loc, literal_value=literal_value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 72, in lock
>     assert not self.locked
> AssertionError
> 
> Failed at nopython (nopython frontend)
> 
> File "stencil_serial_laplace.py", line 63
> [1] During: lowering "[LoopNest(index_variable = $parfor_index_var.79, range = (8, last_ind.114, 1)), LoopNest(index_variable = $parfor_index_var.80, range = (8, last_ind.117, 1)), LoopNest(index_variable = $parfor_index_var.81, range = (8, last_ind.120, 1))]{165: <ir.Block at stencil_serial_laplace.py (32)>, 207: <ir.Block at stencil_serial_laplace.py (37)>, 335: <ir.Block at stencil_serial_laplace.py (38)>, 336: <ir.Block at stencil_serial_laplace.py (38)>, 337: <ir.Block at stencil_serial_laplace.py (63)>, 210: <ir.Block at stencil_serial_laplace.py (37)>, 187: <ir.Block at stencil_serial_laplace.py (36)>, 190: <ir.Block at stencil_serial_laplace.py (37)>}Var($parfor_index_tuple_var.123, stencil_serial_laplace.py (63))" at stencil_serial_laplace.py (63)


Its worth nothing that I was able to use this decorator with a "manual" laplace stencil of the same mathematical definition and achieve parallelization as well as the intended final result of my computation:
 `@numba.njit(parallel=True)`

**Comment by DrTodd13** [comment]
Okay.  I understand now.  Please make the body of the loop "for i in range(1, nt):" into a function and put @njit(parallel=True) on that function.

**Comment by jrt54** [comment]
Okay I created a function for a single timestep returning a total of 3 arrays full of values at the previous, current, and next time value. It works in serial with the expected result, but when I add the @numba.njit(parallel=True) decorator to the new  time_step function, I'm getting a similar error as before. 

Relevant piece of code:
```
@numba.njit(parallel=True)
def time_step(next_timestep, curr_timestep, prev_timestep, source):
	next_timestep = 2*curr_timestep - prev_timestep + laplace(curr_timestep, coeff)*((dt*vel/h)**2) 
	next_timestep[x_idx+radius, y_idx+radius, z_idx+radius] += source*(vel*dt)**2
	prev_timestep = curr_timestep
	curr_timestep = next_timestep
	return next_timestep, curr_timestep, prev_timestep

def all_time_step(next_timestep, curr_timestep, prev_timestep, nt):
	for i in range(1, nt): 
		next_timestep, curr_timestep, prev_timestep = time_step(next_timestep, curr_timestep, prev_timestep, source[i])
	return next_timestep


next_timestep = all_time_step(next_timestep, curr_timestep, prev_timestep, nt)
```

Error message: 

> 
> Traceback (most recent call last):
>   File "stencil_parallel_laplace.py", line 82, in <module>
>     next_timestep = all_time_step(next_timestep, curr_timestep, prev_timestep, nt)
>   File "stencil_parallel_laplace.py", line 78, in all_time_step
>     next_timestep, curr_timestep, prev_timestep = time_step(next_timestep, curr_timestep, prev_timestep, source[i])
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 579, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 80, in compile
>     flags=flags, locals=self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 766, in compile_extra
>     return pipeline.compile_extra(func)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 362, in compile_extra
>     return self._compile_bytecode()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 725, in _compile_bytecode
>     return self._compile_core()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 712, in _compile_core
>     res = pm.run(self.status)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 248, in run
>     raise patched_exception
> numba.errors.LoweringError: Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 647, in stage_nopython_backend
>     self._backend(lowerfn, objectmode=False)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 602, in _backend
>     lowered = lowerfn()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 589, in backend_nopython_mode
>     self.flags)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 885, in native_lowering_stage
>     lower.lower()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 135, in lower
>     self.lower_normal_function(self.fndesc)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 176, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 201, in lower_function_body
>     self.lower_block(block)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
>     self.lower_inst(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 265, in new_error_context
>     six.reraise(type(newerr), newerr, sys.exc_info()[2])
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 259, in new_error_context
>     yield
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
>     self.lower_inst(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 365, in lower_inst
>     func(self, inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/npyufunc/parfor.py", line 67, in _lower_parfor_parallel
>     lowerer, parfor, typemap, typingctx, targetctx, flags, {})
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/npyufunc/parfor.py", line 602, in _create_gufunc_for_parfor_body
>     locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 780, in compile_ir
>     lifted_from=lifted_from)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 370, in compile_ir
>     return self._compile_ir()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 732, in _compile_ir
>     return self._compile_core()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 712, in _compile_core
>     res = pm.run(self.status)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 248, in run
>     raise patched_exception
> LoweringError: Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
>     self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 867, in type_inference_stage
>     infer.build_constraint()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 800, in build_constraint
>     self.constrain_statement(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 959, in constrain_statement
>     self.typeof_assign(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1021, in typeof_assign
>     self.typeof_global(inst, inst.target, value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1147, in typeof_global
>     literal_value=gvar.value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 866, in lock_type
>     tv.lock(tp, loc=loc, literal_value=literal_value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 72, in lock
>     assert not self.locked
> AssertionError
> 
> Failed at nopython (nopython frontend)
> 
> File "stencil_parallel_laplace.py", line 65
> [1] During: lowering "[LoopNest(index_variable = $parfor_index_var.78, range = (8, last_ind.113, 1)), LoopNest(index_variable = $parfor_index_var.79, range = (8, last_ind.116, 1)), LoopNest(index_variable = $parfor_index_var.80, range = (8, last_ind.119, 1))]{1: <ir.Block at stencil_parallel_laplace.py (32)>, 43: <ir.Block at stencil_parallel_laplace.py (37)>, 171: <ir.Block at stencil_parallel_laplace.py (38)>, 172: <ir.Block at stencil_parallel_laplace.py (38)>, 173: <ir.Block at stencil_parallel_laplace.py (65)>, 46: <ir.Block at stencil_parallel_laplace.py (37)>, 23: <ir.Block at stencil_parallel_laplace.py (36)>, 26: <ir.Block at stencil_parallel_laplace.py (37)>}Var($parfor_index_tuple_var.122, stencil_parallel_laplace.py (65))" at stencil_parallel_laplace.py (65)
> 
> Failed at nopython (nopython mode backend)
> Caused By:
> Traceback (most recent call last):
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 240, in run
>     stage()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
>     self.locals)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 867, in type_inference_stage
>     infer.build_constraint()
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 800, in build_constraint
>     self.constrain_statement(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 959, in constrain_statement
>     self.typeof_assign(inst)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1021, in typeof_assign
>     self.typeof_global(inst, inst.target, value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 1147, in typeof_global
>     literal_value=gvar.value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 866, in lock_type
>     tv.lock(tp, loc=loc, literal_value=literal_value)
>   File "/home/jrt54/anaconda2/lib/python2.7/site-packages/numba/typeinfer.py", line 72, in lock
>     assert not self.locked
> AssertionError
> 
> Failed at nopython (nopython frontend)
> 
> File "stencil_parallel_laplace.py", line 65
> [1] During: lowering "[LoopNest(index_variable = $parfor_index_var.78, range = (8, last_ind.113, 1)), LoopNest(index_variable = $parfor_index_var.79, range = (8, last_ind.116, 1)), LoopNest(index_variable = $parfor_index_var.80, range = (8, last_ind.119, 1))]{1: <ir.Block at stencil_parallel_laplace.py (32)>, 43: <ir.Block at stencil_parallel_laplace.py (37)>, 171: <ir.Block at stencil_parallel_laplace.py (38)>, 172: <ir.Block at stencil_parallel_laplace.py (38)>, 173: <ir.Block at stencil_parallel_laplace.py (65)>, 46: <ir.Block at stencil_parallel_laplace.py (37)>, 23: <ir.Block at stencil_parallel_laplace.py (36)>, 26: <ir.Block at stencil_parallel_laplace.py (37)>}Var($parfor_index_tuple_var.122, stencil_parallel_laplace.py (65))" at stencil_parallel_laplace.py (65)
> 

For what it's worth, the above code works in parallel with the aforementioned njit parallel decorator when I replace this line: 

` next_timestep = 2*curr_timestep - prev_timestep + laplace(curr_timestep, coeff)*((dt*vel/h)**2) `

with this line: 

`next_timestep = 2*curr_timestep - prev_timestep `

So the error is probably from the "laplace" stencil itself.

**Comment by DrTodd13** [comment]
It looks like some typing issue.  I notice that coeff, dt, vel, and h are globals and so you won't know their type at the point that function is being compiled.  I suggest that you do not use global variables in either the stencil function or the one with njit.  Can you please try passing those variables in and see if that makes a difference?  If not, I'll try to take a look at this tomorrow in depth.  For that, if you could share the full code it would help.  thanks.

**Comment by jrt54** [comment]
Thank you! This now runs in parallel and returns the expected result. 

For what it's worth, the issue seemed to lie solely in the "coeff" array. It also works without passing dt, vel, and h.
