### ISSUE TITLE
CUDA Streams Not Bound by Default

### ISSUE THREAD

**Issue by njwhite** [numba/numba#2664]
It seems like constructing a device array with an explicit stream doesn't actually bind the array stream to that stream (e.g. the below). Is this expected
````python
from numba import cuda
stream = cuda.stream()
with stream.auto_synchronize():
    arr = cuda.device_array(
        (3, 3),
        dtype=np.float64,
        stream=stream)
    assert arr.bind(stream).stream == stream
    assert arr.stream == stream # throws!
````

**Comment by sklam** [comment]
Good catch.  I think that it is a mistake that we didn't bind the stream to the array.
