### ISSUE TITLE
module 'cffi' has no attribute 'FFI'

### ISSUE THREAD

**Issue by GeekMe93** [numba/numba#2666]
I have installed `numba` via Anaconda. And I just copy and paste example code on numba home page. But I got an error:  module 'cffi' has no attribute 'FFI'

![image](https://user-images.githubusercontent.com/15790176/34440770-763388d2-ecf2-11e7-87a1-831f5b22f73b.png)

![image](https://user-images.githubusercontent.com/15790176/34440784-8913fb12-ecf2-11e7-9a21-791fcaadac20.png)

Anybody has any idea  what's wrong here? Thanks!

**Comment by seibert** [comment]
What does `conda list cffi` show?

**Comment by corona10** [comment]
There was no issue when the cffi is installed.

My environment
```
OS: MacOS High Sierra
Python: CPython 3.6.0
```

**Comment by stuartarchibald** [comment]
Thanks for reporting back. Glad it is working for you now. Closing.
