### ISSUE TITLE
Can't get numba work with CUDA

### ISSUE THREAD

**Issue by shobhitvnagar** [numba/numba#2688]
trying to run numba with cuda support
I get the following error
-----------------------------------------------------------------------------------
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import cuda
>>> print(cuda.gpus)

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 220, in initialize
    self.cuInit(0)
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 259, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 296, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuInit results in CUDA_ERROR_UNKNOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 43, in __str__
    return ', '.join([str(d) for d in self.lst])
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 307, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 244, in __getattr__
    self.initialize()
  File "/opt/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 223, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN:
---------------------------------------------------------------------------------------------------

Tried reinstalling numba and cudatoolkit from conda again again still problem persist?
Please help

**Comment by sklam** [comment]
It is likely that you need to update the CUDA driver on your system.  Since the CUDA driver is not redistributable as a conda package.  You need to get it from your OS provided package manager or from Nvidia directly.

**Comment by shobhitvnagar** [comment]
should i install cuda toolkit using conda or externally?

**Comment by shobhitvnagar** [comment]
can you please tell how to integerate both cuda drivers and anaconda provided cuda toolkit I am stuck

**Comment by sklam** [comment]
@shobhitvnagar , sorry for the late reply.  For the CUDA driver, you can find instructions for Linux at <http://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#linux>.   

Here's a quick summary on what's the cuda packages from different sources:

* The "CUDA" package your OS package manager contains all the contents in the "CUDA Toolkit", including the driver, the compiler, and the libraries.
* `cudatoolkit` package in conda does not contain the driver nor the compiler.  It contains redistributable libraries i.e. cuBLAS, cuRAND, cuFFT...   It will not interfere with the OS/official CUDA package.  It does depends on the OS/official CUDA driver.

**Comment by dantistus** [comment]
@sklam I have just updated CUDA software and GPU driver from Nvidia website and I get the same error:

```
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN:
```

**Comment by sklam** [comment]
Can you paste the output from `nvidia-smi`?

**Comment by quasiben** [comment]
Has this issue gone stale ?

**Comment by seibert** [comment]
Yes, I think so.

**Comment by seibert** [comment]
Closing for now.  If anyone runs into a CUDA_ERROR_UNKNOWN issue (which can have many different causes), please open a new issue for your specific situation.

**Comment by paulcheck** [comment]
I'm having this issue and posted on a different board.  I do have cuda 10 installed on my debian system, and numba -s gives the same error as above: 

"__CUDA Information__
Error: CUDA device intialisation problem. Message:Error at driver init: 
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>"

**Comment by seibert** [comment]
Which version of Numba are you using (0.44 had some updates to CUDA detection), and are there other CUDA applications that work on your system?

**Comment by seibert** [comment]
Also, feel free to open a new issue, since your issue might not be related to this one.

**Comment by paulcheck** [comment]
Well, I fixed the problem.  My conda environment had cuda v 10.1, bit my underlying Debian system only v 9.2.  After updating the underlying system to v 10.1 (via the experimental branch of Debian), everything is working.  

Regards, Paul
