### ISSUE TITLE
Parfors `NUMBA_DEBUG_ARRAY_OPT_STATS` broken

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2700]
Ran into this when running some code with the debugging env var `NUMBA_DEBUG_ARRAY_OPT_STATS=1` set (sets `ParforPass.options.fusion`). The problem is that `self` is used outside of a class here: https://github.com/numba/numba/blob/master/numba/parfor.py#L1632 and therefore the debug print fails. Simply passing the `options.fusion` state through to this function fixes it, so I think it is just an oversight that occurred during some refactoring. Perhaps a fix could go in as part of the refactor in https://github.com/numba/numba/pull/2674 ?

Ping @ehsantn @DrTodd13

**Comment by ehsantn** [comment]
Yes, this is just a silly mistake. Thanks for tracking it down and fixing it.
