### ISSUE TITLE
parallel=True incompatible with caching and AOT compilation

### ISSUE THREAD

**Issue by seibert** [numba/numba#2712]
As part of the gufunc rewrite, we should investigate how to allow ParallelAccelerator functions to be cached.  (This will likely also solve the problems with ahead of time compilation.)

**Comment by DrTodd13** [comment]
@sklam We didn't do this as part of gufunc rewrite but isn't caching working with parellel=True now?  Can close this?

**Comment by esc** [comment]
Yes, caching does seem to work:

```
 💣 zsh» ls __pycache__
issue2712.prange_test-5.py38.1.nbc  issue2712.prange_test-5.py38.nbi
```

I'll close this now, as I believe it has been resolved. If this is not the case, please feel free to re-open the issue. Thanks!
