### ISSUE TITLE
Adjusting threadpool size at runtime

### ISSUE THREAD

**Issue by sklam** [numba/numba#2713]
Users have requested the ability to adjust threadpool size at runtime.  Currently, it is set using the env-var NUMBA_NUM_THREADS, which is loaded once at import time.

**Comment by jzwinck** [comment]
I agree it would be good to allow control per call; it's also worth noting that recently (at least in Numba 0.34), the thread pool is initialized as soon as you import a module that uses numba.vectorize(target='parallel') - even if the decorated function is never called.  That's not good--the threadpool threads should be created only if they are needed.

**Comment by asmeurer** [comment]
I think a straightforward fix for this would be to allow masking out threads in get_thread_count(), that is, we still create a maximum number of threads NUMBA_NUM_THREADS, but allow the user to set fewer than that at runtime.  I tested and changing the value returned by `get_thread_count` does result in fewer than the total thread pool being utilized. Adding new threads to the thread pool beyond NUMBA_NUM_THREADS seems to be a much harder problem. 

One issue with this is that a lot of places compile in the number of threads into the functions, for instance, in parfor.py, num_threads is inlined as a constant here: https://github.com/numba/numba/blob/60d2bddd0a9ddf84cf900a70e4b7e17bcbe5dc87/numba/npyufunc/parfor.py#L139, and code is generated based on the number of threads here https://github.com/numba/numba/blob/60d2bddd0a9ddf84cf900a70e4b7e17bcbe5dc87/numba/npyufunc/parfor.py#L218. There may be other places as well.

I don't fully understand how the code generated in the above places works. Will it be hard to generate code that works with a dynamic number of threads, which is accessed when the function is called? Or would it be better to force parallel functions to recompile whenever the number of threads is changed.

**Comment by seibert** [comment]
@DrTodd13, @ehsantn: Thoughts on how we would make parfors handle having the number of threads set when the function is run, rather than when it was compiled?

**Comment by asmeurer** [comment]
@jrbourbeau and I looked through the parfor code today. We didn't yet get to the `call_parallel_gufunc` code yet, but for the reduction, for N max threads and n actual threads, it seems like it should work to read the number n from within the jitted function, and just mask out the N - n unused threads with a branch.

**Comment by asmeurer** [comment]
I just ran through the uses in `call_parallel_gufunc` and it seems like it should work there as well. The (currently) constant `sched` will need to be recomputed at runtime, and the places that call `get_thread_count()` and inline it as a constant will need to be modified to look up the global variable. 

What's the proper way to lookup a global value from the IR?

**Comment by pearu** [comment]
For TBB threading layer, using [tbb::task_arena](https://software.intel.com/en-us/node/506359) in `parallel_for` function (of `tbbpool.c`) allows running subthreads with the limited number of threads.

In the form of an example, here's a proposal for the numba UI:
```
os.environ['NUMBA_NUM_THREADS'] = '16'
os.environ['NUMBA_THREADING_LAYER'] = 'tbb'

@njit(parallel=True)
def sum_cols(A):
    s = 0
    for i in prange(A.shape[0]):
        s = s + A[i]
    return s

@njit(parallel=True)
def sum_rows(A):
    s = 0
    for i in prange(A.shape[0], num_threads=2):  # NEW UI
        s = s + sum_cols(A[i])
    return s

N = 8
x = np.ones((N, N), dtype=np.int32)
with numba_num_threads(8):  # NEW UI
    s = sum_rows(x)
assert s == 64
```
where `prange` in `sum_rows` would use 8 threads while `prange` in `sum_cols` (as well as all other functions called within the for-loop of `sum_rows`) would use 2 threads.

**Comment by asmeurer** [comment]
WIP PR here https://github.com/numba/numba/pull/4615

**Comment by asmeurer** [comment]
We discussed this at the numba developer meeting today. They should be posting a summary of the discussion on the pull request. 

The chief worry is how to do this safely, and in particular how we can restrict the problem to avoid potential unsafe things. For your use-cases, would it be sufficient if the set_num_threads function had the following limitations?

1. It can only be called from outside a jitted function
2. It cannot be called if any parallel functions are currently executing.

**Comment by DrTodd13** [comment]
I think a requirement should be that this is allowed in jitted functions but should also work when set before the jitted function is called.  We were talking about this function to set this value as if the value were a global but does it need to be that way?  Why can't the value be thread-local?  Then you don't have the issue of multiple threads stomping on each other and there's no need for synchronization.  Is there a use case for controlling the number of threads that the some other thread is creating through parfors?  Seems kind of strange so I wouldn't mind excluding that use case and going with this thread local variable.

**Comment by asmeurer** [comment]
I'm not sure about that. The end goal here is to allow the end-user to have better control of the parallelism utilization with numba + other things that aren't numba by restricting the total number of threads that numba will use. So as long as some recursive parfors aren't going to just use up the masked out threads, it should be fine.

**Comment by lmcinnes** [comment]
Please count me in for this -- this is definitely a feature I would like to have available, and the API @pearu presented is pretty much exactly what I would like to see from a users perspective. Right now I am playing with parallel support in UMAP, both in the optimization step and in the nearest neighbor search. This is mostly done and working well, but to fit with the API and user expectations from sklearn it would be very helpful to have exactly this sort of runtime control of threads.

**Comment by asmeurer** [comment]
To anyone interested in this feature, the pull request https://github.com/numba/numba/pull/4615 is now ready for review if you want to compile it and test it. The basic usage is described in the [documentation which has been added in that PR](https://github.com/numba/numba/pull/4615/files#diff-d394697b7a328d9f69a0c55540a581b4) (comments on the user documentation are welcome as well). Please report back if you do test it, even if everything works, as that's a useful data point to have.
