### ISSUE TITLE
setup_requires + distutils_extension 

### ISSUE THREAD

**Issue by NathanDeMaria** [numba/numba#2718]
I have the following setup to attempt to use an AOT-compiled kernel in a python package, where the package doesn't require `numba` in the environment.

Directory structure
```
setup.py
simple_function.py
package_name/
    __init__.py
```

`setup.py`
```python
from setuptools import setup, find_packages

# Lazy trick to make sure numba gets imported _after_ it's installed from setup_requires
class LazyExtensions(list):
    def __init__(self):
        super(LazyExtensions, self).__init__()
        self.__extensions = None

    @property
    def _extensions(self):
        if self.__extensions is None:
            from simple_function import cc
            self.__extensions = [cc.distutils_extension()]
        return self.__extensions

    def __len__(self):
        return len(self._extensions)

    def __iter__(self):
        yield from self._extensions


setup(
    name='package-name',
    version='0.0.1',
    packages=find_packages(),
    setup_requires=['numpy', 'numba'],
    ext_package='package_name',
    ext_modules=LazyExtensions(),
)
```

`simple_function.py`
```python
from numba.pycc import CC


cc = CC('compiled')


@cc.export('add', 'f8(f8, f8)')
def add(x, y):
    return x + y
```

Installing this in an empty conda environment: 

```bash
conda create -n test_env python pip
conda activate test_env

pip install -e .
# Correctly creates package_name/compiled.<env>.so, but:

python -c 'from package_name.compiled import add'
```

Results in the following error:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(<my path>/package_name/compiled.cpython-36m-darwin.so, 2): Symbol not found: _nrt_atomic_add
  Referenced from: <my path>/package_name/compiled.cpython-36m-darwin.so
  Expected in: flat namespace
 in <my path>/package_name/compiled.cpython-36m-darwin.so
```

I'm not sure if the issue is with my "lazy eval" trick, or using `numba` in `setup_requires` in general. If I assume `numba` is already installed and import `cc` immediately, everything works as expected. However, I'd like to avoid making that assumption.

In case it's helpful,

```bash
conda -V
> conda 4.4.8
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this an issue with compilation opposed to anything particular about the set up.

**Comment by silgon** [comment]
@NathanDeMaria  I'm just curious, did you solve your problem? I'm using the `setup.py` as in the [tutorial](https://numba.readthedocs.io/en/stable/user/pycc.html). However, it's silly, because it demands to have numba already installed. Your trick `LazyExtensions` seems nice, but not sure if you were able to make it work. Thanks in advance.

**Comment by NathanDeMaria** [comment]
No, I ended up giving up and just raising an error that says "must install numba before installing this package"

I _think_ the suggestion above is right, and that the problem has something to do with where/how `numba` is installed as a result of `setup_requires` differing from if you just install it with `pip install numba`

**Comment by silgon** [comment]
Yeah, seems about right. However, I think that's one of the things that'd be cool to have in the tutorial; on how to create a proper package from `numba` with for example the `setup_requires` documented. Not sure myself how to do it though :disappointed: .

**Comment by Stoops-ML** [comment]
In the pyproject.toml file you can include numba in `requires` of `build-system`:
```
[build-system]
requires = ["setuptools>=42.0", "wheel", "numba>=0.55"]
build-backend = "setuptools.build_meta"
```

That way numba will be installed before your package will be installed allowing for AOT compilation.
