### ISSUE TITLE
enhance variable scoping to allow refining types in branches

### ISSUE THREAD

**Issue by sklam** [numba/numba#2719]
This relates to the second issue in <https://github.com/numba/numba/pull/2672#issuecomment-363131354>.

The current variable scoping rules will only allow new variable definition on the ["backbone"](https://github.com/numba/numba/blob/d53fb10511f5aa72c2e449d003a8de9ecefa2bf9/numba/controlflow.py#L164-L170):

https://github.com/numba/numba/blob/d53fb10511f5aa72c2e449d003a8de9ecefa2bf9/numba/controlflow.py#L164-L170

Variables defined outside will always use the variable defined in the closest dominating block.  This makes certain variable type refinement code fail unexpectedly:

```python
out = <..define to be any layout .>
 if out.flags.c_contiguous:
        out = np.ascontiguousarray(out)   
       # out is still any layout despite the previous conversion
```

**Comment by sklam** [comment]
I starting to work on a fix to this problem.  

The idea is:

* all assignment creates a new definition
* the last assignment for a var in the basicblock will carry over to the successors.
* two definitions of the same var (same name) will merge when the basicblocks merge.

**Comment by stuartarchibald** [comment]
@sklam can this be closed?

**Comment by sklam** [comment]
yes
