### ISSUE TITLE
Support ndarray.fill under parfors

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2742]
`ndarray.fill` has parallel semantics and should be supported in ParallelAccelerator

**Comment by EPronovost** [comment]
Is this issue still open?  If so what would it take to get started?

**Comment by stuartarchibald** [comment]
@EPronovost I believe so. I think the first step would be adding an array analysis routine `_analyze_op_call_numpy_fill` to `numba.array_analysis.ArrayAnalysis`. As a warning, this code path is in general very involved.

**Comment by DrTodd13** [comment]
@EPronovost @stuartarchibald This is probably not a good first issue.  I also don't believe it is an array analysis issue since it doesn't create or change the size of an array.  I am looking at it and it requires changes to parfor/_convert_numpy.

**Comment by stuartarchibald** [comment]
Indeed, this is not a first issue :)

@DrTodd13, I see, I guess as there's no shape change that part can be skipped.

**Comment by stuartarchibald** [comment]
Also, @EPronovost if you are looking for something more involved to do with Numba then please ping me on https://gitter.im/numba/numba-dev and we can discuss if you like.

Parfor from ParallelAccelerator (the technology behind `parallel=True`) is really challenging on a number of fronts and historically it takes quite some time to get to a point where it can be debugged and developed. I wouldn't want to discourage looking at it, but it's probably better to try a few other things first.
