### ISSUE TITLE
JIT results differs from AOT precompiled module

### ISSUE THREAD

**Issue by epifanio** [numba/numba#2755]
I'm trying to have a function pre-compiled `AOT` the code is:

* `preconp.py` : 

```python
from numba import jit
from numba.pycc import CC
import numpy as np

cc = CC('nbspatial')


@cc.export('s2r',  'f8[:,:](f8[:,:])')
@jit(nopython=True)
def s2r(l):
    lx = l.shape[0]
    sesp = np.zeros((lx, 2))
    for i in np.arange(lx):
        latdec = l[i,0]+(l[i,1]/60)+l[i,2]/3600
        latrad = (latdec * np.pi ) / 180.
        londec = l[i,3]+(l[i,4]/60)+l[i,5]/3600
        lonrad = (londec * np.pi ) / 180.
        sesp[i,:] = [latrad,lonrad]
    return sesp


if __name__ == "__main__":
    cc.compile()
```

I compile it with:

```bash
python3.6 precomp.py
```

but testing it with:

```python
import nbspatial
import numpy as np

l=np.array([[60, 25, 30, 15, 23, 43], [40, 25, 30, 15, 23, 43]])

nbspatial.s2r(l)

array([[5.e-324, 0.e+000],
       [5.e-324, 0.e+000]])
```

The same function, works fine if not precompiled:

```python
import numpy as np
from numba import jit

@jit(nopython=True)
def s2r(l):
    lx = l.shape[0]
    sesp = np.zeros((lx, 2))
    for i in np.arange(lx):
        latdec = l[i,0]+(l[i,1]/60)+l[i,2]/3600
        latrad = (latdec * np.pi ) / 180.
        londec = l[i,3]+(l[i,4]/60)+l[i,5]/3600
        lonrad = (londec * np.pi ) / 180.
        sesp[i,:] = [latrad,lonrad]
    return sesp

l=np.array([[60, 25, 30, 15, 23, 43], [40, 25, 30, 15, 23, 43]])
s2r(l)

array([[1.0546152 , 0.26869829],
       [0.70554935, 0.26869829]])
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm fairly sure this is because you have declared an AOT function to take a `f8` array and then pass it an integer one. If you do:

```python
import nbspatial
import numpy as np
l=np.array([[60, 25, 30, 15, 23, 43], [40, 25, 30, 15, 23, 43]], dtype=np.float64)
                                                                 #^--- note the dtype
print(nbspatial.s2r(l))
```
you get:
```
[[ 1.0546152   0.26869829]
 [ 0.70554935  0.26869829]]
```
which seems to be the same as running the original function in the interpreter?

**Comment by epifanio** [comment]
@stuartarchibald ,Thank you so much for this reply! Yes, that's the expected result.

**Comment by stuartarchibald** [comment]
Great to hear that. Thanks for confirming. Closing.

**Comment by dhirschfeld** [comment]
Shouldn't the AOT compiled function throw an error if the argument types don't match the signature? Even better would be if it just fell back to the jit decorator, compiling a function with the appropriate argument types on the fly if not of the AOT compiled exports match

Having the AOT compiled function accept incorrect arguments and then silently return the wrong result seems like a bug to me?

**Comment by seibert** [comment]
Yes, silent failure on this should be considered a bug.

**Comment by stuartarchibald** [comment]
Thanks for the feedback. When reading this I was in two minds about whether the function should raise given a user has declared the type and the contract for AOT compilation is more like that of the compilation of statically typed code. What has swayed me is that a user could feasibly want to use AOT to remove a dependency on Numba for a shipped package and it would be most inconvenient to force the user to have to write guard code to ensure type validity at the call site to guarantee numerical correctness. I've opened #2757 to track.

As to dynamically falling back to compiling for missing signatures, whilst I imagine it is possible it would mean having an optional dependency on the Numba machinery at runtime (the significance of the difference between AOT and `cache=True` becomes smaller?) and having to include some Numba-compiler-pipline-useable representation of the original function in the compiled module. If this is desirable please feel free to open a ticket to discuss.

Reclosing this in favour of #2757.
