### ISSUE TITLE
Segfault when using jitted function

### ISSUE THREAD

**Issue by serge-sans-paille** [numba/numba#276]
Hi there,

when turning the function from:

https://github.com/numfocus/python-benchmarks/blob/master/rosen_der/rosen_der_python.py

into a jitted function using:

https://github.com/numfocus/python-benchmarks/blob/master/rosen_der/rosen_der_numba.py

The compilation works nice but using the resulting function yields a segfault, which prevents the inclusion of the test case into https://github.com/numfocus/python-benchmarks

Once this is fix, can you emit a PR against python-benchmarks?

thxs

**Comment by pitrou** [comment]
This works fine these days.
