### ISSUE TITLE
0.37 release missing on Pypi

### ISSUE THREAD

**Issue by leezu** [numba/numba#2760]
Is there any reason for version 0.37 not being published on Pypi yet (even though it was already released a few days ago)?

**Comment by mbargull** [comment]
https://gitter.im/numba/numba-dev?at=5a87058fd786ce546e70ac67:
> @seibert
going to delay announcing the release until Monday. Wheel building is still manual, and Siu's day is going to be occupied with another task

**Comment by seibert** [comment]
Yeah, we'll be posting everything to PyPI on Monday and doing the release announcement.  It just happened that the conda packages finished before we were ready to do the rest.
