### ISSUE TITLE
`mask_var` not defined in _find_mask of numba/parfor.py

### ISSUE THREAD

**Issue by hugobordigoni** [numba/numba#2772]
Hi, I'm really new to numba so I hope it's the good place to post this issue.

Since release 0.37.rc1, this minimal example code raises the exception `UnboundLocalError: local variable 'mask_var' referenced before assignment`
```
import numba
import numpy as np
@numba.njit(parallel=True)
def test():
    n = 20
    A = np.ones((n, n))
    b = np.arange(n)
    np.sum(A[:, b])
test()
```

It worked well in release 0.37.0dev1 and before. I tested it with numpy versions 1.13.3 and 1.14.1.

I think, in previous releases, there was a `mask_var = None` defined outside but accessible to _find_mask function.

If it's a wanted behaviour, sorry for the trouble, I'll adapt my code.

**Comment by stuartarchibald** [comment]
Thanks for the report, I think this is a bug.

I think I would expect the `A[:, b]` to fail in `_find_mask` as neither argument is a boolean array or an integer constant type.

**Comment by DrTodd13** [comment]
I have an attempted fix for this in vectorization PR.

**Comment by stuartarchibald** [comment]
Body of the test is here https://github.com/numba/numba/pull/2727/files#diff-44914098195178c859436d0f2377912bR621 and now passing. Thanks @DrTodd13. Closing this issue.
