### ISSUE TITLE
`side` kwarg for numpy.searchsorted

### ISSUE THREAD

**Issue by seibert** [numba/numba#2775]
Currently, `searchsorted()` in nopython mode only supports the default `side="left"` behavior, but it would be useful to also be able to set `side="right"`.

**Comment by hameerabbasi** [comment]
It would be nice to have this since I might need it down the line in pydata/sparse. If you point me to the code I might be able to take a look.

**Comment by hameerabbasi** [comment]
I found the code, I'll maybe send a PR soon, but first, a question: I'm assuming if I do the exception inside the scalar version, it'll be very slow. I guess it would be best to define Two separate functions for the different side variations and dispatch to those?

How would I do this? A closure?
