### ISSUE TITLE
Support mergesort in `np.sort()` / `np.argsort()`

### ISSUE THREAD

**Issue by seibert** [numba/numba#2776]
Right now the only `np.sort` implementation supported in Numba is quicksort, but quicksort is not stable.  Adding support for `kind="mergesort"` would offer a stable sort.

**Comment by seibert** [comment]
Can base this on the structure of the quicksort implementation here:

https://github.com/numba/numba/blob/master/numba/targets/quicksort.py

And here is NumPy's mergesort implementation in C:

https://github.com/numpy/numpy/blob/master/numpy/core/src/npysort/mergesort.c.src

**Comment by mbargull** [comment]
Not sure if very relevant, but for reference, previous mergesort experiments have been done a while back in https://github.com/numba/numba/issues/1383.

**Comment by stuartarchibald** [comment]
Closed by https://github.com/numba/numba/pull/2822. Thanks.

**Comment by SumNeuron** [comment]
I just tried `np.sort(array)` in a `njit` function and got 

```
Invalid use of Function(<function sort at 0x7fb83c06d400>) with argument(s) of type(s): (array(int64, 2d, C))
```
so maybe not fixed? @stuartarchibald (using latest version)

**Comment by esc** [comment]
@SumNeuron I think it has something to do with the dimensionality of the array:

The following works:

```
from numba import njit
import numpy as np


@njit
def foo():
    z = np.zeros(10)
    print(z)
    np.sort(z)


foo()
```

But the following doesn't:

```
from numba import njit
import numpy as np


@njit
def foo():
    z = np.zeros((10, 10))
    print(z)
    np.sort(z)


foo()
```

**Comment by SumNeuron** [comment]
@esc cool so can we open the issue and get np.sort to work?

**Comment by esc** [comment]
@SumNeuron I had a look at the code and couldn't find an obvious fix yet, but it is certainly worth opening an issue about not being able to sort array of ndim >=2

**Comment by esc** [comment]
Maybe related: https://github.com/numba/numba/issues/4248
