### ISSUE TITLE
Errors on python-2.7 FreeBSD Port

### ISSUE THREAD

**Issue by yurivict** [numba/numba#2785]
Seeing this in the FreeBSD port:
```
/usr/local/bin/python2.7 -O /tmp/tmptMgMyd.py
  File "/usr/local/lib/python2.7/site-packages/numba/tests/annotation_usecases.py", line 12
    def __init__(self, v: int):
                        ^
SyntaxError: invalid syntax
```

**Comment by stuartarchibald** [comment]
Thanks for the report. As noted in the source file https://github.com/numba/numba/blob/master/numba/tests/annotation_usecases.py#L1-L4:
```
Usecases with Python 3 function annotations.  This is a separate module
in order to avoid syntax errors with Python 2.
```
it is not expected to work under Python 2.7 and that error message is typically just ignored. Is this preventing the FreeBSD port from working?

**Comment by seibert** [comment]
Is the FreeBSD port trying to run all the tests?  Numba's built-in test runner specifically skips modules with syntax errors to ensure this test module doesn't affect Python 2.

**Comment by stuartarchibald** [comment]
Relabelled to note FreeBSD.

**Comment by yurivict** [comment]
The FreeBSD port just uses distutils like with all other python ports.

**Comment by seibert** [comment]
Is there a place you could post the full log of building the port?  I don't understand why python is executing this temp file from the fragment above.  `python setup.py install` works on all the other platforms we have tried.

**Comment by yurivict** [comment]
The central package build has this message: http://package21.nyi.freebsd.org/data/111amd64-default-qat/463771/logs/py27-numba-0.37.0.log

**Comment by seibert** [comment]
OK, so it is in the byte compiling stage of installation.  I remember this being a problem a long time ago, but I'm not sure why it doesn't happen now.

**Comment by stuartarchibald** [comment]
All the conda build recipes call this https://github.com/numba/numba/blob/master/buildscripts/remove_unwanted_files.py e.g. https://github.com/numba/numba/blob/master/buildscripts/condarecipe.local/build.sh#L3, which strips the source to suit the python version. I expect any other build system may have to do the same.

**Comment by mbargull** [comment]
Is it feasible to move the testing code outside of the package at some point? That tends to always be the cleanest and most hassle-free solution in my experience.

**Comment by stuartarchibald** [comment]
[Python 2.7 reached EOL on January 1st, 2020](https://github.com/python/devguide/pull/344) and [Numba 0.47 was the last release to support Python 2.7](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/g6wF8D-jV_o). Closing this issue as it is Python 2.7 specific, if this problem is reproducible on Python 3 with Numba >= 0.48 then please reopen it. Many thanks!
