### ISSUE TITLE
Issue with np.concatenate

### ISSUE THREAD

**Issue by vlavorini** [numba/numba#2787]
Hello,

I'm working with Python 3.6, Numpy 1.14.1 and Numba 0.37.0

I have to tile up a 2-D array, and since  the Numpy concatenate function is supported by Numba, I'm trying to use it. But I'm not able to make it work.

Here is an example:

    pts=np.random.randn(1000, 2)
    @jit(nopython=True)
    def myf(points,  n_begin, n_end):
        expd=np.expand_dims(points,2)
        tiled=np.concatenate([expd for i in range(n_end-n_begin)], axis=2)

        return tiled

    myf(pts, 1, 3)

Here the error I get:

    TypingError: Failed at nopython (nopython frontend)
    Invalid usage of Function(<built-in function concatenate>) with parameters (list(array(float64, 3d, A)), axis=int64)
     * parameterized
    In definition 0:
        TypeError: np.concatenate(): expecting a non-empty tuple of arrays, got list(array(float64, 3d, A))
        raised from /usr/local/lib/python3.6/site-packages/numba/typing/npydecl.py:789
    [1] During: resolving callee type: Function(<built-in function concatenate>)
    [2] During: typing of call at <ipython-input-8-b567293363b0> (8)

Can you tell me where I'm doing wrong?

Thank you!

P.S.
this is the workaround I am using while understanding where I'm wrong

    pts=np.random.randn(1000, 2)
    @jit(nopython=True)
    def myf(points,  n_begin, n_end):
        tiled = np.zeros((points.shape[0], points.shape[1], n_end-n_begin))
        for dim in range(n_end-n_begin):
            tiled[:,:,dim]=points

        return tiled

    myf(pts, 1, 3)

**Comment by stuartarchibald** [comment]
Thanks for the report. There is an issue with the documentation, `np.concatenate` is supported but only for arguments passed in a tuple. The good news is that I'd guess that the workaround is likely to be quicker and it will work in Numba.

**Comment by hameerabbasi** [comment]
This would be a nice-to-have for implementing Radix sort.

**Comment by stuartarchibald** [comment]
Good first issue task is to update the documentation on this line to note that only tuple arguments are supported:
https://github.com/numba/numba/blame/b8cb1a8515310054062cdb5d39f110d386eed817/docs/source/reference/numpysupported.rst#L439

**Comment by lucasjinreal** [comment]
@stuartarchibald  what if functions only have list? Looks like list convert to tuple can not be traced.
