### ISSUE TITLE
Improve support on debugging Numba

### ISSUE THREAD

**Issue by mrocklin** [numba/numba#2788]
I've been pleasantly surprised in recent conversations about how open people are today to have large parts of the Scientific Python stack have hard dependencies on Numba.  The introduction of pip wheels seems to have made a large impact.  

The most common concern I hear now is that it is difficult to diagnose issues when Numba itself does not perform well.  I suspect that this is due both to a lack of familiarity with LLVM, and with lack of understanding about how to get information out of Numba.  

Are there ways that we can improve this?  It looks like the standard documentation for this is here: http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html .  Are there things to do to improve that?  Is there tooling that can be built around this issue?  Improved error messages.

I apologize for the poorly-specified issue.  I mostly wanted to report my recent experience, and try to elevate the priority of "debugging numba internals" as a core issue to community adoption.

**Comment by mrocklin** [comment]
This comment is indicative of feedback that I've heard: https://github.com/pydata/sparse/issues/126#issuecomment-370251310

**Comment by stuartarchibald** [comment]
@mrocklin Thanks for the ticket and comments. This is something that has been part of a recent and ongoing discussion for the core developers https://github.com/numba/numba/wiki/Minutes_2018_02_15 `Section 4. Feature Discussion:: Community`.

Making the outward facing part of Numba be more user orientated is something that is hopefully going to take shape over the next few months. Numba contains a huge amount of engineering effort to make good performance possible often from a simple decorator. However, by the nature of the evolution of the project a lot of the debugging information for the engineers working on Numba has been left exposed and readily appears in front of the user. We (Numba core devs) appreciate that the current feedback/reporting of problems is not always particularly easy to interpret and as a result, as Numba heads towards a 1.0, we want to start adjusting the information that is fed back to the user.

Changes that are proposed include:
 * New user facing documentation/web pages, to include:
     * A one page guide to Numba.
     * Numba decorators+flags explained.
     * "Cool stuff"/new features page
     * Explain our DSO infrastructure especially with respect to LLVM (there are a lot of questions about this).
     * "how @jit works" page, high level with pictures etc
     * How to make Numba perform well and a quick guide to achieving good performance.
 * An exceptions catch-all and backtrace hiding/rewriting facility to make exceptions more user friendly (and enabled by default, devs will want to turn this off!). The rewrite facility to include:
   * Provision of better and more user friendly error messages.
   * More effort to find the offending line number(s).
   * Printing the offending line (helps in Jupyter/ipython).
   * Possibly raising exception classes that are user orientated and are not named after language from compiler design.
    * New documentation pages with explanations and examples of common problems that can be inserted into Exception messages as links.
    * Debug hints if applicable (common issues, like use of unsupported types, non-homogeneous lists etc).
    * An Exception class for when there is likely a problem with Numba internals with instructions for users on how to report it.
  * Bug report template
  * Updates to the Numba annotation tool
  * Ensure that the feature support documentation is accurate.

Then from a developer side we are aware that we need to:
 * Write documentation on how to extend Numba and integrate it with existing code bases.
 * Write documentation on how to write new features in Numba without essentially having to build up LLVM IR using llvmlite builder classes (Using `@overload` and `@intrinsic`).
 * Go through the existing documentation and ensure that the user documentation is accurate and that anything that is a Numba implementation/technical detail goes into the developer side documentation.

Thoughts and ideas are welcomed.

**Comment by hameerabbasi** [comment]
The debugging page is a big help. I think the following two things would make a big difference:

- Exact line numbers in the stack trace where compilation failed.
- Optionally turn on warnings when entering object mode via some sort of API.

Optionally, generating HTML annotations like Cython would be appreciated, stating where something entered object mode and why.

**Comment by stefanv** [comment]
It's true that most debugging for Cython is done by looking at the annotation and checking a certain line's "yellowness", or the number of lines of C generated for the corresponding line of Cython.  It's simple, but works surprisingly well.

**Comment by stuartarchibald** [comment]
@hameerabbasi Thanks for the feedback. I agree that line numbers for compilation failure (where possible) would be helpful, that is something that we're planning on improving.

The notion of warning when entering a object mode via an API is interesting, we have other debug warnings to warn users if [automatic parallelisation failed](http://numba.pydata.org/numba-doc/dev/user/faq.html#how-can-i-tell-if-parallel-true-worked) perhaps a similar warning RE object mode could be added (and shown once, else it may appear a lot!).

The `@jit` decorator currently has a load of [flags/options](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#numba.jit) that allow users to control to some level what is or isn't permitted, for example `@jit(nopython=True)` forbids the use of object mode and compilation will abort if something object like is encountered, do these flags help your case? The function that has been jitted also has a few [`inspect_X()` methods](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#Dispatcher.inspect_types) which show everything from the types Numba decided upon through to the assembly that was compiled. Finally there are a number of environment variables that can be set to yield [debug information](http://numba.pydata.org/numba-doc/dev/reference/envvars.html) `NUMBA_DEBUG_TYPEINFER` may be particularly useful as it shows the evolution of type propagation.

Numba has a HTML annotation generation tool, it's part of the binary `numba`. Here is a quick example:
Some source in `demo1.py`
```python
# what this code does is entirely fabricated for demonstration purposes!
import numpy as np
from numba import jit

class clazz(object):

    def __init__(self, arr):
        self._arr = arr

    @property
    def arr(self):
        return self._arr

    @arr.setter
    def arr(self, value):
        self._arr = value


def foo(a, c):

    c.arr += 12

    for i in range(len(a)):
        a[i] = np.sqrt(i) + 7
        if i % 8 + 1 > 4:
            a[i] -= np.pi


    return a

A = np.arange(100.)
c1 = clazz(11)
c2 = clazz(11)

print(foo(A, c1))
print(jit(foo)(A, c2))
```
then the shell command to generate HTML:
```bash
$ numba --annotate-html foo.html demo1.py 
```
The HTML is found in `foo.html` (obviously can't render the javascript etc below, but the `show numba IR` text is live and expands to annotated Numba IR. Also, lifted loops (those which can be compiled in `no python mode` down to machine code) are lurid green, and then code which is running in object mode is orange. This colouring also applied to whole functions IIRC, for those which are running entirely in nopython mode or object mode.
```
Function name: foo
in file: demo1.py
with signature: (array(float64, 1d, C), pyobject) -> pyobject 
---------------------------------------------------------------------------
show numba IR
18: | def foo(a, c):
19: |  
20: | c.arr += 12
21: |  
22: | for i in range(len(a)):
23: | a[i] = np.sqrt(i) + 7
24: | if i % 8 + 1 > 4:
25: | a[i] -= np.pi
26: |  
27: |  
28: | return a
```

**Comment by hameerabbasi** [comment]
Thanks so much for the detailed response!

> and shown once, else it may appear a lot!

Once per line number may be nice.

> @jit(nopython=True)

Unfortunately, we might need to support input combinations not supported by `nopython=True` (such as `np.void` and `object` arrays) so adding that flag isn't an option. Also, in a function we might need to "interleave" `nopython` and `object` modes (which would mean we need to separate the function into parts to be able to get a compilation error).

In this case, an optional warning may be extremely helpful, even if it's in compiler terms, and with line numbers, etc. It would also help find missing features in Numba a lot quicker.

@mrocklin's suggestion is helpful, as will some sort of automatic generation (`annotate=True` argument for the `jit` decorator)

**Comment by stefanv** [comment]
@stuartarchibald That's very useful; could you add a legend to the different colors at the top or bottom of the generated HTML, potentially with an extended description that pops out on click?

**Comment by Carreau** [comment]
> I wonder if we know anyone that can turn that command line tool into an IPython magic for increased accessibility

That should be doable. There is the hackish way (write to a temp file), and the clean way that would need a bit of refactoring to not write the header/footer and use [`<details>/<summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to make it collapsible without using jquery/javascript.

We can also use pygments to have one pass at syntax highlighting  and use green/red background for efficiency. If pygments also supports the IR, it should be possible to highlight the IR as well.

**Comment by stuartarchibald** [comment]
Good idea @stefanv, noted in https://github.com/numba/numba/issues/2792, thanks.

**Comment by stuartarchibald** [comment]
@Carreau Thanks for the info, at present an annotations dictionary is built up and then it's just a jinja2 template in use https://github.com/numba/numba/blob/master/numba/annotations/template.html. I imagine adding a template that is similar but compatible with ipython et al wouldn't be too hard?

Pygments to do highlighting sounds like a good idea. I don't think pygments supports Numba IR itself at present as it is quite custom. Can pygments comprehend a custom grammar? then one could be written to cover a lot of Numba IR reasonably quickly?

**Comment by Carreau** [comment]
See #2793 for the first part of simplifying templates.

One thing I'd like to do is figure out how to call numba inproces to avoid 3 layers of subprocess as the numba command itself call a subprocess.

**Comment by Carreau** [comment]
`!pip install numbannotate`

<img width="537" alt="screen shot 2018-03-05 at 19 02 32" src="https://user-images.githubusercontent.com/335567/37012115-e2665e06-20a7-11e8-9cc1-4889c620adbf.png">


And I still need a few fix in the templates I'll upstream to numba for things to look right in JupyterLab and Classsic notebook. 

Could there be a --json-annotate the return the value to stdout/err to avoid having to use a on-disk file, or even a API to do that ?

**Comment by mrocklin** [comment]
Well that didn't take long :)

**Comment by hameerabbasi** [comment]
Pygments has lexers for each language it supports. I've never written a lexer myself, but there are [docs on that](http://pygments.org/docs/lexerdevelopment/).

Also, there's a discussion about allowing Numba as a dependency on the [Scipy Dev mailing list](https://mail.python.org/pipermail/scipy-dev/2018-March/022576.html), you might want to keep an eye out.

**Comment by Carreau** [comment]
> Well that didn't take long :)

Well 5 hours is still 4 hours too long. Also the code is py3.5+ only (pathlib) and [quite ugly](https://github.com/Carreau/numbannotate) for a 35 line function...

**Comment by stuartarchibald** [comment]
Thanks for starting work on this @Carreau , it looks like a great improvement already (tried it out locally :)). I'm going to move discussion for this feature over to the PR https://github.com/numba/numba/pull/2793, thanks again.

**Comment by stuartarchibald** [comment]
I've added this https://github.com/numba/numba/pull/2859 as a WIP on making debugging Numba compilation problems more user orientated. The giant tracebacks through the compiler are now largely gone, problematic source code is highlighted and help messages are added. Feedback is very welcome. Thanks.

**Comment by stuartarchibald** [comment]
This ticket is tracking progress on usability improvements: https://github.com/numba/numba/issues/2888

**Comment by Rik-de-Kort** [comment]
Something interesting that came up in #3289 was that the error thrown by a function decorated using `@njit` differs from one decorated by `@jit`. The `@jit`-errors tend to not be as transparent as the `@njit`-errors. Unification could be beneficial. It happens on more minimal examples as well, but this one provides a striking difference.

````python
b = [0, 1]

@njit
#@jit
def a():
    c = [b[index] for index in [0, 1]]
    for x in range(5):
        pass

a()
````

With `@njit` this yields the following error:

````python
Traceback (most recent call last):
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\targets\base.py", line 455, in get_constant_generic
    impl = self._get_constants.find((ty,))
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\targets\base.py", line 49, in find
    out = self._find(sig)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\targets\base.py", line 58, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x000001FEB857BB00>, (reflected list(int64),))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\errors.py", line 259, in new_error_context
    yield
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 265, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 406, in lower_assign
    value.value)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\targets\base.py", line 458, in get_constant_generic
    raise NotImplementedError("cannot lower constant of type '%s'" % (ty,))
NotImplementedError: cannot lower constant of type 'reflected list(int64)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-4797534e2cf3>", line 10, in <module>
    a()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 766, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 725, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 712, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 248, in run
    raise patched_exception
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 240, in run
    stage()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 647, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 602, in _backend
    lowered = lowerfn()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 589, in backend_nopython_mode
    self.flags)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 885, in native_lowering_stage
    lower.lower()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\PGGM\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\errors.py", line 259, in new_error_context
    yield
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 265, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\lowering.py", line 406, in lower_assign
    value.value)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\targets\base.py", line 458, in get_constant_generic
    raise NotImplementedError("cannot lower constant of type '%s'" % (ty,))
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
cannot lower constant of type 'reflected list(int64)'
File "<ipython-input-32-4797534e2cf3>", line 5
[1] During: lowering "$6.2.414 = global(b: [0, 1])" at <ipython-input-32-4797534e2cf3> (5)
````

Whereas with `@jit` this is:
````python
Traceback (most recent call last):
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-73b6bb57d735>", line 8, in <module>
    a()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 766, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 725, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 712, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 248, in run
    raise patched_exception
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 240, in run
    stage()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 433, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\compiler.py", line 413, in frontend_looplift
    flags=loop_flags)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\transforms.py", line 193, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\analysis.py", line 213, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "C:\Users\PGGM\Anaconda3\lib\site-packages\numba\controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed at object (object mode frontend)
````

**Comment by Juanlu001** [comment]
@Carreau numbannotate does not work for `nopython=True`, correct?

**Comment by stuartarchibald** [comment]
@Juanlu001, @Carreau kindly integrated the functionality provided by `numbaannotate` into Numba itself in PR https://github.com/numba/numba/pull/2793. Under `nopython` mode the annotate tool has nothing to annotate as all the code is running in `nopython` mode (the tool marks up the difference between `object` mode and `nopython` mode). Using the `@jit` decorator on some code that has some use of objects and some loops that can be compiled, the annotation tool will show which parts of the code are compiled (lifted `nopython` mode loops) and which are running in `object` mode. To access the `numbaannotate` like functionality set `pretty=True` when calling the `.inspect_types` method on the compiled function http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html?highlight=pretty#Dispatcher.inspect_types). Here's an example:

```python
from numba import jit
import numpy as np

@jit
def foo(a, b):
    e = np.zeros_like(a)
    for i in np.arange(a.shape[0] - 1):
        c = np.sqrt(a[i]) + b[i + 1]
        d = np.cos(b[i]) + np.sin(c)
        e[i] = d + 2.
    x = object()
    for i in range(len(e)):
        e[i] += 10.
    return e, x

q = np.arange(10.)
w = np.ones((10,))

print(foo(q, w))

print(foo.inspect_types(pretty=True))
```

Further, the latest release of Numba now has the capacity to allow jumping into the interpreter from `nopython` mode: http://numba.pydata.org/numba-doc/latest/user/withobjmode.html

**Comment by Juanlu001** [comment]
Thanks @stuartarchibald! `pretty=True` worked, and I will look into the new `objmode` context manager soon.

**Comment by cdeil** [comment]
A lot of the discussion in this issue was how to understand `nopython=True/False`.

That is important and can be simplified using e.g. annotate - but in the end figuring this out isn't super hard.

But how to debug performance for code in `nopython=True` mode?

In my very limited experience, this is hard and small changes in how the functions are written will result in very different performance (see e.g. #3980 or #4031).

Maybe it's possible to add more information to the annotation output, specifically which optimisations from `parallel=True` were applied might help? Is it possible / does it make sense to show in the annotate output e.g. where vectorisation occurred?

**Comment by stuartarchibald** [comment]
@cdeil debugging performance for code that is compiled under `nopython=True` is quite hard because the transformations that happen are approximately:

 1. User source as input
 2. Create Numba IR based on the `bytecode` of the source, so even here it's CPython's interpretation of the original source that's being compiled.
 3. Various Numba rewrites of the Numba IR (including, maybe, rewrites for parallelization)
 4. Numba's IR to LLVM IR transformation
 5. Whatever things the `LLVM` compiler decides to do to the LLVM IR
 6. Executable as output

It is therefore really hard to track what happens in a generically applicable manner! It is often a question of understanding what the compiler does, and then looking at what is generated in the above steps. Various environment variables: http://numba.pydata.org/numba-doc/latest/reference/envvars.html can be used to output a lot of this information.

> Maybe it's possible to add more information to the annotation output, specifically which optimisations from parallel=True were applied might help? 

This is already done to some level, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics, suggestions for improvements are welcome.

>  Is it possible / does it make sense to show in the annotate output e.g. where vectorisation occurred?

Please could you clarify precisely what you mean by `where vectorisation occurred`? `vectorisation` is very overloaded as a concept.

I have been working on-and-off on adding linux `perf` support to the Numba tooling, https://github.com/numba/llvmlite/pull/456, which allows assembler level introspection of jitted code and the associated profiling data from execution. @sklam also did some work on obtaining optimisation pass remarks here https://github.com/numba/llvmlite/pull/337. These patches are likely to make it into mainline in due course.

I also think long term, as compiler passes become more formalised https://github.com/numba/numba/issues/4008 and the passes from parallel compilation are also run as part of the standard pipeline (e.g. effect here https://github.com/numba/numba/issues/3980#issuecomment-484181178), then providing some diagnostics about what transforms happened in the Numba IR may become easier.

**Comment by cdeil** [comment]
> debugging performance for code that is compiled under nopython=True is quite hard

I understand. If I find concrete suggestions how to improve the docs or for more annotations / tooling, I'll make them in the future.

> vectorisation?

I meant SIMD.

Specifically in the example I was struggling with today (#4031) I was suspecting that #2680 might be the issue, but I didn't know how to check where SIMD is used. Is it documented how to do this check?

---

Another issue I ran into was #3161, i.e. that `inspect_types` is broken when using `parallel=True`. But as far as I understand, `inspect_types` is not really a concern in my examples - I'm only interested in `nopython=True` and am careful what `dtype` I pass to my functions, so `inspect_types` will probably not help me at all to understand the performance differences.

**Comment by stuartarchibald** [comment]
> I understand. If I find concrete suggestions how to improve the docs or for more annotations / tooling, I'll make them in the future.

Great, thanks. Feedback and suggestions are always welcome.

> I meant SIMD.

> Specifically in the example I was struggling with today (#4031) I was suspecting that #2680 might be the issue, but I didn't know how to check where SIMD is used. Is it documented how to do this check?

I'm wondering how would you normally check for SIMD instruction use? If the answer is by looking at assembler then http://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_DUMP_ASSEMBLY might help?

RE #3161, noted, thanks. Pass formalisation will help with this.

**Comment by stuartarchibald** [comment]
Am going to summarise progress made by linking against what got done, and then close this ticket in favour or having specific tickets for specific items (noted below). Thanks to everyone for participating and providing feedback, it's much appreciated.

--------------------------
**Original ideas:**

Changes that are proposed include:
 * New user facing documentation/web pages, to include:
     * A one page guide to Numba. [**SEE 5 MINUTE GUIDE**](https://numba.readthedocs.io/en/stable/user/5minguide.html)
     * Numba decorators+flags explained. [**DECORATOR DOCS**](https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#jit-functions), [**TUTORIAL NOTEBOOKS**](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=tutorials/nasa_apps_oct_2019)
     * "Cool stuff"/new features page [**IMPLEMENTED AS RELEASE NOTEBOOKS**](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks)
     * Explain our DSO infrastructure especially with respect to LLVM (there are a lot of questions about this). [**DONE IN LLVMLITE DOCS**](https://llvmlite.readthedocs.io/en/latest/faqs.html#why-static-linking-to-llvm)
     * "how @jit works" page, high level with pictures etc [**TUTORIAL NOTEBOOKS**](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=tutorials/nasa_apps_oct_2019)
     * How to make Numba perform well and a quick guide to achieving good performance. [**PERFORMANCE TIPS DOCS**](https://numba.readthedocs.io/en/stable/user/performance-tips.html)
 * An exceptions catch-all and backtrace hiding/rewriting facility to make exceptions more user friendly (and enabled by default, devs will want to turn this off!). The rewrite facility to include:
   * Provision of better and more user friendly error messages. **DONE, error messages are hugely compressed**
   * More effort to find the offending line number(s). **DONE, error message print source and point at the line**
   * Printing the offending line (helps in Jupyter/ipython). **DONE, as above**
   * Possibly raising exception classes that are user orientated and are not named after language from compiler design. **Part done**
    * New documentation pages with explanations and examples of common problems that can be inserted into Exception messages as links. **DONE AS [FAQ DOCS](https://numba.readthedocs.io/en/stable/user/faq.html)**, **Links in error messages were implemented and removed, see next note**
    * Debug hints if applicable (common issues, like use of unsupported types, non-homogeneous lists etc). **DONE, and based on feedback removed, still accessible with [this environment variable](https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_SHOW_HELP)**
    * An Exception class for when there is likely a problem with Numba internals with instructions for users on how to report it. **DONE**
  * Bug report template **[DONE](https://github.com/numba/numba/issues/new?template=Bug_report.md)**
  * Updates to the Numba annotation tool **[DONE](https://github.com/numba/numba/pull/2793)**
  * Ensure that the feature support documentation is accurate. **ONGOING**.

Then from a developer side we are aware that we need to:
 * Write documentation on how to extend Numba and integrate it with existing code bases. **COVERED BY [EXTENSION API DOCS](https://numba.readthedocs.io/en/stable/extending/index.html)**
 * Write documentation on how to write new features in Numba without essentially having to build up LLVM IR using llvmlite builder classes (Using `@overload` and `@intrinsic`). **[MOSTLY DONE](https://numba.readthedocs.io/en/stable/extending/overloading-guide.html)**
 * Go through the existing documentation and ensure that the user documentation is accurate and that anything that is a Numba implementation/technical detail goes into the developer side documentation. **ONGOING**.

--------------------------

**Cross referencing tickets with ongoing work:**

* A line profiler/performance profiler: https://github.com/numba/numba/issues/5028
* Coverage support: https://github.com/numba/numba/pull/5660
* Compiler explorer: https://github.com/numba/numba/issues/5769
* Vectorisation remarks: https://github.com/numba/numba/pull/2817

**Cross referencing related completed work:**
* Assembly control flow graphs: https://github.com/numba/numba/pull/5212 [example1](https://github.com/numba/numba/issues/5063#issuecomment-574636041) [example2](https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#Dispatcher.inspect_disasm_cfg)
* Launching `gdb` directly from Python or Numba jitted code: https://github.com/numba/numba/pull/3392 [docs and guide](https://numba.readthedocs.io/en/stable/user/troubleshoot.html#using-numba-s-direct-gdb-bindings-in-nopython-mode)

**Comment by mrocklin** [comment]
That list is awesome.  It seems like the sort of thing that might go well
in a blogpost.  I think that people would enjoy seeing the progress made
here.
