### ISSUE TITLE
guvectorize and accumulate

### ISSUE THREAD

**Issue by jbschiratti** [numba/numba#2794]
I am using Python 3.6 and Numba 0.37.0 on Windows 10. 

Given that the function `expanding_std` from Pandas is deprecated, I wanted to write my own version of `expanding_std`. To do this, I the following function 

    import numpy as np
    from numba import guvectorize, float32
    from math import sqrt

    @guvectorize([(float32[:], float32[:])], '(n)->()')
    def std_ufunc(x, s):
        m = 0
        for k in range(x.shape[0]):
            m += x[k]
        m /= x.shape[0]
        s[0] = 0
        for j in range(x.shape[0]):
            s[0] = s[0] + (x[j] - m) ** 2.
        s[0] /= (x.shape[0] - 1)
        s[0] = sqrt(s[0])

    X = np.array([1, 2, 3, 4], dtype=np.float32)
    r = std_ufunc(X)
    rr = std_ufunc.accumulate(X)

Once the ufunc `std_ufunc` is defined, I was hopping to do `std_ufunc.accumulate(X)` to get the same results as I would get with `pd.expanding_std(X)`. However, I run into the following error:

    RuntimeError                              Traceback (most recent call last)
    <ipython-input-6-ae36c161d4c6> in <module>()
         17 X = np.array([1, 2, 3, 4], dtype=np.float32)
         18 r = std_ufunc(X)
    ---> 19 rr = std_ufunc.accumulate(X)

    RuntimeError: Reduction not defined on ufunc with signature

**Comment by DrTodd13** [comment]
Could the new auto-parallelism help?  Would something like the following work?

@numba.njit(parallel=True)
def expanding_std(x):
    m = x.sum() / x.len()
    return sqrt(((x - m) ** 2.).sum() / (x.len() - 1))

**Comment by jbschiratti** [comment]
@DrTodd13 I am not sure this could help.
Given an array `x` with shape `(n,)` the function `expanding_std` is expected to return an array of shape `(n,)`  whose j-th entry is the standard deviation of `x[:(j + 1)]`.

**Comment by DrTodd13** [comment]
Well, my code is wrong.  Misunderstood what your example was doing.   Rather than jumping straight to guvectorize, do think about how to write this is vector style or you can use prange if you absolutely have to.  The auto-parallelization stuff maps to guvectorize but should make this easier.

**Comment by ehsantn** [comment]
@jbschiratti our of curiosity, why don't you like the new `Expanding.std` interface in Pandas?

I agree with Todd that `prange` is probably useful here. BTW, we are implementing Pandas functionality in the [HPAT ](https://github.com/IntelLabs/hpat)package, which provides automatic distributed execution, in case you are interested. `Expanding.std` is not implemented yet, but should be easy to add.

**Comment by jbschiratti** [comment]
@ehsantn I did not know about this.
@DrTodd13 Sure ! The following code does the job.

    import numpy as np
    from math import sqrt
    from numba import njit

    @njit(parallel=True)
    def expanding_std(x):
        r = np.zeros((x.shape[0],))
        for j in range(1, x.shape[0]):
            m = 0
            for k in range(j + 1):
                m += x[k]
            m /= (j + 1)
            s = 0
            for k in range(j + 1):
                s += (x[k] - m) ** 2
            s /= j
            r[j] = sqrt(s)
        return r

However, as one can do `np.maximum.accumulate(X)` in one line, I was hoping to do something like "np.std.accumulate(X, ddof=1)`. Even though I can do it with `njit`, is the error I am getting the result of a wrong usage of `guvectorize` ?

**Comment by sklam** [comment]
@jbschiratti , the error you got is due to an limitation of numpy's ufunc implemenation (from [numpy/umath/ufunc_object](https://github.com/numpy/numpy/blob/a3c05b1c2ddbc61be6f5a7eaf7f8f431a4b1479c/numpy/core/src/umath/ufunc_object.c#L3859)).  Numpy ufunc reduction methods cannot be applied to any ufunc that has a non-scalar-only signature.  Since numba's guvectorize creates a numpy ufunc, the numpy limitation also applies to numba.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
