### ISSUE TITLE
CUDA autotune table needs updating for CC 7.0 (Volta)

### ISSUE THREAD

**Issue by seibert** [numba/numba#2808]
When running autotuned kernels on Volta, the warning is printed:
```
numba/cuda/compiler.py:234: UserWarning: Could not autotune, using default tpb of 128
```
This is because the autotune table needs to be updated:
https://github.com/numba/numba/blob/master/numba/cuda/cudadrv/autotune.py#L214-L225

**Comment by sklam** [comment]
Actually, we should drop this in favor of the routine provided by the driver.

**Comment by sklam** [comment]
Now, I really need this for pygdf.
