### ISSUE TITLE
CUDA unit test expected to fail no longer fails on Volta

### ISSUE THREAD

**Issue by seibert** [numba/numba#2809]
Due to the new warp divergence behavior on Volta cards, the `test_raise_causing_warp_diverge_failing` unittest that is expected to fail in debug mode, no longer fails:

https://github.com/numba/numba/blob/master/numba/cuda/tests/cudapy/test_exception.py#L96-L103

Not sure if this is a good thing (I think it is?), but at a minimum we have to change the expectedFailure condition to depend on compute capability <= 7.0.

**Comment by sklam** [comment]
I say this is a good thing.  That means we don't need to change the way we do zero-division error.

**Comment by gmarkall** [comment]
`test_raise_causing_warp_diverge_failing` no longer exists (and all CUDA unit tests generally pass on Volta and beyond), so I'm closing this issue.
