### ISSUE TITLE
Inline functions don't work when compiled ahead of time

### ISSUE THREAD

**Issue by Eric-Vignola** [numba/numba#2827]
[Numba documentation specifies that other compiled functions can be inlined and called from other compiled functions](http://numba.pydata.org/numba-doc/dev/user/jit.html). This does not seem to be true when [compiling ahead of time](http://numba.pydata.org/numba-doc/dev/user/pycc.html).

For example: here are two functions that compute the inner dot product between 2 vector arrays, one of them does the actual product, the other makes the inline call within a loop:

```
# Module test.py
import numpy as np
from numba import njit, float64

@njit(float64(float64[:], float64[:]))
def product(a, b):
    prod = 0
    for i in range(a.size):
        prod += a[i] * b[i]
    return prod

@njit(float64[:](float64[:,:], float64[:,:]))
def n_inner1d(a, b):
    prod = np.empty(a.shape[0])    
    for i in range(a.shape[0]):
        prod[i] = product(a[i], b[i])

    return prod
```

As is, I can do `import test` and use `test.n_inner1d` perfectly fine. Now lets do some modifications so this can be compiled to a .pyd

```
# Module test.py
import numpy as np
from numba import float64
from numba.pycc import CC

cc = CC('test')
cc.verbose = True

@cc.export('product','float64(float64[:], float64[:])')
def product(a, b):
    prod = 0
    for i in range(a.size):
        prod += a[i] * b[i]
    return prod

@cc.export('n_inner1d','float64[:](float64[:,:], float64[:,:])')
def n_inner1d(a, b):
    
    prod = np.empty(a.shape[0])    
    for i in range(a.shape[0]):
        prod[i] = product(a[i], b[i])

    return prod

if __name__ == "__main__":
    cc.compile()
```

I get the following error:
```
# python test.py
Failed at nopython (nopython frontend)
Untyped global name 'product': cannot determine Numba type of <type 'function'>
File "test.py", line 20
```

I'm not sure if this is a bug, or user error. If this is user error I'd love to know how to fix.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this does what you want:
```python
# Module test.py
import numpy as np
from numba import float64, njit
from numba.pycc import CC

cc = CC('test')
cc.verbose = True

@njit
def product(a, b):
    prod = 0
    for i in range(a.size):
        prod += a[i] * b[i]
    return prod

@cc.export('n_inner1d','float64[:](float64[:,:], float64[:,:])')
def n_inner1d(a, b):

    prod = np.empty(a.shape[0])    
    for i in range(a.shape[0]):
        prod[i] = product(a[i], b[i])

    return prod

if __name__ == "__main__":
    cc.compile()
```
if you decorate the callee with `@njit` the function call type resolution will work and resolve (and probably inline) `product` into the `n_inner_1d` function. If you want both a compiled version *and* an inlined version then:
```python
# Module test.py
import numpy as np
from numba import float64, njit
from numba.pycc import CC

cc = CC('test')
cc.verbose = True

@cc.export('product','float64(float64[:], float64[:])')
@njit
def product(a, b):
    prod = 0
    for i in range(a.size):
        prod += a[i] * b[i]
    return prod

@cc.export('n_inner1d','float64[:](float64[:,:], float64[:,:])')
def n_inner1d(a, b):

    prod = np.empty(a.shape[0])    
    for i in range(a.shape[0]):
        prod[i] = product(a[i], b[i])

    return prod

if __name__ == "__main__":
    cc.compile()
```
will do that. The caveat being that it is entirely possible in some cases that the inlined `product` ends up with a different type signature to that of the one declared AOT.

Hope this helps?

@sklam I wonder if it ought to be made so that a `CC` exported function are available during type resolution so that `njit` hack isn't needed?

**Comment by Eric-Vignola** [comment]
Yes this worked. I was afraid this would build a non-generic binary, but it seems to be working on 2 machines with different intel cpus. Thanks!
