### ISSUE TITLE
Support list[any numba type]

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#2828]
It would be useful to allow `list` to hold any Numba-supported type, in particular, other lists and Numpy arrays.

**Comment by stuartarchibald** [comment]
Thanks for the request, this is definitely something that needs work! I am going to close this ticket though as it is a duplicate of https://github.com/numba/numba/issues/2560 (but will add to that ticket the common vocabulary as `memory-managed object` assumes familiarity with Numba internals).
