### ISSUE TITLE
Is it possible to get func_defaults ?

### ISSUE THREAD

**Issue by jbschiratti** [numba/numba#2844]
I am trying to use `inspect.getargspec` with jitted functions. The function `myfunc` below is of type `CPUDispatcher` and has a `func_code` attribute which can be used with `inspect.getargs`. However, `inspect.getargspec` also requires `func.func_defaults`. Given a function such as

    import numba as nb
    import numpy as np
    
    @nb.jit(nb.float64[:](nb.float64[:]))
    def myfun(arr):
        n  = arr.shape[0]
        ret = np.empty((n,))
        for j in range(n):
            ret[j] = arr[j] ** 2
        return ret

Is it possible, somehow, to get `myfun.func_defaults` ?

**Comment by stuartarchibald** [comment]
Thanks for the query. Does `inspect.getargspec(myfun.py_func)` help?

**Comment by jbschiratti** [comment]
Thank you @stuartarchibald for the answer. I did not see that `myfun` has a `py_func` attribute. Problem solved :-)

**Comment by stuartarchibald** [comment]
Great, thanks for confirming. Closing.
