### ISSUE TITLE
cache=True & generators?

### ISSUE THREAD

**Issue by dektoud** [numba/numba#2868]
reproducing code:
``` python
import numba
import numpy as np

@numba.njit(cache=True)
def _thisfunc(vals):
    for v in vals:
        yield v

# calling code:
_thisfunc(np.random.rand(500))

```
results in: 
```
C:\Anaconda3\lib\site-packages\numba\caching.py in _dump(self, obj)
    563 
    564     def _dump(self, obj):
--> 565         return pickle.dumps(obj, protocol=-1)
    566 
    567     @contextlib.contextmanager

PicklingError: Can't pickle <function _thisfunc at 0x0000014AF82B4D08>: it's not the same object as __main__._thisfunc
```
but with `cache=False` the function works. Is there any workaround for this?

**Comment by stuartarchibald** [comment]
Thanks for the report.
```python
from numba import njit
@njit(cache=True)
def f():
    yield 10
f()
```
is a minimal reproducer.

Think this is a bug.

**Comment by NobodyXu** [comment]
@Rik-de-Kort It is officially stated that `yield` is supported, but the above code still gives me error.

**Comment by mtazzari** [comment]
This issue has been opened relatively long ago, and it looks like a genuine bug.
At the same time, `yield` constructs are now fully supported by numba.
Is there a timescale for fixing this?

**Comment by esc** [comment]
> This issue has been opened relatively long ago, and it looks like a genuine bug. At the same time, `yield` constructs are now fully supported by numba. Is there a timescale for fixing this?

@mtazzari thank you for asking about this, I just double checked on current master and the issue still persists. There is currently no timescale or ETA for this being fixed.

**Comment by esc** [comment]
Maybe @sklam knows more, I know there has been recent work on integrating cloud-pickle.

**Comment by sklam** [comment]
cloudpickle should make it work.  let me check

**Comment by esc** [comment]
> cloudpickle should make it work. let me check

Thank you!

**Comment by mtazzari** [comment]
amazing, thanks a lot for @sklam for fixing this!
