### ISSUE TITLE
Wrong type declaration

### ISSUE THREAD

**Issue by suuuehgi** [numba/numba#2876]
**MWE**
```python
from numba import jit 

@jit(nopython=False)
def foo(point1, point2):

  if point1.real == point2.real and point1.imag == point2.imag:
    return 0, 0

  else:
    X = point2.real - point1.real
    Y = point2.imag - point1.imag

    X = int(abs(round(X)))
    Y = int(abs(round(Y)))
    #print(type(X),type(Y))
    print(X,Y)

point1 = 1 + 1j * .5
point2 = 2 + 1j * .2

foo(point1, point2)
```

```bash
$ python MWE
1.0 0.0
```

As soon as I uncomment the first `print` statement, it works as expected:

```bash
$ python MWE
<class 'int'> <class 'int'>
1 0
```
As well as when I remove the `if`-`else` or just change the `if [...]` to `if False`.

EDIT
-------
Additionally, if I set `nopython=True` and uncomment the first `print` statement, it fails with:

```
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
cannot convert native class(float64) to Python object
```

Python 3.6.4
Numba 0.37.0
Numpy 1.14.2
llvmlite 0.23.0dev0+19.g462a8e3

**Comment by smoneck** [comment]
https://repl.it/repls/IncompatibleBaggyForms

**Comment by stuartarchibald** [comment]
Thanks for the report. This produces the correct answer (`1 0`) under Numba 0.51 when compiled with or without `nopython` mode. The reason the print shows a different type is that it's showing the Numba inferred type opposed to cpython's. Closing assuming resolved.
