### ISSUE TITLE
array.ctypes issue with optimization passes

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#2887]
Any function that uses `array.ctypes` fails (seg fault or corrupt result) it it goes through both copy propagation and remove dead code passes (minimum passes required to reproduce this). Example below can reproduce this easily.

I don't know why this is happening since the IR is equivalent either way (only the original variable is gone and replaced with another variable). @stuartarchibald @sklam @DrTodd13 any ideas?

```python
import numba
import numpy as np
numba.parfor.sequential_parfor_lowering = True
from numba import types
from numba.targets.linalg import _BLAS

kind = ord('d')
xxnrm2 = _BLAS().numba_xxnrm2(types.float64)

@numba.njit(parallel=True)
def f():
    a = np.ones(4)
    n = len(a)
    ret = np.empty((1,))
    jmp = int(a.strides[0] / a.itemsize)
    r = xxnrm2(kind, n, a.ctypes, jmp, ret.ctypes)
    return ret[0]

print(np.linalg.norm(np.ones(4)), f())
```

**Comment by stuartarchibald** [comment]
I made this a tiny bit smaller (as anything to shrink IR size is good!).
```python
import numba
import numpy as np
numba.parfor.sequential_parfor_lowering = True
from numba import types
from numba.targets.linalg import _BLAS

xxnrm2 = _BLAS().numba_xxnrm2(types.float64)

@numba.njit(parallel=True)
def f():
    ret = np.zeros(1)
    a = np.ones(4)
    xxnrm2(100, 4, a.ctypes, 1, ret.ctypes)
    return ret[0]

print(np.linalg.norm(np.ones(4)), f())
```
and to help debug, set a gdb command file like:
```
set pagination off
set breakpoint pending on
file python
break numba_xxnrm2

run issue2887.py
p n
p ((double*)x)[0]@4
p ((double*)result)[0]@1
```
put the sample into a file called `issue2887.py` and then run:
```bash
$ gdb -x cmdfile
```
output is:
```
Breakpoint 1, numba_xxnrm2 (kind=100 'd', n=4, x=0x5555563aa2e0, incx=1, result=0x5555563c9820) at numba/_lapack.c:408
408     {
$1 = 4
$2 = {-9.8683099208633679e+148, -9.8683099208633679e+148, -9.8683099208633679e+148, -9.8683099208633679e+148}
$3 = {0}
```
which suggests that it is just the `.ctypes` from variable exiting the parfors loop nest that has issues.

**Comment by seibert** [comment]
Race condition reappears in #4432.

**Comment by sklam** [comment]
Close because https://github.com/numba/numba/pull/4432#issuecomment-538479003
