### ISSUE TITLE
AssertionError - type inference issue on recursive function

### ISSUE THREAD

**Issue by dpatschke** [numba/numba#2890]
Here is a [link](https://gist.github.com/dpatschke/f764996538865b725354b90895d8449b) to a gist I have posted that attempts to port the KD-tree implementation from scipy to numba which removes the object-oriented structure in the implementation.  Since full reproducibility requires the code for building the tree as well, I decided to post as a gist rather than embed the code in the issue. Please let me know if I should do the latter as well.

As a result, the 'traverse' function is a rather complicated recursive function which the type inference engine in numba appears to be having difficulty with. If I remove the 'numba.jit' decorators (or even remove the 'nopython' parameter), the function executes as expected.

Below is the error I am receiving:
assert self.type is not None (AssertionError)

At this point, I am unaware if how I have written the function adheres to the current functionality available within numba or if this is a bug within numba. Posting an issue here in hopes to receive some direction on which it may be.

Thanks,
David

**Comment by sklam** [comment]
@dpatschke, I have tracked down the issue.  It's not a recursion problem.  It is because `np.array([]).astype(np.int32)` has a untyped `list` usage.  Change that line to `np.empty(0, dtype=np.int32)` and it will work.

The minimal reproducer:

**Comment by dpatschke** [comment]
@sklam Thanks so much for looking into this! It works for me now.  
I would never have thought there was a difference between the two.  
Thanks again!
