### ISSUE TITLE
Compilation is not thread safe because of _temporary_dispatcher_map

### ISSUE THREAD

**Issue by batterseapower** [numba/numba#2901]
Let's say you have code like this:

```
def foo():
  @jit
  def inner():
    pass
```

And then you call foo concurrently from multiple threads. This can fail with a KeyError deleting from the _temporary_dispatcher_map (https://github.com/numba/numba/blob/master/numba/typeinfer.py#L722) because another thread may have nuked the mapping you are trying to delete.

**Comment by seibert** [comment]
Fixed by #4254
