### ISSUE TITLE
Requires-Dist field empty

### ISSUE THREAD

**Issue by agoose77** [numba/numba#2903]
## Reporting a bug
If one views the JSON data from PYPI for `numba`, it appears that the `Requires-Dist` field is blank. The [poetry project](https://github.com/sdispater/poetry) uses this for resolving dependencies. See https://pypi.org/pypi/numba/json

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. Looking at the wheel metadata:
```
Metadata-Version: 2.0
Name: numba
Version: 0.37.0
Summary: compiling Python code using LLVM
Home-page: http://numba.github.com
Author: Anaconda, Inc.
Author-email: numba-users@continuum.io
License: BSD
Description-Content-Type: UNKNOWN
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: BSD License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Topic :: Software Development :: Compilers
Requires-Dist: llvmlite (>=0.22.0.dev0)
Requires-Dist: numpy
```
seems like `Requires-Dist` is set. I'm not sure how to make PYPI pick up on this, or is it that it needs to be defined elsewhere?

**Comment by agoose77** [comment]
I'm not very familiar with the packaging process, but have read that if the first wheel uploaded omits this data, newer wheels with the meta data aren't picked up.

**Comment by stuartarchibald** [comment]
ok, thanks, seems like if that's the case then that is what happened, this is the `0.1` metadata:
```
Metadata-Version: 2.1
Name: numba
Version: 0.1
Summary: compiling Python code using LLVM
Home-page: https://numba.github.com
Author: Continuum Analytics, Inc.
Author-email: numba-users@continuum.io
License: BSD
Platform: UNKNOWN
Classifier: Development Status :: 2 - Pre-Alpha
Classifier: Intended Audience :: Developers
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.2
Classifier: Topic :: Utilities

UNKNOWN
```
@seibert @sklam any idea if we can directly edit this on PyPI?

**Comment by sklam** [comment]
Still no metadata in the just released version.

**Comment by pmav99** [comment]
This seems to have been fixed

**Comment by stuartarchibald** [comment]
@pmav99 thanks, seems like there's information in `requires_dist` for 0.53.1 (from https://pypi.org/pypi/numba/json).

Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
