### ISSUE TITLE
numba 0.38.0 cannot be pip installed due to missing llvmlite

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#2917]
I just tried to install the latest numba and it's failing because llvmlite version has been increased

https://github.com/numba/numba/commit/dc3b4a58195126c8db9daf91b4e888472d5b5bc0

to something that is not released on PyPI yet

https://pypi.org/project/llvmlite/#history

**Comment by seibert** [comment]
I've uploaded the sdist for llvmlite.  Wheels will be coming tomorrow.

**Comment by sklam** [comment]
Sorry folks, some unexpected things happened that caused the delay in the wheel building.  All the wheels are uploaded to PyPI now.
