### ISSUE TITLE
Reuse wrapper functions for the same signature

### ISSUE THREAD

**Issue by eltjpm** [numba/numba#293]
Currently compiling every function produces 2 functions: one with the source function's code, callable from C, and another callable from Python that unpacks the arguments tuple and calls the first one. Generating this wrapper for every compiled function takes time and increases code size. Wrappers are easy to reuse, though. The general idea is that usually the number of different signatures is much smaller than the total number of functions. This means we can generate wrappers so that they take target function address from self, instead of hard-coding it, and reuse the same wrapper code for all compiled functions with the same signature (but, of course, still create separate wrapper objects).

**Comment by pitrou** [comment]
jitted functions can now be fully cached on-disk thanks to the `cache` parameter, so this feature request is pretty much obsolete. Closing.
