### ISSUE TITLE
Documentation: guvectorize scalar return value

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#2935]
At my first experience with guvectorize, I wasted a solid 2 hours trying to figure out how you could have the wrapped function return a scalar. It's really not trivial, as if you pass "float64" without brackes in the signature, the wrapped function will receive a plain float.
An example in the documentation would have helped a lot.

e.g.
# Scalar return values
If you want to return a scalar from a function wrapped with guvectorize, you'll need to:
- in the signatures, declare it as ``[:]`` like with a 1-dimensional array
- in the layout, declare it as ``()``
- in the implementation, write to it with ``varname[0] = ...``

Example:
```
@guvectorize(["float64[:], float64[:]"], "(i)->()")
def mysum(x, y):
    "Reimplement x.sum(axis=-1)"
    acc = 0
    for xi in x:
        acc += xi
    y[0] = acc
```

**Comment by Filco306** [comment]
This saved my day. Thank you!

**Comment by stucash** [comment]
good lord... I didn't waste as much time but it took me good time to get to this page to know that the correct example for scalar return value is actually, here. When you guys have time could you also show it on the numba website? https://numba.pydata.org/numba-doc/dev/user/vectorize.html

And reading the website, didn't really help me understand why scalar value is returned this way; if you could write just a liiiiiittle bit more to expand on this, it'll be much appreciated.

Thanks a lot!
