### ISSUE TITLE
Constrain num procs used in parallel testing

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#2940]
## Feature request

In CI environments or other cluster environments, it is typical that the system may misreport the number of cores actually available to the job and instead report the number of cores on the node the job is running on. This in spite of the fact that most jobs are allotted some fraction of the total cores on the node. Thus it is not uncommon to oversubscribe the worker based on this misreporting influencing common query strategies (e.g. `multiprocessing.cpu_count()`). Given this, it would be nice if there was an option in parallel testing to manually constrain the number of cores used for testing to avoid this problem.

**Comment by jllanfranchi** [comment]
Does setting `NUMBA_NUM_THREADS` do what you want?
https://numba.pydata.org/numba-doc/dev/reference/envvars.html#threading-control

**Comment by stuartarchibald** [comment]
@jllanfranchi Thanks for the suggestion. `NUMBA_NUM_THREADS` sets the number of threads available in the native threadpool for parallel execution of Numba jitted functions, I think what @jakirkham is after is a method of setting the number of process in use when using the parallel testing facility. i.e. make the test runner support:
```
python -m numba.runtests -m <NTHREADS>
```
?

**Comment by sklam** [comment]
This is needed for testing on machines with a lot of cpu cores (i.e. power); otherwise, the linux kernel may kill the process due to resource limit.

**Comment by jakirkham** [comment]
> `NUMBA_NUM_THREADS` sets the number of threads available in the native threadpool for parallel execution of Numba jitted functions...

We may also look at this.

> I think what @jakirkham is after is a method of setting the number of process in use when using the parallel testing facility. i.e. make the test runner support:
>
> ```
> python -m numba.runtests -m <NTHREADS>
> ```
>
> ?

Right, this is what I was thinking of when raising this issue.
