### ISSUE TITLE
@vectorize'd functions can't be pickled

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#2943]
numba 0.37.0, Python 3.6, Anaconda 5, Linux 64-bit

Being able to pickle (the reference to) a function is a fundamental prerequisite to dask.distributed.
Functions wrapped with @vectorize fail to pickle, whereas @guvectorize has no issues. I've tried both with and without explicit signatures. 

From the documentation for @vectorize:

> If signatures is non-empty, then the decorator will compile the user Python function into a Numpy ufunc. If no signatures are given, then the decorator will wrap the user Python function in a DUFunc instance

However, it looks like the above is not true - @vectorize always returns a DUFunc, whereas @guvectorize returns a ufunc:

```
import pickle
from numba import vectorize, guvectorize

@vectorize(["float64(float64)"])
def inc1(x):
    return x + 1
    
@guvectorize(["void(float64, float64[:])"], "()->()")
def inc2(x, out):
    out[0] = x + 1
   
print(type(inc2))
print(pickle.dumps(inc2))
print(type(inc1))
print(pickle.dumps(inc1))
```
Output:
```
<class 'numpy.ufunc'>
b'\x80\x03cnumpy.core\n_ufunc_reconstruct\nq\x00X\x0b\x00\x00\x00__mp_main__q\x01X\x04\x00\x00\x00inc2q\x02\x86q\x03Rq\x04.'
<class 'numba.npyufunc.dufunc.DUFunc'>
Traceback (most recent call last):
  File "vectorize_pickle.py", line 15, in <module>
    print(pickle.dumps(inc1))
TypeError: can't pickle DUFunc objects
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is a known limitation. Bug is docs should state this. There is a more long term fix for this planned deep in the Numba work pipeline.

**Comment by simnalamburt** [comment]
Experienced the same problem.

Shall I fix the "vectorize" decorator to return not DUFunc but ufunc to behave as document? Or shall I make DUFunc picklable?

I'm using numba with pyspark, and this issue is quite a big blocker for spark users to adopt numba. I want to offer some help! Just give me a direction.

**Comment by dargen3** [comment]
Hello,

firstly, thank you for Numba, it is amazing project! :)

Secondly, i want to ask. Will be the fix applied for jitclasses? By another words, will be error
"TypeError: can't pickle MyJitClass objects" fixed, please? (I use it with module multiprocessing.)

**Comment by stuartarchibald** [comment]
@dargen3 glad to hear you like Numba :)

> Will be the fix applied for jitclasses? 

Unfortunately this is a different problem to fix so the jitclass pickle problem still exits.

**Comment by dargen3** [comment]
Thank you for quick response. Is there any estimation, whether (and possibly when) it will be fixed? But i absolutely understand, if it has low preference.

**Comment by stuartarchibald** [comment]
It will be fixed, but I am not sure when. We're aware that `jitclass` needs some work, we added a tag a while back to group all the things may need a fix https://github.com/numba/numba/issues?q=is%3Aissue+is%3Aopen+label%3Ajitclass, there's quite a few :)
