### ISSUE TITLE
[bug] numba.errors.LoweringError: Failed at object (object mode frontend)

### ISSUE THREAD

**Issue by cdluminate** [numba/numba#2962]
Minimal repro code:
```python
from typing import *
import numba

@numba.jit
def filter(tokens: Dict, vocab: Dict) -> Dict:
    newtokens = {}
    sifter = lambda x: x if vocab.get(x, False) else '<UNK>'
    for sid, sent in tokens.items():
        newtokens[int(sid)] = list(map(sifter, sent))
    return newtokens

tokens = {1: ['a', 'a', 'a']}
vocab = {'a': 1}

print(filter(tokens, vocab))
```

Numba 0.38.0, llvmlite 0.23.0

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. Just as a quick thing to note, Numba will only have limited capacity to speed up code that contains unsupported containers (like dictionaries) as it will not be able to run in `no python` mode http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#no-python-mode-vs-object-mode. At best it might be able to [loop-lift](http://numba.pydata.org/numba-doc/latest/glossary.html#term-loop-lifting) some loops if there are any present and amenable to `no python` mode compilation.

**Comment by stuartarchibald** [comment]
As of Numba 0.43 this now produces:
```python
numba.errors.UnsupportedError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context: <creating a function from a closure> (op code: make_function not supported). If the feature is explicitly supported it is likely that the result of the expression is being used in an unsupported manner.

File "issue2962.py", line 7:
def filter(tokens: Dict, vocab: Dict) -> Dict:
    <source elided>
    newtokens = {}
    sifter = lambda x: x if vocab.get(x, False) else '<UNK>'
    ^
```
which notes the unsupported language features as an error opposed to lowering failing, closing.
