### ISSUE TITLE
[Feature Request] Support array.conj()

### ISSUE THREAD

**Issue by alanhdu** [numba/numba#2972]
Numba 0.38 supports `np.conj` in `nopython` mode, but it doesn't seem to support `array.conj()`:

```python
In [14]: @numba.jit(nopython=True)
    ...: def f(x):
    ...:     return x.conj()
    ...: 
    ...: x = np.array([3+1j, 4+2j])

In [15]: f(x)
```

raises

```
TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'conj' of type array(complex128, 1d, C)
```

This isn't a big deal, but I find `x.T.conj()` (as a shorthand for the hermitian) clearer and easier to read than `np.conj(x.T)`.

**Comment by ColCarroll** [comment]
I'm looking at this, but wanted to point out that it appears also to fail for any array type, and works for any number type. I'll keep looking, but if anyone has a pointer as to where to add this to methods, that would be very helpful!

```python
@numba.jit(nopython=True)
def f(x):
    return x.conjugate()

print(f(2j))  # ok
print(f(2))  # ok
print(f(2.j))  # ok
f(np.array(2))  

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'conjugate' of type array(int64, 0d, C)
```
