### ISSUE TITLE
Support numpy.cross

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#2978]
## Feature request

At the moment, `numpy.cross` is not supported, which makes some kinematics algorithms harder to implement. See for instance:

https://github.com/poliastro/poliastro/blob/aefb5b66900331e3d57c6d5a92f0c7f72c6bf931/src/poliastro/twobody/rv.py#L14-L61

**Comment by MadhavEsDios** [comment]
Any updates on this ?
