### ISSUE TITLE
Private variables with prange

### ISSUE THREAD

**Issue by tobermeier** [numba/numba#2997]
Hi all,

(mostly) copying my question from the public discussion group: I have a loop over many simulation runs and for each run, some Numpy arrays are created to store intermediate results, which looks basically like this:

```
for i in prange(n):
   temp = np.zeros(...)
   ...
```

This seems somewhat inefficient with large arrays relative to allocating the arrays once per thread and then re-using them. If I create the array before the loop, it is shared between all threads and all threads write to the same entries of the array. It would be useful to have the possibility to create private variables for threads, without allocating them on each loop iteration.

Best,
Tim

## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by tobermeier** [comment]
Thanks, that's great to know! I was trying that with an example code:
```
numba.config.DEBUG_ARRAY_OPT=1

@njit(parallel=True)
def test(n):
    for i in prange(n):
        temp = np.zeros((50, 50))
        for j in range(50):
            temp[j, j] = i

        print(temp[0, 0])

test(10)
```


I saw some mentions of hoisting showing up, but which of the lines tells me that it worked for temp? (Sorry for the very basic question!)

**Comment by DrTodd13** [comment]
@stuartarchibald @tobermeier 
You should see "Instruction $temp.16 = call $empty_attr_attr.11($tuple_var.9, $np_typ_var.12, func=$empty_attr_attr.11, args=[Var($tuple_var.9, issue2997.py (9)), Var($np_typ_var.12, issue2997.py (9))], vararg=None, kws=())  could not be hoisted because it isn't pure."
This means that np.empty isn't currently hoistable because Numba doesn't know/treat numpy.empty as a pure function (pure means it has no side effects that could change the computational result upon reordering and also that it returns the same result every time when called with the same inputs).  So, technically then, empty isn't pure because the result could be different every time but this is probably not impure in a way that matters.  I'll have a discussion with the Numba folks on whether we should add empty as pure but in the meantime, you can force it to treat empty as pure with this:

```
def empty_is_pure(rhs, lives, call_list):
    if call_list == ['empty', np]:
        return True
    return False

numba.ir_utils.is_pure_extensions += [empty_is_pure]
```

**Comment by DrTodd13** [comment]
Oh.  I guess it isn't obvious where empty is coming from.  parallel=True converts np.zeros to np.empty with an initialization to 0 inside the loop.

**Comment by stuartarchibald** [comment]
hmmm, I think we can view empty as pure. Although the contents of the returned memory is uninitialised and will therefore differ across calls with the same args, part of the implied contract is that the initialisation of the memory is left to the user. Therefore, across multiple calls with the same args the semantics are "it is the same quantity being returned" and "it is uninitialised" which I think is sufficient as a condition to assume pure (along with that it is side effect free by definition). Anything relying on uninitialised memory as a condition for success will likely contain surprises. What do you think @DrTodd13 ?

RE: the loop hoist invariant message, we need to do some work on making these debug messages traceable across transforms such that they relate back to the original source. As core developers we know that `np.zeros` is a `np.empty` with a zero init, but that's an implementation detail. Whether this detail is exposed as part of debug messages or not is another question.

**Comment by tobermeier** [comment]
Thanks, that clarifies everything! It's a fairly interesting issue, because so far I wrote all codes assuming that the the array would be re-initialized with zeros and only wrote non-zero entries to it within the loop. When the array is hoisted, one may have to overwrite the results from previous loop iterations instead, if that matters for the computations.

**Comment by stuartarchibald** [comment]
I'm fairly sure that if `np.empty` is declared pure it's solely the allocation from `np.zeros` that is hoisted. Whilst an oversimplification of the reality of the transforms taking place, I think this is approximately what is happening:
```python
@njit(parallel=True)
def test(n):
    for i in prange(n):
        temp = np.empty((50, 50)) # <--- np.zeros() is rewritten as np.empty()
        temp[:] = 0               # <--- and then a zero initialisation
        for j in range(50):
            temp[j, j] = i

        print(temp[0, 0])

test(10)
```
then after hoisting
```python
@njit(parallel=True)
def test(n):
    temp = np.empty((50, 50)) # <--- allocation is hoisted as a loop invariant if considered pure
    for i in prange(n):
        temp[:] = 0           # <--- this remains as assignment is a side effect
        for j in range(50):
            temp[j, j] = i

        print(temp[0, 0])

test(10)
```

**Comment by stuartarchibald** [comment]
@DrTodd13 added the merged https://github.com/numba/numba/pull/3004 which declares empty as pure. Rerunning with this returns nothing, so the allocation is hoisted:
```
python issue2997.py  2>&1|grep hoisted|grep -i empty
```
Any objections to closing?

**Comment by stuartarchibald** [comment]
I've been working on parallel diagnostics. I've put this sample into a file called `example3.py` and then run it with the diagnostics switched on. The result is:
```
A parallel for-loop (labelled as #0) is produced from: 'zeros function' at example3.py (7)
A parallel for-loop (labelled as #1) is produced from: 'user defined prange' at example3.py (6)

Attempting parallel loop fusion (combines loops with similar properties) for function 'test', example3.py (4):

Following the attempted fusion of parallel for-loops, function 'test' (example3.py (4)) has 1 parallel for-loop(s) (originating from loops labelled #1, ).
--------------------------------------------------------------------------------

--------Nested parallel loop summary for function test, example3.py (4):--------

+--1 is a parallel loop, containing:
   +--0 --> rewritten as scalar loop

--------------------------------------------------------------------------------

-------Nested loop diagnostic summary for function test, example3.py (4):-------

Parallel region 0:
+--1 (parallel)
   +--0 (scalar)

--------------------------------------------------------------------------------

The memory allocation derived from the instruction at example3.py (7) is hoisted out of the parallel loop labelled #1 (it will be performed before the loop is executed and reused inside the loop):
   Allocation:: temp = np.zeros((50, 50))
    - numpy.empty() is used for the allocation.
```
is there anything else that's derivable and could be of use, if so I'll work on getting it out?

**Comment by DrTodd13** [comment]
Can't think of anything else that is derivable but I have a suggestion for the format.  I'd suggest that the loop structure be printed before fusion and then after fusion.  As this is currently printed, a user might be confused and think fusion did something when in this case it doesn't.  You could also then say the number of separate loops eliminated by fusion.  Also, is "scalar" the right term here?  What was your thinking process here about scalar vs sequential?

I like the hoisted info you figured out.  Nice job!

**Comment by tobermeier** [comment]
Btw, does hoisting work with nested functions? I tried it with another example, but wasn't sure about the interpretation of the debug info:

```
numba.config.DEBUG_ARRAY_OPT=1

@njit
def inner_function(i):
    temp = np.zeros((50, 50))
    temp[0, 0] = i

    return temp

@njit(parallel=True)
def test(n):
    for i in prange(n):
        temp = inner_function(i)

        print(temp[0, 0])

test(10)
```

**Comment by stuartarchibald** [comment]
@tobermeier Thanks for the new example. If I recall correctly the inner function will not be inlined at the IR transform/processing stage and as a result the loop invariant analysis will not spot the potential to hoist the allocation. The inner function is however likely to be inlined by LLVM during compilation, at LLVM's discretion. To achieve the effect you want you can declare the inner function as a closure like:

```python
import numpy as np
from numba import njit, prange

@njit(parallel=True)
def test(n):

    def inner_function(i):
        temp = np.zeros((50, 50))
        temp[0, 0] = i

        return temp

    for i in prange(n):
        temp = inner_function(i)

        print(temp[0, 0])

test(10)
```
which, with the diagnostics I'm working on running, produces:
```
$ python hoist2.py 
A parallel for-loop (labelled as #0) is produced from: 'zeros function' at hoist2.py (8)
A parallel for-loop (labelled as #1) is produced from: 'user defined prange' at hoist2.py (13)

Attempting parallel loop fusion (combines loops with similar properties) for function 'test', hoist2.py (4):

Following the attempted fusion of parallel for-loops, function 'test' (hoist2.py (4)) has 1 parallel for-loop(s) (originating from loops labelled #1, ).
--------------------------------------------------------------------------------

---------Nested parallel loop summary for function test, hoist2.py (4):---------

+--1 is a parallel loop, containing:
   +--0 --> rewritten as scalar loop

--------------------------------------------------------------------------------

--------Nested loop diagnostic summary for function test, hoist2.py (4):--------

Parallel region 0:
+--1 (parallel)
   +--0 (scalar)

--------------------------------------------------------------------------------

The memory allocation derived from the instruction at hoist2.py (8) is hoisted out of the parallel loop labelled #1 (it will be performed before the loop is executed and reused inside the loop):
   Allocation:: temp = np.zeros((50, 50))
    - numpy.empty() is used for the allocation.
```

**Comment by tobermeier** [comment]
Ok, thanks!

**Comment by stuartarchibald** [comment]
@DrTodd13 I've got it to do this:
```
$ python example1.py 
A parallel for-loop (labelled as #0) is produced from: 'array expression ((-(((p - points) ** 2))) / '$56.15' (temporary variable))' at example1.py (14)
A parallel for-loop (labelled as #1) is produced from: 'array expression (exp((d - m)))' at example1.py (16)
A parallel for-loop (labelled as #2) is produced from: 'numpy.min (internal parallel version)' at example1.py (15)
A parallel for-loop (labelled as #3) is produced from: 'numpy.sum (internal parallel version)' at example1.py (17)
A parallel for-loop (labelled as #4) is produced from: 'user defined prange' at example1.py (12)

Attempting parallel loop fusion (combines loops with similar properties) for function 'kde', example1.py (5):
    Trying to fuse loops #0 and #2:
        - fusion succeeded: parallel for-loop #2 is fused into for-loop #0.
    Trying to fuse loops #1 and #3:
        - fusion succeeded: parallel for-loop #3 is fused into for-loop #1.

-------------Fused loop summary for function kde, example1.py (5):--------------

+--0 has the following loops fused into it:
   +--2 (fused)

+--1 has the following loops fused into it:
   +--3 (fused)


Following the attempted fusion of parallel for-loops, function 'kde' (example1.py (5)) has 1 parallel for-loop(s) (originating from loops labelled #4, ).
--------------------------------------------------------------------------------

--------Nested parallel loop summary for function kde, example1.py (5):---------

+--4 is a parallel loop, containing:
   +--0 --> rewritten as serial loop
   +--1 --> rewritten as serial loop

--------------------------------------------------------------------------------

-------Nested loop diagnostic summary for function kde, example1.py (5):--------

Before fusion:
Parallel region 0:
+--4 (parallel)
   +--0 (parallel)
   +--2 (parallel)
   +--1 (parallel)
   +--3 (parallel)

After fusion:
Parallel region 0:
+--4 (parallel)
   +--0 (serial)
      +--2 (fused)
   +--1 (serial)
      +--3 (fused)

Parallel region 0 (loop #4) had 2 loop(s) fused and 2 loop(s) serialized as part of the larger parallel loop (#4).

--------------------------------------------------------------------------------

The memory allocation derived from the instruction at example1.py (14) is hoisted out of the parallel loop labelled #4 (it will be performed before the loop is executed and reused inside the loop):
   Allocation:: d = (-(p-points)**2)/(2*b**2) #0
    - numpy.empty() is used for the allocation.

    Trying to fuse loops #0 and #1:
        - fusion failed: parallel loop 1 has a dependency on the body of parallel loop 0. 

```
Was that something along the lines you were thinking?

**Comment by stuartarchibald** [comment]
This functionality has been on the master branch and in a few releases now (as of 0.43) closing.
