### ISSUE TITLE
Wrong results when calculating power with an array

### ISSUE THREAD

**Issue by dionhaefner** [numba/numba#2998]
Since Numba 0.38.0, the following function leads to wrong results:

```python
import numpy as np
import numba as nb

def test(a, b):
    return (1. / a) ** b

test_nb = nb.njit(test)
```

Example:

```python
>>> test_nb(0.1 * np.ones(50), np.ones(50))
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 10., 10.])
```

Expected output (with NumPy):

```python
>>> test(0.1 * np.ones(50), np.ones(50))
array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])
```

I have only encountered this bug on Windows, and it does not occur on Numba 0.37.0. Relevant output from `conda list`:

```
llvmlite                  0.23.0                   py36_1    conda-forge
numba                     0.38.0           py36h830ac7b_0
numpy                     1.14.2           py36h5c71026_0
python                    3.6.0                         0
```

Let me know if you need more information.

**Comment by dionhaefner** [comment]
Setting `NUMBA_DISABLE_INTEL_SVML=1` indeed fixes the issue. Thanks for the quick reaction.

**Comment by seibert** [comment]
If this turns out to be a bug that also affects our Windows builds of llvmlite, we will want to put out a patch release that defaults `NUMBA_DISABLE_INTEL_SVML=0`.  If the problem is only with conda-forge builds, we'll need to escalate it to whoever manages that recipe ASAP.

**Comment by dionhaefner** [comment]
Installing `llvmlite==0.23.1` from `defaults` also fixed the issue. So it seems to be `conda-forge` specific.

**Comment by seibert** [comment]
OK, thanks for checking.  I'm going to keep this issue open while we figure out what the best solution with conda-forge is.

**Comment by stuartarchibald** [comment]
RE: https://github.com/numba/numba/issues/2998#issuecomment-392871302 I wonder whether, for cross platform consistency, we ought to switch `SVML` off on windows?

**Comment by seibert** [comment]
Are we sure that the problem is only Windows?  If the conda-forge llvmlite is install on a Linux box with SVML present, what happens?

I'm worried that instead we need to be able to detect when llvmlite has been linked against an unpatched LLVM (regardless of platform), and then disable SVML support in that case, regardless of whether the library is present.
