### ISSUE TITLE
'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by aerusso** [numba/numba#3005]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG). **I'm using Debian unstable 0.37.0**
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba

def A(t,y,*a): 
    return B(t,*y,*a)

def B(*a):
    return sum(a) 

Ac = numba.jit(A)
```

`A(0,(0,))` returns 0. `Ac(0,(0,))` gives an error, `'str' object has no attribute 'name'`. You can work around this by doing something like

```python
def A(t,y,*a):
    return B(*((t,)+tuple(y)+a))
```

Sorry if this has already been fixed, but I wasn't able to get llvmlite 0.23 to build (easily) on Debian, so I gave up trying to get git master to work.

**Comment by aerusso** [comment]
I have been able to reproduce this on 0.38.1. Also, the "workaround" doesn't really work (it fails with `nopython=True`).

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce.

**Comment by aerusso** [comment]
As of 0.42.0 on Debian, I can no longer reproduce this issue.
