### ISSUE TITLE
Detect whether LLVM has SVML enabled and override SVML setting if not present

### ISSUE THREAD

**Issue by seibert** [numba/numba#3006]
The bug in #2998 (and likely the one reported in the discussion of #2938) has revealed a situation where array expressions will give the wrong answer.  Triggering this bug requires:

* The ICC runtime (specifically libsvml) is present in the user's environment
* The user is using an llvmlite statically linked against a version of LLVM that has not been patched with SVML support.
* [Edit: Forgot one more condition] The platform is 64-bit.

We incorrectly assumed that this combination would be extremely unlikely, and if did happen, LLVM would raise an error.  This was a mistake, as it seems:

1. There are a number of Windows users getting llvmlite from the [Chris Gohlke packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/) or from conda-forge, which do not apply all of our LLVM patches.  (Note that anyone who gets llvmlite from the Numba channel on Anaconda Cloud, the default channel from Anaconda, or pip installs the wheels posted to PyPI are unaffected by this problem.)
2. Many Windows users of Numba have the ICC runtime present as Intel Fortran is commonly used to compile SciPy for Windows due to challenges getting other Fortran compilers to work on Windows.
3. Unpatched LLVM does not raise an error when we enable SVML autovectorization, but rather seems to generate incorrect code instead.

To correct this, we're going to add a function to llvmlite to verify if the LLVM being used has the patch.  (Note, as LLVM is statically linked to llvmlite, it does not matter what LLVM is present on the end user system, only which LLVM is used to build llvmlite.)  Numba will look for this function, and if it is not present or returns false (SVML support not available), it will disable the SVML code generation on that platform, regardless of whether the ICC runtime is present.

Although it affects a small number of users, we view this as a critical bug, and will be making patch releases of Numba 0.38 and llvmlite 0.23 outside of our normal release cycle.

**Comment by cgohlke** [comment]
FWIW, I rebuilt the llvmlite binaries at https://www.lfd.uci.edu/~gohlke/pythonlibs/#llvmlite using "the patches".
