### ISSUE TITLE
Unknown py2.7 concurrent compile+cache bug

### ISSUE THREAD

**Issue by sklam** [numba/numba#3011]
There was an unknown concurrent compile+cache bug in #2986 resolved by [changing the test](https://github.com/numba/numba/pull/2986/commits/2a8cb53c2a30f89dfcda6e368374df744bd52542).  The affected tests represent a very unusual use-case.  I guessing the reason for the bug has to do with the lack of `__qualname__` in py2.

**Comment by stuartarchibald** [comment]
Closing as python 2.7 is now unsupported.
