### ISSUE TITLE
InternalError for ndarray.flat used as an argument between njitted functions

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3015]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Problem exists in Numba master.

The root cause of the issue in https://github.com/numba/numba/issues/2954 is that `A.flat` is not working correctly when used as an arg to another njit function.  Reproducer:

```python
from numba import njit
import numpy as np

@njit
def bar(A):
    return A[0]

@njit
def foo(A):
    return bar(A.flat)

foo(np.arange(10))
```
gives:
```
numba.errors.InternalError: Failed at nopython (nopython mode backend)
expecting {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i64, i64*} but got i8*
[1] During: resolving callee type: type(CPUDispatcher(<function bar at 0x7f90410c8ea0>))
[2] During: typing of call at issue2954.py (11)

--%<----------------------------------------------------------------------------


File "issue2954.py", line 11:
def foo(A):
    return bar(A.flat)
    ^
```

**Comment by stuartarchibald** [comment]
This is also a problem:
```python
from numba import njit
import numpy as np

@njit
def bar(A):
    pass

bar(np.arange(10).flat)
```
gives:
```
numba.errors.InternalError: 
[1] During: typing of argument at issue2954.py (6)
--%<----------------------------------------------------------------------------


File "issue2954.py", line 6:
def bar(A):
    pass
    ^

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'numpy.flatiter'>
```

**Comment by stuartarchibald** [comment]
On mainline for 0.55, both of these issues are now not ICEs. The first compiles correctly, the second is a valid typing error.

**Comment by lgarrison** [comment]
Out of curiosity, is it the intended behavior that a `flatiter` can be passed between jitted functions, but not from the interpreter into a jitted function?
