### ISSUE TITLE
ipython kernel dies when using jit

### ISSUE THREAD

**Issue by ysBach** [numba/numba#3016]
I am using numba on Windows 10 (64-bit) with Anaconda3 (v 5.2), numba 0.38.0, and numpy 1.14.3.

When I run the code attached below for test, `ident_loops` works just fine, but the ipython kernel dies if I use `jit` (`jident_loops` in the code). I tested it on spyder and jupyter notebook, but the kernel dies in both cases.

I tested the identical code on my previous machine (Ubuntu 16.04) without any problem, but it kills the kernel now. (Currently I have only Windows so I cannot test it on Ubuntu again).

I deleted Anaconda and re-installed, but nothing changed.

```python
from numba import jit
import numpy as np

def ident_loops(x):
    r = np.empty_like(x)
    n = len(x)
    for i in range(n):
        r[i] = np.cos(x[i]) ** 2 + np.sin(x[i]) ** 2
    return r

@jit
def jident_loops(x):
    r = np.empty_like(x)
    n = len(x)
    for i in range(n):
        r[i] = np.cos(x[i]) ** 2 + np.sin(x[i]) ** 2
    return r

print(ident_loops(np.arange(1000)))
print(jident_loops(np.arange(1000)))
```

Any possible solution to this...?

Added: Some other examples, e.g., at [documentation](http://numba.pydata.org/numba-doc/0.38.0/user/examples.html) seem to work without problem. So now I guess my test code is seriously problematic...?

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce, will look into it.

**Comment by ysBach** [comment]
@stuartarchibald Thanks. I also found that the same code works for `jident_loops(np.arange(n))` for n < 8, but it kills the kernel from n = 8.

**Comment by stuartarchibald** [comment]
Thanks, I believe that would be the case, this is a SVML related problem (SVML does vector math intrinsics, if you have n<8, chances are it is taking a different path depending on hardware etc). As a work around you can do:
```python
import os
os.environ['NUMBA_DISABLE_INTEL_SVML']  = '1'
import numba
```
so that it is disabled before Numba is initialised.

I've pinned it down to an illegal instruction being generated and executed, this is why the kernel dies.

**Comment by stuartarchibald** [comment]
@anton-malakhov any ideas? It's invariant of ipython/jupyter and reproduces in the standard CPython interpreter. The machine I'm reproducing on has a haswell chip and windows 7. Doesn't seem to matter which `icc_rt` is in use (defaults or Numba/Intel version). Conda setup line is:
```
conda create -n issue3016 numba jupyter numpy=1.14.3
```
running and attaching a debugger I can see:
```
Unhandled exception at <address provided if useful> svml_dispmd.dll in python.exe:
0xC000001D: Illegal Instruction
```
and I can provide the disassembly at that location if requested. Thanks.

**Comment by stuartarchibald** [comment]
Spoofing CPUs, seems like Westmere is the highest featureset that will not produce an illegal instruction for this machine.

**Comment by anton-malakhov** [comment]
Thanks for the report, we are on it

**Comment by anton-malakhov** [comment]
First result is that Numba/LLVM generates call to `__svml_cos8_ha` (and sin), which is AVX-512 version, then it fails on zmm-enabled instruction

**Comment by dvnagorny** [comment]
For unfortunately still not found reason LLVM on windows selects 8 as vectorization factor. I'm looking for the source of issue. So as temporary workaround I'd suggest the following to the __init__.py

```python
def _try_enable_svml():
    """
    Tries to enable SVML if configuration permits use and the library is found.
    """
    if not config.DISABLE_INTEL_SVML:
        try:
            if sys.platform.startswith('linux'):
                llvmlite.binding.load_library_permanently("libsvml.so")
            elif sys.platform.startswith('darwin'):
                llvmlite.binding.load_library_permanently("libsvml.dylib")
            elif sys.platform.startswith('win'):
                llvmlite.binding.load_library_permanently("svml_dispmd")
	        llvmlite.binding.set_option('SVML3016', '-force-vector-width=4')
            else:
                return False
            llvmlite.binding.set_option('SVML', '-vector-library=SVML')
            return True
        except:
            if platform.machine == 'x86_64' and config.DEBUG:
                warnings.warn("SVML was not found/could not be loaded.")
    return False
```

**Comment by dvnagorny** [comment]
To select upper bound for vectorization factor LLVM divides widest register length by size smallest type it found in the loop. So the difference between windows and linux in default type of array created by np.arange.  On windows this type is int32, in Linux this type is int64. 
It is the problem of SVML vectorizer itself and it wasn't touched in SVML patch.
I will look for the fix.

**Comment by stuartarchibald** [comment]
Thanks for looking into this @anton-malakhov and @dvnagorny, the explanations seem good. I anticipate that a patch can be applied to the llvmlite LLVM builds independently of upstream acceptance.  As suggested above we should also augment the unit tests for SVML to check for this occurrence. Thanks again :)

**Comment by anton-malakhov** [comment]
the stock clang installation (apt install from  http://apt.llvm.org/xenial llvm-toolchain-xenial/main) has the same issue, reproduced using following:
```C
// svml-3016.c
#include <math.h>
int a[1<<10],b[1<<10];
void foo()
{
    int i = 0;

    for(i = 0; i < 1 << 10; i++) {
        b[i] = sin(a[i]);
    }
}
```
Running `clang-7 svml-3016.c -fvectorize -fveclib=SVML -O -S -emit-llvm -mavx  -o - | grep sin8` will give you the undesired match.

**Comment by stuartarchibald** [comment]
This issue should be fixed in the `llvmlite` builds in the Numba channel, it can be obtained via:
```
conda upgrade llvmlite -c numba
```
With an updated `llvmlite` I now do not see the problem above.

**Comment by generic-github-user** [comment]
I had this issue for a while as well - it turned out to be caused by an out-of-bounds NumPy array index, which was an easy fix once I figured it out. If possible, an explicit error message/warning could be very helpful for new users trying to figure out why the kernel is crashing.

**Comment by esc** [comment]
@generic-github-user thank you for pointing this out. As documented in:

https://numba.pydata.org/numba-doc/dev/reference/jit-compilation.html?highlight=boundscheck

```
[...] boundscheck enables bounds checking for array indices. Out of bounds accesses will raise IndexError. The default is to not do bounds checking. If bounds checking is disabled, out of bounds accesses can produce garbage results or segfaults. However, enabling bounds checking will slow down typical functions, so it is recommended to only use this flag for debugging. You can also set the NUMBA_BOUNDSCHECK environment variable to 0 or 1 to globally override this flag. [...]
```

So this means, boundchecking is turned off by default to enable faster computation and the burden to check if out-of-bounds access can occur is the responsibility of the user.

**Comment by generic-github-user** [comment]
I see, thank you for clarifying.
