### ISSUE TITLE
exponent function fails with Illegal instruction: 4

### ISSUE THREAD

**Issue by andrej5elin** [numba/numba#3024]
Dear numba developers,

I am on numba 0.38 (`conda install -c intel numba`) on OSX (intel broadwell processor). When SVML enabled, the following example fails (kernel dies) with *Illegal instruction: 4*

```python
import os
os.environ['NUMBA_DISABLE_INTEL_SVML']  = '0' #works well with SVML disabled

import numba as nb
import numpy as np

dtype = "complex64" #works well with "complex128"
sig = ["{0}({0})".format(dtype)]
N = 8 #works well with N < 8

@nb.vectorize(sig)
def exp_ok(a):
    return np.exp(a)

@nb.vectorize(sig)
def exp_fails(a):
    return np.exp(a*1j)

@nb.vectorize(sig)
def cos_ok(a):
    return np.cos(a*1j)

a = np.arange(N, dtype = dtype)
print(exp_ok(a))
print(cos_ok(a))
print(exp_fails(a)) #with N>=8 fails with 'Illegal instruction: 4'
```

This may be related to #3016

**Comment by stuartarchibald** [comment]
This issue should be fixed in the `llvmlite` builds in the Numba channel, it can be obtained via:
```
conda upgrade llvmlite -c numba
```
With an updated `llvmlite` I now do not see the problem above.

**Comment by stuartarchibald** [comment]
Numba 0.39.0 has been released and should contain all necessary fixes. Please reopen this issue if you can reproduce on 0.39.0. Thanks.
