### ISSUE TITLE
Slow performance on repeated deserialization

### ISSUE THREAD

**Issue by mrocklin** [numba/numba#3026]
I'm running into performance problems when I deserialize a numba function many times within the same process.  I have a small example here:

### Process 1

```python
import numba
@numba.njit
def f(x):
    total = 0
    for i in range(len(x)):
        total += x[i]
    return total
import cloudpickle
cloudpickle.dumps(f)
```

```
b'\x80\x04\x95\xa8\x01\x00\x00\x00\x00\x00\x00\x8c\x0fnumba.serialize\x94\x8c\x12_rebuild_reduction\x94\x93\x94(\x8c\x16numba.targets.registry\x94\x8c\rCPUDispatcher\x94\x93\x94\x8c$64ebbc90-6b3a-11e8-963f-49110aa33909\x94(K\x04C\x043\r\r\n\x94C\xa4\xe3\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s*\x00\x00\x00d\x01}\x01x t\x00t\x01|\x00\x83\x01\x83\x01D\x00]\x10}\x02|\x01|\x00|\x02\x19\x007\x00}\x01q\x12W\x00|\x01S\x00)\x02N\xe9\x00\x00\x00\x00)\x02\xda\x05range\xda\x03len)\x03\xda\x01x\xda\x05total\xda\x01i\xa9\x00r\x07\x00\x00\x00\xfa\x1e<ipython-input-2-359c566f9f92>\xda\x01f\x01\x00\x00\x00s\x08\x00\x00\x00\x00\x02\x04\x01\x12\x01\x10\x01\x94\x87\x94}\x94(\x8c\x05range\x94\x8c\x08builtins\x94\x8c\x05range\x94\x93\x94\x8c\x03len\x94\x8c\x08builtins\x94\x8c\x03len\x94\x93\x94\x8c\x08__name__\x94\x8c\x08__main__\x94u\x8c\x01f\x94Nt\x94}\x94}\x94\x8c\x08nopython\x94\x88s\x8c\x06direct\x94\x88]\x94t\x94R\x94.'
```

### Process 2

```python
import pickle
import numpy as np
x = np.random.random(1000)
b =  b'\x80\x04\x95\xa8\x01\x00\x00\x00\x00\x00\x00\x8c\x0fnumba.serialize\x94\x8c\x12_rebuild_reduction\x94\x93\x94(\x8c\x16numba.targets.registry\x94\x8c\rCPUDispatcher\x94\x93\x94\x8c$64ebbc90-6b3a-11e8-963f-49110aa33909\x94(K\x04C\x043\r\r\n\x94C\xa4\xe3\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s*\x00\x00\x00d\x01}\x01x t\x00t\x01|\x00\x83\x01\x83\x01D\x00]\x10}\x02|\x01|\x00|\x02\x19\x007\x00}\x01q\x12W\x00|\x01S\x00)\x02N\xe9\x00\x00\x00\x00)\x02\xda\x05range\xda\x03len)\x03\xda\x01x\xda\x05total\xda\x01i\xa9\x00r\x07\x00\x00\x00\xfa\x1e<ipython-input-2-359c566f9f92>\xda\x01f\x01\x00\x00\x00s\x08\x00\x00\x00\x00\x02\x04\x01\x12\x01\x10\x01\x94\x87\x94}\x94(\x8c\x05range\x94\x8c\x08builtins\x94\x8c\x05range\x94\x93\x94\x8c\x03len\x94\x8c\x08builtins\x94\x8c\x03len\x94\x93\x94\x8c\x08__name__\x94\x8c\x08__main__\x94u\x8c\x01f\x94Nt\x94}\x94}\x94\x8c\x08nopython\x94\x88s\x8c\x06direct\x94\x88]\x94t\x94R\x94.'
```

We see that repeated calls of deserializing and then calling the function remain somewhat slow at 60ms per call.

```python
In [5]: %time pickle.loads(b)(x)
CPU times: user 255 ms, sys: 23.8 ms, total: 279 ms
Wall time: 281 ms
Out[5]: 515.6796588752262

In [6]: %time pickle.loads(b)(x)
CPU times: user 63.4 ms, sys: 3.84 ms, total: 67.2 ms
Wall time: 66.2 ms
Out[6]: 515.6796588752262

In [7]: %time pickle.loads(b)(x)
CPU times: user 68.3 ms, sys: 0 ns, total: 68.3 ms
Wall time: 67.1 ms
Out[7]: 515.6796588752262
```

The cost of deserializing is relatively low

```python
In [8]: %time f = pickle.loads(b)
CPU times: user 619 µs, sys: 66 µs, total: 685 µs
Wall time: 696 µs
```

And if we call this function many times then things are ok

```python
In [9]: %time f(x)
CPU times: user 65.9 ms, sys: 3.42 ms, total: 69.3 ms
Wall time: 68.6 ms
Out[9]: 515.6796588752262

In [10]: %time f(x)
CPU times: user 25 µs, sys: 2 µs, total: 27 µs
Wall time: 34.6 µs
Out[10]: 515.6796588752262

In [11]: %time f(x)
CPU times: user 36 µs, sys: 3 µs, total: 39 µs
Wall time: 52.7 µs
Out[11]: 515.6796588752262
```

So my guess is that we should be deduplicating things in some way.  Is this in scope for Numba to resolve or is this something that I should be handling on my end?

**Comment by seibert** [comment]
@sklam is checking on this.  Serialized functions should carry a UUID that allows us to detect when identical functions are being deserialized.

**Comment by sklam** [comment]
Weird, I don't get the same dispatcher object if I `cloudpickle.loads` with `%time`.

```

In [37]: id(cloudpickle.loads(s))
Out[37]: 4480579288

In [38]: id(cloudpickle.loads(s))
Out[38]: 4480579288

In [39]: id(cloudpickle.loads(s))
Out[39]: 4480579288

In [40]: id(cloudpickle.loads(s))
Out[40]: 4480579288

In [41]: id(cloudpickle.loads(s))
Out[41]: 4480579288

In [42]: %time id(cloudpickle.loads(s))
CPU times: user 288 µs, sys: 1 µs, total: 289 µs
Wall time: 293 µs
Out[42]: 4480579768

In [43]: %time id(cloudpickle.loads(s))
CPU times: user 281 µs, sys: 1e+03 ns, total: 282 µs
Wall time: 287 µs
Out[43]: 4480580008

In [44]: %time id(cloudpickle.loads(s))
CPU times: user 287 µs, sys: 1e+03 ns, total: 288 µs
Wall time: 293 µs
Out[44]: 4480580248
```

**Comment by mrocklin** [comment]
A modest time delay would suit my needs well.

**Comment by mrocklin** [comment]
Or alternatively a rolling buffer of the last 100 deserialized functions or so.  Given that we have bytes we could also limit this by size of the serialized result.

**Comment by mrocklin** [comment]
So something like 1MB of serialized functions

**Comment by stuz5000** [comment]
More generically -- could you specify an LRU cache that has configurable limits (either TTL or size).
1MB like to be too small for many.

**Comment by mrocklin** [comment]
Are you suggesting that I do this on my end?  (that would be fine, though less pleasant than Numba handling it)

> 1MB like to be too small for many.

To be clear here we're talking about the serialized form of the function *pre-compilation*.  1MB seems like a decent number because it's small relative to the size of the CPython runtime but likely pretty large relative to function size.  That being said, I agree that extra configurability would be nice.

```python
In [1]: import numba

In [2]: @numba.njit
   ...: def f(x):
   ...:     total = 0
   ...:     for i in range(len(x)):
   ...:         total += x[i]
   ...:     return total
   ...: 

In [3]: import cloudpickle

In [4]: len(cloudpickle.dumps(f))
Out[4]: 435
```

**Comment by stuz5000** [comment]
I don't know if you could.

I'm interested in this because we serialize callable objects to perform distributed RPC - I'm fairly certain that (in total) our serialized python objects and LLVM objects would be >> 1MB. Currently we avoid this by only serializing pure Python functions. It would be nice to be able to serialize the JITed functions too --  re-compilation at every deserialization would be a killer.

**Comment by mrocklin** [comment]
> It would be nice to be able to serialize the JITed functions too -- re-compilation at every deserialization would be a killer

In the application I care about re-compilation once per process would be fine, so serialization of just Python source suffices.

**Comment by mrocklin** [comment]
This remains a pain point for some applications that use Numba and Dask together.  I'm curious if there is anything I can do to push on this.  I tried working around it in Dask but caching at the Dask level but ran into issues. I suspect that Dask isn't caching all of the right things, especially when there are closures and such.

**Comment by seibert** [comment]
PR #3151 resolves the issue with the microbenchmarks above, so feel free to give it a try.  (It is functional, just needs another unit test.)

**Comment by mrocklin** [comment]
Hi all, 

Thanks again for solving this last year.  Is there any chance that this fix would not carry over to `numba.cuda.jit` functions?  Some of my Dask + Numba + GPU workloads are running 100x slower than I think they should, and I'm beginning to suspect that this is why.

**Comment by seibert** [comment]
That seems likely.  Can you open a new issue and assign it to me?  We should be able to slide in a fix before the RC on Sept 30.

**Comment by mrocklin** [comment]
Raised here: https://github.com/numba/numba/issues/4590

I don't have assignment privileges on GitHub, but in my heart you are now assigned to it, if that's worth anything :)
