### ISSUE TITLE
Slow performance with while loops

### ISSUE THREAD

**Issue by mavillan** [numba/numba#3031]
I was trying to figuring out why a function was running so slow in `nopython` mode, when I found that the problem were the while loops. 

Here a little example of the problem:

```python
@numba.jit(nopython=True)
def f1(n):
    s = 0
    for i in range(n):
        s += i
    return s
        
@numba.jit(nopython=True)
def f2(n):
    s = 0
    i = 0
    while i<n:
        s += i
        i += 1
    return s
```

```python
>>> tr1 = %timeit -o -n 10 f1(1e9)
259 ns ± 110 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> tr2 = %timeit -o -n 10 f2(1e9)
701 ms ± 7.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> tr2.average/tr1.average
2706442.9598301877
```

I didn't expect such a difference between `for` and `while`. `while` loops are not a supported Python feature?. In such case, why the `nopython` mode doesn't raise an error?

**Comment by stuz5000** [comment]
Is both f1 and f2, n is supplied as a float. Perhaps in f1, range downcast n to an integer, while f2 does many floating point comparisons? Could you try again with integer parameters?

**Comment by mavillan** [comment]
@stuz5000 

Your are totally right! When `n` is integer the times are similar:

```python
>>> tr1 = %timeit -o -n 10 f1(1000000000)
290 ns ± 164 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> tr2 = %timeit -o -n 10 f2(1000000000)
253 ns ± 99.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Thanks.
