### ISSUE TITLE
[0.37.0/mips,mipsel] Bus error during test

### ISSUE THREAD

**Issue by cdluminate** [numba/numba#3051]
https://buildd.debian.org/status/fetch.php?pkg=numba&arch=mipsel&ver=0.37.0-1&stamp=1521800637&raw=0

https://buildd.debian.org/status/fetch.php?pkg=numba&arch=mips&ver=0.37.0-1&stamp=1521779522&raw=0

mipsel
```
numba/tests/test_array_methods.py::TestArrayMethods::test_round_scalar PASSED [  1%]
numba/tests/test_array_methods.py::TestArrayMethods::test_sum Bus error
E: pybuild pybuild:330: test: plugin custom failed with: exit code=138: cd /<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_numba/build && python2.7 -Wd -m pytest numba/tests -v -rs
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 2.7 returned exit code 13
```

mips
```

numba/tests/test_array_methods.py::TestArrayMethods::test_round_scalar PASSED [  1%]
numba/tests/test_array_methods.py::TestArrayMethods::test_sum Bus error
E: pybuild pybuild:330: test: plugin custom failed with: exit code=138: cd /<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_numba/build && python2.7 -Wd -m pytest numba/tests -v -rs
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 2.7 returned exit code 13
```

**Comment by stuartarchibald** [comment]
Would guess this may be related to misaligned access, could even be coming from NumPy. Do not have a MIPS system to debug.

**Comment by cdluminate** [comment]
Maybe this issue has gone with newer versions of numpy: https://buildd.debian.org/status/fetch.php?pkg=numba&arch=mipsel&ver=0.42.0-1&stamp=1546854123&raw=0
I'm closing this issue as it disappeared.

**Comment by stuartarchibald** [comment]
I seem to recall that some fixes went into NumPy relatively recently that may have helped with access alignment. Thanks for confirming the issue is fixed.
