### ISSUE TITLE
[0.37.0/armel] LLVM Error during sphinx build

### ISSUE THREAD

**Issue by cdluminate** [numba/numba#3052]
https://buildd.debian.org/status/fetch.php?pkg=numba&arch=armel&ver=0.37.0-1&stamp=1521784623&raw=0

```
cp -a docs CHANGE_LOG examples .pybuild/cpython3_3.6_numba/build
http_proxy='127.0.0.1:9' /usr/share/sphinx/scripts/python3/sphinx-build -N -bhtml .pybuild/cpython3_3.6_numba/build/docs/source/ debian/numba-doc/usr/share/doc/numba-doc/html/
Running Sphinx v1.6.7
making output directory...
LLVM ERROR: Program used external function '__sync_fetch_and_add_4' which could not be resolved!
debian/rules:25: recipe for target 'override_dh_installdocs' failed
```

**Comment by stuartarchibald** [comment]
Thanks for the report, ARM support tracking is here: https://github.com/numba/numba/pull/1968

**Comment by stuartarchibald** [comment]
Following on from #3051, seems like there's still some issues https://buildd.debian.org/status/logs.php?pkg=numba&ver=0.42.0-1 but a few of these are possibly related to changes in e.g. NaT handling in NumPy 1.16. Any chance you could please do a build of Numba `0.43.1` against NumPy `1.16.<latest>` and see how that fairs? Thanks.

**Comment by cdluminate** [comment]
Well, I think we have a dependency problem before testing 0.43.1:

```
~ ❯❯❯ apt list python3-colorama -a
Listing... Done
python3-colorama/unstable,unstable,unstable,unstable,unstable,now 0.3.7-1 all [installed,automatic]
```

`0.43.1` requires `colorama >= 0.3.9` so we have to wait for a while.

**Comment by stuartarchibald** [comment]
IIRC it's not a hard dependency, if the colorama version is too low it'll just not use it? Are you finding a behaviour where there's a hard dependency?

https://github.com/numba/numba/blob/5aaf81c4605331b657778dc1d0db29ef95564b47/numba/errors.py#L93-L113

**Comment by RizzerOnGitHub** [comment]
numba is now building docs successfully on ARM (armel) with
* numba 0.48.0
* sphinx 2.4.3
* llvmlite 0.32.0
* llvm 8.0.1

see https://buildd.debian.org/status/logs.php?pkg=numba&arch=armel

I guess this bug can be closed now.

**Comment by stuartarchibald** [comment]
@RizzerOnGitHub Great, thanks for checking up on this.

**Comment by drew-parsons** [comment]
This error is showing up again now on debian experimental with python3-numba 0.52.0-4, llvm-9 1:9.0.1-20, pytest-3, in the tests for fenics-basix 0.3.0-2. You can see the result of the crash in basix build logs, https://buildd.debian.org/status/fetch.php?pkg=fenics-basix&arch=armel&ver=0.3.0-2&stamp=1632700773&raw=0

Running manually with `python3 -m pytest -vs test_numba.py` reveals the culprit,
```
LLVM ERROR: Symbol not found: __sync_fetch_and_add_4
```
