### ISSUE TITLE
Array allocation for dt64

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3058]
## Feature request

The usual ways of allocation for dt64 such as `np.empty(n, dtype=np.dtype('datetime64[ns]'))` and `np.empty(10, dtype='datetime64[ns]')` are required for parallel support.

**Comment by sklam** [comment]
You can implement `np.dtype('datetime64[ns]')` with `intrinsic` and `overload`.
See example in https://gist.github.com/sklam/c75538f86bb5899d41526ba97af2199b

**Comment by ehsantn** [comment]
Closing since this seems to be working in latest Numba.
