### ISSUE TITLE
Pickle SmartArray objects

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#3065]
SmartArray objects can't be pickled if they have an active GPU memory block.
Making them pickle'able would be a trivial addition:
```
def __getstate__(self):
    self._sync('host')
    state = self.__dict__.copy()
    state['_gpu'] = None
    return state
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Would you be interested in submitting this as a PR along with some tests? Thanks again.

**Comment by stuartarchibald** [comment]
SmartArray is deprecated as of 0.44 http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-smartarray. Closing as "wontfix".
