### ISSUE TITLE
Numba support for dict, class definitions, pandas Dataframe

### ISSUE THREAD

**Issue by RohanVardhan** [numba/numba#3074]
Is there any way I can use dict, class definitions and Pandas Dataframe in Numba?

**Comment by stuartarchibald** [comment]
Thanks for the query. At present:
* `dict`: no, but sometime in the future yes, see https://github.com/numba/numba/issues/2096.
* class definitions: some support with [`jitclass`](http://numba.pydata.org/numba-doc/latest/user/jitclass.html)
* Pandas Dataframe: no, but HPAT might help https://github.com/IntelLabs/hpat ?

**Comment by scheung38** [comment]
Hello it is end of May 2021, is this still the case? if so any plan for support it?

**Comment by esc** [comment]
@scheung38 thank you for asking about this.

* Dict support is now available: https://numba.readthedocs.io/en/stable/reference/pysupported.html#typed-dict
* Jitclass support is improving:
* For Dataframes, you now have two options:
  * https://github.com/IntelPython/sdc
  * https://bodo.ai/technology

Hope it helps!

**Comment by scheung38** [comment]
Thank you for prompt reply, 

1. Bodo.ai extends from Numba?
2. Best way to convert excel to Parquet?

**Comment by esc** [comment]
> Thank you for prompt reply,
> 1. Bodo.ai extends from Numba?

Yes.

> 2. Best way to convert excel to Parquet?

No idea, sorry.

> […](#)
> Sent from my iPhone
> On 27 May 2021, at 09:47, esc ***@***.***> wrote: ﻿ @scheung38 thank you for asking about this. Dict support is now available: https://numba.readthedocs.io/en/stable/reference/pysupported.html#typed-dict Jitclass support is improving: For Dataframes, you now have two options: https://github.com/IntelPython/sdc https://bodo.ai/technology Hope it helps! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by scheung38** [comment]
Installation between Python 3.6 to 3.7? Currently 3.9.5 is fine?

**Comment by esc** [comment]
> Installation between Python 3.6 to 3.7? Currently 3.9.5 is fine?

yes, 3.6 - 3.9 currently supported by Numba.

**Comment by scheung38** [comment]
But pip install won't work, but instead conda

**Comment by esc** [comment]
> But pip install won't work, but instead conda

Depends on the platform. What platform are you on?

> https://github.com/IntelPython/sdc
> https://bodo.ai/technology
> 
> Any differences between the two in terms of performance and user friendliness? Thanks

I haven't tried them yet, so I can not comment.

**Comment by ehsantn** [comment]
@scheung38 I'm the initial author of both but not sure about the current focus of SDC. Bodo has significant focus on user friendliness including providing comprehensive coverage of common Pandas APIs and workflows, clear error messages, documentation, tutorials and examples. On the performance side, Bodo focuses on optimizing common data analytics operations and uses MPI for parallelization (which has major advantages for analytics and machine learning). See [installation instructions](https://docs.bodo.ai/latest/source/install.html) and [getting started tutorial](https://github.com/Bodo-inc/Bodo-tutorial/blob/master/bodo_getting_started.ipynb) to get started. I'd be happy to chat in [Bodo Slack](https://join.slack.com/t/bodocommunity/shared_invite/zt-qwdc8fad-6rZ8a1RmkkJ6eOX1X__knA).

**Comment by scheung38** [comment]
@esc I am on Mac Big Sur

Not sure if Bodo also has nopython=True, nogil=True, parallel=True:

https://github.com/Bodo-inc/Bodo-tutorial/issues/18

as cannot navigate into source code

**Comment by esc** [comment]
> @esc I am on Mac Big Sur

I see, yes, then I think `conda` plus installation from the `conda-forge` channels are currently your best option.

BTW: please be aware that we are basically creating a new thread of the end of this closed issue and this is perhaps no the best and most considerate practice to follow. I think it would be best if @scheung38 @ehsantn and myself perhaps moved the conversation to our Discourse, https://numba.discourse.group/ -- what do you say?

**Comment by esc** [comment]
> > @esc I am on Mac Big Sur
> 
> I see, yes, then I think `conda` plus installation from the `conda-forge` channels are currently your best option.


Wait is this the new Apple M1 Silicon or x86_64?

**Comment by scheung38** [comment]
Yes for sure

**Comment by ehsantn** [comment]
@scheung38 Bodo sets these flags by default so it's not necessary with `@bodo.jit`. Feel free to post on Discourse as @esc suggested as well.

**Comment by scheung38** [comment]
> > > @esc I am on Mac Big Sur
> > 
> > 
> > I see, yes, then I think `conda` plus installation from the `conda-forge` channels are currently your best option.
> 
> Wait is this the new Apple M1 Silicon or x86_64?

x86_64 machine

**Comment by esc** [comment]
> > > > @esc I am on Mac Big Sur
> > > 
> > > 
> > > I see, yes, then I think `conda` plus installation from the `conda-forge` channels are currently your best option.
> > 
> > 
> > Wait is this the new Apple M1 Silicon or x86_64?
> 
> x86_64 machine

Oh, we do actually have wheels for those -- you should be able to use pip with `pip install numba` just fine on x86_64 :https://pypi.org/project/numba/#files
