### ISSUE TITLE
inconsistent behavior from numba 0.10.0 in parsing functions in ipython notebook environment

### ISSUE THREAD

**Issue by applio** [numba/numba#310]
Given the following jit'd function:

    @numba.jit('void()')
    def trial3():
        print "3"

Supplying this as input to the ipython shell (text-based) yields a callable function with the expected behavior:

    In [10]: trial3()
    3

Instead, providing the same input to the ipython notebook (browser-based) results in an  error (and hence no callable function):

      File "<unknown file>", line 2
        print "3"
                ^
    SyntaxError: invalid syntax

Yet the following is acceptable / understandable / viable in the same ipython notebook:

    In [7]:  print "3"
    
             3

Changing the print statement to `print("3")` in the jit'd function makes numba happy in the ipython notebook.

**Comment by pitrou** [comment]
Closing as outdated.

**Comment by applio** [comment]
Confirmed that using numba 0.17.0 in an iPython 3.0.0 notebook, the behavior matches that seen in the iPython REPL, addressing the issue.

I even like the the warning triggered by this example:  "RuntimeWarning: Python2 style print partially supported.  Please use Python3 style print."  Happily, the above example still works with its python2-style print statement but the warning message really is a nice touch.
