### ISSUE TITLE
Add np.asarray support

### ISSUE THREAD

**Issue by seibert** [numba/numba#3114]
It would be nice to have np.asarray, which is a common idiom at the start of functions that can take lists or NumPy arrays.  In the case of a NumPy array, Numba can make asarray a no-op, and in the case of a list, we can allocate a view on the list contents (assuming the list element type maps to a NumPy dtype).

(This came from SciPy 2018 sample code.)

**Comment by vyasr** [comment]
The relevant code snippets can be found in the rowan package at https://bitbucket.org/glotzer/rowan/src

**Comment by stuartarchibald** [comment]
Implemented here: https://github.com/numba/numba/pull/3598 closing.
