### ISSUE TITLE
np.norm axis support

### ISSUE THREAD

**Issue by vyasr** [numba/numba#3116]
Following up on issues #3114 and #3115, another function that is not yet implemented is the axis argument to numpy.norm. The ability to specify an axis can be useful when computing norms over high-dimensional arrays. To see how it might be used, see the file rowan/functions in the [rowan repository](https://bitbucket.org/glotzer/rowan/src)

**Comment by stuartarchibald** [comment]
Thanks, this is a duplicate of https://github.com/numba/numba/issues/2558 (assuming `np.linalg.norm` is meant?)?

**Comment by vyasr** [comment]
Yes you are right. Feel free to close this one, I just added a few in bulk when I was discussing with Stan and the others didn't appear to have prior issues, so I didn't check this one. Thanks!

**Comment by stuartarchibald** [comment]
Great, thanks :)
