### ISSUE TITLE
min/max behaves incorrectly on 0-size array

### ISSUE THREAD

**Issue by ZeppLu** [numba/numba#3119]
Consider the following code:
```python
In [324]: def test_0d_min(X):
     ...:     return np.min(X)
     ...:
     ...:

In [325]: test_0d_min(np.array([]))  # correct behavior
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
... (omitted)
ValueError: zero-size array to reduction operation minimum which has no identity

In [326]: nb.jit(test_0d_min)(np.array([]))  # incorrect
Out[326]: 0.0

In [328]: nb.jit(test_0d_min, parallel=True)(np.array([]))  # incorrect
Out[328]: 1.7976931348623157e+308
```

I guess that parallelization for reduction functions is done by calculating each block seperately and then combining them together, so an identity element is used as the initial result of each block. `np.finfo(np.float64)` shows that `1.7976931348623157e+308` is exactly the largest `np.float64` instance, which seems suitable as an identity element of `np.min`.

But actually reduction function (aka folding) and identity element are both defined over binary functions, while min function is obviously an n-ary function (a function that accepts down to 0, up to n arguments) mathematically.

As for non-parallel version of jitted function, I have no idea why it computes to 0.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is just a simple omission in the Numba re-implementation of `np.min`, seems like `np.max`, `np.argmin` and `np.argmax` all suffer similar issues. Your assertion about how `np.min` is working under parallelised reduction is correct. The `parallel` target should just replicate NumPy too. Fix is here: https://github.com/numba/numba/pull/3124

As to why the non-parallel jitted function produces 0, it's a bug in Numba `nditer`, https://github.com/numba/numba/issues/3123.
