### ISSUE TITLE
Feature request `np.fill_diagonal`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3121]
Following on from: https://github.com/numba/numba/issues/3117

Feature request for `np.fill_diagonal` support.

**Comment by rjenc29** [comment]
Hi - I'd be happy to pick up `np.fill_diagonal` support & will open a PR over the weekend if no one else has already done so.
Cheers
Rob

**Comment by stuartarchibald** [comment]
Hi @rjenc29,

I don't believe anyone has picked this ticket up yet, a PR would be very welcome.

Thanks :)

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/3145
