### ISSUE TITLE
 numba acceleration not working in python-sgp4

### ISSUE THREAD

**Issue by sklam** [numba/numba#3141]
A user at scipy sprint pointed out this numba issue:

https://github.com/brandon-rhodes/python-sgp4/issues/18

**Comment by stuartarchibald** [comment]
Closing this as the upstream issue is closed and there's no reproducer.

**Comment by astrojuanlu** [comment]
xref https://github.com/brandon-rhodes/python-sgp4/issues/46 upstream issue was closed because the numba implementation was problematic (not necessarily numba's fault, adding this just for context)
