### ISSUE TITLE
[Question] Would it be possible to support larger step size in `prange`?

### ISSUE THREAD

**Issue by ZeppLu** [numba/numba#3144]
I noticed that `numba.prange` in `parallel=True` accepts `step=1` only, but it would be extremely useful to have a larger step size (so functions like `all`, `min` can be performed along specific axis by specifying step size larger than 1)

**Comment by stuartarchibald** [comment]
ping @DrTodd13 @ehsantn

**Comment by ehsantn** [comment]
I think the restriction mainly comes from the threading backend. @DrTodd13 ?

**Comment by DrTodd13** [comment]
In our internal representation, we do have a "step" parameter and we've tried to plan ahead for it a bit but we've never had much demand for it and so it has never been implemented.  I wouldn't think that the backend is much of an issue.  I'd be more worried about array analysis and fusion.

In short, I think everyone would like to see this feature added eventually.  The question is when will someone have the cycles to do it.
