### ISSUE TITLE
calling cuda math functions (eg. sincospi)

### ISSUE THREAD

**Issue by fzimmermann89** [numba/numba#3149]
Hello,

I am wondering how to add cuda sdk functions to the cuda backend or how to call them directly

Currently I am interested in sincospi
` void @__nv_sincospi(double %x, double* %sptr, double* %cptr) `
https://docs.nvidia.com/cuda/libdevice-users-guide/__nv_sincospi.html#__nv_sincospi

There are two issues: 
- The function doesn't have a python math equivalent
- The results are not returned but two output pointers are used

In the gitter chat, @seibert  already gave the following hints:
```
- make a Python function that does the same thing on the CPU (fast/slow doesn't matter) in the numba.cuda subpackage
- register that Numba can compile that function in CUDA (https://github.com/numba/numba/blob/master/numba/cuda/cudamath.py)
- implement that function as a call to the libdevice function (https://github.com/numba/numba/blob/master/numba/cuda/libdevice.py)
```
and asked me to create an issue here.

Thanks,
Felix

**Comment by sklam** [comment]
I'd suggest using https://github.com/numba/numba/pull/2824 as an example and see how it implemented `numba.cuda.brev`.

**Comment by sklam** [comment]
As for the output pointers, i'd suggest that is dealt with internally by the codegen.  In the user level, the function should return a tuple of two numbers.

**Comment by stuartarchibald** [comment]
Closing, as answers are provided. If this isn't clear/more information is needed, perhaps open a motivating PR for discussion?
