### ISSUE TITLE
Structured dtypes with multi-dim fields: numba either throws or crashes

### ISSUE THREAD

**Issue by aldanor** [numba/numba#3158]
Given this (quite trivial) example:

```python
dtype1 = np.dtype([('a', 'i8'), ('b', 'i4')])
dtype2 = np.dtype((dtype1, (2, 2)))
dtype3 = np.dtype([('x', '?'), ('y', dtype2)])
arr = np.zeros(2, dtype3)

@numba.jit(nopython=True)
def foo(arr):
    return arr[0]

foo(arr)
```

numba will most likely throw like so:

```
.../numba/types/npytypes.py in __init__(self, dtype, shape)
    419 
    420     def __init__(self, dtype, shape):
--> 421         assert dtype.bitwidth % 8 == 0, \
    422             "Dtype bitwidth must be a multiple of bytes"
    423         self._shape = shape

AttributeError: 'Record' object has no attribute 'bitwidth'
```

... or you could also get

```
SystemError: 
CPUDispatcher(<function foo at 0x7f7741382d08>) returned NULL without setting an error
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce the raised `AttributeError`, no luck with reproducing the `SystemError` as yet. This is clearly a bug.

**Comment by kazhoyan** [comment]
This bug occurs in much simpler cases:
```
Item = np.dtype([('some_field', np.int32)])
SomeList = np.dtype([('items', Item, 10)])
```

Accessing `items` property of an instance of `SomeList` crashes with this message:
`'Record' object has no attribute 'bitwidth'`

A quick fix is to replace `NestedArray.size`'s body inside `npytypes.py` with something like this:
```
        if isinstance(self.dtype, Record):
            return self.dtype.size
        else:
            return self.dtype.bitwidth // 8
```

P.S. I would increase this bug's priority - it seems like a fairly common situation.

**Comment by stuartarchibald** [comment]
@kazhoyan thanks, this is an exact reproducer:
```python
from numba import njit
import numpy as np

Item = np.dtype([('some_field', np.int32)])
SomeList = np.dtype([('items', Item, 10)])

arr = np.zeros((2,), SomeList)

@njit
def foo(x):
    x[0]

foo.py_func(arr)
foo(arr)
```
Pull Requests to fix/promote discussion around such issues are welcomed.

**Comment by shash29-dev** [comment]
This still open? 
Any solution till now?

**Comment by stuartarchibald** [comment]
> This still open?

Yes, still reproduces on 0.54.

> Any solution till now?

Not that I'm aware of I'm afraid.

**Comment by gmarkall** [comment]
xref / possible duplicate: #1469
