### ISSUE TITLE
Unable to use jit python function to numba with roctools

### ISSUE THREAD

**Issue by extraymond** [numba/numba#3173]
## Reporting a bug

- [O] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [O] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

---

Hi! I've try to use the new roctool to jit python functions with numba, the code is as simple as below:

```python

@roc.jit(device=True)
def simple_add(a, b):
    return a + b

%timeit simple_add(1,2)
```

However, the error says:

```
----> 1 simple_add(1,2)

TypeError: 'DeviceFunctionTemplate' object is not callable
```

My system setup:

1. OS: ubuntu 18.04 64bit (Kernel 4.15)
2. Numba and roctools: is done via the numba conda channel.
3. ROCM: 1.8.1 

Any help would be appreciated! Thx.

**Comment by stuartarchibald** [comment]
Thanks for the report. Really pleased you are trying out this new target architecture, thanks!!! I'm almost done with a first round of documentation updates for this target so some more relevant documentation should be available soon. In the meantime, here are two key points:

*  kernels cannot explicitly return a value; all result data must be written to an array passed to the function (if computing a scalar, you will probably pass a one-element array);
*  kernels explicitly declare their thread hierarchy when called: i.e. the number of workgroups and the number of workitems per workgroup (note that while a kernel is compiled once, it can be called multiple times with different workgroup sizes or grid sizes).


As with the CUDA implementation, you cannot call a device function directly, you have to call it from a kernel. Here is an example:
```python
from numba import roc
import numpy as np


@roc.jit
def kernel(an_array):
    # workitem id in a 1D workgroup
    tx = roc.get_local_id(0)
    # workgroup id in a 1D grid
    ty = roc.get_group_id(0)
    # workgroup size, i.e. number of workitem per workgroup
    bw = roc.get_local_size(0)
    # Compute flattened index inside the array
    pos = tx + ty * bw
    # The above is equivalent to pos = roc.get_global_id(0)
    if pos < an_array.size:  # Check array boundaries
        an_array[pos] = simple_add(1, pos)



@roc.jit(device = True)
def simple_add(a, b):
    return a + b

n = 16
x = np.zeros(n)

kernel[1, n](x)

print(x)
```
this should print:
```
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
```

As this is a new target architecture, if it is easier to debug things over real time chat, we are on [gitter.im](https://gitter.im/numba/numba).

Thanks.

**Comment by stuartarchibald** [comment]
Added example in https://github.com/numba/numba/pull/3178. Closing.
