### ISSUE TITLE
Is numpy.random thread-safe in no-gil mode

### ISSUE THREAD

**Issue by leezu** [numba/numba#3183]
According to https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

> The generator is not thread-safe when releasing the GIL.
> 
> Also, under Unix, if creating a child process using os.fork() or the multiprocessing module, the child’s random generator will inherit the parent’s state and will therefore produce the same sequence of numbers (except when using the “forkserver” start method under Python 3.4 and later).

However, the Python random generator is thread-safe when releasing the GIL (at least nothing contradictory is mentioned on https://numba.pydata.org/numba-doc/dev/reference/pysupported.html ). As both seem to share most of the implementation, @seibert suggested that the information on the numpy page might be wrong.

**Comment by stuartarchibald** [comment]
AIUI *both* RNG states are held in TLS, hence the state itself is threadsafe:
https://github.com/numba/numba/blob/e2c903d7ff6e08ac97181ab43a389e19e639e4f3/numba/_random.c#L108-L122

and the TLS states are reset to `uninitialized` on `fork(1)` by virtue of calling this init routine:
https://github.com/numba/numba/blob/e2c903d7ff6e08ac97181ab43a389e19e639e4f3/numba/_helpermod.c#L240

at import time for the rng module:
https://github.com/numba/numba/blob/e2c903d7ff6e08ac97181ab43a389e19e639e4f3/numba/targets/randomimpl.py#L19

which also installs `pthread_atfork` handlers:
https://github.com/numba/numba/blob/e2c903d7ff6e08ac97181ab43a389e19e639e4f3/numba/_random.c#L152-L178

which is sufficient condition that when a `numba_get_FOO_random_state` call is made (in `get_state_ptr`), the initialization sequence will run again in the fork:
https://github.com/numba/numba/blob/e2c903d7ff6e08ac97181ab43a389e19e639e4f3/numba/targets/randomimpl.py#L50-L65

So I think the docs need updating to reflect that both the Python and NumPy RNG implementations are fork and threadsafe. I welcome being corrected if I've interpreted this wrong.

Also, for reference 088755f is the patch to the docs for declaring the Python random as fork/threadsafe, went in in PR https://github.com/numba/numba/pull/2883
