### ISSUE TITLE
Support for numpy.partition

### ISSUE THREAD

**Issue by orenbenkiki** [numba/numba#3185]
I have code which looks for the top-3 values in an array, by saying: `-numpy.partition(-data, 3)[0:3]`.

Numba (version 0.39) refused to jit it, saying `Unknown attribute 'partition' of type Module(<module 'numpy' from '... path to numpy ...'>)`.

I can make the code work using a full `numpy.sort` instead of `numpy.partition`, but that makes it run slower.

Is it possible to get `numba` to invoke `numpy.partition` inside jit-ed code?

**Comment by stuartarchibald** [comment]
Thanks for the suggestion. I've added this as a feature request. If you'd like to contribute, the high level Numba extension API `@overload` decorator should get you on the way to implementing this for Numba. Docs are [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions). A lot of example uses are in ['numba/targets/arraymath.py'](https://github.com/numba/numba/blob/master/numba/targets/arraymath.py#L491). Thanks.

**Comment by stuartarchibald** [comment]
Implemented here: https://github.com/numba/numba/pull/3320 closing.
