### ISSUE TITLE
__cuda_array_interface__ not working as expected with Pytorch tensors

### ISSUE THREAD

**Issue by themightyoarfish** [numba/numba#3192]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer

Not sure if this is a stupid issue, but I had hoped that properly adding an `____cuda_array_interface__` dict to a Pytorch `Tensor` would allow me to convert between numpy, pytorch and numba arrays. However, this is not true.

```
import unittest
import numpy as np
np.random.seed(0)
import torch
import numba.cuda as cuda


def typestr(tensor):
    import sys
    endianness = '<' if sys.byteorder == 'little' else '>'
    types = {
        torch.float32: 'f4',
        torch.float: 'f4',
        torch.float64: 'f8',
        torch.double: 'f8',
        torch.float16: 'f2',
        torch.half: 'f2',
        torch.uint8: 'u1',
        torch.int8: 'i1',
        torch.int16: 'i2',
        torch.short: 'i2',
        torch.int32: 'i4',
        torch.int: 'i4',
        torch.int64: 'i8',
        torch.long: 'i8'
    }
    return endianness + types[tensor.dtype]

class TestPTNumba(unittest.TestCase):

    def test_conversion(self):
        array = np.random.rand(5, 5)
        tensor = torch.tensor(array).cuda()
        cai_dict = {
            'shape': tuple(tensor.shape),
            'data': (tensor.data_ptr(), True),
            'typestr': typestr(tensor),
            'version': 0,
            'strides': tensor.stride(),
            'descr': [('', typestr(tensor))]
        }
        setattr(tensor, '__cuda_array_interface__', cai_dict)
        device_array = cuda.as_cuda_array(tensor)
        self.assertTrue(np.allclose(device_array.copy_to_host(None), array))


if __name__ == '__main__':
    unittest.main()
```

It can be seen from inspecting the `device_array` that some data is properly accessible, with a lot of zeros in between or wrong ordering. Is this expected behaviour?

**Comment by themightyoarfish** [comment]
Turns out `tensor.strides()` is not in bytes but in unit of `element_size`.

**Comment by seibert** [comment]
This might be a mistake on our part in trying to copy the spec.  @sklam: can you check this?

**Comment by seibert** [comment]
OK, confirmed that the stride should be in units of bytes.  Sorry about the false alarm.  Closing...
