### ISSUE TITLE
Instantiate default arguments for extension functions early in the pipeline

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3201]
## Feature request

Seems like the dispatcher and the lowering backend are able to handle default arguments. However, default arguments of functions with nopython extensions are not instantiated in the IR early in the pipeline. This would help transformation passes have a simpler implementation without handling all possible combinations explicitly.

I've looked at `pysignature` and `typing.fold_arguments` tools but could find a way.

This seems related to previous issues like #1154 but not quite the same.

**Comment by stuartarchibald** [comment]
NOTE: This issue could do with a reproducer.

**Comment by esc** [comment]
@ehsantn would you like to add a reproducer to this? Or can we perhaps close it? I am asking because this issue was picked up by our internal scanner for 'stale' issues. Thanks!

**Comment by ehsantn** [comment]
Sure, I'll create a reproducer. I believe this is an important feature for writing compiler passes more easily and shouldn't be forgotten :)

**Comment by ehsantn** [comment]
I reviewed the specific use cases and seems like helper functions are mostly good enough, so this is not worth a disruptive change in Numba. Closing.

**Comment by esc** [comment]
@ehsantn great, thanks for following up!
