### ISSUE TITLE
Double `while True` loop causes strange errors

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#3214]
Answering the following question on stackoverflow, I think I found a strange bug in Numba (using 0.39.0 on python 3.6.5):

https://stackoverflow.com/q/51795538/392949

There the code just gets stuck in an infinite loop, but a simpler example suffers from other strange errors.

A simple reproducible example. The following will throw a strange error:

```python
@nb.njit
def test(obs):
    L = obs.shape[0]
    i = 0
    a = 1
    b = 0
    
    while True:
        while True:
            if i == L - 1:
                break
            i += 1
        i += 1
        if i >= L:
            break

    return i, L
```

and running it:

```
obs = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=np.int64)

test(obs)
```

gives:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-80c342766a9d> in <module>()
      1 obs = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=np.int64)
      2 
----> 3 test(obs)

TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type
```

If you get rid of the array argument, you get a different error:

```
@nb.njit
def test():
    L = 10  #obs.shape[0]
    i = 0
    a = 1
    b = 0
    
    while True:
        while True:
            if i == L - 1:
                break
            i += 1
        i += 1
        if i >= L:
            break

    return i, L
```

and running:

```
test()
```

gives:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-fbd55f77ab7c> in <module>()
----> 1 test()

RuntimeError: missing Environment
```

while the following (changing the second `while True` to `while a > b`), runs as expected:

```
@nb.njit
def test(obs):
    L = obs.shape[0]
    i = 0
    a = 1
    b = 0
    
    while True:
        while a > b:
            if i == L - 1:
                break
            i += 1
        i += 1
        if i >= L:
            break
    return i, L
```

**Comment by sklam** [comment]
This is caused by a mishandling of the `POP_BLOCK` python bytecode when `while <constant>` is used.  Python will put a `JUMP` right before the `POP_BLOCK` causing numba to not seeing the `POP_BLOCK`.  This leads the later `break` jumping back into the inner-loop, causing numba to emit an infinite-loop with no side-effect, which is an undefined behavior to LLVM.  The optimizer in LLVM then messes up the function further causing bizarre error messages.
