### ISSUE TITLE
Allowing object type in numba jit signature

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#3218]
It would be nice to be able to include a generic Python `object` type in a Numba `jit` function signature much like the case below.

```python
from numba import jit
  
@jit(["object(int, float)"])
def test(a, b):
    return (a, b)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Does this help?

```python
from numba import jit

@jit(["pyobject(intc, float64)"])
def test(a, b):
    return (a, b)

print(test(3, 4.2))
```

**Comment by stuartarchibald** [comment]
It's also possible to construct signatures from the types themselves, for example:
```python
from numba import jit, types

@jit([types.pyobject(types.intc, types.float64)])
def test2(a, b):
    return (a, b)

print(test2(3, 4.2))
```

**Comment by jakirkham** [comment]
Ah ok. Thanks. That does help. 😄

Also sorry about the `int` vs. `intc` bit. Got a little confused by that initially.

FWIW was looking for this on the [types doc page]( https://numba.pydata.org/numba-doc/dev/reference/types.html ), but missed it.

Feel free to close.

**Comment by stuartarchibald** [comment]
No worries. Seems like `pyobject` isn't mentioned on that page and it probably ought to be! Will add a ticket to update. Thanks.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/issues/3219
