### ISSUE TITLE
Passing scalars by reference

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#3220]
Think this is a feature request. Though it could be I've just missed something. So pointers welcome. :)

It would be nice to be able to pass scalars by reference. The value being if they need to be updated within the function in question. This is particularly useful if multiple values need to be returned from a function (and one would like to use `njit`). Here's a simplistic example (`&` signifying the value to pass by reference) where `b`'s value should be equivalent to a type cast version of `a`'s.

```python
from numba import jit

@jit("void(intc, float64&)")
def make_float(a, b):
    b = float(a)
```

One workaround that I came up with is to simply make the reference object a 1-D scalar array (as shown below).

```python
from numba import jit

@jit("void(intc, float64[::1])")
def make_float(a, b):
    b[0] = float(a)
```

This seems to work ok. Though maybe there are better options that I'm unaware of.

**Comment by seibert** [comment]
Yeah, we've struggled with how to represent the syntax for this.  When calling from the Python interpreter into nopython mode, there's no way to make pass by reference work unless we define our own scalar object types.  (Python numeric objects are immutable.)  If we created special syntax for pass by reference of scalars, it could only be used between nopython mode functions and would fail to work if the JIT was turned off, which is something we generally try to avoid.

That said, tuples are supported in nopython mode, so those are generally the preferred choice if you need to return more than one scalar value from a function, and a NumPy array is not appropriate.

**Comment by jakirkham** [comment]
Yeah I can see why this would be tricky.

Interesting, was not aware tuples were still valid. Will stick with tuples then. Are they being represented by some sort of C struct-like object or similar in LLVM?

**Comment by seibert** [comment]
Yeah, Numba turns them into a struct (each element can be a different type), and then LLVM can do whatever it wants with the representation during optimization.  (A function returning a tuple that is inlined might see the struct optimized away completely, as the scalar components are used directly.)

**Comment by jakirkham** [comment]
Thanks for the clarification.

What about the case of CUDA kernels?

**Comment by seibert** [comment]
Tuples should work there as well.

**Comment by jakirkham** [comment]
Ok, but not as a returned type, right?

**Comment by seibert** [comment]
In `device=True` functions (GPU functions called from GPU code), tuples should be fine.  CUDA kernels (call from the host, run on the GPU) do not support return values at all.  In those cases, you do still have to pass a NumPy array, or a CUDA device array as a function argument.

**Comment by seibert** [comment]
Closing this issue for now.  Syntactically, representing mutable scalars as length 1 arrays is about as good as it gets for Python.  (No way to overload assignment.)
