### ISSUE TITLE
Make ROCm device wavesize and wavebits into compile time constants

### ISSUE THREAD

**Issue by seibert** [numba/numba#3232]
(Feedback from AMD user)
At several points in the examples, globals are created for WAVESIZE and WAVEBITS:

https://github.com/numba/roc-examples/blob/master/numba_roc_examples/reduction/reduction.py#L7
https://github.com/numba/roc-examples/blob/master/numba_roc_examples/radixsort/roc_scan.py#L5
https://github.com/numba/roc-examples/blob/master/numba_roc_examples/kerneldensity/roc_imp.py#L17

These are in principle properties of the device, and should probably be constants in the `numba.roc` module that can be used directly without the user needing to define them.

**Comment by seibert** [comment]
Reopening because #3280 is only part of the solution.  The ultimate goal is to not have WAVESIZE need to be defined by the user as a global constant to use it in their kernel.  For example, we would want this to work:

```
@roc.jit(device=True)
def shuffle_down(val, width):
    tid = roc.get_local_id(0)
    roc.wavebarrier()
    idx = (tid + width) % roc.wavesize
    res = roc.ds_permute(idx, val)
    return res
```
Where `roc.wavesize` becomes `64` (or whatever the value needs to be) at kernel compile time.  This is similar to how `cuda.warpsize` works.

**Comment by stuartarchibald** [comment]
Closing due to https://github.com/numba/numba/pull/6991
