### ISSUE TITLE
lowering error

### ISSUE THREAD

**Issue by gregconner** [numba/numba#3238]
The very short code:
------------------------
from numba import jit

def p(x):
    return

@jit()
def minimalreproducer():
    p(lambda : False)

minimalreproducer()
-------------------------
Gives this error:

Traceback (most recent call last):
  File "minimalreproducer.py", line 11, in <module>
    minimalreproducer()
  File "/anaconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 360, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed at object (object mode backend)
make_function(closure=None, code=<code object <lambda> at 0x10e0a0430, file "minimalreproducer.py", line 8>, name=None, defaults=None)

File "minimalreproducer.py", line 8:
def minimalreproducer():
    p(lambda : False)
    ^
[1] During: lowering "$0.3 = make_function(closure=None, code=<code object <lambda> at 0x10e0a0430, file "minimalreproducer.py", line 8>, name=None, defaults=None)" at minimalreproducer.py (8)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

**Comment by stuartarchibald** [comment]
Thanks for the report. Unfortunately returning a function is unsupported in Numba. In Numba 0.40.0dev (development version for the upcoming 0.40.0 release), Numba has been patched (in https://github.com/numba/numba/pull/3059) against this somewhat confusing message to do the following:

The code:
```python
from numba import jit

def p(x):
    return

@jit()
def minimalreproducer():
    p(lambda : False)

minimalreproducer()
```
Running it:
```
$ python issue3238.py 
Traceback (most recent call last):
  File "issue3238.py", line 10, in <module>
    minimalreproducer()
  File "<path>/numba/numba/dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "<path>/numba/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in object mode pipeline (step: ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context: <lambda> (op code: make_function not supported). If the feature is explicitly supported it is likely that the result of the expression (<lambda>) is being used in an unsupported manner.

File "issue3238.py", line 8:
def minimalreproducer():
    p(lambda : False)
    ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
```

**Comment by gregconner** [comment]
The code doesn’t return a function (or anything for that matter), although it does pass one.  I will be surprised if passing functions isn’t supported since many algorithms (sorts for instance) depend on it.

**Comment by stuartarchibald** [comment]
Yes apologies, I've got to stop seeing `make_function` and just assuming it's a returned function :) (because it commonly is!).

What is happening is that because `p` is defined without the `@jit` decorator Numba sees it as a Python function so has drop back to using the `object` mode compilation, hence it failing in that mode (more about compilation modes [here](http://numba.pydata.org/numba-doc/dev/user/5minguide.html#what-is-nopython-mode)). Irrespective of this, the manner in which `lambda` is being used is not supported.

Here's a quick digest of things that work surrounding what you are trying:
```python
ffrom numba import jit, njit

@njit
def p(x):
    return x * 2

@njit
def q(x, arg):
    return x(arg) * 2

glambda = njit(lambda x: x + 10)

@njit
def minimalreproducer():
    k = lambda : False
    def closure(t):
        return t - 7

    print(p(31))           # Fine, calling another jit/njit function
    print(k())             # Fine, calling a local lambda
    print(glambda(20))     # Fine, calling a jitted global lambda
    print(closure(20))     # Fine, closures are inlined.
    print(q(glambda, 3))   # Fine, jitted functions can take other jitted functions as arguments

    #p(k)       # Will fail, passing or returning a locally defined function is unsupported
    #p(closure) # Will also fail due to the above

minimalreproducer()
```

**Comment by gregconner** [comment]
Thanks a lot for the explanation!  However, it looks like I really might have found a bug, since in my original code I was passing a nonlocal function to another function.  The whole lambda thing was due to trying to find the most minimal of minimal examples.  I’ll respond when/if I find another minimal example that still breaks things but disagrees with the excellent digest you gave.

**Comment by seibert** [comment]
Closing issue for now.  Please reopen if you find another failing example.
