### ISSUE TITLE
BUILD_LIST_UNPACK opcode is not supported.

### ISSUE THREAD

**Issue by sklam** [numba/numba#3240]
`BUILD_LIST_UNPACK` opcode is not supported.  I don't know if we can support it.  But, it can show up on py3.5 with source code like `fn(1, *a, *b)` (see https://github.com/numba/numba/pull/3211/commits/b5d3d60d5e57450b124348346aec95f86237e720).  However, it will run fine on 3.6 due to new opcode.

**Comment by stuartarchibald** [comment]
Closing, referred to test works on mainline for upcoming 0.55 release.
```python
from numba import njit
import numpy as np

def check(p):
    # using eval here since Python 2 doesn't even support the syntax
    @njit
    def inner(*args):
        return args
    pyfunc = eval("lambda a: inner(1, *a, *(1, 2), *a)", locals())
    cfunc = njit(pyfunc)
    assert cfunc(p) == pyfunc(p)
# Homogeneous
check((4, 5))
# Heterogeneous
check((4, 5.5))
```
