### ISSUE TITLE
`import imp` causing DeprecationWarning

### ISSUE THREAD

**Issue by waderoberts123** [numba/numba#3248]
So when I turn the simplefilter to default, I get an error when running the following command:

`from numba import njit, prange`

The error is this:

`DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses import imp`

The traceback file is this one:

`numba\serialize.py:7`

**Comment by stuartarchibald** [comment]
Thanks for the report. Another user has contributed the start of a patch against this here https://github.com/numba/numba/pull/3237. Will try and get it into the 0.40 release.

**Comment by seibert** [comment]
#3237 has been merged, so closing this issue.
