### ISSUE TITLE
ppc64le sporadic fail for `test_power_array_op`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3252]
On `ppc64le` this is an intermittent failure of the test:
```
numba.tests.test_ufuncs.TestArrayOperators.test_power_array_op
```
looks like a wrap around problem with `int32` arrays (`INT_MAX` expected, got `-INT_MAX - 1`).

**Comment by seibert** [comment]
The intermittency of the failure is likely due to the input test arrays being randomly generated.

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/4557. Closing
