### ISSUE TITLE
`numba -s` should show total cores and available cores

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3253]
As title.

**Comment by seibert** [comment]
What counts as "available cores"?

**Comment by stuartarchibald** [comment]
Those which the user/program has permission to use? Thinking of `taskset(1)`/`cpuset(7)` etc based restrictions and affinity etc.

**Comment by seibert** [comment]
Is this motivated by the Binder notebook examples?  I found if you dig into the Kubernetes settings, the Jupyter kernel container is only give 1 CPU "share" to work with, despite there being 16 CPUs visible to the container.  If one of these calls can extract this CPU limit (which I don't know how to query from inside the container), that would be very useful.

**Comment by stuartarchibald** [comment]
That is the motivation, performance looked unusual so I ran `numba -s` to see what was on the machine binder was running on and the thing I wanted to know (CPU count information) hasn't been implemented. The containerized information should be available from `/proc/` and looking for the cpu constraints. e.g.
```python
In [69]: ['0x'+x.replace('Cpus_allowed:\t','') for x in open('/proc/self/status').read().splitlines() if x.startswith('Cpus_allo
    ...: wed:')]
Out[69]: ['0xf']
```
I have 4 CPUs locally, 0xf is 4 bits set.

**Comment by stuartarchibald** [comment]
Seems not to work on kubernetes, wonder what its using underneath to apply the restriction?

**Comment by seibert** [comment]
Poking around a bit more, it looks like you can find it in sysfs:

https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt

On Binder, this represents 1 CPU share, although there are 8 CPUs:
```
jovyan@jupyter-numba-2dnumba-2dexamples-2d6gn95l42:~$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
100000
jovyan@jupyter-numba-2dnumba-2dexamples-2d6gn95l42:~$ cat /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
100000
```
