### ISSUE TITLE
jitclass scalars always stored as 64-bit type

### ISSUE THREAD

**Issue by f-i-s-h-y** [numba/numba#3264]
## Reporting a bug

I would have expected that numba.typeof() would return the pre-assigned type (in spec), but instead all these scalars are returned as their 64-bit versions.

```python
import numba as nb
from numba import jitclass          # import the decorator
from numba import int16, int32, int64, float32, float64    # import the types

spec = [
    ('intvalue1', int16),
    ('intvalue2', int32),
    ('intvalue3', int64),
    ('floatvalue1', float32),
    ('floatvalue2', float64),
]

@jitclass(spec)
class Bag(object):
    def __init__(self, intvalue, floatvalue):
        self.intvalue1 = intvalue
        self.intvalue2 = intvalue
        self.intvalue3 = intvalue
        self.floatvalue1 = floatvalue
        self.floatvalue2 = floatvalue

b = Bag(2, 2.0)

print(nb.typeof(b.intvalue1)) # int64
print(nb.typeof(b.intvalue2)) #int64
print(nb.typeof(b.intvalue3)) #int64
print(nb.typeof(b.floatvalue1)) # float64
print(nb.typeof(b.floatvalue2)) # float64
```

**Comment by seibert** [comment]
If you augment those print statements to print the Python type of the return value, you'll see why:
```
<type 'int'>
int64
<type 'int'>
int64
<type 'int'>
int64
<type 'float'>
float64
<type 'float'>
float64
```
Scalars are returned from functions back to the Python interpreter as Python object (`int` and `float`) which are always 64-bit.

Being able to control whether things are returned as Python scalars or NumPy scalars is a possible feature flag, but we would need to think about the implications.

**Comment by f-i-s-h-y** [comment]
that explains why it does show the correct bitwidths if I do this with arrays, thanks for the clarification!
