### ISSUE TITLE
How to get the progress of the execution

### ISSUE THREAD

**Issue by rtmatx** [numba/numba#3268]
Hi,

I am using numba on a method which has lot of independent for loops with in a loop. How to find the progress of the execution i.e to see until which point has the code been executed. I used to use python print method but since that is not available in `nopython=True` mode, is there any other way to monitor the progress of the code 

Thanks

**Comment by synapticarbors** [comment]
While this is probably more appropriate for the mailing list than the issue tracker, I just wanted to note that you can use the `print()` function in `nopython` mode (http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#built-in-functions). If you are using python2, you need to add `from __future__ import print_function` to the top of your file, and then you can use `print` -- for example:

```
@nb.jit(nopython=True)
def func(N):
    for i in range(N):
        print('loop #: ', i)
```

**Comment by rtmatx** [comment]
Thanks @synapticarbors . I tried to use `print` method but using `f-strings` in python. I am used the original method and it works fine now. So I am closing this thread. Thanks for the help.

**Comment by seibert** [comment]
As a general note, #3166 will move Numba toward support for temporarily leaving nopython mode to run a block of arbitrary code.  This will allow a wider range of callback options, like calling progress bar libraries or notebook widget updates.
