### ISSUE TITLE
"Numba requires at least version 0.25.0 of llvmlite." (current is 0.24)

### ISSUE THREAD

**Issue by hippke** [numba/numba#3271]
I try to run Numba 0.39 on MacOS X 10.9, Python 3.7 64-bit. When importing numba, I get this:
```
ImportError: Numba requires at least version 0.25.0 of llvmlite.
Installed version is 0.24.0.
Please update llvmlite.
```
My version is 0.24 [which is the latest.](http://llvmlite.pydata.org/en/latest/release-notes.html)
What's wrong here? Thanks for your help.

**Comment by stuartarchibald** [comment]
Thanks for the report. Are you using conda? If so, what version of Numba do you have according to `conda list`. For example I have:
```
numba                     0.40.0.dev0+95.g8c3d562           <pip>
```
because I'm on the 0.40.0dev0 series and installed manually!

**Comment by AlexPnt** [comment]
I experienced the same error:

```
ImportError: Numba requires at least version 0.26.0 of llvmlite.
Installed version is 0.25.0.
Please update llvmlite.
```

The most recent is 0.25.0.

**Comment by stuartarchibald** [comment]
@AlexPnt are you working off a development version of Numba? If so, the llvmlite dependency was recently updated to 0.26 for working towards the next release. You can get the latest `llvmlite` version from the Numba channel with:
```
$ conda install -c numba llvmlite
```

**Comment by stuartarchibald** [comment]
Presume this is resolved. Closing.

**Comment by xGeorge1234** [comment]
ImportError: Numba requires at least version 0.38.0 of llvmlite.
Installed version is 0.36.0.
Please update llvmlite.

How can i update to the latest version?

**Comment by stuartarchibald** [comment]
@xGeorge1234 it's possible to update using `conda` with `conda update <package>` or `pip` with `pip install <package> --upgrade` where `<package>` is e.g. `llvmlite` or `numba`. However it might be better to just create a new environment and install the versions of numba/llvmlite you need into that to ensure that you definitely get the versions you want.
