### ISSUE TITLE
Create Array of Dates in Numba?

### ISSUE THREAD

**Issue by jsphon** [numba/numba#3276]
I would like to create an array of dates in a Numba function, running in nopython mode.

I can't see a date type, so I am trying NPDatetime.

My attempted code is:

    import numba as nb
    import numpy as np
    
    
    @nb.jit(nopython=True)
    def xxx():
        return np.empty(10, dtype=nb.types.NPDatetime('D'))
    
    
    print(xxx())

However, the code returns this error:

    Unknown attribute 'NPDatetime' of type Module(<module 'numba.types' from '/home/xxx/anaconda3/lib/python3.6/site-packages/numba/types/__init__.py'>)

My numba version is 0.39.0

**Comment by stuartarchibald** [comment]
Thanks for the query. It's a bit contrived, but this should work:
```python
import numba as nb
import numpy as np
from numba import numpy_support
dt = numpy_support.as_dtype(nb.types.NPDatetime('D'))

@nb.jit(nopython=True)
def xxx():
    return np.empty(10, dtype=dt)


print(xxx())
```
produces:
```
['-10299154637204782-05-01' '-10299154637204782-05-01'
 '-10299154637204782-05-01' '-10299154637204782-05-01'
 '-10299154637204782-05-01' '-10299154637204782-05-01'
 '-10299154637204782-05-01' '-10299154637204782-05-01'
 '-10299154637204782-05-01' '-10299154637204782-05-01']
```

**Comment by jsphon** [comment]
Thanks Stuart. That works great!

**Comment by stuartarchibald** [comment]
No problem, glad to hear it!
