### ISSUE TITLE
can't create pycc AOT compiler on Windows

### ISSUE THREAD

**Issue by subhylahiri** [numba/numba#3304]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

numba.pycc.CC fails upon initialization on windows, despite having a compiler (distutils works fine):

    In  [1]: from numba.pycc import CC
    In  [2]: cc = CC('foo')
    Traceback (most recent call last):
      File "<ipython-input-2-06608376f747>", line 1, in <module>
        cc = CC('foo')
      File "C:\Anaconda3\lib\site-packages\numba\pycc\cc.py", line 62, in __init__
        self._toolchain = Toolchain()
      File "C:\Anaconda3\lib\site-packages\numba\pycc\platform. line 63, in __init__
        self._raise_external_compiler_error()
      File "C:\Anaconda3\lib\site-packages\numba\pycc\platform. line 106, in _raise_external_compiler_error
        raise RuntimeError(msg)
    RuntimeError: Attempted to compile AOT function without the compiler used
    by `numpy.distutils` present. Cannot find suitable msvc.

I tracked the cause down to numba.pycc.platform._check_external_compiler, lines 37-46.
On windows `tempfile` locks its file so cl.exe can't access it (see https://stackoverflow.com/q/20328422/9151228 & https://stackoverflow.com/q/14388608/9151228).
Numba mistakes this for the lack of a compiler.
Using TemporaryDirectory instead of NamedTemporaryFile seems to work for me:

    from distutils.sysconfig import customize_compiler
    from tempfile import NamedTemporaryFile, gettempdir, TemporaryDirectory
    import os.path as osp
    
    def check_compiler_file():
        # see if the external compiler bound in numpy.distutil is present
        # and working
        compiler = new_compiler()
        customize_compiler(compiler)
        for suffix in ['.c', '.cxx']:
            with NamedTemporaryFile('wt', suffix=suffix) as ntf:
                simple_c = "int main(void) { return 0; }"
                ntf.write(simple_c)
                ntf.flush()
                try:
                    # *output_dir* is set to avoid the compiler putting temp files
                    # in the current directory.
                    compiler.compile([ntf.name], output_dir=gettempdir())
                except Exception as exc:  # likely CompileError
                    return exc
        return None
    
    def check_compiler_dir():
        # see if the external compiler bound in numpy.distutil is present
        # and working
        compiler = new_compiler()
        customize_compiler(compiler)
        for suffix in ['.c', '.cxx']:
            with TemporaryDirectory() as tdr:
                fname = osp.join(tdr, "temp" + suffix)
                simple_c = "int main(void) { return 0; }"
                f = open(fname, 'wt')
                f.write(simple_c)
                f.flush()
                f.close()
                try:
                    # *output_dir* is set to avoid the compiler putting temp files
                    # in the current directory.
                    compiler.compile([fname], output_dir=tdr)
                except Exception as exc:  # likely CompileError
                    return exc
        return None

On windows, when there is a compiler available:

    In  [1]: check_compiler_file()
    Out [1]: CompileError(DistutilsExecError("command 'C:\\...\\cl.exe' failed
    with exit status 2"))
    In  [2]: check_compiler_dir()
    Out [2]:

When there is no compiler::

    In  [1]: check_compiler_file()
    Out [1]: DistutilsPlatformError('Unable to find vcvarsall.bat')
    In  [2]: check_compiler_dir()
    Out [2]: DistutilsPlatformError('Unable to find vcvarsall.bat')

Environment:

    import sys
    import numba
    import platform
    print(sys.version)
    print(numba.__version__)
    print(platform.platform())
    3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
    0.39.0
    Windows-10-10.0.17134-SP0

Numba 0.40.0 hasn't made it to anaconda yet, but the relevant part of platform.py looks the same to me.
I managed to hack my way around this (and didn't wind up using the AOT compiler) so this issue doesn't really affect me, but it seemed worth reporting anyway.

**Comment by seibert** [comment]
Thanks for the bug report, and the investigation.  We'll need to see why this isn't caught by our unit tests...
