### ISSUE TITLE
suspected parfors array analysis failure under `reshape`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3314]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The below fails with: `AssertionError: Sizes of result_matrix, result_data do not match on...` under the `parallel=True` function. I suspect that this is a Parfors array analysis failure. Note the use of `-1` in reshape is permitted in a single dimension to indicate "infer from other specified dimensions", I think not handling this is the root cause of the problem. Original report on gitter [here](https://gitter.im/numba/numba?at=5b9b9badf08bc22dfb56c8ec):

```python
import numpy as np
from numba import njit

n_dates = 4
n_sec = 3
price_vector = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 
                        6.0, 7.0, 8.0, 9.0, 10.0,
                        11.0, 12.0])

def func(vec, n_sec, n_dates):
    result_matrix = np.zeros((n_sec, n_sec, n_dates), dtype=np.float64)
    for i in range(n_dates):
        sub_vec = vec[(i * n_sec):((i+1)*n_sec)]
        z = sub_vec.reshape(-1, 1)
        print(z.shape)
        result_data = sub_vec / z
        result_matrix[:,:,i] = result_data

    return result_matrix

print(njit(func)(price_vector, n_sec, n_dates))
print(njit(parallel=True)(func)(price_vector, n_sec, n_dates))
```

**Comment by qlandman** [comment]
Is there an update on this? I posted the original question on gitter a while ago. This bug prevents me from running my code on multi-cores and is therefore slower than it could be. Although the code works, the added performance would be great!

**Comment by stuartarchibald** [comment]
@qlandman I'm afraid not. @DrTodd13 any ideas? If this is just array equivalence analysis failing I can probably take a look.

**Comment by DrTodd13** [comment]
@qlandman @stuartarchibald The problem is with array analysis.  The reshape call allows "-1" to mean infer this length but our current array analysis doesn't handle this special meaning of -1 and treats it naturally so it thinks the array length is -1.  Then there's a later assert that two array lengths are equal, which they won't be because that one is -1.  Working on a solution.
