### ISSUE TITLE
Initial string support

### ISSUE THREAD

**Issue by seibert** [numba/numba#3323]
Based on the various ways people are starting to use Numba (see [fletcher](https://github.com/xhochy/fletcher) and [HPAT](https://github.com/IntelLabs/hpat])), we clearly need to add support for strings.  This issue gathers some requirements and notes for this work.

Before starting:

* Read James Bennett's short review of Unicode in Python: https://www.b-list.org/weblog/2017/sep/05/how-python-does-unicode/

General requirements:
* Support for `str` in Python 2.7
* Support for `str` (unicode) and `bytes` in Python 3.x
* *Not* supporting unicode in Python 2.7 (which uses an entirely different representation than Python >= 3.3)
* When possible, simple operations implemented in Numba are preferrable
* More complex operations can be done in C if required, or even using `with objectmode` if not performance critical.
* Can look to [fletcher](https://github.com/xhochy/fletcher) for ideas of what functions are needed for Pandas use cases.

Given the above, `bytes` / Python 2 `str` can be represented in nopython mode as pointer and a length, Python 3 `str` is a pointer, a length, and an encoding enum indicating latin1, UCS-2 or UCS-4.

What operation are initially needed?  In descending order of priority:
* Creating str/unicode literals in nopython mode
* `__eq__()`
* `len()`
* `__getitem__()` - get element or slice
* `+` - string concatenation
* `in` - substring test
* `startswith()`
* `endswith()`
* `__hash__()`
* `find()`, `rfind()` - substring search
* `< <= > >=` - string ordering

Operations not on this list yet:
* `replace()` - not sure how important this is for Numba use cases
* `format()` - only sensible way to do this is to call back into interpreter
*  all the `isX` methods - I suspect these are difficult to implement for unicode, but not sure what is involved.  Users will expect these to be fast, so calling back into the interpreter is probably not a good solution.

Unknowns:
* How hard are the primary operations with Unicode?  Can we compare lists of code points, or does some normalization have to be done first?

**Comment by godaygo** [comment]
Nice to hear about these plans. Just one question about Python 2 parts of your general requirements - is it really necessary? Taking into account your plans of the [end of Python 2.7 support](https://numba.pydata.org/numba-doc/dev/reference/python27-eol.html#timeline) in December 2018 this effort seems excessive.

**Comment by seibert** [comment]
Since we need to implement `bytes` for Python 3 anyway, we can easily alias it to `str` on Python 2.  The Python 2.7 deprecation is why we aren't going to implement Python 2.7 `unicode` which is entirely different and not useful long term.

**Comment by seibert** [comment]
Dump of information from recent investigations:

- Get parts of unicode struct using `PyUnicode_GET_LENGTH`, `PyUnicode_KIND`,`PyUnicode_DATA`.  These are C macros, so need to wrap in a function call (can do all three) in helperlib.c to call from Python.
- Unicode strings are not automatically in "canonical" form and usable with the above macros.  Need to call `PyUnicode_READY` first to prepare them, which may do some memory allocation.
- Once ready, returned data pointer can be used as a `uint8`, `uint16` or `uint32` array, depending on the value of `kind`.
- Create new unicode object with `PyUnicode_FromKindAndData`, which will allocate storage as needed and return a Python object.
- How should we upgrade strings without breaking existing partial support that treats them as special constant type?
- How to handle memory ownership?
  * Similar to array: Numba can have view on Python-managed string storage.  If Numba creates a string, we have to managed it with NRT in case it is put into jitclass.
  * Different: As soon as we box the Numba string into a Python unicode object, Python copies the string into its memory, and the refcount on NRT version should be decremented.  (no Python unicode views on NRT managed memory)
  * Better: Strings being immutable does make reasoning about all of this easier.
- Unicode string comparison looks fairly straightforward: https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L10786-L10899
  * Thanks to the JIT, we don't need quite all the type switching here.

**Comment by seibert** [comment]
Another thought: perhaps it would be better to treat the unicode "kind" like a dtype.  Since strings are immutable, they can't change kind after creation, and there are clear casting rules for concatenation.  UCS1 + UCS2 => UCS2, and so on.

Going this route (rather than making kind an attribute of a single unicode type) means that can't dynamically reduce the character width returned by an operation.  For example, a `replace` on a UCS2 string could potentially return a UCS1 string, if the resulting code points would allow it.  That can't be determined at compile time, so *if* we wanted to have that option, we would have to hide the unicode kind inside the data model, rather than making it part of the type.

**Comment by seibert** [comment]
I was thinking that the only time we call the Python C API is for boxing and unboxing.  All of the above operations should be implemented with a relatively small amount of compiled Python.  The performance might be identical either way.

To make this concrete, imagine that we have an internal `_get_code_point(string, i)` method that returns the code point at offset `i` in a string.  The equality test for a string is then:
``` python
def eq(a, b):
    if len(a) != len(b):
        return False
    for i in range(len(a)):
        if _get_code_point(a, i) != _get_code_point(b, i):
            return False
    return True
```
If character width is part of the type, then we have effectively three `_get_code_point` type signatures:
  * `uint8(unicode(1), unicode(1))` (UCS1)
  * `uint16(unicode(2), unicode(2))` (UCS2)
  * `uint32(unicode(4), unicode(4))` (UCS4)
The UCS2 pseudocode looks like this (assume the data model has `_data` pointer):
``` python
def _get_code_point(a, i):
    return deref_as_uint16(a._data + 2 * i)
```
whereas if `kind` is a runtime tag (so let's say the data model has a `_kind` enum), then we have only one signature for `_get_code_point`:
  * `uint32(unicode, unicode)`
``` python
# this probably doesn't work in the Numba type system and has to be written with LLVM builder syntax
def _get_code_point(a, i):
    if a._kind == UCS1:
        return deref_as_uint8(a._data + i)
    elif a._kind == UCS2:
        return deref_as_uint16(a._data + 2 * i)
    elif a._kind == UCS4:
        return deref_as_uint32(a._data + 4 * i)
    else:
        pass # there's also a wchar kind, but that's one of the above
```
I suspect the latter will result in slower code (similar to how our NumPy functions are slower for `A` layout compared to `C` layout), but I'm also happy with whatever is more straightforward to implement and maintain.

**Comment by seibert** [comment]
I should note that Python's implementation of unicode equality uses a C macro to generate special case loops for each combination of character width, much the same as Numba would do naturally if we put the kind into the unicode type.

**Comment by seibert** [comment]
Also, a readable (more than the [CPython version](https://github.com/python/cpython/blob/master/Objects/stringlib/fastsearch.h)) and fast substring search algorithm is described here:

http://effbot.org/zone/stringlib.htm

**Comment by seibert** [comment]
also interesting to note that Python always puts an extra null character at the end of the string (to make it easier to pass to C functions, presumably), and the string search algorithm above assumes that it is safe to read `s[n]`, where `n` is the length of the string.

If we follow the same convention for Numba-allocated strings, it also means that slices can't simply be views on other string storage.  "No-malloc" slices seem like a potentially useful optimization, so we might consider deviating from the Python convention.

**Comment by ehsantn** [comment]
I haven't noticed much of string slicing in the use cases I've looked at. However, reading single character was much more common and worth optimizing (i.e. having a character type).

**Comment by seibert** [comment]
ok, talking to Siu, I think we made a few more decisions:
- Stick with the Python approach, which means that slicing has to copy to new storage.
- The data model for strings in Numba will need to indicate whether the string storage is managed by Python (i.e., the string originally came from Python or has been boxed at some point in the past), or the storage is managed by NRT.

**Comment by seibert** [comment]
And yes, `get_code_point()` is sufficiently useful that I think we want it to be a function that other nopython mode functions outside can use to implement string algorithms.  The Python way of making indexing return a length-1 string will result in inefficient code.

**Comment by seibert** [comment]
Not yet.  There's still more to do in 0.42 to cover this issue.

**Comment by stuartarchibald** [comment]
@tswast thanks for the interest, #3989 also asks for `str(int)` to I'm inclined to leave it for now, there's in-flight PRs to address that specific case. 

RE `bytes`, whilst not quite the same as `bytes` itself, this sort of thing works:
```python
from numba import njit
import numpy as np

@njit
def foo():
    n = 10
    x = np.empty(n, dtype=np.uint8)
    for i in range(n):
        x[i]  = 0x41 + i
    return x

print(bytes(foo()))
```

**Comment by tswast** [comment]
> I haven't noticed much of string slicing in the use cases I've looked at.

In the use case that I'm considering (parsing Avro), slices on bytes would be very useful, as it would prevent the need to make extra copies. I tried the above suggested workaround for returning bytes, but since it's making a copy of the data it about doubles the parsing time.

Slices into unicode seems less useful to me, as the formats I'm parsing are binary.

**Comment by MosheVai** [comment]
Any progress on this?

**Comment by stuartarchibald** [comment]
@MosheVai what's "this" in the above?

**Comment by goodmami** [comment]
Is this done? The associated milestone is closed and it doesn't appear in the associated project board (maybe the "awaiting triage" column is removed or hidden for me).

**Comment by stuartarchibald** [comment]
Yes, basic string support is done. List of supported operations is here:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#str

Please open new tickets to request features that are missing. Thanks.
