### ISSUE TITLE
CUDA 10 notes

### ISSUE THREAD

**Issue by seibert** [numba/numba#3327]
CUDA 10 has now been released.  Notes for how this impacts Numba:

* CUDA 10 is required for Turing GPUs, so we need a cudatoolkit 10 conda package for the newer hardware
* We've dodged the [NVVM text IR deprecation problem](#2975) for another release.  It seems that LLVM 3.4-style IR is still accepted.  (Although it can't express of the newer NVVM IR features.)   :sweat_smile:
* CUDA Graphs offer a new way to sequence kernel launches that is more flexible and straightforward than using CUDA streams % events to express dependencies.  We should probably expose this in Numba.
* CUDA device properties include a device UUID, which we should expose as an attribute.
* Not a Numba-exclusive problem, but apparently RHEL/CentOS6 is now deprecated with the release of CUDA 10.  Still supported, but "may" be dropped in the future.  Conda packages are normally built with CentOS 6 support.

**Comment by seibert** [comment]
btw, I've now tried numba + cudatoolkit 9.2 conda package on NVIDIA driver 410.48 (which comes with CUDA 10) and numba using CUDA 10 directly.  In both cases, the Numba CUDA unit tests pass with a Titan Xp card.  (No Turing cards to test.  😁)

**Comment by oxyflour** [comment]
Hi! I'm playing with cuda graph in numba and some codes seems working. (gist [here](https://gist.github.com/oxyflour/c4155633cd949b0c42f1898324bcd7db), dirty and hacky.)
```python
arr = cuda.to_device(np.array([1.]))

@cuda.jit(void(f8[:]))
def k1(a):
  a[0] = 2
  print('k1', a[0])

@cuda.jit(void(f8[:]))
def k2(a):
  print('k2', a[0])

graph = Graph()
kn1 = KernelNode(graph, k1, [], { 'kernelParams': [arr] })
kn2 = KernelNode(graph, k2, [kn1], { 'kernelParams': [arr] })
inst = graph.instance()
st = cuda.stream()
inst.launch(st)
st.synchronize()
```

In order to convert arguments into ctypes and device pointers, `CUDAKernel._prepare_args` is called but I've no idea how to deal with the `retr` array [here](https://github.com/numba/numba/blob/master/numba/cuda/compiler.py#L647) for graphs. Is anyone working on this feature? Do you have any suggestions?

**Comment by seibert** [comment]
We aren't currently working on this feature, but we would be very interested to see your gist turned into a full PR.  Feel free to open a work-in-progress PR to get feedback.  We are more than happy to do early review of stuff.

Regarding your question, I think the challenge is deciding what ought to happen if a user passes a host array to a graph.  For single kernel launches, it effectively makes the launches synchronous, since we have an implicit sync before the memory copy back to the host can happen.

I can imagine two possible approaches:
* Forbid usage of host arrays (or any other data type that needs write-back allocation) with this API and have KernelNode raise an exception if host arrays are passed in.
* Defer preparing arguments until the kernel is launched, do the work to identify arguments that are passed to multiple kernels, convert them to device arrays once, launch the cuda graph, and then make the calls to bring the device arrays back after the graph has been launched.

The second option is more transparent for the user, but makes the feature significantly more complicated.  A PR that does the first option I think makes it much more likely we can get this feature to our users.  :)

**Comment by oxyflour** [comment]
Hello! Thank you for your reply. To be honest I'm an experienced python programmer so I guess I'll try with the first approach. Cuda graph seems useful in my research project, which is in prototype. I'm still doing experiments with it and would like to give a PR when it gets ready. 😁

**Comment by seibert** [comment]
We also think the kernel graph API is a lot more intuitive for launching groups of kernels with complex dependency relationships than trying to use multiple streams and cuda events to permit concurrent execution.  Please let us know how your prototype turns out.

**Comment by gmarkall** [comment]
Some notes on bullet points in the original post:

>     * CUDA 10 is required for Turing GPUs, so we need a cudatoolkit 10 conda package for the newer hardware

CUDA 10 packages have been available for a while, and cudatoolkit packages are also produced and updated fairly quickly by conda-forge: https://github.com/conda-forge/cudatoolkit-feedstock

>     * We've dodged the [NVVM text IR deprecation problem](#2975) for another release.  It seems that LLVM 3.4-style IR is still accepted.  (Although it can't express of the newer NVVM IR features.)   sweat_smile

Numba now supported NVVM 3.4 and 7.0 IR, as of #6661. In the future we need to switch to the bitcode IR.

>     * CUDA device properties include a device UUID, which we should expose as an attribute.

Will be exposed in #6700.

>     * Not a Numba-exclusive problem, but apparently RHEL/CentOS6 is now deprecated with the release of CUDA 10.  Still supported, but "may" be dropped in the future.  Conda packages are normally built with CentOS 6 support.

Current cudatoolkit packages from conda-forge appear to be built with CentOS 7 support: https://github.com/conda-forge/cudatoolkit-feedstock/blob/master/.ci_support/linux_64_major_minor_ver10.0.yaml#L6

**Comment by stuartarchibald** [comment]
@gmarkall can this now be closed?

**Comment by gmarkall** [comment]
> @gmarkall can this now be closed?

Yes.
