### ISSUE TITLE
Type Refactor

### ISSUE THREAD

**Issue by datnamer** [numba/numba#3330]
The wiki states that a "type refactor" is on the horizon for next release.

What are the goals and nature of this refactor? Will it include the ability to handle an expanded set of pep 484 annotated python code?

One use case that I'd love to see covered is parametric JIT classes.

**Comment by user2589** [comment]
@datnamer ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/numba/numba/issues/3330)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!

**Comment by stuartarchibald** [comment]
Thanks for the question. This issue is a couple of years old and am unsure to what it refers. Will close, but please do reopen/create a new issue if there's unresolved items related to current (0.51.2) Numba. Thanks!
