### ISSUE TITLE
CUDA shared array size limitations

### ISSUE THREAD

**Issue by hippke** [numba/numba#3350]
I try a shared CUDA 2D array using `cuda.shared.array(shape=(a, b), dtype=float32)`
This works for large 1D arrays (e.g., `a=1, b=50000`), but crashes for 2D with sizes a=2, b>6144 floats.
The error is: "numba.cuda.cudadrv.driver.LinkerError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN"
Any idea how to solve this?

**Comment by sklam** [comment]
Does it show more info after the CUDA_ERROR_UNKNOWN?

e.g.:

```
LinkerError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN
error   : Entry function '_ZN6cudapy8__main__7foo$242E5ArrayIxLi1E1C7mutable7alignedE' uses too much shared data (0x30d40 bytes, 0xc000 max)
```

**Comment by hippke** [comment]
> numba.cuda.cudadrv.driver.LinkerError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN error   : Entry function'_ZN6cudapy8__main__12itr_cuda$241E5ArrayIfLi1E1C7mutable7alignedE5ArrayIfLi1E1C7mutable7alignedE5ArrayIfLi2E1C7mutable7alignedE5ArrayIdLi1E1C7mutable7alignedE5ArrayIfLi1E1C7mutable7alignedE5ArrayIfLi2E1C7mutable7alignedE' uses too much shared data (0xdac8 bytes, 0xc000 max)

OK, so this says that I'm trying to use 56008 bytes of shared memory, but only 49152 bytes are available. My card is a GTX1060 with 3 GB. And a 1D array of size >56008 bytes works just fine. Strange!

**Comment by seibert** [comment]
I would have expected the 1D case to fail then.  Compute capability 6.x (like your GTX 1060) should only be able to use 48kB of shared memory per block.  (https://docs.nvidia.com/cuda/cuda-c-programming-guide/#features-and-technical-specifications)   Large than that requires compute capability 7.x...

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
