### ISSUE TITLE
Globals error in objmode context-manager for generated functions

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3355]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

For some reason, `objmode` cannot handle the global variables properly if the function is generated with text and `exec`. Here is an example:

```python
import numpy as np
from numba import objmode, njit

def gen_g():
    func_text = "def func():\n"
    func_text += "    with objmode():\n"
    func_text += "        np.array([1,2,3])\n"
    loc_vars = {}
    exec(func_text, {'objmode': objmode, 'np': np}, loc_vars)
    func = loc_vars['func']
    return njit(func)

g = gen_g()
g()
```
```
Traceback (most recent call last):
  File "tmp_tests/obj_gen_test.py", line 14, in <module>
    g()
NameError: global name 'np' is not defined
```

**Comment by sklam** [comment]
That's because the `func()` doesn't see that `global` dictionary.  You need to fill `loc_vars` with `{'np': np, 'objmode': objmode}`  or just `loc_vars.update(globals())`.

**Comment by ehsantn** [comment]
Still the same. Does it work on your end?

**Comment by ehsantn** [comment]
@sklam using `globals()` works, but I get the warning below in HPAT. I can't reproduce it in a small example though. Any idea? Looks like the compile flags may be wrong for the lifted function.

```
<string>:2: NumbaWarning: Function "csv_reader_py" failed type inference: Unknown attribute 'read_csv' of type Module(<module 'pandas' from '/Users/etotoni/pse-hpc/python/pandas/pandas/__init__.py'>)

File "<string>", line 4:
<source missing, REPL in use?>

[1] During: typing of get attribute at <string> (4)

File "<string>", line 4:
<source missing, REPL in use?>

<string>:2: NumbaWarning: Function "csv_reader_py" was compiled in object mode without forceobj=True.
```

**Comment by sklam** [comment]
The warning is issued to let user know that they may be "accidentally" using objectmode.  I'll check and make sure `forceobj=True` is set in `objmode()`.

**Comment by sklam** [comment]
The original error is not `objmode()` specific:

```python
import numpy as np
from numba import objmode, njit, jit
from pprint import pprint

def gen_g():
    func_text = "def func():\n"
    func_text += "    np.array([1,2,3])\n"
    loc_vars = {}
    what = {'np': np}
    exec(func_text, what, loc_vars)
    func = loc_vars['func']
    return jit(forceobj=True)(func)

g = gen_g()
g()
```

**Comment by sklam** [comment]
Found the reason.  The compiled function is taking the module's `__globals__` as the global dictionary for the compiled object-mode function.  That is true for most function creation.  But for `exec`, the code's module is `<dynamic>`.
