### ISSUE TITLE
List modification is lost when list is passed with a tuple to a jitted function

### ISSUE THREAD

**Issue by joelrich** [numba/numba#3358]
I have discovered a very interesting behavior in numba 0.40:

```python
from numba import njit

@njit # jit is broken too
def test(t):
  l, = t
  l.append(4)
  print(l)
  print(list(l))
  return l

t = ([0, 1, 2, 3],)
print(test(t))
```

Output:
```
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
```

It does not happen, if I pass the list directly (without the tuple) to the function. Also, by wrapping the list with `list(...)`, the modified list can be retrieved.

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce.

**Comment by sklam** [comment]
Developer note: The reflection machinery is not recursing into nested types.  I don't think the fix is easy.

**Comment by stuartarchibald** [comment]
As of 0.45 this works fine with the typed List implementation:
```
from numba import njit
from numba.typed import List

@njit
def test(t):
  l, = t
  l.append(4)
  print(l)
  print(list(l))
  return l

lst = List()
lst.extend([0, 1, 2, 3])
t = (lst,)
print(test(t))
```
