### ISSUE TITLE
Attribute error from numba-wrapped function has wrong line number

### ISSUE THREAD

**Issue by jrhastings** [numba/numba#337]
In this snippet the function being called (loop_sum) has @numba.autojit.

It triggers an AttributeError internally (a real bug on my part that came from changing a 1d array to a tuple of 1d arrays) but the AttributeError (tuple has no .sum()) appears as if it were thrown one level up the callstack.

```
-> 1021         x_b, y_b_tup, w_b = loop_sum(x, y_tup, num_bins)

/home/jrh/anaconda/lib/python2.7/site-packages/numba/numbawrapper.so in numba.numbawrapper._NumbaSpecializingWrapper.__call__ (numba/numbawrapper.c:3764)()

AttributeError: 'tuple' object has no attribute 'sum'
```

This was a bit confusing so figured I'd send the issue.  

I wonder if, generically, numba could wrap functions s.t. if they throw an exception it re-runs the original (non-jit'd) function for a more intuitive error?  i.e. automate something like this pseudocode for every numba-wrapping:

```
try:
   numba_versio(...)
except:
   raw_version(...) # this is expected to raise an exception "nicely" so user can debug
   raise RuntimeError("numba version failed but raw Python succeeded")
```

**Comment by seibert** [comment]
Closing old bugs.
