### ISSUE TITLE
Recursive functions will not serialize/pickle

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3370]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

From this question: https://stackoverflow.com/questions/52569621/numba-functions-and-pickle
This:
```python
from numba import njit
import pickle

@njit
def df(n):
    if n <= 0:
        return 1
    else:
        return n * df(n - 2)

pickle.dumps(df)
```
fails with
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```
from the serialization call and it clearly ought not to.

**Comment by luk-f-a** [comment]
hi @stuartarchibald , thanks for picking it up. I wrote that stackoverflow question and was coming here to report it when I saw that you already did. Happy to provide more details if necessary. I am using numba 0.39, as I could not find 0.40 in conda to retest on latest version.

**Comment by stuartarchibald** [comment]
@luk-f-a no problem. We keep an eye on stackoverflow for issues users may be having! Thanks for coming here to report the issue, it's much appreciated. Numba 0.40.0 will still have the bug, but if you want to try it anyway because it has [loads of new features](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/0gMN_-gIhBg) then it is available from the Numba channel:
```
$ conda install -c numba numba=0.40.0
```
and will be available from the main channels soon.

**Comment by bkj** [comment]
I'm actually still running into this problem -- is there any guidance on a workaround for this?

**Comment by guzuomuse** [comment]
+1 same issue here

**Comment by stuartarchibald** [comment]
This does not reproduce on mainline for the upcoming 0.55 release. Closing.
