### ISSUE TITLE
Support user-defined types in objmode context-manager

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3372]
## Feature request

The `objmode` context-manager only supports type strings that are exported in `types` module (used by `_parse_signature_string`). This doesn't allow user-defined types to be used.

This is related to #3356 to some extent.

**Comment by asodeur** [comment]
I just realized the new typed containers already work with `objmode`. You can get a custom type out of `objmode` by putting it into a `Dict`. This looks like an ok work-around for the time being.

```python
from numba import jit, objmode, typed, types
from my_lib import MyClass, my_class_type

@jit(nopython=True)
def objectmode_with_custom_type():
    d = typed.Dict.empty(types.unicode_type, my_class_type)

    with objmode():
        d['result'] = MyClass()

    return d['result']
```
