### ISSUE TITLE
Array analysis fails for slice objects

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3380]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Array analysis fails for standalone slice objects for some reason. Needs investigation.

```python
@numba.njit(parallel=True)
def f():
    a = slice(None, None)
```
~/pse-hpc/python/numba/numba/array_analysis.py in set_shape(self, obj, shape)
    810             assert(isinstance(obj, ir.Var))
    811             typ = self.typemap[obj.name]
--> 812             super(SymbolicEquivSet, self).set_shape(obj, shape)
    813
    814     def _get_shape(self, obj):
AttributeError: Failed in nopython mode pipeline (step: convert to parfors)
'super' object has no attribute 'set_shape'
```

```

**Comment by stuartarchibald** [comment]
Seems like there is indeed no `set_shape` in the class super.
https://github.com/numba/numba/blob/3618091896cb54c6b8d442c290cfe5f9480f6e89/numba/array_analysis.py#L809-L812

probably need something similar to the `_get_shape` just below it to handle the slice?

**Comment by ehsantn** [comment]
I ran into this issue again. Slice objects seem problematic in general in array analysis:
```python
import numba
import numpy as np

@numba.njit(parallel=True)
def f(A, a):
    b = a
    return A[b]

f(np.ones(3), slice(None))
```
```
  File "/home/ehsan/dev/numba/numba/compiler.py", line 245, in run
    stage()
  File "/home/ehsan/dev/numba/numba/compiler.py", line 565, in stage_parfor_pass
    parfor_pass.run()
  File "/home/ehsan/dev/numba/numba/parfor.py", line 1448, in run
    self.array_analysis.run(self.func_ir.blocks)
  File "/home/ehsan/dev/numba/numba/array_analysis.py", line 916, in run
    pre, post = self._analyze_inst(label, scope, equiv_set, inst)
  File "/home/ehsan/dev/numba/numba/array_analysis.py", line 985, in _analyze_inst
    equiv_set.set_shape(lhs, shape)
  File "/home/ehsan/dev/numba/numba/array_analysis.py", line 811, in set_shape
    super(SymbolicEquivSet, self).set_shape(obj, shape)
AttributeError: Failed in nopython mode pipeline (step: convert to parfors)
'super' object has no attribute 'set_shape'
```
