### ISSUE TITLE
Complex power on CUDA

### ISSUE THREAD

**Issue by nigulasikaochuan** [numba/numba#3386]
## Feature request

I am using numba do some simulation,however when i try the complex power in cuda,it report error,and i try a very simple coda as below, the code and the error numba suggests are as below, it there something wrong with my code or is just the numba still not support it:
![10 062206](https://user-images.githubusercontent.com/34807360/46572192-2fea9880-c9b4-11e8-8f7a-6d42da913a71.png)

---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in complete(self)
   1616         try:
-> 1617             driver.cuLinkComplete(self.handle, byref(cubin), byref(size))
   1618         except CudaAPIError as e:

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    289             retcode = libfn(*args)
--> 290             self._check_error(fname, retcode)
    291         return safe_cuda_api_call

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    324                     raise CudaDriverError("CUDA initialized before forking")
--> 325             raise CudaAPIError(retcode, msg)
    326 

CudaAPIError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN

During handling of the above exception, another exception occurred:

LinkerError                               Traceback (most recent call last)
<ipython-input-68-41e1c3856f7c> in <module>()
      1 array1 = np.array([1,2,3,4,5],dtype = np.complex)
----> 2 power_complex[4,4](array1)

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/compiler.py in __call__(self, *args)
    751         Specialize and invoke this kernel with *args*.
    752         '''
--> 753         kernel = self.specialize(*args)
    754         cfg = kernel[self.griddim, self.blockdim, self.stream, self.sharedmem]
    755         cfg(*args)

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/compiler.py in specialize(self, *args)
    762         argtypes = tuple(
    763             [self.typingctx.resolve_argument_type(a) for a in args])
--> 764         kernel = self.compile(argtypes)
    765         return kernel
    766 

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/compiler.py in compile(self, sig)
    781             self.definitions[(cc, argtypes)] = kernel
    782             if self.bind:
--> 783                 kernel.bind()
    784         return kernel
    785 

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/compiler.py in bind(self)
    498         Force binding to current CUDA context
    499         """
--> 500         self._func.get()
    501 
    502     @property

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/compiler.py in get(self)
    383             for path in self.linking:
    384                 linker.add_file_guess_ext(path)
--> 385             cubin, _size = linker.complete()
    386             compile_info = linker.info_log
    387             module = cuctx.create_module_image(cubin)

/mnt/F/ubuntu/anaconda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in complete(self)
   1617             driver.cuLinkComplete(self.handle, byref(cubin), byref(size))
   1618         except CudaAPIError as e:
-> 1619             raise LinkerError("%s\n%s" % (e, self.error_log))
   1620 
   1621         size = size.value

LinkerError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN
error   : Undefined reference to 'numba_cpow' in '<cudapy-ptx>'

**Comment by stuartarchibald** [comment]
Thanks for the report. I don't think this is supported. But also think that that error message ought to be improved and that it probably shouldn't be going down the compilation path it has taken (`numba_cpow` is a reference to the CPU impl). So this is also a bug!
