### ISSUE TITLE
Use device_extents to know the exact base pointer

### ISSUE THREAD

**Issue by sklam** [numba/numba#3387]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

https://github.com/numba/numba/blob/3618091896cb54c6b8d442c290cfe5f9480f6e89/numba/cuda/cudadrv/driver.py#L792

^ This will not work if `owner` is not the base pointer; i.e. from external allocation.

Should use `device_extents` to get the exact base pointer instead.

**Comment by stuartarchibald** [comment]
@gmarkall I'm pretty sure this is fixed on mainline/0.51, do you concur? https://github.com/numba/numba/blob/release0.51/numba/cuda/cudadrv/driver.py#L814-L833

**Comment by gmarkall** [comment]
> @gmarkall I'm pretty sure this is fixed on mainline/0.51, do you concur? https://github.com/numba/numba/blob/release0.51/numba/cuda/cudadrv/driver.py#L814-L833

I do - closing.
