### ISSUE TITLE
Error when copying result from device to host

### ISSUE THREAD

**Issue by duyduc1110** [numba/numba#3388]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I am using GTX 1060 6GB and run this script on CUDA:  
    

    
    import os
    import time
    import numpy as np
    import math
    from numba import cuda, int32, config
    from __future__ import division
    

    @cuda.jit
    def duc_kernel(desc, kw, rs):
        pos = cuda.grid(1)
        if pos < (kw.shape[0] * desc.shape[0]):
            row = pos // kw.shape[0]
            col = pos % kw.shape[0]

            #Define desc, kw for each threads
            pre_row = cuda.local.array(shape = max_len_desc, dtype = int32)
            cur_row = cuda.local.array(shape = max_len_desc, dtype = int32)
            desc_pick = desc[row]
            kw_pick = kw[col]

            #Clean desc, kw
            for len_desc in range(len(desc_pick)):
                if desc_pick[len_desc] == -1:
                    break
            desc_pick = desc_pick[0:len_desc]
            for len_kw in range(len(kw_pick)):
                if kw_pick[len_kw] == -1:
                    break
            kw_pick = kw_pick[0:len_kw]   

            #Modify pre_row
            for i in range(len_desc + 1):
                pre_row[i] = i

            #levenshtein 
            for desc_chr in desc_pick:
                cur_row = pre_row
                for i in range(len_desc+1):
                    cur_row[i] += 1
            
            rs[row, col] = cur_row[len_desc+1]

    if __name__ == '__main__':
        #Read file
        with open("C:/Users/TTEK/Desktop/desc.txt") as f:
            desc = f.read().split("\n")
        with open("C:/Users/TTEK/Desktop/keyword.txt") as f:
            kw = f.read().split("\n")
        result_kw = []

        #Create desc & keyword arrays
        max_len_desc = max(len(i) for i in desc)
        desc_arr = np.full((len(desc), max_len_desc), -1, np.int)
        max_len_kw = max(len(i) for i in kw)
        kw_arr = np.full((len(kw), max_len_kw), -1, np.int)

        #Desc & Keyword arrays into number
        for i in range(len(desc_arr)):
            for j in range(len(desc[i])):
                desc_arr[i,j] = ord(desc[i][j])
        for i in range(len(kw)):
            for j in range(len(kw[i])):
                kw_arr[i,j] = ord(kw[i][j])
        s_time = time.time()

        #Copy arrays to device
        desc_global_mem = cuda.to_device(desc_arr)
        kw_global_mem = cuda.to_device(kw_arr)
        rs_global_mem = cuda.device_array((len(desc), len(kw)))

        #Configure the blocks
        threadsperblock = len(desc)
        blockspergrid = len(kw)
        duc_kernel[blockspergrid, threadsperblock](desc_global_mem, kw_global_mem, rs_global_mem)

        #Copy result to host
        print(time.time() - s_time)
        
        

Some more details:

- len(desc) = 1k
- len(kw) = 50k

It runs pretty good but when I want to copy result to host with this code: ```rs = rs_global_mem.copy_to_host()```, it caused this problem (10k kw is fine):

```CudaAPIError                              Traceback (most recent call last)
<ipython-input-2-0fa94016f277> in <module>()
----> 1 rs = rs_global_mem.copy_to_host()

C:\ProgramData\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devices.py in _require_cuda_context(*args, **kws)
    210     def _require_cuda_context(*args, **kws):
    211         get_context()
--> 212         return fn(*args, **kws)
    213 
    214     return _require_cuda_context

C:\ProgramData\Anaconda3\lib\site-packages\numba\cuda\cudadrv\devicearray.py in copy_to_host(self, ary, stream)
    239         assert self.alloc_size >= 0, "Negative memory size"
    240         if self.alloc_size != 0:
--> 241             _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
    242 
    243         if ary is None:

C:\ProgramData\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py in device_to_host(dst, src, size, stream)
   1604         fn = driver.cuMemcpyDtoH
   1605 
-> 1606     fn(host_pointer(dst), device_pointer(src), size, *varargs)
   1607 
   1608 

C:\ProgramData\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py in safe_cuda_api_call(*args)
    286             _logger.debug('call driver api: %s', libfn.__name__)
    287             retcode = libfn(*args)
--> 288             self._check_error(fname, retcode)
    289         return safe_cuda_api_call
    290 

C:\ProgramData\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py in _check_error(self, fname, retcode)
    321                     _logger.critical(msg, _getpid(), self.pid)
    322                     raise CudaDriverError("CUDA initialized before forking")
--> 323             raise CudaAPIError(retcode, msg)
    324 
    325     def get_device(self, devnum=0):

CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED```

**Comment by duyduc1110** [comment]
Some more details:
- len(desc) = 1k
- len(kw) = 50k

I can pull results with 10k kw, but with 50k, it caused the above problem

**Comment by sklam** [comment]
Because CUDA kernels are running asynchronously, errors inside the kernel are usually reported in the next time a CUDA API is called.  Here, it is the `copy_to_device` that is seeing the error inside the kernel.  You may want to check your problem with [cuda-memcheck](https://docs.nvidia.com/cuda/cuda-memcheck/index.html).

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
