### ISSUE TITLE
Compatibility with CuPy

### ISSUE THREAD

**Issue by randyzwitch** [numba/numba#3422]
## Feature request

Cross post with https://github.com/cupy/cupy/issues/1720

pygdf allows for returning a matrix, but it returns `numba.cuda.cudadrv.devicearray.DeviceNDArray`, which is currently limited in its linear algebra functionality. 

It would be great if there was support for CuPy, which is much more feature rich.

**Comment by stuartarchibald** [comment]
Thanks for the request. The `__cuda_array_interface__` is implemented with view to help with this matter, here is some documentation/issues (a lot is in RC or experimental phase):
* https://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html
* https://docs-cupy.chainer.org/en/latest/reference/interoperability.html#numba
* https://github.com/numba/numba/pull/2860
* https://github.com/cupy/cupy/pull/1144
* https://github.com/pytorch/pytorch/pull/11984

**Comment by berryboy2012** [comment]
Sorry for disturbing, but how can I utilize this feature in combine with `numba.jit` decorator? For example, the first codelet in tutorial [1.1. A ~5 minute guide to Numba](https://numba.pydata.org/numba-doc/dev/user/5minguide.html)? Seems that there is little document about `__cuda_array_interface__`.

**Comment by stuartarchibald** [comment]
`__cuda_array_interface__` is now implemented and IIRC versioned, docs: https://docs.cupy.dev/en/stable/reference/interoperability.html#numba. Closing assume resolved.
