### ISSUE TITLE
Support `numpy.average`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3435]
## Feature request

From: https://stackoverflow.com/questions/52912004/numba-jit-fails-to-speed-up-the-performance-of-this-function-anyway-to-fix-tha

`numpy.average` is not supported, this is a good first issue for someone using `numba.extending`.

**Comment by slnguyen** [comment]
I'd like to work on this issue.

**Comment by stuartarchibald** [comment]
Great, thanks for volunteering @slnguyen!

**Comment by prh-t** [comment]
Is this still open?

**Comment by stuartarchibald** [comment]
@prh-t thanks for the note, https://github.com/numba/numba/pull/7304 closes.
