### ISSUE TITLE
autojit doesn't work with multiprocessing module

### ISSUE THREAD

**Issue by bjarthur** [numba/numba#345]
should it?  see code below:

from numba import autojit
from multiprocessing import Pool

@autojit
def do_it(args):
  return args[0]+args[1]

pool=Pool()

#this works
#idx=map(do_it,zip(range(0,10),range(3,13)))

#but not this, unless the @autojit above is commented out
idx=pool.map(do_it,zip(range(0,10),range(3,13)))

[print(x) for x in idx]

**Comment by pitrou** [comment]
This works fine these days, closing.
