### ISSUE TITLE
Support `numpy.repeat`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3457]
## Feature request
Add support for `numpy.repeat`.

**Comment by NanduTej** [comment]
Hey @stuartarchibald, I wanted to try and contribute to fixing this issue so I pulled the code from development and tried to set it up in my local. When I ran pip install -r requirements.txt, I ran into an error I couldn't solve -

**Comment by stuartarchibald** [comment]
Hi, thanks for wanting to contribute this feature. I'd recommend following the instructions [here](http://numba.pydata.org/numba-doc/dev/developer/contributing.html#build-environment) as they provide the fastest way to get set up to undertake development.

The issue you are seeing is because Numba relies on llvmlite, and Numba master branch uses developmental (and therefore unpublished) versions of llvmlite. These `llvmlite` builds are available for use with pip from here https://anaconda.org/numba/llvmlite, instructions on how to use them are also there.

Hope this helps.

**Comment by NanduTej** [comment]
> Hi, thanks for wanting to contribute this feature. I'd recommend following the instructions [here](http://numba.pydata.org/numba-doc/dev/developer/contributing.html#build-environment) as they provide the fastest way to get set up to undertake development.
> 
> The issue you are seeing is because Numba relies on llvmlite, and Numba master branch uses developmental (and therefore unpublished) versions of llvmlite. These `llvmlite` builds are available for use with pip from here https://anaconda.org/numba/llvmlite, instructions on how to use them are also there.
> 
> Hope this helps.

Thank you.

**Comment by NanduTej** [comment]
@stuartarchibald , Can you help me out with what needs to be done here. I went through - https://github.com/numba/numba/pull/3509, which seemed like a similar issue, but could not figure what exactly needs to be done. TIA.

**Comment by stuartarchibald** [comment]
First you need to write a working implementation of `np.repeat`, then that needs to be wrapped in `numba.extending.overload` to handle dispatch with respect to types. This is probably a simpler PR to look at to get the idea https://github.com/numba/numba/pull/2902

**Comment by stuartarchibald** [comment]
@NanduTej thanks for writing this. Without seeing the code you've written it's quite hard to guess what it is that's wrong. However, I expect the issue is that the code tries to compile something like `ndarray.repeat(x)` without there being an implementation of `ndarray.repeat` registered.

If it's mostly working ok but with just a couple of errors, perhaps open a pull request with the code so you can get some help with the remaining issues? Thanks.

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/3900, closing.
