### ISSUE TITLE
set.pop() behaving incorrectly

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3460]
## Reporting a bug
- [X] I am using the ~~latest released~~ master branch version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import njit

def test_impl():
    R = {1., 2., 3.}
    return R.pop()

print(test_impl())
print(njit(test_impl)())
```
gives:
```
1.
2.
```
which is unexpected!

**Comment by ehsantn** [comment]
I thought `set` is unordered and `pop` returns an arbitrary element. This is unexpected since Numba's implementation is taken from CPython and should match?

**Comment by stuartarchibald** [comment]
yes, I'd hope they match for the reason noted but I don't recall the internal details, it may be that this is known and expected behaviour under the Numba impl.

**Comment by seibert** [comment]
Changes in the hashing function might be the difference here, and I'm not sure if we want to track that across different Python versions.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
