### ISSUE TITLE
Create C extensions with Numba

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3463]
## Feature request

It would be great if Numba could create C extensions for a package at build time given some functions and their type signatures. This would avoid rewriting code in Cython and generating several Cython versions manually.

**Comment by seibert** [comment]
The goal here is to create compiled extensions that can be imported in Python?  We have support for that now, to some extent:

https://numba.pydata.org/numba-doc/dev/user/pycc.html

The main limitation currently is that there is no type-based dispatching to multiple implementations, like with Numba's CPUDispatcher.

**Comment by ehsantn** [comment]
Thanks, @seibert ! I'll look into this.
