### ISSUE TITLE
Add support for np.clip

### ISSUE THREAD

**Issue by arvoelke** [numba/numba#3465]
## Feature request

Currently `np.clip(a, a_min, a_max, out=None)` and `a.clip(a_min=None, a_max=None, out=None)` are not supported by `@njit`.

I tried to implement this myself, but am having trouble installing `llvm-6.0` in order to test my development branch locally. So, without knowing what I'm doing (first time looking at `numba` source code), this was my blind attempt implementing `np.clip(...)`:

```python
# File: numba/targets/arrayobj.py

@lower_builtin(np.clip, types.Array)
def array_clip(context, builder, sig, args):
    def np_clip_impl(a, a_min, a_max, out=None):
        if out is None:
            out = np.empty_like(a)
        for i in range(len(a)):
            if a[i] < a_min:
                out[i] = a_min
            elif a[i] > a_max:
                out[i] = a_max
            else:
                out[i] = a[i]
        return out

    return context.compile_internal(builder, np_clip_impl, sig, args)
```

Following the pattern in #3462, I'm guessing that something like this is also needed (for `a.clip(...)`):

```python
# File: numba/targets/arrayobj.py

@overload_method(types.Array, 'clip')
def array_clip(a, a_min, a_max, out=None):
    def impl(a, a_min, a_max, out=None):
        return np.clip(a, a_min, a_max, out)
    return impl
```

**Edit**: The above implementation is incomplete since the signature for `a.clip` is:
```
    a.clip(min=None, max=None, out=None)
```
Note the default values, which are not present for `np.clip`.

Furthermore, `None` can be passed to `np.clip` for `a_min` or `a_max`, in which case the lower or upper bounds are ignored, respectively.

**Comment by stuartarchibald** [comment]
Thanks for the request and starting the implementation, your contribution is appreciated. What you have written is really close to working, perhaps open a pull request and we can iterate on it?

-----------------------
> I tried to implement this myself, but am having trouble installing llvm-6.0 in order to test my development branch locally.

Some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.

Briefly, you can get away without needing LLVM for this sort of development by just using the `llvmlite` package (all the bits of LLVM needed are statically linked into `llvmlite`'s libraries). `llvmlite` is available via conda (use the Numba channel to get a version that is compatible with Numba mainline):
```
$ conda install -c numba llvmlite 
```
it's also available via `pip` using https://anaconda.org, instructions are on this page:
https://anaconda.org/numba/llvmlite

If you *really* want to build from LLVM source up, then http://llvmlite.pydata.org/en/latest/admin-guide/install.html#building-manually is the instructions to get `llvmlite` built, then switch to the Numba build instructions http://numba.pydata.org/numba-doc/latest/developer/contributing.html#building-numba

-----------------------
To the implementation, the [`numba.extending` high level extension API](http://numba.pydata.org/numba-doc/latest/extending/high-level.html) makes it possible to add functionality like this without having to hit the low level API (`@lower_builtin` and friends).

If you use the `@numba.extending.overload` decorator, creating and registering an implementation of `np.clip` with Numba can be done as follows (this is it, it's now ready to be tested etc!):
```python
@extending.overload(np.clip)
def np_clip(a, a_min, a_max, out=None):
    def np_clip_impl(a, a_min, a_max, out=None):
        if out is None:
            out = np.empty_like(a)
        for i in range(len(a)):
            if a[i] < a_min:
                out[i] = a_min
            elif a[i] > a_max:
                out[i] = a_max
            else:
                out[i] = a[i]
        return out
    return np_clip_impl
```
and indeed, following https://github.com/numba/numba/pull/3462 for the overload of the `np.ndarray` method implementation would provide the functionality noted (obviously need to do some small changes to handle the different default values in the kwargs).

Hope this helps.

**Comment by arvoelke** [comment]
Thanks for the words of encouragement! I managed to get my dev branch working after using that conda command, and have made a pull request at #3468.

**Comment by eecarres** [comment]
Hi! Any hint if this is going to be released at any time?

**Comment by dangpzanco** [comment]
Hi, any update on this issue?

**Comment by gmarkall** [comment]
> Hi, any update on this issue?

PR #6808 opened to try and get the existing work on this over the line.
