### ISSUE TITLE
Run into problem with duke's expectation maximization 

### ISSUE THREAD

**Issue by pjh177787** [numba/numba#3466]
I encountered a problem when autojit the em_gmm_orig function on https://people.duke.edu/~ccc14/sta-663/EMAlgorithm.html#using-em

**Comment by pjh177787** [comment]
When I called the function, it gives error. The way to call the function is here: https://people.duke.edu/~ccc14/sta-663/EMAlgorithm.html#comparison-of-em-routines

**Comment by stuartarchibald** [comment]
Thanks for the report. I've run this under `numba.jit` and it gives no error for me. If `numba.jit(nopython=True)` is used it will give a typing error as `scipy` functionality is not supported or understood by Numba in `nopython` mode.

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by pjh177787** [comment]
Thank you very much! I will try that!

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
