### ISSUE TITLE
Docs: 5 minute guide has a dead link

### ISSUE THREAD

**Issue by nick-morhun** [numba/numba#3476]
In [5minguide.html](http://numba.pydata.org/numba-doc/latest/user/5minguide.html#other-things-of-interest), in the line
> fastmath = True - enable 'fast-math' behaviour for the function.

the link to docs is dead.

**Comment by seibert** [comment]
Thanks for the report!  This was coincidentally fixed by #3452, but hasn't rolled out to the site docs yet.
