### ISSUE TITLE
Random Shuffle error

### ISSUE THREAD

**Issue by gavinpotter** [numba/numba#3477]
A minimum reproducer is shown below.  The np.random.shuffle does not shuffle the numbers in place as the normal numpy function does. 

```
import numba as nb
import numpy as np

def testSuffle():
    numbers = np.array([i for i in range(10)])
    np.random.shuffle(numbers)
    print("Without numba ",numbers)

@nb.njit()
def testNumbaShuffle():
    numbers = np.array([i for i in range(10)])
    np.random.shuffle(numbers)
    print("With numba", numbers)


if __name__ == '__main__':
    testSuffle()
    testNumbaShuffle()
```

Output

Without numba  [4 9 0 1 6 5 2 7 3 8]
With numba [0 1 2 3 4 5 6 7 8 9]

**Comment by sklam** [comment]
Bug confirmed.  It's seems to be related to the InlineClosurePass. Using `numbers = np.arange(10)` works.  The bug only occurs when a list-comprehension is used.

**Comment by sklam** [comment]
The InlineClosurePass is removing the shuffle call thinking it is dead by: 
https://github.com/numba/numba/blob/3b7ad858ab6b60aa1e31ca5bc905647afd0cae32/numba/ir_utils.py#L587-L590

**Comment by huyaoyu** [comment]
Could I use np.random.shuffle() inside a cuda kernel (annotated with @cuda.jit)?

**Comment by seibert** [comment]
No, we generally don't support NumPy array functions on the GPU.  This has more details:

http://numba.pydata.org/numba-doc/latest/cuda/cudapysupported.html
