### ISSUE TITLE
 name The name of the device (e.g. “GeForce GTX 970”) issue

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3479]
Based on https://numba.pydata.org/numba-doc/dev/cuda-reference/host.html
I am trying to get the name of the device but not managing
https://numba.pydata.org/numba-doc/dev/cuda-reference/host.html
`numba.cuda.cudadrv.driver.Device.name`
Error is 
`AttributeError: type object 'Device' has no attribute 'name'`
What is the correct way to do it?

**Comment by sklam** [comment]
`Device`

Try:

```

**Comment by sklam** [comment]
`numba.cuda.cudadrv.driver.Device` is the class.  To get a `Device` instance for the current GPU, use: 
```python
>>> from numba import cuda
>>> cuda.get_current_device().name
b'GeForce GT 750M'
```
