### ISSUE TITLE
numba.stencil does not have a “mode” parameter

### ISSUE THREAD

**Issue by Socob** [numba/numba#3486]
## Reporting a bug
- [x] I am using the latest released version of Numba
- [x] I have included below a minimal working reproducer

The [documentation for `numba.stencil`](https://numba.pydata.org/numba-doc/latest/user/stencil.html#mode) says:

> ### 1.11.4.2. mode
> The optional mode parameter controls how the border of the output array is handled.

However, `numba.stencil` does not actually have a parameter called `mode`. Its signature is

https://github.com/numba/numba/blob/6dfa610208f08fd17855f99f317aedf1d9b664a6/numba/stencil.py#L715

with `options` further defined in

https://github.com/numba/numba/blob/6dfa610208f08fd17855f99f317aedf1d9b664a6/numba/stencil.py#L724-L726

Consequently, trying the example under “basic usage” in the documentation with a `mode` parameter fails:

    from numba import stencil
    
    @stencil(mode='constant')
    def kernel1(a):
        return 0.25 * (a[0, 1] + a[1, 0] + a[0, -1] + a[-1, 0])
    
    # ValueError: Unknown stencil option mode

The correct syntax should be clarified in the documentation or an actual parameter `mode` should be added to the function.

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is a problem with the documentation, should be `func_or_mode`.

**Comment by cems2** [comment]
I found a different 100% reproducible bug in the same function @stencil

the treatment of the edge of the array (cval) is different when the return array is supplied with the optional "out" key word.

import numpy as np
import numba as nb

@nb.stencil(func_or_mode="constant",cval=7.0)
def stencil_d_dx(a):  
    return (a[0,0]-a[1,0])

a = np.ones([3,4])
ret = 9*np.ones([3,4])

print (stencil_d_dx(a))
print ("------")
stencil_d_dx(a,out=ret)
print (ret)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [7. 7. 7. 7.]]     # cval works correctly! 
------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [9. 9. 9. 9.]]  # cval is ignored and whatever value was in ret arrray is used.

You could fix this, or you could document this different effect.

I would suggest that you could make this behaviour the default, or you could add a new mode to handle the two possible actions (fill out-array with cvals, or leave it as supplied)

**Comment by stuartarchibald** [comment]
@cems2 thanks for the additional bug report, much appreicated, I've opened this as a new issue here https://github.com/numba/numba/issues/3518. In future it'd be really helpful if you could please open a new issue for each distinct bug as it makes it easier to track what gets fixed. Many thanks!

**Comment by cems2** [comment]
I will do so next time.  I was unsure since it was my first bug report.

I'll mention also There's A few things I'd like to understand better about @jit and @stencil that are not documented.

1.0  pitfall of using literal constants in @stencil

consider averaging matrices like this:

@nb.stencil()
def stencil_ave(a,b):
    return (a[0,0]+b[0,0])*0.5

The surprise is that 0.5 is a float64, so it up-converts float32 inputs to  float64 on the output.

So too keep float32 you have to write it like this:

@nb.stencil()
def stencil_ave(a,b):
    return (a[0,0]+b[0,0])*numpy.float32(0.5)

What I don't know is if @stencil will optimize out that constant numpy.float32(0.5)  or if every single time you call this the inner loop executes the function numpy.float32(0.5).

that is on a million element arrays you'd be calling that cast 1 million times!!!!

if  @stencil does not optimize it out, perhaps when you call the stencil from a subroutine decorated by @jit, it optimizes it out???

if not this is a nasty problem for using literal constants inside any @stencil

**Comment by cems2** [comment]
Here's an illustration of how stencils inherit python scalar operations for * and +  where as numpy overloads these

The surprise is the pythons + and * operators upconvert float32 to float64 in mixed types but numpy does not!!!


imagine you want to multiply a numpy.float32  array   "a"  by a constant (0.5).

you could do this very simply in numpy:   0.5*a  

of you could use a stencil like this:

@nb.stencil()
def constant_multiply(a,c): 
     return a[0]*c


constant_multiply (a,0.5)


The stencil method returns a float64 numpy array!!! 




import numpy as np
import numba as nb

@nb.stencil()
def constant_multiply(a): 
     return a[0]*0.5
    
DX = np.array([100,100],dtype=np.float32)

numpy_scale = DX*0.5
stencil_scale = constant_multiply(DX)

print("You might expect the following to be the same, but they are not")
print("numpy",numpy_scale.dtype)
print("stencil",stencil_scale.dtype)

    
# here's the explanation           
DX = np.array([100,100],dtype=np.float32)
iDX = 1.0*DX     # numpy overloads * to preserve dtype of float32

scalar = 1.0*DX[0]  # DX[0] is NOT a numpyfloat32.  it's a python float32.  
                    # python multiplies upconvert.  so you get float64
    
print("DX",DX.dtype)
print("iDX",iDX.dtype) 
print("python",scalar.dtype)

**Comment by cems2** [comment]
I filed this as a bug report even though it's a design bug (and thus arguable) not a code bug.

https://github.com/numba/numba/issues/3521 <https://github.com/numba/numba/issues/3521>
