### ISSUE TITLE
Numba nopython mode does not support numpy.cov

### ISSUE THREAD

**Issue by cjiang18** [numba/numba#3496]
It seems that numba's nopython mode does not support numpy.cov

Here is a minimal reproducer.
```
from numba import jit
import numpy as np

@jit(nopython=True)
def test (x):
    y=np.random.randn(x,100000)
    return np.cov(y)

if __name__ == '__main__':

    print(test(5))
```

**Comment by stuartarchibald** [comment]
Thanks for the request. This was added in https://github.com/numba/numba/pull/3345 and will make it into the next release. If you'd like to try it out before hand try a development package from the numba channel on https://anaconda.org (but please wait a few hours to try so we can promote some new builds with the feature in!):
```
$conda install -c numba numba
```

Closing.
