### ISSUE TITLE
Automatic Literal typing without automatic casting in lowerer

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3510]
## Reporting a bug

- [x] I am using the latest ~released~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The Const refactoring PR (#3414) causes Literal types in the signature if the code isn't guarding against it explicitly. Since the lowerer doesn't cast Literals automatically, the lowering function can't be found. The code below demonstrates the issue. Can the lowerer use two passes with and without literals like the typing stages?

```python
import numba
from numba import types
from numba.typing.templates import infer_global, signature, AbstractTemplate
from numba.extending import lower_builtin

def f(a, b):
    pass

@infer_global(f)
class FTyping(AbstractTemplate):
    def generic(self, args, kws):
        return signature(types.none, *args)

# @lower_builtin(f, types.IntegerLiteral, types.IntegerLiteral)
@lower_builtin(f, types.intp, types.intp)
def f_lower(context, builder, sig, args):
    return context.get_dummy_value()


@numba.njit
def g():
    f(1,3)

g()
```

**Comment by sklam** [comment]
I don't think it is a bug.  Typing should reject the literal signature or returning the unliteral'ed signature to force a cast.  To support the two passes approach, lowering will have to try doing a cast.  Implementation selection in lowering should be kept as simple as possible.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
