### ISSUE TITLE
Unused functions abort compilation

### ISSUE THREAD

**Issue by azelcer** [numba/numba#3517]
If an unused (never called) function is defined inside a JIT decorated function, an UnsuportedError is thrown.
Even if the workaround (commenting the unused definition) is very simple, I believe this should be taken as a bug,

Example (with fictitious useless functions)

```python
from numba import jit

@jit()
def NoFail(n):
    def minusone(p):
        return p-1
    return n*minusone(n) # minusone is called, no error thrown

@jit()
def Fail(n):
    def minusone(p): # this function is defined but never called
        return p-1
    return n*(n-1)

print NoFail(3)
print Fail(3) # error raised here
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm fairly sure this has been reported before, I'll have a look and see if I can cross reference the issue. The reason for what you are seeing is as follows...

1. In the `NoFail` function a call is made to the inner function, this means that type information can propagate to it *and* the compiler pass that inlines functions will be able to inline the inner function at the call site.
2. In the `Fail` function, as no call is made to the inner function there is no type information available (what type is `p`? how should it be compiled?) and there is no way or need to inline the function as it is not called, as a result the inner function remains as a declared but unused function. The result of this is that a `make_function` op code still exists in the `Fail` function at the time Numba's legalization compiler pass runs, this picks it up as something that is not supported and consequently raises the exception reported.

I think the way to fix this would be to run a dead code elimination pass prior to legalization. This pass ends up running (for other reasons) in the case of decorating the function with `@jit(parallel=True)` and as a result the code works fine!

```python
@jit(parallel=True)
def WorksDueToDCE(n):
    def minusone(p): # this function is defined but never called
        return p-1
    return n*(n-1)
```

**Comment by stuartarchibald** [comment]
Cross reference: https://github.com/numba/numba/issues/2866

**Comment by stuartarchibald** [comment]
This issue is now caught and trying to compile the above Failing function produces:
```
numba.errors.UnsupportedError: Failed in object mode pipeline (step: ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context: minusone (op code: make_function not supported). If the feature is explicitly supported it is likely that the result of the expression (minusone) is being used in an unsupported manner.
```

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
