### ISSUE TITLE
In the documentation, could you add examples of class definitions with ndarray arguments and output?

### ISSUE THREAD

**Issue by yuvallanger** [numba/numba#352]
I am not sure how it's done, if at all possible.
I only see examples with simple scalars as arguments and output.

Many thanks,
Yuval Langer.

**Comment by sklam** [comment]
[This page](http://numba.pydata.org/numba-doc/latest/user/jitclass.html?highlight=jitclass) contains the latest documentation of the ``@jitclass`` including using array types as class members. Array inputs and outputs in methods will be determined automatically by type inference. 

Closing.
