### ISSUE TITLE
Numba stencils unexpectedly upconvert float32 to float64 differently than numpy

### ISSUE THREAD

**Issue by cems2** [numba/numba#3521]
numba stencils  give unexpected different behavior from numpy when using float32 arrays and constant literals.

The problem is that because stencil syntax requires strictly scalar code (not array ops) they inherit python scalar operations for * and +  where as numpy overloads these and has a different behavior.

The surprise is the python's + and * operators always up convert float32 to float64 in mixed type operations  but numpy * and +  does not when a float64 operand is a scalar!

**Example:**  multiply a numpy.float32  array   "a"  by a constant (0.5).

 in numpy:   0.5*a     This will return a float32 array (even though 0.5 is a float64 literal) 

Now try the same thing with a stencil:
```
@nb.stencil()
def divide_by_two(a): 
    return a[0]*0.5   # stencils are always purely scalar operations

divide_by_two (a)
```
**Surprise: The stencil method returns a float64 numpy array!!!** 
This is because a[0] is a python scalar not a numpy array, therefore the "*" operator follows python rules not numpy rules for mixed types.

**Simple Workaround fails:**
 if you try to "Workaround" this by casting the float64 literal then you end up with something even worse:
```
@nb.stencil()
def divide_by_2(a): 
    return a[0]*np.float32(0.5)
```

What's the problem?  Well if a.size = 1000000 then you just put the cast np.float32(0.5) into the inner loop so it's called 1 million times.

**Workaround that works** but requires user knowledge of the issue to use successfully:
Don't use a literal in the expression
```
@nb.stencil()
def multiply(a,c=numpy.float32(0.5)): 
    return a[0]*np.float32(c)
```

pitfalls:
multiply(a,0.5)    # fails-- return float 64
multiply(a, numpy.float32(0.5) )  # works-- ugly.

thus stencils are hard to use if you need floating point literals in your expression.

SUGGESTED REMEDIES: 
  1.  create a new mode keyword called "cast literal constants to array dtype". 
  2.  Or  even better but harder to implement, "preserve numpy operator overload behaviors".

Here's some code that shows how this happens

```
import numpy as np
import numba as nb

@nb.stencil()
def constant_multiply(a): 
    return a[0]*0.5

DX = np.array([100,100],dtype=np.float32)

numpy_scale = DX*0.5
stencil_scale = constant_multiply(DX)

print("You might expect the following to be the same, but they are not")
print("numpy",numpy_scale.dtype)
print("stencil",stencil_scale.dtype)


# here's the explanation           
a = np.array([100,100],dtype=np.float32)
iDX = 1.0*a     # numpy overloads * to preserve dtype of float32

scalar = 1.0*a[0]  #a[0] is NOT a numpyfloat32.  it's a python float32.  
                   # python multiplies upconvert.  so you get float64
                # the syntax of the @stencil is always python scalars

print("a",a.dtype)
print("numpy",iDX.dtype) 
print("python",scalar.dtype)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think what you are seeing is invariant of `@stencil` and is just part of the choices made in the [type inference mechanism](http://numba.pydata.org/numba-doc/latest/glossary.html#term-type-inference). You can see what types the type inference mechanism has decided by using the `inspect_types` method on dispatcher objects (not going to work for `@stencil` IIRC as it is not implemented, there's lots of magic in `@stencil` and tracking types is hard!). For example:
```python
from numba import njit
import numpy as np

@njit
def foo(a): 
    return a[0] * 0.5

x = np.arange(5., dtype=np.float32)
foo(x)
foo.inspect_types()
```
gives:
```
foo (array(float32, 1d, C),)
--------------------------------------------------------------------------------
# File: issue3521.py
# --- LINE 4 --- 
# label 0

@njit

# --- LINE 5 --- 

def foo(a):

    # --- LINE 6 --- 
    #   a = arg(0, name=a)  :: array(float32, 1d, C)
    #   $const0.2 = const(int, 0)  :: Literal[int](0)
    #   $0.3 = static_getitem(value=a, index=0, index_var=$const0.2)  :: float32
    #   del a
    #   del $const0.2
    #   $const0.4 = const(float, 0.5)  :: float64
    #   $0.5 = $0.3 * $const0.4  :: float64
    #   del $const0.4
    #   del $0.3
    #   $0.6 = cast(value=$0.5)  :: float64
    #   del $0.5
    #   return $0.6

    return a[0] * 0.5


================================================================================
```
and from this the `float64` choice for the constant 0.5 can be seen as:
```
$const0.4 = const(float, 0.5)  :: float64
```
------------------------------------------------------------------------
__Regarding:__

> Simple Workaround fails:
   if you try to "Workaround" this by casting the float64 literal then you end up with something even worse:
   ``` 
   @nb.stencil()
   def divide_by_2(a): 
       return a[0]*np.float32(0.5)
   ```
> What's the problem? Well if a.size = 1000000 then you just put the cast np.float32(0.5) into the inner loop so it's called 1 million times.

It may seem like that, but thankfully Numba is backed by the LLVM compiler infrastructure. Therefore in creating the machine code to execute, LLVM will see that `np.float32(0.5)` is a loop invariant constant and so it will just get compiled down to a long literal or similar and hoisted out of the loop. Take a look at the assembly for this function `foo` using the `inspect_asm` method on the dispatcher object:
```python
from numba import njit
import numpy as np

@njit
def foo(a): 
    for i in range(len(a)):
        a[i] = a[i] * np.float32(0.5)

x = np.arange(5., dtype=np.float32)
foo(x)
print(foo.inspect_asm(foo.signatures[0]))
```
from the assembler, this is one of the definitions of a constant float of value 0.5 (it's repeated 4x so as to be useful in a packed single multiply `mulps` instruction):
```
.LCPI1_0:
        .long   1056964608
        .long   1056964608
        .long   1056964608
        .long   1056964608
        .section        .rodata.cst4,"aM",@progbits,4
        .p2align        2
```
and it's used in the unrolled loop multiply for `a[i] * np.float32(0.5)`:
```asm
.LBB1_17:
        movups  (%rcx,%rsi,4), %xmm0  ; move 4 single precision values from a[i] into %xmm0
        movups  16(%rcx,%rsi,4), %xmm1 ; move 4 more single precision data from a[i] + 16bytes, into %xmm1
        movabsq $.LCPI1_0, %rdx          ; move the 4x 0.5 values to %rdx
        movaps  (%rdx), %xmm2            ; move %rdx to %xmm2 vector register
        mulps   %xmm2, %xmm0            ; 4 way multiply, %xmm0 values by %xmm2
        mulps   %xmm2, %xmm1            ; 4 way multiply, %xmm1 values by %xmm2
```
------------------------------------------------------------------------
__Regarding:__
> Workaround that works but requires user knowledge of the issue to use successfully:
Don't use a literal in the expression
   ```
   @nb.stencil()
   def multiply(a,c=numpy.float32(0.5)): 
      return a[0]*np.float32(c)
   ```
> pitfalls:
   multiply(a,0.5) # fails-- return float 64
   multiply(a, numpy.float32(0.5) ) # works-- ugly.

Unfortunately I cannot replicate:
```python
import numba as nb
import numpy as np

@nb.stencil()
def multiply(a,c=np.float32(0.5)): 
    return a[0]*np.float32(c)

x = np.arange(5., dtype=np.float32)
print("Running: multiply(x, 0.5)")
z = multiply(x, 0.5)
print(z.dtype, z)

print("Running: np.float32(0.5)")
z = multiply(x, np.float32(0.5))
print(z.dtype, z)
```
gives:
```
Running: multiply(x, 0.5)
float32 [0.  0.5 1.  1.5 2. ]
Running: np.float32(0.5)
float32 [0.  0.5 1.  1.5 2. ]
```
--------------------------------------------
Finally, as to the handling of `float32` operations and behaviours with respect to Python/NumPy. There's often cases where `float32` is desirable as the default float type, for example on the GPU targets, related issue: https://github.com/numba/numba/issues/3377. I'll raise this issue of overloaded `*` at the next core developer meeting. Thanks.

**Comment by cems2** [comment]
Hi,
  I wanted to thank you for the extensive and educational responses.  I'm just learning my way with numba and I was really hesitant to report the anomolies I saw because I didn't want to create work for someone else.  But your responses have been both educational, collegial, and very encouraging.  So Thank for being all of those things.  

I'm a research scientist myself and I'm training some students on this too so I am passing along your lessons as well.

One of the aspects of all recompiles is it's obscure to the users just how to help it do it's job.  In this case, just how far will it look ahead to infer immutability and optimize it out.  You just told me it is clever on that.  

 There's just tonnes of things like that one wonders about.  is it easier or harder for @jit  to handle a stencil (implicit loop) versus an explicit python loop. How many layers deep in a nested set of function calls does @jit peek.  Is it better to parallelize inner loops or just the outer loop.  Is it better to pass in an empty array as a workspace for intermediate values or does @jit do a better job of allocating or optimizing out intermediate arrays than offering it a pre-allocated workspace to recycle.

Are there any docs somewhere that give one a mental model one can use to guess which types of algoirithm design ideas matter??

What I'm hoping for is that stencil, which is intentionally very restrictive in syntax, is better optimized by @jit calls to it than a freeforrm python loop would be.  On the otherhand since stencil doesn't know the loop sizes ahead of time it might be recompiling the kernel on each call!  I've been experimenting and so far I see the speed differences depend more on the array sizes than saying one way is always faster than another so I suspect it's because allocations of memory, and intermediate calculations, and call overheads are the long pole in the tent.  My mental models thus are not giving me intuition yet.


Finally, I realize that everything I have reported to you really is about documentation being missing or wrong.  Is it better to report that as a  suggestion or a bug?

**Comment by stuartarchibald** [comment]
@cems2 
>  I wanted to thank you for the extensive and educational responses. I'm just learning my way with numba and I was really hesitant to report the anomolies I saw because I didn't want to create work for someone else. But your responses have been both educational, collegial, and very encouraging. So Thank for being all of those things.

No problem, I'm glad that you found them useful and do please continue to report thing which appear anomalous, it's quite possible there's a design that needs changing or a bug.

>One of the aspects of all recompiles is it's obscure to the users just how to help it do it's job. In this case, just how far will it look ahead to infer immutability and optimize it out. You just told me it is clever on that.

Numba has two main challenges for compilation:
1. Figure out the types of everything in user defined code.
2. Having done 1. work out how to compile it.

To do this a giant pipeline of analysis and transforms is employed, if you are interested [this is some information about the compiler architecture](http://numba.pydata.org/numba-doc/latest/developer/architecture.html), it's a long read.

In the most general case, once Numba has created an intermediate representation (IR) of a decorated function it does some transforms on the IR (e.g. rewriting some classes of constant expressions, inlining closures). Following that it hands off the IR to the lowering implementation to translate the Numba IR into LLVM IR which is then optimised and compiled by LLVM itself. The question is therefore often "what will LLVM do with that generated IR?" and the answer is often "something pretty good".

>There's just tonnes of things like that one wonders about. is it easier or harder for @jit to handle a stencil (implicit loop) versus an explicit python loop.

For loops of the same iteration mechanism (i.e. both do `for ? in <same iterable class>`), chances are they'll compile down to approximately the same thing. The compiler pipeline employed for all the decorator types is v. similar (however `@jit(parallel=True)` is a different matter!) so the difference between e.g. a stencil loop and an explicit loop is essentially who wrote the code, for a stencil loop, the compiler generated the explicit loop for the user.

>How many layers deep in a nested set of function calls does @jit peek.

The `@jit` decorator does not operate recursively. To get the best performance `nopython` mode should be used `@jit(nopython=True)` (as a shortcut `from numba import njit; @njit` is an alias of this), then functions called by a `@njit` function should also be `@njit` decorated. Numba doesn't explicitly inline functions that are called, but it's highly likely that for all but the most involved functions LLVM will inline them.

> Is it better to parallelize inner loops or just the outer loop.

Unfortunately there's no way to provide a general answer to this, it will be entirely application specific, it would not be hard to invent good/bad cases for either! A piece of advice which sits at the top of the [performance tips page](http://numba.pydata.org/numba-doc/latest/user/performance-tips.html) is a good one:
```
"A reasonably effective approach to achieving high performance code is to profile
the code running with real data and use that to guide performance tuning."
```

> Is it better to pass in an empty array as a workspace for intermediate values or does @jit do a better job of allocating or optimizing out intermediate arrays than offering it a pre-allocated workspace to recycle.

Before going down the route of preallocated scratch spaces etc, I'd recommend following the quote above. However, Numba has a runtime which handles allocation, information about allocations and frees can be obtain by looking at:
```
from numba.runtime import rtsys
rtsys.get_allocation_stats()
```
for example:
```python
from numba import njit
from numba.runtime import rtsys
import numpy as np

@njit
def foo(n):
    x = np.arange(n)
    a = np.cos(x)
    b = np.sin(a)
    return b

foo(10)

print(rtsys.get_allocation_stats())
```
shows:
```
nrt_mstats(alloc=3, free=3, mi_alloc=3, mi_free=3)
```
which correlates with `x`, `a`, and `b` all having allocations assigned to them. If however `@njit(parallel=True)` is used, some rewrite passes run which look to optimise the allocations through shortcut deforestation techniques, this change leads to a single allocation being made in that function. Tracking this sort of transform in parallel mode is hard, but the latest [release candidate (0.41.0rc1)](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/cTp2RxGEOjo) has some [new tools to help](http://numba.pydata.org/numba-doc/dev/user/parallel.html#diagnostics).

> Are there any docs somewhere that give one a mental model one can use to guess which types of algoirithm design ideas matter??

I'm afraid I'm not really sure what it is you are asking for? If you've not looked at the [5 minute guide](http://numba.pydata.org/numba-doc/dev/user/5minguide.html) and [performance tips](http://numba.pydata.org/numba-doc/dev/user/performance-tips.html) pages they are a good place to start.

> Finally, I realize that everything I have reported to you really is about documentation being missing or wrong. Is it better to report that as a suggestion or a bug?

Either is fine thanks, we're always open to feedback and it can be recategorized as needed. If you've got questions etc that don't merit issues perhaps use the [mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/numba-users) or real time chat on [gitter.im](https://gitter.im/numba/numba).

Hope this helps.

**Comment by cems2** [comment]
Thanks and happy thanks giving.  I am looking forward to folllowing thevlinks  but not today!  I have already devoured the Numba site pages especially the intro material.  Thanks again.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
