### ISSUE TITLE
@njit is mentioned, but not explained, in chapter 1 of the user manual

### ISSUE THREAD

**Issue by Socob** [numba/numba#3523]
## Reporting a bug
In the [first chapter of the `numba` user manual](https://numba.pydata.org/numba-doc/latest/user/5minguide.html), section 1.1.7 reads as follows:

> ### 1.1.7. Other things of interest:
> Numba has quite a few decorators, we’ve seen `@jit` and `@njit`, but there’s also: 
> […]

However, at this point, `@njit` has never been mentioned in the user manual, let alone has it been explained what the difference between `@jit` and `@njit` is. In fact, this is the *only* mention of `@njit` in the first chapter. Only in [chapter 1.13 “Performance Tips”](https://numba.pydata.org/numba-doc/latest/user/performance-tips.html) does the missing explanation appear, hidden somewhere in the bulk text:

> To make it such that only no python mode is used and if compilation fails an exception is raised the decorators `@njit` and `@jit(nopython=True)` can be used (the first is an alias of the second for convenience).

`@njit` should either not be mentioned in the first chapter at all or its meaning should be explained there.

**Comment by stuartarchibald** [comment]
Thanks for the report, good point! Fixed in https://github.com/numba/numba/pull/3526

**Comment by sklam** [comment]
Closing. Fixed in #3526.
