### ISSUE TITLE
Anything else than os.cpu_count() for NUMBA_NUM_THREADS threated as 1

### ISSUE THREAD

**Issue by rfechtner** [numba/numba#3542]
I somehow cant utilize the NUMBA_NUM_THREADS enviroment variable. Given following simple structure:

**/package/_ _ init _ _.py** 
```
import os
os.environ["NUMBA_NUM_THREADS"] = "10"

import numba
```

**/package/tools/test.py**
```
from numba import njit, prange, config as nbconf
import os

def foo(large_number):
    print(os.environ["NUMBA_NUM_THREADS"])  # prints 10
    print(str(nbconf.NUMBA_NUM_THREADS))    # prints os.cpu_count()
    super_fancy_function(large_number)


@njit(parallel=True)
def super_fancy_function(large_number):
    for i in range(0, large_number):
        for j in prange(i+1, large_number):
             do_something()         
```

**/package/runner.py**
```
from tools import test

if __name__ == '__main__':
    test.foo(100000)
```

I set the NUMBA_NUM_THREADS variable before importing the numba module. But if I set it to a value lower than os.cpu_count() it will only spawn one thread (speed is same regardless of the value - but slower than without parallelization, thus I assume a threading layer is added but only with one thread). If I set it to os.cpu_count() all available threads are used. 

Other enviroment variables, such as "NUMBA_DEBUG" work.

I'm using numba 0.40.1 and python 3.7 [MSC v.1915 64 bit (AMD64)] on win32.

Any suggestions?

**Comment by stuartarchibald** [comment]
Thanks for the report. Is this still an issue on the latest version of Numba (0.51.2) ?

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
