### ISSUE TITLE
Function using np.roots and np.real doesn't compile with nopython=True

### ISSUE THREAD

**Issue by SteffenNa** [numba/numba#3568]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

 the following function does not compile
```
import numpy as np
from numba import hit
@numba.jit(nopython=True)
def alpha_numba(beta: float, rho: float, nu: float, F: float, atmVol: float, t: float) -> float:
    x1 = ((1 - beta) ** 2 * t) / (24 * F ** (2 - 2 * beta))
    x2 = (rho * beta * nu * t) / (4 * F ** (1 - beta))
    x3 = 1 + ((2 - 3 * rho ** 2) * nu ** 2 * t) / 24
    x4 = -atmVol * F ** (1 - beta)
    rts = np.real(np.roots([x1, x2, x3, x4]))
    alpha = np.min(rts[rts > 0])
    return alpha

alpha_numba(0.5, 0.070762, 4.273053, 120.3275, 0.0375, 0.04)
```

throws the following error:

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-4-8d8335fb2e22> in <module>
----> 1 alpha_numba(0.5, 0.070762, 4.273053, 120.3275, 0.0375, 0.04)

~/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    346                 e.patch_message(msg)
    347 
--> 348             error_rewrite(e, 'typing')
    349         except errors.UnsupportedError as e:
    350             # Something unsupported is present in the user code, add help info

~/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

~/miniconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function roots at 0x110714c80>) with argument(s) of type(s): (list(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type list(float64)

File "../../miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py", line 29:
    def roots_impl(p):
        <source elided>

        if len(p.shape) != 1:
        ^

[1] During: typing of get attribute at /Users/steffen/miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py (29)

File "../../miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py", line 29:
    def roots_impl(p):
        <source elided>

        if len(p.shape) != 1:
        ^

    raised from /Users/steffen/miniconda3/lib/python3.7/site-packages/numba/typeinfer.py:860
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type list(float64)

File "../../miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py", line 29:
    def roots_impl(p):
        <source elided>

        if len(p.shape) != 1:
        ^

[1] During: typing of get attribute at /Users/steffen/miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py (29)

File "../../miniconda3/lib/python3.7/site-packages/numba/targets/polynomial.py", line 29:
    def roots_impl(p):
        <source elided>

        if len(p.shape) != 1:
        ^

    raised from /Users/steffen/miniconda3/lib/python3.7/site-packages/numba/typeinfer.py:860
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function roots at 0x110714c80>)
[2] During: typing of call at <ipython-input-3-652e405b9ca3> (7)

File "<ipython-input-3-652e405b9ca3>", line 7:
def alpha_numba(beta: float, rho: float, nu: float, F: float, atmVol: float, t: float) -> float:
    <source elided>
    x4 = -atmVol * F ** (1 - beta)
    rts = np.real(np.roots([x1, x2, x3, x4]))
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

Since `np.real` and `np.roots` seem to be supported I suspect this is a bug indeed. Using latest releases of numpy, numba and python 3.7.1

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is because the code is passing a list to `np.roots` and the implementation expects a `numpy.ndarray`. Further, in fixing this, the roots implementation calls eigenvalue routines which require the domain type to be unchanged across the call (real space in -> real space out, complex space in -> complex space out), this is due having to compute a return type for the output determined solely on the type of the input and what is done with it.

This should work:
```python
import numpy as np
from numba import jit
@jit(nopython=True)
def alpha_numba(beta: float, rho: float, nu: float, F: float, atmVol: float, t: float) -> float:
    x1 = ((1 - beta) ** 2 * t) / (24 * F ** (2 - 2 * beta))
    x2 = (rho * beta * nu * t) / (4 * F ** (1 - beta))
    x3 = 1 + ((2 - 3 * rho ** 2) * nu ** 2 * t) / 24
    x4 = -atmVol * F ** (1 - beta)
    # coeffs are now in an array, and the dtype is complex space.
    rts = np.real(np.roots(np.array([x1, x2, x3, x4], dtype=np.complex128)))
    alpha = np.min(rts[rts > 0])
    return alpha

alpha_numba(0.5, 0.070762, 4.273053, 120.3275, 0.0375, 0.04)
```

**Comment by SteffenNa** [comment]
Fantastic! Thanks so much! Works beautifully and is about 10x faster than pure Numpy.
Also thanks guys for this amazing package.

**Comment by stuartarchibald** [comment]
No problem. Glad you got your code working.
