### ISSUE TITLE
Error in documentation of numba.objmode context manager

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#3575]
I was trying to play with the new context manager that should allow executing python code in a compiled (nopython-) numba function and was surprised to find that the example in the documentation did not run. Here is a fixed version:

```
import numpy as np
from numba import njit, objmode

def bar(x):
    # This code is executed by the interpreter.
    return np.asarray(list(reversed(x.tolist())))

@njit
def foo():
    x = np.arange(5)
    with objmode(x='intp[:]'):  # annotate return type
        # this region is executed by object-mode.
        x += bar(x)
    return x

foo()
```
I changed all variable names `y` to `x` (in three places) and I added a closing bracket to the `bar` function body.

**Comment by stuartarchibald** [comment]
Thanks for the report. Fixed in https://github.com/numba/numba/pull/3577
