### ISSUE TITLE
is None construct in nopython mode

### ISSUE THREAD

**Issue by fingoldo** [numba/numba#3585]
Hello team,
is this a well-known fact that **is None** construct behaves differently in nopython mode?
My code snippet:
``` python
if weights is not None:
        for i,v in enumerate(theSlice):
            weighted_mean=weighted_mean+v*weights[i]
```
When prepended with @numba.jit(), it executes just fine with weights set to None (by default).
However when using @numba.njit(fastmath=True), same call fails with error:

**Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (none, int64)**

Obviously it tries to index None, looks like in nopython mode  is None construct behaves not as expected. What is the correct way? Or is this a bug?

**Comment by stuartarchibald** [comment]
Thanks for the report. Can it be assumed that this represents the issue you are seeing? :
```python
from numba import njit
import numpy as np

def foo(weights, theSlice):
    weighted_mean = 0
    if weights is not None:
        for i, v in enumerate(theSlice):
            weighted_mean=weighted_mean+v*weights[i]
    return weighted_mean

n = 4
w = np.ones((n,))
ts = np.arange(n)
print((njit)(foo)(None, ts))
```
I think what you are seeing is the impact of type inference not specialising on a branch, the assumption is made that weights is indexable (`weights[i]`) irrespective of the condition, and as `None` is not indexable it fails to compile. [`generated_jit`](http://numba.pydata.org/numba-doc/latest/user/generated-jit.html) can help with this:

```python
from numba import njit, generated_jit, types
import numpy as np

@generated_jit(nopython=True)
def foo(weights, theSlice):

    if isinstance(weights, types.NoneType):
        def weights_is_none_impl(weights, theSlice):
            weighted_mean = 0
            return weighted_mean
        return weights_is_none_impl
    else:
        def weights_not_none_impl(weights, theSlice):
            weighted_mean = 0
            for i, v in enumerate(theSlice):
                weighted_mean=weighted_mean+v*weights[i]
            return weighted_mean
        return weights_not_none_impl

n = 4
w = np.ones((n,))
ts = np.arange(n)
print(foo(None, ts))
print(foo(w, ts))
```

**Comment by fingoldo** [comment]
Thank you so much Stuart for the quick and useful reply. I did not know about generated_jit, I get it that such types of issues stem from the very project architecture, are probably unavoidable and not generally fixable (for untrained public like me)? for now I have solved the issue by passing in empty list instead of None and by checking its length, but in future I will have generated_jit in mind :-)

**Comment by stuartarchibald** [comment]
As of Numba 0.43 this sort of thing now just-works with no workaround needed for handling `None`, see the `For Developers` section of this notebook relating to the 0.43 release https://github.com/numba/numba-examples/blob/master/notebooks/Numba_043_release_demo.ipynb

**Comment by analog-cbarber** [comment]
Hmm. I have a function with an `is None` branch that is not being executed on 0.43 when it should be (and was in 0.41).

**Comment by stuartarchibald** [comment]
@analog-cbarber please could you share a minimal example in a new ticket... thanks.

**Comment by analog-cbarber** [comment]
Yes, when I have the time. For now, I am falling back to 0.41.

**Comment by stuartarchibald** [comment]
@analog-cbarber thanks very much, it'd be super helpful. If you are short of time, a larger than minimal-working-example would also be fine. Thanks again.

**Comment by analog-cbarber** [comment]
done: https://github.com/numba/numba/issues/3879
