### ISSUE TITLE
empty_inferred typing error

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3586]
## Reporting a bug

- [x] I am using the latest ~released~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Type inference doesn't work for this code. Any idea why?

```python
import numba

@numba.njit
def f():
    S = numba.unsafe.ndarray.empty_inferred((10,))
    a = 1.1
    for i in range(len(S)):
        S[i] = a+2
    return S

f()
```
```
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot infer the type of variable 'S', have imprecise type: array(undefined, 1d, C).

File "test_rm_emptyinferred.py", line 9:
def f():
    S = numba.unsafe.ndarray.empty_inferred((10,))
    ^
```

**Comment by sklam** [comment]
I found that the issue is due to this part:
```python
    for i in range(len(S)):
        S[i] = a+2
```

Where `S[i] = a+2` would "refine" the type for `S` but the typing cannot occur because it cannot deduce the type of `i`.  The chain goes like:

```
typeof i -> typeof range(len(S)) -> typeof len(S)
```
`len(S)` cannot be deduced.  However, if the loop is written as:

```
for i in range(10):
        S[i] = a+2
```
the function will and should work.

**Comment by sklam** [comment]
`range(S.size)` also works
