### ISSUE TITLE
User defined exceptions in numba 0.41

### ISSUE THREAD

**Issue by esheldon** [numba/numba#3613]
I apologize that I cannot give a simple reproducible version of the issue.  It happens in a complex code base that I can't expect you to install. I have not seen the error in other contexts, for example when I just run snippet below by itself, outside of the application.  This code works in 0.40, and this code has in fact been running in production for quite some time.  I've tested using python 3.6 and 3.7

The overall context is a run of scipy `leastsq`.  An exception is raised by numba, and this occurs in one of the function evaluations.  It does not occur the first time this function is called, it occurs after a few hundred or thousand calls.  The input to the function is the same type every time and there is nothing special that I can see about the situation when the exception is raised.

The function takes a numpy array with fields as an argument and writes some values into it.

When the exception is raised occurs, it is giving this error
```
Untyped global name 'gauss2d_set_norm': cannot determine Numba type of <class 'function'>

File "../../../../../../../gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/cosmos/lib/python3.7/site-packages/ngmix/gmix_nb.py", line 183:
def gmix_set_norms(gmix):
    <source elided>
    for gauss in gmix:
        gauss2d_set_norm(gauss)
```
It seems that perhaps numba has forgotten that it has already compiled this function, and is trying to determine its type again.

Here is the function. 
```python
@njit
def gauss2d_set_norm(gauss):
    """
    set the normalization, and nromalized variances

    A GMixRangeError is raised if the determinant is too small

    parameters
    ----------
    gauss: a 2-d gaussian structure
        See gmix.py
    """

    if gauss['det'] < GMIX_LOW_DETVAL:
        raise GMixRangeError("det too low")

    T=gauss['irr']+gauss['icc']
    if T <= GMIX_LOW_DETVAL:
        raise GMixRangeError("T too low")

    idet=1.0/gauss['det']
    gauss['drr'] = gauss['irr']*idet
    gauss['drc'] = gauss['irc']*idet
    gauss['dcc'] = gauss['icc']*idet
    gauss['norm'] = 1./(2*numpy.pi*numpy.sqrt(gauss['det']))

    gauss['pnorm'] = gauss['p']*gauss['norm']

    gauss['norm_set']=1
```
 The input is an element of an array, e.g. I create an array and am sending it an element, such as follows:

```python
gmix=np.zeros(n, dtype=dtype)
# do some initialization of the data

# call the function on each element
for gauss in gmix:
    gauss2d_set_norm(gauss)
```

**Comment by sklam** [comment]
> Untyped global name 'gauss2d_set_norm': cannot determine Numba type of <class 'function'>

That is a compile error at `gmix_set_norms`.  It is as if `gauss2d_set_norm` is not decorated with `@njit`.        You may want to go into the debugger (i.e. pdb) when that error occurs and poke around the global dictionary to see what `gauss2d_set_norm` is at that point.

**Comment by esheldon** [comment]
I hacked on the code to try to get a more clear error message indicating that the problem is associated with numba, I might have done too much hacking.

If I run my code without changes I see this error.
```
TypeError: __init__() missing 1 required positional argument: 'value'
```
However, this error message makes no sense when examined at face value.  It  occurs calling a numba defined function (there are no constructors called in the function where the error occurs).  In fact the error is coming from numba,  deeper in the code when it tries to call the function I mentioned above, but somehow the error is not propagated as expected.

**Comment by stuartarchibald** [comment]
@esheldon Any chance you could please try and get some back traces from the locations the errors are coming from to help diagnose what's going on? Many thanks.

**Comment by esheldon** [comment]
Here is the full Traceback back. It does not show that the error is bubbling up from numba
```
Traceback (most recent call last):
  File "/home/esheldon/anaconda3/envs/numbabug/bin/fitcosmos", line 30, in <module>
    main()
  File "/home/esheldon/anaconda3/envs/numbabug/bin/fitcosmos", line 27, in main
    processor.go()
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/process.py", line 51, in go
    output, epochs_data = self._process_fof(fofid)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/process.py", line 104, in _process_fof
    output, epochs_data = self.fitter.go(mbobs_list)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/fitting.py", line 174, in go
    _fit_all_psfs(mbobs_list, self['mof']['psf'])
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/fitting.py", line 392, in _fit_all_psfs
    fitter.go()
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/fitting.py", line 412, in go
    _fit_one_psf(psf_obs, self.psf_conf)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/fitcosmos/fitting.py", line 435, in _fit_one_psf
    runner.go(ntry=pconf['ntry'])
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/ngmix/bootstrap.py", line 2282, in go
    fitter.go(guess)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/ngmix/fitting.py", line 1681, in go
    **self.lm_pars
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/ngmix/fitting.py", line 1989, in run_leastsq
    lm_tup = leastsq(func, guess, full_output=1, **keys)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 394, in leastsq
    gtol, maxfev, epsfcn, factor, diag)
  File "/home/esheldon/anaconda3/envs/numbabug/lib/python3.7/site-packages/ngmix/fitting.py", line 1805, in _calc_fdiff
    start,
TypeError: __init__() missing 1 required positional argument: 'value'
```
That error at line 1805 is a call to a numba compiled function.  Again, the function gets called hundreds or thousands of times before the exception is raised.  The types entered to the functions are the same every time.

**Comment by esheldon** [comment]
OK, I've traced it to raising an exception in the numba compiled function.  If I comment out the `raise GMixRangeError` from below the error does not occur.

Note the error above is saying `TypeError: __init__() missing 1 required positional argument: 'value'`. Is it possible the raise of that exception is being rewritten by numba?

I also tried raising `ValueError` instead of my user defined exception and that propagates up properly.

```python
@njit
def gauss2d_set_norm(gauss):
    """
    set the normalization, and nromalized variances

    A GMixRangeError is raised if the determinant is too small

    parameters
    ----------
    gauss: a 2-d gaussian structure
        See gmix.py
    """

    if gauss['det'] < GMIX_LOW_DETVAL:
        raise GMixRangeError("det too low")

    T=gauss['irr']+gauss['icc']
    if T <= GMIX_LOW_DETVAL:
        raise GMixRangeError("T too low")

    idet=1.0/gauss['det']
    gauss['drr'] = gauss['irr']*idet
    gauss['drc'] = gauss['irc']*idet
    gauss['dcc'] = gauss['icc']*idet
    gauss['norm'] = 1./(2*numpy.pi*numpy.sqrt(gauss['det']))

    gauss['pnorm'] = gauss['p']*gauss['norm']

    gauss['norm_set']=1
```

**Comment by esheldon** [comment]
Definition of my  exception class
```python
class GMixRangeError(Exception):
    """
    Some number was out of range
    """
    def __init__(self, value):
        super(GMixRangeError, self).__init__(value)
        self.value = value

    def __str__(self):
        return repr(self.value)
```

**Comment by stuartarchibald** [comment]
@esheldon thanks for doing that. The Numba exception code was rewritten in 0.41 to include synthetic stack frame injection, expect it's related to that. Will take a look.

**Comment by stuartarchibald** [comment]
ok, that's the problem. Reproducer:
```python
from numba import njit

class UDE(Exception):
    def __init__(self, value):
        super(UDE, self).__init__(value)
        self.value = value

    def __str__(self):
        return repr(self.value)

@njit
def foo(x):
    if x < 0:
        raise UDE("error message")


foo(10)
foo(-1)
```
Numba 0.38 (because I have that to hand) works ok, but it's broken on 0.41.

**Comment by esheldon** [comment]
Thanks. Sorry for my initial specification of this issue, which was I think misleading.

**Comment by stuartarchibald** [comment]
No problem, thanks for reporting, it wasn't clear at the outset what the cause was. The problem is this line:
https://github.com/numba/numba/blob/6c890ead1b9dc4501dbbb057fff46748115a2b0d/numba/_helperlib.c#L922
at this point in the code we've unpacked the exception info tuple, figured out that it's a UDE class that needs to be instantiated, and then it ends up being called without the unpacked arguments, hence error.
