### ISSUE TITLE
FakeCUDAAtomic Add, Min and Max methods do not return the old value

### ISSUE THREAD

**Issue by stephenjelfs-gd** [numba/numba#3619]
FakeCUDAAtomic Add, Min and Max methods do not return the old values, as expected:

```
class FakeCUDAAtomic(object):
    def add(self, array, index, val):
        with addlock:
            array[index] += val
```

Instead these methods always return None.  Only compare_and_swap works as expected.

**Comment by namanbiyani** [comment]
Hi i want to solve this bug . As this is my first issue , can u please give me some guidelines?
