### ISSUE TITLE
Issue with list comprehension

### ISSUE THREAD

**Issue by joltinwhite** [numba/numba#3623]
Received an error for  the following function:

`@jit(nopython=True)`
`def makeGrid(num):`
`    grid = [np.array([x,y,0]) for x in np.linspace(-2.5,2.5,num) for y in np.linspace(-2.5,2.5,num)]`
`    return grid`    
    

Here is my build of numba:

# Name                    Version                   Build  Channel
numba                     0.38.0           py36h637b7d7_0

**Comment by seibert** [comment]
Support for lists of arrays in nopython mode requires Numba 0.39 and later.

**Comment by stuartarchibald** [comment]
Closing as upgrade will fix.
