### ISSUE TITLE
why not  I can complie the code using numba.jit 

### ISSUE THREAD

**Issue by Julia1211** [numba/numba#3628]
this is my code ,I couldn't complie the code,and I don't know how to modify it.

@jit(nopython=True)
def Feature_fun():
    for sliz in range(z1, z2 + 1):
        inputz = np.asarray(image[sliz], np.float32)
        fz = f[:, :, :60]
        weights = np.asarray(fz, np.float32)
        res = my_conv2d(inputz, weights, bounds, 2)
        for fil in range(0, 60):
            for dcmy in range(0, rangey):
                for dcmx in range(0, rangex):
                    responses[dcmx + dcmy * (rangex)][sliz - z1][fil] = res[dcmx][dcmy][fil]
                    airportPosition = [x1 + dcmx, y1 + dcmy, sliz]
                    distances = np.sqrt(np.sum(np.asarray(airportPosition - boundary) ** 2, axis=1))
                    mindis = np.min(distances)
                    responses[dcmx + dcmy * (rangex)][sliz - z1][142] = mindis

and this is the Error prompt :
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.asarray' or unsupported use of the function.

File "Main.py", line 311:
def Feature_fun():
    <source elided>
    for sliz in range(z1, z2 + 1):
        inputz = np.asarray(image[sliz], np.float32)
        ^

[1] During: typing of get attribute at F:/daydayup/DosePlan/Doseplan14GPU2/Main.py (311)

**Comment by stuartarchibald** [comment]
Thanks for the report. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

In the code presented, as indicated by the error message, `numpy.asarray` is unsupported/the use of it is unsupported. This https://github.com/numba/numba/pull/3598 is work towards supporting `numpy.asarray` and it should make it into the next release (0.43.0).

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/3598 is merged, closing.
