### ISSUE TITLE
Problem with installing numba Version 0.11 on osx 10.8.5 Python 2.7.3

### ISSUE THREAD

**Issue by mesuvash** [numba/numba#363]
I got following error when i tried to upgrade numba 0.10 to 0.11

gcc -bundle -undefined dynamic_lookup -g -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.o build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime.o build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime_strings.o -o build/lib.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.so

duplicate symbol __days_per_month_table in:

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.o

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime.o

duplicate symbol __datetime_strings in:

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.o

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime.o

duplicate symbol __datetime_strings in:

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.o

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime_strings.o

duplicate symbol __days_per_month_table in:

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/utilities.o

    build/temp.macosx-10.5-x86_64-2.7/numba/external/utilities/datetime/np_datetime_strings.o

ld: 4 duplicate symbols for architecture x86_64

collect2: ld returned 1 exit status

error: command 'gcc' failed with exit status 1

**Comment by pitrou** [comment]
This is outdated, closing.
