### ISSUE TITLE
Forcing parallel and nogil for CC

### ISSUE THREAD

**Issue by max3-2** [numba/numba#3635]
## Feature request

I am starting to use more CC to speed up some computations. Compared to the jit routines, I cannot find informations on how cc.export handles GIL and parallel. Are those by default True since its a C library? When importing and running, what defines the number of allowed threads? Will this still be the numba.config?

Thus, this is a request for a better doc I guess :)

**Comment by stuartarchibald** [comment]
Related issue: https://github.com/numba/numba/issues/3336
