### ISSUE TITLE
Dictionary support

### ISSUE THREAD

**Issue by seibert** [numba/numba#3644]
This issue is for tracking progress on support for dictionaries in nopython mode, one of the 2019 tasks on the [roadmap](http://numba.pydata.org/numba-doc/latest/developer/roadmap.html#short-term-2019h1).

## Goals

- Statically typed (both key and value) Python-like *ordered* dictionary object with nopython-mode storage (i.e., no python objects in the dictionary)
- Create a Python wrapper for using Numba dict from Python interpreter
- Functions that use Numba dict still need to be cacheable (ex: jitclass implementation would prevent caching currently)
- Extension mechanism to register a hashing function for a Numba type
- Python dict <-> Numba dict conversion functions
- Option to mark dictionary as immutable
- Hashing should respect PYTHONHASHSEED
- Python 2.7 support (unless we discover it adds significant work)
- Implement `__getitem__` in nopython mode rather than C to enable LLVM inlining in loops.

## Anti-Goals

- Reflection back to a Python object
- Identical performance to Python dictionary in interpreter(impossible because of need to box/unbox keys and values)
- nopython mode performance as fast as Python dict (Python dict is highly tuned, but Numba does need to be reasonable)
- Heterogenous types (for key or value)
- Hashing functions which return identical values to Python

## Steps

1. [x] Research Python 3.7 ordered dict implementation
2. [x] Refactor hashing to prepare for key hashing
3. [x] Add hashing function for unicode strings
4. [x] Numba dict (only in nopython mode) with just `__getitem__`, `__setitem__`, `__delitem__`, and `__contains__` implemented and explict type declaration (`ndict(key=int32, value=yoloclass)`).
5. [x] Implement remaining dictionary methods using core methods.
6. [x] Python dict <-> Numba dict converters
7. [x] Python wrapper around Numba dict (C extension for performance)
8. [x] Type inference of key and value types

**Comment by seibert** [comment]
Useful reading on Python dictionary internals:

* https://mail.python.org/pipermail/python-dev/2012-December/123028.html
* https://morepypy.blogspot.com/2015/01/faster-more-memory-efficient-and-more.html
* https://github.com/python/cpython/blob/master/Objects/dictnotes.txt
* https://github.com/python/cpython/blob/master/Objects/dict-common.h
* https://github.com/python/cpython/blob/master/Objects/dictobject.c

**Comment by cristipurdel** [comment]
Any chance of being available in vectorize form?
As input and output, also with cuda support?

**Comment by seibert** [comment]
Can you explain more what you mean about being "available in vectorize form"?

CUDA support is interesting.  As specified, no, because adding/removing elements to the dictionary requires memory allocation/deallocation, which we do not allow in GPU code on purpose.  However, when we introduce an immutable dictionary as a type, we could potentially support that on the GPU.

**Comment by cristipurdel** [comment]
Being able to use it with @vectorize decorator, in order to reduce the performance gap with guvectorize.
Vectorize is really fast for scalar calculations, but it would be nice to increase the complexity, especially on the gpu

**Comment by cristipurdel** [comment]
> 
> 
> Can you explain more what you mean about being "available in vectorize form"?
> 
> CUDA support is interesting. As specified, no, because adding/removing elements to the dictionary requires memory allocation/deallocation, which we do not allow in GPU code on purpose. However, when we introduce an immutable dictionary as a type, we could potentially support that on the GPU.

Is it possible to introduce an immutable tuple as a type for GPU?
I know it is working for jit decorator, but not for `vectorize`
I do feel that tuple support in GPU should have prio over dictionary, in order not to use only scalar operations in `vectorize`. If you agree, please open an issue/PR

**Comment by GiorgioBalestrieri** [comment]
Hi, is this planned as part of 43.0?

By the way, this is truly awesome, and it's going to make many applications so much easier.

**Comment by seibert** [comment]
Yes, the main new feature of 0.43 will be dictionaries.  (We will hold 0.43 until they are ready, although we don't foresee a delay at the moment.)

**Comment by hamkz** [comment]
Just asking, approximately when will 0.43 be available? Have been waiting for dictionary support for a while and will be excited to see that. :)

**Comment by GiorgioBalestrieri** [comment]
@hamkz FYI, 43.0 was just released

**Comment by seibert** [comment]
Still in process, but yes, we're working on the release now.  :)  (See #3858 for our checklist)

**Comment by seibert** [comment]
The last item (automatic type inference of key and value types) is what we will work on for next release.

**Comment by GiorgioBalestrieri** [comment]
thanks for the clarification! I see 43.0 in the [releases page](https://github.com/numba/numba/releases) as well as on [conda](https://anaconda.org/numba/numba). 
Does this mean dictionary are not fully functional or that the release is not stable?

**Comment by seibert** [comment]
The release is stable, but we build packages for a lot of platform combinations, and run them through a bunch of tests, so it takes about a day to complete.  Dictionaries will work as described in the documentation (the docs site will be updated today as well).  The main limitation of dictionaries in 0.43 is that you will need to explicitly list the key and value type.  Eventually we want Numba to infer those types from code like:
```
d = {}
d[1] = 'one'  # Numba will assume that dictionary has key of type int and value of type str going forward
```
but that is not available yet.

**Comment by GiorgioBalestrieri** [comment]
ok, thank you again for the explanation - and the awesome work with numba! Dictionary support is really a game changer, and type inference will make it even better.

**Comment by GiorgioBalestrieri** [comment]
@seibert I see 0.43.0 available on Anaconda https://anaconda.org/numba/numba
but I'm not able to conda-install it. 

Running
`conda update numba` won't update my existing 0.39.0 version, and 
`conda install numba==0.43.0` complains it can't find the specified version

Any tips?

**Comment by seibert** [comment]
Correct.  We (the Numba dev team) build packages in the `numba` channel using our build & test computers so people can try things out quickly.  The official Anaconda Distribution packages are built by another team at Anaconda for distribution in the defaults channel, usually with a delay of a few days to a week.

**Comment by richardxing** [comment]
@seibert @stuartarchibald 
Is global typed dictionary supported in nopython mode now?

**Comment by stuartarchibald** [comment]
@richardxing no, there's no way to lower it as a constant value. https://github.com/numba/numba/pull/4070 should catch this issue and report it.

**Comment by stuartarchibald** [comment]
@seibert @sklam can we close this ticket now?

**Comment by sklam** [comment]
Yes, closing
