### ISSUE TITLE
How to write a cuda kernel function that performs a regression（least square estimator ）for each thread?

### ISSUE THREAD

**Issue by zengxiaoqing** [numba/numba#3647]
How to write a cuda kernel function that performs a regression（least square estimator ） for each thread?

I have 1 million points, each with 30 samples and 2 features. I want to use the @cuda.jit function in numba to model the regression model for each point.

That is, using a least squares method at each point (each thread in cuda) to create a regression model,

The result returns one million regression model coefficients, two features with three coefficients (including constant terms)

**Comment by stuartarchibald** [comment]
Thanks for the query. I think this is perhaps more of a question for e.g. https://stackoverflow.com ? `@cuda.jit` will certainly allow such a piece of code to be written, but the scope of the actual implementation is beyond that which is covered in the Numba issue tracker. Perhaps as a start familiarise yourself with the Numba `cuda.jit` through the GTC 2017 tutorial notebooks here: https://github.com/ContinuumIO/gtc2017-numba

**Comment by zengxiaoqing** [comment]
Can you teach me how to get it? I have been troubled by this problem for a long time. I have tried many methods.

> Thanks for the query. I think this is perhaps more of a question for e.g. https://stackoverflow.com ? `@cuda.jit` will certainly allow such a piece of code to be written, but the scope of the actual implementation is beyond that which is covered in the Numba issue tracker. Perhaps as a start familiarise yourself with the Numba `cuda.jit` through the GTC 2017 tutorial notebooks here: https://github.com/ContinuumIO/gtc2017-numba

**Comment by isaac-you** [comment]
@zengxiaoqing  Do you find the answer to your question? I am also interested in this question. Thank you.
