### ISSUE TITLE
nopython mode -- numpy.where function not working with True/False yield values supplied

### ISSUE THREAD

**Issue by ToddJacobus** [numba/numba#3650]
This works just fine in regular numpy:

```
def modifyArray(array):
    return np.where(np.logical_or(array > 8, array < 2), array, 0)

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

mod_array = modifyArray(array)

print(mod_array)
```
Returns:
```
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 9]])
```

However, this fails when wrapped with `@jit(nopython=True)`:

```
@jit(nopython=True)
def modifyArray(array):
    return np.where(np.logical_or(array > 8, array < 2), array, 0)

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

mod_array = modifyArray(array)

print(mod_array)
```
returns: 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function where>) with argument(s) of type(s): (array(bool, 2d, C), array(int32, 2d, C), Literal[int](0))
 * parameterized
In definition 0:
    AttributeError: 'IntegerLiteral' object has no attribute 'ndim'
```

According to the [documentation](https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html), the numpy 'where()' function is supported and no special stipulations are outlined for the parameters.  Is this an issue with Numba, or is the documentation not clearly outlining specific usage?

I should note, that I got the numpy where() function to work in nopython mode if only the condition parameter was passed in, not the True/False yield values.  Thanks everyone very much for your help and in the continued development of Numba!

Todd

**Comment by rjenc29** [comment]
Hi

As a workaround, this should return what you expect:

```python
@jit(nopython=True)
def modifyArray(array):
    return np.where(np.logical_or(array > 8, array < 2), array, np.zeros_like(array))
```

Hope this helps.

@stuartarchibald I can fold this into #3630 or pick it up separately if it helps - ping me when you have a mo.

**Comment by stuartarchibald** [comment]
@rjenc29 thanks, I think it could go into #3630 if you are happy to do that? Seems like a small extension of what is already present?

**Comment by ToddJacobus** [comment]
@rjenc29 Thanks for the work-around.  This seems to perform just fine.  I really appreciate everyone's contributions here!

**Comment by stuartarchibald** [comment]
This works as of Numba 0.43.0, closing.
