### ISSUE TITLE
Return of tuple with optional type

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3653]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Regular optional return of `int64` works:
```python
@numba.njit
def f(a, b):
    if a:
        return b
    return None
print(f(True, 1))
```
But if `int64` is in a tuple it doesn't work:
```python
@numba.njit
def f(a, b):
    if a:
        return b, 0
    return None, 0
```
```
TypeError: cannot convert native ?int64 to Python object
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce, `SystemError` is raised, this needs looking at.
```
$ python issue3653.py 
TypeError: cannot convert native ?int64 to Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue3653.py", line 9, in <module>
    print(f(True, 1))
SystemError: CPUDispatcher(<function f at 0x7f791a789268>) returned a result with an error set
```

**Comment by stuartarchibald** [comment]
As of Numba 0.43 this now works as expected. Closing.
