### ISSUE TITLE
List of lists with array type error

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3654]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Type inference fails for list of lists that includes an array:
```python
import numba
import numpy as np

@numba.njit
def f():
    l = []
    for i in range(10):
        A = np.arange(i)
        l.append([i, A])
    return l


print(f())
```
```
Cannot infer the type of variable 'l', have imprecise type: list(undefined).
```

**Comment by ehsantn** [comment]
Yes, you are right. I got confused with the tuple version of this. The error message could be improved to indicate the non-homogeneous list issue.

**Comment by stuartarchibald** [comment]
hmmm, I don't think we have something to explicitly detect and report that a list is inhomogeneous, should be possible though, if a variable is undefined and a list there's a fair chance that the types of the variables in the list could be traced. https://github.com/numba/numba/issues/3664 to track.

**Comment by ehsantn** [comment]
Thanks.
