### ISSUE TITLE
KeyError when caching with multiple files

### ISSUE THREAD

**Issue by jeffspence** [numba/numba#3658]
First of all, thank you for maintaining and developing numba.  It's really awesome and a delight to use.

Using numba v0.42.0, I encounter a KeyError when trying to cache numba functions if I have multiple numba functions in a single file and import one, but not all of them into another file.  I have been able to reproduce this error on both OSX (High Sierra) and Linux (Ubuntu v16.04) in both python2.7 and python3.6.

This error does not arise when using numba v0.35.0.

A (very) minimal reproducible example is below.

file1.py:
<pre><code>
from file2 import function2
</pre></code>

file2.py:
<pre><code>
from numba import njit

@njit('float64(float64)', cache=True)
def function1(x):
    return x

@njit('float64(float64)', cache=True)
def function2(x):
    return x
</code></pre>

Then, running:
<pre><code>
> python file1.py
> python file2.py
</pre></code>
on the command line

results in:
<pre><code>
  File "file2.py", line 4, in <module>
    @njit('float64(float64)', cache=True)
  File "/path/to/anaconda/lib/python3.6/site-packages/numba/decorators.py", line 184, in wrapper
    disp.disable_compile()
  File "/path/to/anaconda/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/path/to/anaconda/lib/python3.6/site-packages/numba/typeinfer.py", line 729, in register_dispatcher
    del _temporary_dispatcher_map[name]
KeyError: 'function1'
</code></pre>

**Comment by stuartarchibald** [comment]
Thanks for the report (edited the code to add in a missing `:`). I can reproduce locally, seems like it's because the dispatcher registration sequence is entered twice but the map is not reference counted so the `del` deletes the sole reference when in actual fact two are live.

**Comment by jrbourbeau** [comment]
Following up on @stuartarchibald 's comment, would it then make sense to add a reference count map, e.g. `_temporary_dispatcher_ref_count_map`, which keeps track of the number of dispatcher registrations and only deletes once the corresponding reference count is zero? Doing this locally seems to fix the originally posted issue
