### ISSUE TITLE
Raspberry pi 3B+ pip install error

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#3670]
I am trying to instal numba on the Raspi3B+ via pip install numba 

I have beblow error.

wat we can do . ?

PS: llvm-3.8 . is installed.

> Collecting numba
  Using cached https://www.piwheels.org/simple/numba/numba-0.42.0-cp35-cp35m-linux_armv7l.whl
Collecting numpy (from numba)
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.15.4-cp35-cp35m-linux_armv7l.whl
Collecting llvmlite>=0.27.0dev0 (from numba)
  Using cached https://files.pythonhosted.org/packages/d3/59/8f0c20cd6197b3e535b6eb6513b2f1264c77fd343347e520dd4eab425962/llvmlite-0.27.0.tar.gz
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x1d_apx4/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpdyvhanb1pip-wheel- --python-tag cp35:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 383, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 167, in <module>
      main()
    File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 157, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: numpy, llvmlite, numba
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x1d_apx4/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x5wo4ou5-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    got version from file /tmp/pip-build-x1d_apx4/llvmlite/llvmlite/_version.py {'full': '894a1ddab60091869424f697cc56ecfee8156e31', 'version': '0.27.0'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 167, in <module>
        main()
      File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 157, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-x1d_apx4/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-x1d_apx4/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x5wo4ou5-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-x1d_apx4/llvmlite/

**Comment by seibert** [comment]
llvmlite 0.27 requires LLVM 7.  Compiling LLVM on the raspberry pi takes a very long time, though.  Can you use Berryconda for your Python environment?

https://github.com/jjhelmus/berryconda

We have pre-build conda packages for the Raspberry Pi that work with Berryconda:

http://numba.pydata.org/numba-doc/latest/user/installing.html#installing-on-linux-armv7-platforms

In the future, we will look into posting llvmlite wheels on piwheels, but we don't have them yet.

**Comment by MyraBaba** [comment]
I have lot of library i.e. mxnet. I don’t know is it easy to transferring to Berryconda..

Have you experience on this ? Or I will try to compile LLVM 7

**Comment by MyraBaba** [comment]
is this the llvm that I should compile : 

2 wget http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-armv7a-linux-gnueabihf.tar.xz

**Comment by seibert** [comment]
If you need to build LLVM from scratch, you need to take a look at the llvmlite docs here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvm

(In particular, LLVM has a few bugs we have to patch in our builds.)

**Comment by MyraBaba** [comment]
Hi,

I will try to compile numba this weekend for Raspberry pi and also JetsonTx & NanoPcT4 .

What you suggest to steps ?

**Comment by davidschranz** [comment]
Did you succeed to compile numba on the Raspberry pi? I had the exact same error.

**Comment by MyraBaba** [comment]
@davidschranz 
I switch to the Berryconda for raspi 3.  For other SbC I compiled first LLVM and than numba which is not easy. 

For raspi go with Berryconda.

**Comment by dowenrei** [comment]
@MyraBaba Do you managed to successfully download it with berryconda? I'm using raspberry pi zero W and `sudo apt-get llvm` gives llvm version 3.5 which is not compatible as llvmlite requires llvm of 3.8 and above. I tried `conda install llvm`  but the package is not found

**Comment by davidschranz** [comment]
@MyraBaba I was able to install the latest numba on a raspi 3 with debian stretch with following steps:

sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo chmod 600 /var/swap.1
sudo /sbin/swapon /var/swap.1

sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev liblapack-dev libblas-dev  wget  git  cmake

cd /root/
wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
tar xf Python-3.7.2.tar.xz
cd /root/Python-3.7.2
./configure
make -j 4
sudo make altinstall

pip3.7 install --upgrade pip
sudo pip3.7 install wheel
sudo pip3.7 install scipy
sudo pip3.7 install pandas
sudo pip3.7 install plotly

cd /root/
git clone git://github.com/numba/numba.git
git clone https://github.com/numba/llvmlite.git
wget http://releases.llvm.org/7.0.0/llvm-7.0.0.src.tar.xz
tar -xf llvm-7.0.0.src.tar.xz

cd /root/llvm-7.0.0.src
patch -p1 -i /root/llvmlite/conda-recipes/llvm-lto-static.patch
patch -p1 -i /root/llvmlite/conda-recipes/D47188-svml-VF.patch
patch -p1 -i /root/llvmlite/conda-recipes/partial-testing.patch
patch -p1 -i /root/llvmlite/conda-recipes/twine_cfg_undefined_behavior.patch
patch -p1 -i /root/llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
patch -p1 -i /root/llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch

export PREFIX=/usr/local CPU_COUNT=4
chmod +x /root/llvmlite/conda-recipes/llvmdev/build.sh
/root/llvmlite/conda-recipes/llvmdev/build.sh

cd /root/llvmlite
export LLVM_CONFIG=/usr/local/bin/llvm-config
python3.7 setup.py build
python3.7 runtests.py
python3.7 setup.py install

cd /root/numba
python3.7 setup.py install

sudo swapoff /var/swap.1
sudo rm /var/swap.1

python 3.7.2
scipy 1.2.1
pandas 0.24.1
plotly 3.6.1
numba '0.44.0.dev0+41.g8739d1e89-py3.7-linux-armv7l.egg'

**Comment by dowenrei** [comment]
@davidschranz Hi, this(llvmlite) does not support armv6l right? I'm having an error on my raspberry pi zero W when `/root/llvmlite/conda-recipes/llvmdev/build.sh` . 
![image](https://user-images.githubusercontent.com/31242926/54905808-ce72a380-4ed9-11e9-852f-d0ee7c4a3c90.png)

**Comment by davidschranz** [comment]
@dowenrei The compatibility notes from Numba only list ARMv7 http://numba.pydata.org/numba-doc/latest/user/installing.html

**Comment by MyraBaba** [comment]
I will try also compiling.

I change the way to use Berryconda for starts.

**Comment by vlasov01** [comment]
I'm trying to build llvm lite on RPi 3B+. I've followed @davidschranz steps, but some of the patches failed:

`pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/D47188-svml-VF.patch
patching file include/llvm/Analysis/TargetLibraryInfo.h
patching file include/llvm/IR/CMakeLists.txt
patching file include/llvm/IR/CallingConv.h
Hunk #1 succeeded at 220 with fuzz 2 (offset -3 lines).
patching file include/llvm/IR/SVML.td
patching file lib/Analysis/CMakeLists.txt
Hunk #1 succeeded at 93 (offset -7 lines).
patching file lib/Analysis/TargetLibraryInfo.cpp
Hunk #2 succeeded at 1457 (offset -40 lines).
Hunk #3 succeeded at 1480 (offset -40 lines).
patching file lib/AsmParser/LLLexer.cpp
Hunk #1 succeeded at 600 (offset -1 lines).
patching file lib/AsmParser/LLParser.cpp
Hunk #1 succeeded at 1843 (offset -23 lines).
Hunk #2 succeeded at 1903 (offset -25 lines).
patching file lib/AsmParser/LLToken.h
patching file lib/IR/AsmWriter.cpp
Hunk #1 succeeded at 360 (offset 1 line).
patching file lib/IR/Verifier.cpp
Hunk #1 succeeded at 2114 (offset -48 lines).
patching file lib/Target/X86/X86CallingConv.td
Hunk #2 succeeded at 1000 (offset -2 lines).
Hunk #3 succeeded at 1072 (offset -2 lines).
Hunk #4 succeeded at 1181 (offset -2 lines).
patching file lib/Target/X86/X86ISelLowering.cpp
Hunk #1 succeeded at 3279 (offset -149 lines).
patching file lib/Target/X86/X86RegisterInfo.cpp
patching file lib/Target/X86/X86Subtarget.h
Hunk #1 succeeded at 769 (offset -23 lines).
patching file lib/Transforms/Vectorize/LoopVectorize.cpp
Hunk #1 succeeded at 602 (offset -3 lines).
Hunk #2 succeeded at 4126 (offset -1 lines).
Hunk #3 succeeded at 4135 (offset -1 lines).
Hunk #4 succeeded at 4155 (offset -1 lines).
Hunk #5 succeeded at 4198 (offset -5 lines).
patching file test/Transforms/LoopVectorize/X86/scatter_crash.ll
patching file test/Transforms/LoopVectorize/X86/svml-calls-finite.ll
patching file test/Transforms/LoopVectorize/X86/svml-calls.ll
patching file test/Transforms/LoopVectorize/X86/svml-legal-calls.ll
patching file test/Transforms/LoopVectorize/X86/svml-legal-codegen.ll
patching file utils/TableGen/CMakeLists.txt
Hunk #1 succeeded at 38 (offset -1 lines).
patching file utils/TableGen/SVMLEmitter.cpp
patching file utils/TableGen/TableGen.cpp
Hunk #1 FAILED at 54.
Hunk #2 FAILED at 120.
Hunk #3 succeeded at 231 with fuzz 2 (offset -6 lines).
2 out of 3 hunks FAILED -- saving rejects to file utils/TableGen/TableGen.cpp.rej
patching file utils/TableGen/TableGenBackends.h
Hunk #1 FAILED at 90.
1 out of 1 hunk FAILED -- saving rejects to file utils/TableGen/TableGenBackends.h.rej
patching file utils/vim/syntax/llvm.vim
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/partial-testing.patch
patching file CMakeLists.txt
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/twine_cfg_undefined_behavior.patch
patching file include/llvm/Analysis/CFGPrinter.h
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
patch: **** Can't open patch file ../llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch : No such file or directory
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch
patch: **** Can't open patch file ../llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch : No such file or directory
`
And build failed too:
`pi@raspberrypi:~/llvm-7.0.0.src $ ../llvmlite/conda-recipes/llvmdev/build.sh
+ DARWIN_TARGET=x86_64-apple-darwin13.4.0
+ declare -a _cmake_config
+ _cmake_config+=(-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX})
+ _cmake_config+=(-DCMAKE_BUILD_TYPE:STRING=Release)
+ _cmake_config+=(-DLLVM_ENABLE_ASSERTIONS:BOOL=ON)
+ _cmake_config+=(-DLINK_POLLY_INTO_TOOLS:BOOL=ON)
+ _cmake_config+=(-DLLVM_ENABLE_LIBXML2:BOOL=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_CURSES=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_NCURSES=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_NCURSESW=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_TERMINFO=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_TINFO=OFF)
+ _cmake_config+=(-DHAVE_TERMIOS_H=OFF)
+ _cmake_config+=(-DCLANG_ENABLE_LIBXML=OFF)
+ _cmake_config+=(-DLIBOMP_INSTALL_ALIASES=OFF)
+ _cmake_config+=(-DLLVM_ENABLE_RTTI=OFF)
+ _cmake_config+=(-DLLVM_TARGETS_TO_BUILD="host;AMDGPU;NVPTX")
+ _cmake_config+=(-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly)
+ _cmake_config+=(-DLLVM_INCLUDE_UTILS=ON)
+ [[ '' == yes ]]
++ uname
+ [[ Linux == Darwin ]]
++ uname
+ [[ Linux == Linux ]]
+ _cmake_config+=(-DLLVM_USE_INTEL_JITEVENTS=ON)
+ mkdir build
mkdir: cannot create directory 'build': File exists
+ cd build
+ cmake '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_BUILD_TYPE:STRING=Release -DLLVM_ENABLE_ASSERTIONS:BOOL=ON -DLINK_POLLY_INTO_TOOLS:BOOL=ON -DLLVM_ENABLE_LIBXML2:BOOL=OFF -DHAVE_TERMINFO_CURSES=OFF -DHAVE_TERMINFO_NCURSES=OFF -DHAVE_TERMINFO_NCURSESW=OFF -DHAVE_TERMINFO_TERMINFO=OFF -DHAVE_TERMINFO_TINFO=OFF -DHAVE_TERMIOS_H=OFF -DCLANG_ENABLE_LIBXML=OFF -DLIBOMP_INSTALL_ALIASES=OFF -DLLVM_ENABLE_RTTI=OFF '-DLLVM_TARGETS_TO_BUILD=host;AMDGPU;NVPTX' -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DLLVM_INCLUDE_UTILS=ON -DLLVM_USE_INTEL_JITEVENTS=ON ..
../llvmlite/conda-recipes/llvmdev/build.sh: line 69: cmake: command not found
++ uname -m
+ ARCH=armv7l
+ '[' armv7l == armv7l ']'
+ make -j2 VERBOSE=1
make: *** No targets specified and no makefile found.  Stop.
+ make install
make: *** No rule to make target 'install'.  Stop.
+ exit 2
`

**Comment by vlasov01** [comment]
I'm trying to build llvm lite on RPi 3B+. I've followed @davidschranz steps, but some of the patches failed:
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/llvm-lto-static.patch
patching file tools/lto/CMakeLists.txt
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/D47188-svml-VF.patch
patching file include/llvm/Analysis/TargetLibraryInfo.h
patching file include/llvm/IR/CMakeLists.txt
patching file include/llvm/IR/CallingConv.h
Hunk #1 succeeded at 220 with fuzz 2 (offset -3 lines).
patching file include/llvm/IR/SVML.td
patching file lib/Analysis/CMakeLists.txt
Hunk #1 succeeded at 93 (offset -7 lines).
patching file lib/Analysis/TargetLibraryInfo.cpp
Hunk #2 succeeded at 1457 (offset -40 lines).
Hunk #3 succeeded at 1480 (offset -40 lines).
patching file lib/AsmParser/LLLexer.cpp
Hunk #1 succeeded at 600 (offset -1 lines).
patching file lib/AsmParser/LLParser.cpp
Hunk #1 succeeded at 1843 (offset -23 lines).
Hunk #2 succeeded at 1903 (offset -25 lines).
patching file lib/AsmParser/LLToken.h
patching file lib/IR/AsmWriter.cpp
Hunk #1 succeeded at 360 (offset 1 line).
patching file lib/IR/Verifier.cpp
Hunk #1 succeeded at 2114 (offset -48 lines).
patching file lib/Target/X86/X86CallingConv.td
Hunk #2 succeeded at 1000 (offset -2 lines).
Hunk #3 succeeded at 1072 (offset -2 lines).
Hunk #4 succeeded at 1181 (offset -2 lines).
patching file lib/Target/X86/X86ISelLowering.cpp
Hunk #1 succeeded at 3279 (offset -149 lines).
patching file lib/Target/X86/X86RegisterInfo.cpp
patching file lib/Target/X86/X86Subtarget.h
Hunk #1 succeeded at 769 (offset -23 lines).
patching file lib/Transforms/Vectorize/LoopVectorize.cpp
Hunk #1 succeeded at 602 (offset -3 lines).
Hunk #2 succeeded at 4126 (offset -1 lines).
Hunk #3 succeeded at 4135 (offset -1 lines).
Hunk #4 succeeded at 4155 (offset -1 lines).
Hunk #5 succeeded at 4198 (offset -5 lines).
patching file test/Transforms/LoopVectorize/X86/scatter_crash.ll
patching file test/Transforms/LoopVectorize/X86/svml-calls-finite.ll
patching file test/Transforms/LoopVectorize/X86/svml-calls.ll
patching file test/Transforms/LoopVectorize/X86/svml-legal-calls.ll
patching file test/Transforms/LoopVectorize/X86/svml-legal-codegen.ll
patching file utils/TableGen/CMakeLists.txt
Hunk #1 succeeded at 38 (offset -1 lines).
patching file utils/TableGen/SVMLEmitter.cpp
patching file utils/TableGen/TableGen.cpp
Hunk #1 FAILED at 54.
Hunk #2 FAILED at 120.
Hunk #3 succeeded at 231 with fuzz 2 (offset -6 lines).
2 out of 3 hunks FAILED -- saving rejects to file utils/TableGen/TableGen.cpp.rej
patching file utils/TableGen/TableGenBackends.h
Hunk #1 FAILED at 90.
1 out of 1 hunk FAILED -- saving rejects to file utils/TableGen/TableGenBackends.h.rej
patching file utils/vim/syntax/llvm.vim
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/partial-testing.patch
patching file CMakeLists.txt
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/twine_cfg_undefined_behavior.patch
patching file include/llvm/Analysis/CFGPrinter.h
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
patch: **** Can't open patch file ../llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch : No such file or directory
pi@raspberrypi:~/llvm-7.0.0.src $ patch -p1 -i ../llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch
patch: **** Can't open patch file ../llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch : No such file or directory

And the build failed as well:

pi@raspberrypi:~/llvm-7.0.0.src $ ../llvmlite/conda-recipes/llvmdev/build.sh
+ DARWIN_TARGET=x86_64-apple-darwin13.4.0
+ declare -a _cmake_config
+ _cmake_config+=(-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX})
+ _cmake_config+=(-DCMAKE_BUILD_TYPE:STRING=Release)
+ _cmake_config+=(-DLLVM_ENABLE_ASSERTIONS:BOOL=ON)
+ _cmake_config+=(-DLINK_POLLY_INTO_TOOLS:BOOL=ON)
+ _cmake_config+=(-DLLVM_ENABLE_LIBXML2:BOOL=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_CURSES=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_NCURSES=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_NCURSESW=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_TERMINFO=OFF)
+ _cmake_config+=(-DHAVE_TERMINFO_TINFO=OFF)
+ _cmake_config+=(-DHAVE_TERMIOS_H=OFF)
+ _cmake_config+=(-DCLANG_ENABLE_LIBXML=OFF)
+ _cmake_config+=(-DLIBOMP_INSTALL_ALIASES=OFF)
+ _cmake_config+=(-DLLVM_ENABLE_RTTI=OFF)
+ _cmake_config+=(-DLLVM_TARGETS_TO_BUILD="host;AMDGPU;NVPTX")
+ _cmake_config+=(-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly)
+ _cmake_config+=(-DLLVM_INCLUDE_UTILS=ON)
+ [[ '' == yes ]]
++ uname
+ [[ Linux == Darwin ]]
++ uname
+ [[ Linux == Linux ]]
+ _cmake_config+=(-DLLVM_USE_INTEL_JITEVENTS=ON)
+ mkdir build
mkdir: cannot create directory 'build': File exists
+ cd build
+ cmake '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_BUILD_TYPE:STRING=Release -DLLVM_ENABLE_ASSERTIONS:BOOL=ON -DLINK_POLLY_INTO_TOOLS:BOOL=ON -DLLVM_ENABLE_LIBXML2:BOOL=OFF -DHAVE_TERMINFO_CURSES=OFF -DHAVE_TERMINFO_NCURSES=OFF -DHAVE_TERMINFO_NCURSESW=OFF -DHAVE_TERMINFO_TERMINFO=OFF -DHAVE_TERMINFO_TINFO=OFF -DHAVE_TERMIOS_H=OFF -DCLANG_ENABLE_LIBXML=OFF -DLIBOMP_INSTALL_ALIASES=OFF -DLLVM_ENABLE_RTTI=OFF '-DLLVM_TARGETS_TO_BUILD=host;AMDGPU;NVPTX' -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DLLVM_INCLUDE_UTILS=ON -DLLVM_USE_INTEL_JITEVENTS=ON ..
../llvmlite/conda-recipes/llvmdev/build.sh: line 69: cmake: command not found
++ uname -m
+ ARCH=armv7l
+ '[' armv7l == armv7l ']'
+ make -j2 VERBOSE=1
make: *** No targets specified and no makefile found.  Stop.
+ make install
make: *** No rule to make target 'install'.  Stop.
+ exit 2

**Comment by stuartarchibald** [comment]
@vlasov01 IIRC the patches in the current conda recipe for `llvmdev` are for LLVM 8.0.0, `llvmlite` is in an unusual situation at present where two versions of LLVM are supported (7 and 8). If you really want LLVM 7, then try using the patches as present in llvmlite 0.28, https://github.com/numba/llvmlite/releases/tag/v0.28.0.

Also, the Numba team ship conda packages: http://numba.pydata.org/numba-doc/latest/user/installing.html#installing-on-linux-armv7-platforms

**Comment by dSalvoG** [comment]
> @MyraBaba I was able to install the latest numba on a raspi 3 with debian stretch with following steps:
> 
> sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
> sudo /sbin/mkswap /var/swap.1
> sudo chmod 600 /var/swap.1
> sudo /sbin/swapon /var/swap.1
> 
> sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev liblapack-dev libblas-dev wget git cmake
> 
> cd /root/
> wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
> tar xf Python-3.7.2.tar.xz
> cd /root/Python-3.7.2
> ./configure
> make -j 4
> sudo make altinstall
> 
> pip3.7 install --upgrade pip
> sudo pip3.7 install wheel
> sudo pip3.7 install scipy
> sudo pip3.7 install pandas
> sudo pip3.7 install plotly
> 
> cd /root/
> git clone git://github.com/numba/numba.git
> git clone https://github.com/numba/llvmlite.git
> wget http://releases.llvm.org/7.0.0/llvm-7.0.0.src.tar.xz
> tar -xf llvm-7.0.0.src.tar.xz
> 
> cd /root/llvm-7.0.0.src
> patch -p1 -i /root/llvmlite/conda-recipes/llvm-lto-static.patch
> patch -p1 -i /root/llvmlite/conda-recipes/D47188-svml-VF.patch
> patch -p1 -i /root/llvmlite/conda-recipes/partial-testing.patch
> patch -p1 -i /root/llvmlite/conda-recipes/twine_cfg_undefined_behavior.patch
> patch -p1 -i /root/llvmlite/conda-recipes/0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch
> patch -p1 -i /root/llvmlite/conda-recipes/0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch
> 
> export PREFIX=/usr/local CPU_COUNT=4
> chmod +x /root/llvmlite/conda-recipes/llvmdev/build.sh
> /root/llvmlite/conda-recipes/llvmdev/build.sh
> 
> cd /root/llvmlite
> export LLVM_CONFIG=/usr/local/bin/llvm-config
> python3.7 setup.py build
> python3.7 runtests.py
> python3.7 setup.py install
> 
> cd /root/numba
> python3.7 setup.py install
> 
> sudo swapoff /var/swap.1
> sudo rm /var/swap.1
> 
> python 3.7.2
> scipy 1.2.1
> pandas 0.24.1
> plotly 3.6.1
> numba '0.44.0.dev0+41.g8739d1e89-py3.7-linux-armv7l.egg'

Finally I could install Librosa, Tensorflow and Keras on RPI3 and RPI4 following this steps. Thanks!!
You can find all procedure in this rep: https://github.com/dSalvoG/ML-Urban-Sound-Classifier

**Comment by esc** [comment]
Since this issue is somewhat out of date and pertains to older verions of llvm, llvmlite and Numba I will close it now. For reference, current llvmlite and Numba versions (at the time of writing) are: 0.34.0 / 0.51.2.

Instructions for installing pre-compiled binaries on Raspberry PIs using `conda` can be found here:

https://numba.readthedocs.io/en/stable/user/installing.html#installing-on-linux-armv8-aarch64-platforms

If you experience recent trouble installing or compiling Numba, please feel free to open a new issue. Thanks for using Numba!
