### ISSUE TITLE
Comparing tuples of strings error

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3673]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Comparison of tuples with strings fails:

```python
@numba.njit
def f(a):
    return ('aa',) < ('bb',)
```
```
No definition for lowering <built-in function ne>(unicode_type, unicode_type) -> bool
```

I think might be because of mixing new and old extension APIs. I applied this patch but I got another error:
```
diff --git a/numba/targets/base.py b/numba/targets/base.py
index 265715f85..073f8242b 100644
--- a/numba/targets/base.py
+++ b/numba/targets/base.py
@@ -704,7 +704,9 @@ class BaseContext(object):
         assert ty is not None
         cav = self.cast(builder, av, at, ty)
         cbv = self.cast(builder, bv, bt, ty)
-        cmpsig = typing.signature(types.boolean, ty, ty)
+        #cmpsig = typing.signature(types.boolean, ty, ty)
+        key = self.typing_context.resolve_value_type(key)
+        cmpsig = self.typing_context.resolve_function_type(key, argtypes, {})
         cmpfunc = self.get_function(key, cmpsig)
```
```
RuntimeError: Failed in nopython mode pipeline (step: nopython mode backend)
LLVM IR parsing error
<string>:52:84: error: invalid use of function-local name
  %".26" = extractvalue [1 x {i8*, i64, i32, i8*, i8*}] [{i8*, i64, i32, i8*, i8*} %".25"], 0
                                                                                   ^
```

**Comment by stuartarchibald** [comment]
I'm wondering if this is related to https://github.com/numba/numba/issues/3671

**Comment by ehsantn** [comment]
BTW, in the actual workload, type inference falls into infinite loop instead of error!

**Comment by sklam** [comment]
The patch to use `.resolve_value_type` is valid.  And, I've figured out the ```
<string>:52:84: error: invalid use of function-local name
  %".26" = extractvalue [1 x {i8*, i64, i32, i8*, i8*}] [{i8*, i64, i32, i8*, i8*} %".25"],
