### ISSUE TITLE
pow(x,y) or x**y

### ISSUE THREAD

**Issue by AndZhig** [numba/numba#3679]
why does this number give out,, how to fix it?

from numba import jit

@jit #(nopython=True)
def func():
a = pow(2,1000000)
b = 2**1000000
return a,b

print(func())

**(-9223372036854775808, -9223372036854775808)**

without @jit counts normally (but slowly).

Or script from here https://www.rookieslab.com/posts/fast-power-algorithm-exponentiation-by-squaring-cpp-python-implementation

from numba import jit

@jit(nopython=True)
def fast_power(base, power):
result = 1
while power > 0:
if power % 2 == 0:
power = power / 2
base = base * base
else:
power = power - 1
result = result * base
power = power / 2
base = base * base
return result

print (fast_power(2, 2048))

**0**

why 0?

**Comment by seibert** [comment]
Numba does not support big integers, which Python will switch to when dealing with integers that do not fit into a machine word (64 bits most likely for you).  `2**1000000` will overflow the machine integer.

There's no way to fix this, currently.  (Implementing arbitrary size integers is a large task.)  If you need big integers, you will have to stick with regular Python for now.

**Comment by AndZhig** [comment]
> Numba does not support big integers, which Python will switch to when dealing with integers that do not fit into a machine word (64 bits most likely for you). `2**1000000` will overflow the machine integer.
> 
> There's no way to fix this, currently. (Implementing arbitrary size integers is a large task.) If you need big integers, you will have to stick with regular Python for now.

Thanks for the explanation. As I understand, numba supports working with "str", whether it accelerates dec conversion of numbers of a few thousand or more digits (2^16000 in dec to str) as well as working with long str lines, trimming, mixing?
