### ISSUE TITLE
overload_method error on typing of literals

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3683]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Looks like the type inference only passes the literal types to `overload_method`, and doesn't convert to generic types and try again. The example below prints `foo.g(a) input type Literal[str](TEST)` and fails in typing.

```python
import numba
from numba.extending import type_callable, overload_method
from numba import types
from numba.extending import models, register_model

class Foo:
    def __init__(self):
        pass
    def g(self, a):
        return a

class FooType(types.Type):
    def __init__(self):
        super(FooType, self).__init__(name='Foo')

register_model(FooType)(models.OpaqueModel)
foo_type = FooType()

@type_callable(Foo)
def type_foo(context):
    def typer():
        return foo_type
    return typer

@overload_method(FooType, 'g')
def g_overload(f_t, a_t):
    if a_t == types.unicode_type:
        return lambda f, a: a
    print("foo.g(a) input type", a_t)

@numba.njit
def test():
    foo = Foo()
    return foo.g('TEST')

test()
```

**Comment by ehsantn** [comment]
Looks like `IntegerLiteral` inherits from `Integer` but `StringLiteral` doesn't inherit from `UnicodeType`. Which one is correct?

**Comment by sklam** [comment]
(Adding notes from offline discussion)

The `Literal` subclassing is there to minimize changes needed for the support of literals.  For `StringLiteral`, there is the mess that py2 string is not unicode.  IMO, I would want to avoid subclassing the `Type` instances.  We should refactor that at some point.

**Comment by sklam** [comment]
The issue is caused by dispatcher cache for attribute not using the signature as key.  When the first attempt of using literal types failed, the cache incorrectly remembers that the `foo.g` method doesn't exist.
