### ISSUE TITLE
Fix needed for invalid signature specification error message

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3688]
## Feature request

```python
from numba import njit
@njit(['f8',])
def foo(a):
    return 1
```
the above is invalid as the signature makes no sense, however the error message says:
```
  File "gi53.py", line 20, in <module>
    @njit(['f8',])
  File "<path>/numba/numba/decorators.py", line 183, in wrapper
    disp.compile(sig)
  File "<path>/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<path>/numba/numba/dispatcher.py", line 641, in compile
    args, return_type = sigutils.normalize_signature(sig)
  File "<path>/numba/numba/sigutils.py", line 35, in normalize_signature
    % (sig.__class__.__name__,))
TypeError: invalid signature: 'str' instance not allowed
```
fix this so it reports something more useful!

**Comment by stuartarchibald** [comment]
@PGryllos that would be great, thanks... I think that the error message needs to report the input that was invalid along with the output of parsing the input and feed this back to the user, thoughts?

**Comment by PGryllos** [comment]
If I have understood correctly the problem here is that we are feeding a str instead of a valid signature type

> I think that the error message needs to report the input that was invalid

@stuartarchibald the existing msg suffices for this part, right? It says str type cannot be interpreted as a signature; If I look into the compilation the `normalise_signature` outputs exactly that when encountering something other than a tuple of a `Signature`. Or do you mean that it should instead say something like `"f8" is of type str that cannot be interpreter as a signature`?

>  the output of parsing the input 
As far as I can understand this should be the output of `normalise_signature` ?

**Comment by stuartarchibald** [comment]
The following has a signature supplied as a string, the signature is invalid.
```python
from numba import njit
@njit(['f8',])
def foo(a):
    return 1
```
which gives the error message:
```
TypeError: invalid signature: 'str' instance not allowed
```
but this doesn't make sense, because the problem isn't that the signature is specified as a string instance, it's that it is invalid as a signature.

Conversely:
```python
from numba import njit
@njit(['(f8,)',])
def foo(a):
    return 1
```
works fine, it's a signature specified as a string but this time is slightly more valid.

> Or do you mean that it should instead say something like "f8" is of type str that cannot be interpreter as a signature?

I think that something along these lines would be most appropriate, there is nothing wrong with passing in a string for a signature, it's just that the string has to evaluate to something valid.

**Comment by PGryllos** [comment]
@stuartarchibald okay, now I fully understood your point. 

would this msg be closer?

> TypeError: invalid signature: 'str' instance evaluates to 'Float' instead of type tuple or Signature

**Comment by PGryllos** [comment]
@stuartarchibald I opened a pr. I changed the msg for the invalid sig to

> TypeError: invalid signature: 'f8' (type: 'str') evaluates to 'Float' instead of tuple or Signature

I also slightly changed the error msg for wrong types to instead of saying `invalig signature` say 
`invalid type in signature`

**Comment by PGryllos** [comment]
one of the tests fail because of changing the second error msg. I think that saying `invalid signature` when the type in the signature is wrong is not the best. what do you think?

**Comment by stuartarchibald** [comment]
I think the proposed new second error message is more clear and suggest changing the expected string(s) as necessary in the unit test to accommodate. Perhaps also add a test in that unit test for the case above (`'f8'`) that was the root cause of this issue being raised?
