### ISSUE TITLE
getting heapq to work ith @njit

### ISSUE THREAD

**Issue by ebo** [numba/numba#3690]
working on porting some code I hit a complete stopper with trying to get heapq to work.  If anyone has examples to share getting it to work out of the box I would appreciate.  Otherwise I have a potential invasive workaround.

Starting with a minimal example:
> from heapq import heappush, heappop
> from numba import jit
> 
> @jit(nopython=True)
> def test_it():
>     heap = [(1,0,1)]
>     item = (2,0,1)
>     heappush(heap, item)
>     ret = heappop(heap)
>     print(ret)
> 
> test_it()

I get the following error: 
  "Untyped global name 'heappush': cannot determine Numba type of <class 'builtin_function_or_method'>"

I was able to get heapq to work by going back to heapq's source, adding @jit(nopython=True) to every provided function/method, and then seeding the heap with the first element.  I had to seed the heap otherwise numba would complain that it could not figure out the typing.  

Before I hack a custom version of heapq in our project can anyone suggest how to set up function and variable signatures so that it works out of the box?  Otherwise I will integrate the hack in my work and see if it is stable.

This workaround might also help with the lexsort request #3689

**Comment by ebo** [comment]
Thank you for the feedback.  I got it to mostly work all with @jit, but 
when i added nopython=True it would not get past heaps push/pop not 
liking the item being set to a tuple.  I have been thinking of trying to 
build a custom heapq and passing all 4 or 5 of the items to the heap.  
There may be a way to set up a signature to give the compiler a 'hint' 
on what it will be receiving, but I have not quite wrapped my head 
around how to set that up with a tuple containing multiple typed 
objects.  I can convert everything into a float64, and convert back to 
int32 and int8 as needed, but that seems a little wasteful with 100's of 
thousands of items.  If you can point me to a trick to pass along a 
signature, that would be great.  If not I can hack it to pass in 4 or 5 
independent objects.  Can you suggest which method, or something else, 
is best practice?

   Thanks and best regards,

   EBo --

**Comment by stuartarchibald** [comment]
You can specify a signature like this: http://numba.pydata.org/numba-doc/latest/user/jit.html#eager-compilation, this however is not a "hint", it is a direct instruction "compile for these types". The type inference algorithms can usually work out what the types of everything need to be and in general it's a good idea to get that working. However, if needs be you can "hint" (which is really "force this variable to have this type") using the `locals` kwarg to the `@jit` decorator (full docs for the decorator are here: http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html?highlight=locals#jit-functions)

If you are interested in types, `from numba import typeof` will give you a function `typeof` which will tell you what types Numba thinks things are, for example:
```
In [27]: from numba import typeof                                                                                               

In [28]: typeof([(1,0,1)])                                                                                                      
Out[28]: reflected list(tuple(int64 x 3))
```
then the `numba.types` module can be used to construct types:
```
In [30]: from numba import types                                                                                                

In [31]: types.List(types.UniTuple(types.int64, 3), reflected=True)                                                             
Out[31]: reflected list(tuple(int64 x 3))
```
For simple types it's also possible to use a string as the signature, these strings get `eval`'d internally with `numba.types` as locals so will resolve to the same types as demonstrated above. Example:
```python
@njit("float32[:](float64[:])")
def foo(x):
  return x.astype(np.float32)
```
there's a bit more information on signature specification here: http://numba.pydata.org/numba-doc/latest/user/jit.html#signature-specifications and more information on types and how to construct them etc here: http://numba.pydata.org/numba-doc/latest/reference/types.html#signatures

**Comment by ebo** [comment]
Thank you!  While the problem turned out to be somewhere else in the 
code, I had not seen typeof before, and it did help track down what was 
happening.  That said, I could not do a print(numba.typeof(var)) from 
within any method/function that had @jit(nopython=True).  That is the 
one bit of functional upgrade I would request if possible.

The problem turned out to be the way the original code was written to 
use several different input types for a single variable (one where you 
could pass in an array of ints, or a single int).  I will experiment to 
see if I can set up a multiple signature to make this just work.  I was 
able to use @jit on these few, and then use @jit(nopython=True) on 
everything else.

All that said, I was able to get all of heapq to work with 
@jit(nopython=True) applied to each of its methods.  The one thing that 
breaks it a bit (and it might be interesting to search for a workaround) 
is that you have to seed the heap with the first element (and it must be 
exactly the same argument types).  So, that may be something that can be 
added to the numba source tree (a numba wrapped heapq).  One thing that 
I have not tried, because I do not need it, is if all the types resolve 
properly for multiple heaps with different items.

Once again, thank you for the pointers to the docs, and for getting 
back to me.

   EBo --

**Comment by stuartarchibald** [comment]
> Thank you! While the problem turned out to be somewhere else in the code, I had not seen typeof before, and it did help track down what was happening. 

No problem, glad you got this working.

>  That said, I could not do a print(numba.typeof(var)) from within any method/function that had @jit(nopython=True). That is the one bit of functional upgrade I would request if possible.

Indeed, this is because Numba doesn't know how to compile `typeof`. However, you can inspect the types of all the variables using the Numba type annotations, so there may be no need to print? Docs are [here](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#Dispatcher.inspect_types). Quick example:
```python
from numba import njit

@njit
def foo(a, b, c):
    x = a + 1j
    c = c + 10
    return x / b + c

foo(1, 2, 3)

print(foo.inspect_types(pretty=True))
```
gives:
```
$ python example3690.py
<path>/numba/numba/pretty_annotate.py:26: FutureWarning: The pretty_annotate functionality is experimental and might change API
  FutureWarning)
(int64, int64, int64)
Function name: foo
In file: example3690.py
With signature: (int64, int64, int64) -> complex128

3: @njit
--    label 0
4: def foo(a, b, c):
5:     x = a + 1j
--          a = arg(0, name=a)  :: int64
--          b = arg(1, name=b)  :: int64
--          c = arg(2, name=c)  :: int64
--          $const0.2 = const(complex, 1j)  :: complex128
--          $0.3 = a + $const0.2  :: complex128
--          del a
--          del $const0.2
--          x = $0.3  :: complex128
--          del $0.3
6:     c = c + 10
--          $const0.5 = const(int, 10)  :: Literal[int](10)
--          $0.6 = c + $const0.5  :: int64
--          del c
--          del $const0.5
--          c.1 = $0.6  :: int64
--          del $0.6
7:     return x / b + c
--          $0.9 = x / b  :: complex128
--          del x
--          del b
--          $0.11 = $0.9 + c.1  :: complex128
--          del c.1
--          del $0.9
--          $0.12 = cast(value=$0.11)  :: complex128
--          del $0.11
--          return $0.12
```

>  The one thing that breaks it a bit (and it might be interesting to search for a workaround) is that you have to seed the heap with the first element (and it must be exactly the same argument types). 

I'd anticipate that the compiled heap would need seeding for the purposes of type inference, though in the case of your code you can probably avoid actually putting a variable into your heap list through the "trick" demonstrated in the last paragraph of http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html?highlight=empty%20list#my-code-has-an-untyped-list-problem.

> So, that may be something that can be added to the numba source tree (a numba wrapped heapq).

If you'd be interested in working on it, please open a feature request issue. Numba has an [extension API](http://numba.pydata.org/numba-doc/latest/extending/high-level.html) with a simple `@overload` decorator to register functions suitable for compilation. It may be just a question of copying in some `heapq` source functions and decorating them appropriately with that.

**Comment by ebo** [comment]
On Jan 28 2019 6:56 AM, stuartarchibald wrote:

<snipping some to shortend the inline reply>

>>  That said, I could not do a print(numba.typeof(var)) from within 
>> any method/function that had @jit(nopython=True). That is the one bit 
>> of functional upgrade I would request if possible.
>
> Indeed, this is because Numba doesn't know how to compile `typeof`.
> However, you can inspect the types of all the variables using the
> Numba type annotations, so there may be no need to print? Docs are
> 
> [here](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#Dispatcher.inspect_types).
> Quick example:
> ```python
> from numba import njit
>
> @njit
> def foo(a, b, c):
>     x = a + 1j
>     c = c + 10
>     return x / b + c
>
> foo(1, 2, 3)
>
> print(foo.inspect_types(pretty=True))
> ```
> gives:
> ...

Cool.  I am new enough to numba I had not come across inspect_types.  
This will come in handy ;-)

>>  The one thing that breaks it a bit (and it might be interesting to 
>> search for a workaround) is that you have to seed the heap with the 
>> first element (and it must be exactly the same argument types).
>
> I'd anticipate that the compiled heap would need seeding for the
> purposes of type inference, though in the case of your code you can
> probably avoid actually putting a variable into your heap list 
> through
> the "trick" demonstrated in the last paragraph of
> 
> http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html?highlight=empty%20list#my-code-has-an-untyped-list-problem.

In general I see how this works.  I am trying to adapt it to my 
particular situation.   I may be able to effect this by returning the 
heap from the push -- it currently returns void.  This would deviate 
from a strict port to numbafied python heapq, but it would otherwise be 
a drop in replacement in functionality.

>> So, that may be something that can be added to the numba source tree 
>> (a numba wrapped heapq).
>
> If you'd be interested in working on it, please open a feature
> request issue. Numba has an [extension
> 
> API](http://numba.pydata.org/numba-doc/latest/extending/high-level.html)
> with a simple `@overload` decorator to register functions suitable
> for compilation. It may be just a question of copying in some `heapq`
> source functions and decorating them appropriately with that.

I was able to tweak the segmentation code and the heapq in such a way 
that all of heapq's methods compile with nopython=True.  That said, I 
need to wrap my head around what `@overload*` does, and how I can use it 
in various places in my code.  So we should be close to having a usable 
numbafied heapq.  As such I should be able to post that code for review 
if I do not find anything amis.

Beyond this I feel I need to mention that the tasks that have been 
covering my salary while working on dask/xarray/etc. have run out of 
funds for the fiscal year, and I am officially off on other tasks now.  
So any time I put into any of this is as a volunteer, and I have to be 
careful not to work on things which conflict.  That said, I will try to 
break away some time here and there to work on a couple of these issues 
to kick the ball forward so things will be ready when I can pick them up 
again.

Taking a momentary step back, and trying not to get sillyphosical (note 
to non-native english speakers, this is just a play on words meaning 
that if we look at this philosophically while trying not to take it to 
an absurd point of view), if one of the end goals is to support dask and 
xarray, we may need a heap and/or queue which will support concurrent 
and multi-threading.  This will also bring GIL and other things into the 
frey, but might be an overreach, but then again might be necessary.  
Comments?  What I am envisioning here is a mashup of Queue (A 
synchronized queue class) and heapq.

I will work on wrapping my head around the overload decorator and see 
how I can use that, and then go back and work on making sure that the 
old heapq test suite is still functional -- I had only verified the 
functionality I need for the project works.

Thanks again Stuart for the suggestions and pointers.  These have been 
particularly helpful.

   John (EBo) David --

**Comment by stuartarchibald** [comment]
> I was able to tweak the segmentation code and the heapq in such a way that all of heapq's methods compile with nopython=True. That said, I need to wrap my head around what `@overload*` does, and how I can use it in various places in my code. So we should be close to having a usable numbafied heapq. As such I should be able to post that code for review if I do not find anything amis. 

This would be great if you have time, and even if it only partly works or there's parts you are unsure about having something as a starting point would be very useful.

CC @rjenc29. Would this be of interest to you, even in part complete form, perhaps to collaborate on as a back burner PR to explore what it takes to add this sort of thing?

>  if one of the end goals is to support dask and xarray, we may need a heap and/or queue which will support concurrent and multi-threading. This will also bring GIL and other things into the frey, but might be an overreach, but then again might be necessary. Comments? What I am envisioning here is a mashup of Queue (A synchronized queue class) and heapq

I see, I guess it depends where the threading comes from, Numba has it's own parallel support too.

> I will work on wrapping my head around the overload decorator and see how I can use that, and then go back and work on making sure that the old heapq test suite is still functional

Great, thanks. There's quite a few examples of `@overload` in incoming and recently merged PRs, here's one https://github.com/numba/numba/pull/3633 for example.

> Thanks again Stuart for the suggestions and pointers. These have been particularly helpful.

No problem at all, this is something somewhat different and a useful use-case to explore.

**Comment by ebo** [comment]
On Jan 30 2019 3:12 AM, stuartarchibald wrote:
>> I was able to tweak the segmentation code and the heapq in such a 
>> way that all of heapq's methods compile with nopython=True. That said, 
>> I need to wrap my head around what `@overload*` does, and how I can 
>> use it in various places in my code. So we should be close to having a 
>> usable numbafied heapq. As such I should be able to post that code for 
>> review if I do not find anything amis.
>
> This would be great if you have time, and even if it only partly
> works or there's parts you are unsure about having something as a
> starting point would be very useful.

I think I not only got it to fully work, but I also got the warnings to 
shut up by including forceobj=True.  I still need to read up on 
`@overload*`, but it is up.

As a note, the code is in a dask-image fork at 
git@github.com:ebo/dask-image.git and specifically in the files 
dask_image/ndmorph/_numba_heapq.py and 
dask_image/ndmorph/_numba_watershed.py  in the numba_seg branch.

As a note, I have also ported a couple of the tests to 
dask-image/tests/test_dask_image/test_ndmorph/test_numba_{heapq,watershed}.py 
  They are not an exhaustive test, but it is a start.


> CC @rjenc29. Would this be of interest to you, even in part complete
> form, perhaps to collaborate on as a back burner PR to explore what 
> it
> takes to add this sort of thing?

Just let me know what you need/expect, and we can talk about if it is 
worth everyone's time.


>>  if one of the end goals is to support dask and xarray, we may need 
>> a heap and/or queue which will support concurrent and multi-threading. 
>> This will also bring GIL and other things into the frey, but might be 
>> an overreach, but then again might be necessary. Comments? What I am 
>> envisioning here is a mashup of Queue (A synchronized queue class) and 
>> heapq
>
> I see, I guess it depends where the threading comes from, Numba has
> it's own parallel support too.

That would probably have to be a call between the Dask, Numba, and 
Tornado prime developers.  It might also not matter.  That said, Dask 
focuses on scaling and I have not looked into Numba's parallel support 
at all.


>> I will work on wrapping my head around the overload decorator and 
>> see how I can use that, and then go back and work on making sure that 
>> the old heapq test suite is still functional
>
> Great, thanks. There's quite a few examples of `@overload` in
> incoming and recently merged PRs, here's one
> https://github.com/numba/numba/pull/3633 for example.

I'm not finding them, but I will keep digging.  Thanks for the pointer.


>> Thanks again Stuart for the suggestions and pointers. These have 
>> been particularly helpful.
>
> No problem at all, this is something somewhat different and a useful
> use-case to explore.

Thanks.  I look forward to getting the new image processing code up and 
running, as well as using numba to make it run as fast as possible...


   Cheers!

   EBo --

**Comment by rjenc29** [comment]
Thanks for sharing the link to your branch; great stuff.

I'd be happy to raise a PR with the outline of how I think this could
be wired up using the high level extension APIs like `overload` (I am
assuming it's not dissimilar to adding a new numpy function, for example)
and tickle it along.

There's definitely utility in the end result from my perspective, so the
cost / benefit is favourable from my side.

I am a bit short on time at the moment, so if I am holding things up /
you'd rather I didn't get in the way, no worries.  Otherwise, I will make a
start at the weekend.

Cheers

Rob

**Comment by stuartarchibald** [comment]
@ebo with thanks to @rjenc29 `heapq` module support made it into Numba 0.43. Closing!

**Comment by ebo** [comment]
cool.  Thanks for letting me know.  I will see what else I can get going, but I am distracted with many other things.
