### ISSUE TITLE
prange with field from jitclass named T fails

### ISSUE THREAD

**Issue by JeppeDruedahl** [numba/numba#3700]
## Reporting a bug

- [X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

`prange(somejitclass.T)` fails while `prange(somejitclass.L)` works.

```
import numba as nb
import numpy as np

parlist = [('L',nb.int32),('T',nb.int32)]
@nb.jitclass(parlist)
class ParClass():
    def __init__(self):
        self.L = 5
        self.T = 5
        
@nb.njit(parallel=True)
def testL(par,X):
    for i in nb.prange(par.L):
        X[i] = 1

@nb.njit(parallel=True)
def testT(par,X):
    for i in nb.prange(par.T):
        X[i] = 1
        
par = ParClass()

X = np.zeros(par.L)

try:
    testL(par,X)
except:
    print('testL could not run')

try:
    testT(par,X)
except:
    print('testT could not run')    

testT(par,X)

```

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm almost certain that this is because the code spots the `.T` as an attr and interprets this as `numpy.ndarray.T` (i.e. `numpy.transpose`). Clearly a bug.

**Comment by stuartarchibald** [comment]
CC @ehsantn @DrTodd13
