### ISSUE TITLE
Test test_issue_57 failing on OSX python3 sometimes

### ISSUE THREAD

**Issue by sklam** [numba/numba#371]
https://github.com/numba/numba/blob/master/numba/tests/issues/test_issue_57.py
This test is failing on a OSX python3 machine with incorrect result generated by `ra_numba`.

The test is temporarily disabled: https://github.com/numba/numba/commit/ca8d55790afb97db688b140204249b63bee9a002

**Comment by pitrou** [comment]
Closing as outdated.
