### ISSUE TITLE
Global list of strings

### ISSUE THREAD

**Issue by fingoldo** [numba/numba#3732]
Hello, while I know that using globals is undesired and limited, can someone shed light on these errors:

```python
base=['CAD', 'EUR', 'GBP', 'USD']
@numba.njit()
def test():
    res=base[3]
test()
```

> Cannot lower constant of type 'reflected list(unicode_type)'
> 
> File "<ipython-input-226-33fa63a9dbe7>", line 4:
> def test():
>     res=base[3]
>     ^

with tuple even worse:

```python
base=('CAD', 'EUR', 'GBP', 'USD')
@numba.njit()
def test():
    res=base[3]
test()
```

> LLVM IR parsing error
> <string>:35:84: error: invalid use of function-local name

Is this all expected behavior or can be fixed? (Errors go away when base is made an argument and gets passed)
Numba v 0.42

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue in the first example is that the type of `base` is a `"reflected list"`, this is a list which Numba has detected must have changes "reflected" (i.e. you change the list contents in the JITted function, the contents must be updated in the CPython interpreter once the JITted function returns). In Numba globals are [frozen at compile time as compile time constants](http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable) so reflection is simply not permitted. i.e. this also complains the same way and unicode is not involved:
```python
import numba

base=[1, 2, 3, 4, 5]
@numba.njit()
def test():
    res=base[3]
test()
```

This second sample works on the current Numba master branch so should be working fine for the next release. You can grab a Numba development build to check it out with `conda install -c numba/label/dev numba` (usual caveats with development versions apply!).
```python
import numba

base=('CAD', 'EUR', 'GBP', 'USD')
@numba.njit()
def test():
    res=base[0]
test()
```

**Comment by stuartarchibald** [comment]
Closing since receiving the :+1: from @fingoldo
