### ISSUE TITLE
UnicodeView type

### ISSUE THREAD

**Issue by seibert** [numba/numba#3736]
As an optimization, we could create a special `UnicodeViewType` which is functionally identical to a `UnicodeType`, but is a zero-copy view into the storage of another `UnicodeType`.  This would make slicing a zero allocation operation, and also speed up `str.split()` a lot (see #3678 for some discussion there).

Some notes:

* The behavior here would be similar to NumPy, where the view holds a reference count on a buffer object that it may or may not own.  This means a small view of a long string might force the entire string to stick around, increasing memory usage.
* `UnicodeViewType` would have no unboxing method, and boxing would need to copy the data to Python storage (as `UnicodeType` already does), but also decref the underlying string buffer.

**Comment by ehsantn** [comment]
@seibert I just started looking at this. What about using the same type and not creating a new UnicodeViewType? Looks like UnicodeType doesn't actually depend on owning the data buffer anywhere. The only place I could think of is boxing, but `PyUnicode_FromKindAndData` copies the data anyways (python docs is a bit unclear to me but the code which copes is [here](https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L2208))
