### ISSUE TITLE
Documentation clarification: Does prange produce "parallel code" if parallel=False in jit/njit?

### ISSUE THREAD

**Issue by MSeifert04** [numba/numba#3746]
I've been reading the [documentation](https://numba.pydata.org/numba-doc/0.42.0/user/parallel.html#explicit-parallel-loops) of `prange` and it is not really clear (to me) when `prange` actually produces parallel code:

> ## Explicit Parallel Loops
> Another feature of this code transformation pass is support for explicit parallel loops. One can use Numba’s prange instead of range to specify that a loop can be parallelized.

It seems like this is saying that I need to enable the "code transformation pass". But does that mean setting `parallel=True` or does that refer to jitting in general?

Then I had a look at the docstring of `prange`:

> Provides a 1D parallel iterator that generates a sequence of integers. Sequentially, prange is identical to range.

This did not clarify it neither. Does "sequentially" mean here in case that `parallel=False` is set (or omitted)? Or does that simply refer to the similarity to `range` in general?

So my question is: Does `prange` produce parallel code even if I omit the `parallel` argument or set it to `parallel=False`? 

For example **could** there something "parallel" if I change the example to use just `njit`?

```
from numba import njit, prange
@njit()
def prange_test(A):
    s = 0
    for i in prange(A.shape[0]):
        s += A[i]
    return s
```

If not - and some of my timings (and watching the CPU loads) seem to suggest that it doesn't execute parallel - then it would be super helpful to clearly state that `prange`  is only different from `range` if `parallel=True` is set. 

I've seen several examples in the wild (including one [in the numba](https://github.com/numba/numba/blob/master/examples/kernel-density-estimation/kernel_density_estimation_numba.py#L11-L23)) that use `prange` and/or "advertise" parallel code with `prange` but don't provide `parallel=True` so if that doesn't actually produce parallel execution I'm probably not the only one who missed that.

**Comment by DrTodd13** [comment]
Yes, you only get parallel code if prange is accompanied with parallel=True.  Prange is allowed in non-parallel code because sometimes we apply the decorators later so we get Python, njit and njit(parallel=True) variants and it is convenient to have the same code and not special case the use of prange only in parallel=True mode.

If you have some suggestions of how things could be worded to be super clear then we'd welcome a pull request to clarify matters.  If not, then we'll try to clarify it ourselves eventually.

**Comment by MSeifert04** [comment]
@DrTodd13 Thank you for the clarification.

I made a PR that would've been clarifying for me but english is not my mother tongue so ... it could probably be improved. 😄
