### ISSUE TITLE
can not install 0.42.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by PgLoLo** [numba/numba#3756]
Can not install 0.42.1 version onn Ubuntu 18.04. Bacause of that `pipenv install librosa` fails to install dependencies (it tries to install numba of exactly 0.42.1 version)

**Comment by seibert** [comment]
This is the same problem as #numba/llvmlite#459.  We posted a new wheel for 0.42.1 on macOS only, but pipenv assumes all platforms have the same latest version.  Can you force the usage of 0.42.0 until we can upload wheels for all platforms?

**Comment by sklam** [comment]
i have uploaded the linux wheels for 0.42.1.  Closing.
