### ISSUE TITLE
Reduce numba import time

### ISSUE THREAD

**Issue by eltjpm** [numba/numba#376]
Importing numba appears to be quite slow, especially on Windows. My testing shows import time in a fresh python process to be around 3s on Linux and 12s on Windows. This is becoming a problem for us. We'd like to get import time under a second on Linux and under 1-3 seconds on Windows.

**Comment by pitrou** [comment]
See PR #1024 which will halve Numba import time.

**Comment by pitrou** [comment]
Numba importing is still quite slow: around 400ms here, compared to 150ms for only numpy + llvmlite. That's a 250ms overhead.

**Comment by pitrou** [comment]
I'm closing this as I don't think there's much we can improve right now.
