### ISSUE TITLE
NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode) Variable '$34.2' is not defined.

### ISSUE THREAD

**Issue by Galadriel0** [numba/numba#3765]
![screenshot from 2019-02-13 20-53-56](https://user-images.githubusercontent.com/44665029/52757273-214f6600-2fd2-11e9-99bc-593c35d987c3.png)
Can anyone help? Thanks very much~
The errors are follows:
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    161         try:
--> 162             return self._con[name]
    163         except KeyError:

KeyError: '$34.2'

During handling of the above exception, another exception occurred:

NotDefinedError                           Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get_exact(self, name)
    801         try:
--> 802             return self.localvars.get(name)
    803         except NotDefinedError:

~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    163         except KeyError:
--> 164             raise NotDefinedError(name)
    165 

NotDefinedError: Variable '$34.2' is not defined.

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numba/ir.py in get(self, name)
    161         try:
--> 162             return self._con[name]
    163         except KeyError:

KeyError: '$34.2'

During handling of the above exception, another exception occurred:

NotDefinedError                           Traceback (most recent call last)
<ipython-input-68-027aa3f39a94> in <module>
     44                 columns[39] = b[index_2,1]
     45                 return [columns[15],columns[16],columns[38],columns[39]]
---> 46             data = main("S655kHCRHits.dat")
     47             print(data)
     48 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    354             # These errors are probably from an issue with either the code supplied
    355             # being syntactically or otherwise invalid
--> 356             error_rewrite(e, 'interpreter')
    357         except errors.ConstantInferenceError as e:
    358             # this is from trying to infer something as constant when it isn't

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

NotDefinedError: Failed in object mode pipeline (step: analyzing bytecode)
Variable '$34.2' is not defined.
Unsupported Python functionality was found in the code Numba was trying to
compile. This error could be due to invalid code, does the code work
without Numba? (To temporarily disable Numba JIT, set the `NUMBA_DISABLE_JIT`
environment variable to non-zero, and then rerun the code).

If the code is valid and the unsupported functionality is important to you
please file a feature request at: https://github.com/numba/numba/issues/new

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you paste in the code (and at least one line of the data file) that is causing this problem so that the Numba developers can run it locally to debug the problem? Thanks.

**Comment by Galadriel0** [comment]
import numpy as np
from numba import jit
with open("S655kHCRCoincidences.dat", "r") as f:
    for row in f:
        columns = row.split()
        if len(columns) >= 40:
            event_ID_1= int(columns[1])
            event_ID_2 = int(columns[24])
            module_1 = 32 - int(columns[12])
            module_2 = 32 - int(columns[35])
            block_1 = int(columns[13])
            block_2 = int(columns[36])
            @jit
            def main(filename):
                a = np.empty([0,3])
                b = np.empty([0,3])
                with open(filename) as e:
                    for line in e:
                        lines = line.split()
                        ID = int(lines[1])
                        MODULE = 32-int(lines[5])
                        BLOCK = int(lines[6])
                        if ID == event_ID_1 and MODULE == module_1 and BLOCK ==  block_1:
                            CRYSTAL_1 = int(lines[8])
                            LAYRER_1 = int(lines[9])
                            TIME_STAMP_1 = float(lines[10])
                            temp1 = np.array([[CRYSTAL_1,LAYRER_1,TIME_STAMP_1]])
                            a = np.append(a,temp1,axis=0)
                      
                        elif ID == event_ID_2 and MODULE == module_2 and BLOCK ==  block_2:
                            CRYSTAL_2 = int(lines[8])
                            LAYRER_2 = int(lines[9])
                            TIME_STAMP_2 = float(lines[10])
                            temp2 = np.array([[CRYSTAL_2,LAYRER_2,TIME_STAMP_2]])
                            b = np.append(b,temp2,axis=0)
                       
                time_stamp_1 = a[:,2]
                time_stamp_2 = b[:,2]
                index_1 = np.argmin(time_stamp_1)
                index_2 = np.argmin(time_stamp_2)
                columns[15] = a[index_1,0]
                columns[16] = a[index_1,1]
                columns[38] = b[index_2,0]
                columns[39] = b[index_2,1]
                return [columns[15],columns[16],columns[38],columns[39]]
            data = main("S655kHCRHits.dat")
            print(data)
I am so sorry I cant send the data which I can not attach it, but it is just the .dat file, I attached the Screenshot. Thank you so much!
![screenshot from 2019-02-14 18-38-09](https://user-images.githubusercontent.com/44665029/52824847-4f8f7d00-3088-11e9-9c56-35ea517f9b42.png)

**Comment by stuartarchibald** [comment]
Thanks for the extra information, without data from both files it's not possible to run this. I have mocked up some data and made it so the code will run, however I cannot reproduce the problem. There were some bugs fixed relatively recently for `@jit` so perhaps make sure you are running with the latest Numba version (0.42). 

I think that this code could be helped by Numba, but would need rewriting to solely accommodate the features supported by Numba and ideally to use the `@njit` decorator (`@njit` is the `nopython` fast mode). In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

Further, ideally the `@jit` decorated function needs to be in the module itself and not a closure (else a new version would get compiled every loop iteration), and all the arguments should be passed in to the function including the data read from file (Numba in `nopython` mode does not support `open` and file handling).

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by Galadriel0** [comment]
Sorry to reply lately. Thank you so much, your guide is very helpful, I
learnt much. My numba version is latest 0.42,python version is 3.6. And I
agree the problem is from my own code,because I run other codes
successfully. I tried to check data type and change the open file command
avoiding the with and closure, but still failed and the same error happened
in whether the nopython mode or the  object mode.
Anyway thank you so much !

**Comment by stuartarchibald** [comment]
No problem. If you get a concrete reproducer then please do open a new ticket. Thanks.
