### ISSUE TITLE
[1] During: resolving callee type: Function(<built-in function max>)

### ISSUE THREAD

**Issue by jenny623** [numba/numba#3767]
[1] During: resolving callee type: Function(<built-in function max>)

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:
1. The code that you were running.
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

**Comment by stuartarchibald** [comment]
Closing due to lack of information, if more information is available please reopen this ticket and include it. Thanks.
