### ISSUE TITLE
Type inference for np.min and np.max

### ISSUE THREAD

**Issue by ml31415** [numba/numba#378]
I had a bit of a grief today, when I couldn't figure the reason for a very slow jitted execution: http://stackoverflow.com/questions/20679380/optimizing-access-on-numpy-arrays-for-numba

Looks like the type inference for `np.min` and `np.max` should be added, just like for `sum` and `prod`. The detection code is more or less already there in `type_inference/modules/numpyufuncs.py` and would just need to be registered again.

    register_inferer(np, 'max', reduce_)
    register_inferer(np, 'min', reduce_)

All the nanmin, nanmax, nansum are also missing.

**Comment by pitrou** [comment]
This is now supported in nopython mode.
