### ISSUE TITLE
Numba problem in for loop

### ISSUE THREAD

**Issue by tarunbadial** [numba/numba#3783]
## i run a code by using numba iam facing following problem:

![screenshot from 2019-02-20 18-03-30](https://user-images.githubusercontent.com/43639402/53092143-f74df480-3539-11e9-8a10-aab27f61e2c3.png)

**Comment by stuartarchibald** [comment]
Thanks for the report. Dictionaries are not yet supported, hence the error message regarding unsupported functionality. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

The next release of Numba (scheduled for sometime in the next few weeks) will have some basic dictionary support.
