### ISSUE TITLE
isnan(int) isinf(int) should work

### ISSUE THREAD

**Issue by sklam** [numba/numba#3789]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

`math.isnan(123)` and `math.isinf(123)` should not cause jit'ed function to raise TypingError.

**Comment by sklam** [comment]
This can be probably be solved easily by implementing isnan(int)=>False

**Comment by esc** [comment]
@sklam could you provide a minimal snippet that exposes this bug?

**Comment by sklam** [comment]
@esc 
Oh, I just noticed it only break CUDA backend.

```python
from numba import njit
from numba import cuda
import math

@cuda.jit
def foo(x):
    math.isnan(x)


foo(1)
```
will raise:
```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No definition for lowering <built-in function isnan>(int64,) -> bool

File "isnan.py", line 7:
def foo(x):
    math.isnan(x)
    ^

[1] During: lowering "$0.4 = call $0.2(x, kws=[], vararg=None, func=$0.2, args=[Var(x, isnan.py (7))])" at isnan.py (7)
```

**Comment by sklam** [comment]
The lowering error indicates that the CUDA backend has no implementation for it.  An implementation is needed in https://github.com/numba/numba/blob/master/numba/cuda/libdevice.py

**Comment by niteya-shah** [comment]
I'd like to work on this issue.

**Comment by esc** [comment]
@niteya-shah feel free to address the issue and submit a pull-request for review.
