### ISSUE TITLE
Simplify and expose maximum register use in code in cuda.kernel

### ISSUE THREAD

**Issue by cems2** [numba/numba#3798]
**Problem being addressed**

- invoking a kernel for which number_registers*number_threads > 65K (or whatever the cuda capacity is for the device) will always error with a cryptic "out of resources" cuda error.

This can be handled more gracefully since the inevitable train wreck is easily detected when one calls the kernel function at runtime.  Just check the above inequality and then give a warning that the register count requires a lower thread count to run.

**Going beyond this**
There are three further steps one, small and one large that would greatly improve refactoring cuda code to get better occupancy by reducing register use.

First, document the command _func.get().attr which is a way for the user to get the register count and thus understand where the resources are going.

Second, it appears to me that the kernel keyword max_registers does not actually work to limit the max_registers used.  I filed a bug report on this.  But if I'm mistaken on it's proper use then better documents would help that too.

**The Big one that would be really nice**
Third, Is there some way to tell what lines of code are requiring registers?  Code seems to use far more registers than one can easily guess by looking at it.  for example:
https://gist.github.com/sklam/0e750e0dea7571c68e94d99006ae8533

I would suggest that a  really really nice interface for tracking registers would be to build it into the .inspect_types output.    In addition to listing a type one could also add the tag  ":: K registers"  where K is the number of registers the line of code is causing to be used.

**Comment by gmarkall** [comment]
Some comments:

- PR #6447 addresses the request to provide a better way for the user to get register usage.
- Issue #3795 addresses the `max_registers` keyword not respecting the request.
- "The big one" - to provide a way to provide the register requirements of each line is infeasible, as in general there isn't a correlation between register usage and specific lines.
