### ISSUE TITLE
Windows: Numba should use math functions from C runtime

### ISSUE THREAD

**Issue by eltjpm** [numba/numba#380]
Let me know if this is addressed by llvmmath.
```python
from   numba import jit, double
import math

@jit(double(double))
def tan(x):
    return math.tan(x)

def main():
    print tan(math.pi/2)
    print math.tan(math.pi/2)
```
I get this result:
```
1.63317787284e+16
1.63312393532e+16
```
The values turn out to be quite different, because different implementations of tan are used. The `math` module uses math functions from CRT it's linked with. For VC9 these functions use SSE2 implementations by default. Compiled code creates a call to `tan`. As Numba does not explicitly map `tan` to some address, JIT does a symbol search that emulates Unix behavior. It ends up picking it up from `ntdll` instead of CRT. ntdll does not have SSE2 implementations (as of Windows 7). This causes inconsistent results and possibly lower performance.

**Comment by pitrou** [comment]
`llvmmath` doesn't exist anymore. For trigonometric functions, we tend to use libc implementations if possible (for C89 functions). For some simpler functions, we may still use our own implementations to allow for inlining and vectorizing. This is an implementation decision that will probably not change, so I'm closing this issue (finally :-)).
