### ISSUE TITLE
 Please report the error message and traceback, along with a minimal reproducer

### ISSUE THREAD

**Issue by jiedr** [numba/numba#3801]

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

**Comment by seibert** [comment]
Feel free to reopen this issue if you can provide more information.
