### ISSUE TITLE
Code restructuring

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3807]
Ideally, Numba should have a clear code structure and a simple document explaining this structure to help ramp up new core developers. Currently, there are a lot of files in the root (`numba/`) directory that should be moved in folders. For example:

- A folder for analysis/transformations/optimizations?
- A folder for basics of Python such as dictionaries and strings?
- A folder for utility C extensions?

@seibert @sklam @stuartarchibald @DrTodd13 Ideas?

**Comment by innovate-invent** [comment]
I would like to point out my issue addressing this #2980. It has a more comprehensive plan.

**Comment by stuartarchibald** [comment]
0.49 undertook a large refactoring, https://github.com/numba/numba/pull/5197, which addresses the above, the docs also now contain a repo map http://numba.pydata.org/numba-doc/latest/developer/repomap.html. Am going to close this issue, if there's specific fixed scope things that can be improved further please feel free to open additional tickets, thanks.
