### ISSUE TITLE
Implement bytes on DeviceNDArray

### ISSUE THREAD

**Issue by TomAugspurger** [numba/numba#3810]
It'd be useful to know the size in bytes of a DeviceNDArray. With a NumPy array I would use `.nbytes`. To write code that supports memoryview, ndararys, and DeviceNDArrays, it'd be great if these were all called `.nbytes`.

With a DeviceNDArray, it seems like the two options are `.alloc_size` or `.dtype.itemsize * .size`

```python
In [14]: arr = numba.cuda.device_array((4, 3))

In [15]: arr.dtype.itemsize * arr.size
Out[15]: 96
```

I didn't see `.alloc_size` documented in https://numba.pydata.org/numba-doc/dev/cuda/memory.html.

**Comment by mrocklin** [comment]
@quasiben can I ask you to handle this?  it'd be good to get the ball rolling on this soon so a Numba release can come out and we don't have to special case this in Dask.

**Comment by quasiben** [comment]
yes.  I'll take a look shortly
