### ISSUE TITLE
Sum with axis argument on 1d array returns array instead of skalar

### ISSUE THREAD

**Issue by P-Tillmann** [numba/numba#3815]
When numba performs a sum reduction with specified axis parameter on a 1d array it returns again an array. However numpy returns a skalar for the same case.

Would you consider this a bug?

Best,
Peter

Example(tested on numba from git master):

```
import numpy as np
import numba

@numba.njit
def numba_sum():
    return np.array([1,2,3]).sum(axis=-1)

print('Expected: {}'.format(
        type(np.array([1,2,3]).sum(axis=0))
        ))
print('Numba jitted: {}'.format(
        type(numba_sum())
        ))

Expected: <class 'numpy.int64'>
Numba jitted: <class 'numpy.ndarray'>
```

**Comment by seibert** [comment]
Yes, this should be considered a bug.  Usually when someone specifies an axis, it is for a higher dimensional array, so the return is also an array.  We need to special case the 1D situation to return a scalar.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bug.

```python
import numpy as np
import numba

@numba.njit
def f():
    return np.array([1,2,3]).sum(axis=-1)

print(f(), type(f()))
print(f.py_func(), type(f.py_func()))
```
gives
```
6 <class 'numpy.ndarray'>
6 <class 'numpy.int64'>
```

**Comment by P-Tillmann** [comment]
Thanks for the quick fix!

**Comment by stuartarchibald** [comment]
@P-Tillmann no problem, new development builds should roll out within the next few hours. If you would like to try out the latest development releases of Numba they are available via:
```bash
conda install -c numba/label/dev numba
```
(usual caveats about development versions apply!).
