### ISSUE TITLE
setup.py integration doc not for real, multi-file use case

### ISSUE THREAD

**Issue by nmgeek** [numba/numba#3824]
It appears to me that the example integration with AOT and distutils (or setuputils) works _only_ when there is one and only one source file.  And from #3823 it also seems that the source file can contain only one level of hierarchy in its functions.  The documentation (and perhaps implementation) sorely needs a real world example with _multiple_ source files in a package subdirectory.

The typical pattern for python packages is to put the python source files in a directory below the directory holding setup.py.  The numba setup.py example in the documentation, however, shows the .py file to be compiled into the _same_ directory.

This is a one-file use case, all the source must be in a single file.

When your source files are in the package subdirectory then you have to import the AOT file like this:

`from package_name.my_module import cc
`

And when you do this, the extension module shared library ends up in the directory _above_ the package and is therefore a standalone, separate module.  With this configuration the source file is also installed inside the package module directory so that it s .pyc file is what runs when you import via package_name.my_module.  So such a configuration runs, but runs the pyc code instead of the compiled code inside the compiled module.

**Comment by esc** [comment]
@nmgeek it seems that this issue hasn't seen any attention for over two years. Can you confirm that the bug is still present in the source?
