### ISSUE TITLE
kernel crashing under jupyter

### ISSUE THREAD

**Issue by leobargigli** [numba/numba#3827]
## Reporting a bug

- [X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

there is no traceback since simply the kernel (Python 3) dies out repeatedly (but not always)
I run Ubuntu 18.04.2 LTS

the code is as follows:
```python
import numpy as np
from numpy.random import uniform, normal, seed
from numba import jit

@jit(nopython = True, parallel=True)
def switch(N,T,a,b,N_opt):
    trun = 0
    xold = 2*N_opt/N - 1
    x = np.zeros((T,))
    x[0] = xold
    told = 0
    while trun < T: 
        omeg1 = a + b* N_opt 
        omeg2 = a + b* (N - N_opt) #omeg2: trans. rate from optimistic to pessimistic
        u = uniform(0,1)# uniform random number
        lamda = N_opt* omeg2 + (N - N_opt) *omeg1 # adding up transition rates over all *nx agents
        tchange = -np.log(u)/lamda # exponentially distributed next event time
        trun += tchange #increment run time
        u = uniform(0,1)
        if u <= N_opt * omeg2 / lamda: # if satisfied, an optimist switches to pessimist
            N_opt += - 1 
        else: # otherwise, a pessimist switches to optimist
            N_opt += 1
        xnew = 2 * N_opt / N - 1
        tnew = int(np.floor(trun))
        for i in range(told,tnew):
            x[i] = xold
        xold = xnew
        told = tnew
    return x


def ALW_model(N,T,a,b,N_opt,sigma):
    x = switch(N,T,a,b,N_opt)
    eps = np.random.normal(0,sigma,T)
    pf = np.cumsum(eps)
    p = pf + N*x*C/F
    return p,x

N = 100.
a = 0.3/1000
b = 1.4/1000
sigma = 1.
C = 1.
F = 1.
T = 2000
N_opt = 50.

args = (N,t,a,b,N_opt,sigma)
p,x = ALW_model(*args)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I've reformatted the text so it's easier to read, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by leobargigli** [comment]
Thanks for your assistance!

Il giorno lun 4 mar 2019 alle ore 16:54 stuartarchibald <
notifications@github.com> ha scritto:

**Comment by stuartarchibald** [comment]
No problem. If the `@jit` decorator is removed and the function is run under NumPy only, this sort of thing can happen:
```
$ python issue3827.py 
Traceback (most recent call last):
  File "issue3827.py", line 51, in <module>
    p,x = ALW_model(*args)
  File "issue3827.py", line 34, in ALW_model
    x = switch(N,T,a,b,N_opt)
  File "issue3827.py", line 27, in switch
    x[i] = xold
IndexError: index 2000 is out of bounds for axis 0 with size 2000
```
I also see segfaults when the `@jit` decorator is applied which is the likely cause of the Jupyter kernel dying. I suspect once the code is fixed up to index always in bounds the kernel death issue will resolve.

**Comment by leobargigli** [comment]
thank you very much!

Il giorno lun 4 mar 2019 alle ore 18:29 stuartarchibald <
notifications@github.com> ha scritto:

**Comment by stuartarchibald** [comment]
No problem, I'm going to close this now, if you still have the same problem once you've fixed the code please reopen this issue. Thanks.
