### ISSUE TITLE
ARMv8 cuda findlib issue

### ISSUE THREAD

**Issue by cosama** [numba/numba#3831]
### Versions
* `python 3.6`
* `llvmlite 0.28.0.dev0+41.gd5fadcc` (compiled from source, current master)
* `numba==0.43.0.dev0+577.g1bfb050f4` (compiled from source, current master)

### System
* ARM v8.2 with custom Ubuntu 18.04 (see [Jetson Xavier](https://developer.nvidia.com/embedded/buy/jetson-agx-xavier-devkit))

### Minimum working reproducer
```
import numba
from numba import cuda

@cuda.jit('(int64, float32)')
def cuda_issue(dd, ff):
    test = dd + ff

cuda_issue(1,1.1)
```

### Error message:
```
Traceback (most recent call last):
  File "cuda_issue.py", line 4, in <module>
    @cuda.jit('(int64, float32)')
  File "numba/numba/cuda/decorators.py", line 98, in kernel_jit
    kernel.bind()
  File "numba/numba/cuda/compiler.py", line 503, in bind
    self._func.get()
  File "numba/numba/cuda/compiler.py", line 381, in get
    ptx = self.ptx.get()
  File "numba/numba/cuda/compiler.py", line 352, in get
    **self._extra_options)
  File "numba/numba/cuda/cudadrv/nvvm.py", line 475, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "numba/numba/cuda/cudadrv/nvvm.py", line 350, in __init__
    if get_libdevice(arch) is None:
  File "numba/numba/cuda/cudadrv/libs.py", line 22, in get_libdevice
    candidates = find_file(re.compile(pat), libdir)
  File "numba/numba/findlib.py", line 45, in find_file
    entries = os.listdir(ldir)
FileNotFoundError: [Errno 2] No such file or directory: 'u'
```

### Additional information

* Bug was not present in `numba==0.42.0`, using the above mentioned version of `llvmlite`.
* I currently am running the `numba` tests on the machine but they take quite a while. I can upload the logs for both `0.42.0` and the most recent version if that would help to also resolve some other issues.

**Comment by stuartarchibald** [comment]
Thanks for the report, I've a feeling I know what's causing this. Some changes to library finding were needed to accommodate some necessary alterations in the latest builds of the `cudatoolkit` package on windows. I think when I patched it I didn't anticipate code paths that would end up with a a single string as the `libdir` argument, so it ends up doing `list(<string>)` hence the single char as the search dir.

**Comment by stuartarchibald** [comment]
In fact, this reproduces on `x86`:
```
NUMBAPRO_LIBDEVICE="/usr/local/somelib.so" python issue3831.py 
```

**Comment by cosama** [comment]
@stuartarchibald Thanks so much for looking into this so quickly. Your pull request fixes that issue for me.

**Comment by stuartarchibald** [comment]
@cosama No problem, thanks for confirming the fix works!
