### ISSUE TITLE
support `__mul__` for strings

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3834]
## Feature request

As title. This sort of thing should work:

```python
'abc' * 5
'abc'.__mul__(5) 
```

**Comment by luk-f-a** [comment]
@stuartarchibald, if this is still open I can make a PR.

**Comment by stuartarchibald** [comment]
@luk-f-a this is still open, a PR would be most welcome, thanks for offering!

The use of Numba's extension API is strongly recommended for this task, documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html).

If you get stuck/need a hand, the Numba core developers are also available on [gitter.im](https://gitter.im/numba/numba) real time chat.

Thanks again.

**Comment by luk-f-a** [comment]
@stuartarchibald  #3952 is ready for review.
