### ISSUE TITLE
numba with cudatoolkit on Windows not finding libraries

### ISSUE THREAD

**Issue by MattWenham** [numba/numba#3840]
I've bounced this over from https://github.com/numba/conda-recipe-cudatoolkit/issues/16

I finally got `numba -s` to correctly recognise my GPU by using `cudatoolkit` (current version 10.0) and not the nVidia CUDA SDK (currently at version 10.1). I got the following output:

    __CUDA Information__
    Found 1 CUDA devices
    id 0        b'GeForce MX130'                              [SUPPORTED]
                          compute capability: 5.0
                               pci device id: 0
                                  pci bus id: 3
    Summary:
            1/1 devices are supported
    CUDA driver version                           : 10010
    CUDA libraries:
    Finding cublas
            ERROR: can't locate lib
    Finding cusparse
            ERROR: can't locate lib
    Finding cufft
            ERROR: can't locate lib
    Finding curand
            ERROR: can't locate lib
    Finding nvvm
            named  nvvm64_33_0.dll
            finding libdevice for compute_20...     ok
            finding libdevice for compute_30...     ok
            finding libdevice for compute_35...     ok
            finding libdevice for compute_50...     ok

[This page](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/V2aKezXuOh8) helped me realise that I needed to manually set `NUMBAPRO_CUDALIB`. I searched for `cublas64_100.dll` and set `NUMBAPRO_CUDALIB` manually, I then got output which showed that the libraries had been found:

    __CUDA Information__
    Found 1 CUDA devices
    id 0        b'GeForce MX130'                              [SUPPORTED]
                          compute capability: 5.0
                               pci device id: 0
                                  pci bus id: 3
    Summary:
            1/1 devices are supported
    CUDA driver version                           : 10010
    CUDA libraries:
    Finding cublas
            named  cublas64_100.dll
            trying to open library...       ok
    Finding cusparse
            named  cusparse64_100.dll
            trying to open library...       ok
    Finding cufft
            named  cufft64_100.dll
            trying to open library...       ok
    Finding curand
            named  curand64_100.dll
            trying to open library...       ok
    Finding nvvm
            named  nvvm64_33_0.dll
            trying to open library...       ok
            finding libdevice for compute_20...     ok
            finding libdevice for compute_30...     ok
            finding libdevice for compute_35...     ok
            finding libdevice for compute_50...     ok

Comments on the `cudatoolkit` issue I raised linked above said that 

> Numba should be searching for the cudatoolkit where it is installed in the conda environment and not relying on the environment variable, which is intended to override the default behavior. If Numba is failing to find the required libraries, that is a Numba bug.

**Comment by seibert** [comment]
As @stuartarchibald reminded me, it is possible we fixed this on master a few weeks ago.  Can you try out the release candidate for Numba 0.43 we just posted?

```
conda install -c numba numba=0.43.0rc1
```

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Comment by MattWenham** [comment]
Yes, using `cudatoolkit` version 10 and setting `NUMBAPRO_CUDALIB` manually fixed the issue.

**Comment by stuartarchibald** [comment]
Great, thanks for confirming.
