### ISSUE TITLE
"data type not understood" with readonly array argument

### ISSUE THREAD

**Issue by batterseapower** [numba/numba#3844]
## Reporting a bug

The following program should succeed, because `astype` makes a copy of its argument:

```
@nb.jit()
def numba_astype(xs):
    ys = xs.astype(nb.float32)
    ys[0] = 1.0
    return ys

xs = np.array([1.0], dtype='f4')
xs.flags.writeable = False
numba_astype(xs)
```

In fact it just throws `TypeError: data type not understood`. (This might be related to the fact that the type of the array returned by `astype` is still marked `readonly` if the inital array is `readonly` - i.e. the readonly flag is not being cleared.)

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. Fixed in https://github.com/numba/numba/pull/3845

**Comment by batterseapower** [comment]
That was impressively fast. Thanks!

**Comment by stuartarchibald** [comment]
No problem!
