### ISSUE TITLE
Rewrite of refcount pruning pass w/o regex

### ISSUE THREAD

**Issue by sklam** [numba/numba#3851]
## Feature request

https://github.com/numba/llvmlite/pull/466 opens up a possibility to rewrite the refcount pruning pass without the use of hacky regex. 

It will also need a quick patch to add binding to `LLVMInstructionEraseFromParent`.

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/6266. Closing.
