### ISSUE TITLE
Support np.delete

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3854]
## Feature request

From https://stackoverflow.com/questions/55103396/delete-element-from-array-numba

as title.

**Comment by guilhermeleobas** [comment]
Hi, I can work on this one!

**Comment by stuartarchibald** [comment]
@guilhermeleobas great, thanks!

As a new contributor, some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.

The use of Numba's extension API `@overload` decorator is strongly recommended for this task, documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

If you get stuck/need a hand, the Numba core developers are also available on [gitter.im](https://gitter.im/numba/numba) real time chat.

Thanks again!
