### ISSUE TITLE
Raise error directly from typing template

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3868]
## Feature request

Currently, type inference catches and aggregates all errors in the typing templates and prints extensive debug info for all templates. However, some templates might encounter fatal errors that need to be reported to the user in a succinct format. Maybe we can use a special-purpose exception type for this purpose.

**Comment by ehsantn** [comment]
`TypingError` seems to provide this functionality to large extent. Is it recommended to use?

**Comment by sklam** [comment]
yes,`TypingError` is recommended.

**Comment by ehsantn** [comment]
Ok, thanks.

**Comment by sklam** [comment]
@ehsantn 

But is that sufficient though?

I thought you want it to not show the error messages from other templates:


<details><summary>example code</summary>

```python
from numba import njit
from numba.extending import overload
from numba.errors import TypingError


def do(x):
    pass

@overload(do)
def impl_do_1(x):
    raise TypingError(1)


@overload(do)
def impl_do_2(x):
    raise TypingError(2)

@njit
def foo(x):
    return do(x)

foo(1)
```

</details>


the error message
```
Invalid use of Function(<function do at 0x101d980d0>) with argument(s) of type(s): (int64)
 * parameterized
In definition 0:
    TypingError: 1
    raised from chkerr.py:11
In definition 1:
    TypingError: 1
    raised from chkerr.py:11
In definition 2:
    TypingError: 2
    raised from chkerr.py:17
In definition 3:
    TypingError: 2
    raised from chkerr.py:17
```

**Comment by ehsantn** [comment]
Ideally, yes. But many of my cases have just one template. I'll reopen this for future reference.

**Comment by stuartarchibald** [comment]
I think #7397 covers this, using the `new_style` captured error handling makes any exception raised during compilation that does not inherit from a `numba.core.errors.NumbaError` into a "hard error", i.e. the exception will propagate the compilation will halt. Closing as fixed.
