### ISSUE TITLE
Dict.get(k,default) is a little fussy about the type of default

### ISSUE THREAD

**Issue by stuz5000** [numba/numba#3880]
In 0.43.0, Dict.get is extremely fussy about the type of the second parameter to Dict.get (but not 
about the key parameter):
```
import numba
import numba.typed

@numba.njit()
def test1(d):
    return d[1]   # OK

@numba.njit()
def test2(d):
    return d.get(1,0)  # Fails because 0 is not explicitly int64

d = numba.typed.Dict.empty(
    key_type=numba.types.int32,
    value_type=numba.types.int32, 
)
d[1] = 10
test1(d) # OK
test2(d) # Fails

d.get(1,numba.types.int32(0))  # .get(int64, int32) ==> OK
d.get(1,0)                                  # .get(int64, int32) ==> fails
```

I'd expect that if the key parameter can be handled without explicitly casting it to int32, so could the default parameter.

**Comment by stuartarchibald** [comment]
Thanks for the report, this sort of feedback is v. helpful. The typed dictionaries are extremely strict right now, once automatic type inference is implemented (it's coming soon) some of this sort of difficulty should go away. Ping @sklam, I think the above is a helpful motivating case.

**Comment by stuz5000** [comment]
Perhaps leave open to avoid questions until resolved with type inference?
