### ISSUE TITLE
np.random.choice doesn't adhere to np.random.seed inside of numba

### ISSUE THREAD

**Issue by grej** [numba/numba#3888]
np.random.choice does not seem to be following the np.random.seed the same way other np.random functions are, from within numba:

Example code:
```
choice_array = np.random.randint(300, size=1000).astype(np.int32)

# select two random values without replacement from an array:
def nprands(n_to_return):
    np.random.seed(1337)
    out = np.empty((n_to_return, 2), np.int32)
    for i in range(n_to_return):
        out[i] = np.random.choice(choice_array, 2, False)
    return out

nprands(5)

>>>
##  array([[286, 101],
##       [ 60, 126],
##       [225, 161],
##       [175,  17],
##       [125,  33]], dtype=int32)

@numba.njit
def numba_rands(n_to_return):
    np.random.seed(1337)    
    out = np.empty((n_to_return, 2), np.int32)
    for i in range(n_to_return):
        out[i] = np.random.choice(choice_array, 2, False)
    return out

numba_rands(5)

>>>
##  array([[233,  86],
##       [ 68, 243],
##       [257, 252],
##       [254, 182],
##       [  5,  64]], dtype=int32)

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bug, I think it's down to implementation differences between NumPy and Numba.

**Comment by grej** [comment]
@stuartarchibald - you were correct it was an implementation difference, and a straightforward fix. PR ready for review.

**Comment by mgbukov** [comment]
does anyone know starting from when this fix will be effective?

**Comment by stuartarchibald** [comment]
@mgbukov once https://github.com/numba/numba/pull/3897 is completed and merged to master the fix will be in the release that follows. IIRC that pull request needs tests adding to assert the change is valid and then it can be reviewed.

**Comment by stuartarchibald** [comment]
Closing, patches forwarded to https://github.com/numba/numba/pull/5310 with view to merge that.
