### ISSUE TITLE
Implement swapaxes

### ISSUE THREAD

**Issue by clemisch** [numba/numba#3891]
## Feature request

Dear `numba` team,

it would be great to have support for `swapaxes`, as it allows for clean code when working with arrays of arbitrary dimension and similar multiplications along specific axes. 

For example, this would be handy for computing the discrete spatial gradient.

```python
def gradient(arr, axis):
    out = zeros((len(axis),) + arr.shape, dtype=arr.dtype)

    for i, k in enumerate(axis):
        # swap current gradient axis to the front
        out_swap = swapaxes(out, 1, 1+k)
        arr_swap = swapaxes(arr, 0, k)

        # central difference
        out_swap[i, 1:-1] = 0.5 * (arr_swap[2:] - arr_swap[:-2])

        # forward/backward diff at borders
        out_swap[i, 0] = arr_swap[1] - arr_swap[0]
        out_swap[i, -1] = arr_swap[-1] - arr_swap[-2]

    return out
```

This is just an example; I'm aware of the `gradient` function in `numpy` ;-)

Thanks for your continuous effort on this great package!

**Comment by dkafri** [comment]
It looks like [numpy.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html) is implemented in [numba](https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#other-methods). You can pass an arbitrary axis ordering to this function, so I think this should provide the same functionality as `swapaxes`.

**Comment by stuartarchibald** [comment]
I don't think the Numba implementation of `np.transpose` (as of 0.48) supports arguments.

**Comment by clemisch** [comment]
Thank you @dkafri for the suggestion! I've actually already tried this for myself, but ran into numba compiler errors which I was not able to resolve. 

@stuartarchibald `np.transpose` seems to support arguments, as in an explicit `return np.transpose(x, (1, 2, 0))` for example. When I tried to construct the arguments more dynamically is where I ran into problems. 

Repro:
```python
import numpy as np
from numba import jit
from functools import partial

@partial(jit, nopython=True)
def swap(x, a, b):
    axes = list(range(x.ndim))
    axes[a], axes[b] = axes[b], axes[a]
    return np.transpose(x, tuple(axes))

x = np.random.rand(10, 20, 30)
print(x.shape)
print(swap(x, 1, 2).shape)
```

gives
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<class 'tuple'>) with argument(s) of type(s): (list(int64))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<class 'tuple'>)
[2] During: typing of call at <ipython-input-3-6cc830e49edf> (9)


File "<ipython-input-3-6cc830e49edf>", line 9:
def swap(x, a, b):
    <source elided>
    axes[a], axes[b] = axes[b], axes[a]
    return np.transpose(x, tuple(axes))
    ^
```

**Comment by dkafri** [comment]
@clemisch, I think you need to limit your variables to numpy arrays and homogeneously typed tuples. Here is a version of swap that works (on numba 0.48), but with a somewhat different call signature:

```python
import numpy as np
from numba import jit
from functools import partial


@partial(jit, nopython=True)
def swap(x, t_args):
    return np.transpose(x, t_args)


x = np.random.rand(10, 20, 30)
print(x.shape)
print(swap(x, (0, 2, 1)).shape)

```
You may want to consider setting `cache=True` in the call to `jit`.

> I don't think the Numba implementation of `np.transpose` (as of 0.48) supports arguments.

@stuartarchibald, `transpose`  seems to support arguments for me. I was able to implement a kludgy version of tensordot.

```python
import numpy as np
from numba import jit
from typing import Tuple


@jit(nopython=True)
def my_tensor_dot(left: np.ndarray, transpose_args_left: Tuple[int, ...],
                  left_shape: Tuple[int, ...], right: np.ndarray,
                  transpose_args_right: Tuple[int, ...],
                  right_shape: Tuple[int, ...],
                  output_shape: Tuple[int, ...]) -> np.ndarray:
    # We will need to reshape the array so that the contracted indices are
    # merged into the first index. To do so the array data must be C-contiguous.
    right = np.ascontiguousarray(np.transpose(right, transpose_args_right))
    # merge contracted indices
    right = right.reshape(right_shape)

    left = np.ascontiguousarray(np.transpose(left, transpose_args_left))
    left = left.reshape(left_shape)

    # take contraction and unmerge axes
    return np.dot(left, right).reshape(output_shape)


L = np.arange(24, dtype=float).reshape((4, 3, 2))
R = np.arange(60, dtype=float).reshape((3, 5, 4))

L_t_args = (2, 1, 0)
R_t_args = (0, 2, 1)
L_shape = (2, 12)
R_shape = (12, 5)
LR_shape = (2, 5)

actual = my_tensor_dot(L, L_t_args, L_shape, R, R_t_args, R_shape, LR_shape)
expected = np.tensordot(L, R, ((1, 0), (0, 2)))
np.testing.assert_almost_equal(actual, expected)
```

**Comment by stuartarchibald** [comment]
@dkafri ah great, thanks for looking, the docs could probably do with an update.

**Comment by clemisch** [comment]
Thanks for the suggestion @dkafri. Your version of `swap` is merely a proxy for `transpose`, which does not fulfil the same role as `swapaxes`. That's the reason why I created this issue in the first place ;-) 

I was hoping that someone could cast some light on the problem or a solution/workaround for the error from my repro. 
(The swapaxes behavior is there; it's "just" not jit'able.)

**Comment by blackbox-tech** [comment]
If it helps you, this is what I do in my own code.  This works because ```a.ndim``` is known at compile time.

```python
import numba as nb
from numba.np.unsafe.ndarray import to_fixed_tuple, tuple_setitem

@nb.njit
def swapaxes(a, axis1, axis2):
    """ Numba swapaxes ala np.swapaxes() """
    axis1 = a.ndim + axis1 if axis1 < 0 else axis1
    axis2 = a.ndim + axis2 if axis2 < 0 else axis2
    if axis1 == axis2:
        return a
    pos = to_fixed_tuple(np.arange(a.ndim), a.ndim)
    tmp = pos[axis1]
    pos = tuple_setitem(pos, axis1, pos[axis2])
    pos = tuple_setitem(pos, axis2, tmp)
    return a.transpose(pos)
```

**Comment by clemisch** [comment]
That looks great @blackbox-tech! I was not aware of `to_fixed_tuple` and `tuple_setitem`, thanks.

**Comment by esc** [comment]
@blackbox-tech thanks for submitting this! Perhaps this implementation could be the beginning of a pull-request to implement the requested feature? 😉

**Comment by blackbox-tech** [comment]
Will do...

**Comment by blackbox-tech** [comment]
> @blackbox-tech thanks for submitting this! Perhaps this implementation could be the beginning of a pull-request to implement the requested feature?

I'm not familiar with the innards of numba, so I've not yet been able to get it to work.  I tried this but I got stuck as the ```@overload``` decorator seems to only except pure-python, so the ```to_fixed_tuple``` intrinsic is not available.  Also numba's ```np_transpose_impl()``` signature does not take a tuple, so I'm not sure how to pass my arguments to it?

```python
@overload(np.swapaxes)
def numpy_swapaxes(a, axis1, axis2):
    @register_jitable
    def numpy_swapaxes_impl(a, axis1, axis2):
        if isinstance(axis1, types.Literal):
            axis1 = axis1.literal_value
        if isinstance(axis2, types.Literal):
            axis2 = axis2.literal_value
        axis1 = a.ndim + axis1 if axis1 < 0 else axis1
        axis2 = a.ndim + axis2 if axis2 < 0 else axis2
        if axis1 == axis2:
            return a
        pos = to_fixed_tuple(np.arange(a.ndim), a.ndim)
        tmp = pos[axis1]
        pos = tuple_setitem(pos, axis1, pos[axis2])
        pos = tuple_setitem(pos, axis2, tmp)
        return np_transpose_impl(a, pos)
    return numpy_swapaxes_impl(a, axis1, axis2)
```

Any pointers on how to overload numpy functions with numba code instead of pure-python would be great.

**Comment by esc** [comment]
@blackbox-tech I am not sure what the error message is you are receiving. But perhaps the following will help?

http://numba.pydata.org/numba-doc/latest/extending/overloading-guide.html

I have never seen `@register_jitable` being used with an `@overload`. If code works within `@njit` it is likely to working with `@overload`.

**Comment by stuartarchibald** [comment]
The use of Numba's extension API `@overload` decorator is strongly recommended for this task. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

**Comment by stuartarchibald** [comment]
Also, this is a bit tricky as literals are required, here's a rough sketch to get a PR going:
```python
from numba import njit, literally, types
import numpy as np
from numba.extending import overload
from numba.np.unsafe.ndarray import to_fixed_tuple, tuple_setitem

@overload(np.swapaxes)
def numpy_swapaxes(a, axis1, axis2):
    # THIS IS TYPING SCOPE, EVERYTHING IS A TYPE

    # This is a special function to tell Numba to go and get literal values
    # if they aren't literal already
    force_literal = lambda a, axis1, axis2: a, literally(axis1), literally(axis2)
    if isinstance(axis1, types.Literal):
        axis1_val = axis1.literal_value
    else:
        return force_literal
    if isinstance(axis2, types.Literal):
        axis2_val = axis2.literal_value
    else:
        return force_literal

    def impl(a, axis1, axis2):
        # THIS IMPLEMENTATION SCOPE, BUT YOU CAN ACCESS THE OUTER SCOPE
        axis1 = a.ndim + axis1_val if axis1_val < 0 else axis1_val
        axis2 = a.ndim + axis2_val if axis2_val < 0 else axis2_val
        if axis1 == axis2:
            return a
        pos = to_fixed_tuple(np.arange(a.ndim), a.ndim)
        tmp = pos[axis1]
        pos = tuple_setitem(pos, axis1, pos[axis2])
        pos = tuple_setitem(pos, axis2, tmp)
        return a.transpose(pos)

    return impl


@njit
def foo(a):
    return np.swapaxes(x, 0, 2)

x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

print(foo(x))
```

**Comment by blackbox-tech** [comment]
@stuartarchibald  I've started a PR here https://github.com/numba/numba/pull/6272 but I'm not at all confident it correct if you want to review it?

**Comment by clemisch** [comment]
`np.swapaxes` seems to be implemented in the way I needed it when creating this function.

Working repro:

```python
import numpy as np
from numba import jit
from functools import partial


@partial(jit, nopython=True)
def gradient(arr, axis):
    out = np.zeros((len(axis),) + arr.shape, dtype=arr.dtype)

    for i, k in enumerate(axis):
        # swap current gradient axis to the front
        out_swap = np.swapaxes(out, 1, 1+k)
        arr_swap = np.swapaxes(arr, 0, k)

        # central difference
        out_swap[i, 1:-1] = 0.5 * (arr_swap[2:] - arr_swap[:-2])

        # forward/backward diff at borders
        out_swap[i, 0] = arr_swap[1] - arr_swap[0]
        out_swap[i, -1] = arr_swap[-1] - arr_swap[-2]

    return out


x = np.random.rand(2, 10)
print(x.shape)  # (2, 10)
print(gradient(x, (0, 1)).shape)  # (2, 2, 10)
```
