### ISSUE TITLE
Meta issue: SSA for variable

### ISSUE THREAD

**Issue by sklam** [numba/numba#3904]
## Feature request

Use SSA for variables.

- `func_ir.get_definitions()` problems
    - problem example:
        ```python
        def doit(x):
            return x

        def bar(pred):
            if pred:
                foo = True
            else:
                foo = False
            # do something with foo
            return doit(foo)
        ```
    - because `foo` has one name in all basic-blocks.  Analysis cannot easily tell what local `foo` definition must be.  For instance, if `bool(pred)==True`, we know that `foo == True` in the "then" block.
    - Many issues are related to this (what are they?)
   
Work items:
- [x] add dominance frontier
- [ ] add phi-node insertion in `interpreter.py`

**Comment by guilhermeleobas** [comment]
Hi, I can work on this

**Comment by sklam** [comment]
@stuartarchibald, i remember you started looking at this.  Can you give us an update?

**Comment by guilhermeleobas** [comment]
@sklam, can you point me a direction on the source code? I saw that the dominator tree algorithm is implemented on `numba/controlflow.py`. I can start implementing the [dominance frontier algorithm](https://homepages.dcc.ufmg.br/~fernando/classes/dcc888/ementa/slides/StaticSingleAssignment.pdf) there.

**Comment by stuartarchibald** [comment]
@sklam IIRC I've got the dominance frontier and dominator tree and was working on the data flow equations for phi node insertion.

**Comment by guilhermeleobas** [comment]
Hi @stuartarchibald, the code for the dominance frontier is in the `master` branch? I could only find the code to compute the (post)Dominator Tree.

**Comment by stuartarchibald** [comment]
@guilhermeleobas its not, I just hacked it together locally in the simplest way (form up dominance tree and mask off each vertex in turn) so I could start working on where to put phi nodes. If you are familiar with these concepts and the algorithms involved please feel free to write an implementation, it would be interesting to compare notes/you may well get this finished ahead of me doing it! Thanks.

**Comment by guilhermeleobas** [comment]
Cool, I will start working on that as soon as I have some cycles to spare.

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/5351, closing.
