### ISSUE TITLE
numpy calls interfere with external code in nopython=True functions

### ISSUE THREAD

**Issue by cosama** [numba/numba#3906]
### System
* conda `python 3.7` with:
    * llvmlite 0.27.0-py37hd408876_0 --> 0.28.0-py37hd408876_0
    * numba 0.42.0-py37h962f231_0 --> 0.43.0-py37h962f231_0
* Tested on Fedora and Ubuntu 18.04

### Minimal example

```
import numba
import numpy as np


@numba.jit(nopython=False)
def cross_issue(a=None):
    if a is None:
        a = 1
    np.sum([1, 2, 3])
    return a


print(cross_issue())
```

### Expected result
* after the if statement a should be `1`, however the function returns `None`.
* The behavior doesn't show up if the call to `np.sum` is removed. The weird behavior is also present with other functions (I originally discovered it with `np.cross` and saw it with `np.mean` too). 
* I have honestly no idea how this even can be or how to debug it. Suggestions are welcome.

**Comment by cosama** [comment]
I forgot to mention, the above code works fine in numba `0.42.0` and `0.41.0`.

**Comment by stuartarchibald** [comment]
Thanks for the report. What you are seeing is most likely due to this bug: https://github.com/numba/numba/issues/3879 which was fixed here: https://github.com/numba/numba/pull/3883, the recently released Numba 0.43.1 fixes this problem, perhaps try updating your Numba installation:
```
conda install numba=0.43.1
```

**Comment by cosama** [comment]
Yeah `0.43.1` fixed this. Sorry didn't find the other issue. I will close this then.

**Comment by stuartarchibald** [comment]
@cosama great, thanks for confirming.
