### ISSUE TITLE
Deprecate object mode

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3907]
Historically "recent" (since early ~2014?!) Numba has had the `object mode` compilation path which will attempt to compile any python code into a compiled function. This compiled function treats all variables as Python objects and uses the Python C API to perform all operations on those objects. The performance of the compiled function is often no better, and can even be worse, than simply interpreting the original source in the CPython interpreter.

Object mode is accessed by either setting the `numba.jit` decorator kwarg `forceobj` to `True` or via a fall back mechanism where compilation of a `numba.jit` decorated function is first tried through `nopython` mode and if this fails object mode is used instead. The fall back can be confusing in that seemingly innocuous changes in user code lead to drastic performance changes as code which may have once compiled in `nopython` mode may switch to object mode silently. e.g.:

```python
from numba import jit

@jit
def foo():
    l = []
    for x in range(10):
        l.append(x)
    return l

foo()

assert foo.nopython_signatures

@jit
def bar():
    l = []
    for x in range(10):
        l.append(x)
    return reversed(l) # innocuous change, but no reversed support in nopython mode

bar()

assert not bar.nopython_signatures
```
Another reason to remove the fall back is that it is confusing for the compiler engineers as it causes internal state problems that are really hard to debug and makes manipulating the compiler pipelines incredibly challenging.

Object mode itself is not without merit, there are some minor but important uses in the case of a `with objmode:` context managed block which permits a section of a `nopython` mode function to run in `object mode`. It is therefore not appropriate to completely remove this mode and compilation pipeline.

Further, it has long been considered best practice that the `nopython` kwarg in the `numba.jit` decorator is set to `True` and that any user effort spent should go into making code work in this mode as there's very little gain if it does not. The result is that, as Numba has evolved, the amount of use object mode gets in practice and it's general utility has decreased. It can be noted that there are some minor improvements available through the notion of `loop-lifting`, whereby a loop that can be compiled to not use the Python C API inside an object mode function is "lifted" out into a `nopython` mode function. The cases of this being used in practice are, however, rare and often a legacy from less-recent Numba whereby such behaviour was better accommodated/the use of `@jit` was recommended.

Proposed changes:

1. `numba.jit` will compile code in `nopython` mode by default.
2. `numba.jit` will compile in object mode only if `forceobj=True` is set as a kwarg in the decorator.
3. The fall back behaviour is removed entirely.
4. Numba internals ends up with two distinct pipelines, one for `nopython` mode and one for object mode.

Summary of benefits:

1. Less confusion for (especially new) users, i.e. `numba.jit` either manages to compile in `nopython` mode and benefit is immediately felt, or the user is told there is a compilation problem, this prevents reports of "`numba.jit` did nothing for performance".
2. Encourages users to pursue `nopython` mode for better performance.
3. Makes it much harder for users to create accidental performance regressions.
4. Less confusion for developers debugging/manipulating a state heavy compilation pipeline.

Proposed method for implementing changes:

1. Issue a deprecation warning to users using the `numba.jit` decorator with the value of the  `nopython` kwarg set to `False` (the default value at the time of writing). This message should convey that the default for the `nopython` kwarg will at some time in the future become `True`. Once the default is updated, object mode will still work, but users will have to opt-in to using it. Write an entry in the documentation about why this change is being made, explain to users how to adjust their code differentiating between code which can be compiled in `nopython` mode and code which cannot. Also explain why in general object mode is not going to yield good performance and encourage users to remove the decorator/fix their code to work under `nopython=True`. Link to documentation from warning. Fix Numba testing code to silence this warning.

2. Deprecate the "nopython falls back to object mode" behaviour, a warning can be issued from the use of the fall back path in the pipeline that describes that a) it is happening and b) if the user wants objmode to use `forceobj=True` kwarg. Relevant documentation can be provided to link to from the warning message text. Fix Numba test base to silence this warning.

3. Set the `nopython` kwarg default to `True` and make it so that it becomes an error to set it to any other value, the reason for not removing the kwarg is its extensive use in the wild (due to having to constantly spell it out at present and recommending this as best practice). The error message can refer to documentation about why this is so and also mention `forceobj`.

4. Split the nopython and object mode pipelines so there's a pure variant of each pipeline with no interference between the two, this makes it easier to debug and implement pipeline changes. The default is now to always compile in `nopython` mode, users wanting object mode can opt in with `forceobj=True`. This internal change should be transparent to the user base as the "fall back" behaviour would have been removed earlier from the user API entry points by virtue of the decorator kwarg default changes.

It may be most profitable to perform steps 1 and 2 simultaneously so that there is a loud and clear warning for all users that are relying on object mode/object mode fall back that they will have to change their code at some point in the future. This change being to either:

1. use `forceobj=True`
2. only decorate functions that can be compiled in `nopython` mode.

**Comment by stuartarchibald** [comment]
I should add... edits/ideas/comments are most welcome!

**Comment by luk-f-a** [comment]
@stuartarchibald, with so many libraries implementing Numpy's API it is very common to write functions that work on many types of array-like objects, for example Numpy and Dask arrays. What would be the best way to decorate functions such that when receiving a Numpy array they are jitted but when receiving an array that Numba cannot handle they fallback on pure python? I am talking about parameter-type fallback, not line-by-line fallback as currently.
would it be possible to retain some opt-in fallback for when functions receive a type that they cannot handle? Or should users write `overload`s for their own functions, such that when the functions receives non-Numpy arrays they return a pure python function?

**Comment by stuartarchibald** [comment]
@luk-f-a please could you open a new issue about the above, and if possible please provide a couple of examples, thanks.

**Comment by godaygo** [comment]
Not sure where this comment fits better here or in #4159. I, too, rather consider current fallback behavior to an object mode as an error in my code than a useful feature. Therefore, I would vote for:

>3. The fall back behaviour is removed entirely.

On the other hand, my experience tells me that there is some (in many cases significant) difference in an idiomatic code that I write with `numba` in mind and without. In other words, if `numba.njit` does not work, then I’m not just deleting the decorator, but almost always completely rewriting the function in a different style. And this of course contradicts my first paragraph.

Of course at the moment it is only a superficial idea, but what if we have the ability to explicitly control the fallback behavior through new `fallback` kwarg? Like:

```python
@nb.njit(..., fallback=None)  # raise if it can't compile to nopython

@nb.njit(..., fallback=some_callable)  # call some_callable if it can't compile to nopython

@nb.njit(..., fallback=nb.object_mode)  # current behavior -> fallback to object mode
```

where `nb.object_mode` is some singleton. What do you think?

**Comment by stuartarchibald** [comment]
Thanks @godaygo I've added a note to #4159 to make sure this comment is considered.

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/4159#issuecomment-501000264

**Comment by stuartarchibald** [comment]
#8702 deprecates the fall-back to object mode behaviour.
