### ISSUE TITLE
Thread safety of typed.Dict could use clarification in docs

### ISSUE THREAD

**Issue by stuz5000** [numba/numba#3909]
A common use of Python's dict class is performing lockless memoization. 
We can (often) get away without using locks around dict's get and set operations because we can rely upon a atomicity of of these operations thanks to the GIL (and we often don't care about ordering and work duplication for memoization).

In these higher performance applications, you might think typed.Dict to be a shoe in upgrade. However, it's unclear if it shares the same atomicity (and type safety) properties of Python's native dict, particular for simple set/get. (I expect it does not - but a note in the docs would make it clear).

(In 0.43.0)

PS. typed.Dict is very wonderful. We have many uses for it.

**Comment by seibert** [comment]
The dictionary is definitely not thread-safe at this point, although we could introduce a per-dictionary lock to solve it in the simplest way.  If we always enable the locking, I suspect the dictionary will slow down, so the question here is whether to require thread-safe dictionary access to be opt-in.

For example, we could enable this kind of code for acquiring exclusive access to the dictionary to update it:
``` python
with d.lock():
    d['x'] = 1
```

**Comment by stuz5000** [comment]
Thank you. I don't think its good to try and add locking if it affects performance (otherwise, why numba?) 
Mostly it could use a comment in the docs, since people unfamiliar with the internals of your dict come with preconceptions about what's safe with Python's dict.

So, my next question is: if I fill the typed.Dict, and no longer perform state mutating operations, are the remaining read-only/non-state-mutating/pure-function operations (.get, .keys, .items, ....) safe for concurrency from that point on? Like this:

```
# Setup
d = state()  # create the dict, and populate the data. S is the typed.Dict

# thread 1
    read(d)   # .get/items/keys/values
# thread 2
    read(d)  # .get/items/keys/values
```

I _assume_ so, but I ask because I found pandas.Series violating this 'assume-this-operation-to-be-thread-safe-because-it-looks-like-a-pure-function-and-only-reads-the-data' principle, and can no longer use it. So, I'm looking at typed.Dict for this reason, the better performance and the ability to write other efficient functions (such as mapping an array directly to another array).

**Comment by seibert** [comment]
Yes, the getitem operation does not mutate the dictionary (so it should be safe to call from multiple threads), and in fact is implemented in a way that allows it to be inlined into the calling function for higher performance.

**Comment by stuz5000** [comment]
Super. Thanks!

**Comment by stuartarchibald** [comment]
Opened #3911 to track doc change needed. Thanks for the suggestion. Closing in favour of #3911.

**Comment by rteja1113** [comment]
Hi @stuz5000 , can you provide an example where you can get away with not using explicit locks on a dictionary's set method in a program that uses multiple threads ?

**Comment by stuz5000** [comment]
When using python’s builtin dict, set and get are atomic (because of
cpython’s GIL).
Generally it seems like bad practice though since operations such as .items
are not atomic.

**Comment by stuz5000** [comment]
PS. @rteja1113 I don't think you should reasonably expect similar thread safety with typed.Dict (or be able to use it as a drop in replacement for cpython's dict).
