### ISSUE TITLE
typed.Dict docs update RE threadsafety

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3911]
## Feature request

As per discussion https://github.com/numba/numba/issues/3909, clarify in docs that `typed.Dict` is not threadsafe, but prepopulated Dict getitem is compiled inlined so RO should be.

**Comment by rteja1113** [comment]
Hi @stuartarchibald , do you mind if I take a first stab at it ?

**Comment by stuartarchibald** [comment]
@rteja1113 not at all, thanks very much!

**Comment by stuartarchibald** [comment]
This is noted here: https://numba.readthedocs.io/en/stable/user/parallel.html#unsupported-operations, closing.
