### ISSUE TITLE
uncommon behaviors about float and int

### ISSUE THREAD

**Issue by uwmyuan** [numba/numba#3912]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

My env is win10, py3.6, cuda10, numba0.43. I'd like to create some random ints and pass them to float variables in some formulas. However, this may not work in the following code. Each part of code is tested seperately and `#not work` means the program ends with the error `Exception has occurred: OSError exception: access violation reading 0x0000000000000000`.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import numpy as np
from numba import cuda, int32, float32
from numba.cuda.random import create_xoroshiro128p_states, xoroshiro128p_uniform_float32

@cuda.jit
def run(r, Q, A):
    Q[0,0,0] = round(xoroshiro128p_uniform_float32(r, 1)) # not work
    Q[0,0,1] = xoroshiro128p_uniform_float32(r, 1) # work
    Q[0,0,2] = 1 # work

    a = cuda.local.array(shape=(2), dtype=float32)
    a[0] = round(xoroshiro128p_uniform_float32(r, 1))
    Q[1,0,0] = a[0] #not work

    Q[1,0,0] = a[0]  * 1.0 # not work  
 

    b = cuda.local.array(shape=(2), dtype=int32)
    b[0] = xoroshiro128p_uniform_float32(r, 1)
    Q[1,0,1] = b[0] # work

    A[0,0,0] = round(xoroshiro128p_uniform_float32(r, 1)) # work
    A[0,0,1] = xoroshiro128p_uniform_float32(r, 1) # work
    A[0,0,2] = 0.1 # work

Q = cuda.device_array(shape=(2, 2, 2), dtype=np.float32)
A = cuda.device_array(shape=(2, 2, 2), dtype=np.int32)
rng_states = create_xoroshiro128p_states(100, seed=1)
run[128, 128](rng_states, Q, A)
print(Q.copy_to_host())
```

**Comment by sklam** [comment]
Looks like it's due to: https://github.com/numba/numba/issues/2435

**Comment by esc** [comment]
#2435 was fixed in #4137 - maybe this will work now?

**Comment by esc** [comment]
I just tried this with the latest Numba master on Linux and the above program doesn't raise any exceptions. @uwmyuan can you check this on your end?

**Comment by uwmyuan** [comment]
@esc Thanks for letting me know. I just check and confirm the bug is fixed.

**Comment by esc** [comment]
@uwmyuan great, thanks for following up on this, we appreciate it!
