### ISSUE TITLE
Add Numba Python 2 timeline to Python3Statement

### ISSUE THREAD

**Issue by CAM-Gerlach** [numba/numba#3917]
Given Numba already has a concrete [timeline for dropping support for Python 2](https://numba.pydata.org/numba-doc/dev/reference/python27-eol.html) by the EoL, I suggest [adding](https://github.com/python3statement/python3statement.github.io) the dates to [Python3Statement](https://python3statement.org/), like most of the rest of the PyData stack have done, to make it easy for users to find in one central place and help accelerate Python 3 adoption.

**Comment by esc** [comment]
I made a pull-request here:

https://github.com/python3statement/python3statement.github.io/pull/188

I left the timeline information deliberately vague, simply stating:

```
    'Numba':[
        {content: 'Python 2 & 3', start: '2012-03-08', end: '2019-12-31', py2:true},
        {content: 'Python 3 only', start: '2020-01-01', end: '2023-12-31'},
    ],
```

I choose to do this, because the timeline at https://numba.pydata.org/numba-doc/dev/reference/python27-eol.html states:

```
December 2018: Tag and release Numba 1.x.0. Create a Python 2.7 branch based on this release.
```

And we don't have a Numba 1 release yet.. We can however be pretty certain that we won't continue to support Python 2 beyond 2020-01-01.

**Comment by stuartarchibald** [comment]
Thanks for submitting a PR @esc, we can discuss this further in the core developer meeting tomorrow.

**Comment by CAM-Gerlach** [comment]
@stuartarchibald @seibert @esc Hey, any updates on this? Thanks!

**Comment by stuartarchibald** [comment]
@CAM-Gerlach not as yet, when a decision has been made the PR https://github.com/python3statement/python3statement.github.io/pull/188 will be updated to reflect. Thanks.

**Comment by seibert** [comment]
We need to adjust our timeline here.  I wanted to get through some of our backward compatibility-breaking changes before the final Python 2.7 release of Numba, but those have taken longer than we imagined a year ago.  We'll have to address this next week when all of the core developers are available.

**Comment by sklam** [comment]
Python 2 is already removed from numba. Closing.
