### ISSUE TITLE
Numba support for JAX

### ISSUE THREAD

**Issue by ktattan** [numba/numba#3923]
Google has a great library, [JAX](https://github.com/google/jax), for automatic differentiation (AD). It seems JAX is undergoing heavy development and using its `grad` method is a lot easier than AD in other libraries (e.g. theano).

Given that a lot of algorithms (Deep Neural Nets, No-U-Turn Sampling etc.) rely on differentiation at their core, it would be great if numba could support JAX to achieve that incredible speed up already supported in numpy functions.

**Comment by seibert** [comment]
Given that JAX is also a JIT compiler, are there situations where it can compute the gradient, but you would not want to compile the resulting function with JAX itself?

**Comment by seibert** [comment]
Or are you looking for the reverse, where Numba has interop with JAX to use it to differentiate functions you are compiling with Numba?

**Comment by ktattan** [comment]
I suppose the former. But ultimately whichever implementation is most general and benefits the community the most would be best.

What I've noticed is that it is hard to compile functions with numba njit when there is differentiation using JAX involved. Even if the function is broken into many sub functions that can individually be compiled with njit, the "main" function (the outer loop, say) cannot be compiled (at least not in nopython mode), and therefore the code doesn't achieve great speed ups.

I hope this makes sense. It's hard to generalize my use cases to the wider community.

**Comment by seibert** [comment]
I haven't looked at the details of how JAX differentiation works, but I know we took a close look at [Tangent](https://github.com/google/tangent).  The code that generates is very close to being Numba supportable, if we added support for the particular stack data structure that Tangent uses in its generated code.  I suspect JAX has a similar issue.

**Comment by seibert** [comment]
Looking into JAX more, it seems that they delegate to [Autograd](https://github.com/hips/autograd/) for differentiation, so this request is more specifically a "Numba support for Autograd".  :)

**Comment by agoose77** [comment]
This doesn't really answer the question, but I wanted to try using customcall for numba functions, so here it is. As you can't use it to do grad, it's not really that useful, but there we are.
https://gist.github.com/agoose77/ba52400980b106e110b1f6342e1a8397

**Comment by bhack** [comment]
Check also the thread at https://llvm.discourse.group/t/numpy-scipy-op-set/768 (expecially last posts) /cc @sklam @DrTodd13
