### ISSUE TITLE
Incorrect infer a index variant into `float` type

### ISSUE THREAD

**Issue by ucasFL** [numba/numba#3925]
I have following code which can not work in nopython mode:
```python
from numba import njit
from numpy import *

@njit(nogil = True)
def test():
    i = 1
    b = uint64(100)
    a = zeros((100, ), dtype = uint8)

    while i :
        j = 0
        j +=1

        for j in range(b):
            print(a[j])

        i -= 1


if __name__ == '__main__':
    test()
```
The error message is obvious:
```
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(uint8, 1d, C), float64)
```
When reference array a, the index `j` is inferred into type float64.

If I replace j with uint64 variant `index`, it's work well:
```python
from numba import njit
from numpy import *

@njit(nogil = True)
def test():
    i = 1
    b = uint64(100)
    a = zeros((100, ), dtype = uint8)

    while i :
        j = 0
        j +=1

        for j in range(b):
            index = uint64(j)
            print(a[index])

        i -= 1


if __name__ == '__main__':
    test()
```
Also , if I delete the first two lines of while loop or rename index j, it's also work well:
```python
from numba import njit
from numpy import *

@njit(nogil = True)
def test():
    i = 1
    b = uint64(100)
    a = zeros((100, ), dtype = uint8)

    while i :

        for j in range(b):
            print(a[j])

        i -= 1


if __name__ == '__main__':
    test()
```
```python
from numba import njit
from numpy import *

@njit(nogil = True)
def test():
    i = 1
    b = uint64(100)
    a = zeros((100, ), dtype = uint8)

    while i :
        j = 0
        j += 1

        for k in range(b):
            print(a[k])

        i -= 1


if __name__ == '__main__':
    test()
```
And if b is not numpy.uint64 type, it's work well too:
```python
from numba import njit
from numpy import *

@njit(nogil = True)
def test():
    i = 1
    b = 100
    a = zeros((100, ), dtype = uint8)

    while i :
        j = 0
        j += 1

        for j in range(b):
            print(a[j])

        i -= 1


if __name__ == '__main__':
    test()
```
Maybe this is not a big trouble, but it makes me headache when writing code with numba.

**Comment by esc** [comment]
@ucasFL Thank you very much for reporting this bug!

This is a bug similar to:

https://github.com/numba/numba/issues/2194

Essentially, what is happening is that the assignment `j=0` initializes `j` to be of type `int64`. Then, the range loop sets `j` to be `uint64`. This is then coerced to `float64` which is why you see the error.

A suggestion might be to use  to set `j` up as a `uint64` in the first place like:
``` 
j = uint64(0)
```

Let us know if that solves your issue.

**Comment by ucasFL** [comment]
@esc It can solve my issue, I just think it's not user-friendly.

**Comment by esc** [comment]
@ucasFL we appreciate your feedback, unfortunately there isn't much we can do about it beyond tzhe workarounds you already listed.

**Comment by stuartarchibald** [comment]
@esc perhaps open an issue for investigating the removal of the unsigned range variant which would make stuff like this go away?

**Comment by esc** [comment]
@stuartarchibald perhaps.. I am wondering if this might be needed in some circumstances, for example where you want to iterate beyond the max value of a signed int?

**Comment by esc** [comment]
@stuartarchibald any more thoughts on this?
