### ISSUE TITLE
Include functools.wraps in wrapers.py  for projects using sphinx and numba decorators.  

### ISSUE THREAD

**Issue by pordyna** [numba/numba#3945]
## Feature request

If I use one of the numba decorators (e.g.) `njit` on a function and later use sphinx autodoc to generate documentation for my project, the signature of this function will be missing in the docs. According to [https://github.com/sphinx-doc/sphinx/issues/3783](url) the signature is correctly included if the decorator uses  `functools.wraps`. 

Would it be possible for you to include  `@wraps` in your decorators so that users could easily
use numba and sphinx together in their projects?

**Comment by esc** [comment]
@pordyna thank you for your feature request. I just had a quick look, and it would appear, that we already support this.

From the page: https://docs.python.org/3.7/library/functools.html - `wraps` just calls `update_wrapper` and `update_wrapper` is called in Numba in the `Dispatcher`:

https://github.com/numba/numba/blob/master/numba/dispatcher.py#L550

A good way to check if it is working is to check the dunder methods which `update_wrapper` sets, such as `__name__`, `__doc_`, `__wrapped__` etc..:

```pycon
In [1]: from numba import njit

In [2]:

In [2]: @njit
   ...: def foo():
   ...:     """ This is it """
   ...:     return 1
   ...:

In [3]: foo.__module__
Out[3]: '__main__'

In [4]: foo.__name__
Out[4]: 'foo'

In [5]: foo.__qualname__
Out[5]: 'foo'

In [6]: foo.__annotations__
Out[6]: {}

In [7]: foo.__doc__
Out[7]: ' This is it '

In [8]: foo.__wrapped__
Out[8]: <function __main__.foo()>

In [9]: foo.__wrapped__.__name__
Out[9]: 'foo'

In [10]: foo.__wrapped__.__doc__
Out[10]: ' This is it '
```

So anyway, I think it *should*  work fine. If you are having a specific issue with using Sphinx on your project that uses Numba, maybe you could send a link?

**Comment by pordyna** [comment]
Alright, thank you for the fast answer.  Then it's probably sth with my sphinx configuration, I'll look into it.

**Comment by esc** [comment]
@pordyna no problem. I will close this issue for now. Please feel free to open it again in case you don't find the snag.
