### ISSUE TITLE
weird behavior of Records.make_c_struct.

### ISSUE THREAD

**Issue by weinbe58** [numba/numba#3949]
OK so the idea I want to implement is make a `cfunc` and pass that function into some C++ code which calls the function pointer as shown in this python script. Here `test_callback` is some cython module which compiles a C function which calls the function pointer.
```
from test_callback import callback_C
from numba import cfunc,carray,types

wrapper = types.Record.make_c_struct([
   ('m', types.intc),
   ('n', types.complex128),
])

sig = types.void(types.CPointer(wrapper))

@cfunc(sig)
def C_caller(argptr):
	arg = carray(argptr,1)
	arg[0].m = 1
	arg[0].n = -1j
	return 

print wrapper
callback_C(C_caller)
```

note that the make_c_struct does not align the memory properly,
the result of `print wrapper` gives: `Record(m[type=int32;offset=0],n[type=complex128;offset=16];24;True)`
but the offset for `n` should be 4 bytes not 16. 
I can reverse the order and it works fine but in the current order will not work.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think what you are seeing is due to the following. The `intc` is:
```
size: 4
align: 4
misalign: 0
offset: 0
```
then the `complex128` ends up as:
```
size: 16
align: 8
misalign: 4
offset: 16
```
i.e. it would be a misaligned load if packed against the 4 byte alignment of the `intc` so gets padded to the 16 byte offset. I think it might be possible to adjust the offset computation to be the `offset += align - misalign`, but probably not the suggested 4 byte offset as it would be misaligned for the type. @sklam thoughts?

**Comment by weinbe58** [comment]
@stuartarchibald OK I think maybe I don't quite understand how the data is actually packed into the struct.

however the outstanding issue is that the code I wrote does not work with the integer first, if you want I Can provide the source code for the C++/cython code which fails when you change the order in the struct.

**Comment by sklam** [comment]
Looks like there's a bug in the alignment of `n`.

<details>

```python
from numba import cfunc,carray,types
from cffi import FFI
from pprint import pprint


wrapper = types.Record.make_c_struct([
    ('m', types.intc),
    ('n', types.complex128),
])

print(wrapper)


ffi = FFI()
ffi.cdef("""
struct complex128 { double real, imag; };
typedef struct _Rec{
    int m;
    struct complex128 n;
} Rec;
""")

c_rec_type = ffi.typeof('Rec')
pprint(dir(c_rec_type))
print(c_rec_type)
for k, fd in c_rec_type.fields:
    print(k, fd.offset, fd.type)
```
</details>

Prints:

```
Record(m[type=int32;offset=0],n[type=complex128;offset=16];24;True)
['cname', 'fields', 'kind']
<ctype 'Rec'>
m 0 <ctype 'int'>
n 8 <ctype 'struct complex128'>
```

`n` should have 8-byte offset but it's getting a 16-byte offset from `Record.make_c_struct`.

**Comment by sklam** [comment]
the `offset += align - misalign` suggestion seems to have fixed it.  i'll be opening a patch soon.

**Comment by sklam** [comment]
Oh, there's some trouble: 

````
In [9]: np.dtype([('m', np.intc), ('n', np.complex128)], align=True)
Out[9]: dtype({'names':['m','n'], 'formats':['<i4','<c16'], 'offsets':[0,16], 'itemsize':32}, align=True)
```
Numpy thinks `np.complex128` has 16-byte alignment but LLVM thinks it has 8-byte alignment.

**Comment by sklam** [comment]
According to https://github.com/numpy/numpy/issues/3768, the 16-byte alignment was due to sparc64.

**Comment by sklam** [comment]
so, this is fixed since numpy1.16.
