### ISSUE TITLE
Feature request, general purpose iteration by dimension over arrays

### ISSUE THREAD

**Issue by thomasaarholt** [numba/numba#3950]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

There is a bug turning extracting an array where the first axis has N entries, into N variables, please see the following minimal example:
```python
@jit(nopython=True)
def test():
    data = np.array([[1,2],[3,4]])
    a,b = data
    return a

>>> test()
---
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
iterating over 2D array

File "<ipython-input-48-ced6c9f6a280>", line 4:
def test():
    <source elided>
    data = np.array([[1,2],[3,4]])
    a,b = data
    ^

[1] During: lowering "$0.14 = exhaust_iter(value=data, count=2)" at <ipython-input-48-ced6c9f6a280> (4)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```

Meanwhile, in regular python:

```python
def test2():
    data = np.array([[1,2],[3,4]])
    a,b = data
    return a
>>> test2()
array([1, 2])
```

**Comment by esc** [comment]
I can reproduce this on current master (b5a7131d88d6960f27497c7bc199e7bbfa6eab3f)

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a known problem and due to lack of support for iterating over arrays with dimension > 1. Whilst not nice, this will work as no iterator is created:

```python
@njit
def test2():
    data = np.array([[1,2],[3,4]])
    a, b = data[0], data[1]
    return a

test2()
```

Feature request for support: https://github.com/numba/numba/issues/3111
Duplicate: https://github.com/numba/numba/issues/3300

**Comment by thomasaarholt** [comment]
Closing this due to duplicates.
