### ISSUE TITLE
Numba and google or-tools

### ISSUE THREAD

**Issue by abduakhatov** [numba/numba#3954]
Does numba works well with [or-tools](https://developers.google.com/optimization) ([git](https://github.com/google/or-tools)) by google? or-tools is written in C++, as numpy.
P.S. by "works well" I mean speed up

**Comment by stuartarchibald** [comment]
Thanks for the query. Simple answer is no, Numba works well with Python code that makes use of NumPy. It can interact with C/external libraries, but there's no direct performance benefit (Numba will just perform a function call to a function in the library).
