### ISSUE TITLE
Caching for function with objmode context-manager

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3955]
## Feature request
Looks like `cache=True` has no effect for functions that use `objmode` blocks. This would be quite useful for complex workloads that use `objmode`.

**Comment by sklam** [comment]
The reason the `objmode` block disables caching is the use of ``add_dynamic_addr`` at https://github.com/numba/numba/blob/700d38e4f5004d84966c260d5c9050d0fb637f5d/numba/core/lowering.py#L803-L807

There's a potential to use serialization to freeze `entry_pt` into the LLVM IR.

**Comment by sklam** [comment]
There's a usecase in SDC which is an overload for `pandas.read_csv` at https://github.com/IntelPython/sdc/blob/eb87e63d072b7fc6eea9964e23f5eb9ff0b97fab/sdc/io/csv_ext.py#L482-L488.
