### ISSUE TITLE
Remove deprecated use of inspect.getargspec 

### ISSUE THREAD

**Issue by sklam** [numba/numba#3960]
(From mailing list: https://groups.google.com/a/continuum.io/d/msgid/numba-users/83ccf8f9-fb9f-4d76-8229-0d89608fe816%40continuum.io?utm_medium=email&utm_source=footer)

On python 3.6.7, numba 0.43.1, MacOS, usage of dufunc is causing a DeprecationWarning:

```
/home/build/.local/share/virtualenvs/work-WgJkZa2_/lib/python3.6/site-packages/numba/npyufunc/dufunc.py:86
  /home/build/.local/share/virtualenvs/work-WgJkZa2_/lib/python3.6/site-packages/numba/npyufunc/dufunc.py:86: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    super(DUFunc, self).__init__(dispatcher, **kws)
  /home/build/.local/share/virtualenvs/work-WgJkZa2_/lib/python3.6/site-packages/numba/npyufunc/dufunc.py:86: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    super(DUFunc, self).__init__(dispatcher, **kws)
```

The warning is corresponding to the lines at https://github.com/numba/numba/blob/ca731bf94bc6b23cdc865470b9e98ef647c0b1c8/numba/npyufunc/_internal.c#L166-L174

**Comment by dhirschfeld** [comment]
It seems there are a couple more usages but I don't think they're the ones contributing to the warnings in our test suite
```
2019-04-11T04:14:07.1452476Z   C:\Miniconda3\envs\pricing\lib\site-packages\numba\npyufunc\dufunc.py:86: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
2019-04-11T04:14:07.1452563Z 
2019-04-11T04:14:07.1452648Z     super(DUFunc, self).__init__(dispatcher, **kws)
2019-04-11T04:14:07.1452711Z 
2019-04-11T04:14:07.1452783Z 
```

https://github.com/numba/numba/blob/b3afbb876a3a789e431554ef4d80ba2bcf982439/numba/npyufunc/ufuncbuilder.py#L243

https://github.com/numba/numba/blob/c5461dd295663559b55f7e59280df9317062887c/numba/tracing.py#L156

**Comment by esc** [comment]
@dhirschfeld is still relevant or has it been fixed with #3935 ?

**Comment by dhirschfeld** [comment]
That was a different warning. AFAIK this is still relevant. Haven't yet tested on the latest though...

**Comment by esc** [comment]
@dhirschfeld O.K. - I just had a quick look for a minimal reproducer but failed to find it. Did it miss it? May I kindly request that you point me in the right direction? Thanks!

**Comment by dhirschfeld** [comment]
Still seeing this in our CI with:
```
numba              pkgs/main/win-64::numba-0.43.1-py37hf9181ef_0
```
