### ISSUE TITLE
Wikipedia page on Numba

### ISSUE THREAD

**Issue by cdeil** [numba/numba#3977]
The Wikipedia page on Numba is spectacularly bad:
https://en.wikipedia.org/wiki/Numba

- The code examples that are given are incomplete (no imports, no working example for first-time users)
- Broken links, e.g. to http://numba.pydata.org/numba-doc/dev/hsa/overview.html
- The text / description isn't a good summary of Numba, basically copy & pasting from http://numba.pydata.org/ would improve the situation
- https://en.wikipedia.org/wiki/Python_(programming_language) mentions Numba once, under "major implementations" in the box on the top right, together with CPython, Jython, PyPy, ... which is incorrect
- One example of `sum1d` is given, with dubious performance claims.

---

Concerning Numba performance,  Wikipedia currently says this:

> This optimized function runs 200 times faster than the interpreted original function on a long NumPy array; and it is 30% faster than NumPy's builtin sum()function (version 0.27.0).[2][3]

referring to [2] https://www.ibm.com/developerworks/community/blogs/jfp/entry/A_Comparison_Of_C_Julia_Python_Numba_Cython_Scipy_and_BLAS_on_LU_Factorization?lang=en and [3] https://jakevdp.github.io/blog/2013/06/15/numba-vs-cython-take-2/

As far as I can see, those two blog posts don't contain a performance measurement for `sum1d` or make the claim that Numba is 30% faster than Numpy.

With latest Numba and Numpy (from Anaconda on macOS), I find that Numba is a factor of 2 slower than Numpy:
```
In [1]: import numpy as np                                                                                                                                          

In [2]: from numba import jit                                                                                                                                       

In [3]: @jit('f8(f8[:])') 
   ...: def sum1d(my_double_array): 
   ...:     total = 0.0 
   ...:     for i in range(my_double_array.shape[0]): 
   ...:         total += my_double_array[i] 
   ...:     return total 
   ...:                                                                                                                                                             

In [5]: a = np.arange(1.e7)                                                                                                                                         

In [6]: %timeit a.sum()                                                                                                                                             
4.36 ms ± 299 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit sum1d(a)                                                                                                                                            
8.75 ms ± 50.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

I see #3046 by @stuartarchibald , so it seems Numba will get faster soon.

Given that Numpy and Numba performance is highly version- and machine-dependent, I think the only sane solution can be to remove the performance comparison on the Wikipedia page completely, and to refer to http://numba.pydata.org/numba-doc/latest/user/performance-tips.html instead and summarise that Numba can give good performance in many cases.

---

What to do?

Is deleting the page and replacing links to it with links to http://numba.pydata.org/ which has a very good description already an option?

Or should the Wikipedia page be kept and improved?
In that case, a low-effort option could be to take the short text from the http://numba.pydata.org/ front-page as summary (if allowed), and removing the code examples and performance claim (instead linking to the docs and http://numba.pydata.org/numba-doc/latest/user/performance-tips.html), and editing the main Python page to mention Numba not as a "Python implementation" but somewhere else on that page would be good.

Does one of you from the Numba team have time to do the edits?
If no, please comment here what you think would be best, and I could give it a shot.

**Comment by stuartarchibald** [comment]
Thanks for raising this. Indeed the page is not particularly up-to-date or accurate and I am not sure who wrote it or maintained/updated it?! I'm also not sure what the policy on package authors maintaining pages on wikipedia is? @seibert any ideas?

**Comment by seibert** [comment]
Yeah, I think having Numba developers edit the wikipedia page would violate the spirit of [Wikipedia's conflict of interest guidelines](https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest), especially since we are paid to work on Numba.  If someone in the community would like to clean things up, we would definitely appreciate it.

**Comment by cdeil** [comment]
I've improved https://en.wikipedia.org/wiki/Numba a bit, addressing some of the issues mentioned above, the current version is this: https://en.wikipedia.org/w/index.php?title=Numba&oldid=892759091

It's certainly still not good, it should be extended and probably grow sections "Design" and "History" and "Features" like other good Wikipedia pages such as e.g. CPython or Cython. And more references should be added, like to the ACM proceedings (#3981) and public talks. And possibly more examples, e.g. one with Numpy and one showing how to use GPU.

Or, given that http://numba.pydata.org/ really has all information - the Wikipedia page could be simplified further, e.g. by removing the "GPU support" and "Alternative approaches" sections, since each just contains 1-2 sentences that could go in the section at the top.

**Comment by luk-f-a** [comment]
maybe this podcast transcription would be accepted as a source, at least for things like the history section: https://github.com/Quansight/Quansight.github.io/blob/master/_posts/2019-03-01-Episode-15-Numba.md

**Comment by esc** [comment]
@cdeil thanks a lot for looking into this.

**Comment by stuartarchibald** [comment]
Thanks to everyone who updated the wiki article.

Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by esc** [comment]
I just took a look at the Numba page on wikipedia and it seems like the release information is quitze outdated and the docs point to the "old" 'pyata' site, not readthedocs. (And FWIW the German variant isn't any better).
