### ISSUE TITLE
SSA for loop variables

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#3979]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have seen type unification error for loop variables in a couple of workloads, which SSA can fix. Example below:

```python
@numba.njit
def f(A,B):
    for i in A:
        print(i)
    for i in B:
        print(i)

f([1, 2],['A', 'B'])
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Can confirm this is an SSA related issue.
