### ISSUE TITLE
Open access for numba ACM proceedings?

### ISSUE THREAD

**Issue by cdeil** [numba/numba#3981]
Currently http://numba.pydata.org/numba-doc/latest/user/faq.html?highlight=acm#how-do-i-reference-cite-acknowledge-numba-in-other-work links to http://dl.acm.org/citation.cfm?id=2833162&dl=ACM&coll=DL 

That's behind a paywall - many researchers will not be able to access it, or not want to make an account there and pay for it. So this is non-ideal.

Could you please check if there is a way for you to post a copy of the PDF publicly, e.g. on http://numba.pydata.org or on a preprint server?

If it's forbidden by ACM, you could consider writing something new in the future in an open-access journal?

**Comment by seibert** [comment]
I've moved the Git repo for the paper to a public location here:

https://github.com/numba/Numba-SC15-Paper

Our draft PDF (effectively a preprint) is in the repo, which should have the same contents as the final ACM publication.

We'll update the docs to point people at that location in addition to the ACM link.  Thanks for bringing this up!

**Comment by esc** [comment]
https://github.com/numba/numba/pull/3990 <-- will be fixed by this.
