### ISSUE TITLE
Passing jit'ed cuda device function pointer to compiled cuda code.

### ISSUE THREAD

**Issue by sklam** [numba/numba#3983]
## Feature request

Bring similar functionality as `@cfunc` to GPUs.

**Comment by kkraus14** [comment]
@sklam and I talked offline briefly and he asked me to add to this issue. There's also the demand for getting the device pointer of a JITed kernel function to register it with another CUDA Context.

**Comment by uchytilc** [comment]
I thought I would make a quick post letting you know that there is interest in this feature. I am working on a package that lets users define there own functions that are then executed in a MAP style pattern or are passed to a more complex kernel where the user defined function augment what the kernel does. In order to make it work I need to recompile the kernel function for every device function the user creates a la the factory method mentioned here https://github.com/numba/numba/issues/4272. Having the ability to pass the device function to a C++ or numba kernel directly without recompiling would help a great deal.

**Comment by sklam** [comment]
Another user-request for this: https://gitter.im/numba/numba?at=5f0f15f79c75aa256b40da81

> What I am missing is how to get the c/c++ signature of the numba jitted function. It's a function with a signature (float32[:],float32[:]) - it gets and returns a numpy array in python. But, I want to call it from c++. When I try to c++filt the signature, I get something like "cudapy::test_numba::add$242(Array<float, 1, A, mutable, aligned>, Array<float, 1, A, mutable, aligned>)" how can I figure the memory layout of Array<>?

> The end goal is to integrate numba to pytorch torchscript with an extension module. I want to be able to write numba code, call it from pytorch code and then "script" everything to torchscript, while seamlessly compiling the numba code to ptx, and embed it inside the torchscript file. Then - load everything from c++ code and run without python interpreter using c++ libtorch and cuda driver api.

**Comment by dmadisetti** [comment]
is this possible 2 years later? Just checking

**Comment by gmarkall** [comment]
> is this possible 2 years later? Just checking

It isn't, but the modifications to support it are probably easier now than they were two years ago - the mechanism for doing this would probably involve adding a method to generate a [`CUDACodeLibrary`](https://github.com/numba/numba/blob/master/numba/cuda/codegen.py#L47) for a [`DeviceFunction`](https://github.com/numba/numba/blob/master/numba/cuda/compiler.py#L367), for which the `get_cufunc()` method would return a pointer to the device function.

**Comment by dmadisetti** [comment]
Wow, git blame says this is fresh. Thanks @gmarkall.
Hm, when will your changes be cut into prod?
`AttributeError: 'CUDACodeLibrary' object has no attribute 'get_cufunc'`

`assert numba.__version__ == '0.53.0'`

**Comment by gmarkall** [comment]
They'll be in in 0.54. You can build from source if you're interested in trying to make the necessary modifications though: https://numba.readthedocs.io/en/stable/developer/contributing.html#getting-set-up

**Comment by gmarkall** [comment]
It feels like we can almost do this, but I'm struggling with lookup up the pointer to the device function. I've tried a couple of different ways to do this:

1. Using the standard `get_cufunc()` route, which uses `cuModuleGetFunction()` internally.
2. Treating the device function as a global instead, and trying to look it up with `cuModuleGetGlobal()`.

Both of these fail to find the device function, and I'm not sure why. Perhaps:

- I'm not looking up the correct name
- I should be using some other method to look up the name
- The device function is getting discarded during linking / loading, and I should be changing the linking / loading behaviour somehow.

Code for my attempts so far:

```python
from ctypes import byref, c_size_t
from numba import cuda, int32
from numba.cuda.cudadrv import devices, drvapi
from numba.cuda.cudadrv.driver import driver


# Create a device function, compile it for a given set of args, and look up the
# compiled function name.

@cuda.jit(device=True)
def f(x):
    return x + 1


args = (int32,)
f.compile(args)

codelib = f._compileinfos[args].library
entry_name = codelib._module.functions[0].name


# Attempt 1: use get_cufunc(). Internally uses cuModuleGetFunction().

# Set the entry_name of the codelib to match the device function name so that
# it doesn't complain about that when we call get_cufunc() - this works around
# the codelib not expecting get_cufunc() to be called for a device function.
codelib._entry_name = entry_name

# Here we fail with:
#
#     CudaAPIError: [500] Call to cuModuleGetFunction results in
#                         CUDA_ERROR_NOT_FOUND
ptr = codelib.get_cufunc()


# Attempt 2: Attempt to get a pointer to a global with the same name as the
# device function

# Get the code for the function and load it to the device
ctx = devices.get_context()
cubin = codelib.get_cubin()
module = ctx.create_module_image(cubin)

# Return values for the pointer and size to the global
ptr = drvapi.cu_device_ptr(0)
size = c_size_t()

# Here we fail with:
#
#    CudaAPIError: [500] Call to cuModuleGetGlobal results in
#                        CUDA_ERROR_NOT_FOUND
driver.cuModuleGetGlobal(byref(ptr), byref(size), module.handle,
                         entry_name.encode())
```

**Comment by gmarkall** [comment]
Maybe useful for reference, the API log running the above:

```
$ NUMBA_CUDA_LOG_LEVEL=DEBUG NUMBA_CUDA_LOG_API_ARGS=1 python ctor.py 
== CUDA [317]  INFO -- init
== CUDA [317] DEBUG -- call driver api: cuInit(0)
== CUDA [323] DEBUG -- call driver api: cuCtxGetCurrent(<cparam 'P' (0x7faf9e692790)>)
== CUDA [323] DEBUG -- call driver api: cuDeviceGetCount(<cparam 'P' (0x7faf9e692790)>)
== CUDA [323] DEBUG -- call driver api: cuDeviceGet(<cparam 'P' (0x7faf9e692790)>, 0)
== CUDA [324] DEBUG -- call driver api: cuDeviceComputeCapability(<cparam 'P' (0x7faf9e692710)>, <cparam 'P' (0x7faf9e558e90)>, 0)
== CUDA [324] DEBUG -- call driver api: cuDeviceGetName(<numba.cuda.cudadrv.driver.c_char_Array_128 object at 0x7faf9e558ec0>, 128, 0)
== CUDA [324] DEBUG -- call driver api: cuDeviceGetUuid(<cparam 'P' (0x7faf9e558d10)>, 0)
== CUDA [324] DEBUG -- call driver api: cuDeviceGet(<cparam 'P' (0x7faf9e692710)>, 1)
== CUDA [324] DEBUG -- call driver api: cuDeviceComputeCapability(<cparam 'P' (0x7faf9e692790)>, <cparam 'P' (0x7faf9e558d90)>, 1)
== CUDA [324] DEBUG -- call driver api: cuDeviceGetName(<numba.cuda.cudadrv.driver.c_char_Array_128 object at 0x7faf9e558cc0>, 128, 1)
== CUDA [324] DEBUG -- call driver api: cuDeviceGetUuid(<cparam 'P' (0x7faf9e558e90)>, 1)
== CUDA [324] DEBUG -- call driver api: cuDevicePrimaryCtxRetain(<cparam 'P' (0x7faf9e692790)>, 0)
== CUDA [404] DEBUG -- call driver api: cuCtxPushCurrent_v2(c_void_p(94537907645936))
== CUDA [404] DEBUG -- call driver api: cuMemGetInfo_v2(<cparam 'P' (0x7faf9e692710)>, <cparam 'P' (0x7faf9e558e10)>)
== CUDA [405] DEBUG -- call runtime api: cudaRuntimeGetVersion
== CUDA [414] DEBUG -- call driver api: cuLinkCreate_v2(6, <numba.cuda.cudadrv.driver.c_int_Array_6 object at 0x7faf9e558c40>, <numba.cuda.cudadrv.driver.c_void_p_Array_6 object at 0x7faf9e558b40>, <cparam 'P' (0x7faf9e558b10)>)
== CUDA [415] DEBUG -- call driver api: cuLinkAddData_v2(c_void_p(94537912893024), 1, c_char_p(94537915007264), 707, c_char_p(140392251828272), 0, None, None)
== CUDA [415] DEBUG -- call driver api: cuLinkComplete(c_void_p(94537912893024), <cparam 'P' (0x7faf9e558e90)>, <cparam 'P' (0x7faf9e558d90)>)
== CUDA [415] DEBUG -- call driver api: cuLinkDestroy(c_void_p(94537912893024))
== CUDA [415] DEBUG -- call driver api: cuModuleLoadDataEx(<cparam 'P' (0x7faf9e558a90)>, b'\x7fELF\x02\x01\x013\x07\x00\x00\x00\x00\x00\x00\x00\x02\x00\xbe\x00q\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x05\x00\x00\x00\x00\x00\x00\x80\x03\x00\x00\x00\x00\x00\x00K\x05K\x00@\x008\x00\x03\x00@\x00\x07\x00\x01\x00\x00.shstrtab\x00.strtab\x00.symtab\x00.symtab_shndx\x00.nv.info\x00.text._ZN8__main__5f$241Ei\x00.debug_frame\x00.nv.info._ZN8__main__5f$241Ei\x00.rel.debug_frame\x00.nv.global\x00.nv.rel.action\x00\x00.shstrtab\x00.strtab\x00.symtab\x00.symtab_shndx\x00.nv.info\x00_ZN8__main__5f$241Ei\x00.text._ZN8__main__5f$241Ei\x00_ZN08NumbaEnv8__main__5f$241Ei\x00.debug_frame\x00.nv.info._ZN8__main__5f$241Ei\x00#ili\x00.rel.debug_frame\x00.nv.global\x00.nv.rel.action\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x81\x00\x00\x00\x03\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc2\x00\x00\x00\x03\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcd\x00\x00\x00\x03\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00b\x00\x00\x00\x11\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff0\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x03\x00\x04|\x94\x80\x80(\x0c\x81\x80\x80(\x00\x08\xff\x81\x80(\x08\x81\x80\x80(\x08\x94\x80\x80(\x08\x95\x80\x80(\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff(\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x04\x00\x00\x00\x0c\x81\x80\x80(\x00\x04\x14\x00\x00\x00K\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x08\x10\n/"\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x08\x08\x00\x00\x00\x00\x00\x00\x10\x08\x00\x00\x00\x00\x00\x00\x18\x08\x00\x00\x00\x00\x00\x00 \x08\x00\x00\x00\x00\x00\x00(\x08\x00\x00\x00\x00\x00\x000\x08\x00\x00\x00\x00\x00\x008\x08\x00\x00\x00\x00\x01\x00\x00\x08\x00\x00\x00\x00\x01\x00\x08\x08\x00\x00\x00\x00\x01\x00\x10\x08\x00\x00\x00\x00\x01\x00\x18\x08\x00\x00\x00\x00\x01\x00 \x08\x00\x00\x00\x00\x01\x00(\x08\x00\x00\x00\x00\x01\x000\x08\x00\x00\x00\x00\x01\x008\x08\x00\x00\x00\x00\x02\x00\x00\x08\x00\x00\x00\x00\x02\x00\x08\x08\x00\x00\x00\x00\x02\x00\x10\x08\x00\x00\x00\x00\x02\x00\x18\x08\x00\x00\x00\x00\x02\x00 \x08\x00\x00\x00\x00\x02\x00(\x08\x00\x00\x00\x00\x02\x000\x08\x00\x00\x00\x00\x02\x008\x08\x00\x00\x00\x00\x00\x00\x00\x14,\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe3\x00\x00\x00\x00\x00\x00\x00\xdc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x13\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc0\x01\x00\x00\x00\x00\x00\x00x\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00M\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x008\x02\x00\x00\x00\x00\x00\x00p\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x94\x00\x00\x00\x0b\x00\x00p\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa8\x02\x00\x00\x00\x00\x00\x00\xd8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x89\x00\x00\x00\x08\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x03\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x05\x00\x00\x00@\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00\x80\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00', 5, <numba.cuda.cudadrv.driver.c_int_Array_5 object at 0x7faf9e558b40>, <numba.cuda.cudadrv.driver.c_void_p_Array_5 object at 0x7faf9e558d40>)
== CUDA [416] DEBUG -- call driver api: cuModuleGetFunction(<cparam 'P' (0x7faf9e692710)>, c_void_p(94537916008880), b'_ZN8__main__5f$241Ei')
== CUDA [416] ERROR -- Call to cuModuleGetFunction results in CUDA_ERROR_NOT_FOUND
Traceback (most recent call last):
  File "ctor.py", line 33, in <module>
    ptr = codelib.get_cufunc()
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 169, in get_cufunc
    cufunc = module.get_function(self._entry_name)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2023, in get_function
    driver.cuModuleGetFunction(byref(handle), self.handle,
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 299, in verbose_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 345, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [500] Call to cuModuleGetFunction results in CUDA_ERROR_NOT_FOUND
== CUDA [416]  INFO -- add pending dealloc: module_unload ? bytes
```

**Comment by gmarkall** [comment]
I'm starting to come to the conclusion that you can't just get a device function pointer and pass it to another compiled kernel - nothing I see suggests it's supported. It looks like the closest you can come to this is to get PTX for a device function and link that with a `__global__` kernel that has the `__device__` function declared extern at runtime using `cuLinkCreate`, `cuLinkAddData`, etc.. @dmadisetti Can you explain your potential use case so we can see if there's a way to support it?

**Comment by dmikushin** [comment]
[Here](https://gist.github.com/dmikushin/7871337859128b111333a2025a7df5a5) I've put together a simple CUDA/PTX code example. There, a GPU kernel calls a device function via a jump-table, which ends up begin an arithmetic goto in machine assembly code. I thought jumptable would be the most "enforcing" way for a device function to reveal its address. Alas, this address appears to be just an internal offset, not the actual address in the GPU memory. It's remarkable that the jumptable global variable itself is accessed via a real pointer:

```
$ cuda-gdb ./jumptable 
NVIDIA (R) CUDA Debugger
11.1 release
(cuda-gdb) set cuda break_on_launch application 
(cuda-gdb) r
[Switching focus to CUDA kernel 0, grid 1, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 0, lane 0]
0x0000555555b9c1c8 in kernel<<<(1,1,1),(1,1,1)>>> ()
(cuda-gdb) set cuda disassemble_from device_memory 
(cuda-gdb) disass
Dump of assembler code for function kernel:
   0x0000555555b9c1c0 <+0>:	 
=> 0x0000555555b9c1c8 <+8>:	MOV R1, c[0x0][0x20] 
   0x0000555555b9c1d0 <+16>:	MOV32I R18, 0xce400000  // !!!
   0x0000555555b9c1d8 <+24>:	MOV32I R19, 0x7fff // !!!
```

So, when it's needed, the runtime linker or relocator is able to substitute the real GPU memory address into the code. This also happens to a device function, when it is referenced (and device-linked) from the CUDA program like this:

```
__device__ int (*)(int) = &foo;
```

The procedure of revealing the device function address is unclear to me in this case. I'm only certain that it's not a part of __cudaRegisterVar mechanics. I think the "trigger" is written into the special section of CUBIN ELF.

**Comment by dmikushin** [comment]
We need to place a device function pointer into a device variable in the PTX code, which is simple. Then the hard part would be to add a CUBIN ELF entry for this variable into a `.rel.nv.global.init` section. I think this will trigger resolving the device function pointer to a real (that is, _relocatable_) address.

**Comment by dmadisetti** [comment]
@gmarkall I feared as much. I do think that I could write an External Memory management (EMM) plug in conjunction with this and get it working. Maybe?

My use case is to pass down a numba callback to pybind11 and invoke it in a kernel. Obviously convenience over speed here. I haven't seriously gone down this route, and it was more on an idea at this point

**Comment by gmarkall** [comment]
> We need to place a device function pointer into a device variable in the PTX code, which is simple. Then the hard part would be to add a CUBIN ELF entry for this variable into a `.rel.nv.global.init` section. I think this will trigger resolving the device function pointer to a real (that is, _relocatable_) address.

Whilst there might be a way to get this implemented, I think the level of hackery required here makes me uncomfortable about implementing it as something that's considered supported in Numba - for example, I'm not sure that using that address outside the module it's defined in would be guaranteed to work.

**Comment by gmarkall** [comment]
> @gmarkall I feared as much. I do think that I could write an External Memory management (EMM) plug in conjunction with this and get it working. Maybe?

EMM plugins only allow you to manage your own memory for device arrays, not for code, so I don't think they would help here.

> My use case is to pass down a numba callback to pybind11 and invoke it in a kernel. Obviously convenience over speed here. I haven't seriously gone down this route, and it was more on an idea at this point.

Can you use [`compile_ptx`](https://numba.readthedocs.io/en/stable/cuda-reference/host.html#numba.cuda.compile_ptx) and JIT link the PTX to your kernel instead?

If you can't do that - cuDF uses [JITify](https://github.com/NVIDIA/jitify) to inline PTX from Numba into kernels instead: see e.g. [Combined Python/CUDA JIT for Flexible Acceleration in RAPIDS](https://developer.nvidia.com/gtc/2020/video/s21393-vid).

> edit: I did consider passing down the byte code representation or the get_llvm_code, and compiling it C side- but like I said this is all very tentative

I think it would be easier to work with the PTX than with LLVM IR - if you used LLVM IR you'd need to roll your own way of feeding it to NVVM anyway (or use some more unusual mechanism for compiling it).

**Comment by uchytilc** [comment]
Just to through my two cents in here, I've gotten something basically described by @gmarkall working for a bit now. As he said modules don't expose device functions which makes the entire process very complicated. The jump table method works but all device functions need to exist within the same module so it would required some way of knowing which functions you could pass in so that they are included within the module. I did this mixing C with Numba where the kernel functions are in C and the user defines their own custom Numba device function. I grab the LLVM from the device function pass it through NVVM to get the PTX and then link the kernel PTX and the device function PTX in the Linker to generate a module (you also need to rename the numba device function entry point to match what it is on the C side). You can also skip the NVVM step like gmarkall said and simply use the output PTX from the device function (you still need to demangle the name). The draw backs are that it requires recompilation each time you want to use a different function (although you can cash the PTX which can make recompilations a little faster) and the device function cannot be inlined into the kernel making it somewhat slower. If I'm not mistaken I think that CuDF also does some super fancy stuff to get the generated PTX actually directly inlined into the Kernel that calls it but you would need to double check me on that.

**Comment by uchytilc** [comment]
Oh that's awesome, I'll have to watch the talk. I remembered reading a numba github Issue a while ago that linked to a cuDF issue that discussed this but it was some time ago and couldn't remember the details.

**Comment by shaunc** [comment]
I'm not sure if this is useful to anyone tracking this, but if you know what what the bindings are supposed to be in python, you may be able to avoid the need for a function pointer in the compiled code, instead rebinding in python before compilation. You can use something like:

```py
import types
import functools
from typing import Any, Mapping, Optional


def copy_func(
    f: types.FunctionType, new_globals: Optional[Mapping[str, Any]] = None
) -> types.FunctionType:
    """
    Copy a python function, optionally substituting for globals.

    Based on http://stackoverflow.com/a/6528148/190597 (Glenn Maynard)
    """
    globals = f.__globals__
    if new_globals is not None:
        globals = globals.copy()
        globals.update(new_globals)

    g = types.FunctionType(
        f.__code__,
        globals,
        name=f.__name__,
        argdefs=f.__defaults__,
        closure=f.__closure__,
    )
    g = functools.update_wrapper(g, f)
    g.__kwdefaults__ = f.__kwdefaults__  # type: ignore
    return g  # type: ignore
```
on a function that you want to compile to copy using new globals - so in particular function calls can be substituted to bind to different functions. Then you can explicitly wrap it in the jit dispatcher.

**Comment by gmarkall** [comment]
Having done some research recently whilst looking into implementing allocation on-device (e.g. for rapidsai/cudf#13181 etc.), I've discovered that there isn't a supported way to do this even in CUDA C/C++ (there are cases where it can appear to work, but those cases are where one gets lucky with register and local memory allocations, etc.), so I'm going to close this so as to avoid the illusion that progress might be possible under current constraints.
