### ISSUE TITLE
Improve SIMD Vectorization docs

### ISSUE THREAD

**Issue by cdeil** [numba/numba#3984]
The "Learn more" link for SIMD Vectorisation on the http://numba.pydata.org/ front-page doesn't point anywhere, it has an empty href which in my browser makes it jump to the top of http://numba.pydata.org/ itself, which is confusing.

https://github.com/numba/numba-webpage/blob/bcbfa8a825944b47b9687eae42eb35d2bf1b68b7/index.html#L176

Searching for SIMD in the docs http://numba.pydata.org/numba-doc/latest/search.html?q=simd&check_keywords=yes&area=default only points to http://numba.pydata.org/numba-doc/latest/user/faq.html?highlight=simd#does-numba-vectorize-array-computations-simd which isn't very useful.

Maybe a short section on SIMD could be added to the docs?

It could just be a sentence or two and link to https://github.com/numba/numba-examples/blob/master/notebooks/simd.ipynb .

Then the frontpage, FAQ entry and also http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml would have a place they can link to and it would be much easier for people like me that are discovering Numba to find the information.

**Comment by stuartarchibald** [comment]
Thanks for the report. 

> The "Learn more" link for SIMD Vectorisation on the http://numba.pydata.org/ front-page doesn't point anywhere, it has an empty href which in my browser makes it jump to the top of http://numba.pydata.org/ itself, which is confusing.

This is clearly a mistake and your suggestion about having a small section on auto-vectorization seems good, thanks.

**Comment by cdeil** [comment]
PR to fix this issue: https://github.com/numba/numba-webpage/pull/9

(IMO that's good enough - suggest to close this issue, unless you want to keep it open and write more docs for SIMD)
