### ISSUE TITLE
dict library can't import

### ISSUE THREAD

**Issue by richardxing** [numba/numba#3986]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi there,

I encounter this import problem when trying to run the example shown in the reference
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#dict
```
from ex_typed_dict_from_cpython of examples/dict_usage.py
```
```
  File "C:\Users\username\AppData\Local\Continuum\Anaconda3-5.2.0\lib\site-packages\numba\typed\typeddict.py", line 6, in <module>
    from numba.types import DictType, TypeRef

ImportError: cannot import name 'DictType'
```

Can you fix this bug or provide correct code for how to use dict in nopython mode? Thank you very much and looking forward to hearing from you.

Best regards,
Richard

**Comment by stuartarchibald** [comment]
NOTE: Updated report markdown.

**Comment by stuartarchibald** [comment]
@richardxing Thanks for the report. Please could you confirm that you are using version 0.43.x of Numba (dictionaries were not supported on releases prior to this).
From a Python3 prompt:
```
import numba; print(numba.__version__)
```
should be sufficient. Thanks.

**Comment by richardxing** [comment]
@stuartarchibald thank you for your reply. I did use 0.43.1 but I guess there was something wrong with the installation. I reinstalled and it works now. Sorry for the confusion.
