### ISSUE TITLE
numba -s doesn't work

### ISSUE THREAD

**Issue by richardxing** [numba/numba#3987]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi there,
 numba -s doesn't work in command line. Can you update how to get system info? Thanks!
Regards
Richard

**Comment by stuartarchibald** [comment]
NOTE: updated comment for markdown syntax.

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you answer the following?

1. How Numba was installed?
2. Which version of Numba was installed?
3. Which OS you are running on which platform?
4. Does `python -c "import numba; print(numba.__version__)"` work?

Thanks.

**Comment by richardxing** [comment]
@stuartarchibald 
Numba is installed via pip
0.43.1. 
OS is windows10 64. 
python -c "import numba; print(numba.__version__)" returns 0.43.1. 
Thanks!

**Comment by stuartarchibald** [comment]
Thanks @richardxing, seems like this ought to be ok. What does:
> numba -s doesn't work in command line.

actually mean? Does it do nothing, do something unexpected, hang, crash?

**Comment by richardxing** [comment]
https://numba.pydata.org/numba-doc/dev/user/installing.html
shows one can use numba -s to see information about your system capabilities

I run it in command line and it shows:
'numba' is not recognized as an internal or external command,
operable program or batch file.

**Comment by stuartarchibald** [comment]
ok, thanks, seems like there's a problem with the installation on your machine perhaps? I cannot replicate using either windows or linux and the following:
```
conda create -n issue3987 python=3 llvmlite numpy
conda activate issue3987
pip install numba
numba -s
```

**Comment by richardxing** [comment]
@stuartarchibald okay, I see. I will try it on another computer. Thanks!

**Comment by stuartarchibald** [comment]
Great, thanks. If you can find some way of reproducing it I'd be happy to take a look.

**Comment by esc** [comment]
Can you perhaps try to execute `numba` using it's full path? You should be able to find it in the `bin` directory of your Python implementation.

**Comment by cdeil** [comment]
@richardxing - This might help you figure out which Numba you're using and what your system info is:
```
python -c 'import numba; print(numba)'
python -c 'from numba.numba_entry import get_sys_info; get_sys_info()'
```

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
