### ISSUE TITLE
Is there any way to write a "good" cuda reduce function?

### ISSUE THREAD

**Issue by luckyyus** [numba/numba#3988]
Since cuda.reduce is not cached by jit, I tried to write a reduce function manually.

```python
    @njit

    def reduce_sum_float64(arr):

      n = arr.shape[0]

        while n > TpB:

            blocks = utility.power_of_two((n + TpB * 2 - 1) // (TpB * 2))

            __reduce_gpu_float64[blocks, TpB](arr, n)

            n = blocks

        return np.sum(arr[0:n].copy_to_host())

```

where __reduce_gpu_float64 is a kernel function with decorator cuda.jit.
Then I  #got:

numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name '__reduce_gpu_float64': cannot determine Numba type of <class 'numba.cuda.compiler.AutoJitCUDAKernel'>

Does that mean a jit function cannot call a kernel function in numba?

**Comment by stuartarchibald** [comment]
NOTE: updated markdown for readability.

**Comment by stuartarchibald** [comment]
Thanks for the report. At present it is not possible to launch a CUDA kernel directly from `nopython` mode, this is to what the error you are seeing is referring. Could you please explain a bit more about what it is you are trying to do? Thanks.

**Comment by luckyyus** [comment]
I already solve it by using cupy. thank you

**Comment by stuartarchibald** [comment]
Great, thanks for reporting back, I'm glad `CuPy` was a good fit for your use case.

**Comment by arainboldt** [comment]
I'm getting this error using the code from the docs below:

https://numba.pydata.org/numba-doc/dev/cuda/reduction.html

```
@cuda.reduce
def sum_reduce(a, b):
    return a + b


sum_reduce = cuda.reduce(lambda a, b: a + b)


@cuda.jit("void(float{}[:, :], float{}[:, :], float{}[:, :])".format(bits, bits, bits))
def cuda_manhattan(matA, matB, out):
    assert matA.shape == matB.shape
    m = matA.shape[0]
    n = matB.shape[1]
    i, j = cuda.grid(2)
    d = 0
    if i < m and j < m:
        for k in range(n):
            tmp = matA[i, k] - matB[j, k]
            d += sum_reduce(tmp)
        out[i, j] = d
```
```

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'sum_reduce': cannot determine Numba type of <class 'numba.cuda.kernels.reduction.Reduce'>

File "<ipython-input-10-1d680ab43b6b>", line 37:
def cuda_manhattan(matA, matB, out):
    <source elided>
            tmp = matA[i, k] - matB[j, k]
            d += sum_reduce(tmp)
            ^
```

**Comment by gmarkall** [comment]
@arainboldt Reduction kernels are intended to be called from host code, rather than device code.

If you have further issues, it's best to start a post on the Numba Discourse: https://numba.discourse.group/ rather than starting new discussions in old, closed issues.
