### ISSUE TITLE
Numba division zero error with numpy linalg functions

### ISSUE THREAD

**Issue by celinew1221** [numba/numba#3992]
```
@jit(nopython=True, error_model='numpy')
def is_inv(matrix):
    cond_threshold = 1 / np.finfo(np.float64).eps
    cond = np.linalg.cond(matrix)
    return cond < cond_threshold
```
I want to check if a matrix is singular or not because I can't try and catch the singular error in numba. However, np.linalg.cond is now giving my division by zero error. I used error_model='numpy', but it still gives me a python semantic error.

The fixed I have is to go into targets/linalg.py, and change line s[0] / s[-1] to np.divide in cond_imple.

**Comment by stuartarchibald** [comment]
Thanks for the report. Full reproducer:
```python
import numpy as np
from numba import njit

def is_inv(matrix):
    cond_threshold = 1 / np.finfo(np.float64).eps
    cond = np.linalg.cond(matrix)
    return cond < cond_threshold

x = np.arange(12.).reshape((4, 3))
x [-2:,:] = 0.

is_inv(x)

try:
    njit(is_inv)(x)
except ZeroDivisionError as e:
    print(e)

try:
    njit(error_model='numpy')(is_inv)(x)
except ZeroDivisionError as e:
    print(e)
```
suggested fix seems appropriate, would you be interested in contributing a patch for this and corresponding tests? Thanks.
