### ISSUE TITLE
Subclass primitive types as jitclass

### ISSUE THREAD

**Issue by louisabraham** [numba/numba#4004]
# Feature request

In some applications, one uses a primitive type to represent data.

It would be great to be able to subclass this type to indicate it is used in a certain manner and to factor the code.

Example: right now I'm trying to code a SAT solver in numba (for fun and experimentation, not performance). It produces code like that:

```python
Var = numba.int32
Lit = numba.int32


@njit(Lit(Var))
def lit_new(var):
    return var


@njit(Lit(Lit))
def lit_neg(lit):
    return -lit


@njit(numba.boolean(Lit))
def lit_sign(lit):
    return lit < 0


@njit(Var(Lit))
def lit_var(lit):
    return abs(lit)


@njit(numba.uint32(Lit))
def lit_index(lit):
    if lit_sign(lit):
        return 2 * (lit_var(lit) - 1)
    else:
        return 2 * lit_var(lit) - 1
```

**Comment by stuartarchibald** [comment]
Thanks for the query, does this documentation about extending Numba help numba.pydata.org/numba-doc/dev/extending/interval-example.html ?

**Comment by louisabraham** [comment]
Thank you for the answer.
I have read most of the documentation.
My query would more look like inheritance for jitclass from primitive data types.
The code I wrote does what I want. The only problem is that I would have to drop some performance (I guess) by using a jitclass with only one attribute. In the example I'm using jit methods on a primitive data type (which in return produces code that is less readable).

But I'm not sure this is even a desirable feature for most users.

Globally, I find it hard to define custom compiled data types in numba (without reflection), as compared to directly writing C++ or Cython (sorry about this little rant).
I think there is already a feature request about that, but type inference in the constructor based on the spec would be great too! (eg for lists)

**Comment by sklam** [comment]
Are you trying to achieve something like pattern-matching?
Do you want to overload methods on the subclass?

**Comment by louisabraham** [comment]
I'm not sure about what you mean with pattern matching.
I don't need to overload methods on the subclass.
I would like to access all the methods of the parent class (here an int) and add other methods.
Currently there are two alternatives : using functions like I did in the example (but there is no benefit from the type system and the code quality is low without objects) or creating a new jitclass with just one attribute and "binding" all the methods.

I would really like the ability to inherit jitclasses, from native types or even other jitclasses. Other types that are supported like namedtuples would be great. 
The ability to override methods would be an advantage too.
