### ISSUE TITLE
Regression for structured arrays with titles

### ISSUE THREAD

**Issue by JelleAalbers** [numba/numba#4005]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Since v0.43, numba has problems with structured arrays with titles. Example:
```python
import numba
import numpy as np

x = np.zeros(2, dtype=[
    (("title a", 'a'), np.float),
    ('b', np.float)])

@numba.jit
def f(x):
    return x

print("Before: ", x.dtype)
print("After:  ", f(x).dtype)
```

In numba 0.42 this gives the expected:
```
Before:  [(('title a', 'a'), '<f8'), ('b', '<f8')]
After:   [(('title a', 'a'), '<f8'), ('b', '<f8')]
```

But in 0.43 and the latest master, it gives:
```
Before:  [(('title a', 'a'), '<f8'), ('b', '<f8')]
After:   {'names':['a','title a','b'], 'formats':['<f8','<f8','<f8'], 'offsets':[0,0,8], 'itemsize':16}
```
The title is gone from field a, and instead a new field has been added to the array. This new field has the same offset, so the array now has overlapping fields. This will crash things like compressors that view the array as a memory buffer, with an error like:
```
ValueError: dtypes with overlapping or out-of-order fields are not representable as buffers. Consider reordering the fields.
```

I'm guessing this new behaviour was introduced with the Record refactor in #3661?

I attempted a naive fix by replacing the iteration over `dtype.fields` here: https://github.com/numba/numba/blob/e9518295f1c5461137d62c9735d525896f2c37fb/numba/numpy_support.py#L420 with 
```python
    for name in dtype.names:
        info = dtype.fields[name]
```
which removes the extra fields. Unfortunately, this would break accessing a field by its title, and doesn't resolve the fact that titles of fields are gone after passing through numba.

**Comment by stuartarchibald** [comment]
Thanks for the report. Indeed this was altered in #3661. Ping @sklam.
