### ISSUE TITLE
Missing linecache import in parfor.py

### ISSUE THREAD

**Issue by cdeil** [numba/numba#4013]
There's a missing `import linecache` in `parfor.py`, that will lead to a `NameError` here:

https://github.com/numba/numba/blob/a35920c275916297500743bfa4fb7af232bd9659/numba/parfor.py#L1214

Not sure how to add a test for this, so didn't send a PR.

**Comment by stuartarchibald** [comment]
Thanks for the report, this is clearly an omission. The code is part of the allocation hoisting diagnostics, I'm not sure if it's the diagnostics that are not running or, perhaps more likely, that the input to them/what is accepted for hoisting has changed. I'll take a look.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/4024 Fixes both the import problem, and that allocation hoisting got broken and now tests for both!

**Comment by cdeil** [comment]
Fixed in #4024
