### ISSUE TITLE
Doesn't produce the correct results  in nopython mode.

### ISSUE THREAD

**Issue by ucasFL** [numba/numba#4016]
In Python, when the tuple's element is a list, the element can be changed, such as:
```python
def test(a):
    a[0].append(2)
    print(a)

m = ([0],)
test(m)
```
However, in nopython mode, it doesn't work.
```python
from numba import njit
@njit(nogil=True)
def test(a):
    a[0].append(2)
    print(a)

m = ([0],)
test(m)
```
`m` has no change after run test function.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is evidently a bug and I imagine is to do with container-containing-reflected-object, list-of-list reflection (i.e .`m=[[0],]) is already caught by the compiler as something that cannot be handled.

**Comment by stuartarchibald** [comment]
Numba 0.45 (release upcoming) `typed.List` implementation works correctly in this situation, would suggest using that as reflected lists are being deprecated, thanks.
```python
from numba import njit
from numba.typed import List

@njit(nogil=True)
def test(a):
    a[0].append(2)
    print(a)

l = List()
l.append(0)
m = (l,)
test(m)
```
Closing.
