### ISSUE TITLE
Make type.Optional string representation more friendly

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4025]
## Feature request

For e.g.  `types.Optional(types.float64)` the current `str()` is `?float64` which is fine, but it may be more helpful for users to produce something like:
 `OptionalType(float64) i.e. type 'float64 or None'`
such that an error message might read e.g.:
```
Dict.value_type cannot be of type OptionalType(float64) i.e. type 'float64 or None'
```
instead of:
```
Dict.value_type cannot be of type ?float64
```

**Comment by guilhermeleobas** [comment]
Hi @stuartarchibald, I will work on this issue. 

Regards

**Comment by stuartarchibald** [comment]
@guilhermeleobas great, thanks very much!
