### ISSUE TITLE
Wrong dtype of array inside reflected list

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#4028]
When trying to overload a numpy function that expects a list or tuple of boolean arrays there's a funny asymmetric behaviour going on. It looks like a bug, although maybe it's intended to be like this. When trying to query the dtype of the array, in one case it is `reflected list(array(int64, 1d, C))` and in the other one is `int64`. I think the second case should be the right answer in both cases.

```python
from numba import njit
from numba.extending import overload

@overload(np.select)
def np_select(arg):
    print('arg type', type(arg), '\narg[0] type', type(arg[0]), '\narg[0].dtype', arg[0].dtype)

@nb.njit
def test(arg):
    return np.select(arg)

test([np.arange(3)])
```
out when passing a list:
```python
arg type <class 'numba.types.containers.List'> 
arg[0] type <class 'numba.types.npytypes.Array'> 
arg[0].dtype reflected list(array(int64, 1d, C))
```
When passing a tuple
```
test((np.arange(3),))
```
out:
```python
arg type <class 'numba.types.containers.UniTuple'> 
arg[0] type <class 'numba.types.npytypes.Array'> 
arg[0].dtype int64
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is a bug in the type system class hierarchy. The `types.List` class should override the abstract `Type` class `__getitem__` to return a `self.dtype`.

**Comment by luk-f-a** [comment]
@stuartarchibald, thanks for looking into it. I need it working to address #1313, so if you think it's easy I might have a go at it.

**Comment by stuartarchibald** [comment]
@luk-f-a great, thanks. I think it's just a question of doing literally the above, perhaps give it a try as it's only a couple of lines and see if that fixes it? Relevant file is `numba/types/containers.py` and the `List` class. I'm not sure if there'd be any unexpected side-effects :) !
