### ISSUE TITLE
readthedocs build failure: cannot cache function: no locator available for file 

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#4032]
My project uses numba 0.43.1 (from conda-forge) and has functions decorated with ``@numba.jit('<signature>', nopython=True, nogil=True, cache=True)``.
Everything works fine locally, on Travis, and AppVeyor.
readthedocs fails as soon as it tries importing the modules, with the following log:
```
WARNING: autodoc: failed to import module 'copula' from module 'pyscenarios'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 232, in import_module
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/pyscenarios-0.2.0-py3.7.egg/pyscenarios/copula.py", line 12, in <module>
    from .sobol import sobol
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/pyscenarios-0.2.0-py3.7.egg/pyscenarios/sobol.py", line 67, in <module>
    def _calc_v_kernel(directions: np.ndarray) -> np.ndarray:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/numba/decorators.py", line 191, in wrapper
    disp.enable_caching()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/numba/dispatcher.py", line 566, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '_calc_v_kernel': no locator available for file '/home/docs/checkouts/readthedocs.org/user_builds/pyscenarios/conda/v0.2.0/lib/python3.7/site-packages/pyscenarios-0.2.0-py3.7.egg/pyscenarios/sobol.py'
```

I've worked around the problem with the following hack:
```
def jit(sig: str):
    def decorator(func):
        try:
            return numba.jit(sig, nopython=True, nogil=True, cache=True)(func)
        except RuntimeError:
            # Work around issues with permissions on readthedocs
            return numba.jit(sig, nopython=True, nogil=True, cache=False)(func)
    return decorator
```

**Comment by seibert** [comment]
This error is very strange, as it suggests that the cache cannot write to any of the standard locations on readthedocs.  Assuming that `/tmp` is writeable, you could try setting the environment variable `NUMBA_CACHE_DIR` to `/tmp`.

If that works, let us know and we can put that suggestion into the Numba FAQ.

**Comment by crusaderky** [comment]
I rebuilt today, without setting any env variables, and the error disappeared.
Looks like the readthedocs engineers noticed it too and fixed it.

**Comment by SumNeuron** [comment]
Just encountered this in a docker container

RuntimeError: cannot cache function 'my_func': no locator available for file '/usr/local/lib/python3.6/dist-packages/lrng/numba/conversions.py

**Comment by esc** [comment]
@SumNeuron maybe you can set `NUMBA_CACHE_DIR` to `$HOME` or a subdirectory therof?

**Comment by SumNeuron** [comment]
I will try and get back to you, thank you for the suggestion

**Comment by esc** [comment]
@SumNeuron potentially, yes.

**Comment by SumNeuron** [comment]
@esc tried it, now i get
```
RuntimeError: cannot cache function 'my_func': no locator available for file
```

I suggest a fallback so that way numba doesn't break in docker

**Comment by esc** [comment]
@SumNeuron if you would like us to look into this some more, perhaps open a new issue, list the code you have (or something that illustrates your issue) your dockerfile and any commands that need to be used to reproduce the issue? Thanks!

**Comment by SumNeuron** [comment]
docker file is essentially

```dockerfile
FROM tensorflow/tensorflow:1.15.0rc2-gpu-py3-jupyter
COPY requirements.txt .
RUN pip install requirements.txt
```

then 

```python
from somemodule import jitted_numba_fn
```
where `docker run -u $(id -u):$(id -g) ...` causes the issue and without `-u $(id -u):$(id -g)` (run as root) does not.

**Comment by esc** [comment]
@SumNeuron thanks, setting `NUMBA_CACHE_DIR` to a writable location should have worked. How did you run the container to inject the environment variable?

**Comment by SumNeuron** [comment]
docker file is essentially

```dockerfile
FROM tensorflow/tensorflow:1.15.0rc2-gpu-py3-jupyter
COPY requirements.txt .
RUN pip install requirements.txt
```

then 

```python
from somemodule import jitted_numba_fn
```
where `docker run -u $(id -u):$(id -g) ...` causes the issue and without `-u $(id -u):$(id -g)` (run as root) does not.

**Comment by esc** [comment]
@SumNeuron thank you for responding back. I am sorry, but there seems to have been a misunderstanding. I was wondering how you managed to inject the `NUMBA_CACHE_DIR` environment variable into the docker container? Thanks!

**Comment by SumNeuron** [comment]
I have docker compose build and spin up the dockerfile with the env vars being read in from an env file

**Comment by esc** [comment]
O.K. I am thinking that maybe `$HOME` is evaluated outside of the Docker context and perhaps such a user and home directory doesn't exist inside the docker container. Could you try to setup a `chmod 777` directory in the Dockerfile and then point `NUMBA_CACHE_DIR` at that?

**Comment by 99991** [comment]
I had a similar issue. My package's code would run fine when run directly out of the directory, but after `python setup.py install --user`, it would fail to import with the error message ```RuntimeError: cannot cache function 'foo': no locator available for file '/home/username/.local/lib/python3.6/site-packages/mypackage-1.0.0-py3.6.egg/mypackage/mymodule.py```

`export NUMBA_CACHE_DIR=/tmp` and `os.environ["NUMBA_CACHE_DIR"] = "/tmp"` did no help.

However, removing a `__pycache__`-directory fixed the issue. Arguably, this directory should not have been there anyway, but I thought I should mention it in case others are having the same problem.

**Comment by bjarthur** [comment]
@SumNeuron thanks for the workaround.  i found though that NUMBA_CACHE_DIR was not persisted to the container because it was in a RUN command.  so i put it in an ENV and it worked beautifully.  also found that i did not have to actualy create the numba_cache directory either.  so for me i ended up simply with:

```
ENV NUMBA_CACHE_DIR=/tmp/numba_cache
```

**Comment by cdiaz45** [comment]
@bjarthur Thank you for this! This fixed my issue as well.

**Comment by souravjamwal77** [comment]
Hi All, I'm facing this issue on version 0.56.3 (for a lambda image), Can you please suggest something? I already tried the solutions given above.

**Comment by esc** [comment]
@souravjamwal77 thank you for adding to this. I can not suggest anything immediately without knowing more about this issue you are facing. I don't think there are many people that have tried to run Numba in a AWS Lamba function (I am assuming this is what you mean?) Can you please open a new issue stating:

* What you are trying to accomplish
* What you are expecting
* What happens instead

Thank you!

**Comment by erikreed** [comment]
This was a helpful thread for fixing with GCP functions, which just like AWS Lambda, has a read-only filesystem except for /tmp. The suggested fix of setting `NUMBA_CACHE_DIR` env variable to `/tmp` did the trick.
