### ISSUE TITLE
Formalise optional dependencies

### ISSUE THREAD

**Issue by esc** [numba/numba#4046]
It would be useful to formalise all optional dependencies, such as `pyyaml`, in a single place. This would make it easier to create conda environments that support all of Numba's bells and whistles.

**Comment by stuartarchibald** [comment]
Should also note optional compile-time dependencies for users building Numba from source.

**Comment by esc** [comment]
@stuartarchibald yes, good point.

**Comment by esc** [comment]
O.K. I will start by listing all the places that dependencies are mentioned:

* The following lists the basic dependencies, and mentions that threading dependencies can be installed.
* http://numba.pydata.org/numba-doc/latest/developer/contributing.html#build-environment
* llvmlite numpy scipy jinja2 cffi
* tbb lvm-openmp intel-openmp.

* The following mentions `pyyaml` only.
* http://numba.pydata.org/numba-doc/latest/reference/envvars.html
* pyyaml

* The following mentions a bunch of optional dependencies, including pyyaml:
* http://numba.pydata.org/numba-doc/latest/user/5minguide.html#how-do-i-get-it
* scipy colorama pyyaml icc_rt

* The following script lists a few more 'optional' dependencies:
* https://github.com/numba/numba/blob/master/buildscripts/incremental/setup_conda_environment.sh#L64
* cffi scipy jinja2 ipython pygments
* The script also lists all the dependencies needed for documentation:
* sphinx pygments sphinx-bootstrap

* The conda recipe also has an extensive list of dependencies:
* https://github.com/numba/numba/blob/master/buildscripts/condarecipe.local/meta.yaml#L20

**Comment by stuartarchibald** [comment]
I think this covers most of it:

Required build time
 * `setuptools`
 * `numpy`
 * `llvmlite`
 * `funcsigs` (Python 2)
 * `singledispatch` (Python 2)

Optional build time:
 * `llvm-openmp` (OSX) - provides headers for compiling OpenMP support into Numba's threading backend
 * `intel-openmp` (OSX) - provides OpenMP library support for Numba's threading backend.
 * `tbb-devel` - provides TBB headers/libraries for compiling TBB support into Numba's threading backend

Required run time:
 * `numpy`
 * `llvmlite`
 * `funcsigs` (Python 2)
 * `singledispatch` (Python 2)

Optional runtime are:
 * `scipy` - provides cython bindings for used in Numba's `np.linalg.*` support
 * `tbb` - provides the TBB runtime libraries used by Numba's TBB threading backend
 * `jinja2` - for "pretty" type annotation output (HTML) via the `numba` CLI
 * `cffi` - permits use of CFFI bindings in Numba compiled functions
 * `intel-openmp` - (OSX) provides OpenMP library support for Numba's OpenMP threading backend
 * `ipython` - if in use, caching will use IPython's cache directories/caching still works
 * `pyyaml` - permits the use of a `.numba_config.yaml` file for storing per project configuration options
 * `colorama` - makes error message highlighting work
 * `icc_rt` - (numba channel) allows Numba to use Intel SVML for extra performance
 * `pygments` - for "pretty" type annotation

To build the documentation:
 * `sphinx`
 * `pygments`
 * `sphinx-bootstrap`

**Comment by esc** [comment]
Great! Thanks! Is there anything in the categories: "required for testing" or "optional for testing"?

**Comment by stuartarchibald** [comment]
np.
>  Is there anything in the categories: "required for testing" or "optional for testing"?

same as runtime

**Comment by esc** [comment]
O.K. I think this is simple enough. Any ideas as to where in the documentation we should add this?

**Comment by seibert** [comment]
I think it should go on the installation page:

http://numba.pydata.org/numba-doc/latest/user/installing.html

Between "Installing from Source" and "Checking your installation"

**Comment by esc** [comment]
Implemented in https://github.com/numba/numba/pull/4607

**Comment by esc** [comment]
#4607 was merged fixing this. Closing.
