### ISSUE TITLE
cudnn interface and raw kernel

### ISSUE THREAD

**Issue by uwmyuan** [numba/numba#4050]
## Feature request

I'd like to call the `cudnn` library from `cuda.jit` kernel functions defined in CUDA-python. Could you add some features like defining raw CUDA kernel or a `cudnn` interface like `cupy.rawkernel` and `cupy.cudnn`? A sample code might be as follows.

Option 1: We may call `cudnn` library in raw cuda-c code.
```
from numba import cuda

@cuda.raw
def raw_fun():
    #some code in CUDA-C
    return r'''//code in cuda-c'''

@cuda.jit
def kernel_fun():
    #some code here
    raw_fun()
```

Option 2: call `cudnn` from `numba.cuda.cudnn` interface.

```
from numba.cuda import cudnn 
import numpy as np

x = np.array([1.0, 2.0, 3.0])
mode = cudnn.CUDNN_ACTIVATION_RELU
expected = cudnn.activation_forward(x, mode)
cuda.synchronize()
```

**Comment by esc** [comment]
@uwmyuan hi, and thanks for asking this question and your interest in Numba. We will need to take a closer look at this. One additional question to clarify: the reason you suggest to make a raw kernel is so that you can access cudnn from within it. It sounds like you have tried using the raw kernels from CuPy to access cudnn and you maybe have a working example of such a kernel?

**Comment by uwmyuan** [comment]
@esc hi, sorry for replying late. After a close look at cudnn, I found the high-level interface of cudnn can be accessed from the host/cpu program, but not from the kernel. Thus, the raw kernel might be another option in addition to the cuda.jit compiler.
In Option 2, I'm not sure whether the numba developers could access low-level interface of cudnn to make it work in a kernel function.

**Comment by gmarkall** [comment]
I don't think Numba will ever add a cuDNN interface - the [CUDA Array Interface (CAI)](https://numba.readthedocs.io/en/latest/cuda/cuda_array_interface.html) provides for libraries to operate on each others' data, so instead I'd recommend using a wrapper around cuDNN (perhaps https://github.com/hannes-brt/cudnn-python-wrappers) and using the CAI to get access to data pointers when necessary (or ideally, add support for CAI to the cuDNN wrapper).

I'm closing this issue as there's no likely forward direction here.
