### ISSUE TITLE
Misleading in numba.cuda.const.array_like

### ISSUE THREAD

**Issue by luckyyus** [numba/numba#4057]
In CUDA, constant memory can only be written from host and be read on device. 
The life time of an array in constant memory can be that of the whole program instead of just in one global function.

But in numba.cuda.jit, we can only allocate a constant memory in a CUDA kernel at compile time. that means every time the kernel is jit-compiled, the constant memory will be reset. Also, different kernels (global functions) cannot share the same constant memory so that the constant array have to be defined at each kernel.

Is there anyway to define a constant array which is "constant" to all kernels?

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the enquiry. I think that the `__constant__` memory space specifier is used to declare a variable that (amongst other things) resides in the constant memory space and has the lifetime of the context in which it was created.

Numba currently permits the compilation of kernels and use of the CUDA runtime API. I think for constant memory as there's no runtime API binding for creating such memory it cannot be part of the Numba CUDA context and I'm not sure how the seemingly necessary "program at once" specification of constant memory would work in Numba's CUDA programming model.

Ping @sklam any ideas?

**Comment by seibert** [comment]
As the cache architecture of CUDA hardware has evolved, I'm not sure whether or not there is a performance benefit to using constant memory anymore.  I'd be curious to know if this is something Numba needs to continue supporting.  Unfortunately, NVIDIA's documentation is somewhat hazy on the topic.  Shared memory and L1 cache are now physically the same starting with Volta, and the texture cache and L1 cache were unified in Pascal hardware.  I can't find anything in the tuning guides after Kepler on constant cache behavior.

That said, if the constant cache continues to be useful, we will need to think about how to make a global constant array.

**Comment by gmarkall** [comment]
Closing as the original question appears to have been answered.

**Comment by MarioVillar** [comment]
Hello.

Have there been any updates on the use allocation of constant data in numba? As I have inferred from the docs, numba.cuda.const.array_like has to be called within a device kernel, rather than in the host. Checking NVIDIA's docs I would say that it would be useful to replicate the behaviour where constant memory is allocated from the host and then available to be accessed in device kernels.

Kind regards
