### ISSUE TITLE
Mention TBB on install page

### ISSUE THREAD

**Issue by cdeil** [numba/numba#4068]
I suggest to add a mention of `conda install tbb` at http://numba.pydata.org/numba-doc/latest/user/installing.html

This is currently only mentioned at http://numba.pydata.org/numba-doc/latest/user/threading-layer.html

I find it very confusing to know if I have a "good" (i.e. high-performance) Numba installation or a "bad" one (i.e. not as performant as my CPU allows and as I can get with conda install).

As far as I can tell, the way to check is to run `numba -s`, so I think having a better description of it as in #4066 will help a little bit.

I just tried `conda install tbb`, and that worked. But then it seems there's something wrong - it's not avaibable!? And the OpenMP that was available before executing `conda install tbb` (I think) also isn't available any more!?
```
__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True
```
See full log at https://gist.github.com/cdeil/04c6abb8f8bee182fca3d5f9f683db53

So probably aside from a mention of `conda install tbb` on the install page, it could be useful to make the output more complete, i.e. give a way to check why I get `TBB Threading layer available                 : False` ?

**Comment by cdeil** [comment]
`conda install tbb` does work for me in a new environment:
https://gist.github.com/cdeil/1bfb3eec64c4c795e54588bdb20bc9fd

Probably the issue I saw was because I was in a Numba development environment.

But the suggestions are still there:
- Mention `conda install tbb` on the Numba install page
- Improve the output in the case of a "broken" or misconfigured TBB install to show some information what's wrong (or mention in the docs how to find out), i.e. this isn't very helpful:
```
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
```

**Comment by esc** [comment]
related #4046

**Comment by stuartarchibald** [comment]
Thanks for the query. `TBB` is an optional dependency for Numba and Numba's declared dependency tree is deliberately small so it can be easily used as a core library without bringing extra requirements. #4046 is tracking docs to mention all the optional dependencies.

> I find it very confusing to know if I have a "good" (i.e. high-performance) Numba installation or a "bad" one (i.e. not as performant as my CPU allows and as I can get with conda install).

There are some workloads where TBB will do better, some where OpenMP will do better and quite possibly some where the built-in "workqueue" threading backend will do better. The emphasis on what to install for a backend is based on the concurrent execution paradigm required, the docs here describe that: http://numba.pydata.org/numba-doc/latest/user/threading-layer.html. What the performance is like for a specific application will require measurement.

> I just tried conda install tbb, and that worked. But then it seems there's something wrong - it's not avaibable!? And the OpenMP that was available before executing conda install tbb (I think) also isn't available any more!?

TBB is a library, Numba's `tbbpool` threading backend (also a library with functionality wrapped as a C extension) has linkage specified against the TBB library. The `numba -s` command will try and import the threading backends in turn e.g. `from numba.npyufunc import tbbpool`, if this fails it means there's something wrong but the scope of what could be wrong is huge. There is a bit of debug output in `numba -s` if you hit common linker problems on linux, what does  `from numba.npyufunc import tbbpool` show for you?

**Comment by cdeil** [comment]
I get this in the `numbadev` env:
```
>>> from numba.npyufunc import tbbpool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'tbbpool' from 'numba.npyufunc' (/Users/deil/work/code/numba/numba/npyufunc/__init__.py)
```

The build command just says "TBB not found"
```
$ python setup.py build_ext -i
TBB not found
OpenMP not found
```
even though I have
```
(numbaenv) hfm-1804a:numba deil$ conda list | grep tbb
tbb                       2019.4               h04f5b5a_0  
```

Does TBB only work with the Intel compiler or do I have to build it myself if I build `numba` myself?

See https://gist.github.com/cdeil/be3ef4dad42781a9cb43b89ad13457fb for details.

---

http://numba.pydata.org/numba-doc/latest/user/threading-layer.html is great documentation.
I'm just suggesting to mention `conda install tbb` on the install page and link to the threading page for details.

I would suggest the same for 
http://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml
The install page should mention `conda install -c numba icc_rt` and link to that page with details on what it is.

And then the page describing `numba -s` could be extended to describe how to check what is installed / available. My understanding is that the way to check is by looking at the `SVML operational` line in it's output: https://github.com/numba/numba/pull/4066/files#diff-94f9bfb78b77793dfa97997fe9583066R119

**Comment by stuartarchibald** [comment]
@cdeil ok, I think I understand what has happened and what you are doing now. I didn't realise that you were trying this from a source build. To build in support for TBB in Numba, at compile time for the Numba package the TBB header files must be present, these are in the conda package `tbb-devel`. If you install that and recompile the Numba package itself, it should generate a C extension called `tbbpool` that resides in `numba.npyufunc`, if you also have the `tbb` package installed, when you try and import this extension, it should work fine. Essentially `tbb` is a runtime optional-dependency, `tbb-devel` is a package compile time optional-dependency, the former needs the latter to have been present at package compile time to work at all.

I don't think that this is documented, and certainly not as a requirement for compilation, largely because it is not a requirement as nothing breaks in Numba unless you explicitly say you want to use TBB at runtime. I think documenting optional build dependencies and the couple of suggested updates above linking across to the other pages can also be added to #4046.

**Comment by cdeil** [comment]
@stuartarchibald - Thanks for the infos.

Yes, if I `conda install tbb-devel` and rebuild, then `import numba.npyufunc.tbbpool` works.
The place to mention `tbb-devel` is here: http://numba.pydata.org/numba-doc/latest/developer/contributing.html?highlight=tbb#build-environment

**Comment by stuartarchibald** [comment]
TBB is now noted as an optional build time dependency here: https://numba.readthedocs.io/en/stable/user/installing.html#dependency-list

Closing as resolved.
