### ISSUE TITLE
Python-3.8.0a4 wheel support ?

### ISSUE THREAD

**Issue by stonebig** [numba/numba#4071]
Would it be possible to have a  test wheel for numba on pypi for Python-3.8.0a4 (or b1) Windows 64 bit ?

(it's for datashader use, currently miss the Qt & Numba ecosystems on 3.8)

**Comment by seibert** [comment]
We will take a look, though I'm not sure if we'll have it working in time for the 0.44 release in a few weeks.  I believe we can publish test wheels to Anaconda.org as well as conda packages.

**Comment by stonebig** [comment]
well, I have now a more basic problem of python-3.8 change in asyncio not playing nice with Tornado, so it's no more urgent.

**Comment by stonebig** [comment]
hum. PEP570 adds a new parameter in Types interface "co_posonlyargcount", it may not be a quick patch.

**Comment by stonebig** [comment]
Python-3.8.0b2 support ?

**Comment by seibert** [comment]
It is still on our todo list, but not the highest priority yet since 3.8 final doesn't come out until October.  We're likely to work on 3.8 testing and support (which due to bytecode changes might not be totally trivial) in the July/August timeframe.

**Comment by stonebig** [comment]
I see Christoph Gohlke has succeeded to do a 1rst wheel https://www.lfd.uci.edu/~gohlke/pythonlibs/#numba

**Comment by sklam** [comment]
python3.8 is now supported. closing.
