### ISSUE TITLE
parfors array_analysis (possibly) bug

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4075]
## Reporting a bug

- [x] I am using the ~latest released~ mainline version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import prange, njit
import numpy as np

def foo(n):
    a = np.ones(10)
    c = a[1:]
    s = len(c)
    return s

for d in [njit, njit(parallel=True)]:
    print(d(foo)(10))
```
prints
```
9
10
```
which is unfortunate.

**Comment by stuartarchibald** [comment]
ping @DrTodd13

**Comment by DrTodd13** [comment]
@stuartarchibald There's a bug in the slice handling code.  That code was getting the type of the size of a (which was Literal(Int)(10)) and then applying that to be the type of the size of c as well.  I have a fix that resolves this issue but it is currently breaking parfor slice tests 1-5.  So, I need to do some more debugging there.

**Comment by stuartarchibald** [comment]
@DrTodd13 thanks for looking into this, much appreciated.
