### ISSUE TITLE
typing error numpy.shape "not supported" 

### ISSUE THREAD

**Issue by dinosg** [numba/numba#4080]
```
using spyder 3.3.4, python 3.7.0 in anaconda environment 1.9.7 on OS X 10.14.4 (mojave)
get this:
TypingError: Use of unsupported NumPy function 'numpy.shape' or unsupported use of the function.
File "testcode.py", line 23:
def ggp_timestep(g, Pfr):
    <source elided>
    sg=np.shape(g)       #this is line 23 in testcode.py
    thearr = np.random.rand(sg[0], sg[1])
```

Come on guys, it says over and over in the reference manual that shape is a supported numpy function.

**Comment by dinosg** [comment]
File "testcode.py", line 23:
def ggp_timestep(g, Pfr):
    <source elided>
    sg=np.shape(g)
    thearr = np.random.rand(sg[0], sg[1])
    ^

[1] During: typing of get attribute at /Users/dpg/jobs/ameresco/new heather project/testcode.py (23)

File "testcode.py", line 23:
def ggp_timestep(g, Pfr):
    <source elided>
    sg=np.shape(g)   #this is line 23 in testcode.py
    thearr = np.random.rand(sg[0], sg[1])

**Comment by stuartarchibald** [comment]
NOTE. Edited original markdown as it was pasted into the commented out instruction section.

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
Thanks for the report. I don't believe it says in the documentation that the NumPy module function `shape` (i.e. `np.shape`) is supported, if it does please could you point to where, this is probably an error. The `numpy.ndarray.shape` attribute is supported, this is functionally equivalent but not the same as the use of the module level function. i.e.:
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return x.shape

@njit
def bar(x):
    return np.shape(x)

print(foo(np.arange(12).reshape(3, 4))) # returns (3, 4)
print(bar(np.arange(12).reshape(3, 4))) # error, not supported
```
