### ISSUE TITLE
TypeError in warnings machinery

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#4083]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I see the error below on master which I believe is due to the introduction of deprecated warnings. `WarningsFixer` tries to sort warnings [here](https://github.com/numba/numba/blob/master/numba/errors.py#L425), but Numba warnings don't have comparison implemented. This happens only if previous attributes of the warning data structure happen to be the same. I haven't been able to create a small reproducer for this yet.

```
../numba/numba/compiler.py:1017: in compile_ir
    lifted_from=lifted_from)
../numba/numba/compiler.py:385: in compile_ir
    return self._compile_ir()
../numba/numba/compiler.py:893: in _compile_ir
    return self._compile_core()
../numba/numba/compiler.py:873: in _compile_core
    res = pm.run(self.status)
../numba/numba/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
../numba/numba/compiler.py:254: in run
    raise patched_exception
../numba/numba/compiler.py:245: in run
    stage()
../numba/numba/compiler.py:501: in stage_nopython_frontend
    self.locals)
../numba/numba/compiler.py:1109: in type_inference_stage
    warnings.flush()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <numba.errors.WarningsFixer object at 0x7f368b3c2cf8>

    def flush(self):
        """
        Emit all stored warnings.
        """
>       for (filename, lineno, category), messages in sorted(self._warnings.items()):
E       TypeError: Failed in bodo mode pipeline (step: convert to distributed)
E       Failed in nopython mode pipeline (step: nopython frontend)
E       '<' not supported between instances of 'type' and 'type'

../numba/numba/errors.py:425: TypeError
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I've a feeling that this may always have been a problem but was not ever encountered because warnings were off by default.

**Comment by stuartarchibald** [comment]
This reproduces:
```python
from numba import errors
import warnings

wfix = errors.WarningsFixer(errors.NumbaWarning)
with wfix.catch_warnings('foo', 10):
    warnings.warn(errors.NumbaWarning(''))
    warnings.warn(errors.NumbaPerformanceWarning(''))

wfix.flush()
```
two warnings of different category are caught, but their contents is identical. How this is arising in practice I'm not sure!?

**Comment by ehsantn** [comment]
The way I got this was through a complicated exec/compile/transform/compile path...

**Comment by stuartarchibald** [comment]
If you can look with `pdb` as to the contents of those warnings when flush fails it'd be useful to where they are coming from, thanks.

**Comment by ehsantn** [comment]
Below is the warning contents by printing `self._warnings`.
```python
defaultdict(<class 'set'>,
{('<string>', 4, <class 'numba.errors.NumbaWarning'>):
{'Function "agg_update" was compiled in object mode without forceobj=True.\n\nFile "<string>", line 1:\n<source missing, REPL/exec in use?>\n', '\nCompilation is falling back to object mode WITH looplifting enabled because Function "agg_update" failed type inference due to: Untyped global name \'__update_redvars\': cannot determine Numba type of <class \'numba.ir.UndefinedType\'>\n\nFile "<string>", line 2:\n<source missing, REPL/exec in use?>\n'},
('<string>', 4, <class 'numba.errors.NumbaDeprecationWarning'>):
{'\nFall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.\n\nFor more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit\n\nFile "<string>", line 1:\n<source missing, REPL/exec in use?>\n'}})
```

**Comment by stuartarchibald** [comment]
@ehsantn thanks, I think the identical synthetic source and line number are the likely cause as it probably leads to comparison of the type itself.

**Comment by seibert** [comment]
Can we add a generic comparison operator to the base class that just compares on `id()`?  Once the sorting gets to that level, it doesn't really matter what the ordering is, it just has to be there.

**Comment by stuartarchibald** [comment]
Would `str(__class__)` then `id()` be ok, it'd then group warnings by class?

**Comment by seibert** [comment]
oh yeah, that would work better.
