### ISSUE TITLE
Depend on enum34 using PEP 508 environment markers

### ISSUE THREAD

**Issue by dsevero** [numba/numba#4103]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This is a straight up copy of https://github.com/numba/llvmlite/pull/483 

Looks like the offending lines are https://github.com/numba/numba/blob/master/setup.py#L309-L312 as mentioned by @esc

**Comment by stuartarchibald** [comment]
Thanks for the report. Fixed in #4104

**Comment by dsevero** [comment]
`llvmlite` had the same issue and has been fixed at the master branch, but a new release has not been made. Hence, this PR alone will not fix the issue, we need a new release of `llvmlite`.

Right?

**Comment by stuartarchibald** [comment]
The core team are in the process of producing release candidates as it's the end of a development cycle, rest assured that they will appear shortly. Numba takes longer to release as the build farm has to churn through literally hundreds of combinations, but they'll appear in the next few days!
