### ISSUE TITLE
cannot reassign the value to the elements of vector 

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4116]
```python
@jit(nopython=True)
def corJit(x1,x2,d):
    n = len(x1)
    ret = np.zeros(n)
    for i in np.arange(n-d+1):
        xx1_i = x1[i:(i+d)]
        xx2_i = x2[i:(i+d)]
        ret[i] = 1
    return ret

@jit(nopython=True)
def correlationJit(x1,x2,d):
    n = len(x1)
    ret = np.zeros(n)
    for i in np.arange(n-d+1):
        xx1_i = x1[i:(i+d)]
        xx2_i = x2[i:(i+d)]
        ret[i] = np.correlate(xx1_i,xx2_i)
    return ret
```
the function corJit can work, cause just assign the value to an inter
the function correlationJit cannot work, I don't konw why 
it says: 
```
TypingError: Failed at nopython (nopython frontend)
Cannot resolve setitem: array(float64, 1d, C)[int64] = array(float64, 1d, C)
```
can you give me some advice many thanks for help.

**Comment by stuartarchibald** [comment]
Thanks for the report. NOTE Updated comment with formatting.

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
I think following... `np.correlate` when called on two 1D array inputs will return a single element 1D array. This demonstrates:
```python
x1 = np.zeros(10)
x2 = np.zeros(10)
@jit(nopython=True)
def foo(x1, x2):
    return np.correlate(x1, x2)

print(foo(x1, x2))
print(foo.nopython_signatures)
```
gives:
```
[0.]
[(array(float64, 1d, C), array(float64, 1d, C)) -> array(float64, 1d, C)]
```
which shows a 1D array, value zero, being returned. The signature is then printed, which shows two `array(float64, 1d, C)` inputs and a return `->` of `array(float64, 1d, C)`, i.e. a 1D array is returned.

Numba does not support assignment of a 1D array to a scalar index, as demonstrated here:
```python
@jit(nopython=True)
def bar(idx):
    a = np.zeros(10)
    b = np.zeros(1)
    a[idx] = b

bar(0)
```
which produces the same error message as your code. The combination of these two effects is what is stopping your code from being compiled.

Thankfully, fixing this is pretty easy, the result of `np.correlate` on two identical length vectors is always a single value, so you can just index the zero-th element of the returned 1D array and assign that into the store for return.
```python
@jit(nopython=True)
def correlationJit(x1,x2,d):
    n = len(x1)
    ret = np.zeros(n)
    for i in np.arange(n-d+1):
        xx1_i = x1[i:(i+d)]
        xx2_i = x2[i:(i+d)]
        ret[i] = np.correlate(xx1_i,xx2_i)[0]
    return ret

x1 = np.arange(10)
x2 = np.arange(10)
d = 2
print(correlationJit(x1,x2,d))
```
gives:
```
[  1.   5.  13.  25.  41.  61.  85. 113. 145.   0.]
```
which is the same as NumPy.

Hope this helps.

**Comment by isaac-you** [comment]
@stuartarchibald  Thank you very much indeed. The reply  solve the problem immediately. :+1:

**Comment by stuartarchibald** [comment]
No problem. Closing this issue as it seems to be resolved. Thanks for using Numba!

**Comment by isaac-you** [comment]
@stuartarchibald 
And I have find some other problem. 
`@jit(nopython=True)
def correlation1_jit(x1,x2,d):
	'''
	numba way 
	time series correlation of two series
	x1/x2: such as open/high/low/close ...
	d: the delay window 
	'''
	n = len(x1)
	ret = np.zeros(n)
	for i in np.arange(n-d+1):
	    xx1_i = x1[i:(i+d)]
	    xx2_i = x2[i:(i+d)]
	    #ret[i] = np.correlate(xx1_i,xx2_i)[0]
	    ret[i] = np.corrcoef(xx1_i,xx2_i)[0][1]
	return ret`

TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'corrcoef' of type Module(<module 'numpy' from '/home/bosera/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>)

And in the code above I use the index [0][1] to make sure it is a scalar, but still the bug.

**Comment by isaac-you** [comment]
@stuartarchibald
And I have find some other problem:

`@jit(nopython=True)
def correlation1(x1,x2,d):
	n = len(x1)
	ret = np.zeros(n)
	for i in np.arange(n-d+1):
	    xx1_i = x1[i:(i+d)]
	    xx2_i = x2[i:(i+d)]
	    #ret[i] = np.correlate(xx1_i,xx2_i)[0]
	    ret[i] = np.corrcoef(xx1_i,xx2_i)[0][1]
	return ret`

TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'corrcoef' of type Module(<module 'numpy' from '/home/bosera/anaconda3/lib/python3.6/site-packages/numpy/init.py'>)

And in the code above I use the index [0][1] to make sure it is a scalar, but still the bug.

**Comment by isaac-you** [comment]
@stuartarchibald
And I have find some other problem. : 
```python <@jit(nopython=True)
def correlation1_jit(x1,x2,d):
	'''
	numba way 
	time series correlation of two series
	x1/x2: such as open/high/low/close ...
	d: the delay window 
	'''
	n = len(x1)
	ret = np.zeros(n)
	for i in np.arange(n-d+1):
	    xx1_i = x1[i:(i+d)]
	    xx2_i = x2[i:(i+d)]
	    #ret[i] = np.correlate(xx1_i,xx2_i)[0]
	    ret[i] = np.corrcoef(xx1_i,xx2_i)[0][1]
	return ret> ```


TypingError: Failed at nopython (nopython frontend)
Unknown attribute 'corrcoef' of type Module(<module 'numpy' from '/home/bosera/anaconda3/lib/python3.6/site-packages/numpy/init.py'>)

And in the code above I use the index [0][1] to make sure it is a scalar, but still the bug.

**Comment by stuartarchibald** [comment]
@isaac-you In future it'd be really helpful if you could please open a new issue for each distinct bug/problem as it makes it easier to track what gets fixed. Many thanks!

To the problem you note, `np.corrcoef` support was added to Numba in 0.42, https://github.com/numba/numba/pull/3509, which version of Numba do you have?
