### ISSUE TITLE
Weird behaviour with uint64

### ISSUE THREAD

**Issue by usamec** [numba/numba#4124]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

There is some weird overflow magic going on.
With numba:
```
import numba
@numba.njit(numba.uint64(numba.uint64, numba.uint64, numba.uint64))	
def foo(a, b, x):	
    return (a * x + b) % 515024571323837

foo(2744776747, 3698061793, 3897592450)
```
The result is `336756169721829`, which is incorrect.
Correct one should be: `445758773403616`.
(C++ gets it right: https://ideone.com/u50a7Q)

**Comment by stuartarchibald** [comment]
Thanks for the report. I think what you are seeing is because the integer constant `515024571323837` is considered an `int64` (CPython default integer type is signed) which then has an impact on the modulo operation as the overflowed result of `(a * x + b)` is interpreted as signed. The following works as expected, note the use of `.inspect_types()` at the end to look at the type Numba inferred for each variable:

```python
import numba

@numba.njit(numba.uint64(numba.uint64, numba.uint64, numba.uint64))
def foo(a, b, x):
    return (a * x + b) % numba.uint64(515024571323837)

args = (2744776747, 3698061793, 3897592450)
print(foo.py_func(*args)) # this is the result from the interpreter
print(foo(*args))         # this is the result from compiled code
assert foo.py_func(*args) == foo(*args)

foo.inspect_types()
```

**Comment by stuartarchibald** [comment]
Oh and C++ get's it right because the const is specified as ` 515024571323837ull`, the above does the equivalent.

**Comment by usamec** [comment]
@stuartarchibald thanks for reply.
Btw C++ gets it right even without `ull` annotation. https://ideone.com/CwdbAi

**Comment by stuartarchibald** [comment]
hmm, that's interesting. I think this just comes down to Numba deciding that the const is signed, which is default, and as a result it "infects" the modulo. Seems like, from the disassembly, that C++ doesn't suffer from this.

**Comment by sklam** [comment]
That's a potential enhancement we can do.  The inspect types shows:

```python
def foo(a, b, x):

    # --- LINE 5 --- 
    #   a = arg(0, name=a)  :: uint64
    #   b = arg(1, name=b)  :: uint64
    #   x = arg(2, name=x)  :: uint64
    #   $0.3 = a * x  :: uint64
    #   del x
    #   del a
    #   $0.5 = $0.3 + b  :: uint64
    #   del b
    #   del $0.3
    #   $const0.6 = const(int, 515024571323837)  :: Literal[int](515024571323837)
    #   $0.7 = $0.5 % $const0.6  :: int64
    #   del $const0.6
    #   del $0.5
    #   $0.8 = cast(value=$0.7)  :: uint64
    #   del $0.7
    #   return $0.8

    return (a * x + b) % 515024571323837
```

Where the modulo operator is seeing `$const0.6` as a `Literal[int]` type.  The modulo (and all binary arithmetic-operators) can be modified to cast any Literal type to the type of the other operand (if non-Literal).

**Comment by sklam** [comment]
The whole problem comes from the `(a * x + b)` part resulting in a number that takes all 64-bit (MSB set).  But, Numba prefers to use a signed modulo (vs C/C++ prefers unsigned) when the operands have differing signedness.  This causes the result of `(a * x + b)` to be implicitly casted to signed int64 and misinterpreting the MSB as sign-bit.

**Comment by sklam** [comment]
I'm closing this issue since it can be resolve by forcing a `uint64` modulo by explicitly casting the RHS.
