### ISSUE TITLE
ndarray.max() method in nopython is order-dependent with NaN

### ISSUE THREAD

**Issue by bsamuel-ui** [numba/numba#4125]
## Reporting a bug

- [x] I am using `0.43.1`
- [x] I have included below a minimal working reproducer.

### Observed behavior

```python
from numba import njit
import numpy as np

@njit
def nm(x):
    return x.max()

a = np.array([5.0, np.nan])
print(nm(a), a.max())
a = np.array([np.nan, 5.0])
print(nm(a), a.max())

5.0 nan
nan nan
```

Same behavior observed with `.min`. Testing with datetime64 is also inconsistent.

### Expected behavior

Expect compatibility with numpy, and that a min/max function returns the same result regardless of order.

Numpy handles datetimes differently; NaT is ignored if possible, but will be returned if it's the only value. (So numpy NaNs are treated as most extreme, but NaT is treated as least extreme.)

### Possible fix

In [this function](https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/numba/targets/arraymath.py#L468):
* add a fork for Floats to check `isnan` and return it immediately.
* add a fork for Datetime to check for NaT and skip.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce, this is an algorithmic bug.

**Comment by timothymillar** [comment]
Just for anyone else who stumbles across this,
in numba `0.45.1` and `0.47.0` the same bug in the following functions:
```
np.max
np.min
np.argmax
np.argmin
```
