### ISSUE TITLE
Overload of Numpy ufuncs doesn't work

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#4133]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Overload of ufuncs doesn't work. A minimal reproducer is below:
```python
@numba.extending.overload(np.exp)
def exp_list_overload(A):
   if isinstance(A, numba.types.List):
      return lambda A: np.exp(np.array(A))

@numba.njit
def f():
    return np.exp([1,2,3])

f()
```
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<ufunc 'exp'>) with argument(s) of type(s): (list(int64))
 * parameterized
In definition 0:
    TypingError: can't resolve ufunc exp for types (list(int64),)
    raised from /home/ehsan/dev/numba/numba/typing/npydecl.py:109
In definition 1:
    TypingError: can't resolve ufunc exp for types (list(int64),)
    raised from /home/ehsan/dev/numba/numba/typing/npydecl.py:109
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<ufunc 'exp'>)
[2] During: typing of call at <ipython-input-2-e2192680c324> (7)


File "<ipython-input-2-e2192680c324>", line 7:
def f():
    return np.exp([1,2,3])
    ^
```

**Comment by seibert** [comment]
This is almost certainly a collision between the old-style and new-style registration of functions.  @sklam: thoughts?

**Comment by sklam** [comment]
Oh, very likely.

**Comment by sklam** [comment]
The problem is caused by https://github.com/numba/numba/blob/309d6157a07b370b129688c68548c7f64df67046/numba/extending.py#L94 disabling the `infer_global`.  I need to review why that branch is needed.
