### ISSUE TITLE
numba fails to compile ray casting function

### ISSUE THREAD

**Issue by brycefrank** [numba/numba#4135]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I rely on a numba JIT-compiled function to perform a ray casting operation. The function performs reliably in ~99% of cases, but I have found a case where it fails.

The reproducible example is:

```{python}
from numba import vectorize, bool_, float64
import numpy as np

# Define points to clip
x_vec = [468559.33, 468559.99]
y_vec = [5016610.22, 5016609.12]

bad_poly = np.array([[468560.495, 5016609.98611111],
                [468560.495, 5016607.625],
                [468558.245, 5016609.875],
                [468557.97700443, 5016610.41099114],
                [468558.13454149, 5016610.51065745],
                [468560.495, 5016609.98611111]])

good_poly = np.array([[468560.495, 5016609.98611111],
                     [468560.495, 5016607.625],
                     [468558.245, 5016609.875],
                     [468558.13454149, 5016610.51065745],
                     [468560.495, 5016609.98611111]])

poly = bad_poly

@vectorize([bool_(float64, float64)])
def ray(x, y):
    n = len(poly)
    inside = False
    p2x = 0.0
    p2y = 0.0
    xints = 0.0
    p1x, p1y = poly[0]
    for i in range(n + 1):
        p2x, p2y = poly[i % n]
        if y > min(p1y, p2y):
            if y <= max(p1y, p2y):
                if x <= max(p1x, p2x):
                    if p1y != p2y:
                        xints = (y - p1y) * (p2x - p1x) / (p2y - p1y) + p1x
                    if p1x == p2x or x <= xints:
                        inside = not inside
        p1x, p1y = p2x, p2y
    return inside
```

If `poly=bad_poly` then the function does not compile and the following error is produced

```
python: /tmp/build/80754af9/llvmdev_1546540969021/work/include/llvm/ADT/APInt.h:1124: bool llvm::APInt::operator==(const llvm::APInt&) const: Assertion `BitWidth == RHS.BitWidth && "Comparison requires equal bit widths"' failed.
```

If `poly=good_poly`, then the function compiles. It seems that deleting one or some of the coordinates allows the function to compile.

**Comment by seibert** [comment]
To make sure we understand your environment completely, can you run `numba -s` and pasted the output here?

**Comment by seibert** [comment]
Thanks!  We'll try to reproduce this.

**Comment by brycefrank** [comment]
Thank you!

I attempted to update to `0.44` and I receive the same error. [This](https://gist.github.com/brycefrank/6c86f48c59efbd038c44b5aa570247aa) environment is much smaller and achieves the same error so it may help speed up the debugging.

I was able to compile the function on a different computer with no error yesterday, I will try to track down the environment for that as well.

**Comment by brycefrank** [comment]
The script passes under [this](https://gist.github.com/brycefrank/99db619be7690ae10d88a124b693992d)
 environment (I downgraded to `0.4.1`). I am checking it on a large number of `poly`s in a different script.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is an LLVM issue:
```
NUMBA_CPU_NAME="ivybridge" NUMBA_CPU_FEATURES="" python issue4135.py
```
reproduces under Numba 0.44 with LLVM 8 backing. Nehalem chips onward seem to trigger the problem, however, switching on AVX512 seems to make it go away, e.g.:
```
NUMBA_CPU_NAME="skylake-avx512" NUMBA_CPU_FEATURES="" python issue4135.py 
```

**Comment by stuartarchibald** [comment]
This does not reproduce on mainline for Numba 0.55 (with LLVM 11). Closing assumed fixed.
