### ISSUE TITLE
np.int8 and np.unit8 doesn't work with np.bincount function.

### ISSUE THREAD

**Issue by justasz** [numba/numba#4169]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Numba version: 0.44.0
Numpy version: 1.16.2

### Reproduction of an issue
```python
import numpy as np
from numba import njit

@njit()
def get_event_count1(grp, wgt):
    return np.bincount(grp, weights=wgt)


def get_event_count2(grp, wgt):
    return np.bincount(grp, weights=wgt)


np.random.seed(42)
N = 10000
group = np.random.randint(0, 10, N)
target = np.random.randint(0, 2, N).astype(np.uint8)

print(f'With njit: {sum(get_event_count1(grp=group, wgt=target))}\nWithout njit: {sum(get_event_count2(grp=group, wgt=target))}')
>>> With njit: 1449
>>> Without njit: 5033.0
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce, this is a bug. Fix in #4173.
