### ISSUE TITLE
@numba.jit not handling integer parameters properly

### ISSUE THREAD

**Issue by josericardo** [numba/numba#418]
Hi, I don't know what the problem can be, but I'm getting different results for the following code

```
@numba.jit
def paint(r, t):
    drawn = 0

    while (r+1)**2 - r**2 <= t:
        drawn += 1
        t -= (r+1)**2 - r**2
        r += 2

    return drawn
```

If my script contains only one call to

paint(10000000000000000, 1000000000000000000)

I get **49** as the result, which is the right answer.

Unfortunately, If my script calls `paint` with small integers as parameters, like:

paint(1, 10)
paint(10000000000000000, 1000000000000000000)

The second call returns **51** as the result.

Strangely, if I change the second line of the while loop to 

```
t -= 2*r + 1
```

The function behaves well for both cases.

I'm using: 

Python 2.7.6 :: Continuum Analytics, Inc.
conda 3.4.1
numba 0.13.1

**Comment by pitrou** [comment]
This is now correctly handled as the handling of integer arguments has changed (see [NBEP 1: Changes in integer typing](http://numba.pydata.org/numba-doc/dev/proposals/integer-typing.html)).
