### ISSUE TITLE
Question: How to set up custom Literals?

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#4181]
I know this interface isn't really public at the moment, but I've a question on how to expand numba to support custom literal types.

I want to pass a tuple defining my implementation *by value* into generated_jit

The following works, but is a cludge:

```python
@numba.generated_jit(nopython=True, nogil=True, cache=True)
def fn(a, b):
    print(a)
    print(b)
    print(b.instance_type.literal_value)

    def impl(a, b):
        return a.sum()

    return impl

a = 1
print(fn(np.ones((10, 10)), types.Literal((a, 2, 3))))
a = 4
print(fn(np.ones((10, 10)), types.Literal((a, 2, 3))))

from pprint import pprint
pprint(fn.signatures)
```

produces the following:

```
[(array(float64, 2d, C), typeref[Literal[tuple]((1, 2, 3))]),
 (array(float64, 2d, C), typeref[Literal[tuple]((4, 2, 3))])]
```

It's a cludge because  according to:

https://github.com/numba/numba/blob/e8ac4951affacd25c63ba2c18d62a3f12ed7e0ba/numba/types/abstract.py#L379-L385

we should use the following to create new literals:

https://github.com/numba/numba/blob/5217ce98ccc10b252885a859a4dcc405084600c2/numba/types/misc.py#L58-L59

Which seems to depend on writing something like the following:

```python
class BobLiteral(types.Literal, types.containers.Tuple):
    def __init__(self, value):
        self._literal_init(value)
        print(self.literal_type)
        types.containers.Tuple.__init__(self,
                                        tuple(type(v) for v in value))


class bob(tuple):
    pass


types.Literal.ctor_map[bob] = BobLiteral
```

but this would need to registered somehow with:

https://github.com/numba/numba/blob/e8ac4951affacd25c63ba2c18d62a3f12ed7e0ba/numba/datamodel/models.py#L720-L725

Is this possible at the moment? I'm not sure how to go the rest of the way.

**Comment by stuartarchibald** [comment]
This sort of thing seems to work, but is likely dangerous and definitely uses internal APIs!
```python
from numba import types, typeof
from numba import njit, generated_jit
from numba.datamodel.models import UniTupleModel
from numba.datamodel.registry import register_default

import numpy as np

class UniTupleLiteral(types.Literal, types.UniTuple):

    def __init__(self, value):
        self._literal_init(value)
        ty = typeof(value[0])
        for x in value[1:]:
            if typeof(x) != ty:
                raise TypeError("unituple not homogeneous")
        types.UniTuple.__init__(self, ty, len(value))
        self.name = "literal tuple"

types.Literal.ctor_map[tuple] = UniTupleLiteral
register_default(UniTupleLiteral)(UniTupleModel)

@generated_jit
def fn(x):
    print(x)
    ret = np.prod(x.literal_value)
    def impl(x):
        return ret
    return impl

@njit
def call_fn():
    return fn((10, 20, 30))

print(call_fn())
```

**Comment by ehsantn** [comment]
@stuartarchibald any reason for not supporting tuple literals in general? I know it's some work to potentially adapt every place tuples are used, but it would be very useful for several use cases.

**Comment by stuartarchibald** [comment]
@ehsantn I think with some effort it could be done, it may require some sort of work-out-the-type-of-tuple-literal call back, and the cost of walking through large tuples at compile time probably also needs to be considered, but it's no worse than e.g. `hash` for the same.

**Comment by sjperkins** [comment]
@stuartarchibald Cool!

In order to make it less dangerous, perhaps it might be better to restrict it to the following (i.e. force the literal, rather than let the internal typing mechanisms just convert any tuple to a literal)?

```python
from numba.types.misc import literal

@njit
def call_fn():
    return fn(literal(10, 20, 30))
```
