### ISSUE TITLE
Unicode lstrip/rstrip/strip do not handle all whitespace characters

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#4188]
## Reporting a bug

- [x] I am using the latest ~released~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Unicode `lstrip`, `rstrip`, `strip` functions only handle space as whitespace. Other whitespace characters like `\t` are ignored:
```python
In [5]: numba.njit(lambda: '\ta'.lstrip())()                                                                                                                                                                
Out[5]: '\ta'

In [6]: '\ta'.lstrip()                                                                                                                                                                                      
Out[6]: 'a'
```
`string` library reports whitespace characters as below, but we need to look into CPython implementation.
```
In [1]: import string                                                                                                                                                                                       
In [2]: string.whitespace                                                                                                                                                                                   
Out[2]: ' \t\n\r\x0b\x0c'
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. This is the table from CPython:

https://github.com/python/cpython/blob/3.7/Objects/unicodetype_db.h#L5996-L6031

an ASCII based shortcut is also in use:

https://github.com/python/cpython/blob/3.7/Objects/unicodeobject.c#L265-L294
