### ISSUE TITLE
Question: vecotrize `vmap` in `Jax`

### ISSUE THREAD

**Issue by JiahaoYao** [numba/numba#4193]
## Feature request

Hi, do we have something like `vmap` in the `Jax`: https://github.com/google/jax#auto-vectorization-with-vmap? `vmap` optimize mapping a function to a list.

**Comment by seibert** [comment]
There is no vmap equivalent in Numba.  It could be created, though, possibly by using some of the gufunc machinery.

**Comment by JiahaoYao** [comment]
I see. Thanks @seibert!
