### ISSUE TITLE
Untyped global name 'prange': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

### ISSUE THREAD

**Issue by Sushrut98** [numba/numba#4195]
```python
@jit(nopython=True, parallel=True)
def pos_stream(pos, vel, acc, dt):
	pos_new = np.zeros((N,1))			
	for i in prange(N):
		pos_new[i,0] = pos[i,0] + vel[i,0]*dt + 0.5*acc*(dt**2)
	return pos_new
```
trying to run this code in parallel and got below error:
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'prange': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

File "Poisseuille_Compile.py", line 36:
def pos_stream(pos, vel, acc, dt):
    <source elided>
	pos_new = np.zeros((N,1))			
	for i in prange(N):
 ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

then removed nopython=True and got this error

global name 'prange' is not defined

**Comment by stuartarchibald** [comment]
Thanks for the report. To use `prange` it needs to be imported from the `numba` module like `from numba import prange`. This works:
```python
from numba import jit, prange
import numpy as np

N = 10

@jit(nopython=True, parallel=True)
def pos_stream(pos, vel, acc, dt):
    pos_new = np.zeros((N, 1))
    for i in prange(N):
        pos_new[i,0] = pos[i,0] + vel[i,0]*dt + 0.5*acc*(dt**2)
    return pos_new

pos_stream(np.zeros((N, 1)), np.zeros((N, 1)), 1.0, 2.0)
```
