### ISSUE TITLE
Upgrading numba 0.43.1 to 0.44.0 breaks my code

### ISSUE THREAD

**Issue by jbhopkins** [numba/numba#4203]
Note: I initially sent this to the mailing list, but was asked to open a bug report here.

I'm using numba quite happily in several places where I need speed, and it's been working great. However, when I upgraded from 0.43.1 to 0.44.0 my code suddenly stopped working. I've attached (and inlined below) a minimal working example. For clarity, this particular function checks whether a given input array of points is within the area of an arbitrarily defined polygon with a given array of vertices. All vertices and points always have integer positions, and the function returns an array with a True/False value for each input point.

I'm running this using python 2.7.15 and numpy 1.16.3, both installed through conda on MacOS 10.14.5. I tried with both 0.44.0 and 0.44.1 and got the same error. I don't actually know if this is a bug or new expected behavior, I'm hoping you can help me figure that out.

The error I get is:

```
min_example.py:4: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "npnpoly" failed type inference due to: Invalid use of Function(<built-in function empty_like>) with argument(s) of type(s): (array(int64, 1d, A), dtype=Function(<type 'bool'>))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function empty_like>)
[2] During: typing of call at min_example.py (12)




File "min_example.py", line 12:
def npnpoly(verts,points):
    <source elided>
    """
    out = np.empty_like(points[:,0], dtype=np.bool)
    ^


  @jit
min_example.py:4: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "npnpoly" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>


File "min_example.py", line 25:
def npnpoly(verts,points):
    <source elided>
    maybe = np.empty(len(xpi),dtype=np.bool)
    for i in xrange(points.shape[0]):
    ^


  @jit
Traceback (most recent call last):
  File "min_example.py", line 41, in <module>
    npnpoly(verts, points)
  File "/Users/jessehopkins/miniconda2/lib/python2.7/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
    raise e
RuntimeError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:610:27: error: expected type
  %".407" = icmp sge i64 (slice(None, None, None), 0), -9223372036854775808
```

Here's a minimal working example:

```python
import numpy as np
from numba import jit

@jit
def npnpoly(verts,points):
    """Check whether given points are in the polygon.

    points - Nx2 array

    See http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html
    """
    out = np.empty_like(points[:,0], dtype=np.bool)

    xpi = verts[:,0]
    ypi = verts[:,1]

    xmin = min(xpi)
    xmax = max(xpi)
    ymin = min(ypi)
    ymax = max(ypi)
    # shift
    xpj = xpi[np.arange(xpi.size)-1]
    ypj = ypi[np.arange(ypi.size)-1]
    maybe = np.empty(len(xpi),dtype=np.bool)
    for i in xrange(points.shape[0]):
        x,y = points[i]

        if (x<xmin or xmax<x) or (y<ymin or ymax<y):
            out[i] = 0
        else:
            maybe[:] = ((ypi <= y) & (y < ypj)) | ((ypj <= y) & (y < ypi))

            out[i] = np.sum(x < (xpj[maybe]-xpi[maybe])*(y - ypi[maybe]) \
                           / (ypj[maybe] - ypi[maybe]) + xpi[maybe]) % 2

    return out

verts = np.array([[0,0], [10,0], [10,10], [0, 10]])
points = np.array([[1,1], [-1,-1], [-1,-2]])

out = npnpoly(verts, points)

print out
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I suspect that what you are seeing is due to the work done to decouple the fall-back behaviour of the compilation pipeline [that is being deprecated](http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit). I'm also pretty sure I've seen a `slice` leak into LLVM IR before on another ticket.

However, I suspect that this is a scientific application and I imagine looking for performance, therefore I can strongly recommend taking a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html), particularly the part about `nopython` mode. The use of `numba.jit` without the `nopython=True` kwarg means that the compiler can fall back to object mode (this pattern [is being deprecated](http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit) because of cases just like this one) and as a result of this the performance of the compiled function is unlikely to be a) stable and b) anywhere near optimal.

For reference, this function a) works b) works in `nopython` mode and c) will execute a lot faster as a result of b).
```python
import numpy as np
from numba import jit

@jit(nopython=True)
def npnpoly(verts,points):
    """Check whether given points are in the polygon.

    points - Nx2 array

    See http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html
    """
    dt = np.bool_
    out = np.empty_like(points[:,0], dtype=dt)

    xpi = verts[:,0]
    ypi = verts[:,1]

    xmin = min(xpi)
    xmax = max(xpi)
    ymin = min(ypi)
    ymax = max(ypi)
    # shift
    xpj = xpi[np.arange(xpi.size)-1]
    ypj = ypi[np.arange(ypi.size)-1]
    maybe = np.empty(len(xpi),dtype=dt)
    for i in range(points.shape[0]):
        x,y = points[i]

        if (x<xmin or xmax<x) or (y<ymin or ymax<y):
            out[i] = 0
        else:
            maybe[:] = ((ypi <= y) & (y < ypj)) | ((ypj <= y) & (y < ypi))

            out[i] = np.sum(x < (xpj[maybe]-xpi[maybe])*(y - ypi[maybe]) \
                           / (ypj[maybe] - ypi[maybe]) + xpi[maybe]) % 2

    return out

verts = np.array([[0,0], [10,0], [10,10], [0, 10]])
points = np.array([[1,1], [-1,-1], [-1,-2]])

out = npnpoly(verts, points)

print out
```

Hope this helps.

**Comment by jbhopkins** [comment]
Thanks for the response, you're right that this is a scientific application. Most of my code does use nopython=True (and cache=True). I think the reason I didn't do that here is that if I just run with @jit(nopython=True) I get an error. Looking at your code it looks like it's a difference between np.bool and np.bool_ as the dtype. Until I just googled it just now I hadn't realized np.bool aliased the python bool, whereas np.bool_ is the numpy bool . . .

Anyways, thanks for the help!

**Comment by seibert** [comment]
This sort of confusion is one the reasons we are deprecating object mode, although it was not our intention to break it, so we'll see if there is a way to fix this regression.  Glad this clears things up for you!

**Comment by stuartarchibald** [comment]
This now doesn't reproduce on master, think https://github.com/numba/numba/pull/4224 fixed.

**Comment by ARF1** [comment]
@stuartarchibald I believe this issue should be reopened:

On numba 0.46 the following code fails:
```
@njit 
def test(x)
    y = np.empty_like(x, np.bool)
```

Error message:
`Invalid use of Function(<built-in function empty_like>) with argument(s) of type(s): (array(float64, 1d, C), Function(<class 'bool'>))`

Oddly enough, with `np.bool_` the whole thing works...

**Comment by stuartarchibald** [comment]
@ARF1 thanks for the report. I'm not sure that what you are doing is the same as the originally reported problem, the code sample you present is not causing an LLVM IR parsing error?

From the error message it seems like you are using `np.bool` when `np.bool_` is meant. It's important to note that `np.bool` is an alias of Python's `bool` where as `np.bool_` is a NumPy dype i.e.:
```
In [1]: import numpy as np                                                                                                      

In [2]: np.bool is bool                                                                                                         
Out[2]: True

In [3]: np.bool_ is bool                                                                                                        
Out[3]: False

In [4]: np.bool_.mro()                                                                                                          
Out[4]: [numpy.bool_, numpy.generic, object]
```
The use of Python types as dtype arguments to NumPy allocator functions is not supported in `nopython` mode (as requested by the use of `@njit` in your code). A similar issue is the use of `np.int` when `np.int_` is meant, https://github.com/numba/numba/issues/4658#issuecomment-538309948.

**Comment by ARF1** [comment]
@stuartarchibald 
> From the error message it seems like you are using `np.bool` when `np.bool_` is meant. It's important to note that `np.bool` is an alias of Python's `bool` where as `np.bool_` is a NumPy dype i.e.:
> 
> 
> The use of Python types as dtype arguments to NumPy allocator functions is not supported in `nopython` mode (as requested by the use of `@njit` in your code). A similar issue is the use of `np.int` when `np.int_` is meant, [#4658 (comment)](https://github.com/numba/numba/issues/4658#issuecomment-538309948).

I was definitely not aware of the `np.bool_` vs. `np.bool` significance. Is this well known? Did I miss some big-fat warning in the docs? Somehow, I never encountered the issue when working with numpy.

If you have time: Could this be auto-corrected by numpy? It seems like this would be a very frequent mistake. Or are the two `dtypes` not equivalent?
