### ISSUE TITLE
support for 'dtype' keyword argument in np.sum()

### ISSUE THREAD

**Issue by pSpitzner** [numba/numba#4220]
## Feature request: Add `dtype` keyword argument to `np.sum()`

I am working on a scientific toolbox that relies on numpy and scipy and requires decent numeric precision. To parallelize core parts, I considered using Numba as an _optional dependency_ with a fallback to native numpy. This seems doable and elegant except for the following:

The existing code relies heavily on `np.mean()` with the `axis` and `dtype` keyword arguments. `dtype=np.float64` is needed to get enough precision in certain situations.

* This does _not_ cast (copy to new dtype) the input array, only the temporary variable is of a higher precision.
* I managed to implement this in numba with a manual for loop, casting _within_ the loop
* The problem arises when using arrays of higher dimension. A specific function has to be written for every ndim-to-axis combination. As far as i understand, one cannot tell numba to check if-conditions for dimensionality during compilation, to avoid `tuple index out of range`.

The script below illustrates the precision issue:

```
import numpy as np
import numpy.random
import time

try:
    from numba import jit, njit, prange, gdb
    # raise ImportError # uncomment to toggle numba
except ImportError:
    print('Numba not available, skipping parallelization')
    # replace numba functions if numba not available:
    # we only use jit and prange
    # helper needed for decorators with kwargs
    def parametrized(dec):
        def layer(*args, **kwargs):
            def repl(f):
                return dec(f, *args, **kwargs)
            return repl
        return layer

    @parametrized
    def jit(func, **kwargs):
        return func
    def prange(*args):
        return range(*args)

ftype = np.float64


@jit(nopython=True, parallel=False, fastmath=True)
def mean_lowprec(a):
    return np.sum(a)/(2*a.shape[1])

@jit(nopython=True, parallel=False, fastmath=True)
def mean_copy(a):
    # copies in ram, factor two memory required
    b = a.astype(ftype)
    return np.sum(b)/(2*a.shape[1])

@jit(nopython=True, parallel=False, fastmath=True)
def mean_2d_reduce(a):
    total = ftype(0)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            total += ftype(a[i,j])

    return total/ftype(a.shape[0]*a.shape[1])


a = np.zeros((2, 512*512), dtype=np.float32)
a[0, :] = 1.0
a[1, :] = 0.1

# compile first call
mean_lowprec(a)
mean_copy(a)
mean_2d_reduce(a)

time_beg = time.time()
print(f'np.sum f4:           {np.sum(a)/(2*a.shape[1])}')
print(f'{(time.time()-time_beg)*1000 :.2f} ms\n')

time_beg = time.time()
print(f'np.sum f8:           {np.sum(a, dtype=ftype)/(2*a.shape[1])}')
print(f'{(time.time()-time_beg)*1000 :.2f} ms\n')

time_beg = time.time()
print(f'mean_lowprec(a):     {mean_lowprec(a)}')
print(f'{(time.time()-time_beg)*1000 :.2f} ms\n')

time_beg = time.time()
print(f'mean_copy(a):        {mean_copy(a)}')
print(f'{(time.time()-time_beg)*1000 :.2f} ms\n')

time_beg = time.time()
print(f'mean_2d_reduce(a):   {mean_2d_reduce(a)}')
print(f'{(time.time()-time_beg)*1000 :.2f} ms\n')
```

Results in
```
np.sum f4:           0.5499992370605469
0.49 ms

np.sum f8:           0.5500000007450581
0.55 ms

mean_lowprec(a):     0.5498046875
0.10 ms

mean_copy(a):        0.5500000007450581
0.84 ms

mean_2d_reduce(a):   0.5500000007450581
0.15 ms
```

While the last option seems a good candidate performance/memory wise, I failed to come up with a solution that offers a one-wrapper-function fits-all to mimic the native `numpy.mean()`.

Hence, I believe support for the `dtype` argument in numba would be a great feature!
I would greatly appreciate ideas for a workaround or some background on the details I am missing. 

Thanks,
Paul

**Comment by sklam** [comment]
Summarizing:

- [ ] feature request for `np.mean()` with `dtype` argument.
- [ ] additional feature request for `np.sum()` with `dtype` argument (because `np.mean` calls `np.sum`).

The ability to do `if my_array.ndim == 2` relates to the dead branch pruning feature, but it doesn't do work in this case.  @stuartarchibald, i think this case will require type-inference info in branch pruning.

**Comment by stuartarchibald** [comment]
@sklam think the semantic constant rewrites https://github.com/numba/numba/pull/4113 will replace the `my_array.ndim` in `if my_array.ndim == 2` with the constant  value, e.g. were it 2, the condition would end up `if 2 == 2` which would prune fine?
