### ISSUE TITLE
How can I vectorize the function 

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4235]
there are lots of vectorized functions in numpy  such as: np.mean/np.min/np.sum...
they can calculate the result for each row of the matrix simultaneously. Now I want to calculate the rank correlation for each row of two matrix 

```
def ICIR(out,targetValue):
	'''
	the mean rankIC divided by std 
	'''
	rankic = []  	#suppose the length of targetValue and out is the same 
	timeNum = targetValue.shape[0]		#the number of different timeID 
	
	for i in range(timeNum):
		rankic.append(rankIC(out[i,:],targetValue[i,:]))
	
	rankic = np.array(rankic)
	icir = rankic.mean()/rankic.std()

	return icir
```  
and How can I make the function ICIR vectorized to calculate the  rank correlation for each row of two matrix  simultaneously?
Thank you very much.

**Comment by esc** [comment]
@isaac-you thanks for asking this question and contributing to Numba. You will probably need to use the following to vectorize this:

http://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-guvectorize-decorator

**Comment by isaac-you** [comment]
Thank you so much. I will figure it out. @esc

**Comment by esc** [comment]
@isaac-you you are welcome, please don't hesitate to report back if you encounter any issues. Good luck!
