### ISSUE TITLE
Dead Kernel WSL Debian on np.arctan()

### ISSUE THREAD

**Issue by saltypeanuts** [numba/numba#4247]
I'm currently running numba on WSL (Debian, Windows 10) and having my kernel die whenever I run a loop with np.arctan(). Processor is an FX8350

Working:
```
for i in range(start, len(array)):
    temp = array[i-start+1:i+1]
    temp = (temp - temp.min())/(temp.max() - temp.min())*2-1
    out[i] = np.arctanh(temp[-1]) 
```
Failing:
```
@jit(nopython=True)
     
     def jit_loop(start, array):
         for i in range(start, len(array)):
             out = np.zeros(len(array))
             temp = array[i-period+1:i+1]
             temp = (temp - temp.min())/(temp.max() - temp.min())*2-1
             out[i] = np.arctanh(temp[-1]) 
                             
         return out


```

**Comment by saltypeanuts** [comment]
Here's the dump from the command line:

-linux-gnu/libcrypto.so.1.1
7f6f1679a000-7f6f167b8000 r--p 0026a000 00:00 1323864            /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7f6f167b8000-7f6f167c6000 rw-p 00288000 00:00 1323864            /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7f6f167c6000-7f6f167c9000 rw-p 00000000 00:00 0
7f6f167d0000-7f6f16833000 r-xp 00000000 00:00 1323866            /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7f6f16833000-7f6f1683d000 ---p 00063000 00:00 1323866            /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7f6f1683d000-7f6f16a32000 ---p 0006d000 00:00 1323866            /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7f6f16a32000-7f6f16a36000 r--p 00062000 00:00 1323866            /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7f6f16a36000-7f6f16a3c000 rw-p 00066000 00:00 1323866            /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7f6f16a40000-7f6f16a45000 r-xp 00000000 00:00 1325444            /usr/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so
7f6f16a45000-7f6f16a47000 ---p 00005000 00:00 1325444            /usr/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so
7f6f16a47000-7f6f16c44000 ---p 00007000 00:00 1325444            /usr/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so
7f6f16c44000-7f6f16c45000 r--p 00004000 00:00 1325444            /usr/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so
7f6f16c45000-7f6f16c46000 rw-p 00005000 00:00 1325444            /usr/lib/python3.5/lib-dynload/_hashlib.cpython-35m-x86_64-linux-gnu.so
7f6f16c50000-7f6f16d50000 rw-p 00000000 00:00 0
7f6f16d50000-7f6f16d51000 r-xp 00000000 00:00 1325445            /usr/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so
7f6f16d51000-7f6f16d52000 ---p 00001000 00:00 1325445            /usr/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so
7f6f16d52000-7f6f16f50000 ---p 00002000 00:00 1325445            /usr/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so
7f6f16f50000-7f6f16f51000 r--p 00000000 00:00 1325445            /usr/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so
7f6f16f51000-7f6f16f52000 rw-p 00001000 00:00 1325445            /usr/lib/python3.5/lib-dynload/_opcode.cpython-35m-x86_64-linux-gnu.so
7f6f16f60000-7f6f16fe0000 rw-p 00000000 00:00 0
7f6f16fe0000-7f6f17005000 r-xp 00000000 00:00 1312220            /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7f6f17005000-7f6f17006000 ---p 00025000 00:00 1312220            /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7f6f17006000-7f6f17204000 ---p 00026000 00:00 1312220            /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7f6f17204000-7f6f17205000 r--p 00024000 00:00 1312220            /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7f6f17205000-7f6f17206000 rw-p 00025000 00:00 1312220            /lib/x86_64-linux-gnu/liblzma.so.5.2.2
7f6f17210000-7f6f17217000 r-xp 00000000 00:00 1325864            /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so
7f6f17217000-7f6f1721a000 ---p 00007000 00:00 1325864            /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so
7f6f1721a000-7f6f17416000 ---p 0000a000 00:00 1325864            /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so
7f6f17416000-7f6f17417000 r--p 00006000 00:00 1325864            /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so
7f6f17417000-7f6f17419000 rw-p 00007000 00:00 1325864            /usr/lib/python3.5/lib-dynload/_lzma.cpython-35m-x86_64-linux-gnu.so
7f6f17420000-7f6f1742f000 r-xp 00000000 00:00 1312156            /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f6f1742f000-7f6f17431000 ---p 0000f000 00:00 1312156            /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f6f17431000-7f6f1762e000 ---p 00011000 00:00 1312156            /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f6f1762e000-7f6f1762f000 r--p 0000e000 00:00 1312156            /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f6f1762f000-7f6f17630000 rw-p 0000f000 00:00 1312156            /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f6f17630000-7f6f17634000 r-xp 00000000 00:00 1325847            /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so
7f6f17634000-7f6f17636000 ---p 00004000 00:00 1325847            /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so
7f6f17636000-7f6f17833000 ---p 00006000 00:00 1325847            /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so
7f6f17833000-7f6f17834000 r--p 00003000 00:00 1325847            /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so
7f6f17834000-7f6f17835000 rw-p 00004000 00:00 1325847            /usr/lib/python3.5/lib-dynload/_bz2.cpython-35m-x86_64-linux-gnu.so
7f6f17840000-7f6f17841000 rw-p 00000000 00:00 0
7f6f1784c000-7f6f17852000 r--p 00000000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f17852000-7f6f17868000 r-xp 00006000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f17868000-7f6f1786d000 r--p 0001c000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f1786d000-7f6f1786e000 ---p 00021000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f1786e000-7f6f1786f000 r--p 00021000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f1786f000-7f6f17870000 rw-p 00022000 00:00 683698             /home/my_user/.local/lib/python3.5/site-packages/numba/_helperlib.cpython-35m-x86_64-linux-gnu.so
7f6f17870000-7f6f17930000 rw-p 00000000 00:00 0
7f6f17930000-7f6f1793d000 r-xp 00000000 00:00 1325862            /usr/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so
7f6f1793d000-7f6f1793f000 ---p 0000d000 00:00 1325862            /usr/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so
7f6f1793f000-7f6f17b3c000 ---p 0000f000 00:00 1325862            /usr/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so
7f6f17b3c000-7f6f17b3d000 r--p 0000c000 00:00 1325862            /usr/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so
7f6f17b3d000-7f6f17b3e000 rw-p 0000d000 00:00 1325862            /usr/lib/python3.5/lib-dynload/_json.cpython-35m-x86_64-linux-gnu.so
7f6f17b40000-7f6f17cc0000 rw-p 00000000 00:00 0
7f6f17cc0000-7f6f17e55000 r-xp 00000000 00:00 1312577            /lib/x86_64-linux-gnu/libc-2.24.so
7f6f17e55000-7f6f17e5d000 ---p 00195000 00:00 1312577            /lib/x86_64-linux-gnu/libc-2.24.so
7f6f17e5d000-7f6f18055000 ---p 0019d000 00:00 1312577            /lib/x86_64-linux-gnu/libc-2.24.so
7f6f18055000-7f6f18059000 r--p 00195000 00:00 1312577            /lib/x86_64-linux-gnu/libc-2.24.so
7f6f18059000-7f6f1805b000 rw-p 00199000 00:00 1312577            /lib/x86_64-linux-gnu/libc-2.24.so
7f6f1805b000-7f6f1805f000 rw-p 00000000 00:00 0
7f6f18060000-7f6f18163000 r-xp 00000000 00:00 1312582            /lib/x86_64-linux-gnu/libm-2.24.so
7f6f18163000-7f6f18164000 ---p 00103000 00:00 1312582            /lib/x86_64-linux-gnu/libm-2.24.so
7f6f18164000-7f6f18362000 ---p 00104000 00:00 1312582            /lib/x86_64-linux-gnu/libm-2.24.so
7f6f18362000-7f6f18363000 r--p 00102000 00:00 1312582            /lib/x86_64-linux-gnu/libm-2.24.so
7f6f18363000-7f6f18364000 rw-p 00103000 00:00 1312582            /lib/x86_64-linux-gnu/libm-2.24.so
7f6f18370000-7f6f18389000 r-xp 00000000 00:00 1312135            /lib/x86_64-linux-gnu/libz.so.1.2.8
7f6f18389000-7f6f1838a000 ---p 00019000 00:00 1312135            /lib/x86_64-linux-gnu/libz.so.1.2.8
7f6f1838a000-7f6f18588000 ---p 0001a000 00:00 1312135            /lib/x86_64-linux-gnu/libz.so.1.2.8
7f6f18588000-7f6f18589000 r--p 00018000 00:00 1312135            /lib/x86_64-linux-gnu/libz.so.1.2.8
7f6f18589000-7f6f1858a000 rw-p 00019000 00:00 1312135            /lib/x86_64-linux-gnu/libz.so.1.2.8
7f6f18590000-7f6f185b7000 r-xp 00000000 00:00 1323818            /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7f6f185b7000-7f6f185ba000 ---p 00027000 00:00 1323818            /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7f6f185ba000-7f6f187b7000 ---p 0002a000 00:00 1323818            /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7f6f187b7000-7f6f187b9000 r--p 00027000 00:00 1323818            /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7f6f187b9000-7f6f187ba000 rw-p 00029000 00:00 1323818            /lib/x86_64-linux-gnu/libexpat.so.1.6.2
7f6f187c0000-7f6f187c2000 r-xp 00000000 00:00 1312602            /lib/x86_64-linux-gnu/libutil-2.24.so
7f6f187c2000-7f6f187c3000 ---p 00002000 00:00 1312602            /lib/x86_64-linux-gnu/libutil-2.24.so
7f6f187c3000-7f6f189c1000 ---p 00003000 00:00 1312602            /lib/x86_64-linux-gnu/libutil-2.24.so
7f6f189c1000-7f6f189c2000 r--p 00001000 00:00 1312602            /lib/x86_64-linux-gnu/libutil-2.24.so
7f6f189c2000-7f6f189c3000 rw-p 00002000 00:00 1312602            /lib/x86_64-linux-gnu/libutil-2.24.so
7f6f189d0000-7f6f189d3000 r-xp 00000000 00:00 1312580            /lib/x86_64-linux-gnu/libdl-2.24.so
7f6f189d3000-7f6f189d4000 ---p 00003000 00:00 1312580            /lib/x86_64-linux-gnu/libdl-2.24.so
7f6f189d4000-7f6f18bd2000 ---p 00004000 00:00 1312580            /lib/x86_64-linux-gnu/libdl-2.24.so
7f6f18bd2000-7f6f18bd3000 r--p 00002000 00:00 1312580            /lib/x86_64-linux-gnu/libdl-2.24.so
7f6f18bd3000-7f6f18bd4000 rw-p 00003000 00:00 1312580            /lib/x86_64-linux-gnu/libdl-2.24.so
7f6f18be0000-7f6f18bf8000 r-xp 00000000 00:00 1312595            /lib/x86_64-linux-gnu/libpthread-2.24.so
7f6f18bf8000-7f6f18c02000 ---p 00018000 00:00 1312595            /lib/x86_64-linux-gnu/libpthread-2.24.so
7f6f18c02000-7f6f18df7000 ---p 00022000 00:00 1312595            /lib/x86_64-linux-gnu/libpthread-2.24.so
7f6f18df7000-7f6f18df8000 r--p 00017000 00:00 1312595            /lib/x86_64-linux-gnu/libpthread-2.24.so
7f6f18df8000-7f6f18df9000 rw-p 00018000 00:00 1312595            /lib/x86_64-linux-gnu/libpthread-2.24.so
7f6f18df9000-7f6f18dfd000 rw-p 00000000 00:00 0
7f6f18e00000-7f6f18e23000 r-xp 00000000 00:00 1312572            /lib/x86_64-linux-gnu/ld-2.24.so
7f6f18e30000-7f6f18e40000 r-xp 00000000 00:00 0
7f6f18e40000-7f6f18e80000 rw-p 00000000 00:00 0
7f6f18e80000-7f6f18e88000 r-xp 00000000 00:00 0
7f6f18e88000-7f6f19023000 r--p 00000000 00:00 1313728            /usr/lib/locale/locale-archive
7f6f19023000-7f6f19024000 r--p 00023000 00:00 1312572            /lib/x86_64-linux-gnu/ld-2.24.so
7f6f19024000-7f6f19025000 rw-p 00024000 00:00 1312572            /lib/x86_64-linux-gnu/ld-2.24.so
7f6f19025000-7f6f19026000 rw-p 00000000 00:00 0
7f6f19029000-7f6f1902b000 r--p 00000000 00:00 694238             /home/my_user/.local/lib/python3.5/site-packages/numba/npyufunc/_internal.cpython-35m-x86_64-linux-gnu.so
7f6f1902b000-7f6f1902d000 r-xp 00002000 00:00 694238             /home/my_user/.local/lib/python3.5/site-packages/numba/npyufunc/_internal.cpython-35m-x86_64-linux-gnu.so
7f6f1902d000-7f6f1902e000 r--p 00004000 00:00 694238             /home/my_user/.local/lib/python3.5/site-packages/numba/npyufunc/_internal.cpython-35m-x86_64-linux-gnu.so
7f6f1902e000-7f6f1902f000 r--p 00004000 00:00 694238             /home/my_user/.local/lib/python3.5/site-packages/numba/npyufunc/_internal.cpython-35m-x86_64-linux-gnu.so
7f6f1902f000-7f6f19030000 rw-p 00005000 00:00 694238             /home/my_user/.local/lib/python3.5/site-packages/numba/npyufunc/_internal.cpython-35m-x86_64-linux-gnu.so
7f6f19030000-7f6f19031000 rwxp 00000000 00:00 0
7f6f19032000-7f6f19035000 r--p 00000000 00:00 682653             /home/my_user/.local/lib/python3.5/site-packages/numba/_dispatcher.cpython-35m-x86_64-linux-gnu.so
7f6f19035000-7f6f1903c000 r-xp 00003000 00:00 682653             /home/my_user/.local/lib/python3.5/site-packages/numba/_dispatcher.cpython-35m-x86_64-linux-gnu.so
7f6f1903c000-7f6f1903e000 r--p 0000a000 00:00 682653             /home/my_user/.local/lib/python3.5/site-packages/numba/_dispatcher.cpython-35m-x86_64-linux-gnu.so
7f6f1903e000-7f6f1903f000 r--p 0000b000 00:00 682653             /home/my_user/.local/lib/python3.5/site-packages/numba/_dispatcher.cpython-35m-x86_64-linux-gnu.so
7f6f1903f000-7f6f19040000 rw-p 0000c000 00:00 682653             /home/my_user/.local/lib/python3.5/site-packages/numba/_dispatcher.cpython-35m-x86_64-linux-gnu.so
7f6f19040000-7f6f19102000 rw-p 00000000 00:00 0
7f6f19103000-7f6f19104000 r--p 00000000 00:00 693435             /home/my_user/.local/lib/python3.5/site-packages/numba/jitclass/_box.cpython-35m-x86_64-linux-gnu.so
7f6f19104000-7f6f19105000 r-xp 00001000 00:00 693435             /home/my_user/.local/lib/python3.5/site-packages/numba/jitclass/_box.cpython-35m-x86_64-linux-gnu.so
7f6f19105000-7f6f19106000 r--p 00002000 00:00 693435             /home/my_user/.local/lib/python3.5/site-packages/numba/jitclass/_box.cpython-35m-x86_64-linux-gnu.so
7f6f19106000-7f6f19107000 r--p 00002000 00:00 693435             /home/my_user/.local/lib/python3.5/site-packages/numba/jitclass/_box.cpython-35m-x86_64-linux-gnu.so
7f6f19107000-7f6f19108000 rw-p 00003000 00:00 693435             /home/my_user/.local/lib/python3.5/site-packages/numba/jitclass/_box.cpython-35m-x86_64-linux-gnu.so
7f6f19108000-7f6f1910a000 r--p 00000000 00:00 697128             /home/my_user/.local/lib/python3.5/site-packages/numba/runtime/_nrt_python.cpython-35m-x86_64-linux-gnu.so
7f6f1910a000-7f6f1910c000 r-xp 00002000 00:00 697128             /home/my_user/.local/lib/python3.5/site-packages/numba/runtime/_nrt_python.cpython-35m-x86_64-linux-gnu.so
7f6f1910c000-7f6f1910e000 r--p 00004000 00:00 697128             /home/my_user/.local/lib/python3.5/site-packages/numba/runtime/_nrt_python.cpython-35m-x86_64-linux-gnu.so
7f6f1910e000-7f6f1910f000 r--p 00005000 00:00 697128             /home/my_user/.local/lib/python3.5/site-packages/numba/runtime/_nrt_python.cpython-35m-x86_64-linux-gnu.so
7f6f1910f000-7f6f19110000 rw-p 00006000 00:00 697128             /home/my_user/.local/lib/python3.5/site-packages/numba/runtime/_nrt_python.cpython-35m-x86_64-linux-gnu.so
7f6f19110000-7f6f19112000 rw-p 00000000 00:00 0
7f6f19112000-7f6f19114000 r--p 00000000 00:00 699165             /home/my_user/.local/lib/python3.5/site-packages/numba/typeconv/_typeconv.cpython-35m-x86_64-linux-gnu.so
7f6f19114000-7f6f19116000 r-xp 00002000 00:00 699165             /home/my_user/.local/lib/python3.5/site-packages/numba/typeconv/_typeconv.cpython-35m-x86_64-linux-gnu.so
7f6f19116000-7f6f19117000 r--p 00004000 00:00 699165             /home/my_user/.local/lib/python3.5/site-packages/numba/typeconv/_typeconv.cpython-35m-x86_64-linux-gnu.so
7f6f19117000-7f6f19118000 r--p 00004000 00:00 699165             /home/my_user/.local/lib/python3.5/site-packages/numba/typeconv/_typeconv.cpython-35m-x86_64-linux-gnu.so
7f6f19118000-7f6f19119000 rw-p 00005000 00:00 699165             /home/my_user/.local/lib/python3.5/site-packages/numba/typeconv/_typeconv.cpython-35m-x86_64-linux-gnu.so
7f6f19119000-7f6f19120000 r--s 00000000 00:00 1312908            /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f6f19120000-7f6f19122000 rw-p 00000000 00:00 0
7f6f19122000-7f6f19123000 rw-s 00000000 00:00 553109             /run/shm/I008sb (deleted)
7f6f19123000-7f6f19124000 r--p 00000000 00:00 683183             /home/my_user/.local/lib/python3.5/site-packages/numba/_dynfunc.cpython-35m-x86_64-linux-gnu.so7f6f19124000-7f6f19125000 r-xp 00001000 00:00 683183             /home/my_user/.local/lib/python3.5/site-packages/numba/_dynfunc.cpython-35m-x86_64-linux-gnu.so7f6f19125000-7f6f19126000 r--p 00002000 00:00 683183             /home/my_user/.local/lib/python3.5/site-packages/numba/_dynfunc.cpython-35m-x86_64-linux-gnu.so7f6f19126000-7f6f19127000 r--p 00002000 00:00 683183             /home/my_user/.local/lib/python3.5/site-packages/numba/_dynfunc.cpython-35m-x86_64-linux-gnu.so7f6f19127000-7f6f19128000 rw-p 00003000 00:00 683183             /home/my_user/.local/lib/python3.5/site-packages/numba/_dynfunc.cpython-35m-x86_64-linux-gnu.so7f6f19200000-7f6f195f0000 r-xp 00000000 00:00 1325508            /usr/bin/python3.5
7f6f197ef000-7f6f197f1000 r--p 003ef000 00:00 1325508            /usr/bin/python3.5
7f6f197f1000-7f6f19888000 rw-p 003f1000 00:00 1325508            /usr/bin/python3.5
7f6f19888000-7f6f198b9000 rw-p 00000000 00:00 0
7fffcc279000-7fffd2f3b000 rw-p 00000000 00:00 0                  [heap]
7fffd2f40000-7fffd3740000 rw-p 00000000 00:00 0                  [stack]
7fffd3eb8000-7fffd3eb9000 r-xp 00000000 00:00 0                  [vdso]

**Comment by saltypeanuts** [comment]
If it helps, I get these warnings when running without numba (divide by 0 => np.inf / np.nans):

/home/my_user/.local/lib/python3.5/site-packages/ipykernel_launcher.py:765: RuntimeWarning: divide by zero encountered in arctanh
/home/my_user/.local/lib/python3.5/site-packages/ipykernel_launcher.py:764: RuntimeWarning: invalid value encountered in double_scalars

**Comment by esc** [comment]
@saltypeanuts thanks for reporting this and for using Numba. You are the first user I have heard of who is using Numba on WSL, so congratulations! 😄 Having said that, we don't have a Windows 10 box that would allow us to debug this locally right now, so I encourage you to continue prodding at this issue and report back any new evidence that may surface.

**Comment by seibert** [comment]
We're going to try to reproduce this in a Windows 10 VM.

**Comment by seibert** [comment]
Can you post the output of `numba -s` so we can recreate your exact environment?

**Comment by saltypeanuts** [comment]
> 
> 
> Can you post the output of `numba -s` so we can recreate your exact environment?
```
my_usert@comp:~$ numba -s
-bash: numba: command not found
```
On an unrelated note there's some inconsistencies between the numba on Windows and WSL:
```
max_high = max((array[i-fixed_val:i]))```

Works on WSL but errors on window

**Comment by saltypeanuts** [comment]
> 
> 
> Can you post the output of `numba -s` so we can recreate your exact environment?

user@my_comp:~$ pip3 install numba
Collecting numba
  Downloading https://files.pythonhosted.org/packages/84/8e/18e74153e6bddda68a6ff9382b9d347d5da8599ea2326b34ded099df5216/numba-0.44.1-cp35-cp35m-manylinux1_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 348kB/s
Collecting numpy (from numba)
  Using cached https://files.pythonhosted.org/packages/bb/ef/d5a21cbc094d3f4d5b5336494dbcc9550b70c766a8345513c7c24ed18418/numpy-1.16.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting llvmlite>=0.29.0 (from numba)
  Using cached https://files.pythonhosted.org/packages/fc/8c/6412b14976f90d703279b5cd53c6f036e4e1fda434007f305e8a1e103d06/llvmlite-0.29.0-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: numpy, llvmlite, numba

**Comment by saltypeanuts** [comment]
```import numba
print(numba.__version__)```
0.44.1

**Comment by saltypeanuts** [comment]
Not sure how helpful this is, but on a known clean data set (35k instances) I'm not having any issues. When I run on a big dataset (~1.5m instances), I'm getting dropped. Memory limits seem to be fine (I'm not going over ~3 gb on a 16 gb machine).

I relied heavily on numpy's handling of dirty data (e.g. np.infs, np.nans, and the creation of such when using the data). This might the area where issues are being caused.

**Comment by saltypeanuts** [comment]
Here's another jit loop that's erroring out. I'm pretty certain it's due to error handling. Trying to isolate exactly where so I can upload data.
```def jit_loop(array, fixed_val):
    out = np.zeros(len(array))
        for i in (fixed_val, len(array)):
            if(i%100 == 0):
                print(i)
                
            data = array[i-fixed_val+1:i+1]
            mean_val = np.mean(data)
            diff = 0
            for j in range(len(data)):
                diff = diff + np.abs(data[j]-mean_val)
            out[i] = diff/mean_val
        return out
```

**Comment by saltypeanuts** [comment]
This code has an error right here:

 for i in (fixed_val, len(array)):

should be

 for i in range(fixed_val, len(array)):

It errors correctly on its own, but when it's wrapped inside another function(s) (trying that out right now, it's 3 layers deep in functions and I'm trying not to drop 2000+ lines of code) that kills the kernel without erroring.
 ```
@jit(nopython = True)
def jit_loop(array, fixed_val):
    out = np.zeros(len(array))
        for i in (fixed_val, len(array)):
            if(i%100 == 0):
                print(i)
                
            data = array[i-fixed_val+1:i+1]
            mean_val = np.mean(data)
            diff = 0
            for j in range(len(data)):
                diff = diff + np.abs(data[j]-mean_val)
            out[i] = diff/mean_val
        return out
```

Current iteration of testing:
```def error_test(test_array):
    test_array = test_array + 1
    
    def error_test_2(test_array):
        a = 1+test_array
        
        @jit(nopython = True)
        def jit_loop(array, fixed_val):
            out = np.zeros(len(array))
            for i in (fixed_val, len(array)):
                if(i%100 == 0):
                    print(i)

                data = array[i-fixed_val+1:i+1]
                mean_val = np.mean(data)
                diff = 0
                for j in range(len(data)):
                    diff = diff + np.abs(data[j]-mean_val)
                out[i] = diff/mean_val
            print(out)
            return out
        
        out = jit_loop(a, fixed_val = 14)
        print(out)
        return out
    
    out = error_test_2(test_array)
    print(out)
    return out
test = error_test(test_array)
print(test)```

Is not killing the kernel

**Comment by seibert** [comment]
Thanks for doing so much detailed debugging!  My suspicion is that something in the error handling or NaN-related behavior is off in this special build of Debian running under Windows.  I will see if we can get a VM running here that the Numba devs can dive into.

Regarding the `numba -s` command, that is usually installed into the path when a virtualenv or conda environment is active.  Not sure what is supposed to happen when a package is installed into .local.

**Comment by saltypeanuts** [comment]
> 
> 
> Thanks for doing so much detailed debugging! My suspicion is that something in the error handling or NaN-related behavior is off in this special build of Debian running under Windows. I will see if we can get a VM running here that the Numba devs can dive into.
> 
> Regarding the `numba -s` command, that is usually installed into the path when a virtualenv or conda environment is active. Not sure what is supposed to happen when a package is installed into .local.

I probably don't have everything set up correctly and that may be causing issues as well. Let me know what you need from me and I'm happy to get it for you.

**Comment by seibert** [comment]
After some looking, I think you will find the command in `~/.local/bin/numba` on your system.

**Comment by saltypeanuts** [comment]
> 
> 
> After some looking, I think you will find the command in `~/.local/bin/numba` on your system.

user@my_comp:~$ ~/.local/bin/numba -s
System info:
--------------------------------------------------------------------------------
__Time Stamp__
2019-07-01 18:14:18.029234

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : bdver2
Number of accessible CPU cores                : 1
Listed accessible CPUs cores                  : 0
CFS restrictions                              : Information not available
CPU Features                                  :
64bit aes avx bmi cmov cx16 f16c fma fma4 lwp lzcnt mmx pclmul popcnt prfchw
sahf sse sse2 sse3 sse4.1 sse4.2 sse4a ssse3 tbm xop xsave

__OS Information__
Platform                                      : Linux-4.4.0-43-Microsoft-x86_64-with-debian-9.9
Release                                       : 4.4.0-43-Microsoft
System Name                                   : Linux
Version                                       : #1-Microsoft Wed Dec 31 14:42:53 PST 2014
OS specific info                              : debian9.9
glibc info                                    : glibc 2.9

__Python Information__
Python Compiler                               : GCC 6.3.0 20170516
Python Implementation                         : CPython
Python Version                                : 3.5.3
Python Locale                                 : en_US UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
CUDA driver library cannot be found or no CUDA enabled devices are present.
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
Conda not present/not working.
Error was [Errno 2] No such file or directory: 'conda'

--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
============================================================

**Comment by saltypeanuts** [comment]
This might be just a Windows 10 issue as well?

Numba seems to be a bit unstable and kills my kernel consistently (but not every time) when running through feature creation process on Windows 10, numba version 0.43.1, using a dirty dataset. It doesn't die in the same place each time, but it's always somewhere reliant on numpy handling of divide by 0 errors (e.g. creating np.inf / np.nan and expecting numpy math to carry the inf/nan through the rest of the process correctly).

I'm going to boot up a pure Debian instance later and see if the kernel also dies there.

**Comment by saltypeanuts** [comment]
A bit more trouble shooting:

Current workflow looks like:
```

#import stuff
#define functions
def create_features():
    #load base from db
    df['1'] = fn_1(stuff)
    df['2'] = fn_2(stuff)
    ...
    df['n'] = fn_n(stuff)
    return df

```

This kills the kernel on random fn's that are numba enabled. I tried running through 20 times with a 100% kernel kill rate

Now when this is unwrapped and is just called by:
```
#import stuff
#define functions

#load base from db
df['1'] = fn_1(stuff)
df['2] = fn_2(stuff)
...
df['n'] = fn_n(stuff)
print(data_frame)
```

It's run successfully 2 times out of 7.

**Comment by saltypeanuts** [comment]
Another simplified jit loop that has caused crashes while wrapped:


```
@jit(nopython = True)
def test_loop(array1, array2):
    out = np.zeros(len(array1))
    for i in range(1, len(array1)):
        out[i] = (array1[i] - array2[i]) / (array1[i-1] - array2[i-1])
    return out
```

**Comment by saltypeanuts** [comment]
Figured out what's happening, but I can't reproduce it.

The dead kernel is being caused by an out of bounds loop that isn't correctly erroring out.

```
series = pd.Series([0,1,2,3,4,5,6])
def first_test_loop(series):
    series = second_test_loop(series.values)
    return series

@jit(nopython = True)        
def second_test_loop(array):      
    for i in range(0, len(array)+1):
        array[i] = 5*array[i]
    return(array)
        
series = first_test_loop(series)
```
Incorrectly returns: [ 0  5 10 15 20 25 30]

When it should error out

```
series = pd.Series([0,1,2,3,4,5,6])
array = series.values
out = second_test_loop(array)
print(out)

```

Incorrectly returns: [ 0  5 10 15 20 25 30]

When it should error out

```
series = pd.Series([0,1,2,3,4,5,6])

array = series.values

for i in range(0, len(array)+1):
    array[i] = 5*array[i]

```

Correctly returns:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-40430a2cf7a4> in <module>
      4 
      5 for i in range(0, len(array)+1):
----> 6     array[i] = 5*array[i]

IndexError: index 7 is out of bounds for axis 0 with size 7


```

I think somewhere with the nesting it kills the kernel (maybe something to do with memory or size?)

**Comment by gmarkall** [comment]
Closing this as it seems the original issue is resolved and there has been no further followup.

**Comment by stuartarchibald** [comment]
> Closing this as it seems the original issue is resolved and there has been no further followup.

Closing!
