### ISSUE TITLE
Numpy aggregate function shims and np.sort()

### ISSUE THREAD

**Issue by greenstick** [numba/numba#4248]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I've been experimenting with writing shims for numpy aggregation functions (e.g. `np.max()`, `np.min()`, etc.) that allow for the `axis` kwdarg, which Numba currently doesn't support (version 0.44.1). 

To do this, I went through the [Numpy Supported](https://numba.pydata.org/numba-doc/latest/reference/numpysupported.html) and [Python Supported](https://numba.pydata.org/numba-doc/latest/reference/pysupported.html) documentation to devise some shims that work for limited values of the `axis` kwdarg. For example:

```
import numpy as np
import numba

@numba.jit(nopython = True)
def npmin (X, axis = -1):
    """
    Shim for broadcastable np.min(). 
    Allows np.min(array), np.min(array, axis = 0), and np.min(array, axis = 1)
    Note that the argument axis = -1 computes on the entire array.
    """
    if axis == 0:
        _min = np.sort(X.transpose())[:,0]
    elif axis == 1:
        _min = np.sort(X)[:,0]
    else:
        _min = np.sort(np.sort(X)[:,0])[0]
    return _min

if __name__ == "__main__":
    a = np.array([[ 0,  1,  2,  3,  4], [-2, -4, -3, -1,  0]])
    _min = npmin(a, axis = 1)
else:
    pass
```

The above function recapitulates the functionality and output of `np.min()` for 2D arrays, however, once I throw Numba into the mix I get the following error:

```
Traceback (most recent call last):
  File "shims.py", line 81, in <module>
    _min = npmin(a)
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 348, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/usr/local/lib/python3.7/site-packages/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)
  File "/usr/local/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function sort at 0x10abd5ea0>) with argument(s) of type(s): (array(int64, 2d, F))
 * parameterized
In definition 0:
    All templates rejected
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function sort at 0x10abd5ea0>)
[2] During: typing of call at shims.py (27)


File "shims.py", line 27:
def npmin (X, axis = -1):
    <source elided>
    if axis == 0:
        _min = np.sort(X.transpose())[:,0]
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

```

I'm aware that this may just be a problem with my reading of the documentation, however, if that's not the case, it seems this may come down to a typing issue (despite Numba flagging my call to `np.sort()`. I've opened a question up on [StackOverflow](https://stackoverflow.com/questions/56827566/numba-aggregate-function-shims-typing-and-np-sort), but I thought it would be good to flag this as a potential issue – specifically, that `np.sort()` may not be working on all `numpy.array`  instances. In addition, any guidance on whether creating such shims is possible would be much appreciated.

**Comment by synapticarbors** [comment]
This is not a bug per-se, but it appears as if numba-izing `np.sort` only works on arrays with `ndim == 1`. I think this is the relevant bit of source code:

https://github.com/numba/numba/blob/92dbdb90e34402f99d158c035f5a1806378161d3/numba/typing/npydecl.py#L692-L700

As I posted over on [StackOverflow](https://stackoverflow.com/a/56874730/392949), here's an alternative shim for 2d arrays:

```python
@numba.jit(nopython=True)
def npmin2(X, axis=0):
    if axis == 0:
        _min = np.empty(X.shape[1])
        for i in range(X.shape[1]):
            _min[i] = np.min(X[:,i])
    elif axis == 1:
        _min = np.empty(X.shape[0])
        for i in range(X.shape[0]):
            _min[i] = np.min(X[i,:])

    return _min
```

although you'll have to figure out a workaround for the `axis=-1` case, because that's going to return a scalar, and the other arguments will return arrays and Numba will not be able to "unify" the return type into something consistent.

The performance, on my machine at least, seems to be roughly comparable to just calling the equivalent np.min, with sometimes `np.min` being faster and other times `npmin2` winning out, depending on the input array size and axis. You can also parallelize this, and I see a nice speed-up:

```python
from numba import prange

@numba.jit(nopython=True, parallel=True)
def npmin2p(X, axis=0):
    if axis == 0:
        _min = np.empty(X.shape[1])
        for i in prange(X.shape[1]):
            _min[i] = np.min(X[:,i])
    elif axis == 1:
        _min = np.empty(X.shape[0])
        for i in prange(X.shape[0]):
            _min[i] = np.min(X[i,:])
    
    return _min
```

**Comment by greenstick** [comment]
Thanks so much for this! Saw and accepted your answer on StackOverflow. I have some questions, but I'll dig into the code base and open issues, as I suspect the answers are already there.

**Comment by ucasiggcas** [comment]
hi,could you pls see my problem,
thx
https://github.com/numba/numba/issues/6285
