### ISSUE TITLE
Typing behavior with Integer and IntegerLiteral

### ISSUE THREAD

**Issue by funkindy** [numba/numba#4265]
I am trying to convert 1d numpy array of integers to tuple to use it a set operations.
I am using to_fixed_tuple function but i cant pass a length to it properly:
import numpy as np

```python
import numba
from numba.unsafe.ndarray import to_fixed_tuple

arr = np.array([1, 2, 3, 4, 5])
arr_length = len(arr)

@numba.njit
def foo(arr):
    l = 5
    return to_fixed_tuple(arr, l)


@numba.njit
def bar(arr):
    l = len(arr)
    return to_fixed_tuple(arr, l)


@numba.njit
def baz(arr, l):
    return to_fixed_tuple(arr, l)


foo(arr) # works okay
bar(arr) # RequireLiteralValue: *length* argument must be a constant
baz(arr, 5) # RequireLiteralValue: *length* argument must be a constant
```

Seems like in `bar `and `baz ` the second argument of `to_fixed_tuple` becomes Integer and not IntegerLiteral. If this behavior is expected, can i somehow cast the length to needed type inside jitted function?

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue here is that Numba in general specialises based on type information only, there are however a few "Literal*" types which can be resolved as constant values in the case that they are actually constant. Taking your examples:

```python
@numba.njit
def foo(arr):
    l = 5 # <---------- this is a compile time constant, it cannot be altered
    return to_fixed_tuple(arr, l)
```

```python
@numba.njit
def bar(arr):
    l = len(arr) # <---- this is not a compile time constant, `arr` is passed in to
                 #       the function, different `arr`'s would created different
                 #       values for `l`
    return to_fixed_tuple(arr, l)
```

```python
@numba.njit
def baz(arr, l):
    return to_fixed_tuple(arr, l) # <--- l is an argument and is from a variable,
                                  # it is not a compile time constant.
```


Does this help with your use case:
```python
import numba
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

@numba.njit
def foo(arr1, arr2):
    s1 = set([_ for _ in arr1])
    s2 = set([_ for _ in arr2])
    return s1 & s2

print(foo(a, b))
```

**Comment by funkindy** [comment]
@stuartarchibald thanks for clarifications, unfortunately the last snippet doesnt help me.

I am asking the question because i am solving a very common(from my p.o.v.) problem: i generate 1d-arrays continuously and i want to check if a new one already exists in a collection. So i just want to create some hashable analog of array (tuple in my case) to check if is already in a set (this check is quite fast). At first ive tried more simple solutions to convert array to tuple, but they dont work also https://stackoverflow.com/questions/56846678/numba-converting-numpy-array-into-hashable-object

So i thought that to_fixed_tuple has to solve it but seems like there is no way to use input array length in it.

**Comment by stuartarchibald** [comment]
Are the arrays always the same length?

**Comment by funkindy** [comment]
No, unfortunately.

**Comment by stuartarchibald** [comment]
How much variation is there?

**Comment by funkindy** [comment]
Lengths are about 10 to 70, i can manually put maximum length to_fixed_tuple, but for lower lengths it will produce some "random" numbers on positions from len to max_len:
![image](https://user-images.githubusercontent.com/17568549/60716568-30ab5d80-9f39-11e9-9841-9c87123836f8.png)

I wonder if those numbers are always the same on the same kernel session/machine etc.

**Comment by stuartarchibald** [comment]
I suspect those values are just from interpreting uninitialized memory. Not ideal, but does this do what you want ?
```python
import numpy as np
import numba as nb
from numba import types
from numba.unsafe.tuple import tuple_setitem
from numba.extending import intrinsic
from numba import typing

@intrinsic
def to_fixed_tuple(typingctx, array, length):
    """Convert *array* into a tuple of *length*

    Returns ``UniTuple(array.dtype, length)``

    ** Warning **
    - No boundschecking.
      If *length* is longer than *array.size*, the behaviour is undefined.
    """
    if not isinstance(length, types.IntegerLiteral):
        raise RequireLiteralValue('*length* argument must be a constant')

    if array.ndim != 1:
        raise TypingError("Not supported on array.ndim={}".format(array.ndim))

    # Determine types
    tuple_size = int(length.literal_value)
    tuple_type = types.UniTuple(dtype=array.dtype, count=tuple_size)
    sig = tuple_type(array, length)

    def codegen(context, builder, signature, args):
        def impl(array, length, empty_tuple):
            out = empty_tuple
            l = len(array)
            for i in range(l):
                out = tuple_setitem(out, i, array[i])
            for i in range(l, length):
                out = tuple_setitem(out, i, 0)
            return out

        inner_argtypes = [signature.args[0], types.intp, tuple_type]
        inner_sig = typing.signature(tuple_type, *inner_argtypes)
        ll_idx_type = context.get_value_type(types.intp)
        # Allocate an empty tuple
        empty_tuple = context.get_constant_undef(tuple_type)
        inner_args = [args[0], ll_idx_type(tuple_size), empty_tuple]

        res = context.compile_internal(builder, impl, inner_sig, inner_args)
        return res

    return sig, codegen

LEN_MAX = 15

@nb.jit(nopython=True)
def foo(n):

    uniques = []
    uniques_set = set()

    def make_hashable(arr):
        return to_fixed_tuple(arr, LEN_MAX)

    for _ in range(n):

        arr = np.random.randint(0, 3, _ % 3)
        arr_hashable = make_hashable(arr)

        if arr_hashable in uniques_set:
            pass
        else:
            uniques_set.add(arr_hashable)
            uniques.append(arr)

    return uniques

print(foo(1000))
```

**Comment by funkindy** [comment]
Yes, it does! Thank you so much!

**Comment by stuartarchibald** [comment]
No problem. Unfortunately mixing dynamic things (array lengths) with immutable things (tuples) when the compilation path is type based and static is always a challenge.
