### ISSUE TITLE
Add numba.cuda.jit examples

### ISSUE THREAD

**Issue by mrocklin** [numba/numba#4266]
I'm sitting with a group of people and we started talking about numba.cuda.jit. I turned a recent blogpost into a Google Colab notebook, and it seems to be somewhat effective in getting people started.  https://gist.github.com/mrocklin/cdb99419552bd8df2f2bea2adfd6231f

However, they don't know how to extend this, except with other stencil operations (my example is a stencil computation).  I think that if they had a few examples for reductions, matmul ([which we have already](https://numba.pydata.org/numba-doc/dev/cuda/examples.html#examples)), elementwise, and so on, then they would be able to pull from those and generalize a bit.  

So concretely, I'd love to see an expansion of the numba.cuda.jit examples documentation.  Secondarily I'd love to see this in notebook form that could run on Colab (or some other GPU-cloud service).

**Comment by mrocklin** [comment]
cc @stuartarchibald (who I think will be interacting with this same group tomorrow)

**Comment by stuartarchibald** [comment]
Does the GTC tutorial series help: https://github.com/ContinuumIO/gtc2019-numba ?

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/4288

**Comment by gmarkall** [comment]
Potentially useful examples:

- [ ] Use of `@jit` function from both CPU- and GPU-jitted functions
- [ ] CuPy / Numba interop examples
- [ ] Transcribe / translate appropriate examples from CUDA release notebooks: https://github.com/numba/numba-examples/tree/master/notebooks

**Comment by quasiben** [comment]
@seanlaw do you have an thoughts on good examples of using numba GPU kernels ?

**Comment by seanlaw** [comment]
@quasiben I don't have any particularly good examples that are easily approachable but, from my limited experience, I've found that the biggest challenge/barrier to entry for users is being able identify appropriate SIMD scenarios to fit the GPU programming paradigm. It almost feels like there are some basic patterns that the user needs to get exposed to first and then, later, be able to recognize it as a chunk of CPU code that would be great on a GPU.

**Comment by brandon-b-miller** [comment]
I'm working on this and should have a PR shortly if thats ok :)

**Comment by sklam** [comment]
Please note that examples should now go into https://github.com/numba/numba-examples.
