### ISSUE TITLE
Recommended workaround to reflected list in a function using prange ?

### ISSUE THREAD

**Issue by NicolasHug** [numba/numba#4276]
I have an `njit` function that accepts a list as parameter. I'm getting the "reflected list" deprecation warning.

Since I don't mutate the list, an easy workaround would be to convert the list into a tuple. But tuple arguments conflict with `prange` (https://github.com/numba/numba/issues/2625), which I'm using too.

What is the recommended workaround?

Thanks!

**Comment by esc** [comment]
@NicolasHug thank you for your question, we appreciate your interest in Numba. We are currently working on a replacement for the reflected-list called a *typed-list*. The PR is still in flight and should both hit master soon and become available as an experimental feature during the next release. The reflected list will however continue to work for at least another release cycle so you will be safe for a while.

**Comment by esc** [comment]
The `numba.typed.List` has been around for a while now and is documented at:

https://numba.readthedocs.io/en/stable/reference/pysupported.html#list

Unfortunately, it still suffers from some performance issues which we are working on. As a result, the reflected list still exists as a fallback. You could try to switch to the typed-list and check if it suffers  from performance issues compared to the reflected list for your use case too.
