### ISSUE TITLE
Should Numba check consistency of cudatoolkit and CUDA driver?

### ISSUE THREAD

**Issue by seibert** [numba/numba#4285]
It will take some time before we can rely on conda to consistently match the `cudatoolkit` package with the CUDA supported by the system driver.  While conda 4.6.? can now detect CUDA driver version, the `cudatoolkit` package hasn't yet been changed to rely on it while the team decides how to make sure everything is backward compatible with older conda versions.

In light of that, and user issues like:

https://github.com/numba/numba/issues/2688#issuecomment-509232503

Is there a way that Numba could detect that the cudatoolkit conda package doesn't match the driver version and give the user guidance on how to match them?

**Comment by stuartarchibald** [comment]
@seibert can this now be closed?

**Comment by seibert** [comment]
Let's close this for now.
