### ISSUE TITLE
Define a standard way to provide overloads for a module

### ISSUE THREAD

**Issue by person142** [numba/numba#4292]
Moved from Gitter:

https://gitter.im/numba/numba?at=5d2397ad0c8daa1686ac4c00

Suppose there's a package `foo`, and I write some `@overload`s for `foo` in a separate package called `foo_overloads`. I'm currently telling Numba about those overloads by doing something like

```python
import numba
import foo
import foo_overloads  # Apply the overloads at import time

@numba.njit
def bar():
    x = foo.baz()
    # Etc.
```

This feels funny because the `foo_overloads` import is being used purely for side effects. You could also do something explicit like

```python
import foo_overloads
foo_overloads.generate_overloads()
```

but that feels awkward.

So the feature request is: could there be a standard way to define overloads so that after installing `foo_overloads` the following would just work?

```python
import numba
import foo

@numba.njit
def bar():
    x = foo.baz()
    # Etc.
```

One could imagine having a config file somewhere that Numba reads from to pull in a bunch of overloads defined by third-party packages.

**Comment by stuartarchibald** [comment]
Thanks for writing this up as discussed @person142, much appreciated. Numba already has a way to configure internal things via a YAML file so perhaps this could be extended, http://numba.pydata.org/numba-doc/dev/reference/envvars.html#environment-variables ?

A side issue to this is also what if two extension modules decide to overload the same function/other name space collision type stuff. For core packages like SciPy extensions the, not existing anywhere other than in bits and pieces on various computers, but much talked about, "scumba" (SciPy+Numba) project would perhaps be the place to organise this.

**Comment by person142** [comment]
> "scumba" (SciPy+Numba) project would perhaps be the place to organise this.

Perhaps the time for scumba is now? I'd be happy to start doing the legwork.

**Comment by stuartarchibald** [comment]
> > "scumba" (SciPy+Numba) project would perhaps be the place to organise this.
> 
> Perhaps the time for scumba is now? I'd be happy to start doing the legwork.

After a very quick discussion on this with @seibert, how does this sound:

1. The Numba core devs are just in the middle of a cutting a release right now so are pretty busy with that, but as soon as it is done and we hit the next dev cycle (0.46.0) "scumba" will start, practically this will be in a week or so.
2. The Numba org will host the repo for "scumba".
3. The Numba core devs will throw in some time as appropriate to write the really low level stuff to get the key parts of various bits of SciPy accepted by Numba (consider for example a CSR matrix crossing the CPython->machine code barrier).
4. The rest is to be largely community driven.


Points 3. & 4. are open to expansion and discussion. We cannot alter 1. we have to get 0.45.0 out the door :) and 2. seems to make sense on a number of levels,it  also makes it easy to push stuff through the Numba build farm. 

>  I'd be happy to start doing the legwork.

As you are someone who has helped drive this, contributed to Numba, and clearly has an interest in such a project existing, your code, help, views, and expertise would be most appreciated. Thanks!

**Comment by person142** [comment]
> how does this sound

Generally speaking, sounds good.

Sort of related to 3-I’d hope that as things develop we’d continue to find a better compatibility story. For example, if things like `cython_special` make special functions in Numba easy, then I’d like to think about how we can do more of that.

**Comment by stuartarchibald** [comment]
@person142 thanks, great to have you on board :)

> Sort of related to 3-I’d hope that as things develop we’d continue to find a better compatibility story. For example, if things like `cython_special` make special functions in Numba easy, then I’d like to think about how we can do more of that.

This is an excellent point, at present Numba also relies on SciPy's cython linalg exports to get pointers to BLAS and LAPACK functions. I could envisage it becoming a necessity in the future to bind to other optimised numerical libraries where writing equivalent functionality in Numba would be inefficient and impractical. Having a route to expose these, even if it means keeping in sync more with SciPy, would be incredibly helpful.

**Comment by stuartarchibald** [comment]
Just pinging a few other regular contributors/persons who may be interested in what this ticket has sprung into to increase awareness/gather opinion... 
CC: @rjenc29 @synapticarbors @luk-f-a

**Comment by luk-f-a** [comment]
@stuartarchibald , thanks for pinging.
this sounds great. I've needed distributions support before, and used rvlib to get around the problem.
I've also needed a sparse matrix, and I don't think there's any workaround for that (besides creating it myself which I did for my limited use case).
If I understand it well, the goal of scumba would be to expose SciPy functionality that is in C, to Numba. What about the functionality that is in pure Python? I shudder at the thought of creating hundreds of `@overloads` for SciPy functions. 
If there would be a chance to get buy-in from the SciPy team to make their functions jit-friendly, together with recursive jitting (#2634) we could avoid lots of `overloads` without having to actually add Numba as a SciPy dependency.

**Comment by person142** [comment]
> If there would be a chance to get buy-in from the SciPy team to make their functions jit-friendly

(Note: just speaking for myself here, not any of the other SciPy core devs.) I think that’s going to be a tough sell because it effectively makes implementation details part of the SciPy API (which then greatly increases the surface area of the API).

To take a concrete example, consider this PR:

https://github.com/scipy/scipy/pull/10170

It takes a currently jit-friendly cdf  and makes it a non-jit friendly ufunc but greatly increases accuracy. We’re always going to want to reserve the right to make changes like that.

Something that I think might be better received is encouraging SciPy to expose more C-level APIs (like the Lapack and special function ones). They don’t expose as much API surface area and are more broadly useful. A tiny bit of discussion of that on the stats side can be found here:

https://github.com/scipy/scipy/pull/10281

**Comment by seibert** [comment]
Yeah, I agree that it is hard to make functions which achieve the best performance in both Numba and Python/NumPy at the same time (we always strive to compress that Venn diagram, but it will never be perfect).

Being able to call down into the underlying C implementation (when such a thing exists) would be very helpful for us.  We want to reimplement simple operations so that LLVM can inline them, but complex algorithms don't benefit from being in Numba/Python vs. C.

We struggle with this when working with CPython as well.  Numba now has a copy of CPython's unicode database because we could not find any reasonable way to access the underlying C structs (even doing slightly dangerous things).  Anything that lets us avoid repeating other's work is great.

**Comment by luk-f-a** [comment]
@person142, I see your point. 

I am wondering what a reasonable goal for scumba could be. If I understand the discussion so far, the first step is to find a way to access the existing C implementations. Is this right?

what about all the functions and classes that are currently in pure python? Out of scope? Or second step?

**Comment by stuartarchibald** [comment]
> I am wondering what a reasonable goal for scumba could be. If I understand the discussion so far, the first step is to find a way to access the existing C implementations. Is this right?

I think it's best to just lean on well known libraries where possible, and if these are not exposed and SciPy could provide a binding/consistent interface for accessing them, then that's great and a good place to spend effort. I think the goal for scumba is to provide the ability to be able to use parts of SciPy from within Numba compiled code, it'll be a small part at first by necessity. This is not dissimilar to Numba making it possible to use NumPy in compiled code and the amount of NumPy supported has slowly grown with time.

> what about all the functions and classes that are currently in pure python? Out of scope? Or second step?

There is likely to be some element of translation required here. I would anticipate the first tranche of effort on this project would be to explore a couple of limited scope areas, to work out the sort of things that go well, which tasks can be more easily tackled, which are more difficult and also those which will require low level alterations/code gen effort in Numba itself.

To this effect I propose exploring the `scipy.special` functions as `ufunc`s and probably `scipy.sparse`  perhaps concentrating on CSR as it's very commonly used and the patterns established would likely be readily extended to other sparse formats. I'm aware that there are some users interested in `scipy.stats` too, other suggestions are welcomed!

**Comment by person142** [comment]
`scipy.sparse` is an interesting case because there are hopes that it will be replaced with

https://github.com/pydata/sparse

at some point, and it already uses Numba (not sure of the details though). So we should be careful because the ground might shift under us.

**Comment by luk-f-a** [comment]
@stuartarchibald , I agree that `sparse` is a very important area to explore.

@person142, regarding pydata/sparse I wonder how much they plan to jit, because I could see a situation where performance-critical functions are jitted but unless the entire object is jitted (via `jitclass`) then it cannot be used within Numba.

Out of my personal use cases (ML, statistics and finance), I would say that stats support would be nice to have. I could definitely contribute here.

**Comment by matthewfeickert** [comment]
Given discussions at SciPy 2019 I'm just commenting here to say that this would also be helpful for `pyhf`, so I'll be following this for future developments.

**Comment by stuartarchibald** [comment]
For anyone watching this ticket for "scumba". Project is at https://github.com/numba/scumba. Infrastructure buildout is in progress, hope to start accepting PRs soon.

**Comment by person142** [comment]
> hope to start accepting PRs soon

Let me know when you do, I can make a PR with a port of the `numba_special` code.

**Comment by stuartarchibald** [comment]
Update:

We (numba core devs) figured there's potentially a bunch of Numba extension projects possible so have elected to copy a naming scheme similar to that used by `dask` and its subprojects.

Github URL: https://github.com/numba/numba-scipy
PyPI: https://pypi.org/project/numba-scipy/

**Comment by stuartarchibald** [comment]
Update:

`numba-scipy` is now accepting PRs!

**Comment by stuartarchibald** [comment]
I also think this feature http://numba.pydata.org/numba-doc/latest/extending/entrypoints.html answers the original issue on the ticket. Am closing this, feel free to reopen as needed.
