### ISSUE TITLE
Add inspect_types (etc) docstrings

### ISSUE THREAD

**Issue by jni** [numba/numba#4306]
## Feature request

When I use tab-completion to explore my jit-compiled functions, I see `inspect_*` methods that are actually super useful. However, if I want to see a description of what they do, I need to go online [here](http://numba.pydata.org/numba-doc/0.18.1/reference/compilation.html). Doing `inspect_asm?` in IPython yields `<no docstring>`. It would be great if the methods contained these docstrings, not to mention a link to more extensive documentation about how to read the resulting output.

**Comment by stuartarchibald** [comment]
Thanks for the request, this is a good point. Would you be interested in creating a patch to add these docstrings? It would be most welcome. Thanks!

**Comment by seibert** [comment]
Sounds like a good item for the SciPy sprints.  :)

**Comment by jni** [comment]
@seibert it was! Sorry that I was too busy with other stuff! Would you be able to point me to the right place to look in the codebase?

**Comment by stuartarchibald** [comment]
@jni, https://github.com/numba/numba/blob/37ab1420fa87d02b635991b32f0faf5c65e8fc4d/numba/dispatcher.py#L397-L461, thanks.
