### ISSUE TITLE
Powers of complex numbers in @cuda.jit decorated function

### ISSUE THREAD

**Issue by mahmoudasmar** [numba/numba#4326]
I was trying to make a @cuda.jit decorated function which contains powers of complex numbers. The function works if the power is 2. However, if the power is 3 and higher the function does not work  and I get errors. Are the powers of complex numbers supported in these type of functions?  And if not is there a way around this issue? 

Thanks!

**Comment by stuartarchibald** [comment]
Thanks for the report. I don't think this is supported, IIRC there's no complex math intrinsics available in the CUDA math API.

Duplicate of: https://github.com/numba/numba/issues/3386

**Comment by stuartarchibald** [comment]
Closed by https://github.com/numba/numba/pull/6290
