### ISSUE TITLE
Definitions of a variable share the same reference to the Var object

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#4332]
Consider this small function which produces the following IR

```{python}
@njit
def calc(n):
    arr = [0]
    for i in range(1, n+1):
        arr += [i]
    return arr
```

```
---------------------------------IR DUMP: calc----------------------------------
label 0:
    n = arg(0, name=n)                       ['n']
    $const0.1 = const(int, 0)                ['$const0.1']
    $0.2 = build_list(items=[Var($const0.1, a.py (12))]) ['$0.2', '$const0.1']
    del $const0.1                            []
    arr = $0.2                               ['$0.2', 'arr']
    del $0.2                                 []
    jump 6                                   []
label 6:
    jump 8                                   []
label 8:
    $8.1 = global(range: <class 'range'>)    ['$8.1']
    $const8.2 = const(int, 1)                ['$const8.2']
    $const8.4 = const(int, 1)                ['$const8.4']
    $8.5 = n + $const8.4                     ['$8.5', '$const8.4', 'n']
    del n                                    []
    del $const8.4                            []
    $8.6 = call $8.1($const8.2, $8.5, func=$8.1, args=[Var($const8.2, a.py (13)), Var($8.5, a.py (13))], kws=(), vararg=None) ['$8.1', '$8.5', '$8.6', '$const8.2']
    del $const8.2                            []
    del $8.5                                 []
    del $8.1                                 []
    $8.7 = getiter(value=$8.6)               ['$8.6', '$8.7']
    del $8.6                                 []
    $phi22.1 = $8.7                          ['$8.7', '$phi22.1']
    del $8.7                                 []
    jump 22                                  []
label 22:
    $22.2 = iternext(value=$phi22.1)         ['$22.2', '$phi22.1']
    $22.3 = pair_first(value=$22.2)          ['$22.2', '$22.3']
    $22.4 = pair_second(value=$22.2)         ['$22.2', '$22.4']
    del $22.2                                []
    $phi24.1 = $22.3                         ['$22.3', '$phi24.1']
    $phi38.1 = $22.3                         ['$22.3', '$phi38.1']
    del $phi38.1                             []
    del $22.3                                []
    $phi38.2 = $phi22.1                      ['$phi22.1', '$phi38.2']
    del $phi38.2                             []
    branch $22.4, 24, 38                     ['$22.4']
label 24:
    del $22.4                                []
    i = $phi24.1                             ['$phi24.1', 'i']
    del $phi24.1                             []
    $24.4 = build_list(items=[Var(i, a.py (13))]) ['$24.4', 'i']
    del i                                    []
    $24.5 = inplace_binop(fn=<built-in function iadd>, immutable_fn=<built-in function add>, lhs=arr, rhs=$24.4, static_lhs=Undefined, static_rhs=Undefined) ['$24.4', '$24.5', 'arr']
    del $24.4                                []
    arr = $24.5                              ['$24.5', 'arr']
    del $24.5                                []
    jump 22                                  []
label 38:
    del $phi24.1                             []
    del $phi22.1                             []
    del $22.4                                []
    jump 40                                  []
label 40:
    $40.2 = cast(value=arr)                  ['$40.2', 'arr']
    del arr                                  []
    return $40.2                             ['$40.2']
```

This IR defines the variable `arr` twice. One on label 0 and another on label 24:

```
label 0:
  arr = $0.2                               ['$0.2', 'arr']

label 24:
  arr = $24.5                              ['$24.5', 'arr']
```

When creating the statements for those lines, numba uses the same object to both Stmt. In other words, the target field of both `Assign` statements points to the same `Var` object. The problem with this approach is that if one wants to change the name field of the first **arr**, the second is updated as well since they are the same object.

I don't think this is the expected behavior. I would expect that every definition to create a copy of it's LHS `Var` object. Therefore, I think a plausible solution would be to replace `target` by a copy of it on file [interpreter.py:274](https://github.com/numba/numba/blob/master/numba/interpreter.py#L274)

**Comment by sklam** [comment]
`Var` is treated as immutable.  It should not matter rather `Var` is referenced in multiple places.  I would prefer all rewrite passes to always create new nodes instead of mutating existing nodes.  I'd think the actual problem is that the IR nodes do not prevent mutation.

**Comment by guilhermeleobas** [comment]
Hi @sklam, following up our discussion on Gitter. One part of the SSA transformation is [variable renaming](https://homepages.dcc.ufmg.br/~fernando/classes/dcc888/ementa/slides/StaticSingleAssignment.pdf). For instance, when inserting a PHI node for `arr` at the beginning of label 22: `arr.phi22 = PHI [(arr, 0), (arr, 24)], one would rename the first and the second `arr` to distinguish them in further analysis. 

If I am not wrong, LLVM does this! Every assignment creates a new variable and names are not shared among the LHS of assignments.

**Comment by sklam** [comment]
The trouble with mutating the `Var.name` attribute is a limitation of the design in the Numba IR. LLVM IR is designed for rewrite passes. When the Numba IR is created, we didn't envision that we need an extensive suite of rewrite passes.  Thus, it is very limited.  There're plans to improve the Numba IR but it will not be ready soon.

As for adding SSA, have you considered doing it when the Numba IR is generated so that you don't need to rewrite them later?  At `numba/interpreter.py`, the `Interpreter` class translates Python bytecode into Numba IR.  I think it has sufficient information to covert the stack based bytecode into SSA form in the Numba IR.

**Comment by guilhermeleobas** [comment]
> The trouble with mutating the Var.name attribute is a limitation of the design in the Numba IR. LLVM IR is designed for rewrite passes. When the Numba IR is created, we didn't envision that we need an extensive suite of rewrite passes. Thus, it is very limited. There're plans to improve the Numba IR but it will not be ready soon.

There are places in the code where mutating `Var` seems necessary ([ref](https://github.com/numba/numba/blob/e8ac4951affacd25c63ba2c18d62a3f12ed7e0ba/numba/npyufunc/array_exprs.py#L311-L331)). Is `Var` **immutable** only because of the name?

The *"problem"* is that renaming variables require iterating over the RHS of each instruction in the Numba IR and as far as I am aware, there is no *easy* way of doing that without implementing it for every possible instruction type. 

For instance, imagine that we have an instruction `I` which the RHS is an `Expr` and we want to 1) check if `arr` is in the RHS of `I` and 2) if yes, rename it (replace) by something else. 


But, there are currently 18 types of `Expr` and they all define different operands:
* binop (fn, lhs, rhs)
* inplace_binop (fn, immutable_fn, lhs, rhs)
* unary (fn, value)
* call (func, args, kws, vararg)
* build_tuple (items)
* build_list (...)
* build_set
* build_map
* pair_first
* pair_second
* getiter
* iternext
* exhaust_iter
* getattr
* getitem
* static_getitem
* cast
* make_function

Therefore, adding the step of renaming variables would increase the coupling between PHI nodes and other IR instructions. Any design changes/addition in the IR would require the step of renaming variables to be aware of those changes. 

Maybe before this, we could come up with a solution for iterating over instruction operands. Perhaps implement a `getOperand/setOperand` in a base class?

Let me know if that makes sense to you.

**Comment by sklam** [comment]
@guilhermeleobas, there were some IR manipulation tools added in `numba.ir_utils`.  They are mostly done by @ehsantn and @DrTodd13 during the development of the parfors passes.  I have not a good mental map of what is available in it.  From a quick look at it, I think `replace_var_names` should work for you.  

We'll need better docs for everything in `numba.ir_utils`.
