### ISSUE TITLE
Memory leak when looping over slices

### ISSUE THREAD

**Issue by jw-rs** [numba/numba#4339]
Looping over array slices results in a memory leak.

E.g., running:

```
from __future__ import print_function
from numba import njit
from numba.runtime import rtsys
from numpy import zeros

@njit
def leak(data):
  x = data[:]
  for v in (x,): pass

leak(zeros((10,)))
print(rtsys.get_allocation_stats())
```

gives the following output:
`nrt_mstats(alloc=1L, free=0L, mi_alloc=1L, mi_free=0L)`

But commenting out the for loop removes the leak:
```
#!/usr/bin/env python

from __future__ import print_function
from numba import njit
from numba.runtime import rtsys
from numpy import zeros

@njit
def leak(data):
  x = data[:]
  #for v in (x,): pass

leak(zeros((10,)))
print(rtsys.get_allocation_stats())
```

`nrt_mstats(alloc=1L, free=1L, mi_alloc=1L, mi_free=1L)`

**Comment by esc** [comment]
@jw-rs thank you for the report and helping to improve Numba. I am unable to reproduce this using Mac OSX and Numba 0.44.1 as well as current `master`. Which version of Numba are you running and could you post the output of `numba -s` please? Thanks!

**Comment by jw-rs** [comment]
Hi @esc 

Sincere apologies. I thought I was using the latest numba, but the report above is for version 0.40.1 (Linux x86_64). Just retested on version 0.44.1 (Linux x86_64, llvm 7.0.1) and the issue is fixed.

Apologies again for the spam.

**Comment by esc** [comment]
@jw-rs no problem at all, thanks for following up on this and closing the issue. Please don't hesitate to open new issues should you hit any more snags!
