### ISSUE TITLE
Spurious logging messages

### ISSUE THREAD

**Issue by JSKenyon** [numba/numba#4359]
The logging behaviour of the latest release of Numba (0.45.0) has changed for both Python2 and Python3. I am seeing a large number of spurious DEBUG messages. I have verified that this does not happen with 0.44.1. The error messages are as follows:

```
DEBUG:numba.typeinfer:captured error
Traceback (most recent call last):
  File "/venvs/local/lib/python2.7/site-packages/numba/typeinfer.py", line 147, in propagate
    constraint(typeinfer)
  File "/venvs/local/lib/python2.7/site-packages/numba/typeinfer.py", line 459, in __call__
    fnty = typevars[self.func].getone()
  File "/venvs/local/lib/python2.7/site-packages/numba/typeinfer.py", line 115, in getone
    raise TypingError("Undecided type {}".format(self))
TypingError: Undecided type $327.268 := <undecided>
[1] During: resolving caller type: $327.268
[2] During: typing of call at /venvs/local/lib/python2.7/site-packages/cubical/kernels/full_complex.py (404)
```

Note that the code still works as expected. I have worked around this by adding:
```
import logging
logging.getLogger('numba.typeinfer').setLevel(logging.WARNING)
```
to the top of my main application script.

I believe that the offending line is [here](https://github.com/numba/numba/blob/f7a60964d871c29040457caaa26194a01ba98d28/numba/typeinfer.py#L30).

**Comment by esc** [comment]
@JSKenyon thanks for the report and for helping to improve Numba. From a first guess this does look like a regression but will have to be investigated further.

**Comment by esc** [comment]
@JSKenyon do you happen to have a minimal reproducer? I.e. a small snippet of code that will allow us to reproduce the logging behaviour you are seeing?

**Comment by JSKenyon** [comment]
@esc I will try come up with something. Unfortunately, it is a relatively challenging situation to replicate.

**Comment by JSKenyon** [comment]
ln my efforts to reproduce this, I discovered a relic in my own code which was causing this behaviour. The reason it only appeared in 0.45.0 is due to the fact that previously there was no logger (and no DEBUG level messages). Apologies for the false alarm.

**Comment by esc** [comment]
@JSKenyon thanks a lot for following up on this and no worries on the false alarm. Happy to hear you managed to sort it out!
