### ISSUE TITLE
Header in documentation cuts off the top of the page sometimes

### ISSUE THREAD

**Issue by asmeurer** [numba/numba#4365]
For example at https://numba.pydata.org/numba-doc/dev/user/parallel.html#numba-parallel

![image](https://user-images.githubusercontent.com/71486/61833318-2a6e1a00-ae31-11e9-8e08-2a126c88d4a1.png)

There is a header at the top of the page that says "1.10. Automatic parallelization with @jit¶" but you can't see it.

It doesn't do it on every page. For instance at https://numba.pydata.org/numba-doc/dev/user/jit.html#parallel-jit-option it is fine: 
![image](https://user-images.githubusercontent.com/71486/61833399-686b3e00-ae31-11e9-9d07-b53ee598f9e1.png)

**Comment by seibert** [comment]
This appears to be a side effect of some long-standing fights I've had with the CSS used in our documentation theme...  The problem pages seem to bump the search box down a line, which result in the header being taller than expected and covering up some of the page.

**Comment by seibert** [comment]
For bonus fun, this seems to happen in Safari, but not in Chrome due to subtle layout differences between the browsers.

**Comment by seibert** [comment]
#4366 appears to fix this (on my machine anyway).

**Comment by stuartarchibald** [comment]
I think #4366 is one option to fix but I'm not sure about whether this is the best route to take. Locally the `latest` docs http://numba.pydata.org/numba-doc/latest/reference/types.html render fine, but the `dev` docs http://numba.pydata.org/numba-doc/dev/reference/types.html exhibit the behaviour described above, do you both see the same? If so I'm wondering if we should try and work out what the difference is (expect it's doc build envs) and fix that ahead of tweaking CSS?

**Comment by asmeurer** [comment]
Both pages you linked to render the same for me. I am using Chrome on Linux.
