### ISSUE TITLE
Numba could not be imported

### ISSUE THREAD

**Issue by ltc1996** [numba/numba#4367]
I'm wirtting a python scripts for 3ds Max and i need to `import numba` for fast speed. I did as the procedure says in [3ds Max Python extension libraries](http://help.autodesk.com/view/3DSMAX/2020/ENU/?guid=__developer_python_extension_libraries_html).

(In step 3, i run `pip install --no-cache-dir numba`)

After i pip `numba` in my `C:\Program Files\Autodesk\3ds Max 2017\python\Lib\site-packages`, I can see the folder numba in it, 
![image](https://user-images.githubusercontent.com/47720586/61857067-fe689c80-aef5-11e9-8d25-1a9195508d2e.png)
Then I start Max Python console and hit `import numba', Max error  with log:
```python
>>> import numba
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\__init__.py", line 18, in <module>
    from .special import typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\special.py", line 3, in <module>
    from .typing.typeof import typeof
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\typing\__init__.py", line 2, in <module>
    from .context import BaseContext, Context
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\typing\context.py", line 12, in <module>
    from numba.typeconv import Conversion, rules
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\typeconv\rules.py", line 3, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages\numba\typeconv\typeconv.py", line 16, in <module>
    raise ImportError(msg)
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
```
![image](https://user-images.githubusercontent.com/47720586/61856972-cc573a80-aef5-11e9-812d-b553fa172221.png)

Last line it says DLL load failed. How can i solve it?

I dont know where i can rerun 'python setup.py build_ext'.  But i pip `numpy` in my py2.7 pathfolder `C:\Python27\Lib\site-packages` then start **python Command Line** then  `from numba import jit`, i get no error. 
![image](https://user-images.githubusercontent.com/47720586/61857123-1809e400-aef6-11e9-8290-75f3b0e618e4.png)

I'm so confused. How can i import numba in Max without error ?

**Comment by esc** [comment]
@ltc1996 thank you for reporting this and helping to improve Numba. My first guess, from what you have written is that you have multiple Python installations on your machine. There seems to be one at `C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages` and another at `C:\Python27\Lib\site-packages`. It does appear like Numba might be installed correctly in the latter but not in the former.

Maybe you could run `numba -s` from the windows command prompt and post the output here?

**Comment by esc** [comment]
The hint about running `python setup.py build_ext --inplace` is only applicable if you are developing Numba.

**Comment by esc** [comment]
Also, if you are having trouble using the `numba` command line interface, there are some additional hints here:

http://numba.pydata.org/numba-doc/latest/user/cli.html

**Comment by ltc1996** [comment]
> @ltc1996 thank you for reporting this and helping to improve Numba. My first guess, from what you have written is that you have multiple Python installations on your machine. There seems to be one at `C:\Program Files\Autodesk\3ds Max 2017\python\lib\site-packages` and another at `C:\Python27\Lib\site-packages`. It does appear like Numba might be installed correctly in the latter but not in the former.
> 
> Maybe you could run `numba -s` from the windows command prompt and post the output here?

Yes, Max has its own py2.7 which it supports, i have py2.7 too, but when i `pip numba`, i use as structured `pip install --no-cache-dir numba` [3d Max pip](http://help.autodesk.com/view/3DSMAX/2020/ENU/?guid=__developer_python_extension_libraries_html):
![image](https://user-images.githubusercontent.com/47720586/61870947-151cec80-af12-11e9-800d-bed4af71fc49.png)

In powershell, i run as followed and jump a txt, is that right ?
![image](https://user-images.githubusercontent.com/47720586/61872432-d9842180-af15-11e9-84b1-5355b47900f8.png)

**Comment by ltc1996** [comment]
> Also, if you are having trouble using the `numba` command line interface, there are some additional hints here:
> 
> http://numba.pydata.org/numba-doc/latest/user/cli.html
the version of numba i install:
![image](https://user-images.githubusercontent.com/47720586/61872555-3b448b80-af16-11e9-81a5-d1c05b3fd014.png)

**Comment by esc** [comment]
Maybe you have multiple versions of `pip` installed? Can you check where the `pip` is located that you are using to install `numba`?

**Comment by ltc1996** [comment]
I only have one version of pip 19.2.1, but in **step 1**, i have to copy `get-pip.py` into Max install folder and run it. This is the procedure you may need to check: [3d Max pip for package management](http://help.autodesk.com/view/3DSMAX/2020/ENU/?guid=__developer_python_extension_libraries_html).
![image](https://user-images.githubusercontent.com/47720586/61876334-32a48300-af1f-11e9-8bbe-723708d4f54c.png)
So in this way the `pip` i use is inside the Max?
![image](https://user-images.githubusercontent.com/47720586/61876157-d5103680-af1e-11e9-8153-807499769cf3.png)
Thanks very much for your answer, i have trying to solve this error for 2 days, smh... :(

**Comment by esc** [comment]
Is there a way you can search your computer for all files with the name `pip`? I still suspect that there is something wrong with the `pip`s you are using and thus `numba` was not installed correctly.

**Comment by ltc1996** [comment]
Yes, I can search all `get-pip.py` in my computer
![image](https://user-images.githubusercontent.com/47720586/61882434-23c3cd80-af2b-11e9-8043-dcd7f3c901fa.png)
I don't have it in my `C:\Python27\Lib\site-packages\pip` perhaps Max helps me uninstall it and reinstall in its folder.

**Comment by esc** [comment]
Sorry, I mean just the `pip`program itself, not `get-pip.py`.

**Comment by ltc1996** [comment]
My bad, it seems that i have two `pip`.
![image](https://user-images.githubusercontent.com/47720586/61992537-48868500-b092-11e9-9c3a-f37475a8a905.png)

**Comment by esc** [comment]
@ltc1996 with so many different `pip` executables it may be that `numba` wasn't installed correctly or in the correct place. At this point I am running out of ideas as to what to suggest. Note that this isn't a problem we see very often so we don't have a good solution for you at this stage. If possible, it might be worth trying to re-install 3ds Max.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
