### ISSUE TITLE
Default argument gives "this should not have happened" error

### ISSUE THREAD

**Issue by jason-levy** [numba/numba#4385]
## Reporting a bug

- [x ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba as nb; nb.njit(lambda n, x=[0]: x[n])(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot lower constant of type 'reflected list(int64)'

File "<stdin>", line 1:
<source missing, REPL/exec in use?>

[1] During: lowering "x = arg(1, name=x)" at <stdin> (1)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

```

This is under Ubuntu 18.04.2.  When I use `@nb.jit` instead of `njit`, I get the deprecation warning and the correct answer.

Based on https://github.com/numba/numba/issues/4382#issue-474265682 I guess that numba  isn't expected to compile this successfully, but should give a different error message.

**Comment by stuartarchibald** [comment]
Thanks for the report. Unwinding the code so it can be explained...

```python
from numba import njit
@njit
def foo(n, x=[0]): 
  return x[n]
```
In the above, the declaration `x=[0]` will consider the type of `[0]` a reflected list, but because its bound to the kwarg `x` it is considered a constant and this combination is unsupported. #4382 is indeed in part related.

**Comment by stuartarchibald** [comment]
Closing on the basis that it's not recommended to use mutable types as default args and I don't think Numba will fix this.
