### ISSUE TITLE
Jitting linked list takes an unexpectedly long time

### ISSUE THREAD

**Issue by 99991** [numba/numba#4387]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import jit

@jit
def make_list(n):
    if n <= 0:
        return None
    
    return (n, make_list(n - 1))

print(make_list(100))
```

This code makes a linked list with 100 nodes and takes over 40 seconds to run with `@jit` or 0.02 seconds without.

My actual goal is to implement a kdtree, but type conversion between a jitclass and an optional child member of that same class does not work yet, so I tried tuples instead and ran into this issue.

**Comment by stuartarchibald** [comment]
Thanks for the report. I presume the time reported includes compilation time? Also, please could you let us know which Numba version you are using, thanks.

**Comment by 99991** [comment]
> I presume the time reported includes compilation time?

Yes. The first call to `make_list` takes a while and consumes several gigabytes of RAM, but subsequent runs are faster (0.1 to 0.2 milliseconds).

> Also, please could you let us know which Numba version you are using, thanks.

I get 0.45.0 when running `print(numba.__version__)`.

In addition, I just noticed that the process finishes immediately when sending a SIGINT, so maybe the jit simply crashes due to running out of memory and falls back to some other method.

**Comment by stuartarchibald** [comment]
CC @sklam, probably of interest to you.

**Comment by sklam** [comment]
The long compilation time is caused by the inability for the type inferencer to converge on a return-type. The function tries to make an infinitely nested tuple type. Eventually, it causes an error (probably due to out-of-memory error) and fallback to object mode.
