### ISSUE TITLE
CUDA kernel slowdown after several thousand kernel iterations

### ISSUE THREAD

**Issue by jd-bartlett96** [numba/numba#4390]
Numba: 0.45.0

I'm working on a cuda kernel that needs to run thousands of iterations. After around 1000 iterations (exact number seems to depend on complexity of kernel and specific graphics card), the time taken by one iteration of the kernel increases by a factor of anywhere from 2 to 20. I've made the most minimal example I could; the effect is much more dramatic when I try to run the kernel I'm actually working on.

Minimal code:

	import numpy as np
	from numba import cuda
	import time
	import math

	totnode = 100000;
	nt = 10000

	coords = np.random.rand(3,totnode)

	d_coord = cuda.to_device(coords)
	d_conn = cuda.to_device(np.random.randint(totnode, size=(5, totnode)))

	@cuda.jit
	def d_Integrate(d_conn,d_coord):
		global totnode

		i = cuda.grid(1)

		if i<totnode:
			cix, ciy, ciz = d_coord[:,i]
			conn = d_conn[:,i]
			for a in range(5):
				temp = 0.
				ind = conn[a]
				if ind>-1:
					ccx, ccy, ccz = d_coord[:,ind]
					nlen = math.pow(ccx-cix,2)
					L0 = math.pow(ccx-cix,2)
					temp = (nlen - L0)/L0

	def Integrate():
		TPB = 32
		BPG = (totnode+TPB-1)//TPB
		d_Integrate[BPG,TPB](d_conn,d_coord)

	for tt in range(nt):
		t0 = time.time()
		Integrate()
		print(tt,time.time()-t0)

Excerpt from terminal output on GTX 980 (showing the timing slowdown happening at iteration 1981):

> 1974 0.00024175643920898438
1975 0.00024127960205078125
1976 0.00024008750915527344
1977 0.00024175643920898438
1978 0.0002415180206298828
1979 0.00024080276489257812
1980 0.00024127960205078125
1981 0.0003216266632080078
1982 0.0006465911865234375
1983 0.0004718303680419922
1984 0.000606536865234375
1985 0.0004963874816894531
1986 0.0004942417144775391
1987 0.0006222724914550781
1988 0.000499725341796875
1989 0.0004980564117431641
1990 0.0004985332489013672
1991 0.0004973411560058594
1992 0.0004975795745849609

Excerpt from terminal output on RTX 2070 (showing the timing slowdown happening at iteration 1491):

> 1482 0.00015592575073242188
1483 0.00015783309936523438
1484 0.000156402587890625
1485 0.0001571178436279297
1486 0.000156402587890625
1487 0.0001647472381591797
1488 0.00015807151794433594
1489 0.00015735626220703125
1490 0.0001590251922607422
1491 0.00031685829162597656
1492 0.00042724609375
1493 0.0004374980926513672
1494 0.0004353523254394531
1495 0.0004372596740722656
1496 0.00043702125549316406
1497 0.0004372596740722656
1498 0.0004420280456542969
1499 0.00043082237243652344
1500 0.0004372596740722656
1501 0.0004379749298095703

**Comment by seibert** [comment]
Kernel launches are asynchronous (when the inputs are device arrays, and not numpy arrays), which means that the Python interpreter will keep executing once the kernel is handed off to the CUDA driver and not wait for it to complete.  Your times on the first few passes through the loop are measuring this launch overhead, and once the launch buffer fills up, you will start seeing the effect of the actual computation on the time.

If you want to accurately time each kernel execution, you need to call `cuda.synchronize()` after running the kernel to force the interpreter to wait until the kernel has finished executing on the GPU.  Kernels will run in order, so you don't need to synchronize unless you are benchmarking (and in fact you'll get better throughput if you don't).

**Comment by jd-bartlett96** [comment]
Thank you! Didn't fully comprehend the implications this had for timing/benchmarking.

**Comment by seibert** [comment]
No worries.  This is a common source of confusion.  Glad we could help.
