### ISSUE TITLE
Hello. I am ru

### ISSUE THREAD

**Issue by maryam69898895** [numba/numba#4391]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
This report seems to be opened in error, https://github.com/numba/numba/issues/4392 is likely the issue contents. Closing.
