### ISSUE TITLE
NotImplementedError: (<class 'numba.ir.StaticSetItem'>, heatmap.1[(slice(None, None, None), slice(None, None, None), -1)] = $151.17)

### ISSUE THREAD

**Issue by maryam69898895** [numba/numba#4394]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. It looks like this is the same problem as reported here https://github.com/numba/numba/issues/4392? If so, please comment on that issue with more information, in general new issues do not need opening for duplicate/known problems. Thanks for your cooperation in resolving this matter.
