### ISSUE TITLE
Turn off function name numbering for easier caching for CUDA

### ISSUE THREAD

**Issue by sklam** [numba/numba#4396]
## Feature request

`FunctionID` stores a `uid` into the symbol name to avoid name collision.  But, it is affecting the ability to cache in cudf.

**Comment by sklam** [comment]
Maybe we can just turn it off in `@cuda.jit(name_numbering=False)`?

**Comment by sklam** [comment]
maybe consider letting user override the symbol name

**Comment by gmarkall** [comment]
This is no longer necessary - caching in cudf compares the Python function code, closure variables, and argument types instead, so it doesn't matter exactly what the returned PTX looks like: https://github.com/rapidsai/cudf/pull/7371

I'd suggest not supporting this feature for other libraries either, as it seems like a bit of a hack.
