### ISSUE TITLE
slowing down the functions 

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4420]
```
@jit(nopython=True)
def plus_mat(m1,m2):

	ndim1 = m1.ndim 
	ndim2 = m2.ndim
	
	if ndim1 == 1 or ndim2 == 1:	#if any of m is a constant then can plus directly 
		retMat = m1 + m2 
		return retMat

	rowNum1 = m1.shape[0]
	rowNum2 = m2.shape[0]
	#colNum = m1.shape[1]	#assume the column number is same 

	if rowNum1 == rowNum2:
		retMat = m1 + m2 
		return retMat
	elif rowNum1 < rowNum2:
		m2 = m2[-rowNum1:,:]
	elif rowNum1 > rowNum2:
		m1 = m1[-rowNum2:]
	
	retMat = m1 + m2 
	return retMat
```
```
@jit(nopython=True)
def multiply_mat(m1,m2):

	ndim1 = m1.ndim 
	ndim2 = m2.ndim
	
	if ndim1 == 1 or ndim2 == 1:	#if any of m is a constant then can plus directly 
		retMat = m1 * m2 
		return retMat

	rowNum1 = m1.shape[0]
	rowNum2 = m2.shape[0]
	#colNum = m1.shape[1]	#assume the column number is same 

	if rowNum1 == rowNum2:
		retMat = m1 * m2 
		return retMat
	elif rowNum1 < rowNum2:
		m2 = m2[-rowNum1:,:]
	elif rowNum1 > rowNum2:
		m1 = m1[-rowNum2:]
	
	retMat = m1 * m2 
	return retMat
```

```
m1 = np.random.randn(300,3000)
m2 = np.random.randn(300,3000)

%timeit plus_mat(m1,m2)
732 µs ± 3.71 µs per loop
%timeit plus_mat.py_func(m1,m2)
47.7 µs ± 62.6 ns per loop

%timeit multiply_mat(m1,m2)
734 µs ± 4.13 µs per loop
%timeit multiply_mat.py_func(m1,m2)
48.2 µs ± 54.5 ns per loop
```

So why numba slow down the functions  dramatically , how can I fix the problem. Thank you.

**Comment by sklam** [comment]
For the given inputs, the two functions boil down to the speed of `m1 + m2` and `m1 * m2`.  When using numpy build with MKL, numpy is likely using multiple threads for the operation.  As for numba, if `parallel=True` is set in `@jit`, it can achieve similar speed.

**Comment by isaac-you** [comment]
Thank you I found the same reason . 

If I want to calculate 1000 times  'multiply_mat'  parallelly,  and the core function 'multiply_mat' works  parallelly itself ,  will it speed up the whole calculation??? 

I think the core function 'multiply_mat' should work in single cpu , then calculate 1000 times 'multiply_mat'  parallelly, is this better than another way ??? 

Am I right ?

**Comment by sklam** [comment]
It depends on how you structure the code and what threading backend is used.  If you use `numba.prange` as the parallel forloop, the compiler will automatically run the inner parallel loop sequentially.  If the threading backend is TBB, it is aware of nested parallelism and can schedule the parallel task efficiently.   See this [page about threading backends in numba](http://numba.pydata.org/numba-doc/latest/user/threading-layer.html).

It's hard to give general advise about optimization. The best approach is to benchmark different approaches for your specific case.

**Comment by isaac-you** [comment]
thank you so much

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
