### ISSUE TITLE
paralled numpy array error:

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#4438]
I have below error for this code : 
```python
@njit( parallel=True)
def search(c_desc,  p_descs, ):
		tupZ = [(1, 18.265, 100, 0.1)]

		for x in prange(p_descs.shape[0]):
			sim = np.dot(c_desc, p_descs[x].T)
			dist = np.sum(np.square(c_desc - p_descs[x]))

			if float(dist) < threshold:
				name_number = x
				a_float = dist
				an_int = x
				small_float = sim
				tupZ.append((name_number, a_float, an_int, small_float))


		return tupZ
```

Error:

Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)

File "<string>", line 2:
<source missing, REPL/exec in use?>

[1] During: lowering "_tupZ_102 = arg(1, name=_tupZ_102)" at <string> (2)
[2] During: lowering "id=3[LoopNest(index_variable = parfor_index.101, range = (0, $8.5, 1))
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

How can I use properly parallel execution for above code ?

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:

1. The data needed to run the code (example inputs would be fine).

Thanks.

**Comment by MyraBaba** [comment]
c_desc= np.empty(shape=[0, 512], dtype=np.float32) 
p_desc= np.empty(shape=[1000000, 512], dtype=np.float32) 

its a numpy array floating points filled.

**Comment by stuartarchibald** [comment]
Thanks for the extra information, I cannot reproduce the above. This fails with:
```
Invalid use of BoundFunction(list.append for list((int64, float64, int64, float64))) with parameters ((int64, float32, int64, array(float32, 1d, C)))
 * parameterized
[1] During: resolving callee type: BoundFunction(list.append for list((int64, float64, int64, float64)))
[2] During: typing of call at issue4438.py (17)


File "issue4438.py", line 17:
def search(c_desc,  p_descs, ):
    <source elided>
                    small_float = sim
                    tupZ.append((name_number, a_float, an_int, small_float))
```
code used:
```python
from numba import njit, prange
import numpy as np

threshold = 1.

@njit( parallel=True)
def search(c_desc,  p_descs, ):
    tupZ = [(1, 18.265, 100, 0.1)]

    for x in prange(p_descs.shape[0]):
            sim = np.dot(c_desc, p_descs[x].T)
            dist = np.sum(np.square(c_desc - p_descs[x]))
            if float(dist) < threshold:
                    name_number = x
                    a_float = dist
                    an_int = x
                    small_float = sim
                    tupZ.append((name_number, a_float, an_int, small_float))

    return tupZ


c_desc = np.empty(shape=[0, 512], dtype=np.float32)
p_desc = np.empty(shape=[100, 512], dtype=np.float32)

search(c_desc,  p_desc)
```
it should also be noted that the use of `list.append` in a `prange` loop is invalid as `list.append` is not threadsafe.

**Comment by MyraBaba** [comment]
above my code is worked with :

@njit(parallel=True , nopython=True) .  ## 16 seconds

without parallel its 1.2 seconds.

ten times slower.

first slower one gives warning . 

> site-packages/numba/decorators.py:217: RuntimeWarning: nopython is set for njit and is ignored
  warnings.warn('nopython is set for njit and is ignored', RuntimeWarning)

attached example non empty array "np.empty(shape=[0, 512], dtype=np.float32)"

you can load wtih np.load

file:
[cmp_test.npy.zip](https://github.com/numba/numba/files/3493634/cmp_test.npy.zip)

**Comment by stuartarchibald** [comment]
Thanks, please could you create a piece of code that reproduces this problem and demonstrates the execution times such that to test it all that is required is to do `python your_reproducer.py`? Thanks again.

**Comment by MyraBaba** [comment]
Here the minimal code .

gives error wit parallel = True
```

`from numba import njit , prange
import numpy as np
import random

threshold = 1

@njit(parallel=True )
def Search_2(compare_desc,  p_descs, ):
		tupZ = [(1, 18.265, 100, 0.1)]
		for x in prange(p_descs.shape[0]):
			sim = np.dot(compare_desc, p_descs[x].T)
			dist = np.sum(np.square(compare_desc - p_descs[x]))

			if float(dist) < threshold:
				# a_string = people_namesTUPLE[x]
				name_number = x
				a_float = dist
				an_int = x
				small_float = sim
				tupZ.append((name_number, a_float, an_int, small_float))

		return tupZ


p_desct = np.empty(shape=[2000000, 512], dtype=np.float32)
c_desc  = np.empty(shape=[1, 512], dtype=np.float32)
i=0
while i < 2000000:
	p_desct[i][0] = random.random()
	c_desc[0][0] = random.random()
	i += 1

tup = Search_2(c_desc[0] , p_desct)
print(tup.__sizeof__())

tup = Search_2(c_desc[0] , p_desct)
print(t`
```

**Comment by stuartarchibald** [comment]
Thanks for the working reproducer. The issue you are seeing is because the tuple being appending to `tupZ` has incorrect type, this is something we'll investigate. However, this point is moot as doing `list.append` inside a `prange` is invalid as it is not threadsafe.

**Comment by stuartarchibald** [comment]
Version that will compile, note the forced types, this version is still invalid because of the unsafe list append.
```python

from numba import njit , prange, types
import numpy as np
import random

threshold = 1

@njit(parallel=True )
def Search_2(compare_desc,  p_descs, ):
    tupZ = [(1, 18.265, 100, 0.1)]
    for x in prange(p_descs.shape[0]):
        sim = np.dot(compare_desc, p_descs[x].T)
        dist = np.sum(np.square(compare_desc - p_descs[x]))

        if float(dist) < threshold:
                name_number = x
                a_float = dist
                an_int = x
                small_float = sim
                tup = (types.int64(name_number), a_float, types.int64(an_int), small_float)
                tupZ.append(tup)

    return tupZ

N = 100
p_desct = np.empty(shape=[N, 512], dtype=np.float32)
c_desc  = np.empty(shape=[1, 512], dtype=np.float32)
i=0
while i < N:
        p_desct[i][0] = random.random()
        c_desc[0][0] = random.random()
        i += 1

tup = Search_2(c_desc[0] , p_desct)
print(tup.__sizeof__())

tup = Search_2(c_desc[0] , p_desct)
print(tup)
```
CC @DrTodd13 Any ideas as to why parfors is typing that tuple as a `4x float64`?

**Comment by MyraBaba** [comment]
@stuartarchibald  thanks for investigation.

what would be the best approach to replace list.append ?

**Comment by MyraBaba** [comment]
@stuartarchibald 

ı tested your code when I give N = 10000 and more it gives : 

> Python(47764,0x70000ef43000) malloc: *** error for object 0x100ab8200: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x70000f749000) malloc: *** error for object 0x100be3a00: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x700010352000) malloc: *** error for object 0x100be3a00: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x70000f346000) malloc: *** error for object 0x100be3a00: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x70000fb4c000) malloc: *** error for object 0x100b96200: double free
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x70000eb40000) malloc: *** error for object 0x100b96200: double free
*** set a breakpoint in malloc_error_break to debug
Python(47764,0x70000ff4f000) malloc: *** error for object 0x100b96200: double free
*** set a breakpoint in malloc_error_break to debug

**Comment by stuartarchibald** [comment]
yes, it's not threadsafe.

**Comment by MyraBaba** [comment]
what I can use instead of list ?

**Comment by stuartarchibald** [comment]
Right now I don't think that there is anything that is particularly easy/reliable to do that would match your use case.

**Comment by MyraBaba** [comment]
@stuartarchibald  is there any thread safe type that I can use with in this case ?

**Comment by MyraBaba** [comment]
@stuartarchibald  

i tried and not worked :) 

what we can do may be try to add some code to the numba code to handle this ?

**Comment by MyraBaba** [comment]
@stuartarchibald 
Hi 

Can we write the above minimal code for CUDA in numba ? 

what is the correct way to do use GPU from numba for above minimal codes ? 

I tried to add @vectorize (['float32(float32,float32)'], target='cuda')

gives below error.

is it possible*

numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type float32

**Comment by MyraBaba** [comment]
@stuartarchibald 

Hi 

anu improvement for threadsafe container append ?

**Comment by stuartarchibald** [comment]
The containers are not threadsafe, this is now noted in the docs:
https://numba.readthedocs.io/en/stable/user/parallel.html#unsupported-operations

Please do open any future specific feature requests in separate tickets. Closing this question as it seems to be resolved. Numba now has a discourse forum  https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
