### ISSUE TITLE
Support more cuda intrinsic math functions

### ISSUE THREAD

**Issue by codemk8** [numba/numba#4441]
## Feature request

CUDA has more intrinsic math functions:
https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__DOUBLE.html

But currently, numba does not seem to support all of them:
https://github.com/numba/numba/blob/master/numba/cuda/libdevice.py

For instance: normcdfinv, erfcinv, erfinv.

Can we add them in the near future release?
Thanks!

**Comment by leofang** [comment]
We also need single-precision variants (with suffix `f`).

**Comment by gmarkall** [comment]
All libdevice functions will be added in #6152

**Comment by gmarkall** [comment]
Closing as #6152 is now merged, and all libdevice functions are now available in 0.52.0RCx, and will be available in 0.52 when it is released.
