### ISSUE TITLE
can we use Numba on Phones?

### ISSUE THREAD

**Issue by wangshuai666** [numba/numba#4444]

**Comment by stuartarchibald** [comment]
Please could you describe what it is your are trying to do? i.e. what the hardware is, what the software stack is, which OS etc. Thanks.

**Comment by seibert** [comment]
Just to put in some info here.  The Termux issue (#4380) is probably the closest to this question, as it regards Android support.  It seems there are still some issues there.  As for iOS, we have no experience here.

**Comment by mhsmith** [comment]
Numba on Android is now supported by the current version of [Chaquopy](https://chaquo.com/chaquopy/).

**Comment by stuartarchibald** [comment]
Thanks for the info @mhsmith. Out of interest, what provides the:
``` 0x0000000000000001 (NEEDED)             Shared library: [libLLVM-8.so]```
for `libllvmlite.so` ?

**Comment by mhsmith** [comment]
Where a package depends on a non-Python library like LLVM, Chaquopy distributes those libraries as separate wheels. See the "chaquopy-" subdirectories at https://chaquo.com/pypi-7.0/.

**Comment by stuartarchibald** [comment]
I see, this is great, thanks for taking the time to support Numba :)

**Comment by gmarkall** [comment]
Closing this as the original question seems to be answered and there have not been any updates for over a year.

**Comment by sfornengo** [comment]
I am really interested by using numba on android, is there any step forward on the subject ?
Could someone explain current state ?

**Comment by mhsmith** [comment]
As far as I know, there's been no change in the last year. Numba and llvmlite are quite difficult to build for Android. Chaquopy has managed to support them, but Kivy has not.

**Comment by sfornengo** [comment]
Could we use the wheel packages for android (llvmlite, numba) developed by chaquopy ?
https://chaquo.com/pypi-7.0/

**Comment by mhsmith** [comment]
I built those packages, and I have no objection to any other project using them.

**Comment by sfornengo** [comment]
Thank you but what about the licensing limitations of chaquopy ?

**Comment by mhsmith** [comment]
The Chaquopy license doesn't apply to third-party packages, so other projects are free to use our builds if they want. However, they'll have to come up with their own solution for installing and loading the native libraries, which Chaquopy does automatically.

**Comment by sfornengo** [comment]
> I built those packages, and I have no objection to any other project using them.

Could you provide a script and instructions on how to setup target hardware ?
This question comes from numba member (https://github.com/numba/llvmlite/issues/772#issuecomment-1059367978)

**Comment by mhsmith** [comment]
Sorry, I can only provide support for using the packages with Chaquopy. Other projects will have to work out the details themselves.
