### ISSUE TITLE
Document libraries that adopted __cuda_array_interface__

### ISSUE THREAD

**Issue by leofang** [numba/numba#4448]
As discussed on Gitter (starting [here](https://gitter.im/numba/numba?at=5d52fa614e17537f522664ae)) and encouraged by @seibert, it'd be nice to document libraries that adopt `__cuda_array_interface__` on Numba's `__cuda_array_interface__` webpage: http://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html. This serves not only as a showcase of a great community effort toward the interoperability of GPU libraries, but also as a successful model for how different groups of library developers and maintainers can work together.

Currently, the list I have at hand is
- Numba
- CuPy
- PyTorch
- PyArrow
- cuDF
- cuML
- mpi4py
- ArrayViews

Known planned/proposed efforts:
- tensorflow (tensorflow/tensorflow#29039)
- jax (google/jax#1100)

I'll make a PR later this week. One question for the PR: should I hyperlink to the 3rd party library's GitHub repo, to the actual documentation that introduces this support, or to the landing page of the official website?

In the meanwhile please feel free to add items to the list. I am sure I must have left out some.

cc: @mrocklin

**Comment by mrocklin** [comment]
I think that this would be a great doc to have.  Thank you for proposing it @leofang

**Comment by seibert** [comment]
My preference for the linkage would be first to the project doc page describing the extent of `__cuda_array_interface__` support, if it exists, otherwise link to the project home page.
