### ISSUE TITLE
Rebuild Numba 0.45.1 packages with NumPy 1.17

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#4450]
## Feature request

It would be great to have the Numba 0.45.1 packages rebuilt with NumPy 1.17. Currently they seem to be pinned to NumPy 1.16. Better still would be to relax the upper bound on the NumPy pinning to allow other newer versions of NumPy to be installed [like with the Numba package in conda-forge]( https://github.com/conda-forge/numba-feedstock/blob/efc8d1b20387e630cb0d425d18129ebe9b2cb691/recipe/meta.yaml#L46 ).

For context, there are some really nice features in NumPy 1.17 like [array creation functions that allow the shape to be overridden]( https://github.com/numpy/numpy/pull/13046 ). These end up being used in conjunction with other array libraries like Dask, Sparse, CuPy, etc. So are handy when using the NumPy API with other array-like libraries.

cc @jjhelmus

**Comment by seibert** [comment]
Which packages are you talking about?  The conda packages in the `numba` channel?

**Comment by jjhelmus** [comment]
The upper bound on the `numba` packages in `defaults` is 2.0.  There is no numpy 1.17 in `defaults` yet which may explain the perceived behavior.

**Comment by jakirkham** [comment]
Am referring to the ones in the `numba` channel.

**Comment by stuartarchibald** [comment]
The ones in the Numba channel need a NumPy 1.17 conda package to build against.

**Comment by jakirkham** [comment]
Would you be open to relaxing the pinning as is done in `defaults` and `conda-forge`? If so, we don't need a NumPy 1.17 package.

**Comment by stuartarchibald** [comment]
We're in the process of redesigning and rebuilding the Numba build farm so it produces packages more like the Anaconda distribution and indeed `conda-forge` releases, so yes, sometime in the near future. The reason it pins now is historical, we've been building and testing huge numbers and combinations of packages way before the Anaconda build and tooling chains could be used to help with such situations and a lot of complexity was necessarily baked into the farm as a result.

**Comment by jakirkham** [comment]
I'm happy to do a small PR for this bit if it helps. 🙂 Though can hold off if not.

**Comment by jakirkham** [comment]
Any updates here? Can submit a PR for the recipe if that would help. 🙂

**Comment by esc** [comment]
@jakirkham we really appreciate the offer of a PR, however since we are currently re-vamping our CI infrastructure the PR is unlikely to be of much use to us. Please stay tuned however, since we are interested in this too and it is likely to happen in the near- to mid-term. Thank you for your patience.

**Comment by stuartarchibald** [comment]
@jakirkham thanks for the offer, is this holding something down/up-stream of us up?

**Comment by jakirkham** [comment]
Someone installed an environment during the EuroSciPy sprints and they couldn't understand why they had `numpy` 1.16 installed in the environment. They assumed it was because of `defaults` not having a `numpy` 1.17 package. After a little debugging, we ran into this issue again. Figured it would be good for us to check-in here.

Thanks for the updates. :)

**Comment by jakirkham** [comment]
I think this got fixed in 0.47.0 and appears to be fixed since. Is that right (just want to make sure my eyes aren't playing tricks on me 😜)? If so, I think we can close this out 🙂

**Comment by esc** [comment]
@jakirkham I think I recall seeing something about this in the release notes and Numpy 1.17 support was patched in 0.45.1 - but that seems to be dated 30 Jul 2019. I am not sure that this is what you are asking about? I also tried the test case from #4702:

```
conda create -n test_n117_nb046 python=3.6 numpy=1.17 numba=0.46
```

And that seems to work fine.

**Comment by jakirkham** [comment]
Cool, thanks for confirming! 😄

Yeah found the change [that fixed it]( https://github.com/numba/numba/pull/5046/files#diff-ac687339c687419934ddd1b3e1d97f5c ). Going to close this out.

Maybe ( https://github.com/numba/numba/issues/4702 ) should be closed too? 😉

**Comment by esc** [comment]
@jakirkham I am glad to hear it, thanks for closing out the issue!

**Comment by jakirkham** [comment]
Thanks for the fixes! 😄

**Comment by stuartarchibald** [comment]
@jakirkham just FYI, build recipe now isn't pinned to a specific NumPy, a buildfarm overhaul made this possible. There's now a host dep on NumPy, and a runtime dep on `numpy >=1.15` (which IIRC follow's NumPy's own support schedule).
`
