### ISSUE TITLE
Failure when specify a list of jitclass instance

### ISSUE THREAD

**Issue by bohan-gsm** [numba/numba#4459]
I want to create a jitclass Node, which has an atrribute 'next' is a list of Node.
I used nb.deferred_type and nb.typeof but failed.

import numba as nb

next_type = nb.deferred_type()

@nb.jitclass(spec=[
    ('value', nb.float64),
    ('next', nb.optional(next_type)),
])
class Node(object):
    
    def __init__(self, value):
        self.value = 0.
        self.next = None

next_type.define(nb.typeof([Node.class_type.instance_type]))

NIL = Node(np.inf)
NIL.next = [Node(np.inf)]

D:\ProgramData\Anaconda3\lib\site-packages\numba\ir_utils.py:1959: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument '__numba_val' of function 'mutator'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "<string>", line 2:
<source missing, REPL/exec in use?>

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
D:\ProgramData\Anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    661     try:
--> 662         yield
    663     except NumbaError as e:

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_inst(self, inst)
    399             value = self.context.cast(self.builder, value, valuety,
--> 400                                       signature.args[1])
    401 

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\base.py in cast(self, builder, val, fromty, toty)
    691             impl = self._casts.find((fromty, toty))
--> 692             return impl(self, builder, fromty, toty, val)
    693         except NotImplementedError:

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\optional.py in any_to_optional(context, builder, fromty, toty, val)
    108     else:
--> 109         val = context.cast(builder, val, fromty, toty.type)
    110         return context.make_optional_value(builder, toty.type, val)

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\base.py in cast(self, builder, val, fromty, toty)
    691             impl = self._casts.find((fromty, toty))
--> 692             return impl(self, builder, fromty, toty, val)
    693         except NotImplementedError:

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\builtins.py in any_to_deferred(context, builder, fromty, toty, val)
     91 def any_to_deferred(context, builder, fromty, toty, val):
---> 92     actual = context.cast(builder, val, fromty, toty.get())
     93     model = context.data_model_manager[toty]

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\base.py in cast(self, builder, val, fromty, toty)
    691             impl = self._casts.find((fromty, toty))
--> 692             return impl(self, builder, fromty, toty, val)
    693         except NotImplementedError:

D:\ProgramData\Anaconda3\lib\site-packages\numba\targets\listobj.py in list_to_list(context, builder, fromty, toty, val)
   1091     # Casting from non-reflected to reflected
-> 1092     assert fromty.dtype == toty.dtype
   1093     return val

AssertionError: 

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-257-a06ab3b23e70> in <module>
     17 
     18 NIL = Node(np.inf)
---> 19 NIL.next = [Node(np.inf)]

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    393                     e.patch_message(''.join(e.args) + help_msg)
    394             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 395             raise e
    396 
    397     def inspect_llvm(self, signature=None):

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    350                 argtypes.append(self.typeof_pyval(a))
    351         try:
--> 352             return self.compile(tuple(argtypes))
    353         except errors.TypingError as e:
    354             # Intercept typing error that may be due to an argument

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    691 
    692             self._cache_misses[sig] += 1
--> 693             cres = self._compiler.compile(args, return_type)
    694             self.add_overload(cres)
    695             self._cache.save_overload(sig, cres)

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     74 
     75     def compile(self, args, return_type):
---> 76         status, retval = self._compile_cached(args, return_type)
     77         if status:
     78             return retval

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_cached(self, args, return_type)
     88 
     89         try:
---> 90             retval = self._compile_core(args, return_type)
     91         except errors.TypingError as e:
     92             self._failed_cache[key] = e

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_core(self, args, return_type)
    106                                       args=args, return_type=return_type,
    107                                       flags=flags, locals=self.locals,
--> 108                                       pipeline_class=self.pipeline_class)
    109         # Check typing error if object mode is used
    110         if cres.typing_error is not None and not flags.enable_pyobject:

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    970     pipeline = pipeline_class(typingctx, targetctx, library,
    971                               args, return_type, flags, locals)
--> 972     return pipeline.compile_extra(func)
    973 
    974 

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    388         self.lifted = ()
    389         self.lifted_from = None
--> 390         return self._compile_bytecode()
    391 
    392     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    901         """
    902         assert self.func_ir is None
--> 903         return self._compile_core()
    904 
    905     def _compile_ir(self):

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    888         self.define_pipelines(pm)
    889         pm.finalize()
--> 890         res = pm.run(self.status)
    891         if res is not None:
    892             # Early pipeline completion

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    264                     # No more fallback pipelines?
    265                     if is_final_pipeline:
--> 266                         raise patched_exception
    267                     # Go to next fallback pipeline
    268                     else:

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    255                 try:
    256                     event("-- %s" % stage_name)
--> 257                     stage()
    258                 except _EarlyPipelineCompletion as e:
    259                     return e.result

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in stage_nopython_backend(self)
    762         """
    763         lowerfn = self.backend_nopython_mode
--> 764         self._backend(lowerfn, objectmode=False)
    765 
    766     def stage_compile_interp_mode(self):

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _backend(self, lowerfn, objectmode)
    701             self.library.enable_object_caching()
    702 
--> 703         lowered = lowerfn()
    704         signature = typing.signature(self.return_type, *self.args)
    705         self.cr = compile_result(

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in backend_nopython_mode(self)
    688                 self.calltypes,
    689                 self.flags,
--> 690                 self.metadata)
    691 
    692     def _backend(self, lowerfn, objectmode):

D:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1141         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1142                                metadata=metadata)
-> 1143         lower.lower()
   1144         if not flags.no_cpython_wrapper:
   1145             lower.create_cpython_wrapper(flags.release_gil)

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower(self)
    175         if self.generator_info is None:
    176             self.genlower = None
--> 177             self.lower_normal_function(self.fndesc)
    178         else:
    179             self.genlower = self.GeneratorLower(self)

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_normal_function(self, fndesc)
    216         # Init argument values
    217         self.extract_function_arguments()
--> 218         entry_block_tail = self.lower_function_body()
    219 
    220         # Close tail of entry block

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_function_body(self)
    241             bb = self.blkmap[offset]
    242             self.builder.position_at_end(bb)
--> 243             self.lower_block(block)
    244 
    245         self.post_lower()

D:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    256             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 
    260     def create_cpython_wrapper(self, release_gil=False):

D:\ProgramData\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

D:\ProgramData\Anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    668         from numba import config
    669         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 670         six.reraise(type(newerr), newerr, tb)
    671 
    672 

D:\ProgramData\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)

File "<string>", line 3:
<source missing, REPL/exec in use?>

[1] During: lowering "(__numba_self_).next = __numba_val" at <string> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by bohan-gsm** [comment]
This will work.


import numba as nb


next_type = nb.deferred_type()

@nb.jitclass(spec=[
    ('value', nb.float64),
    ('next', nb.optional(next_type)),
])
class Node(object):
    
    def __init__(self, value):
        self.value = 0.
        self.next = None


next_type.define(nb.types.List(Node.class_type.instance_type))

NIL = Node(np.inf)
NIL.next = [Node(np.inf)]

**Comment by esc** [comment]
@bohan-gsm thanks for following up on this issue and solving it yourself!
