### ISSUE TITLE
pycc generated header file is misleading

### ISSUE THREAD

**Issue by seibert** [numba/numba#446]
The header file generated for a numba function by `pycc --header` can't be used for anything because the compiled function produced by pycc doesn't follow the C calling convention.

For example, the Numba function:
```python
import numba
def mysquare(x):
    raise Exception('foo')
    return x * x
numba.export('mysquare f8(f8)')(mysquare)
```
will be compiled by pycc to a function with LLVM IR signature:
```llvm
define i32 @mysquare(double* nocapture, double %arg.x)
```
which cannot be called from a C program using the signature in the pycc-generated header:
```c
extern float64 mysquare(float64);
```

Either the pycc-generated function needs to follow the C calling convention, or the generated C header needs to indicate the Numba calling convention.

**Comment by pitrou** [comment]
Generation of header files is pretty much obsolete now, I think this issue can be closed.
