### ISSUE TITLE
How to express bool arguments to a @guvectorise function?

### ISSUE THREAD

**Issue by davidwynter** [numba/numba#4477]
I asked this question on SO - [how-to-express-bool-arguments-to-a-guvectorise-function](https://stackoverflow.com/questions/57596395/how-to-express-bool-arguments-to-a-guvectorise-function) But no takers so far. Not clear if you monitor the numba tag there. 

Once I get this working I can benchmark, as it is not clear if the classification of the 2 string columns as boolean makes the approach I have still faster than using 4 different vectorized function and splitting the dataframes into 4 each satisfying each condition in the boolean tests in the current function.

**Comment by esc** [comment]
@davidwynter thanks for asking about this, we appreciate it! Let's just say we monitor SO on a best effort basis and your chances of getting an answer are currently (Aug 2019) best if you use the Github issue tracker or our Gitter chat. I'll label this as 'needtriage' for the time being.

**Comment by stuartarchibald** [comment]
I think the issue here is likely due to the use of `not` on a NumPy array, which raises a `ValueError`, it just manifests in Numba as an invalid use of a function.

```python
import numpy as np

def foo(x):
    return not x

z = np.ones(10, dtype=np.bool_)

foo(z) # ValueError: The truth value of an array with more than one element
          # is ambiguous. Use a.any() or a.all()

```

**Comment by dhirschfeld** [comment]
For monitoring SO [this](https://github.com/bots-for-humanity/trio-gitter-bot) bot might be useful?

**Comment by stuartarchibald** [comment]
Thanks for the tip @dhirschfeld

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
