### ISSUE TITLE
Detect workqueue re-entrant to avoid deadlock

### ISSUE THREAD

**Issue by sklam** [numba/numba#4485]
This issue describe a potential fix for https://github.com/numba/numba/issues/4484.

Workqueue should detect re-entrant to avoid deadlock. 

Workqueue (https://github.com/numba/numba/blob/master/numba/npyufunc/workqueue.c) was originally designed for parallel-ufunc. It was later repurpose for handling Parfors (i.e. parallelized array-expr and prange), in which nested parallel region was possible.  However, workqueue was written assuming such nested parallel region is not possible. 

The fix do not need to make the workqueue schedule correctly for nested parallel region, but make it detect such cases and signal an error.

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/commit/1fa4da7c1599bd4e7cb7bb9a7bb9ac851dfacbc4. Closing.
