### ISSUE TITLE
[feature request] user defined priorities of automatic threading layer choice

### ISSUE THREAD

**Issue by ickc** [numba/numba#4486]
## Feature request

In <https://numba.pydata.org/numba-doc/dev/user/threading-layer.html>, it is shown how to select the 3 available threading layers.

This feature request concerns setting relative priorities between this 3 threading layers. i.e. I still want Numba to automatically choose one for me, but I want to specify the priorities between them. For example if the first is not available, fall back to lower priority ones.

The priority I want to set is `'omp', 'tbb', 'workqueue'`. By the way, is the current behavior having the priority of `'tbb', 'omp', 'workqueue'`, i.e. `tbb` is chosen first, and if not available fall back to `omp`, etc.?

**Comment by stuartarchibald** [comment]
I think that this request is feasible and can be accommodated without breaking anyone relying on the current behaviour. @ickc would you perhaps be interested in providing a patch and tests? Thanks.
