### ISSUE TITLE
Loops in Prange produces incorrect result

### ISSUE THREAD

**Issue by sklam** [numba/numba#4489]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Failing example:
```python

@njit(parallel=True)
def foo(N):
    total = 0
    X = np.ones(N)
    for i in prange(-N, 5):
        total += X[i]
        for j in range(-N, 5):
            total += X[j]
    return total

args = [10]
got = foo(*args)
expect = foo.py_func(*args)
print(got, expect)
assert got == expect
```

Also fail with https://github.com/numba/numba/pull/4474.
But this pass on the SSA branch: https://github.com/numba/numba/pull/4445

**Comment by DrTodd13** [comment]
@sklam  Master has SSA integrated right but this issue isn't failing there now so suggest we close.

**Comment by esc** [comment]
I just tried this on master `0.51.0dev0-122-g9ce5c30d32` and it passed fine.
