### ISSUE TITLE
Critical error using "all(...)" or "any(...)" in if statement

### ISSUE THREAD

**Issue by tmillenaar** [numba/numba#4498]
Good day,

When using either an "all(....)" or "any(....)" iteration in an if statement assessment, nonpython mode correctly identifies it as a problem. When using the jit decorator however, I received the following message:

> This should not have happened, a problem has occurred in Numba's internals.
> You are currently using Numba version 0.45.1.
> 
> Please report the error message and traceback, along with a minimal reproducer
> at: https://github.com/numba/numba/issues/new

I did exactly that, so here is a minimal reproducer:

```
from numba import jit
from numpy import random

foo = random.rand(3)

@jit
def testFunc(bar):
    """Do an operation that includes `all()` in an if statement assessment. """
    if( all( value<0.7 for value in bar) ): 
        return "None of the numbers exceeds 0.7!"
    else:
        return "At least one number exceeds 0.7!"
        
result = testFunc(foo)

print(result, foo)
```
If you are already aware of this issue, feel free to discard this message.
Kind regards

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue here is that there's a generator expression in use `value<0.7 for value in bar`. It's quite hard to differentiate between this and yield in a closure, either way, this patch https://github.com/numba/numba/pull/4282 which is going into Numba 0.46.0 catches this and (on my local 0.46.0 development branch) the error is reported:
```python
numba.errors.UnsupportedError: Failed in object mode pipeline (step: inline calls to locally defined closures)
The use of yield in a closure is unsupported.

File "issue4498.py", line 9:
def testFunc(bar):
    <source elided>
    """Do an operation that includes `all()` in an if statement assessment. """
    if( all( value<0.7 for value in bar) ): 
    ^
```
