### ISSUE TITLE
LoweringError iterating over 2D array @numba.jit(nopython=True)

### ISSUE THREAD

**Issue by yusosov** [numba/numba#4508]
#### # FAILS: **This should not have happened**, a problem has occurred in Numba's internals.  You are currently using Numba version 0.45.1...LoweringError: Failed in nopython mode pipeline (step: nopython mode backend) iterating over 2D array...**Please report**...
a=numpy.array([[0, 1],[1, 3],[2, 2]])
@numba.jit(nopython=True)
def f(a):
..for i in a:
....print(i)
f(a)

#### # RUNS WITH A WARNING: Compilation is falling back to object mode WITH looplifting enabled because Function f failed at nopython mode lowering due to: iterating over 2D array
a=numpy.array([[0, 1],[1, 3],[2, 2]])
@numba.jit()
def f(a):
.. for i in a:
....print(i)
f(a)

### I figured out that the way to do what I need:
a=numpy.array([[0, 1],[1, 3],[2, 2]])
@numba.jit(nopython=True, nogil=True, cache=True)
def f(a):
..lst=[]
..for i in range(0,len(a)):
....lst.append(a[i,1])
..return lst(a)
f(a)
### filing the bug because is was requested by @numba.jit error message

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this error in lowering has been reported a sufficient number of times that a fix is needed at typing time, this is done in #4512.

To the specific problem, in `nopython` mode Numba does not have support for direct iteration over arrays with dimension greater than 1. The workaround, as you have discovered, is to use indexing.
