### ISSUE TITLE
Untyped global name 'str': cannot determine Numba type of <class 'type'>

### ISSUE THREAD

**Issue by SrGrace** [numba/numba#4525]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by sklam** [comment]
Can you provide more context? i.e what is the code that triggered the error?

**Comment by SrGrace** [comment]
@sklam 
I was trying to call a function inside a @njit function by typecasting its parameters as str()
code:
 `


    @njit
    def build_document(self):
        """Called only from TreeStructureBuilder::filter()"""

        self.page_id = []
        self.sec_dic = {}
        self.sent_dic = {}
        section_id = []
        h_y2, f_y2 = get_header_footer(self.doc_json)
        for p_idx in prange(len(self.doc_json['pages'])):
            page = self.doc_json['pages'][p_idx]
            # print('Processing page {}'.format(page['page_number']))
            self.page_dic = dict()
            self.page_dic['_id'] = Utils.get_guid()
            self.page_dic['coordinates'] = {'top': 0, 'bottom': page['height'], 'left': 0, 'right': page['width']}
            self.page_dic['fileID'] = self.doc_name
            self.page_dic['index'] = int(page['page_number']) - 1
            self.page_dic['text'] = ""
            self.page_dic['type'] = 'PAGE'
            start = page['height']
            for lines in page['lines']:
                self.page_dic['text'] += lines['text']
                for word in lines['words']:
                    if start > word['top']:
                        start = word['top']
            self.page_dic['textPosition'] = start
            self.page_dic['textLength'] = len(self.page_dic['text'])
            indexes = self.get_section_bboxes(str(self.doc_name + "-" + str(page['page_number'] - 1) + ".jpeg"),
                                              str(self.doc_name + "_" + str(page['page_number'] - 1) + ".jpeg"),
                                              page, h_y2, f_y2, original_tree=False, page=self.page_dic['index'],
                                              fileID=self.page_dic['fileID'])

            # insert rest of your codes here

`

while calling function **get_section_bboxes**, got this error:
`
    Untyped global name 'str': cannot determine Numba type of <class 'type'>
`

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.
