### ISSUE TITLE
Error when converting numpy array to bool

### ISSUE THREAD

**Issue by pj1989** [numba/numba#4526]
The example below is quite self-explanatory. 
```
from numba import njit
import numpy as np

@njit
def fun(a):
    
    if a == 0:
        return True
    return False

fun(a=10) #WORKS
fun(a=np.array([0])) #FAILS
```

In the function above, if the parameter a is passed as a 1-D numpy array, the code fails with the error

> ```
>   File "C:/Users/Luca.amerio/Documents/GitLab/Surface pressure mapping and modal integration/numba_bug.py", line 19, in <module>
>     fun(a=np.array([0]))
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 395, in _compile_for_args
>     raise e
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 352, in _compile_for_args
>     return self.compile(tuple(argtypes))
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 693, in compile
>     cres = self._compiler.compile(args, return_type)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 76, in compile
>     status, retval = self._compile_cached(args, return_type)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
>     retval = self._compile_core(args, return_type)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
>     pipeline_class=self.pipeline_class)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 972, in compile_extra
>     return pipeline.compile_extra(func)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 390, in compile_extra
>     return self._compile_bytecode()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
>     return self._compile_core()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 890, in _compile_core
>     res = pm.run(self.status)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 266, in run
>     raise patched_exception
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 257, in run
>     stage()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 764, in stage_nopython_backend
>     self._backend(lowerfn, objectmode=False)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 703, in _backend
>     lowered = lowerfn()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 690, in backend_nopython_mode
>     self.metadata)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\compiler.py", line 1143, in native_lowering_stage
>     lower.lower()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py", line 177, in lower
>     self.lower_normal_function(self.fndesc)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
>     self.lower_block(block)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
>     self.lower_inst(inst)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\errors.py", line 670, in new_error_context
>     six.reraise(type(newerr), newerr, tb)
> 
>   File "C:\Users\Luca.amerio\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
>     raise value
> 
> LoweringError: Cannot cast array(bool, 1d, C) to bool: %".167" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$0.3"
> ```

Despite being weird having a 1-D np.array, with only 1 number, this occurred in my code due to how  `h5py` loads attributes. This **does not** cause problems in the non-numba version of the code, but it cause the error above if the numba decorator is used.

Most surprisingly, the following versions does **not** cause the error
```
from numba import njit
import numpy as np

@njit
def fun2(a):
    return a == 0

@njit
def fun3(a):
    x = a == 0
    return x

fun2(a=np.array([0])) #WORKS
fun3(a=np.array([0])) #WORKS
```

while the following fails (probably for the same or a similar reason, but with a different (and clearer) error message)

```
from numba import njit
import numpy as np

@njit
def fun4(a):
    return bool(a == 0)

fun4(a=np.array([0])) #FAILS
```

**Comment by sklam** [comment]
I think this is a duplication of https://github.com/numba/numba/issues/4230

**Comment by pj1989** [comment]
> I think this is a duplication of #4230

It is. Sorry for the duplicate. I think this one can be closed
