### ISSUE TITLE
Cannot traverse `DeferredStructModel`

### ISSUE THREAD

**Issue by asodeur** [numba/numba#4538]
Calling `context.nrt.incref/decref` on a deferred type raises exceptions. The root cause seems to be that `DeferredStructModel` cannot be traversed.
```python
from llvmlite import ir
from numba import cgutils, types
from numba.datamodel import models, default_manager, register_default

class DeferredArrayType(types.DeferredType):
    pass

deferred_array_type = DeferredArrayType()
deferred_array_type.define(types.Array(types.float64, 1, 'C'))  # <- actual type should not matter
register_default(DeferredArrayType)(models.DeferredStructModel)


block = ir.Function(  # there might be a simpler way to create a block
    ir.Module(), ir.FunctionType(ir.DoubleType(), ()), 'dummy'
).append_basic_block()
builder = ir.IRBuilder(block)

dm = default_manager[deferred_array_type]
deferred_array = ir.Constant(dm.get_value_type(), None)


for mtyp, getter in dm.traverse(builder):
    print(getter(deferred_array))  # <- raises TypeError
```
fails with the following exception raised:
```python
Traceback (most recent call last):
  File "<module1>", line 23, in <module>
  File "<path_to_numba>\numba\numba\datamodel\models.py", line 1340, in <lambda>
    lambda value: builder.extract_value(value, [0]))]
  File "<path_to_venv>\lib\site-packages\llvmlite\ir\builder.py", line 911, in extract_value
    instr = instructions.ExtractValue(self.block, agg, idx, name=name)
  File "<path_to_venv>\lib\site-packages\llvmlite\ir\instructions.py", line 619, in __init__
    typ = typ.elements[i]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by esc** [comment]
@asodeur thanks for reporting this! I can confirm that I can reproduce this locally.

**Comment by sklam** [comment]
Why are you trying to subclass from `DeferredType`?

**Comment by sklam** [comment]
`DeferredType` is an implementation detail in handling cyclic references between types. It is to provide a kind of forward declaration.  

The datamodel for a deferred type is a `IdentifiedStructType` in llvm.  To traverse over it, it must be defined (not an opaque type anymore).  To resolve this issue, one can put a `self._define` in https://github.com/numba/numba/blob/60d2bddd0a9ddf84cf900a70e4b7e17bcbe5dc87/numba/datamodel/models.py#L1338.

**Comment by gmarkall** [comment]
Closing this as the original question appears to be answered and there have been no further updates for over a year.
