### ISSUE TITLE
numpy array_equal implementaton

### ISSUE THREAD

**Issue by rspadim** [numba/numba#4550]
hi folks, could the array_equal function be implemented with @numba.jit ?

it compare shapes are equal, and if all values are equal

https://github.com/numpy/numpy/blob/v1.17.0/numpy/core/numeric.py#L2299-L2339

**Comment by esc** [comment]
@rspadim thanks for submitting this! I will label it as a feature request accordingly. Also here is a minimal reproducer to show that it is indeed not yet implemented.

```python
from numba import njit
import numpy as np

@njit
def func(a,b):
    np.array_equal(a, b)

c = np.zeros((3,4))
d = np.zeros((3,4))

func(c,d)
```

As a temporary workaround, maybe you could use the following construct?

```python
from numba import njit
import numpy as np

@njit
def func(a,b):
    return np.all(a == b)

c = np.zeros((3,4))
d = np.zeros((3,4))

print(func(c,d))
```

**Comment by esc** [comment]
Also, it should be possible to implement this using `@overload` --- here is some documentation to get started, should you feel the inclination:

https://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html

**Comment by rspadim** [comment]
just include the shape sizes check too
```
@njit
def func(a,b):
    if a.shape!=b.shape:
        return False
    return np.all(a == b)
```
