### ISSUE TITLE
How to deal with NumbaPendingDeprecationWarning?

### ISSUE THREAD

**Issue by endolith** [numba/numba#4553]
My algorithm makes the most sense using `set()`, and numba works with it, but complains that set will be deprecated in the future:

```
NumbaPendingDeprecationWarning:
	Encountered the use of a type that is scheduled for deprecation: type 'reflected set' found for argument 'eliminated' of function '_update_pointer'.

	For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
```

But the typed.Set replacement doesn't exist yet, right?  So I'm a little confused about what I'm supposed to do with this warning.  That page says:

> Projects that need/rely on the deprecated behaviour should pin their dependency on Numba to a version prior to removal of this behaviour

and 

> Deprecation warnings and replacements will be issued in version 0.46.0

So setup.py should contain

```
extras_require={
        'fast':  ["numba<0.46"],
        }
```

and then suppress the warnings?

```
import warnings
from numba import NumbaDeprecationWarning

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=NumbaPendingDeprecationWarning)
    @njit
    def function_that_uses_set():
```

and then when 0.46 is released and provides `typed.Set`, we can update the setup.py to just         `'fast':  ["numba>=0.46"]` and do something like 

```
try:
    from numba import typed.Set as set
except ImportError:
    pass
```

and the two `set` implementations will both work, as long as they are only used to hold a set of integers of the same type?

**Comment by gmarkall** [comment]
Closing this as the issue / question is quite old and hasn't seen any updates for over a year.

**Comment by seanlaw** [comment]
> Once the typed.Set becomes available you can switch to that.

I have come across [this deprecation explanation in the docs](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types) and that `typed.Set` will be implemented. Can anybody please point me to the relevant Github issue that tracks the implementation for `typed.Set`?

Thanks in advance!

**Comment by endolith** [comment]
@gmarkall  Has his been solved?

**Comment by stuartarchibald** [comment]
> > Once the typed.Set becomes available you can switch to that.
> 
> I have come across [this deprecation explanation in the docs](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types) and that `typed.Set` will be implemented. Can anybody please point me to the relevant Github issue that tracks the implementation for `typed.Set`?
> 
> Thanks in advance!

Thanks for asking @seanlaw, there's no tracking issue, but `typed.Set` is being worked on in #8741.
