### ISSUE TITLE
keep the parameter's reference(passed first time) and not free

### ISSUE THREAD

**Issue by yxdragon** [numba/numba#4558]
I find some jit function would keep the parameter first passed, here is a simple demo:

```python
import numpy as np
from numba import jit

@jit
def add_one(img):
    if img.dtype==np.uint8:
        for r in range(img.shape[0]):
            for c in range(img.shape[1]):
                img[r,c] += 1

# extend numpy.ndarray, and overwrite the del method
class Array(np.ndarray):
    def __new__(cls, input_array, name):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    #  print self.name, so I can know if it is deleted
    def __del__(self):
        print('del', self.name)
        
a = Array([[1,2,3]], 'a')
add_one(a)
del a

b = Array([[1,2,3]], 'b')
add_one(b)
del b
```
output:
>>> del b

a could not be deleted, but b can! 
That is just a simple demo, and I do many test
if I remove the "if", a would be deleted!
if I simple the for loop, a would be deleted too!
sometimes, a function with more than 3 parameters (even the parameter is not used), a would not free.
...
I am very confused about these.
but all the function only grab the parameter passed first time
 (every parameter type one time).
if i pass a parameter in other types, the function would grab it too

So, I need help, is it a bug? or how should I write the jit function?

**Comment by yxdragon** [comment]
@stuartarchibald thanks for the reply, I had looked the 5 minute guide. In fact, I am not freshman to numba, but did not see the document for a long time. (I had an opensource project [ImagePy](https://github.com/Image-Py/imagepy) which depend on numba). when I upgrade numba to 0.45, my code report many warning, even cound not run such as this [watershed ](https://github.com/Image-Py/imagepy/blob/master/imagepy/ipyalg/hydrology/watershed.py) algrithm. So now I need to read the document again.

This is an image canvas panel for image label, I write the affine transform, colormap lookup, and front-back ground image blend in numba, purpose to have a fast fps. [canvas](https://github.com/Image-Py/imagepy/blob/master/imagepy/ui/canvas/imutil.py), I had adjust the code in nopython (as your advice), now it runs fine, but it still did not free the reference as said befor.

**Comment by stuartarchibald** [comment]
@yxdragon great, glad you've had some success.

RE the reference held. I cannot reproduce this issue on master or 0.45. I always get:
```
del a
del b
```

**Comment by yxdragon** [comment]
ok, I will change all my code to 0.45.
another question, I found the code to check dtype would cause error in nopython mode.
I want check the dtype, 

if uint8 dim 3, I show it directly.
if uint8 dim 2, use a lookuptable to index, then show it.
if other dtype, scale it to 0-255, then lookuptable, show...

*if arr.dtype is np.uint8:* cause error, So now I write every function in cell(just loop, with no if),
then I wrote the top level function in pure python (no jit)

what is the right way?

**Comment by stuartarchibald** [comment]
IIRC as of 0.45 you cannot compare dtypes at runtime. What you may want is to use `generated_jit` to create a specialization of this function based on type, at compile time.
Here's an example:
```python
from numba import generated_jit, numpy_support
import numpy as np

@generated_jit(nopython=True)
def foo(x):
    dt = numpy_support.as_dtype(x.dtype) # convert the Numba type inferred type to a true NumPy type
    if dt == np.int8:
        def impl(x):
            print("Using int8 implementation")
            return 1
    elif dt == np.uint8:
        def impl(x):
            print("Using uint8 implementation")
            return 2
    else:
        def impl(x):
            print("Using not {u,}int8 implementation")
            return 3
    return impl

foo(np.zeros((10,), np.uint8))
foo(np.zeros((10,), np.int8))
foo(np.zeros((10,), np.float64))
```
The documentation for this feature is here: http://numba.pydata.org/numba-doc/latest/user/generated-jit.html
