### ISSUE TITLE
c++ vs numba compiled code speed

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#4561]
Hi 

I have two piece of code one is python and numba optimized other is c++

and numba compiled is 2x faster than c++.

Codes are below.

python:
```python
@njit
        dist = numpy.sum(np.square(compare_desc - descs))

```

c++:
```c++
 cv::Mat broad;
           cv::Mat features
           broad = features - cmp;
            cv::pow(broad,2,broad);
            cv::reduce(broad, broad, 1, cv::REDUCE_SUM);
```

Is this a fact  ? or what am I doing wrong ? shoulnt the c++ faster ? Or what could be the better way to have faster ?

both Mat and python descs&compare_desc is 512 x float
Best

**Comment by MyraBaba** [comment]
Can you give me some hints to how to compile to reach numba speed on the c++ ?

g++ or clang++ ?  what would be the compiler options *

**Comment by stuartarchibald** [comment]
This is entirely speculation... 

It looks like OpenCV has the ability to do fusion across types adhering to the `MatrixExpression` contract, so I imagine this is happening:
```
            broad = features - cmp;  // matrix expression, new allocation into broad
            cv::pow(broad,2,broad); // broad element wise updated with `pow(2)`
            cv::reduce(broad, broad, 1, cv::REDUCE_SUM); // broad reduced
```
seems like you could try a manual strength reduction, like:
```
            broad = (features - cmp).mul(features - cmp);  // matrix expression, might use `*` not sure?!
            cv::reduce(broad, broad, 1, cv::REDUCE_SUM); // broad reduced
```
which might get compiled into something more efficient?

As to compiler options, perhaps have a look in OpenCV docs/mailing lists/search engine for such advice?

**Comment by max9111** [comment]
The implementation is different. Numba simplifies np.square to a simple multiplication. In your C++ implementation you call a pow function, which very likely calls a general pow(float, int), which is much slower.
