### ISSUE TITLE
How do we get lineinfo while profiling a Numba CUDA application?

### ISSUE THREAD

**Issue by Nischay-Pro** [numba/numba#4573]
Hello,

I would like to get a mapping from CUDA Source to Assembly. 

The nvcc flag for getting this is `-lineinfo`. Is there a way I can get lineinfo in Python Numba Code?

**Comment by stuartarchibald** [comment]
Thanks for the query. The `@cuda.jit` decorator supports the `debug` kwarg which will leave LNS `.loc` entries in the ptx. e.g.
```python
import numpy as np
from numba import cuda

@cuda.jit(debug=True)
def matadd(A, B, C):
    i = cuda.grid(1)
    C[i] = A[i] + B[i]

n = 4
a = np.ones((n,))
result = np.zeros((n,))

matadd[1, 128](a, a, result)

sig = [x for x in matadd.inspect_asm().keys()][0][1]
print(matadd.inspect_asm(sig))
```
see https://sourceware.org/binutils/docs-2.18/as/LNS-directives.html#LNS-directives for encoding.
