### ISSUE TITLE
Use different cuOccupancyMaxPotentialBlockSize call?

### ISSUE THREAD

**Issue by seibert** [numba/numba#4589]
As per https://github.com/numba/numba/pull/4581#issuecomment-532880510, we should investigate if there is a different call we can make that removes the need to create a cfunc that always returns zero.

**Comment by sklam** [comment]
Oh, the callback can be null and the dyanmic-shared-memory size can be passed as a constant:

> If per-block dynamic shared memory allocation is needed, then if the dynamic shared memory size is constant regardless of block size, the size should be passed through dynamicSMemSize, and blockSizeToDynamicSMemSize should be NULL.
