### ISSUE TITLE
Scalar float type signature not respected for both inputs and outputs

### ISSUE THREAD

**Issue by lzlarryli** [numba/numba#4594]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

While array type signatures are respected, scalar type signatures are not.

Example

```
import numpy as np
import numba as nb

@nb.njit('f4(f4)')
def f(x):
    return x + np.float32(1.0)

x = np.float64(2.0)
print(isinstance(f(x), np.float32))

x = np.float32(2.0)
isinstance(f(x), np.float32)
```

Expectation: the first call should fail while the second call should show True.

What happens?

```
False
False
```

Numba version:

```
# conda list numba

# Name                    Version                   Build  Channel
numba                     0.45.1           py37h6440ff4_0  
```

In comparison, the behavior for arrays is correct:

```
import numpy as np
import numba as nb

@nb.njit('f4[:](f4[:])')
def g(x):
    return x + np.array([1.0], dtype=np.float32)

y = np.array([1.0], dtype=np.float32)
print(g(y).dtype)

y = np.array([1.0], dtype=np.float64)
print(g(y).dtype)
```

Output:

```
float32
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-f308276cbb3c> in <module>
     10 
     11 y = np.array([1.0], dtype=np.float64)
---> 12 print(g(y).dtype)

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _explain_matching_error(self, *args, **kws)
    498         msg = ("No matching definition for argument type(s) %s"
    499                % ', '.join(map(str, args)))
--> 500         raise TypeError(msg)
    501 
    502     def _search_new_conversions(self, *args, **kws):

TypeError: No matching definition for argument type(s) array(float64, 1d, C)
```

**Comment by sklam** [comment]
The behavior is expected.

* For arguments, implicit casting for scalar types is allowed.  Float64 can be downcasted to float32.
* For returned values, the compiled function is returning float32 but the bridge between the compiled code and the python interpreter is converting float32 values into a Python `float`. 

All these are caused by numba not modeling number types exactly as in Python or NumPy.

**Comment by lzlarryli** [comment]
I see~ Thanks for the clarification.
