### ISSUE TITLE
Trying Numba with Grakel (Graph kernel, Random Walk)

### ISSUE THREAD

**Issue by nikitabaldan** [numba/numba#4596]
Hi, I'm trying to speed up this snippet of code but it's not working. Any suggestion?
I'm using Grakel as library to compute the graph kernel
```
from sklearn.model_selection import cross_val_score
from grakel import GraphKernel
from grakel import Graph
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from numba import jit, njit, jitclass
import numba
from numba import vectorize,cuda
import time
...
@numba.jit(nopython=True, parallel=True)
def computeKernelSP(graphs):
    print("-- computing kernel")
    start_time = time.time()
    sp_kernel = GraphKernel(kernel=[{"name": "random_walk"}], normalize=True)
    final =  sp_kernel.fit_transform(graphs)
    print("--- %s seconds ---" % (time.time() - start_time))
    return final
```
Thanks so much

**Comment by stuartarchibald** [comment]
Thanks for the report. If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

What you have in the above code cannot be compiled as Numba doesn't know about `GraphKernel` or `grakel` in general.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
