### ISSUE TITLE
CUDA Library Load (check prefix)

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#4613]
## Feature request

When searching for the CUDA libraries, it would be nice if Numba checked `sys.prefix` for them as well. In a Conda environment, this maps to the prefix of the environment. So this would ensure CUDA libraries that are part of the `cudatoolkit` Conda package are also found without needing an environment variable.

**Comment by stuartarchibald** [comment]
Thanks for the request. This should already be happening (since 0.44). 
https://github.com/numba/numba/blob/2da803c60bd484012fce92bbdf31f4335501ec95/numba/cuda/cuda_paths.py#L112-L123

Is it not working/doing something unexpected?

**Comment by jakirkham** [comment]
We find ourselves still needing to set `NUMBAPRO_NVVM` and `NUMBAPRO_LIBDEVICE` despite both being deprecated for a while now. ( https://github.com/numba/numba/pull/4096 )

**Comment by seibert** [comment]
Still not sure I understand.  Those variables were replaced with the much more common`$CUDA_HOME` environment variable.  Are those also not working?

**Comment by stuartarchibald** [comment]
@jakirkham Please shout if there's a demonstrable problem with what is present in 0.45. Docs for the replacements for `NUMBAPRO_*` are here: http://numba.pydata.org/numba-doc/latest/cuda/overview.html#setting-cuda-installation-path

We're a couple of days away from cutting a 0.46RC1 and if there is a problem it'd be great to get it fixed for it! (I'm also changing this section of the code base right now to accommodate the deprecations, so it's high in my memory at present!). Thanks.

**Comment by jakirkham** [comment]
Will do. Thanks @stuartarchibald! 😀

**Comment by jakirkham** [comment]
Apologies. This seems to work correctly. I think I confused myself.

**Comment by stuartarchibald** [comment]
@jakirkham No problem, thanks for checking and getting back to us.
