### ISSUE TITLE
numba fail to import after succesful installation (centos py2.7)

### ISSUE THREAD

**Issue by epifanio** [numba/numba#462]
Hi All,

i'm trying to install nuba and blaze on a centos linux distribution I installed python and all the numba dependencies from source, the installation ends without error but trying to import the library i got this log : 

https://gist.github.com/6cb0495902ddc8bed397

```
AttributeError: 'module' object has no attribute 'dylib_add_symbol'
```
is ```dylib_*``` an osx specific dynamic library object? 
  
other lib like : llvm and blz are imported correctly.
Am i missing to export some environment var? or have you any clue on what's wrong ?

**Comment by pitrou** [comment]
This is outdated. If you have trouble with a recent numba version, consider opening a new issue. Thanks!
