### ISSUE TITLE
numba fallback because 'spdiags': cannot determine Numba type of <class'function'>

### ISSUE THREAD

**Issue by AJJLagerweij** [numba/numba#4627]
Dear developers or community,

I'm exploring the options to use @jit/@njit to speed up code in my optimization [project](https://github.com/AJJLagerweij/topopt).
Up until now I've tried to write 'fast' code by relying on routines in external packages (such as numpy, scipy and cvx) which works reasonably well. Currently, my project has two bottlenecks, the [finite element solver](https://github.com/AJJLagerweij/topopt/blob/master/src_Actuator/fesolvers.py) and the [MMA update scheme](https://github.com/AJJLagerweij/topopt/blob/1ad20e0bf961301ebca7a07205d02a51b7827196/src_Actuator/topopt.py#L508-L695).
The Method of Moving Asymptotes update scheme and its mathematical explanation can be found [here](https://www.doi.org/10.1002/nme.1620240207).
I want to try using numba to speed up the update scheme, I think that it is a great target for jit/njit because of the amount of (array) multiplications and loops that are being performed.

I tried to use the @jit command but I run into issues because of the scipy.sparse.spdiags functions that I use. What can I do to allow my code to work with numba? (Both advice on changes it the algorithm implementation or from the numba side are welcome)
Be aware that even for small problems the sparse matrix can become of the size (10000, 10000) and it blows up quickly for more complex problems.

Regards,
Bram Lagerweij

The terminal reports:
```
/home/bram/Documenten/TUDelft/Thesis/Phyton/topopt/src_Compliance/topopt.py:490: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "solvemma" failed type inference due to: Untyped global name 'spdiags': cannot determine Numba type of <class 'function'>

File "topopt.py", line 571:
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
        <source elided>
                gvec = np.dot(P, uxinv1) + np.dot(Q, xlinv1)
                GG = P*spdiags(uxinv2, 0, n, n) - Q*spdiags(xlinv2, 0, n, n)
                ^

  @jit
/home/bram/Documenten/TUDelft/Thesis/Phyton/topopt/src_Compliance/topopt.py:490: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "solvemma" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "topopt.py", line 524:
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
        <source elided>
        s = eem
        itera = 0
        ^

  @jit
/home/bram/.anaconda3/envs/TopOpt_Linux/lib/python3.6/site-packages/numba/compiler.py:742: NumbaWarning: Function "solvemma" was compiled in object mode without forceobj=True, but has lifted loops.

File "topopt.py", line 491:
    @jit
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
    ^

  self.func_ir.loc))
/home/bram/.anaconda3/envs/TopOpt_Linux/lib/python3.6/site-packages/numba/compiler.py:751: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "topopt.py", line 491:
    @jit
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
    ^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
/home/bram/Documenten/TUDelft/Thesis/Phyton/topopt/src_Compliance/topopt.py:490: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "solvemma" failed type inference due to: Untyped global name 'spdiags': cannot determine Numba type of <class 'function'>

File "topopt.py", line 571:
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
        <source elided>
                gvec = np.dot(P, uxinv1) + np.dot(Q, xlinv1)
                GG = P*spdiags(uxinv2, 0, n, n) - Q*spdiags(xlinv2, 0, n, n)
                ^

  @jit
/home/bram/.anaconda3/envs/TopOpt_Linux/lib/python3.6/site-packages/numba/compiler.py:742: NumbaWarning: Function "solvemma" was compiled in object mode without forceobj=True.

File "topopt.py", line 524:
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
        <source elided>
        s = eem
        itera = 0
        ^

  self.func_ir.loc))
/home/bram/.anaconda3/envs/TopOpt_Linux/lib/python3.6/site-packages/numba/compiler.py:751: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "topopt.py", line 524:
    def solvemma(self, m, n, epsimin, low, upp, alfa, beta, p0, q0, P, Q, a0, a, b, c, d):
        <source elided>
        s = eem
        itera = 0
        ^
```

P.S. I'm not sure if this is the correct place to ask about how to use numba. Just tell me if I need to shift to another forum.

P.P.S. For the FE solver I'll focus on selecting a more efficient solving method using a conjugate gradient multigrid implementation before working on the code implementation itself.

**Comment by stuartarchibald** [comment]
Thanks for the query.

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

Numba does not support SciPy yet, though efforts are under way to do that here https://github.com/numba/numba-scipy, but this started only a few weeks ago. Also, in general, only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

The quickest way to get your code going would probably be to write the e.g. `spdiags` implementation and the `np.dot` for sparse diagonals by hand as a `@jit` decorated function (there's no penalty for writing loops in Numba, in fact, it quite likes them). Same goes for anything else unsupported.

Hope this helps.

**Comment by AJJLagerweij** [comment]
Thanks this most definitely helps.
Its a pity that scipy is not yet supported, but cool that you are working on it.
I'll be spending my time on converting the equation with the diagonals into other expressions.

I am curious about one detail however, the speed of numpy inside a `@jit` decorated equation.
Do the numpy features speed up as well when you use `@jit`?
Do you expect a (significant) difference in speed between between the following cases:

1) No numpy, everything written inside loops, and using `@jit` to speed up the overarching definition.
2) Using numpy arrays to do the same computations and using `@jit` around the overarching definition.

Thanks a lot

**Comment by stuartarchibald** [comment]
> Thanks this most definitely helps.

No problem.

> Its a pity that scipy is not yet supported, but cool that you are working on it.
> I'll be spending my time on converting the equation with the diagonals into other expressions.
> 
> I am curious about one detail however, the speed of numpy inside a `@jit` decorated equation.
> Do the numpy features speed up as well when you use `@jit`?

It depends, individual functions are unlikely to be any faster, e.g. the `exp` function called on a `np.ndarray`  from NumPy or Numba is fundamentally limited by the speed of `exp`. Same goes for e.g. `np.dot` where the underlying BLAS implementation is the fundamental limit on speed.

> Do you expect a (significant) difference in speed between between the following cases:
> 
>     1. No numpy, everything written inside loops, and using `@jit` to speed up the overarching definition.
> 
>     2. Using numpy arrays to do the same computations and using `@jit` around the overarching definition.

This will depend on the use case. It's generally a good idea to create code that works and is well tested first, then profile it, then start changing things to note the impact.

Numba does some things internally like it fuses ufunc expressions that are all on the same logical line into a single expression, this can be enough under the conditions noted above to make the performance the same, but it can also be insufficient.

> 
> Thanks a lot

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
