### ISSUE TITLE
CUDA device arrays are always 'A' order and they probably shouldn't be.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4628]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

There may be good reasons for this that I'm yet to discover. But this:
```python
from numba import cuda
import numpy as np
import math

@cuda.jit
def func(A, out):
    i = cuda.grid(1)
    out[i] = math.cos(A[i])

n = 4
a = np.ones((n,))
result = np.zeros((n,))

func[1, 128](a, result)

for f in func.definitions:
    print(f, func.definitions[f])

d_a = cuda.to_device(a)
func[1, 128](d_a, result)

print("After device array")
for f in func.definitions:
    print(f, func.definitions[f])
```
does this:
```
((5, 0), (array(float64, 1d, C), array(float64, 1d, C))) <numba.cuda.compiler.CUDAKernel object at 0x7fe2ae2de748>
After device array
((5, 0), (array(float64, 1d, C), array(float64, 1d, C))) <numba.cuda.compiler.CUDAKernel object at 0x7fe2ae2de748>
((5, 0), (array(float64, 1d, A), array(float64, 1d, C))) <numba.cuda.compiler.CUDAKernel object at 0x7fe2ae256978>
```
i.e. the device array is typed as `array(float64, 1d, A),` which triggers a recompilation. Further, this seems to be hardcoded:
https://github.com/numba/numba/blob/3825f12cddecdf8c3af2fa75eff935f2e5617263/numba/cuda/cudadrv/devicearray.py#L153-L160

such that all device arrays `numba.typeof` as "A" order.

**Comment by stuartarchibald** [comment]
Related discussion on gitter: https://gitter.im/numba/numba?at=5d8e32aeeb1eff63d635062a, seems like CuPy arrays are also appearing 'A' ordered.

CC: @leofang @beckermr

**Comment by leofang** [comment]
Thanks a lot @stuartarchibald for experimenting and reporting for us. I'd have thought the other way around. Looks like Numba is silently converting 'C' (or 'F') to 'A' somewhere? Because in CuPy only 'C' and 'F' are supported: https://github.com/cupy/cupy/blob/36ecb4423762a79aea98bd1bbb40a3903d28ac18/cupy/core/core.pyx#L106-L107

**Comment by stuartarchibald** [comment]
> Thanks a lot @stuartarchibald for experimenting and reporting for us.

No problem

> I'd have thought the other way around. Looks like Numba is silently converting 'C' (or 'F') to 'A' somewhere? Because in CuPy only 'C' and 'F' are supported: https://github.com/cupy/cupy/blob/36ecb4423762a79aea98bd1bbb40a3903d28ac18/cupy/core/core.pyx#L106-L107

yes, well, seems like device arrays are typed as 'A' ordered irrespective of what they are in reality https://github.com/numba/numba/blob/3825f12cddecdf8c3af2fa75eff935f2e5617263/numba/cuda/cudadrv/devicearray.py#L153-L160 not sure what happens to a CuPy array in typing, but would guess the same, will check.

**Comment by leofang** [comment]
Thanks for the fix, @gmarkall!
