### ISSUE TITLE
Method never returns

### ISSUE THREAD

**Issue by JackMcCoy** [numba/numba#4634]
Hope this isn't an abuse of this issues forum, but I am trying to speed up a part of my code where I'd like to reverse the keys and values of a dictionary and combine those new values that have the same key into lists of values (the original dict is derived from a pandas Series, where multiple records have the same value, and I'd like a dict of the values and their index locations). I had a helluva time trying to get numba to recognize the types of values of the Dict() I was sending once it came time to put those values in a new list, then I decided to try passing lists of the keys and values separately. Wrangled with types for a while, then hit on this code that doesn't produce any errors when defined, but when I run it, it seems to go forever, never returning anything. Thoughts?

Note: k and v are lists of equal length.

```
@njit
def x(k,v):
    dk = List()
    dv = List()
    for i in range(len(k)):
        if len(dk) == 0:
            dk.append(v[i])
            item = k[i]
            templist = [item]
            dv.append(templist)
        else:
            flag = False
            for j in range(len(dk)):
                if dk[j] == v[i]:
                    flag = True
                    dv[j].append(k[i])
            if flag == False:
                dk.append(v[i])
                newItem = k[i]
                newList = [newItem]
                dv.append(newList)
    output = dict()
    for i in range(len(dk)):
        targetkey = dk[i]
        targetval = dv[i]
        output[targetkey]= np.array(targetval, np.int64)
    return output
```

The output I get gives me depreciation warnings about reflected lists, one for k and one for v, and then never returns. Running it with two typed Lists (which I'd rather not use, for times sake), produces no warnings, but still no return.

**Comment by esc** [comment]
@JackMcCoy I tried to run this with the following input:

```
a = List()
[a.append(i) for i in range(10)]
b = List()
[b.append(i) for i in range(10)]

print(x(a, b))
``` 

And the function returns w/o issues. Could you provide some sample input perhaps?

**Comment by JackMcCoy** [comment]
Okay, yes - this works for me as well, and when I run the method with my data as typed Lists (one of ints, the other of strings, which is the data I'm working with), it works as well. It never returned (or seemed to never return - I probably didn't give it long enough) when I used untyped lists, and when I tested with typed lists I didn't give it enough (I'm using this on lists with lengths of perhaps 50k-200k). I knew it wasn't the most straightforward way of doing what I want, but hadn't realized just how awful it was. Sorry for jumping the gun!

If you have the time - the real way I want to do this is along the lines of the following:

```
array_type = types.int64[:] 
@njit 
def x(dicttoreverse): 
    output=Dict.empty(key_type=types.string,value_type=array_type,) 
    for key, val in dicttoreverse.items(): 
        current = output.setdefault(val,List()) 
        current.append(key) 
        output[val]=current 
    return output 
```

However, when I try running this with a typed Dict (with the same key/value types, but reversed) as a parameter, I get the error that "Undecided type $28.12 := <undecided>" for the "current.append(key)" line.

**Comment by JackMcCoy** [comment]
Spent a couple hours messing with signatures/ reading through code, got nowhere then figured out the below, which works. Numba is a strange, yet wonderful beast.

```
array_type = types.int64[:] 
@njit 
def x(dicttoreverse): 
    output=Dict() 
    for key, val in dicttoreverse.items(): 
        if val in output: 
            newval = output[val] 
            newval.append(types.int64(key)) 
            output[val]=newval 
        else: 
            current = List() 
            current.append(types.int64(key)) 
            output[val]=current 
    return output 
```

**Comment by esc** [comment]
@JackMcCoy great! Glad you managed to get it to work and thanks for following up and closing this issue!
