### ISSUE TITLE
ImportError: cannot import name 'jit' from 'numba'

### ISSUE THREAD

**Issue by RajanZhan** [numba/numba#4638]
this is my code ,
`
from numba import jit

  `
 I m sure that my numba is installed,  pip list like this:

Package        Version
-------------- ---------
altgraph       0.16.1
future         0.17.1
llvmlite       0.29.0
numba          0.45.1
numpy          1.17.2
pefile         2019.4.18
pip            19.2.3
PyInstaller    3.5
pywin32-ctypes 0.2.0
setuptools     40.6.2

why I cant not import jit from numba ?

**Comment by esc** [comment]
@RajanZhan thanks for asking about this on the Numba issue tracker. The line `from numba import jit` will work if Numba is correctly installed. Given the limited view I have I suspect that the `python` that you are using is a different `python` than the one that has `pip` and `numba` installed. Depending on your operating system, you may be able to figure how many and which Pythons are installed using `which -a python`. That may shed further light onto why you can not import `jit` from `numba`.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Comment by sekrett** [comment]
I have the same on Ubuntu 20.04, Python 3.8. I created a fresh virtualenv.

% which -a python
/home/..../venv/bin/python

% which -a pip   
/home/..../venv/bin/pip

% pip freeze     
numba==0.52.0
numpy==1.19.4
opencv-contrib-python==4.4.0.46
opencv-python==4.4.0.46
Pillow==8.0.1
pkg-resources==0.0.0
pyocr==0.7.2
pytesseract==0.3.7

**Comment by stuartarchibald** [comment]
@sekrett Thanks for raising this, I'm not sure that this is the same issue as originally reported. Numba moved `numba.jitclass` to `numba.experimental.jitclass` a while back, warnings were issued along with the path deprecation cycle added to the docs. With numba=0.52 try `from numba.experimental import jitclass`.

**Comment by sekrett** [comment]
Thank you, useful to know in the future. I realised currently `jitclass` is not used in that code, so I commented it out.

**Comment by kuangllbnu** [comment]
I use conda to install the numba. When I run in the python cmds in the Promt UI, it runs ok.
When I write it in to a script file named such as _test.py_, then execute the script the error accur 
`ImportError: cannot import name 'jit' from partially initialized module 'numba'`

PS: The python script is an example from the user manual
`from numba import jit
import numpy as np
import time

x = np.arange(100).reshape(10, 10)

@jit(nopython=True)
def go_fast(a): # Function is compiled and runs in machine code
    trace = 0.0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (with compilation) = %s" % (end - start))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))
`

**Comment by deepakcrk** [comment]
I got this error due to python script filename.

When my filename is `timeit.py`, I got this: `ImportError: cannot import name 'jit' from partially initialized module 'numba'`

Issue was resolved on renaming the file.
