### ISSUE TITLE
Unsupported functionality was found in the code Numba was trying to compile.

### ISSUE THREAD

**Issue by smyhlin** [numba/numba#4639]
```
def fillDB(client):
    <source elided>
        username = str(u.user.username).replace('None', '')
        try:
        ^
```
"try" not suppported?((

**Comment by esc** [comment]
@smyhlin thanks for reporting this issue and yes you are correct `try` isn't supported:

http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#language

**Comment by esc** [comment]
This is a duplicate of https://github.com/numba/numba/issues/4019
