### ISSUE TITLE
[Help] TypeError CUDA kernel or TypingError Numba type

### ISSUE THREAD

**Issue by tausia** [numba/numba#4649]
Good afternoon, I would like to ask for your help with my code.
I need to make a confusion matrix with the results of comparing faces using [face_recognition](https://github.com/ageitgey/face_recognition) of ageitgey.

I have many images (5750 dirs/people and 13290 images total) to compare between them, as expected, it takes a long time to finish.

That is why I am testing CUDA, because I have read that using the GPU reduces computation time, and Numba is the option that gives more search results.
But I have problems with it, which I hope someone can solve.

The code:<details>
```
from imutils import paths
import cv2, timeit
import numpy as np
from face_recognition import compare_faces, face_encodings

from numba import cuda

#@cuda.jit
@cuda.jit("u2(f8[:], f8[:])")
def compareFaces(imageCheck, imageKnown):
    #compare_faces return a list of True/False values
    results = compare_faces([imageKnown], imageCheck, 0.4)
    
    if True in results:
        return 1
    else:
        return 0

def main():
    There are 3 loops: for each row, column and calc the result
    [...]
            # face_encodings return a list of 128-dimensional face encodings
            imageKnown = face_encodings(cv2.imread(imagePathKnown))[0]
            imageCheck = face_encodings(cv2.imread(imagePath2Check))[0]
            
            count=( count + compareFaces(imageCheck, imageKnown) )
            
        confMatrix[i][j]=float("%.2f" % (count/(k+1)))

if __name__ == "__main__":
    main()
```
</details>

Using <b>@cuda.jit("u2(f8[:], f8[:])")</b> return <b>CUDA kernel must have void return type.</b></br> Or using <b>@cuda.jit</b> return <b>cannot determine Numba type of <type 'function'></b>

What do you think I'm wrong about? Is Numba what I'm looking for?

PD: I have also tried using CUDA in the <b>encode_faces.py</b> code from [pyimagesearch.com](https://www.pyimagesearch.com/2018/06/18/face-recognition-with-opencv-python-and-deep-learning/) with the same result.

**Comment by esc** [comment]
@tausia thanks for asking about this on the Numba issue tracker, we appreciate your input. In your case I am not sure that Numba is the right tool. In the example above you are trying to run `compare_faces`  as part of your GPU code but haven't told Numba about how to compile `compare_faces`.

I think what you are looking for is a solution for running embarrassingly parallel code (https://en.wikipedia.org/wiki/Embarrassingly_parallel), two good solutions here are:

* https://joblib.readthedocs.io/en/latest/
* https://dask.org/

If, on the other hand, you want to know more about how Numba can make use of GPUs, I would suggest the following set of Notebooks:

* https://github.com/numba/euroscipy2019-numba

**Comment by tausia** [comment]
> @tausia thanks for asking about this on the Numba issue tracker, we appreciate your input. In your case I am not sure that Numba is the right tool. In the example above you are trying to run `compare_faces` as part of your GPU code but haven't told Numba about how to compile `compare_faces`.
> 
> I think what you are looking for is a solution for running embarrassingly parallel code (https://en.wikipedia.org/wiki/Embarrassingly_parallel), two good solutions here are:
> 
> * https://joblib.readthedocs.io/en/latest/
> * https://dask.org/
> 
> If, on the other hand, you want to know more about how Numba can make use of GPUs, I would suggest the following set of Notebooks:
> 
> * https://github.com/numba/euroscipy2019-numba

Thanks for answering, as you said, I'm not sure how to tell Numba how to compile <code>compare_faces</code>, that's why I assumed that <b>@cuda.jit("u2(f8[:], f8[:])")</b> was necessary.

I will test your proposed solutions.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
