### ISSUE TITLE
This error is usually caused by passing an argument of a type that is unsupported by the named function

### ISSUE THREAD

**Issue by paulomann** [numba/numba#4650]
The following does not compile with Numba. I have no idea why, though.

```Python
@jit(nopython=True)
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0])
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx
```
**The error:**

numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float64, 1d, C), int64, array(float32, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at .../imgsim.py (135)

File "imgsim/imgsim.py", line 135:
def _get_most_similar(
    <source elided>
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
        ^

**Comment by guilhermeleobas** [comment]
Hi @paulomann,

I think your problem is that `query_ftrs` be a `np.float32` array and `ftrs` be a `np.float64` array. Try to cast both to have the same type.

Not all NumPy functions are available on Numba but `np.dot` seems to be supported:
```python
from numba import njit
import numpy as np

@njit
def foo(a, b):
    return np.dot(a, b)

a = np.array([1, 2, 3], dtype=np.float64)
b = np.array([1, 2, 3], dtype=np.float64)
c = foo(a, b)
print(c) # works just fine
```

**Comment by paulomann** [comment]
I have already tried casting both to the same type. Still getting the same errors.

**Comment by guilhermeleobas** [comment]
Can you please post the entire error report produced by Numba?

**Comment by stuartarchibald** [comment]
@paulomann are you doing something like this?:
```python
from numba import njit
import numpy as np

@njit
def _get_most_similar(query_ftrs, all_images_ftrs):
    products = np.empty(all_images_ftrs.shape[0])
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx


a = np.zeros((10, 10))
b = np.zeros((10, 10))

_get_most_similar(a, b)
```
which will produce the error above, it's because the code is trying to set an element of `products` (which is a 1d NumPy array) to the value from the `np.dot` (which is also a 1d NumPy array). This won't work plain in NumPy either.
```python
from numba import njit
import numpy as np

#@njit <------- NOT GOING TO USE NUMBA
def _get_most_similar(query_ftrs, all_images_ftrs):
    products = np.empty(all_images_ftrs.shape[0])
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx


a = np.zeros((10, 10))
b = np.zeros((10, 10))

_get_most_similar(a, b)
```
gives:
```
$ python issue4650.py 
Traceback (most recent call last):
  File "issue4650.py", line 16, in <module>
    _get_most_similar(a, b)
  File "issue4650.py", line 8, in _get_most_similar
    products[i] = np.dot(query_ftrs, ftrs)
ValueError: setting an array element with a sequence.
```

**Comment by paulomann** [comment]
Hello @stuartarchibald, thanks for your kindly reply. In fact, I am doing something like this:

``Python
a = np.zeros(10)
b = np.zeros((10,10))
_get_most_similar(a, b)
``
@guilhermeleobas 

With variables as
query_ftrs size: (1, 2048)
all_images_ftrs size: (18536, 2048)
query_ftrs dtype: float32
all_images_ftrs dtype: float32

I receive the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../Documentos/img-sim/imgsim/imgsim.py", line 237, in <module>
    ".../Documentos/img-sim/data/query_images/96611fdd-17b7-4cc0-851d-d06b13d1667d.png"
  File ".../Documentos/img-sim/imgsim/imgsim.py", line 164, in get_most_similar
    sorted_idx = _get_most_similar(query_ftrs, all_images_ftrs)
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File ".../anaconda3/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float32, 1d, C), int64, array(float32, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at .../imgsim.py (135)

File "imgsim/imgsim.py", line 135:
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    <source elided>
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by paulomann** [comment]
When testing with the code 

```Python
from numba import jit
@jit(nopython=True)
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i, ftrs in enumerate(all_images_ftrs):
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx

a = np.zeros(10)
b = np.zeros((10,10))
_get_most_similar(a, b)
```
I get the following error:

Traceback (most recent call last):
  File ".../anaconda3/lib/python3.7/site-packages/numba/errors.py", line 627, in new_error_context
    yield
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 454, in lower_assign
    return self.lower_expr(ty, value)
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 937, in lower_expr
    res = impl(self.builder, (castval,))
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1132, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1157, in wrapper
    return fn(*args, **kwargs)
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/imputils.py", line 311, in wrapper
    _IternextResult(context, builder, pairobj))
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/iterators.py", line 58, in iternext_enumerate
    srcres = call_iternext(context, builder, enumty.source_type, enum.iter)
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/imputils.py", line 337, in call_iternext
    val = iternext_impl(builder, (val,))
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1132, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1157, in wrapper
    return fn(*args, **kwargs)
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/imputils.py", line 311, in wrapper
    _IternextResult(context, builder, pairobj))
  File ".../anaconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 288, in iternext_array
    raise NotImplementedError("iterating over %dD array" % arrayty.ndim)
NotImplementedError: iterating over 2D array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 658, in compile
    cres = self._compiler.compile(args, return_type)
  File ".../anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 244, in run
    stage()
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 731, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 681, in _backend
    lowered = lowerfn()
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 668, in backend_nopython_mode
    self.metadata)
  File ".../anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1063, in native_lowering_stage
    lower.lower()
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File ".../anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File ".../anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../anaconda3/lib/python3.7/site-packages/numba/errors.py", line 635, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File ".../anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
iterating over 2D array

File "imgsim/imgsim.py", line 134:
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    <source elided>
    for i, ftrs in enumerate(all_images_ftrs):
    ^

[1] During: lowering "$32.2 = iternext(value=$phi32.1)" at .../imgsim/imgsim.py (134)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment]
Iterating over 2D arrays is not supported. That it appears as a `LoweringError` is bad, I'll make a ticket to fix that. In the mean time, try this:

```python
from numba import njit
import numpy as np

@njit
def _get_most_similar(query_ftrs, all_images_ftrs):
    products = np.empty(all_images_ftrs.shape[0])
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx


a = np.zeros((10,))
b = np.zeros((10, 10))

out_numba = _get_most_similar(a, b)
out_numpy = _get_most_similar.py_func(a, b)

np.testing.assert_allclose(out_numba, out_numpy)
```

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/4653

**Comment by paulomann** [comment]
Thanks a lot, @stuartarchibald. However, I am still having problems when integrating the code with my pipeline, as I mentioned [here](https://github.com/numba/numba/issues/4650#issuecomment-537498532). Still, I don't know why.

**Comment by stuartarchibald** [comment]
Please could you post a full working reproducer for the problem you are seeing, including inputs (dummy ones are fine), it'll be a lot easier to debug if the errors can be reproduced locally. Thanks.

**Comment by paulomann** [comment]
```Python
from numba import njit
@njit
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs)
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx


def get_most_similar(query_image_path: Path, k: int = 20) -> List[Path]:
    """
    Parameters:
    -----------
    query_image_path: query image path
    k: the number of top k most similar pictures to the query image.

    Returns
    -------
    The list of images paths (of size k) sorted in decreased similarity with 
    the query image
    """
    query_ftrs = get_query_features(query_image_path, save_vectors=False)
    features_path = os.path.join(
        settings.FEATURES_NPY_FOLDER, settings.FEATURES_NPY_DUMP
    )
    all_images_ftrs = np.load(features_path + ".npy")
    with open(features_path + ".txt", "r") as f:
        files_paths = f.read().splitlines()
    query_ftrs = np.zeros((1, 2048), dtype="float32")          # <--------
    all_images_ftrs = np.zeros((18536, 2048), dtype="float32") # <--------
    sorted_idx = _get_most_similar(query_ftrs, all_images_ftrs)
    most_similar_pictures = []
    for idx in sorted_idx[0:k]:
        file_path = files_paths[idx]
        most_similar_pictures.append(eval(file_path))
    return most_similar_pictures
```
This code above returns this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paulomann/Documentos/img-sim/imgsim/imgsim.py", line 162, in get_most_similar
    sorted_idx = _get_most_similar(query_ftrs, all_images_ftrs)
  File "/home/paulomann/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/paulomann/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "/home/paulomann/anaconda3/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(float32, 1d, C), int64, array(float32, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at /home/paulomann/Documentos/img-sim/imgsim/imgsim.py (136)

File "imgsim/imgsim.py", line 136:
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    <source elided>
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs)
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by stuartarchibald** [comment]
Thanks for sharing that, this is a working minimal reproducer:
```python
from numba import njit
import numpy as np

@njit
def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs)

query_ftrs = np.zeros((1, 2048), dtype="float32")
all_images_ftrs = np.zeros((18536, 2048), dtype="float32")

_get_most_similar.py_func(query_ftrs, all_images_ftrs) # numpy is fine

_get_most_similar(query_ftrs, all_images_ftrs) # numba is not
```

**Comment by stuartarchibald** [comment]
Running this code:
```python
import numpy as np


def _get_most_similar(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        def print_info(name, var):
            print("%s: shape: %s, ndim:%s, size:%s" %
                  (name, var.shape, var.ndim, var.size))
        print_info("query_ftrs", query_ftrs)
        print_info("ftrs", ftrs)
        tmp = np.dot(query_ftrs, ftrs)
        print_info("tmp", tmp)
        print_info("products[i]", products[i])
        products[i] = tmp
        break


query_ftrs = np.zeros((1, 2048), dtype="float32")
all_images_ftrs = np.zeros((18536, 2048), dtype="float32")

_get_most_similar(query_ftrs, all_images_ftrs) # numpy is fine
```
gives this:
```
query_ftrs: shape: (1, 2048), ndim:2, size:2048
ftrs: shape: (2048,), ndim:1, size:2048
tmp: shape: (1,), ndim:1, size:1
products[i]: shape: (), ndim:0, size:1
```
I think the issue here is that the `np.dot` call is effectively performing an inner product between a `(1, N)` and an `(N,)` sized array, this yields a 1d array containing 1 element. What is not happening in Numba is degrading this 1d array of size 1 into a single value as required by the assignment into `products[i]`. A work around would be to just get the zero-th index the result of the inner product and use that in the assignment. e.g.
```python
from numba import njit
import numpy as np


@njit
def _get_most_similar_numba(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs)[0] # INDEX IS HERE
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx


def _get_most_similar_numpy(query_ftrs: np.ndarray, all_images_ftrs: np.ndarray) -> np.ndarray:
    products = np.empty(all_images_ftrs.shape[0], dtype=query_ftrs.dtype)
    for i in range(len(all_images_ftrs)):
        ftrs = all_images_ftrs[i]
        products[i] = np.dot(query_ftrs, ftrs) # NO INDEX HERE
    sorted_idx = np.argsort(products)[::-1]
    return sorted_idx

np.random.seed(0)
# NOTE use of float64, float32 has rounding problems in the np.dot
query_ftrs = np.random.random((1, 2048)).astype(np.float64)
all_images_ftrs = np.random.random((18536, 2048)).astype(np.float64)

nb_result = _get_most_similar_numba(query_ftrs, all_images_ftrs)
np_result = _get_most_similar_numpy(query_ftrs, all_images_ftrs)

np.testing.assert_allclose(np_result, nb_result)
```
a minimal reproducer for this issue is:
```python
from numba import njit
import numpy as np

@njit
def foo():
    a = np.zeros((5,))
    a[0] = np.ones((1,))


foo.py_func() # numpy fine
foo() # numba broken
```
fixing it will likely require implementing specific NumPy scalar types such that an indexing operation like ` a[0]` in the above will be type inferred as a NumPy scalar type and then behaviours such as this assignment may be permitted, but would still need a run time check for cases where there's more than one element in the array on the RHS, e.g.
```python
def foo():
    a = np.zeros((5,))
    a[0] = np.ones((1,))  #fine
    a[0] = np.ones((1,1))  #fine
    a[0] = np.ones((2,)) # bad
```

**Comment by paulomann** [comment]
Really smart conclusion, @stuartarchibald. I appreciate the detailed answer, thanks a lot for that. You taught me how to inspect problems better :).

My problem is now solved.
