### ISSUE TITLE
induced >1d array iteration should be caught at type inference time

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4653]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    for _ in enumerate(x):
        pass

foo(np.zeros((10, 10)))
```
produces a LoweringError:
```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
iterating over 2D array
```
it should be caught at type inference time.

**Comment by eric-wieser** [comment]
Looks like auto-close didn't work here
