### ISSUE TITLE
Implement a pygments lexer for Numba IR

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4657]
## Feature request

It'd be nice, especially in jupyter notebooks/ipython if Numba IR was syntax highlighted. I think most of the work to do this will involve implementing an appropriate lexer for pygments, docs: http://pygments.org/docs/lexerdevelopment/

**Comment by 1844144** [comment]
Where can I find Numba IR specification?

**Comment by stuartarchibald** [comment]
@1844144 Numba IR is an "implementation detail" and unfortunately has no formal specification, it changes a small bit over time but is largely fixed.
