### ISSUE TITLE
A suggestion, an issue with int, and a strange issue with `prange`

### ISSUE THREAD

**Issue by netw0rkf10w** [numba/numba#4658]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hello,

First of all thank you for the great software!

I have just learned about Numba very recently (well, since yesterday!). I tried it on a problem that I had spent a lot of time trying to vectorize with Numpy: simply replacing a `range()` (in a naive code) with `numba.prange()` gave me a speedup of >100x, which is twice as fast as my vectorized code. I was shocked! This is awesome!

When browsing the [FAQ](https://numba.pydata.org/numba-doc/dev/user/faq.html#how-do-i-reference-cite-acknowledge-numba-in-other-work) page and I saw that there is a paper on the software. I think the paper would deserve a better place where people can notice. According to Google Scholar, the paper has been cited 156 times, which is too modest in my opinion (and one reason might be not many people know about it).

Now I have two issues that I would like to ask for your help.

The first may be a bug: it is not possible to declare `np.zeros` with `dtype`. This function
```
@numba.jit(nopython=True)
def test():
    v = np.zeros(3, dtype=int)
```

gave the following error message:

> File "reproduce.py", line 166:
> def test():
>     v = np.zeros(3, dtype=int)
>     ^
> 
> This is not usually a problem with Numba itself but instead often caused by
> the use of unsupported features or an issue in resolving types.
> 
> To see Python/NumPy features supported by the latest release of Numba visit:
> http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
> and
> http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
> 
> For more information about typing errors and how to debug them visit:
> http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
> 
> If you think your code should work with Numba, please report the error message
> and traceback, along with a minimal reproducer at:
> https://github.com/numba/numba/issues/new
> 

The second issue is that when running the code below (at the end of this post), I obtained the following message:

> python(6019,0x1181af5c0) malloc: Incorrect checksum for freed object 0x7fae9acd75f8: probably modified after being freed.
> Corrupt value: 0x0
> python(6019,0x1181af5c0) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6

To see what should be obtained, simply remove the `@numba` line and replace `numba.prange` by `range`. Unfortunately I could not produce a simpler minimal working example (I tried to, but in all those simpler examples, everything was working).

I am using **Numba 0.45.1, Python 3.7.2**, installed in a virtual environment on macOS.

Thank you very much in advance for your help!

```
import numpy as np
import random
import numba

np.random.seed(12)
random.seed(12)

@numba.jit(nopython=True, parallel=True)
def build_pairwise_sparse(points1, points2, adj1=None, adj2=None, assignment_mask=None, len_weight=0.5):
    """
    points1: n1 x 2 array
    points2: n2 x 2 array
    For each pair of matches: i <--> p and j <--> q, the pairwise cost
        P(ip, jq) = w*leng + (1 - w)*0.5*(1 - cos_angle)
    where 
        leng = np.abs(norm1 - norm2)/(norm1 + norm2)
        cos_angle = ((xi-xj)*(xp-xq) + (yi-yj)*(yp-yq))/(norm1*norm2)
        norm1 = np.sqrt((xi-xj)*(xi-xj) + (yi-yj)*(yi-yj))
        norm2 = np.sqrt((xp-xq)*(xp-xq) + (yp-yq)*(yp-yq))
        w = len_weight
    adj1, adj2: n1xn1, n2xn2 adjacency matrices of points1 and points2.
        If None then fully connected.
    assignment_mask: the mask for the assignment matrix
        assignment_mask[i, p] = 0 means i should never match to p
    """
    len_weight = min(1.0, max(len_weight, 0))
    n1 = len(points1)
    n2 = len(points2)
    N = n1*n2
    
    # all assignment indices
    # if assignment_mask is None:
    #     assignment_mask = np.ones((n1, n2))
    aidx = np.flatnonzero(assignment_mask)
    A = len(aidx)

    # pre-compute x,y coordinates of each linear index 
    lidx = np.zeros(A)
    ridx = np.zeros(A)
    for idx_a in range(A):
        a = aidx[idx_a]
        p = a % n2
        i = int((a - p)/n2)
        lidx[idx_a] = i
        ridx[idx_a] = p

    # count the number of non-zero element in the final pairwise matrix
    # not easy to get a formula, so we iterate
    # upper-bound for the total number of non-zeros: min(2*E1*E2, A*(A-1)/2)
    num_nonzeros = 0
    for idx_a in range(A - 1):
        i = lidx[idx_a]
        p = ridx[idx_a]
        for idx_b in range(idx_a + 1, A):
            j = lidx[idx_b]
            q = ridx[idx_b]
            if q == p or j == i:
                continue
            # if ij or pq is not an edge then no potential
            if adj1 is not None and adj1[i, j] <= 0:
                continue
            if adj2 is not None and adj2[p, q] <= 0:
                continue
            num_nonzeros += 1
    
    # now we iterate again to get the indices i, j, p, q
    # last column of data is the potential
    data = np.zeros((num_nonzeros, 5))
    idx = 0
    for idx_a in range(A - 1):
        i = lidx[idx_a]
        p = ridx[idx_a]
        for idx_b in range(idx_a + 1, A):
            j = lidx[idx_b]
            q = ridx[idx_b]
            if q == p or j == i:
                continue
            # if ij or pq is not an edge then no potential
            if adj1 is not None and adj1[i, j] <= 0:
                continue
            if adj2 is not None and adj2[p, q] <= 0:
                continue
            data[idx, 0] = i
            data[idx, 1] = j
            data[idx, 2] = p
            data[idx, 3] = q
            idx += 1


    for pidx in numba.prange(num_nonzeros):
        i = int(data[pidx, 0])
        j = int(data[pidx, 1])
        p = int(data[pidx, 2])
        q = int(data[pidx, 3])
        xi = points1[int(i), 0]
        yi = points1[int(i), 1]
        xj = points1[int(j), 0]
        yj = points1[int(j), 1]
        xp = points2[int(p), 0]
        yp = points2[int(p), 1]
        xq = points2[int(q), 0]
        yq = points2[int(q), 1]

        norm1 = np.sqrt((xi-xj)*(xi-xj) + (yi-yj)*(yi-yj))
        norm2 = np.sqrt((xp-xq)*(xp-xq) + (yp-yq)*(yp-yq))
        leng = np.abs(norm1 - norm2)/(norm1 + norm2)
        cos_angle = ((xi-xj)*(xp-xq) + (yi-yj)*(yp-yq))/(norm1*norm2)
        tt = len_weight*leng + (1 - len_weight)*0.5*(1 - cos_angle)

        data[pidx, 4] = tt

    return data


def main():
    n1 = 4
    n2 = 2
    assert n1 >= n2

    # create a set of randoms 2D points, zero-centered them
    points1 = np.random.randint(100, size=(n1, 2))
    points1 = points1 - np.mean(points1, axis=0)

    # randomly transform it
    theta = np.random.rand()*np.pi/2
    # scale = np.random.uniform(low=0.5, high=1.5)
    scale = 1
    tx = np.random.randint(low=120, high=150)
    ty = np.random.randint(50)
    M = np.array([[scale*np.cos(theta), np.sin(theta),       tx],
                  [-np.sin(theta),       scale*np.cos(theta),  ty]])
    # transform the first set of features
    points2 = np.ones((3, n1))
    points2[:2] = np.transpose(points1)
    points2 = np.transpose(np.dot(M, points2))
    
    # randomly choose n2 points
    indices = list(range(n1))
    random.shuffle(indices)
    points2 = points2[indices]
    points2 = points2[:n2]
    
    # start = time.time()
    # adj1 = np.fill_diagonal(np.ones((n1, n1), dtype=int), 0)
    # adj2 = np.fill_diagonal(np.ones((n2, n2), dtype=int), 0)
    # assignment_mask = np.ones((n1, n2), dtype=int)
    # adj1 = np.fill_diagonal(np.ones((n1, n1)), 0)
    # adj2 = np.fill_diagonal(np.ones((n2, n2)), 0)
    assignment_mask = np.ones((n1, n2))
    # data = build_pairwise_sparse(points1, points2,
    #                              adj1=adj1,
    #                              adj2=adj2,
    #                              assignment_mask=assignment_mask
    #                              )

    data = build_pairwise_sparse(points1, points2,
                                 adj1=None,
                                 adj2=None,
                                 assignment_mask=assignment_mask
                                 )

    print(data)

@numba.jit(nopython=True)
def test():
    v = np.zeros(3, dtype=int)

if __name__ == "__main__":
    main()
    # test()
```

**Comment by DrTodd13** [comment]
You don't have any pranges in your build_pairwise_sparse function.  Which ranges did you try to run as pranges?

Also, the paper you reference with respect to Numba is responsible for only part of the 100x speed-up that you saw.  Something called ParallelAccelerator technology was integrated with Numba a few years ago and responsible for most of that speedup.  That technology is described in a paper "Parallelizing Julia with a Non-Invasive DSL" in ECOOP 2017.

**Comment by netw0rkf10w** [comment]
@DrTodd13 Thanks for your reply. Sorry I removed `prange` to test but then forgot to add it back. I have updated the code (`prange` is used in the last `for` loop).

> Also, the paper you reference with respect to Numba is responsible for only part of the 100x speed-up that you saw. Something called ParallelAccelerator technology was integrated with Numba a few years ago and responsible for most of that speedup. That technology is described in a paper "Parallelizing Julia with a Non-Invasive DSL" in ECOOP 2017.

Thanks for the information! I think all these papers deserve more credit!

**Comment by stuartarchibald** [comment]
RE: references/citations, @DrTodd13, any chance you could please open a PR against the docs with info about papers relating to ParallelAccelerator, such that if people wish to cite this feature it's easy to obtain some good references. Thanks. Suggested location is bottom of this page https://github.com/numba/numba/blob/5bd018fd55ab2ff0916ab2c6360334fe94e471a4/docs/source/user/faq.rst, under the `How do I reference/cite/acknowledge Numba in other work?` title?

**Comment by stuartarchibald** [comment]
RE possible bug:
```python
@numba.jit(nopython=True)
def test():
    v = np.zeros(3, dtype=int)
```
this is a known feature request (if I can find another ticket asking for it I'll cross reference), the `dtype` kwarg is supported but the value must be a NumPy type, `int` is the Python type. Try this:
```python
In [1]: from numba import njit                                                                                                  

In [2]: import numpy as np                                                                                                      

In [3]: @njit 
   ...: def foo(): 
   ...:     return np.zeros(3, dtype=np.int_) 
   ...:                                                                                                                         

In [4]: foo()                                                                                                                   
Out[4]: array([0, 0, 0])

In [5]: np.int_?                                                                                                                
Init signature: np.int_(self, /, *args, **kwargs)
Docstring:     
Signed integer type, compatible with Python `int` anc C ``long``.
Character code: ``'l'``.
Canonical name: ``np.int_``.
Alias *on this platform*: ``np.int64``: 64-bit signed integer (-9223372036854775808 to 9223372036854775807).
Alias *on this platform*: ``np.intp``: Signed integer large enough to fit pointer, compatible with C ``intptr_t``.
File:           <path>/lib/python3.7/site-packages/numpy/__init__.py
Type:           type
Subclasses:   
```

**Comment by stuartarchibald** [comment]
RE the massive piece of code with `build_pairwise_sparse` doing the work, this exposes a bug in ParallelAccelerator, MWR:
```python
from numba import njit
import numpy as np

def foo(X):

    acc = 0
    for _ in range(4):
        acc += 1

    print("acc", acc)
    data = np.zeros((acc,))
    print("data shape",data.shape)
    print(data)

x = np.ones(7)
njit(foo)(x)
print('-' *80)
njit(parallel=True)(foo)(x)
```
gives:
```
acc 4
data shape (4,)
[0. 0. 0. 0.]
--------------------------------------------------------------------------------
acc 4
data shape (0,)
[]
```

**Comment by netw0rkf10w** [comment]
@stuartarchibald Thank you so much for your messages!
On the ParallelAccelerator bug: good catch! I couldn't imagine that the issue lies at the `+=` :o 
I'll try putting this part of the code outside of the function to see.
