### ISSUE TITLE
Release candidate 0.46.0rc1 does not seem compatible with `cupy`

### ISSUE THREAD

**Issue by RemiLehe** [numba/numba#4661]
Here is a simple reproducer that creates a `cupy` array, pointing to the data in a `numba.cuda` array:
```python
import numpy as np
from numba import cuda
import cupy

x = np.empty(100)
d_x = cuda.to_device(x)
cupy_x = cupy.asarray(d_x)
```

With `cupy 6.4.0` and `numba 0.45.1`, this works as expected.
With `cupy 6.4.0` and `numba 0.46.0rc1`, this fails with the following error:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    cupy_x = cupy.asarray(d_x)
  File "/home/rlehe/miniconda3/lib/python3.6/site-packages/cupy/creation/from_data.py", line 66, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 1713, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1739, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2519, in cupy.core.core._convert_object_with_cuda_array_interface
TypeError: zip argument #2 must support iteration
```

Is this expected? Should users install a different version of `cupy`?

**Comment by leofang** [comment]
This is because we recently updated `__cuda_array_interface__` so that C-contiguous arrays either have no `strides` key in the dict or have `strides` set to `None`. Both the Numba (numba/numba#4609) and CuPy (cupy/cupy#2491) upstreams are updated. However, CuPy v6.4.0 is not updated yet:
https://github.com/cupy/cupy/blob/be8d39a744f99382b851c6aad3a8f9c13416a5f7/cupy/core/core.pyx#L2516-L2520
You can see it didn't test the possibility `strides=None`, hence `zip` complains.

**Comment by seibert** [comment]
Thanks for catching this!  We should consider how to proceed so as not to surprise people.

**Comment by RemiLehe** [comment]
@leofang @seibert Thanks a lot for letting me know!
I'll keep on eye on the `cupy` releases, for the new compatible interface :)

**Comment by leofang** [comment]
@stuartarchibald I suppose the bug tag is for pre-0.46.0rc1 releases? 😛 

@RemiLehe In case you wondered (you probably knew already), Numba wasn't fully compliant with the protocol earlier (see #4175). I'll help CuPy update it in a new v6 release.

**Comment by StanczakDominik** [comment]
I suppose this is slightly out of date and could be closed now, given 4 minor versions have come out since :)

**Comment by esc** [comment]
@StanczakDominik thanks for following up!
