### ISSUE TITLE
How can I get the numba0.46

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#4662]
the following codes can just install  '0.45.1' for the system 
```
$ conda install numba
$ pip install numba
```

But I find there is   '0.46' version numba 

And How can I get the latest numba, thank you.

**Comment by seibert** [comment]
We are in the middle of the release process for Numba 0.46.  We posted a release candidate to our development channel here:
```
conda install -c numba numba
```
The final 0.46.0 release will be posted to PyPI next week and Anaconda shortly there after.

**Comment by isaac-you** [comment]
ok . thank you so much

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by Dimplexion** [comment]
Hey, I'm also having issues with installing the 0.46.0 RC. Running this command seems to install version 0.44.1 for me: `conda install -c numba numba`. Am I missing something?

**Comment by stuartarchibald** [comment]
@Dimplexion it might be that you have an environment that is making it so some of the constraints from the numba builds on the numba channel cannot be met, either that or a package might be missing for a particular configuration. I presume:
```
conda create -n  <some_temporary_name> -c numba numba
```
works fine?

**Comment by seibert** [comment]
It might be necessary to force the version.  I don't recall what conda's logic is for upgrades, but you can force a specific version:
```
conda install -c numba numba=0.46.0rc1
```
