### ISSUE TITLE
I have a question about half precision float support in numba cuda

### ISSUE THREAD

**Issue by xuanshi123** [numba/numba#4670]
Will the half precision float be supported in numba cuda in the next release? I see change log in llvmlite saying supporting half precision float. And when will it be available on anaconda cloud. 

Thanks

## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by seibert** [comment]
The work in llvmlite is the start of supporting half-float in Numba, but there are many more things to do.  See #4402 for more discussion and a list of tasks.

**Comment by gmarkall** [comment]
Closing as a duplicate of #4402.
