### ISSUE TITLE
Same code works on macOS Python 3.7.2 but not on Ubuntu 16.04 Python 3.5.2

### ISSUE THREAD

**Issue by netw0rkf10w** [numba/numba#4674]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hello,

The following minimal example gave me errors (appended at the end of this message) on Ubuntu 16.04 with Python 3.5.2, while it works well on my Mac with Python 3.7.2 (both are inside a virtual environment and have Numba 0.45.1).

Could you please help me to fix this?
Thank you very much in advance!

```
import numpy as np
import scipy.sparse
import numba


@numba.jit(nopython=True, parallel=True, cache=True)
def simplex_projection_inequality_sparse(data, indices, indptr, num_vectors):
    """
    simplex project (with inequality constraints) of each row or each column of a sparse matrix C
    If C is CSR: each row; if C is CSC: each column
    data, indices, indptr, shape: representation of C (same notation as scipy csr/csc matrix)
    num_vectors = number of rows if C is CSR
                = number of cols if C is CSC
    """
    x = np.zeros(len(data))
    for i in numba.prange(num_vectors):
        # projection for each row independently
        start = indptr[i]
        end = indptr[i+1]
        ci = data[start:end]
        u = np.maximum(ci, 0)
        if np.sum(u) <= 1:
            xi = u
        else:
            ni = end - start
            a = -np.sort(-ci)
            lambdas = (np.cumsum(a) - 1)/np.arange(1, ni+1)  
            for k in range(ni-1, -1, -1):
                if a[k] > lambdas[k]:
                    xi = np.maximum(ci - lambdas[k], 0)
                    break
        x[start:end] = xi
    return x


def test():
    A = scipy.sparse.random(4, 5, density=0.5, format='csr')
    x = simplex_projection_inequality_sparse(A.data, A.indices, A.indptr, A.shape[0])

if __name__ == "__main__":
    test()
```

> Traceback (most recent call last):
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/errors.py", line 662, in new_error_context
>     yield
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block
>     self.lower_inst(inst)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 410, in lower_inst
>     func(self, inst)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/npyufunc/parfor.py", line 240, in _lower_parfor_parallel
>     bool(alias_map), index_var_typ, parfor.races)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/npyufunc/parfor.py", line 1103, in _create_gufunc_for_parfor_body
>     locals)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 1036, in compile_ir
>     lifted_from=lifted_from)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 398, in compile_ir
>     return self._compile_ir()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 910, in _compile_ir
>     return self._compile_core()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 890, in _compile_core
>     res = pm.run(self.status)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 266, in run
>     raise patched_exception
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 257, in run
>     stage()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 515, in stage_nopython_frontend
>     self.locals)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 1123, in type_inference_stage
>     infer.build_constraint()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 883, in build_constraint
>     self.constrain_statement(inst)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 1162, in constrain_statement
>     self.typeof_assign(inst)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 1233, in typeof_assign
>     self.typeof_global(inst, inst.target, value)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 1372, in typeof_global
>     self.lock_type(target.name, lit or typ, loc=inst.loc)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 950, in lock_type
>     tv.lock(tp, loc=loc, literal_value=literal_value)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/typeinfer.py", line 82, in lock
>     assert not self.locked
> AssertionError: Failed in nopython mode pipeline (step: nopython frontend)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test.py", line 41, in <module>
>     test()
>   File "test.py", line 38, in test
>     x = simplex_projection_inequality_sparse(A.data, A.indices, A.indptr, A.shape[0])
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
>     raise e
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 693, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 76, in compile
>     status, retval = self._compile_cached(args, return_type)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 90, in _compile_cached
>     retval = self._compile_core(args, return_type)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/dispatcher.py", line 108, in _compile_core
>     pipeline_class=self.pipeline_class)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 972, in compile_extra
>     return pipeline.compile_extra(func)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 390, in compile_extra
>     return self._compile_bytecode()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 903, in _compile_bytecode
>     return self._compile_core()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 890, in _compile_core
>     res = pm.run(self.status)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 266, in run
>     raise patched_exception
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 257, in run
>     stage()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
>     self._backend(lowerfn, objectmode=False)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 703, in _backend
>     lowered = lowerfn()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
>     self.metadata)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
>     lower.lower()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 177, in lower
>     self.lower_normal_function(self.fndesc)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 218, in lower_normal_function
>     entry_block_tail = self.lower_function_body()
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 243, in lower_function_body
>     self.lower_block(block)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/lowering.py", line 258, in lower_block
>     self.lower_inst(inst)
>   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/errors.py", line 670, in new_error_context
>     six.reraise(type(newerr), newerr, tb)
>   File "/home/ubuntu/.env/python3/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
>     raise value
> numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
> Failed in nopython mode pipeline (step: nopython frontend)
> 
> 
> File "test.py", line 16:
> def simplex_projection_inequality_sparse(data, indices, indptr, num_vectors):
>     <source elided>
>     x = np.zeros(len(data))
>     for i in numba.prange(num_vectors):
>     ^
> 
> [1] During: lowering "id=9[LoopNest(index_variable = parfor_index.178, range = (0, num_vectors, 1))]{342: <ir.Block at test.py (28)>, 40: <ir.Block at test.py (16)>, 365: <ir.Block at test.py (29)>, 469: <ir.Block at test.py (31)>, 246: <ir.Block at test.py (23)>, 472: <ir.Block at test.py (31)>, 345: <ir.Block at test.py (28)>, 223: <ir.Block at test.py (22)>}Var(parfor_index.178, test.py (16))" at test.py (16)
> -------------------------------------------------------------------------------
> This should not have happened, a problem has occurred in Numba's internals.
> You are currently using Numba version 0.45.1.
> 
> Please report the error message and traceback, along with a minimal reproducer
> at: https://github.com/numba/numba/issues/new
> 
> If more help is needed please feel free to speak to the Numba core developers
> directly at: https://gitter.im/numba/numba
> 
> Thanks in advance for your help in improving Numba!

**Comment by sklam** [comment]
I can replicate this bug.

**Comment by sklam** [comment]
Same problem on current master branch (bdd8e312a24c5b76ee4fe480abe553cff349aa51).  No repo on OSX as described in the issue.  Bug seems come from parfor codepath.

**Comment by sklam** [comment]
This is a problem in parfor type inference extension trying to reject the same IR node into a different block object. It causes a duplicated constraint created. I have yet to find out why it only replicate on py3.5.

**Comment by stuartarchibald** [comment]
Closing as Python 3.5 is not supported. If this can be reproduced on a supported Python version with the latest Numba (0.55) please do reopen/file a new issue, thanks.
