### ISSUE TITLE
Help for VMProf with Numba

### ISSUE THREAD

**Issue by cnwangfeng** [numba/numba#4683]
I am profiling the python with Vmprof. Everything is OK if without Numba. However, a message of "Process finished with exit code 132 (interrupted by signal 4: SIGILL)" would be showed when I try to profile the codes with Numba.

Is it possible to ignore such signal and continue to profile?

Thanks in advance.

Feng Wang @ SKAO

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm not sure what would be going on solely from the description presented but SIGILL means an illegal instruction has been encountered and it very unlikely a recoverable situation.

Can you share your CPU, OS and Python version details please? Thanks.

**Comment by stuartarchibald** [comment]
@cnwangfeng is this still a problem on the latest Numba (0.51.2) ? Thanks.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
