### ISSUE TITLE
Missing arg in TypeError

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4684]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Note: This has been edited.
```python
from numba import njit
import numpy as np

np.random.seed = 0 # this is entirely wrong

@njit
def foo(a):
    pass

foo(None)
```
a `TypingError` is raised from https://github.com/numba/numba/blob/9eb26b300e361911731f1f128ce6b7234491d098/numba/typing/templates.py#L924

**Comment by stuartarchibald** [comment]
Above is edited because it's entirely the wrong syntax, `seed` is a function to call. However, the error raised still has a bug in it in that `%r` is never set.

**Comment by Arenhart** [comment]
I don't know if it helps, but I have a situation with a similar error:
I have three functions:
def full_morphology_characterization(img):

def covariogram_irregular(img):

@njit(parallel = True)
def _covariogram_irregular(img):

currently, full_morphology_characterization calls covariogram_irregular, and covariogram_irregular calls _covariogram_irregular
If I run full_morphology_characterization, everything works fine, but if I run any of the other two, it raises the same error as OPs.

I'm using numba version 0.50.1

**Comment by stuartarchibald** [comment]
The OP does not reproduce on mainline as of 0.55, so will close this. @Arenhart if you have a minimal working reproducer for the issue you are seeing, please do open a new issue, thanks!
