### ISSUE TITLE
inline_closure_call may ignore glbls parameter

### ISSUE THREAD

**Issue by AlexanderKalistratov** [numba/numba#4687]
- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```inline_closure_call``` function may ignore ```glbls``` parameter:

```
    if isinstance(callee, pytypes.FunctionType):
        from numba import compiler
        callee_ir = compiler.run_frontend(callee, inline_closures=True)
    else:
        callee_ir = get_ir_of_code(glbls, callee_code)
```

```glbls``` is passed only in ```else``` branch and is not used in ```if``` branch.
This results in appearing errors like this:

```Untyped global name 'hpat': cannot determine Numba type of <class 'numba.ir.UndefinedType'>```

Removing ```if``` branch and always using ```else``` branch fixes the issue

**Comment by stuartarchibald** [comment]
Thanks for the report. This was added to accommodate inlining and generally make `inline_closure_call` more robust. The `if` branch is if you have a `callee` that's a python function, in which case it should be self consistent in its definition (i.e. if the function object `.__code__` requires globals then they should be defined correctly in the objects `.__globals__`), the `else` branch is if you have a code object (i.e.  a closure) in which case a limited amount of global injection is performed from the supplied `glbls`. This comment should hopefully explain what you are seeing and how to fix it https://github.com/numba/numba/issues/4533#issuecomment-531204547. If it does not, please could you produce a minimal working reproducer, thanks.

**Comment by stuartarchibald** [comment]
> @stuartarchibald The behavior of inline_closure_call is inconsistent. It should either do not accept `glbls` parameter at all or used it if it provided. At the moment it used in some cases and not used in anothers

This API is not public but I know it is extensively used by HPAT, I deliberately did not change the interface when writing the inlining support to limit the impact to HPAT. Further, that this function now "does the right thing" with Python functions actually fixed quite a few long standing awkward bugs with freevars (for example see: https://github.com/numba/numba/pull/4208#issuecomment-518636945).

Assuming the interface needs a change, I'm inclined to make globals a kwarg `glbls=None` and make it an error if a Python function is passed along with globals. Another option in the case of a Python function being passed in along with globals is to synthesise a new function based on the old with the globals updated, however, I'm reluctant to do this as the functions passed in should just be self consistent which seems like a more reliable code path.

**Comment by stuartarchibald** [comment]
Also have to ask, is it necessary to use this API? Is there some use case the inliner is not handling? If so, we should fix that too!

**Comment by stuartarchibald** [comment]
A new inliner API was implemented in https://github.com/numba/numba/pull/5673 that provides self consistency. Closing.
