### ISSUE TITLE
Inconsistent behavior of `stencil` decorator

### ISSUE THREAD

**Issue by d-v-b** [numba/numba#4696]
I observed the following strange behavior when using `stencil` as a decorator:
This function works fine (taken from the [stencil examples](https://numba.pydata.org/numba-doc/dev/user/stencil.html): 
```python
@njit(parallel=True)
def stencil_test1(A):
    c = 2
    B = stencil(
        lambda a, c: 0.3 * (a[-c+1] + a[0] + a[c-1]))(A, c)
    return B
stencil_test1(np.arange(10))
# returns array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 0. ])
```

But this function, which I thought would be equivalent, generates an error at runtime:

```python
@njit(parallel=True)
def stencil_test2(A):
    @stencil
    def fun (a):
        c = 2
        return 0.3 * (a[-c+1] + a[0] + a[c-1])
    B = fun(A)
    return B
```
running `stencil_test2(np.arange(10))` generates a long error with the following message at the end:
```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
stencil kernel index is not constant, 'neighborhood' option required

File "<ipython-input-454-f1261a271023>", line 7:
    def fun (a,c):
        <source elided>
        return 0.3 * (a[-c+1] + a[0] + a[c-1])
    B = fun(A,c)
    ^

[1] During: lowering "$B.9060 = call $fun.9059(A, $c.9058, func=$fun.9059, args=[Var(A, <ipython-input-454-f1261a271023> (3)), Var($c.9058, <ipython-input-454-f1261a271023> (3))], kws=(), vararg=None)" at <ipython-input-454-f1261a271023> (7)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.
```
The full traceback can be seen at this gist: https://gist.github.com/d-v-b/630506e0b34a3ee2dd49f6e9c8d2c3b0

In communication via gitter, @stuartarchibald found that removing the `@stencil` decorator and instead calling `stencil(fun)(A,c)` worked fine.

**Comment by DrTodd13** [comment]
@stuartarchibald @d-v-b The problem was that in the second case stencilparfor was not recognizing the stencil call because there was an intermediate Var in between.  So:
```
C = stencil(...)
D = A
call D(...)
```
This is due to a problem in get_call_table.  I have a branch that resolves this issue and I will make a PR but I'm not sure the semantics of the solution are what we would always want.  I guess we should discuss in the PR.

**Comment by stuartarchibald** [comment]
Thanks for figuring out the issue @DrTodd13, will continue discussion on the PR.
