### ISSUE TITLE
nested dictionaries failed

### ISSUE THREAD

**Issue by scirocc** [numba/numba#4697]
wanna do this：
     map={1:{2:3}}

here is my code：
    import numba
    d1 = numba.typed.Dict.empty(
        key_type=numba.types.float64,
        value_type=numba.types.float64,
        )
    d2 = numba.typed.Dict.empty(
        key_type=numba.types.float64,
        value_type=d1,
        )

and here is the typeError:
    unhashable type: 'Dict'

hope nested dictionaries can be supported sometime

**Comment by stuartarchibald** [comment]
Thanks for the report. Nested dictionaries work fine, the issue in the above code is that the `value_type` of `d2` is specified as the dictionary instance `d1`, not the Numba type of `d1`. You may find `numba.typeof()` helpful as it returns the Numba type of its argument and can be used in cases such as the above, alternatively `types.DictType` is the Numba dictionary type for use in a type specification.

Here's an example with a couple of ways to achieve what you want:

```python
from numba import njit, typeof, typed, types

d1 = typed.Dict.empty(
    key_type=types.float64,
    value_type=types.float64,
)
d2 = typed.Dict.empty(
    key_type=types.float64,
    value_type=typeof(d1), # base the d2 instance values of the type of d1
)

print("d1's Numba type is", typeof(d1))
# d1 is an instance so you can use it like a dict
d1[5.] = 6.
print(d1)

@njit
def foo(d2):
    d2[1.] = {2.: 3.}
    return d2

print("Using d2")
print(foo(d2))

# you can also spell it like this:
d1_type = types.DictType(types.float64, types.float64)
d3 = typed.Dict.empty(types.float64, d1_type)

print("Using d3")
print(foo(d3))

```

**Comment by scirocc** [comment]
Thank you so much for your useful reply.Now it worked！

**Comment by stuartarchibald** [comment]
No problem, glad it's working. Closing this issue.
