### ISSUE TITLE
Request for f-string support and numpy.isscalar.

### ISSUE THREAD

**Issue by Emoshe** [numba/numba#4699]
Looks like numba is missing the following very common features:
1.  formatted strings, e.g., f'This string contains x = {x:.3f}'
2. NumPy function 'numpy.isscalar'

**Comment by synapticarbors** [comment]
- Discussion of f-string support is in https://github.com/numba/numba/issues/3250
- `np.isscalar` is currently being implemented in https://github.com/numba/numba/pull/4610

**Comment by stuartarchibald** [comment]
@Emoshe Thanks for the report. Edited title to better reflect the issue. As @synapticarbors noted, both of these items are already being tracked, please comment on those issues directly if you have suggestions etc, thanks for your cooperation. Closing.
