### ISSUE TITLE
Numba makes Large Numbers Negative

### ISSUE THREAD

**Issue by christyjestin** [numba/numba#4700]
I was working on a project with permutations and combinations when I noticed that my predictor function calculated correct values for lower values but stopped working after 20. I traced each step back and discovered that the njit decorated factorial function I made had inaccurate and sometimes negative values for numbers greater than 20!. In most cases, the ratio between consecutive factorials (with the exception of 41 and 52) was also not correct. The function, included below, had all correct values and ratios for 20! and under. I implemented the same code without njit, and it worked. In retrospect, numba was not necessary for this function and is incompatible with the  later steps of the problem.

I have no idea why the njit decorated function has different values. The code for both versions of the function and their respective values for n between 1 and 24 are included below.

```
def factorial(x):
    result = 1
    for i in range(1,x+1):
        result*=i
    return result

@njit
def njit_factorial(x):
    result = 1
    for i in range(1,x+1):
        result*=i
    return result

for i in range(2,25):
    print(factorial(i), njit_factorial(i))

1 1
2 2
6 6
24 24
120 120
720 720
5040 5040
40320 40320
362880 362880
3628800 3628800
39916800 39916800
479001600 479001600
6227020800 6227020800
87178291200 87178291200
1307674368000 1307674368000
20922789888000 20922789888000
355687428096000 355687428096000
6402373705728000 6402373705728000
121645100408832000 121645100408832000
2432902008176640000 2432902008176640000
51090942171709440000 -4249290049419214848
1124000727777607680000 -1250660718674968576
25852016738884976640000 8128291617894825984
620448401733239439360000 -7835185981329244160
```

**Comment by rjenc29** [comment]
Hi

I think this is because the result quantity exceeds the maximum of the return dtype (`np.int64` on my machine) and so overflows.

```python
def factorial(x):
    result = 1
    for i in range(1,x+1):
        result*=i
    return result, result > np.iinfo(np.int64).max  # <- if True then expect overflow

@njit
def njit_factorial(x):
    result = 1
    for i in range(1,x+1):
        result*=i
    return result

for i in range(2,25):
    print(factorial(i), njit_factorial(i))
```

```
(2, False) 2
(6, False) 6
(24, False) 24
(120, False) 120
(720, False) 720
(5040, False) 5040
(40320, False) 40320
(362880, False) 362880
(3628800, False) 3628800
(39916800, False) 39916800
(479001600, False) 479001600
(6227020800, False) 6227020800
(87178291200, False) 87178291200
(1307674368000, False) 1307674368000
(20922789888000, False) 20922789888000
(355687428096000, False) 355687428096000
(6402373705728000, False) 6402373705728000
(121645100408832000, False) 121645100408832000
(2432902008176640000, False) 2432902008176640000
(51090942171709440000, True) -4249290049419214848
(1124000727777607680000, True) -1250660718674968576
(25852016738884976640000, True) 8128291617894825984
(620448401733239439360000, True) -7835185981329244160
```

Cheers, Rob

**Comment by stuartarchibald** [comment]
Thanks for the report. As @rjenc29 demonstrates (thanks for that!), the issue is that your code overflows signed 64 bit integers. Numba does not support `BigInt` like behaviour, as it has to use types commonly available in the LLVM backend, which is somewhat dictated by C/C++/other compiled languages etc. For more information on integer overflow here's a wiki article:  https://en.wikipedia.org/wiki/Integer_overflow . Closing.
