### ISSUE TITLE
Erroneous behaviour of np.transpose() after two transpositions

### ISSUE THREAD

**Issue by clionFHR** [numba/numba#4708]
On some occasions I have noticed some erratic weird behaviour of numba, when I am performing more than one transposition on a multidimensional numpy array. A minimal code that reproduces this bug (numba 0.45.1, numpy 1.16.4) in my case is the following:
```
from numba import jit
import numpy as np

@jit(nopython=True, cache=True)
def debug_numba_transpose(M,N):
    r1 = np.reshape(np.arange(M*N*3),(M,3,N))
    r2 = np.reshape(np.arange(N*3),(N,3))
    Rdif = (r1 - r2.T).T
    Rdif = np.transpose(Rdif,(2,0,1))
    Rdif = Rdif + 1
    return Rdif

def debug_transpose(M,N):
    r1 = np.reshape(np.arange(M*N*3),(M,3,N))
    r2 = np.reshape(np.arange(N*3),(N,3))
    Rdif = (r1 - r2.T).T
    Rdif = np.transpose(Rdif,(2,0,1))
    Rdif = Rdif + 1
    return Rdif

Rdif = debug_numba_transpose(3,2)
Rdif0 = debug_transpose(3,2)
print(Rdif-Rdif0)
```
The expected result should be a zero matrix. On my system it is not the case (I get the following result)
```
[[[ 0 -3 -1]
  [ 1 3 0]
 [[ 0 -3 -1]
  [ 1 3 0]]
 [[ 0 -3 -1]
  [ 1 3 0]]]
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. This is a smaller reproducer:
```python
from numba import njit
import numpy as np


@njit
def debug_numba_transpose(M, N):
    r1 = np.reshape(np.arange(M * N * 3), (M, 3, N))
    r2 = np.reshape(np.arange(N * 3), (N, 3))
    Rdif = (r1 - r2.T).T
    Rdif = np.transpose(Rdif, (2, 0, 1))
    z = Rdif + 1  # this line is needed to trigger the problem
    return z


expected = debug_numba_transpose.py_func(3, 2)
got = debug_numba_transpose(3, 2)

print(expected)
print('-' * 80)
print(got)
np.testing.assert_allclose(expected, got)
```

**Comment by adeak** [comment]
I've run into what I believe is the same problem, while trying to get around https://github.com/numba/numba/issues/4580.

Here's what I've found:
```
import numpy as np 
from numba import njit 

@njit 
def debug_numba_transpose(arr): 
    return arr.transpose(0,1).copy().reshape(2, -1) 
     
arr = np.arange(2*3).reshape(2,3).astype(float) 

print(debug_numba_transpose.py_func(arr)) 
print('-' * 80)
print(debug_numba_transpose(arr))
```
Transpose with `(0,1)` should even be a no-op, and so would reshaping.

If I remove the `.copy()` call inside the function the result suddenly becomes correct. Is this the same bug? I can imagine the `Rdif + 1` step could force a copy for the output array, essentially having the same mechanics.

**Comment by adeak** [comment]
This indeed seems fixed in master now thanks to @Vdimir. All three code blocks here now give expected results. Should this issue be closed?

**Comment by stuartarchibald** [comment]
> This indeed seems fixed in master now thanks to @Vdimir. All three code blocks here now give expected results. Should this issue be closed?

Confirmed against master, thanks. Closing.
