### ISSUE TITLE
vectorize function does not handle divide by zero correctly

### ISSUE THREAD

**Issue by jayvius** [numba/numba#471]
The following code:

    @vectorize(['f8(f8,f8)'])
    def foo(x, y):
        return x/y

    a = np.arange(10, dtype='f8')
    b = np.zeros(10, dtype='f8')
    print foo(a,b)

produces:

[  2.12276654e-314   2.12276654e-314   2.12276654e-314   2.12276654e-314
   2.12276654e-314   2.12276654e-314   2.12276654e-314   2.12276654e-314
   2.12276654e-314   2.12276654e-314]

whereas using numpy's div ufunc:

    a = np.arange(10, dtype='f8')
    b = np.zeros(10, dtype='f8')
    print a/b

produces:

[ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf]

A scalar divide by zero in the context of a vectorize function should return nan/inf, but a scalar divide by zero in a normal jit function should raise an error.

**Comment by pitrou** [comment]
This now works properly:
```
>>> foo(a, b)
/home/antoine/35/bin/ipython:1: RuntimeWarning: divide by zero encountered in foo
  #!/home/antoine/35/bin/python3
/home/antoine/35/bin/ipython:1: RuntimeWarning: invalid value encountered in foo
  #!/home/antoine/35/bin/python3
array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf])
```
