### ISSUE TITLE
slice constructor inconsistent with python

### ISSUE THREAD

**Issue by ivirshup** [numba/numba#4714]
While working on #4707, I noticed the `slice` constructor behaves differently in python code vs numba code. This occurs on bdd8e312a24c5b76e and `v0.46.0`. Here's a couple examples:

```python
from numba import njit

def slice_no_args(): slice()
def slice_one_arg(): slice(10)

cslice_no_args = njit(slice_no_args)
cslice_one_arg = njit(slice_one_arg)

slice_no_args()
# TypeError: slice expected at least 1 arguments, got 0
cslice_no_args()  # Runs fine

slice_one_arg()  # Runs fine
cslice_one_arg()
# TypingError: Failed in nopython mode pipeline (step: nopython frontend)
# Invalid use of Function(<class 'slice'>) with argument(s) of type(s): (Literal[int](10))
```

I think I've figured out how to make the behavior more consistent and would be happy to open a PR. I wanted to get dev opinion on this first, since I'm not sure if changing `slice()` to an error would be breaking (update: it actually gets tested [here](https://github.com/numba/numba/blob/a01986f1a2d9082aa88e8898049e9d55969124cb/numba/tests/test_slices.py#L64)).

I think the total changes would be:

* Add a case for 1 argument [here](https://github.com/numba/numba/blob/a01986f1a2d9082aa88e8898049e9d55969124cb/numba/targets/slicing.py#L157-L163)
* Remove 0-arity signature and add a 1-arity signatures for `None` and `int` [here](https://github.com/numba/numba/blob/a01986f1a2d9082aa88e8898049e9d55969124cb/numba/typing/builtins.py#L46-L58)

**Comment by stuartarchibald** [comment]
Thanks for the report. Looking at the known signatures:
```
Known signatures:
 * () -> slice<a:b>
 * (none, none) -> slice<a:b>
 * (none, int64) -> slice<a:b>
 * (int64, none) -> slice<a:b>
 * (int64, int64) -> slice<a:b>
 * (int64, int64, int64) -> slice<a:b:c>
 * (none, int64, int64) -> slice<a:b:c>
 * (int64, none, int64) -> slice<a:b:c>
 * (none, none, int64) -> slice<a:b:c>
```
explains the issues reported above. I just went and checked Python 2 to see if it was some inherited difference and it is not. I think fixing this to be correct is probably a good idea else people's code won't work if they turn off the JIT.

**Comment by ivirshup** [comment]
Great! I think I've got this fixed in a branch on my machine. The branch uses some of the testing code from #4707 so I'm thinking I'll wait on that first.
