### ISSUE TITLE
Some question about nogil mode

### ISSUE THREAD

**Issue by scirocc** [numba/numba#4720]
I've notice that,in the example,the way of using nogil-mode is like this:
-------------------------------------------------------------------------
```python
import numpy as np
import numba as nb
import threading as td
@nb.jit(nopython=True,nogil=True)
def thread__task(ndarray,i):
    ndarray[i]=i

def main():
    x = np.zeros(10)
    sTD=[]
    for i in range(10):sTD.append(td.Thread(target=thread__task,args=(x,i)))
    for i in range(10):sTD[i].start()
    for i in range(10):sTD[i].join()
    print(x)
main()
```
-------------------------------------------------------------------------
And i wanna use multiple threads to modify list or numba.typed.Dict.As the Doc says,numba.typed.Dict is not support modify by multiple threads .I've try to put a thread.lock() on it,
But I failed.Is there any way to do that?Or I just simply shouldn't use numba.typed.Dict as a parameter for function in nogil-mode?
Besides,can I use multiple threads to modify list?Is it thread-safe?

**Comment by stuartarchibald** [comment]
Thanks for the report, I've fixed up the markdown syntax.

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
To answer your question. The `numba.typed` containers (`List` and `Dict`) are in general not threadsafe for writing (there are some caveats), but are for reading, same goes for Numba's reflected list. There's no way to lock a region short of reacquiring the GIL, the `threading` module is not supported in Numba compiled code.

**Comment by scirocc** [comment]
Thank you so much for taking your valuable time to answer the question.It's very helpful to me.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
