### ISSUE TITLE
numpy.array_equal is not supported

### ISSUE THREAD

**Issue by nrasadi** [numba/numba#4727]
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.array_equal' or unsupported use of the function.

**Comment by stuartarchibald** [comment]
Thanks for the report. `numpy.array_equal` was implemented in #4568 and is in the 0.46.0 release of Numba which is available via the numba channel (it will be on defaults soon), to get it right now try:
```bash
conda install -c numba numba=0.46
```

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
