### ISSUE TITLE
Python 3.7 warns on `from collections import Iterable`

### ISSUE THREAD

**Issue by mattip** [numba/numba#4733]
[This line](https://github.com/numba/numba/blob/master/numba/types/containers.py#L3) in `containers.py` is causing a `DeprecationWarning` on python3.7. Is that a known issue? The message is `Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Comment by seibert** [comment]
Good catch.  We should fix this in our next patch release which is adding Python 3.8 support anyway.
