### ISSUE TITLE
problem with jitted function when integer indexing with zero element

### ISSUE THREAD

**Issue by jgathen** [numba/numba#4742]
Hi, I am currently in the midst of speeding up code via numba. I stumbled across a problem, which I do not understand. I am sorry for the title, but I didn't know exactly how I should better describe the problem.

The issue arises inside a jitted function where I need to set a number of elements of an array to a large negative number. I am doing the following:

```
test_array[:,:x,:,:] = -10e9
```
The issue arises if I set x=0. In that case, I expect the function to assign to an empty array as in numpy, but instead, numba seems to assign to the entire array. 

The following code is a stripped down version of my current code that reproduces the problem:

```
test_array = np.zeros((10, 100, 10, 2, 2), dtype=np.float32)

class testclass:
    
    def __init__(self,cost = 2):
        self.cost = cost
        
def operators_for_problem(class_instance):
    
    cost = np.int32(class_instance.cost)
    
    @njit(parallel=True)
    def function_that_takes_time(test_array):
        
        updated_test_array = np.empty_like(test_array, dtype = np.float32)
        updated_test_array[:,cost:,:,:,:] = test_array[:,:(100-cost),:,:,:]
        updated_test_array[:,:cost,:,:,:] = -10e9
        
        return updated_test_array
    
    return function_that_takes_time

test_model = testclass(cost=0)
update_test = operators_for_problem(class_instance = test_model)
updated_test_array = update_test(test_array)
updated_test_array
```

**Comment by jgathen** [comment]
Okay, nevermind, this is purely a problem of parallelization! Without parallelization, this problem vanishes. I should have seen this, sorry.

**Comment by jgathen** [comment]
Okay, nevermind, this is purely a problem of parallelization! Without parallelization, this problem vanishes. I should have seen this, sorry. I am not sure if such a situation should throw a warning, so I will leave this open for now.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think there is an issue in array analysis on slice-to-zero (`:0`)for the parallel target. Minimal reproducer:
```python
from numba import njit
import numpy as np

def foo(x):
    tmp = np.zeros_like(x)
    tmp[:,:0,:] = 1
    return tmp


test_array = np.zeros((2, 3, 4), dtype=np.float32)
print(foo(test_array))
print(njit(foo)(test_array))
print(njit(parallel=True)(foo)(test_array))
```
gives:
```
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
```

**Comment by stuartarchibald** [comment]
> Is it possible to exclude parts of the function from parallelization?

At present the decorator applies to the entire function, so if `parallel=True` is present any statement in the function is considered for parallel application. You are of course free to call other non-parallel functions from a parallel one.

**Comment by stuartarchibald** [comment]
CC: @DrTodd13

**Comment by DrTodd13** [comment]
@jgathen Appears fixed in master.  If it isn't working for you on master then please reopen this issue.
