### ISSUE TITLE
question about the efficientcy of numba.typed.dict

### ISSUE THREAD

**Issue by scirocc** [numba/numba#4743]
Found that:  numba.typed.dict is slower then pyDict.
Here is my code
```python
import numba as nb
import time
h={}
for i in range(1000):
    subh={i:i for i in range(5000)}
    h[i]=subh
nbh=pyObjToNumbaObj(h)#my type cast function
time1=time.time()
do1(nbh)
time2=time.time()
do2()
time3=time.time()
print(time2-time1,time3-time2)
```
Numba.typed.dict takes 0.166 seconds and pyDict takes 0.06 seconds.
Did i do anything wrong?Or I just simply shouldn't use numbaDict.

**Comment by esc** [comment]
@scirocc thanks for reporting this, I have labeled it as needing triage and fixed the syntax highlighting.

**Comment by esc** [comment]
So I guess `pyObjToNumbaObj` is from: https://github.com/numba/numba/issues/4728 ?

What about `do2()`? I can't seem to find it, or did I miss something?

**Comment by scirocc** [comment]
@esc Yes it is  from: #4728 .Sorry I am too careless, LOL.
function do1() and do2()  like this：

```python <your code> 
@nb.jit(nopython=True,cache=True)
def do1(nbh):
    for key in nbh:
        for key in nbh[key]:
            pass
def do2(h):
    for key in h:
        for key in h[key]:
            pass

```

**Comment by esc** [comment]
@scirocc thanks for submitting this, I can reproduce the timings here:

```
0.14887595176696777 0.057743072509765625
```

Though I don't know where the slowness is coming from.

**Comment by stuartarchibald** [comment]
Probably timing compilation as well as execution? Doing this:
```
do1(nbh) #warm up

time1=time.time()
do1(nbh)
time2=time.time()
do2(h)
time3=time.time()

print(time2-time1,time3-time2)
```
gives me:
```
0.04458880424499512 0.0912477970123291
```

**Comment by scirocc** [comment]
@stuartarchibald @esc 
Thank u for your help.I just dicover it is the preheating process takes much time.Got same answer too!
0.033528804779052734 0.10158753395080566

**Comment by scirocc** [comment]
@stuartarchibald 
Now the only problem is that,the process of type casting between pyObject and NumbaObject is too slow.But the i think it is worthy.

**Comment by stuartarchibald** [comment]
@scirocc I think that `numba.typeof` will help a lot.

**Comment by sylvain-ri** [comment]
Am I using it the wrong way ? The speed difference is unbelievable :o

`dico = numba.typed.Dict.empty(key_type=numba.types.unicode_type,
                              value_type=numba.types.int64)
for k, v in zip(('A', 'C', 'G', 'T'), range(4)):
    dico[k] = v
`
![image](https://user-images.githubusercontent.com/25283744/99813180-a7092980-2b47-11eb-8ff6-a161266602ad.png)

`dico = {'A':0,'C':1,'G':2,'T':3, } `
![image](https://user-images.githubusercontent.com/25283744/99813309-d029ba00-2b47-11eb-82be-9d9c2dc5496c.png)

**Comment by stuartarchibald** [comment]
@sylvain-ri there's an open PR to add some documentation about this: https://github.com/numba/numba/pull/6440/files#diff-6f032d897e4cf2f12a5bf9ccc7dc469ef6d11f7e34ae04833c53ff12b27dceeeR153

the answer is in there.

**Comment by sylvain-ri** [comment]
I see. Thanks.
