### ISSUE TITLE
type unification problem

### ISSUE THREAD

**Issue by scirocc** [numba/numba#4747]
Don't konw why this won't work
```
import numba as nb
@nb.jit(nopython=True,cache=True)
def do(typeOfa):
    if typeOfa=='string':
        nbType=nb.types.string
    elif typeOfa=='int':
        nbType=nb.types.int32
do('string')
```
But that one is ok:
```
import numba as nb
@nb.jit(nopython=True,cache=True)
def do(typeOfa):
    if typeOfa=='string':
        nbType=nb.types.string

do('string')
```

**Comment by stuartarchibald** [comment]
Thanks for the report, if you follow the link in the error message it will hopefully explain:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem

Essentially, in the first case `nbType` is one of two possible types depending on a run time value.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
