### ISSUE TITLE
jitting a jitted function raises AttributeError

### ISSUE THREAD

**Issue by dhirschfeld** [numba/numba#4750]
## Reporting a bug

```python
In [39]: @njit([float64(float64, float64)])
    ...: def add(x, y):
    ...:     return x + y
    ...:     

In [40]: njit(add)
Traceback (most recent call last):

  File "<ipython-input-40-c810b9ae6410>", line 1, in <module>
    njit(add)

  File "C:\Users\dhirschfeld\envs\dev\lib\site-packages\numba\decorators.py", line 239, in njit
    return jit(*args, **kws)

  File "C:\Users\dhirschfeld\envs\dev\lib\site-packages\numba\decorators.py", line 176, in jit
    return wrapper(pyfunc)

  File "C:\Users\dhirschfeld\envs\dev\lib\site-packages\numba\decorators.py", line 192, in wrapper
    **dispatcher_args)

  File "C:\Users\dhirschfeld\envs\dev\lib\site-packages\numba\dispatcher.py", line 657, in __init__
    exact_match_required=False)

  File "C:\Users\dhirschfeld\envs\dev\lib\site-packages\numba\dispatcher.py", line 210, in __init__
    default_values = self.py_func.__defaults__ or ()

AttributeError: 'CPUDispatcher' object has no attribute '__defaults__'

In [41]: numba.__version__
Out[41]: '0.46.0'
```

It would be nice if this worked but if it's not supported it should probably fail with a meaningful error message rather than an AttributeError.

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm not sure it should "just work", the contract of `@njit` is to in general lazily  compile the wrapped function, `njit(njit)` implies compiling the `njit` decorator? Agree the message should be better as it's likely just a typo/accident and it'd be useful to point this out.

**Comment by dhirschfeld** [comment]
My usecase was because the original function was jitted only for a particular signature and I wanted to allow it to be compiled on demand for *any* arguments.

I guess you can do `njit(add.py_func)` but in my case the jitted function calls other jitted functions... which also only take `float64` arguments.

I'm fine with an error message saying "Don't do that!" maybe also pointing to the `py_func` workaround.

**Comment by stuartarchibald** [comment]
As of mainline for 0.55, this:
```python
from numba import njit, float64
import numpy as np

@njit([float64(float64, float64)])
def add(x, y):
    return x + y


njit(add)
```
produces:
```
TypeError: A jit decorator was called on an already jitted function CPUDispatcher(<function add at 0xaddress)>).  If trying to access the original python function, use the CPUDispatcher(<function add at (0xaddress)>).py_func attribute.
```

Closing as fixed. Thanks!
