### ISSUE TITLE
Passing a Tuple of Numpy arrays to cfunc (scipy.integrate.quad)

### ISSUE THREAD

**Issue by max9111** [numba/numba#4754]
The question is related to [this one](https://stackoverflow.com/q/58421549/4045774) on stackoverflow. 

The calling syntax of the cfunc has to be as follows:

```c
double func(double x, void *user_data) 
```

where a Tuple of numpy arrays have to be passed through `void *user_data`. There should be an easy way to pass numpy-arrays as a Tuple/CStruct to the cfunc. (Changing the interface isn't possible in this case. 
I thought that this would be straigth forward, by passing a C_struct containing

```c
int arr_1_ndims
int* arr_1_shape
double* arr_1_data
int arr_2_ndims
int* arr_2_shape
double* arr_2_data
....
```

but this isn't possible because Numba doesn't seem to support pointers in a C_struct. I learned from [issue3220](https://github.com/numba/numba/issues/3220) that Tuples are actually represented as a C_struct in LLVM, so it should be possible to do it somehow.

I found a workaround (shown beyond) using a numpy structured array, but this has the big disadvantage that the cfunc has to be recompiled if the array shapes are changing.

**Pure Python Example**

```Python
def function_using_arrays(x1, x2, array1, array2):
    res1 = np.interp(x1, array1[0], array1[1])
    res2 = np.interp(x2, array2[0], array2[1])

    return res1 + res2

def do_integrate_w_arrays(a, lolim=0, hilim=1):
    foo = np.arange(20, dtype=np.float).reshape(2, -1)
    bar = np.arange(60, dtype=np.float).reshape(2, -1)

    return integrate.quad(function_using_arrays, 0, 1, (a, foo, bar))

```

**Workaround**

```Python

import numpy as np
import numba as nb
from numba import types
from scipy import integrate, LowLevelCallable
import ctypes

def create_jit_integrand_function(integrand_function,args,args_dtype):
    jitted_function = nb.njit(integrand_function)

    @nb.cfunc(types.float64(types.float64,types.CPointer(args_dtype)))
    def wrapped(x1,user_data_p):
        #Array of structs
        user_data = nb.carray(user_data_p, 1)

        #Extract the data
        x2=user_data[0].a
        array1=user_data[0].foo
        array2=user_data[0].bar

        return jitted_function(x1, x2, array1, array2)
    return wrapped

def function_using_arrays(x1, x2, array1, array2):
    res1 = np.interp(x1, array1[0], array1[1])
    res2 = np.interp(x2, array2[0], array2[1])

    return res1 + res2

def jit_with_dummy_data(args,args_dtype):
    func=create_jit_integrand_function(function_using_arrays,args,args_dtype)
    return func

def do_integrate_w_arrays(func,args,lolim=0, hilim=1):
    integrand_func=LowLevelCallable(func.ctypes,user_data=args.ctypes.data_as(ctypes.c_void_p))
    return integrate.quad(integrand_func, lolim, hilim)
```

**Usage**

```Python
#creating some sample data
a=3
foo = np.arange(200, dtype=np.float64).reshape(2, -1)
bar = np.arange(600, dtype=np.float64).reshape(2, -1)

args_dtype = types.Record.make_c_struct([
    ('a', types.float64),
    ('foo', types.NestedArray(dtype=types.float64, shape=foo.shape)),
    ('bar', types.NestedArray(dtype=types.float64, shape=bar.shape)),])

args=np.array((a,foo,bar),dtype=args_dtype)

#compile the integration function (array-shapes are fixed)
#There is only a structured array like args allowed
func=jit_with_dummy_data(args,args_dtype)


print(do_integrate_w_arrays(func,args, lolim=0, hilim=1))
```

**Comment by stuartarchibald** [comment]
Thanks for writing this up @max9111, much appreciated. Someone will take a look.

**Comment by sklam** [comment]
I think reading a cstruct from `void*` is possible by writing some [`intrinsic`](http://numba.pydata.org/numba-doc/latest/extending/high-level.html?highlight=intrinsic#implementing-intrinsics) that reinterpret the `void*` into what you need.  It's a matter of designing an API to do it for generic C-struct. 

There are some example in: https://github.com/numba/numba/blob/3e1d89cb500e84c26fec3810164fbaf07003f991/numba/unsafe/bytes.py#L25-L33

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
