### ISSUE TITLE
numba-RNG in 2D threads

### ISSUE THREAD

**Issue by Aslan9602** [numba/numba#4757]
In numba document,a sample program that uses the random number generator is provided:
```python
from numba import cuda
from numba.cuda.random import create_xoroshiro128p_states, xoroshiro128p_uniform_float32
import numpy as np

@cuda.jit
def compute_pi(rng_states, iterations, out):
    """Find the maximum value in values and store in result[0]"""
    thread_id = cuda.grid(1)

    # Compute pi by drawing random (x, y) points and finding what
    # fraction lie inside a unit circle
    inside = 0
    for i in range(iterations):
        x = xoroshiro128p_uniform_float32(rng_states, thread_id)
        y = xoroshiro128p_uniform_float32(rng_states, thread_id)
        if x**2 + y**2 <= 1.0:
            inside += 1

    out[thread_id] = 4.0 * inside / iterations

threads_per_block = 64
blocks = 24
rng_states = create_xoroshiro128p_states(threads_per_block * blocks, seed=1)
out = np.zeros(threads_per_block * blocks, dtype=np.float32)

compute_pi[blocks, threads_per_block](rng_states, 10000, out)
print('pi:', out.mean())
```
In this program,  thread_id = cuda.grid(1), but I wonder how to use RNG when thread_id = [2] ?
for example:
```python
import numpy as np
import math
from numba import cuda
from numba.cuda.random import create_xoroshiro128p_states, xoroshiro128p_uniform_float64
@cuda.jit
def RNG(rng_states,x):
    i,j = cuda.grid(2)
  
    if i >= x.shape[0] or j >= x.shape[1]:
        return
    x[i,j] = xoroshiro128p_uniform_float64(rng_states,   )
   
TPB = 16
threadsperblock = (TPB, TPB)
x = np.random.randint(1,10,(1024,1024))
blockspergrid_x = math.ceil(x.shape[0]/threadsperblock[0])
blockspergrid_y = math.ceil(x.shape[1]/threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)
rng_states = create_xoroshiro128p_states(   , seed=  )
RNG[blockspergrid, threadsperblock](rng_states,x)
print(x)
```
 What parameters should I set for `create_xoroshiro128p_states( )` and `xoroshiro128p_uniform_float64( )`

**Comment by stuartarchibald** [comment]
RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by Aslan9602** [comment]
Sorry,It's my first time to ask a question here.
I have learned how to insert my code. Thank you for your help.

**Comment by stuartarchibald** [comment]
Thanks for the query, and no problem about the formatting, the above is just a canned reply with info for users :)

To your question, I think this might do what you want:
```python
from numba import cuda
from numba.cuda.random import create_xoroshiro128p_states, xoroshiro128p_uniform_float32
import numpy as np
import math

@cuda.jit
def RNG(rng_states, x):
    startx, starty = cuda.grid(2)
    stridex, stridey = cuda.gridsize(2)

    for i in range(startx, x.shape[0], stridex):
        for j in range(starty, x.shape[1], stridey):
            idx = i * stridey + j
            rng = xoroshiro128p_uniform_float32(rng_states, idx)
            x[i, j] = rng

TPB = 8
threadsperblock = (TPB, TPB)
x = np.zeros((50, 3), dtype=np.float32)
blockspergrid_x = math.ceil(x.shape[0]/threadsperblock[0])
blockspergrid_y = math.ceil(x.shape[1]/threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)

total_threads = np.prod(threadsperblock)
total_blocks = np.prod(blockspergrid)

nstates = int(total_threads * total_blocks)

rng_states = create_xoroshiro128p_states(nstates, seed=1)

RNG[blockspergrid, threadsperblock](rng_states, x)
print(x)
```
the main thing to note is that looping over the grid with striding means the program becomes less dependent on the launch configuration. I can't really comment on the validity of this method of using the RNG as I don't recall the internal details of the implementation. Hope this helps.

**Comment by seibert** [comment]
The important thing is to ensure two threads never share an rng state, so computing a unique index the way Stuart has done is the way to go.

**Comment by Aslan9602** [comment]
Stuart,Thank you for your answer. Your code really have helped me a lot.
My purpose is to get int-RNG  in range[1,8]. It seem that I can't find  a function in Numba which can do this job.So I have to use  'int(xoroshiro128p_uniform_float64(rng_states,ID)*8 + 1)' to  meet my requirement.
Besides,How could I know the size of my array exceeds the size of gridsize,in which case I  must use the loop to ensure the uniqueness of the index?In other word,how to compute the largest size of gridsize?

**Comment by stuartarchibald** [comment]
> Besides,How could I know the size of my array exceeds the size of gridsize,in which case I must use the loop to ensure the uniqueness of the index?In other word,how to compute the largest size of gridsize?

The idea in the above is to make it so that the code works for whatever array, grid size and block size chosen. It essentially adds flexibility.

**Comment by Aslan9602** [comment]
> The idea in the above is to make it so that the code works for whatever array, grid size and block size chosen. It essentially adds flexibility.
Yes,I have learned to add flexibility for my code with your help.

**Comment by Aslan9602** [comment]
```python
import numpy as np
from numba import cuda
import math
from numba.cuda.random import create_xoroshiro128p_states, xoroshiro128p_uniform_float32


@cuda.jit
def A(rng_states,x, p):
    startx,starty = cuda.grid(2)
    stridex,stridey = cuda.gridsize(2)
    for i in range(startx,x.shape[0],stridex):
        for j in range(starty,x.shape[1],stridey):
            if 0 < i < x.shape[0] -1 and 0 < j < x.shape[1] - 1:
                ID = i * stridey + j
                if xoroshiro128p_uniform_float32(rng_states,ID) > p:
                    return
                count = np.bincount(x[i-1:i+2,j-1:j+2].ravel())
                x[i,j] = np.argmax(count)


def B(y, TPB, p):     
    x = cuda.to_device(y)          
    threadsperblock = (TPB, TPB)
    blockspergrid_x = math.ceil(x.shape[0]/threadsperblock[0])
    blockspergrid_y = math.ceil(x.shape[1]/threadsperblock[1])
    blockspergrid = (blockspergrid_x, blockspergrid_y)
    rng_states = create_xoroshiro128p_states(int(np.prod(threadsperblock) * np.prod(blockspergrid)), seed = 1)
    A[blockspergrid, threadsperblock](rng_states, x, p)
    return x


y = np.random.randint(1,4,(256,256))
TPB = 16
p = 0.5
x = B(y, TPB, p)
print(x)
```
In this code,x[i,j] will change to the mode of its 3*3 neighbourhood with a probability of 0.5.
Can I use 'np.bincount'   and 'np.argmax' in the kernel function?
