### ISSUE TITLE
Malloc Error when checking array flag

### ISSUE THREAD

**Issue by TNonet** [numba/numba#4775]
I don't really know how to classify this Issue, so I apologize if the title is a misnomer. I also don't know if this is the minimum example because I am having this issue in a much larger project and it was difficult to locate.

I am running the latest version of Numba
```python
import numba as nb
import numpy as np
print(nb.__version__)
```

```python

'0.46.0'
```

Minimum Test Case.
I define an internal JitClass, A, and create a tuple of instances of A.
Then I create JitClass B that holds the tuple of As. 
```python
A_spec = [
    ('a', nb.float64[::100,::100]),
]

@nb.jitclass(A_spec)
class A:
    def __init__(self, _a):
        self.a = _a
        
    def sum2d(self, other):
        if other.flags.f_contiguous:
            raise Exception("Fortran Array Needed")
        return other + self.a

def B_constructor(A_iterable):
    depth = len(A_iterable)
    A_tuple = tuple(A_iterable)

    A_type = nb.deferred_type()
    A_type.define(A.class_type.instance_type)

    B_spec = [
        ('A_tuple', nb.types.UniTuple(A_type, depth)),
    ]

    @nb.jitclass(B_spec)
    class B:
        def __init__(self, _a_tuple):
            self.A_tuple = _a_tuple
            
        def iter(self, init):
            out = np.zeros((10,10))
            for sub_A in self.A_tuple:
                out += sub_A.sum2d(init)
            return np.mean(out)
                
    return B(A_tuple)
```

When I create B like so:
```python
num = 5
lst = []
for i in range(num):
    lst.append(A(np.random.rand(100,100)))

B = B_constructor(lst)
```
I find a Malloc Error when I run:
```python
B.iter(np.random.rand(100,100))
```

```terminal
python(5598,0x11462f5c0) malloc: *** error for object 0x7f9054cc8e00: pointer being freed was not allocated
python(5598,0x11462f5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

However, when I create B differently:
```python
num = 2
lst = []
for i in range(num):
    lst.append(A(np.random.rand(100,100)))

B = B_constructor(lst)
```

I find that iter runs:
```python
B.iter(np.random.rand(100,100))
```
```python
2.105222642910346
```

If I remove the fortran array check everything runs fine!
```python
    def sum2d(self, other):
        # if other.flags.f_contiguous:
        #     raise Exception("Fortran Array Needed")
        return other + self.a
```

**Comment by esc** [comment]
@TNonet thanks for reporting this, I have queued this for triage.

**Comment by esc** [comment]
@TNonet thanks again for reporting this. I can reproduce everything you mention in the bug report locally.

**Comment by stuartarchibald** [comment]
MWE:
```python
import numba as nb
import numpy as np

@nb.jitclass(dict())
class B:

    def __init__(self):
        pass

    def foo(self, X):
        X.flags

Z = B()
Z.foo(np.ones(4))
```

**Comment by sklam** [comment]
I think .flags is forgetting a incref; at https://github.com/numba/numba/blob/master/numba/targets/arrayobj.py#L2154

**Comment by esc** [comment]
Using the following patch, fixes the error on my end:

```
xtra options: '-g'
diff --git i/numba/targets/arrayobj.py w/numba/targets/arrayobj.py
index b26bf993e6..e8d1db2129 100644
--- i/numba/targets/arrayobj.py
+++ w/numba/targets/arrayobj.py
@@ -2151,6 +2151,7 @@ def array_flags(context, builder, typ, value):
     flagsobj = context.make_helper(builder, types.ArrayFlags(typ))
     flagsobj.parent = value
     res = flagsobj._getvalue()
+    context.nrt.incref(builder, typ, value)
     return impl_ret_new_ref(context, builder, typ, res)
```

Anyone to confirm and I'll prep a PR.

**Comment by TNonet** [comment]
> MWE:
> 
> ```python
> import numba as nb
> import numpy as np
> 
> @nb.jitclass(dict())
> class B:
> 
>     def __init__(self):
>         pass
> 
>     def foo(self, X):
>         X.flags
> 
> Z = B()
> Z.foo(np.ones(4))
> ```

Thank You! I doubted I needed all of the extra fluff to cause the error. If you have time, could you explain why the bug shows up when  `num = 5` but not when `num = 2`?

**Comment by esc** [comment]
I submitted a PR with the fix and I can confirm that this does indeed fix the issue when running the original, more complex reproducer. However, in my case the new MWE fails to provoke the issue. I am on OSX 10.14.6 with Python 3.7.4 llvmlight 0.30.0rc1 and Numba compiled from b26b19df632d9302f740d39c5f00032dd70f356d.
