### ISSUE TITLE
Does numba support sympy?

### ISSUE THREAD

**Issue by overghostfire** [numba/numba#4795]
Sympy solves the five-element equations too slowly. Can it be accelerated with numba?

**Comment by seibert** [comment]
Google translates this to: "Sympy solves the five-element equations too slowly. Can it be accelerated with numba?"

@asmeurer: Thoughts?  I don't know much about the current status of using Numba with Sympy.

**Comment by asmeurer** [comment]
It's hard to answer this question without more context of what you are doing. Numba can't speed up SymPy itself, as it doesn't know how to compile the sorts of things that SymPy does. If you want faster symbolic math, you can take a look at SymEngine. Or it's possible that something you are doing is inefficient can be improved.

Numba speeds up numeric calculations. If the slow part of what you are doing is numeric, then SymPy has many ways to speed it up using code generation (like `ccode` or `autowrap`). One way is to use `lambdify`, which converts SymPy expressions into NumPy functions. These can also be wrapped with numba to make them faster, like `njit(lambdify(...))`.

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
