### ISSUE TITLE
Numba future feature flag design

### ISSUE THREAD

**Issue by seibert** [numba/numba#4808]
For the migration from reflected list to typed list, we need to have toggle-able feature flags that Numba users and library authors can opt into without affecting the entire applications.  In Python, this is done with the `from __future__ import X` mechanism, which enables backward incompatible features to be turned on at the module level.  This mechanism doesn't seem to be extensible to usage by other libraries, so we need to do our own thing.

This proposal is to have 3 layers of feature flag setting:
* Package level
* Module level
* Decorator level (only for testing purposes)

The mechanism for package level and module level will be the same.  We will have a `numba.__future__` module that will contain attributes like `disable_reflected_list` which correspond to a particular configurable feature.  In order to opt into this feature early (which will become mandatory in a future release) can import the symbol at global scope in their module
```
from numba.__future__ import disable_reflected_list
```
As with Python, we will never remove things from the `numba.__future__` module, even once they stop having an effect because the future feature has become mandatory.

Numba will scan the globals for each function compiles for these special feature flag values, and modify the compilation behavior accordingly.  This allows the future behavior to be enabled in scripts, notebooks, and packages on a module-by-module basis.

As a convenience for package authors, if a future flag is imported in the top-level `__init__.py` for the package, it will apply to all functions in the entire package tree. 

For testing purposes, we may introduce private flags (prefixed with `_`) to turn on and off future features in individual functions, but we advise 3rd party code not to use those flags as we will remove them without warning in future releases.  

Open questions:
* Does this cover everything?
* Is the package level setting introducing needless complexity?  Walking up the import tree might not be worth it to save a package from having to import the future feature in each of the files where they define compiled functions.

**Comment by seibert** [comment]
make future symbols (like `disable_reflected_list`) a callable so that people can call it to make their linters happy.  The actual call will have no effect.

**Comment by seibert** [comment]
Also, after some discussion, we are going to drop the package-level future flags.  Each source file needs to import the future flag.  If code is being generated some other creative way, it may need to be injected into the globals to `exec`.

**Comment by esc** [comment]
Implemented by #4883

**Comment by seibert** [comment]
closing this issue since this was juts for design discussion.  Feature can be tracked in #4883.
