### ISSUE TITLE
Does numba's implementation of np.diff have a bug?

### ISSUE THREAD

**Issue by alanlujan91** [numba/numba#4819]
I'm having this problem where the numba implementation of np.diff does not work on a slice of a matrix. Is this a bug or am I doing something wrong?

```

    import numpy as np
    from numba import njit
    v = np.ones((2,2))

    np.diff(v[:,0])

```
array([0.])
```

    @njit
    def numbadiff(x):
        return np.diff(x)
    
    numbadiff(v[:,0])

```

    ---------------------------------------------------------------------------
    TypingError                               Traceback (most recent call last)
    <ipython-input-6-1838803668db> in <module>
    ----> 1 numbadiff(v[:,0])
    
    ~\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
        399                 e.patch_message(msg)
        400 
    --> 401             error_rewrite(e, 'typing')
        402         except errors.UnsupportedError as e:
        403             # Something unsupported is present in the user code, add help info
    
    ~\Anaconda3\lib\site-packages\numba\dispatcher.py in error_rewrite(e, issue_type)
        342                 raise e
        343             else:
    --> 344                 reraise(type(e), e, None)
        345 
        346         argtypes = []
    
    ~\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
        666             value = tp()
        667         if value.__traceback__ is not tb:
    --> 668             raise value.with_traceback(tb)
        669         raise value
        670 
    
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Invalid use of Function(<function diff at 0x000001AD488E8E58>) with argument(s) of type(s): (array(float64, 1d, A))
     * parameterized
    In definition 0:
        TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Internal error at <numba.typeinfer.CallConstraint object at 0x000001AD4B281608>.
    reshape() supports contiguous array only
    [1] During: resolving callee type: BoundFunction(array.reshape for array(float64, 1d, A))
    [2] During: typing of call at C:\Users\alujan\Anaconda3\lib\site-packages\numba\targets\arraymath.py (3227)
    
    Enable logging at debug level for details.
    
    File "..\..\..\..\Anaconda3\lib\site-packages\numba\targets\arraymath.py", line 3227:
        def diff_impl(a, n=1):
            <source elided>
            # To make things easier, normalize input and output into 2d arrays
            a2 = a.reshape((-1, size))
            ^
    
        raised from C:\Users\alujan\Anaconda3\lib\site-packages\numba\typeinfer.py:951
    In definition 1:
        TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Internal error at <numba.typeinfer.CallConstraint object at 0x000001AD4B281608>.
    reshape() supports contiguous array only
    [1] During: resolving callee type: BoundFunction(array.reshape for array(float64, 1d, A))
    [2] During: typing of call at C:\Users\alujan\Anaconda3\lib\site-packages\numba\targets\arraymath.py (3227)
    
    Enable logging at debug level for details.
    
    File "..\..\..\..\Anaconda3\lib\site-packages\numba\targets\arraymath.py", line 3227:
        def diff_impl(a, n=1):
            <source elided>
            # To make things easier, normalize input and output into 2d arrays
            a2 = a.reshape((-1, size))
            ^
    
        raised from C:\Users\alujan\Anaconda3\lib\site-packages\numba\typeinfer.py:951
    This error is usually caused by passing an argument of a type that is unsupported by the named function.
    [1] During: resolving callee type: Function(<function diff at 0x000001AD488E8E58>)
    [2] During: typing of call at <ipython-input-5-8138554adfcb> (3)
    
    
    File "<ipython-input-5-8138554adfcb>", line 3:
    def numbadiff(x):
        return np.diff(x)
        ^
    
    This is not usually a problem with Numba itself but instead often caused by
    the use of unsupported features or an issue in resolving types.
    
    To see Python/NumPy features supported by the latest release of Numba visit:
    http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
    and
    http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
    
    For more information about typing errors and how to debug them visit:
    http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
    
    If you think your code should work with Numba, please report the error message
    and traceback, along with a minimal reproducer at:
    https://github.com/numba/numba/issues/new

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue you are seeing is because there's no support for `.reshape()` (as used by `np.diff`) on non-contiguous arrays, which is what the input is by virtue of taking a column out of a 2D C ordered array.

**Comment by Mullahz** [comment]
what is the solution or alternative of using  `.reshape()`
