### ISSUE TITLE
Question regarding the performance

### ISSUE THREAD

**Issue by jajcayn** [numba/numba#4859]
Dear `numba` team.

I am struggling with the efficient implementation of network simulation I have to do. First a bit of context: I got older code from one of my collaborators: it is a mean-field model of cortical activity. Roughly speaking, it consists of ~70 nodes, each node has 13 state variables so the state vector is approximately 900 variables, integration times are approx 50000 iterations. Right now, the function is written like this:

```python
@numba.njit()
def numba_integrate(<a lot (~80) of float, int and np.array parameters>):
    ...some arrays preparation (np.zeros((..)) and such)...
    for time in range(duration):
        for node in range(N):
            ...integration itself: lot of lines with simple math,
            ...computing right-hand sides of eqs
            ...Euler-Maruyama scheme in the end...
            y[time, node] = y[time, node] + dt * d_y[time, node] # no noise
            y[time, node] = y[time, node] + dt * d_y[time, node] + sqrt(dt) * sigma * xi # xi is GWN
```

the performance is stellar, it takes only a couple of seconds to run.
However, now I should rewrite the code to be more general: first of all, not all the nodes will have the same parameters, second of all some nodes will have different dynamics, hence different `d_y` updates. First step I wanted to take is to just rewrite the current code and not to add any further functionality. 
My first idea was to just write a numba function for `d_y` and not the full integration. The second idea was to not pass all the parameters as simple function arguments, but rather as a `numba.typed.Dict` and pass the parameters e.g. from `yaml` or `json` file with the possibility to create nested dicts, so each node can have different parameters.

So I did write a function like this:
```python
@numba.njit()
def numba_dydt(y_current, t_current, params_dict):
    for node in range(params_dict["N"]):
        ...integration itself: just per node

def EulerMaruyama(y0, tspan, f, params_dict):
    y = np.zeros((len(y0), len(tspan)))
    dt = tspan[1] - tspan[0]
    for time in range(1, len(tspan)):
        y_current = y[:, time-1]
        y[:, time] += dt*f(y_current, t, params_dict) # f is numba_dydt
```
The performance is, however, very bad. While the original implementation runs a few seconds, second one takes almost an hour! 

At first, I thought I made some mistakes and numba just cannot compile some of the objects, but after inspecting (`f.inspect_types()`) I see no `pyobject`s, just ints, floats and arrays (and literals for `params_dict` keys). 
Then I thought that using numba on the whole thing is just faster than using it just for dy/dt update and then integrate in time without numba. However, I created a very simple example with double-spring system integration and find out that pure numba integrator (meaning dummy Euler in single function which has `njit` iterator) is actually **slower** than using `njit` just on state updates dy/dt and then integrate with a simple function. I have no idea why. But in any case, having `njit` just on the dy/dt state updates and using different functions for actual integration is also beneficial as one can easily add different SDE schemes, e.g. Heun, SRK, etc.

So my question is, whether you have some idea why my code is SO slow. Can it be because of using the typed dictionary? Is it really that slow in comparison with lot of simple float and int arguments? Or can it really just be that the pure numba integration (having state vector updates inside the `njit`ted function) is that much faster and my simple benchmark is wrong for some reason? I attached my benchmark here as txt file (just remove the txt and you have a python script). From there is obvious that jitting whole thing and jitting just right-hand side computation is almost no difference, and if anything, jitting just RHS is faster. Of course, my actual cortical code is much more complex (computing the RHS).

Any help will be much appreciated! Thanks a lot.
By the way - superb work, I really like numba :)

P.S.: the `numba_test` I shared might seem a bit complicated with a class for the double-spring system, but I wanted to emulate the actual network I'd simulate after with some useful attributes, parameter loading, helpers etc.

[numba_test.py.txt](https://github.com/numba/numba/files/3854145/numba_test.py.txt)

**Comment by esc** [comment]
@jajcayn thanks for submitting this and for your kind words and feedback about Numba. We do appreciate it! I have labeled your issue as a 'question'. Since your question is somewhat involved it may take some time until someone get's around to looking at it, until then, please be patient. Thank you!

**Comment by gmarkall** [comment]
@jajcayn Thankyou for your kind words and feedback on Numba, and apologies that nobody has yet managed to answer your question - did you manage to make progress with this? If not, and it would still be helpful to get some input, you might want to open a thread on the Discourse group, where other Numba users are active and it will be easier to get some thoughts / feedback: https://numba.discourse.group

I'll close the issue here as we're trying to keep this issue tracker for issues / feature requests and use Discourse for discussions / questions - many thanks for your understanding.

**Comment by jajcayn** [comment]
hey, 

I got some feedback on the Discourse group, so all good:)
Thanks
