### ISSUE TITLE
Acquiring/releasing __cuda_array_interface__

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#4886]
## Feature request

The `__cuda_array_interface__` is great in that it has provided us a standard way to share GPU array information between libraries. Many libraries have picked it up as a result. This has really made interoperability much easier.

Though one point that has remained a bit unclear (at least to me) is how to ensure timely cleanup of GPU memory. In particular we want to ensure the validity of the object that gave us the data so the memory isn't cleaned up while we are using it. This might be handled by hanging onto the object in downstream objects. If that's how we want to handle this, we should spell it out somehow. Alternatively we could shove this into `__cuda_array_interface__` and have downstream users hang onto that `dict` with the original object included.

However we also want to ensure that once we are done with the object and associated memory it does get cleaned up. This is important to properly manage GPU memory without getting OOM. The best way to do this in Python is a bit unclear. Have seen users running `gc.collect()` to ensure cleanup occurs. It would be good to avoid this somehow.

I'm not totally sure the answers to these problems. Just want to raise the concern I see. The [Python Buffer Protocol]( https://docs.python.org/3/c-api/buffer.html ) seemed to handle this well by hanging onto the original object when producing a `Py_buffer` object and providing functions to acquire/release buffers to affect their lifetimes. Maybe we could do something similar? Maybe there are other options?

**Comment by gmarkall** [comment]
A short concrete example of the issue:

```python
import numpy as np
from numba import cuda

hostarray = np.arange(10).reshape(2, 5)
face = cuda.to_device(hostarray).__cuda_array_interface__

i = 0
while True:
    print("Iteration", i)
    cuda.from_cuda_array_interface(face)
    cuda.device_array((128, 128, 128))
    i += 1
```

falls over quite quickly as the original device array from which `face` was derived is cleaned up:

```
Iteration 0
Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
Iteration 6
Iteration 7
Iteration 8
Iteration 9
Iteration 10
Traceback (most recent call last):
  File "repro.py", line 10, in <module>
    cuda.from_cuda_array_interface(face)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/devices.py", line 225, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/api.py", line 49, in from_cuda_array_interface
    devptr = driver.get_devptr_for_active_ctx(desc['data'][0])
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 1390, in get_devptr_for_active_ctx
    driver.cuPointerGetAttribute(byref(devptr), attr, ptr)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 302, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 337, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.error.CudaAPIError: [1] Call to cuPointerGetAttribute results in CUDA_ERROR_INVALID_VALUE
```

There are instances in the test suite where this error (failing to retain a reference to an array when the `__cuda_array_interface__` will be used) is made, e.g. https://github.com/numba/numba/blob/master/numba/cuda/tests/cudapy/test_cuda_array_interface.py#L250 - I discovered this when experimenting with replacing Numba's memory management with RMM (and a plugin interface in general), and found that my current implementation's more aggressive cleaning up caused this test to fail.

**Comment by leofang** [comment]
This discussion on the lifetime of Python GPU objects branches from #4876. I think the suggestion
> we could shove this into `__cuda_array_interface__` and have downstream users hang onto that dict with the original object included.

is probably the easiest solution. 

But, I am always curious, how did NumPy solve the lifetime problem with `__array_interface__` on the Python side? Looking through that doc, I don't find this concern at all, which is a bit surprising.

**Comment by gmarkall** [comment]
I've attempted to codify that the consumer of `__cuda_array_interface__` should hold on to the object owning the data to ensure its lifetime is adequately preserved in #5162. For the future, I think there could be improvements to the protocol to make it better / safer / more usable / etc... but I think it's worthwhile being explicit about the current expectations for now.

**Comment by jakirkham** [comment]
Yep, agree. Sounds like a good thing to add Graham 🙂

**Comment by gmarkall** [comment]
The documentation now states that the consumer should retain a reference to the producer for as long as it is using it, now that #5323 is merged. @jakirkham: do you feel this issue is closed now that the expectation is made explicit, or would you prefer leaving it open to explore the idea of doing something similar to the buffer protocol to retain the original object?

**Comment by jakirkham** [comment]
Thanks Graham! That's great 😄

There is a separate discussion about having a lower-level implementation of the `__cuda_array_interface__` ( https://github.com/numba/numba/issues/4876 ). So maybe we can keep that discussion there and close this out. WDYT? 😉

**Comment by gmarkall** [comment]
Closing this sounds good! I can't close the issue myself as I don't have write access to this repo, but feel free to close it :-)

**Comment by jakirkham** [comment]
Ah ok. Closing this out then...
