### ISSUE TITLE
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by smile-fyl** [numba/numba#4887]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/fuyilong/pysot-toolkit/pysot/evaluation/ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/opt/conda/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/opt/conda/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/opt/conda/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
[1] During: typing of argument at /home/fuyilong/pysot-toolkit/pysot/utils/statistics.py (104)

File "pysot/utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    ^

This error may have been caused by the following argument(s):
- argument 1: Unsupported array dtype: object

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

"""
```

**Comment by esc** [comment]
@smile-fyl thank you for reporting this. Can you add the code that you ran that triggered this?

**Comment by smile-fyl** [comment]
> @smile-fyl thank you for reporting this. Can you add the code that you ran that triggered this?

Sorry to reply to you so late！
The code :
@jit(nopython=True)
def overlap_ratio(rect1, rect2):
    left = np.maximum(rect1[:,0], rect2[:,0])
    right = np.minimum(rect1[:,0]+rect1[:,2], rect2[:,0]+rect2[:,2])
    top = np.maximum(rect1[:,1], rect2[:,1])
    bottom = np.minimum(rect1[:,1]+rect1[:,3], rect2[:,1]+rect2[:,3])

    intersect = np.maximum(0,right - left) * np.maximum(0,bottom - top)
    union = rect1[:,2]*rect1[:,3] + rect2[:,2]*rect2[:,3] - intersect
    iou = intersect / union
    iou = np.maximum(np.minimum(1, iou), 0)
    return iou

@jit(nopython=True)
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    success = np.zeros(len(thresholds_overlap))
    iou = np.ones(len(gt_bb)) * (-1)
    mask = np.sum(gt_bb > 0, axis=1) == 4
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
    for i in range(len(thresholds_overlap)):
        success[i] = np.sum(iou > thresholds_overlap[i]) / float(n_frame)
    return success

@jit(nopython=True)
def success_error(gt_center, result_center, thresholds, n_frame):
    # n_frame = len(gt_center)
    success = np.zeros(len(thresholds))
    dist = np.ones(len(gt_center)) * (-1)
    mask = np.sum(gt_center > 0, axis=1) == 2
    dist[mask] = np.sqrt(np.sum(
        np.power(gt_center[mask] - result_center[mask], 2), axis=1))
    for i in range(len(thresholds)):
        success[i] = np.sum(dist <= thresholds[i]) / float(n_frame)
    return success

**Comment by stuartarchibald** [comment]
Thanks for updating the issue. NOTE: I formatted the above.

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

I cannot reproduce the above problem on Numba 0.47 release candidate with this:
```python
from numba import njit
import numpy as np

@njit
def overlap_ratio(rect1, rect2):
    left = np.maximum(rect1[:,0], rect2[:,0])
    right = np.minimum(rect1[:,0]+rect1[:,2], rect2[:,0]+rect2[:,2])
    top = np.maximum(rect1[:,1], rect2[:,1])
    bottom = np.minimum(rect1[:,1]+rect1[:,3], rect2[:,1]+rect2[:,3])

    intersect = np.maximum(0,right - left) * np.maximum(0,bottom - top)
    union = rect1[:,2]*rect1[:,3] + rect2[:,2]*rect2[:,3] - intersect
    iou = intersect / union
    iou = np.maximum(np.minimum(1, iou), 0)
    return iou

@njit
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    success = np.zeros(len(thresholds_overlap))
    iou = np.ones(len(gt_bb)) * (-1)
    mask = np.sum(gt_bb > 0, axis=1) == 4
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
    for i in range(len(thresholds_overlap)):
        success[i] = np.sum(iou > thresholds_overlap[i]) / float(n_frame)
    return success

success_overlap(np.ones((5, 3)), np.ones((5, 3)), 2)
```
do you have some sample input data that demonstrates the problem please? Thanks!

**Comment by smile-fyl** [comment]
> Thanks for updating the issue. NOTE: I formatted the above.
> 
> RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: `` ```python <your code> ``` ``. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).
> 
> I cannot reproduce the above problem on Numba 0.47 release candidate with this:
> 
> ```python
> from numba import njit
> import numpy as np
> 
> @njit
> def overlap_ratio(rect1, rect2):
>     left = np.maximum(rect1[:,0], rect2[:,0])
>     right = np.minimum(rect1[:,0]+rect1[:,2], rect2[:,0]+rect2[:,2])
>     top = np.maximum(rect1[:,1], rect2[:,1])
>     bottom = np.minimum(rect1[:,1]+rect1[:,3], rect2[:,1]+rect2[:,3])
> 
>     intersect = np.maximum(0,right - left) * np.maximum(0,bottom - top)
>     union = rect1[:,2]*rect1[:,3] + rect2[:,2]*rect2[:,3] - intersect
>     iou = intersect / union
>     iou = np.maximum(np.minimum(1, iou), 0)
>     return iou
> 
> @njit
> def success_overlap(gt_bb, result_bb, n_frame):
>     thresholds_overlap = np.arange(0, 1.05, 0.05)
>     success = np.zeros(len(thresholds_overlap))
>     iou = np.ones(len(gt_bb)) * (-1)
>     mask = np.sum(gt_bb > 0, axis=1) == 4
>     iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
>     for i in range(len(thresholds_overlap)):
>         success[i] = np.sum(iou > thresholds_overlap[i]) / float(n_frame)
>     return success
> 
> success_overlap(np.ones((5, 3)), np.ones((5, 3)), 2)
> ```
> 
> do you have some sample input data that demonstrates the problem please? Thanks!
Thank you for your reply! I have solved this prolem! It's caused by the dataset's name.
