### ISSUE TITLE
wont njit compile usage of a tuple of functions (with same real->real interface) in a loop

### ISSUE THREAD

**Issue by iurisegtovich** [numba/numba#4889]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi,

i've been seeing huge performance improvement using numba as long as i follow certain rules, which has been working great so far,
now i have stumbled upon this behavior when trying to njit compile usage of a tuple of functions (with same real->real interface) in a loop

this works:

```
@njit
def ftest(x):
    #l=[np.sin,np.cos]#complains about lists but goes fine with tuples
    l=(np.sin,np.cos)
    a=l[0](x)
    b=l[1](x)
    return a+b


ftest(3)
```

this does'nt work:

```
@njit
def ftest(x):
    l=(np.sin,np.cos)
    a=0
    for i in range(2): #does not compile the loop with the tuple of different functions
        a+=l[i](x)
    return a

ftest(3)
```

with error:

`Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): ((Function(<ufunc 'sin'>), Function(<ufunc 'cos'>)), int64)`

but this workaround does it

```
@njit
def l(i,x):
    l=(np.sin,np.cos)
    if i==0:
        f=l[0](x)
    elif i==1:
        f=l[1](x)
    return f

@njit
def ftest(x):
    a=0
    for i in range(2): #can compile using manifold function
        a+=l(i,x)
    return a

ftest(3)
```

As the first and third examples work, I think the second example should work, but the parser is not currently capable of translating that.

(as i saw it as a supported feature that fails on a specific caase i thought i should report as a bug, rather than as a feature request)

seems related to this question at stackoverflow: https://stackoverflow.com/questions/52536806/iterating-over-a-tuple-at-jit-compile-time-in-numba

see my uploaded example on google colab / gist with numba 0.46 at 

[https://colab.research.google.com/gist/iurisegtovich/9d709607c4879584559b0d4b74d32d49/trynumbatuplefunctionnjitmanifold.ipynb](https://colab.research.google.com/gist/iurisegtovich/9d709607c4879584559b0d4b74d32d49/trynumbatuplefunctionnjitmanifold.ipynb)

thanks for your attention :)

**Comment by seibert** [comment]
This may be allowed by an upcoming PR, coincidentally.  We'll tag this issue when that PR is opened.

**Comment by stuartarchibald** [comment]
This should work:
```python
from numba import njit, literal_unroll
import numpy as np

@njit
def ftest(x):
    l = (np.sin,np.cos)
    a = 0
    for i in literal_unroll(l):
        a += i(x)
    return a

print(ftest(3))
```
as does:
```python
from numba import njit, literal_unroll
import numpy as np

@njit
def ftest(x):
    l = (np.sin,np.cos)
    a = 0
    for i in literal_unroll((0, 1)):
        a += l[i](x)
    return a

print(ftest(3))
```
what's important is the use of `literal_unroll` to make sure the loop bodies are versioned.

Another way around this is through first-class function types:
```python
from numba import njit, literal_unroll, float64
import numpy as np

@njit(float64(float64))
def np_sin(x):
    return np.sin(x)

@njit(float64(float64))
def np_cos(x):
    return np.cos(x)

@njit
def ftest(x):
    l = (np_sin, np_cos)
    a = 0
    for i in range(2):
        a += l[i](x)
    return a

print(ftest(3))
```
I think this can be closed as there's multiple ways to achieve this effect. If anyone disagrees please do comment and the discussion can be reopened. Thanks for your help!
