### ISSUE TITLE
Numba talks -- scipy 2019

### ISSUE THREAD

**Issue by NicolasHug** [numba/numba#4895]
There was 3 Numba related talk at scipy 2019 (one of them is mine):

- https://www.youtube.com/watch?v=-4tD8kNHdXs
- https://www.youtube.com/watch?v=0pUPNMglnaE
- https://www.youtube.com/watch?v=cLpIh8Aiy2w

in case you want to add them to https://numba.pydata.org/numba-doc/latest/user/talks.html

**Comment by esc** [comment]
@NicolasHug thanks for bring our attention to this! I have labelled it as a feature request for the docs.
