### ISSUE TITLE
Support for numpy.isnat in nopython mode needed since no w/a longer exists

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#4897]
Hi,

Can you please add support for np.isnat function in nopython mode, since comparing elements of datetime arrays to dtype('NaT') no longer works due to changes in Numpy (see [this](https://stackoverflow.com/questions/38509538/numpy-checking-if-a-value-is-nat/38531233)).

I was using these versions of Numba and Numpy:
numba                     0.46.0dev0      np116py37h6538335_568    numba/label/dev
numpy                     1.16.5           py37h19fb1c0_0
numpy-base                1.16.5           py37hc3f5095_0   

The test that I used to verify np.isnat is not supported in nopython mode:
```
    def test_numba_datetime64_isnat(self):
        import numba
        def test_impl(A):
            return np.isnat(A)
        jitted_func = numba.njit(test_impl)

        A = np.array(['nat', '1970-12-01', '2012-07-25', 'NaT', '2014-07-21'], dtype='datetime64[ns]')
        np.testing.assert_array_equal(jitted_func(A), test_impl(A))
```

The test with workaround that passes on Numpy=1.13 and fails on Numpy=1.16.5:
```
    def test_numba_datetime64_isnat_wa(self):
        import numba
        nat = np.datetime64('NaT')
        def test_impl(A):
            res = [nat == A[i] for i in np.arange(len(A))]
            return res
        jitted_func = numba.njit(test_impl)

        A = np.array(['nat', '1970-12-01', '2012-07-25', 'NaT', '2014-07-21'], dtype='datetime64[ns]')
        jitted_res = jitted_func(A)
        pandas_res = np.isnat(A)
        print("Results: pandas={}, hpat={}".format(pandas_res, jitted_res))
        np.testing.assert_array_equal(jitted_res, pandas_res)
```

Best Regards,
Alexey.

**Comment by esc** [comment]
@kozlov-alexey thanks for asking about this. I believe this issue will need to be triaged some more so I have labelled it accordingly.

**Comment by stuartarchibald** [comment]
Thanks for the request. This indeed needs doing.
