### ISSUE TITLE
try excepts support

### ISSUE THREAD

**Issue by direbutterfly** [numba/numba#4898]
It could be useful for numba to support try/excepts

**Comment by esc** [comment]
@direbutterfly thanks for asking about this. I believe there may be something cooking already and  @sklam may know more.

**Comment by sklam** [comment]
I am working on a very basic version for try/except. 

The bare-except:

```python
try:
   ...
except:
   ...    
```

and the catch all user-exception:

```python
try:
    ...
except Exception:
   ...
```

**Comment by sklam** [comment]
Basic support added in #4902
