### ISSUE TITLE
Numba typed containers (List/Dict)  not supported with NUMBA_DISABLE_JIT

### ISSUE THREAD

**Issue by lmcinnes** [numba/numba#4905]
The new ``numba.typed.List`` is great, however it currently does not support running with ``NUMBA_DISABLE_JIT=1``. Currently I have tests running with that environment variable set for code coverage testing (since coverage tools don't currently see jitted functions). Unfortunately these tests fail due to use of typed lists.

## Reproducer

```
$ export NUMBA_DISABLE_JIT=1
$ python

>>> import numba
>>> alist = numba.typed.List.empty_list(numba.types.int32) 
```

## Expected behaviour

This should ideally run just as it does without the ``NUMBA_DISABLE_JIT`` environment variable set. Unfortunately it currently reports a ``NotImplementedError``.

## Notes

A resolution to #4268 would also go a long way to alleviating this for me -- although being able to replicate behaviour with ``NUMBA_DISABLE_JIT`` set is likely useful for other reasons as well.

**Comment by esc** [comment]
@lmcinnes thanks for reporting this!

**Comment by seibert** [comment]
@esc: Can we make typed list fall back to a Python list when JIT is disabled?  It will be more permissive than the real typed list,  but so is all of Numba when the JIT is turned off, so I don't see that as an issue.

**Comment by esc** [comment]
@seibert sure, that is no problem at all.

**Comment by hmc-cs-mdrissi** [comment]
I can make a separate issue if it helps, but this problem also appears for typed dictionaries and similarly having it fall back to a python dict would be nice.

**Comment by esc** [comment]
@hmc-cs-mdrissi absolutely.

**Comment by esc** [comment]
@hmc-cs-mdrissi the fix for dict is at #4921 - maybe you could give it a review and see if it works for you?

**Comment by hmc-cs-mdrissi** [comment]
@esc I tested it just now. It got rid of the error I had before, but it's still not enough to make a typed dict with JIT disabled. The stack trace points to the problem being that _make_dict calls _as_meminfo which is marked intrinsic and intrinsic decorator can't be called with JIT disabled. Here's the relevant stack trace,

File "test.py", line 7, in test
    x = typed.Dict.empty(int32, int32)
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/typeddict.py", line 88, in empty
    return cls(dcttype=DictType(key_type, value_type))
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/typeddict.py", line 103, in __init__
    self._dict_type, self._opaque = self._parse_arg(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/typeddict.py", line 114, in _parse_arg
    opaque = _make_dict(dcttype.key_type, dcttype.value_type)
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/typeddict.py", line 20, in _make_dict
    return dictobject._as_meminfo(dictobject.new_dict(keyty, valty))
  File "/usr/local/lib/python3.6/dist-packages/numba/dictobject.py", line 83, in new_dict
    raise NotImplementedError

Also here's a simple test case that throws that error if you run it with NUMBA_DISABLE_JIT set,

```
from numba import njit, typed
from numba.types import int32


@njit
def test():
    x = typed.Dict.empty(int32, int32)

test()
```

**Comment by esc** [comment]
@hmc-cs-mdrissi thanks for trying this out, this is unfortunate and will require some more investigation. I changed the title of the issue accordingly, because fixing it for one, means we know how to fix it for the other. The stack trace you posted may not be the correct one, so here is the correct one for reference:

```
 zsh» NUMBA_DISABLE_JIT=1 python foo/foo73.py
Traceback (most recent call last):
  File "foo/foo73.py", line 9, in <module>
    test()
  File "foo/foo73.py", line 7, in test
    x = typed.Dict.empty(int32, int32)
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 88, in empty
    return cls(dcttype=DictType(key_type, value_type))
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 103, in __init__
    self._dict_type, self._opaque = self._parse_arg(**kwargs)
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 114, in _parse_arg
    opaque = _make_dict(dcttype.key_type, dcttype.value_type)
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 20, in _make_dict
    return dictobject._as_meminfo(dictobject.new_dict(keyty, valty))
  File "/Users/vhaenel/git/numba/numba/extending.py", line 292, in __call__
    raise NotImplementedError(msg)
NotImplementedError: <intrinsic _as_meminfo> is not usable in pure-python
```

**Comment by esc** [comment]
Smells like this might need a metaclass to resolve.

**Comment by esc** [comment]
FWIW the following does seem to work, even with `NUMBA_DISABLE_JIT`. 

```
from numba import njit, typed


@njit
def test():
    x = typed.Dict()

test()
```

**Comment by esc** [comment]
#4921 has been updated.

**Comment by esc** [comment]
#4920 is the solution for list.

**Comment by lmcinnes** [comment]
Excellent! Thank you!

**Comment by esc** [comment]
@lmcinnes good good, do let us know if it ends up working for you.
