### ISSUE TITLE
Cuda: Using shared memory to add numbers results in overwriting

### ISSUE THREAD

**Issue by scheng123** [numba/numba#4907]
I have been trying to add numbers using shared memory so it would be as follows:

Thread 0: Add 1 to shared memory variable sharedMemT[0]

Thread 1: Add 1 to shared memory variable sharedMemT[0]

synchronize threads and store sharedMemT[0] into output[0]

But the result was... 1??
```
@cuda.jit()
def add(output):
    sharedMemT = cuda.shared.array(shape=(1), dtype=int32)
    sharedMemT[0] = 0
    cuda.syncthreads()

    sharedMemT[0] += 1
    cuda.syncthreads()
    output[0] = sharedMemT[0]

out = np.array([0])
add[1, 2](out)
print(out) # results in [1]
```

**Comment by esc** [comment]
@scheng123 thanks for asking about this on the Numba issue tracker. There is some tutorial material at https://github.com/numba/euroscipy2019-numba/blob/master/4%20-%20Writing%20CUDA%20Kernels.ipynb that suggests using:

```
cuda.atomic.add(sharedMemT, 0, 1)
```

Instead of:

```
sharedMemT[0] += 1
```

In order to perform an atomic add to the value at location `[0]` of the `sharedMemT`. My bet here is that you are seeing the result of a race condition. Could you try that and see if it helps?

**Comment by scheng123** [comment]
I know that working with GPUs always result in a race condition but I want to know why it doesn't work.

My though process:
Declare shared memory variable as [0]
syncthreads
Now every thread should increment at the same time when I run sharedMemT[0] += 1

But why doesn't it work?? It is so confusing. Thank you for your time and patience. My first time working with CUDA :)

**Comment by scheng123** [comment]
Thanks for the article @esc, I understand now. I'm going to post the portion that talks about race conditions just on case someone else stumbles upon this "issue" ^:::^

> However, there are many cases where different threads need to combine results. Consider something very simple, like: "every thread increments a global counter." Implementing this in your kernel requires each thread to:

> 1. Read the current value of a global counter.
> 2. Compute counter + 1.
> 3. Write that value back to global memory.

> However, there is no guarantee that another thread has not changed the global counter between steps 1 and 3. To resolve this problem, CUDA provides "atomic operations" which will read, modify and update a memory location in one, indivisible step. Numba supports several of these functions, described here.
>

**Comment by esc** [comment]
@scheng123 thanks for following up on this, we appreciate it. Glad that your issue has been resolved!
