### ISSUE TITLE
bitarray support

### ISSUE THREAD

**Issue by ilanschnell** [numba/numba#4912]
Here is the traceback:
```
Cannot lower constant of type 'buffer(uint8, 1d, C)'

File "357.py", line 9:
def f(n):
    a[n] = 0
    ^

[1] During: lowering "$0.2 = global(a: bitarray('1111111111'))" at 357.py (9)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
And my small test program:
```
from bitarray import bitarray
from numba import njit

a = bitarray(10)
a.setall(True)

@njit
def f(n):
    a[n] = 0

f(1)
print(a)
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. Numba doesn't support `bitarray` at present so I think this is more of a feature request than anything else. There's also the issue that even if it were supported [globals are considered compile time constants](http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable) and so doing `a[n]` would not be permitted.

**Comment by stuartarchibald** [comment]
Closing this as supporting `bitarray` is not in scope for Numba as it's not part of the python standard library. Numba has numerous extension mechanisms available for adding support for additional types etc. See: https://numba.readthedocs.io/en/stable/extending/index.html
