### ISSUE TITLE
reshape() supports contiguous array only

### ISSUE THREAD

**Issue by NP-Prob** [numba/numba#4917]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

# Update2:
Problem solved, one need to use `numpy.copy()` to create a contiguous array copy of the slice for use, and everything will be fine. Like this:
`Q = ions[:,1].copy()`
A topic about the contiguous array and non-contiguous array is here:
https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays
Just in case that anyone would encounter the same problem like me.
# Update1:
I've read the issue #4819, I think that I've found where the problem is, but if I really need to extract a column out of a 2-d array for use, what should I do? Thanks for the help!
# Problem and code:
if I do something like this:
```python
Q = np.array([1.60217663e-19, 1.60217663e-19, 1.60217663e-19, 1.60217663e-19])
Electric_Potential_Force(n, Q, pos, t)
```

everyting is fine, but if I try someting below, where the `ions[:,1]` is exactly the `Q` mentioned above, and warnings come out, am I doing someting wrong? Is it because of the slice I've made here?
I've tried to use `q = ions[:,1]` to create a new array, but still don't work.
```python
Q = ions[:,1]
Electric_Potential_Force(n, Q, pos, t)
```

It seems that the problem raise from a `numpy.reshape()` function used in the self-defined function `Electric_Potential_Force(num, q, r, t)`

here is the `Electric_Potential_Force(num, q, r, t)` function:
```python
@jit
def Electric_Potential_Force(num, q, r, t):
    temp = np.zeros((num, 3))
    for i in range(num):
        r_t_temp = np.append(r[i], np.array(t))
        temp[i] = Electric_Potential_Gradient(r_t_temp)
    return temp * q.reshape(num, 1)
```

# warings:
Compilation is falling back to object mode WITH looplifting enabled because Function "Electric_Potential_Force" failed type inference due to: Internal error at <numba.typeinfer.CallConstraint object at 0x0000024B5DF72288>.
reshape() supports contiguous array only
[1] During: resolving callee type: BoundFunction(array.reshape for array(float64, 1d, A))
[2] During: typing of call at f:/Protomol/MD Simulation/test.py (181)

Enable logging at debug level for details.

File "test.py", line 181:
def Electric_Potential_Force(num, q, r, t):
    <source elided>
        temp[i] = Electric_Potential_Gradient(r_t_temp)
    return temp * q.reshape(num, 1)
    ^

  @jit
f:/Protomol/MD Simulation/test.py:173: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "Electric_Potential_Force" failed type inference due to: cannot determine Numba type of <cla
ss 'numba.dispatcher.LiftedLoop'>

File "test.py", line 178:
def Electric_Potential_Force(num, q, r, t):
    <source elided>
    temp = np.zeros((num, 3))
    for i in range(num):
    ^

  @jit
D:\ProgramData\Anaconda3\lib\site-packages\numba\object_mode_passes.py:178: NumbaWarning: Function "Electric_Potential_Force" was compiled in object mode without forceobj=True, but has
 lifted loops.

File "test.py", line 174:
@jit
def Electric_Potential_Force(num, q, r, t):
^

  state.func_ir.loc))
D:\ProgramData\Anaconda3\lib\site-packages\numba\object_mode_passes.py:187: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "test.py", line 174:
@jit
def Electric_Potential_Force(num, q, r, t):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, state.func_ir.loc))

**Comment by stuartarchibald** [comment]
Thanks for opening/closing this! Glad you got something working. In general it's a good idea to try and use `@jit(nopython=True)` or `@njit` (they are aliases) so that [`nopython` mode](http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode) is used as this gives the best performance. 

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by anilsathyan7** [comment]
It seems the copy() or ascontiguous() functions takes considerable amount of time in python or numba, especially if it is a big array; unlike a contiguous one. Is there a way to overcome this performance issue with numba? We usually come up with such issues if we take transpose or views on some arrays and end up with a non-contiguous array.

**Comment by stuartarchibald** [comment]
@anilsathyan7 please could you open a new ticket with a reproducing example to discuss, thanks.
