### ISSUE TITLE
prange reduction incorrect when operation happens inside a conditional block

### ISSUE THREAD

**Issue by sklam** [numba/numba#4922]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Reproducer

```python
In [1]: from numba import njit, prange

In [2]:
   ...: def udt(n):
   ...:     c = 0
   ...:     for i in prange(n):
   ...:         c += 1
   ...:         if i > 10:
   ...:             c += 1
   ...:     return c
   ...:

In [3]: udt(10)
Out[3]: 10

In [4]: njit(parallel=True)(udt)(10)
Out[4]: 18    # result doesn't match pure python

In [5]: njit(parallel=False)(udt)(10)
Out[5]: 10    # result matches pure python
```

**Comment by stuartarchibald** [comment]
CC @DrTodd13
