### ISSUE TITLE
Cannot use 1d array containing a single value as a predicate.

### ISSUE THREAD

**Issue by vivekvekariya** [numba/numba#4923]
Cannot cast array(float64, 1d, C) to bool: %".155" = load {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}* %"large"

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Thanks.

**Comment by bittremieux** [comment]
@vivekvekariya Are you using Python 3.8? If so, this might be related to #4712.

**Comment by vivekvekariya** [comment]
@bittremieux  No I am using Python 3.7.4

**Comment by stuartarchibald** [comment]
Gitter discussion: https://gitter.im/numba/numba?at=5de6abae46397c721c7e5f17

This is a reproducer:
```python
import numpy as np
from numba import njit

def foo():
    x = np.ones(1)
    if x:
        pass

njit(foo)()
```
it's the bug fixed by this: https://github.com/numba/numba/pull/3901

**Comment by stuartarchibald** [comment]
Fixed by https://github.com/numba/numba/pull/5225, closing.
