### ISSUE TITLE
Numba 0.47 Python 3.8 on pypi and anaconda cloud

### ISSUE THREAD

**Issue by valeriupredoi** [numba/numba#4936]
Hi guys, we're currently stuck at py=3.7+ because we need numba and your current available version on both pypi and anaconda cloud is 0.46/py<3.8 -> any chance you will be updating the conda and pypi packages soon with 0.47 that (I believe) works with py3.8? Many thanks in advance and apologies if this issue is a duplicate, have not searched in depth the issues tree :beer:

**Comment by esc** [comment]
@valeriupredoi thanks for asking about this. The plan is to have a release candidate out for 0.47 on Dec 19th and that should work with Python 3.8

**Comment by valeriupredoi** [comment]
brilliant, cheers muchly @esc - feel free to close the issue, I'll report back to my team about the date :beer:

**Comment by esc** [comment]
@valeriupredoi no problem at all, glad I could help!
