### ISSUE TITLE
comparing ndarray with boolean fails in lowering error

### ISSUE THREAD

**Issue by sklam** [numba/numba#4939]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
In [11]: @njit
    ...: def foo(x):
    ...:     return (x == True)  # works if `x == 1`

In [12]: foo(np.ones(10).astype(np.bool_))
```

The error
```

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
non-numeric type in Num

File "<ipython-input-9-44d49d9f64e2>", line 3:
def foo(x):
    return (x == True)
    ^

[1] During: lowering "$6compare_op.2 = arrayexpr(expr=(<built-in function eq>, [Var(x, <ipython-input-9-44d49d9f64e2>:3), const(bool, True)]), ty=array(bool, 1d, C))" at <ipython-input-9-44d49d9f64e2> (3)
```

**Comment by rjenc29** [comment]
Hi, this might be related to #4530

**Comment by stuartarchibald** [comment]
The MWR works on mainline as of ~0.55, closing as fixed.
