### ISSUE TITLE
Error trying to return array passed in to function

### ISSUE THREAD

**Issue by jayvius** [numba/numba#494]
The following code:

    from numba import njit

    @njit
    def foo2(x):
        return x

    @njit
    def foo(x):
        return foo2(x)

    a = np.arange(10)
    print foo(a)

produces the following error in function foo:

    ValueError: Only accept returning of array passed into the function as argument

even though the array being returned from foo is the original array passed in to foo.

**Comment by pitrou** [comment]
This now works fine, closing.
