### ISSUE TITLE
Invalid use of Function

### ISSUE THREAD

**Issue by coreyhahn** [numba/numba#4950]
I have hit this error before... but this one i cannot get around.
```
(at)cuda.jit 
def mult_mod_v03(a, b, c):
    tx = cuda.blockDim.x*cuda.blockIdx.x+cuda.threadIdx.x
    
    tempc0 = 0
    tempc1 = 0
    tempc2 = 0
    tempc3 = 0
    tempc4 = 0
    tempa0 = a[0,tx]
    tempa1 = a[1,tx]
    tempa2 = a[2,tx]
    tempa3 = a[3,tx]
    tempa4 = a[4,tx]
    mod = np.uint32(2**13+7)
    mask = np.uint32(1)
    for n in range(32):
        if (b[4,tx] & mask):
            tempc4 ^= tempa4
            tempc3 ^= tempa3
            tempc2 ^= tempa2
            tempc1 ^= tempa1
            tempc0 ^= tempa0
        tempa0 <<= 1
        tempa0 += (tempa1 >= 0x80000000)
        tempa1 <<= 1
        tempa1 += (tempa2 >= 0x80000000)
        tempa2 <<= 1
        tempa2 += (tempa3 >= 0x80000000)
        tempa3 <<= 1
        tempa3 += (tempa4 >= 0x80000000)
        tempa4 <<= 1
        if (tempa0 >= 8):
            tempa4 ^= mod
        tempa0 &= 0x7
        mask <<= 1

    c[0,tx] = tempc0
    c[1,tx] = tempc1
    c[2,tx] = tempc2
    c[3,tx] = tempc3
    c[4,tx] = tempc4
```

The error
```
Invalid use of Function(<built-in function ixor>) with argument(s) of type(s): (int64, float64)
Known signatures:
 * (bool, bool) -> bool
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at ./numbaCudaPlayground.py (45)

File "numbaCudaPlayground.py", line 45:
def mult_mod_v03(a, b, c):
    <source elided>
            tempc4 ^= tempa4
            tempc3 ^= tempa3
            ^
```
What am i missing?

**Comment by gmarkall** [comment]
Executable reproducer:

```
from numba import cuda
import numpy as np

block = 128
grid = 128
elems = block * grid

a = np.ones(shape=(5, elems), dtype=np.float32)
b = np.ones(shape=(5, elems), dtype=np.float32)
c = np.zeros_like(a)

@cuda.jit
def mult_mod_v03(a, b, c):
    tx = cuda.blockDim.x*cuda.blockIdx.x+cuda.threadIdx.x

    tempc0 = 0
    tempc1 = 0
    tempc2 = 0
    tempc3 = 0
    tempc4 = 0
    tempa0 = a[0,tx]
    tempa1 = a[1,tx]
    tempa2 = a[2,tx]
    tempa3 = a[3,tx]
    tempa4 = a[4,tx]
    mod = np.uint32(2**13+7)
    mask = np.uint32(1)
    for n in range(32):
        if (b[4,tx] & mask):
            tempc4 ^= tempa4
            tempc3 ^= tempa3
            tempc2 ^= tempa2
            tempc1 ^= tempa1
            tempc0 ^= tempa0
        tempa0 <<= 1
        tempa0 += (tempa1 >= 0x80000000)
        tempa1 <<= 1
        tempa1 += (tempa2 >= 0x80000000)
        tempa2 <<= 1
        tempa2 += (tempa3 >= 0x80000000)
        tempa3 <<= 1
        tempa3 += (tempa4 >= 0x80000000)
        tempa4 <<= 1
        if (tempa0 >= 8):
            tempa4 ^= mod
        tempa0 &= 0x7
        mask <<= 1

    c[0,tx] = tempc0
    c[1,tx] = tempc1
    c[2,tx] = tempc2
    c[3,tx] = tempc3
    c[4,tx] = tempc4

mult_mod_v03(a, b, c)
```

**Comment by gmarkall** [comment]
The error message that I see is:

```
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function and_>) with argument(s) of type(s): (float32, uint64)
Known signatures:
 * (bool, bool) -> bool
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at repro.py (29)

File "repro.py", line 29:
def mult_mod_v03(a, b, c):
    <source elided>
    for n in range(32):
        if (b[4,tx] & mask):
```

which provides a bit more detail, pointing to the use of `b[4, tx] & mask` being the problem - `&` can only be used for integers, not floating point types. Additionally, the xor (`^`) has the same problem. Changing the types of `a` and `b` to `np.int32` makes the problem disappear. I imagine this does not necessarily solve your problem in terms of helping you to get a correct implementation - if you can suggest what you're trying to do, perhaps I can suggest a way to implement it.

Also - what version of Numba are you using?

**Comment by coreyhahn** [comment]
Thank you.
>>> numba.__version__
'0.43.1'

Indeed. changing my input types to np.int does remove the error.  I believe i can reformulate my kernel with with the MSb as a sign bit.  XOR and AND should work the same.  This does not seem like correct behavior, but i can make it work.

BRB

**Comment by gmarkall** [comment]
> Indeed. changing my input types to np.int does remove the error. I believe i can reformulate my kernel with with the MSb as a sign bit.

For floating point values, the MSB is the sign bit, but why would you want to try to check the bit instead of checking for less than zero?

> XOR and AND should work the same.

The same as what?

> This does not seem like correct behavior, but i can make it work.

What seems incorrect?

**Comment by coreyhahn** [comment]
I am feeding np.uint into the function.  That is why it is so frustrating.
I don't use float or double anywhere in my program.  And I am careful to
type everything unit32

**Comment by coreyhahn** [comment]
here is a complete example
(must learn this formatting stuff)

from numba import cuda

import numpy as np
#import math
import ecc2m131 as ecc
import inversion_playground as ip


     
@cuda.jit ##((u4,u4,u4))  ##locals={ 'tempa0': numba.uint64,'tempa1': numba.uint64,'tempa2': numba.uint64,'tempa3': numba.uint64,'tempa4': numba.uint64,'tempc0': numba.uint64,'tempc1': numba.uint64,'tempc2': numba.uint64,'tempc3': numba.uint64,'tempc4': numba.uint64 })
def mult_mod_v03(a, b, c):
    tx = cuda.blockDim.x*cuda.blockIdx.x+cuda.threadIdx.x
    
    tempc0 = 0
    tempc1 = 0
    tempc2 = 0
    tempc3 = 0
    tempc4 = 0
    tempa0 = a[0,tx]
    tempa1 = a[1,tx]
    tempa2 = a[2,tx]
    tempa3 = a[3,tx]
    tempa4 = a[4,tx]
    mod = np.int32(2**13+7)
    mask = np.int32(1)
    for n in range(32):
        if (b[4,tx] & mask):
            tempc4 ^= tempa4
            tempc3 ^= tempa3
            tempc2 ^= tempa2
            tempc1 ^= tempa1
            tempc0 ^= tempa0
        tempa0 <<= 1
        tempa0 += (tempa1 >= 0x80000000)
        tempa1 <<= 1
        tempa1 += (tempa2 >= 0x80000000)
        tempa2 <<= 1
        tempa2 += (tempa3 >= 0x80000000)
        tempa3 <<= 1
        tempa3 += (tempa4 >= 0x80000000)
        tempa4 <<= 1
        if (tempa0 >= 8):
            tempa4 ^= mod
        tempa0 &= 0x7
        mask <<= 1

    c[0,tx] = tempc0
    c[1,tx] = tempc1
    c[2,tx] = tempc2
    c[3,tx] = tempc3
    c[4,tx] = tempc4
    

    
        
# Host code  
threadsperblock = 256
blocks = 4
size1 = threadsperblock * blocks

np.random.seed(7)

data1 = np.random.randint(0,2**32,[5, size1],dtype=np.uint32)##.astype(np.int32)
data2 = np.random.randint(0,2**32,[5, size1],dtype=np.uint32)




data1_d = cuda.to_device(data1)
data2_d = cuda.to_device(data2)
outdata_d = cuda.device_array([5,size1],dtype=np.int32)

blockspergrid = size1 // threadsperblock
mult_mod_v03[blockspergrid, threadsperblock](data1_d, data2_d, outdata_d) 


outdata = outdata_d.copy_to_host()
 
for n in range(5):
    print(n, outdata[n,:])


[deleteme.py.zip](https://github.com/numba/numba/files/3957432/deleteme.py.zip)

**Comment by stuartarchibald** [comment]
Thanks for the report and reproducer. There's two things to note:

1. Operations involving an unsigned int and a signed into often end up as a float result, this is due to NumPy rules.
```
In [10]: a = np.uint64(10)                                                                                                      

In [11]: b = np.int64(20)                                                                                                       

In [12]: c = a + b                                                                                                              

In [13]: type(c)                                                                                                                
Out[13]: numpy.float64
```
also that operations on signed and unsigned 32 bit values often end up as `int64`, and then unsigned anything with `int64` often ends up as a float.

2. That Numba treats all literal integers as signed (there's a long running issue/debate about changing this and it's something that will happen), however, this means doing `a << 2` if `a` is unsigned will likely trip the behaviours in 1.

Here's a code which largely fixes it, but `mod` is explicitly defined as `np.int32`, so I'm leaving that for you to change to e.g `np.uint32` or something else as you see fit.
```python
from numba import cuda

import numpy as np

@cuda.jit
def mult_mod_v03(a, b, c):
    tx = cuda.blockDim.x*cuda.blockIdx.x+cuda.threadIdx.x
    # define constant unsigned literals
    uint32_zero = np.uint32(0)
    uint32_one = np.uint32(1)
    uint32_hex7 = np.uint32(0x7)

    tempc0 = uint32_zero
    tempc1 = uint32_zero
    tempc2 = uint32_zero
    tempc3 = uint32_zero
    tempc4 = uint32_zero
    tempa0 = a[0,tx]
    tempa1 = a[1,tx]
    tempa2 = a[2,tx]
    tempa3 = a[3,tx]
    tempa4 = a[4,tx]
    mod = np.int32(2**13+7) # this is causing the float. uint ^= int --> float
    mask = np.int32(1)

    for n in range(32):
        if (b[4,tx] & mask):
            tempc4 ^= tempa4
            tempc3 ^= tempa3
            tempc2 ^= tempa2
            tempc1 ^= tempa1
            tempc0 ^= tempa0
        tempa0 <<= uint32_one
        tempa0 += np.uint32(tempa1 >= 0x80000000)
        tempa1 <<= uint32_one
        tempa1 += np.uint32(tempa2 >= 0x80000000)
        tempa2 <<= uint32_one
        tempa2 += np.uint32(tempa3 >= 0x80000000)
        tempa3 <<= uint32_one
        tempa3 += np.uint32(tempa4 >= 0x80000000)
        tempa4 <<= uint32_one
        if (tempa0 >= 8):
            tempa4 ^= mod #---------- THIS LINE IS THE PROBLEM
        tempa0 &= uint32_hex7
        mask <<= uint32_one

    c[0,tx] = tempc0
    c[1,tx] = tempc1
    c[2,tx] = tempc2
    c[3,tx] = tempc3
    c[4,tx] = tempc4

# Host code  
threadsperblock = 256
blocks = 4
size1 = threadsperblock * blocks

np.random.seed(7)

data1 = np.random.randint(0,2**32,[5, size1],dtype=np.uint32)##.astype(np.int32)
data2 = np.random.randint(0,2**32,[5, size1],dtype=np.uint32)




data1_d = cuda.to_device(data1)
data2_d = cuda.to_device(data2)
outdata_d = cuda.device_array([5,size1],dtype=np.int32)

blockspergrid = size1 // threadsperblock
mult_mod_v03[blockspergrid, threadsperblock](data1_d, data2_d, outdata_d) 


outdata = outdata_d.copy_to_host()
 
for n in range(5):
    print(n, outdata[n,:])

```

Hope this helps.

**Comment by coreyhahn** [comment]
This is intuitive.  Thank your for the explanation.

**Comment by stuartarchibald** [comment]
> This is intuitive. Thank your for the explanation.

No problem, thanks for using Numba!
