### ISSUE TITLE
Why numba decorators is not compatible with some numpy functions?

### ISSUE THREAD

**Issue by AbdolvahabT** [numba/numba#4953]
numba decorators like jit is not compatible with some numpy functions like tile. When I write some functions to define them the code will be slow. And I have no idea to solve these problems.

**Comment by esc** [comment]
@AbdolvahabT thanks for asking about this on the Numba issue tracker. Only a subset of Numpy is supported, you can read more about this here:

http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
