### ISSUE TITLE
Jitclass with List crashes when pop element

### ISSUE THREAD

**Issue by elch10** [numba/numba#4960]
I have following code:
```python
from numba import jitclass, int32, float32, types, njit
from numba.typed import List
import numpy as np


_spec = [
    ('sigma',types.int32),
    ('Y_rf', types.ListType(float32[::, ::1])),
]

@jitclass(_spec)
class DensityRatioEstimation:
    def __init__(self, sigma):
        self.sigma = sigma
        l = List()
        l.append(np.array([[0.]], dtype=float32))
        self.Y_rf = l

    def add_arr(self, arr):
        self.Y_rf.pop(0) # <--- crashes here
        self.Y_rf.append(arr)

inst = DensityRatioEstimation(12)
inst.add_arr(np.array([[1.]], dtype=np.float32))
print(inst.Y_rf)
```
When called `self.Y_rf.pop(0)` in `DensityRatioEstimation.add_arr` python crashes (I think it is due numba) without no error logged.

`Python 3.7.3` and `numba 0.46.0`

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce.

**Comment by francoislauger** [comment]
I have the same proble with a very similar code. With Numba 0.48 and python 3.7.6, llvmlite-0.31 I got this error with the code of @elch10 :
```
python(44439,0x11cda35c0) malloc: *** error for object 0x7fbd73a4c630: pointer being freed was not allocated
python(44439,0x11cda35c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by francoislauger** [comment]
My use is with an instance of jitclass in an List() :
```
import numpy as np
from numba import njit,jitclass,float64
from numba.typed import Dict,List

person_spec = [("age",float64)]
@jitclass(person_spec)
class person():
    def __init__(self,age):
        self.age= np.float(age)

@njit()
def simulation(n):
    pop = List()
    for i in range(n):
        pop.append(person(np.random.randint(0,100)))
    print(len(pop))
    to_remove = List()
    for i in range(n-5,n):
        to_remove.append(i)
    to_remove.sort(reverse=True)
    print(to_remove)
    for i in to_remove:
        print(i)
        pop.pop(i)
simulation(10)
## Error msg:
python(38925,0x1130025c0) malloc: *** error for object 0x7fb1326f9cd0: pointer being freed was not allocated
python(38925,0x1130025c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by esc** [comment]
There is now a potential fix for this issue in #5602 -- although that one deals with NumPy arrays specifically, it should be good for this issue too.

**Comment by esc** [comment]
I tried #5602 with both snippets listed in this issue and both no longer segfault. @elch10 @francoislauger -- would you have some spare cycles to test and confirm?

**Comment by stuartarchibald** [comment]
@esc Should probably push these through valgrind to make sure that the segfault hasn't just disappeared by accident?

**Comment by esc** [comment]
I am still struggling to create a minimal reproducer. My initial assumption was that it has something to do with doing a `pop` on a list of jitclass instances. But that doesn't seem to suffice:

```
from numba import njit, jitclass, int32
from numba.typed import List


@jitclass([('value', int32)])
class Simple(object):
    def __init__(self, value):
        self.value = value


@njit
def foo():
    l = List((Simple(23),))
    l.pop()
    return l


print(repr(foo()))
```

**Comment by francoislauger** [comment]
With the pull request (0.50.0.dev0+117.g8d4c4f4df) both the minimum reproducer and my snippets are working.

**Comment by esc** [comment]
@francoislauger excellent, thanks very much for trying this out and reporting back!  Thanks also for the reproducer, I will probably include it as a test case!

Note to self: https://numba.pydata.org/numba-doc/latest/developer/debugging.html#memcheck

**Comment by esc** [comment]
closing via #5602
