### ISSUE TITLE
parfors issue with recent patch

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#4963]
## Reporting a bug

This:
```python
from numba import njit
import numpy as np

N = 5
M = 17

@njit(parallel=True)
def test_func(nthreads):
    buf = np.zeros((M, N))
    return buf

test_func(23)
```
now reports 
```
numba/numba/lowering.py", line 1154, in getvar
    return self.varmap[name]
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'$12call_method.5_size0.1'

File "foo123321.py", line 9:
def test_func(nthreads):
    buf = np.zeros((M, N))
```
on master as of 71ebcc9.

bisect points to `[b7300f5f0e4c8b09cf58716101392c916b54d669] Experiment with union type` but it might be that in combination with other recent things.

**Comment by asmeurer** [comment]
Specifically PR https://github.com/numba/numba/pull/4910. Doing a `git revert -m 1 d46a516e1852a3b66226f63cac9a96a1521fba8a` (and fixing the trivial conflicts) fixes this. Perhaps if a simple fix cannot be found that PR should be reverted?

**Comment by stuartarchibald** [comment]
#4910 adds an important feature, so reverting isn't really feasible. A fix will be found.

**Comment by stuartarchibald** [comment]
I've found the bit of code that's triggering it, it's here: https://github.com/numba/numba/blob/0072af34ff11b1337870458d0bcc3fa64d78c5c6/numba/array_analysis.py#L1501-L1511

commenting that out makes the sample above pass. I think I've just done this analysis section wrong in the midst of writing the loop body versioning code. @DrTodd13 any chance you could perhaps take a look as well please, think you are more familiar with this code path than me? Thanks!
