### ISSUE TITLE
Unknown attribute 'set_trace' of type Module(<module 'pdb' from '/home/xxx/.conda/envs/torch12/lib/python3.6/pdb.py'>)

### ISSUE THREAD

**Issue by WhatAShot** [numba/numba#4965]
when I use "pdb" to debug:
```
import numpy as np
from numba import cuda
@cuda.jit
def histogram(x, xmin, xmax, histogram_out):
    nbins = histogram_out.shape[0]
    bin_width = (xmax - xmin) / nbins
    start = cuda.grid(1)
    stride = cuda.gridsize(1)

    ### DEBUG FIRST THREAD
    if start == 0:
        from pdb import set_trace; set_trace()
    ###

    for i in range(start, x.shape[0], stride):
        bin_number = np.int32((x[i] + xmin)/bin_width)

        if bin_number >= 0 and bin_number < histogram_out.shape[0]:
            cuda.atomic.add(histogram_out, bin_number, 1)

x = np.random.normal(size=50, loc=0, scale=1).astype(np.float32)
xmin = np.float32(-4.0)
xmax = np.float32(4.0)
histogram_out = np.zeros(shape=10, dtype=np.int32)

histogram[64, 64](x, xmin, xmax, histogram_out)

print('input count:', x.shape[0])
print('histogram:', histogram_out)
print('count:', histogram_out.sum())
```

An error raise: 
```
Unknown attribute 'set_trace' of type Module(<module 'pdb' from '/home/xxx/.conda/envs/torch12/lib/python3.6/pdb.py'>)
```
It's weird...
But I test on the console session,
```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
>>> pdb.set_trace()
--Return--
> <stdin>(1)<module>()->None
(Pdb) 
...
```
that means the package is installed and works well. So I don't know what happens...

**Comment by stuartarchibald** [comment]
Thanks for the report. You cannot use `pdb` from compiled code, `numba.*jit` is creating a compiled executable and that is executing in place of the normally interpreted Python code, therefore things like `pdb` aren't really applicable. If you want to debug compiled code tools such as `gdb` and `lldb` are needed. The CPU target has `gdb` support as a built-in function http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#debugging-jit-compiled-code-with-gdb, the CUDA targets require running the code under [`CUDA` `gdb`](https://docs.nvidia.com/cuda/cuda-gdb/index.html). The Numba CUDA target also has a simulator http://numba.pydata.org/numba-doc/latest/cuda/simulator.html which will simulate execution of your CUDA code on a CPU and in this case `pdb` should work, I'd recommend trying this first for your code above.

Also, if you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by WhatAShot** [comment]
Thank you so much!
