### ISSUE TITLE
Vectorized function not working in nopython mode

### ISSUE THREAD

**Issue by fingoldo** [numba/numba#4969]
Trying to calculate running maximum:

```python
@numba.vectorize(["int32(int32,int32)","int64(int64,int64)","float32(float32,float32)"])
@numba.njit()
def nmax(x, y):
    if x>y:
        return x
    else:
        return y
@numba.njit()
def test():
    a = np.arange(12)[::-1]
    return a,nmax.accumulate(a)
test()
```
however, Numba 0.46.0 throws error

> Unknown attribute 'accumulate' of type Function(<numba._DUFunc 'nmax'>)

Starts working fine after un-njitting the test function.
However, i obviously want to call nmax from the nopython mode...
Any help please...

**Comment by stuartarchibald** [comment]
Thanks for the report. This was recently clarified in https://github.com/numba/numba/pull/4578 for the upcoming 0.47 release.

> Note
> Only the broadcasting features of ufuncs are supported in compiled code.

Rendered docs are here http://numba.pydata.org/numba-doc/dev/user/vectorize.html#the-vectorize-decorator

Essenitally, what is in the above (calling `.accumulate` on a Numba `@vectorize` function from inside a `@njit` decorated function) is not yet supported.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
