### ISSUE TITLE
Unicode equality overload regression

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#4970]
## Reporting a bug

- [x] I am using the latest ~~released~~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The overload for `eq` of unicodes on current master always returns `False` if one of the types is unicode but the other one is not. This is too generic and does not allow defining comparison with unicodes for extension types (e.g. String arrays). Here is a simple example:

```python
import operator
import numba
from numba.extending import overload, register_model, models, unbox, NativeValue, typeof_impl

class Foo:
    pass

class FooType(numba.types.Type):
    def __init__(self):
        super(FooType, self).__init__(name='Foo')


foo_type = FooType()
register_model(FooType)(models.OpaqueModel)


@typeof_impl.register(Foo)
def _typ_foo(val, c):
  return FooType()


@unbox(FooType)
def unbox_foo(typ, obj, c):
  return NativeValue(c.context.get_dummy_value())


@overload(operator.eq)
def foo_eq(a, b):
    if a == FooType():
        return lambda a, b: True


@numba.njit
def f(a):
    return a == "A"


print(f(Foo()))  # prints False instead of True
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This change was made to support the use of heterogeneous container types in a wider range of scenarios. I think this raises the question of, how, in general, does this sort of thing get supported. We have to be able to define type based equality to permit more dynamic (albeit still static) typing and ensure things like `'a' == 12` work. One obvious way is via the `resolve_value_type/get_call_type/get_function` idiom, but this requires having a typing/codegen context around and associated hassle of `@intrinsic`. I'm wondering again whether `@overload` should store a reference to these precisely for this sort of scenario?

**Comment by ehsantn** [comment]
Ideally, extension functions like `@overload` should not be generic, and should just handle the input types specifically. To make it easier in this case, maybe there could be a concept of "default overload" that is used if other overloads failed. But specifying all basic types isn't too bad and can ensure robustness.

**Comment by stuartarchibald** [comment]
> Ideally, extension functions like `@overload` should not be generic, and should just handle the input types specifically.

I in part agree. I agree in that being generic in this case is not ideal. I'm struggling to agree about spelling out numerous of type combinations vs. doing some sort of secondary resolve. Whilst it's easy to say "one input must be string, string literal or unicode char sequence" trying to say "other input can be any of \<literally the entire *unextended* type system apart from those other three things\>" is not so easy. Perhaps if there were a set of all types, that might help, but really this is something to think about for when declarative typing arrives.

> To make it easier in this case, maybe there could be a concept of "default overload" that is used if other overloads failed. But specifying all basic types isn't too bad and can ensure robustness.

Maybe "default overload" could work, but we'd probably need to set up a special place to go look for those to prevent interference with normal resolution.

**Comment by stuartarchibald** [comment]
@ehsantn @sklam this https://github.com/numba/numba/pull/4983 implements the discussed "fix" from the core developer meeting. Having actually written this I'm not sure I'm comfortable with it, I still kind of more want to be able to spell out the set difference of `(all internal types - locally defined accepted types)` and use that in the `@overload` guard instead.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/4987 is an alternative to #4983 that requires nothing of users defining extensions to the type system, onus is on Numba to add guards in internal all-type consuming functions to make sure that it only impacts the closed internal Numba type system. I prefer this approach.

**Comment by ehsantn** [comment]
Thank you, @stuartarchibald ! Both approaches give maximum flexibility to the user and are fine with me. I agree that the second one seems a bit cleaner.

**Comment by stuartarchibald** [comment]
@ehsantn no problem, I think we all prefer the second version, adding it into 0.47.
