### ISSUE TITLE
Regression finding libNVVM in 0.46.0

### ISSUE THREAD

**Issue by pitrou** [numba/numba#4979]
Since 0.46.0 I get the following error. 0.45.0 was fine (both packages from conda-forge):
```
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 111, in __new__
    inst.driver = open_cudalib('nvvm', ccc=True)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/libs.py", line 47, in open_cudalib
    raise OSError('library %s not found' % lib)
OSError: library nvvm not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/arrow/dev/python/pyarrow/tests/test_cuda_numba_interop.py", line 232, in test_pyarrow_jit
    increment_by_one[blockspergrid, threadsperblock](darr)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 799, in __call__
    kernel = self.specialize(*args)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 810, in specialize
    kernel = self.compile(argtypes)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 829, in compile
    kernel.bind()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 543, in bind
    self._func.get()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 421, in get
    ptx = self.ptx.get()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 392, in get
    **self._extra_options)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 468, in llvm_to_ptx
    cu = CompilationUnit()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 146, in __init__
    self.driver = NVVM()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 116, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
library nvvm not found
```

I am on Ubuntu 18.04 with the `nvidia-cuda-dev` package installed.
```
$ locate nvvm
[ ... ]
/usr/include/nvvm.h
/usr/lib/cuda/nvvm
/usr/lib/cuda/nvvm/libdevice
/usr/lib/x86_64-linux-gnu/libnvvm.so
/usr/lib/x86_64-linux-gnu/libnvvm.so.3
/usr/lib/x86_64-linux-gnu/libnvvm.so.3.2.0
[ ... ]
```

**Comment by sklam** [comment]
Can you confirm that it worked in 0.45.0? IIRC, last change in the cuda library finding logic is in 0.44.  Since then, you can use the following to test the library loading:

```python
from numba.cuda import cudadrv
cudadrv.libs.test()
```

On my ubuntu 18.04 + `nvidia-cuda-dev` setup, i can confirm that numba can't find nvvm since 0.44.

**Comment by sklam** [comment]
In the past, the convention is that cuda on linux is located at `/usr/local/cuda` and the `libnvvm` library is in a subdirectory named `nvvm/lib64`. The `nvidia-cuda-dev` package is completely different and puts the libraries in `/usr/lib/x86_64-linux-gnu/` without any subdirectories for `libnvvm`. It can now be loaded with just `ctypes.CDLL('libnvvm.so')`, but that has never worked before.

@gmarkall, do you know if there is a new recommended load path?

**Comment by pitrou** [comment]
Yes, it works with 0.45.0. I am using the following variables (apparently they are deprecated?):
```
export NUMBAPRO_LIBDEVICE=/usr/lib/cuda/nvvm/libdevice
export NUMBAPRO_NVVM=/usr/lib/x86_64-linux-gnu/libnvvm.so
```

```python
>>> import numba                                                                                                                                                            
>>> numba.__version__                                                                                                                                                       
'0.45.0'
>>> from numba.cuda import cudadrv                                                                                                                                          
>>> cudadrv.libs.test()                                                                                                                                                     
/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=/usr/lib/x86_64-linux-gnu/libnvvm.so.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_LIBDEVICE=/usr/lib/cuda/nvvm/libdevice.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
Finding cublas from <unavailable>
	ERROR: can't locate lib
Finding cusparse from <unavailable>
	ERROR: can't locate lib
Finding cufft from <unavailable>
	ERROR: can't locate lib
Finding curand from <unavailable>
	ERROR: can't locate lib
Finding nvvm from NUMBAPRO_NVVM
	located at /usr/lib/x86_64-linux-gnu/libnvvm.so
Finding libdevice from NUMBAPRO_LIBDEVICE
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok
False
>>>                                                                                                                                                                         
```

**Comment by gmarkall** [comment]
Just catching up on recent history with this deprecation (I don't have an Ubuntu 18.04 system handy to try with) - @pitrou does setting `CUDA_HOME` (http://numba.pydata.org/numba-doc/latest/cuda/overview.html#setting-cuda-installation-path) allow you to provide the correct location of libNVVM? If not, perhaps we need to add a `NUMBA_NVVM` env var that provides the same function as the old `NUMBAPRO_NVVM`?

**Comment by pitrou** [comment]
`CUDA_HOME` does not work, no. Perhaps Numba should simply detect the Ubuntu layout?

**Comment by sklam** [comment]
I think we can do that by falling back to the system loader; i.e. `ctypes.CDLL('libnvvm.so')`. It looks like the debian packages are putting all cuda libraries in the default search both.  However, just having libnvvm is not enough. We need to find where the `libdevice` bitcode files are located.

**Comment by sklam** [comment]
I also noticed that the CUDA linux installation guide (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) has no mentioning of the debian package.

**Comment by gmarkall** [comment]
> I also noticed that the CUDA linux installation guide (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) has no mentioning of the debian package.

There are debian packages that you will reach from the link to the downloads - e.g. https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork - however, I don't think the `nvidia-cuda-dev` package from Debian NVIDIA Maintainers (which I think @pitrou is using) is one of those. IIRC the packages from developer.nvidia.com do install into /usr/local/cuda.

>  However, just having libnvvm is not enough. We need to find where the libdevice bitcode files are located.

Right now I have the `nvidia-cuda-dev` package installed on 18.04 and I can't find the libdevice bitcode files anywhere - I only see:

```
$ locate libdevice
/usr/lib/llvm-10/lib/clang/10.0.0/include/__clang_cuda_libdevice_declares.h
```

Are they included in `nvidia-cuda-dev`?

> I think we can do that by falling back to the system loader; i.e. ctypes.CDLL('libnvvm.so'). It looks like the debian packages are putting all cuda libraries in the default search both.

Falling back to the system loader seems reasonable, and what I'd expect / hope for as a "normal" user - in general, having shared libs on the library search path results in them being found once other options have been exhausted.

**Comment by gmarkall** [comment]
> > However, just having libnvvm is not enough. We need to find where the libdevice bitcode files are located.
> 
> Right now I have the `nvidia-cuda-dev` package installed on 18.04 and I can't find the libdevice bitcode files anywhere...

I now noticed they're in the `nvidia-cuda-toolkit` package, which places them at `/usr/lib/nvidia-cuda-toolkit/libdevice`. Maybe that would need adding as another location to search for it, in addition to falling back to the system loader for shared objects.

**Comment by gmarkall** [comment]
Just to clarify, I'd be happy to make a PR that:

1. Falls back to the system loader for shared objects if they're not otherwise found.
2. Also looks for libdevice in `/usr/lib/nvidia-cuda-toolkit`.

if there's agreement that this is an acceptable way to solve the problem - @sklam would you be happy with this?

**Comment by sklam** [comment]
@gmarkall, that should solve the problem.
