### ISSUE TITLE
[Bug Report] Compile error using prange and ravel

### ISSUE THREAD

**Issue by dk1013** [numba/numba#4996]
Below code simply won't compile.
Numba version: 0.46.0

```python
import numba as nb
import numpy as np

@nb.njit(parallel=True)
def foo(X):
    X.ravel()[np.isnan(X.ravel())] = 0
    n_row, n_col = X.shape
    out = np.full((n_row, n_col, 3), np.nan)
    for r in nb.prange(n_row):
        for c in range(n_col):
            out[r, c] = X[r-2:r+1, c]
    return out

foo(np.random.random((20, 20)))
```

The error message is quite long, which I ignored here. I think this is a bug because at the end of the error messaeg, it says sth like below:
"This should not have happened, a problem has occurred in Numba's internals. You are currently using Numba version 0.46.0. 
Please report the error message and traceback, along with a minimal reproducer at: ..."

## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. The code sample presented does not seem to work in pure NumPy:
```python
import numpy as np

def foo(X):
    X.ravel()[np.isnan(X.ravel())] = 0
    n_row, n_col = X.shape
    out = np.full((n_row, n_col, 3), np.nan)
    for r in nb.prange(n_row):
        for c in range(n_col):
            out[r, c] = X[r-2:r+1, c]
    return out

foo(np.random.random((20, 20)))
```
gives
```
Traceback (most recent call last):
  File "issue4996.py", line 13, in <module>
    foo(np.random.random((20, 20)))
  File "issue4996.py", line 10, in foo
    out[r, c] = X[r-2:r+1, c]
ValueError: could not broadcast input array from shape (0) into shape (3)
```
and then on Numba master branch and Numba 0.46.0 it gives me:
```
$ cat issue4996.py
import numba as nb
import numpy as np

@nb.njit(parallel=True)
def foo(X):
    X.ravel()[np.isnan(X.ravel())] = 0
    n_row, n_col = X.shape
    out = np.full((n_row, n_col, 3), np.nan)
    for r in nb.prange(n_row):
        for c in range(n_col):
            out[r, c] = X[r-2:r+1, c]
    return out

foo(np.random.random((20, 20)))

$ python -c 'import numba; print(numba.__version__)'
0.46.0

$ python issue4996.py
Traceback (most recent call last):
  File "issue4996.py", line 14, in <module>
    foo(np.random.random((20, 20)))
ValueError: cannot assign slice from input of different size
```

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
