### ISSUE TITLE
try command support

### ISSUE THREAD

**Issue by astroXiao** [numba/numba#4999]
Numba failed to use nopython mode because there is a "try" command in my code.
I hope Numba can support try command. Although we use Numba mainly for mathematic calculations, the usage of try will simplify our code sometimes.

Thanks

**Comment by esc** [comment]
@astroXiao thanks for asking about this the initial support for `try` and `except` will be introduced with the 0.47.0 release: 

https://github.com/numba/numba/pull/4995/files

The release candidate is tagged already and packages are now arriving for conda and pip.

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/4902 closing.
