### ISSUE TITLE
Complete basic NumPy ufunc support

### ISSUE THREAD

**Issue by ovillellas** [numba/numba#501]
- Ideally, all standard ufuncs in NumPy should compile in no-python mode.
- Supported ufuncs and its degree of support must be documented.

This is a task, to group similar subtasks to advance this support.

**Comment by stuartarchibald** [comment]
I think we can close this, most NumPy ufuncs are supported (Numba 0.37). If any specific ufuncs are missing new tickets can be opened just for them.
