### ISSUE TITLE
Provide documentation, docstrings, tests, examples for dynamic shared memory

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#5025]
Dynamic shared memory is supported in CUDA Python but there appears to be little in the way of documentation and examples. Some things to consider adding:

- User guide / reference documentation
- Examples
- Docstrings
- Additional tests

Some useful references:

- [CUDA C Programming guide: Execution Configuration](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#execution-configuration)
- [CUDA C Programming guide: Shared Memory](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#shared)
- [Numba-users thread in which I previously described dynamic shared memory](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/yckiwJZ0y-A)
- Issue #2463 - support for more than one dimension would be nice to add.

**Comment by leofang** [comment]
One more ref: https://stackoverflow.com/a/30524712/2344149

**Comment by gmarkall** [comment]
Thanks @leofang - I got started on documenting this but I got a bit sidetracked running into bugs whilst writing examples - e.g. https://github.com/numba/numba/pull/5099 and https://github.com/numba/numba/issues/5206 - this task is now unblocked as far as I'm aware, and just needs getting round to.

**Comment by gmarkall** [comment]
A couple of notes - dynamic shared memory is declared with a `0` shape, e.g.:

https://github.com/numba/numba/blob/3497fb205e15cb2123ef18053ca2206c0393794b/numba/cuda/tests/cudapy/test_sm.py#L140

The size of dynamic shared memory is specified as the third launch configuration parameter, e.g.:

https://github.com/numba/numba/blob/3497fb205e15cb2123ef18053ca2206c0393794b/numba/cuda/tests/cudapy/test_sm.py#L133

An open question - if you need a dynamic shared array with multiple dimensions, can you create a view on the 1D dynamic shared array? (I haven't tested this)

**Comment by k1m190r** [comment]
@gmarkall may I give this a go?
Capturing [your answer on discourse](https://numba.discourse.group/t/how-do-i-use-sharedmem-parameter-in-kernel/1841/2?u=biosckon)
