### ISSUE TITLE
How do you raise an exception from the unboxing context?

### ISSUE THREAD

**Issue by AlexanderKalistratov** [numba/numba#5030]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba
from numba.extending import (register_model, unbox, make_attribute_wrapper, typeof_impl, models)
from numba import cgutils

class Dummy:
    def __init__(self, a=0):
        self.a = a

class DummyType(numba.types.Type):
    def __init__(self):
        super().__init__(name="dummy")

@register_model(DummyType)
class DummyTypeModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [('a', numba.types.int64)]
        super().__init__(dmm, fe_type, members)

@unbox(DummyType)
def unbox_dummy(typ, val, c):
    context = c.context
    builder = c.builder

    a_obj = c.pyapi.object_getattr_string(val, "a")
    a_value = c.pyapi.long_as_longlong(a_obj)

    dmm = cgutils.create_struct_proxy(typ)(context, builder)

    with builder.if_then(a_value):
        context.call_conv.return_user_exc( # <-- here is the problem
            builder, ValueError,
            ("exception!",)
        )

    dmm.a = a_value
    return NativeValue(dmm._getvalue())

make_attribute_wrapper(DummyType, 'a', 'a')

def test_impl(d):
    return d.a

@typeof_impl.register(Dummy)
def typeof_dummy(val, c):
    return DummyType()

jtest = numba.njit(test_impl)
print(jtest(Dummy(0)))
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/numba_git/numba_master_master/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
...
  File "/home/automation/data/anaconda/envs/NUMBA_MASTER/lib/python3.7/site-packages/llvmlite/ir/builder.py", line 740, in store
    % (value.type, ptr.type))
TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot store {i8*, i32}* to i8*: mismatching types
```

numba version: 6d7cddb9084d843e12bcdf9c443bc9cce56aa02f

Looks like something wrong with `@unbox` function signature

**Comment by stuartarchibald** [comment]
Thanks for the report. In unboxing the CPython API (available as the `.pyapi` member of the unboxing context) is used to create exceptions and then the `NativeValue` ctor has a signalling bit to note whether an exception is pending. Also, the predicate in `if_then` needs to be an `i1`. Try this:
```python
import numba
from numba.extending import (register_model, unbox, make_attribute_wrapper,
                             typeof_impl, models, NativeValue)
from numba import cgutils

class Dummy:
    def __init__(self, a=0):
        self.a = a

class DummyType(numba.types.Type):
    def __init__(self):
        super().__init__(name="dummy")

@register_model(DummyType)
class DummyTypeModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [('a', numba.types.int64)]
        super().__init__(dmm, fe_type, members)

@unbox(DummyType)
def unbox_dummy(typ, val, c):
    context = c.context
    builder = c.builder

    a_obj = c.pyapi.object_getattr_string(val, "a")
    a_value = c.pyapi.long_as_longlong(a_obj)

    dmm = cgutils.create_struct_proxy(typ)(context, builder)
    errorptr = cgutils.alloca_once_value(c.builder, cgutils.false_bit)

    zero = a_value.type(0)

    with builder.if_then(builder.icmp_signed("!=", a_value, zero)):
        c.pyapi.err_format("PyExc_ValueError", "exception!")
        builder.store(cgutils.true_bit, errorptr)
        builder.ret(c.pyapi.get_null_object())

    dmm.a = a_value
    return NativeValue(dmm._getvalue(), is_error=builder.load(errorptr))

make_attribute_wrapper(DummyType, 'a', 'a')

def test_impl(d):
    return d.a

@typeof_impl.register(Dummy)
def typeof_dummy(val, c):
    return DummyType()

jtest = numba.njit(test_impl)
print(jtest(Dummy(0x0)))
print(jtest(Dummy(0x1)))
```
which gives:
```
$ python issue5030.py 
0
Traceback (most recent call last):
  File "issue5030.py", line 52, in <module>
    print(jtest(Dummy(0x1)))
ValueError: exception!
```
Will change the issue title to reflect problem.

**Comment by AlexanderKalistratov** [comment]
@stuartarchibald many thanks for the clarifications.

I've faced this issue moving SDC (a.k.a HPAT) code to newer Numba version.
One of our type uses  [_empty_nd_impl](https://github.com/numba/numba/blob/master/numba/targets/arrayobj.py#L3335) function inside `@unbox`. And `_empty_nd_impl` generates an [user exception](https://github.com/numba/numba/blob/master/numba/targets/arrayobj.py#L3382). 
It wasn't a good solution anyway, since using internal API is always a bad idea, so I think we would find some workaround.

On the other hand, this means, that we can't uses the same function inside `@unbox` and `@intrinsic`, which could be a problem.
Is it possible to use `@intrinsic` which generates user exception inside `@unbox`?

**Comment by stuartarchibald** [comment]
I see, thanks for the update.

> Is it possible to use @intrinsic which generates user exception inside @unbox?

Yes, you need a call convention wrapper, if you are prepared to wait a few weeks we will be writing one as it's needed for part of the [Q1 2020 switch to using the extension API internally (`@overload` style changes)](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/CY7oXibUwXA). Else, there's a small example here: 
https://github.com/numba/numba/blob/master/numba/targets/setobj.py#L490-L527 where Numba call convention functions (`@overload`'s for `__hash__`) need calling from a place where the CPython call convention is in use.

**Comment by AlexanderKalistratov** [comment]
@stuartarchibald thanks one more time. It is not critical for us right now, so I think we can wait. Anyway the solution is clear.

**Comment by stuartarchibald** [comment]
@AlexanderKalistratov no problem.
