### ISSUE TITLE
LLVM Assembly output gets truncated

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5032]
It seems to me that with 0.46.0, the LLVM debug output gets truncated:

```
-------------------------OPTIMIZED DUMP array_max_impl2-------------------------
; ModuleID = 'array_max_impl2'
source_filename = "<string>"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

<... snipped ...>

  %.521 = fcmp fast ogt double %.503, %max_value.
================================================================================
```

The `.` is just hanging there. It seems like a number should follow.

The code that produced this output was:

```
from numba import types
from numba.extending import intrinsic
import numba

@intrinsic
def conditional_move(typing_context, condition, lhs, rhs):
    # # check for accepted types
    # if isinstance(src, types.Integer):
    # create the expected type signature
    result_type = numba.typeof(lhs).dtype
    sig = result_type(types.Boolean, numba.typeof(lhs).dtype, numba.typeof(lhs).dtype)
    # defines the custom code generation
    def codegen(context, builder, signature, args):
        # llvm IRBuilder code here
        [condition, lhs, rhs] = args
        return builder.select(condition, lhs, rhs)
    return sig, codegen

# %%
@jit(nopython=True, nogil=True, fastmath=True, error_model='numpy')
def array_max_impl2(arr, axis=None):
    it = np.nditer(arr)
    max_value = next(it).take(0)

    for view in it:
        v = view.item()
        max_value = conditional_move(v > max_value, v, max_value)
    return max_value
```

This is not an isolated case however, see this output:

```
-------------------------OPTIMIZED DUMP array_max_impl--------------------------
; ModuleID = 'array_max_impl'
source_filename = "<string>"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

<... snipped ...>

B48.endif:                                        ; preds = %B48.endif.preheader, %B48.endif
  %max_value.016 = phi double [ %max_value.1, %B48.endif ], [ %.2032.i13, %B48.endif.preheader ]
  %.132.015 = phi i64 [ %.440, %B48.endif ], [ 1, %B48.endif.preheader ]
  %scevgep = gete
================================================================================
```

Here `getelementptr` even got truncated in the middle of the instruction name.

Here the code was:

```
MSG = zero_dim_msg("maximum")

@jit(fastmath=True)
def array_max_impl(arr, axis=None):
    if arr.size == 0:
        raise ValueError(MSG)

    it = np.nditer(arr)
    max_value = next(it).take(0)

    for view in it:
        v = view.item()
        if v > max_value:
            max_value = v
    return max_value
```

This bug makes debugging really difficult. I pulling my hair out trying to figure out how the LLVM code can possibly work. It took me ages to realise that the code in the debug out in fact CANNOT work at all...

**Comment by ARF1** [comment]
BTW, same issue with `inspect_llvm()`. It's output is truncated at exactly the same position.

**Comment by stuartarchibald** [comment]
Thanks for the report. Using this:
```python
from numba import types, jit
from numba.extending import intrinsic
import numba
import numpy as np

@intrinsic
def conditional_move(typing_context, condition, lhs, rhs):
    # # check for accepted types
    # if isinstance(src, types.Integer):
    # create the expected type signature
    result_type = numba.typeof(lhs).dtype
    sig = result_type(types.Boolean, numba.typeof(lhs).dtype, numba.typeof(lhs).dtype)
    # defines the custom code generation
    def codegen(context, builder, signature, args):
        # llvm IRBuilder code here
        [condition, lhs, rhs] = args
        return builder.select(condition, lhs, rhs)
    return sig, codegen

# %%
@jit(nopython=True, nogil=True, fastmath=True, error_model='numpy')
def array_max_impl2(arr, axis=None):
    it = np.nditer(arr)
    max_value = next(it).take(0)

    for view in it:
        v = view.item()
        max_value = conditional_move(v > max_value, v, max_value)
    return max_value


a = np.zeros((4,))
array_max_impl2(a)

print(array_max_impl2.inspect_llvm(array_max_impl2.signatures[0]))
```
I cannot reproduce either issue on linux, wonder if this is windows LLVM/windows terminal related.

**Comment by ARF1** [comment]
I did consider the terminal but there are two factors that made me dismiss it as an option:

- The truncated output is preceeded and followed by the output of other functions. (Note the line with `===` following the truncated output to deliminate from the next function...
- The output is also truncated with `inspect_llvm()` in jupyter.

So if it is a terminal issue, it is some deeply buried instance of terminal that is invoked for each function in turn. It would not appear to be an issue with the terminal that is used to invoke python from what I can tell from above analysis.

**Comment by ARF1** [comment]
@stuartarchibald You were right after all. I checked with a different terminal and it does not show this problem.

For the record: Visual Studio Code does strange things to numba's debug output... I am still baffled why it did not simply cut all the output but instead did cut the output per-function.

Many thanks for your help.

**Comment by stuartarchibald** [comment]
@ARF1 thanks for reporting back, I'm not sure how to "fix" such problems on the terminal but if you have a reproducer someone could take a look. Thanks.

**Comment by ARF1** [comment]
@stuartarchibald It's not for numba to fix. VSCode will have to fix it for sure. That's why I closed the issue after I realized the source.

Turns out vscode intentionally truncates "too long" jupyter text output for "performance reasons" without notifying the user (and without documentation from what I can tell). For them it's intended behaviour... I suspect they have similar "performance enhancements" for their shell. I will be filing a report with them.

 Sorry for wasting your time.

**Comment by stuartarchibald** [comment]
> @stuartarchibald It's not for numba to fix. VSCode will have to fix it for sure. That's why I closed the issue after I realized the source.

ok, if you're sure there's nothing we can do.

> Turns out vscode intentionally truncates "too long" jupyter text output for "performance reasons" without notifying the user (and without documentation from what I can tell). For them it's intended behaviour... I suspect they have similar "performance enhancements" for their shell. I will be filing a report with them.

Great, thanks.

> Sorry for wasting your time.

Not at all. It's good to know that this is a problem, that it's recorded may well be useful for others.
