### ISSUE TITLE
Review minimum requirements and version pinning

### ISSUE THREAD

**Issue by seibert** [numba/numba#5036]
We need to make sure that the documentation, setup.py metadata, and the conda recipes all reflect:

* Python >= 3.6
* NumPy >= 1.15 (but 1.11 allowed for building, so this is a doc-only requirement, I think?)
* SciPy, if present >= 1.0.0
* Conda recipe needs to not pin to specific NumPy minor release
* Do need to pin to most recent llvmlite minor release (see #5035 for the consequences of not doing that in setup.py)

**Comment by seibert** [comment]
See #5046

**Comment by esc** [comment]
All pinning tasks have been merged, so I am closing this one now.
