### ISSUE TITLE
List comprehensions unsupported

### ISSUE THREAD

**Issue by pitrou** [numba/numba#504]
```
>>> @jit
... def f():
...     return [x * 2 for x in range(5)]
...
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "numba\dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "numba\dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "numba\compiler.py", line 90, in compile_extra
    bc = bytecode.ByteCode(func=func)
  File "numba\bytecode.py", line 296, in __init__
    table = utils.SortedMap(ByteCodeIter(code))
  File "numba\utils.py", line 46, in __init__
    for i, (k, v) in enumerate(sorted(seq)):
  File "numba\bytecode.py", line 216, in next
    raise NotImplementedError(ts % tv)
NotImplementedError: offset=33 opcode=12 opname=LIST_APPEND
```

**Comment by mangecoeur** [comment]
+1

**Comment by datnamer** [comment]
+1

**Comment by jiamo** [comment]
If list can't append , using what to replace it?  Is there something support data types  do the same logic?

**Comment by InonS** [comment]
+1

**Comment by PeterMinin** [comment]
+1 to jiamo: is there any replacement available?
Also, is the pull request #1045 waiting for a 3.x implementation?

**Comment by seibert** [comment]
At the time, it was holding for a 3.x implementation.  Now that we've actually implemented real list support in nopython mode, I suspect the entire implementation needs to change.  (On the plus side, we can now contemplate making list comprehensions work in nopython mode, which was not possible even with #1045.)

**Comment by PeterMinin** [comment]
Thanks for the info. And for the whole project, by the way!

**Comment by astewart-twist** [comment]
+1

**Comment by InonS** [comment]
@seibert, that would be great! We're all just waiting for [those missing basic features](http://numba.pydata.org/numba-doc/dev/reference/pysupported.html#constructs) to be implemented, so we can produce quality code

**Comment by camlorn** [comment]
Any update on this?  I'm running into it as well.

**Comment by seibert** [comment]
Nothing to report yet.  We're working on recursion, additional linear algebra, and clearing out bug reports for the next release.

**Comment by amrit-poudel** [comment]
@seibert : Any news on this yet? Thanks for the effort.

I run into the same error as above (NotImplementedError: offset=98 opcode=0x5e opname=LIST_APPEND)  when I try to jit a python function whose input and output are lists of numpy arrays of  complex data type.  Are there any other alternatives that I could use in such a situation?

Thanks.

**Comment by kilojoules** [comment]
+1

**Comment by stuartarchibald** [comment]
Added in https://github.com/numba/numba/pull/2369
