### ISSUE TITLE
Can @jitclass support numpy.array([string])?

### ISSUE THREAD

**Issue by WanBenLe** [numba/numba#5050]
like 
@jitclass( 'name', types.byte)
class a:
def __init__(self):
self.name=np.arraty(['a','b'])
will raise Error

**Comment by stuartarchibald** [comment]
Thanks for the report. The answer is "sort of", IIRC there's no support for creating `np.ndarray` with strings inside Numba jitted functions, but Numba can understand such arrays if they are passed in, e.g.:
```python
from numba import njit, jitclass, types
import numpy as np

spec = {'name': types.Array(types.UnicodeCharSeq(1), 1, 'C')}


@jitclass(spec)
class MyClass(object):
    def __init__(self, data):
        self.name = data


my_data = np.array(['a','b'])
inst = MyClass(my_data)

print(inst.name)
```

**Comment by shaunc** [comment]
Is there also a workaround for variable length strings? I have a array of strings from Xarray that gets typed as (e.g.) '<U12'  -- where Xarray (or netcdf) sets the size of the dtype on load. I have tried declaring `("cut", string[:])` and passing my strings in as `cut=patterns.cut.values.astype(str)` get:
``` Can only insert {i8*, i64, i32, i32, i64, i8*, i8*}* at [4] in {i8*, i8*, i64, i64, {i8*, i64, i32, i32, i64, i8*, i8*}*, [1 x i64], [1 x i64]}: got [12 x i32]*```

... ?

**Comment by stuartarchibald** [comment]
> Is there also a workaround for variable length strings? I have a array of strings from Xarray that gets typed as (e.g.) '<U12' -- where Xarray (or netcdf) sets the size of the dtype on load. I have tried declaring `("cut", string[:])` and passing my strings in as `cut=patterns.cut.values.astype(str)` get:
> ` Can only insert {i8*, i64, i32, i32, i64, i8*, i8*}* at [4] in {i8*, i8*, i64, i64, {i8*, i64, i32, i32, i64, i8*, i8*}*, [1 x i64], [1 x i64]}: got [12 x i32]*`
> 
> ... ?

@shaunc I think you'd need to dynamically create a `jitclass` based on the type appearing from Xarray. e.g.
```python
from numba import njit, types
from numba.experimental import jitclass
import numpy as np
import string

def mock_xarray_load():
    return np.array([string.ascii_letters], dtype='<U12')

my_data = mock_xarray_load()

# specialise type on data from Xarray
char_size = np.dtype('<U1').itemsize
uty = types.UnicodeCharSeq(my_data.dtype.itemsize // char_size)
spec = {'name': types.Array(uty, 1, 'C')}


@jitclass(spec)
class MyClass(object):
    def __init__(self, data):
        self.name = data

inst = MyClass(my_data)

print(inst.name)
```

**Comment by shaunc** [comment]
Thanks! ... hmm... now I have to figure out how to keep mypy happy with my dynamic MyClass.

**Comment by gmarkall** [comment]
Closing this issue as the original questions appear to be answered.
