### ISSUE TITLE
is there any Thread Safe Container ?

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#5070]
Hi,

My below code gives error. Is there any way to accumulate result in a thread safe container and get from it numba paralell function  like : 
```python
@njit(parallel=True )
def Search_2(compare_desc,  p_descs, ):
    res_count= 0
    count = 0
    for x in prange(30000):
        dist = np.sum((compare_desc - p_descs[88]))
        count = count+1

        if float(dist) < 4:
                name_number = x
                a_float = dist
                an_int = x
                small_float = sim
                new_np = np.asarray([types.float32(res_count), types.float32(a_float), types.float32(an_int), types.float32(small_float)])
                result_np[res_count, 0] =  types.float32(res_count)
                result_np[res_count, 1] = types.float32(a_float)
                result_np[res_count, 2]= types.float32(an_int)
                result_np[res_count, 3]= types.float32(small_float)
                res_count = res_count +1

    return result_np
```

it gives error:

> numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (readonly array(float32, 2d, C), Tuple(int64, Literal[int](0)), float32)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    TypeError: Cannot modify value of type readonly array(float32, 2d, C)
    raised from /Users/tulpar/.venv/lib/python3.7/site-packages/numba/typing/arraydecl.py:179
In definition 9:
    TypeError: Cannot modify value of type readonly array(float32, 2d, C)
    raised from /Users/tulpar/.venv/lib/python3.7/site-packages/numba/typing/arraydecl.py:179
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at /Users/tulpar/Projects/deploy/_process_queue_tests.py (85)

File "_process_queue_tests.py", line 85:
def Search_2(compare_desc,  p_descs, ):
    <source elided>
                new_np = np.asarray([types.float32(res_count), types.float32(a_float), types.float32(an_int), types.float32(small_float)])
                result_np[res_count, 0] =  types.float32(res_count)
                ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by stuartarchibald** [comment]
Thanks for the report. I'd guess that `result_np` is defined in the `globals()` of the function `Search_2` and as a result it is read-only (see http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable). If it's passed in as an argument you should be able to mutate it. I don't think this is thread-safety related?

**Comment by MyraBaba** [comment]
@stuartarchibald 
This one is looks working. any comment or logic error ? 
```

`@njit(parallel=True )
def Search_2(compare_desc,  p_descs, ):
    tupZ = np.asarray([1, 18.265, 100, 0.1])
    result_np = np.full((20000,4),19.11)

    res_count= 0
    count = 0
    total = p_descs.shape[0]
    for x in prange(total):
        sim = np.dot(compare_desc, p_descs[x].T)
        dist = np.sum(np.square(compare_desc - p_descs[x]))
        count = count+1

        if float(dist) < 1.5:
                name_number = x
                a_float = dist
                an_int = x
                small_float = sim
                result_np[res_count, 0] = x
                result_np[res_count, 1] =  a_float
                result_np[res_count, 2]=  x
                result_np[res_count, 3]= small_float
                res_count = res_count +1

    return result_np , res_count`
```

**Comment by esc** [comment]
@MyraBaba I am assuming this issue has been solved for now. I am closing it thus. Please feel free to re-open in case the problem resurfaces.
