### ISSUE TITLE
Readability issues in the docs

### ISSUE THREAD

**Issue by asmeurer** [numba/numba#5074]
This was originally reported at https://github.com/numba/numba/pull/4615#issuecomment-573257722

There are some serious readability issues in the documentation. 

1. The sidebar with the table of contents flows into the contents. 

2. The "see also" sections are red on purple, which makes them very difficult to read. 

If you build the docs in that branch (or wait until it is merged) and take a look at docs/_build/html/user/threading-layer.html you'll see what I'm talking about. Here is a screenshot that shows both issues

<img width="953" alt="Screenshot 2020-01-13 12 26 24" src="https://user-images.githubusercontent.com/71486/72285301-10530e80-3600-11ea-8b39-a3faf4878b8d.png">

**Comment by stuartarchibald** [comment]
Thanks for the report, I think the sidebar comes from a version of the doc libraries that Numba does not use (IIRC we found the side bar did that and had other problems so opted for a version without it). The red on purple is pretty unreadable, suggestions welcomed.

**Comment by asmeurer** [comment]
>  I think the sidebar comes from a version of the doc libraries that Numba does not use (IIRC we found the side bar did that and had other problems so opted for a version without it).

OK, then there should be a version check in conf.py. Or if the library is simple enough I would suggest just vendoring it, unless it's possible to fix the latest version with some configuration.

For red-on-purple, I guess you could add a white background behind the text, similar to what is done in a note with `code` (see the note at the top of the threading layer docs). Either that or make the text white. Personally I don't think the purple looks good anyway aesthetically, but if you want to keep it having white text or a white background on the text is the only way to make it readable.

**Comment by seibert** [comment]
Rather than go down a custom CSS rabbit hole, is there a different Sphinx theme that we should switch to which has a less buggy layout and is more readable?

**Comment by asmeurer** [comment]
The sidebar issue can be fixed by disabling the scrolling. Maybe there is a better fix that doesn't disable it. Probably an upstream issue should be raised in sphinx-bootstrap-theme. 

I can't figure out how to fix the CSS for the link colors. It seems the background color for `literal` is already set to white, but it gets overridden by the background color for links, which is set to transparent. 

https://github.com/numba/numba/pull/5118.

**Comment by stuartarchibald** [comment]
Closing as this ticket refers to the old docs templates etc. Numba now uses RTD:
https://numba.readthedocs.io/en/stable/index.html
which hopefully renders more clearly.
