### ISSUE TITLE
Please include support for Python exception handling

### ISSUE THREAD

**Issue by parikshitchitnis** [numba/numba#5077]
Numba currently does not seem to support exception handling in Python. Please include the functionality so that Numba does not raise errors during try except blocks in Python code.

**Comment by stuartarchibald** [comment]
Thanks for the report. Basic support for this was added in Numba 0.47.0 http://numba.pydata.org/numba-doc/dev/reference/pysupported.html#exception-handling

If you would like to try out the latest releases of Numba they are available in the `numba` channel:
```bash
conda install -c numba numba=0.47.0
```
