### ISSUE TITLE
dtype=np.bool doesn't work in array constructors

### ISSUE THREAD

**Issue by rjzak** [numba/numba#5080]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I copied and pasted into a new file this jitclass example, and it worked. https://numba.pydata.org/numba-doc/latest/user/jitclass.html However, when changing the `spec` and array `dtype` to `np.bool`, it has an error, yet boolean types seem to be supported https://numba.pydata.org/numba-doc/dev/reference/types.html

    >>> import numba
    >>> numba.__version__
    '0.47.0'
    >>> numba.boolean[:]
    array(bool, 1d, A)
    >>> import numpy
    >>> numba.typeof(numpy.zeros(10, dtype=numpy.bool))
    array(bool, 1d, C)

**Code:**

    import numpy as np
    from numba import jitclass          # import the decorator
    from numba import int32, float32, bool_    # import the types

    spec = [
        ('value', int32),               # a simple scalar field
        ('array', bool_[:]),          # an array field
    ]

    @jitclass(spec)
    class Bag(object):
        def __init__(self, value):
            self.value = value
            self.array = np.zeros(value, dtype=np.bool)

        @property
        def size(self):
            return self.array.size

        def increment(self, val):
            for i in range(self.size):
                self.array[i] = val
            return self.array

    if __name__ == '__main__':
        p = Bag(100)
        p.increment(1)
        print(p.size)

**Error:**

```
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function zeros>) with argument(s) of type(s): (int64, dtype=Function(<class 'bool'>))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function zeros>)
[2] During: typing of call at test2.py (14)


File "test2.py", line 14:
    def __init__(self, value):
        <source elided>
        self.value = value
        self.array = np.zeros(value, dtype=np.bool)
        ^

[1] During: resolving callee type: jitclass.Bag#7fa2103159e8<value:int32,array:array(bool, 1d, A)>
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: jitclass.Bag#7fa2103159e8<value:int32,array:array(bool, 1d, A)>
[4] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**However:** this seems to work:

    import numpy as np
    import numba

    @numba.jit()
    def test():
        return np.zeros(10, dtype=np.bool)

    if __name__ == '__main__':
        print(test())

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue here is because `np.bool != np.bool_`, the former is an alias to Python `bool` the latter is the NumPy boolean `dtype`. The Numba implementation for `np.zeros` (and in fact all the array constructors) take NumPy `dtype`s. Changing your code to:
```python
import numpy as np
from numba import jitclass          # import the decorator
from numba import int32, float32, bool_    # import the types

spec = [
    ('value', int32),               # a simple scalar field
    ('array', bool_[:]),          # an array field
]

@jitclass(spec)
class Bag(object):
    def __init__(self, value):
        self.value = value
        self.array = np.zeros(value, dtype=np.bool_) # <--- USE THE DTYPE BOOL

    @property
    def size(self):
        return self.array.size

    def increment(self, val):
        for i in range(self.size):
            self.array[i] = val
        return self.array


if __name__ == '__main__':
    p = Bag(100)
    p.increment(1)
    print(p.size)
```
makes it work.

There's an open ticket about making the array constructors accept Python types, if I can find it I'll link it here.

**Comment by stuartarchibald** [comment]
NOTE: title change to reflect issue.

**Comment by rjzak** [comment]
Thank you, I didn't realise there was a difference.

**Comment by stuartarchibald** [comment]
@rjzak no problem, it appears quite regularly on the issue tracker, we should probably just fix the issue!

**Comment by rjzak** [comment]
Or maybe add it to some examples.

**Comment by verbose-void** [comment]
why tf would they remove `np.bool`. that's a tensorflow-level flop.
