### ISSUE TITLE
warning: ignoring debug info with an invalid version (0) in <string> with strange behaviour

### ISSUE THREAD

**Issue by haimivan** [numba/numba#5093]
Hi,

I am using the following versions:
    llvmlite.__version__: 0.31.0
    numba.__version__: 0.47.0

I observe the following behaviour:

setting 
`# @nb.jit(debug=True)` in all my methods in comments does not lead to an error. The code executes without problems.

When this directive is active, I can observe the following:
the following message appears 64 times before my numba optimized code is entered:
     `warning: ignoring debug info with an invalid version (0) in <string>`

Afterwards, my numba optimized code gets executed and somewhere(?) in my code an error happens, which shows itself as:

    IndexError: getitem out of range

No extra information is shown.

Is there anything I can do to get more informations about the exact position of the error? (and it strikes me a little bit that without `numba` no error appears and the code gets executed without problems).

Unfortunately, it is not possible to post my code here.

Thanks in advance!

**Comment by haimivan** [comment]
Hi,

I found a workaround (and opened https://github.com/numba/numba/issues/5094 ):

1. I set  `@nb.jit(boundscheck=True, debug=True, forceobj=True)` for my numba dependant functions. I get the error described in https://github.com/numba/numba/issues/5094 . To solve this error,

2. I replaced:
a)
```
def printing4Numba(runner, datetimeInt, par0, par1, par2, par3, par4):
    with nb.objmode():
        print('%8s' % runner, datetime.datetime.utcfromtimestamp(datetimeInt), par0, par1, par2, par3, par4)
        1 + 1
```
with:
b)
```
@nb.jit(boundscheck=True, debug=True, forceobj=True)
def printing4Numba(runner, datetimeInt, par0, par1, par2, par3, par4):
    1+1
```

Remark: a) gets called from my main Numba function several times. 
Changing the code removes the error described in https://github.com/numba/numba/issues/5094 .

3. I added (an usually superfluous) initialisation of dTC at the beginning of this code excerpt:
c) 

```
for runner2 in range(myShape):
    dTTC = lRPCA[runner2, lRPCLC['my_date']]
    dTC = int(dTTC / AMOUNT_OF_SECONDS_PER_DAY) * AMOUNT_OF_SECONDS_PER_DAY

    dTNC = lRPCA[runner2 + 1, lRPCLC['my_date']]
    dayNextCandle = int(dTNC / AMOUNT_OF_SECONDS_PER_DAY) * AMOUNT_OF_SECONDS_PER_DAY

    if dTC < dayNextCandle:
        lRPDList.append([dTC, lRPD])

        lRPD = 0.0
    else:
        lRPD += lRPCA[runner2, lRPCLC['lRPC']]
# append the last (not completed) day
if myShape > 0:
    lRPDList.append([dTC, lRPD])
else:
    1+1
```
so that it looks like this:

d)
```
dTC = -1
for runner2 in range(myShape):
    dTTC = lRPCA[runner2, lRPCLC['my_date']]
    dTC = int(dTTC / AMOUNT_OF_SECONDS_PER_DAY) * AMOUNT_OF_SECONDS_PER_DAY

    dTNC = lRPCA[runner2 + 1, lRPCLC['my_date']]
    dayNextCandle = int(dTNC / AMOUNT_OF_SECONDS_PER_DAY) * AMOUNT_OF_SECONDS_PER_DAY

    if dTC < dayNextCandle:
        lRPDList.append([dTC, lRPD])

        lRPD = 0.0
    else:
        lRPD += lRPCA[runner2, lRPCLC['lRPC']]
# append the last (not completed) day
if myShape > 0:
    lRPDList.append([dTC, lRPD])
else:
    1+1
```

Now the error described in this bug disappears.

**Comment by stuartarchibald** [comment]
Thanks for the update. If you set `NUMBA_FULL_TRACEBACKS=1` then some information about where the out of bounds accessed occurred, there's some info in the docs here http://numba.pydata.org/numba-doc/latest/reference/envvars.html#envvar-NUMBA_BOUNDSCHECK

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
