### ISSUE TITLE
Imprecise result when raising complex128 to power of complex128

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5107]
On numba 0.48dev0 raising one `complex128` to the power of another `complex128` returns a result that is very close but not identical to numpy:

```python
In [1]: import numpy as np

In [2]: a = np.complex128(2+2j)

In [3]: b = np.complex128(2+3j)

In [4]: from numba import njit

In [5]: @njit
   ...: def test_numba(a, b):
   ...:     return a ** b
   ...:

In [6]: a ** b
Out[6]: (-0.01700619604873402-0.758051063351431j)

In [7]: test_numba(a, b)
Out[7]: (-0.017006196048733355-0.7580510633514314j)

In [8]: c = a ** b

In [9]: @njit
   ...: def test_numba(a, b):
   ...:     return (a ** b) == c
   ...:

In [10]: test_numba(a, b)
Out[10]: False
```

Not sure whether numpy or numba is imprecise here.

**Comment by esc** [comment]
@ARF1 thanks for submitting this, I will label it as 'needtriage' for now.

**Comment by stuartarchibald** [comment]
The deviation appears near the 15th place, complex 128 is 2 x float64, which have 53 bit mantissa, maximum precise digits: `log10(2**53) = 15.954589770191003`, i.e. 15.
```
-0.0170061960487340
-0.0170061960487333
```
probably just some floating point wobble due to slight algorithmic difference.

**Comment by seibert** [comment]
Yeah, variation on this scale for special math functions (like non-integer exponentiation) can even be seen between different versions of glibc, so we tend not to worry about it.  I'm a little curious what the algorithm difference is, but this sounds like a rounding difference somewhere.

**Comment by stuartarchibald** [comment]
Think it's this in NumPy https://github.com/numpy/numpy/blob/maintenance/1.18.x/numpy/core/src/npymath/npy_math_complex.c.src#L439-L524 i.e. will likely `cpow` from `libm`. Numba does this https://github.com/numba/numba/blob/40fb2d06859a782db9463ac6d7eae8405eb6a81d/numba/targets/numbers.py#L976-L1015
then calls `_Py_c_pow` here: https://github.com/numba/numba/blob/40fb2d06859a782db9463ac6d7eae8405eb6a81d/numba/_helperlib.c#L115-L124

I can't replicate locally (get the same across various Python and NumPy (Anaconda and conda-forge)), e.g.:
```pycon
In [2]: import numpy as np                                                                                                      

In [3]:  a = np.complex128(2+2j)                                                                                                

In [4]: b = np.complex128(2+3j)                                                                                                 

In [5]: a ** b                                                                                                                  
Out[5]: (-0.017006196048733355-0.7580510633514314j)

In [6]: from numba import njit                                                                                                  

In [7]: @njit 
   ...: def foo(a, b): 
   ...:     return a ** b 
   ...:                                                                                                                         

In [8]: foo(a, b)                                                                                                               
Out[8]: (-0.017006196048733355-0.7580510633514314j)
```

**Comment by ARF1** [comment]
Thanks for the explanations. I'm ok if you close this.

Might it be a good idea to make a note in the docs somewhere that minor differences can occur? Not that it will make a difference to any(?) users but to save you from having to answer this question again in the future.

**Comment by seibert** [comment]
yeah, this is our section on it: https://numba.pydata.org/numba-doc/dev/reference/fpsemantics.html
