### ISSUE TITLE
modifying numpy in the paralel loop

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#5108]
Hi,
@stuartarchibald 
in my paralell loop : 
```python

def x_2(compare_desc,  p_descs, ):
    result_np = np.full((10000,4),19.11)

    res_count= 0
    count = 0
    total = p_descs.shape[0]

    for x in prange(total):
       
        if float(...) < 16 :
                a_float = dist
                name_number = x
                an_int = x
                small_float = sim
                # new_np = np.asarray([types.float32(res_count), types.float32(a_float), types.float32(an_int), types.float32(small_float)])
                # result_np[0:] = [3,3,3,3]
                result_np[res_count, 0] = x
                result_np[res_count, 1] =  a_float
                result_np[res_count, 2]=  x
                result_np[res_count, 3]= small_float
                res_count = res_count +1
      return result_np , res_count

```

it is running in parallel and I am wondering the result_np array. is it inserted sequentially or threads inserts starting from a point ? if I get the slice from the beginning to res_count am I getting all inserted data ?

**Comment by esc** [comment]
@MyraBaba thanks for submitting this, I have edited your submission to include some syntax highlighting for Python.

**Comment by stuartarchibald** [comment]
@MyraBaba I don't think `prange` can make any guarantee about insertion order, and I don't think the algorithm above is safe as the writes to `rec_count` are not atomic (there's no API to do this yet). If you want to store the results into `results_np` then do so using the `x` variable as the index.

**Comment by MyraBaba** [comment]
@stuartarchibald 
Is there any elegant way to send numpy array to the numba parallel and receive another numpy array without guessing the size of returning numpy array ?

**Comment by MyraBaba** [comment]
@stuartarchibald 
using the x varibable solves the problem if the numpy array below the 10Million. I am creating 10M numpy array in the numba function so every time I need to sort returning numpy array to get top 20 .

it is very ineffective approach. how we can make an atomic variable to use for this purposes ?

**Comment by stuartarchibald** [comment]
> it is very ineffective approach. how we can make an atomic variable to use for this purposes ?

I'd suggest opening a feature request for atomic operations.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by MyraBaba** [comment]
@stuartarchibald 
Hi 
Is there any improvement about this parallel process with list append in it ?

**Comment by stuartarchibald** [comment]
@MyraBaba no changes have been made for this I'm afraid.

**Comment by MyraBaba** [comment]
@stuartarchibald 

I would  like to learn your opinion about above code  which is matrix calculation over all arrays and decide the result is greater than threshold.

Numba give good speedup.

How can I use GPU for above code ? Do you think it makes a speeding up the overall function?

**Comment by MyraBaba** [comment]
@stuartarchibald 

As an idea : 

Is that possible each thread create and append its own container list  after parallell is finished they accumulate and return ?

Dumb idea but could be a shortcut ?
