### ISSUE TITLE
Numba nested function won't execute (version 0.47)

### ISSUE THREAD

**Issue by 6Hhcy** [numba/numba#5109]
I'm confused as to why this doesn't work, the docs say:

*2.6.1.2.3. Inner function and closure:
 Numba now supports inner functions as long as they are non-recursive and only called locally, but not passed as argument or returned as result. The use of closure variables (variables defined in outer scopes) within an 
inner function is also supported.*

 
```
    import numba


    @numba.jit(nopython=True, debug=False, parallel=False, cache=True)
    def outer() -> int:

        @numba.jit(nopython=True, debug=False, parallel=False, cache=True)
        def inner() -> int:
            return 1

        return inner()

    outer()
```

And the error:

```
Failed in nopython mode pipeline (step: analyzing bytecode)
op_MAKE_FUNCTION with annotations is not implemented
```

Am I doing something silly here?

(os: Ubuntu 19.10)
```

**Comment by esc** [comment]
@6Hhcy thanks for asking about this. There are two issues with the snippet that you submitted,the first one is that type annotations aren't yet supported and the second is that the `@jit`decorator won't work in functions that have already been annotated with `@jit`. Something along the lines of the following will though:

```
import numba


@numba.jit(nopython=True, debug=False, parallel=False, cache=True)
def outer() -> int:

    def inner():
        return 1

    return inner()

outer()
```

Hope that helps?

**Comment by 6Hhcy** [comment]
thank you very much.

**Comment by esc** [comment]
@6Hhcy thanks for following up and closing.
