### ISSUE TITLE
ord builtin not supported

### ISSUE THREAD

**Issue by TomGoBravo** [numba/numba#5116]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I'm expecting the simple builtin function `ord` to be supported in nopython mode. Instead I get the error `Untyped global name 'ord': cannot determine Numba type of <class 'builtin_function_or_method'>`.

For a running example see https://repl.it/@TomGoBravo/numba-ord

**Comment by stuartarchibald** [comment]
Thanks for the report. This isn't a bug as it's not declared as supported  http://numba.pydata.org/numba-doc/latest/reference/pysupported.html  :) , however I agree it really should be. #5117 implements `ord` and `chr`.
