### ISSUE TITLE
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by zz273** [numba/numba#5120]
I am having a problem using `@jit(nopython = True)`. I guess the reason is the package named "Tasmanian", which is used to apply the adaptive sparse grid method:

```
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'TasmanianSparseGrid' of type Module
(<module 'TasmanianSG' from '/Users/xxxxxxxx/TasmanianSG.py'>)

File "interpolation.py", line 41:
def sparse_grid(ygrid, def_y, Py):
    <source elided>
    for iy in range(ny):
        Vc_list.append(TasmanianSG.TasmanianSparseGrid())
        ^

[1] During: typing of get attribute at /Users/yyyyyyyyyy/interpolation.py (41)

File "interpolation.py", line 41:
def sparse_grid(ygrid, def_y, Py):
    <source elided>
    for iy in range(ny):
        Vc_list.append(TasmanianSG.TasmanianSparseGrid())
        ^
```

I check TasmanianSG.py, the class TasmanianSG.TasmanianSparseGrid() does not have the attribute of type. 

I do want to use `@jit(nopython = True)` to speed up my code. I appreciate any advice to solve this problem. Thanks!

**Comment by sklam** [comment]
The `@jit(nopython=True)` can only compile code that is also decorated with `@jit(nopython=True)` or there is a known replacement inside Numba. 

Please see http://numba.pydata.org/numba-doc/latest/user/5minguide.html#will-numba-work-for-my-code for a quick description of what Numba support.

**Comment by ywang273** [comment]
Hi Siu, 

Thank you for your quick reply. Now I understand how the system works.

Unless I can make sure that  "Tasmanian" is also decorated with `@jit(nopython=True)`, I should consider other methods to speed up.

Thanks again!
