### ISSUE TITLE
Issue with NUMBA 

### ISSUE THREAD

**Issue by fenil0619** [numba/numba#5121]
I have get this code from 
### **https://github.com/arthurflor23/handwritten-text-recognition**
and follow the instructed steps.

I have three folder in my IAM folder
     |--- ascii
     |--- largeWriterIndependentTextLineRecognitionTask
     |--- lines

But in this process, I got stuck at transforming into the HDF5 files.

THIS IS MY ERROR:

![image](https://user-images.githubusercontent.com/44478779/72874611-6f0f3b00-3d18-11ea-9df8-d2659567b5f1.png)

![image](https://user-images.githubusercontent.com/44478779/72874650-85b59200-3d18-11ea-914f-335eef73ccfb.png)

![image](https://user-images.githubusercontent.com/44478779/72874675-9239ea80-3d18-11ea-85f3-bfea2956a3a2.png)

Please Help ASAP...!!!

**Comment by esc** [comment]
@fenil0619 thanks for asking about this on the Numba issue tracker. In order to diagnose this further please list the exact commands that you used to setup the folders, download the software and so on. We will need this information in order to reproduce the error you are seeing. Thanks!

**Comment by esc** [comment]
@fenil0619 also, screenshots are a suboptimal way of posting error logs, since we are unable to copy and paste any test from them. GitHub supports using markdown to format code and errors, and  also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by esc** [comment]
@fenil0619 we haven't received an answer yet, so I am assuming this issue has been resolved. Please feel free to re-open with the required information if need be.
