### ISSUE TITLE
Key Error in numba annotations when caching is turned on

### ISSUE THREAD

**Issue by CookieChief** [numba/numba#5129]
Hi, I am running into an error when turning on caching:

I am using  Windows 10 with Python 3.7.6 and Numba 0.47.0. I get the following error message when I set chache=True and no error otherwise. I attached an example that reproduces the error for me.
[scratch_5.zip](https://github.com/numba/numba/files/4102396/scratch_5.zip)

> Traceback (most recent call last):
>   File "C: ... /.PyCharm2019.3/config/scratches/scratch_5.py", line 55, in <module>
>     countsort_indexer(groups,max_ngroups)
>   File "C: ... \venv\lib\site-packages\numba\dispatcher.py", line 420, in _compile_for_args
>     raise e
>   File "C: ... \venv\lib\site-packages\numba\dispatcher.py", line 353, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "C: ... \venv\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\ ... venv\lib\site-packages\numba\dispatcher.py", line 774, in compile
>     self._cache.save_overload(sig, cres)
>   File "C: ... \venv\lib\site-packages\numba\caching.py", line 665, in save_overload
>     self._save_overload(sig, data)
>   File "C: ... \venv\lib\site-packages\numba\caching.py", line 674, in _save_overload
>     data = self._impl.reduce(data)
>   File "C: ... \venv\lib\site-packages\numba\caching.py", line 400, in reduce
>     return cres._reduce()
>   File "C: ... \venv\lib\site-packages\numba\compiler.py", line 106, in _reduce
>     typeann = str(self.type_annotation)
>   File "C: ... \venv\lib\site-packages\numba\annotations\type_annotations.py", line 274, in __str__
>     return self.annotate()
>   File "C: ... \venv\lib\site-packages\numba\annotations\type_annotations.py", line 118, in annotate
>     groupedinst = self.prepare_annotations()
>   File "C: ... \venv\lib\site-packages\numba\annotations\type_annotations.py", line 95, in prepare_annotations
>     atype = self.calltypes[inst.value]
> KeyError: call assert.427(msg.426, counts__arr_size0.421, _24binary__add_9, func=assert.427, args=[Var(msg.426, scratch_5.py:33), Var(counts__arr_size0.421, <string>:2), Var(_24binary__add_9, <string>:2)], kws={}, vararg=None)

**Comment by stuartarchibald** [comment]
Thanks for the report. The code in the zip file is here:
```python
import numpy as np
from numba import njit, prange


@njit(cache=True, parallel=True, nogil=True)
def countsort_indexer(index, max_ngroups):
    """
    compute a 1-d indexer that is an ordering of the passed index,
    ordered by the groups.

    max_ngroups: the maximal number of groups to be expected.
    running time of this alg is O(len(index)+max_ngroups)
    thus choose max_ngroups close to n_groups. Note however that group label in index must be between 0 and max_ngroups
    """
    print('Counting')
    nthreads = 10
    p_counts = np.zeros((nthreads, max_ngroups + 1), dtype=np.int64)
    counts = np.zeros(max_ngroups + 1, dtype=np.int64)
    n = len(index)
    result = np.zeros(n, dtype=np.int64)
    where = np.zeros(max_ngroups + 1, dtype=np.int64)

    # count group sizes, location 0 for NA
    length = len(index) / 10
    slice = [int(np.floor(j * length)) for j in range(nthreads)]
    slice.append(len(index))

    for j in prange(nthreads):
        for i in range(slice[j], slice[j + 1]):
            p_counts[j, index[i] + 1] += 1

    for j in prange(nthreads):
        counts += p_counts[j]

    print('Marking starts')
    # mark the start of each contiguous group of like-indexed data
    for i in range(1, max_ngroups + 1):
        where[i] = where[i - 1] + counts[i - 1]

    print('Compute indexer')
    # this is our indexer
    for i in range(n):
        label = index[i] + 1
        result[where[label]] = i
        where[label] += 1

    return result, counts


if __name__ == "__main__":
    groups = np.array([2, 2, 2, 2, 2, 1, 1, 1, 1, 1], dtype=np.uint32)

    max_ngroups = 2

    countsort_indexer(groups,max_ngroups)

```

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
This issue reproduces directly from the above code.

**Comment by stuartarchibald** [comment]
This does not reproduce on mainline at ~0.55. Closing. There's also an index error in the MWR.
```
    p_counts[j, index[i] + 1] += 1
IndexError: index 3 is out of bounds for axis 1 with size 3
```
