### ISSUE TITLE
Issues with `operator.is(int, int)`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5133]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import njit
@njit
def ident(x):
    print(x is 0)
    print(x == 0)

print("numba".center(80, '-'))
ident(0)
ident(1)

print("python".center(80, '-'))
ident.py_func(0)
ident.py_func(1)
```
gives:
```
-------------------------------------numba--------------------------------------
False
True
False
False
-------------------------------------python-------------------------------------
True
True
False
False
```

**Comment by gmarkall** [comment]
Is this an actual bug? Although the CPython interpreter happens to intern the integers 0 to 256, I'm not sure its behaviour that ought to be relied on. E.g. in CPython 3.7.5:

```python
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: def ident(x): 
   ...:     print(x is 257) 
   ...:     print(x == 257)                                                                                                                                                                                                                                                                                                           

In [2]: ident(257)                                                                                                                                                                                                                                                                                                           
False
True

In [3]: def ident(x): 
   ...:     print(x is 256) 
   ...:     print(x == 256)                                                                                                                                                                                                                                                                                                              

In [4]: ident(256)                                                                                                                                                                                                                                                                                                                    
True
True
```

**Comment by gmarkall** [comment]
Clarification - it's -5 to 256: https://docs.python.org/3.8/c-api/long.html#c.PyLong_FromLong

**Comment by seibert** [comment]
Beyond `None`, I'm not sure what other values in Python are guaranteed to be singletons...

**Comment by stuartarchibald** [comment]
Seems like it's in the CPython API as a declared behaviour for all Numba's supported version of Python. The question I suppose is, do we want to replicate it?

**Comment by gmarkall** [comment]
I'd lean towards not worrying about replicating it - it looks like an instance of using `is` for equality (as does the original sample from which it was derived on gitter)... I was under the impression that this is not a good pattern.

**Comment by dhirschfeld** [comment]
The interning of integers is an implementation detail so I'm fine with numba not replicating CPython behaviour here - if code is using `is` to check for equality that's a bug in the code IMHO.

AFAIK only `None`, `True` and `False` are singletons and hence able to be compared with `is`.

**Comment by stuartarchibald** [comment]
Thanks for the thoughts everyone, seems like the consensus is to not worry about it :) Use of such a pattern is probably by accident rather than design, users can make such a trivial alteration to their code. Closing!
