### ISSUE TITLE
Support for dictionary comprehensions.

### ISSUE THREAD

**Issue by phyukhaing7** [numba/numba#5135]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/Research/code/Python/code/main.py", line 111, in <module>
    main()
  File "D:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "D:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "D:\Anaconda3\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in object mode pipeline (step: inline calls to locally defined closures)
Use of unsupported opcode (MAP_ADD) found

File "main.py", line 81:
```
def main():
    <source elided>
    random.shuffle(ids_train)
    X2train_shuffled = {_id: X2train[_id] for _id in ids_train}
    ^

```

**Comment by esc** [comment]
@phyukhaing7 thannks for asking about this on the Numba issue tracker. This type of dictionary comprehension (not 100% about the name) isn't supported by Numba at this time. A minimal reproducer follows:


```python
from numba import njit


@njit
def foo():
    return {i: i for i in range(10)}


print(foo.py_func())
print(foo())
```

**Comment by stuartarchibald** [comment]
The issue to here to fix first is to make the closure inliner give a better error message... then to work on implementing this.

**Comment by gioxc88** [comment]
any update on this?
it seems like a basic feature.

Many thanks

**Comment by stuartarchibald** [comment]
> any update on this?
> it seems like a basic feature.
> 
> Many thanks

@gioxc88 https://github.com/numba/numba/pull/6736 implements.
