### ISSUE TITLE
Support per-thread default streams in CUDA

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#5137]
Following the merge of https://github.com/numba/numba/pull/5136, it might be useful to have support for the per-thread default-stream option (reference: https://devblogs.nvidia.com/gpu-pro-tip-cuda-7-streams-simplify-concurrency/)

I think this wouldn't be a large effort to implement - opening this issue to note that it could be implemented and to gauge interest.

Are there any use cases this would unblock for anyone?

**Comment by leofang** [comment]
This is interesting. I checked the documentation and saw [this](https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html#stream-sync-behavior):
> The per-thread default stream is not a non-blocking stream and will synchronize with the legacy default stream if both are used in a program.

So I suppose the interplay between two libraries built with different `--default-stream` options, say CuPy (on `legacy`) and Numba (on `per-thread` with this proposal), is safe? Am I right that there will be a synchronization before a CuPy array on the `legacy` default stream being passed to a Numba kernel on the `per-thread` default stream?

**Comment by gmarkall** [comment]
> So I suppose the interplay between two libraries built with different `--default-stream` options, say CuPy (on `legacy`) and Numba (on `per-thread` with this proposal), is safe? Am I right that there will be a synchronization before a CuPy array on the `legacy` default stream being passed to a Numba kernel on the `per-thread` default stream?

When you say "a CuPy array on the `legacy` default stream", are you referring to a scenario like:

1. A `cuMemcpy<something>Async` with the array as the destination on the legacy default stream, then
2. The array immediately being passed to a kernel launched on a per-thread default stream?

If so, my understanding is that the interplay between them would be safe (though I would specifically be testing this scenario as part of implementing per-thread default stream support in Numba).

If I've misunderstood - could you explain a little more about the scenario you're thinking of please?

**Comment by leofang** [comment]
Yes, this is more or less what I had in mind, except that in CuPy a GPU array typically does not need memcpy to initialize, so it can be as simple as
```python
import cupy as cp
from numba import cuda

@cuda.jit
def some_func(x):
   # ...

a = cp.arange(0, 100).astype(cp.float64) # <- lives on "legacy" default stream
some_func[(1,), (100,)](a)               # <- may live on "per-thread" default stream
```
In this case, CuPy internally launches a ufunc kernel to initialize the array.

On the testing:
> though I would specifically be testing this scenario as part of implementing per-thread default stream support in Numba

It'd be nice to do this, but I am not sure how you could test a sync indeed happens as expected. If we just look at the output, even if there's no synchronization between the two kinds of default streams, the output could still be (non-deterministically) correct.

**Comment by sklam** [comment]
I was thinking about per-thread streams when I reviewed #5136, too. I have also been reviewing and experimenting with the legacy stream's implicit sync behavior.

I think the example from @leofang is safe:

```python
a = cp.arange(0, 100).astype(cp.float64) # <- lives on "legacy" default stream
some_func[(1,), (100,)](a)               # <- may live on "per-thread" default stream
```

because the legacy stream is implicitly synchronizing. The CUDA programming guide (at https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#default-stream)  says:

> Two commands from different streams cannot run concurrently if any one of the following operations is issued in-between them by the host thread:
> ...
> * any CUDA command to the NULL stream,

(The NULL stream is the legacy stream).

With that, we know that the per-thread default stream must run after any command to the legacy stream.

This article (https://devblogs.nvidia.com/gpu-pro-tip-cuda-7-streams-simplify-concurrency/) also says "Note that cudaStreamLegacy still synchronizes implicitly with the per-thread default streams if you happen to mix them in a program."

These lead me to believe that mixing the legacy and per-thread streams are safe.

**Comment by gmarkall** [comment]
Thanks for the discussions @sklam / @leofang - it seems like it should be safe. As an additional point of safety, I think that the per-thread default stream should be off by default, so that the default stream semantics are unchanged after adding the implementation. I'd imagine a config variable so that something like:

```
NUMBA_DEFAULT_STREAM="per-thread" python prog.py
```

or 

```python
numba.config.DEFAULT_STREAM="per-thread" # "legacy" being the default
```

would be used to enable it.


> It'd be nice to do this, but I am not sure how you could test a sync indeed happens as expected. If we just look at the output, even if there's no synchronization between the two kinds of default streams, the output could still be (non-deterministically) correct.

I'm not sure I could write an automated test for this - I'm imagining writing a small example that I'd be carefully checking runs of by hand under various circumstances (with some attempt to make the test prone to failure if the synchronisation doesn't happen / happens at the wrong point). Perhaps something could be done with events on the streams to check the order of things happening could be used, but I'd need to think a bit harder about it to come to a definite conclusion.

**Comment by gmarkall** [comment]
Quick note: the implementation would need (when PTDS is enabled) to use the appropriate driver API functions: those suffixed with `_ptds` (or `_ptsz` in some cases) instead of the variants with the `_v2` suffix (or no suffix, if there was no `_v2`-suffixed version).

**Comment by gmarkall** [comment]
A quick starter patch:

```diff
diff --git a/numba/cuda/cudadrv/driver.py b/numba/cuda/cudadrv/driver.py
index 77e4c5eae..a2bdb5789 100644
--- a/numba/cuda/cudadrv/driver.py
+++ b/numba/cuda/cudadrv/driver.py
@@ -309,17 +309,15 @@ class Driver(object):
         return functools.wraps(libfn)(wrapper)
 
     def _find_api(self, fname):
-        # Try version 2
-        try:
-            return getattr(self.lib, fname + "_v2")
-        except AttributeError:
-            pass
-
-        # Try regular
-        try:
-            return getattr(self.lib, fname)
-        except AttributeError:
-            pass
+        variants = ('_v2_ptds', '_v2_ptsz', '_ptds', '_ptsz', '_v2', '')
+        for variant in variants:
+            try:
+                full_name = f'{fname}{variant}'
+                api = getattr(self.lib, full_name)
+                print(f"\nUsing {full_name}\n")
+                return api
+            except AttributeError:
+                pass
 
         # Not found.
         # Delay missing function error to use
```

passes all tests:

```
$ python -m numba.runtests numba.cuda.tests

...

Ran 1140 tests in 87.612s

OK (skipped=10, expected failures=1)
```

A summary of the functions it reports can be produced:

```bash
grep "^Using" test_output.txt | sort | uniq | awk '{print $2}'
```

which gives:

```
cuCtxCreate_v2
cuCtxDestroy_v2
cuCtxGetCurrent
cuCtxGetDevice
cuCtxPopCurrent_v2
cuCtxPushCurrent_v2
cuCtxSynchronize
cuDeviceCanAccessPeer
cuDeviceComputeCapability
cuDeviceGet
cuDeviceGetAttribute
cuDeviceGetCount
cuDeviceGetName
cuDeviceGetUuid
cuDevicePrimaryCtxRelease_v2
cuDevicePrimaryCtxReset_v2
cuDevicePrimaryCtxRetain
cuEventCreate
cuEventDestroy_v2
cuEventElapsedTime
cuEventRecord_ptsz
cuEventSynchronize
cuFuncGetAttribute
cuInit
cuIpcCloseMemHandle
cuIpcGetMemHandle
cuIpcOpenMemHandle_v2
cuLaunchCooperativeKernel_ptsz
cuLaunchKernel_ptsz
cuLinkAddData_v2
cuLinkAddFile_v2
cuLinkComplete
cuLinkCreate_v2
cuLinkDestroy
cuMemAllocManaged
cuMemAlloc_v2
cuMemcpyDtoD_v2_ptds
cuMemcpyDtoHAsync_v2_ptsz
cuMemcpyDtoH_v2_ptds
cuMemcpyHtoDAsync_v2_ptsz
cuMemcpyHtoD_v2_ptds
cuMemFreeHost
cuMemFree_v2
cuMemGetAddressRange_v2
cuMemGetInfo_v2
cuMemHostAlloc
cuMemHostGetDevicePointer_v2
cuMemHostRegister_v2
cuMemHostUnregister
cuMemsetD8_v2_ptds
cuModuleGetFunction
cuModuleGetGlobal_v2
cuModuleLoadDataEx
cuModuleUnload
cuOccupancyMaxActiveBlocksPerMultiprocessor
cuOccupancyMaxPotentialBlockSize
cuPointerGetAttribute
cuProfilerStart
cuProfilerStop
cuStreamAddCallback_ptsz
cuStreamCreate
cuStreamDestroy_v2
cuStreamSynchronize_ptsz
cuStreamWaitEvent_ptsz
```

To finish the patch, we need:

- Validation that all the correct API functions are chosen - the above list of functions can be correlated with those defined using the `__CUDA_API_PTDS` and `__CUDA_API_PTSZ` macros in `cuda.h`.
- A config option for PTDS. On by default probably makes sense, assuming other CUDA Python libraries such as CuPy also have it on by default.
- Addition of some tests of PTDS behaviour.
- Tidying up the implementation of `_find_api` a little.

**Comment by gmarkall** [comment]
Adding this to the 0.54RC milestone as it seems that it could plausibly be implemented for the next release.

**Comment by gmarkall** [comment]
> Validation that all the correct API functions are chosen - the above list of functions can be correlated with those defined using the __CUDA_API_PTDS and __CUDA_API_PTSZ macros in cuda.h.

I've manually verified that the above implementation picks up all the correct APIs.

**Comment by insertinterestingnamehere** [comment]
This is amazing! Thank you!

**Comment by gmarkall** [comment]
@insertinterestingnamehere Would you like to take #6396 for a test drive and see if it works / helps with your use case?

**Comment by jakirkham** [comment]
cc @charlesbluca @pentschev @quasiben

**Comment by insertinterestingnamehere** [comment]
Will do! Also cc'ing @hfingler and @dialecticDolt.
