### ISSUE TITLE
Switch Azure CI windows config to use VS2017 images

### ISSUE THREAD

**Issue by seibert** [numba/numba#5140]
Azure will be retiring the `vs2015-win2012r2` on March 23, 2020.  We are encouraged to upgrade to `vs2017-win2016` before then.  Some cursory investigation of the ABI compatibility question suggests that it should be fine, but we'll need to give it a try.

**Comment by stuartarchibald** [comment]
Seems to be done https://github.com/numba/numba/blob/master/azure-pipelines.yml#L105 closing.
