### ISSUE TITLE
Adding `MemoryPointer` to public API

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#5163]
## Feature request

The `MemoryPointer` class is very useful. However IIUC this is technically part of the private API. It would be useful to have it in the public API (namely documented and easily accessible from `numba.cuda`).

**Comment by gmarkall** [comment]
For reference / info, NBEP 7 adds it to the public API: https://github.com/gmarkall/nbep-7#device-memory

**Comment by esc** [comment]
@jakirkham @gmarkall I would suggest to keep this open until NBEP 7 arrives?

**Comment by gmarkall** [comment]
@esc I think so, in case nbep 7 changes before it is merged (probably not likely to not expose the MemoryPointer in it, but just in case)

**Comment by esc** [comment]
@gmarkall 👍

**Comment by gmarkall** [comment]
This is resolved by #5328 which added `MemoryPointer`, `AutoFreePointer`, `PinnedMemory` and `MappedMemory` to the public API as part of NBEP 7, External Memory Management Plugins.
