### ISSUE TITLE
Syntax error installing from pip3

### ISSUE THREAD

**Issue by bbimber** [numba/numba#5166]
Hello,

We have code that installs umap-learn via pip3, which in turn installs numba, defaulting to 0.48.0.  This gives a syntax error:

      File "/tmp/pip-build-jqwz5pcy/numba/setup.py", line 305
        build_requires = [f'numpy >={min_numpy_build_version}']

do you expect this?

Full log here:

```
Collecting umap-learn
  Downloading https://files.pythonhosted.org/packages/ad/92/36bac74962b424870026cb0b42cec3d5b6f4afa37d81818475d8762f9255/umap-learn-0.3.10.tar.gz (40kB)
Collecting numpy>=1.13 (from umap-learn)
  Using cached https://files.pythonhosted.org/packages/52/e6/1715e592ef47f28f3f50065322423bb75619ed2f7c24be86380ecc93503c/numpy-1.18.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting scikit-learn>=0.16 (from umap-learn)
  Downloading https://files.pythonhosted.org/packages/a8/01/a37d1ae4191ef09adc6385ae9f9306409e93370f7e85338152b608e7d6a3/scikit_learn-0.22.1-cp35-cp35m-manylinux1_x86_64.whl (7.0MB)
Collecting scipy>=0.19 (from umap-learn)
  Downloading https://files.pythonhosted.org/packages/c1/60/8cbf00c0deb50a971e6e3a015fb32513960a92867df979870a454481817c/scipy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl (26.0MB)
Collecting numba>=0.37 (from umap-learn)
  Downloading https://files.pythonhosted.org/packages/c3/81/453926761dc00b02b22d1cd6935aaa8a736fca011d33615315bc7c132788/numba-0.48.0.tar.gz (2.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jqwz5pcy/numba/setup.py", line 305
        build_requires = [f'numpy >={min_numpy_build_version}']
                                                             ^
    SyntaxError: invalid syntax
```

Thanks,
Ben

**Comment by seibert** [comment]
Are you using python 3.5?

**Comment by bbimber** [comment]
It appears Travis ci is python 3.6. This install succeeded up until this afternoon.

**Comment by seibert** [comment]
We just posted Numba 0.48 wheels where we made some updates to `setup.py`.  I am puzzled by the SyntaxError, because f-strings are supported in Python 3.6 and later.  pip3 on travis-ci must not be using Python 3.6.

As a temporary workaround while we try to understand this, can you install Numba 0.47 before installing umap-learn?

**Comment by seibert** [comment]
Also, it seems very strange that pip is not grabbing the pre-built wheel, but is instead downloading and attempting to build from source.  Are you sure that `pip3` is installing into a Python 3.6 environment?  Can you show the output of `pip3 --version` in this environment?

**Comment by bbimber** [comment]
I noticed one thing.  It installed numba==0.47 OK.  but umap-learn has this:

 'install_requires': ['numpy >= 1.13',
                         'scikit-learn >= 0.20',
                          'scipy >= 1.0',
                         'numba >= 0.42, != 0.47',
                         'tbb >= 2019.0'],

https://github.com/lmcinnes/umap/blob/master/setup.py

so it tried to then install 0.48 anyway.  i'm trying to force numba==0.46

**Comment by esc** [comment]
@bbimber not sure if you know already, but Travis CI does have a debug console facility: 
https://docs.travis-ci.com/user/running-build-in-debug-mode/

This might help debugging, rather than making 10s of commits all labelled 'debugging Travis CI', if you know what I mean? 😉

**Comment by bbimber** [comment]
@esc  thank you.  when i started with travisci I looked for something like that but somehow missed it.  all those "debugging" commits at least get squashed, but you're spot on.  this will be quite useful.

**Comment by bbimber** [comment]
also, i think the problem is more about the travis environment than numba, so this can be closed.  thank you both for your help.

**Comment by esc** [comment]
@bbimber thanks for reporting back about this. Should it turn out, contrary to your current hypothesis, that it is indeed a Numba problem, please don't hesitate to re-open this issue or open a new one. Thanks for using Numba!
