### ISSUE TITLE
[DOC] Publishing docs on __cuda_memory__

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#5168]
## Feature request

It looks like `__cuda_memory__` is used for some things internally and is checked in a few places. There even appear to be docstrings about it within the code. However it doesn't seem to show up in the docs online. Would be good to publish these to the webpage.

**Comment by esc** [comment]
@jakirkham thanks for submitting this, I have labelled this as a feature request for CUDA accordingly.

**Comment by gmarkall** [comment]
@jakirkham Do you still see any need for this? I'm not sure I'd want to publish anything about it without good reason, as I don't think there's been much thinking through it as an external API.

**Comment by jakirkham** [comment]
I don't think so. At the time it wasn't clear if we should be using this in other libraries like RMM for better interoperability with Numba. Though I think `__cuda_array_interface__` and other Numba & RMM improvements have obviated the need here
