### ISSUE TITLE
@vectorize doesn't work with Numpy arrays (NotImplementedError)

### ISSUE THREAD

**Issue by tjorda01** [numba/numba#5175]
When I use `@vectorize` with Numpy arrays, Numba displays this error message: `NotImplementedError: array(float64, 2d, A) cannot be represented as a Numpy dtype`

I'm using Numba version 0.48.0

Here source code that reproduces the error:
``` python
import numpy as np
from numba import prange, vectorize, float64, float32
from matplotlib import pyplot as plt

@vectorize([float64[:,:](float64[:,:], float64[:,:])])
def ndvi(img_nir:np.ndarray, img_red:np.ndarray) -> np.ndarray:
    fillvalue = 0
    dims = img_nir.shape
    out_img = np.full(dims, fillvalue, dtype=img_nir.dtype)
    a = dims[0]
    b = dims[1]
    for y in range(a):
        for x in range(b):
            out_img[y,x] = (img_nir[y,x] - img_red[y,x]) / (img_nir[y,x] + img_red[y,x])
    return out_img

if __name__ == '__main__':
    tile_shape = (1024, 1024)
    array1 = np.random.default_rng().uniform(low=0.0, high=10000.0, size=tile_shape)
    array2 = np.random.default_rng().uniform(low=0.0, high=10000.0, size=tile_shape)
    print(f"  image dtype = {array1.dtype}")
    
    ndvi_array = ndvi(array1, array2)

    plt.imshow(ndvi_array, cmap='jet')
    plt.title("NDVI w/vectorize")
    plt.tight_layout()
    plt.colorbar()
    plt.show()
```
I also tried replacing `range` with `prange`, and removing type hints from the function signature but the results are the same.

Stacktrace
```
Traceback (most recent call last):
  File "C:\data\dev\git_gpa\src\examples\numba_parallel.py", line 38, in <module>
    def ndvi_njit(img_nir:np.ndarray, img_red:np.ndarray) -> np.ndarray:
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\decorators.py", line 120, in wrap
    vec.add(sig)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\dufunc.py", line 163, in add
    return self._compile_for_argtys(args, return_type)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\dufunc.py", line 213, in _compile_for_argtys
    cres, actual_sig)
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 180, in _build_element_wise_ufunc_wrapper
    dtypenums = [as_dtype(a).num for a in signature.args]
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 180, in <listcomp>
    dtypenums = [as_dtype(a).num for a in signature.args]
  File "C:\apps\Anaconda3\envs\img_proc3\lib\site-packages\numba\numpy_support.py", line 152, in as_dtype
    % (nbtype,))
NotImplementedError: array(float64, 2d, A) cannot be represented as a Numpy dtype
```

**Comment by esc** [comment]
@tjorda01 thanks for reporting this, I can reproduce locally, but this will still need some triage.

**Comment by tjorda01** [comment]
@esc  Thanks for you prompt reply and confirming that you're able to reproduce.

**Comment by esc** [comment]
@tjorda01 I have looked at this in more detail, and it seems you may not be using `@vectorize` correctly. It works on scalars and not on arrays as described here http://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-vectorize-decorator --- So, if you change the signature to `@vectorize([float64(float64, float64)])` the function will compile, but not run, as you access the array api, e.g. `shape`, within the function body.  If you want to do this on arrays, please have a look at `@guvectorize` here: http://numba.pydata.org/numba-doc/latest/user/vectorize.html#the-guvectorize-decorator which may be more along the lines of what you want. Hope that helps?

**Comment by esc** [comment]
@tjorda01 do you require any additional advice  on this one, or may I close it?

**Comment by tjorda01** [comment]
I think documentation para 1.6 should have an introduction sentence that says there are two Numpy universal functions: @vectorize and @guvectorize. 
@vectorize for scalars and @guvectorize for arrays. 

⁣Tom Jordan
USA Archery Level 3 Coach​

**Comment by esc** [comment]
@tjorda01 indeed, that would be a good idea. Pull-requests are welcome, as usual. 🙏

**Comment by stuartarchibald** [comment]
> @tjorda01 indeed, that would be a good idea. Pull-requests are welcome, as usual. pray

done in https://github.com/numba/numba/pull/5297
