### ISSUE TITLE
Add `dtype` property to `List` class

### ISSUE THREAD

**Issue by rohitsanj** [numba/numba#5233]
## Feature request

add a `dtype` property to the `List` class that forwards to the `dtype` of the contained `_list_type`

Expected functionality:
```python
>>> from numba.typed import List
>>> a = List()
>>> a.append(3)
>>> a.dtype
'int64'
```

**Comment by rohitsanj** [comment]
I've started working on this.

**Comment by esc** [comment]
@rohitsanj thanks for submitting this, I have labeled it as a feature request and have added it to the milestone for the next release.
