### ISSUE TITLE
Typed list construct from iterable.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5241]
## Feature request

This appeared on SO: https://stackoverflow.com/questions/60186698/create-a-numba-typed-list-without-looping-over-a-python-list

We've discussed this previously but I don't recall the discussion being recorded. Whilst it's necessary to iterate a Python list to pull each value out into a typed list, it may be less alarming/weird if the typed list had a constructor that did just that. e.g.

```python
from numba.typed import List
pylist = [1, 2, 3, 4]
typedlist = List(pylist)
```
CC @esc

**Comment by rohitsanj** [comment]
Since I have already taken up a couple of issues based on `List`, I would like to take this one up as well.

**Comment by esc** [comment]
@rohitsanj that would be very cool indeed. This is a long standing issue that would bring a lot of value to Numba and code-base. However, in this case it will probably warrant some discussion before starting to determine what the API should look like. I'll sketch the various ways to construct a list first so that we can decide on how to proceed.

**Comment by esc** [comment]
Here are the three ways that I can think of how to initialize a typed-list:

```
from numba import njit
from numba.typed import List, listobject
from numba import types


@njit
def foo1():
    l = listobject.new_list(types.int32)
    l.append(types.int32(1))
    return l


print(repr(foo1()))
print(repr(foo1.py_func()))


@njit
def foo2():
    l = List()
    l.append(types.int32(1))
    return l


print(repr(foo2()))
print(repr(foo2.py_func()))


@njit
def foo3():
    l = List.empty_list(types.int32(1))
    l.append(types.int32(1))
    return l


print(repr(foo2()))
print(repr(foo2.py_func()))
```

**Comment by esc** [comment]
FWIW: I have started working on this.  Implementing it in the interpreter is fairly straightforward, implementing it to work within `@njit` functions, not so much.

**Comment by esc** [comment]
PR is up: https://github.com/numba/numba/pull/5294

**Comment by esc** [comment]
Closing as #5294 was merged.
