### ISSUE TITLE
Tuple in np.array constructor fails without clear error only upon direct assignment to secondary array

### ISSUE THREAD

**Issue by Goobley** [numba/numba#5243]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have taken to always using tuples in my numpy array constructors in numba so that multi-dimensional arrays work correctly (as specified by the docs [here](https://numba.pydata.org/numba-doc/0.48.0/reference/numpysupported.html#literal-arrays)). I have some functions that are known to work under numba 0.45.1 and just fine in raw python. With 0.47 and 0.48 some of these functions mysteriously stop working. (Assume `q` is some 2D numpy array, say, `np.zeros((3,10))`)

```python
@njit
def working(q):
    lin = np.array((0.1, 0.6, 0.3))
    x = lin / q[0, 0:3]

@njit
def not_working(q):
    lin = np.array((0.1, 0.6, 0.3))
    stencil = np.zeros((3,3))
    stencil[0, 0] = q[0, 0]
```
The function `working` compiles without any problems, as will `not_working` if the definition of `lin` is removed. In the form presented above, the error is:
```
---------------------------------------------------------------------------
RedefinedError                            Traceback (most recent call last)
<ipython-input-5-44297253a00f> in <module>
----> 1 not_working(np.ones((3,10)))

/local0/scratch/cmo/miniconda3/envs/LightweaverDev/lib/python3.8/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    407             # These errors are probably from an issue with either the code supplied
    408             # being syntactically or otherwise invalid
--> 409             error_rewrite(e, 'interpreter')
    410         except errors.ConstantInferenceError as e:
    411             # this is from trying to infer something as constant when it isn't

/local0/scratch/cmo/miniconda3/envs/LightweaverDev/lib/python3.8/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

/local0/scratch/cmo/miniconda3/envs/LightweaverDev/lib/python3.8/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670 

RedefinedError: Failed in nopython mode pipeline (step: analyzing bytecode)
$const_0.1
```
Simply changing `lin` to take a list in the constructor mysteriously makes the function compile again.

```python
@njit
def also_working(q):
    lin = np.array([0.1, 0.6, 0.3])
    stencil = np.zeros((3,3))
    stencil[0, 0] = q[0, 0]
```

The multi-dimensional arrays seem to be fine constructed from tuples, as changing the definition of `lin` to `np.array(((0.1, 0.6, 0.3), ))` allows the function to compile.

Should we just be using lists in the numpy constructors for 1D arrays?

**Comment by Goobley** [comment]
I just found that changing the definition of `lin` to `np.array((1.0, 2.0, 3.0))` doesn't cause the error, but changing the first number to 0.2 changes the variable in the error message to `$const_0.2`, so something in the naming scheme for constants is presumably clashing with the numbers put into this tuple...

**Comment by stuartarchibald** [comment]
Thanks for the report. Pretty sure this is due to a bad interaction between `op_LOAD_CONST` in the interpreter and the naming scheme in there:
https://github.com/numba/numba/blob/a4413366a946459c8f0929e1556ee9ee765fc7c2/numba/core/interpreter.py#L722-L734

along with the edefinition scheme in the scope:
https://github.com/numba/numba/blob/a4413366a946459c8f0929e1556ee9ee765fc7c2/numba/core/interpreter.py#L394

The result being two consts get the same "name". SSA should resolve.
