### ISSUE TITLE
double free or corruption (!prev) Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by krishvishal** [numba/numba#5248]
## Code to reproduce the error

    import numpy as np
    from numba import jit, prange
    import itertools

    def generate_curr(size):
        curr = np.array(list(map(list, itertools.product([0., 1.], repeat = size))))
        return curr

    curr = generate_curr(16)

    @jit(nopython=True, parallel=True)
    def find_region(curr):
        region = []    
        curr_sum = np.sum(curr, axis=1)
        for i in prange(curr.shape[0]):
            if curr_sum[i] > 0 and curr_sum[i] < 5:
                region.append(curr[i])
        return reg

## Result
When I try to use the `find_region` function, I get the following error trace.

    double free or corruption (!prev)
    Aborted (core dumped)

## Environment

```
import sys
import numba
import platform
print(sys.version)
print(numba.__version__)
print(platform.platform())
```
Output:

```
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
0.48.0
Linux-4.15.0-72-generic-x86_64-with-debian-buster-sid
```
How to solve this issue?

**Comment by georgeblck** [comment]
I am experiencing the same seg-fault when simply loading numba (Version: 0.45.1 from Channel intel) on anaconda version 3.7.6 and Ubuntu 18.04

It's working when I use the most recent python (3.8.1) and a more recent version of numba (0.48.0).

If it doesn't matter to you what Python-Version you are using then switch to 3.8.1 and try it again

**Comment by georgeblck** [comment]
I am experiencing the same seg-fault simply when loading numba 0.48.0 `import numba`. WIth Anaconda 3.7.6 and Ubuntu 18.04

When I use the newest Anaconda Python 3.8.1 there are no problems.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue here is that `list.append` is not threadsafe and so is invalid for use in a `prange` driven parallel region. Suggested work around: https://github.com/numba/numba/issues/4206#issuecomment-503947050

Duplicate of https://github.com/numba/numba/issues/4206 and https://github.com/numba/numba/issues/2408.

**Comment by stuartarchibald** [comment]
Documented here https://numba.readthedocs.io/en/latest/user/parallel.html#unsupported-operations

Closing as a duplicate of #2408
