### ISSUE TITLE
Moved numba.targets causes AttributeError for pandas

### ISSUE THREAD

**Issue by TomAugspurger** [numba/numba#5256]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

In https://github.com/pandas-dev/pandas/blob/fa2aa9f54dc125e4d9a3546f99ec5bf3e1b50e4d/pandas/core/window/numba_.py#L45, pandas relies on `numba.targets` being present. I see that in  https://github.com/numba/numba/commit/044212ad90f19e9110ea86a9020f84155d1563d6 it was moved.

Is it possible to provide a shim (possibly with a warning), so that pandas 1.0.0 and 1.0.1 will continue to work with the numba engine?

cc @mroeschke, since we'll likely need to update this on the pandas side too.

**Comment by seibert** [comment]
We are definitely planning to insert compatibility shims before the release.

**Comment by seibert** [comment]
(FYI, the release is in mid-March.)

**Comment by stuartarchibald** [comment]
Shim will happen before 0.49 is cut, things are still potentially moving! :)

I'm also thinking though that it might make sense to create a better spelling for "it's a jit wrapped function" as I've been asked about 3 times recently. I think having such a spelling would be generally beneficial.

**Comment by stuartarchibald** [comment]
Talking to @TomAugspurger out of band, seems like a `numba.is_jitted()/numba.extending.is_jitted()` would be a good idea.

**Comment by stuartarchibald** [comment]
`numba.is_jitted` was implemented in https://github.com/numba/numba/pull/5308

**Comment by stuartarchibald** [comment]
Closing. 0.49.0RC has `numba.extending.is_jitted()` and also a compatibility shim to give a grace period of one Numba release (about 6-7 weeks) to patch in any changes. The `numba.targets` module will be gone permanently in Numba 0.50. CC @mroeschke @TomAugspurger
