### ISSUE TITLE
Numba documentation page does not provide different versions

### ISSUE THREAD

**Issue by dannyk0104** [numba/numba#5266]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Numba website used to have a drop down menu(When I click the version at the top of webpage) to chose different doc version. But that functionality is gone now.
Should be able to chose different versions on the website instead of typing the version I want directly on the URL.

**Comment by esc** [comment]
@dannyk0104 thanks for reporting this, I have labeled it accordingly. IIRC we recently changed the sphinx theme, so that functionality may have been lost. Maybe @asmeurer or @stuartarchibald know more.

**Comment by stuartarchibald** [comment]
From memory alone, at best I vaguely remember there being some sort of drop down button but don't recall there being anything with the feature you describe. IIRC the docs are built as a single build on the released version of Numba and then uploaded. I took a look in the wayback machine and 0.27, 0.35, 0.39, 0.43, 0.44, 0.45 all have no drop down. I also am wondering which URL you are using to access older versions?

Thanks.

**Comment by asmeurer** [comment]
Was it ever published on readthedocs? That would have provided the drop down button?

**Comment by stuartarchibald** [comment]
> Was it ever published on readthedocs? That would have provided the drop down button?

Solely from memory, I don't think so, but this is a good point, probably worth checking with @seibert.

**Comment by seibert** [comment]
I don't recall ever putting Numba's docs on readthedocs because last time we thought about it (years ago), we couldn't get the doc generation to work within the constraints of their environment.  (llvmlite didn't have such issues, which is why it has always been hosted on RTD)

I bet we could get Numba's docs to work on RTD now, which would be a nice change so we didn't have to maintain our bespoke doc automation system.

**Comment by esc** [comment]
I have marked this as a good first issue, in case anyone would like to tackle it.
