### ISSUE TITLE
Jitting changes result when adding certain kind of 0 to local variable

### ISSUE THREAD

**Issue by fuglede** [numba/numba#5273]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This issue is identical to [this StackOverflow question](https://stackoverflow.com/q/60260414/5085211) but has been included here in its entirety for reference:

Consider the following function for calculating the number of steps for a given input to the 3 *n* + 1 problem:
```
def num_steps(b, steps):
    e = b
    d = 0
    while True:
        if e == 1:
            d += steps[e]
            return d
        if e % 2 == 0:
            e //= 2
        else:
            e = 3*e + 1
        d += 1
```

Here, `steps` exists to allow for memoization of the result, but for the sake of this question, we just note that as long as `steps[1] == 0`, it should have no effect, since in that case, the effect of `d += steps[e]` is to add 0 to `d`. Indeed, the following example gives the expected result:

```
import numpy as np

steps = np.array([0, 0, 0, 0])
print(num_steps(3, steps))  # Prints 7
```

If, however, we JIT compile the method using `numba.jit` (or `njit`), we no longer get the right result:
```
import numpy as np
from numba import jit

steps = np.array([0, 0, 0, 0])
print(jit(num_steps)(3, steps))  # Prints 0
```

If we remove the seemingly-redundant `d += steps[e]` before compiling the method, we do get the right result, though. We could even put in a `print(steps[e])` prior to `d += steps[e]` and see that the value is 0. I can also move the `d += 1` to the top of the loop (and initialize `d = -1` instead) to get something that also works in the Numba case.

This happens with Numba 0.48.0 (llvmlite 0.31.0) on Python 3.8 (the most recent versions available through the standard conda channel). As noted on StackOverflow, the issue does not appear in Numba 0.46.0.

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is a duplicate of https://github.com/numba/numba/issues/5267?

**Comment by fuglede** [comment]
Certainly is; thanks.

**Comment by stuartarchibald** [comment]
Thanks for taking the time to report this from StackOverflow @fuglede. The Numba core devs to keep a track of what's tagged with `#numba` on there but sometimes things to slip through. Your diligence in reporting is appreciated!
