### ISSUE TITLE
`prange` fails to generate reproducible random sequence with printing

### ISSUE THREAD

**Issue by shizejin** [numba/numba#5290]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi. I was trying to parallelize random number generations with `prange` and hoping to have reproducible sequence by setting `numpy.random.seed`. It seems to be working fine until I found that the reproducibility cannot be held with printing.

[Here](https://nbviewer.jupyter.org/github/shizejin/Notebooks/blob/master/numba%20seed.ipynb) is a notebook that demonstrates the problem I have.

I am not sure if this is a bug or just a feature of `prange`. Any help will be highly appreciated.

**Comment by esc** [comment]
@shizejin thanks for reporting this to the Numba issue tracker. It may indeed be a genuine bug. What's interesting to note, is that the first value still remains the same, even when printing.

**Comment by esc** [comment]
@DrTodd13 could you perhaps have a look at this?

**Comment by stuartarchibald** [comment]
I'd anticipate that this has something to do with going back into the interpreter, which is necessary for performing `print`.

**Comment by DrTodd13** [comment]
Don't think it has to do with interpreter.  If you replace print with "for j in range(10000): pass", it does the same thing.  So, it is just down to timing I think.

**Comment by stuartarchibald** [comment]
@DrTodd13 think you are right:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def f3(x):

    a = np.empty(x)

    np.random.seed(0)
    acc = 0
    for i in prange(x):
        for j in range(10000 * i): # pointless delay
            acc += np.sqrt(j)
        a[i] = np.random.rand()

    print(a)

for i in range(3):
    f3(5)
```
produces:
```
[0.5488135  0.71518937 0.06410496 0.4208659  0.77193401]
[0.5488135  0.71518937 0.9494599  0.67294647 0.92017928]
[0.5488135  0.71518937 0.00565258 0.34336378 0.45166052]
```

**Comment by sklam** [comment]
From today's meeting, we think that the observed behavior here is expected. Which thread is initializing the random state with random bytes draw from `os.urandom`. No attempt is made to guarantee consistency.

Here's an modified reproducer that shows the writing threads for each output slot:

```python
from numba import njit, prange
import numpy as np
from numba.np.ufunc.parallel import _get_thread_id


@njit(parallel=True)
def f3(x):

    a = np.zeros(x)
    b = np.zeros(x, dtype=np.int32)

    np.random.seed(0)
    acc = 0
    for i in prange(x):
        for j in range(10000 * i): # pointless delay
            acc += np.sqrt(j)
        a[i] = np.random.rand()
        b[i] = _get_thread_id()

    print(a)
    print(b)

for i in range(3):
    f3(5)
```
produces:

```
[0.5488135  0.71518937 0.78093257 0.02302717 0.92944802]
[0 0 5 7 4]
[0.5488135  0.71518937 0.0289736  0.2024581  0.27636139]
[0 0 1 5 2]
[0.5488135  0.71518937 0.67160982 0.53330408 0.38477666]
[0 0 6 1 3]
```

**Comment by stuartarchibald** [comment]
Thanks for confirming @sklam, as discussed, I agree with the diagnosis.

Docs also have reference to this:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#random
> Note
> Since version 0.28.0, the generator is thread-safe and fork-safe. Each thread and each process will produce independent streams of random numbers.
