### ISSUE TITLE
inline="always" flag for @overload_attribute

### ISSUE THREAD

**Issue by dannyk0104** [numba/numba#5298]
## Feature request

Just like `@overload` and `@overload_method` can we have `inline` flag for overload_attribute?
Thanks

**Comment by stuartarchibald** [comment]
Thanks for the report. Pretty sure `@overload_attribute` has the `inline` flag, https://github.com/numba/numba/pull/4695 implemented it, should be in Numba 0.47 and later, which version do you have?

**Comment by dannyk0104** [comment]
Just confirmed that it does. 
I will close the issue.

**Comment by stuartarchibald** [comment]
Great, thanks for checking.
