### ISSUE TITLE
Call to cuInit results in UNKNOWN_CUDA_ERROR

### ISSUE THREAD

**Issue by happynear** [numba/numba#5303]
## Reporting a bug
I don't have a conda in my docker image, so I git clone this repo and did `python setup.py install`.
Numba reports this error:
Error: CUDA device intialisation problem. Message:Error at driver init:
[-1] Call to cuInit results in UNKNOWN_CUDA_ERROR:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
I have CUDA 10.1 installed.

System info:
--------------------------------------------------------------------------------
__Time Stamp__
2020-02-23 16:29:19.076283

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : broadwell
CPU count                                     : 56
CFS restrictions                              : None
CPU Features                                  :
64bit adx aes avx avx2 bmi bmi2 cmov cx16 f16c fma fsgsbase invpcid lzcnt mmx
movbe pclmul popcnt prfchw rdrnd rdseed rtm sahf sse sse2 sse3 sse4.1 sse4.2
ssse3 xsave xsaveopt

__OS Information__
Platform                                      : Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid
Release                                       : 4.4.0-142-generic
System Name                                   : Linux
Version                                       : #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019
OS specific info                              : debianstretch/sid
glibc info                                    : glibc 2.3.4

__Python Information__
Python Compiler                               : GCC 5.4.0 20160609
Python Implementation                         : CPython
Python Version                                : 3.6.8
Python Locale                                 :

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Error: CUDA device intialisation problem. Message:Error at driver init:
[-1] Call to cuInit results in UNKNOWN_CUDA_ERROR:
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : True
+--> Vendor:                                  : GNU
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
Conda not present/not working.
Error was [Errno 2] No such file or directory: 'conda': 'conda'

--------------------------------------------------------------------------------

- [ -] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. Do you have CUDA Toolkit installed in the container? CUDA support requires this and a suitable CUDA driver present on the host (and the container to have permissions etc to use it and the hardware).

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
