### ISSUE TITLE
[cuda] more accurate debuginfo

### ISSUE THREAD

**Issue by sklam** [numba/numba#5312]
Because of https://github.com/numba/numba/issues/5311, I reviewed the debuginfo generation in the cuda backend. The CUDA backend has a emit debuginfo differently from the CPU backend, due to the mismatch of LLVM version used by NVVM. For the CUDA backend, debug info is marked by an inlineasm statement (at https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/core/debuginfo.py#L276), instead of marking at everything LLVM statement. As a result, debuginfo could be missing for some Python source statements after LLVM optimization.

I think we can drop the inlineasm hack by emitting the debug into metadata as `!numba.dbg`, so that LLVM stops checking the debug metadata and skipping them due to invalid format. Right before pass it to NVVM, we can rewrite the `!numba.dbg` back into `!dbg`.  This technique is already employed for the inlineasm already, but it's currently limited to exactly the inlineasm call we are emitting (see https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/cuda/cudadrv/nvvm.py#L578-L582).

**Comment by c200chromebook** [comment]
Lemmie know if there's anything I can do to help this one, but glad it repros.

**Comment by gmarkall** [comment]
This only applies to debuginfo generation for NVVM 3.4 - NVVM 7.0 debuginfo generation uses the `DIBuilder` class shared with the CPU target, so this issue shouldn't affect it.

I don't think there's much value in going back and trying to improve the NVVM 3.4 debuginfo builder, so I'll close this issue.
