### ISSUE TITLE
Contiguity of contiguous array inconsistent (Python 2)

### ISSUE THREAD

**Issue by senselessDev** [numba/numba#5316]
I have found a problem with the contiguity of numba device arrays in Python 2. Because of the ` Python 2.7 End of Life Plan`, I don't know if that still matters. But here is an example:

``` python
import numba
import numba.cuda
import numpy

print(numba.__version__)
x = numpy.array([[12., 27, 4]])
x_cont = numpy.ascontiguousarray(x[:, :2])
print('numpy flags', x_cont.flags)
z = numba.cuda.device_array_like(x_cont)
print('numba flags', z.flags)
```

Python 2 is giving
```python
0.47.0
('numpy flags',   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False)
('numba flags', {'F_CONTIGUOUS': False, 'C_CONTIGUOUS': False})

```

while Python 3 gives
```python
0.48.0
numpy flags   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

numba flags {'F_CONTIGUOUS': False, 'C_CONTIGUOUS': True}
```

The problem is that in Python 2 I am not able to use `z` in a cuda kernel then. The usual `ValueError: Array contains non-contiguous buffer and cannot be transferred as a single memory region. Please ensure contiguous buffer with numpy .ascontiguousarray()` stuff is stopping the usage of `z`. On the contrary, Python 3 is working fine with the correctly found contiguity.

**Comment by seibert** [comment]
Yeah, we're not planning to go back and do any more releases on the last Python 2 release, so this is good to document in case someone else stumbles on this, but I don't think it will be fixed.

**Comment by stuartarchibald** [comment]
Thanks for the report. Whilst evidently a bug, I do not think it is critical and so it would not warrant a patch to the 0.47.x series. As a result, this is a "won't fix" I'm afraid, sorry.
