### ISSUE TITLE
Build failed: fatal error: omp.h: No such file or directory

### ISSUE THREAD

**Issue by openedev** [numba/numba#5324]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have added python3, python-llvmlite, python-numpy dependencies for numba-0.48.0 version. Build is failing due to missing omp.h please check this [numba_build_log](https://paste.ubuntu.com/p/9V7HKnvtfr/)

**Comment by openedev** [comment]
Look like it an openmp requirement, any flag to disable to openmp during build. I have tried --disable-openmp but no use.

**Comment by openedev** [comment]
Enabling openmp support on toolchain seems building fine, but failed to import at target.

# python --version
Python 3.8.1
# python3 -c "import llvmlite"
# pip show llvmlite
Name: llvmlite
Version: 0.31.0
Summary: lightweight wrapper around basic LLVM functionality
Home-page: http://llvmlite.pydata.org
Author: Continuum Analytics, Inc.
Author-email: numba-users@continuum.io
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: 
Required-by: numba
# python3 -c "import numpy"
# pip show numpy
Name: numpy
Version: 1.18.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: 
Required-by: scikit-learn, resampy, numba, matplotlib, librosa
# python3 -c "import numba"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/numba/__init__.py", line 48, in <module>
    import numba.charseq
  File "/usr/lib/python3.8/site-packages/numba/charseq.py", line 6, in <module>
    from numba import types, cgutils, unicode
  File "/usr/lib/python3.8/site-packages/numba/unicode.py", line 32, in <module>
    from numba.targets.hashing import _Py_hash_t
  File "/usr/lib/python3.8/site-packages/numba/targets/hashing.py", line 632, in <module>
    raise NotImplementedError("FNV hashing is not implemented")
NotImplementedError: FNV hashing is not implemented

Look like the numba/targets/hashing.py is looking for siphash24 and I enabled both siphash, csiphash and siphashc modules as well but still have the same error.

# pip show siphash
Name: siphash
Version: 0.0.1
Summary: siphash - python siphash implementation
Home-page: http://github.com/majek/pysiphash#readme
Author: Marek Majkowski
Author-email: marek@popcount.org
License: MIT
Location: /usr/lib/python3.8/site-packages
Requires: 
Required-by: 


Any comments?

**Comment by stuartarchibald** [comment]
Thanks for the report. Yes, OpenMP headers and runtime are needed on Linux at compile time, in part because at present we have no way of easily asking the question "does this system have OpenMP", this is probably something to look at. For now I'll update the docs saying that it is required.

**Comment by stuartarchibald** [comment]
RE: siphash24

Numba is looking at the CPython build to see if `siphash24` is the hashing alg in use internally in CPython. For example, Anaconda distribution CPython has the hash algorithm set as `'siphash24'`, 
```pycon
In [1]: import sys                                                                                                              

In [2]: sys.hash_info.algorithm                                                                                                 
Out[2]: 'siphash24'
```
This is because Anaconda CPython is compiled with it enabled (as signaled by this flag at compile time https://github.com/python/cpython/blob/e263bb1e97ae8f84fb4f2ab5b0c4f529a2e5696d/configure#L1532-L1534).

I'm thinking that for a Python with no `siphash24`, it might be best to issue a loud warning that hash values won't match those computed in the Python interpreter and then just switch to using `siphash` i.e. implement the `TODO` here:
https://github.com/numba/numba/blob/a4c4a8dceb0801672d6fda9199c36047dba16f0b/numba/cpython/hashing.py#L612-L614
Common use cases for hashing, like dictionaries, wouldn't be affected by such a change, it would only be cases where the specific value of the hash matters.

**Comment by stuartarchibald** [comment]
I should also add that this is the first use case in the wild I've seen where `siphash24` is not in use, any idea why this is the case? See [PEP 456](https://www.python.org/dev/peps/pep-0456/) for the [rational for change](https://www.python.org/dev/peps/pep-0456/#rationale) behind its use, the [conclusion](https://www.python.org/dev/peps/pep-0456/#conclusion) is:
> SipHash provides the best combination of speed and security. Developers of other prominent projects have came to the same conclusion.

**Comment by openedev** [comment]
@stuartarchibald Thanks for taking care of this. So numba is looking for siphash24 since it is not been part of python it is by default assume fnv and it indeed went to fnv if statement, is it true?

How can we add siphash24 to python? by some kind of patches or a separate module?

I'm using [python3.8](https://github.com/python/cpython/blob/3.8/configure#L1519) and I can find the log saying it is using default hash (like siphash24)

Python3.8 configure log:

checking for textdomain in -lintl... no
checking aligned memory access is required... yes
checking for --with-hash-algorithm... default
checking for --with-address-sanitizer... no
checking for --with-memory-sanitizer... no
checking for --with-undefined-behavior-sanitizer... no
checking for t_open in -lnsl... no

**Comment by stuartarchibald** [comment]
No problem.

`siphash24` and `FNV` are both implemented in CPython:
FNV: https://github.com/python/cpython/blob/3.8/Python/pyhash.c#L237
siphash24: https://github.com/python/cpython/blob/3.8/Python/pyhash.c#L367-L431

By compiling CPython without setting the `--with-hash-algorithm` flag means the definition `Py_HASH_ALGORITHM` will not be set (`else` branch here https://github.com/python/cpython/blob/3.8/configure#L10051-L10073). As a result the hashing algorithm selection will be based on this: https://github.com/python/cpython/blob/3.8/Include/pyhash.h#L133-L139 which checks the if `HAVE_ALIGN_REQUIRED` is defined, this is determined here at configure time
https://github.com/python/cpython/blob/3.8/configure#L10000-L10043

Relating this back to your logs...
```
checking aligned memory access is required... yes
```
means `HAVE_ALIGNED_REQUIRED` is set and having not specified a hashing algorithm `Py_HASH_ALGORITHM` is unset, and as a result when [this](https://github.com/python/cpython/blob/3.8/Include/pyhash.h#L133-L139) is evaluated:
```c
#ifndef Py_HASH_ALGORITHM
#  ifndef HAVE_ALIGNED_REQUIRED
#    define Py_HASH_ALGORITHM Py_HASH_SIPHASH24
#  else
#    define Py_HASH_ALGORITHM Py_HASH_FNV
#  endif /* uint64_t && uint32_t && aligned */
#endif /* Py_HASH_ALGORITHM */
```
you end up with the `Py_HASH_FNV` algorithm being selected.

**Comment by openedev** [comment]
@stuartarchibald Got it, detailed explanation. Since FNV is not implemented in numba, what if I can set the --with-hash_algorithm=siphash24 if numba enabled. Once the fnv supported by numba, then we can anyway drop this explicit config.

All I'm looking here is, I just wanted to check the supporting hash of numb instead of giving waning for fnv (from your patch) does it sound good?

**Comment by stuartarchibald** [comment]
I would not anticipate that FNV will be implemented in Numba. PEP 456 strongly advocates `siphash24` and as noted previously, this is the first case seen where FNV is in use. Other `aarch64` Python, e.g. that which comes with a Jetson TX2, or Python's built for the `c4aarch64` distribution have `siphash24` so I think it should probably work fine?!

The patch in https://github.com/numba/numba/pull/5327 will stop the presence of FNV being a hard error.

**Comment by openedev** [comment]
I'm getting this print for your patch, ofcouse as expected.

# python3 -c "import numba"
/usr/lib/python3.8/site-packages/numba/targets/hashing.py:496: UserWarning: FNV hashing is not implemented in Numba. See PEP 456 https://www.python.org/dev/peps/pep-0456/ for rationale o
ver not using FNV. Numba will continue to work, but hashes for built in types will be computed using siphash24. This will permit e.g. dictionaries to continue to behave as expected, howe
ver anything relying on the value of the hash opposed to hash as a derived property is likely to not work as expected.
  warnings.warn(msg)

So, this still go with siphash24 and print this before. can't we hide this warning prints? something like debug print until it enable.

or I can force the python3 build with siphash24 hash by saying above information on comments.

Let me know which one make more reasonable?

**Comment by stuartarchibald** [comment]
> So, this still go with siphash24 and print this before. can't we hide this warning prints? something like debug print until it enable.

I'm of the view that silently implementing a different hashing algorithm to the interpreter might break user code in unexpected and confusing ways. I'd rather explicitly warn about the situation, this warning can be silenced by users in one of the standard manners.

> or I can force the python3 build with siphash24 hash by saying above information on comments.
> 
> Let me know which one make more reasonable?

I am unsure as to what the purpose of your interaction with building Numba and CPython is. Are you undertaking a package maintenance role for a linux distribution?
