### ISSUE TITLE
'numba' has no attribute 'set_num_threads'

### ISSUE THREAD

**Issue by cgramesp** [numba/numba#5362]
I am using version 0.48.0 of Numba. The functions set_num_threads() and get_num_threads() are not working since the attribute can not be found.

Code to reproduce:

    import numba
    numba.set_num_threads(8)

    AttributeError: module 'numba' has no attribute 'set_num_threads'

Same problem can be reproduced using "get_num_threads()". Everything works, if I set the number of threads via a system environment variable.

Is there any workaround setting the number of threads inside the python script?

**Comment by esc** [comment]
@cgramesp thanks for asking about this on the Numba issue tracker. May I ask, did you read somewhere that `set_num_threads`  and `get_num_threads` are supposed to be supported? If so, where did you read this? Also, which threading backend would you like to use?

**Comment by stuartarchibald** [comment]
The code that brought this functionality to Numba isn't in a released version yet so you'd need to use a development version. The `dev` docs http://numba.pydata.org/numba-doc/dev/user/threading-layer.html#setting-the-number-of-threads (note the `numba-doc/dev/` in the URL, opposed to `latest` at e.g. http://numba.pydata.org/numba-doc/latest/user/threading-layer.html) will contain reference to the unreleased features in the development version of Numba.

If you would like to try out the latest development releases of Numba they are available via:
```bash
conda install -c numba/label/dev numba
```
(usual caveats about development versions apply!).

**Comment by cgramesp** [comment]
sorry, haven't realized, that I was reading the dev docs. It works with the latest development relaase. Thanks!

**Comment by esc** [comment]
@cgramesp thanks for following up and closing the issue.

**Comment by stuartarchibald** [comment]
Opened https://github.com/numba/numba/issues/5363, should make it more obvious that dev docs are for development versions, it's not really clear.

@cgramesp thanks for confirming, given the thread masking is very new, please do open issues if you encounter any problems. Feedback is very welcome. Thanks.
