### ISSUE TITLE
np.linspace cannot work in nopython mode 

### ISSUE THREAD

**Issue by isaac-you** [numba/numba#5384]
```
# @jit(nopython=True)
# def SEQUENCE(n):
# 	'''
# 	n: must be int scalar
# 	return: the series from 1 to n such as : 1,2,3,4,5
# 	'''
# 	size = n.size 

# 	if size != 1:
# 		return np.array([np.nan],dtype=float32)

# 	if n < 5:
# 		return np.array([np.nan],dtype=float32)

# 	ret = np.linspace(1,n,n).astype(np.float32)
	
# 	return ret 
```

```
ret = SEQUENCE(np.array([10],dtype=np.float32))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function linspace at 0x7f18b802cc80>) with argument(s) of type(s): (Literal[int](1), array(float32, 1d, C), array(float32, 1d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function linspace at 0x7f18b802cc80>)
[2] During: typing of call at <ipython-input-278-ef4938ac07af> (15)


File "<ipython-input-278-ef4938ac07af>", line 15:
def SEQUENCE(n):
    <source elided>
		
	ret = np.linspace(1,n,n).astype(np.float32)
 ^
```

```
ret = SEQUENCE.py_func(np.array([10],dtype=np.float32))
 this can work 
```
and if use np.arange() to replace np.linspace  will give the same error 
so How can I fix this problem, thanks

numpy:   '1.17.2'
numba:   '0.48.0'

**Comment by seibert** [comment]
This looks like a bug in the usage of your SEQUENCE function.  The comment on the function say that `n` should be a scalar, but you pass in `n` as an array.  (Note the `size = n.size` statement.)  Given the usage, I think you want to write `ret = np.linspace(1,size,size).astype(np.float32)`.

Note that the reason your test works in the Python interpreter is that the function returns before the problematic line, whereas the Numba compiler has to type-check the entire function.  (Also note that NumPy will let you use length 1 arrays the same as scalars in some contexts, whereas Numba will not.)

**Comment by esc** [comment]
@isaac-you thanks for reporting this on the Numba issue tracker, we appreciate your continued efforts to improve Numba. It looks like this issue may need some additional triaging.

**Comment by isaac-you** [comment]
@seibert @esc  thank you for the help.

**Comment by stuartarchibald** [comment]
Closing as this seems to be an issue with providing the correct types to `linspace` and it wouldn't work in NumPy either. Example:
```
In [1]: import numpy as np

In [2]: np.linspace(1, 5 * np.ones(5, dtype=np.float32),  np.ones(5, dtype=np.float32))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: object of type <class 'numpy.ndarray'> cannot be safely interpreted as an integer.
```
Would recommend following @seibert's suggestions.
