### ISSUE TITLE
the right way to jit a matrix dot function (why so slow?)

### ISSUE THREAD

**Issue by yxdragon** [numba/numba#5391]
```python
import numpy as np
from time import time
from numba import njit

k = np.zeros((1000, 500), dtype=np.uint8)
x = np.zeros((100, 500), dtype=np.uint8).T
out = np.zeros((1000, 100), dtype=np.uint8)


@njit
def dot(A,B,C):
    m, n = A.shape
    p = B.shape[1]
    for i in range(m):
        for j in range(p):
            s = 0
            for k in range(n):
                s += A[i,k]*B[k,j]
            C[i,j] = s
    return C

dot(k, x, out)
start = time()
for i in range(10):
    dot(k, x, out)
print(time()-start)

start = time()
for i in range(10):
    np.dot(k, x)
print(time()-start)
```

the jit dot cost 0.5s, and the np.dot cost 0.007s
so some questions:
1. what is the right way to jit a dot function?
2. if I modify **s += A[i,k]*B[k,j]** to **s = A[i,k]*B[k,j]**, the cost became 0.001s, (does the compiler detect it is a waste loop, and jump to the last turn?)
3. I write a dot fonction for 1d, and it runs faster than np.dot (about 5 times)
4. np.dot works on int dtype is very slow, about 30 times than float.
5. I had write a 1d jit dot function, and it is 5 times faster than np.dot.

It is not bug, but I am very confused, any help would be welcom!

**Comment by stuartarchibald** [comment]
Thanks for the report.

First up, you are including the time taken to compile the function in the time taken to execute it. See http://numba.pydata.org/numba-doc/latest/user/5minguide.html#how-to-measure-the-performance-of-numba for help on how to time code.

Second, some answers:
1. Typically, one uses the BLAS `xGEMV` or `xGEMM` functions for floating point types, these are wired in to NumPy and Numba's `np.dot` implementations so will automatically get used for floating point types. For types such as `uint8` there's no BLAS function available so something custom has to happen, writing something like you have is one way, casting to a float type might be another.
2. I'd guess that the compiler spots the "waste loop" and "jumps".
3. I'm not sure what this means, please could you expand?
4. Quite probably, the BLAS routines for floating point types are incredibly well optimised.
5. Is this different to 3. ?

**Comment by yxdragon** [comment]
5 is same as 3, I am sorry.
As the 2d dot function is slow, So I test it in 1d.
```python
@njit
def dot(x, y):
    s = 0
    for i in range(len(x)):
        s += x[i]*y[i]
    return s

x = np.zeros(1000000, dtype=np.float64)

start = time()
(x**2).sum()
print(time()-start)

start = time()
np.dot(x, x)
print(time()-start)

dot(x, x)
start = time()
dot(x, x)
print(time()-start)
```
the cost is:
(x**2).sum(): 0.006
np.dot(x, x):  0.018
jit dot(x, x):   0.001

Why in 1d jit is faster than np.dot, (about 6 times faster)
but in 2d, jit is slower than np.dot, (about 60 times slower)

**Comment by yxdragon** [comment]
I find that is because the array's size. 
       x**2   np.dot jit_dot
1e6: 0.003, 0.003, 0.001
1e7: 0.040, 0.017, 0.014
1e8: 0.301, 0.024, 0.142
jit is a linear cost, but np.dot is below a linear cost!

**Comment by stuartarchibald** [comment]
I would recommend reading e.g. this page https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms on what BLAS is. But essentially, it's a specification that describes common linear algebra operations, there are a large number of implementations of the specification. These routines are so fundamental to numerical computing that most hardware vendors supply super optimised versions of them for their hardware. Numba, where possible, uses these routines, as does NumPy. 

What you are doing in the code above is JIT compiling some function that does a BLAS-like operation and then timing execution, the code being compiled is not optimised in the same way BLAS would be, but its quite cheap to launch and doesn't perhaps have some of the overheads of making a BLAS call. There's also the `(x**2).sum()` example, which is using the NumPy API, it's quite possible that the `x**2` is creating a temporary array to store the result of the operation ahead of doing the `sum`. The execution times are going to be influenced by a number of things, as is scaling, as e.g. array temporaries and spatial and temporal locality effects are going to come into play.

> I am not familiar with BLAS, do you mean now cpu with xGEMV treat float faster than int?

No. BLAS operates on floating point types only.

> then another question, ml function are all based on matrix, such as Dense and Convolve...
we often simplelize ml model to uint8, what is the meaning? just compess the model?

It's possible to write highly optimised BLAS-like kernels for e.g. `uint8`, integer arithmetic is a lot cheaper than floating point. It also has the advantage of being a smaller representation, so less data needs moving about, and if it can be "got away with" and produce an acceptable result then this is an optimisation that could appear attractive.

**Comment by yxdragon** [comment]
@stuartarchibald Hi again! 
In fact I am writing a pure numpy cnn framwork (and numba as optional), now it is OK [here](https://github.com/Image-Py/numpy-cnn). following your tips, I use np.dot to get a good performance. And use numba to do im2col (if no numba, I use np.where instead). now it is faster then torch-cpu (tested on windows).

It is very light and flex, esay to install. So now I want to write another vertion with pyopencl, and I find many document and tutorial. But no matter how I modify the code gemm, It is slower then np.dot. even I try it on (intel, amd, nvida GPU). I had spend several days on this peroblem. So I think you may have experience in this field, can you give me some guid or some document.

**Comment by stuartarchibald** [comment]
I don't think that for a standard GEMM operation you'll be able to beat a BLAS function written by a hardware vendor. I suspect your function will always be slower because it isn't doing all the "tricks" that a tuned BLAS does. This is why Numba's `numpy.linalg.dot` implementation also just calls BLAS. The only exception might be for very small matrices, in which case the overhead of making a BLAS call might be significant in comparison to some locally defined GEMM function that can be inlined by LLVM.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
