### ISSUE TITLE
Suggestion for Numba/TARDIS-SN GSoC project

### ISSUE THREAD

**Issue by wkerzendorf** [numba/numba#5394]
TARDIS-SN (http://github.com/tardis-sn/tardis) is a montecarlo radiative transfer code that simulates synthetic observables for supernovae. We have been selected as a GSoC mentor organization and one of our project is to convert our c/cython code to numba. Part of this has already been done - https://github.com/tardis-sn/tardis/pull/929 and the project would be to convert the rest as well as profile and make it faster. We would love to have a co-mentor(s) from the Numba community that would lend their insights on Numba to this applied problem. We would also be very happy if the student is guided to make some improvements to numba. @stuartarchibald suggested posting this here. 

you can reach me here or reach out to wkerzend@msu.edu

**Comment by wkerzendorf** [comment]
I think this would likely be on a 1 hour per week (or less) sort of basis.

**Comment by stuartarchibald** [comment]
@wkerzendorf thanks for posting this, are there some guidelines from e.g. GSoC over what the expectations are of "mentoring" and what it involves etc. Thanks.

**Comment by stuartarchibald** [comment]
I spoke with @sklam and @esc (a couple of the other core devs), we'd really like to help with providing guidance, though are somewhat stretched time wise, and so we were wondering how we can best do this? We can probably lend a hand for about an hour a week to e.g. look at code, discuss approaches to changes, help debug etc. Would that work?

Thanks.

**Comment by wkerzendorf** [comment]
That would be wonderful. Should we meet outside of this issue sometime?

**Comment by stuartarchibald** [comment]
Yes, sometimes towards of the end of next week would probably be good for us as we're in the process of finalising a release candidate/shipping over the next few days. Would that work for you? I'll ping you on https://gitter.im, and we'll sort it out on there!?! Thanks.

**Comment by stuartarchibald** [comment]
I think this issue is "resolved" in that https://github.com/tardis-sn/tardis uses Numba for acceleration now and support channels are set up etc. Thanks for raising this and for using Numba!
