### ISSUE TITLE
How to change structure of a custom object in place?

### ISSUE THREAD

**Issue by densmirn** [numba/numba#5397]
- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Example:
```python
import numba
from numba import cgutils, types
from numba.extending import (box, intrinsic, make_attribute_wrapper, models,
                             overload_method, overload, register_model)
from numba.targets.boxing import box_list
from numba.typing import signature


class Dummy:
    def __init__(self, data):
        self.data = data

    def insert(self, pos, value):
        self.data = self.data[:pos] + [value] + self.data[pos:]


class DummyType(types.Type):
    def __init__(self, data):
        self.data = data
        super().__init__(name=f'Dummy({self.data})')


@register_model(DummyType)
class DummyTypeModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [
            ('data', fe_type.data),
        ]
        super().__init__(dmm, fe_type, members)


make_attribute_wrapper(DummyType, 'data', '_data')


@intrinsic
def init_dummy(typingctx, data):
    def codegen(context, builder, sig, args):
        typ = sig.return_type
        data, = args
        dummy = cgutils.create_struct_proxy(typ)(context, builder)
        dummy.data = data

        return dummy._getvalue()

    ret_typ = DummyType(data)
    sig = signature(ret_typ, data)

    return sig, codegen


@overload(Dummy)
def dummy_overload(data):
    def ctor(data):
        return init_dummy(data)

    return ctor


@box(DummyType)
def box_interval(typ, val, c):
    dummy = cgutils.create_struct_proxy(typ)(c.context, c.builder, value=val)
    data_obj = box_list(typ.data, dummy.data, c)
    class_obj = c.pyapi.unserialize(c.pyapi.serialize_object(Dummy))
    res = c.pyapi.call_function_objargs(class_obj, (data_obj,))
    c.pyapi.decref(data_obj)
    c.pyapi.decref(class_obj)

    return res


@overload_method(DummyType, 'insert')
def insert_overload(self, pos, value):
    def impl(self, pos, value):
        self = Dummy(self._data[:pos] + [value] + self._data[pos:])
        return self

    return impl


def test_impl(data, pos, value):
    d = Dummy(data)
    d.insert(pos, value)

    return d


jtest_impl = numba.njit(test_impl)

data = [0, 1, 2, 3, 4]
pos = 3
value = 10

dummy = test_impl(data, pos, value)
print('Expected:', dummy.data)  # -> [0, 1, 2, 10, 3, 4]

jdummy = jtest_impl(data, pos, value)
print('Got:     ', jdummy.data)  # -> [0, 1, 2, 3, 4]
```
Output:
```
Expected: [0, 1, 2, 10, 3, 4]
Got:      [0, 1, 2, 3, 4]
```

Could you please tell am I able to change structure of a custom object in place? If I am then how can I do that?

Numba version: ef119bcd1733ff49d71bdf2da8a66e91bb704f83

**Comment by stuartarchibald** [comment]
Thanks for the report. You can probably do something like:
```python
@overload_method(DummyType, 'insert')
def insert_overload(self, pos, value):
    def impl(self, pos, value):
        tmp = self._data[pos:][:] # copy list tail
        self._data[pos] = value # inject value
        self._data.append(value) # extend the list by one
        self._data[pos + 1:] = tmp # copy in tail
        return self

    return impl
```
there's also what looks like some ref counting issues that are likely contributing to the segfaults.

**Comment by densmirn** [comment]
Thanks for the workaround for provided example, but in real task I need to use construction like this `self = some_dummy_obj`. So am I able to use this options somehow?

**Comment by sklam** [comment]
`self = some_dummy_obj` would be binding a new variable to `self`. Any inplace mutation would have to be changing the attributes of `self`.

**Comment by stuartarchibald** [comment]
I'm not sure what this means? Are you trying to replace self?

**Comment by AlexanderKalistratov** [comment]
> I'm not sure what this means? Are you trying to replace self?

Yes. There is three cases:
1. Replace underlying data in Series:
```python
    self._data = np.array()
```
But at the moment Numba doesn't allow writable attributes.

2. The same, but with DataFrame. DataFrame has `tuple` of arrays as `_data`:
```python
    self._data[i] = np.array()
```

3. Add new column to DataFrame (extend `tuple`). This actually mutate DataFrame type:
```python
    self._data = tuple(list(self._data) + [np.array()])
```

I assume, the 3rd case is impossible in Numba right now, but what about 1st and 2nd?

**Comment by AlexanderKalistratov** [comment]
@sklam @stuartarchibald let's forget about 3rd case (when we need to mutate type). How can we replace one array member with another array? Of the same type

**Comment by sklam** [comment]
@AlexanderKalistratov, after attempting to produce an example, I am realizing that it is unnecessarily complicated to create a mutable attribute for a `StructModel`. Part of what is needed is implemented in `jitclass`.  To make a internally mutable object, the structure payload has to be stored as a refcounted pointer (`MemInfoPointer`). The jitclass data model does that: https://github.com/numba/numba/blob/700d38e4f5004d84966c260d5c9050d0fb637f5d/numba/experimental/jitclass/base.py#L21-L40.  However, the use of refcounted pointer requires us to define a destructor for the payload. Attributes access become indirect because they go through a pointer. The jitclass implementation is automating all of these.

I think the proper thing to do is to refactor these part of `jitclasses` out into extendable code that works with `StructModel`-style API.
