### ISSUE TITLE
How well can CUDA be compatible with class

### ISSUE THREAD

**Issue by YebiaoJ** [numba/numba#5398]
Hi all,

I'm trying to make my code more modular, so inevitably I will want to write CUDA device functions and kernel functions into different classes, e.g. I want to put device function d() in class A and kernel functions f() into class B. When I try to call the device function d() within the kernel function f(), can i directly use A.d()? And moreover, can i directly use the variable in class A: A.a within kernel function f() as a constant?

I'm aware that jitclass does not support the CUDA well, here I try to break my long code into pieces instead of sealing the device & kernel function in one script.

Thanks in advance!

**Comment by stuartarchibald** [comment]
Thanks for the question. I think the answer to pretty much all of the above is "probably not". That said `@staticmethods` _may_ (I'm really not sure from memory) work. In general, Numba is most happy with module level functions!
