### ISSUE TITLE
numba.errors.TypingError

### ISSUE THREAD

**Issue by sin-en-2009** [numba/numba#5407]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'isinstance': cannot determine Numba type of <class 'builtin_function_or_method'>

my code:
```
def minkowski_distance(vec1:np.ndarray, vec2:np.ndarray, p=3)->float:
       if not isinstance(vec1,np.ndarray) or not isinstance(vec2,np.ndarray):
        print('change vector to np.array.....')
        vec1, vec2 = np.asarray(vec1), np.asarray(vec2)
       else:pass
       dis = sum([(x - y) ** p for (x, y) in zip(vec1, vec2)])
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Numba doesn't support `isinstance` in `nopython` mode. Also, as `np.asarray` is a no-op if the argument is already an array, you can probably just not have that branch and always `np.asarray()` your vectors?

In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
