### ISSUE TITLE
CUDA printing is unreliable

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#5421]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Reproducer:

```python
from numba import cuda

@cuda.jit
def f():
    print("Hello from f")

print("Launch f")
f[1, 1]()

@cuda.jit
def g():
    print(1)

print("Launch g")
g[1, 1]()
```

Expected:

```
Launch f
Hello from f
Launch g
1
```

Actual:

```
Launch f
Launch g
Hello from f
```

**Comment by gmarkall** [comment]
The problem is between the keyboard and the chair - printing is asynchronous. Changing to:

```python
from numba import cuda

@cuda.jit
def f():
    print("Hello from f")

print("Launch f")
f[1, 1]()
cuda.synchronize()

@cuda.jit
def g():
    print(1)

print("Launch g")
g[1, 1]()
cuda.synchronize()
```

yields:

```
Launch f
Hello from f
Launch g
1
```

**Comment by gmarkall** [comment]
Some explanation added to the docs in #5423.

**Comment by sklam** [comment]
Right, it needs a synchronize call.
