### ISSUE TITLE
Array analysis failure `cannot unpack non-iterable NoneType object`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5439]
## Reporting a bug

- [x] I am using the ~latest released~ master version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This:

```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def f3():
    arr = np.arange(20)
    for i in prange(2):
        for j in range(20):
            idx = j

        _ = arr[:idx]

f3()

```
does this:
```
numba/numba/parfors/array_analysis.py", line 826, in plus
    (var, offset) = x
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
cannot unpack non-iterable NoneType object
```

**Comment by stuartarchibald** [comment]
CC @DrTodd13

**Comment by sklam** [comment]
Fixed by https://github.com/numba/numba/pull/5694
