### ISSUE TITLE
Numba doesnt recognize another classes

### ISSUE THREAD

**Issue by kuttamuwa** [numba/numba#5444]
I am trying to make coordinate transformation on numpy array. I've tried many things to do that using numba but couldn't handle due to pypreproj objects. 

`
from pyreproj import Reprojector
from numba import jit

rp = Reprojector()

@jit(nopython=True)
def transform(x, y):
    p1_transformed = rp.transform(Point(x, y), 'epsg:4326', 'epsg:32636')
    return p1_transformed.x, p1_transformed.y

@jit(nopython=True)
def run():
    for row in coords:
        row[0], row[1] = transform(row[0], row[1])

run()
`

Does numba allow to use another classes types? The problem sources on here. If not, can we do? Otherwise, numba seems useful because only arithmetic operations can be done, right?

**Comment by esc** [comment]
Thanks for the report. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.

 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

I.e. `pyreproj` objects are not supported. You  could try using raw Numpy arrays instead, perhasp?

**Comment by esc** [comment]
The other option might be to re-implement your transforms as Numba kernels/functions.

**Comment by kuttamuwa** [comment]
Thanks for reply. Unfortunately I cannot use raw numpy array because I need coordinate transformation and that can be done with pyreproj lib. 

Implementing as numba kernel functions? How can i do that? I suppose this cant be done either because I cannot implement whole module from pyreproj.

I don't know, I'll try to use dask or multiprocessing. I run simple loop for my array yesterday 15:30 and it still going on :) I don't know how to do that.

**Comment by esc** [comment]
@kuttamuwa my suggestion would be to implement the projection that you need in pure python + Numpy code and then try to jit-compile it.  You could then use a `ufunc` or `gufunc`:

http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#vectorized-functions-ufuncs-and-dufuncs

to apply that transformation to an array in "bulk". Maybe you could also extract the relevant projection from the Reprojector project?

**Comment by kuttamuwa** [comment]
I solved the problem without numba, thanks:

`# coords = np.array(nc_in_df[['Latitude', 'Longitude']])
# coords = coords.round(decimals=5)
# coords_tuple = [tuple(x) for x in coords]
#
# new_pts = [i for i in transformer.itransform(points=coords)]
# new_coords = np.array(new_pts)`

**Comment by esc** [comment]
@kuttamuwa thanks for following up and closing this issue.
