### ISSUE TITLE
Use complex number ordering from NumPy?

### ISSUE THREAD

**Issue by seibert** [numba/numba#546]
Pure python does not allow complex numbers to be ordered:

``` python
>>> (1 + 2j) < (2 + 1j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: no ordering relation is defined for complex numbers
```

However, NumPy does, using lexical ordering (real, then imaginary part):

``` python
>>> import numpy as np
>>> np.less(1+2j, 2+1j)
True
>>> np.less(1+2j, 1+0j)
False
```

Which convention should we support?

**Comment by stuartarchibald** [comment]
Do what NumPy does. As per https://github.com/numba/numba/pull/3657#issuecomment-452024544. Closing.
