### ISSUE TITLE
Regression 0.49RC1 vs 0.48 (tuple of functions)

### ISSUE THREAD

**Issue by piotrbartman** [numba/numba#5470]
```
import numba


@numba.njit()
def foo():
    return 0


formulae_foo = (foo, foo)


@numba.njit()
def bar_scalar(_, __):
    return 0


@numba.njit()
def bar():
    return bar_scalar(*formulae_foo)


bar()
```
This code works with numba 0.48, but with numba 0.49RC1 it produce following error:

```
Type of variable '$6call_function_ex.2' cannot be determined, operation: call $2load_global.0(*$4load_global.1, func=$2load_global.0, args=[], kws=[], vararg=$4load_global.1), location: .../numba_tst.py (19)
File "numba_tst.py", line 19:
def bar():
    return bar_scalar(*formulae_foo)
    ^
```

**Comment by esc** [comment]
@piotrbartman thanks for submitting this. I tried this on the current master and can reproduce this.

**Comment by stuartarchibald** [comment]
I expect the first-class function type feature triggered this regression, CC @pearu

**Comment by pearu** [comment]
@stuartarchibald  , a fix as been filed in PR #5473

**Comment by stuartarchibald** [comment]
Thanks @pearu, much appreciated.

**Comment by esc** [comment]
@piotrbartman if you have bandwidth, we would appreciate you checking that #5473 fixes your issue indeed.

**Comment by piotrbartman** [comment]
With numba from https://github.com/Quansight/numba/tree/pearu/issue5470 this test works, but with some modifications:

```
import numba


@numba.njit()
def apply(fun_0, fun_1):
    return 0


def make_bar():

    formulae_foo = (__make_foo(), __make_foo())

    @numba.njit()
    def bar():
        return apply(*formulae_foo)

    return bar


def __make_foo():
    @numba.njit()
    def foo():
        return 0
    return foo


fun = make_bar()
fun()
```

still produce error (and additional warning):

```
...\numba\core\utils.py:509: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  category=NumbaExperimentalFeatureWarning)
(...)
Type of variable '$6call_function_ex.2' cannot be determined, operation: call $2load_global.0(*$4load_deref.1, func=$2load_global.0, args=[], kws=[], vararg=$4load_deref.1), location: .../numba_tst.py (15)
File "numba_tst.py", line 15:
    def bar():
        return apply(*formulae_foo)
        ^
```

**Comment by esc** [comment]
@pearu could you take another look, please? Thanks!

**Comment by pearu** [comment]
The underlying problem here is that it is hard to predict what is user intention with a tuple containing unprecise function objects: are the tuple items supposed to have the same precise type or not?
I'll dig further to find a sensible solution to this problem..

**Comment by piotrbartman** [comment]
The source of  these minimal working reproducers is the software (some numerical PDE solver) which I develop, and which works with numba 0.48 but it failed with the new version.

**Comment by pearu** [comment]
@piotrbartman Thank you very much for testing numba RC 0.49 against your application!
In #5473 , I have turned off the first-class function support for tuples of dispatchers.
Could you recheck if your application works with #5473 now?

**Comment by piotrbartman** [comment]
With [#5473](https://github.com/numba/numba/pull/5473) it works!

**Comment by esc** [comment]
@pearu @piotrbartman thanks for circling back on this one!

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/5529. Closing.
