### ISSUE TITLE
typed List() append changes types

### ISSUE THREAD

**Issue by ortmann-paul** [numba/numba#5483]
When initiating a typed List and appending a tuple the previously specified types of the elements in the tuple are not preserved. Is this intended?
```
from numba.typed import List
import numpy as np
from numba import typeof
my_tuple=(np.uint32(0), np.uint32(10))
test=List()
test.append(my_tuple)
typeof(test[0][0])
Out: int64
```

**Comment by esc** [comment]
@ortmann-paul thanks for asking about this. I had a look and I am not sure why, but using `np.int32` seems the problem here. Using `int32?` from `numba` instead yields what you want for now:

```
In [10]: from numba.typed import List

In [11]: from numba import njit, int32, typeof

In [12]: l = List([(int32(0),int32(1),)])

In [13]: typeof(l[0][0])
Out[13]: int64
```

**Comment by esc** [comment]
Note, the `List` ctor is new and only available from `0.49.0RC1` onwards.

**Comment by ortmann-paul** [comment]
@esc maybe there was a misunderstanding but I don't think this actually fixed the issue. It's still int64, I'd expect int32. But yaay, looking forward to list constructors (:

**Comment by esc** [comment]
@ortmann-paul whoopsi, my bad, you are right. The type still seems to be correct however so it looks like the `getitem` might be to blame:

```
In [4]: l
Out[4]: ListType[UniTuple(int32 x 2)]([(0, 1)])
```

**Comment by esc** [comment]
It seems to happen for plain integers also:

```
In [1]: from numba.typed import List

In [2]: from numba import njit, int32, typeof

In [3]: l = List((int32(1),))

In [4]: l
Out[4]: ListType[int32]([1])

In [5]: l[0]
Out[5]: 1

In [8]: typeof(l[0])
Out[8]: int64
```

**Comment by esc** [comment]
taking a closer look here:

```
In [15]: from numba import njit, int32, typeof

In [16]: from numba.typed import List

In [17]: l = List((int32(1),))

In [18]: typeof(l[0])
Out[18]: int64

In [19]: type(l[0])
Out[19]: int

In [20]: type(int32(1))
Out[20]: numpy.int32
```

So the problem is, that when you use `getitem` in the interpretr, the return value is boxed into a Python type, i.e. an `int`. Then: calling `typeof` on a Python `int` will tell you that Numba will represent this as an `int64` if you send it into a Numba compiled function, hence the output of what you see.

**Comment by ortmann-paul** [comment]
That makes sense, but then it should not hold inside of a jitted function that uses the values right?
```
from numba.typed import List
   ...:from numba.types import uint32
   ...:from numba import typeof
   ...:my_tuple=(uint32(0), uint32(10))
   ...:my_test=List()
   ...:my_test.append(my_tuple)
   ...:@njit
   ...:def foo(test):
   ...:    return test[0][0]
   ...:typeof(foo(my_test))
Out[28]: int64
```

**Comment by esc** [comment]
@ortmann-paul indeed, but in the case above you are also returning from a jitted function. This is actually how `getitem` is implemented in the interpreter:

https://github.com/numba/numba/blob/master/numba/typed/typedlist.py#L74-L76

**Comment by esc** [comment]
@ortmann-paul one way to checkout the types is to use `inspect_types()` on your compiled function.

```
In [1]: from numba.typed import List

In [2]: from numba import njit, int32, typeof

In [3]: @njit
   ...: def foo(a):
   ...:     return a[0]
   ...:

In [4]: l = List((int32(1),))

In [5]: foo(l)
Out[5]: 1

In [6]: foo.inspect_types()
foo (ListType[int32],)
--------------------------------------------------------------------------------
# File: <ipython-input-3-acf86f5c2185>
# --- LINE 1 ---

@njit

# --- LINE 2 ---

def foo(a):

    # --- LINE 3 ---
    # label 0
    #   a = arg(0, name=a)  :: ListType[int32]
    #   $const4.1 = const(int, 0)  :: Literal[int](0)
    #   $6binary_subscr.2 = static_getitem(value=a, index=0, index_var=$const4.1)  :: int32
    #   del a
    #   del $const4.1
    #   $8return_value.3 = cast(value=$6binary_subscr.2)  :: int32
    #   del $6binary_subscr.2
    #   return $8return_value.3

    return a[0]


================================================================================
```

**Comment by ortmann-paul** [comment]
alright, thanks for the clarification!

**Comment by esc** [comment]
@ortmann-paul thanks for following up and closing this issue.
