### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'numpy_support' in numpy 0.49

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#5487]
`pygae/clifford` assumes that `numba.numpy_support` is pre-imported by numba internally before using it.

However, while a shim is present at `numba/numpy_support.py`, it is not enough for modules assuming it is pre-imported.

To solve this, I think `numba.__getattr__` needs to be defined to convert `getattr(numba, 'numpy_support')` into `import numba.np.numpy_support; return numba.np.numpy_support`.

**Comment by stuartarchibald** [comment]
Thanks for the report and suggested fix. I think this is the same problem as reported here: https://github.com/numba/numba/issues/5466, seems pressing that we find a way to make this work ok for the 0.49 shim.

**Comment by eric-wieser** [comment]
Yep, this is a duplicate.
