### ISSUE TITLE
Invalid copy of Array analysis object for IR extension handlers (regression in 0.49rc1)

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#5515]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The commit eae2d2bc341df8032879d1fd4c4ec7a2d9dd401d in array analysis refactoring PR (#5320)  avoids mutation of array analysis objects when passed to IR extension handlers. However, this defeats the whole purpose of these handlers, which are supposed to add more information. See handler of parfors [here](https://github.com/numba/numba/blob/1ea770564cb3c0c6cb9d8ab92e7faf23cd4c4c19/numba/parfors/parfor.py#L646).

@sklam was there a problem with these handlers that copying solves?

**Comment by gmarkall** [comment]
Thanks for the issue report - marked to triage by @sklam.

**Comment by sklam** [comment]
I made a patch to revert the commit. 

@ehsantn it'd be great if you can show us the code that https://github.com/numba/numba/commit/eae2d2bc341df8032879d1fd4c4ec7a2d9dd401d is breaking.

**Comment by ehsantn** [comment]
Any code that needs array analysis inside a parfor will break. Creating a simple example that actually fails is difficult. But let's consider this code:
```python
@numba.njit(parallel=True)
def f(n):
    A = np.empty(n)
    for i in numba.prange(n):
        S = np.arange(i)
        A[i] = S[0]
    return A

f(10)
```
The post parfor array analysis [here](https://github.com/numba/numba/blob/ce2139c7dd93127efb04b35f28f4bebc7f44dfd5/numba/parfors/parfor.py#L2623) won't have any info about variable `S` (or its renamed names).

**Comment by sklam** [comment]
@ehsantn, 

> The post parfor array analysis here won't have any info about variable S (or its renamed names).

Do you know where would that information be stored? I am trying to create a test by using the `parallel_diagnostics()` to check for differences in the performed optimizations but I am not finding any.

**Comment by ehsantn** [comment]
I don't think `parallel_diagnostics` stores array analysis info. I'd see how testing array analysis is done in `test_array_analysis.py`.

**Comment by sklam** [comment]
A lot of `test_array_analysis.py` is based on `equiv_set` which is cleared before hitting the line you referred to at post parfor array analysis.

**Comment by ehsantn** [comment]
You can just add a compiler stage after parfor stage is done, and rerun array analysis. That specific line is not important. It should be after parfor transformation is done (parfor nodes are present).
