### ISSUE TITLE
Tuple of inner functions typing regression in 0.49rc1 due to first class functions feature

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#5522]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Type inference in 0.49rc1 infers a tuple of different inner functions as a unituple like `UniTuple(UndefinedFunctionType[undefined()1] x 2)`.  Example:
```python
import numba
from numba.extending import overload


def g(t):
    pass

@overload(g)
def overload_g(t):
    print(t)
    print(t.types[0].dispatchers)
    return lambda t: 0

@numba.njit
def f():
    def h1(x):
        return x

    def h2(x):
        return 2 * x
    
    return g((h1, h2))

f()
```
output in 0.48:
```
Tuple(type(CPUDispatcher(<function g.<locals>.f at 0x1258cb5f0>)), type(CPUDispatcher(<function g.<locals>.f at 0x1258cb9e0>)))
```
output in 0.49rc1:
```
UniTuple(UndefinedFunctionType[undefined()1] x 2)
```
Looks like there is an attribute with a set of dispatchers:
```
print(t.types[0].dispatchers)
# {CPUDispatcher(<function g.<locals>.f at 0x11f4d1dd0>), CPUDispatcher(<function g.<locals>.f at 0x11f4d1d40>)}
```
Somehow it doesn't recognize that the functions are actually different.

**Comment by stuartarchibald** [comment]
Thanks for the report. Does #5473 perhaps fix this?

**Comment by ehsantn** [comment]
Looks like it fixes it.

**Comment by stuartarchibald** [comment]
Duplicate cause as https://github.com/numba/numba/issues/5470

**Comment by stuartarchibald** [comment]
#5529 Merged. Closing.
