### ISSUE TITLE
How to create a typed dict in Numba dict[str] = list

### ISSUE THREAD

**Issue by 6Hhcy** [numba/numba#5524]
I am trying to create a dictionary in nopython mode. This is what I have:

```
import numba

@numba.njit()
def func():

    d = numba.typed.Dict.empty(
        key_type=numba.types.unicode_type,
        value_type=numba.ListType(np.float64)
    )

    d["a"] = [1, 1]

    return d

print(func())
```

Error:
```
Invalid use of Function(<class 'numba.types.containers.ListType'>) with argument(s) of type(s): (Function(<class 'float'>))
 * parameterized
In definition 0:
    TypeError: typer() takes 0 positional arguments but 1 was given
```

**Comment by esc** [comment]
@6Hhcy thanks for asking about this, how about:

```
import numba

@numba.njit()
def func():

    d = numba.typed.Dict()
    d["a"] = numba.typed.List((1.0, 1.0))

    return d

print(func())
```

You'll need at least 0.49.0RC1 to do the `List` constructor, but it should get you what you want.

**Comment by esc** [comment]
@6Hhcy haven't heard back from you yet, was just wondering if my comment was of use at all?

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by 6Hhcy** [comment]
Apologies for the late reply. I'm using v0.48...is there no way to do it in this version? Regards

**Comment by esc** [comment]
@6Hhcy thanks for following up and yes, there is. But you need to set the list up in several steps.

```python
import numba

@numba.njit()
def func():

    d = numba.typed.Dict()
    l = numba.typed.List()
    for i in (1.0, 1.0):
        l.append(i)
    d["a"] = l

    return d

print(func())
```

**Comment by 6Hhcy** [comment]
thank you
