### ISSUE TITLE
Add figure for total memory to `numba -s` output.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5525]
## Feature request

It'd be useful to have the amount of memory available on a machine added to the `numba -s` output. This is useful to know for cases where e.g. swapping might be occurring.

This is a good first issue, work involves:

1. Find a way to get the total available memory using Python standard libraries or NumPy.
2. Print the information in 1. in this section: https://github.com/numba/numba/blob/master/numba/misc/numba_entry.py#L34 such that `numba -s` reports the amount of available memory.

**Comment by jagaudin** [comment]
It seems that [psutil](https://github.com/giampaolo/psutil) would be the way to go. It claims it supports a range of platforms (Unix-like, Windows, etc.). Can a dependency be added or is it preferable to write independent code? I'd be quite happy to work on this.

**Comment by gmarkall** [comment]
If writing independent code becomes an inferior re-implementation of psutil, it might be better to have an optional dependency on psutil (with memory information omitted if psutil is not present).

**Comment by jagaudin** [comment]
That would be my preference indeed, maintaining the code for several platforms may become tedious and there could be difficulties with testing.

**Comment by esc** [comment]
depending on the size and license of `psutil` it may make sense to vendor the library so as to avoid having to spec, resolve and install another dependency .

**Comment by jagaudin** [comment]
The psutil folder on my machine is 1.6 MB and the software goes under BSD 3-Clause "New" or "Revised" License.

**Comment by stuartarchibald** [comment]
Given vendoring `psutil` involves compiling in largish C extensions etc., I think we can either cover linux, osx, windows, which should be reasonably ok to do given it's just reading a value with a variety of methods available to do this. Or add an optional dep on `psutil`, the field in `numba -s` can just have "install psutil to see this" if `psutil` isn't present.

**Comment by jagaudin** [comment]
I've done a bit of research for linux, osx and windows. In summary:

- **Linux**: `cat /proc/meminfo` gives total, free and available memory as well as swap total and swap free
- **Mac OS**: this seems a bit more tricky. There is a relevant [discussion](https://github.com/giampaolo/psutil/issues/1277) about the way it is calculated in `psutil`. `psutil`'s function for Mac is written in C and seems to make use of a `sysctl` library. 
- **Windows**: `psutil`'s function is written in C and seems to use `Psapi` library.

Writing a short module in C is within reach for me (although I did that some time ago) and the code in `psutil` gives a good indication of what to look for.

I don't have a Mac available for test, but I have Linux and a Windows 10 virtual machine.

**Comment by stuartarchibald** [comment]
Thanks for looking a this, whilst a C module would likely work, it has a maintenance cost that needs to be balanced against the use. I'm wondering what your thoughts are on a more basic alternative, perhaps:

* Linux: read `/proc/meminfo` as we do for e.g. CFS groups:
  https://github.com/numba/numba/blob/ce2139c7dd93127efb04b35f28f4bebc7f44dfd5/numba/misc/numba_entry.py#L61-L64
* OSX: open a subprocess, call `sysctl hw.memsize`, capture output
* Windows: Perhaps `ctypes.windll.kernel32` call to https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex ?

**Comment by jagaudin** [comment]
@stuartarchibald My first impression was that running shell commands via a subprocess or reading files would introduce some parsing code which can sometimes look a bit verbose. However, this option would be written in Python and be easy to debug.

I have summarized the pros and cons of the different options we have so far (please feel free to edit):

- **`import psutil`**
    - Pros: clean code, results returned as a named tuple, can add features later
    - Cons: need optional dependency

- **Subprocesses / file parsing**
    - Pros: internal code, no dependency, written in Python, easy to debug
    - Cons: parsing code can be verbose and break later, adding features requires new parsing code

- **C module**
    - Pros: internal code, features can be added later, results can be used programmatically
    - Cons: C code maintenance, platform-dependent build, debugging may be less easy

**Comment by seibert** [comment]
My vote is for optional dependency on psutil.  It is relatively easy to tell someone to conda/pip install it if they don't have it and we need additional information.

**Comment by esc** [comment]
My first vote is for a *Subprocessing / file parsing* solution provided that it doesn't turn into a deep rabbit hole. I would like to see the amount of memory that the machine has by default when executing `numba -s` and I don't believe that this should be optional. If we can get that working with a small, self contained and robust solution. If that is not feasible and I am underestimating complexity here then an optional dependency on `psutil` would also be acceptable for me too, however.

**Comment by jagaudin** [comment]
I found a Windows command that can be used to get the total and available memory:

    systeminfo | findstr /C:"Memory"

That makes me lean towards the subprocessing option. I need someone with a mac to give me the output of `sysctl hw.memsize` though.

**Comment by stuartarchibald** [comment]
I think I'd also prefer some version of it to just work OOTB. It seems like it'd be pretty cheap (probably <30 lines) to find something that works most-of-the-time even if not perfect. I think going with just total memory is fine as a start. None of this precludes looking for `psutil` in the env to start with as a shortcut.

Requested example output on a mac:
```
$ sysctl hw.memsize
hw.memsize: 17179869184
```

**Comment by jagaudin** [comment]
Considering that in the future, we will return a dictionary of the system info, I've written a little [snippet]("https://gist.github.com/jagaudin/30ba6eda936b48aeae3646918b4ba602.js") to show how I would proceed. Let me know if you have any comments, otherwise will proceed on this base for Windows and MacOs.

**Comment by jagaudin** [comment]
I've created a PR to add the feature. The code was getting long so I put it in a separate script. I've done some refactoring to be able to return a `dict` with all the information, it looks like big changes but the information collection process is pretty much the same.

**Comment by stuartarchibald** [comment]
@jagaudin great, thanks for doing this.

**Comment by jagaudin** [comment]
@stuartarchibald You're most welcome. Once the code will be reviewed and agreed on, I can add `psutil` to the mix and maybe an option to save the system info `dict` as a json file from the `numba` command entry.
I'll keep an eye on additional features we could get for free if `psutil` is installed.

**Comment by esc** [comment]
@jagaudin this is great news! Can you link in the PR you created, please?

**Comment by jagaudin** [comment]
@esc It is #5591

**Comment by jagaudin** [comment]
#5591 is ready for review with psutil, testing and json export. Hope you'll like it.
