### ISSUE TITLE
Numba 0.49.0rc1 does not provide aliases for some use cases

### ISSUE THREAD

**Issue by PokhodenkoSA** [numba/numba#5528]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When I use Numba 0.49.0rc1 I see many warnings like this:
```
Import of 'from_dtype' requested from: 'numba.numpy_support', please update to use 'numba.np.numpy_support' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.`
```
It is OK and aliases work fine for the most of my cases but does not work for some cases I have:
1. `from numba.targets import quicksort`
1. `from numba.special import literally` and `from numba.special import prange`
1. `from numba import postproc`
1. `import numba` and `numba.analysis.ir_extension_usedefs[Join] = join_usedefs`
1. `from numba import consts`
1. `import numba` and `lower_builtin('getiter', string_array_type)(numba.targets.arrayobj.getiter_array)`
1. `from numba.config import IS_32BITS`
1. `import numba` and `numba.datamodel.register_default(...)`

Please, give me note whether it is possible to be fixed before 0.49.0 release.

**Comment by sklam** [comment]
Thanks for the report. There are a few PRs in-flight trying to address the import alias issues. We will make sure they are addressed.
