### ISSUE TITLE
Invalid np.dot() output for vector/matrix multiply of empty arrays

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#5539]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Looks like `np.dot` implementation doesn't handle empty input properly:

```python
In [161]: X = np.array([]).reshape(0, 2)

In [162]: Y = np.array([])

In [163]: numba.njit(lambda X, Y: np.dot(Y, X))(X, Y)
Out[163]: array([-1.36311572e+57, -1.36311572e+57])

In [164]: np.dot(Y, X)
Out[164]: array([0., 0.])
```

**Comment by gmarkall** [comment]
I can reproduce this - executable reproducer for ease of copy/paste/go:

```python
import numba
import numpy as np

X = np.array([]).reshape(0, 2)

Y = np.array([])

print(numba.njit(lambda X, Y: np.dot(Y, X))(X, Y))
# array([-1.36311572e+57, -1.36311572e+57])

print(np.dot(Y, X))
# array([0., 0.])
```
