### ISSUE TITLE
No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special'

### ISSUE THREAD

**Issue by AashinShazar** [numba/numba#5550]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I'm getting an exception has occured: ValueError for the following piece of code:

```
@njit
def mainSequence(TrainData):
    TrainData = preprocessing.scale(TrainData, axis=1)
    return TrainData

def main():
    Data = np.random.rand(15360,192)
    mainSequence(Data)

```

I get the following error for Data passed into mainSequence within def main():

> No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special'. 

Does this something to do with the dtype being float64? Any help is appreciated, thank you!

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect that you have `numba-scipy` installed along with a version of SciPy that accidentally broke `numba-scipy`. See https://github.com/numba/numba-scipy/issues/35 and fix https://github.com/numba/numba-scipy/pull/37. Numba 0.49, when it ships sometime in the next week or so, also has a fix to deal with broken extension packages.

If you would like to try out the 0.49 release candidate of Numba (it's on rc2, rc1 needed fixes) it's available via:
```bash
conda install -c numba numba=0.49.0rc2
```
(usual caveats about development versions apply!).

**Comment by AashinShazar** [comment]
Thanks for your reply! Uninstalling numba-scipy provided a fix for this issue.
