### ISSUE TITLE
Environment variables with NUMBAPRO prefix are depreciated

### ISSUE THREAD

**Issue by YebiaoJ** [numba/numba#5563]
## Reporting a bug
I just updated my NUMBA from 0.42 to 0.48 and a warning has arisen:
/home/bepp/yebiao/ProjectA/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning:
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning:
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice/.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I used environment path: 
export NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice/

What new environment path should I use instead to get rid of the warnings?

**Comment by stuartarchibald** [comment]
Thanks for the report. If you follow the link in the warning message it takes you here: http://numba.pydata.org/numba-doc/latest/cuda/overview.html, the section "Setting CUDA Installation Path" explains a few options. I think in your case you may just not need to have them set any more as using an installation in `/usr/local/cuda` is now supported. Hope this helps?

**Comment by YebiaoJ** [comment]
Is it true that I can ignore the warning? At least, my code seems to run as before except for these warnings.

**Comment by stuartarchibald** [comment]
@YebiaoJ I expect you have case 3 here: http://numba.pydata.org/numba-doc/latest/cuda/overview.html#setting-cuda-installation-path

> System-wide installation at exactly /usr/local/cuda on Linux platforms. Versioned installation paths (i.e. /usr/local/cuda-10.0) are intentionally ignored. Users can use CUDA_HOME to select specific versions.

Numba will ignore the environment variables starting with `NUMBAPRO_` and work anyway because I think you have case 3 above. To get rid of the warnings, stop setting the `NUMBAPRO_` environment variables.

**Comment by YebiaoJ** [comment]
Thanks so much! Problem has been perfectly solved.

**Comment by stuartarchibald** [comment]
No problem, thanks for using Numba!
