### ISSUE TITLE
numba.roc.atomic erroneously assumes ints

### ISSUE THREAD

**Issue by hexi03** [numba/numba#5577]
Hi, I have a question about numba.roc.atomic and I don't know where I can ask about it, so I will ask it here.
How can I use numba.roc.atomic.add with floating point numbers, and where can I find other atomic operations?
I tried to execute the code from the attached file, but i got this:

[test.txt](https://github.com/numba/numba/files/4491569/test.txt)

> RuntimeError: Failed in nopython mode pipeline (step: nopython mode backend)
LLVM IR parsing error
<string>:278:44: error: atomicrmw add operand must be an integer
  %".246" = atomicrmw add double* %".245", double %".228" monotonic

I read https://numba.pydata.org/numba-doc/latest/roc/intrinsics.html, but did not find the necessary information there
thanks in advance for your reply

**Comment by stuartarchibald** [comment]
Thanks for the report. I think you've hit a bug. The code gen for the atomic is assuming `int` types:
https://github.com/numba/numba/blob/1f9d82fc892678242216b4e2e4f724b4ff3db973/numba/roc/hsaimpl.py#L234 and issuing an `add` whereas it ought to be looking at the data types and issuing instructions based on the type, `fadd` in the case you present.

> where can I find other atomic operations?

IIRC there are no other atomic operations implemented. The ROC target doesn't have as much implemented as e.g. the CUDA target.

**Comment by hexi03** [comment]
I experimented a bit and replaced 'add' with 'fadd' in 'return builder.atomic_rmw ("add", ptr, val, ordering =' monotonic ')'
And I got this:
`
LLVM IR parsing error
<string>: 278: 23: error: expected binary operation in atomicrmw
..% ". 246" = atomicrmw fadd double *% ". 245", double% ". 228" monotonic
...................... ^
`
It seems that the syntax is correct, but llvm still swears
I also did 'sudo apt-get install llvm' but nothing changed

**Comment by stuartarchibald** [comment]
Thanks for reporting back, it might be that `atomicrmw` doesn't support floating point, would have to check.

**Comment by hexi03** [comment]
'fadd' and 'fsub' instructions for 'atomicrnw' only appear in llvm9. It seems time to upgrade 'llvmlite', as I understand it, it only supports 'llvm8'
https://releases.llvm.org/9.0.0/docs/ReleaseNotes.html

**Comment by stuartarchibald** [comment]
@hexi03 ah, thanks for looking, beat me to it :) Yes, seems like `roctools` needs an update to LLVM 9 for this to work.

**Comment by esc** [comment]
@stuartarchibald do we want to close this issue, given the deprecation schedule for ROCm?

**Comment by stuartarchibald** [comment]
Yes, I think this can be archived.
