### ISSUE TITLE
Incorrect Directory Reference to numba/npyunfunc

### ISSUE THREAD

**Issue by seanlaw** [numba/numba#5586]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report and fix.
