### ISSUE TITLE
Single float value in numba Dict

### ISSUE THREAD

**Issue by oiluigio** [numba/numba#5594]
I am trying to set a dictionary with int64 as keys and single precision float32 as values.
For example: 

from numba.typed import Dict
from numba import types

dict = Dict.empty(
    key_type=types.int64,
    value_type=types.float32
)

When I assign one single precision value for example to dict[0] 
and check what is in dict[0] I find the double precision version of the value. 
Curiously if I print with a format identifier %f a single precision value is printed,
but dict[0] is truly a double precision value.

here is a minimal reproducer, I use numba 0.49.0

[numba_Dict_float32.txt](https://github.com/numba/numba/files/4503978/numba_Dict_float32.txt)

**Comment by sklam** [comment]
When returning a `numba.types.float32` from compiled code, Numba will use the python `float` representation, which is double-precision. So when reading `dict[0]` from the non-compiled code, you will see a double-precision value.  The reason being that there is no builtin single-precision float type in Python and the `numpy.float32` type is very slow. 

As for print formatting, it is not an accurate way to tell if the value is single or double precision. You are seeing the difference in decimal precision of the formatter.

**Comment by oiluigio** [comment]
Are you suggesting that it is only a matter of print formatting and that numba.typeof should produce a different response? numba.typeof seems to indicate that the type has changed:
[numba_Dict_float32_typeof.txt](https://github.com/numba/numba/files/4508793/numba_Dict_float32_typeof.txt)

**Comment by stuartarchibald** [comment]
@oiluigio RE formatting in GitHub issues, for future reference triple backticks can be used to create a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

This is your last posted example in such a code block:
```python
import numpy as np
import numba as nb
from numba.typed import Dict
from numba import types


dict = Dict.empty(
    key_type=types.int64,
    value_type=types.float32
)


value = types.float32(np.random.rand()) 
value_type = nb.typeof(value)
print("value is %f, according to numba.typeof type is %s "%(value,value_type))

dict[0] = value
print("I assign value to dict[0]")
print("If I use formatted print value of dict[0] is %lf"%dict[0])
print("If I use plain print value with no formatting dict[0] is ", end ='')
print(dict[0])
print("According to numba.typeof type of dict[0] is %s" %nb.typeof(dict[0]))
```

**Comment by sklam** [comment]
RE: https://github.com/numba/numba/issues/5594#issuecomment-617046344

@oiluigio, yes, it's mostly a matter of formatting and the change of type (float32 being returned as float64) is a quirk with Numba that will not result in a loss of precision.

When I run your script, I got:

```python
value is 0.876713, according to numba.typeof type is float32
I assign value to dict[0]
If I use formatted print value of dict[0] is 0.876713
If I use plain print value with no formatting dict[0] is 0.8767133951187134
According to numba.typeof type of dict[0] is float64

In [2]: str(0.876713)
Out[2]: '0.876713'

In [3]: print(0.876713)
0.876713

# Formatting for float32
In [4]: str(np.float32(0.876713))
Out[4]: '0.876713'

# Formatting for float64
In [5]: str(np.float64(np.float32(0.876713)))
Out[5]: '0.8767129778862'

# Values are equal?
In [6]: np.float64(np.float32(0.876713)) == np.float32(0.876713)
Out[6]: True
```
