### ISSUE TITLE
ImportError: Numba could not be imported

### ISSUE THREAD

**Issue by aloboa** [numba/numba#5600]
After installing numba on Win7, the test does not work:
```
C:\Windows\System32>python3 -m numba -s
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\core\typeco
nv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\runpy.py", line 183, in _run_mo
dule_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\runpy.py", line 142, in _get_mo
dule_details
    return _get_module_details(pkg_main_name, error)
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\runpy.py", line 109, in _get_mo
dule_details
    __import__(pkg_name)
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\__init__.py
", line 20, in <module>
    from numba.misc.special import (
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\misc\specia
l.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\core\typing
\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\core\typing
\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\core\typeco
nv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\numba\core\typeco
nv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you m
ay need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-d
oc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: No se puede encontrar el módulo especi
ficado.'
--------------------------------------------------------------------------------

If possible please include the following in your error report:

sys.executable: C:\PROGRA~1\QGIS3~1.12\bin\python3.exe


C:\Windows\System32>
```

**Comment by aloboa** [comment]
This problem does not occur wit numb 0.47.0

**Comment by sklam** [comment]
Can you tell us how you installed numba? e.g. conda, pip, or manually?

**Comment by aloboa** [comment]
Using python3 and pip:
`python -m install numba`
Then
```
python -m pip uninstall numba
python -m pip install numba==0.47.0
```

and worked.

**Comment by sklam** [comment]
I cannot replicate the problem. I will need more info.

- What is your OS version?  32-bit or 64-bit?
- Did you install Python via Anaconda/Miniconda? If so, can you install numba on a fresh environment?

**Comment by misantroop** [comment]
Exactly same issue starting with 0.49. 0.48 works fine.
Win 10 64bit, Python 3.8.2, installing with pip install --force-reinstall numba --user.

**Comment by aloboa** [comment]
@sklam Cannot install on a fresh environment. 
These are the details of my environment:
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32 installed through OSgeo4W on Win7 

Nombre del sistema operativo:              Microsoft Windows 7 Professional
Versión del sistema operativo:             6.1.7601 Service Pack 1 Compilación 7601
Fabricante del sistema operativo:          Microsoft Corporation
Fabricante del sistema:                    LENOVO
Modelo el sistema:                         4291B66
Tipo de sistema:                           x64-based PC
Procesador(es):                            1 Procesadores instalados.
                                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~1975 Mhz

Please check
https://bitbucket.org/hu-geomatics/enmap-box/issues/405/import-numba-crashes-qgis-on-linux
(same problem reported on linux)

**Comment by cmartinezdem** [comment]
Same issue over here.

It works correctly in a computer with Windows 10 Home (64 bits), but it fails in another computer with Windows 10 Pro (64 bits). Both tests have been done with Python 3.8.2 and Numba has been installed from pip.

**Comment by stuartarchibald** [comment]
Could all those reporting problems with Numba installs for 0.49 please run `numba -s`, edit out any bits you don't want to share, and then post the rest here? Many thanks in advance.

Hopefully there'll be some identifiable pattern!

**Comment by jjhelmus** [comment]
The `_typeconv.cp37-win_amd64.pyd` file in the numba 0.49.0 wheel imports from `VCRUNTIME140_1.dll`.  The 0.48.0 file did not import from this DLL.  

It is possible that this DLL is not present on all Windows systems.  

My guess is that this is a result of switching from VS 2015 to VS 2017.


```
$ # numba 0.49.0
$ python -c "import lief; b = lief.parse('_typeconv.cp37-win_amd64.pyd'); [print(i.name) for i in b.imports]"
MSVCP140.dll
python37.dll
KERNEL32.dll
VCRUNTIME140_1.dll
VCRUNTIME140.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
$ # numba 0.48.0
$ python -c "import lief; b = lief.parse('_typeconv.cp37-win_amd64.pyd'); [print(i.name) for i in b.imports]"
MSVCP140.dll
python37.dll
KERNEL32.dll
VCRUNTIME140.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
```

**Comment by jjhelmus** [comment]
For those running into this issue, does installing the latest [Visual Studio Redistributable from Microsoft ](https://aka.ms/vs/16/release/vc_redist.x86.exe) resolve the issue?

**Comment by sklam** [comment]
We updated the compiled since we supported py3.8. It's odd that this issue shows up only in this release and not in 0.47, which is first to support py3.8

**Comment by sklam** [comment]
Oh, I know why. It's because I updated the buildfarm to VS2019 with a VC14.2 compiler to build LLVM9.

**Comment by misantroop** [comment]
> 
> 
> For those running into this issue, does installing the latest [Visual Studio Redistributable from Microsoft ](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) resolve the issue?

This solved it for me.

**Comment by cmartinezdem** [comment]
> 
> 
> For those running into this issue, does installing the latest [Visual Studio Redistributable from Microsoft ](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) resolve the issue?

This solved it for me too.

**Comment by xiaosujie** [comment]
> Could all those reporting problems with Numba installs for 0.49 please downgrade to 0.48, run `numba -s`, edit out any bits you don't want to share, and then post the rest here? Many thanks in advance.
> 
> Hopefully there'll be some identifiable pattern!

yes, 0.48 is ok

**Comment by esc** [comment]
I have update the labels to reflect the recent discoveries regarding this issue.

**Comment by sklam** [comment]
For those having on windows with numba0.49.0, please try 0.49.1rc1 wheels from https://pypi.org/project/numba/0.49.1rc1/

**Comment by stuartarchibald** [comment]
Closing this, resolved in 0.49.1. Thanks for the input all.

**Comment by zabbix-byte** [comment]
> ```
> python -m pip install numba==0.47.0
> ```
Why i have this error ? 

![image](https://user-images.githubusercontent.com/67012651/100548343-3ca16900-326c-11eb-8ed5-405f4385cc14.png)
wen i install numba

**Comment by esc** [comment]
@zabbix-byte thank you for adding to this issue. I see you have also opened https://github.com/numba/llvmlite/issues/657 -- is the issue you report above related.
