### ISSUE TITLE
Error in py_module_import(module, convert = convert) :    ImportError: Numba could not be imported.

### ISSUE THREAD

**Issue by qianxu05172019** [numba/numba#5604]
Hi,
I am trying to use reticulate to import a python package scanpy. Here is the R script I use: 

library(reticulate)
reticulate::use_condaenv('r-reticulate')
scanpy <- reticulate::import('scanpy')

The error massage I met is as follows:
Error in py_module_import(module, convert = convert) : 
  ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Program Files\RStudio\bin\rsession.exe

Thanks in advance for any help!

**Comment by sklam** [comment]
Can you tell us how you installed numba?

**Comment by qianxu05172019** [comment]
> Can you tell us how you installed numba?

I use pip install numba and I got this message:

Requirement already satisfied: numba in c:\users\qianxu~1\appdata\local\r-mini~1\envs\r-reticulate\lib\site-packages (0.49.0)                                                                                                                Requirement already satisfied: llvmlite<=0.33.0.dev0,>=0.31.0.dev0 in c:\users\qianxu~1\appdata\local\r-mini~1\envs\r-reticulate\lib\site-packages (from numba) (0.32.0)                                                                     Requirement already satisfied: numpy>=1.15 in c:\users\qianxu~1\appdata\local\r-mini~1\envs\r-reticulate\lib\site-packages (from numba) (1.18.1)                                                                                             Requirement already satisfied: setuptools in c:\users\qianxu~1\appdata\local\r-mini~1\envs\r-reticulate\lib\site-packages (from numba) (45.2.0.post20200210)

**Comment by sklam** [comment]
I have yet to replicate the problem. I doubt it is just an issue with the wheel we have. 

Did you upgrade numba from an older version?
Are you able to install numba into a fresh environment (i.e. conda env or virtualenv)?

**Comment by sklam** [comment]
This might be related to https://github.com/numba/numba/issues/5600

**Comment by qianxu05172019** [comment]
Thanks! I use:

python -m pip install numba==0.46.0 

and it worked!

**Comment by sklam** [comment]
0.46.0 is an old version from Oct 2019. 

There may still be an actual problem for installing via pip in 0.49.
