### ISSUE TITLE
`np.floor_divide` does not match numpy for divide by zero with floats

### ISSUE THREAD

**Issue by eriknw** [numba/numba#5613]
When numpy divides a positive value by zero as floating point, it returns `nan`.  numba returns `inf`.  Observe:
```python
Python 3.7.7 (default, Mar 26 2020, 10:32:53)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.18.1'

>>> import numba
>>> numba.__version__
'0.49.0'

>>> @numba.njit
... def floordiv(x, y):
...     return np.floor_divide(x, y)
...
>>> floordiv(1.0, 0.0)
inf

>>> np.floor_divide(1.0, 0.0)
nan

>>> a = np.ones(2, dtype='float64')
>>> floordiv(a, 0*a)
array([inf, inf])

>>> np.floor_divide(a, 0*a)
array([nan, nan])
```
I don't know why numpy behaves this way.

**Comment by sklam** [comment]
why doesn't floor_divide follow divide?!

```

**Comment by sklam** [comment]
I'll say that's numpy's problem.

```python
>>> np.floor(np.divide(1., 0.))
inf
>>> np.floor_divide(1., 0.)
nan
```
Numpy doc say:

> y = floor(x1/x2) This is a scalar if both x1 and x2 are scalars.

(https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor_divide.html)

**Comment by sklam** [comment]
Related Numpy issue: https://github.com/numpy/numpy/issues/7709

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
