### ISSUE TITLE
Cannot unify array vstack

### ISSUE THREAD

**Issue by AashinShazar** [numba/numba#5637]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When I try performing vstack as seen below, I get the following error:

> Cannot unify array(float64, 1d, C) and array(float64, 2d, C) for 'cx'

```
from numba import njit
import numpy as np
@njit(parallel=True)
def stacker():
    order = 6
    st = 100
    en = 150
    xval = np.random.rand(15360,192)
    for i in range(0, 1024):
            cx = xval[i, st:en]
            
            for dt in range (1, order+1):
                cx = np.vstack((cx, xval[i,st-dt:en-dt])) 
```

Now I've read some other issues regarding nested loops and variable reassignment, and I believe the error has to do with cx being reassigned a new value? How can I go about resolving this?

**Comment by esc** [comment]
@AashinShazar thanks for reporting this on the Numba issue tracker. I attempted to run your reproducer locally, but it seems the variable `order` isn't defined anywhere. Perhaps, if could, please post an updated reproducer to fix this? Also note that, the reproducer is missing the appropriate import statements, in this case:

```
from numba import njit
import numba as np
```

It would be good if you could add those too, as this will make it more convenient for reviewers to checkout your issue and run code locally. Many thanks in advance for your cooperation!

**Comment by AashinShazar** [comment]
> @AashinShazar thanks for reporting this on the Numba issue tracker. I attempted to run your reproducer locally, but it seems the variable `order` isn't defined anywhere. Perhaps, if could, please post an updated reproducer to fix this? Also note that, the reproducer is missing the appropriate import statements, in this case:
> 
> ```
> from numba import njit
> import numba as np
> ```
> 
> It would be good if you could add those too, as this will make it more convenient for reviewers to checkout your issue and run code locally. Many thanks in advance for your cooperation!

My apologies! I've updated the code above.

**Comment by esc** [comment]
@AashinShazar thank for updating the example above. I'm afraid I am unable to reproduce the error using the code provided. I also tried to change the `range` statements to `prange` but that was also successful. I modified the code a little to comply with coding standards and am posting the exact version I used here:

```
from numba import njit, prange
import numpy as np


@njit(parallel=True)
def stacker():
    order = 6
    st = 100
    en = 150
    xval = np.random.rand(15360,192)
    for i in prange(0, 1024):
        cx = xval[i, st:en]
        for dt in prange(1, order + 1):
            cx = np.vstack((cx, xval[i,st - dt:en - dt]))
```

**Comment by esc** [comment]
@AashinShazar perhaps if you could provide more information about your operating system and Python and Numba versions?

**Comment by stuartarchibald** [comment]
I get:
```python
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float64, 1d, C) and array(float64, 2d, C) for 'cx.2', defined at issue5437_2.py (13)

File "issue5437_2.py", line 13:
def stacker():
    <source elided>
        cx = xval[i, st:en]
        for dt in prange(1, order + 1):
        ^

[1] During: typing of assignment at issue5437_2.py (13)

File "issue5437_2.py", line 13:
def stacker():
    <source elided>
        cx = xval[i, st:en]
        for dt in prange(1, order + 1):
        ^
```
on master.

I think the problem is because `cx = xval[i, st:en]` is a 1d array, then, in the loop:
```python
        for dt in prange(1, order + 1):
            cx = np.vstack((cx, xval[i,st - dt:en - dt]))
```
`cx` becomes a 2D array by virtue of the `vstack`. However, Numba has to compile the code based on statical analysis and its analysis algorithms cannot tell if that loop will execute, if it does, `cx` might be 1d or 2d, and hence the problem.

**Comment by esc** [comment]
Oh, my bad, I missed the lack of a function execution `stacker()` at the end of the file. I can confirm I now get this error too.

**Comment by AashinShazar** [comment]
> I get:
> 
> ```python
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Cannot unify array(float64, 1d, C) and array(float64, 2d, C) for 'cx.2', defined at issue5437_2.py (13)
> 
> File "issue5437_2.py", line 13:
> def stacker():
>     <source elided>
>         cx = xval[i, st:en]
>         for dt in prange(1, order + 1):
>         ^
> 
> [1] During: typing of assignment at issue5437_2.py (13)
> 
> File "issue5437_2.py", line 13:
> def stacker():
>     <source elided>
>         cx = xval[i, st:en]
>         for dt in prange(1, order + 1):
>         ^
> ```
> 
> on master.
> 
> I think the problem is because `cx = xval[i, st:en]` is a 1d array, then, in the loop:
> 
> ```python
>         for dt in prange(1, order + 1):
>             cx = np.vstack((cx, xval[i,st - dt:en - dt]))
> ```
> 
> `cx` becomes a 2D array by virtue of the `vstack`. However, Numba has to compile the code based on statical analysis and its analysis algorithms cannot tell if that loop will execute, if it does, `cx` might be 1d or 2d, and hence the problem.

Yeah, that's exactly the problem I'm experiencing. How would I go about resolving this?

**Comment by stuartarchibald** [comment]
You'll probably need to create a buffer and just write the slices into it opposed to `vstack`ing them up. Further, this would likely work in a `prange` loop whereas the algorithm in the current code has a loop carried dependency on `cx` which would prevent parallelisation.

**Comment by AashinShazar** [comment]
How would I go about creating a buffer for this? I can't use regular lists to create a buffer and all errors indicate I need a tuple but I can't convert a list to a tuple either.

**Comment by stuartarchibald** [comment]
> How would I go about creating a buffer for this? I can't use regular lists to create a buffer and all errors indicate I need a tuple but I can't convert a list to a tuple either.

How about creating an array that's the correct size to hold the "stacked" output and just writing into that based on the loop index?

**Comment by AashinShazar** [comment]
> > How would I go about creating a buffer for this? I can't use regular lists to create a buffer and all errors indicate I need a tuple but I can't convert a list to a tuple either.
> 
> How about creating an array that's the correct size to hold the "stacked" output and just writing into that based on the loop index?

Thank you! That gave me the direction I needed to solve this.

**Comment by stuartarchibald** [comment]
> > > How would I go about creating a buffer for this? I can't use regular lists to create a buffer and all errors indicate I need a tuple but I can't convert a list to a tuple either.
> > 
> > 
> > How about creating an array that's the correct size to hold the "stacked" output and just writing into that based on the loop index?
> 
> Thank you! That gave me the direction I needed to solve this.

No problem, glad you got something working.
