### ISSUE TITLE
Could numba support big integers for a * b?

### ISSUE THREAD

**Issue by atcherkasov** [numba/numba#5642]
Hello. I , I try to use numba to parallelize a function that takes 2 arrays and returns their multiplication (`res [i] = a [i] * b [i]`). However, the problem is that the values ​​of a and b are greater than int64. 
So the problem is that if i try to run the following code:
```
from numba import guvectorize, int64

@guvectorize([(int64[:], int64[:], int64[:])], '(n), (n)->(n)', target='cuda')
def multiplication(a , b, res):
    for i in range(len(a)):
      res[i] = a[i] * b[i]

N = 10
a = [10**N]
b = [10**N]
res = [0]

size = 10 ** 3
A = [a] * size
B = [b] * size
Res = [res] * size
multiplication(A, B, Res)
```
I'll get the incorrect results because of overflowing: `Res[0][i] == 7766279631452241920` of course it's less than `10**20`
I read [issues](https://github.com/numba/numba/issues/4877#issuecomment-556994798) in github saying that large int64 numbers are not used because it is part of the relationship with NumPy, however in NumPy I can do this calculation:
```
import numpy as np
a = np.array([10** 20])
b = np.array([10** 20])
a * b
>>> array([10000000000000000000000000000000000000000], dtype=object)
```
So NumPy casts it to  type "object". While in numba I did not find analogues of "object". 
Is it possible to calculate first example of code with out  overflowing?
## If it's not possible please advise me to get out of this situation in another way)

**Comment by seibert** [comment]
Numba does not have support for big integers, and using Python objects (in this case, Python's integer objects support arbitrary size integers) in nopython mode also is not supported.

Unfortunately, I'm not aware of a workaround for this.  I see you are trying to run on the GPU, which adds additional constraints.

**Comment by stuartarchibald** [comment]
xref https://github.com/numba/numba/issues/5005, duplicate, closing.
