### ISSUE TITLE
Numba njit restarts my IPython kernel

### ISSUE THREAD

**Issue by MislavSag** [numba/numba#5646]
I use python 3.7, VScode, Windows 10.

This simple numba function:
```
@njit
def enter_positions(sides):
    for i in range(sides.shape[0]):
        if (i > 0):
            if (sides[i-1, 1] == -1) | (sides[i, 1] == -1.0):
                sides[i, i] = -1
            else: 
                sides[i, i] = 1
        elif np.isnan(positions[i, 0]):
            sides[i, 0] = 1
        else:
            sides[i, 0] = -1
    return sides
```
restarts my IPython kernel in VSCode.

**Comment by gmarkall** [comment]
Is it possible that you're accessing out of bounds and crashing the interpreter? Can you post a complete executable reproducer?

**Comment by gmarkall** [comment]
Also, if you remove `@njit`, does the function execute as you expect?

**Comment by MislavSag** [comment]
You are right. There was an error if without @njit. Sorry. But didn't know it restarts session if there is an error :)

**Comment by esc** [comment]
@MislavSag thanks for asking about this and @gmarkall thanks for debugging. I am closing this now as I am assuming it is resolved. Please do re-open and add more information if this is not the case. Thanks!
