### ISSUE TITLE
  Unexpected behavior taking the minimum of an array of `np.inf` when `parallel=True`.

### ISSUE THREAD

**Issue by mbattifarano** [numba/numba#5662]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When using `np.min` on an array with all infinite values, I expect `np.inf` to be returned. This happens correctly when the function is compiled in nopython mode. When `parallel=True` however, the minimum is returned as the largest `float64` value  

In the code snippet below the first two assertion pass on my machine but the third fails.

```python
import numba
import numpy as np

@numba.njit()
def min(a):
    return a.min()

@numba.njit(parallel=True)
def pmin(a):
    return a.min()

infs = np.array([np.inf, np.inf])

assert min(infs) == np.inf
assert pmin(infs) == np.finfo(np.float64).max
assert min(infs) == pmin(infs)
```

**Comment by esc** [comment]
@mbattifarano thanks for reporting this, I can reproduce this on the current master `0.50.0dev0-179-g86e600d0ec` and this might be a bug related to the parallel accelerator. @DrTodd13 could you have a look?

**Comment by stuartarchibald** [comment]
It's a simple impl bug:
https://github.com/numba/numba/blob/86e600d0ec867402cb4f41100295878586f2a019/numba/parfors/parfor.py#L123-L145

**Comment by esc** [comment]
@stuartarchibald how about we initialize `val` then to `inf` in the `float` case? What about the `max` impl.?

**Comment by DrTodd13** [comment]
@esc @stuartarchibald It seems like initializing val to inf for float should work.  Can you try that Val?
