### ISSUE TITLE
Cythonizing a module containing numba functions

### ISSUE THREAD

**Issue by cmartinezdem** [numba/numba#5664]
Hello,

I am trying to cythonize a module which contains numba functions and I am getting an Exception when trying to use such functions. Is there a way to cythonize a module containing njitted functions? 

Thank you!

**Comment by cmartinezdem** [comment]
After checking Numba documentation, I have come up with a solution. I can use Ahead-Of-Time compilation so as to generate a .pyd extension of my .py module containing Numba functions. However, the documentation says nothing about the 'fastmath' flag when carrying out AOT compilation. Is there a way to enable fast match capabilities?

Thank you so much.

**Comment by esc** [comment]
@cmartinezdem thanks for asking about this on the Numba issue tracker. Since this is a fairly exotic request, could you perhaps submit a small example of how you want to combine Numba and Cython?

**Comment by cmartinezdem** [comment]
I have several .py modules with some njitted functions. For instance, my .py modules could be as the following one:

```
import numpy as np
import numba as nb

@nb.njit
def foo(a, b):
    return a**b
```

Everything works fine but I need to cythonize the module, generating a .pyd file in Windows (.so in Linux) and generate a wheel so as to distribute it, and Numba seems not to work when the .py module is cythonized.

**Comment by cmartinezdem** [comment]
After trying AOT compilation using a setup.py file, I am getting the following error in the linker:

> modulemixin.obj : error LNK2001: unresolved external symbol nrt_atomic_sub
> modulemixin.obj : error LNK2001: unresolved external symbol nrt_atomic_add

This is my setup.py file:

```
from setuptools import setup
from utils import cc as utils_cc

setup(
    ext_modules=[utils_cc.distutils_extension()],
)
```

However, if I manually compile the code using iPython, it works:

```
from utils import cc as utils_cc
utils_cc.compile()
```

**Comment by esc** [comment]
@cmartinezdem thanks for updating this issue! I not sure how to help in this case so I have a suggestion: perhaps it would make sense to setup something like a demo repository to showcase Numba and Cython interoperability? This would include a `setup.py` file and a few demo files to quickly get the use case you are describing going. Does that  sound like something you  might be able to set up?

**Comment by cmartinezdem** [comment]
Hi @esc. Thank you for your support.

The best way to fix this is to use AOT compilation, so all Numba related functions get compiled into a .pyd library (exactly the same that Cython does).

I have managed to make it work with the following setup.py:

```
from setuptools import setup  # To setup package

from source_module import cc


setup(
    ext_modules=[cc.distutils_extension()]
)
```

where 'source_module' is the python module containing my Numba functions. All Numba functions need to be decorated with '@cc.export'.

The only drawback I have found (for now) is that @njit flags, such as 'fastmath' or 'parallel' cannot be used.

**Comment by cmartinezdem** [comment]
> 
> 
> After trying AOT compilation using a setup.py file, I am getting the following error in the linker:
> 
> > modulemixin.obj : error LNK2001: unresolved external symbol nrt_atomic_sub
> > modulemixin.obj : error LNK2001: unresolved external symbol nrt_atomic_add
> 
> This is my setup.py file:
> 
> ```
> from setuptools import setup
> from utils import cc as utils_cc
> 
> setup(
>     ext_modules=[utils_cc.distutils_extension()],
> )
> ```
> 
> However, if I manually compile the code using iPython, it works:
> 
> ```
> from utils import cc as utils_cc
> utils_cc.compile()
> ```
> 
> I am running Windows 10 with Python 3.8.2 (64 bits).

This was happening because I was using a complex setup.py which was preventing Numba from applying monkey patching to `distutils.build_ext`

**Comment by cmartinezdem** [comment]
Adding the possibility of using `@njit` flags in `@cc.export` would be great! Is it possible?

**Comment by cmartinezdem** [comment]
I have managed to add the 'fastmath' flag to the `ExportEntry` object:

```
class ExportEntry(object):
    """
    A simple record for exporting symbols.
    """

    def __init__(self, symbol, signature, function, fastmath=False):
        self.symbol = symbol
        self.signature = signature
        self.function = function
        self.fastmath = fastmath
```

Then, the `_cull_exports` methodof the `_ModuleCompiler` object shall me modified with the following code:

```
for entry in self.export_entries:
            flags_aux = flags.copy()
            if entry.fastmath:
                flags_aux.set('fastmath', value=cpu.FastMathOptions(True))

            cres = compile_extra(self.typing_context, self.context,
                                 entry.function,
                                 entry.signature.args,
                                 entry.signature.return_type, flags_aux,
                                 locals={}, library=library)
```

And it is working for me right now. I guess this code may be improved, but this simple patch works, so I would expect that 'fastmath' and 'parallel' flags could be added to `@cc.export` in an "official" way.

**Comment by esc** [comment]
@cmartinezdem how would you like to proceed with this issue. Do you want to open (or convert this into) a feature request?

**Comment by gmarkall** [comment]
New feature request #7179 created. Closing this issue as the original issue appears to be resolved.
