### ISSUE TITLE
No error for jit(nopython=True, forceobj=True)

### ISSUE THREAD

**Issue by HPLegion** [numba/numba#5665]
- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When using the `jit` decorator with both `nopython=True` and `forceobj=True` no error is reported, despite these flags probably being mutually exclusive.
```python
import numba

@numba.jit(nopython=True, forceobj=True)
def f():
    pass

f()
```
The prior example runs without complaints. If the `njit` decorator is used instead, appropriate warnings are thrown.

**Comment by stuartarchibald** [comment]
Thanks for the report. From https://gitter.im/numba/numba?at=5eafceefb6dd230697a45990. Think this will just permit the objmode pipeline to run.

**Comment by HPLegion** [comment]
@stuartarchibald I just noticed that `njit` throws warnings that it will ignore `nopython` and `forceobj` but `forceobj` is actually passed on to `jit`. In combination with the behaviour above, that means that `njit(forceobj=True)` actually compiles in object mode (this might be convenient for in some cases, but somewhat contradicts the idea of njit). 

Do you think it would be appropriate to eliminate `forceobj` if it is passed to `njit`, and add a check to `jit` that raises an error if both options are passed as True?

If yes, then I am happy to use this as pull request training :)
