### ISSUE TITLE
All example code fails in the 5 minute guide to Numba

### ISSUE THREAD

**Issue by Shellcat-Zero** [numba/numba#5668]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I've just installed numba to start working with it, but the code examples in your [5 Minute Guide](https://numba.pydata.org/numba-doc/latest/user/5minguide.html) are failing.

Example 1:
```python
from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))
```
Error 1:
```python
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$56binary_add.2', defined at <ipython-input-1-1606668fbe19> (11)

File "<ipython-input-1-1606668fbe19>", line 11:
def go_fast(a): # Function is compiled to machine code when called the first time
    <source elided>
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting
    ^

[1] During: typing of intrinsic-call at <ipython-input-1-1606668fbe19> (11)

File "<ipython-input-1-1606668fbe19>", line 11:
def go_fast(a): # Function is compiled to machine code when called the first time
    <source elided>
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting
```
Example 2:
```python
from numba import jit
import numpy as np
import time

x = np.arange(100).reshape(10, 10)

@jit(nopython=True)
def go_fast(a): # Function is compiled and runs in machine code
    trace = 0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (with compilation) = %s" % (end - start))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))
```
Error 2:
```python
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$56binary_add.2', defined at <ipython-input-2-4b4887488317> (12)

File "<ipython-input-2-4b4887488317>", line 12:
def go_fast(a): # Function is compiled and runs in machine code
    <source elided>
        trace += np.tanh(a[i, i])
    return a + trace
    ^

[1] During: typing of intrinsic-call at <ipython-input-2-4b4887488317> (12)

File "<ipython-input-2-4b4887488317>", line 12:
def go_fast(a): # Function is compiled and runs in machine code
    <source elided>
        trace += np.tanh(a[i, i])
    return a + trace
```

OS: Ubuntu 18.04
Python: 3.7.7
GPU: Nvidia GeForce GTX 960
Cuda: 10.2 (Do I need a version < 10.14, and if so where do I find that?)
CPU: Xeon X5690
Numba: 0.49.0 and 0.50.0 (dev) versions attempted

The examples provided by the CUDA drivers do in fact run successfully.

**Comment by HPLegion** [comment]
I can replicate these errors (also using 0.49)

There is no problem if x is initialised as an array of floats though. Seems something is going awry when using arrays with different dtypes

**Comment by stuartarchibald** [comment]
Thanks for the report. This is because Numba 0.49 finally went to full SSA form and as a result stronger type stability requirements were enforced, see also https://github.com/numba/numba/issues/5501 for a more full explanation. #5669 fixes.

**Comment by Shellcat-Zero** [comment]
Thanks, I was able to get them working with the new details in #5669.  I might also recommend highlighting this type stability requirement more strongly in the documentation or modifying the TypeError to make it more obvious in the error output.  I suspect you will be getting many more bug reports regarding "Cannot unify array" where this user error has occurred.

Unless it has already been addressed, I also suspect this error has also not yet been corrected in your `examples` and `tutorials` sections, both in the repo and on your http://numba.pydata.org/ page. I'm just bringing these points up because it is (and will be) painful for new users to Numba like myself, who're trying to get going with Numba and evaluate it for their purposes.

**Comment by stuartarchibald** [comment]
Thanks, dealing with type stability is something we're thinking about more, it's a challenging problem. There's information on `TypingError`s for type unification problems here: http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem (could probably do with some info on type stability of loops), also note, these are not `TypeError`'s but `TypingError`s, they come from Numba's type inference mechanism. Examples got fixed here: https://github.com/numba/numba-examples/pull/16/files if you find any more please feel free to open issues. Thanks again!
