### ISSUE TITLE
Need a way to construct a string from bytes or decode bytes to string in nopython mode

### ISSUE THREAD

**Issue by pragmasoft-ua** [numba/numba#5672]
## Feature request

I need a support of string arrays in nopython mode so I decided to use apache arrow for this. In arrow string arrays are represented with three buffers: nullable bitmask, data and offsets. Whereas I can get an array item as bytes slice or numpy u8 array, I currently see no way to construct a string from it.

Ideally it would be to have a native support of arrow arrays, but this is likely another feature request

**Comment by stuartarchibald** [comment]
Thanks for the report. `ord` and `chr` are supported, so as a very cheap to try conversion method this might work?

```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return ''.join([chr(z) for z in x])

x = np.arange(ord('a'), ord('f'), dtype=np.uint8)
print(foo(x))
```

Short of that, it's relatively easy to build strings, have a look in:https://github.com/numba/numba/blob/master/numba/cpython/unicode.py

**Comment by pragmasoft-ua** [comment]
Unfortunately ord seems does not work, I got a following error:

> Untyped global name 'ord': cannot determine Numba type of <class 'builtin_function_or_method'>

`@nb.njit(nb.types.u4(nb.types.string, nb.types.u4))
def base_n(s: str, base: int = 10) -> int:
    '''
    Converts string to an int with a specified base (base is 10 if not provided), e.g.
    base_n('100') == 100
    base_n('f', 16) = 15
    '''
    multiplier: int = 1
    result: int = 0
    pos = len(s) - 1
    while pos >= 0:
        c = s[pos]
        lc = c.lower()
        if '0' <= lc <= '9':
            origin = ord('0') 
        elif 'a' <= lc <= 'z':
            origin = ord('a') - 10 
        else:
            raise ValueError('Unsupported character, must be [0-9][a-z]')
        code = ord(lc) - origin
        result += code * multiplier
        multiplier *= base
        pos -= 1
    return result
`

**Comment by stuartarchibald** [comment]
Your sample compiles fine for me on Numba version 0.49, which version are you using? `ord` supported was added in 0.49: https://github.com/numba/numba/blob/master/CHANGE_LOG#L158

**Comment by pragmasoft-ua** [comment]
Indeed, I had 0.48, sorry, now it works as expected

**Comment by stuartarchibald** [comment]
Great, thanks for confirming. Closing this as resolved.
