### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'core'

### ISSUE THREAD

**Issue by shahkirill** [numba/numba#5675]
numba 0.49.0

import numba
Traceback (most recent call last):

  File "<ipython-input-21-68d4f1bcefa7>", line 1, in <module>
    import numba

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\__init__.py", line 17, in <module>
    from numba.core import types, errors

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\core\types\__init__.py", line 8, in <module>
    from .functions import *

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\core\types\functions.py", line 9, in <module>
    _termcolor = errors.termcolor()

  File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\numba\core\errors.py", line 291, in termcolor
    scheme = themes[numba.core.config.COLOR_SCHEME]

AttributeError: module 'numba' has no attribute 'core'

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information:

* How did you install Numba?
* What you were doing to trigger this problem?
* Does this happen all the time?
* Does this happen in a new environment?

Thanks for your help.

**Comment by shahkirill** [comment]
- I tried both  conda update numba and  pip install numba 
- I tried to make quantecon-0.4.7 to work. when I was importing quantecon I got an error
File "C:\Users\ks0063\AppData\Local\Continuum\anaconda3\lib\site-packages\quantecon\util\numba.py", line 15, in
types.float32: 's',
AttributeError: module 'numba.types' has no attribute 'float32'

python 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)]
quantecon-0.4.7
numba-0.49.0

**Comment by stuartarchibald** [comment]
@shahkirill please could you try the recently released Numba 0.49.1, it's available as described here: https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/DqSatiOo3ks and would likely fix the problem described. Thanks.

**Comment by drsxr** [comment]
I am getting a similar error with Numba 0.49.1 under python version 3.6.9
I'm trying to install umap-learn in a NGC docker container which uses conda.
Get this:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-a0612868ce68> in <module>
----> 1 import numba
      2 import umap

/opt/conda/lib/python3.6/site-packages/numba/__init__.py in <module>
     27 
     28 # Re-export types itself
---> 29 import numba.core.types as types
     30 
     31 # Re-export all type names

AttributeError: module 'numba' has no attribute 'core'`

tried to install numba separately with 
`pip install numba
 conda update numba`
no effect.

**Comment by esc** [comment]
For anyone who is still experiencing this, you may want to try setting up your environment from scratch and installing the most recent version of Numba directly i.e. without updating. Current evidence in https://github.com/numba/numba/issues/5677 seems to point towards the idea that this issue may be introduced locally during the update process for some people.

**Comment by Eddieliu0514** [comment]
Same issue here. Tried 0.49.0 and 0.48.0. Both have same issue. I created separated environment yet  there is problem.

**Comment by esc** [comment]
@Eddieliu0514 thanks for reporting back about this. The module `numba.core` is definitely there: https://github.com/numba/numba/tree/master/numba/core -- so maybe you could submit the piece of code you are using that has this error. Perhaps that will allow us to move forward on this issue?

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
