### ISSUE TITLE
umap import failure

### ISSUE THREAD

**Issue by camneese** [numba/numba#5677]
I was trying to import umap into jupyter notebooks, but kept getting an error message saying numba couldn't be imported as part of the process.

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\CodingLanguages\Anaconda\python.exe

**Comment by sklam** [comment]
If you are using numba=0.49. It could be related to #5600. Please try to use the 0.49.1rc1 wheel.

**Comment by camneese** [comment]
Thank you, that seemed to clear up the big issue! It's still throwing me one error, is this package not included in this wheel? Any way to get around it?

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-28-623e299b05c0> in <module>
----> 1 import umap

~\AppData\Roaming\Python\Python37\site-packages\umap\__init__.py in <module>
----> 1 from .umap_ import UMAP
      2 
      3 # Workaround: https://github.com/numba/numba/issues/3341
      4 import numba
      5 

~\AppData\Roaming\Python\Python37\site-packages\umap\umap_.py in <module>
     24 import scipy.sparse
     25 import scipy.sparse.csgraph
---> 26 import numba
     27 
     28 import umap.distances as dist

C:\CodingLanguages\Anaconda\lib\site-packages\numba\__init__.py in <module>
     18 
     19 # Re-export typeof
---> 20 from numba.misc.special import (
     21     typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init,
     22     literally, literal_unroll

ModuleNotFoundError: No module named 'numba.misc.special'

**Comment by stuartarchibald** [comment]
@camneese which version of Numba do you have? It looks like the environment might be a bit confused?

**Comment by stuartarchibald** [comment]
This is strangely similar to https://github.com/numba/numba/issues/5675

**Comment by stuartarchibald** [comment]
Just pip installed `umap-learn==0.4.2` on a windows machine with Python 3.7, cannot reproduce the above.

**Comment by stuartarchibald** [comment]
@camneese do you have a method of reproducing this please?

**Comment by camneese** [comment]
Sorry, just saw this! I tried again a few days later and it went through without an error. I didn't do anything different; I'm still using numba=0.49.1rc1. Still not sure what caused it, but it very well may have just been a confused environment. Thanks for the help!

**Comment by esc** [comment]
@camneese cool! Thanks for reporting back and thanks for using Numba! 🙏
