### ISSUE TITLE
bug in analysis NumbaParallelSafetyWarning

### ISSUE THREAD

**Issue by Harveyt47** [numba/numba#5678]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When I run 
```
@njit(parallel=True)
def while_for(n, max_iter=10):
    a = np.empty((n,n))
    i=0
    while i <= max_iter:
        for j in prange(len(a)):
            for k in prange(len(a)):
                a[j,k] = np.random.rand()
        i+=1
    return a
while_for(4)
```
I get the following warning 
```
Variable i.3 used in parallel loop may be written to simultaneously by multiple workers and may result in non-deterministic or unintended results. 
File "<ipython-input-44-a9dc46b8042f>", line 6: 
def while_for(n, max_iter=10): 
<source elided> 
while i <= max_iter: 
for j in prange(len(a)): ^ warnings.warn(NumbaParallelSafetyWarning(msg, loc))
```
When I replace `@njit(parallel=True)` with `@njit` it goes away.

**Comment by stuartarchibald** [comment]
Thanks for the report. As a guess, seems like that this is because `i` is a parfors var but unused in the loop nest. @DrTodd13 please could you take a look? Thanks.

**Comment by DrTodd13** [comment]
@sklam @stuartarchibald The parfor code detects races in a parallel region by looking for assignments to variables that are live-out of the region that are not reductions.  I think that SSA is doing the following with the variable i.

```
def while_for(n, max_iter=1):
    a = np.empty((n,n))
    i=0
    #i2 = i
    while i <= max_iter:
        #i3 = i2
        for j in prange(len(a)):
            #i4 = i3
            for k in range(len(a)):
                #i4 = i4
                a[j,k] = np.random.rand()
            #i3 = i4
        i+=1
        #i1 = i3 + 1
        #i2 = i1
    return a
```

So, inside the parallel region we have i.3 = i.4 and i.3 is live-out.  It doesn't seem like i.3 and i.4 are necessary for the SSA transformation.  Maybe they were just added for consistency of the SSA code.

Thus, the solution here is to not have SSA generate those variables or extend parfor race detection to trace the assignments and if it ends up being a cycle (like in this case i3 -> i4 -> i3) involving only SSA versions then it isn't a race.  In general, it seems like analysis could be easier in general if SSA had a minimization property (the only SSA versions created are actually necessary).

Thoughts?

**Comment by sklam** [comment]
Yes, I can confirm that the SSA implementation is failing on the minimization property. I think I did the iterated domfront wrong.
