### ISSUE TITLE
Support __len__ in jitclass

### ISSUE THREAD

**Issue by tony-fav** [numba/numba#5690]
## Feature request

jitclass currently seems to not see or do anything with `__len__` method. I am not sure about other magic methods, but improving this aspect would be appreciated. Example:

```
from numba import jitclass


@jitclass([])
class LenTest(object):
    def __init__(self):
        pass

    def __len__(self):
        return 1


test = LenTest()
print(len(test))
# print(test.__len__())
```
returns
`TypeError: object of type LenTest has no len()`

**Comment by GuillaumeLeclerc** [comment]
This would be great. I cam here for the same reason

**Comment by stuartarchibald** [comment]
Thanks for the request. Think this is related to https://github.com/numba/numba/issues/4002.
