### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by xrr** [numba/numba#570]
Dear all,

Here is a sample code that will raise a MemoryError after a few seconds :

``` python
import numba, numpy
def leak(x):
    @numba.jit
    def since(a):
        out = numpy.zeros(a.shape)
        last = numpy.zeros(a.shape[1])
        for i in range(a.shape[0]):
            for j in range(a.shape[1]):
                if a[i, j]: last[j] = i
                out[i, j] = i - last[j]        
        return out
    y = since(x)
data = numpy.random.randn(1e7, 2)
while True: leak(data)
```

At least on my setup :
Windows 7 64bits, Python 3.3.4 64bits (Miniconda build), Numba 0.13.2

What will fix the leakage :
- removing the jit decorator (plain python)
- moving the decorator outside of the leak function
- calling the decorated function without storing the result (remove 'y = ')

What will not :
- gc.collect() at various stages.

Best regards,

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. As of 0.44, the above marginally consumes more memory as time goes by, but that's probably expected given the use case.

It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
