### ISSUE TITLE
CUDA Matrix Multiplication Code failing with ConstantInferenceError

### ISSUE THREAD

**Issue by LKapoor1** [numba/numba#5710]
For this template MatrixMultiplication code, running the function gives ConstantInferenceError.
**_### Function Code:_**
@cuda.jit
def fast_mat_mul_kernel(a,b,out):
  blocksize = 32
  a_sub = cuda.shared.array(shape=(blocksize,blocksize),dtype=numba.float32)
  b_sub = cuda.shared.array(shape=(blocksize,blocksize),dtype=numba.float32)
  x,y = cuda.grid(2)
  tx = cuda.threadIdx.x
  ty = cuda.threadIdx.y
  num_blocks = cuda.gridDim.x
  
  if x>=out.shape[0] or y>=out.shape[1]:
    return
  
  tmp=0. 
  for i in range(num_blocks):
    a_sub[tx,ty] = a[x,ty+i*blocksize]
    b_sub[tx,ty] = b[tx+i*blocksize,y]
    cuda.syncthreads()
    for j in range(blocksize):
      tmp += a_sub[tx,j] * b_sub[j,ty]
    cuda.syncthreads()
  
  out[x,y] = tmp

### **_Input/Host Code:_**
N = 512
a = np.ones((N, 2*N), dtype=np.float32) * 2
b = np.ones((2*N, N), dtype=np.float32) * 3
#blocksize = cuda.get_current_device().WARP_SIZE
blocksize = 32
gridsize = (2*N + blocksize-1)//blocksize
block_dim = (blocksize, blocksize)
grid_dim = (gridsize, gridsize)
out = np.zeros((N, N), dtype=np.float32)
fast_mat_mul_kernel[grid_dim, block_dim](a, b, out)

### **_Error:_**
---------------------------------------------------------------------------
ConstantInferenceError                    Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numba/rewrites/macros.py in _expand_callable_macro(self, func_ir, call, macro, loc)
     98             try:
---> 99                 kws[k] = func_ir.infer_constant(v)
    100             except errors.ConstantInferenceError:

23 frames
ConstantInferenceError: Constant inference not possible for: getattr(value=$0.8, attr=float32)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numba/rewrites/macros.py in _expand_callable_macro(self, func_ir, call, macro, loc)
    102                       "constant at {loc}".format(name=k,
    103                                                  loc=loc)
--> 104                 raise ValueError(msg)
    105 
    106         try:

ValueError: Failed in nopython mode pipeline (step: nopython rewrites)
Argument 'dtype' must be a constant at <ipython-input-46-0611f0f825d9> (4)

## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by LKapoor1** [comment]
I think this is bug as I ran this template code from Numba website onto Colab GPU. Please let me know the reason behind this issue. Thanks.

**Comment by gmarkall** [comment]
Thanks for the report. Will look into this.

**Comment by LKapoor1** [comment]
Hi. I found the cause. Somehow I had imported from numba, the cuda and jit decorators but forgot to import whole numba itself. Adding it removed the issue. Sorry for the silliest issue added here.

**Comment by gmarkall** [comment]
OK - thanks for the update!
