### ISSUE TITLE
complex power fails with cuda

### ISSUE THREAD

**Issue by jorenham** [numba/numba#5727]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When I run the following code, I expect to get the output `20+2j`:

```python
@guvectorize([(complex128[:], complex128[:])], '()->()', target='cuda')
def f(val, out):
    out = val[0] ** val[0]

f(4+2j)
```

Instead, a `numba.cuda.cudadrv.driver.LinkerError` is raised with the message `Undefined reference to 'numba_cpow' in '<cudapy-ptx>'`.

**Comment by gmarkall** [comment]
I can reproduce this.

**Comment by gmarkall** [comment]
Thanks for the report! Will post updates once I've had some time to look into this.

**Comment by stuartarchibald** [comment]
Think this is a duplicate https://github.com/numba/numba/search?q=numba_cpow&type=Issues

**Comment by jorenham** [comment]
The workaround:
```python
@guvectorize([(complex128[:], complex128[:], complex128[:])], '(),()->()', target='cuda')
def f(base, exponent, out):
    r, theta = cmath.polar(base[0])
    z = exponent[0]
    out[0] = cmath.exp(math.log(r) * z + 1j * theta * z)


print((4+2j)**(3-2j), f(4+2j, 3-2j))
```
