### ISSUE TITLE
Using jitclass with types.List of array results in TypingError

### ISSUE THREAD

**Issue by spomjaksilp** [numba/numba#5730]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

# Issue
Using `jitclass()` on a class with an attribute of type `ListType[array(int64, 1d, A)]` leads to a `TypingError`. However, this type is correctly printed when calling without a decorator.

# Minimal example
```python
from numba import types, typed, typeof
from numba.experimental import jitclass
import numpy as np

spec = [
    ("b", types.ListType(types.int64[:])),
]

@jitclass(spec)
class ListAttribute:
    def __init__(self):
        self.b = typed.List.empty_list(types.int64[:])
        self.b.append(np.zeros(2, dtype=np.int64))


x = ListAttribute()
print(typeof(x.b))
```

# Trace
``` python
Traceback (most recent call last):
  File "/home/suthep/.config/JetBrains/PyCharm2020.1/scratches/scratch_1.py", line 16, in <module>
    x = ListAttribute()
  File "/home/suthep/git/uas/venv/lib/python3.8/site-packages/numba/experimental/jitclass/base.py", line 122, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/home/suthep/git/uas/venv/lib/python3.8/site-packages/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/suthep/git/uas/venv/lib/python3.8/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/suthep/git/uas/venv/lib/python3.8/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (class(int64), slice<a:b>)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at /home/suthep/.config/JetBrains/PyCharm2020.1/scratches/scratch_1.py (12)
[2] During: typing of static-get-item at /home/suthep/.config/JetBrains/PyCharm2020.1/scratches/scratch_1.py (12)

File "scratch_1.py", line 12:
    def __init__(self):
        self.b = typed.List.empty_list(types.int64[:])
        ^

[1] During: resolving callee type: jitclass.ListAttribute#7f7dfdb8b910<b:ListType[array(int64, 1d, A)]>
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: jitclass.ListAttribute#7f7dfdb8b910<b:ListType[array(int64, 1d, A)]>
[4] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>
```

# Environment:
```
python==3.8.2

attrs==19.3.0
coverage==5.1
cycler==0.10.0
decorator==4.4.2
imagecodecs==2020.2.18
imageio==2.8.0
joblib==0.14.1
kiwisolver==1.2.0
llvmlite==0.32.1
matplotlib==3.2.1
more-itertools==8.2.0
networkx==2.4
numba==0.49.1
numpy==1.18.4
packaging==20.3
Pillow==7.1.2
pluggy==0.13.1
py==1.8.1
pyparsing==2.4.7
pytest==5.4.2
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.17.2
scikit-learn==0.23.0
scipy==1.4.1
six==1.14.0
threadpoolctl==2.0.0
tifffile==2020.5.11
```

**Comment by esc** [comment]
@spomjaksilp thanks for asking about this on the Numba issue tracker. Specifying types involving jitclasses typed-lists and arrays can be a bit quirky at times. Here is a workaround that should get you what you want:

```
from numba import types, typed, typeof
from numba.experimental import jitclass
import numpy as np

array_type = types.int64[:]

spec = [
    ("b", types.ListType(array_type)),
]


@jitclass(spec)
class ListAttribute:
    def __init__(self):
        self.b = typed.List.empty_list(array_type)
        self.b.append(np.zeros(2, dtype=np.int64))


x = ListAttribute()
print(typeof(x.b))
```

**Comment by esc** [comment]
It might be worth adding this example to the documentation at:

https://numba.pydata.org/numba-doc/latest/user/jitclass.html

**Comment by stuartarchibald** [comment]
There's specific docs on typed containers here: http://numba.pydata.org/numba-doc/latest/user/jitclass.html#specifying-numba-typed-containers-as-class-members ? I'm unsure that this is really a jitclass problem, think it's more the use of the `getitem` override on the Numba type system types inside a compiled region?

**Comment by esc** [comment]
@stuartarchibald while this is true, it might be useful to have this example none the less for people to copy and paste from. I'm of no strong opinion on this though.

**Comment by spomjaksilp** [comment]
@esc thanks for the proposed solution which in fact works in my case. While I agree with @stuartarchibald that using typed containers is present in the docs, I did not find that the example

```python
from numba import jitclass, types, typed

# key and value types
kv_ty = (types.int64, types.unicode_type)

# A container class with:
# * member 'd' holding a typed dictionary of int64 -> unicode string (kv_ty)
# * member 'l' holding a typed list of float64
@jitclass([('d', types.DictType(*kv_ty)),
           ('l', types.ListType(types.float64))])
class ContainerHolder(object):
    pass
```
quite matching. Sure, basically there is `kv_ty = (types.int64, types.unicode_type)`, but I rather thought it was done that way for reasons of clean code. I did not expect, that this fixes a particular _quirkiness_ as @esc called it.
I can try to make a PR for the docs in this case with this special example.

**Comment by esc** [comment]
After some discussion today, we came to the conclusion that we would rather want to fix this than document it. I.e. implement `getitem` on the Numby types. As a result, I will close this issue and open a new feature request to document what needs to be done.

**Comment by andreapiso** [comment]
Sorry for reopening this closed discussion and very sorry if I am missing something obvious, however I think the approach proposed for List of Array in jitclass proposed here due to arrays of different contiguity are seen as of different types (and therefore cannot go on the same numba List). 

I think in most cases it would be preferable to have the jitclass contain arrays that are C/F contiguous rather than A (of course might not be always true) otherwise a lot of problems can arise such as: 

```
array_type = numba.types.int64[:]

spec = [
    ("b", numba.types.ListType(array_type)),
]
@numba.experimental.jitclass(spec)
class TestArrayList(object):
    def __init__(self, array_list):
        self.b = array_list

array_list = numba.typed.List()
array_list.append(np.empty(0, dtype=np.int64))
TestArrayList(array_list)
```
Failing due to:
`Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast ListType[array(int64, 1d, C)] to ListType[array(int64, 1d, A)]`

Not sure if this is the best way, but you can have your spec set the list to contain C contiguous arrays by creating a small mock object of and getting its type:

```
mock_array_list = numba.typed.List()
mock_array_list.append(np.empty(0, dtype=np.int64))

spec = {
    'b': numba.typeof(mock_array_list)
}
```

With the new spec, the above code does not crash anymore as the list is set to contain C-contiguous array. 

Again, sorry if i am missing something obvious to everyone else, just thought this could be another helpful example.

**Comment by esc** [comment]
@andreapiso thanks, that's some very helpful input, we appreciate it!

Perhaps the following could be used to make the type spec for the Array:

```
In [14]: numba.types.Array(numba.types.int64, ndim=1, layout="C")
Out[14]: array(int64, 1d, C)
```
