### ISSUE TITLE
np.isnan for np.datetime64 (numpy 1.18)

### ISSUE THREAD

**Issue by quantology** [numba/numba#5736]
The following fails:
```python
from numba import njit
import numpy as np

@njit
def check_nan(dt):
    if np.isnan(dt):
        raise ValueError()
    return dt

check_nan(np.datetime64("2020-01-01"))
```
with: `TypingError: ufunc 'isnan' using the loop 'M->?' not supported in this mode`

Not that this also makes np.searchsorted fail on datetime types.

**Comment by sklam** [comment]
`np.isnan` on datetime64 is a new feature in numpy1.18. Numba has not added all the new features for numpy1.18.
