### ISSUE TITLE
Numba CUDA kernel very slow compared to CuPy fuse

### ISSUE THREAD

**Issue by pwuertz** [numba/numba#5737]
Using the Numba `vectorize` decorator I defined an element-wise function for a CUDA device:
```python
@vectorize([types.float32(types.float32, types.float32, types.float32)], target="cuda")
def nb_function(xx, yy, xy):
    sqrt_term = math.sqrt(max(0., xx * xx - 2. * xx * yy + 4. * xy * xy + yy * yy))
    return .5 * (xx + yy - sqrt_term)
```

Being just a simple element-wise function, the definition is pretty much the same in CuPy:
```python
@cp.fuse
def cp_function(xx, yy, xy):
    sqrt_term = cp.sqrt(cp.maximum(0., xx * xx - 2. * xx * yy + 4. * xy * xy + yy * yy))
    return .5 * (xx + yy - sqrt_term)
```

Oddly enough, the Numba kernel is between 5x - 10x slower than the CuPy kernel (pure kernel execution time, no memory allocations/transfers).
Timings with Cuda 10.2, NVidia 2070, size 4048x4048:
  - Numba 5.1ms
  - CuPy 0.8ms

I tried implementing the method with `numba.cuda.jit` (manual thread / block handling), but the timing was almost identical to the `vectorize` version.

Does this indicate that something "bad" is happening to the element-wise-code that is generated for the CUDA compiler? Naively I wouldn't expect any significant difference.

Here is the full benchmark code for Numba and CuPy:
```python
# Numba version
import math
import numpy as np
from numba import cuda, vectorize, types


@vectorize([types.float32(types.float32, types.float32, types.float32)], target="cuda")
def nb_function(xx, yy, xy):
    sqrt_term = math.sqrt(max(0., xx * xx - 2. * xx * yy + 4. * xy * xy + yy * yy))
    return .5 * (xx + yy - sqrt_term)


sz = 4096
a1, a2, a3, a_out = (cuda.device_array((sz, sz), dtype=np.float32) for _ in range(4))

# Warmup
for _ in range(3):
    nb_function(a1, a2, a3, out=a_out)

# Timeit
e1, e2, stream = cuda.event(), cuda.event(), cuda.stream()
e1.record(stream)
nb_function(a1, a2, a3, out=a_out, stream=stream)
e2.record(stream)
e2.synchronize()
print(f"Numba: {e1.elapsed_time(e2):.2f} ms")
```

```python
# CuPy version
import numpy as np
import cupy as cp


@cp.fuse
def cp_function(xx, yy, xy):
    sqrt_term = cp.sqrt(cp.maximum(0., xx * xx - 2. * xx * yy + 4. * xy * xy + yy * yy))
    return .5 * (xx + yy - sqrt_term)

sz = 4096
a1, a2, a3 = (cp.empty((sz, sz), dtype=np.float32) for _ in range(3))

# Warmup
for _ in range(3):
    cp_function(a1, a2, a3)

# Timeit
e1, e2, stream = cp.cuda.Event(), cp.cuda.Event(), cp.cuda.Stream()
with stream:
    e1.record(stream)
    cp_function(a1, a2, a3)
    e2.record(stream)
e2.synchronize()
print(f"Cupy: {cp.cuda.get_elapsed_time(e1, e2):.2f} ms")
```

**Comment by sklam** [comment]
This is interesting. I wonder if it's from all the overhead in numba to launch the kernel.

**Comment by pwuertz** [comment]
@sklam I don't think so. This really is the timing from the kernel itself, double checked it with the NVidia Visual Profiler. Also interesting: I fed the same equation into `cp.ElementwiseKernel` and the exact same timing from Numba popped out. Magic?

**Comment by pwuertz** [comment]
All right, here is what fuse is doing: The expression is transformed into ~100loc with all operations explicitly written down and assigned to temporary variables, one by one. Also, every single value that goes in/out of each intermediate operation is being wrapped with `static_cast<float>`.

After burning some time trying to figure out some deeper meaning behind the specific order the operations were being transformed to... the solution was dead simple:

```python
@vectorize([types.float32(types.float32, types.float32, types.float32)], target="cuda")
def nb_function(xx, yy, xy):
    sqrt_term = math.sqrt(max(nb.float32(0.), xx * xx - nb.float32(2.) * xx * yy + nb.float32(4.) * xy * xy + yy * yy))
    return nb.float32(.5) * (xx + yy - sqrt_term)
```
Same execution time. Conclusion, always typecast your constants!

I suppose there isn't an easy way to prevent such accidents? Require constants being typed?

**Comment by gmarkall** [comment]
> I suppose there isn't an easy way to prevent such accidents? Require constants being typed?

Not at the moment. I'd like to add support for adjusting the typing for CUDA (e.g. make constants `float32` by default as an option, prefer `int32` for integer arithmetic, etc.) but that's not something I will get to in the near-term.

**Comment by stuartarchibald** [comment]
I don't recall if we have a ticket for it, but a quick diagnostic helper might be to update Numba's HTML annotate to colourize the types based on their bitwidth, this making it trivial to see when types are wider than anticipated.

**Comment by pwuertz** [comment]
Closing this since this is a coding problem on the user side, not an issue with the compiled kernel.

**Comment by esc** [comment]
@pwuertz thanks for following up and closing this issue!
