### ISSUE TITLE
NumPy 1.18 Support

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#5752]
## Feature request

It would be great to have support for NumPy 1.18. Noticed the following issues currently (not sure if there are others):

* [ ] https://github.com/numba/numba/issues/5736
* [ ] https://github.com/numba/numba/issues/5178

**Comment by esc** [comment]
@jakirkham thanks for posting this, I have labelled it as a feature request. NumPy 1.18 support has been on the wishlist for some time now. Let's use this issue to track progress and collect any issues that need to be resolved.

**Comment by jakirkham** [comment]
Sounds good. Thanks Valentin! Also please feel free to edit the OP to update the list as needed 🙂
