### ISSUE TITLE
Indexing a structured Numpy array using a variable throws an error

### ISSUE THREAD

**Issue by marnixhoh** [numba/numba#5756]
In plain python this works:

```
from numba import njit
import numpy as np

struct_dtype = np.dtype([
    ('one', np.float64),
    ('two', np.float64)])


def my_test():
    struct_array = np.empty((2, 1), dtype=struct_dtype)
    columns = ['one', 'two']
    for column in columns:
        struct_array[column][0] = 1234
    return struct_array


result = my_test()
print(result)
```

When jitting the function, it doesn't:

```
from numba import njit
import numpy as np

struct_dtype = np.dtype([
    ('one', np.float64),
    ('two', np.float64)])

@njit
def my_test():
    struct_array = np.empty((2, 1), dtype=struct_dtype)
    columns = ['one', 'two']
    for column in columns:
        struct_array[column][0] = 1234
    return struct_array


result = my_test()
print(result)
```

I found out through this bug when trying to find a way to assign rows of structured arrays, as a result of the bug I found in issue #5753.

numba: 0.49.1
numpy: 1.18.4
python: 3.7.1

## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by esc** [comment]
@marnixhoh thanks for submitting this, I can confirm that I am able to reproduce this.

**Comment by stuartarchibald** [comment]
This is the same problem as https://github.com/numba/numba/issues/5753#issuecomment-636762753

**Comment by stuartarchibald** [comment]
Closed this as making https://github.com/numba/numba/issues/5753#issuecomment-636762753 work will also make this work. It's the same "cannot determine the type of something in a loop/need a versioned loop body" problem.
