### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'targets'

### ISSUE THREAD

**Issue by ballchuuu** [numba/numba#5772]
Trying to use numba engine for pandas rolling.apply and I keep getting the following error:

```
    138             raise AttributeError(
    139                 f"module {__name__!r} has no attribute {attr!r}",
--> 140             ) from None
    141         else:
    142             errors.deprecate_moved_module(submodule_name, new_name)

AttributeError: module 'numba' has no attribute 'targets'
```

This was the code that I executed.
```
def f(x):
    return np.sum(x)

s = s.groupby("customer_id", as_index=False).rolling("7D", closed="left", on="time").apply(f, engine="numba", raw=True)
```
Would really appreciate some help as I really want to use numba to speed up the rolling summation. Thank you!

**Comment by stuartarchibald** [comment]
Thanks for the report. I think you've got a Numba that's too new for your Pandas installation? I think these would likely work:
* Numba <= 0.48 with Pandas <= 1.0.3
* Numba >= 0.49 with Pandas >= 1.0.4

**Comment by ballchuuu** [comment]
Thank you it works! @stuartarchibald

**Comment by esc** [comment]
@ballchuuu thanks for following up!
