### ISSUE TITLE
prange reverts to serial when thread count doesn't divide iterations

### ISSUE THREAD

**Issue by calvin-sykes** [numba/numba#5778]
## Bug report checklist

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

## Description

If the thread count doesn't divide the number of iterations in a Numba `prange` statement, the iterations that form the remainder are run in serial. If the thread and iteration count are similar, and/or individual iterations are expensive, this results in significant slowdown.

## Reproducer

```python
$cat numba_test.py
import numba as nb

@nb.jit(nopython=True, nogil=True, parallel=True)
def numba_func(num):
    for i in nb.prange(num):
        print("iteration", i)

if __name__ == '__main__':
    numba_func(20)

$NUMBA_NUM_THREADS=11 ./numba_test.py
iteration 0
iteration 1
iteration 6
iteration 4
iteration 10
iteration 2
iteration 9
iteration 5
iteration 11
iteration 7
iteration 3
iteration 8
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Which Numba version are you using, which operating system and which threading backend?

You can get the threading backend in use from updating your script like:
```python
if __name__ == '__main__':
    numba_func(20)
    print(nb.threading_layer())
```
Thanks.

**Comment by calvin-sykes** [comment]
The behaviour is the same in numba 0.48 and 0.49.1, installed via pip in a clean virtual environment. The OS is CentOS, but I'm unsure of the version and won't have access to the machine to check until later this week, sorry.

In any case I tried a local install on my laptop (running Ubuntu 20.04) with numba 0.49.1 and the same thing happens. On both machines the `tbb` threading layer is default, and both it and `workqueue` behave the same way.

I tried installing from conda to test the OpenMP layer and cannot get that to work at all - `python3 -m numba` immediately segfaults. I've never used conda before though so this may well be my fault, i'll have another look tomorrow.

**Comment by stuartarchibald** [comment]
Doing e.g. `NUMBA_DEBUG_ARRAY_OPT=1 NUMBA_NUM_THREADS=12 python issue5778.py`
shows the debug output from the schedule:
```
Parfor has potentially negative start False
_lower_parfor_parallel done
loop range[0]: 0 20 (1)
num_dim = 1
ranges = ([0, 19], )
num_threads = 12
sched[0] = 0 0 
sched[1] = 1 1 
sched[2] = 2 2 
sched[3] = 3 3 
sched[4] = 4 4 
sched[5] = 5 5 
sched[6] = 6 6 
sched[7] = 7 7 
sched[8] = 8 8 
sched[9] = 9 9 
sched[10] = 10 10 
sched[11] = 11 19
```

**Comment by stuartarchibald** [comment]
I think the issue comes down to the way the scheduler is balancing work.

**Comment by stuartarchibald** [comment]
cc @DrTodd13
