### ISSUE TITLE
np.positive is not implemented

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#5786]
Interestingly, the comment here says it doesn't exist!

https://github.com/numba/numba/blob/579db91677b7d82ef81599905c3afed55668cf17/numba/core/typing/npydecl.py#L146-L153

It was added in numpy 1.13, https://numpy.org/doc/1.18/reference/generated/numpy.positive.html

**Comment by stuartarchibald** [comment]
Thanks for the report, the time stamp on that docstring is `2015-04-17 17:36:36 -0500` which predates NumPy 1.13 by a couple of years? Guess this could do with an update on a few fronts.

1. Remove that docstring
2. Add in the lowering for `np.positive`.
3. Test 2.

**Comment by niteya-shah** [comment]
Can I work on this ?

**Comment by stuartarchibald** [comment]
@niteya-shah certainly! Thanks for helping out!
