### ISSUE TITLE
under @njit, the result of np.max/np.argmax is actually np.nanmax/np.nanargmax

### ISSUE THREAD

**Issue by wenyuC94** [numba/numba#5788]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I am using numba 0.49.0 (not the most recent 0.49.1). Under `@njit`, the result of np.max/np.argmax is actually np.nanmax/np.nanargmax.

Example:
```
import numpy as np
import numba as nb
a = np.array([2, 3, np.nan])

print(np.max(a))
print(np.argmax(a))

print(np.nanmax(a))
print(np.nanargmax(a))
```

The output is
```
nan
2
3.0
1
```

Now define the njit functions:
```
@nb.njit
def amax(a):
    return np.amax(a)

@nb.njit
def argmax(a):
    return np.argmax(a)

print(amax(a))
print(argmax(a))
```

The output is
```
3.0
1
```
This output is the output of np.nanmax and np.nanargmax, not that of np.max and np.argmax

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is a known bug, https://github.com/numba/numba/pull/4210 was on the way to fixing it and under the NumPy 1.18 support branch https://github.com/numba/numba/pull/5758 this problem is fixed.
