### ISSUE TITLE
`pip install numba==0.48` does not make `bin/numba` executable

### ISSUE THREAD

**Issue by yumasheta** [numba/numba#5805]
### Description
When installing the 0.48 version of numba via pip ( in an active virtual environment ) the `numba` executable placed in the `bin/` folder of the venv will not have the executable flag set.
Other versions I tested (0.47, both 0.49) do set the executable flag correctly.

##### OS
5.6.15-arch1-1 x86_64 GNU/Linux

##### Console log:
[parts removed for better readablitiy]
```
$ python3 -m venv testnumba
$ source testnumba/bin/activate
$ pip install numba==0.48
... [completed successfully] ...
$ pip list
Package    Version
---------- -------
llvmlite   0.31.0 
numba      0.48.0 
numpy      1.18.4 
pip        19.2.3 
setuptools 41.2.0 
$ ls testnumba/bin/numba
-rw-r--r-- 1  numba
```

Note:
I do know, that this issue is related to an older version of numba and should not be posted.
However, that version is served via pypi and will not work correctly if installed. This issue seems to be new, as I have an old install of version 0.48 via pip which did set `numba` as executable.
I do not even know, if it is possible to fix this problem "in place" for version 0.48.

Thanks.

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/5379

**Comment by yumasheta** [comment]
Is there no way to fix it for 0.48?

(sry I missed that previous issue )

**Comment by stuartarchibald** [comment]
Thanks for the report. I think it would require a rebuild of the 0.48 series wheels and Numba does not have a history of backporting fixes. Would the work around of using the `numba` module work?
Docs: http://numba.pydata.org/numba-doc/latest/user/cli.html#usage
Example:
```
$ python -m numba -s
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2020-06-03 09:38:42.420476
UTC start time                                : 2020-06-03 08:38:42.420485
Running time (s)                              : 3.967619
<snip>
```

**Comment by yumasheta** [comment]
for my usecase that w/a is fine.

AFAK the sysinfo module for numba got major updates for 0.49.
l guess your w/a will be supported by future versions, just the same as calling `$ numba -s` directly.

Thanks.

**Comment by stuartarchibald** [comment]
> for my usecase that w/a is fine.

great, glad to hear that.

> AFAK the sysinfo module for numba got major updates and code refactoring done for 0.49.

I don't think the code was changed? The module location just moved.

> l guess your w/a will be supported by future versions, just the same as calling `$ numba -s` directly.

Yes, I'd anticipate that to be the case.

I think what you are hitting is an issue with the way wheels were being build that got fixed some time in the 0.49.x release series.

**Comment by yumasheta** [comment]
Just to clarify:
Technically this issue is not resolved (and will not be?). But the w/a above should work in probably all cases.
Should this issue be closed?

**Comment by stuartarchibald** [comment]
@sklam any view on rebuilding 0.48.x wheels to set the execute bit on `bin/numba` ?

**Comment by sklam** [comment]
Rebuilding wheel... buildfarm id: `numba_wheel_19`

**Comment by sklam** [comment]
I have uploaded new wheel builds that fixed the problem. 

There were several issues coming from `auditwheel` and `wheel` packages from Python that is making this harder than expected: 

- `auditwheel repair` does not respect `--build-number`: dropping the build-number and creating corrupted output
- `wheel unpack` does not respect the execution bit: unpacks without the execution bit set; thus creating the problem reported here.
