### ISSUE TITLE
Unexpected behavior from `prange` when accessing large arrays

### ISSUE THREAD

**Issue by bkj** [numba/numba#5816]
Running the following program, I'd expect to see basically linear speedups from an increasing number of threads:
```
#!/usr/bin/env python

"""
    test_prange.py
"""

import argparse
import numpy as np
from time import time
from numba import njit, prange

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', type=int)
    return parser.parse_args()


@njit()
def seq(X):
    out = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            if X[i, j] > 0.5:
                out[i] = i
    
    return out

@njit(parallel=True)
def par(X):
    out = np.zeros(X.shape[0])
    for i in prange(X.shape[0]):
        for j in range(X.shape[1]):
            if X[i, j] > 0.5:
                out[i] = i
    
    return out

# --
# Init

args = parse_args()
X = np.random.uniform(0, 1, (args.n, args.n))

# --
# Trigger JIT

_ = seq(X[:100, :100])
_ = par(X[:100, :100])

# --
# Time

t = time()
_ = seq(X)
print('seq_time', time() - t)

t = time()
_ = par(X)
print('par_time', time() - t)
```
However, the performance of the parallel version is substantially worse than the serial version:
```
$ NUMBA_NUM_THREADS=1 python tmp.py --n 15000
seq_time 0.4682962894439697
par_time 0.9559032917022705
$ NUMBA_NUM_THREADS=2 python tmp.py --n 15000
seq_time 0.46035265922546387
par_time 0.8765692710876465
$ NUMBA_NUM_THREADS=4 python tmp.py --n 15000
seq_time 0.5803713798522949
par_time 0.8302707672119141
$ NUMBA_NUM_THREADS=8 python tmp.py --n 15000
seq_time 0.45206165313720703
par_time 0.7821910381317139
```

Any ideas what might be going on here?  Is there some way I can re-write the code to get a better speedup from prange?

Thanks!

**Comment by gmarkall** [comment]
My gut reaction is that this example is fairly memory bandwidth bound, and adding more threads doesn't help much or even hinders because memory bandwidth usage is already close to its limits. Though perhaps someone more familiar with ParallelAccelerator will be able to pinpoint what is going on, or provide a modification to the example that shows some speedup.

**Comment by bkj** [comment]
OK thanks.  Yeah I'd wondered about memory bandwidth as well, but if I implement the same program in C++ I get real speedups:
```
// mtest.cpp
// compile with
// g++ -std=c++11 -Wall -O3 -fopenmp -o mtest mtest.cpp

#include <stdlib.h>
#include <stdio.h> 
#include <string.h>
#include <sys/time.h>

typedef double Real;

double get_time() {
    struct timeval t;
    gettimeofday(&t, NULL);
    return (t.tv_sec + (t.tv_usec / 1000000.0)) * 1000.0;
}

void malloc2d(Real*** x_, int r, int c) {
    Real** x = (Real **)malloc(sizeof(int*) * r + sizeof(Real) * r * c); 
    for(int i = 0; i < r; i++) 
        x[i] = ((Real *)(x + r) + c * i); 
    
    *x_ = x;
}

int main(int argc, char* argv[]) { 
    int n = 15000;
    
    // Allocate random matrix
    Real** mat;
    malloc2d(&mat, n, n);
    for(int i = 0; i < n; i++) {
        for(int j = 0; j < n; j++) {
            Real r = (Real)rand() / (Real)(RAND_MAX);
            mat[i][j] = r;
        }
    }
    
    // Allocate output
    int* out = (int *)malloc(sizeof(int) * n); 
    for(int i = 0; i < n; i++) {
        out[i] = 0;
    }
    
    // Run function
    double start_time = get_time();
    #pragma omp parallel for
    for(int i = 0; i < n; i++) {
        for(int j = 0; j < n; j++) {
            if(mat[i][j] > 0.5) {
                out[i] = i;
            }
        }
    }
    double end_time = get_time();
    printf("elapsed=%f\n", (end_time - start_time));
    
    // Print output
    for(int i = 0; i < n; i++) {
        fprintf(stderr, "%d ", out[i]);
    }
}
```
Results:
```
g++ -std=c++11 -Wall -O3 -fopenmp -o mtest mtest.cpp

OMP_NUM_THREADS=1 ./mtest 2>/dev/null # elapsed=1895.288818
OMP_NUM_THREADS=2 ./mtest 2>/dev/null # elapsed=996.917969
OMP_NUM_THREADS=4 ./mtest 2>/dev/null # elapsed=777.301758
OMP_NUM_THREADS=8 ./mtest 2>/dev/null # elapsed=436.251709
```

So that's ~4x speedup using 8 threads.

I've run into this problem before with other applications that do lots of (random) accesses to large matrices -- `prange` doesn't yield a speed up, but an OpenMP implementation does.

~ Ben

**Comment by max9111** [comment]
Is there any reason why you compile the Numba function for arrays with arbitrary memory layout? You don't do this in your C++ version. The comparable Numba function would be:

```Python

#!/usr/bin/env python

"""
    test_prange.py
"""

import argparse
import numpy as np
from time import time
from numba import njit, prange

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', type=int)
    return parser.parse_args()


@njit()
def seq(X):
    out = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            if X[i, j] > 0.5:
                out[i] = i
    
    return out

@njit(parallel=True)
def par(X):
    out = np.zeros(X.shape[0])
    for i in prange(X.shape[0]):
        for j in range(X.shape[1]):
            if X[i, j] > 0.5:
                out[i] = i
    
    return out

# --
# Init

args = parse_args()
X = np.random.uniform(0, 1, (args.n, args.n))

# --
# Trigger JIT

_ = seq(X) #C-contigous
_ = par(X) #C-contigous

# --
# Time

t = time()
_ = seq(X)
print('seq_time', time() - t)

t = time()
_ = par(X)
print('par_time', time() - t)
```

Than you also see a relevant speedup for the parallel-version:

```
python Test.py --n 15000 
seq_time 0.15650105476379395
par_time 0.04111123085021973
```

instead of:

```
python Test.py --n 15000 
seq_time 0.2975647449493408
par_time 0.4863617420196533
```

The impact of the non aligned-memory access is just larger in the parallel version, but both are significantly slower than they could be.

**Comment by svenrahmann** [comment]
So you are saying that just by providing a sub-array for the initial JIT compilation, it is compiled differently? I don't see why this would change memory-alignment, though. The sub-array is just a different view into the original memory.

**Comment by max9111** [comment]
Yes, just check the function signature which Numba uses for compilation.  You are passing a view with arbitrary memory layout to the function, which has to be differnently handeled in compiled code. The same issue can also be reproduced in Cython. eg. double [:,:] x instead of double [:,::1]. 

You could also compile the version for c-contigous arrays first and than for non-contigous arrays afterwards, but not the other way around. 

@gmarkall Maybe it would make sense to add an option to force a compilation pass if the signature changes, even if they are compatible.

**Comment by esc** [comment]
I will close this assuming the original issue has been resolved. If the issue crops up again or continues to persist, please open a new thread on our discourse:  https://numba.discourse.group/
