### ISSUE TITLE
Add back support for atomics that always return the non-NaN values

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#5820]
## Feature request

From @uchytilc in #5556:
> I saw this change in the change log and was wondering if there would be a way to revert the change via an option or something to allow atomic min/max to return the non-Nan value always. I have found this a very useful feature. For example it prevents the need to initialize different values when trying to find a max/min reduction (i.e. -inf vs +inf).

**Comment by uchytilc** [comment]
Thanks for recording this @gmarkall. If I have time to do this, how would you recommend I record/set an optional variable to change between the two methods? Would it be best to have it in the definition of the function (i.e. cuda.atomic.min(args..., nan_arg = True)) and pass in an additional argument to the llvm ir function? It looks like the llvm_to_ptx function in nvvm.py looks for references in the llvm ir to do a string replace with the reduction ptx so the python arguments are lost at this point. I could either add in a bool argument to the llvm ir (so the choosing is done during evaluation in CUDA kernel) or I could record the python argument in Python somewhere and pick which version to compile.

**Comment by stuartarchibald** [comment]
`nanmax` and `nanmin` might be good names cf. NumPy

**Comment by gmarkall** [comment]
@uchytilc Thanks for your interest in this - as @stuartarchibald suggests, it would probably be better to bring back the old versions with names `cuda.atomic.nanmax` and `cuda.atomic.nanmin` instead - this will avoid dealing with the additional argument. if you copy the existing parts of the implementation for `max` and `min` (the typing in `numba.cuda.cudadecl`, lowering in `numba.cuda.cudaimpl`, and the IR in `numba.cuda.cudadrv.nvvm`) and modify the IR string to implement the old behaviour, that should work - does this give you enough to go on to start implementation?

**Comment by uchytilc** [comment]
That is probably enough to get me started. It might be a bit before I get around to doing it but I'll get to it eventually.

**Comment by jonmmease** [comment]
Hi All, thanks for taking a look at this!

After doing a bit of investigation into https://github.com/holoviz/datashader/issues/932, I just wanted to pass along the implications of this situation for Datashader.

 - The change in semantics for `numba.cuda.atomic.min`/`max` in numba 0.50 was a breaking change for Datashader's GPU support (brief description in https://github.com/holoviz/datashader/issues/932#issuecomment-651395153).
 - In combination with https://github.com/numba/numba/issues/5746, this means Datashader will need to remain pinned to `numba<=0.48` until it's possible to get the old behavior back.
 - Transitively, this means that Datashader can't be compatible with the cudf/rapids 0.14+ because these have a lower bound on numba of 0.49.

Thanks again!

**Comment by esc** [comment]
Since this seems to be blocking quite a few things downstream I'd like to get this fixed by 0.51.0RC1, hence I updated the Milestone.

**Comment by gmarkall** [comment]
I'm looking at this now.

**Comment by stuartarchibald** [comment]
@gmarkall I've done most of the patch, I can push up if you want to continue on that?

**Comment by stuartarchibald** [comment]
https://github.com/stuartarchibald/numba/commit/8b308bdaab5c05b6b85f84fe776dda0546c268eb

**Comment by gmarkall** [comment]
@jonmease There was a bug in the old semantics - the old value in the array was always supposed to be returned by `min` and `max` - however, if there was a NaN initially, then the new value got returned instead. Ideally when we implement the old behaviour again as `nanmin` and `nanmax`, we'd like to fix this bug, and ensure that the old value is always returned. Was this a behaviour that you relied on in Datashader?

**Comment by jonmmease** [comment]
Hi @gmarkall, thanks for taking a look! I'm not sure I'm following though.

Datashader relies on being able to initialize an array of NaN values. In psuedo-code

```
a = [nan, nan, nan]
```

Then it repeatedly performs min/max operations (in parallel)

First operation
```
cuda.atomic.max(a, 1, 3.0)
a
```
```
[nan, 3.0, nan]
```
Second operation
```
cuda.atomic.max(a, 1, 4.0)
a
```
```
[nan, 4.0, nan]
```
I'm not sure what you mean by "we'd like to fix this bug, and ensure that the old value is always returned".
Does the new behavior of `nanmin`/`nanmax` you have in mind still behave this way?

FWIW, there's already work in progress in Datashader to switch from `min`/`max` to `nanmin`/`nanmax` in https://github.com/holoviz/datashader/pull/940.

**Comment by gmarkall** [comment]
Thanks for the quick reply! It does still behave that way - what you should also be able to do is:

```python
a = [nan, nan, nan]
```

```python
old = cuda.atomic.nanmax(a, 1, 3.0)
```

At this point, `old`, should hold the value `nan` - but in the original implementation, it holds `3.0`. I think it looks like you're not using the returned value at all, so it should be safe for you if the `nanmax` and `nanmin` implementations always return the old value (i.e. `nan` in this case)?

**Comment by jonmmease** [comment]
Ahh, I understand now. Yes, we were not using the returned value so semantically this isn't a problem for Datashader.

But does this change have a performance implication? Does it involve making a copy of the input array?

**Comment by gmarkall** [comment]
> But does this change have a performance implication? Does it involve making a copy of the input array?

Sorry I didn't respond sooner - there's no copy of the input array made, and no performance implication for the change - something was always returned anyway, it's just that the wrong values were sometimes returned before.
