### ISSUE TITLE
Conditional execution of functions in nopython mode

### ISSUE THREAD

**Issue by SilMon** [numba/numba#5823]
I currently encountered strange behaviour whilst trying to use numba to accelerate image processing functions. It does not seem to be possible to write a function to accept numpy arrays of different dimensionality, or to be more precise: Grayscale as well as RGB images. That issue seems to be caused because numba seems to evaluate expressions even if the condition is not met, leading to errors.

The whole issue is described here:

https://stackoverflow.com/questions/62197510/conditional-execution-of-numba-functions-in-nopython-mode

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a minimal working example of the problem:
```python
from numba import njit
import numpy as np

@njit
def apply_lut(image, lut):
    """
    Function to apply a lookup table to the given image

    :param image: The image
    :param lut: The lookup table to apply to the image. Needs to be in range[img_min, img_max]
    :return: The image with applied LUT
    """
    # Check if image has only one channel
    if len(image.shape) == 2:
        return _apply_lut_to_grayscale(image, lut)
    # Create new empty image
    img = np.empty_like(image)
    # Get number of channels
    channels = img.shape[2]
    for c in range(channels):
        for y in range(image.shape[0]):
            for x in range(image.shape[1]):
                img[y][x][c] = lut[image[y][x][c]]
    return img


@njit
def _apply_lut_to_grayscale(image, lut):
    """
    Function to apply a lookup table to the given grayscale image

    :param image: The grayscale image
    :param lut: The lookup table to apply to the image. Needs to be in range[img_min, img_max]
    :return: The image with applied LUT
    """
    # Create new empty image
    img = np.zeros(shape=image.shape, dtype=image.dtype)
    # Apply lut
    for y in range(image.shape[0]):
        for x in range(image.shape[1]):
            img[y][x] = lut[image[y][x]]
    return img


grey_scale = np.ones((4, 5), dtype=np.uint8)
colour = np.ones((4, 5, 3), dtype=np.uint8)

lookup = (0, 1)

apply_lut(grey_scale, lookup)
```
Numba has to be able to statically infer the types of all variables based solely on the types of the inputs and some built in rules about e.g. what NumPy functions do. The case presented does not conform to this as Numba cannot work out solely from the type of the image whether `len(image.shape) == 2` is true or not (this would require compile time evaluation of that expression which isn't possible right now) and so it tries to work out both branches and then hits a problem because one branch is for 2d and the other for 3d. There is however a workaround, Numba will propagate the constant `<np.ndarray instance>.ndim` into the source and then it can evaluate the simple expression e.g. `image.ndim == 2` and this permits the static analysis to specialise the code for just one branch. For example this would likely work:
```python
from numba import njit
import numpy as np

@njit
def apply_lut(image, lut):
    """
    Function to apply a lookup table to the given image

    :param image: The image
    :param lut: The lookup table to apply to the image. Needs to be in range[img_min, img_max]
    :return: The image with applied LUT
    """
    # Check if image has only one channel
    if image.ndim == 2:
        return _apply_lut_to_grayscale(image, lut)
    # Create new empty image
    img = np.empty_like(image)
    # Get number of channels
    channels = img.shape[2]
    for c in range(channels):
        for y in range(image.shape[0]):
            for x in range(image.shape[1]):
                img[y][x][c] = lut[image[y][x][c]]
    return img


@njit
def _apply_lut_to_grayscale(image, lut):
    """
    Function to apply a lookup table to the given grayscale image

    :param image: The grayscale image
    :param lut: The lookup table to apply to the image. Needs to be in range[img_min, img_max]
    :return: The image with applied LUT
    """
    # Create new empty image
    img = np.zeros(shape=image.shape, dtype=image.dtype)
    # Apply lut
    for y in range(image.shape[0]):
        for x in range(image.shape[1]):
            img[y][x] = lut[image[y][x]]
    return img


grey_scale = np.ones((4, 5), dtype=np.uint8)
colour = np.ones((4, 5, 3), dtype=np.uint8)

lookup = (0, 1)

apply_lut(grey_scale, lookup)
apply_lut(colour, lookup)
```
Hope this helps?

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
