### ISSUE TITLE
Weird behavior for loop

### ISSUE THREAD

**Issue by khazit** [numba/numba#5825]
## Reporting a bug

I encountered some weird behavior when using Numba. This is a simplified version of the code. Feel free to ask for more details if needed.

I'm using LIDAR data points to create and fill a grid map. This is the function that I use: 

```python
@jit(nopython=True)
def fill_grid(grid, lidar_pts, discrete_coord):
   for idx, coord in enumerate(discrete_coord):
     grid[coord[0], coord[1]] = np.maximum(
        grid[coord[0], coord[1]], 
        lidar_pts[idx, -1]
     )
    return grid
``` 

The weird behavior is that when I run this function, I get the following grid, which is wrong.

![false](https://user-images.githubusercontent.com/43420058/84018305-2cc16000-a980-11ea-874d-58ada3babf7d.png)

But then if I remove the `@jit` compilation, I get the correct grid.

![good](https://user-images.githubusercontent.com/43420058/84018826-c38e1c80-a980-11ea-87cc-ae0879ca36eb.png)

It seems that the `for` iterate on the wrong values, but I'm not sure why.

**Comment by gmarkall** [comment]
Thanks for the report - could you provide minimal reproducer that can be executed please?

**Comment by khazit** [comment]
I'm trying to but I can't find the root cause. I'll put it here once I'm done, but it could take time.

**Comment by stuartarchibald** [comment]
Might be this: https://github.com/numba/numba/pull/5721 Perhaps try the 0.50.0 release candidate which contains the fix:
```
conda install -c numba numba=0.50.0rc1
```

**Comment by khazit** [comment]
You're right, I just tested it and still the same problem.

**Comment by gmarkall** [comment]
> I'm trying to but I can't find the root cause. I'll put it here once I'm done, but it could take time.

OK - could you provide the output of `fill_grid.signatures` just before and after the call that has the problem please?

**Comment by khazit** [comment]
> Might be this: #5721 Perhaps try the 0.50.0 release candidate which contains the fix:
> 
 
I made a mistake, this actually fixes it. I forgot to restart my ipython kernel.

Thank you for your help. I'm closing this issue.
