### ISSUE TITLE
Can't njit code containing an np.ndarray subclass

### ISSUE THREAD

**Issue by mishana** [numba/numba#5827]
Hi, I implemented a wrapper class for numpy arrays (actually, a subclass of `np.ndarray`). When trying to `njit` a function that uses my ndarray subclass, it fails with a type error. Is there something I can do about it? I want to be able to `njit` code that calls my subclassed c'tor and other implemented methods/properties.

Thanks,
Michael

**Comment by stuartarchibald** [comment]
Thanks for the report. Without a reproducer it's hard to guess, please could you post one? Once we have a reproducer someone can take a look. Thanks for your help.

**Comment by mishana** [comment]
![image](https://user-images.githubusercontent.com/5438682/84127148-8a6caf80-aa47-11ea-81e3-577dc83bd87a.png)
![image](https://user-images.githubusercontent.com/5438682/84127168-8f316380-aa47-11ea-837e-857c08576999.png)

**Comment by stuartarchibald** [comment]
Thanks for the update. What you have will not work in Numba out of the box, I think you'd have to write an extension type, there's an example of doing this here http://numba.pydata.org/numba-doc/latest/extending/interval-example.html, or perhaps you could start inheriting from Numba's internal implementations. As a warning, this is not a particularly easy thing to do. What is it you are hoping the get from Numba?

**Comment by mishana** [comment]
I'm implementing a (graph) planning algorithm that relies heavily on my subclass of `np.ndarray` and numerical calculations - seems like Numba is tailored to accelerate some of the more expensive calculations. I actually looked into the "interval example" and tried to recreate it with no luck:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/5438682/84130181-99556100-aa4b-11ea-8167-7a932abc6051.png">
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/5438682/84130206-a4a88c80-aa4b-11ea-8fa9-5724cccfb350.png">

**Comment by mishana** [comment]
@stuartarchibald can this be achieved by using `@jitclass` without extending numba's types?

**Comment by sklam** [comment]
@mishana, you can use `@jitclass` to contain a field for the numpy array and define properties for `x1` and `x2`. But if you need it to extend `ndarray` such that it carries all the methods of ndarray, I don't think there is any easy way to achieve that in Numba.

**Comment by mishana** [comment]
@sklam thank you for the answer. Too bad it is so much work writing an extension type. For now, I am using the workaround of breaking up functions in my code, such that all jitted functions work only on pure numpy arrays. For example:
```python
def foo(a: NumpySubclass):
    return a.x1**2 + a.x2**2 
``` 
Is turned into:
```python
def foo(a: NumpySubclass):
    return foo_jit(a.x1, a.x2)

@njit
def foo_jit(x1: np.ndarray, x2: np.ndarray):
    return x1**2 + x2**2
```

**Comment by mishana** [comment]
@stuartarchibald @sklam If there is nothing else I can do, then I think we can close this issue.
