### ISSUE TITLE
native<->objmode calls overhead for small functions

### ISSUE THREAD

**Issue by Hardcode84** [numba/numba#5828]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

@sklam  Just to document things discussed on meeting.

I tried to investigate example with native<->objmode calls overhead
https://gist.github.com/sklam/8b574306b20766cf821e7a6cec4b76c4

And it seems in this particular case this is due to repeating object deserializing on each function call.
Numba calls `serialize_uncached` on python side to serialize object into buffer and save it in IR(this happens only on first call).
https://github.com/numba/numba/blob/release0.49/numba/core/pythonapi.py#L1303

But then it deserialize this buffer into object on each function call via `numba_unpickle`
https://github.com/numba/numba/blob/release0.49/numba/_helperlib.c#L993

I tried to replace `numba_unpickle` body with just `return 0` and got almost identical times between mixed and pure python after that.

So questions:
* Why we can't just use object from outside without serializing/deserializing it.
* Is it safe to cache deserialized object on native side (e.g. deserialize it on first call and save obj into global var)

Slightly modified example:
```
import numpy as np
from numba import njit, jit, objmode, typeof
from numba.extending import overload
import timeit
import time

t = 0.0

def unknown_func(arr):
    b = time.time()
    res = np.linalg.norm(arr)
    e = time.time()
    global t
    t += (e - b)
    return res

@overload(unknown_func)
def unknown_lib_func(arr):
    def impl(arr):
        # What we know is that the function takes an array and return a float
        with objmode(out='float64'):
            out = unknown_func(arr)  # use the pure-python implementation
        return out

    return impl

def example(arrays):
    out = 0
    for arr in arrays:
        out += unknown_func(arr)
    return out

jit_example = njit(example)

arrs = np.random.random((1, 1000))

example(arrs)
jit_example(arrs)

t = 0.0
print(timeit.timeit(lambda: example(arrs)))
print(t)
print()

t = 0.0
print(timeit.timeit(lambda: jit_example(arrs)))
print(t)
```
Tested on 0.49.1

**Comment by stuartarchibald** [comment]
Thanks for the report. CC @sklam .

**Comment by asodeur** [comment]
I am caching deserialized objects (see [this](https://gitter.im/numba/numba?at=5ed0b2383ffa6106f1dfda15)) but @sklam advised you had to be careful not to keep function types alive longer than neccessary. Have not found a good way to identify types containing function types, yet. Once I found a way I'll likely open a PR.

**Comment by sklam** [comment]
> Why we can't just use object from outside without serializing/deserializing it

The current approach is to keep a unified IR generation for both cached and uncached code. For cached code, the loading process must recreate the session by deserialize the referenced objects. 

> Is it safe to cache deserialized object on native side (e.g. deserialize it on first call and save obj into global var)

It is "safe" as in it will not cause semantic error. But, large objects (like large temporary functions) can be holding up memory resulting in memory-leak for long running process. We will need a good way to clean up the cached deserialized objects.

**Comment by sklam** [comment]
I can confirm that caching the deserialized object reduced most of the overhead. 

However, my patch (https://github.com/numba/numba/pull/5674) to allow caching of `with objmode` is causing significantly more overhead seen in this issue.

**Comment by Hardcode84** [comment]
> I can confirm that caching the deserialized object reduced most of the overhead.

Can you please provide some public branch with this change so we can test performance on our workloads.

**Comment by sklam** [comment]
@Hardcode84, 

https://github.com/sklam/numba/commit/0e0a969d29909588ddab65e667c2e83c2a806be4 is the experimental patch to add caching of deserialization.
That patch alone is fixing the overhead you see in this issue.
That patch combined with https://github.com/numba/numba/pull/5674 is a lot slower unfortunately. I need to debug it to know why.

**Comment by sklam** [comment]
@Hardcode84, I have a new proposed patch https://github.com/numba/numba/pull/5922 to would solve the objmode overhead problem. 

Using the reproducer code that you have, on master (f55b055b82892a3030ec0bbc504cf17cf098ec10) I get:

```
6.917409159
5.096495151519775

9.579834582
5.7540082931518555
```

With https://github.com/numba/numba/pull/5922, I get:

```
6.88690711
5.080684185028076

6.91699412
5.253177642822266
```

That shrinks the objmode overhead.

**Comment by sklam** [comment]
Closed by https://github.com/numba/numba/pull/5922
