### ISSUE TITLE
Slower initial compilation with newer numba from Miniconda

### ISSUE THREAD

**Issue by mathomp4** [numba/numba#5832]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

All,

I'm a bit of a newbie to numba, so it's possible I'm doing something wrong, but I'm not sure what. To wit, I help maintain/build Python stacks on a computing cluster and our "current" version is based on Anaconda 2019.10 (so a bit old) with numba:
```
$ conda list | grep numba
numba                     0.45.1           py37h962f231_0
```
Yesterday, in an attempt to build a new stack, I found my self having to use Miniconda instead, but I still seemed to get most of the packages I needed (indeed with less cruft) and numba did install:
```
$ conda list | grep numba
numba                     0.49.1           py37h0da4684_0    conda-forge
```
Now, the odd thing is I asked a user to try it out and he reported some odd slowness with some Numba examples. Not knowing much numba, I decided to start with the most basic example I could find, the one from ["How to measure the performance of numba?"](https://numba.pydata.org/numba-doc/latest/user/5minguide.html#how-to-measure-the-performance-of-numba). I did a bit of copy-paste to run more than once after the compilation. Using the older numba:
```
$ python numba_example.py
Elapsed (with compilation) = 0.9423942565917969
Elapsed (after compilation 1) = 3.5762786865234375e-06
Elapsed (after compilation 2) = 9.5367431640625e-07
Elapsed (after compilation 3) = 9.5367431640625e-07
Elapsed (after compilation 4) = 9.5367431640625e-07
Elapsed (after compilation 5) = 9.5367431640625e-07
```
Using the newer numba:
```
$ python numba_example.py
Elapsed (with compilation) = 4.7247231006622314
Elapsed (after compilation 1) = 3.5762786865234375e-06
Elapsed (after compilation 2) = 1.430511474609375e-06
Elapsed (after compilation 3) = 9.5367431640625e-07
Elapsed (after compilation 4) = 9.5367431640625e-07
Elapsed (after compilation 5) = 7.152557373046875e-07
```
So, as can be seen, it looks like the slowness that the new user saw is all in the initial compile. I guess my question is: is there a package that numba uses that might be "optional" in Miniconda but installed with Anaconda that speeds this up?

Now I did run `numba -s` on each and can provide if needed. Other than the obvious differences in the Conda environment, the only glaring difference is the old one has:
```
__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : True
Workqueue Threading layer available           : True
```
but the new one says:
```
__Threading Layer Information__
TBB Threading layer available                 : True
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True
```
Not sure if that has anything to do with the slow compile?

**Comment by stuartarchibald** [comment]
Thanks for the report. I can't seem to reproduce, am using this:
```python
from numba import jit, __version__
import numpy as np
import time

print("Version", __version__)

x = np.arange(100).reshape(10, 10)

@jit(nopython=True)
def go_fast(a): # Function is compiled and runs in machine code
    trace = 0.0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

# DO NOT REPORT THIS... COMPILATION TIME IS INCLUDED IN THE EXECUTION TIME!
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (with compilation) = %s" % (end - start))

# NOW THE FUNCTION IS COMPILED, RE-TIME IT EXECUTING FROM CACHE
start = time.time()
go_fast(x)
end = time.time()
print("Elapsed (after compilation) = %s" % (end - start))
```
and get:
```
$ python issue5832.py                                                                                                           
Version 0.45.1                                                                                                                  
Elapsed (with compilation) = 0.3457908630371094                                                                                 
Elapsed (after compilation) = 6.67572021484375e-06                                                                              
```
and
```
$ python issue5832.py 
Version 0.49.1
Elapsed (with compilation) = 0.36968302726745605
Elapsed (after compilation) = 6.198883056640625e-06
```

**Comment by stuartarchibald** [comment]
I just spotted you are using `conda-forge`s Numba for 0.49.1, I'll try that now too.

**Comment by stuartarchibald** [comment]
conda-forge Numba 0.49.1 gives me:
```
Version 0.49.1
Elapsed (with compilation) = 0.33069396018981934
Elapsed (after compilation) = 6.67572021484375e-06
```

**Comment by stuartarchibald** [comment]
> I guess my question is: is there a package that numba uses that might be "optional" in Miniconda but installed with Anaconda that speeds this up?

I can't think of any package that would immediately speed up/slow down compilation. For reference, the optional dependencies are listed here: http://numba.pydata.org/numba-doc/latest/user/installing.html#dependency-list

**Comment by mathomp4** [comment]
Well this is baffling. I'm attaching the two `numba -s` outputs. In case you can see anything glaring I might be missing. I'll go through your dependency list. 

[0_49_1_numba_s.txt](https://github.com/numba/numba/files/4752548/0_49_1_numba_s.txt)
[0_45_1_numba_s.txt](https://github.com/numba/numba/files/4752550/0_45_1_numba_s.txt)

**Comment by mathomp4** [comment]
Oh. And the code I was running was the same as @stuartarchibald was. I just copy-and-pasted the "after compilation" section a few times. Just to make sure I wasn't seeing some other issue that wasn't present after the first after try.

**Comment by mathomp4** [comment]
I also tried `issue5832.py` as exactly above:
```
$ python issue5832.py
Version 0.45.1
Elapsed (with compilation) = 0.627617597579956
Elapsed (after compilation) = 3.337860107421875e-06
```

```
$ python issue5832.py
Version 0.49.1
Elapsed (with compilation) = 3.6047301292419434
Elapsed (after compilation) = 4.291534423828125e-06
```

But then I had a thought. What if I run a few over and over. Old:
```
$ for i in {1..3}; do python ./issue5832.py ; done
Version 0.45.1
Elapsed (with compilation) = 0.574366569519043
Elapsed (after compilation) = 3.0994415283203125e-06
Version 0.45.1
Elapsed (with compilation) = 0.5865664482116699
Elapsed (after compilation) = 3.0994415283203125e-06
Version 0.45.1
Elapsed (with compilation) = 0.5943951606750488
Elapsed (after compilation) = 4.291534423828125e-06
```
New:
```
$ for i in {1..3}; do python ./issue5832.py ; done
Version 0.49.1
Elapsed (with compilation) = 3.706967830657959
Elapsed (after compilation) = 3.5762786865234375e-06
Version 0.49.1
Elapsed (with compilation) = 1.086216926574707
Elapsed (after compilation) = 3.337860107421875e-06
Version 0.49.1
Elapsed (with compilation) = 0.6895918846130371
Elapsed (after compilation) = 3.5762786865234375e-06
```
Huh. Weird.

**Comment by stuartarchibald** [comment]
Does this reproduce for you across runs? Also in a clean environment with just Numba and python installed do you get the same for 0.49.1?

**Comment by mathomp4** [comment]
@stuartarchibald It does seem pretty reproducible. But per your suggestion, I downloaded a fresh copy of Miniconda3 latest, and after installing ran:
```
$ ./miniconda3/bin/conda install numba
```
I also decided to see, just in case, if it mattered what the disk subsystem was (this is a supercomputing cluster so we have a big GPFS/NFS space as well as a smaller SSD based space). 

Old Anaconda numba in /usr/local:
```
Version 0.45.1
Elapsed (with compilation) = 0.7379286289215088
Elapsed (after compilation) = 4.5299530029296875e-06
```
Miniconda with a zillion extra packages (like Anaconda), on slow disks:
```
Version 0.49.1
Elapsed (with compilation) = 3.744454860687256
Elapsed (after compilation) = 3.5762786865234375e-06
```

Fresh miniconda3 with just numba, slow disks:
```
Version 0.49.1
Elapsed (with compilation) = 1.9278156757354736
Elapsed (after compilation) = 3.337860107421875e-06
```

Fresh miniconda3 with just numba, fast disks:
```
Version 0.49.1
Elapsed (with compilation) = 0.6466431617736816
Elapsed (after compilation) = 3.0994415283203125e-06
```

So is numba writing file(s) when it does its jit? This might have just been disk slowness?

**Comment by stuartarchibald** [comment]
Thanks for the data. Numba is not writing files but it does read, well, it scans the packages in the environment to see if any of them are trying to register Numba extensions, environments on NAS may make such a scan slower. It looks like in the results presented originally that it may be a compounding of "loads of packages" and "disk is slow" (based on the new data)?

PR: https://github.com/numba/numba/pull/5209 is to fix.

**Comment by mathomp4** [comment]
Let's see. Looking at #5209 and drilling down...
Old in /usr/local:
```
$ python -X importtime -c "import numba" |& sort -k3 -g |& tail -5
import time:     88628 |    1501989 |   numba.config
import time:    222359 |     703555 |     numpy
import time:    348582 |     374195 |     numba.typed.typeddict
import time:    457982 |     733534 |           pkg_resources
import time:    494285 |    1232622 |         llvmlite.binding.ffi
```
Big Anaconda-like Miniconda on slow:
```
$ python -X importtime -c "import numba" |& sort -k3 -g |& tail -5
import time:    174441 |     174441 |                         _hashlib
import time:    427721 |     427721 |             numpy.core._multiarray_umath
import time:   1009566 |    2821066 |           pkg_resources
import time:   2015831 |    2215902 |     numba.typed.typeddict
import time:   3731544 |    6574220 |         llvmlite.binding.ffi
```
Basic Miniconda on slow disks:
```
$ python -X importtime -c "import numba" |& sort -k3 -g |& tail -5
import time:    166140 |     269839 |                 pkg_resources._vendor.pyparsing
import time:    285993 |    2941520 |           pkg_resources
import time:    686270 |     686270 |             numpy.core._multiarray_umath
import time:   1215509 |    1404058 |     numba.typed.typeddict
import time:   3601916 |    6584613 |         llvmlite.binding.ffi
```
Basic miniconda on fast disks:
```
$ python -X importtime -c "import numba"  |& sort -k3 -g |& tail -5
import time:     36711 |    1660546 |   numba.core.config
import time:     66742 |     510430 |           pkg_resources
import time:     97247 |      97247 |             numpy.core._multiarray_umath
import time:    511450 |     547816 |     numba.typed.typeddict
import time:    913333 |    1431906 |         llvmlite.binding.ffi
```
It does seem scanning that tree is a lot faster on the fast disks.

**Comment by stuartarchibald** [comment]
Thanks for looking, I think we've got to the bottom of this then?

**Comment by mathomp4** [comment]
I guess so. Hopefully #5209 gets in soon.

**Comment by stuartarchibald** [comment]
Thanks for closing this, I think #5209 is waiting on some armv7l/noarch builds of the `importlib-metadata` package.
