### ISSUE TITLE
operator.pos fails on strided arrays

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#5848]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
@numba.njit
def pos(x):
    return +x
pos(np.arange(6)[::2])
```
gives
```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Don't know how to allocate array with layout 'A'.

File "<ipython-input-12-72e97bb40740>", line 3:
def pos(x):
    return +x
    ^
```

**Comment by stuartarchibald** [comment]
Can confirm #5796 fixes.
