### ISSUE TITLE
Emit warnings when constructs aren't unsupported in nopython mode

### ISSUE THREAD

**Issue by pitrou** [numba/numba#586]
There should be a mode of operation where all constructs which are unsupported in Python mode raise warnings on stderr, so that the output can be inspected to evaluate the "optimizability" of a code base.

For example by enabling a NUMBA_WARNINGS=1 environment variable.

**Comment by StanczakDominik** [comment]
I think #677 fixed this, so today's as good a day as any to close this :)

**Comment by stuartarchibald** [comment]
Closing as fixed by #677.
