### ISSUE TITLE
Minimum time for deprecation cycles?

### ISSUE THREAD

**Issue by bmcfee** [numba/numba#5865]
## Feature request

This is more of a meta request, but I wanted to ask if it's possible to have longer deprecation cycles for API-breaking changes.

This request is motivated by the 0.50 release dropping the shim for decorators.  It's great that you communicated this clearly in the release notes and warnings, but as far as I can tell, the entire deprecation cycle here was less than two months (warning first appeared in 0.49.0 on 2020-04-16, breaking change implemented in 0.50.0 on 2020-06-10).

Since we're not on strict semantic versioning territory here, these kinds of changes are impossible to anticipate by matching version numbers, so the best we (as downstream package maintainers) can do is watch for warnings and react as quickly as possible.  The "as quickly as possible" is the catch here, since many of us are time- and resource-constrained, and can't operate on fast release schedules.

I don't have any strong recommendations here, but I wanted to raise the issue because it's causing a lot of trouble for end-users whose installations have suddenly broken because downstream maintainers could not react quickly enough.  In my specific case, this deprecation cycle landed on the busiest time of the year (end of the academic year), though I expect in general that downstream maintainers will have widely varying schedule conflicts.  Having a documented, longer cycle for handling deprecations (e.g., at least 6 months) could go a long way toward supporting downstream devs and end-users.

**Comment by sklam** [comment]
@bmcfee, sorry about the short deprecation cycle. Part of the reason that we moved so quickly is that we assumed downstream projects can pin to the older versions that they support. Would that be possible for your case?

**Comment by bmcfee** [comment]
> Part of the reason that we moved so quickly is that we assumed downstream projects can pin to the older versions that they support. Would that be possible for your case?



Yeah, that makes sense, but as a library (not an end-user application), pinning to exact versions could easily result in unsatisfiable configurations.  Pinning to wildcards is possible, if you know what the wildcards should be in advance, but without semantic versioning that's impossible to predict.

I have been telling end-users to pin while we sort things out, but I don't think it's a feasible solution in general.

**Comment by stuartarchibald** [comment]
As another core developer, I'd also like to offer my apologies for this and the impact it had on `librosa`. We tried to contact all the projects that we knew about that were using internal APIs ahead of deciding how fast to move (https://github.com/numba/numba/issues/5214). The general feedback, from various user groups using Numba's internal APIs, was that they were tracking Numba latest release/Numba master branch. As a result it was decided that a quick deprecation cycle would be fine. This is the first time in about 5 years the project has seen a refactor of this scale, should this be needed again (and I really hope not for a long time!) I think doing a more typical length deprecation cycle (http://numba.pydata.org/numba-doc/latest/reference/deprecation.html, some are running for over a year!) would be something to consider.

I also think it was just a bit unfortunate that `librosa` was using something from Numba's internals, when it probably didn't need to be https://github.com/librosa/librosa/pull/1164, I hope that patch fixed the project and also makes it less susceptible to any future changes to Numba internals. If there's anything else we can do to help out with this please shout! Thanks :)

**Comment by bmcfee** [comment]
No worries, these things happen!  It's true that we never should have been using an internal API in the first place (and the usage had long been deprecated anyway), but thanks for the correction.



> If there's anything else we can do to help out with this please shout! Thanks :)

Nope, I think we're all good!  No major harm done, I just wanted to raise the point that maybe a little documentation about expected cycle length could be helpful.  But it sounds like you're all well on top of that anyway, so I'm happy for this issue to be closed out.  Thanks again!
