### ISSUE TITLE
TypeError: compile_kernel() got an unexpected keyword argument 'boundscheck'

### ISSUE THREAD

**Issue by ttsesm** [numba/numba#5868]
Hi, I am quite new to `numba` and was trying to play with it. Thus, I was trying to run the following simple example:

```
from numba import jit, cuda 
import numpy as np 
import os

# function optimized to run on gpu
@jit(target ='cuda')
def func2(a):
    for i in range(10000000):
        a[i]+= 1

if __name__ == '__main__':
    n = 10000000
    a = np.ones(n, dtype=np.float64)
    b = np.ones(n, dtype=np.float32)

    func2(a)
    os._exit(0)
```

but for some reason I am getting the `TypeError`:

`TypeError: compile_kernel() got an unexpected keyword argument 'boundscheck'`

I checked on the web for similar issues but I did not really found anything relevant. Any idea what might be wrong.

Thanks.

System info:
Python 3.8
Windows 10
Numba 0.50

**Comment by vhviveiros** [comment]
I have the same issue

**Comment by ttsesm** [comment]
Here is the exact error message:

```
Traceback (most recent call last):
  File "C:\Users\TTsesm\Desktop\dev\rad\r_venv\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
TypeError: compile_kernel() got an unexpected keyword argument 'boundscheck'
```

**Comment by Super-Gil** [comment]
Same here too...

**Comment by esc** [comment]
@ttsesm thanks for reporting this, I can reproduce on a GPU enabled machine.

**Comment by esc** [comment]
So I tried a few major versions too. `0.49.0` gives the same error, but `0.48.0` gives:

```
/home/vhaenel/git/numba/numba/cuda/decorators.py:116: UserWarning: autojit is deprecated and will be removed in a future release. Use jit instead.
  warn('autojit is deprecated and will be removed in a future release. Use jit instead.')
Traceback (most recent call last):
  File "foo002.py", line 16, in <module>
    func2(a)
  File "/home/vhaenel/git/numba/numba/cuda/dispatcher.py", line 42, in __call__
    return self.compiled(*args, **kws)
  File "/home/vhaenel/git/numba/numba/cuda/dispatcher.py", line 38, in compiled
    self._compiled = autojit(self.py_func, **self.targetoptions)
  File "/home/vhaenel/git/numba/numba/cuda/decorators.py", line 117, in autojit
    return jit(*args, **kwargs)
  File "/home/vhaenel/git/numba/numba/cuda/decorators.py", line 56, in jit
    raise NotImplementedError("bounds checking is not supported for CUDA")
NotImplementedError: bounds checking is not supported for CUDA
```

**Comment by esc** [comment]
It seems like the orgin of this may be: https://github.com/numba/numba/pull/5257

**Comment by esc** [comment]
Here is an initial patch that can get someone started: 

```
diff --git a/numba/cuda/decorators.py b/numba/cuda/decorators.py
index 9625954..b44a6fd 100644
--- a/numba/cuda/decorators.py
+++ b/numba/cuda/decorators.py
@@ -53,6 +53,8 @@ def jit(func_or_sig=None, argtypes=None, device=False, inline=False, bind=True,

     if kws.get('boundscheck') == True:
         raise NotImplementedError("bounds checking is not supported for CUDA")
+    elif kws.get('boundscheck') == False:
+        kws.pop('boundscheck')

     fastmath = kws.get('fastmath', False)
     if argtypes is None and not sigutils.is_signature(func_or_sig):
```

**Comment by esc** [comment]
Probably, the above patch needs some enhancement as `== True` is not the recommended way to compare to booleans: https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_true.html

I'm labelling this as `good first issue` -- please, anyone with stake in this matter, don't hesitate to grab my patch, upgrade the tests and submit a PR with a fix. Thanks!

**Comment by ttsesm** [comment]
thanks @esc for working on it and @hameerabbasi for the pull request

**Comment by hameerabbasi** [comment]
See #5951, this functionality is partially undocumented and untested. We're still figuring out whether it makes sense.

**Comment by GermanCM** [comment]
Although it does not solve the issue with using the GPU (I am having the same error too), you can still use numba on the CPU and get faster executions:
![image](https://user-images.githubusercontent.com/32896503/86894383-47176680-c103-11ea-861c-2b7214ada821.png)

**Comment by esc** [comment]
I think the preferred/correct way to launch a CUDA kernel would be:

```python
from numba import cuda


@cuda.jit
def func():
    pass
```

Is there any reason this approach can not be used in this case?

**Comment by esc** [comment]
I believe the following variant of the original submission does what you want:

```
from numba import cuda
import numpy as np

# function optimized to run on gpu
@cuda.jit
def func2(a):
    for i in range(10000000):
        a[i]+= 1

if __name__ == '__main__':
    n = 10000000
    a = np.ones(n, dtype=np.float64)

    func2[1, 1](a)
    print(a)
```

**Comment by ttsesm** [comment]
I can verify that the latest provided example from @esc works here without issues as well.

**Comment by gmarkall** [comment]
Closing this as `@jit(target=)` is now deprecated.
