### ISSUE TITLE
np.linalg.pinv Unintended mutation of input

### ISSUE THREAD

**Issue by rjenc29** [numba/numba#5870]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hello all, long time!

The following script (apologies - rather contrived) is an example of a function which does not error when compiled but manages to mutate one of its inputs (not intentionally).

It you call the compiled function with the same inputs many times, you find the mutated input switches from one set of values to another; the 'other' values are very close to the original input values.

Per the note, simply copying the input makes all the assertions pass, as you'd expect.

Just wasn't sure why the input gets modified / why the copy is needed - this might be more of a question than an issue, but it took a while to track down so thought it might be worth posting in case other users find it of interest.

Cheers

Rob

```python
import numpy as np
import pandas as pd
from numba import njit


@njit
def some_fn(alp, v):
    rows, cols = alp.shape
    p = np.empty_like(alp)

    for i in range(rows):
        A_ = v[i]
        b_ = alp[i]

        res = np.linalg.pinv(A_) @ b_

        p[i] = res[:cols]

    return p


if __name__ == '__main__':

    v_data = pd.DataFrame(
        [
            [0.55, -0.21, 0, 0.07],
            [-0.21, 0.48, 0, 0.10],
            [0, 0, 0.31, -0.15],
            [0.07, 0.10, -0.15, 0.51]
        ]
    )

    v_data_original = v_data.copy()

    a_data = pd.DataFrame([[0.1, 0.3, -0.1, 0.05]])

    v = v_data.to_numpy().reshape((1, 4, 4))  # <- using this, the cfunc assertions all fail

    # v = v_data.to_numpy(copy=True).reshape((1, 4, 4))  # <- using this, the cfunc assertions all pass

    a = a_data.values

    # -------- pyfunc

    some_fn.py_func(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # pass

    some_fn.py_func(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # pass

    # -------- cfunc

    some_fn(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # fails (case 1)

    some_fn(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # fails (case 2)

    some_fn(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # fails (case 1)

    some_fn(a, v)
    pd.testing.assert_frame_equal(v_data_original, v_data)  # fails (case 2)
```

* case 1 values are quite different to the original input
* case 2 values are quite similar to the original input

**Comment by stuartarchibald** [comment]
Hi Rob, indeed, it's been a long time, hope things are good with you! Thanks for the report. The depths of my memory suggests I've seen this before in another form, it's something to do with things that are interpreted as 'A' ordered not being copied on entry. xref: https://github.com/numba/numba/issues/3368. 

IR has:
```
    #   $14call_method.6 = call $6load_method.2($12binary_subscr.5, func=$6load_method.2, args=[Var($12binary_subscr.5, issue5870.py:7)], kws=(), vararg=None)  :: (array(float64, 2d, A), omitted(default=1e-15)) -> array(float64, 2d, F)
```
the `pinv` call is on an `'A'` ordered array.


MWR:
```python
import numpy as np
from numba import njit

@njit
def some_fn(v):
    np.linalg.pinv(v[0])


if __name__ == '__main__':

    v_data = np.ones((4, 4), order='F')

    v_orig = v_data.copy()
    reshaped_v = v_data.reshape((1, 4, 4))

    print(v_data)
    print(reshaped_v, "\n", reshaped_v.flags)

    # -------- pyfunc

    some_fn.py_func(reshaped_v)
    np.testing.assert_allclose(v_data, v_orig)  # pass

    # -------- cfunc

    some_fn(reshaped_v)
    np.testing.assert_allclose(v_data, v_orig)  # fail
```

**Comment by rjenc29** [comment]
Thanks very much for confirming, it does indeed look like the same kind of thing - I will make a note (impressive total recall)!
