### ISSUE TITLE
Cannot run on simple for loop

### ISSUE THREAD

**Issue by FiReTiTi** [numba/numba#5881]
Hi,
I've just installed Numba to speed up a simple code (as I was happy with Numba speed up processing time for a previous application):

    @numba.njit
    def _FillVotes(votes, array1, array2, width: int, height: int):
        for y in range(height):
            for x in range(width):
                votes[array1[:,y,x], array2[:,y,x]] += 1

But I get errors when I try to run the code:

    numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    No implementation of function Function(<built-in function getitem>) found for signature:
 
     >>> getitem(array(uint16, 2d, C), UniTuple(array(uint16, 1d, A) x 2))
 
    There are 16 candidate implementations:
      - Of which 14 did not match due to:
      Overload in function 'getitem': File: <built-in>: Line <N/A>.
        With argument(s): '(array(uint16, 2d, C), UniTuple(array(uint16, 1d, A) x 2))':
       No match.
      - Of which 2 did not match due to:
      Overload in function 'getitem': File: <built-in>: Line <N/A>.
        With argument(s): '(array(uint16, 2d, C), UniTuple(array(uint16, 1d, A) x 2))':
       Rejected as the implementation raised a specific error:
         NotImplementedError: only one advanced index supported
      raised from ......./site packages/numba/core/typing/arraydecl.py:65

    During: typing of intrinsic-call at ./FiReTiTiPyLib/Evaluations.py (316)

    File "FiReTiTiPyLib/Evaluations.py", line 316:
    def _FillVotes(votes, array1, array2, width: int, height: int):
        <source elided>
    		for x in range(width):
    			votes[array1[:,y,x], array2[:,y,x]] += 1
       ^

Am I doing something wrong?

**Comment by HPLegion** [comment]
Hi,

if I am interpreting your code correctly, you are using `array1` and `array2` to index into `votes`.
If this is true, then the following may be related:

From the numba docs:
https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#array-access

> Array access
> Arrays support normal iteration. Full basic indexing and slicing is supported. A subset of advanced indexing is also supported: only one advanced index is allowed, and it has to be a one-dimensional array (it can be combined with an arbitrary number of basic indices as well).

So this may be failing because you have two, non-basic indices.

**Comment by FiReTiTi** [comment]
@HPLegion 
Thank you for your answer.
I interpret it the same way, so I think you've found out why it does not work.

Is there any workaround?

**Comment by HPLegion** [comment]
The two things I can think of, off the top of my hat would be to flatten your votes array so that it is 1D, or maybe you can loop over the slice of array2 to combine the advanced index of array1, with a basic index extracted from array2, which according to the docs, should work? - There are probably more clever ways to do this :-P

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.

**Comment by bmabir17-asj** [comment]
@HPLegion I was facing same error while running with jit.
```python
 @staticmethod
    @jit(nopython=True) 
    # @cuda.jit
    def _get_transmission(rows,cols,Alight,src,tran,radius=7, omega=0.95):
        # print("Starting to compute transmission...")
        # start = time.time()
        for i in range(rows):
            for j in range(cols):
                rmin = max(0,i-radius)
                rmax = min(i+radius,rows-1)
                cmin = max(0,j-radius)
                cmax = min(j+radius,cols-1)
                pixel = (src[rmin:rmax+1,cmin:cmax+1]/Alight).min()
                tran[i,j] = 1. - omega * pixel
        # print("time:",time.time()-start)
        return tran
```
Can you help me out how to solve it?
