### ISSUE TITLE
isinstance fails with complex numba types

### ISSUE THREAD

**Issue by andreapiso** [numba/numba#5898]
For example:
```
l = numba.typed.List()
isinstance(l, numba.types.ListType)
```
Returns `False`. 

Complex/Deep types fail altogether:

```
isinstance(l, numba.types.List(numba.types.Array))
```

returns:

```
isinstance() arg 2 must be a type or tuple of types
```

On numba 0.49

**Comment by andreapiso** [comment]
PS the first example returns `True` when in a `@generated_jit` function, while `False` when in the Python interpreter. 

```
l = numba.typed.List()
isinstance(l, numba.types.List)
```

Returns False both in `generated_jit` and python.

**Comment by esc** [comment]
@andreapiso thank you for reporting this and thank you for using Numba. This is a bit tricky to explain, so please forgive me if I am being confusing.

Observe the following:

```
In [1]: import numba

In [2]: l = numba.typed.List()

In [3]: isinstance(l, numba.typed.List)
Out[3]: True

In [5]: lt = numba.types.List(numba.int64)

In [6]: isinstance(lt, numba.types.List)
Out[6]: True
```

What you are seeing is the difference between Python types and Numba types, I guess. `isinstance` checks that a `numba.typed.List` is indeed of type `numba.typed.List`. The `numba.types.List` is the Numba type for the `numba.typed.List`. So, the one from `typed` is the implementation-class and the one from `types` is the type-class. I am not sure, that it makes sense for the implementation class to inherit from the type class, which is what isinstance checks for. 

Equally, if you instantiate a Numba type and then use `isinstance` to check that `numba.types.List` if of (Python) type `numba.types.List`, this will equally succeed. 

For more complex examples this holds equally:

```
In [9]: lat = numba.types.List(numba.types.Array(numba.int64, ndim=1, layout='C'))

In [10]: lat
Out[10]: list(array(int64, 1d, C))

In [11]: type(lat)
Out[11]: numba.core.types.containers.List

In [12]: isinstance(lat, numba.types.List)
Out[12]: True
```

Lastly, I am afraid I don't quite understand your last comment regarding `generated_jit`. Can you please clarify with a code example using `generated_jit` as to what you are seeing. Thanks!

Hope it helps and do let me know if I should expand on any of the above.

**Comment by andreapiso** [comment]
I see, seems my understanding was just partial. My point on generated jit is that sometimes is tricky to understand whether you should use `types.List`, `typed.List` or `typed.ListType` to check types

For example:
```
l = numba.typed.List()
l.append(2)
print(isinstance(l, numba.types.ListType))
print(isinstance(l, numba.types.List))
print(isinstance(l, numba.typed.List))
```

```
False
False
True
```

But:
```
def mock_func(l):
    return l
@numba.generated_jit(nopython=True)
def check_l(l):
    print(isinstance(l, numba.types.ListType))
    print(isinstance(l, numba.types.List))
    print(isinstance(l, numba.typed.List))
    return mock_func
check_l(l)
```
```
True
False
False
```

Which i guess it makes sense as @generated_jit is called at type inference and looks at just the type. But somehow it is easy to think this type should be `types.List` instead of `numba.types.ListType`

**Comment by esc** [comment]
@andreapiso thanks for reporting back. I got confused myself here. There are two type-classes:`numba.types.List` and `numba.types.ListType`. So, the `numba.types.List` is the type-class for the reflected list type. The reflected list is the predecessor of the `numba.typed.List`. We are currently transitioning from the reflected list to the `numba.typed.List` but we expect to take some more time until this is completed. The naming is slightly unfortunate, but we do expect `numba.types.List` to go away at some point or to become an alias for `numba.types.ListType`. 

Beyond that, your analysis of `generated_jit` is correct:

http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html?highlight=generated_jit#numba.generated_jit

Before returning this implementation, we are within a typing context, so the Numba types are passed as arguments indeed.

**Comment by esc** [comment]
So, to clarify, when checking for types in `overload_*` or `generated_jit` use `numba.types.ListType` to check if the argument is a `numba.typed.List`.

**Comment by andreapiso** [comment]
I am still quite confused on the way types work in numba. For example, why does

```
def test():
    print(numba.types.List(numba.types.Array(numba.int64, ndim=1, layout='C')))
```
print the type of the list in the interpreter:
```
list(array(int64, 1d, C))
```

but fails in numba:
```
@numba.njit
def test():
    print(numba.types.List(numba.types.Array(numba.int64, ndim=1, layout='C')))
```
```
Unknown attribute 'List' of type Module(<module 'numba.types' from '/Users/xxx/miniconda3/envs/xxx/lib/python3.7/site-packages/numba/types/__init__.py'>)

File "<ipython-input-102-bd5c691b4449>", line 3:
def test():
    print(numba.types.List(numba.types.Array(numba.int64, ndim=1, layout='C')))
    ^

[1] During: typing of get attribute at <ipython-input-102-bd5c691b4449> (3)

File "<ipython-input-102-bd5c691b4449>", line 3:
def test():
    print(numba.types.List(numba.types.Array(numba.int64, ndim=1, layout='C')))
    ^
```

**Comment by andreapiso** [comment]
Another example: 
```
def test():
    print(numba.types.ListType(numba.types.int64))
```
prints `ListType[int64]`

while

```
@numba.njit
def test():
    print(numba.types.ListType(numba.types.int64))
```

Fails:

```
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<class 'numba.core.types.containers.ListType'>) with argument(s) of type(s): (class(int64))
 * parameterized
In definition 0:
    TypingError: List() argument must be iterable
```

**Comment by stuartarchibald** [comment]
The above issues are from trying to compile instances of the Numba type system type class opposed to the implementation the type is describing.
`numba.types.List*` = type system
`numba.typed.List` = concrete implementation of the type

there's also reflected vs. typed lists involved, see: https://numba.readthedocs.io/en/stable/reference/pysupported.html#list
 
```pycon
In [10]: from numba import types

In [11]: types.ListType(types.int64) # A ListType of type int64
Out[11]: ListType[int64]

In [12]: types.List(types.int64) # A ListType of type int64 (this is reflected list)
Out[12]: list(int64)<iv=None>

In [13]: types.ListType(types.int64) # A ListType of type int64 (this is typed list)
Out[13]: ListType[int64]

In [14]: from numba import types

In [15]: types.List(types.int64) # A List of type int64 (this is reflected list)
Out[15]: list(int64)<iv=None>

In [16]: types.ListType(types.int64) # A ListType of type int64 (this is typed list)
Out[16]: ListType[int64]

In [17]: type(types.List(types.int64)) # it's a Numba type
Out[17]: numba.core.types.containers.List

In [18]: type(types.ListType(types.int64))  # it's a Numba type
Out[18]: numba.core.types.containers.ListType

In [19]: from numba import typeof

In [20]: from numba import typed

In [21]: l = typed.List((1,)) # create an instance of the concrete implementation

In [22]: l
Out[22]: ListType[int64]([1])

In [23]: typeof(l) # it has a Numba *type* of ListType[int64]
Out[23]: ListType[int64]

In [24]: typeof([1,]) # whereas a python list has a Numba *type* of reflected list(int64)
Out[24]: reflected list(int64)<iv=None>
```
Numba can compile the thing the type is describing but it cannot compile Numba types themselves (apart from where they are spelling out e.g. a dtype of a concrete instance, but that's a special case). Numba uses the types to work out what the things in the code are and how they should behave etc.

Am going to close this as assumed resolved. Also, for more general questions, I can recommend asking on the Numba discourse forum https://numba.discourse.group :) Thanks!
