### ISSUE TITLE
cuda: inconsistency between data type specifications in `device_array` and `local.array`

### ISSUE THREAD

**Issue by ShuhuaGao** [numba/numba#5901]
- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

To create `cuda.device_array` of a 32-bit floating-point number type, I can do it as follows:
```python
arr1 = cuda.device_array(100, 'float32')
arr2 = cuda.device_array(100, np.float32)
print(arr1.dtype, arr2.dtype)
```
which prints `float32 float32` as expected.  However, I cannot use `numba.float32` instead:
```python
arr3 = cuda.device_array(100, numba.float32)
````
which yields the error `TypeError: data type not understood`.

By contrast, to create a local array in a Cuda kernel, I have to define it as follows:
```python
@cuda.jit
def test_local_array_kernel():
    arr = cuda.local.array(100, numba.float32)
    print(arr.size)
```
in which neither `np.float32` nor `'float32'` works.  For example, if we use a `np.float32', the following error is produced: 
"type object 'numpy.float32' has no attribute 'is_precise'"

I guess all the above three types refer to the same 32-bit floating-point numbers. Why is there a difference in interfaces of `device_array` and `local.array`? Is it an intentional design?  It would be much better if such an inconsistency can be removed.

**Comment by sklam** [comment]
Thanks for reporting this issue. The difference observed here is due to legacy code. I think we can improve the usability issue here by taking numpy dtype everywhere.

**Comment by gmarkall** [comment]
This actually seems to work now - I've added some tests for it in #6879 to ensure it continues to work. I'm not sure when it started working, though (or why).
