### ISSUE TITLE
cuda.jit does NOT preserve the original __doc__ and __module__ of the decorated function

### ISSUE THREAD

**Issue by ShuhuaGao** [numba/numba#5902]
- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I noticed this issue when using [pdoc3](https://pdoc3.github.io/pdoc/) to generate documentation. `pdoc3` works by extracting the `__doc__` attribute. Consider the following example.
```python
from numba import cuda, jit, njit

@jit
def add1(a: int, b: int) -> int:
    """Add two integers

    Args:
        a (int): one integer
        b (int): the other integer

    Returns:
        int: the sum
    """
    return a + b


@njit
def add2(a: int, b: int) -> int:
    """Add two integers

    Args:
        a (int): one integer
        b (int): the other integer

    Returns:
        int: the sum
    """
    return a + b


@cuda.jit
def add3(a: int, b: int) -> int:
    """Add two integers

    Args:
        a (int): one integer
        b (int): the other integer

    Returns:
        int: the sum
    """
    return a + b


print('add1\n', add1.__doc__)
print('add2\n', add2.__doc__)
print('add3\n', add3.__doc__)
```

Both `add1` and `add2` keep the `__doc__` of the original function. However, `add3` does not.
```
add1
 Add two integers

    Args:
        a (int): one integer
        b (int): the other integer

    Returns:
        int: the sum

add2
 Add two integers

    Args:
        a (int): one integer
        b (int): the other integer

    Returns:
        int: the sum

add3

    CUDA Kernel object. When called, the kernel object will specialize itself
    for the given arguments (if no suitable specialized version already exists)
    & compute capability, and launch on the device associated with the current
    context.

    Kernel objects are not to be constructed by the user, but instead are
    created using the :func:`numba.cuda.jit` decorator.
```
Is it quick or possible to fix this issue? Thank you.

**Comment by ShuhuaGao** [comment]
Following the above issue, I found that `cuda.jit` does NOT preserve the original `__module__,` either.
If we import the above module named `pdoc_tt.py`  and check the `__module__` attribute, we have the following results:
```python
from pdoc_tt import add1, add2, add3

add1.__module__
# 'pdoc_tt'

add2.__module__
# 'pdoc_tt'

add3.__module__
# 'numba.cuda.compiler'
```
Consequently, `pdoc3` does not take `add3` as a function of the module and does not generate documentation for it (aside from the above `__doc__`  issue). 

It seems one possible fix is to use `functools.wraps`, though I am not quite sure (check the related issues in `pdoc3` [here](https://github.com/mitmproxy/pdoc/issues/58))

**Comment by HPLegion** [comment]
I think this is somewhat related to #5755

**Comment by kernc** [comment]
The related pdoc3 issue is https://github.com/pdoc3/pdoc/issues/221.

**Comment by eyaltrabelsi** [comment]
@kernc @sklam I was to work on it, from the description here it sounds like there a need to add functools.wraps to the decorators, am i right?

**Comment by kernc** [comment]
Yeah, `functools.wraps()` should probably be added to all transparent decorators, ever.
