### ISSUE TITLE
operands on datetime64 data types

### ISSUE THREAD

**Issue by MislavSag** [numba/numba#5926]
I don't dows numba support datetime vectorize cmparisons. For example, this doesn;y work for me:
```
@njit
def datetime_operand(date1, date2):
    x = date1 > date2
    return x
d1 = np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172'], dtype='datetime64')
d2 = np.datetime64('2005-02-25T03:40')
datetime_operand(d1, d2)

```
Is this expected and is there something that can be done to make this work?

**Comment by esc** [comment]
@MislavSag thanks for reporting this. Unfortunately, I don't understand your question.

I fixed up the reproducer like this:

```
import numpy as np
from numba import njit


@njit
def datetime_operand(date1, date2):
    x = date1 > date2
    return x


d1 = np.array(['2001-01-01T12:00', '2002-02-03T13:56:03.172'],
              dtype='datetime64')
d2 = np.datetime64('2005-02-25T03:40')
print(datetime_operand(d1, d2))
```

And when I run it, I get:

```
zsh» python issue5926.py
[False False]
```

Maybe you could say, what you expected to happen and what happend instead?

**Comment by MislavSag** [comment]
@esc , sorry I didn't paste the errror message. When I run your example I get the error:
```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
unsupported type for input operand: datetime64[m]

File "", line 3:
def datetime_operand(date1, date2):
    x = date1 > date2
    ^

[1] During: lowering "$6compare_op.2 = arrayexpr(expr=(, [Var(date1, :3), Var(date2, :3)]), ty=array(bool, 1d, C))" at  (3)
```
More infor:
OS: Winodws 10
IDE: VSCode
Python 3.7.6
numba 0.49.1.

**Comment by esc** [comment]
@MislavSag thanks for following up. I am able to reproduce this with Numba version 0.49.1. This is fixed with Numba version 0.50.1 which was released yesterday. Can you try to upgrade and see if it is still broken for you?

**Comment by MislavSag** [comment]
If I use:
`conda update numba`
or 
`conda install -c numba numba`
it installs versin 0.49.
If I install dev version it installs version 0.50

How to isntall 0.51?

**Comment by MislavSag** [comment]
I confirm ity works with numba 0.50.1

**Comment by esc** [comment]
@MislavSag excellent, thank you for following up and closing the issue!
