### ISSUE TITLE
Support for exec() at precompile time

### ISSUE THREAD

**Issue by mha-py** [numba/numba#5931]
Hi!

When I use exec('y = x**n') inside a function which i put a jit decorator before, it tries to jit the function including the exec() function (i. e. it wants to exec at runtime). Instead I'd wish that it does the exec, and then compiles the resulting function... which should be possible if many cases. Example:
```python

n = 3
@jit
def f(x):
    # stuff
    exec(n * 'x = x**2\n')
    # other stuff
```
which i want to work like
```python

@jit
def f(x):
    x = x**2
    x = x**2
    x = x**2
    return x
```
At the moment, it will first jit, then exec, instead of first exec and then jit. Lets call it precompile and postcompile exec...
This example is silly, but I have an example where code like "a[2] = c2" etc. could be avoided with the above idea

**Comment by esc** [comment]
@mha-py thank you for submitting this. As a workaround, you could use the following `exec` based construct:

https://github.com/numba/numba/blob/master/numba/tests/test_typedlist.py#L612-L619

This should allow you to generate the function you need and then call it from your `@njit` decorated function.

**Comment by mha-py** [comment]
I'll try that out, thank you!

**Comment by esc** [comment]
@mha-py great, thanks for reporting back! Good luck and do let us know the results.
