### ISSUE TITLE
Wrong result with np.linalg.inv for 1x1 size, modifies input in-place

### ISSUE THREAD

**Issue by pv** [numba/numba#5933]
Numba jit-compiled np.linalg.inv modifies its input argument when it is an 1x1 view to a different array.
(Versions used: numba 0.50.1, numpy 1.19.0, scipy 1.5.0).

The following code fails:
```
import numpy as np, scipy
import numba

@numba.jit
def bug(a):
    return np.linalg.inv(a[:1,:1])  # Modifies a, but should not!

a = np.array([[0.5]], dtype=np.float_)
b = bug(a)
print(numba.__version__, np.__version__, scipy.__version__)
assert a.item() == 0.5, (a, b)
```
with output
```
0.50.1 1.19.0 1.5.0
Traceback (most recent call last):
  File "repro.py", line 11, in <module>
    assert a.item() == 0.5, (a, b)
AssertionError: (array([[2.]]), array([[2.]]))
```
Note that the content of `a` is overwritten by its inverse. The issue does not occur if `a[:1,:1]` above is replaced by `a`.

**Comment by stuartarchibald** [comment]
Thanks for the report. https://github.com/numba/numba/pull/5879 fixes.
