### ISSUE TITLE
numba -s fails with: AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by bitsisbits** [numba/numba#5947]
I just installed numba and was verifying the installation with "numba -s" which gave the error:

```
(numba_roc) tony@tonga:~$ numba -s
...
__ROC information__
ROC Available                                 : True
ROC Toolchains                                : ['librocmlite library', 'ROC command line tools']
HSA Agents Count                              : 2
HSA Agents:
Traceback (most recent call last):
  File "/usr/local/envs/numba_roc/bin/numba", line 11, in <module>
    sys.exit(main())
  File "/usr/local/envs/numba_roc/lib/python3.8/site-packages/numba/misc/numba_entry.py", line 47, in main
    display_sysinfo()
  File "/usr/local/envs/numba_roc/lib/python3.8/site-packages/numba/misc/numba_sysinfo.py", line 660, in display_sysinfo
    print(*tuple(fmt % ('\t' + k, v) for (k, v) in d.items()),
AttributeError: 'str' object has no attribute 'items'
```

The code in numba/misc/numba_sysinfo.py starting at line 406 is:
```
           agents += {
                'Agent id': i,
                'Vendor': decode(agent.vendor_name),
                'Name': decode(agent.name),
                'Type': agent.device,
            }
```

and should be:
```
            agents.append( {
                'Agent id': i,
                'Vendor': decode(agent.vendor_name),
                'Name': decode(agent.name),
                'Type': agent.device,
            })
```
Kind regards,
Tony

**Comment by esc** [comment]
@bitsisbits thanks for reporting this! I have update the issue report with some markdown syntax formatting to increase legibility. For future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by esc** [comment]
I don't think I can reproduce this faithfully, as I don't have any HSA agents available:

```
HSA is not currently supported on this platform (darwin).
```

**Comment by esc** [comment]
@bitsisbits judging from what you suggest, I tried:

```
>>> l = []
>>> l += {'a': 1}
>>> l
['a']
>>> l.append({'a': 1})
>>> l
['a', {'a': 1}]
>>>
```

Looking at the error message you received I believe the fix is good! Would you be able to submit a pull-request? We will find a machine with ROC to test  this on for such a PR.

**Comment by bitsisbits** [comment]
Pull request created: #5949

**Comment by bitsisbits** [comment]
Yes, I am very new to github so thanks for cleaning that up.  I did make a
pull request but I suspect that I should have created one for a new branch
or will the one in  0.11_maintenance be sufficient?

Thanks.
Tony

**Comment by esc** [comment]
@bitsisbits I think the branch should target the current `master` branch instead.

**Comment by esc** [comment]
And thanks for opening that PR, it is much appreciated!

**Comment by bitsisbits** [comment]
I think that I finally clicked on enough things to get a proper pull
request:  Update numba_sysinfo.py #5956

Kind regards,
Tony

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/5956, thanks, closing.
