### ISSUE TITLE
Decide whether or not to support the target kwarg in the numba.jit decorator

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#5951]
In a couple of issues, e.g. #5868, users have reported that using the `target=` kwarg for the `numba.jit` decorator doesn't always work. While this isn't documented on the website ([website docs](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#numba.jit)), it is documented in the docstring, and so anyone running `numba.njit?` in `ipython` or Jupyter will find it. An excerpt from the docstring is below:
```
    target: str
        Specifies the target platform to compile for. Valid targets are cpu,
        gpu, npyufunc, and cuda. Defaults to cpu.
```

So, there is a decision to be made. Does the Numba team support the kwarg (which means writing tests, fixing up bugs etc.), or not (which means deprecation and removal).

**Comment by stuartarchibald** [comment]
Thanks for raising this. I think e.g. `'gpu'` is not a target, the rest are valid as there are function registries for these and we should see if they working/if it makes sense for the code path to exist.
