### ISSUE TITLE
Move doc links over to RTD

### ISSUE THREAD

**Issue by seibert** [numba/numba#5954]
Now that we have an [RTD page for docs](https://numba.readthedocs.io/en/latest/), we should link to it from the [Numba homepage](https://numba.pydata.org/).  This is the reminder to do the steps:

* [x] Wait for 0.51.0 to be tagged
* [x] Ensure that 0.51.0 docs are built on RTD
* [x] Make 0.51.0 tag the "stable" version (if it doesn't happen automatically)
* [x] Update RTD config in Advanced Options to default to "stable" version rather than "latest" (which is repo master and not released)
* [x] Update index.html in [numba/numba-webpage](https://github.com/numba/numba-webpage) to link to RTD.
* [x] Manually regenerate numba.pydata.org by running gh-pages script in numba-webpage repo and pushing from the gh-pages subdirectory.

**Comment by sklam** [comment]
Done
