### ISSUE TITLE
0.50.1 missing source distribution on PyPI

### ISSUE THREAD

**Issue by moubctez** [numba/numba#5966]
Numba 0.50.1 is missing source distribution on PyPI. Please, provide one. Thank you.

**Comment by stuartarchibald** [comment]
Thanks for the report. Should be there now, any chance you could please confirm. Thanks again!

**Comment by moubctez** [comment]
I got the source code and updated Numba on PkgSrc (http://pkgsrc.org). Cheers.

**Comment by stuartarchibald** [comment]
Thanks for confirming.
