### ISSUE TITLE
test_cos does not match exactly on win32

### ISSUE THREAD

**Issue by sklam** [numba/numba#597]
Test is skipped for release https://github.com/numba/numba/commit/0e7e6b97e0e49c2c70d1e6a3d96e00d2517dd4ce

**Comment by seibert** [comment]
With all the changes (and now that Win7 is our minimum supported Windows), we should reverify this.

**Comment by sklam** [comment]
It's currently skipped in win32:

https://github.com/numba/numba/blob/master/numba/tests/test_mathlib.py?utf8=%E2%9C%93#L237-L241
