### ISSUE TITLE
Add note to docs about boundschecking being off by default and how to switch it on

### ISSUE THREAD

**Issue by ludaavics** [numba/numba#5970]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba as nb
import numpy as np

def foo():
    return np.zeros(5)[6]

foo()  # raises IndexError
nb.jit(foo)()   # returns something
nb.njit(foo)()  # returns something

```

I would have expected compiled code to also raise an exception? 
If I am missing some subtlety in numba behavior, perhaps needs to be added [here](https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html#) ?

Took me a while to figure out an off-by-one error.

**Comment by stuartarchibald** [comment]
Thanks for the report. Numba supports bounds checking but it's opt-in in the `jit` decorators via the kwarg `boundscheck=True`, docs: http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html?highlight=boundscheck#numba.jit

Example
```python
from numba import njit
import numpy as np
@njit(boundscheck=True)
def foo():
  return np.zeros(5)[6]
foo() # raises IndexError
```

A PR with an addition to note that bounds checking is off by default and how to switch it on [in this doc](https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html) would be welcomed if you have time, thanks!

**Comment by ludaavics** [comment]
Ah, it all makes sense now, thanks for clarifying.
Will open a PR.
