### ISSUE TITLE
Incorrect results from (deterministic) prange loop

### ISSUE THREAD

**Issue by jason-levy** [numba/numba#5979]
## Reporting a bug

This seems sufficiently different from https://github.com/numba/numba/issues/5942 that I'm bringing it up as a separate issue.

First, a case where the array doesn't seem to be read correctly:
```
import numba as nb
@nb.njit(parallel=True)
def f():
    for k in nb.prange(5):
        X = [0]
        X[0] = 1
        print(k, X, X[0])
```

Actual:
```
>>> f()
4 [1] 0
0 [1] 0
3 [1] 0
2 [1] 0
1 [1] 0
```
Expected: lines of the form `k [1] 1`

Next a case where the array doesn't seem to be written to correctly.
```
import numba as nb
@nb.njit(parallel=True)
def f(n):
    for k in nb.prange(n):
        X = [0]
        print(k, X)
        for j in range(1):
            X[j] = 1
```
It seems that in each thread the array X doesn't get re-initialized to [0].
<details>

```
>>> f(2*8+1)  # my machine has 8 threads.
0 [0]
2 [0]
3 [1]
8 [0]
9 [1]
14 [0]
4 [0]
1 [1]
12 [0]
15 [1]
6 [0]
5 [1]
10 [0]
13 [1]
7 [1]
11 [1]
16 [1]
>>> 
```
The order of the lines will change but the values do not.
</details>

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bug, and probably the same bug in both cases.

Case 1:
```python
import numba as nb
@nb.njit(parallel=True)
def f():
    for k in nb.prange(5):
        X = [0]
        X[0] = 1
        print(k, X, X[0])

f()
```
I think what's happening is that the `build_list` of `X = [0]` is being hoisted as loop invariant when it ought not be.

Case 2:
```python
import numba as nb
@nb.njit(parallel=True)
def f(n):
    for k in nb.prange(n):
        X = [0]
        print(k, X)
        for j in range(1):
            X[j] = 1

f(3)
```
same as Case 1, think `X = [0]` is erroneously hoisted as loop invariant.

CC @DrTodd13
