### ISSUE TITLE
Passing objects as input of jit.cuda function

### ISSUE THREAD

**Issue by nicolapivaro** [numba/numba#5987]
## Feature request

Hi guys, 
I'm quite new about GPU programming so I'm not sure I'm asking for something feasible but I'll try to introduce you my use case.
I'm trying to use numba to parallelize a code where I'm calling a function several times. The problem is that this function is using an object which has many attributes and methods, so it is a bit complex to transform it into a bunch of subfunctions.
I tried to pass this object as input to a jit.cuda function and if I correctly understood, this is still not implemented. Am I right?
Do you know if there's any trick for this kind of issues?
Thank you,
Nicola

**Comment by gmarkall** [comment]
There's no way to use objects with the CUDA target - it will be necessary to transform the methods into functions, as you suggest. On the CPU target, JIT classes might make the translation easier, but that's not presently implemented for CUDA.

**Comment by nicolapivaro** [comment]
Thank you @gmarkall!
I moved in the direction you suggested. I was using a class because the function I'm working on is power train model, and it has a lot of static attributes like efficiency maps and stuff like that. Implementing the power train as a function forced me to pass each time a lot of inputs (for example maps) and I'm quite sure this is decreasing performances of the execution because at each time I call the GPU function I have to transfer memory from CPU to CPU right? 
Do you know if there is a possible solution to this kind of issue? I was thinking to hardcode these maps as variables inside the function itself. Do you think this is the right way? 
Thank you very much for your help!
Nicola

**Comment by gmarkall** [comment]
If you copy the data to the device first, then you won't get a transfer between the host and device every time you call a kernel. See: http://numba.pydata.org/numba-doc/latest/cuda/memory.html#data-transfer

Ideally you program is structured like:

1. Copy all input data to the GPU
2. Do lots of work on that data in lots of kernels, keeping all intermediate arrays / results on the GPU
3. Copy results back

There are variants of this - for example the above might be wrapped in a loop, but as long as you make sure to do a good chunk of work with data transferred to the GPU, the impact of copying becomes negligible. You can also make asynchronous copies to stream data in / out concurrently with kernel execution, by using pinned memory on the host and copying on a stream (Stream documentation: http://numba.pydata.org/numba-doc/latest/cuda/memory.html#streams )

**Comment by gmarkall** [comment]
BTW, for further discussions about using Numba - the Numba Discourse: https://numba.discourse.group/ is a good place for posting questions (and finding answers to previous questions).

**Comment by gmarkall** [comment]
This seems to be resolved, so closing the issue - for further discussions, please do start a thread on Discourse.
