### ISSUE TITLE
Misleading Documentation for synchronous CUDA Kernel 

### ISSUE THREAD

**Issue by yumasheta** [numba/numba#5992]
I want to suggest a change to the [documentation for CUDA kernel invication](http://numba.pydata.org/numba-doc/latest/cuda/kernels.html#kernel-invocation).
Here it says under the second bullet point:

> By default, running a kernel is synchronous: the function returns when the kernel has finished executing and the data is synchronized back

I think this statement is misleading. For demonstration purposes consider the python script below:
(using the newest python and numba versions)

Here I set up a simple cuda kernel function and time the execution inside python with the timeit library as well as when executing the script with the GNU time command. The results are provided at the end of the file as comments. I marked two lines in the code ( <= (x) ), which are either commented out or not, depending on the test.

```python
"""Test setup for timing cuda kernels to show they work asynchronous."""

from timeit import timeit
import numpy as np
from numba import cuda

@cuda.jit
def matmul(A, B, C):
    """Perform square matrix multiplication of C = A * B."""
    i, j = cuda.grid(2)
    if i < C.shape[0] and j < C.shape[1]:
        tmp = 0.0
        for k in range(A.shape[1]):
            tmp += A[i, k] * B[k, j]
        C[i, j] = tmp


a = np.linspace(0, 10000, int(1e6), dtype=np.float32).reshape(1000, 1000)
b = np.linspace(0, 10000, int(1e6), dtype=np.float32).reshape(1000, 1000)
c = np.empty((1000, 1000), dtype=np.float32)

a = cuda.to_device(a)
b = cuda.to_device(b)
c = cuda.to_device(c)

threadsperblock = (16, 16)
blockspergrid_x = int(np.ceil(a.shape[0] / threadsperblock[0]))
blockspergrid_y = int(np.ceil(a.shape[1] / threadsperblock[1]))
blockspergrid = (blockspergrid_x, blockspergrid_y)
# first call to compile
matmul[blockspergrid, threadsperblock](a, b, c)
r = c.copy_to_host()

def run_test():
    """Cuda kernel launch and sync for ease of use."""
    matmul[blockspergrid, threadsperblock](a, b, c)
    # cuda.synchronize()  # <= (1)


time = timeit("run_test()", "from __main__ import run_test; gc.enable()", number=1000)
# r = c.copy_to_host()    # <= (2)

print(time)


# results:
# #######

# without (1) or (2)
# $ /bin/time -f "real: %e" python test_sync/numba_test.py
# 0.10445902400169871
# real: 1.83

# without (1)
# $ /bin/time -f "real: %e" python test_sync/numba_test.py
# 0.10325762899810798
# real: 19.63

# without (2)
# $ /bin/time -f "real: %e" python test_sync/numba_test.py
# 19.046607808999397
# real: 19.71

# with (1) and (2)
# $ /bin/time -f "real: %e" python test_sync/numba_test.py
# 19.109487649002403
# real: 19.78
```

## Results
From the results it is clear, that the cuda kernel is only synchronous when actively calling `cuda.synchronize()`. What is more, if the data the GPU is working on never gets accessed on the host, the whole script will terminate instantly. If acessing the data, eg. by copying it back to the host, then the single kernel invocations are still asynchronous, but the whole script will return only after the calculations are done.
Now, I do understand, that never synchronizing back the data does not make sense in applications, but for profiling and timing (as shown in the example above) it may be justified. However, this does not change my problem with the wording of the documentation.

To be clear: I do not think this behaviour is a bug!
I think the documentation should be changed to reflect, that the kernel will work asynchronous, if the data is not synchronized back immediately.
My suggestion for the documentation:

> By default, running a kernel is asynchronous: the function returns immediately. Only if the data that is accessed by the kernel is synchronized back, either manually or implicitly when passing an input array that resides in host memory, the kernel will be synchronous. Use [`cuda.synchronize()`](http://numba.pydata.org/numba-doc/latest/cuda-reference/host.html#numba.cuda.synchronize) if you want to force synchronous kernels regardless of this condition. Note: if you manually manage device memory (eg. use [cuda.to_device(h_arr) and d_arr.copy_to_host()](http://numba.pydata.org/numba-doc/latest/cuda-reference/memory.html#memory-management) ) the kernel function itself will be asynchronous, but the act of copying the data to or from the device will be synchronous.

(Please consider the fact, that I am not native in english and this is just a suggestion open for discussion.)

## Additional thoughts:
I did not test the case for kernels returning values. I would reckon the same as for implicit memory management will apply.
I did not test how streams affect this problem.

Thank you very much!

**Comment by sklam** [comment]
@yumasheta, i like your suggestion. Do you want to open a PR to apply your proposed change?

**Comment by yumasheta** [comment]
Sure thing!
I have a questions though:

1. what about my "additional thoughts"? That cases do not get mentionend in my proposed rephrasing.

**Comment by yumasheta** [comment]
#6013
