### ISSUE TITLE
Updating 1d array with 0d array fails

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#6000]
## Reporting a bug

I tried writing data to an output array that was created in a Numba-compiled function. This failed under some conditions, where a 1d array needed to be populated with a 0d array. A minimal working example is:
```python
@nb.njit
def f(arr):
    out = np.zeros((1,))
    out[0] = arr
    return out

f(np.array(1.))
# expect output: array([1.])
```
Instead of giving the expected output (which is returned without using numba), I get the following error:
```
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(array(float64, 1d, C), Literal[int](0), array(float64, 0d, C))
```

I here use numba version 0.50.1, which I believe is the current one.

**Comment by sklam** [comment]
Bug comfirmed. This is a problem of failing to use 0d-array, the `np.array(1.)`, as a scalar.

**Comment by david-zwicker** [comment]
Thanks for confirming the bug! Is there any workaround that I could use in the meantime or do I have to wait for a numba release that fixes this?

**Comment by david-zwicker** [comment]
I ended up writing a small wrapper function that turns 0d arrays into scalars:

```python
@nb.generated_jit
def convert_scalar(arr):
    """ helper function that turns 0d-arrays into scalars """
    if isinstance(arr, nb.types.Array) and arr.ndim == 0:
        return lambda arr: arr[()]
    else:
        return lambda arr: arr
```

This helps to avoid the bug, but is obviously not a long-term solution.

**Comment by ziofil** [comment]
PR https://github.com/numba/numba/pull/4516 should fix this issue for good, correct?

**Comment by david-zwicker** [comment]
This bug has been fixed – thanks!
