### ISSUE TITLE
`typed.List` ignores constructor arguments when jitting is disabled

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#6001]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
>>> from numba.typed import List
>>> List([1])
ListType[int64]([1])

>>> from numba import config
>>> config.DISABLE_JIT = True
>>> List([1])
[]  # where did the 1 go?
```

**Comment by esc** [comment]
@eric-wieser thanks for reporting, it's a bug indeed. Probably a good first or second issue for someone, although the `List` construction/initialization is somewhat contrived.

**Comment by eric-wieser** [comment]
Yeah, I'm very puzzled by the arguments to `typed.List.__new__` which I don't seem to be able to actually pass.

**Comment by esc** [comment]
perhaps it is a matter of adding `*args`?

**Comment by gmarkall** [comment]
Maybe worth noting from the [docs for `__new()__`](https://docs.python.org/3/reference/datamodel.html#object.__new__):

> If __new__() is invoked during object construction and it returns an instance or subclass of cls, then the new instance’s __init__() method will be invoked like __init__(self[, ...]), where self is the new instance and the remaining arguments are the same as were passed to the object constructor.
>
> If __new__() does not return an instance of cls, then the new instance’s __init__() method will not be invoked.

**Comment by gmarkall** [comment]
> Yeah, I'm very puzzled by the arguments to `typed.List.__new__` which I don't seem to be able to actually pass, and don't seem to include this argument at all.

I think they were getting swallowed by the `lsttype` kwarg.

**Comment by esc** [comment]
> > Yeah, I'm very puzzled by the arguments to `typed.List.__new__` which I don't seem to be able to actually pass, and don't seem to include this argument at all.
> 
> I think they were getting swallowed by the `lsttype` kwarg.

Do you think we could `isinstance(lsttype)` and then branch on that?

**Comment by gmarkall** [comment]
> Do you think we could `isinstance(lsttype)` and then branch on that?

That feels like overloading a single parameter for different purposes, which I find a bit of an anti-pattern. Isn't it better to ensure `lsttype` is passed as a kwarg? (I note that the change in #7251, which does do this, has passed all tests).
