### ISSUE TITLE
Global Random Seed

### ISSUE THREAD

**Issue by ChristianMichelsen** [numba/numba#6002]
Hi,

First and foremost thanks for a great package!

I have a short question about whether or not it is possible to set a global random seed for numba? 

I have a main file which uses a bunch of numba functions defined in other files. Most of these external numba functions make use of `np.random` and I would thus like to set a global random seed.

I have tried setting `os.environ['PYTHONHASHSEED'] = str(seed)` in the main file, however, this does not work (the numba functions change output from run to run). 
Note that I am running the file through VS Code, so, as far as I know, I cannot set environmental variables in other ways. 

If I define `np.random.seed(seed)` in each of the numba functions (and add the extra variable `seed` to the function), it works. This method, however, is cumbersome and does not seems like the optimal way.

I hope that you can help!

Cheers,

**Comment by stuartarchibald** [comment]
Thanks for the report, glad to hear you like Numba!

From memory, in Numba the RNG seeds are held in thread local storage, so if the code is single threaded it should be possible to call the seed setting function once at the start of the program and then it'll be reproducible across runs. Example:
```python
from numba import njit
import numpy as np

@njit
def set_seed(value):
    np.random.seed(value)


@njit
def foo():
    return np.random.random()

@njit
def bar():
    return np.random.random()

@njit
def baz():
    return np.random.random()

@njit
def call_all():
    return foo(), bar(), baz()

if __name__ == "__main__":
    set_seed(0)
    print(foo())
    print(bar())
    print(baz())
    print(call_all())
```
running this repeatedly:
```
$ python issue6002.py
0.5488135039273248
0.7151893663724195
0.6027633760716439
(0.5448831829968969, 0.4236547993389047, 0.6458941130666561)

$ python issue6002.py
0.5488135039273248
0.7151893663724195
0.6027633760716439
(0.5448831829968969, 0.4236547993389047, 0.6458941130666561)

$ python issue6002.py
0.5488135039273248
0.7151893663724195
0.6027633760716439
(0.5448831829968969, 0.4236547993389047, 0.6458941130666561)
```

**Comment by ChristianMichelsen** [comment]
Oh, cool, I didn't even think it'd be this simple - thanks a lot for the quick reply!

**Comment by jeertmans** [comment]
Hello @stuartarchibald ! Sorry to re-open this but, after digging a bit, it does not seem obvious to me that one needs to wrap the `numpy.random.seed` function with the `jit` decorator to effectively affect the random number generation within jitted functions (correct me if I am wrong).

Indeed, when searching on the internet, the first two pages from Numba's documentation do not mention this (https://numba.pydata.org/numba-doc/latest/cuda/random.html and http://numba.pydata.org/numba-doc/0.22.1/reference/numpysupported.html).

Maybe it is obvious for some people but it was not for me and I lost quite some time trying to understand why my seeding was not working properly :')

Therefore, wouldn't it be a good idea to put some words about this in Numba's documentation ? I think this would help and I would be glad to help you if needed.

I hope this is not a duplicate.

Thanks in advance !

**Comment by jeertmans** [comment]
Thanks for you quick answer @stuartarchibald . It will then work on a PR in the next few days.

**Comment by stuartarchibald** [comment]
> Thanks for you quick answer @stuartarchibald . It will then work on a PR in the next few days.

Great, thanks, much appreciated!
