### ISSUE TITLE
Error hidden when source is not available

### ISSUE THREAD

**Issue by sklam** [numba/numba#6005]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Example:

```python
import numpy as np

from numba import njit, typed, typeof
from numba.core import types
from numba.experimental import structref


@structref.register
class ParticleType(types.StructRef):
    pass


class Particle(structref.StructRefProxy):
    def __new__(cls, pos, mass):
        return structref.StructRefProxy.__new__(cls, pos) # <- didn't provide the required mass argument


structref.define_proxy(Particle, ParticleType, ["pos", "mass"])

Particle(pos=1, mass=2)
```
Because `StructRef`is building the source code dynamically, the `inspect.getsourcelines` will fail in https://github.com/numba/numba/blob/a7c121a6631ba576561bcc6e72a4bfe97151fb4d/numba/core/typing/templates.py#L752

It will be nice to fix this to make `StructRef` error be meaningful

**Comment by stuartarchibald** [comment]
This is what needs fixing:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f9caff486d0>.
could not get source code
```
