### ISSUE TITLE
CPU vs GPU performane comparison for distance calc

### ISSUE THREAD

**Issue by MyraBaba** [numba/numba#6039]
@njit
def srch(compare_desc,  pe_descs, ): #### Process de çoklanabilir diye düşünüyorum
        tupZ = [(1, 18.265, 100, 0.1)]

        for x in range(peo_descs.shape[0]):
            sim = np.dot(compare_desc, pe_descs[x].T)
            if float(dist) < threshold:
                # a_string = people_namesTUPLE[x]
                name_number = x
                a_float = dist
                an_int = x
                small_float = sim
                tupZ.append((name_number, a_float, an_int, small_float))

        return tupZ

pe_desc = nd.random_normal(0, 1, shape=(5000000, 256))
compare_desc=nd.random_normal(0, 1, shape=(1, 256))

above code is running find and at good speed in CPU .

I donw know how to write above for GPU numb version. But is it worth to try ? Is it possibly run faster in GPU ?

Is there nay body can make an GPU/Numba version for above to test speed ? 

BEST

**Comment by gmarkall** [comment]
As this is a question, it would be best to start a thread on the Numba discourse: https://numba.discourse.group

When you post there, could you please post a complete executable sample code? This will make it easier to understand the example and make suggestions for implementing a GPU version. Many thanks!

**Comment by gmarkall** [comment]
Relevant discussion on discourse: https://numba.discourse.group/t/cpu-vs-gpu-version/138

Closing this issue as the discussion continues there.
