### ISSUE TITLE
CUDA: Add runtime version to `numba -s`

### ISSUE THREAD

**Issue by sklam** [numba/numba#6040]
## Feature request

With https://github.com/numba/numba/pull/5819 highlighting that Runtime API version is needed in additional to the Driver API version, i think we should add the Runtime version in `numba -s` along with https://github.com/numba/numba/blob/b3c5bcbaca955c544d06778ec778f8c62f89b60c/numba/misc/numba_sysinfo.py#L346-L368

**Comment by PhanatosZou** [comment]
@gmarkall @sklam Hi, I would like to work on this feature, but I'm new here and would like to request some help in guiding to start working on this feature. Thanks in advance!

**Comment by stuartarchibald** [comment]
@PhanatosZou thanks for wanting to work on this, Numba's contributing guide is here https://numba.readthedocs.io/en/stable/developer/contributing.html and the file to be edited is that noted in the above.

**Comment by PhanatosZou** [comment]
@stuartarchibald Thank you so much for the information. I'll check it out.

**Comment by rawwar** [comment]
Since this is open, I want to take it up. What should be the output format? Cuda runtime is returned as `1000 major + 10 minor`. So, should the output be `11.2` for `11020` for Cuda runtime 11.2?

**Comment by gmarkall** [comment]
@rawwar It can - thanks for the reminder! :-)
