### ISSUE TITLE
Passing in dtype to array fails on NumPy master in pip-installed version

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#6041]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Please note that this doesn't happen on the conda-installed version, only pip-installed**

```python
import numba
import numpy as np

dt1 = np.dtype("float64")
dt2 = np.dtype("float64")

dtr = np.result_type(dt1, dt2)

@numba.jit(
    nopython=True,
    nogil=True,
    locals={"data_curr": numba.np.numpy_support.from_dtype(dtr)},
)
def _dot_coo_coo(coords1, data1, coords2, data2):  # pragma: no cover
    return np.empty((0,), dtype=dtr)

coords1 = np.array([], dtype=np.int64).reshape((2, 0))
coords2 = coords1

data1 = np.array([], dtype=dt1)
data2 = data1

_dot_coo_coo(coords1, data1, coords2, data2)
```

Output
```
Traceback (most recent call last):
  File "sandbox.py", line 23, in <module>
    _dot_coo_coo(coords1, data1, coords2, data2)
TypeError: expected dtype object, got 'numpy.dtype[float64]'
```

Original issue by @TomAugspurger in pydata/sparse#383

```
Package    Version
---------- -------------------
llvmlite   0.33.0
numba      0.50.1
numpy      1.20.0.dev0+1ce5457
pip        20.1.1
scipy      1.5.2
setuptools 49.2.0
sparse     0.10.0
wheel      0.34.2
```

**Comment by gmarkall** [comment]
I can reproduce this with a pip-installed and conda-installed Numba - to test the conda-installed Numba I did have to install it, force removal of `numpy` and `numpy-base`, then build and install NumPy master from source, but I see the same TypeError in this case as well as with the pip-installed Numba.

**Comment by seibert** [comment]
If there is an ABI change, this presents an interesting issue as we haven't had to pin Numba packages to a specific NumPy range for as long as I can recall.  We can build multiple variants of Conda packages, but I'm not sure how one would ship wheels for both pre and post numpy 1.20.

**Comment by hameerabbasi** [comment]
IIRC, @seberg said that things compiled for new should work on old automatically.

**Comment by eric-wieser** [comment]
Actually, this is a API change followed by an ABI change. the following things happened:

* 1.18.0: https://github.com/numpy/numpy/commit/6108b5d1e138d07e3c9f2a4e3b1933749ad0e698, `PyArray_DescrCheck` now accepts subclasses
* 1.20.0: `np.dtype` now produces subclasses

This means that building numba against `numpy < 1.18.0` but running against `numpy >= 1.20.0` fails.

**Comment by seberg** [comment]
Right, when I did the first change, I thought we could in theory backport the macro, but that its probably not worth the trouble, since basically it is a single C-API call (even though slightly faster-paths are imaginable, I guess).

**Comment by stuartarchibald** [comment]
Note from Numba core dev meeting, preference is to fix up Numba's use of the macro so as to not have to move NumPy base versions.

**Comment by seberg** [comment]
Thanks, sorry for missing to give a heads-up. I had probably noticed the use in Numba at the time.  Yes, I think its the best solution. If we end up having more such things, we could consider backporting such header only changes to have canonical (old) versions to compile against, but I think its not too helpful here.

**Comment by stuartarchibald** [comment]
@seberg no worries, we can patch around it.

**Comment by stuartarchibald** [comment]
Is this the place to get NumPy nightlies still: https://anaconda.org/scipy-wheels-nightly/numpy/files ?

**Comment by eric-wieser** [comment]
Perhaps also worth raising that this elevated `Array` to the status of an object with a boxer than can fail, which results in the same `SystemError` as in #5693.
