### ISSUE TITLE
Cube Root Intrinsic for CUDA

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6051]
## Feature request

For those working with things that happen across calendars, things are often taken to the 1/12th, which is sqrt(sqrt(cbrt())). It would be really awesome if cuda.cbrt mapped to numpy.cbrt.

**Comment by gmarkall** [comment]
An example extension that implements a `cbrt` function for scalars is described here: https://numba.discourse.group/t/cuda-building-extensions-to-call-libdevice-functions-cube-root-example/140 as a workaround.

**Comment by c200chromebook** [comment]
Sweet! Thanks.

**Comment by gmarkall** [comment]
The libdevice cube root intrinsic is added in #6152.
