### ISSUE TITLE
Numba disregards the first element of the output list, using simple python range

### ISSUE THREAD

**Issue by dizcza** [numba/numba#6053]
This is my first try of using numba. Strange that it has such profound bugs in parsing simple python code.

## Reporting a bug

```python
@numba.njit()
def compute(n=10):
    res = [0.]
    for i in range(n):
        res.append(i)
    return np.array(res, dtype=np.float32)
```

With the `numba.njit` decorator the output is `[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]`.
Without the decorator the (correct) output is `[0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]`

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

numba ~v0.51.0~ 0.50.1, installed with conda.

**Comment by esc** [comment]
@dizcza thanks for reporting this, a very interesting bug you found there. I believe it has something to do with the `np.array` constructor. If I run the following (which uses integers however):

```
import numba


@numba.njit()
def compute(n=10):
    res = [0]
    for i in range(n):
        res.append(i)
    return res


print(compute())
print(compute.py_func())
```

I get the  correct output:

```
[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by sklam** [comment]
i am testing it with current master (6c01e9ab74efb84094c8a443a8635b696f5b2d88) and it is fine:

```python
import numpy as np
import numba


@numba.njit()
def compute(n=10):
    res = [0.]
    for i in range(n):
        res.append(i)
    return np.array(res, dtype=np.float32)


print(compute())
print(compute.py_func())
```

@dizcza, you said you installed v0.51.0 but we haven't release that version yet. Did you use one of our dev builds?

**Comment by sklam** [comment]
0.50.1 tag is also fine.

**Comment by dizcza** [comment]
I ran `conda install numba`

**Comment by dizcza** [comment]
Ah sorry, my version is 0.50.1

**Comment by sklam** [comment]
Thanks for the clarification.

I am now able to replicate it on master as well. It's a problem specific to Python 3.8. I was using Python 3.7 before and it has no problem.

**Comment by sklam** [comment]
Marking this bug a highpriority because incorrect result is the worst kind of bug.

**Comment by esc** [comment]
Yes, I can confirm that I am unable to reproduce this with Python 3.7, so it seems to be a 3.8 issue only issue.
