### ISSUE TITLE
Direct construction of typed list from an existing Python list is undocumented

### ISSUE THREAD

**Issue by rht** [numba/numba#6060]
I noticed that the feature (since 0.49.1) where a typed list can be constructed from an existing Python list is not yet documented in https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#typed-list. I became aware of the feature through the answer of this [Stackoverflow question](https://stackoverflow.com/questions/60186698/create-a-numba-typed-list-without-looping-over-a-python-list)
i.e.
```python
py_list = [2,3,5]    
number_list = numba.typed.List(py_list)
```
This feature does help a lot in improving code readability, so, would be nice if it is documented.

**Comment by esc** [comment]
@rht thanks for bringing this to our attention, I have marked it as a feature request for the docs. Note: we do welcome pull-requests and this is probably a good first issue.
