### ISSUE TITLE
Shared memory persists between kernel launches

### ISSUE THREAD

**Issue by zhihaoy** [numba/numba#6076]
Shared memory should be deallocated after each kernel launches.  But in the following example

```python
import numba
from numba import cuda
import numpy as np

@cuda.jit('void(float64[:], float64)')
def k(y, x):
    l = cuda.shared.array(4, np.float64)
    if cuda.threadIdx.x == 0:
        print(l[0])
        l[0] += x
        y[0] = l[0]  # don't optimize away l


def f(x):
    y = np.empty(4)
    k[1, 1](y, x)

if __name__ == '__main__':
    f(10.)
    f(900.)
    f(5000.)
```

```
0.000000
10.000000
910.000000
```

are printed.

Python 3.7.7 :: Intel(R) Corporation
numba-0.50.1
Microsoft Windows [Version 10.0.19041.421]

**Comment by stuartarchibald** [comment]
Thanks for the report. @gmarkall will likely be able to provide a more thorough explanation, but it seems to me like what you are seeing is just a result of getting uninitialized memory and reading from it and it just so happens that subsequent launches gives the same bit of uninitialized memory back (which happens to have the previous written values written in it). As an example, this writes `0xcafe` into the shared array on the first run which puts a known value into the "uninitialized" memory region and then doesn't on the next two:
```python
import numba
from numba import cuda
import numpy as np

MARKER = 0xcafe

@cuda.jit('void(float64[:], float64, boolean)')
def k(y, x, mark):
    l = cuda.shared.array(4, np.float64) # This memory isn't zero'd
    if cuda.threadIdx.x == 0:
        if mark:
            l[:] = MARKER
        print(l[0])
        l[0] += x
        y[0] = l[0]  # don't optimize away l


def f(x, marker):
    y = np.empty(4)
    k[1, 1](y, x, marker)

if __name__ == '__main__':
    f(1., True)
    f(10., False)
    f(1000., False)
```
output is:
```
51966.000000 # 0xcafe + 1
51967.000000 # 0xcafe + 1 + 10
51977.000000 # 0xcafe + 1 + 10 + 100
```

**Comment by gmarkall** [comment]
I don't have anything to add to the explanation of what's happening - @stuartarchibald's explanation contains all the relevant details. Your single block happens to get launched on the same SM each time, but in general blocks could be scheduled to any SM, and multiple blocks can be scheduled on an SM, so you also shouldn't rely on shared memory values appearing to persist between blocks / launches.

**Comment by stuartarchibald** [comment]
Thanks for confirming @gmarkall

**Comment by zhihaoy** [comment]
I'm okay with the explanation, but then it is unexpected that local memory is zero-initialized while shared memory is uninitialized.

Is that possible to add the 3rd parameter to `numba.cuda` array factories so that users can immediately be aware of this issue?  For example

```python
m1 = cuda.shared.memory(3, np.float64)                    # uninitialized
m2 = cuda.shared.memory(3, np.float64, fill=0.)  # equivalent to m2 = 0. followed by a syncthreads()
```

**Comment by leofang** [comment]
I think as a general rule of thumb you need to initialize any memory yourself before using it. It could be very likely that the local memory happens to be zero by chance.

**Comment by stuartarchibald** [comment]
I think that this is entirely down to luck, it just so happened some memory in the original case was zero'd, if the original kernel launch took place after doing something that filled the card's memory then I'd expect it to not be zero'd, but again, luck!

@zhihaoy please could you open a feature request for zero-init as an kwarg to promote discussion if that's something you'd find useful? Thanks.

I'm going to close this ticket as resolved as the originally reported issue is, I believe, solved. Thanks all for contributing to the discussion.
