### ISSUE TITLE
numpy max for arrays of several dimensions not implemented for parallelized code

### ISSUE THREAD

**Issue by Micro-Sandworms** [numba/numba#6095]
Hi, 
First of all: GREAT JOB!

I am running into what I think is a bug. This can be reproduced with the following code:

**import numpy as np
import numba as nb

@nb.jit(nopython=True, parallel=True)
def find_maxima_3D_jit():
    package = np.zeros((10, 10, 10)).astype(np.int16)
    for index in range(0, 10):
        z_stack = package[index, :, :]
        B = np.max(z_stack)
    return

find_maxima_3D_jit()**

The program does not crash when any of the following is true:
1- the option parallel=True is removed
2- the function np.max is applied on an array of one dimension: B = np.max(z_stack[0])
3- when the variable z_stack is defined before the loop (for example as a numpy array of zeros)

Thank you for your support!

**Comment by stuartarchibald** [comment]
Thanks for the report, glad you like Numba :) 
The above does demonstrate a bug:
```python
import numpy as np
import numba as nb

@nb.jit(nopython=True, parallel=True)
def find_maxima_3D_jit():
    package = np.zeros((10, 10, 10)).astype(np.int16)
    for index in range(0, 10):
        z_stack = package[index, :, :]
    B = np.max(z_stack)
    return

find_maxima_3D_jit()
```

Gives:
```
  File "<path>/numba/numba/parfors/parfor.py", line 2336, in find_mask_from_size
    result = _find_mask(pass_states.typemap, pass_states.func_ir, arr_def)
  File "<path>/numba/numba/parfors/parfor.py", line 2683, in _find_mask
    raise AssertionError('unreachable')
AssertionError: Failed in nopython mode pipeline (step: convert to parfors)
unreachable
```
cc @DrTodd13

**Comment by stuartarchibald** [comment]
It also seems that both full slice indexes are needed to trigger the problem.

**Comment by sklam** [comment]
I think this is due to me adding the assertion because the branch was never exercised. Now, we found a case that will trigger it.
