### ISSUE TITLE
What's the input of Numba

### ISSUE THREAD

**Issue by czs1886** [numba/numba#6105]
As is described in the doc, the input of Numba is python function bytecode. Does this mean that Numba takes the pyc files as inputs and generate llvm IR as the final output?

**Comment by stuartarchibald** [comment]
Thanks for the question. For the future, Numba's discourse forum is a good place to ask this sort of thing [https://numba.discourse.group](https://numba.discourse.group/).

Numba's compilation chain works from bytecode, where the bytecode comes from doesn't really matter, there doesn't have to be a source file involved, it can just be an `'exec'`d string to get a function. There are lots of intermediate outputs available, including LLVM IR, but the target most users use is (approximately) an ELF object that is wrapped in a function that can be called from Python. There's more information on this here: http://numba.pydata.org/numba-doc/latest/developer/architecture.html

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by czs1886** [comment]
> Thanks for the question. For the future, Numba's discourse forum is a good place to ask this sort of thing [https://numba.discourse.group](https://numba.discourse.group/).
> 
> Numba's compilation chain works from bytecode, where the bytecode comes from doesn't really matter, there doesn't have to be a source file involved, it can just be an `'exec'`d string to get a function. There are lots of intermediate outputs available, including LLVM IR, but the target most users use is (approximately) an ELF object that is wrapped in a function that can be called from Python. There's more information on this here: http://numba.pydata.org/numba-doc/latest/developer/architecture.html
> 
> If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

Thank you so much for your reply！
