### ISSUE TITLE
Building/Using Numba with PTDS enabled

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#6106]
Is it possible to build (or use) Numba with PTDS enabled? What issues (if any) would one encounter when trying this?

ref: https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/

**Comment by seibert** [comment]
I would move this discussion over to #5137.

**Comment by jakirkham** [comment]
Oops, sorry for the dup. Thanks Stan! 😄
