### ISSUE TITLE
Setting an item in a structured type in a device array behaves differently than raw arrays.

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6114]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When you set an item on a device array, if you are using a structured type, the copied variant to the host is modified but the original on the device is not. This is counterintuitive and inconsistent with cudasim behavior (comment out the mapped_arrays to observe).

```python
import numpy as np
import numba as nb
from numba import cuda
from numba.cuda.cudadrv import driver

da_f = cuda.device_array(1)
pa_f = cuda.pinned_array(1)
ma_f = cuda.mapped_array(1)
out_f = cuda.mapped_array(1)
da_f[0] = 3
pa_f[0] = 4
ma_f[0] = 5

@cuda.jit
def whatever_f(i, o):
    o[0] = i[0]


for x in (da_f, pa_f, ma_f):
    whatever_f[1, 1](x, out_f)
    print(out_f)

np_fake_dtype = np.dtype([('one', np.int16), ('two', np.int16)])
nb_fake_dtype = nb.from_dtype(np_fake_dtype)

da = cuda.device_array(1, dtype=nb_fake_dtype)
pa = cuda.pinned_array(1, dtype=nb_fake_dtype)
ma = cuda.mapped_array(1, dtype=nb_fake_dtype)
out = cuda.mapped_array(1, dtype=nb_fake_dtype)
da[0]['one'] = 3
pa[0]['one'] = 4
ma[0]['one'] = 5

cuda.synchronize()
@cuda.jit
def whatever(i, o):
    o[0].one = i[0].one


for x in (da,pa,ma):
    whatever[1, 1](x, out)
    print(out)
```
Yields:
```
[3.]
[4.]
[5.]
[(0, 0)]
[(4, 0)]
[(5, 0)]
```

Compare:
```python
da = cuda.device_array((2, 2))
pa = cuda.pinned_array((2,2))
ma = cuda.mapped_array((2,2))
out = cuda.pinned_array((2,2))
da[0][0] = 3
pa[0][0] = 4
ma[0][0] = 5
cuda.synchronize()
@cuda.jit
def whatever(i, o):
    o[0][0] = i[0][0]


for x in (da, pa,ma):
    whatever[1, 1](x, out)
    print(out[0][0])
```
Which yields the more intuitive 3,4,5.

**Comment by esc** [comment]
@gmarkall or @testhound : would either of you have a minute to look at this one? Thank you.

**Comment by gmarkall** [comment]
Indeed, this is inconsistent and a bit weird. Marking as a bug.

**Comment by gmarkall** [comment]
I'll add this to 0.55 as a reminder to take a look after the next RC.
