### ISSUE TITLE
IndexError in _version_info with build from master 

### ISSUE THREAD

**Issue by rpopovici** [numba/numba#6125]
I get this error with custom build from latest master(today's commits)

Steps to reproduce:
1. uninstall numba and llvmlite
2. download numba-master.zip and unzip to folder of your choosing
3. run: python setup.py install
4. install numba master + llvm 0.33 or 0.34 rc
5. load any script, e.g:
```
import numba as nb
print('test')
```
6. IndexError..

**Comment by rpopovici** [comment]
Error report:
```
IndexError                                Traceback (most recent call last)
 in 
----> 1 import numba as nb

~\AppData\Local\Programs\Python\Python37\lib\site-packages\numba-0+unknown-py3.7-win-amd64.egg\numba\__init__.py in 
     33     return _version_info(major, minor, patch, short, full, string, tup,
     34                          git_revision)
---> 35 version_info = _gen_v_info()
     36 del _gen_v_info
     37 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\numba-0+unknown-py3.7-win-amd64.egg\numba\__init__.py in _gen_v_info()
     24             return None
     25     major = try_int(parts[0])
---> 26     minor = try_int(parts[1])
     27     patch = try_int(parts[2])
     28     short = (major, minor)

IndexError: list index out of range
```

**Comment by esc** [comment]
@rpopovici thanks for reporting this, would you be able to attach a debugger and print the value of `parts`?

**Comment by gmarkall** [comment]
Looks like the version is `0+unknown`, which will be causing the issue - it's assumed in `_gen_v_info()` that the version can be split on dots into at least three parts. (IIRC this version number can occur if versioneer couldn't get the info using git).

**Comment by esc** [comment]
May I ask, how was Numba installed?

**Comment by rpopovici** [comment]
@esc downloaded the zip from github, unzip, run the install script.. I didn't use git clone if that's what you are asking

**Comment by rpopovici** [comment]
@gmarkall the version is indeed 0+unknown

**Comment by esc** [comment]
@rpopovici thank you! I can reproduce this on a git checkout, after removing all tags with:

`git tag | xargs git tag -d``

It is correct that `versioneer.py` will traverse the git history to look for the most recent tag and use that to determine the version number (uses `git describe` internally). 

The fix will be to check if the version number can be split and act accordingly if it can't.

**Comment by esc** [comment]
I think in this case, a `version_info` of:

`version_info(major=None, minor=None, patch=None, short=(None, None), full=(None, None, None), string='0+unknown', tuple=('0+unknown',), git_revision=None)`

Is probably the best we can do.

**Comment by esc** [comment]
There is a hotfix in #6126.
