### ISSUE TITLE
Compilation time regressions 0.47-0.51.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6136]
There have been a few reports on `gitter.im` about compilation times having increased across various recent (0.47-latest) versions of Numba. This issue is to track them!

**If you have a compilation time regression please post some reproducing code along with the "fast" compilation environment and the "slow" compilation environment in which it reproduces below!**

Some things that have changed in Numba that may be related (patch releases didn't have anything obvious so are not included):

| Version | Changes from previous version that might impact compile time|
| --------------- | --------------- |
| 0.47.0 |  Large rewrite and update of control flow analysis to accommodate the large bytecode changes in Python 3.8, this increases compilation time slightly. |
| 0.48.0 | Nothing obvious! |
| 0.49.0 | • Numba IR moves to a `ir.Del` free [SSA form](https://en.wikipedia.org/wiki/Static_single_assignment_form) for correctness. This will most likely impact code with large numbers of variables and/or large numbers of blocks. It has the potential to significantly increase compilation time. |
|0.50.0 | • Improved SSA performance (should speed up compilation time vs. 0.49). <br /> • Update backend to LLVM 9. <br /> • For correctness `inline=True` forces full compilation pipeline to run when creating IR to be inlined, this increases compilation time. |
|0.51.0 |  • Switched compilation to prefer non-literal values i.e. `a = 12` would mean `a` is now `int64` type instead of `LiteralInteger(12)`. The impact of this change should be to decrease compilation time unless literal values are required. <br /> • Update backend to LLVM 10. <br />   • For users of `cache=True`, caching is vastly improved but more involved. This may slightly increase compilation time.

**Comment by stuartarchibald** [comment]
CC @luk-f-a @lmcinnes

**Comment by gmarkall** [comment]
E.g.: #6133 from @c200chromebook

**Comment by luk-f-a** [comment]
@stuartarchibald , I've managed to complicate the example enough to see a 20% compilation time difference. Is that enough to be useful? The full example has 100% difference (ie 2x slower).
So far this was tested on Windows, so I will re-test on Linux.

**Comment by stuartarchibald** [comment]
@luk-f-a thanks for doing that, 20% should be enough, please do post :) Thanks again!

**Comment by stuartarchibald** [comment]
Way to reproduce by @lmcinnes here https://gitter.im/numba/numba?at=5f3aa69660892e0c6979923b

**Comment by stuartarchibald** [comment]
With many thanks to @luk-f-a for persisting in figuring out what the issue was. This is a reproducer for one of the performance regressions:
```python
from numba import njit, literal_unroll
import numpy as np

rdt = np.dtype([('FRUIT', 'U5'),
                ('FLOAT', np.float64)], align=True)

@njit
def foo(rec):
    if rec[0]['FRUIT'] == "APPLE":
        return 10
    else:
        return 100

arr = np.array([("APPLE", 2.2,)], dtype=rdt)

foo(arr)
```
due to a bug here:
https://github.com/numba/numba/blob/b9efc8323c4b5915be55b7a375c4b0b8fdd84fef/numba/cpython/unicode.py#L454
where `types.UnicodeCharSeq` is accepted for a function that calls `_cmp_region`:
https://github.com/numba/numba/blob/b9efc8323c4b5915be55b7a375c4b0b8fdd84fef/numba/cpython/unicode.py#L461
which assumes a unicode struct like object such that e.g. `var._length` and `var._kind` are available (in a callee):
https://github.com/numba/numba/blob/b9efc8323c4b5915be55b7a375c4b0b8fdd84fef/numba/cpython/unicode.py#L388-L404
as a result, this path is run and fails a huge number of times.

**Comment by rpopovici** [comment]
**Why this:**

```
from numba import typed, typeof, njit, int64, types, optional, deferred_type
from numba.experimental import jitclass
from numba.extending import overload_method, overload

BagType = deferred_type()

spec = [
    ('max_length', int64),
    ('data', types.ListType(int64)),
    ('child', optional(BagType))
]

@jitclass(spec)
class Bag(object):
    def __init__(self, max_length):
        
        self.max_length = max_length
        self.data = typed.List.empty_list(int64)
        self.child = None
        
    def child_insert(self, value):
        if len(self.data) < self.max_length:
            self.data.append(value)        

    def insert(self, value):
        if len(self.data) < self.max_length:
            self.data.append(value)
        else:
            # self.get_child(self.child, value)
            if self.child is not None:
                # self.child.insert(value) 
                self.child.child_insert(value) # eliminate recursion
            else:
                self.child = Bag(self.max_length) #self.add_child()  
        
    def add_child(self):
        return Bag(self.max_length)

BagType.define(Bag.class_type.instance_type)

@njit
def test():
    mybag = Bag(5)

    print(mybag.data)
    print(mybag.child)

    for i in range(10):
        mybag.insert(i)

    print(mybag.data)
    print(mybag.child)
    print(mybag.child.data)
    
test()
```

**compiles much faster than this:**

```
from numba import typed, typeof, njit, int64, types, optional, deferred_type
from numba.experimental import jitclass
from numba.extending import overload_method, overload

BagType = deferred_type()

spec = [
    ('max_length', int64),
    ('data', types.ListType(int64)),
    ('child', optional(BagType))
]

@jitclass(spec)
class Bag(object):
    def __init__(self, max_length):
        
        self.max_length = max_length
        self.data = typed.List.empty_list(int64)
        self.child = None

BagType.define(Bag.class_type.instance_type)

@overload_method(types.misc.ClassInstanceType, 'child_insert')
def ol_bag_add_child_insert(inst, value):
    if inst is Bag.class_type.instance_type:
        def impl(inst, value):
            if len(inst.data) < inst.max_length:
                inst.data.append(value)
            
        return impl

@overload_method(types.misc.ClassInstanceType, 'insert')
def ol_bag_insert(self, value):
    if self is Bag.class_type.instance_type:
        def impl(self, value):
            print('insert ' + str(value))

            # eliminate recursion here by implementing a fake stack
            stack = typed.List()
            stack.append((self, value))

            while len(stack):
                node = stack[0][0]
                value = stack[0][1]
                stack.pop(0)

                if len(node.data) < node.max_length:
                    node.data.append(value)
                else:
                    if node.child is None:
                        node.child = Bag(node.max_length - 1) #self.add_child() # this works too
                    else:
                        print('child insert')
                        stack.append((node.child, value))
                        # self.child.child_insert(value) # this will work as well because we eliminated the recursion

        return impl

@overload_method(types.misc.ClassInstanceType, 'add_child')
def ol_bag_add_child(inst,):
    if inst is Bag.class_type.instance_type:
        def impl(inst,):
            print('add_child')
            return Bag(inst.max_length - 1)
            
        return impl

@njit
def test():
    mybag = Bag(5)

    print(mybag.data)
    print(mybag.child)

    for i in range(10):
        mybag.insert(i)

    print(mybag.data)
    print(mybag.child)
    print(mybag.child.data)
    
test()
```

They are doing more or less the same thing..

**Comment by stuartarchibald** [comment]
@rpopovici thanks for the report. I was wondering how this is related to compile time regressions between 0.47 and 0.51? Is it perhaps a more general question, if so please could you ask it on [numba.discourse.group](https://numba.discourse.group)? Thanks for your help.

**Comment by rpopovici** [comment]
@stuartarchibald not sure if it's a regression, but I thought that it might be related since jitclasses were literally untouched in the past 7 months or so.. and prefer_literal was added recently to overload methods

Anyway, I will ask there

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved.
