### ISSUE TITLE
Scalars returned from arrays have less attributes in numba than in numpy

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#6155]
I encountered a compilation error when translating numpy code to numba. The issue seems to be that numba returns simple floats when accessing an array while numpy returns its own scalar types that have additional attributes.

A minimal working example demonstrates the issue
```python
def f_np(arr):
    return arr[0].size
f_nb = nb.njit(f_np)

a = np.arange(4)
f_np(a)
# >>> 1
f_nb(a)
# >>> TypingError: Unknown attribute 'size' of type int64
```
Clearly, the code works when a higher dimensional array is supplied as an argument.

I've tested the code on the latest numba version (0.51.0).

**Comment by esc** [comment]
@david-zwicker thanks for reporting this to the Numba issue tracker! I can report that I was able to reproduce this locally.

**Comment by esc** [comment]
@david-zwicker I think this might be related: https://github.com/numba/numba/issues/5990

**Comment by stuartarchibald** [comment]
Pretty sure that this is the issue highlighted in #5990

**Comment by stuartarchibald** [comment]
Thanks for reporting this @david-zwicker, am going to close as I think it's a duplicate, if you feel otherwise please do reopen. Many thanks.
