### ISSUE TITLE
Better error message in `with ... as ...`

### ISSUE THREAD

**Issue by sklam** [numba/numba#6163]
Probably we can catch the error message and give you a better message along the lines of: "Numba is currently unable to compile your code."

_Originally posted by @esc in https://github.com/numba/numba/issues/6142#issuecomment-679160903_

We can catch the NotDefinedError can report a better message that says the compiler failed to analyze the bytecode.

**Comment by abhinavjonnada82** [comment]
Can I get this?

**Comment by esc** [comment]
@abhinavjonnada82 feel free to start working on it and submit a PR!

**Comment by stuartarchibald** [comment]
This was implemented in https://github.com/numba/numba/pull/6185. Closing.

@abhinavjonnada82 thanks for asking, as evident in #6185, this ticket should be closed, apologies for any confusion. If you'd like to contribute to Numba there's a [good first issue](https://github.com/numba/numba/labels/good%20first%20issue) label which contains other issues which might be good to try? Thanks.
