### ISSUE TITLE
Assign np.number its own type for comparisons

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6164]
Currently numba converts `np.number` to `np.float64` for the purposes of creating a type. However there a certain functions where types are passed as arguments and `np.float64` has a different meaning from `np.number`. Often this means that `np.number` should match all numbers but `np.float64` should not.

This is difficult to handle without providing `np.number` a separate type because types are provided by user code.

### Reproducing code example:

```python
import numpy as np
import numba
>>> numba.core.typing.typeof.typeof(np.number)
class(float64)
>>> numba.core.typing.typeof.typeof(np.int32)
class(int32)
>>> numba.core.typing.typeof.typeof(np.float64)
class(float64)
```

**Comment by seibert** [comment]
Can you give an example bit of code where you want to use `np.number`?  The challenge here is that `np.number` matches a range of data types, but itself doesn't have a concrete representation, which is how Numba uses its type system (to select concrete representations in memory).    If you are wanting to use `np.number` in an explicit type signature to a `@jit` function, I can't think of a way to do this now other than providing no signature, and allowing the JIT to specialize for each concrete numeric type that the function is called with.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Comment by njriasan** [comment]
Hi sorry for the lack of response. My use is basically supporting `pandas.DataFrame.select_dtypes`, for which you can find the documentation here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html. However really this usage is simply the ability to compare a type passed by a user to the type of an array at compile time, and then have three different paths, one for equality, one for inequality, and one for comparison to `np.number`. Here is code that would accomplish what I want to do.

```python
import numpy as np
import numba
import numba.core.types as types
from numba.extending import overload


def array_match(arr, user_type):
    return False

@overload(array_match)
def array_match_overload(arr, user_type):
    import pdb; pdb.set_trace()
    if not isinstance(arr, types.Array):
        return
    arr_type = arr.dtype
    utype = user_type.dtype
    # There is no export for np.number but ideally classes could be
    # compared even if the underlying dtype is still float64
    # This clearly doesn't work
    number_type = np.number
    if arr_type == utype:
        return lambda arr, user_type: True
    elif user_type == number_type and isinstance(arr_type, (types.Integer, types.Float)):
        return lambda arr, user_type: True
    else:
        return lambda arr, user_type: False


arr = np.array([1, 2, 1, 4])

@numba.njit
def f(arr):
    print(array_match(arr, np.int64))
    print(array_match(arr, np.bool_))
    print(array_match(arr, np.number))
    print(array_match(arr, np.float64))

f(arr)
```

This code doesn't work of course because `np.number` is not the correct way to get the type described by `np.number`. Ideally `number` could be available inside types so I could compare the classes directly and then the underlying dtype could just be `float64`.
