### ISSUE TITLE
ImportError: cannot import name 'npyimpl'

### ISSUE THREAD

**Issue by bshahid331** [numba/numba#6170]
## Reporting a bug

Before submitting a bug report please ensure that you can check off these boxes:

- [x ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Description**
Error when calling librosa.load, the really odd thing is it works sometimes and sometimes throws this errors(with the same audio files)

**Versions**
numba==0.48.0
librosa==0.7.2
llvmlite==0.31.0

Running Python 3.6.9

I've tried with different audio files

**Stack trace below**

`librosa_data = librosa.load(file_name) File "/home/ubuntu/***/venv/lib/python3.6/site-packages/librosa/core/audio.py", line 172, in load File "/home/ubuntu/***/venv/lib/python3.6/site-packages/librosa/core/audio.py", line 584, in resample File "/home/ubuntu/***/venv/lib/python3.6/site-packages/resampy/core.py", line 120, in resample resample_f(x_2d, y_2d, sample_ratio, interp_win, interp_delta, precision) File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 434, in _compile_for_args File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 367, in _compile_for_args File "/home/ubuntu/auto_dj/venv/lib/python3.6/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 819, in compile File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 78, in compile File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 92, in _compile_cached File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/dispatcher.py", line 110, in _compile_core File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/compiler.py", line 624, in compile_extra File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/compiler.py", line 311, in __init__ File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/base.py", line 283, in refresh File "/home/ubuntu/***/venv/lib/python3.6/site-packages/numba/core/cpu.py", line 66, in load_additional_registries ImportError: cannot import name 'npyimpl'`

Any ideas? I tried searching for this error and couldn't find anything. I can get it to work on OSX but this problem occurs on linux.

**Comment by gmarkall** [comment]
The path `numba/core/cpu.py` did not appear in 0.48.0. How did you determine the Numba version?

Possibly your virtualenv includes code from two different versions of Numba, or is somehow messed up - if you create a new venv and install everything from scratch into it, do you still see the same issue?

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
