### ISSUE TITLE
Importing AOT compiled function in 0.51.0 still requires numba installed

### ISSUE THREAD

**Issue by alex-ong** [numba/numba#6177]
I've got a CI/CD system that uses the latest numba.
I use pyinstaller, and AOT all numba functions, then exclude numba from pyinstaller. This reduces build by around 50MB.
Unfortunately, in numba 0.51.0, importing an AOT function fails, citing that the AOT function requires importing numba.
This is a regression from 0.50.1, which behaved correctly.

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by gmarkall** [comment]
Many thanks for the report - would you be able to provide:

- the traceback when importing the AOT function, and
- Some steps / code to reproduce the issue

please?

**Comment by alex-ong** [comment]
Thanks gmarkall, sorry for not attaching anything useful.

here's a repo. 

https://github.com/alex-ong/numba_aot

Simply run `runme.bat or runme.sh`
it does the following

Runs working version
* install numba 0.50.1
* compiles a function AOT
* uninstalls numba (but leaves llvmlite + numpy)
* runs main.py which imports the AOT function
* This prints out `imported successfully, 100`

Cleans up pip installs
* Uninstalls numba/llvmlite/numpy

Runs nonworking version
* Installs numba 0.51.0
* compiles function AOT
* uninstalls numba (but leaves llvmlite + numpy)
* runs main.py which imports the AOT function
* Fails to import. Stacktrace isn't helpful apart from it saying it wants numba:
```
python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from my_module import multi
ModuleNotFoundError: No module named 'numba'
```

**Comment by gmarkall** [comment]
Thanks for the repo - I can reproduce the issue now.

**Comment by gmarkall** [comment]
The issue appears to have been introduced by this commit: https://github.com/numba/numba/pull/5922/commits/2a6ac69f61058f5d0671679ff39bdb83a55ebf69 in PR #5922.

**Comment by gmarkall** [comment]
@sklam any thoughts on the correct way to proceed with fixing this?

**Comment by gmarkall** [comment]
Following discussion in the triage meeting, the way forward is to fix this issue and add tests that check that AOT-compiled code can be imported without Numba - e.g. by running tests in a subprocess, and checking whether Numba was imported after the test code executes. However, this will not be done in time for 0.51.2, which is scheduled to be tagged tomorrow.

**Comment by alex-ong** [comment]
Thanks! looking forward to eventual fix 👍

**Comment by sklam** [comment]
I can fix it by bypassing `_numba_unpickle` for AOT and falling back to `pickle.loads`
