### ISSUE TITLE
Integer to string conversion is extremely slow

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#6189]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Integer to string conversion (`str(int)`) is extremely slow in Numba (~10x slower than Python and ~100x slower than C). The implementation ([here](https://github.com/numba/numba/blob/0db523ea8e0e5ad95d8a4262b4c9c44b65ecbc25/numba/cpython/unicode.py#L2353)) looks very inefficient since it allocates every single produced character. My guess is that someone copied it from CPython, but unlike Numba, CPython has string interning. The integer to string implementation can be much more efficient. Also, SSO (#3965) can avoid these allocations for many string programs in general.

```python
In [7]: def f(n):
   ...:     c = 0
   ...:     for i in range(n):
   ...:         c += len(str(n))
   ...:     return c
   ...:

In [8]: %timeit f(1000_000)
194 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]: g = numba.njit(f)

In [11]: g(1000_000)
Out[11]: 7000000

In [12]: %timeit g(1000_000)
1.97 s ± 68.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by sklam** [comment]
I can confirm the 10x speed difference.
