### ISSUE TITLE
nested dictionary as attribute of jitclass failed

### ISSUE THREAD

**Issue by rubick1896** [numba/numba#6191]
I was trying to use the jitclass decorator with the following class. I can't see any difference between with my code and the official example of jitclass other than one of my fields is a nested dictionary.

`
@jitclass([('dt', types.int32),
            ('last_index_tick', types.DictType(types.int32, types.DictType(types.unicode_type, types.int64)))])
class TickFeature:
    def __init__(self, dt: int):
        self.dt = dt
        #self.last_index_tick = defaultdict(dict)
        #tmp = numba.typed.Dict.empty(key_type=types.unicode_type, value_type=types.int64)
        self.last_index_tick = numba.typed.Dict.empty(
            key_type=types.int32,
            value_type=types.DictType(types.unicode_type, types.int64) #numba.typeof(tmp)
        )
        self.init_index_tick()

    def init_index_tick(self):
        l = np.array([905, 300, 16, 399005, 399006], dtype=np.int64)

        tmp = numba.typed.Dict.empty(key_type=types.unicode_type, value_type=types.int64)
        '''
        self.last_index_tick = numba.typed.Dict.empty(
            key_type=types.types.int32,
            value_type=types.DictType(types.unicode_type, types.int64)
        )
        '''
        for item in l:
            self.last_index_tick[item] = tmp

`
Here is the error message it gives:

Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'numba.core.types.containers.DictType'>) found for signature:
 
 >>> DictType(typeref[unicode_type], class(int64))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'DictType': File: numba/core/extending.py: Line 37.
        With argument(s): '(typeref[unicode_type], class(int64))':
       Rejected as the implementation raised a specific error:
         TypeError: typer() takes 0 positional arguments but 2 were given
  raised from /home/wenrui29/.opt/anaconda/lib/python3.7/site-packages/numba/core/typing/templates.py:363

During: resolving callee type: Function(<class 'numba.core.types.containers.DictType'>)
During: typing of call at <ipython-input-45-75ce687ed4a7> (10)

File "<ipython-input-45-75ce687ed4a7>", line 10:
    def __init__(self, dt: int):
        <source elided>
            key_type=types.int32,
            value_type=types.DictType(types.unicode_type, types.int64) #numba.typeof(tmp)
            ^

During: resolving callee type: jitclass.TickFeature#7fb893f8e7d0<dt:int32,last_index_tick:DictType[int32,DictType[unicode_type,int64]]>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.TickFeature#7fb893f8e7d0<dt:int32,last_index_tick:DictType[int32,DictType[unicode_type,int64]]>
During: typing of call at <string> (3)

**Comment by sklam** [comment]
Looks like the problem came from this line:

```python
   self.last_index_tick = numba.typed.Dict.empty(
            key_type=types.int32,
            value_type=types.DictType(types.unicode_type, types.int64) #numba.typeof(tmp)
        )
```

Numba does not let you create types inside the jitted code yet. The `types.DictType(types.unicode_type, types.int64)` needs to be lifted out as a global:

Something like below would work:
```python
import numba
from numba import jitclass, types


inner_dict_type = types.DictType(types.unicode_type, types.int64)
@jitclass([('dt', types.int32),
            ('last_index_tick', types.DictType(types.int32, types.DictType(types.unicode_type, types.int64)))])
class TickFeature:
    def __init__(self, dt: int):
        self.dt = dt
        #self.last_index_tick = defaultdict(dict)
        #tmp = numba.typed.Dict.empty(key_type=types.unicode_type, value_type=types.int64)
        self.last_index_tick = numba.typed.Dict.empty(
            key_type=types.int32,
            value_type=inner_dict_type
        )
        # self.init_index_tick()


TickFeature(1)
```

**Comment by rubick1896** [comment]
@sklam Thanks for the help. Is this desired feature or could be changed in the future? I personally feel it counter-intuitive to declare the type of a filed outside an object.

**Comment by esc** [comment]
I seem to recall there may be an open issue about this already, but I was unable to locate it.
