### ISSUE TITLE
String formatting support for dict keys

### ISSUE THREAD

**Issue by rubick1896** [numba/numba#6198]
I cannot find in the doc whether this is supported or not, but the following function does not work.
``` python
@njit
def func():
    res = numba.typed.Dict.empty(
        key_type=types.unicode_type,
        value_type=types.float32
    )

    for item in (905, 300, 16, 399005, 399006):
        base_i = 1.
        open_i = 1.

        i_roc = 2. / base_i
        i_roo = 2. / open_i

        res["log2_i_roc_%d"%(item)] = np.log2(i_roc)

    return res

```

I've tried the .format() function and f-string, non of those properly. Suppose there is a list of data that has to be passed to the function and the dict key depends on this data, what is the best solution based on the current version of numba?

**Comment by gmarkall** [comment]
The list of supported operations on strings is at: https://numba.readthedocs.io/en/stable/reference/pysupported.html#str - string formatting is not supported.

In your example the string only varies by `item` - is it possible to use a dict with integer keys in your case?

**Comment by rubick1896** [comment]
@gmarkall 
According to the doc, both str(int) and string concatenation should work. If I just do 

`
@njit
def func():
    res = numba.typed.Dict.empty(
        key_type=types.unicode_type,
        value_type=types.float32
    )

    for item in (905, 300, 16, 399005, 399006):
        base_i = 1.
        open_i = 1.

        i_roc = 2. / base_i
        i_roo = 2. / open_i

        name = "log2_i_roc_" + str(item)
        res[name] = np.log2(i_roc)

    return res
`
It should work, right? But it gives this:

Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'str'>) found for signature:
 
 >>> str(int64)
 
There are 4 candidate implementations:
  - Of which 4 did not match due to:
  Overload of function 'str': File: <numerous>: Line N/A.
    With argument(s): '(int64)':
   No match.

During: resolving callee type: Function(<class 'str'>)
During: typing of call at <ipython-input-19-cf2c46f2ab4c> (15)

**Comment by gmarkall** [comment]
What is the output of `numba -s`? For me, the following:

```python
from numba import njit, types, void
from numba.typed import Dict
import numpy as np


@njit
def func():
    res = Dict.empty(
        key_type=types.unicode_type,
        value_type=types.float32
    )

    for item in (905, 300, 16, 399005, 399006):
        base_i = 1.

        i_roc = 2. / base_i

        name = "log2_i_roc_" + str(item)
        res[name] = np.log2(i_roc)

    return res

print(func())
```

produces:

```
repro.py:19: NumbaTypeSafetyWarning: unsafe cast from float64 to float32. Precision may be lost.
  res[name] = np.log2(i_roc)
{log2_i_roc_905: 1.0, log2_i_roc_300: 1.0, log2_i_roc_16: 1.0, log2_i_roc_399005: 1.0, log2_i_roc_399006: 1.0}
```

**Comment by rubick1896** [comment]
Is this the info you need?

System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2020-09-01 17:26:44.471096
UTC start time                                : 2020-09-01 09:26:44.471106
Running time (s)                              : 10.864031

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake-avx512
CPU Count                                     : 20
Number of accessible CPUs                     : 20
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 avx512bw
                                                avx512cd avx512dq avx512f avx512vl
                                                bmi bmi2 clflushopt clwb cmov cx16
                                                cx8 f16c fma fsgsbase fxsr invpcid
                                                lzcnt mmx movbe mpx pclmul popcnt
                                                prfchw rdrnd rdseed rtm sahf sse
                                                sse2 sse3 sse4.1 sse4.2 ssse3
                                                xsave xsavec xsaveopt xsaves

Memory Total (MB)                             : 128615
Memory Available (MB)                         : 83664

__OS Information__
Platform Name                                 : Linux-4.15.0-108-generic-x86_64-with-debian-buster-sid
Platform Release                              : 4.15.0-108-generic
OS Name                                       : Linux
OS Version                                    : #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020
OS Specific Version                           : ?
Libc Version                                  : glibc 2.10

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.7.4
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 9.0.1

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 10020
CUDA Detect Output:
Found 2 CUDA devices
id 0    b'GeForce GTX 1080 Ti'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 23
id 1    b'GeForce GTX 1080 Ti'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 101
Summary:
        2/2 devices are supported

CUDA Librairies Test Output:
Finding cublas from Conda environment
        named  libcublas.so.10.2.2.89
        trying to open library...       ok
Finding cusparse from Conda environment
        named  libcusparse.so.10.3.1.89
        trying to open library...       ok
Finding cufft from Conda environment
        named  libcufft.so.10.1.2.89
        trying to open library...       ok
Finding curand from Conda environment
        named  libcurand.so.10.1.2.89
        trying to open library...       ok
Finding nvvm from Conda environment
        named  libnvvm.so.3.3.0
        trying to open library...       ok
Finding libdevice from Conda environment
        searching for compute_20...     ok
        searching for compute_30...     ok
        searching for compute_35...     ok
        searching for compute_50...     ok


__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : 3.18.9
Conda Env                                     : 4.8.4
Conda Platform                                : linux-64
Conda Python Version                          : 3.7.4.final.0
Conda Root Writable                           : True

__Installed Packages__
_anaconda_depends         2020.02                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
_libgcc_mutex             0.1                        main
absl-py                   0.8.1                    pypi_0    pypi
aiodns                    2.0.0                    pypi_0    pypi
aiohttp                   3.6.2            py37h7b6447c_0
aiosocks                  0.2.6                    pypi_0    pypi
akshare                   0.6.19                   pypi_0    pypi
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.4                      py_0
apex                      0.1                      pypi_0    pypi
arch                      4.14                     pypi_0    pypi
argh                      0.26.2                   py37_0
argon2-cffi               20.1.0           py37h7b6447c_1
arrow-cpp                 0.11.1           py37h5c3f529_1
asn1crypto                1.4.0                      py_0
astor                     0.8.0                    pypi_0    pypi
astroid                   2.4.2                    py37_0
astropy                   4.0.1.post1      py37h7b6447c_1
async-timeout             3.0.1                    py37_0
atomicwrites              1.4.0                      py_0
attrs                     20.1.0                     py_0
autopep8                  1.4.3                    py37_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.9.1                    py37_0
bitarray                  1.5.2            py37h7b6447c_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blis                      0.4.1                    pypi_0    pypi
blosc                     1.16.3               hd408876_0
bokeh                     2.1.1                    py37_0
boto                      2.49.0                   py37_0
boto3                     1.10.39                  pypi_0    pypi
botocore                  1.13.39                  pypi_0    pypi
bottleneck                1.2.1            py37h035aef0_1
brotlipy                  0.7.0           py37h7b6447c_1000
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.7.22                     0
cachetools                3.1.1                    pypi_0    pypi
cairo                     1.14.12              h8948797_3
catalogue                 0.2.0                    pypi_0    pypi
cchardet                  2.1.5                    pypi_0    pypi
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h2e261b9_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
conda                     4.8.4                    py37_0
conda-build               3.18.9                   py37_3
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py37h7b6447c_0
conda-verify              3.4.2                      py_1
contextlib2               0.6.0.post1                py_0
cryptography              2.7              py37h1ba5d50_0
cssutils                  1.0.2                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1
curl                      7.65.3               hbc83047_0
cxxfilt                   0.2.1            py37h3340039_1    conda-forge
cycler                    0.10.0                   py37_0
cymem                     2.0.3                    pypi_0    pypi
cython                    0.29.17                  pypi_0    pypi
cytoolz                   0.10.1           py37h7b6447c_0
dask                      2.24.0                     py_0
dask-core                 2.24.0                     py_0
dbus                      1.13.6               h746ee38_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
demjson                   2.2.4                    pypi_0    pypi
diff-match-patch          20200713                   py_0
dill                      0.3.1.1                  py37_0
distributed               2.24.0                   py37_0
docopt                    0.6.2                    py37_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                he6710b0_2
fastai                    1.0.59                   pypi_0    pypi
fastcache                 1.1.0            py37h7b6447c_0
fastprogress              0.2.0                    pypi_0    pypi
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
flask                     1.1.2                      py_0
fontconfig                2.13.0               h9420a91_0
fonttools                 4.12.1                   pypi_0    pypi
freetype                  2.10.2               h5ab3b9f_0
fribidi                   1.0.10               h7b6447c_0
fsspec                    0.8.0                      py_0
future                    0.18.2                   py37_0
gast                      0.2.2                    pypi_0    pypi
get_terminal_size         1.0.0                haa9412d_0
gevent                    20.6.2           py37h7b6447c_0
gflags                    2.2.2                he6710b0_0
glib                      2.56.2               hd408876_0
glob2                     0.7                        py_0
glog                      0.3.5                hf484d3e_1
gluonts                   0.5.0                    pypi_0    pypi
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py37h10f8cd9_2
google-auth               1.7.1                    pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.1.8                    pypi_0    pypi
graphite2                 1.3.14               h23475e2_0
greenlet                  0.4.16           py37h7b6447c_0
grpcio                    1.25.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.9.0            py37h7918eee_0
harfbuzz                  1.8.8                hffaf4a1_0
harvester                 0.20                      dev_0    <develop>
hdf5                      1.10.4               hb1b8bf9_0
heapdict                  1.0.1                      py_0
holidays                  0.9.12                   pypi_0    pypi
html5lib                  1.0.1                    py37_0
hyperopt                  0.2.3                    pypi_0    pypi
hypothesis                5.29.0                     py_0
icu                       58.2                 he6710b0_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
iniconfig                 1.0.1                      py_0
inlinestyler              0.2.5                    pypi_0    pypi
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.1.2            py37h39e3cac_0
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     5.4.2                    py37_0
itsdangerous              1.1.0                    py37_0
jbig                      2.1                  hdba287a_0
jdcal                     1.4.1                      py_0
jedi                      0.15.1                   py37_0
jeepney                   0.4.3                      py_0
jinja2                    2.11.2                     py_0
jmespath                  0.9.4                    pypi_0    pypi
joblib                    0.16.0                     py_0
jpeg                      9b                   h024ee3a_2
json5                     0.9.5                      py_0
jsonpath                  0.82                     pypi_0    pypi
jsonschema                3.2.0                    py37_1
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.2.6                      py_0
jupyterlab_server         1.2.0                      py_0
kaggle                    1.5.6                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
keyring                   21.3.1                   py37_0
kiwisolver                1.2.0            py37hfd86e86_0
krb5                      1.16.4               h173b8e3_0
lazy-object-proxy         1.4.3            py37h7b6447c_0
ld_impl_linux-64          2.33.1               h53a641e_7
libarchive                3.3.3                h5d8350f_5
libboost                  1.67.0               h46d08c1_4
libcurl                   7.65.3               h20c2e04_0
libedit                   3.1.20191231         h14c3975_1
libevent                  2.1.8                h1ba5d50_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
liblief                   0.10.1               he6710b0_0
libllvm9                  9.0.1                h4a3c616_1
libpng                    1.6.37               hbc83047_0
libpq                     11.2                 h20c2e04_0
libprotobuf               3.10.1               hd408876_0
libsodium                 1.0.18               h7b6447c_0
libspatialindex           1.9.3                he6710b0_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libtool                   2.4.6                h7b6447c_5
libuuid                   1.0.3                h1bed415_2
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               he19cac6_1
libxslt                   1.1.34               hc22bd24_0
lightgbm                  2.3.1                    pypi_0    pypi
llvmlite                  0.33.0           py37hc6ec683_1
locket                    0.2.0                    py37_1
lxml                      4.4.1            py37hefd8a0e_0
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h7b6447c_2
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37h14c3975_1
matplotlib                3.1.1            py37h5429711_0
matplotlib-base           3.3.1            py37h817c723_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37h14c3975_1001
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.1.0            py37h23d657b_0
mkl_random                1.1.0            py37hd6b4f25_0
mo-common                 0.10                      dev_0    <develop>
mock                      4.0.2                      py_0
mocore                    0.10                      dev_0    <develop>
monary                    0.5.0                    pypi_0    pypi
more-itertools            8.4.0                      py_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mplfinance                0.12.6a3                 pypi_0    pypi
mpmath                    1.1.0                    py37_0
msgpack-python            1.0.0            py37hfd86e86_1
multidict                 4.5.2            py37h7b6447c_0
multipledispatch          0.6.0                    py37_0
murmurhash                1.0.2                    pypi_0    pypi
mxnet-cu102               1.6.0                    pypi_0    pypi
mysql-connector-c         6.1.11               h597af5e_1
mysqlclient               1.4.6            py37he6710b0_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
ncurses                   6.2                  he6710b0_1
networkx                  2.2                      pypi_0    pypi
ninja                     1.10.0           py37hfd86e86_0
nltk                      3.5                        py_0
nose                      1.3.7                 py37_1004
notebook                  6.1.1                    py37_0
numba                     0.50.1           py37h0573a6f_1
numdifftools              0.9.39                   pypi_0    pypi
numexpr                   2.7.1            py37h423224d_0
numpy                     1.17.2           py37haad9e8e_0
numpy-base                1.17.2           py37hde5b4d6_0
numpydoc                  1.1.0                      py_0
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0
opendatatools             1.0.0                    pypi_0    pypi
openpyxl                  3.0.5                      py_0
openssl                   1.1.1g               h7b6447c_0
opt-einsum                3.1.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandas                    1.0.3                    pypi_0    pypi
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py37_1
pango                     1.42.4               h049681c_0
parso                     0.8.0                      py_0
partd                     1.1.0                      py_0
patchelf                  0.11                 he6710b0_0
path                      15.0.0                   py37_0
path.py                   12.5.0                        0
pathlib2                  2.3.5                    py37_1
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py37_0
pcre                      8.44                 he6710b0_0
pep8                      1.7.1                    py37_0
pexpect                   4.8.0                    py37_1
pickleshare               0.7.5                 py37_1001
pillow                    6.2.0            py37h34e0f95_0
pip                       20.1.1                   pypi_0    pypi
pixman                    0.40.0               h7b6447c_0
pkgconfig                 1.5.1                    pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0
plac                      1.1.3                    pypi_0    pypi
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
preshed                   3.0.2                    pypi_0    pypi
progressbar2              3.51.3                   pypi_0    pypi
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.6                      py_0
prompt_toolkit            3.0.6                         0
property-cached           1.6.4                    pypi_0    pypi
protobuf                  3.10.0                   pypi_0    pypi
psutil                    5.7.2            py37h7b6447c_0
psycopg2                  2.8.4            py37h1ba5d50_0
ptyprocess                0.6.0                    py37_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py37h403a769_0
pyaml                     20.4.0                   pypi_0    pypi
pyarrow                   0.11.1           py37he6710b0_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.7                    pypi_0    pypi
pycares                   3.1.1                    pypi_0    pypi
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37h7b6447c_0
pycparser                 2.20                       py_2
pycrypto                  2.6.1           py37h7b6447c_10
pycurl                    7.43.0.3         py37h1ba5d50_0
pydantic                  1.5.1                    pypi_0    pypi
pydocstyle                5.1.0                      py_0
pyexecjs                  1.5.1                    pypi_0    pypi
pyflakes                  2.1.1                    py37_0
pygments                  2.6.1                      py_0
pylint                    2.6.0                    py37_0
pymongo                   3.10.1                   pypi_0    pypi
pymysql                   0.9.3                    pypi_0    pypi
pyodbc                    4.0.30           py37he6710b0_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.7                      py_0
pypinyin                  0.38.1                   pypi_0    pypi
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.16.0           py37h7b6447c_0
pysocks                   1.7.1                    py37_1
pytables                  3.6.1            py37h71ec239_0
pytesseract               0.3.4                    pypi_0    pypi
pytest                    6.0.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.8.0                      py_0
pytest-openfiles          0.5.0                      py_0
pytest-remotedata         0.3.2                    py37_0
python                    3.7.4                h265db76_1
python-dateutil           2.8.1                      py_0
python-graphviz           0.8.4                    pypi_0    pypi
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.31.10                  py37_0
python-libarchive-c       2.9                        py_0
python-rapidjson          0.9.1                    pypi_0    pypi
python-slugify            4.0.0                    pypi_0    pypi
python-utils              2.4.0                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorchts                 0.1.1                    pypi_0    pypi
pytz                      2020.1                     py_0
pywavelets                1.1.1            py37h7b6447c_0
pyxdg                     0.26                       py_0
pyyaml                    5.1.2            py37h7b6447c_0
pyzmq                     19.0.1           py37he6710b0_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7                h5867ecd_1
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.6                      py_0
qtpy                      1.9.0                      py_0
readline                  7.0                  h7b6447c_5
redis                     5.0.3                h7b6447c_0
redis-py                  3.3.11                     py_0
regex                     2019.12.9                pypi_0    pypi
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                    pypi_0    pypi
ripgrep                   11.0.2               he32d670_0
rope                      0.17.0                     py_0
rsa                       4.0                      pypi_0    pypi
rtree                     0.9.4                    py37_1
ruamel_yaml               0.15.87          py37h7b6447c_0
s3transfer                0.2.1                    pypi_0    pypi
sacremoses                0.0.35                   pypi_0    pypi
scikit-image              0.16.2           py37h0573a6f_0
scikit-learn              0.23.2           py37h0573a6f_0
scikit-optimize           0.7.4                    pypi_0    pypi
scipy                     1.3.1            py37h7c811a0_0
seaborn                   0.10.1                     py_0
secretstorage             3.1.2                    py37_1
send2trash                1.5.0                    py37_0
sentencepiece             0.1.83                   pypi_0    pypi
setuptools                49.6.0                   py37_0
shadow                    0.10                      dev_0    <develop>
simplegeneric             0.8.1                    py37_2
simplejson                3.17.0           py37h7b6447c_0
singledispatch            3.4.0.3               py37_1000
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0                     py_0
snappy                    1.1.8                he6710b0_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
spacy                     2.2.3                    pypi_0    pypi
sphinx                    3.2.1                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.9            py37h7b6447c_0
sqlite                    3.33.0               h62c20be_0
srsly                     0.2.0                    pypi_0    pypi
statsmodels               0.11.1           py37h7b6447c_0
sympy                     1.6.2                    py37_0
ta-lib                    0.4.18                   pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tbb                       2020.2               hfd86e86_0
tblib                     1.7.0                      py_0
tensorboard               2.0.1                    pypi_0    pypi
tensorflow-estimator      2.0.1                    pypi_0    pypi
tensorflow-gpu            2.0.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
text-unidecode            1.3                      pypi_0    pypi
thinc                     7.3.1                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0
thrift-cpp                0.11.0               h02b749d_3
tk                        8.6.10               hbc83047_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
torchdiffeq               0.0.1                    pypi_0    pypi
torchvision               0.6.1                py37_cu102    pytorch
tornado                   6.0.4            py37h7b6447c_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py37_0
transformers              2.2.2                    pypi_0    pypi
tushare                   1.2.54                   pypi_0    pypi
typed-ast                 1.4.1            py37h7b6447c_0
typing_extensions         3.7.4.3                    py_0
ujson                     1.35                     pypi_0    pypi
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h14c3975_0
urllib3                   1.25.10                    py_0
vitu                      1.1.0                    pypi_0    pypi
wasabi                    0.4.2                    pypi_0    pypi
watchdog                  0.10.3                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
websocket-client          0.57.0                   pypi_0    pypi
werkzeug                  0.16.0                     py_0
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py37_0
wrapt                     1.11.2           py37h7b6447c_0
wurlitzer                 2.0.1                    py37_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.3.3                      py_0
xlwt                      1.3.0                    py37_0
xz                        5.2.5                h7b6447c_0
yaml                      0.1.7                had09818_2
yapf                      0.30.0                     py_0
yarl                      1.5.1            py37h7b6447c_0
zeromq                    4.3.2                he6710b0_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3
zope                      1.0                      py37_1
zope.event                4.4                      py37_0
zope.interface            5.1.0            py37h7b6447c_0
zstd                      1.3.7                h0b5b093_0

No errors reported.


__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init:
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

**Comment by gmarkall** [comment]
That's the info, yes. You have Numba 0.50.1 - `str(int)` was added in 0.51.0 - could you try again with Numba 0.51.0 please?

**Comment by gmarkall** [comment]
Thanks for the feedback - normally `conda install numba` does give you the latest version, but I think at the moment 0.51.0 hasn't yet been finished being packaged for the Anaconda distribution - this should be resolved in a few days' time.

Closing the issue as it now appears to be resolved.
