### ISSUE TITLE
jit compilation no longer works on google colab after v0.51.1

### ISSUE THREAD

**Issue by thomasdkelly** [numba/numba#6207]
Hi I have a module that relies on numba jit compiled functions which i run on google colab. However, after version 0.51.1 the functions no longer compile on colab but do locally. When i exit the compilation, the line of code it is stuck on is in the controlflow file. I assume it is because of the changes made in "PR #6146: Fix compilation slowdown due to controlflow analysis" though i do not know why exactly. 

Is there any reason why these changes mean the jit compilation no longer works in colab?

Thanks
Tom

**Comment by stuartarchibald** [comment]
Thanks for the report. I would guess from the description you are hitting this bug: https://github.com/numba/numba/issues/6186 that was introduced in 0.51.1, good news is it's fixed in https://github.com/numba/numba/pull/6195 and 0.51.2 with this fix in is shipping as I type this.

**Comment by thomasdkelly** [comment]
perfect thank you, will let you know if it continues with 0.51.2

**Comment by stuartarchibald** [comment]
> perfect thank you, will let you know if it continues with 0.51.2

Great, thanks.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
