### ISSUE TITLE
I am getting typing error.

### ISSUE THREAD

**Issue by nidhinsathyan2012** [numba/numba#6210]
@njit(parallel=True)
def totforcex(sysx,sysy):
    fx=np.zeros(10000, dtype = np.float32)

    
 
    

    for j in prange(sysx.shape[0]):

        for i in range(0,n):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

**Comment by gmarkall** [comment]
You're accessing `nfx` like it's an array, but it looks like `nfx` has never been defined prior to accessing it. I imagine you will also get an error message if you remove the `@njit(parallel=True)` decorator from the function. If you don't, could you post a complete runnable example of the code that you see the issue with please?

**Comment by nidhinsathyan2012** [comment]
from numba import njit,prange

@njit(parallel=True)
def prange_test(A):
    s=0
    for i in prange(A.shape[0]):
        s +=A[i]
    return s
@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=10000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c


def totforcex(sysx,sysy):
    fx=np.zeros(10000, dtype = np.float32)

    nfx=np.zeros(10000,dtype=np.float32)
 
    

    for j in prange(sysx.shape[0]):

        for i in range(0,n):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)

**Comment by nidhinsathyan2012** [comment]
import timeit
import numpy as np
from numba import njit,prange

@njit(parallel=True)
def prange_test(A):
    s=0
    for i in prange(A.shape[0]):
        s +=A[i]
    return s
@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=10000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c


def totforcex(sysx,sysy):
    fx=np.zeros(10000, dtype = np.float32)

    nfx=np.zeros(10000,dtype=np.float32)
 
    

    for j in prange(sysx.shape[0]):

        for i in range(0,n):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)

**Comment by nidhinsathyan2012** [comment]
```

import timeit
import numpy as np
from numba import njit,prange

@njit(parallel=True)
def prange_test(A):
    s=0
    for i in prange(A.shape[0]):
        s +=A[i]
    return s
@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=1000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c


def totforcex(sysx,sysy):

    fx=np.zeros(10000, dtype = np.float32)

    nfx=np.zeros(10000,dtype=np.float32)
 
    

    for j in prange(sysx.shape[0]):

        for i in range(0,n):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)

```

**Comment by nidhinsathyan2012** [comment]
```

import timeit
import numpy as np
from numba import njit,prange

@njit(parallel=True)
def prange_test(A):
    s=0
    for i in prange(A.shape[0]):
        s +=A[i]
    return s
@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=1000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c


def totforcex(sysx,sysy):

    fx=np.zeros(10000, dtype = np.float32)

    nfx=np.zeros(10000,dtype=np.float32)
 
    

    for j in range(0,N):

        for i in range(0,N):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)


```

**Comment by nidhinsathyan2012** [comment]
```

import timeit
import numpy as np
from numba import njit,prange


@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=1000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c


def totforcex(sysx,sysy):

    fx=np.zeros(N, dtype = np.float32)

    nfx=np.zeros(N,dtype=np.float32)
 
    

    for j in range(0,N):

        for i in range(0,N):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)


```

**Comment by esc** [comment]
@nidhinsathyan2012 thanks for posting the example. I just ran it on the current `master` at `0.52.0dev0-132-g0d2ac24f91` and it produced no errors. Would you be able to attach a backtrace of the error you encountered. Also, what version of Numba are you using?

**Comment by nidhinsathyan2012** [comment]
```

import timeit
import numpy as np
from numba import njit,prange


@njit

def r(xd1,yd1,xd2,yd2):
    dis=((xd1-xd2)**2+(yd1-yd2)**2)**0.5
    return(dis)
@njit
def wcax(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(xd1-xd2)
    else:
        p=0
    
    return(p)
@njit
def wcay(xd1,yd1,xd2,yd2):
    dis=r(xd1,yd1,xd2,yd2)
    if(dis)<2**(1/6):
        p= 24*(2*(1/dis)**14-(1/dis)**8)*(yd1-yd2)
    else:
        p=0
    
    return(p)

N=1000
A=np.zeros(N,dtype=np.float32)

sysx=np.zeros(N,dtype=np.float32)
sysy=np.zeros(N,dtype=np.float32)
box=110
b=0
n=100
for i in range(0,N):
    if i%n==0:
        b=b+1
    sysx[i]=b+2
    c=i%n+1
    sysy[i]=c

@njit(parallel=True)
def totforcex(sysx,sysy):

    fx=np.zeros(N, dtype = np.float32)

    nfx=np.zeros(N,dtype=np.float32)
 
    

    for j in prange(sysx.shape[0]):

        for i in range(sysx.shape[0]):

            if i == j:

                fx[i] = 0

            else:

                if (sysx[j]-sysx[i])>box/2:

                    dumsx = sysx[i]+box

                elif (sysx[j]-sysx[i])<-box/2:

                    dumsx = sysx[i]-box

                else:

                    dumsx = sysx[i]

                if (sysy[j]-sysy[i])>box/2:

                    dumsy = sysy[i]+box

                elif (sysy[j]-sysy[i])<-box/2:

                    dumsy = sysy[i]-box

                else:

                    dumsy = sysy[i]

                fx[i] = wcax(sysx[j],sysy[j],dumsx,dumsy) 
                
                
        nfx[j] = sum(fx)
        
    return(nfx)

k=np.zeros(N,dtype=np.float32)
k=totforcex(sysx,sysy)


```

**Comment by esc** [comment]
@nidhinsathyan2012 Numba currently does not implement `sum` -- try using `np.sum` instead.

**Comment by nidhinsathyan2012** [comment]
Yeah now it's working. When I look into the performance. My GPU is not working. How can I  start working with the CUDA?

**Comment by esc** [comment]
@nidhinsathyan2012 thank you for confirming! I will close this issue now as I believe it has been resolved. For CUDA, please see the documentation at: https://numba.readthedocs.io/en/stable/cuda/index.html - thank you for using Numba and have a great day!

**Comment by esc** [comment]
@nidhinsathyan2012 btw, we do have a real-time chat for Numba at: https://gitter.im/numba/numba -- in case you hit minor snags it may be quicker to ask there rather than opening an issue.

**Comment by nidhinsathyan2012** [comment]
Thanks alot to esc and gmarkall.❤
