### ISSUE TITLE
Suggested Numpy features to implement in Numba

### ISSUE THREAD

**Issue by jaistech-sp** [numba/numba#6214]
Hi there!

First of all congratulations on Numba's project! Is is what Python actually need to overcome its historical problems with *"speed"*. 

I have been implmenting Numba in some of my scripts, I would like to highlight some Numpy functions that are crucial to me but yet not implemented in Numba.

- `np.save`. Generates .npy files in ROM. It is very useful as intermediate function in my processing since I use to lack of RAM memory, so I just store them on disk memory.
- `np.isin`. Almost always used. I think it was partially developed but the script was not reviewed by the Developed. #4815 
- `np.maximum` / `np.minimum` / `np.nanargmin` / `np.nanargmax`. Those features are NOT critical, I've just seen that numba supports some basic aggregations funcs. with nans such as nansum, so it would be cool to have those too.

Thanks a lot for your time!

**Comment by esc** [comment]
@jaistech-sp thank you for your suggestions, I have marked this issue as a feature request accordingly.

**Comment by stuartarchibald** [comment]
Thanks for this, I think this request is covered by https://github.com/numba/numba/issues/4074 and would suggest `np.save` would best be done in an [object mode block](https://numba.readthedocs.io/en/stable/user/withobjmode.html#the-objmode-context-manager) as it is doing IO. Closing as a duplicate.
