### ISSUE TITLE
fastmath=True gives invalid np.isfinite() value

### ISSUE THREAD

**Issue by segatrade** [numba/numba#6217]
### Check off these boxes:

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
0.51.2

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

- [x] there is no other issue present that already describes the issue you have (search at https://github.com/numba/numba/issues?&q=is%3Aissue).

### Details of the bug here, including, if applicable, what you expected to happen

fastmath=True gives invalid np.isfinite() value

in this case it's invalid:
```
@njit(fastmath=True,nogil=True,cache=False ) 
def _check_finite_matrix(a):
        for v in np.nditer(a):
            if not np.isfinite(v.item()):
              error=True

a=[[ inf -inf]
 [-inf 265.]]
_check_finite_matrix(a)
```

in linalg.py it's valid because no fastmath=True:
```
@register_jitable
def _check_finite_matrix(a):
    for v in np.nditer(a):
        if not np.isfinite(v.item()):
            raise np.linalg.LinAlgError(
                "Array must not contain infs or NaNs.")
```

Is it bug or feature? Is it possible to use `fastmath` with these checks? I have problem on `py3.6` with `try`, because seems support for `try` only from `py3.7`

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the `fastmath` flag is doing what is intended. If you add `fastmath` to a function it will permit a number of optimisations based on assumptions as described [here](http://llvm.org/docs/LangRef.html#fast-math-flags). If you wish to limit the scope of the assumptions it's possible to select on a flag-by-flag basis which parts of `fastmath` to use, for example:
```python
from numba import njit
import numpy as np

def foo(a):
    for v in a:
        print("-" * 40)
        print("--> isfinite(", v, "):", np.isfinite(v))
        print("--> isnan(", v, "):", np.isnan(v))

a=np.array([np.inf, -np.inf, np.nan, 12.])

base_flags = {'nsz', 'reassoc', 'arcp', 'contract', 'afn', 'reassoc'}

print("NumPy")
foo(a)

for flags in (False,
              True,
              base_flags,
              base_flags|{'nnan'},
              base_flags|{'ninf'},
              base_flags|{'ninf', 'nnan'}):
    def pflags(f):
        if not isinstance(f, set):
            return {f,}
        else:
            return f
    print("\nFlags {}".format(sorted(pflags(flags))))
    njit(fastmath=flags)(foo)(a)
```

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
