### ISSUE TITLE
Confusing error message when cudatoolkit version is wrong

### ISSUE THREAD

**Issue by jacobtomlinson** [numba/numba#6226]
I accidentally installed `cudatoolkit=11.0` when I only had CUDA 10.2. This resulted in the following error message when running a kernel.

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-3c5abde27154> in <module>
----> 1 get_arch_option(*cc)

~/miniconda3/envs/techexeter/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py in get_arch_option(major, minor)
    343     else:
    344         arch = find_closest_arch((major, minor))
--> 345     return 'compute_%d%d' % arch
    346 
    347 

TypeError: not enough arguments for format string
```

In this case `arch` was an empty tuple because there were no valid architectures available.

It would be nice to catch this and raise a more helpful error message.

**Comment by stuartarchibald** [comment]
Thanks for the report. Is this a duplicate of https://github.com/numba/numba/issues/6223 ?

**Comment by jacobtomlinson** [comment]
Ah yep! Sorry I did look but must've missed that one.
