### ISSUE TITLE
literally does not behave like in the doc example (and the test)

### ISSUE THREAD

**Issue by albop** [numba/numba#6238]
I'm trying to replicate the example from https://www.github.com/numba/numba/blob/master/numba/tests/test_literal_dispatch.py .

On my computer (numba 0.51.2), it doesn't print the desired output, meaning that function specializations on literal types are not computed.  (incidentally, the test does not check for correct behaviour: might be better if specialized functions returned different output)

In the changelog, I read for version 0.50: "Numba has internally switched to prefer non-literal types over literal ones so  as to reduce function over-specialization, this with view of speeding up compile times (Siu Kwan Lam)." Indeed, with version 0.50, it works as expected.

Has the functionality completely disappeared or changed ? Is there a way to reenable it ?

**Comment by stuartarchibald** [comment]
Thanks for the report. From the description I'm not sure precisely what it is that is not working, please could you provide more information?

1. Which tests in the above don't appear to work.
2. Which tests are not checking for "correct behaviour".
3. Something to reproduce the problem(s).

Thanks for your help.


> Has the functionality completely disappeared or changed ? Is there a way to reenable it ?

It's still there and many projects are using it in production. All that changed was the default order for trying types against a function such that less specialised types are tried first (stops e.g. `foo(x); foo(1); foo(2)` specialising on `1` and `2` unless requested, it'll just specialise as `foo(intp)`).

**Comment by albop** [comment]
@stuartarchibald: one million apologies, I linked to the wrong example
I was trying to replicate https://numba.pydata.org/numba-doc/latest/developer/literal.html which comes from the test https://github.com/numba/numba/blob/master/numba/tests/doc_examples/test_literally_usage.py. 

Here it is, slightly modified so as to make the point clearer:

```
import numba

def power(x, n):
    raise NotImplementedError

@numba.extending.overload(power)
def ov_power(x, n):
    if isinstance(n, numba.types.Literal):
        # only if `n` is a literal
        if n.literal_value == 2:
            # special case: square
            print("square")
            return lambda x, n: x * x + 1
        elif n.literal_value == 3:
            # special case: cubic
            print("cubic")
            return lambda x, n: x * x * x + 2

    print("generic")
    return lambda x, n: x ** n

@numba.njit
def test_power(x, n):
    return power(x, numba.literally(n))

# should print "square" and "10"
print(test_power(3, 2))

# should print "cubic" and "29"
print(test_power(3, 3))

# should print "generic" and "81"
print(test_power(3, 4))
```
On numba 0.51.2, I get:
```
generic
9
27
81
```
While I was expecting:

```
square
10
cubic
29
generic
81
```
The absence of the strings square and cubic in the output, shows that the wrong code is used. The test I link to can't catch the mistake, because it assumes all variants compute the same value `x**n`.

**Comment by stuartarchibald** [comment]
@albop great, thanks, I can reproduce with the above, will take a look.

**Comment by stuartarchibald** [comment]
Think the code probably needs to look like this:
```python
import numba
from numba import literally

def power(x, n):
    raise NotImplementedError

@numba.extending.overload(power)
def ov_power(x, n):
    if isinstance(n, numba.types.Literal):
        # only if `n` is a literal
        if n.literal_value == 2:
            # special case: square
            print("square")
            return lambda x, n: x * x + 1
        elif n.literal_value == 3:
            # special case: cubic
            print("cubic")
            return lambda x, n: x * x * x + 2
    else:
        return lambda x, n: (x, literally(n))

    print("generic")
    return lambda x, n: x ** n

@numba.njit
def test_power(x, n):
    return power(x, n)

# should print "square" and "10"
print(test_power(3, 2))

# should print "cubic" and "29"
print(test_power(3, 3))

# should print "generic" and "81"
print(test_power(3, 4))
```

**Comment by albop** [comment]
Thanks, I understand the logic of the new version which works fine, not why the original one doesn't works. that's good enough for me ;-)

**Comment by stuartarchibald** [comment]
> Thanks, I understand the logic of the new version which works fine, not why the original one doesn't work. that's good enough for me ;-)

No problem. The original now doesn't work because when the literal value of `n` arrives at the call site of `power` by virtue of `literally`, it's immediately `unliteral`'d to try for use in the `ov_power` overload as unliteral types are now preferred, and because the `ov_power` overload has a branch for this (`"generic"`) it just compiles that version and keeps using it.

**Comment by albop** [comment]
Makes sense. Thank you for the explanation
