### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'core' #5675

### ISSUE THREAD

**Issue by jkylearmstrong** [numba/numba#6246]
## Reporting a bug
- [ x] I have tried using the latest released version of Numba 
- [ x] I have included below a minimal working reproducer 

I have found issue #5675 and I am receiving similar error when attempting latest version of numba as suggested in [here](https://groups.google.com/a/continuum.io/g/numba-users/c/DqSatiOo3ks?pli=1)

``!pip3 install numba==0.49.1``

``import numba``

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-6d1098de51de> in <module>()
----> 1 import numba

/home/cdsw/.local/lib/python3.6/site-packages/numba/__init__.py in <module>()
     27 
     28 # Re-export types itself
---> 29 import numba.core.types as types
     30 
     31 # Re-export all type names

AttributeError: module 'numba' has no attribute 'core'
```

**Comment by jkylearmstrong** [comment]
I have tested
```python
!pip3 install numba==0.48.0
```

and do not receive the error with this version

**Comment by gmarkall** [comment]
It looks like your Python installation or virtualenv may have somehow got different versions of Numba installed into it / mixed up. If I create a new virtualenv and install with:

```
python -m venv test
. test/bin/activate
pip install numba==0.49.1
```

then import Numba:

```
$ python
Python 3.8.5 (tags/v3.8.5-dirty:580fbb018f, Sep  4 2020, 12:57:44) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> 
```

There appears to be no issue with Numba 0.49.1. If you create a new virtualenv and install Numba, does it work?

The latest version of Numba is 0.51.2 - you may wish to install Numba with `pip install numba` to get the latest version.

**Comment by esc** [comment]
It might also be worth running `pip uninstall numba` several times to get rid of all old installs. Basically until `pip` reports it does no longer have a `numba` installed.

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.

**Comment by yeyang1021** [comment]
> It looks like your Python installation or virtualenv may have somehow got different versions of Numba installed into it / mixed up. If I create a new virtualenv and install with:
> 
> ```
> python -m venv test
> . test/bin/activate
> pip install numba==0.49.1
> ```
> 
> then import Numba:
> 
> ```
> $ python
> Python 3.8.5 (tags/v3.8.5-dirty:580fbb018f, Sep  4 2020, 12:57:44) 
> [GCC 7.5.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numba
> >>> 
> ```
> 
> There appears to be no issue with Numba 0.49.1. If you create a new virtualenv and install Numba, does it work?
> 
> The latest version of Numba is 0.51.2 - you may wish to install Numba with `pip install numba` to get the latest version.

thank you, this version has numba.core
