### ISSUE TITLE
.ptp() not @njit compilable anymore?

### ISSUE THREAD

**Issue by La-Li-Lu-Le-Loa** [numba/numba#6257]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
 

I cant pass numpy arrays like the following to an `njit` compiled function that contains` numpy.ptp()`.
Why is that ( I think here it says, that .ptp() is supported: https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html)
 ```
a = [0.         ,0.         ,0.         ,0.         ,0.         ,0.
 ,0.         ,0.         ,0.00224828 ,0.00317533 ,0.00830591 ,0.00934349  
 ,0.80603907 ,0.80603907 ,0.80603907 ,0.80603907 ,0.80603907 ,0.94597275,
 1.,        1.,        1.,        1.,        1.,        1., 
 1.,       ]

import math
from numba import  prange
@nb.njit(nopython=True,parallel=True)
def anynan(array): 
    for i in prange(array.size):
        if math.isnan(array[i]):
            return True
    return False
@nb.njit
def scale_zero2one(x):
      
    x -= x.min()  
    x /= x.ptp()   
    if anynan(x):  
        x[np.isnan(x)] = 0               
    return x 

a = np.asarray(a,dtype=np.float32) 
print(scale_zero2one(a))
```

**Comment by gmarkall** [comment]
`np.ptp` is supported, but the `.ptp` method of array objects is not. Modifying your reproducer to define missing imports, define `a`, and use `np.ptp` instead results in a successful compilation:

```python
import math
import numpy as np
from numba import prange, njit


@njit(nopython=True, parallel=True)
def anynan(array):
    for i in prange(array.size):
        if math.isnan(array[i]):
            return True
    return False


@njit
def scale_zero2one(x):

    x -= x.min()
    x /= np.ptp(x)
    if anynan(x):
        x[np.isnan(x)] = 0
    return x


a = [1, 2, 3]

a = np.asarray(a, dtype=np.float32)
print(scale_zero2one(a))
```

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/6261 fixes
