### ISSUE TITLE
Add support for `ndarray` 'contains'

### ISSUE THREAD

**Issue by LucIJspeert** [numba/numba#6259]
- [x] I have tried using the latest released version of Numba
- [x] I have included below a minimal working reproducer

In trying to replace numpy's setxor1d (which is unfortunately not supported by Numba), I came across an error that does occur for (integer) ndarrays but not for lists.
In my case the setxor1d can be replaced by [i for i in a if i not in b], but for the sake of testing, here is a different minimal working example:

```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    return 6 in included
```
This will give the error:

```
No implementation of function Function(<built-in function contains>) found for signature:

 >>> contains(array(int64, 1d, C), Literal[int](6))
```

While the funtion:
```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    return 6 in list(included)
```

Works fine. 
I'm assuming it is supposed to work for the array as well.
I came accross this previous issue that looks similar at first glance: [github.com/numba/numba/issues/4150](https://github.com/numba/numba/issues/4150)
But there it concerns an array of floats, so it is evident that 'int in array(float)' is not going to work.

**Comment by LucIJspeert** [comment]
There's actually another issue related to my stand-in setxor function:

```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    not_included = [i for i in range(10) if i not in list(included)]
    return not_included
```
produces:
```
Type of variable '$18compare_op.7.7054' cannot be determined, operation: unary(fn=<built-in function not_>, value=$18compare_op.7.7054), location: <ipython-input-138-e85438f982c0> (4)
```
I had to get around this by instead doing:
```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    not_included = [i for i in range(10) if (i in list(included)) is False]
    return not_included
```
Which is not very pretty. But I should probably open a new issue for this separately?

**Comment by gmarkall** [comment]
Thanks for the question! Marking this as a feature request, to add support for `contains` for NumPy arrays.

>  But I should probably open a new issue for this separately?

It would be helpful for issue / feature tracking to have a separate issue for this - many thanks!

**Comment by stuartarchibald** [comment]
The use of Numba's extension API `@overload` decorator is strongly recommended for this task. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files
