### ISSUE TITLE
Type cannot be determined when using 'if a not in b' in list construction 

### ISSUE THREAD

**Issue by LucIJspeert** [numba/numba#6260]
- [x] I have tried using the latest released version of Numba
- [x] I have included below a minimal working reproducer

In trying to make a replacement for numpy's setxor1d I came across the following error (minimal example below):
```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    not_included = [i for i in range(10) if i not in list(included)]
    return not_included
```
Which results in:

`Type of variable '$18compare_op.7.7054' cannot be determined, operation: unary(fn=<built-in function not_>, value=$18compare_op.7.7054), location: <ipython-input-138-e85438f982c0> (4)`

Which does not occur when the 'not' statement (in if i not in list(included)]) is not there
I could get around this by instead doing:
```
@nb.njit()
def test():
    included = np.array([1, 2, 6, 8])
    not_included = [i for i in range(10) if (i in list(included)) is False]
    return not_included
```
Which is not very pretty.

**Comment by esc** [comment]
@LucIJspeert thanks for reporting this! I can reproduce it. It seems like the `not` doesn't work properly in the list comprehension context.
