### ISSUE TITLE
Support fortran ordered arrays in parallel accelerator

### ISSUE THREAD

**Issue by tariqul-islam** [numba/numba#6268]
I was trying to use numba for a code that required loading files from *.mat files. I found that I have to make a copy of the variable in order to use it. If I don't copy it it throws an error. A code that reproduces the error is given below:

```
import numpy as np

from scipy.io import savemat, loadmat

import numba
from numba import prange

x = np.random.randn(5,5)

@numba.jit(nopython=True, parallel=True)
def my_func(X):
    val = 0.0
    for i in prange(X.shape[0]):
        for j in prange(X.shape[1]):
            dist = np.sum((X-X[i,:])**2,axis=1)
            
            val += np.max(dist)
            
    return val

print(my_func(x)) #no error

d = {}
d['x'] = x
savemat('x.mat', d)

y = loadmat('x.mat')['x']

print(my_func(y.copy())) #no error

print(my_func(y)) #produces error
```

**Comment by sklam** [comment]
Can you paste the error message please?

**Comment by tariqul-islam** [comment]
Here is the error message:

> UnsupportedError: Failed in nopython mode pipeline (step: nopython mode backend)
> Failed in nopython mode pipeline (step: nopython frontend)
> Unsupported op-code encountered: arrayexpr(expr=(<built-in function pow>, [(<built-in function sub>, [Var(X, <ipython-input-3-0cad61ef7dc6>:12), Var($44.12, <ipython-input-3-0cad61ef7dc6>:15)]), const(int, 2)]), ty=array(float64, 2d, F))
> 
> File "<ipython-input-3-0cad61ef7dc6>", line 15:
> def my_func(X):
>     <source elided>
>         for j in prange(X.shape[1]):
>             dist = np.sum((X-X[i,:])**2,axis=1)
>             ^
> 
> During: lowering "id=13[LoopNest(index_variable = parfor_index.1350, range = (0, $8.5, 1))]{24: <ir.Block at <ipython-input-3-0cad61ef7dc6> (13)>}Var(parfor_index.1350, <ipython-input-3-0cad61ef7dc6>:13)" at <ipython-input-3-0cad61ef7dc6> (13)

**Comment by esc** [comment]
@tariqul-islam I would like to try to reproduce the error you encountered on my machine but the code example seems malformed. Perhaps you could look at the GitHub basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). Thanks!

**Comment by stuartarchibald** [comment]
Think the issue here will be lack of Fortran ordered array support in parfors. IIRC Matlab's default data layout is Fortran order so loading from a `.mat` array will end up with this order, `.copy()` will force to C order.

**Comment by tariqul-islam** [comment]
> @tariqul-islam I would like to try to reproduce the error you encountered on my machine but the code example seems malformed. Perhaps you could look at the GitHub basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). Thanks!

Sorry! I have changed the format.

**Comment by stuartarchibald** [comment]
> > @tariqul-islam I would like to try to reproduce the error you encountered on my machine but the code example seems malformed. Perhaps you could look at the GitHub basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). Thanks!
> 
> I have changed the format.
> 
> > Think the issue here will be lack of Fortran ordered array support in parfors. IIRC Matlab's default data layout is Fortran order so loading from a `.mat` array will end up with this order, `.copy()` will force to C order.
> 
> Thanks. Will numba support Fortran ordered array in the future?

Probably, https://github.com/numba/numba/pull/5659 does a lot of the work already.

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/5659. Closing.
