### ISSUE TITLE
Issues using the target keyword argument with @vectorize decorator

### ISSUE THREAD

**Issue by esc** [numba/numba#6280]
from: https://groups.google.com/a/continuum.io/g/numba-users/c/7DeQ9dHgw7c/m/_0Kp9pl8BQAJ?pli=1

I'm learning how to use numba, and so im trying to optimize and make this block of code run faster:

```
from numba import vectorize,njit
import numpy as np

@vectorize("i2(i8)",target="parallel")
def collatz_step_counter(n):
    count=0
    while n!=1:
        if n%2==0:
            n/=2
        else:
            n=(3*n+1)/2
            count+=1
        count+=1
    return count

@njit
def max_collatz_steps(num,want_data=False):
    max_steps=0
    max_input=0
    lis=np.arange(1,num+1,2,dtype=np.int64)
    lis=collatz_step_counter(lis)
    max_steps=max(lis)
    max_input=2*lis.argmax()+1
    return max_input,max_steps

max_collatz_steps(1000000)
```

But when I put the @njit decorator on max_collatz_steps, it gives me one of two errors:

-If for the first function I write target="parallel", it gives me this error:
TypingError: cannot determine Numba type of <class 'numpy.ufunc'>

-Instead, if I write target="cuda", it gives me this error:
TypingError: cannot determine Numba type of <class 'numba.cuda.dispatcher.CUDAUFuncDispatcher'>

When I write target="cpu", it works fine.
Thanks in advance.

**Comment by esc** [comment]
I can confirm I am able to replicate the behavior described.

**Comment by ismaelbrowne** [comment]
This issue is related to this other issue: https://github.com/numba/numba/issues/5720

**Comment by esc** [comment]
@ismaelbrowne it seem like this issue may be a duplicate of #5720 -- do you agree?

**Comment by ismaelbrowne** [comment]
Yeah, I agree

**Comment by esc** [comment]
@ismaelbrowne thanks for confirming! I'll label this as a duplicate now and close it! Thanks again for reporting.
