### ISSUE TITLE
could I use the numba speed up the np.argsort ?

### ISSUE THREAD

**Issue by ucasiggcas** [numba/numba#6285]
hi,dear 
Now I have a data with shape of (10240,38853), of course we can use the down **scores**
`scores=np.random.randn(10240,38853)`
but when I use np.argsort,the time is long
```
t0=time.time()
inds=np.argsort(scores, 1)
t1=time.time()
```
t1-t0 is about 34 seconds,it's a long time, 
So could I use the perfect numba deal this problem ?

thx

**Comment by esc** [comment]
@ucasiggcas thank you for asking about this! Unfortunately Numba is unable to accelerate `argsort` for 2D arrays and when using the `axis` keyword. The relevant issue tracking this is here: https://github.com/numba/numba/issues/4636
