### ISSUE TITLE
Implement np.logspace and np.geomspace

### ISSUE THREAD

**Issue by holymonson** [numba/numba#6301]
## Feature request

Implement `np.logspace` and `np.geomspace`, the code in `numpy` seems easy.

```python
@array_function_dispatch(_logspace_dispatcher)
def logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None,
             axis=0):
    y = linspace(start, stop, num=num, endpoint=endpoint, axis=axis)
    if dtype is None:
        return _nx.power(base, y)
    return _nx.power(base, y).astype(dtype, copy=False)
```

**Comment by esc** [comment]
@holymonson thanks for submitting this. We track missing Numpy implementation in the issue at https://github.com/numba/numba/issues/6301 - but the functions requested were not yet part of that list. I have added them to the Issue now and will close this one to avoid duplication. Please feel free to add some tests and submit the suggested code as a pull-request.

**Comment by Unoaccaso** [comment]
seems to me that geomspace is not implemented yet.

**Comment by esc** [comment]
> seems to me that geomspace is not implemented yet.

@Unoaccaso thank you for asking about this. I think you may have missed something? Or perhaps you are on an older version? I just had a look at the release notes for 0.58 and it clearly states that `np.geomspace` was added in that version:

https://numba.readthedocs.io/en/stable/release/0.58.0-notes.html#added-support-for-np-geomspace-function

Does that help?
