### ISSUE TITLE
Import Error with Numba _typeconv

### ISSUE THREAD

**Issue by dshung** [numba/numba#6323]
While trying to install SHAP unable to import the module due to this error with Numba. On a Mac OS - not sure if that is the problem?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typeconv/typeconv.py in <module>
      3     # Numba, if it fails to import, provide some feedback
----> 4     from numba.core.typeconv import _typeconv
      5 except ImportError as e:

ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typeconv/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-4-efbb001a1501> in <module>
----> 1 import shap

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shap/__init__.py in <module>
     10     warnings.warn("As of version 0.29.0 shap only supports Python 3 (not 2)!")
     11 
---> 12 from ._explanation import Explanation
     13 
     14 # explainers

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shap/_explanation.py in <module>
      8 from slicer import Slicer, Alias
      9 # from ._order import Order
---> 10 from .utils._general import OpChain
     11 
     12 # slicer confuses pylint...

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shap/utils/__init__.py in <module>
----> 1 from ._clustering import hclust_ordering, partition_tree, partition_tree_shuffle, delta_minimization_order, hclust
      2 from ._general import approximate_interactions, potential_interactions, sample, safe_isinstance, assert_import, record_import_error
      3 from ._general import shapley_coefficients, convert_name, format_value, ordinal_str, OpChain
      4 from ._show_progress import show_progress
      5 from ._masked_model import MaskedModel, make_masks

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/shap/utils/_clustering.py in <module>
      2 import scipy as sp
      3 from scipy.spatial.distance import pdist
----> 4 from numba import jit
      5 import sklearn
      6 import warnings

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/__init__.py in <module>
     17 
     18 # Re-export typeof
---> 19 from numba.misc.special import (
     20     typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init,
     21     literally, literal_unroll

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/misc/special.py in <module>
      1 import numpy as np
      2 
----> 3 from numba.core.typing.typeof import typeof
      4 
      5 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typing/__init__.py in <module>
----> 1 from .context import BaseContext, Context
      2 from .templates import (signature, make_concrete_template, Signature,
      3                         fold_arguments)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typing/context.py in <module>
      9 import numba
     10 from numba.core import types, errors
---> 11 from numba.core.typeconv import Conversion, rules
     12 from numba.core.typing import templates
     13 from .typeof import typeof, Purpose

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typeconv/rules.py in <module>
      1 import itertools
----> 2 from .typeconv import TypeManager, TypeCastingRules
      3 from numba.core import types
      4 
      5 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/typeconv/typeconv.py in <module>
     15            "possible please include the following in your error report:\n\n"
     16            "sys.executable: %s\n")
---> 17     raise ImportError(msg % (url, reportme, str(e), sys.executable))
     18 
     19 from numba.core.typeconv import castgraph, Conversion

ImportError: Numba could not be imported.

**Comment by esc** [comment]
@dshung thanks for submitting this! would you please attach the output of `numba -s` to this PR?  Thanks!

**Comment by dshung** [comment]
/bin/sh:~/miniconda3/bin/numba: Permission denied

**Comment by esc** [comment]
@dshung ok, in that case I presume your environment is probably broken somehow. How did you install Python and Numba?

**Comment by esc** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
