### ISSUE TITLE
NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9002. The TBB threading layer is disabled.

### ISSUE THREAD

**Issue by ucasiggcas** [numba/numba#6350]
hi,dear
how to modify the warning ?
could you pls help me ?
thx

**Comment by esc** [comment]
@ucasiggcas thank you for asking about this. My guess is that you need to update your version of `tbb`.

**Comment by ucasiggcas** [comment]
hi,thanks in advance
but tbb is what in python ? or how to update the module ?
thx

**Comment by sklam** [comment]
If you installed with conda, you can use `conda install tbb` to update it.
If you installed with pip, use `pip install --upgrade tbb`

**Comment by eagle40** [comment]
It's updated by 'pip install --upgrade tbb' to 2020.3.254. But it doesn't work. There is  same 'NumbaWarning' message.

**Comment by esc** [comment]
@eagle40 `pip` can sometimes not upgrade properly so old versions have a tendency to "hang around". I would suggest starting with a fresh virtualenvironment (or whatever other means you have for installing packages) to avoid such cases.

**Comment by stuartarchibald** [comment]
This most likely occurs when a user is using `@jit(parallel=True)` and one of:
1. the user is using conda and has installed TBB and it's of a too old version for Numba to use.
2. the user is using conda and hasn't installed TBB, but is running in the base `conda` environment which has an older version of TBB.
3. the user has installed TBB via pip and it's unlikely that the pip library directories are on a path that Numba can find and so a potentially too old system level TBB is found.
4. the user hasn't installed TBB but there is a potentially too old version of this library present at system level.

Quickest path to getting TBB working is to use `conda` and install `tbb` like:
```
$ conda install tbb
```
quickest way to stop the message if the `tbb` threading layer isn't wanted is to specify the threading layer that is wanted instead. e.g.
```
$ NUMBA_THREADING_LAYER='omp' python <my program>
```
see https://numba.readthedocs.io/en/stable/user/threading-layer.html#selecting-a-threading-layer-for-safe-parallel-execution for more information.

**Comment by slayoo** [comment]
On a related note: when running python with ``-We`` (treat warnings as errors mode), the logic within ``numba.np.ufunc.parallel._launch_threads()`` does not work anymore as it expects an ``ImportError`` to be raised but this code:
```python
            warnings.warn(problem)
            raise ImportError("Problem with TBB. Reason: %s" % msg)
```
raises a numba.core.errors.NumbaWarning instead.

This leads further to things like:
```
...
During handling of the above exception, another exception occurred:
...
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/decorators.py:218: in wrapper
    disp.compile(sig)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/dispatcher.py:819: in compile
    cres = self._compiler.compile(args, return_type)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/dispatcher.py:78: in compile
    status, retval = self._compile_cached(args, return_type)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/dispatcher.py:92: in _compile_cached
    retval = self._compile_core(args, return_type)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/dispatcher.py:105: in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler.py:627: in compile_extra
    return pipeline.compile_extra(func)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler.py:363: in compile_extra
    return self._compile_bytecode()
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler.py:425: in _compile_bytecode
    return self._compile_core()
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler.py:405: in _compile_core
    raise e
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler.py:396: in _compile_core
    pm.run(self.state)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_machinery.py:341: in run
    raise patched_exception
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_machinery.py:332: in run
    self._runPass(idx, pass_inst, state)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_machinery.py:291: in _runPass
    mutated |= check(pss.run_pass, internal_state)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/compiler_machinery.py:264: in check
    mangled = func(compiler_state)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/typed_passes.py:442: in run_pass
    NativeLowering().run_pass(state)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/typed_passes.py:370: in run_pass
    lower.lower()
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/lowering.py:136: in lower
    self.lower_normal_function(self.fndesc)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/lowering.py:190: in lower_normal_function
    entry_block_tail = self.lower_function_body()
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/lowering.py:216: in lower_function_body
    self.lower_block(block)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/lowering.py:230: in lower_block
    self.lower_inst(inst)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/contextlib.py:131: in __exit__
    self.gen.throw(type, value, traceback)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/errors.py:752: in new_error_context
    reraise(type(newerr), newerr, tb)
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/numba/core/utils.py:81: in reraise
    raise value
E   numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
E   The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
```

Unintuitive and very tricky to understand.

Perhaps it would be worth to refactor the logic in select_known_backend() so it does not use exceptions for control flow?
Or catch both ImportError and NumbaWarning?

**Comment by stuartarchibald** [comment]
@slayoo thanks, I've opened #6592 to track.

**Comment by stuartarchibald** [comment]
There's more information on this topic on the Numba discourse forum here: https://numba.discourse.group/t/suppress-tbb-warning

Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by iDhanushReddy** [comment]
This  issue occurs sometimes when the path is not properly set in r"  ".  Check all the paths carefully after upgrading tbb.
