### ISSUE TITLE
Enumerate decrefs too eagerly

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6356]
- [x] I have tried using the ~latest released~ mainline version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This, under `NUMBA_OPT=1`:
```python
from numba import njit

@njit
def foo():
    for i, s in enumerate('a'):
        pass
    return s

foo()
```
double frees:
```
*** Error in `python': double free or corruption (fasttop): 0x00005614ae8001b0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x7f1fdae97299]
numba/core/runtime/_nrt_python.cpython-37m-x86_64-linux-gnu.so(+0x3e5e)[0x7f1fc1202e5e]
```
it's ok under `NUMBA_OPT=3`.

NRT trace under `NUMBA_OPT=1`:
```
$ NUMBA_OPT=1 python debug_enumerate.py 
NRT_Allocate bytes=42 ptr=0x5614ae8001b0
NRT_MemInfo_alloc_dtor_safe 0x5614ae8001d8 2
NRT_MemInfo_call_dtor 0x5614ae8001b0
nrt_internal_custom_dtor_safe 0x5614ae8001d8, (nil)
nrt_internal_dtor_safe 0x5614ae8001d8, (nil)
NRT_Free 0x5614ae8001b0
NRT_MemInfo_call_dtor 0x5614ae8001b0
nrt_internal_custom_dtor_safe 0x5614ae8001d8, (nil)
nrt_internal_dtor_safe 0x5614ae8001d8, (nil)
NRT_Free 0x5614ae8001b0
```
`0x5614ae8001b0` is obviously free'd twice.

Commenting this stops the double free but also leaks:
https://github.com/numba/numba/blob/c5788551c582711255dc6ab737e4c76a6e794155/numba/cpython/iterators.py#L66-L67

**Comment by stuartarchibald** [comment]
![_ZN8__main__7foo241E](https://user-images.githubusercontent.com/907717/95852098-17ec4300-0d4b-11eb-93a1-c8943109c967.png)

**Comment by sklam** [comment]
Attempted fix at: https://github.com/numba/numba/pull/6357

**Comment by esc** [comment]
#6357 fixed it, closing!
