### ISSUE TITLE
Inconsistent result for Numba in Metropolis-Hastings Distribution Implementation w/ SciPy interp2d

### ISSUE THREAD

**Issue by sdwebb** [numba/numba#6360]
I'm using a scipy interp2d on a dataset to implement a Metropolis-Hastings algorithm. The function to generate the MH sequence gives the right distribution for the data, while adding a `@numba.jit` decorator leads to an incorrect distribution. I have attached a minimum working example, which includes the dataset I'm using and a plot of the discrepancy.

My versions are:
`numba=0.51.2`
`scipy=1.5.2`
`numpy=1.19.1`

![comparison](https://user-images.githubusercontent.com/7430829/95948974-eefd9980-0dae-11eb-8501-44946218ea9f.png)
[numba_bug.zip](https://github.com/numba/numba/files/5375892/numba_bug.zip)

**Comment by esc** [comment]
@sdwebb thank you for submitting this to the Numba issue tracker. I have had a look at the code you submitted and have a few followup comments questions about it.

a) Numba itself does not support `scipy` out-of-the-box. There is an extension project here: https://github.com/numba/numba-scipy but I am not  sure that it supports `interp2d`. The result of this is that you will get error messages of the form:

```
 💣 zsh» python numba_bug.py
numba_bug.py:21: NumbaWarning:
Compilation is falling back to object mode WITH looplifting enabled because Function "random_MH_nb" failed type inference due to: non-precise type pyobject
During: typing of argument at numba_bug.py (25)

File "numba_bug.py", line 25:
def random_MH_nb(dist_func, y0, burnoff=10, sigma=1.):
    <source elided>
    # burnoff period
    theta_t = sigma*np.random.random()
    ^

  @numba.jit
/Users/vhaenel/git/numba/numba/core/object_mode_passes.py:151: NumbaWarning: Function "random_MH_nb" was compiled in object mode without forceobj=True.

File "numba_bug.py", line 22:
@numba.jit
def random_MH_nb(dist_func, y0, burnoff=10, sigma=1.):
^

  warnings.warn(errors.NumbaWarning(warn_msg,
/Users/vhaenel/git/numba/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning:
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "numba_bug.py", line 22:
@numba.jit
def random_MH_nb(dist_func, y0, burnoff=10, sigma=1.):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
python numba_bug.py  16.46s user 0.45s system 79% cpu 21.174 total
```

Which essentially tells you that Numba was unable to compile the function properly. 

b) You should also note that, if you compile a function with `@njit` the original function remains available as the `py_func` attribute of the decorated function. So in this case you could use `random_MH_nb.py_func(...)` and there is no necessity to duplicate the function.

c) I am not sure, what you mean by 'incorrect distribution', how is it incorrect? When I run this on my machine locally I obtain the following plot:

![comparison](https://user-images.githubusercontent.com/41563/95974559-6ebe4f00-0e15-11eb-977a-a0a78fac6bc9.png)

Which, by my naive interpretation looks like the two generated distributions are indeed quite similar? Could it be that you  just obtained a very skewed sample run? Or did I miss something?

**Comment by sdwebb** [comment]
@esc --

Thanks for pointing me at the `numba-scipy` library, I think I knew that scipy wasn't compatible with numba.

For c) I have run it multiple times and consistently get the figure I attached, so I'm confident it's an issue in the could. Could this be an OS related bug or some other version issue? I'm on Mac OS 10.15.7, with the aforementioned versions on what should be the relevant libraries.

**Comment by esc** [comment]
@sdwebb I am also on OSX 10.15.7 and I just installed the libraries you mentioned above and tried to run the code. I am unable to replicate the figure you posted. A question about the plot, how do you derive from the plot, that this is an incorrect distribution?

**Comment by esc** [comment]
@sdwebb just following up here, did you manage to gain any more insights. One thought might be to seed the random number generators to produce code that will produce the same results on other peoples machines.

**Comment by sdwebb** [comment]
@esc apologies, I got drowned by work.

The sampling is wrong because I would expect the histogram to line up with the green `dist` line. Mine consistently does not over any number of runs, and in fact is pretty consistent with the orange histogram in my figure. Are there any other dependencies I might be missing on my machine?

**Comment by stuartarchibald** [comment]
Numba's RNG is designed to produce, from the same input conditions in serial computation (no threads), identical sequences to that of NumPy and CPython. I'd start by setting the RNG seed in the code (make sure you set it in somewhere that's JIT compiled) and writing a test to assert that two runs with the same seed produce the same output. At this point it will be possible to start working out if there's a problem with Numba as there's a consistent numerical result against which to compare.

Example of setting the RNG seed with NumPy:

```python
In [35]: import numpy as np; from numba import njit

In [36]: def ex_rng_seed(seed, n):
    ...:     np.random.seed(seed)
    ...:     return np.random.random((n,))
    ...: 

In [37]: ex_rng_seed(123, 4)
Out[37]: array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [38]: njit(ex_rng_seed)(123, 4)
Out[38]: array([0.69646919, 0.28613933, 0.22685145, 0.55131477])
```

**Comment by sdwebb** [comment]
So, this took an odd turn.

While working with this, I fixed a small bug in the Metropolis-Hastings function itself, so the correct function reads as:

```python
def random_MH(dist_func, y0, burnoff=10, sigma=1.):

    # burnoff period
    theta_t = sigma*np.random.random()

    idx = 0
    while idx < burnoff:
        theta_star = np.random.normal(loc=theta_t, scale=sigma)
        alpha = min(dist_func(theta_star, y0)/dist_func(theta_t, y0), 1.)
        u = np.random.random()
        if u < alpha:
            theta_t = theta_star
        idx += 1

    new_value = False
    while new_value == False:
        theta_star = np.random.normal(loc=theta_t, scale=sigma)
        alpha = min(dist_func(theta_star, y0)/dist_func(theta_t, y0), 1.)
        u = np.random.random()
        if u < alpha:
            new_value = True
            theta_t = theta_star
        return theta_t
```

this involved taking the `idx+=1` out of the `if u < alpha` term, and the Numba and uncompiled functions agree. I'm not sure why that would lead to a difference in the Numba and uncompiled functions, but the problem seems to rest with that instead of the interp2d function.

**Comment by stuartarchibald** [comment]
All Numba dispatcher objects (the thing returned by the `@jit` decorator) have a `.py_func` attribute which is the function that the `@jit` decorator is wrapping, I'd recommend using that to compare results as it means you just have to maintain one implementation and can guarantee that the thing Numba is compiling and the thing CPython is interpreting is exactly the same. For example
```pycon
In [1]: from numba import njit

In [2]: @njit
   ...: def foo(x):
   ...:     a = 3
   ...:     if x < 2:
   ...:         return a + 4
   ...:     return 7
   ...: 

In [3]: arg = 1

In [4]: assert foo.py_func(arg) == foo(arg)
```

**Comment by esc** [comment]
@sdwebb does this mean algorithmically, the burnoff period is higher and so you wait for longer for the chain to reach equilibrium? The difference between Numba and non-Numba might in this case be due to the way in which the random numbers are sampled due to a different seeding of the random number generator or perhaps use of a different random number generator. Just a guess though.

**Comment by sdwebb** [comment]
Yes, that would make sense. Very interesting.

**Comment by gmarkall** [comment]
Is this issue now resolved?

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks and thank you @sdwebb for using Numba!
