### ISSUE TITLE
0.52.0RC1 issues

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6371]
Things broken on the farm for 0.52.0RC1:

1. CUDA 9 on windows 64bit, python 3.8, np1.18: `numba.cuda.tests.cudapy.test_multithreads.TheMultiThreadCompiling`, `self.assertEqual(p.exitcode, 0)` fails as `p.exitcode` is `0xC0000005`. CC @gmarkall 
2. PPC64LE and ARM7vl: `numba.tests.test_vectorization.TestVectorization.test_slp`, seems like it can't vectorize what's present to a `2 x double`.
3. OSX, all builds: Bizarrely, `numba.tests.npufunc.test_errors.TestFloatingPointExceptions.test_remainder_float` is failing with an assertion error, the length of the warnings/error messages doesn't match (essentially, none were found when one was expected).
4. Windows 32bit, all builds: Fails tests `numba.tests.test_vectorization.TestVectorization.*`, there's no `vector.body` in the LLVM IR. Also fails numerous tests in the family `numba.tests.test_dyn_array.TestNd*` with an integer size matching problem in the error message.
5. Linux x86_64, test environments containing SVML: Fails tests `numba.tests.tests_parfors.TestParforsVectorizer.{test_unsigned_refusal_to_vectorize, test_vectorizer_fastmath_asm}` errors are related to instruction generation being incorrect.
6. AArch64: `libm` has versioned symbol `GLIBC_2.29` missing. Testing fails.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/6372 sorts out 5.

**Comment by stuartarchibald** [comment]
@sklam investigated 3. Looks to be the split-optimiser with the cheap pass at `O1` being too strong, moving to `O0` seems to fix and could well increase compilation speed.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/6378 hopefully fixes 2 and half of 4.

**Comment by gmarkall** [comment]
>     1. CUDA 9 on windows 64bit, python 3.8, np1.18: `numba.cuda.tests.cudapy.test_multithreads.TheMultiThreadCompiling`, `self.assertEqual(p.exitcode, 0)` fails as `p.exitcode` is `0xC0000005`. CC @gmarkall

Another potential data point on this issue: https://github.com/numba/numba/pull/6367#issuecomment-712166266

**Comment by stuartarchibald** [comment]
Closing, all issue resolved.

**Comment by GillesC** [comment]
I still get 6. with version 0.54.0rc2:

```
    import numba
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/__init__.py", line 39, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/sim-wdnD78jmvr/.venv/lib/python3.9/site-packages/numba/_helperlib.cpython-39-aarch64-linux-gnu.so)
```

**Comment by stuartarchibald** [comment]
@GillesC thanks for the report, as this issue is for a closed and completed release, any chance you could please open a new issue with the problem you are seeing and describe your system in that? Many thanks for your help.
