### ISSUE TITLE
Can't AOT String Keyed Dictionaries:  undefined symbol: _numba_hashsecret_siphash_k1

### ISSUE THREAD

**Issue by DannyWeitekamp** [numba/numba#6386]
- [x] I have tried using the latest released version of Numba (0.51.2).
- [x] I have included below a minimal working reproducer 

Running this
```python
from numba.pycc import CC
from numba import i8
from numba.core.types import DictType, unicode_type
cc = CC('my_module')

nb_nt = DictType(unicode_type,i8)

@cc.export('foo',(DictType(unicode_type,i8),unicode_type))
def foo(d,x):
   if(x not in d):
      d[x] = len(d)

cc.compile()

import my_module
```
Produces this
```bash
Traceback (most recent call last):
  File "numba_error.py", line 15, in <module>
    import my_module
ImportError: /home/danny/my_module.cpython-38-x86_64-linux-gnu.so: undefined symbol: _numba_hashsecret_siphash_k1
```
I don't really know what's going on, but my best guess is this stuff:
https://github.com/numba/numba/blob/master/numba/cpython/hashing.py#L437
Isn't making its way into the .so

**Comment by DannyWeitekamp** [comment]
@stuartarchibald So I guess #6410 fixes this issue but now I've caught another. Running this with the changes in #6410 enabled

```python
from numba.pycc import CC
from numba import njit
from numba.core.types import unicode_type

cc = CC('my_module')

@cc.export('print_hash_A',(unicode_type,))
@njit
def print_hash_A(s):
   print(hash(s),hash('A'))

print_hash_A("A")

cc.compile()

from my_module import print_hash_A
from numba.typed import List, Dict

print_hash_A("A")
```
```bash
-2819232634433833240 -2819232634433833240
-2819232634433833240 2507792285634992701
```
It seems that if a string is instantiated inside an AOT compiled function it's hash function operates incorrectly. But if the string is instantiated in python and passed in it works fine. This has been giving me a number of weird bugs involving dictionaries. 
I can open a new issue for this, I'm not sure what is appropriate considering that this error is only reproducible off of a PR.

**Comment by stuartarchibald** [comment]
Thanks for looking at this some more. I think just post problems on here for now thanks, this is as good a place as any. I've look at the machine code, think the issue is here:
```asm
:	00 
    3401:	4c 8d 05 8c 8c 00 00 	lea    0x8c8c(%rip),%r8        # c094 <.bytes.-252770131550325040>
    3408:	48 89 e7             	mov    %rsp,%rdi
    340b:	48 8d 74 24 18       	lea    0x18(%rsp),%rsi
    3410:	41 b9 01 00 00 00    	mov    $0x1,%r9d
    3416:	e8 75 04 00 00       	callq  3890 <_ZN5numba7cpython7hashing15_siphash24$2414Eyy7void$2ax>
    341b
```
I need to look a bit deeper but it looks like the address of something is getting baked in and then the hash alg is called on that, hence constant and as it's an `int` the hash is just the value.

**Comment by DannyWeitekamp** [comment]
Wow I'm impressed that you can find anything in the assembly!?!
Here's my best attempt at figuring out what's going on. If I totally butcher _Py_HashBytes so that it just returns the hashsecret like this without even considering what it is hashing: 
```python
@register_jitable(locals={'_hash': _Py_uhash_t})
def _Py_HashBytes(val, _len):
    return process_return(types.uint64(_load_hashsecret('siphash_k0')))
```
Then running the script above gives me:
```bash
8479070453469464170 -6204705148984751709
8479070453469464170 0
```
which seems to indicate that in the AOT'd function the value of _numba_hashsecret_siphash_k0 isn't actually being assigned, and is instead taking the default value of zero. This also explains why every time I run this I get the same thing in that 4th printed value, the hash secret/seed is always the same.

**Comment by DannyWeitekamp** [comment]
I feel like a dummy. Just doing this fixed it:

```diff
diff --git a/numba/pycc/modulemixin.c b/numba/pycc/modulemixin.c
index cc6d176e3..ccfeb9340 100644
--- a/numba/pycc/modulemixin.c
+++ b/numba/pycc/modulemixin.c
@@ -116,6 +116,10 @@ PYCC(pycc_init_) (PyObject *module, PyMethodDef *defs,
                                     env_def_t *envs,
                                     env_gv_t *envgvs)
 {
+    _numba_hashsecret_siphash_k0 = _Py_HashSecret.siphash.k0;
+    _numba_hashsecret_siphash_k1 = _Py_HashSecret.siphash.k1;
+    _numba_hashsecret_djbx33a_suffix = _Py_HashSecret.djbx33a.suffix;
+
     PyMethodDef *fdef;
     PyObject *modname = NULL;
     PyObject *docobj = NULL;
```
dunno if that's a good place to put it but we can talk about it in the PR
