### ISSUE TITLE
Support __hash__ for numpy.datetime64

### ISSUE THREAD

**Issue by SleepingPills** [numba/numba#6393]
## Feature request
The numpy datetime64 type can't be used as a typed Dict key currently as Numba doesn't seem to implement a hash function for it.

E.g.
```
import numpy as np
from numba.typed import Dict

d = Dict()
d[np.datetime64("2000-01-01")] = 1
```

Fails with an error message stating that there is no `__hash__` attribute on datetime64[D]

**Comment by stuartarchibald** [comment]
Fairly sure that this is just not implemented yet. It's a bit tricky but not too hard to deal with, `__hash__` of the date time types is just their `int64` value.
