### ISSUE TITLE
Compilation time regression in 0.52rc1

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#6411]
hi, there seems to be compilation time regression in 0.52rc1

The following code runs in 40 seconds in 0.51, but in 0.52rc1 it does not complete after 5 minutes.

```python
from typing import Tuple, Callable, NamedTuple, Union
import time
import numpy as np
from numba import njit, literal_unroll


class COOFunctions(NamedTuple):
    data: Tuple[Callable[[int], Union[int, Tuple[int, ...]]], ...]
    rows: Tuple[int, ...]
    cols: Tuple[int, ...]


class COOVecs(NamedTuple):
    data: Tuple[np.ndarray, ...]
    rows: Tuple[int, ...]
    cols: Tuple[int, ...]


@njit
def foo(t):
    return 0, t *2


def make_looper(coo_fs):
    fs_enum = tuple(enumerate(coo_fs.data))

    @njit
    def get_values(out, t, vecs) -> np.ndarray:
        for x in literal_unroll(fs_enum):
            idx, fc = x
            out[coo_fs.rows[idx], coo_fs.cols[idx]] = vecs.data[idx][fc(t)]
        return out

    return get_values


n = 367
timing_funs = tuple([foo for _ in range(n)])
coo_fs = COOFunctions(timing_funs, tuple(range(n)), tuple(np.repeat(0, n)))
vecs_data = tuple([np.zeros((1, 1441)) for _ in range(n)])
vecs = COOVecs(vecs_data, tuple(range(n)), tuple(np.repeat(0, n)))
out = np.zeros((1000, 1000), np.float64)


looper = make_looper(coo_fs)
t = time.perf_counter()
res = looper(out, 0, vecs)
print(t-time.perf_counter())
```

I also ran with different n and got: n=30 took 37 seconds, n=40 took 153 seconds.

**Comment by gmarkall** [comment]
Could this be the fix? https://github.com/numba/llvmlite/pull/644 cc @sklam

**Comment by luk-f-a** [comment]
it might be, considering sklam's answer here: https://numba.discourse.group/t/code-generation-vs-literal-unroll/301/2

When I posted I was running on 0.51, so I took his answer to mean the difference between code generation and literal unroll. Maybe he was testing on 0.52 and already saw this problem.

**Comment by sklam** [comment]
Yes, this will be fixed by https://github.com/numba/llvmlite/pull/644. But I need to find a better solution so that I don't disable some pruning cases (the reason why the CI on that PR is failing).

**Comment by sklam** [comment]
https://github.com/numba/llvmlite/pull/644 is ready for review. The patch now keeps the compilation time close to pre 0.52

**Comment by stuartarchibald** [comment]
Closing as resolved by https://github.com/numba/llvmlite/pull/644
