### ISSUE TITLE
Numpy array  indexing lead to an error in numba 

### ISSUE THREAD

**Issue by balandongiv** [numba/numba#6415]
When indexing an array under numba-enclosed function, the compiler return an error:

```
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (BUILD_LIST_UNPACK) found
File "rcap_trans_par.py", line 57:
def my_numba(all_result,new_id):
    <source elided>
        long_tab = np.reshape ( np.array ( final_opt [[*num_pair], :] ), (-1, sub_group * main_group) )
```

In normal mode, the indexing process run successfully w./o any error thrown.

The code to reproduce the above error is as below.

```
import numpy as np
import itertools
from random import seed
from random import randint
import numexpr
from numba import jit


case_no = 40  
set_number = 6  
sub_group = 3  
case_select = {1: {'tot_length': 3, 'steps': 1, 'start_val': 1, 'main_group': 4},  # light_case
               2: {'tot_length': 600, 'steps': 1, 'start_val': 0, 'main_group': 1300}}  # extreme_case


case = 'light_case'
# case='extreme_case'
case_no = 1 if case == 'light_case' else 2

tot_length = case_select [case_no] ['tot_length'] 
steps = case_select [case_no] ['steps']
start_val = case_select [case_no] ['start_val']
main_group = case_select [case_no] ['main_group'] 

list_no = np.arange ( start_val, tot_length, steps, dtype=np.float32 )
x, y, z = np.meshgrid ( *[list_no for _ in range ( 3 )], sparse=True )

final_opt = list_no [np.array ( (numexpr.evaluate ( "((x >= y) & (y >= z))" )).nonzero () ).T]

final_opt [:, [0, 1]] = final_opt [:, [1, 0]]  # Is possible to swap the column from the above
all_result = itertools.product ( range ( 0, final_opt.shape [1] + 1 ), repeat=main_group )

seed ( 4 )
unique_comb = 11
new_id = [randint ( 0, unique_comb ) for _ in range ( set_number )] 

@jit ( nopython=True )
def my_numba (all_result, new_id):
    for num, num_pair in enumerate ( all_result, start=1 ):
        long_tab = np.reshape ( np.array ( final_opt [[*num_pair], :] ), (-1, sub_group * main_group) )
        column_sums = (np.ceil ( 1 // long_tab [:, new_id] )).sum ( axis=1 )


my_numba ( all_result, new_id )
```

**Comment by gmarkall** [comment]
Numba supports a subset of Python language features and libraries - the list of supported Python features is https://numba.readthedocs.io/en/stable/reference/pysupported.html, and the list of supported NumPy features is at https://numba.readthedocs.io/en/stable/reference/numpysupported.html.

In the example above, there are at least a couple of unsupported idioms:

- `[*num_pair]` building a list from unpacking an iterable is not supported
- `all_result` is an instance of `itertools.product`, which is unsupported.
- Some of the NumPy array indexing may be a bit too advanced for Numba (on the line computing `long_tab`)

To compile with Numba, `my_numba` would need to be rewritten using alternative constructs that are supported.

**Comment by gmarkall** [comment]
BTW - If you need some assistance in understanding how to rewrite this code in a way that it can be compiled with Numba, it would be a good thing to start a thread on the Numba Discourse: https://numba.discourse.group/

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
