### ISSUE TITLE
Building docs with NUMBA_LLVM_REFPRUNE_PASS

### ISSUE THREAD

**Issue by EPronovost** [numba/numba#6429]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When trying to build the docs locally, I need to set `NUMBA_LLVM_REFPRUNE_PASS=0` explicitly.  The default (1) causes the error

```
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/codegen.py", line 1086, in __init__
    self._init(self._llvm_module)
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/codegen.py", line 1107, in _init
    opt=0)
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/codegen.py", line 1143, in _module_pass_manager
    pm.add_refprune_pass(_parse_refprune_flags())
AttributeError: 'ModulePassManager' object has no attribute 'add_refprune_pass'
```

Command to reproduce: `NUMBA_LLVM_REFPRUNE_PASS=1 make html` (or omit env var if not already set).

**Comment by stuartarchibald** [comment]
Thanks for the report. Do you have a version of `llvmlite` which has the reference pruner pass in your local environment (llvmlite 0.35 series builds)? One way to enforce this might be to:
```
$ conda install -c numba llvmlite=0.35.0rc1
```

**Comment by EPronovost** [comment]
Ah that fixed it! I had done `pip install -U`, and it seems the `0.35.0` release candidates aren't on pypi.

**Comment by stuartarchibald** [comment]
Thanks for confirming.
