### ISSUE TITLE
Wrong call type resolved when overloading set of unicodes in Numba 0.52.0rc1

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#6431]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi,

We observe some kind of regression in 0.52.0rc1 with our code that is overloading `set` function, that returns some Numba extension type representing a set of unicodes. It seems #5639 changed the way how such calls are resolved, so that now if a user provides it's own implementation it's not compiled, due to the fact that built-in implementation exists (though it raises LoweringError). We have an obvious workaround to use separate func overload instead, so it's no blocking, but it looks strange that subsequent overload that provides working implementation is not used.

Consider the following example, which compiles on numba=0.51.2 and fails on numba=0.52.0rc1:
```
import operator
import numba
from numba import types
from numba.extending import (
    overload,
    models,
    register_model,
)
from numba.core.extending import intrinsic
from numba.core.typing import signature

class SetStrType(types.Opaque):
    def __init__(self):
        super(SetStrType, self).__init__(name='SetStrType')

register_model(SetStrType)(models.OpaqueModel)

@intrinsic
def set_ctor(typingctx, data):

    def codegen(context, builder, sig, args):
        newobj = context.get_dummy_value()
        return newobj

    sig = signature(SetStrType(), data)
    return sig, codegen

@overload(operator.contains)
def settype_op_contains_ovld(self, val):
    if not isinstance(self, SetStrType):
        return None

    def settype_op_contains_impl(self, val):
        return True

    return settype_op_contains_impl

@overload(set)
def set_of_str_ovld(data):
    if not (isinstance(data, types.Sequence)
            and isinstance(data.dtype, types.UnicodeType)):
        return None

    def set_of_str_impl(data):
        return set_ctor(data)

    return set_of_str_impl

@numba.njit
def test_impl(str_list):
    str_set = set(str_list)
    return 'b' in str_set

data = ['a', 'b', 'c', 'd']
print(test_impl(data))
```

The exact error is:
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Use of reference counted items in 'set()' is unsupported, offending type is: 'unicode_type'.

File "test_set_typeinfer.py", line 57:
def test_impl(str_list):
    str_set = set(str_list)
    ^

During: lowering "$6call_function.2 = call $2load_global.0(str_list, func=$2load_global.0, args=[Var(str_list, test_set_typeinfer.py:57)], kws=(), vararg=None)" at test_set_typeinfer.py (57)
```

Debugging shows that even there're multiple overloads for `set` during resolving call type, the built-in implementation for it is first, and on numba=0.52 it now returns a correct signature, so that next user provided overload is not compiled:

> self.templates[0](context).get_template_info()
{'kind': 'overload', 'name': 'SetBuiltin.generic', 'sig': '(args, kws)', 'filename': 'numba\\core\\typing\\setdecl.py', 'lines': (20, 31), 'docstring': None}
> self.templates[1](context).get_template_info()
{'kind': 'overload', 'name': 'set_of_str_ovld', 'sig': '(data)', 'filename': 'test_set_typeinfer.py', 'lines': (43, 52), 'docstring': None}

Below is the actual call-stack during type-inference:
```
MainThread - pid_23112_id_1741918417344	
	generic [setdecl.py:27]	                        # <---- this now returns correct signature: (reflected list(unicode_type)<iv=None>,) -> set(unicode_type)
	apply [templates.py:345]	
	get_call_type [functions.py:298]	        # so that the first template in self.templates is used
	_resolve_user_function_type [context.py:246]	
	resolve_function_type [context.py:194]	
	resolve_call [typeinfer.py:1538]	
	resolve [typeinfer.py:586]	
	__call__ [typeinfer.py:566]	
	propagate [typeinfer.py:154]	
	propagate [typeinfer.py:1063]	
	type_inference_stage [typed_passes.py:72]	    # and typemap['$6call_function.2']  would be  set(unicode_type)
	run_pass [typed_passes.py:94]	
	check [compiler_machinery.py:262]	
	_runPass [compiler_machinery.py:289]	
	_acquire_compile_lock [compiler_lock.py:32]	
	run [compiler_machinery.py:330]	
	_compile_core [compiler.py:385]	
	_compile_bytecode [compiler.py:414]	
	compile_extra [compiler.py:352]	
	compile_extra [compiler.py:602]	
	_compile_core [dispatcher.py:104]	
	_compile_cached [dispatcher.py:91]	
	compile [dispatcher.py:77]	
	compile [dispatcher.py:857]	
	_acquire_compile_lock [compiler_lock.py:32]	
	_compile_for_args [dispatcher.py:366]	
	<module> [test_set_typeinfer.py:62]	
```

And the LoweringError that is raised during lowering of set_constructor:
```
MainThread - pid_19828_id_2338040103360	
	_lookup [setobj.py:208]	
	_add_key [setobj.py:443]	
	add [setobj.py:495]	
	set_constructor [setobj.py:1191]	
	wrapper [base.py:1194]	
	__call__ [base.py:1164]	
	_lower_call_normal [lowering.py:994]	
	lower_call [lowering.py:761]	
	lower_expr [lowering.py:1023]	
	lower_assign [lowering.py:502]	
	lower_inst [lowering.py:327]	
	lower_block [lowering.py:230]	
	lower_function_body [lowering.py:216]	
	lower_normal_function [lowering.py:190]	
	lower [lowering.py:136]	
	run_pass [typed_passes.py:373]	
	run_pass [typed_passes.py:449]	
	check [compiler_machinery.py:262]	
	_runPass [compiler_machinery.py:289]	
	_acquire_compile_lock [compiler_lock.py:32]	
	run [compiler_machinery.py:330]	
	_compile_core [compiler.py:385]	
	_compile_bytecode [compiler.py:414]	
	compile_extra [compiler.py:352]	
	compile_extra [compiler.py:602]	
	_compile_core [dispatcher.py:104]	
	_compile_cached [dispatcher.py:91]	
	compile [dispatcher.py:77]	
	compile [dispatcher.py:857]	
	_acquire_compile_lock [compiler_lock.py:32]	
	_compile_for_args [dispatcher.py:366]	
	<module> [test_set_typeinfer.py:62]	
```

is propagated up the stack, but does not retrigger type-inference. 

So the question here is: should in this scenario subsequent overloads be actually compiled?

Kind Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue here is that prior to 0.52.0 this would have worked due to a bug, that bug is now fixed. What I think was happening was that the typing for the `set` constructor:
https://github.com/numba/numba/blob/d774cdd4e89c1929dda38fa6c7285e21a0fc129b/numba/core/typing/setdecl.py#L17-L31
rejected the list of unicode because the unicode type was not hashable (this is the bug) and as a result it meant you could write an overload for the `set` constructor that would be called should the one above reject it. In 0.52.0 unicode type inherits from hashable and so is accepted by the `set` constructor typing, however, that the unicode model is reference counted is not known at typing time, it's part of the target information, and as a result it's only when lowering occurs the error is raised. Fixes could include:
1. Make the `set` constructor typing only consider Numba internal types, this forcing users to implement their own `set` if they want to use such a thing with their type.
2. Make the target context part of typing logic (potentially huge change).
3. Rewrite `set` so it "just works" with reference counted types, but as this `set` implementation is "reflected" cf. "reflected list" it should just get a `typed.Set` counterpart instead and this implementation be retired.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Thanks!
