### ISSUE TITLE
Lowering Error while trying to run parallel with prange

### ISSUE THREAD

**Issue by ismaelbrowne** [numba/numba#6433]
Hello.
Whenever I run this code:
```
from numba import njit, prange

@njit(parallel=True)
def s(n):
    lis=[]
    for i in prange(n+1):
        lis.append(i)
    return lis

s(1)
``` 
It gives me LoweringError:
And if I make lis into an empty np array:
```
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def s(n):
    lis=np.empty(0)
    for i in prange(n+1):
        lis=np.append(lis,i)
    return lis
```
It gives 'ValueError: Failed in nopython mode pipeline (step: convert to parfors)
Use of reduction variable lis in an unsupported reduction function.'
And checking the internet I didnt find any solution to this.
Thanks in advance

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue with the first example is that lists are not thread safe, and so writing to them in a parallel loop is invalid. The issue with the second example is that it has a loop carried dependency (reducing in `lis`). If you want to write to a container in a parallel loop then a pattern that can work is to pre-allocate the container to the loop size and then write into a slot in that container based on the induction variable. For example:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def s(n):
    lis=np.empty((n + 1,))
    for i in prange(n + 1):
        lis[i] = i
    return lis

print(s(4))
```
Hope this helps?

**Comment by ismaelbrowne** [comment]
Thank you so much!

**Comment by ismaelbrowne** [comment]
And how would I apply this for this function?
```
from numba import njit, prange
import numpy as np

@njit
def triplePartition(n):
    lis=[]
    for i in range(n+1):
        for j in range(n-i+1):
            lis.append((i,j,n-i-j))
    return lis
```

**Comment by ismaelbrowne** [comment]
Also, sorry for closing and opening, I misclicked

**Comment by stuartarchibald** [comment]
No problem RE: open/close. 

As the above sample involving `triplePartition` is a more general question, I'd recommend asking it on the Numba discourse forum https://numba.discourse.group/ :) Thanks!
