### ISSUE TITLE
Typed List causes IPython console to hang when gets printed

### ISSUE THREAD

**Issue by ma-sadeghi** [numba/numba#6434]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

All elements of `numba`'s typed `List` get printed to `IPython` console, causing it to crash if the list is long. This doesn't happen with Python's native lists, as they get shortened when printed.

```python
In [1]: x = [1] * 1_000_000
In [2]: y = numba.typed.List(x)
In [3]: y
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Unfortunately I can't reproduce, though it'd probably make sense to fix this anyway. Are you using windows, I wonder if it's terminal/stdout/buffer related? Also, when you say "crash" what actually happens, does the terminal hang/segfault (access violation)/do nothing? Thanks in advance!

**Comment by ma-sadeghi** [comment]
I'm using Spyder IDE on Windows. Sorry, I misspoke, I didn't mean "crash", but it gets stuck until it succeeds in printing the entire list in the `IPython` console. I also realized that 1 million elements is not large enough for it to hang, but 10 million elements keeps my PC hanging for 10-20 sec.

**Comment by stuartarchibald** [comment]
@ma-sadeghi thanks for confirming, I think you are just experiencing the effect of buffering a large amount of output. I think this should be reasonable to fix, just by restricting the amount of printing done for the `List` type.

**Comment by stuartarchibald** [comment]
This is a good first issue. The task is to:
1. Add a limit to the amount of items printed if a `numba.typed.List`'s `__str__` method is called from within an `ipython` shell.
2. Add a test for the above to `numba.tests.test_typedlist`.

Location of code involved:
https://github.com/numba/numba/blob/0db8a2bcd0f53c0d0ad8a798432fb3f37f14af27/numba/typed/typedlist.py#L393-L397

Developer guide:
https://numba.readthedocs.io/en/stable/developer/contributing.html#getting-set-up

**Comment by ma-sadeghi** [comment]
@stuartarchibald I'd be more than happy to contribute to `numba`! I'll take a crack at it.

**Comment by stuartarchibald** [comment]
> @stuartarchibald I'd be more than happy to contribute to `numba`! I'll take a crack at it.

Great, thanks for taking it on!

**Comment by caljrobe** [comment]
@stuartarchibald @ma-sadeghi is this issue open for work? If so I would be happy to try and make my first contribution to numba!

**Comment by esc** [comment]
@caljrobe since no progress has been made so far, I would guess the issue is open for work if you don't hear back from @ma-sadeghi within a day or two.

**Comment by ma-sadeghi** [comment]
@stuartarchibald @caljrobe @esc I was a bit swamped, so couldn't get back to this issue promptly, sorry about that. I just opened up a PR that addresses this issue.
