### ISSUE TITLE
Creating coo_sparse matrix from numba typed List is significantly slower than Python list or numpy arrays

### ISSUE THREAD

**Issue by ma-sadeghi** [numba/numba#6435]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numpy as np
from numba.typed import List
from time import time
from scipy.sparse import coo_matrix


N = 1_000_000
M = 1_000_000
i = np.random.randint(0, N, size=M)
j = np.random.randint(0, N, size=M)
v = np.random.rand(M)

# Numpy arrays
t0 = time()
A = coo_matrix((v, (i, j)))
print(f"Numpy array: {time() - t0:.3f}")

# Numba typed List
i, j, v = [List(x) for x in [i, j, v]]

t0 = time()
A = coo_matrix((v, (i, j)))
print(f"Numba typed List: {time() - t0:.3f}")

# Python list
i, j, v = [list(x) for x in [i, j, v]]

t0 = time()
A = coo_matrix((v, (i, j)))
print(f"Python list: {time() - t0:.3f}")

# Numba typed List + conversion time
i, j, v = [List(x) for x in [i, j, v]]

t0 = time()
i, j, v = [np.array(x) for x in [i, j, v]]
A = coo_matrix((v, (i, j)))
print(f"Numba typed List + conversion time: {time() - t0:.3f}")

# Python list + conversion time
i, j, v = [list(x) for x in [i, j, v]]

t0 = time()
i, j, v = [np.array(x) for x in [i, j, v]]
A = coo_matrix((v, (i, j)))
print(f"Python list + conversion time: {time() - t0:.3f}")

```
```bash
Numpy array: 0.001
Numba typed List: 30.124
Python list: 0.305
Numba typed List + conversion time: 14.727
Python list + conversion time: 0.411
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is known behaviour and there's definitely room for improvement. However, the issue is essentially that the `typed.*` containers are designed to offer high performance containers in compiled code, all the examples above are in interpreted code and as a result there's a load of work having to be done to convert from the native representations in which the lists are stored to something that the CPython interpreter can consume. Example of using a `typed.List` in JIT code:
```python
from numba import njit
from numba.typed import List
import numpy as np
from time import time

runs = 5
np.random.seed(0)

n = 1000000
pl = [np.random.rand() for x in range(n)]
tl = List(pl)

def accumulate(lst):
    acc = 0.
    for x in lst:
        acc += x
    return acc

expected = accumulate(pl)

# python
ts = time()
for _ in range(runs):
    accumulate(pl)
print(f"Python: {time() - ts:.8f}")

# numba
jitted_accumulate = njit(accumulate)
jitted_accumulate(tl) # warm up

ts = time()
for _ in range(runs):
    jitted_accumulate(tl) # time it
ts = time()
print(f"Numba : {time() - ts:.8f}")

assert jitted_accumulate(tl) == expected
```

**Comment by stuartarchibald** [comment]
Also, for more general questions, I can recommend asking on the Numba discourse forum https://numba.discourse.group :)

**Comment by ma-sadeghi** [comment]
Thanks for your quick reply. Actually, I generate `i`, `j`, and `v` lists using a `numba`-jitted function, in which there's a for loop. That works perfectly fine and fast. The issue is that I eventually want to make this `coo_matrix` out of these three lists, which turned out to be the bottleneck.

**Comment by stuartarchibald** [comment]
> Thanks for your quick reply. Actually, I generate `i`, `j`, and `v` lists using a `numba`-jitted function, in which there's a for loop. That works perfectly fine and fast. The issue is that I eventually want to make this `coo_matrix` out of these three lists, which turned out to be the bottleneck.

No problem :)

I see, if you really need the `coo_matrix` form from SciPy and want to construct that from `typed.List` instances then I think you'll be hitting the general issues with iteration speed of the typed containers from the Python interpreter. Am wondering if we ought to just write some converter methods on `typed.List` to get back to CPython list or even an array (as I think `coo_matrix` would be happy with that). CC @esc have you looked into this already?

The just released today 0.52.0RC2 https://numba.discourse.group/t/numba-0-52-0-and-llvmlite-0-35-0-release-candidates/284/4 has a load of improvements to typed list performance in JIT code, expect more to be made incrementally.

**Comment by ma-sadeghi** [comment]
@stuartarchibald That'd be great and I look forward to that. 

I found a workaround though for now, instead of incrementally populating the `typed.List` in my `numba`-jitted for loop method, I now do the same thing but on a `numpy.empty` array. I get the fast performance out of the `numba` method, and `coo_matrix` is now happy with the `numpy.ndarray` data type!

Anyway, thank you for creating this great package! It's really helped me dramatically optimizing those hard-to-be-vectorized parts of the projects I'm working on, especially since I have almost zero experience writing low-level C code.

**Comment by stuartarchibald** [comment]
> @stuartarchibald That'd be great and I look forward to that.
> 
> I found a workaround though for now, instead of incrementally populating the `typed.List` in my `numba`-jitted for loop method, I now do the same thing but on a `numpy.empty` array. I get the fast performance out of the `numba` method, and `coo_matrix` is now happy with the `numpy.ndarray` data type!

Excellent, am pleased that you've found a way through :)

> Anyway, thank you for creating this great package! It's really helped me dramatically optimizing those hard-to-be-vectorized parts of the projects I'm working on, especially since I have almost zero experience writing low-level C code.

Glad you like it, many thanks for your support!
