### ISSUE TITLE
Numba Dict implementation lot slower than pure python Dict Implementation

### ISSUE THREAD

**Issue by chennupushkar** [numba/numba#6439]
```
Jitted Function:
    -----------------
    
    from numba.typed import List, Dict

    dict_A = Dict.empty(
             key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
             value_type=types.int64[:],
         )
    dict_B = Dict.empty(
         key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
         value_type=types.int64,
    )
    common_keys = List()  # This is list of tuples of type (types.unicode_type, types.unicode_type, types.unicode_type)
    
    @jit(nopython=True)
    def final_calculations(common_keys, dict_A, dict_B):
        final_out_dict = Dict.empty(
            key_type=types.int64,
            value_type=types.int64,
        )
        for key in common_keys:
            for v in dict_A.get(key):
                if key in dict_B:
                    if v not in final_out_dict:
                        final_out_dict[v] = 0
                    final_out_dict[v] += dict_B[key]
        return final_out_dict


       Non Jitted function:
        --------------------
        
        def final_calculations(common_keys, dict_A, dict_B):
            final_out_dict = defaultdict(int)
            for key in common_keys:
                for v in dict_A.get(key):
                    final_out_dict[v] += dict_B[key]
            return final_out_dict
           
```
Running `timeit` on Jitted functions shows it much slower than Non-Jitted function.
```
Results:

Jitted function:

    common_keys = List()
    dict_B[("4tglt", "101", "9")] = 90
    dict_B[("4tglt", "102", "102")] = 30
    common_keys.append(("4tglt", "101", "9"))
    dict_A[("4tglt", "101", "9")] = np.asanyarray([15013958])

%timeit final_calulations(common_keys, dict_A, dict_B)
27.3 µs ± 321 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
```
Non-Jitted Function:

        dict_B = {}
        dict_B[("4tglt", "101", "9")] = 90
        dict_B[("4tglt", "102", "102")] = 30
        common_keys = [("4tglt", "101", "9")]
        dict_A = {}
       dict_A[("4tglt", "101", "9")] = [15013958]

%timeit final_calulations(common_keys, dict_A, dict_B)
610 ns ± 5.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

Why is numba `Dict` operations lot slower than pure python Dict operations?

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a valid reproducer:
```python
from numba import types, jit
from numba.typed import List, Dict
import numpy as np
from time import time
from collections import defaultdict

# N iterations
niter = 20

dict_A = Dict.empty(
            key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
            value_type=types.int64[:],
        )
dict_B = Dict.empty(
        key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
        value_type=types.int64,
)
common_keys = List()  # This is list of tuples of type (types.unicode_type, types.unicode_type, types.unicode_type)
dict_B[("4tglt", "101", "9")] = 90
dict_B[("4tglt", "102", "102")] = 30
common_keys.append(("4tglt", "101", "9"))
dict_A[("4tglt", "101", "9")] = np.asanyarray([15013958])

@jit(nopython=True)
def final_calculations(common_keys, dict_A, dict_B):
    final_out_dict = Dict.empty(
        key_type=types.int64,
        value_type=types.int64,
    )
    for key in common_keys:
        for v in dict_A.get(key):
            if key in dict_B:
                if v not in final_out_dict:
                    final_out_dict[v] = 0
                final_out_dict[v] += dict_B[key]
    return final_out_dict

# warm up JIT
final_calculations(common_keys, dict_A, dict_B)

# time JIT
ts = time()
for _ in range(niter):
    final_calculations(common_keys, dict_A, dict_B)
print(f"Elapsed: {time() - ts}")

def final_calculations_python(common_keys, dict_A, dict_B):
    final_out_dict = defaultdict(int)
    for key in common_keys:
        for v in dict_A.get(key):
            final_out_dict[v] += dict_B[key]
    return final_out_dict

# time CPython
ts = time()
for _ in range(niter):
    final_calculations_python(common_keys, dict_A, dict_B)
print(f"Elapsed: {time() - ts}")
```
I think the answer is the same as https://github.com/numba/numba/issues/6435#issuecomment-719616995, essentially that Numba's typed containers are designed to be fast from JIT code, use from the CPython interpreter works but is inevitably slower as there's a load of work having to be done to convert from the native representations in which the typed container data is stored to something that the CPython interpreter can consume.

Will write a FAQ entry about this as it's come up twice in the past week.

**Comment by chennupushkar** [comment]
@stuartarchibald Thank you. Can you please suggest any work round to achieve the same functionality?

**Comment by mind6** [comment]
> @stuartarchibald Thank you. Can you please suggest any work round to achieve the same functionality?

Your inner loop has just 9 items. It seems the startup cost is a bit higher for numba function with typed Dict. Put a x100000 in your inner loop, I got 37x speedup from numba.

`#%connect_info
from numba import types, jit
from numba.typed import List, Dict
import numpy as np
from time import time
from collections import defaultdict

# N iterations
niter = 100000

dict_A = Dict.empty(
            key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
            value_type=types.int64[:],
        )
dict_B = Dict.empty(
        key_type=types.Tuple((types.unicode_type, types.unicode_type, types.unicode_type)),
        value_type=types.int64,
)
common_keys = List()  # This is list of tuples of type (types.unicode_type, types.unicode_type, types.unicode_type)
dict_B[("4tglt", "101", "9")] = 90
dict_B[("4tglt", "102", "102")] = 30
common_keys.append(("4tglt", "101", "9"))
dict_A[("4tglt", "101", "9")] = np.array([15013958], dtype=np.int64)

@jit(nopython=True)
def final_calculations(common_keys, dict_A, dict_B):
    final_out_dict = Dict.empty(
        key_type=types.int64,
        value_type=types.int64,
    )
    for i in range(niter):
        for key in common_keys:
            for v in dict_A.get(key):
                if key in dict_B:
                    if v not in final_out_dict:
                        final_out_dict[v] = 0
                    final_out_dict[v] += dict_B[key]
    return final_out_dict

# warm up JIT
final_calculations(common_keys, dict_A, dict_B)

# time JIT
%timeit final_calculations(common_keys, dict_A, dict_B)

def final_calculations_python(common_keys, dict_A, dict_B):
    final_out_dict = defaultdict(int)
    for i in range(niter):
        for key in common_keys:
            for v in dict_A.get(key):
                final_out_dict[v] += dict_B[key]
    return final_out_dict

# time CPython
%timeit final_calculations_python(common_keys, dict_A, dict_B)`

Thanks for your question because I did want to test the performance before I used it myself.

**Comment by mind6** [comment]
This question is comparing using numba typed.Dict in numba code, versus using python dict in python code. I also saw it was slower for numba version. This is so slow that it wouldn't be usable for dynamic names in the inner loop. 
```python
import numba

# N iterations
niter = 1000000

dict_nb = numba.typed.Dict.empty(
            key_type=types.unicode_type,
            value_type=types.int64,
        )
dict_py = {}

dict_nb['k1'] = dict_py['k1'] = 12345

@numba.jit(nopython=True)
def run_nb(d):
    for i in range(niter):
        d['k1'] += 1

def run_py(d):
    for i in range(niter):
        d['k1'] += 1

# warm up JIT
run_nb(dict_nb)

# time JIT
%timeit run_nb(dict_nb)
%timeit run_py(dict_py)
```
```
145 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
101 ms ± 4.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
