### ISSUE TITLE
0.52.0rc2 regression: invalid array data if used after print

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#6444]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Array data looks invalid if used after a print. Looks like a refcount issue:
```python
import numba
import numpy as np

@numba.njit
def f():
    A = np.ones(3)
    print(A)
    return A[0]

print(f())
```
```
[1. 1. 1.]
-9.868309920863368e+148
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is the diamond pruner:
```python
import numba
import numpy as np

@numba.njit
def f():
    A = np.ones(3)
    print(A)
    return A[0]

print(f())
f.inspect_cfg(f.signatures[0]).display(view=True)
cres = f.overloads[f.signatures[0]]
print(cres.metadata['prune_stats'])
```
Output:
```
$ NUMBA_LLVM_REFPRUNE_FLAGS='diamond' python issue6444.py 
[1. 1. 1.]
-9.868309920863368e+148
PruneStats(basicblock=0, diamond=2, fanout=0, fanout_raise=0)
```

**Comment by sklam** [comment]
This is coming from `NRT_adapt_ndarray_to_python` that is stealing a reference and the pruner did not account for the stealing.

**Comment by sklam** [comment]
[RC3 builts are now available](https://numba.discourse.group/t/help-us-testing-0-52-0-rc/327/10?u=sklam ) and it contains fixes for this issue.
