### ISSUE TITLE
Type inference with int size error

### ISSUE THREAD

**Issue by max3-2** [numba/numba#6452]
## Reporting a bug

During debugging a code I recently stumbled upon an error in `nopython` mode which I can't seem to resolve. I broke it down to the following sample - this is so simple I expect the error to be quite stupid, but I can't figure it out so this may be a bug? 

Running on newest pypi versions with macOS. I know printing is not good in numba but this is solely for demonstration.

This works and prints the type to int16
```
#!/usr/bin/env python3
import numba
import numpy as np
@numba.jit("i8[:](i4)", nopython=True)
def testIt(sizeOfB):
    b = np.ones((sizeOfB,), dtype=np.int16)
    print(b.dtype)
    b = b * 2
    for i in range(sizeOfB):
        if i < 3:
            b[i] = -2
        else: b[i] = 5
    return b

if __name__ == '__main__':
    print(testIt(10))
```

This fails with `No conversion from array(int64, 1d, C) to array(int16, 1d, A) for '$84return_value.1', defined at None`, the only difference being the i2 in the signature, which should be right

```
#!/usr/bin/env python3
import numba
import numpy as np
@numba.jit("i2[:](i4)", nopython=True)
def testIt(sizeOfB):
    b = np.ones((sizeOfB,), dtype=np.int16)
    print(b.dtype)
    b = b * 2
    for i in range(sizeOfB):
        if i < 3:
            b[i] = -2
        else: b[i] = 5
    return b

if __name__ == '__main__':
    print(testIt(10))
```

**Comment by sklam** [comment]
This is a known limitation of numba's type inference. With just NumPy, you get:
```python

In [15]: (np.ones(10, dtype=np.int16) * 0xfff).dtype
Out[15]: dtype('int16')

In [16]: (np.ones(10, dtype=np.int16) * 0xffff).dtype
Out[16]: dtype('int32')

In [17]: (np.ones(10, dtype=np.int16) * 0xffffffffff).dtype
Out[17]: dtype('int64')
```

The output type of the multiplication is conditional to the constant value of the RHS. 

Numba's type inference scheme cannot handle the dynamic result type and is preferring numeric accuracy thus opting for the `int64` output type in this case.

It is important to note that this NumPy promotion rule only applies to scalars. If you have a 1D array instead, the type promotion rule is the same as what you get with Numba:

```python
In [18]: (np.ones(10, dtype=np.int16) * np.asarray([0xffffffffff])).dtype
Out[18]: dtype('int64')

In [19]: (np.ones(10, dtype=np.int16) * np.asarray([0xf])).dtype
Out[19]: dtype('int64')
```

**Comment by sklam** [comment]
Closing because this is known limitation.
