### ISSUE TITLE
stencil kernel performance not scaling in njit(parallel=True)

### ISSUE THREAD

**Issue by animator** [numba/numba#6456]
```python
import numba as nb
import numpy as np

@nb.stencil
def kernel1(a):
    return 0.25 * (a[0, 1] + a[1, 0] + a[0, -1] + a[-1, 0])

@nb.njit
def calc1(in_arr):
    out_arr = kernel1(in_arr)
    return out_arr

@nb.njit(parallel= True) 
def calc2(in_arr):
    out_arr = kernel1(in_arr)
    return out_arr

@nb.njit
def calc3(in_arr):
    out_arr = np.zeros(in_arr.shape)
    for i in range(1, in_arr.shape[0]-1):
        for j in range(1, in_arr.shape[1]-1):
            out_arr[i,j] = 0.25 * (in_arr[i, j+1] + in_arr[i+1, j] + in_arr[i, j-1] + in_arr[i-1, j])
    return out_arr

@nb.njit(parallel=True)
def calc4(in_arr):
    out_arr = np.zeros(in_arr.shape)
    for i in range(1, in_arr.shape[0]-1):
        for j in range(1, in_arr.shape[1]-1):
            out_arr[i,j] = 0.25 * (in_arr[i, j+1] + in_arr[i+1, j] + in_arr[i, j-1] + in_arr[i-1, j])
    return out_arr


input_arr = np.linspace(1, 50000, 500000000).reshape((50000, 10000))
```

For a large matrix (`input_arr`), I am experiencing the following run times (avg. 5 runs):
`calc1(input_arr)` [njit + stencil] - `2.09s`
`calc2(input_arr)` [Parallel njit + stencil] - `2.35s`
`calc3(input_arr)` [njit + Loops] - `2.10s`
`calc4(input_arr)` [Parallel njit + Loops] - `1.08s`

As per the above timings, `njit + stencil` is performing similar to `njit + Loops`, as by-default the stencil kernels are not executed in parallel.
I am trying to understand why `Parallel njit + stencil` is not performing similar to `Parallel njit + Loops`?
How can I parallelize the stencil execution?
I have 16 threads available on my machine.

Any solution will be highly appreciated. Thank you!

The first time this issue was mentioned in Github - https://github.com/numba/numba/issues/2982

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by sklam** [comment]
I can confirm the performance seen here. I saw multiple threads running and the process taking 200% cpu time in `parallel=True` versions. 

Ping @DrTodd13.

**Comment by DrTodd13** [comment]
@animator I believe the problem is that when stencil parfor calls a kernel it allocates the result with np.full with the stencil's cval.  I guess np.full with 0 is much slower than np.zeros.  If you pre-allocate the output using np.zeros and then pass it to the kernel as calc2(in_arr, out=out_arr) then I think you'll see that that is equivalent to calc4 (my local testing shows this to be true).  This is a workaround but I am working on a permanent fix to allocate the output with np.empty and to only fill in the borders with cval.  Hopefully that is much faster than np.full.

**Comment by animator** [comment]
Thank you for investigating @DrTodd13 . Eagerly waiting for the fix.

Regards.

**Comment by pauljurczak** [comment]
I described a similar problem in my post https://numba.discourse.group/t/the-future-of-kernel-programming-style-with-numba/1363.

I did a few tests using stencil and the results are not great. This snippet:
```
import numba as nb
import numpy as np
import timeit as ti

def ker0(a):
  return 42*a

@nb.stencil
def ker(a):
  return 42*a[0, 0]

@nb.njit(fastmath=True)
def ker1(a):
  return ker(a)

@nb.njit(fastmath=True, parallel=True)
def ker2(a):
  return ker(a)

a = np.arange(10000).reshape((100, 100))

for i in range(3):
  fun = f'ker{i}(a)'
  t = 1000 * np.array(ti.repeat(stmt=fun, setup=fun, globals=globals(), number=1, repeat=100))
  print(f'{fun}:  {np.amin(t):6.3f}ms  {np.median(t):6.3f}ms')
```
produces:
```
ker0(a):   0.005ms   0.005ms
ker1(a):   0.009ms   0.009ms
ker2(a):   0.020ms   0.020ms
```
on a 6-core CPU with Python 3.10.4. Parallel mode slows stencil down.
