### ISSUE TITLE
Array assignment to a structure's nested array 

### ISSUE THREAD

**Issue by ceo-domido** [numba/numba#6473]
Impossible to assign an array to the nested array in the structured array. Without numba all the options below are working, but with numba only the last option works. 

- The first option falls with an error "Can only insert i8 at [0] in [1024 x i8]: got i8*". 
- The second option falls with "Buffer dtype cannot be buffer, have dtype: nestedarray(uint8, (1024,))"
- The third option falls with "Buffer dtype cannot be buffer, have dtype: nestedarray(uint8, (1024,))"

```
import numba as nb
import numpy as np

BLOCK = np.dtype([("id", np.uint64), ("props", (np.uint8, 1024))])

@nb.njit()
def set_props1(_source, _target):
    _target[0]["props"] = _source[0]["props"]

@nb.njit()
def set_props2(_source, _target):
    _target["props"][0] = _source["props"][0]

@nb.njit()
def set_props3(_source, _target):
    for i in range(1024):
        _target["props"][0, i] = 1

@nb.njit()
def set_props4(_source, _target):
    for i in range(1024):
        _target[0]["props"][i] = 1

source = np.ones(1, dtype=BLOCK)
target = np.zeros(1, dtype=BLOCK)
set_props1(source, target)
print(target)
set_props2(source, target)
print(target)
set_props3(source, target)
print(target)
set_props4(source, target)
print(target)

```

**Comment by esc** [comment]
@ceo-domido - thank you for reporting this on the Numba issue tracker. I can reproduce this locally and it seems fine with Numpy but broken with Numba.

**Comment by stuartarchibald** [comment]
This is a bug. Something like this probably works fine:
```python
import numba as nb
import numpy as np

BLOCK = np.dtype([("id", np.uint64), ("props", (np.uint8, 1024))])

@nb.njit()
def set_props1(_source, _target):
    _target[0]["props"][:] = _source[0]["props"] # NOTE THE SLICE

source = np.ones(1, dtype=BLOCK)
target = np.zeros(1, dtype=BLOCK)
set_props1(source, target)
print(target)
```

**Comment by HPLegion** [comment]
I think I ran into a related isse: https://numba.discourse.group/t/structured-arrays-with-nd-fields/496

**Comment by astoeriko** [comment]
I think that I am seeing the same issue with the current numba version (0.53.1) when trying to convert to a numpy array:
```python
import numba
import numpy as np

@numba.njit
def foo(val):
    x = np.empty_like(val.x)
    x[:] = val.x
    return x

@numba.njit
def bar(val):
    np.asarray(val.x)

val = np.zeros(1, dtype=[("x", "float64", (10,))])[0]

foo(val) # works fine
bar(val) # fails
```

**Comment by gmarkall** [comment]
Now that #7359 is merged, this is fixed. (cc @luk-f-a)

**Comment by luk-f-a** [comment]
wow, so many issues addressed by that PR
