### ISSUE TITLE
Update canonical_url configuration in docs

### ISSUE THREAD

**Issue by seibert** [numba/numba#6479]
I think we need to fix the canonical_url in our generated docs, especially now that we have moved documentation to RTD.  This should help search engines direct users to the latest documentation even after indexing older versions.    According to the sphinx RTD theme, the URL should be the base path:

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-canonical_url

I think we did this incorrectly before (linking to the index file, rather than the base URL), so we will need to fix the path as well as relocate to the new Numba docs domain:

https://github.com/numba/numba/blob/master/docs/source/conf.py#L125

**Comment by seibert** [comment]
for more info about how canonical URLs are treated by search engines: https://yoast.com/rel-canonical/

(hat tip to the Kevin Sheppard on the NumPy mailing list for the link)

**Comment by stuartarchibald** [comment]
Added https://github.com/numba/numba/pull/6531, not sure if it's right.
