### ISSUE TITLE
Wrap around negative indexing for cuda atomic operations

### ISSUE THREAD

**Issue by RendersJens** [numba/numba#6496]
## Feature request

The CUDA atomic operations currently do not support negative indices as offset from the end of the array. One would expect that

`cuda.atomic.add(ary, idx, val)`
performs
`ary[idx] += val`
Like the docs state, independent of whether idx is negative or positive. This can lead to anoying bugs to track down if you translate sequential code to parallel code.

**Comment by gmarkall** [comment]
I think the documentation is further misleading - for example, might one expect:

```
cuda.atomic.add(ary, slice(2,4), val)
```

to add `val` to elements 2 and 3 of `ary`?

I think this is both a documentation bug and a feature request, so I'll label as such.

**Comment by ashutoshvarma** [comment]
Adding support for negative indices seems pretty easy to me, as `cgutils.get_item_pointer` already support wraparound.
https://github.com/numba/numba/blob/00ad12751725391e8423d67ef845ba56110c55df/numba/cuda/cudaimpl.py#L610
https://github.com/numba/numba/blob/00ad12751725391e8423d67ef845ba56110c55df/numba/core/cgutils.py#L667-L668

**Comment by gmarkall** [comment]
This is now implemented.
