### ISSUE TITLE
got an unexpected keyword argument 'boundscheck'

### ISSUE THREAD

**Issue by futuremoneybtc** [numba/numba#6511]
**Please correct my code** 

import time
from numba import jit, cuda
import random

@jit(target ="cpu")
def ran():
    a = random.randint(4572817073304302,9145634146608603)
    return a

while 1 == 1:

    start_time = time.time()
    i = 10000000
    while i >= 1:
        z = ran()
        b = z*2017
    
        i = i -1
    print("--- %s seconds ---" % (time.time() - start_time),b)
    break

**output is --- 3.242293357849121 seconds --- 13321781515078407442**

And when I select "cuda" instead of "cpu" I got an error 

**TypeError: compile_kernel() got an unexpected keyword argument 'boundscheck'**

**Comment by seibert** [comment]
If you want to compile and run code on CUDA with Numba, you either need to write a `@vectorize` or `@guvectorize` function, or write a custom CUDA kernel.  You might find this tutorial helpful if you are getting started with Numba on the GPU:

https://github.com/ContinuumIO/gtc2020-numba

**Comment by gmarkall** [comment]
Also, note that the use of the `target` kwarg with the jit decorator was deprecated in Numba 0.51:

- https://github.com/numba/numba/pull/5980 
- https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-the-target-kwarg

Instead, the `@cuda.jit` decorator should be used.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
