### ISSUE TITLE
LiteralStrKeyDict error for non-identifier key names

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#6518]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

`LiteralStrKeyDict` creates a `namedtuple` in its constructor which requires key names to be valid identifiers, leading to unexpected errors. Seems to me like this can be avoided.
https://github.com/numba/numba/blob/d12bb5946527e2ef75f25136e89a53b156cb9b54/numba/core/types/containers.py#L775
```python
import numba

@numba.njit
def f():
    a = {"A+1": 4, "B": "C"}
    return a["A"]

print(f())
```
```
Traceback (most recent call last):
  File "../tmp/numba_litstrdict.py", line 9, in <module>
    print(f())
  File "/Users/ehsan/dev/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/ehsan/dev/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/ehsan/dev/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.BuildMapConstraint object at 0x7fecd29301f0>.
Type names and field names must be valid identifiers: 'A+1'
During: typing of dict at ../tmp/numba_litstrdict.py (5)
Enable logging at debug level for details.

File "../tmp/numba_litstrdict.py", line 5:
def f():
    a = {"A+1": 4, "B": "C"}
    ^
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This sort of thing isn't implemented as the `LiteralStrKeyDict` leans on `NamedTuple` for a lot, including lowering, not sure how hard it would be to decouple this.

**Comment by sklam** [comment]
I wonder if we can avoid a massive change if we only change away from the `namedtuple` in the container type but the numba lowering is still using a namedtuple. The numba lowered NamedTuple probably does not care about the field names.
