### ISSUE TITLE
typed.List.extend returns self in some cases

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#6523]
```python
from numba.typed import List
  ...: my_list = List([1,2])
  ...: print(my_list.extend(List([1,2])))
  ...: print(my_list.extend(tuple()))
None
[1, 2, 1, 2]
```

It should always return None but in some cases it's returning self. Below is python list's behaviour.

```python
  ...: my_list = list([1,2])
  ...: print(my_list.extend(list([1,2])))
  ...: print(my_list.extend(tuple()))
None
None
```
_Originally posted by @luk-f-a in https://github.com/numba/numba/issues/5958#issuecomment-734750145_

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bug. I note in the implementation of `typed.List` that a number of "extend" related functions are returning the value from calling the implementing function, which probably shouldn't happen either, even if `None`.
