### ISSUE TITLE
inconsistency in assignment to global variables

### ISSUE THREAD

**Issue by yusosov** [numba/numba#6525]
Why assigning to global real is legal in nopython=True while
assigning to global numpy.array is illegal in nopython=True?

import numba
print(numba.__version__)
output: 0.51.2 (latest in conda)

THIS COMPILES:
a=0
@numba.jit(nopython=True, nogil=True, cache=True)
def f():
    a=1
    return a
f()
output: 1

DOES NOT COMPILE:
import numpy
maxLen=3
a=numpy.zeros(maxLen,dtype=int)
@numba.jit(nopython=True, nogil=True, cache=True)
def f():
    for i in range(maxLen):
        a[i]=1
    return a
f()
output with nopython=False: array([1, 1, 1])
with nopython=True:
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
setitem(readonly array(int64, 1d, C), int64, Literal[int](1))
def f():
    for i in range(maxLen):
        a[i]=1
        ^

In both examples are assignments to global variables.

**Comment by gmarkall** [comment]
Because globals are frozen as constants: https://numba.readthedocs.io/en/stable/reference/pysemantics.html#global-and-closure-variables

In your first example, you're not writing to the global `a`, you're writing to the local `a`. If we do:

```python
from numba import njit

a=0

@njit(nopython=True, nogil=True, cache=True)
def f():
    a=1
    return a

print(f())
print(a)
```

we get:

```
1
0
```

**Comment by stuartarchibald** [comment]
Thanks for the question, Numba has a [discourse forum](https://numba.discourse.group/) which is great for questions like this, perhaps consider posting there next time?

To answer your question, Numba considers globals as compile time constants, here's the related [FAQ entry](https://numba.readthedocs.io/en/stable/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable). Hope this helps.

**Comment by gmarkall** [comment]
Closing as answered / further discussion should move to Discourse.

**Comment by yusosov** [comment]
sorry, you are wrigt, this was my mistake
now it is consistant
`@njit(nopython=True, nogil=True, cache=True)
def f():
    global a
    a=1
    return a`
