### ISSUE TITLE
Support prefer_literal option for intrinsic decorator

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#6533]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi, 

I noticed that `prefer_literal` option that was added recently for overload decorators is not supported for `intrinsic`.
It seems that `make_intrinsic_template` does not have prefer_literal argument (unlike for example `make_overload_template`) and moreover objects of `_Intrinsic` class do not store any options at all. At the same time intrinsic templates are created from base `FunctionTemplate`, which has `prefer_literal` hardcoded to False:
https://github.com/numba/numba/blob/4f985a5d90c4202c5f77bbd05fcff894200752de/numba/core/typing/templates.py#L261

This results in multiple calls to `get_call_type` with non-literal arguments during type-inference and may cause subtle issues if intrinsic code does not have correct input type checks. For instance the output of the following script

```
import numba
from numba import types
from numba.extending import overload, intrinsic
from numba.core.typing.templates import signature
import numpy as np

@intrinsic
# @intrinsic(prefer_literal=True)
def tuple_take(typingctx, data, idxs):

    print("DEBUG: tuple_take: data", data)
    print("DEBUG: tuple_take: idxs", idxs)
    if not isinstance(data, types.Tuple):
        return None
    if not (isinstance(idxs, types.Tuple)
            and all(isinstance(x, types.IntegerLiteral) for x in idxs)):
        return None

    old_ncols = len(data)
    unlit_keep_idxs = [a.literal_value for a in idxs]
    keep_col_idxs, new_typs = zip(*((i, t) for i, t in enumerate(data) if i in unlit_keep_idxs))
    def codegen(context, builder, signature, args):
        old_data = args[0]
        new_data = [
            builder.extract_value(
                old_data,
                types.intp(i)
            ) for i in range(old_ncols) if i in keep_col_idxs
        ]

        res = context.make_tuple(builder, ret_typ, new_data)
        return res

    ret_typ = types.Tuple(new_typs)
    sig = signature(ret_typ, data, idxs)
    return sig, codegen

def foo(data, idxs):
    pass

@overload(foo, prefer_literal=True)
def foo_ovld(data, idxs):
    print(f"DEBUG: foo: data={data}")
    print(f"DEBUG: foo: idxs={idxs}")

    def foo_impl(data, idxs):
        return tuple_take(data, idxs)
    return foo_impl

@numba.njit
def test_func():
    data = ('a', [2, 3], np.nan, 600)
    keep_idxs = (1, 3)
    return foo(data, keep_idxs)

res = test_func()
print(f"DEBUG: res={res}")
```
shows that we entered `tuple_take` code twice with non-literal arguments
> DEBUG: foo: data=Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
> DEBUG: foo: idxs=Tuple(Literal[int](1), Literal[int](3))
> DEBUG: tuple_take: data Tuple(unicode_type, list(int64)<iv=None>, float64, int64)
> DEBUG: tuple_take: idxs UniTuple(int64 x 2)
> DEBUG: tuple_take: data Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
> DEBUG: tuple_take: idxs Tuple(Literal[int](1), Literal[int](3))
> DEBUG: tuple_take: data Tuple(unicode_type, list(int64)<iv=None>, float64, int64)
> DEBUG: tuple_take: idxs UniTuple(int64 x 2)
> DEBUG: res=([2, 3], 600)

and in the ideal case it can be this way:
> DEBUG: foo: data=Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
> DEBUG: foo: idxs=Tuple(Literal[int](1), Literal[int](3))
> DEBUG: tuple_take: data Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
> DEBUG: tuple_take: idxs Tuple(Literal[int](1), Literal[int](3))
> DEBUG: res=([2, 3], 600)

Can this be changed in the future and prefer_literal added to intrinsic too?

BR,
Alexey.

**Comment by sklam** [comment]
The requested changes makes sense and it should be very easy to accomplish.

**Comment by sklam** [comment]
Tips for implementation:

- Plumbing needed to set `prefer_literal` at https://github.com/numba/numba/blob/4f985a5d90c4202c5f77bbd05fcff894200752de/numba/core/typing/templates.py#L878-L879 from `@intrinsic(prefer_literal=True)`
- other changes needed at https://github.com/numba/numba/blob/4f985a5d90c4202c5f77bbd05fcff894200752de/numba/core/extending.py#L280-L282, and https://github.com/numba/numba/blob/4f985a5d90c4202c5f77bbd05fcff894200752de/numba/core/extending.py#L308
- a test can be created from the reproducer code in this issue.

**Comment by ashutoshvarma** [comment]
I would love to contribute back to numba, can I work on this one? @sklam

**Comment by esc** [comment]
@ashutoshvarma thank you for asking about this. I see you have already started, that's the spirit! Good luck with the implementation!

**Comment by ashutoshvarma** [comment]
Thanks for your reply! @esc 


@kozlov-alexey Its not related to this issue but I kept getting `MemoryError` while running your code snippet on latest numba.
```console
❯ python _test.py
DEBUG: foo: data=Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
DEBUG: foo: idxs=Tuple(Literal[int](1), Literal[int](3))
DEBUG: tuple_take: data Tuple(unicode_type, list(int64)<iv=None>, float64, int64)
DEBUG: tuple_take: idxs UniTuple(int64 x 2)
DEBUG: tuple_take: data Tuple(Literal[str](a), list(int64)<iv=[2, 3]>, float64, Literal[int](600))
DEBUG: tuple_take: idxs Tuple(Literal[int](1), Literal[int](3))
DEBUG: tuple_take: data Tuple(unicode_type, list(int64)<iv=None>, float64, int64)
DEBUG: tuple_take: idxs UniTuple(int64 x 2)
MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_test.py", line 56, in <module>
    res = test_func()
SystemError: CPUDispatcher(<function test_func at 0x7f1760a6d8b0>) returned a result with an error set
```
Replacing list `[2,3]` in `data` variable with tuple `(2,3)` seems to fix this.

**Comment by stuartarchibald** [comment]
> Thanks for your reply! @esc
> 
> @kozlov-alexey Its not related to this issue but I kept getting `MemoryError` while running your code snippet on latest numba.
> 

Example is segfaulting, probably need to incref the list:
```python
    def codegen(context, builder, signature, args):
        old_data = args[0]
        new_data = [
            builder.extract_value(
                old_data,
                types.intp(i)
            ) for i in range(old_ncols) if i in keep_col_idxs
        ]
        context.nrt.incref(builder, new_typs[0], new_data[0])

        res = context.make_tuple(builder, ret_typ, new_data)
        return res
```
