### ISSUE TITLE
bytecode analysis failure with `BUILD_TUPLE_UNPACK`.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6534]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
from numba import njit

@njit
def foo(x):
    return (*x,)

foo((1,2))
```
does this:
```
<path>/numba/core/byteflow.py in _build_tuple_unpack(self, state, inst)
    846         state.append(inst, tuples=tuples, temps=temps)
    847         # The result is in the last temp var
--> 848         state.push(temps[-1])
    849 
    850     def op_BUILD_TUPLE_UNPACK_WITH_CALL(self, state, inst):

IndexError: Failed in nopython mode pipeline (step: analyzing bytecode)
list index out of range
```

**Comment by sklam** [comment]
bug confirmed on py3.7

**Comment by stuartarchibald** [comment]
yeah, it's been around a while, just hit it whilst trying to work out whether to peephole the python 3.9 bytecode back to using this or workout how to make lists into tuples.
