### ISSUE TITLE
Pypi wheels fail to install on Windows

### ISSUE THREAD

**Issue by duburcqa** [numba/numba#6538]
## Reporting a bug

`pip install numba` on a clean setup is failing on Windows because it is trying to build `llvmlite` version `0.35.0` from source. I guess it is because `lvmlite==0.35.0` do not provide any wheel for Windows 64 bits for now.

**Comment by esc** [comment]
@duburcqa Numba 0.52.0 and llvmlite 0.35.0 were tagged this week. During the release process some inconsistencies may arise as packages take time to arrive on the package repositories such as PyPi. However, I just checked and the Python 3.6/3.7/3.8 wheels are all present, so  it should have worked. Other causes for  this symptom are your Python  being too new, we  don't  support 3.9 yet or your `pip` being too old, it needs 19.0 (if I am not mistaken).

**Comment by duburcqa** [comment]
I'm not using Python 3.9. But I just notice that the wheels for `llvmlite` have been released just 1hour ago. So it should be working now.

**Comment by duburcqa** [comment]
My point is, every wheel of numba dependences, such as `llvmlite`, should be available before releasing `numba` itself on Pypi. Otherwise continuous integration is failing in the meantime for projects depending on `numba`, which is very inconvenient.

**Comment by esc** [comment]
@duburcqa thank you for reporting back. We are in agreement about wheels needing to exist. In this case, it was an unknown glitch which meant some of the llvmlite wheels didn't arrive in time.

**Comment by duburcqa** [comment]
Great ! Thank you for your time :+1:
