### ISSUE TITLE
Dead branch (optional argument test) not being pruned before type inference

### ISSUE THREAD

**Issue by batterseapower** [numba/numba#6541]
- [0.51.2] I have tried using the latest released version of Numba: I actually used 0.51.2, which is the most recent in Anaconda, rather than the bleeding edge 0.52.0.
- [x] I have included a self contained code sample to reproduce the problem.

With the following code, I expect both of the `f` calls to succeed:

```
@nb.njit()
def f(xs, out=None):
    N, = xs.shape
    if out is None:
        out = np.arange(N)
    else:
        assert np.all((0 <= out) & (out < N))
    out[:] = N
    return out


f(np.array([3, 1, 2]))
f(np.array([3, 1, 2]), out=np.arange(3, dtype='i8'))
```

But in fact the first call fails with a `TypingError` because numba can't compare `None` to an `int` when compliing the `is not None` branch of the else (full stack trace below). The second call is OK.

Judging by https://github.com/numba/numba/issues/3585#issuecomment-446302215, I think the expected behaviour is that when `out` is None, the `else` branch will be pruned before type checking so this type error shouldn't happen. I suppose that in this example something must be blocking the pruning from taking place.

For what it's worth, I think this code did work in some earlier version of numba. (I haven't run the affected file for maybe 1-2 years so I'm not quite sure which numba version it was working with.)

```
TypingError                               Traceback (most recent call last)
<ipython-input-4-1e4e60a654dd> in <module>
----> 1 f(np.array([3, 1, 2]))

~\Anaconda3\envs\py3_1\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~\Anaconda3\envs\py3_1\lib\site-packages\numba\core\dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359
    360         argtypes = []

~\Anaconda3\envs\py3_1\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function le>) found for signature:

 >>> le(Literal[int](0), none)

There are 20 candidate implementations:
  - Of which 18 did not match due to:
  Overload of function 'le': File: <numerous>: Line N/A.
    With argument(s): '(int64, none)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'le': File: unknown: Line unknown.
    With argument(s): '(int64, none)':
   No match for registered cases:
    * (bool, bool) -> bool
    * (int8, int8) -> bool
    * (int16, int16) -> bool
    * (int32, int32) -> bool
    * (int64, int64) -> bool
    * (uint8, uint8) -> bool
    * (uint16, uint16) -> bool
    * (uint32, uint32) -> bool
    * (uint64, uint64) -> bool
    * (float32, float32) -> bool
    * (float64, float64) -> bool

During: typing of intrinsic-call at <ipython-input-3-162a2050856a> (7)

File "<ipython-input-3-162a2050856a>", line 7:
def f(xs, out=None):
    <source elided>
    else:
        assert np.all((0 <= out) & (out < N))
        ^
```

**Comment by batterseapower** [comment]
The workaround is to use `generated_jit`, as suggested in the comment on #3585

```
@nb.generated_jit(nopython=True)
def merge_argsort(xs, out=None):
    if isinstance(out, (nb.types.NoneType, nb.types.Omitted)):
        def f(xs, out):
            N, = xs.shape
            out = np.arange(N)
            out[:] = N
            return out
    else:
        def f(xs, out):
            N, = xs.shape
            assert np.all((0 <= out) & (out < N))
            out[:] = N
            return out

    return f
```

**Comment by sklam** [comment]
I can confirm the error. It looks like the reusing of `out` is confusing the pruner. If I use a new variable like below, it will work:

```python
import numba as nb
import numpy as np

@nb.njit()
def f(xs, out=None):
    N, = xs.shape
    if out is None:
        out1 = np.arange(N)   # store to new variable
    else:
        assert np.all((0 <= out) & (out < N))
        out1 = out                    # store to new variable
    out1[:] = N
    return out1


f(np.array([3, 1, 2]))
f(np.array([3, 1, 2]), out=np.arange(3, dtype='i8'))
```

**Comment by sklam** [comment]
@stuartarchibald, I believe this is an issue that can be fixed if `DeadBranchPrune` is working on SSA IR.

**Comment by stuartarchibald** [comment]
@sklam agree, I've noticed a few things of late the pruner used to spot which it now can't. I've a WIP patch against my local tree which actually moves the SSA build to just after the initial interpreting of the bytecode to IR and then fixes up the down stream passes. It's mostly working but there's still a few issues.

**Comment by njriasan** [comment]
@stuartarchibald Is this still an open issue?

**Comment by stuartarchibald** [comment]
> @stuartarchibald Is this still an open issue?

@njriasan I think so as it still reproduces. The branch pruner now handles SSA form correctly (Numba 0.55) but the IR is not in SSA form at the point in the default pipeline when it is called, as not all the subsequent passes can handle SSA.
