### ISSUE TITLE
np.linalg.eigval wrong results when using np.float32

### ISSUE THREAD

**Issue by alanhdu** [numba/numba#6546]
I am implementing a simple matrix logarithm specialized for positive-definite matrices, but am getting very strange results when running against `np.float32`. If you run the following code:

```python
import numpy as np
import numba as nb
@nb.njit
def psd_logm(X):
    eigvals, eigvecs = np.linalg.eigh(X)
    mask = eigvals > 0

    eigvals = eigvals[mask]
    eigvecs = eigvecs[:, mask]

    return eigvecs @ np.diag(np.log(eigvals)) @ eigvecs.T

X = np.arange(16).reshape(4, 4)
X = X @ X.T

print("Float32")
print(psd_logm.py_func(X.astype(np.float32)))
print(psd_logm(X.astype(np.float32)))
print()
print("Float64")
print(psd_logm.py_func(X.astype(np.float64)))
print(psd_logm(X.astype(np.float64)))
```

You will see that the f32 py_func, the f64 py_func, and the jitted f64 versions all return basically the same matrix, but the jitted f32 version gives a very different result:
```
Float32
[[ -7.680479   13.077436    2.5546834  -5.439105 ]
 [ 13.077437  -15.880291   -1.6454424   9.097394 ]
 [  2.5546834  -1.6454422   1.61128     4.2651343]
 [ -5.439105    9.097394    4.2651343   0.9987916]]
[[ 0.9514792   0.47183022  1.8699914  -0.78077316]
 [ 0.47183022  0.56112206  3.2884974   0.3276325 ]
 [ 1.8699914   3.2884974  -6.202431    7.829625  ]
 [-0.78077316  0.32763228  7.8296247   1.5457208 ]]

Float64
[[ -7.68047763  13.07743694   2.55468349  -5.43910502]
 [ 13.07743694 -15.88029172  -1.64544232   9.09739357]
 [  2.55468349  -1.64544232   1.61127982   4.26513417]
 [ -5.43910502   9.09739357   4.26513417   0.99879114]]
[[ -7.68047763  13.07743694   2.55468349  -5.43910502]
 [ 13.07743694 -15.88029172  -1.64544232   9.09739357]
 [  2.55468349  -1.64544232   1.61127982   4.26513417]
 [ -5.43910502   9.09739357   4.26513417   0.99879114]]
```

**Comment by alanhdu** [comment]
On further investigation, this might just be because the `np.linalg.eigh` gives slightly different results based for `np.float32` for jitted vs non-jitted code:

```python
import numpy as np
import numba as nb
@nb.njit
def eigvalh(X):
    eigvals, eigvecs = np.linalg.eigh(X)
    return eigvals
X = np.arange(16).reshape(4, 4)
X = X @ X.T

print("Float32")
print(eigvalh.py_func(X.astype(np.float32)))
print(eigvalh(X.astype(np.float32)))
print()
print("Float64")
print(eigvalh.py_func(X.astype(np.float64)))
print(eigvalh(X.astype(np.float64)))
```

gives

```
Float32
[-1.5157233e-14  1.2446503e-13  5.1829538e+00  1.2348170e+03]
[-4.5826033e-05  6.7352867e-06  5.1829019e+00  1.2348173e+03]

Float64
[-1.51572333e-14  1.24465023e-13  5.18295404e+00  1.23481705e+03]
[-1.51572333e-14  1.24465023e-13  5.18295404e+00  1.23481705e+03]
```

I'm a bit of numerical linear algebra novice, so I'm not sure whether a `5e-5` magnitude difference is considered reasonable or not.

**Comment by sklam** [comment]
@stuartarchibald, needs your expertise here

**Comment by stuartarchibald** [comment]
Think this is just down to NumPy using 64bit floating point and Numba just using the 32bit floating point routines. Considering:
```python
import numpy as np
import numba as nb
@nb.njit
def psd_logm(X):
    eigvals, _ = np.linalg.eigh(X)
    return eigvals

X = np.arange(16).reshape(4, 4)
X = X @ X.T

print("Float32")
print("numpy", psd_logm.py_func(X.astype(np.float32)))
print("numba", psd_logm(X.astype(np.float32)))
print()
print("Float64")
print("numpy", psd_logm.py_func(X.astype(np.float64)))
print("numba", psd_logm(X.astype(np.float64)))
```
as noted gives:
```
$ python issue6546.py 
Float32
numpy [-1.4498175e-13 -4.5088424e-14  5.1829538e+00  1.2348170e+03]
numba [-4.4798289e-05  2.8365971e-06  5.1828971e+00  1.2348173e+03]

Float64
numpy [-1.44981757e-13 -4.50884250e-14  5.18295404e+00  1.23481705e+03]
numba [-1.44981757e-13 -4.50884250e-14  5.18295404e+00  1.23481705e+03]
```
NumPy always gives the 64 bit result, whereas Numba gives a result related to the input precision. NumPy triggers this behaviour here by specifying the `gufunc` signature:
https://github.com/numpy/numpy/blob/maintenance/1.20.x/numpy/linalg/linalg.py#L1469

> I'm a bit of numerical linear algebra novice, so I'm not sure whether a 5e-5 magnitude difference is considered reasonable or not.

The maximum amount of precision a IEEE754 float can give is based on its [storage representation](https://en.wikipedia.org/wiki/Single-precision_floating-point_format#IEEE_754_single-precision_binary_floating-point_format:_binary32). In the case of a `float32` this is 23 bits in the fraction, which gives `log10(2**(23+1)) ~= 7` digits (the +1 is implied in the format). Hope this helps?

**Comment by alanhdu** [comment]
> NumPy always gives the 64 bit result, whereas Numba gives a result related to the input precision

Interesting... thanks for the info! I think this has the information I need for our use-case. I'm happy to close the issue if you don't need to elave it open for tracking something.

**Comment by stuartarchibald** [comment]
Great, thanks for confirming.
