### ISSUE TITLE
PR 6343 issues

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#6553]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This is related to #6343 and using numba version 0.52.0+0.g18825058a.dirty

The error is the following:

Also, is it possible to use guvectorize instead of cuda.jit?

```
  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Documents/Cristi/Tools/Python/GitHub/numba/6343.py", line 13, in <module>
    f[1, 1](r, x)

  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\numba\cuda\compiler.py", line 773, in __call__
    self.stream, self.sharedmem)

  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\numba\cuda\compiler.py", line 879, in call
    kernel.launch(args, griddim, blockdim, stream, sharedmem)

  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\numba\cuda\compiler.py", line 645, in launch
    self._prepare_args(t, v, stream, retr, kernelargs)

  File "D:\Kit\PortableApps\Miniconda3\lib\site-packages\numba\cuda\compiler.py", line 760, in _prepare_args
    raise NotImplementedError(ty, val)

NotImplementedError: (Tuple(array(int64, 1d, C), int64, UniTuple(int64 x 2)), (array([1], dtype=int64), 10, (4, 3)))
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you explain precisely what it is you are reporting and include a reproducer for it `i.e. it's possible to run as 'python bug.py'.`? You've ticked both boxes above, is perhaps something not rendering or something is missing? Thanks for your help.

**Comment by cristipurdel** [comment]
What I ran was the code from
https://github.com/numba/numba/pull/6343#pullrequestreview-513573411

**Comment by stuartarchibald** [comment]
Numba has a long release cycle to try and reduce bugs in the final release, features are essentially  frozen when the first release candidate is produced, then multiple release candidates are made fixing bugs/regressions as they are found by the Numba community. Once the release seems stable a final version is tagged and released.

The release tags and corresponding dates can be seen here: https://github.com/numba/numba/releases. #6343 will not be in 0.52 as it is a new feature produced after the first 0.52 release candidate was tagged. In future there's a few places to you can look to work out when features might appear in a release:
* You can also check the "Milestone" on the PR, it's 0.53 (https://github.com/numba/numba/milestone/44) in this case.
* Another good place to look for what changes are in a release is the [CHANGE_LOG](https://github.com/numba/numba/blob/master/CHANGE_LOG), it's also rendered into the [documentation](https://numba.readthedocs.io/en/stable/release-notes.html).
* You can just use git, checkout a release branch and see if the PR you want is merged into that.


If you would like to try out the latest development releases of Numba they are available via:
```bash
conda install -c numba/label/dev numba
```
(usual caveats about development versions apply!).

**Comment by cristipurdel** [comment]
Thank you for the lengthy explanation.
I totally forgot to read the ... release notes
If you want, you can close the issue. However, I might reopen it if I do not manage to use `guvectorize` instead of `cuda.jit`

**Comment by stuartarchibald** [comment]
Thanks for confirming. The [issue reporting page](https://github.com/numba/numba/issues/new/choose) provides guidance over where to file new bugs/feature requests/questions, am going to close this issue as the reported item is resolved. Thanks again!
