### ISSUE TITLE
NotImplementedError: bounds checking is not supported for CUDA

### ISSUE THREAD

**Issue by MikhailMashukov** [numba/numba#6554]
I am trying to run code on GPU without writing explicit cuda.threadIdx and so on. Worked nice before, but no luck now. For example, when I add target='cuda' or 'gpu' to be sure it is not run on CPU, I am getting

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-1-313d2388f40f> in <module>()
      3 import numpy as np
      4 
----> 5 @numba.jit(void(int32[:, :]), target='cuda')
      6 # @numba.jit(void(int32[:, :]), target='gpu', device=True)
      7 def fill(a):

2 frames
/usr/local/lib/python3.6/dist-packages/numba/decorators.py in wrapper(func)
    198             with typeinfer.register_dispatcher(disp):
    199                 for sig in sigs:
--> 200                     disp.compile(sig)
    201                 disp.disable_compile()
    202         return disp

/usr/local/lib/python3.6/dist-packages/numba/cuda/dispatcher.py in compile(self, sig, locals, **targetoptions)
     28         options = self.targetoptions.copy()
     29         options.update(targetoptions)
---> 30         kernel = jit(sig, **options)(self.py_func)
     31         self._compiled = kernel
     32         if hasattr(kernel, "_npm_context_"):

/usr/local/lib/python3.6/dist-packages/numba/cuda/decorators.py in jit(func_or_sig, argtypes, device, inline, bind, link, debug, **kws)
     55     print(kws)
     56     if 'boundscheck' in kws:
---> 57         raise NotImplementedError("bounds checking is not supported for CUDA")
     58 
     59     fastmath = kws.get('fastmath', False)

NotImplementedError: bounds checking is not supported for CUDA
```

Code: 

```
import numba
from numba import cuda, void, int32, int64, float32, float64
import numpy as np

@numba.jit(void(int32[:, :]), target='cuda')
def fill(a):
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            a[i, j] = 5
            
hostB = np.full((100, 10), 1, dtype=np.int32)
b = cuda.to_device(hostB)
fill(b)
```

Run in Google Colab (Tesla T4), so numba==0.48.0.

Btw, in decorators.py we can see 

```
if 'boundscheck' in kws:
        raise NotImplementedError("bounds checking is not supported for CUDA")
```
Maybe it should be
```
if 'boundscheck' in kws and kws['boundscheck']:
        raise NotImplementedError("bounds checking is not supported for CUDA")
```
?

Without target='cuda' it doesn't accept
b = cuda.device_array((100, 10), dtype=np.int32):

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-41e3b09d2e9c> in <module>()
---> 18 fill(b)

TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type
```

**Comment by MikhailMashukov** [comment]
After updating with pip install -U numba to numba==0.52.0 - the same without target:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-08d9ad5b2ab5> in <module>()
     15 b = cuda.device_array((100, 10), dtype=np.int32)
---> 16 fill(b)
     17 # fill[16, 16](b)
     18 cuda.synchronize()

/usr/local/lib/python3.6/dist-packages/numba/core/dispatcher.py in _explain_matching_error(self, *args, **kws)
    644         msg = ("No matching definition for argument type(s) %s"
    645                % ', '.join(map(str, args)))
--> 646         raise TypeError(msg)
    647 
    648     def _search_new_conversions(self, *args, **kws):

TypeError: No matching definition for argument type(s) array(int32, 2d, C)
```

Btw, re-running of the same cell produces

`TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type`

with target='cuda' - 

```
/usr/local/lib/python3.6/dist-packages/numba/core/decorators.py:153: NumbaDeprecationWarning: The 'target' keyword argument is deprecated.
  warnings.warn("The 'target' keyword argument is deprecated.", NumbaDeprecationWarning)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0103826377cb> in <module>()
      3 import numpy as np
      4 
----> 5 @numba.jit(void(int32[:, :]), target='cuda')
      6 def fill(a):
      7     m, n = a.shape

/usr/local/lib/python3.6/dist-packages/numba/core/decorators.py in wrapper(func)
    210         disp = dispatcher(py_func=func, locals=locals,
    211                           targetoptions=targetoptions,
--> 212                           **dispatcher_args)
    213         if cache:
    214             disp.enable_caching()

TypeError: __init__() got an unexpected keyword argument 'py_func'
```

**Comment by stuartarchibald** [comment]
Thanks for the report.

RE: `boundscheck`, think this fixed it in Numba 0.49 https://github.com/numba/numba/pull/5257

RE The `target` keyword. It has been deprecated since 0.51 and will be removed in 0.53, IIRC it wasn't really used and the code path it triggered was not maintained so has bugs https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-the-target-kwarg

Perhaps post a question about what you want to do to the [Numba discourse group](https://numba.discourse.group/c/numba/how-do-i-do/9) ?

**Comment by MikhailMashukov** [comment]
Ok, thanks... So in new versions there is no way to automatically compile higher-level code without cuda.threadIdx and so on to GPU? Or if we use @jit, we have a hope it will be run on GPU?

I suppose, StackOverflow is more suitable for questions, all technologies and people in one place...

**Comment by stuartarchibald** [comment]
> Ok, thanks... So in new versions there is no way to automatically compile higher-level code without cuda.threadIdx and so on to GPU? Or if we use @jit, we have a hope it will be run on GPU?

Can you perhaps just swap the decorator if you really want to do this? i.e. use `numba.njit` for CPU, `numba.cuda.jit` for CUDA GPU. Or write your own decorator that defers to one of these targets based on some specification you choose? It should be noted that better performance is often achieved on the CUDA target if the CUDA programming model is acknowledged and used.

> I suppose, StackOverflow is more suitable for questions, all technologies and people in one place...

In response to community feedback, Numba has a specific place for asking questions about Numba, which is supported by the Numba developers and community members, it's here: [Numba discourse group](https://numba.discourse.group/c/numba/how-do-i-do/9).

**Comment by MikhailMashukov** [comment]
>Can you perhaps just swap the decorator if you really want to do this? i.e. use numba.njit for CPU, numba.cuda.jit for CUDA GPU

No, the miracle didn't happen

```
import numba
from numba import cuda, void, int32, int64, float32, float64
import numpy as np

@cuda.jit
def fill2(a):
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            v = 1 + i * 0.01 + j * 0.0001    
            for k in range(100):
                v *= v      # For v += j results are not so understandable, maybe compiler optimized it out
            a[i, j] = v

b = np.full((1000, 1000), 1, dtype=np.float64)
%timeit fill2(b)
```

Numba 0.48: numba.jit - 18 ms, cuda.jit - 300 ms.
Numba 0.52: numba.jit - 70 ms, cuda.jit - "Kernel launch configuration was not specified",
   fill2[(16, ), (16, )](b) - 3 s (each GPU thread processes entire image).

**Comment by gmarkall** [comment]
Perhaps the `@vectorize` or `@guvectorize` decorator could help you write the functions in the style you want without explicitly assigning threads to work items? https://numba.readthedocs.io/en/stable/user/vectorize.html - it does support the `target='cuda'` kwarg.

**Comment by MikhailMashukov** [comment]
`@(gu)vectorize` - sort of, with a note that they are designed for transforming arrays basically 1 to 1, so look as dialects, not normal programming language. In principle many tasks are so, and several current tasks of mine too, but I haven't understood how to write what I need https://stackoverflow.com/questions/65180802/numba-vectorize-with-participation-of-a-constant

Also I've got strangely slow performance of the mentioned replace function, 90 ms on Tesla T4 for 500 MB array. So no luck yet...

**Comment by stuartarchibald** [comment]
> > Can you perhaps just swap the decorator if you really want to do this? i.e. use numba.njit for CPU, numba.cuda.jit for CUDA GPU
> 
> No, the miracle didn't happen
> 
> ```
> import numba
> from numba import cuda, void, int32, int64, float32, float64
> import numpy as np
> 
> @cuda.jit
> def fill2(a):
>     m, n = a.shape
>     for i in range(m):
>         for j in range(n):
>             v = 1 + i * 0.01 + j * 0.0001    
>             for k in range(100):
>                 v *= v      # For v += j results are not so understandable, maybe compiler optimized it out
>             a[i, j] = v
> 
> b = np.full((1000, 1000), 1, dtype=np.float64)
> %timeit fill2(b)
> ```
> 
> Numba 0.48: numba.jit - 18 ms, cuda.jit - 300 ms.
> Numba 0.52: numba.jit - 70 ms, cuda.jit - "Kernel launch configuration was not specified",
> `fill2[(16, ), (16, )](b)` - 3 s (each GPU thread processes entire image).

This is because CUDA kernels need a [launch configuration](https://numba.readthedocs.io/en/stable/cuda/kernels.html#kernel-invocation) specifying, you could always wrap this if you wanted to. I'm going to close this ticket as resolved as it is largely discussion and suggest that further questions are asked on the [Numba discourse group](https://numba.discourse.group/c/numba/how-do-i-do/9) which is much better suited for Q&A. Thanks for your help!
