### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [numba/numba#6558]
**Summary**
Installing numba on aarch64 via pip using command "pip3 install numba" tries to build wheel from source code

**Problem description**
numba doesn't have wheel for aarch64 on PyPI repository. So, while installing numba via pip on aarch64, pip builds wheel for same resulting in it takes more time to install numba. Making wheel available for aarch64 will benefit aarch64 users by minimizing numba installation time.

**Expected Output**
Pip should be able to download numba wheel from PyPI repository rather than building it from source code.

@numba-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make numba wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by esc** [comment]
@odidev thank you for submitting this feature request. Building wheels for Numba for `aarch64` requires building the wheels for dependency `llvmlite`. Once that is completed we will be able to ship corresponding wheels for Numba too. See also: https://github.com/numba/llvmlite/issues/665

**Comment by Aposhian** [comment]
Looks like the lvmlite aarch64 wheels are now available. https://github.com/numba/llvmlite/issues/665#issuecomment-902894212

**Comment by esc** [comment]
> Looks like the lvmlite aarch64 wheels are now available. [numba/llvmlite#665 (comment)](https://github.com/numba/llvmlite/issues/665#issuecomment-902894212)

Correct, both Numba and llvmlite wheels are now available via PyPi and support this architecture.
