### ISSUE TITLE
Does Numba have Cooperative Groups?

### ISSUE THREAD

**Issue by zuzhaoye** [numba/numba#6566]
---

## Feature request

I read from a resource [1] that Numba currently doesn't support cuda Cooperative Groups [2], i.e. synchronization between thread blocks. I just want to double-check here if you have any plan to incorporate this feature. Much appreciated.

[1] https://stackoverflow.com/questions/54595609/numba-support-for-cuda-cooperative-block-synchronization-python-numba-cuda-gri
[2] https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#grid-synchronization-cg

**Comment by seibert** [comment]
Some work has already been done by @gmarkall here: https://github.com/numba/numba/pull/6245

I think there are more aspects of cooperative groups yet to be implemented, so if you have specific things you want to see first, let us know.

**Comment by zuzhaoye** [comment]
Thx a lot. I do not have specific things requested other than sync btw blocks. I just want to stop by and say Hi, then check how far I can go with Numba in case one day I don't like C cuda. 

Since it is a very new feature on Numba, I don't expect you have documentation on it (as I don't find it on Numba homepage), but in case you do have one, please let me know and try.

**Comment by zuzhaoye** [comment]
> 
> 
> Some work has already been done by @gmarkall here: #6245
> 
> I think there are more aspects of cooperative groups yet to be implemented, so if you have specific things you want to see first, let us know.

Thx a lot. I do not have specific things requested other than sync btw blocks. I just want to stop by and say Hi, then check how far I can go with Numba in case one day I don't like C cuda.

Since it is a very new feature on Numba, I don't expect you have documentation on it (as I don't find it on Numba homepage), but in case you do have one, please let me know and try.

**Comment by stuartarchibald** [comment]
@zuzhaoye perhaps try: https://numba.readthedocs.io/en/latest/cuda/cooperative_groups.html the "latest" docs are building from mainline opposed to a tagged release.

**Comment by zuzhaoye** [comment]
> 
> 
> @zuzhaoye perhaps try: https://numba.readthedocs.io/en/latest/cuda/cooperative_groups.html the "latest" docs are building from mainline opposed to a tagged release.

This looks excellent. I like how you design the invoke of a cooperative group using the same syntax. Good luck with your follow-on development.
