### ISSUE TITLE
Add Zenodo badge

### ISSUE THREAD

**Issue by HDembinski** [numba/numba#6572]
https://zenodo.org is a service funded by CERN and the EU to make software and specific software versions easily citeable in scientific documents. It is easy to set up and generates a DOI for each released version, so that scientific documents can cite specific versions of numba.

All you need to do to make numba citeable is an account on zenodo.org and and follow the GitHub integration steps

https://guides.github.com/activities/citable-code/

After setting it up once, it works automatically in the background.

Disclaimer: I am not affiliated with Zenodo in any way. I am just a scientist who wants to cite Numba. Zenodo works great, I have made my own project [iminuit](https://github.com/scikit-hep/iminuit) citeable.

**Comment by esc** [comment]
@HDembinski thank you for suggesting this!. I have labelled it as a feature request and w will discuss this during the next core developer meeting.

**Comment by seibert** [comment]
The DOI is live now although the badge isn't yet in the readme: https://zenodo.org/record/4343231

**Comment by HDembinski** [comment]
Excellent, thanks!
