### ISSUE TITLE
Unexpected "divide by zero" warning with numba.vectorize and np.log

### ISSUE THREAD

**Issue by szsdk** [numba/numba#6576]
The behavior of `np.log` function under `numba.vectorize` is strange to me. It throws unexpected warning but gives the correct result.
Here is the testing code.

```python
import numpy as np
import numba

def slog(a):
    if a > 0:
        return np.log(a)
    return 0

print(np.__version__)
print(numba.__version__)
assert numba.vectorize(slog)(0) == 0
with np.errstate(divide="raise"):
    slog(0)
    numba.jit(slog)(0)
    numba.vectorize(slog)(0)
```

The output is
```
numpy version 1.19.4
numba version 0.52.0
h.py:11: RuntimeWarning: divide by zero encountered in slog
  assert numba.vectorize(slog)(0) == 0
Traceback (most recent call last):
  File "h.py", line 15, in <module>
    numba.vectorize(slog)(0)
FloatingPointError: divide by zero encountered in slog
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think that this is the same as this: https://github.com/numba/numba/issues/4793#issuecomment-622323686

Looking at the LLVM IR from env var `NUMBA_DEBUG=1`, it has:
```llvm
  %.94 = load i64, i64* %.93, align 8 ; Load variable 'a' into %.94
  %.13.i2 = icmp sgt i64 %.94, 0 ; signed integer "greater than" comparison, between 'a' and 0, store result to %.13.i2
  %.51.i4 = sitofp i64 %.94 to double ; cast 'a' to a 'double' type and store in %.51.i4
  %.52.i5 = tail call double @llvm.log.f64(double %.51.i4) #2 ; Call `log` on variable %.51.i4 and store into %.52.i5
  %34 = bitcast double %.52.i5 to i64 ; Cast the result of the log to an int64 and store in %34.
  %35 = select i1 %.13.i2, i64 %34, i64 0 ; If %.13.i2 is true store the result of the log call, if false store 0.
```
which is doing the same as in #4793 (I've added descriptions after the `;` on each line). Basically, LLVM elects to call the `log` function speculatively.

**Comment by szsdk** [comment]
Yes, you are right. So is there any way to close this warning? I know I could use numpy.seterr, but am not sure it would give the best performance.

**Comment by esc** [comment]
@szsdk I believe the workaround from https://github.com/numba/numba/issues/4793#issuecomment-623296850 is the only currently known one. If you are concerened about performance I would suggest benchmarking it to determine the impact this has.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
