### ISSUE TITLE
from numba import * fails due to jitclass still being in __all__

### ISSUE THREAD

**Issue by lschr** [numba/numba#6583]
5f7ecf3bbfdf25b55f663f5278e4e31ad6fdde4c removes `jitclass` from the `numba` namespace, but `__init__.py`'s `__all__` still contains `jitclass`, causing `from numba import *` to fail.

**Comment by stuartarchibald** [comment]
Thanks for the report. Fixed in https://github.com/numba/numba/pull/6584.
