### ISSUE TITLE
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)

### ISSUE THREAD

**Issue by yylhero** [numba/numba#6594]

**Comment by stuartarchibald** [comment]
Thanks for the report. There's no contents present in this report, was this issue opened by accident at the same time as https://github.com/numba/numba/issues/6595 ?

**Comment by yylhero** [comment]
yes


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "numba/numba"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 晚上9:23
收件人:&nbsp;"numba/numba"<numba@noreply.github.com&gt;;
抄送:&nbsp;"李阳阳"<626439197@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [numba/numba] LoweringError: Failed in nopython mode pipeline (step: nopython mode backend) (#6594)





 
Thanks for the report. There's no contents present in this report, was this issue opened by accident at the same time as #6595 ?

**Comment by stuartarchibald** [comment]
ok, thanks for confirming, I'll close this.
