### ISSUE TITLE
Parallel loop unexpected overhead

### ISSUE THREAD

**Issue by stavoltafunzia** [numba/numba#6603]
Hi, I recently migrated to a more recent numba version and found out that some code started running much slower. An example is given by the code below;

```
import numba
import numpy as np
import math
import timeit
            
#%%

def bar(a, out):    
    N = a.shape[0]
    for i in range(out.shape[0]):
        for j in range(N):
            if (j >=15):
                out[i, j] = 0
                out[i, j, j] = 1
            else:
                b = 0
                for k in range(N):
                    x = math.exp(a[j, k] * j) * math.cos(i % 5 + j * k - i)
                    x *= math.tan(x/(j+1))
                    out[i, j, k] = x
                    b += x
                for k in range(N):
                    out[i, j, k] /= b


bar = numba.njit(bar)
       
            
def foo():
    N = 50
    M = 46
    L = 2
    a = np.ones((N, N))
    out = np.empty((M, L, N, N), dtype=np.float64)    
    for j in numba.prange(M):
        for i in range(100):
            bar(a, out[j])


foo = numba.njit(foo, parallel=True)

print("Compile")    
foo()
start = timeit.time.process_time() 
print("Start")
%timeit -n 50 -r 7 foo()
end = timeit.time.process_time() 
print("Elapsed cpu time {:.0f}".format(end-start))

```

Up to numba 0.50, the performance I have is something like:
```
20 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 50 loops each)
Elapsed cpu time 183
```
From numba 0.51 (including 052) however I get:
```
47.9 ms ± 21.8 ms per loop (mean ± std. dev. of 7 runs, 50 loops each)
Elapsed cpu time 737
```

In particular I noticed that not only the function runs slower, but it's also much more inefficient (see cpu time). I'm running this example on a 46 core machine (Python 3.7, icc and tbb installed), and indeed the fast version uses only 60% of the CPU, the slow version uses 100% of it.
Unfortunately the overhead of the parallel accelerator with numba 0.51+ is such that the original code (not the example) runs almost at the same speed with the parallel=True and False, yet parallel=True uses 100% of the cpu, parallel=False uses only 2-3%.

**Comment by sklam** [comment]
Numba 0.52.0 has a lot of performance improvements. Please consider upgrading to the latest version to see if the issues are still present.

**Comment by stavoltafunzia** [comment]
Hi, yes it happens from 0.51, in 0.52 it has the same behavior. Tomorrow will do some further checks to see if llvmlite versions can have an impact too.

**Comment by sklam** [comment]
Notes from out-of-band discussion:

- 0.51:
     - changed llvm
     - avoided unnecessary literals (this have an effect on `range(100)`)
- 0.52 changed llvm passes

**Comment by stuartarchibald** [comment]
I can't seem to reproduce this locally. Am using:
```python
import numba
import numpy as np
import math
import timeit

#%%

def bar(a, out):    
    N = a.shape[0]
    for i in range(out.shape[0]):
        for j in range(N):
            if (j >=15):
                out[i, j] = 0
                out[i, j, j] = 1
            else:
                b = 0
                for k in range(N):
                    x = math.exp(a[j, k] * j) * math.cos(i % 5 + j * k - i)
                    x *= math.tan(x/(j+1))
                    out[i, j, k] = x
                    b += x
                for k in range(N):
                    out[i, j, k] /= b


bar = numba.njit(bar)

def foo():
    N = 50
    M = 46
    L = 2
    a = np.ones((N, N))
    out = np.empty((M, L, N, N), dtype=np.float64)    
    for j in numba.prange(M):
        for i in range(100):
            bar(a, out[j])


foo = numba.njit(foo, parallel=True)

print(f"Version: {numba.__version__}")
print("Compile")
foo()
start = timeit.time.process_time() 
print("Start")
%timeit -n 10 -r 2 foo()
end = timeit.time.process_time() 
print("Elapsed cpu time {:.0f}".format(end-start))
print(f"Threading layer: {numba.threading_layer()}")
```
on a 4 core machine and get:
```
Version: 0.50.0
Compile
Start
432 ms ± 5.3 ms per loop (mean ± std. dev. of 2 runs, 50 loops each)
Elapsed cpu time 151                                                                                                            
Threading layer: tbb   
```
and
```
Version: 0.53.0dev0
Compile
Start
427 ms ± 21.9 ms per loop (mean ± std. dev. of 2 runs, 50 loops each)
Elapsed cpu time 152
Threading layer: tbb
```

@stavoltafunzia do you see the same behaviour if you use the OpenMP threading layer ([docs on how to change it](https://numba.readthedocs.io/en/stable/user/threading-layer.html#setting-the-threading-layer))?

**Comment by stavoltafunzia** [comment]
Indeed the threading layer seems the cause. In Numba 0.50 the default threading layer in my machine is workqueue, in 0.51 and 0.52 omp is used instead, and this is where the performance decreases. Manually setting the threading layer to workqueue I get the same performance (fast) in Numba 0.50, 0.51 and 0.52. 

Couldn't try tbb yet since an error occurs when importing it (disabled due to unknown import error).

**Comment by stuartarchibald** [comment]
@stavoltafunzia thanks for checking. Multiple threading layers are provided as they all have different characteristics and different things they are relatively good/bad at doing. I'd probably set up some speed tests and switch through the backends, find the best one for the application being tested, use that, and then put the tests in as regression tests to rerun periodically to make sure that the selected threading layer is still the best.

I'm not sure why `tbb` wouldn't work for you, are you using conda packages or something else?

**Comment by stavoltafunzia** [comment]
I was using pip rather than conda. Tried with conda but still ```tbb``` is unavailable. Don't know why, probably due to the dummy OS I'm forced to use. In another machine with a different OS I'm able to use ```tbb```. The workqueue layer is enough for what I have to do, though. Thanks for pointing my attention to the threading layer.

**Comment by esc** [comment]
@stavoltafunzia thank you for reporting back. I will close this issue assuming it is resolved. If new information comes to light, please don't hesitate to re-open.
