### ISSUE TITLE
numba.errors.TypingError: Failed in nopython mode pipeline

### ISSUE THREAD

**Issue by Zakaria-Talhi** [numba/numba#6612]
Hi,

i wrote this code to resize images :

```python
from numba import njit,jit,prange

from os import  listdir,getcwd
from cv2 import imread,resize,imwrite,IMREAD_UNCHANGED,INTER_AREA

width =1080
height = 1080
dim = (width, height)


@njit(parallel=True)
def ress():
    FList = listdir(getcwd()+"/1020/")
    fdirl=getcwd()+"/1020/"

    Fsave = listdir(getcwd()+"/1080/")
    fdirs=getcwd()+"/1080/"

    for i in FList:
        
        img = imread(fdirl+i, IMREAD_UNCHANGED)
    
        resized = resize(img, dim, interpolation = INTER_AREA)

        imwrite(fdirs+i[0:-4]+'-1080.png',resized)

ress()`
```

i got this error 

```
Traceback (most recent call last):
  File "c:/Users/**/Desktop/img/Fast Pay/Design/Post/1Resize/Resize - Copy.py", line 32, in <module>
    ress()
  File "C:\Users\**\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\**\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\**\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'listdir': cannot determine Numba type of <class 'builtin_function_or_method'>

File "Resize - Copy.py", line 17:
def ress():
    FList = listdir(getcwd()+"/1020/")
    ^
```

please how i can fix that 
and thank you

**Comment by HPLegion** [comment]
Hi @Zakaria-Talhi 

Numba is not generally able to compile arbitrary Python code. Your function seems to call a lot of functions interacting with both the operating system and external C libraries from OpenCV. Numba does not know what to do with these.

Typically Numba is used for computationally intensive operations, which benefit most from low level implementations.

So you could, in theory, load the images into numpy arrays outside of numba. Then you call a jitted ("fast") resize function on the image return the new array and save it using normal python. This would still require you to program your own "resize" function or tell numba how to play nicely with resize from `cv2`.

This brings me to the last point:
To my knowledge OpenCV is already heavily optimised and using C libraries underneath. So you may have a hard time improving your performance over that of OpenCV.

It is hard to tell what might be bottlenecking you specifically, whenever there is a combination of File I/O with heavy processing, this may be one of the occasions where multithreading may give you a gain. This is particular true if you can release Python's GIL during the compute-intensive work.

I don't know if OpenCV offers a mechanism for releasing the GIL, but numba does. So if you manage to wrestle the `resize` function into numba there might be some gain.

**Comment by esc** [comment]
@HPLegion thank you for answering this one. @Zakaria-Talhi for reference, the list of Python constructs supported by Numba can be found here: https://numba.readthedocs.io/en/stable/reference/pysupported.html
