### ISSUE TITLE
CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by dkhokhlov** [numba/numba#6620]
---
I need a way to tell Numba to use specific target sm, to override cc received by numba from device.
I have a case when I need to downgrade target sm from 21 to 20 because of
numba.cuda.cudadrv.driver.LinkerError: [999] Call to cuLinkAddData results in CUDA_ERROR_UNKNOWN.

**Comment by esc** [comment]
@dkhokhlov thank you for raising this issue on the Numba issue tracker. The description is somewhat terse and I am not exactly sure what you are asking. Maybe you could use the following guidelines to elaborate on your needs:

* What did you do (or what did you try)?
* What did you expect to happen?
* What happened instead?

Thanks

**Comment by seibert** [comment]
To expand a bit on this: Numba needs to tell NVVM what generation of CUDA device to generate code for.  By default, it detects the compute capability (often called "cc" or "sm" for historical reasons) of the active device and uses that.  See:

https://github.com/numba/numba/blob/f82ed9ff82f31a1ab87dc1511a442cfc2d4a22fa/numba/cuda/compiler.py#L128-L135

That said, I think Numba has an environment variable `NUMBA_FORCE_CUDA_CC` to override this choice:

https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_FORCE_CUDA_CC

**Comment by seibert** [comment]
If that env variable isn't working, we can ask @gmarkall or @testhound to take a look.

**Comment by dkhokhlov** [comment]
NUMBA_FORCE_CUDA_CC worked. I see PTX is compiled with sm 20.

Unfortunately for me it did not resolve CUDA_ERROR_UNKNOWN in numba:
numba.cuda.cudadrv.driver.LinkerError: [999] Call to cuLinkAddData results in CUDA_ERROR_UNKNOWN.

But I have no errors when I build and run cudatoolkit samples with SMS=20, even though the card is 2.1.

-----------------------------------------------------------------------------------------
/usr/local/cuda-8.0/samples/1_Utilities/deviceQuery# ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 560 Ti"
  CUDA Driver Version / Runtime Version          9.1 / 8.0
  CUDA Capability Major/Minor version number:    2.1
  Total amount of global memory:                 963 MBytes (1010106368 bytes)
  ( 8) Multiprocessors, ( 48) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            1760 MHz (1.76 GHz)
  Memory Clock rate:                             2100 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.1, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GTX 560 Ti
Result = PASS

**Comment by seibert** [comment]
Oh wait, I didn't think about the SM value you were asking about.  Numba dropped support for CC < 3.5 recently, and I think CC 3.0 was the minimum requirement for some time before that.  I'm not sure when Numba last support CC 2.x devices.
