### ISSUE TITLE
Performance issue: jitclass+typedlist more than 10 x slower than Julia

### ISSUE THREAD

**Issue by paugier** [numba/numba#6625]
Hi! I was playing with jitclass and typedlist and get a bad performance result. Since the doc tells us to report performance problems with typedlist, I fill it!

Two codes doing the same thing in Julia and Numba. First the results:

- Python
```
%timeit sum_few_x(points)                                               
14 µs ± 19.3 ns per loop
```

- Julia
```
  1.022 μs (1 allocation: 16 bytes)
```

Now the codes:
- Python (Am I doing something stupid?)
```python
from numba import njit
from numba.experimental import jitclass
from numba.typed import List as TypedList

jit = njit(cache=True, fastmath=True)

@jitclass
class Point:
    x: float
    y: float
    z: float

    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

@jit
def sum_few_x(vec):
    s = 0.0
    for i in range(10, len(vec)):
        s += vec[i].x
    return s

points = TypedList()
for i in range(1000):
    points.append(Point(i, i, i))
```

- Julia

```Julia
using Printf
using BenchmarkTools

function sum_few_x(vec)
    result = 0.
    for i in 11:length(vec)
        result += vec[i].x
    end
    return result
end

struct Point
    x::Float64
    y::Float64
    z::Float64
end

zero(T::Type{Point}) = Point(0, 0, 0)

points = Vector{Point}(undef, 1000)

function init_vec(vec)
    x = 0.0
    for i in eachindex(points)
        points[i] = Point(x, 0, 0)
        x += 1.0
    end
end

init_vec(points)

@btime sum_few_x(points)
```

A related question: do you think there could be a good equivalent of `points = Vector{Point}(undef, 1000)` in Python? It would be very nice to be able to do `points = Vector[Point].empty(1000)`.

**Comment by esc** [comment]
@paugier thanks for reporting this, it will need some triage.

**Comment by esc** [comment]
@paugier without looking into the generate IR, my guess is that the for-loop is not vectorizing. Maybe you could try the following variant:

```
@jit
def sum_few_x(vec):
    s = 0.0
    for i in vec:
        s += i.x
    return s
```

It may bring you closer to the Julia example. Let us know you findings and thanks again for reporting this!

**Comment by paugier** [comment]
Yes, it's much better when one iterates on all elements!

```
In [10]: %timeit sum_all_x(points)                                              
1.87 µs ± 14 ns per loop
```

However, for the (nearly) "real life" code I'm working with (https://github.com/paugier/nbabel), it's important to be fast also when iterating on few elements:

The hottest loops look like this:

```python
def compute_accelerations(accelerations, masses, positions):
    nb_particules = len(masses)
    for i0 in range(nb_particules - 1):
        mass0 = masses[i0]
        position0 = positions[i0]
        for i1 in range(i0 + 1, nb_particules):
            mass1 = masses[i1]
            position1 = positions[i1]
            delta = position0 - position1
            distance_cube = delta.norm_cube()
            accelerations[i0] -= mass1 / distance_cube * delta
            accelerations[i1] += mass0 / distance_cube * delta
```

**Comment by esc** [comment]
@paugier perhaps it could be possible to slice the list before handing it into the jit compiled function? Also, perhaps you could use the new StructRef module:

https://numba.pydata.org/numba-doc/dev/extending/high-level.html#implementing-mutable-structures

Or maybe even a 3 x 1000 or 1000 x 3 NumPy array since you aren't attaching any functionality to the Jitclass? Maybe even try slicing the NumPy array instead of iterating with integers and then using `__getitem__`?

**Comment by paugier** [comment]
There is already a pretty good implementation using Numba and Numpy arrays in https://github.com/paugier/nbabel. Here, my goal was to see if I could rewrite a very fast Julia implementation (https://github.com/paugier/nbabel/blob/master/julia/nbabel4_serial.jl) with Numba. I need to be able to "attach" methods to the jit class.

Unfortunately, "slice the list before" is slower, see:

```
@jit
def sum_few_x_alt(vec):
    s = 0.0
    for elem in vec[10:]:
        s += elem.x
    return s

In [12]: %timeit sum_few_x_alt(points)                                          
63.6 µs ± 12.4 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [13]: %timeit sum_few_x(points)                                              
13.9 µs ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [14]: %timeit sum_all_x(points)                                              
1.81 µs ± 10.9 ns per loop
```

**Comment by stuartarchibald** [comment]
Would `namedtuple`help here?
```python
from numba import njit
from numba.experimental import jitclass
from numba.typed import List as TypedList
from collections import namedtuple
import time
jit = njit(fastmath=True)

@jitclass
class Point:
    x: float
    y: float
    z: float

    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

@jit
def buf(vec):
    s = 0.0
    z = vec[10:]
    for i in z:
        s += i.x
    return s

points = TypedList()
for i in range(1000):
    points.append(Point(i, i, i))

ts=time.time()
for x in range(10):
    buf(points)
print(time.time()- ts)

Point2 = namedtuple('Point2', 'x y z')
points2 = TypedList()
for i in range(1000):
    points2.append(Point2(i, i, i))

ts=time.time()
for x in range(10):
    buf(points)
print(time.time()- ts)
```
gives me
```
0.7356758117675781
0.0016891956329345703
```

**Comment by esc** [comment]
I think it will be best to close this issue and move the discussion to Discourse at https://numba.discourse.group/ -- the rational is that this does not track an immediate issue with Numba per-se (such as a bug or a feature request) and we would like to improve on the signal-to-noise ratio of the issue tracker. @paugier what do you think?
