### ISSUE TITLE
Numba not getting installed in Python3.8 in centos

### ISSUE THREAD

**Issue by connectsachit** [numba/numba#6630]
I am getting following while installing numba.

running build_ext
  building 'numba._dynfunc' extension
  Warning: Can't read registry to find the necessary compiler setting
  Make sure that Python modules winreg, win32api or win32con are installed.
  C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC

  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/numba
  compile options: '-I/usr/local/include/python3.8 -c'
  gcc: numba/_dynfuncmod.c
  gcc -pthread -shared build/temp.linux-x86_64-3.8/numba/_dynfuncmod.o -o build/lib.linux-x86_64-3.8/numba/_dynfunc.cpython-38-x86_64-linux-gnu.so
  building 'numba._dispatcher' extension
  C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPI

**Comment by stuartarchibald** [comment]
@connectsachit thanks for the report. Please could you paste the full error message you get?

As an aside, I can confirm Python 3.8 builds and works fine on Centos.

**Comment by connectsachit** [comment]
@stuartarchibald 
Doing yum install of gcc-c++ fixed this issue. Close this. Thanks

**Comment by stuartarchibald** [comment]
@connectsachit thanks for confirming.
