### ISSUE TITLE
MKL Oversubscription in Cython if Numba njitted function is run first

### ISSUE THREAD

**Issue by ashutoshvarma** [numba/numba#6637]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (the most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self-contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'. [(files to reproduce)](https://github.com/ashutoshvarma/numba_cython_mkl_oversubscription_bug)

When running MKL accelerated NumPy functions such as `np.dot` inside numba njitted's `prange` block it leads to oversubscription ( #2861 ).

But when using those njitted numba functions together with cython extension functions which also has MKL functions (like `np.dot`) inside their `prange` (cython) block it cause them to oversubscribe also.

Usually, by default MKL run single-threaded when running inside OpenMP parallel block (cython's prange) but loading/running numba njitted functions first seems to break that

```python
# numba_mkl.py
@njit(parallel=True)
def numba_mkl(A, B):
    for i in prange(128):
        np.dot(A, B)
``` 

```cython
# cython_mkl.py
def cython_mkl(A, B):
    cdef Py_ssize_t i
    for i in prange(128, nogil=True):
        with gil:
            np.dot(A, B)
```

Running numba first
```python
A = np.random.random((10**3, 10**3))
B = np.random.random((10**3, 10**3))

numba_mkl(A, B)                  # ------> 32 threads
cython_mkl(A, B)                 # ------> 36 threads
```
Running cython first
```python
cython_mkl(A,B)                  # ------> 8 threads
numba_mkl(A, B)                 # ------> 32 threads
```

Happens in both `workqueue` and `tbb` except `omp`  threading layer.

**Comment by stuartarchibald** [comment]
Thanks for the report. How many cores does your machine have? 8?

**Comment by ashutoshvarma** [comment]
I am using my laptop with Intel i5-9300H, 4 cores ( 8 with hyper threading )

**Comment by stuartarchibald** [comment]
> I am using my laptop with Intel i5-9300H, 4 cores ( 8 with hyper threading )

Thanks! Helps to make sense of the above.

I can replicate the over-subscription situation in the Numba code, I suspect the threadpools simply carry over into the cython call.

Solely for the Numba issue... I note that setting the environment variable `MKL_NUM_THREADS=1` seems to have the desired effect of keeping the thread count to what might be expected. It's also possible to get MKL to cooperate with Numba's `tbb` backend by setting ` MKL_THREADING_LAYER=tbb` to achieve a reasonable subscription [docs on all this](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-linux-developer-guide/top/managing-performance-and-memory/improving-performance-with-threading/calling-onemkl-functions-from-multi-threaded-applications.html). I think those two environment variables should be sufficient as workarounds for the problems arising in the `workqueue` and `tbb` cases.

Hope this helps?

**Comment by ashutoshvarma** [comment]
You are right threadpools are indeed carrying over into cython call.
I remember trying both `MKL_NUM_THREADS=1`  and `MKL_THREADING_LAYER=tbb` before also, but they were only able to prevent oversubscription in the first function call only.

<table>
  <tr>
    <th colspan="2"><code>MKL_NUM_THREADS=1</code></th>
  </tr>
  <tr>
    <td colspan="1">
      <pre lang="python">
numba_mkl(A, B)                  # ------> 8 threads
cython_mkl(A, B)                 # ------> 16 threads</pre>
     </td>
<td colspan="1">
      <pre lang="python">
cython_mkl(A, B)                 # ------> 8 threads
numba_mkl(A, B)                  # ------> 16 threads</pre>
     </td>
  </tr>
</table>

Same results with `MKL_THREADING_LAYER=tbb`, this reaffirms that threadpool is carrying over.

I will be sticking with `omp` threading layer, having common threading runtime between cython and numba seems to fix this.

Thnaks for you help!

**Comment by stuartarchibald** [comment]
No problem. Are the threads actually doing work or are they just in existence? I wonder if it's a situation where threads from the user defined code are just delegating to a new thread in MKL, in which case, there's a bit of effort for threads handing off work and waiting but no over-subscription of cores.

**Comment by ashutoshvarma** [comment]
After checking again using htop and restricting the numba and cython threads to 2, it's clear that threads are only in existence and not doing any work. 

```console
OMP_NUM_THREADS=2 NUMBA_NUM_THREADS=2 MKL_NUM_THREADS=1 ./check_thread.sh ipython test.py
```

![image](https://user-images.githubusercontent.com/17181457/104811637-edff5c80-5822-11eb-840b-de7a585134fa.png)
(Thread count in the photo is actually 4, the extra one is spawned by ipython for saving command history)

There is no substantial regression in performance also.
```console
❯ ipython test.py cython
only cython_mkl
cython : 2.3212240000025486

❯ ipython test.py cython-first
cython then numba
cython : 2.3246966999940923
numba : 2.7127484000011464

❯ ipython test.py
numba then cython
numba : 2.7117838000049233
cython : 2.4403693000000203
```

Looks like I was unnecessarily worrying over thread count  :relieved:

**Comment by stuartarchibald** [comment]
@ashutoshvarma thanks for checking and reporting back. I think that it is not uncommon for thread pools to keep threads alive but give them no work as there's no benefit at a particular time/it's not the requested threading behaviour so they do nothing (particularly TBB). Looks like this is resolved so am going to close this ticket. Please do reopen if there are any further issues, or feel free to open another ticket if a different problem is observed. Thanks again!

**Comment by ashutoshvarma** [comment]
No problem !
Thanks for your help
