### ISSUE TITLE
Error Using Typed List in Function Signatures 

### ISSUE THREAD

**Issue by leora-dot** [numba/numba#6641]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I'm trying to write a function which will take a typed list as input and return a typed list as output. However, the code below produces the following error:

```
import numba

@numba.jit(numba.typed.List(numba.typed.List))
def test_function(input_list):
    return input_list

```
Error: 
```

Traceback (most recent call last):
  File "C:\Users\my_name\miniconda3\lib\site-packages\numba\typed\typedlist.py", line 243, in __init__
    iter(iterable)
TypeError: 'ABCMeta' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_script.py", line 14, in <module>
    @numba.jit(numba.typed.List(numba.typed.List))
  File "C:\Users\my_name\miniconda3\lib\site-packages\numba\typed\typedlist.py", line 245, in __init__
    raise TypeError("List() argument must be iterable")
TypeError: List() argument must be iterable
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue you are seeing is from using `typed.List` instances in a place (signature) where Numba expects Numba types (they are in `numba.types`). Here's an example that will hopefully clear things up:
```python
import numba
import numpy as np

# can use `numba.typeof` to find the Numba type-system type of something
print(numba.typeof(1.234)) # what type Numba thinks a float is
print(numba.typeof('aaa')) # what type Numba thinks a string is
print(numba.typeof(np.zeros((3,)))) # what type Numba thinks this NumPy array is

# instance of a typed list
tl = numba.typed.List()
print(tl)

# append a float64, it's now refined to a typed list of type float64
tl.append(1.234)
print(tl)
print(numba.typeof(tl)) # what Numba type is it?

# To construct a function signature that e.g. takes a typed.List of float64
# values, one needs to do:
list_type = numba.types.ListType(numba.types.float64) # this is the type for "typed list of float64s"

@numba.jit([list_type(list_type),], nopython=True) # use it!
def test_function(input_list):
    return input_list

print(test_function.signatures)

# However, Numba can just figure the types of things out on the fly, so you 
# don't really need to provide signatures unless you want to prevent further
# compilation or force compilation to happen at a certain time. e.g.

@numba.jit(nopython=True)
def test_function_no_signature(input_list):
    return input_list

test_function_no_signature(tl)
print(test_function_no_signature.signatures) # Numba worked it out
```
If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

Hope this helps.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
