### ISSUE TITLE
np.cross gives error

### ISSUE THREAD

**Issue by smiet** [numba/numba#6646]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The numba implementation of `numpy.cross()` fails on the dimension check of the input arguments

```python
from numba import njit
import numpy as np

@njit
def mycross(a,b):
  return np.cross(a,b)

a = np.random.random(3)
b = np.random.random(3)

mycross(a,b)
```

which results in the following error: 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function cross at 0x7f5eaefa0430>) found for signature:

 >>> cross(reflected list(int64)<iv=None>, reflected list(int64)<iv=None>)

There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload in function 'np_cross': File: numba/np/arraymath.py: Line 4364.
      With argument(s): '(reflected list(int64)<iv=None>, reflected list(int64)<iv=None>)':
     Rejected as the implementation raised a specific error:
       UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
     Use of unsupported opcode (CONTAINS_OP) found

     File "../../.local/lib/python3.9/site-packages/numba/np/arraymath.py", line 4372:
         def impl(a, b):
             <source elided>
             b_ = np.asarray(b)
             if a_.shape[-1] not in (2, 3) or b_.shape[-1] not in (2, 3):
             ^

  raised from /home/smiet/.local/lib/python3.9/site-packages/numba/core/byteflow.py:269

During: resolving callee type: Function(<function cross at 0x7f5eaefa0430>)
During: typing of call at <ipython-input-1-8c89f6d7a38d> (6)


File "<ipython-input-1-8c89f6d7a38d>", line 6:
def mycross(a,b):
  return np.cross(a,b)
  ^
```

though clearly the dimensions are correct.

**Comment by stuartarchibald** [comment]
Thanks for the report. The above is failing because you are using Python 3.9, which is not supported by any released version of Numba yet. See here: https://github.com/numba/numba/issues/6345#issuecomment-759509837 for how to get a development version with 3.9 support, or perhaps create a new environment for using Numba with a supported python (3.6, 3.7, 3.8 should all work fine)? I've tested the above code and it's working fine else. Hope this helps?

**Comment by smiet** [comment]
Thank you, the issue has been resolved by switching to the master version of numba and llvm. Providing the installation commands using pip for reference: 
`pip install git+https://github.com/numba/numba`
`pip install git+https://github.com/numba/llvmlite`

**Comment by esc** [comment]
@smiet happy to hear that you managed to resolve this issue by using development versions! As a sidenote, I would like to comment that the `llvmlite` you installed may not have been compiled against the custom LLVM version as required by Numba. It's probably fine for your use-case right now, but you may at some point later on, encounter some issues. So, this is just something to keep in mind in the future. You can read about it here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html

Also, we do provide pre-compiled `llvmlite` packages -- but only for conda -- doing the following

```
conda install -c numba numba
```

Should always get you the latest "nightly" pre-compiled build of both  Numba and llvmlite (with a correctly patched and compiled LLVM statically linked into the llvmlite packages).

Thanks again for following up on this and posting your solution.
