### ISSUE TITLE
global variable and default value

### ISSUE THREAD

**Issue by swchiow** [numba/numba#667]
Hi there,

When there is a global variable used in a @jit function, an error message shows up:
LoweringError: Internal error:
TypeError: unhashable type: 'numpy.ndarray'

When there is a variable with default value and not assigned when called, an error message shows up:
TypeError: Required argument 'xxx' (pos 3) not found

It took me sometime to figure these out.

Cheers,
SC

**Comment by pitrou** [comment]
This was fixed in the above PR.
