### ISSUE TITLE
setup.py does not support multiple command execution if an info command (e.g. egg_info) is one of them

### ISSUE THREAD

**Issue by teruokun** [numba/numba#6687]
Attempting to run the following will yield no build output as it contains a single info command:
```
setup.py build build_ext egg_info
```  

This is considered normal practice for running multiple commands at a time with `setup.py`.  This is because the optimization logic around `setup.py:is_building` is using a negative constraint (i.e. no info commands) instead of a positive constraint (e.g. commands are empty or includes one of the build commands).  This should be minor to fix and will make it possible to include info-generating commands with the build step when building from source, which is still useful for exporting entry points, dependency requirements, and other metadata.

**Comment by esc** [comment]
@teruokun thank you for submitting this. I have marked it as needing triage and I hope someone will look at it in due course.

**Comment by HPLegion** [comment]
It looks like the problem may be here: https://github.com/numba/numba/blob/00ad12751725391e8423d67ef845ba56110c55df/setup.py#L113-L138

The `'ext_modules'` field of the setup metadata is only appended if the function above returns True.
However that function only if checks if an info command is present in `sys.argv`, it does not check whether ONLY info commands are given.
