### ISSUE TITLE
Error Profiling Code with Numba's njit decorator in Spyder

### ISSUE THREAD

**Issue by hannahbus** [numba/numba#6699]
Hi,

I'd like to profile my code - including the function below - using Spyder's profiling tool on a Windows machine (equipped with Python 3.8). 
 
```
@njit(cache  = True)
def quadratic_form(vec, mat):
       return np.dot(vec, mat @ vec)
```

However, when profiling the code I get the following output and error

from numba import njit
from numba.core import config
import llvmlite.binding as ll
from .dylib import *
from llvmlite.binding import ffi
raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: llvmlite.dll

I realised that with Version 0.49.0 Andreas Sodeur fixed a bug relating to cProfile and Numba JIT compiled functions in #4476. 

Thanks for your help.

**Comment by esc** [comment]
@hannahbus thank you for asking about this. This issue will need some triage, presumably. Perhaps a good place to start would be to ask: "does this only happen when you profile"? Also, how did you install Python, was it `pip` or `conda` or something else?

**Comment by hannahbus** [comment]
@esc Thanks for getting back to me. Regarding your question .. This only happens when I profile the code. I installed Python via conda.

**Comment by esc** [comment]
@hannahbus OK, thank you for reporting back. I am out of ideas here as to what to do so I can only guess from this point onwards. The error basically means, that the Python interpreter can not find the `llvmlite.dll` library so it is unlikely that #4476 will help in this case. My wild guess is that either the Windows equivalent of `LD_LIBRARY_PATH` (the environment variable that governs this on Linux) is somehow incorrect in the case of profiling or that the `python` executable used by Spyder when profiling is different. 

My suggestions for next steps are:

* Work out what environment variable governs how shared libraries are loaded on Windows and attempt to print that during profiling and not-profiling to see if it has been modified somehow.
* Work out which `python` executable is used by Spyder during profiling.
* Run the code outside Spyder, but using `cProfile`, to ensure that this is indeed a Spyder issue and doesn't happen during 'regular' Profiling.
* Ask the Spyder community if this is something familiar to them and perhaps they already have a solution.

Good luck and let us know how it goes!

**Comment by esc** [comment]
@hannahbus we haven't heard back from you regarding this issue, did you manage to find a solution or workaround?

**Comment by gmarkall** [comment]
Closing this issue as there's no further information to reproduce and it's been marked stale twice.
