### ISSUE TITLE
CUDA: Support compare and swap on array elements other than the first

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#6702]
(Noticed whilst reviewing #6695)

From the [docs for `numba.cuda.atomic.compare_and_swap`](https://numba.readthedocs.io/en/stable/cuda/intrinsics.html#supported-atomic-operations):

> class compare_and_swap(ary, old, val)
>> Conditionally assign val to the first element of an 1D array ary if the current value matches old.
>> Returns the current value as if it is loaded atomically.

It seems a little odd that this is implemented to always operate on the first array element, instead of an arbitrary element like the other atomic operations. Perhaps another variant that operates on an arbitrary element would be a nice addition. Options for the signature include:

- `compare_and_swap(ary, idx, old, val)`: Consistent with other atomic functions, a bit jarring compared to the existing `compare_and_swap(ary, old, val)` as it inserts a new `idx` argument in the argument list.
- `compare_and_swap(ary, old, val, idx)`: Consistent with the existing `compare_and_swap`, but inconsistent with other atomic functions
- `cas_element(ary, idx, old, val)`: Consistent with other atomic functions, doesn't clash with the existing `compare_and_swap` argument order in the sense that it's not the same function name, but adds another function for the same operation.

I'd lean to towards the `cas_element` option because it feels least likely to violate the principle of least astonishment (but could be convinced on the merits of another option either above or not listed here).

**Comment by rawwar** [comment]
I am guessing this should be an easy one. I want to take it up.  But, I checked numba.cuda.atomic . Sub classes inside atomic don't seem to have any implementation. Can i get some pointers on how exactly i can implement the functionality?

**Comment by rawwar** [comment]
#2278 looks like a good starting point to understand how to implement this. I want to take it up and try

**Comment by gmarkall** [comment]
@rawwar Thanks for your interest in contributing to Numba! Although #2278 first added atomics, the code then was a bit different to what it is now - looking at https://github.com/numba/numba/pull/6499 which is a much more recent addition to the atomics will probably provide a better guide for your understanding. If you need any guidance or explanation, please do ask on Discourse or drop into the numba-dev gitter channel: https://gitter.im/numba/numba-dev

**Comment by rawwar** [comment]
I tried writing a test case for cas_element. Please correct if the test case correctly tests the feature.
```

import sys
from random import shuffle
sys.path.append(r"H:\OpenSource\numba")

import numpy as np
from numba import cuda

res = [-1,-1,-1,-1]
res = np.array(res)
old = np.array([0,0,0,0])
ary = np.array([10,20,30,40])
idx = list(range(len(res)))
idx = shuffle(idx)
fill_val = -1

def atomic_compare_and_swap_elem(res, old, idx,ary, fill_val):
    gid = cuda.grid(1)
    if gid < res.size:
        out = cuda.atomic.compare_and_swap_element(res[gid:], idx[gid],fill_val, ary[idx[gid]])
        old[idx[gid]] = out


cuda_func = cuda.jit(atomic_compare_and_swap_elem)
cuda_func[2,2](res,idx,old,ary,fill_val)


```

**Comment by gmarkall** [comment]
@rawwar One thing that's missing from your example is an assertion that checks that the CAS operation has done the right thing - suppose the `atomic_compare_and_swap_element` function did nothing, this example could still run to completion. Usually for checking correctness, I'd write a sequential implementation (e.g. on a NumPy array the CPU) that computes the expected result, and then check that it matches the version from CUDA, e.g.

```python
# expected_out = <computation in Python>
# expected_err = <computation in Python>
np.testing.assert_equal(expected_out, out)
np.testing.assert_equal(expected_res, res)
```
