### ISSUE TITLE
caching + (safe) casting + recursive function -> segmentation fault

### ISSUE THREAD

**Issue by louisabraham** [numba/numba#6713]
I'm using numba 0.52.0 with Python 3.8.6 on arch.

I observed a weird bug, here is a MWE.

```python
import numpy as np
from numba import njit


njit = njit(cache=True)


@njit
def _find(forest, i):
    if forest[i] != i:
        forest[i] = _find(forest, forest[i])
    return forest[i]


@njit
def f(x):
    print("inside")
    forest = np.array([0], dtype=np.uint64)
    _find(forest, x)
    return


print("before")
print(f(np.uint32(0)))
print("done")
```

I launch: `rm -rf __pycache__ && python bug.py  && python bug.py`

Output:

```
before
inside
None
done
before
Segmentation fault (core dumped)
```

When I disable the cache by commenting `njit = njit(cache=True)`, it works.

I tested several pairs of integer types and basically, I get the error iff the two types don't match.

**Comment by esc** [comment]
@louisabraham thank you for reporting this. I can reproduce this issue locally on my mac. I also noticed that the runtime is significantly increased when hitting the bug, and that when run several times, it may even crash earlier:

```
 💣 zsh» python issue6713.py && python issue6713.py                                                                                                                 :(
before
[3]    57745 segmentation fault (core dumped)  python issue6713.py
python issue6713.py  0.63s user 6.05s system 59% cpu 11.215 total
```

My wild guess is there is some run-away loop or recursive function invocation that leads to the segfault. 

Using Python 3.8.2 on OSX 10.15.7

**Comment by esc** [comment]
Here is an `lldb` trace:

```
 💣 zsh» lldb -- python issue6713.py
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) settings set -- target.run-args  "issue6713.py"
(lldb) run
Process 58200 launched: '/Users/esc/miniconda3/envs/numba_3.8/bin/python' (x86_64)
before
Process 58200 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (_fblas.cpython-38-darwin.so) stopped.
```

**Comment by louisabraham** [comment]
My guess is that there is an issue in the way overloaded functions are stored: note that without cache it works fine!

**Comment by louisabraham** [comment]
Hi, any update on this? I can reproduce on m1 with 0.53.1

**Comment by esc** [comment]
yes, I can reproduce this from `master` on my `x86_64` Macbook:

```
 zsh» rm -rf __pycache__ && python issue6713.py && python issue6713.py
before
inside
None
done
before
[1]    50622 segmentation fault (core dumped)  python issue6713.py
python issue6713.py  0.90s user 16.61s system 54% cpu 32.067 total
```

**Comment by esc** [comment]
hmmmm.

```
 zsh» lldb python
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) r issue6713.py
Process 52878 launched: '/Users/vhaenel/miniconda3/envs/numba_3.8/bin/python' (x86_64)
before
Process 52878 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: (_ufuncs.cpython-38-darwin.so) stopped.
```

**Comment by esc** [comment]
@louisabraham thank you for asking about this. We have not yet made any progress on this issue and I can confirm I am still able to reproduce this on master.

**Comment by AleCandido** [comment]
Simpler than the OP: the following script is enough to crash, when you run it twice.

```py
import numba as nb


@nb.njit(cache=True)
def f(exit):
    if exit:
        return 1.0
    return f(True)


print(f(True))
```

**Comment by gmarkall** [comment]
@AleCandido Thanks, it probably is.

**Comment by louisabraham** [comment]
Thank you for observing the same behavior!

I think it is probably the same issue but I don't have any problem without casting:

> I tested several pairs of integer types and basically, I get the error iff the two types don't match.

For example,

```py
import numpy as np
from numba import njit


njit = njit(cache=True)


@njit
def _find(forest, i):
    if forest[i] != i:
        forest[i] = _find(forest, forest[i])
    return forest[i]


@njit
def f(x):
    print("inside")
    forest = np.array([0], dtype=np.uint64)
    _find(forest, x)
    return


print("before")
print(f(np.uint64(0)))
print("done")
```

works fine.

If you already know what the problem is, you can ignore it. Else this behavior could give a few supplementary hints.
