### ISSUE TITLE
RPi3: cannot install Numba due to issue with LLVM toolchain

### ISSUE THREAD

**Issue by COfek** [numba/numba#6723]
## Reporting a bug

system information:
- Raspberry pi 3 Model B
- os is Rapsbian 10 (buster)
- Python 3.7.3
- attempting to install Librosa through pip 20.0.1
- gcc version 8.3.0

Hello,

I've been trying to install Librosa on my raspberry pi 3 model B.
the line I used in order to install Librosa was: `pip3 install --upgrade --user librosa`
after a really long download the installation got into infinite backtracking of the pip resolver trying to solve version conflicts over numba so I decided to  run the line: `pip3 install --upgrade --user -no--deps librosa` instead and it did work and librosa was installed successfully according to pip.

right now when I attempt to import Librosa in the python shell I get the following Traceback:

`pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/pi/.local/lib/python3.7/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/pi/.local/lib/python3.7/site-packages/numba/__init__.py", line 4, in <module>
    from numba import module_type_inference
  File "/home/pi/.local/lib/python3.7/site-packages/numba/module_type_inference.py", line 8, in <module>
    from numba import typesystem, symtab
  File "/home/pi/.local/lib/python3.7/site-packages/numba/typesystem/__init__.py", line 6, in <module>
    from .typemapper import *
  File "/home/pi/.local/lib/python3.7/site-packages/numba/typesystem/typemapper.py", line 3, in <module>
    import llvm.core
ModuleNotFoundError: No module named 'llvm'
`

I've tried to run `sudo apt-get install llvm` and it did install llvm but didn't solve the issue.
also tried running `pip3 instal llvmlite` but got the following result:

`sudo pip3 install llvmlite
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting llvmlite
  Could not find a version that satisfies the requirement llvmlite (from versions: )
No matching distribution found for llvmlite
`

another attempt at installing librosa with pip resulted in this error:

```

ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s9gczj9k
       cwd: /tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/
  Complete output (15 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py
  LLVM version... 7.0.1
  
  Traceback (most recent call last):
    File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 143, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: pycparser, llvmlite, numba, cffi, soundfile, resampy, audioread
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c8uz7phd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/llvmlite
         cwd: /tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/
    Complete output (18 lines):
    running install
    running build
    got version from file /tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py
    LLVM version... 7.0.1
    
    Traceback (most recent call last):
      File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/ffi/build.py", line 143, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '7.0.1'. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gw3_ve1/llvmlite_1d4974bee4c74364ac4e473f80edfd7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c8uz7phd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/llvmlite Check the logs for full command output.
```

**Comment by esc** [comment]
@COfek thank you for asking about this on the Numba issue tracker. Unfortunately we don't currently support binary wheels for llvmlite for Raspberry Pi yet. Hopefully in the next release. In the meantime you can either use `conda` to install a binary package or resort to compiling llvmlite from scratch. Instructions and more information can be found at:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#building-manually

**Comment by COfek** [comment]
@esc Thanks for responding, I am unable to use conda to install binary package because of conda not including some of the packages I need for raspberry pi like pyaudio, kivy and librosa itself seems to not install properly through conda as well I gave up on even trying to install tensorflow on a conda environment.
so my last resort is to try compile it from scratch, as I am not very experienced with this, may I ask what do I need to execute in command line to complete step 3 in the installation guide you gave me
`Decompress the LLVM tar file and apply the following patches from the llvmlite/conda-recipes/ directory. You can apply each patch using the Linux patch -p1 -i {patch-file} command:`

**Comment by esc** [comment]
@COfek thank you for following up on this. As far as I understand the `librosa` package is available from the `conda-forge` repositories as a conda package: https://anaconda.org/conda-forge/librosa -- perhaps is is worth giving this a shot?

Lastly, regarding the issue when compiling: Unfortunately the `llvmlite` documentation assumes a certain familiarity with the compilation of libraries from sources in general. What the documentation is referring to with `patch -p1 -i {patch-file}` is to run the command `patch -p1 -i` on each `{patch-file}` then listed below.

**Comment by abebeos** [comment]
@esc, just curious: is Raspberry pi 3 a valid target for numba?

**Comment by COfek** [comment]
@abebeos are you suggesting that numba would be valid on raspberry pi 4 ?

**Comment by abebeos** [comment]
> @abebeos are you suggesting that numba would be valid on raspberry pi 4 ?

No. Just wondering what the numba system-requirements are, and if raspberry (and similar boards) are within the limits.

**Comment by seibert** [comment]
To add some clarification here: 

Numba works and is tested on armv7l (32-bit ARM) and aarch64 (64-bit ARM) architectures.  The Raspberry Pi 2-4 are 64-bit ARM chips, but for backward compatibility reasons Raspberry Pi OS (aka "Raspbian", but not called that now) has been shipped primarily as a 32-bit OS, with 64-bit versions still considered beta.  Ubuntu 64-bit works fine (and is what we use for 64-bit ARM testing).

The main obstacle here is that we have not shipped wheels for ARM before.  Now that manylinux2014 (and pip) has a spec for 32-bit and 64-bit ARM wheels, we can start doing that once we can get it into our automation.  That should simplify installation on Raspberry Pis.  Building LLVM is painful on all platforms, and we should provide prebuilt binaries whenever we can.

As an aside: Does anyone know if manylinux2014 wheels (which are based on Centos 7 on all hardware platforms) work on recent versions of Pi OS?  I assume they have a new enough glibc, but haven't tested yet.

**Comment by esc** [comment]
@COfek how did it go with the install? Or did you maybe even get the conda-forge package to work? Is there anything else we can help with?

**Comment by COfek** [comment]
@esc I did give conda-forge a try and it didn't work,
I didn't try to build llvm manually yet because I'm not sure as for how I should do it.
I never worked with these sort of files tar.xz / gz and have little experience as for what lines I should do in the terminal in order to build it manually.
would really appreciate it if you could translate the guide into command lines I need to execute.
Thanks

**Comment by abebeos** [comment]
@esc, I had myself many trouble with manual llvmlite build. What needs to be done here, to help COfek and other folks in similar situation:

=> Simplify "build llvmlite from source" (ideally: a few cli instructions), revise docs (related: numba/llvmlite#686)

@COfek , not sure if this helps in your setup:

the simplest sequence to build llvmlite would be something like this:

```sh
conda install -c numba llvmdev  # llvmdev=<specific version:>
git clone https://github.com/numba/llvmlite.git
# git checkout <specific version>
cd llvmlite
python setup.py build
python runtests.py
python setup.py install
```

@esc should know about `<specific version>` needed.

**Comment by COfek** [comment]
@abebeos sorry for the rude question but,
could I replace conda with anything else ?
berryconda only supports python 3.6 so I'm not able to use the 3.7 env where I was able to setup other problematic packages.

**Comment by esc** [comment]
@COfek i
As for compiling the Numba/llvmlite stack without `conda` may also mean building it without `conda-build`. This is something I have only had to do once and it was reasonably involved. I don't think anyone has yet published step by step instructions on how to do this. Having said that, I would continue to recommend trying to obtain a suitable conda distribution and try the pre-compiled packages. I think that getting this setup to work properly on a RaspberryPi will yield more mileage for you in the long-term. It is my understanding that `miniforge` ships a suitable distribution for using recent Pythons on Raspberry PIs:

https://github.com/conda-forge/miniforge

But as far as I know, you will need the replacement of Raspbian with a 64 bit OS (ubuntu 64?) This may solve issues if you are unable to install miniforge.

**Comment by abebeos** [comment]
> sorry for the rude question

I see no rudeness!

As for conda: I recently came in contact with numba/llvmlite, and my summary is more or less: one needs to use conda, otherwise it can become difficult, even for experienced devs.

curiosity: can you please give me the result of your `uname -a`?

**Comment by COfek** [comment]
@abebeos 
uname -r returns 5.10.14-v7+, so kernel v7?
also I think that I may just resort to formatting the sd card and download everything on an ubuntu since everything did work as a whole on 64bit os.

**Comment by abebeos** [comment]
my understanding of https://github.com/numba/numba/issues/6723#issuecomment-779303209 tells me that you'll have similar problems.

uname -a ? (not -r)

**Comment by COfek** [comment]
@abebeos 

`uname -a
Linux raspberrypi 5.10.14-v7+ #1401 SMP Mon Feb 8 14:23:24 GMT 2021 armv7l GNU/Linux
`

**Comment by abebeos** [comment]
> `uname -a Linux raspberrypi 5.10.14-v7+ #1401 SMP Mon Feb 8 14:23:24 GMT 2021 armv7l GNU/Linux `

nice!

> by the way I didn't get a clear answer, do you think that if I run ubuntu on my RPI instead of raspbian everything would work fine ?

Yes, I think (according to comments made by seibert & esc, 64bit ubuntu works on RPI, and you could use miniforge (instead of miniconda3) , should be this one:

https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh

**Comment by COfek** [comment]
@abebeos Thanks a bunch I will try it tomorrow and update you guys on the situation.

**Comment by abebeos** [comment]
@COfek , I did not dig out my pi, but was curious enough to try on an fresh emulated ubuntu:20.04, arm64/aarch64

```sh
# use ubuntu aarch64, as suggested by @seibert
# on a fresh arm64 ubuntu:20.04

apt update && apt install  git wget gcc g++ make -y

# use conda-forge, as suggested by @esc
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh
chmod +x Miniforge3-Linux-aarch64.sh
./Miniforge3-Linux-aarch64.sh # follow through manually, usually  [ENTER] or "yes"
bash # start new shell to activate conda

#scikit-learn not working 
conda install -c conda-forge numpy numba scikit-learn

# your initial  installation line:
pip3 install --upgrade --user librosa

# => should install fine
```

**Comment by COfek** [comment]
@abebeos 
so I formatted my *new* SD card and installed the recommended Ubuntu Desktop 20.10 with the official imager of raspberry pi.
first thing I noticed is that the raspberry pi is extremely slow when using ubuntu compared to Raspbian,
as for trying to execute the following.
the python version installed by default is 3.8.6 and when I attempted to check pip version by `pip3 --version` pip didn't even seem to exist which already seems weird to me.
so I just apt installed pip3 and now `pip3 --version` returns `pip 20.1.1`
I was just casually trying to install numpy just to see if basic libraries would still install.
and got back no matching distribution found for numpy.
I haven't used ubuntu before so I didn't really know what to expect.
then I followed your instructions and it worked fine so far but I'll have to ask how using bash opened a conda environment ?
before I had to activate the relevant environment so why now opening a new shell automatically considers it to be a conda environment? 
Thanks again

**Comment by abebeos** [comment]
opening a shell from within a shell is more or less like restarting a shell (close / open).

As for your problem: whenever you see a sequence of instructions (https://github.com/numba/numba/issues/6723#issuecomment-780708001) , follow them strictly: start with a fresh ubuntu 20.04, execute one by one the instructions without anything else before (maybe add a `sudo` now and then when necessary).

If all this fails, then sorry, but this would be the point where I give up (as this needs to be verified on a real RPI then).

**Comment by COfek** [comment]
@abebeos 
I see thanks for answering.
I will try again, thank you very much for your help.

**Comment by esc** [comment]
Installing Numba via `pip` w/o compilation is currently not supported on RaspberryPi as we don't release binary wheels for `aarch64` platform yet. The current recommended workaround is to use `conda`.

**Comment by abebeos** [comment]
@COfek , one last try:

you could replace ubuntu64 with Raspberry Pi OS 64bit:

https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370

and then apply the same steps: https://github.com/numba/numba/issues/6723#issuecomment-780708001

**Comment by esc** [comment]
I just had another look at anaconda.org -- and it seems you may be able to install `librosa` using:

`conda install -c conda-forge librosa`

As the package is available here: https://anaconda.org/conda-forge/librosa/files?type=conda

**Comment by COfek** [comment]
@esc @abebeos just wanted to update you guys,
I got a new image for ubuntu 20.10 server and managed to install llvmlite and librosa successfully through pip.
the reason pip didn't work initially is because by default for some reason the pi used a ipv6 address instead of ipv4 so it had some communication issues with pypi.
after getting that figured out I just had to pip3 install llvmlite and following that librosa.

**Comment by abebeos** [comment]
Glad you did it.

But you were right that ubuntu is quite slow (i finally powered my dusted pi3+ after 2  years).

On my (tiny)'machine", I switched from umbutu to (the newly available) RPI OS 64:

* https://www.raspberrypi.org/forums/viewtopic.php?t=275370
* https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/2020-08-20-raspios-buster-arm64.zip

faster and looks funnier!

(note that you can close this issue if you feel it is solved)

**Comment by abebeos** [comment]
@esc, you mentioned miniforge, and it looks like conda-forge is anaconda.org related (https://conda-forge.org/#about).

It looks like conda-forge is kind of more complete (context: architectures) than miniconda, why is it not used for numba (e.g. within the buildscripts) ?

**Comment by abebeos** [comment]
follow-up:  #120

**Comment by esc** [comment]
> @esc, you mentioned miniforge, and it looks like conda-forge is anaconda.org related (https://conda-forge.org/#about).
> 
> It looks like conda-forge is kind of more complete (context: architectures) than miniconda, why is it not used for numba (e.g. within the buildscripts) ?

In my experience conda-forge is not quite as stable. While they do make new and fresh packages available very quickly, these are often still buggy. Using `defaults`/`main` has been the more stable alternative historically.

> EDIT: found this https://stackoverflow.com/questions/60532678/what-is-the-difference-between-miniconda-and-miniforge, but I'm now even more confused (mostly by Anaconda not including the quite relevant arm64 architecture into miniconda).

I believe it is simply not available yet.

**Comment by esc** [comment]
@COfek thank you for following up and closing this issue. I am glad you managed to get things up and running.
