### ISSUE TITLE
Error copying to host when memory slightly increased

### ISSUE THREAD

**Issue by jeffrey-cochran** [numba/numba#6729]
## Reporting a bug
Hi,

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I saw the same issue get raised twice before, but it was closed for lack of information. Running the following code:

```
from __future__ import division
from numba import cuda, float32
import numpy
import math

# Controls threads per block and shared memory usage.
# The computation will be done on blocks of TPBxTPB elements.
TPB = 256

@cuda.jit
def fast_matmul(A, B, C):
    """
    Perform cross product.
    A[i,:] x B[i,:] = C[i,:]
    """

    # Define an array in the shared memory
    # The size and type of the arrays must be known at compile time
    sA = cuda.shared.array(shape=(TPB, 3), dtype=float32)
    sB = cuda.shared.array(shape=(TPB, 3), dtype=float32)

    x  = cuda.grid(1)
    
    tx = cuda.threadIdx.x
    
    if x >= C.shape[0]:
        # Quit if (x, y) is outside of valid C boundary
        return

    # Each thread computes one element in the result matrix.
    # The dot product is chunked into dot products of TPB-long vectors.
    tmp = 0.
    for i in range(int(A.shape[0] / TPB)):
        for k in range(3):
            # Preload data into shared memory
            sA[tx, k] = A[tx + i * TPB, k]
            sB[tx, k] = B[tx + i * TPB, k]

        # Wait until all threads finish preloading
        cuda.syncthreads()

        # Computes partial product on the shared memory
        for j in range(TPB):
            C[j, 0] = sA[j, 1] * sB[tx, 2] - sA[j, 2] * sB[tx, 1]
            C[j, 1] = sA[j, 0] * sB[tx, 2] - sA[j, 2] * sB[tx, 0]
            C[j, 2] = sA[j, 1] * sB[tx, 0] - sA[j, 0] * sB[tx, 1]

        # Wait until all threads finish computing
        cuda.syncthreads()

    

# The data array
data_blocks = 1000
A = numpy.full((TPB*data_blocks, 3), 3, float) # [32 x 48] matrix containing all 3's
B = numpy.full((TPB*data_blocks, 3), 4, float) # [48 x 16] matrix containing all 4's

# memory size of numpy array in bytes 
print("Memory size of numpy array in bytes:", 
      A.size * A.itemsize)

A_global_mem = cuda.to_device(A)
B_global_mem = cuda.to_device(B)
C_global_mem = cuda.device_array((TPB*data_blocks, 3)) # [32 x 16] matrix result

# Configure the blocks
threadsperblock = (TPB,)
blockspergrid_x = int(math.ceil(A.shape[0] / threadsperblock[0]))
blockspergrid = (blockspergrid_x,)

# Start the kernel 
fast_matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)
res = C_global_mem.copy_to_host()
```

I get the following error:

> (point-location) C:\Users\jeffr\git\point-location>python sandbox.py
> Memory size of numpy array in bytes: 6144000
> Traceback (most recent call last):
>   File "sandbox.py", line 212, in <module>
>     res = C_global_mem.copy_to_host()
>   File "C:\Users\jeffr\anaconda3\envs\point-location\lib\site-packages\numba\cuda\cudadrv\devices.py", line 224, in _require_cuda_context
>     return fn(*args, **kws)
>   File "C:\Users\jeffr\anaconda3\envs\point-location\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 265, in copy_to_host
>     _driver.device_to_host(hostary, self, self.alloc_size,
>   File "C:\Users\jeffr\anaconda3\envs\point-location\lib\site-packages\numba\cuda\cudadrv\driver.py", line 2398, in device_to_host
>     fn(host_pointer(dst), device_pointer(src), size, *varargs)
>   File "C:\Users\jeffr\anaconda3\envs\point-location\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
>     self._check_error(fname, retcode)
>   File "C:\Users\jeffr\anaconda3\envs\point-location\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
>     raise CudaAPIError(retcode, msg)
> numba.cuda.cudadrv.driver.CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED

This does is not an issue for smaller choices of data_blocks; however, the array size is still relatively tiny in the above example (in my opinion), so I would be shocked if it's unable to copy for memory reasons. Hopefully, I'm just misunderstanding something. Please let me know what other useful information I can provide.

**Comment by gmarkall** [comment]
Thanks for the issue report and providing a reproducer. When I run on this on my system (Quadro RTX 8000), the reproducer terminated successfully. I'm just running it through `cuda-memcheck` to see if that reveals an issue, but this takes a little while to run.

**Comment by jeffrey-cochran** [comment]
Thanks @gmarkall! So maybe it does have something to do with my memory constraints?

**Comment by gmarkall** [comment]
Ah, I see you're on Windows - is your GPU running in TCC or WDDM mode? If it's in WDDM (the likely default) if the kernel runs for more than 2 seconds it'll be killed - does it appear to get killed after two seconds?

**Comment by jeffrey-cochran** [comment]
Aha! Yes, I'm almost certain that it is in WDDM mode. Since it completes for smaller matrices, I suspect you're right about that.

**Comment by gmarkall** [comment]
OK - you may have to modify the kernel so you can call it for multiple sub-2-second runs if you need to stay in WDDM mode.

**Comment by gmarkall** [comment]
BTW, I'm running on Linux so I don't have the limit. Running the kernel generally seems to eventually complete for different data sizes, and cuda-memcheck looks good:

```
$ cuda-memcheck python repro.py 
========= CUDA-MEMCHECK
Memory size of numpy array in bytes: 614400
========= ERROR SUMMARY: 0 errors
```

(I did this for `data_blocks = 100` to save time)

**Comment by jeffrey-cochran** [comment]
Awesome. Thanks @gmarkall

It's my laptop's onboard GeForce GTX 960M, so I suspect I can't run it in a headless configuration. 

I do have an external GPU that I can thunderbolt to, maybe I'll try that next.

**Comment by jeffrey-cochran** [comment]
It also seems that I may be able to configure the timeout. I'll let you know if that works

**Comment by jeffrey-cochran** [comment]
@gmarkall I was able to use Nvidia's Nsight monitor (why do they insist on these ridiculous names) to turn off the Time Detection and Recovery limit altogether. I then switched all rendering to my cpu, and I'm able to execute the operation without any issue whatsoever. 

Thanks so much for your help. It would have been a pain to hook up my external GPU just for putzing around with some toy computations :)

**Comment by gmarkall** [comment]
> I was able to use Nvidia's Nsight monitor (why do they insist on these ridiculous names)

Surely you meant "awesome names" :-)

> Thanks so much for your help. It would have been a pain to hook up my external GPU just for putzing around with some toy computations :)

You're welcome - I'm glad your problem is solved!
