### ISSUE TITLE
Interface for registering Python to Numba type mappings

### ISSUE THREAD

**Issue by seibert** [numba/numba#673]
As part of #665, I'm trying to simplify and document the ways we extend Numba to support new types.

In the case of Python to Numba type mappings, we have two places where this is currently done:

1. In the function dispatcher (`_OverloadedBase.typeof_pyval()`): Used to map Python function arguments to Numba types to decide which compiled function to use, or to trigger a new compilation if none can be found.
2. In the typing context (`BaseContext.resolve_value_type()`): Used to find the Numba type of globals values accessed from the function being compiled.

Neither of these functions is particularly extensible to new Numba types.  `typeof_pval()` has a hardcoded mapping in the form of if/else chain, falling back to checking if the Python object has a `_numba_type_` attribute.  

The `resolve_value_type()` method has a different hardcoded list of types (longer than `typeof_pyval()`), and falls back to a dictionary mapping global values to Numba types.

---

The use case I want to support is a library author wanting a non-standard Python type to map to a particular Numba type during autojit, as well as if they have any global constants of a non-standard Python type.

(I've had some discussion with @sklam about what this API should look like, so I'll follow up with that.)

**Comment by pitrou** [comment]
The `@typeof_impl` generic function now allows to do this easily :-)
