### ISSUE TITLE
Docs: redefinition of stdlib functions causing invalid cross references.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6737]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] N/A ~I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.~

Following on from https://github.com/numba/numba/pull/6619#discussion_r578554321 the doc pages that come from "autogeneration" via `numba.misc.help.inspector` redefine functions from python stdlib modules, e.g. `math.sin`, as a result referring to `` :func:`math.sin` `` in docs leads to a link being generated to the Numba redefinition opposed to the Python docs.

**Comment by gmarkall** [comment]
Would marking them `:noindex:` help?

**Comment by stuartarchibald** [comment]
> Would marking them `:noindex:` help?

Good idea, thanks, https://github.com/numba/numba/pull/6742 fixes.
