### ISSUE TITLE
After adding nopython=True in @jit() getting error.

### ISSUE THREAD

**Issue by Hawk-55** [numba/numba#6752]
/home/harshal/.local/lib/python3.6/site-packages/sympy/printing/ccode.py:12: SymPyDeprecationWarning: 

importing from sympy.printing.ccode has been deprecated since SymPy
1.7. Use Import from sympy.printing.c instead. See
https://github.com/sympy/sympy/issues/20256 for more info.

  deprecated_since_version="1.7").warn()

Bad key "text.kerning_factor" on line 4 in
/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Simulator,	 Number of Qbits,	 Time Taken
Traceback (most recent call last):
  File "../qft1.py", line 111, in <module>
    main()
  File "../qft1.py", line 107, in main
    n_time = elapsed_time(args,11)
  File "../qft1.py", line 65, in elapsed_time
    qft(qc,qu)
  File "../qft1.py", line 52, in qft
    qft_rotations(circuit, n)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 348, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x7fc8d02dec50>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/errors.py", line 617, in new_error_context
    yield
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/typeinfer.py", line 198, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/typeinfer.py", line 141, in propagate
    constraint(typeinfer)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/typeinfer.py", line 199, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/harshal/.conda/envs/py36/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: 
[1] During: typing of argument at ../qft1.py (33)
--%<----------------------------------------------------------------------------

File "../qft1.py", line 33:
def qft_rotations(circuit, n):
    <source elided>
    """Performs qft on the first n qubits in circuit (without swaps)"""
    if n == 0:
    ^

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'qiskit.circuit.quantumcircuit.QuantumCircuit'>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

--------------> numba version = 0.42.1

**Comment by esc** [comment]
@Hawk-55 thank you for submitting this to the Numba issue tracker. I can not see the code you ran to obtain this stacktrace so it may be worthwhile to add that. Guessing from the error, you may have attempted to compile a `qiskit.circuit.quantumcircuit.QuantumCircuit` which is not a datatype understood by Numba, i.e. not something Numba can compile.

Also note that Numba 0.42.1 is almost two years and I would recommend to upgrade to a recent version, regardless of weather this fixes the current error or not.

**Comment by Hawk-55** [comment]
#import numba as nb
#from numba import jit
import random

import numpy as np
# importing Qiskit
import qiskit
from qiskit import QuantumCircuit, execute
from qiskit.tools.monitor import job_monitor
import time
import matplotlib.pyplot as plt
import argparse
import sys
#from qiskit import Aer 

# In[5]:

from concurrent.futures import ThreadPoolExecutor
import resource

from time import sleep
#sys.setrecursionlimit(4000)

@jit(nopython=True, parallel=True)
def qft_rotations(circuit, n):
    """Performs qft on the first n qubits in circuit (without swaps)"""
    if n == 0:
        return circuit
    n -= 1
    circuit.h(n)
    for qubit in range(n):
        circuit.cu1(np.pi/2**(n-qubit), qubit, n)
    # At the end of our function, we call the same function again on
    # the next qubits (we reduced n by one earlier in the function)
    qft_rotations(circuit, n)

#@jit(parallel=True)
def swap_registers(circuit, n):
    for qubit in range(n//2):
        circuit.swap(qubit, n-qubit-1)
    return circuit

#@jit(parallel=True)
def qft(circuit, n):
    """QFT on the first n qubits in circuit"""
    qft_rotations(circuit, n)
    swap_registers(circuit, n)
    return circuit


def elapsed_time(args,qu):
    backend = args.get('backend')
    shots = args.get('shots')
    sim_backend = qiskit.BasicAer.get_backend(backend)
#    sim_backend = Aer.get_backend(backend)
    qc = QuantumCircuit(qu)

    qft(qc,qu)
    start = time.time()
    options = {
        "thermal_factor": 0.,
        "decoherence_factor": .9,
        "depolarization_factor": 0.99,
        "bell_depolarization_factor": 0.99,
        "decay_factor": 0.99,
        "rotation_error": {'rx':[1., 0.], 'ry':[1., 0.], 'rz': [1., 0.]},
        "tsp_model_error": [1., 0.],
        "plot": False
    }
    qc1 = qiskit.execute(qc, backend=sim_backend, shots=shots, **options)
    result = qc1.result()
    #print(result)
    #qc.draw()

    elapsed = (time.time() - start)

    print(str(backend) + "," + str(qu) + "," + str(elapsed), flush=True)

    return elapsed

def plot_graph(lst1,lst2):
    plt.title('QFT on quantum circuit')
    plt.plot(lst2, lst1)
    plt.xticks(lst2)
    plt.yticks(lst1)
    plt.ylabel('Time elapsed in seconds')
    plt.xlabel('Number of Q Bits')
    plt.show()

    return True

#@jit(parallel=True)
def main():
#    args = {'backend':'qasm_simulator','shots':1024}
    args = {'backend':'dm_simulator','shots':1}
    print("Simulator,\t Number of Qbits,\t Time Taken")
    n_time = elapsed_time(args,11)



main()

--------------------------------------------------------------------------------
Thank u @esc, but I have updated to 0.50.1 but still getting error.
This code , i'm using. 

Thanks

**Comment by esc** [comment]
@Hawk-55 thank you for following up on this. It is as I expected, `QuantumCircuit` is not a type that can be used as an argument to a `@jit(nopython=True, parallel=True)` decorated function. Supported Python features and types are listed here:
https://numba.readthedocs.io/en/stable/reference/pysupported.html

**Comment by esc** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by esc** [comment]
@Hawk-55  it may also be worth reading the 5-min Numba guide to Numba to familiarize yourself with Numba's capabilities: https://numba.pydata.org/numba-doc/latest/user/5minguide.html
