### ISSUE TITLE
Breaking Changes in Intel TBB 2021.1 - Numba Fails to Build

### ISSUE THREAD

**Issue by danieldjewell** [numba/numba#6806]
## TBB 2021.1

TBB 2021.1 has some breaking changes as noted in the [release notes](https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html). Also see the [TBB revamp](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html) document Intel published describing the changes.

### Changes

There are several changes to TBB that completely breaks building Numba. Notably: 
* removal of ```tbb::task_scheduler_init``` and other API changes

### Affected Versions

As of this writing, ```master``` (rev cdcb78848ca100f74744c65b4e8a32cf39079d57) is affected.

### Other Notes

Using ```libtbb-dev - 2020.1-2``` from Ubuntu ```focal``` does work. *Seems* like tbb 2020.4.304 from Intel does work.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is indeed an issue! A fix is scheduled, there's a WIP PR here https://github.com/numba/numba/pull/6096 if you'd like to track progress. Thanks again!

**Comment by stuartarchibald** [comment]
Feature request is to support new ABI TBB.

**Comment by stuartarchibald** [comment]
This was fixed in https://github.com/numba/numba/pull/6854. The upcoming Numba 0.54 will be the first release to support TBB 2021.
