### ISSUE TITLE
If condition against an integer fails

### ISSUE THREAD

**Issue by mathisc** [numba/numba#6815]
Hi, 

Considering the code below, I don't see why `_test_tuple` works fine in both  'if' cases whereas `_test_int` fails in one of the two cases :   
```python
from numba import njit, prange
import numpy as np


def _test_int(_input, additional_dimension: int):
    for x in prange(_input.shape[0]):
        if additional_dimension > 0:

            for dim_idx in prange(0, additional_dimension):

                local_slice = _input[x, dim_idx]
                # Do some specific treatement here
        else:
            local_slice = _input[x]
            # Do some other treatement here


def _test_tuple(_input, additional_dimension: tuple):
    """Same function as above but addtional_dimension is a tuple"""
    for x in prange(_input.shape[0]):
        if len(additional_dimension) > 0:

            for dim_idx in prange(0, additional_dimension[0]):

                local_slice = _input[x, dim_idx]
                # Do some specific treatement here
        else:
            local_slice = _input[x]
            # Do some other treatement here


np.random.seed(2021)
data_simple = np.random.random((10,))
data_complete = np.random.random((10, 2))

# Compilation :
_test_int_jitted = njit(_test_int)
_test_tuple_jitted = njit(_test_tuple)

# Executions :
# OK
_test_tuple_jitted(data_complete, (2,))
# OK
_test_tuple_jitted(data_complete, (0,))
# OK
_test_int_jitted(data_complete, 2)
# KO : why the if branching does fail here?
_test_int_jitted(data_simple, 0)
```
The latest line fails with the following error (meaning we took the wrong branch in the `if` since addtional_dimension equals zero : 
```bash
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array(float64, 1d, C), UniTuple(int64 x 2))
 
There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(float64, 1d, C), UniTuple(int64 x 2))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 162.
    With argument(s): '(array(float64, 1d, C), UniTuple(int64 x 2))':
   Rejected as the implementation raised a specific error:
     TypeError: cannot index array(float64, 1d, C) with 2 indices: UniTuple(int64 x 2)
  raised from /home/claire/.virtualenvs/sunmet/lib/python3.8/site-packages/numba/core/typing/arraydecl.py:84

During: typing of intrinsic-call at numba_test.py (11)

File "numba_test.py", line 11:
def _test_int(_input, additional_dimension: int):
    <source elided>

                local_slice = _input[x, dim_idx]
```

The fact that the code works fine with a tuple and fails with an int feels incoherent to me, does any one have any tips or hints on this behaviour?
(Python==3.8.5, numba==0.52.0, numpy==1.19.4)
Thanks.

**Comment by esc** [comment]
@mathisc thank you for asking about this on the Numba issue tracker. The problem here is that Numba isn't interpreted. So the error you are seeing is not actually during execution or runtime (i.e. the if branch isn't even being executed yet). Numba will try to do type inference based on the type of `input_`, it will see that this is a 1D array, then it will look for uses of `_input` and see that you are trying to index into a 1D array with a tuple. This doesn't make any sense and so Numba yields the error message above. My suggestion would be to make two Numba njit compiled functions, one for 1D arrays and one for 2D arrays. Then check the  dimensionality of your array and then decide on which Numba function to call. 

Hope this makes sense and helps?

**Comment by esc** [comment]
I should add that `_test_tuple_jitted(data_simple, (0,))` will also fail. So, both `test_*` functions will fail if presented with a 1D array as input.

**Comment by mathisc** [comment]
Arg, this is an error of me trying to reproduce my issue (I indeed wanted to run `_test_tuple_jitted(data_simple, (0,))` but I mistakingly run `_test_tuple_jitted(data_complete, (0,))`). Also in the actual code I wasn't using `(0,)` but a true empty `tuple`. Sorry about that, please find another snippet below that works with with tuples but not an int : 
```python
from numba import njit, prange
import numpy as np

@njit()
def _test_int(_input, additional_dimension: int):
    for x in prange(_input.shape[0]):
        if additional_dimension > 0:

            for dim_idx in prange(0, additional_dimension):

                local_slice = _input[x, dim_idx]
                # Do some specific treatement here
        else:
            local_slice = _input[x]
            # Do some other treatement here


@njit()
def _test_tuple(_input, additional_dimension: tuple):
    """Same function as above but addtional_dimension is a tuple"""
    for x in prange(_input.shape[0]):
        for y in prange(_input.shape[1]):
            for z in prange(_input.shape[2]):
                
                if len(additional_dimension) != 0:
                    for dim_idx in prange(0, additional_dimension[0]):

                        local_slice = _input[x,y,z,dim_idx]
                        # Do some specific treatement here
                else:
                    local_slice = _input[x,y,z]
                    # Do some other treatement here


np.random.seed(2021)
data_simple = np.random.random((10,9,8))
data_complete = np.random.random((10,9,8,2))

# Executions :
# OK
_test_tuple(data_complete, (2,))
# OK
_test_tuple(data_simple, tuple())
# OK
_test_int(data_complete, 2)
# KO : why the if branching does fail here?
_test_int(data_simple, 0)
```

**Comment by mathisc** [comment]
Indeed, this is an error of me trying to make a snippet reproduce the behaviour I am seeing : I indeed wanted to run `_test_tuple_jitted(data_simple, (0,))` but I mistakingly run `_test_tuple_jitted(data_complete, (0,))`). What's more in the actual code I wasn't using `(0,)` but a true empty `tuple`.
Sorry about that, please find another snippet below that actually reproduces the behaviour I am talking about : 
```python
from numba import njit, prange
import numpy as np

@njit()
def _test_int(_input, additional_dimension: int):
    for x in prange(_input.shape[0]):
        if additional_dimension > 0:

            for dim_idx in prange(0, additional_dimension):

                local_slice = _input[x,dim_idx]
                # Do some specific treatement here
        else:
            local_slice = _input[x]
            # Do some other treatement here


@njit()
def _test_tuple(_input, additional_dimension: tuple):
    """Same function as above but addtional_dimension is a tuple"""
    for x in prange(_input.shape[0]):
        if len(additional_dimension) != 0:
            for dim_idx in prange(0, additional_dimension[0]):

                local_slice = _input[x,dim_idx]
                # Do some specific treatement here
        else:
            local_slice = _input[x]
            # Do some other treatement here


np.random.seed(2021)
data_simple = np.random.random((10))
data_complete = np.random.random((10,2))

# Executions :
# OK
_test_tuple(data_complete, (2,))
_test_tuple(data_simple, tuple())

# KO
#_test_int(data_complete, 2)
#_test_int(data_simple, 0)
```

**Comment by esc** [comment]
@mathisc thank you for updating your question. Just to make sure we are aligned:

`_test_int(data_complete, 2)` <--- this works
`_test_int(data_simple, 0)` <--- this doesn't

**Comment by esc** [comment]
@mathisc I am not sure exactly why this example works for `tuple`. I think it is because the length of the tuple is not known at typing time, whereas the value of an integer may be literal and may be known at typing time. So with an `int` as parameter Numba can reject the function outright, but with a `tuple` it needs to partly execute before it can determine which branch to take.

@stuartarchibald do you concur?

**Comment by mathisc** [comment]
On my side, neither of the `_test_int` methods work, but both of the `_test_tuple` calls are working fine on my side. 
This feels weird as they basically _do_ the same kind of branching.
Given your explanations above, what actually puzzles me really is that : 
`_test_tuple(data_simple, tuple()) ` works like a charm.

**Comment by stuartarchibald** [comment]
@esc yes, it's essentially that Numba "sees" the type of the tuple as "tuple with X things in it", and so at compile time `len(<some tuple>)` can be resolved to a constant `X`, the branch pruning algs then kick in and remove unreachable code based on constants they can work out. In the case of an integer input, Numba just sees the type as "it's some integer" and so cannot specialise further (without doing something complicated to tell it to do this). This is to prevent creating a new version of the function being compiled for every value of integer provided.

**Comment by mathisc** [comment]
@esc @stuartarchibald thanks a lot of the clarification. 
Would you consider this to be a "valid and sustainable trick" or would you recommend to split the code into 2 functions depending on the branching ?

**Comment by stuartarchibald** [comment]
> @esc @stuartarchibald thanks a lot of the clarification.
> Would you consider this to be a "valid and sustainable trick" or would you recommend to split the code into 2 functions depending on the branching ?

No problem. Numba uses it internally, and there's compiler passes on the default compilation pipelines to ensure this behaviour works. It was originally designed in part to deal with the common pattern:
```python
def foo(n, x=None):
  if x is None:
    x = np.empty(n)
  #... do work with `x`
```

**Comment by mathisc** [comment]
Thanks a lot guy ;)

**Comment by esc** [comment]
> Thanks a lot guys!

@mathisc no problem, thank you for using Numba.
