### ISSUE TITLE
declaring the type for numba jit is slower than not? 

### ISSUE THREAD

**Issue by JiahaoYao** [numba/numba#6820]
This is the MWE:  
```python
N = 10000
A = np.random.randn(N, N)
b = np.random.randn(N)

%timeit A.dot(b)

@nb.jit
def mydot(A, b): 
    return np.dot(A, b)

%timeit A.dot(b)

@nb.njit
def mydot(A, b): 
    return np.dot(A, b)

%timeit A.dot(b)

@nb.njit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit A.dot(b)

@nb.jit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit A.dot(b)

```

This is the result: 
```markdown
27.3 ms ± 487 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
27.2 ms ± 324 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
27.9 ms ± 811 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
<ipython-input-12-5fc3b5131339>:21: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 1d, A))
  return np.dot(A, b)
27.3 ms ± 540 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
<ipython-input-12-5fc3b5131339>:27: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 1d, A))
  return np.dot(A, b)
29.4 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Several questions: 
1. why jit with `nopython=True` is sometimes slower than just the `jit`? 
2. why declare the type for `jit` makes the code slower? and `NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 1d, A))` means I am doing something wrong? 
3. why jit not bring the speedup? 

I would appreciate your feedback, thanks!

**Comment by esc** [comment]
@JiahaoYao I think you may be confused about how Numba works. In order to actually use the function `mydot` you need to call it like `mydot(A,b)`. In the example above you repeatedly c

**Comment by esc** [comment]
Sorry, my keyboard did something weird and my comment above was interrupted and the issue closed. I will try again below.

**Comment by esc** [comment]
@JiahaoYao I think you may be confused about how Numba works. In order to actually use the function `mydot` you need to call it like `mydot(A,b)`. In the example above you repeatedly call `%timeit A.dot(b)` which just calls the Numpy implementation again and again. The speed timings you are seeing are just the result of regular jitter and noise of your computer since you are repeatedly benchmarking the same function.

So for example, the benchmarks should be more like:

```
In [2]: import numpy as np

In [3]: import numba as nb

In [4]: N = 10000
   ...: A = np.random.randn(N, N)
   ...: b = np.random.randn(N)

In [5]: %timeit A.dot(b)
   ...:
47 ms ± 3.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: @nb.jit
   ...: def mydot(A, b):
   ...:     return np.dot(A, b)
   ...:

In [7]: %timeit mydot(A,b)
47.4 ms ± 4.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]: @nb.njit
   ...: def mydot(A, b):
   ...:     return np.dot(A, b)
   ...:

In [9]: %timeit mydot(A,b)
46.6 ms ± 5.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

1) Since no Numba functions are being called this question makes no sense. But judging from my example above `njit` and `jit` compiled functions are of similar speeds.

2) If you  specify the types you will not specify if the array is `C-order` (`C`)  or `F-order` (`F`) but instead `Any-order` (`A`) . Hence during compilation the error message will be raised. Try and see if you get this also when executing the function and not just compiling it.

3) In this case, judging from my example above,  using Numba will have little effect because the Numpy implementation of `dot` is already highly optimized and Numba will have nothing left to optimize.

It may be worth looking at the 5-min guide here https://numba.readthedocs.io/en/stable/user/5minguide.html to get a better sense of how Numba works.

**Comment by JiahaoYao** [comment]
Thanks @esc for your kind reply. Appreciated it! 

Oh, I forgot to change that line, thanks for changing it and reruning it.
```python
N = 10000
A = np.random.randn(N, N)
b = np.random.randn(N)

%timeit A.dot(b)

@nb.jit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)

@nb.jit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)
```

The results are 

![image](https://user-images.githubusercontent.com/20907377/111008675-7cd1b680-8346-11eb-8630-af9f79165449.png)


I see there are no room for numba to help the `np.dot`, but as for the type-inferring stuff. I am helping numba to figure out the type, and why that leads to slow-down. Do you mean this is not necessary? [And yes, the second time there is no warning. ] Could I ask when we need to specify the type because in some cases I did observe the speed-up? 

Thanks a lot for your feedback!

**Comment by JiahaoYao** [comment]
Thanks @esc for your kind reply. Appreciated it! 

Oh, I forgot to change that line, thanks for changing it and reruning it.
```python
N = 10000
A = np.random.randn(N, N)
b = np.random.randn(N)

%timeit A.dot(b)

@nb.jit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)

@nb.jit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)
```

The results are 

![image](https://user-images.githubusercontent.com/20907377/111008675-7cd1b680-8346-11eb-8630-af9f79165449.png)


I see there are no room for numba to help the `np.dot`, but as for the type-inferring stuff. I am helping numba to figure out the type, and why that leads to slow-down. Do you mean this is not necessary? [And yes, the second time there is no warning. ] Could I ask when we need to specify the type because in some cases I did observe the speed-up? 

Thanks a lot for your feedback!

**Comment by JiahaoYao** [comment]
Thanks @esc for your kind reply. Appreciated it! 

Oh, I forgot to change that line, thanks for changing it and reruning it.
```python
N = 10000
A = np.random.randn(N, N)
b = np.random.randn(N)

%timeit A.dot(b)

@nb.jit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)

@nb.njit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)

@nb.jit(nb.float64[:](nb.float64[:, :], nb.float64[:]))
def mydot(A, b): 
    return np.dot(A, b)

%timeit mydot(A, b)
%timeit mydot(A, b)
```

The results are 

![image](https://user-images.githubusercontent.com/20907377/111008675-7cd1b680-8346-11eb-8630-af9f79165449.png)


I see there are no room for numba to help the `np.dot`, but as for the type-inferring stuff. I am helping numba to figure out the type, and why that leads to slow-down. Do you mean this is not necessary? [And yes, the second time there is no warning. ] Could I ask when we need to specify the type because in some cases I did observe the speed-up? 

Thanks a lot for your feedback!

**Comment by esc** [comment]
Numba does type-inference so specifying the types ahead of time isn't strictly necessary. 

I had another look at:

https://numba.readthedocs.io/en/stable/reference/types.html#arrays

And it turns out, that specifying the layout of the Numpy arrays does make the code perform better (but still a little slower?):

```
In [2]: import numba as nb
im
In [3]: import numpy as np

In [4]: N = 10000
   ...: A = np.random.randn(N, N)
   ...: b = np.random.randn(N)

In [5]: @nb.njit(nb.float64[::1](nb.float64[:, ::1], nb.float64[::1]))
   ...: def mydot(A, b):
   ...:     return np.dot(A, b)
   ...:

In [6]: %timeit mydot(A,b)
44.5 ms ± 6.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: %timeit mydot(A,b)
44.2 ms ± 3.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

(Also, this will make the warnings go away.) 

Hope this helps?

**Comment by JiahaoYao** [comment]
Thanks @esc ! Your reply is really helpful and valuable!

**Comment by esc** [comment]
@JiahaoYao no problem, glad I could help. Please don't hesitate to open more issues or start a discussion on our Discourse ( https://numba.discourse.group/) if you hit any more snags or have any more questions. Thank you for using Numba 🙏

**Comment by JiahaoYao** [comment]
Appreciate it, @esc !
