### ISSUE TITLE
Regression: guvectorized functions can no longer be pickled in numba 0.53

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#6821]
This is a showstopper regression for users of guvectorized functions on dask.distributed:

```python
import numba
import pickle


@numba.guvectorize(["f8,f8[:]"], "()->()")
def double(x, out):
    out[:] = x * 2


print(pickle.dumps(double))
```

On Linux x64:
```bash
$ conda create -n test52 -c conda-forge python=3.8 numba=0.52
$ conda activate test52
$ python demo.py
b'\x80\x04\x95\x1a\x00\x00\x00\x00\x00\x00\x00\x8c\x0b__mp_main__\x94\x8c\x06double\x94\x93\x94.'
$ conda create -n test53 -c conda-forge python=3.8 numba=0.53
$ conda activate test53
$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    print(pickle.dumps(double))
_pickle.PicklingError: Can't pickle <ufunc 'double'>: it's not the same object as __main__.double
```

**Comment by esc** [comment]
@crusaderky thank you for submitting this! I can confirm, I am able to reproduce this with `b1258c82c0ed2845fce52508f439e29f729384a9` (current master) on OSX.

**Comment by esc** [comment]
@crusaderky thank you again for reporting this. During today's issue triage we concluded fixing this is important and we are planning a 0.53.1 release in two weeks from now. I have created a 0.53.1 milestone and will now add this issue to that.
