### ISSUE TITLE
Implement np.nan_to_num

### ISSUE THREAD

**Issue by jpivarski** [numba/numba#6857]
## Feature request

This is a formal request to implement [np.nan_to_num](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html), as a first step in contributing a PR. (I knew I'd be contributing something to Numba at some point...) I need to read over the [contributing guidelines](https://numba.pydata.org/numba-doc/dev/developer/contributing.html) to set up my environment, but the implementation would just be this:

```python
@numba.extending.overload(numpy.nan_to_num)
def nan_to_num(x, copy=True, nan=0.0, posinf=None, neginf=None):
    if isinstance(x, numba.types.Array):
        def nan_to_num_impl(x, copy=True, nan=0.0, posinf=None, neginf=None):
            if copy:
                out = numpy.copy(x).reshape(-1)
            else:
                out = x.reshape(-1)
            for i in range(len(out)):
                if numpy.isnan(out[i]):
                    out[i] = nan
                if posinf is not None and numpy.isinf(out[i]) and out[i] > 0:
                    out[i] = posinf
                if neginf is not None and numpy.isinf(out[i]) and out[i] < 0:
                    out[i] = neginf
            return out.reshape(x.shape)

    else:
        def nan_to_num_impl(x, copy=True, nan=0.0, posinf=None, neginf=None):
            if numpy.isnan(x):
                return nan
            if posinf is not None and numpy.isinf(x) and x > 0:
                return posinf
            if neginf is not None and numpy.isinf(x) and x < 0:
                return neginf
            return x

    return nan_to_num_impl
```

(Of course, if you want to add this before I have a chance to open a PR myself, please do so!)

It might be better for this to be implemented on `numba.types.ArrayCompatible`, rather than `numba.types.Array`, but I don't know if you're doing that yet.

**Comment by sklam** [comment]
👍 

Regarding `ArrayCompatible`, the code base is using that in quite a few places already. It would be a good idea for new implementation to use that.

**Comment by jpivarski** [comment]
Elsewhere, I see `type_can_asarray`:

https://github.com/numba/numba/blob/d4b18d66e7454ce7c643d382f0d1fc51b79f8959/numba/np/numpy_support.py#L667-L675

That would be convenient because it's one function call in the typing layer and `np.asarray` in the lowered layer. Is this what should be used for new functions?

**Comment by sklam** [comment]
> Is this what should be used for new functions?

Yes.

**Comment by jpivarski** [comment]
I think this has been implemented. I've `pip uninstalled vector` (which had a workaround implementation) and did

```python
>>> import numpy as np
>>> import numba as nb
>>> nb.__version__
'0.55.1'
>>> def f(a, b):
...     return np.nan_to_num(a, nan=b)
... 
>>> f(np.array([1, 2, 3, np.nan, np.nan, 10]), np.array([999, 999, 999, 123, 321, 999]))
array([  1.,   2.,   3., 123., 321.,  10.])
```

Not only that, but this is a case (`nan` is not scalar) that my workaround implementation didn't handle. So this issue should be closed, right?

My only uncertainty comes from the fact that I can't find the function when I do a GitHub search of the Numba repository.

**Comment by jpivarski** [comment]
No, I'm still wrong. There is no Numba implementation of `np.nan_to_num`. I was being fooled by my override, which was somehow still effective when the package it was in was uninstalled. The `entry_points` hook can be confusing.

**Comment by mrolinek** [comment]
Is there any activity on this?
