### ISSUE TITLE
Doc error: old reference to hsa

### ISSUE THREAD

**Issue by sklam** [numba/numba#6860]
The 
```
from numba import hsa
```
should be
```
from numba import roc
```
on this page: https://numba.pydata.org/numba-doc/latest/roc/memory.html

**Comment by rawwar** [comment]
This Issue can be closed?

**Comment by stuartarchibald** [comment]
@rawwar yes, thanks, will close it now. For future you can also close issues via direct linking from a pull request by using predefined "keywords" from [here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Example: https://github.com/numba/numba/pull/6742 has `Fixes: #6737` which means when it gets merged `#6737` gets closed.
