### ISSUE TITLE
Try command

### ISSUE THREAD

**Issue by sergiysavelyev** [numba/numba#6863]
Can 'try' command be supported by jit?

**Comment by farahhariri** [comment]
thanks for your question @sergiysavelyev . Yes there is support for `try`. The details of what syntax is supported can be found in the documentation [here](https://numba.pydata.org/numba-doc/latest/reference/pysupported.html?highlight=try#try-except)

For the future, if you have a question, Gitter or Discource are a better place to ask (in this case of a simple question Gitter is best). That way you get a faster response from the community as there are more eyes there. Issues are more adequate for bugs/feature requests/etc.
