### ISSUE TITLE
Issue with __synchronize() identifier undefined. 

### ISSUE THREAD

**Issue by Emerald233** [numba/numba#6875]
So this started out as an issue with the identifier __synchonize() undefined. After tweaking the code a little bit, I was able to fix the issue by removing #include <device_launch_parameter.h> however, this makes __global__ undefined. I am at a loss here, I searched everywhere online. I need help! thanks in advance. :)

Images https://imgur.com/a/COQe0Ef

**Comment by rawwar** [comment]
Hi @Emerald233, Thank you for raising the issue. Can you please share your `python`, `numba`, `llvmlite` version. Also, please included a self-contained code sample to reproduce the problem i.e. it's possible to run as 'python bug.py'. so that I can reproduce and debug it.

**Comment by Emerald233** [comment]
I apologize, I did post this in the wrong repository thank you for informing me, I will post in the correct repository next time. I solved the issue, visual studio will underline some identifiers as error, but the code works fine when you run it. it's a bug they are currently trying to work out.
