### ISSUE TITLE
Numba and tbb version 2021 packages incompatibility on Linux

### ISSUE THREAD

**Issue by Alexander-Makaryev** [numba/numba#6892]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am trying to use tbb package version 2021 (or greater).
When I try to create environment on Linux, I am getting:
```
conda create -n numbatbbtest numba=0.53 tbb=2021
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - numba=0.53 -> tbb[version='>=2019.5,<=2020.3']
  - tbb=2021
Use "conda info <package>" to see the dependencies for each package.
```

I tried 3.7, 3.8, 3.9 versions of Python, channels `-c numba -c conda-forge`.

At the same time I am able to create such environment on Windows and MacOS.
So it looks like a bug, could you please clarify?

**Comment by sklam** [comment]
Thank you for reporting the issue. The TBB 2021 support is added after the 0.53 release. Please use the nightly builds to try the TBB 2021 support. e.g:

```bash
$ conda create -n numbatbbtest -c numba/label/dev -c numba 'numba>0.53' tbb=2021
```

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/pull/6854 which implemented.

**Comment by gmarkall** [comment]
Can this now be closed?

**Comment by Alexander-Makaryev** [comment]
@gmarkall Yes, I think so, this can be closed. Thanks!)
