### ISSUE TITLE
Closures guaranteed to resolve are not handled well by inliner

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6896]
In consideration of the below code, you know that shorthands will resolve later down the chain, yet you will get an error if you try to run it. You do not get an error using the commented out code. It yields `Cannot capture the non-constant value associated with variable 'f' in a function that will escape.`

```
import numpy as np
import numba as nb
from numba import cuda

datum = [('a',np.float64),('b',np.float64)]
np_datum = np.dtype(datum,align=True)
nb_datum = nb.from_dtype(np_datum)

@nb.njit(nb.void(nb_datum))
def one_arg(f):
    '''
    def a():
        return f['a']
    def b():
        return f['b']
    '''
    def shorthands():
        def a():
            return f['a']
        def b():
            return f['b']
        return a,b
    a, b = shorthands()
    f['b'] += a()
```

**Comment by HPLegion** [comment]
Should it be `def shorthands(f):` in your example? You are calling it with an argument later.

**Comment by c200chromebook** [comment]
> Should it be `def shorthands(f):` in your example? You are calling it with an argument later.

Good catch, sorry, I had fixed that in a later version...

**Comment by guilhermeleobas** [comment]
Hi @c200chromebook, I couldn't execute your code without the `@njit` decorator. I got the following error in the interpreter:

```bash
$ python a.py
Traceback (most recent call last):
  File "a.py", line 26, in <module>
    one_arg(datum)
  File "a.py", line 24, in one_arg
    f['b'] += a()
TypeError: list indices must be integers or slices, not str
```

**Comment by c200chromebook** [comment]
Datum is the type - you'd have to make a real one, eg: `one_arg(np.zeros(1,dtype=np_datum))`

**Comment by gmarkall** [comment]
My understanding of the problem you describe is a combination of:

- [Numba freezes closure variables as constants:](https://numba.readthedocs.io/en/latest/reference/pysemantics.html#global-and-closure-variables) *In nopython mode, global and closure variables are frozen by Numba: a Numba-compiled function sees the value of those variables at the time the function was compiled.*
- In `one_arg`, `f` is not constant.

For example:

```python
import numpy as np
import numba as nb
from numba import cuda

datum = [('a',np.float64),('b',np.float64)]
np_datum = np.dtype(datum,align=True)
nb_datum = nb.from_dtype(np_datum)

#@nb.njit(nb.void(nb_datum))
def one_arg(f):
    '''
    def a():
        return f['a']
    def b():
        return f['b']
    '''
    def shorthands():
        def a():
            return f['a']
        def b():
            return f['b']
        return a,b
    a, b = shorthands()
    f['b'] += a()

f1 = np.zeros(1,dtype=datum)
one_arg(f1)
f2 = np.ones(1,dtype=datum)
one_arg(f2)

print(f1)
print(f2)
```

prints

```
[(0., 0.)]
[(1., 2.)]
```

demonstrating that `f` is not constant across calls of the function, nor during the execution of the function.

**Comment by gmarkall** [comment]
Closing this as this a documented limitation for the foreseeable future.
