### ISSUE TITLE
Missing conversion from StringLiteral to unicode_type

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6907]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This:
```python
from numba import typeof, types
from numba.core.typing import Context

x = types.literal('string literal')
print(x, type(x))
print("conversion:", x.can_convert_to(Context(), types.unicode_type))
```
does this:
```
Literal[str](string literal) <class 'numba.core.types.misc.StringLiteral'>
conversion: None
```
I think it should be possible to convert a `StringLiteral` to a `unicode_type` but not the converse.

A `can_convert_to()` method needs adding to this class:
https://github.com/numba/numba/blob/3461bcb76a479bffbadbef24b6662107229e2a8a/numba/core/types/misc.py#L40-L41

xref: https://numba.discourse.group/t/how-to-pass-string-argument-to-numba-njit-python-function-from-inside-another-whilst-specifying-signature-type/663 which hits this bug.

**Comment by gmarkall** [comment]
Would fixing this also fix #6897?
