### ISSUE TITLE
numba cannot resolve valid cuda driver

### ISSUE THREAD

**Issue by radiantone** [numba/numba#6909]
Ubuntu 20.10

I install nvidia-cuda-toolkit

I set NUMBA_CUDA_DRIVER to point to the driver file. 

Numba claims it is invalid file, which is not true.

ValueError: NUMBA_CUDA_DRIVER /usr/lib/x86_64-linux-gnu/libcuda.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver

**Comment by radiantone** [comment]
This turned out to be a problem with PyCharm

**Comment by stuartarchibald** [comment]
> This turned out to be a problem with PyCharm

Thanks for confirming and closing.
