### ISSUE TITLE
Inconsistent behavior of reshape between numpy and numba/cuda device array

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6930]
Consider the below code. Numpy will happily reshape using -1 to fill in any missing dimension, numba/cuda will not. Please mirror numpy behavior.
```
import numpy as np
import numba as nb
from numba import cuda
sixty_four = np.zeros(64)

blocks_of_thirty_two = sixty_four.reshape(-1,32)
nb_sixty_four = cuda.to_device(sixty_four)
nb_sixty_four.reshape(-1, 32)
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. This seems to simply be not implemented but should be relatively easy to do. A branch needs adding here (referenced below) to check for a single `-1` instance in the `newdims` and then the computation doing to work out the missing dimension and then an update to `newdims` to reflect this.
https://github.com/numba/numba/blob/12355c16ef70d10b0812c4266a3e143bd135a7f1/numba/misc/dummyarray.py#L316-L323

**Comment by laurenarnett** [comment]
I'd love to contribute to Numba and take this on as a good first issue! Found the numpy implementation of computing the missing dimension [here](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/src/multiarray/shape.c#L470-L515) and am replicating similar logic in the section of `dummyarray.py` referenced by @stuartarchibald.

**Comment by stuartarchibald** [comment]
> I'd love to contribute to Numba and take this on as a good first issue! Found the numpy implementation of computing the missing dimension [here](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/src/multiarray/shape.c#L470-L515) and am replicating similar logic in the section of `dummyarray.py` referenced by @stuartarchibald.

Great, thanks @laurenarnett !

As a new contributor, some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.
