### ISSUE TITLE
 Memory leak when returning bytes from input argument

### ISSUE THREAD

**Issue by goxeq** [numba/numba#6932]
# Bug description
I found a memory leak when I return bytes object from njitted function that I put inside as argument. It can be illustrated by example below (function `leak`).

Amount of leaked memory does not depend on the size of the bytes object (i.e. when I set `arg` to `b"a"*100000` I get the same behaviour).

The leak is also present when I return slice of the bytes object (`leak2`), but not when I only return one character (`noLeak2`). Also, the leak is not present when I don't use numba (`noLeak3`). The workaround that works for me is to return numpy array of bytes (`noLeak`)

I used numba 0.53.1, which I believe is the current version as of writing this report. The bug works on both windows and linux systems which I tested. Python version is 3.8.7.

# Minimal example
```python
#!/usr/bin/env python3
import numpy as np
from numba import njit,version_info
import psutil,os
print(version_info,end="\n\n")
pythonProcess = psutil.Process(os.getpid())
def printMem():    
    print("mem: %.2fM"%(float(pythonProcess.memory_info().rss)/1e6))


@njit
def leak(b):
    return b
@njit
def leak2(b):
    return b[0:1]
@njit
def noLeak(b):
    return np.frombuffer(b,dtype=np.uint8)
@njit
def noLeak2(b):
    return b[0]

def noLeak3(b):
    return b

arg=b"a"
for fcn in (leak,leak2,noLeak,noLeak2,noLeak3):
    print(fcn.__name__)
    for _ in range(3):
        for _ in range(100000):
            fcn(arg)
        printMem()
```

## Example output

```
version_info(major=0, minor=53, patch=1, short=(0, 53), full=(0, 53, 1), string='0.53.1', tuple=('0', '53', '1'), git_revision=None)

leak
mem: 98.61M
mem: 103.41M
mem: 108.27M
leak2
mem: 114.58M
mem: 119.44M
mem: 124.23M
noLeak
mem: 125.41M
mem: 125.41M
mem: 125.41M
noLeak2
mem: 125.59M
mem: 125.59M
mem: 125.59M
noLeak3
mem: 125.59M
mem: 125.59M
mem: 125.59M
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is fixed in https://github.com/numba/numba/pull/6937.
