### ISSUE TITLE
Undocumented behaviour in prange

### ISSUE THREAD

**Issue by skailasa** [numba/numba#6933]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

There is some undocumented behaviour in the prange statement. Consider the following code below, which is a typical hot loop for parallelisation. When the result of a computation are reduced to a slice as below, 

```python
@numba.njit(parallel=True)
def hot_loop():
    
    n=10000
    
    result = np.zeros((n*100), np.float32)
    for i in numba.prange(n):
        
        # Run computations
        res = np.random.rand(100,100) @ np.random.rand(100)
        
        # Store result
        result[i*100:(i+1)*100] += res
        
    return result
```
it is significantly slower than an allocated array,

```python
@numba.njit(parallel=True)
def hot_loop():
    
    n=10000
    
    result = np.zeros((n*100), np.float32)
    for i in numba.prange(n):
        
        # Run computations
        res = np.random.rand(100,100) @ np.random.rand(100)
        
        # Store allocated array
        result[i*100:(i+1)*100] += np.random.rand(100)
        
    return result
```

Results for my Intel I7 CPU are 74ms for the former, and 974 microseconds for the latter. There is no mention of this anywhere in the docs, or on other issues, but significantly impacts what you can really use prange for? The issue may be that prange is not fully supported to reduce to slices in this way, however, that doesn't seem to matter for the latter case - which is confusing and non-intuitive behaviour.

**Comment by skailasa** [comment]
Just a thought, is it because the compiler knows the size of the allocated array beforehand? In which case iterating through the result of a computation and reducing each component to an array should work, but I can report that this also doesn't help.

**Comment by skailasa** [comment]
Another weirder behavouir - the hot method's writing time in prange depends on the type of computation! Not just on the shape of the array it's writing, bizarre.

For example

```
@numba.njit(parallel=True)
def hot_loop():
    
    n=10000
    
    result = np.zeros((n*100), np.float32)
    for i in numba.prange(n):
        
        # Run computations
#         res = np.random.rand(100,100) @ np.random.rand(100)
        res = np.random.rand(100) @ np.random.rand(100)
        # Store result
#         result[i*100:(i+1)*100] += np.random.rand(100)
        result[i*100:(i+1)*100] += res
        
    return result
```
Also takes around 1ms on my CPU, despite 'res' containing the exact same shape/type array as a matvec in the example above...

**Comment by skailasa** [comment]
Running the following code, creating a temporary array within the loop in which to store the result of the computation, results in the same slow behaviour as the reduction from a computation above,

```python
@numba.njit(parallel=True)
def hot_loop(result):
    
    n=10000

    result = np.zeros((n*100), np.float32)

    for i in numba.prange(n):
        
        # Run computations
        res = np.random.rand(100,100) @ np.random.rand(100)
        res2 = np.empty(100)
        tmp[:] = res[:]
        result[i*100:(i+1)*100] = tmp
```

This implies that Numba is doing something along these lines for a reduction but hiding it from the user.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think what is happening is as follows...

In this case:
```python
@numba.njit(parallel=True)
def hot_loop():
    
    n=10000
    
    result = np.zeros((n*100), np.float32)
    for i in numba.prange(n):
        
        # Run computations
        res = np.random.rand(100,100) @ np.random.rand(100)
        
        # Store result
        result[i*100:(i+1)*100] += res
        
    return result
```
The variable `res` is being used after its definition (`+=res`) and so is "live" and it's expression must be executed for the result to be correct.

Whereas in this case:
```python
@numba.njit(parallel=True)
def hot_loop():
    
    n=10000
    
    result = np.zeros((n*100), np.float32)
    for i in numba.prange(n):
        
        # Run computations
        res = np.random.rand(100,100) @ np.random.rand(100)
        
        # Store allocated array
        result[i*100:(i+1)*100] += np.random.rand(100)
        
    return result
```
The variable `res` is defined but not used and so is "dead". The result of which is that the compiler removes the statement as it has no effect, the work is therefore not present and so the function runs more quickly.

This process is called [Dead Code Elimination](https://en.wikipedia.org/wiki/Dead_code_elimination) and is an optimisation technique employed by the `parallel=True` compilation target.

**Comment by skailasa** [comment]
Hi @stuartarchibald , thank you for the detailed explanation.

I tried to simplify my real codeexamples, with more complex matvecs (specifically multiple chained uses of the @ operator) where this is definitely the case, I know these are taking place as I see multiple cores being hit while running top even when `parallel=False` is set for the prange - implying that the underlying Blas matvec is being called in a multithreaded way. 

My reasoning here was that there is a massive oversubscription of threads caused by using prange on top of numpy, when one has more than one matvec. Furthermore I wrote my own single threaded matvec function, and saw a decrease in runtime, further validating this hypothesis of thread oversubscription. 

My further question for you is, as it's likely that this will be a common usecase for prange (i.e. calling numpy/blas routines which may be multithreaded over all threads invoked by prange) how does a programmer handle for this, without resorting to writing single threaded implementations of blas routines.

**Comment by stuartarchibald** [comment]
> Hi @stuartarchibald , thank you for the detailed explanation.

No problem. For future, this sort of discussion is great to have on Numba's forum: https://numba.discourse.group.

> I tried to simplify my real codeexamples, with more complex matvecs (specifically multiple chained uses of the @ operator) where this is definitely the case, I know these are taking place as I see multiple cores being hit while running top even when `parallel=False` is set for the prange - implying that the underlying Blas matvec is being called in a multithreaded way.

Chances are your BLAS is multithreaded. If you use Numba's TBB threading layer and also use MKL for your BLAS they are aware of each other and over subscription shouldn't occur. If you 

```
$ conda install tbb
```
that should get you TBB and Numba will automatically detect this and use it. Docs on the threading layers are here: https://numba.readthedocs.io/en/stable/user/threading-layer.html.

> My reasoning here was that there is a massive oversubscription of threads caused by using prange on top of numpy, when one has more than one matvec. Furthermore I wrote my own single threaded matvec function, and saw a decrease in runtime, further validating this hypothesis of thread oversubscription.
> 
> My further question for you is, as it's likely that this will be a common usecase for prange (i.e. calling numpy/blas routines which may be multithreaded over all threads invoked by prange) how does a programmer handle for this, without resorting to writing single threaded implementations of blas routines.

I think the above suggestion should fix it, if it doesn't there are environment variables that can be set to force single threaded BLAS (background info here: https://github.com/numba/numba/issues/6637#issuecomment-760460620). I'd also strongly recommend not writing BLAS routines unless you are doing research in the area simply because the existing BLAS implementations are going to be hard to beat.

**Comment by skailasa** [comment]
Hi, I will be sure to check out the forum in the future. Cheers for the link.

I tried out the env vars suggested in the other issue, and was able to use the numpy routines without over-subscription. Thanks again for helping me out with this!

**Comment by stuartarchibald** [comment]
> Hi, I will be sure to check out the forum in the future. Cheers for the link.
> 
> I tried out the env vars suggested in the other issue, and was able to use the numpy routines without over-subscription. Thanks again for helping me out with this!

No problem, glad you've got something that is working as expected.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Thanks for using Numba!
