### ISSUE TITLE
Support for array of objects / jitclasses

### ISSUE THREAD

**Issue by ghostoid** [numba/numba#6951]
For my tasks I've implemented List jitclass based on np.array, but indeed I need array of Lists and even array of arrays of Lists:
1. List, e.g., List(4) - 4 is current length
2. AOL, e.g. [List(4), List(1), List(9)]
3. AOAOL, e.g.
[
      [List(4), List(1), List(9)]
    , [List(7), List(3)]
]

Straightforward implementation of AOL should be like
```python
from numba.experimental import jitclass
from numba import njit, int32
import numba
import numpy as np

spec_List = [
    ('capacity', int32)
    ,('collection', int32[:])
    ,('p_top', int32)
]
@jitclass(spec_List)
class List:
    def __init__(self):
        pass


spec_ArrayOfLists = [
    ('capacity', int32)
    ,('l', List.class_type.instance_type[:])  # magic is here [:]
    ,('p_top', int32)
]

@jitclass(spec_ArrayOfLists)
class ArrayOfLists:
    def __init__(self):
        pass

aol = ArrayOfLists()
```

But I get an error
```
NotImplementedError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
instance.jitclass.List#271415645c8<capacity:int32,collection:array(int32, 1d, A),p_top:int32> cannot be represented as a Numpy dtype
```

Every List length may vary, every array length may vary too but basically can be predicted in case of my task, so I can consider them as const. and there is workaround: we declare jitclass with 2-dim array where last dimension have size of maximal sub-List length (9 in example) and first dimension contains total count of lists (5 in the example), and there is special table with start indexes of every AOL: [0, 3] in the example. So my array should have shape of (5, 9). But of course it's better without workarounds :)

**Comment by stuartarchibald** [comment]
Thanks for the report. Just to check the intent... the issue here is that your code would need a NumPy `ndarray` with a `dtype` which is a `typed.List`? If so, I think this would end up in NumPy as an object array and Numba has no support for arrays of arbitrary objects.

**Comment by ghostoid** [comment]
typed.List is too slow for me (about 85 ns per operation, my own List - about 1-2 ns per op).

**Comment by luk-f-a** [comment]
@ghostoid is the final content always a number (like int32 in the example above)? If so, jagged arrays provided by Awkward (https://github.com/scikit-hep/awkward-1.0) might be what you want.

**Comment by gmarkall** [comment]
For any further discussion, I'd suggest moving this over to Discourse: https://numba.discourse.group/
