### ISSUE TITLE
Caching of functions with keyword arguments

### ISSUE THREAD

**Issue by maxnoe** [numba/numba#6957]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Using keyword arguments somehow results in the cache being recreated for each process.

Using the following script:

```python
from numba import njit
import numpy as np


@njit(cache=True)
def example(x, y, eps=1e-12):
    result = x + y
    result[result < eps] = 0
    return result


if __name__ == '__main__':
    rng = np.random.default_rng(0)
    x = rng.normal(0, 0.1, 50)
    y = rng.normal(0, 0.1, len(x))
    print(example(x, y))
```

Results in this behaviour when called multiple times:

```
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
[cache] index saved to '__pycache__/fitting.example-5.py38.nbi'
[cache] data saved to '__pycache__/fitting.example-5.py38.1.nbc'
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
[cache] index saved to '__pycache__/fitting.example-5.py38.nbi'
[cache] data saved to '__pycache__/fitting.example-5.py38.2.nbc'
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
[cache] index saved to '__pycache__/fitting.example-5.py38.nbi'
[cache] data saved to '__pycache__/fitting.example-5.py38.3.nbc'
```

Observe that the cache is written each time, with an increasing number in the filename. This created problems when running a numba function on a cluster, generating multiple GB of caching data.

Removing the keyword argument solves the issue:

```
from numba import njit
import numpy as np


@njit(cache=True)
def example(x, y):
    eps = 1e-12
    result = x + y
    result[result < eps] = 0
    return result


if __name__ == '__main__':
    rng = np.random.default_rng(0)
    x = rng.normal(0, 0.1, 50)
    y = rng.normal(0, 0.1, len(x))
    print(example(x, y))

```

Observe no "saved" output on second and third run:

```
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
[cache] index saved to '__pycache__/fitting.example-5.py38.nbi'
[cache] data saved to '__pycache__/fitting.example-5.py38.1.nbc'
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
❯ NUMBA_DEBUG_CACHE=1 python fitting.py  | grep saved
```

**Comment by maxnoe** [comment]
Actually using the optional argument also solves the caching issue:

```
print(example(x, y, eps=1e-12))
```

**Comment by esc** [comment]
After some debugging, it turns out that the `Omitted` type uses the `id` (memory address) as part of it's `key` and  effectively the `id` becomes part of the `hash` -- so that means, that the hash of the argument is different on every instantiation (But only when the keyword argument is omitted, denoted by the `Omitted` type.,

The offending line is:

https://github.com/numba/numba/blob/master/numba/core/types/misc.py#L91

We (the Numba community)  discussed this today at length, and we are not sure yet what to do about it or how to fix this.

**Comment by njriasan** [comment]
> After some debugging, it turns out that the `Omitted` type uses the `id` (memory address) as part of it's `key` and effectively the `id` becomes part of the `hash` -- so that means, that the hash of the argument is different on every instantiation (But only when the keyword argument is omitted, denoted by the `Omitted` type.,
> 
> The offending line is:
> 
> https://github.com/numba/numba/blob/master/numba/core/types/misc.py#L91
> 
> We (the Numba community) discussed this today at length, and we are not sure yet what to do about it or how to fix this.

@esc could you point me to the meeting notes where this issue was discussed or expand on why `id` is necessary? I'd like to work on this issue if possible.

**Comment by gmarkall** [comment]
These are the minutes for the meeting, but there are no specific notes on this particular issue: https://github.com/numba/numba/wiki/Minutes_2021_04_27

**Comment by gmarkall** [comment]
A comment with some thoughts about the same fix for a related issue: https://github.com/numba/numba/issues/6173#issuecomment-850831761

**Comment by njriasan** [comment]
> A comment with some thoughts about the same fix for a related issue: [#6173 (comment)](https://github.com/numba/numba/issues/6173#issuecomment-850831761)

This comment (and the followup) discuss removing the `id(self._value)`, but it seems to me that just `id` should be removed. Is there a good reason we can't just use `self._value`? Rerunning your example:

```python
import numba

@numba.njit
def func(x, y=1.0, z=1):
    return x+x + y + z
print(func(2.2))

@numba.njit
def func2(x, y=1.0, z=1):
    return x+x + y + z
print(func2(2.2))

@numba.njit
def func3(x, y=2.0, z=4):
    return x+x + y + z
print(func3(2.2))

@numba.njit
def func4(x, y=2.0):
    return x+x + y
print(func4(2.2))
```
I stilll get the output:
```python
6.4
6.4
10.4
6.4
```

**Comment by stuartarchibald** [comment]
You cannot guarantee the type is hashable.
```python
import numba

@numba.njit
def func(x, y=[1, 2]):
    return x + y[0]

print(func(2.2))
```
will fail if the key contains the value.

**Comment by maxnoe** [comment]
@stuartarchibald Is this really a case for consideration? Mutable default arguments are a "nogo" in python and immutable types are hashable.

It seems strange to me to break the normal usecase (immutable, hashable default values) for something that is universally discouraged in the language.

I think it would be a very valid decision for numba to not allow unhashable default parameters.
It might be the only solution for this problem.

**Comment by esc** [comment]
> @stuartarchibald Is this really a case for consideration? Mutable default arguments are a "nogo" in python and immutable types generally are hashable.
> 
> It seems strange to me to break the normal usecase (immutable, hashable default values) for something that is universally discouraged in the language.
> 
> I think it would be a very valid decision for numba to not allow unhashable default parameters.
> It might be the only solution for this problem.

A fair point.

**Comment by stuartarchibald** [comment]
> @stuartarchibald Is this really a case for consideration? Mutable default arguments are a "nogo" in python and immutable types generally are hashable.

It was the most trivial thing to demonstrate the issue in `nopython` mode, indeed, don't use mutable default args :-)

> immutable types generally are hashable.

It might be this that needs to be enforced as a requirement to create the necessary guarantees.

I do wonder what would happen in objmode where the hash of the key might involve calling hash on an object which inherits its `__hash__` from `object` itself and so ends up calling `id`. I think this lands us back at the same problem but there's now something that can be done in user land to fix it (implement the `__hash__`).

**Comment by njriasan** [comment]
> @stuartarchibald Is this really a case for consideration? Mutable default arguments are a "nogo" in python and immutable types generally are hashable.
> 
> It seems strange to me to break the normal usecase (immutable, hashable default values) for something that is universally discouraged in the language.
> 
> I think it would be a very valid decision for numba to not allow unhashable default parameters.
> It might be the only solution for this problem.

I think we could just provide separate implementations for both situations. Something like this:

```python

class Omitted(Opaque):
    """
    An omitted function argument with a default value.
    """

    def __init__(self, value):
        self._value = value
        self._hash_value = value if hasattr(value, "__hash__") and value.__hash__ is not None else id(value)
        super(Omitted, self).__init__("omitted(default=%r)" % (value,))

    @property
    def key(self):
        return type(self._value), self._hash_value

    @property
    def value(self):
        return self._value
```



> I do wonder what would happen in objmode where the hash of the key might involve calling hash on an object which inherits its `__hash__` from `object` itself and so ends up calling `id`. I think this lands us back at the same problem but there's now something that can be done in code controlled by the user to fix it (implement the `__hash__`).

@stuartarchibald the changes I'm proposing are fairly simple and I'm happy to submit a PR. If you are worried about this use case could you provide me a example code segment that I could test this behavior on?

**Comment by njriasan** [comment]
> > @stuartarchibald Is this really a case for consideration? Mutable default arguments are a "nogo" in python and immutable types generally are hashable.
> > It seems strange to me to break the normal usecase (immutable, hashable default values) for something that is universally discouraged in the language.
> > I think it would be a very valid decision for numba to not allow unhashable default parameters.
> > It might be the only solution for this problem.
> 
> I think we could just provide separate implementations for both situations. Something like this:
> 
> ```python
> class Omitted(Opaque):
>     """
>     An omitted function argument with a default value.
>     """
> 
>     def __init__(self, value):
>         self._value = value
>         self._hash_value = value if hasattr(value, "__hash__") and value.__hash__ is not None else id(value)
>         super(Omitted, self).__init__("omitted(default=%r)" % (value,))
> 
>     @property
>     def key(self):
>         return type(self._value), self._hash_value
> 
>     @property
>     def value(self):
>         return self._value
> ```
> 
>  > I do wonder what would happen in objmode where the hash of the key might involve calling hash on an object which inherits its `__hash__` from `object` itself and so ends up calling `id`. I think this lands us back at the same problem but there's now something that can be done in code controlled by the user to fix it (implement the `__hash__`).
> 
> @stuartarchibald the changes I'm proposing are fairly simple and I'm happy to submit a PR. If you are worried about this use case could you provide me a example code segment that I could test this behavior on?

This didn't work exactly because this wasn't complete, but a `try except` with `hash` does accomplish this. I added a PR here: https://github.com/numba/numba/pull/7422. @stuartarchibald if you have an edge case you are concerned with can you suggest a test?

**Comment by stuartarchibald** [comment]
@njriasan I think something like this might trigger it, but am not sure how common or well considered practice this sort of thing is:
```python
from numba import jit
import numpy as np

class MyPropertiesClass(object):

    def __init__(self, arg):
        self.arg = arg

    # inherited object.__hash__

_default_parameters = MyPropertiesClass(100)

@jit(cache=True)
def foo(x, y=_default_parameters):
    object() # force objmode
    return x + y.arg

print(foo(10))
print(foo(20))
```

Am also wondering how this can be explained to users and if and how they can be warned about it.

**Comment by sklam** [comment]
@stuartarchibald, the `hash()` or `id()` pattern is already used in https://github.com/numba/numba/blob/e617b39a0b4b23d7b69d16f482fd66b4ac6cc307/numba/core/types/abstract.py#L427-L432.

I don't think the `def foo(x, y=_default_parameters):` is common. This is similar to the case of using mutable values as the default value. There is nothing protecting user from doing so. At best, we can put it in a best practice guide. But, there won't be an easy way to detect and check for the uesrs.
