### ISSUE TITLE
cannot import numba inside ipykernel: OSError: Could not load shared object file: llvmlite.dll

### ISSUE THREAD

**Issue by scratchmex** [numba/numba#6959]
## Reporting a bug

If you run `import numba` inside a Jupyter notebook it throws:
```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-b9db46d3506b> in <module>
----> 1 import numba
      2 print(numba.__version__)

~\miniconda3\lib\site-packages\numba\__init__.py in <module>
     17 
     18 
---> 19 from numba.core import config
     20 from numba.testing import _runtests as runtests
     21 from numba.core import types, errors

~\miniconda3\lib\site-packages\numba\core\config.py in <module>
     14 
     15 
---> 16 import llvmlite.binding as ll
     17 
     18 IS_WIN32 = sys.platform.startswith('win32')

~\miniconda3\lib\site-packages\llvmlite\binding\__init__.py in <module>
      2 Things that rely on the LLVM library
      3 """
----> 4 from .dylib import *
      5 from .executionengine import *
      6 from .initfini import *

~\miniconda3\lib\site-packages\llvmlite\binding\dylib.py in <module>
      1 from ctypes import c_void_p, c_char_p, c_bool, POINTER
      2 
----> 3 from llvmlite.binding import ffi
      4 from llvmlite.binding.common import _encode_string
      5 

~\miniconda3\lib\site-packages\llvmlite\binding\ffi.py in <module>
    189         break
    190 else:
--> 191     raise OSError("Could not load shared object file: {}".format(_lib_name))
    192 
    193 

OSError: Could not load shared object file: llvmlite.dll
```

but this doesn't happen if you run the python repl and run the import: 
```python
>>> import numba
>>> numba.__version__
'0.53.1'
```

The environment is _miniconda_ with only _numpy_ and _numba_ installed.

```text
> python -V
Python 3.9.1
```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by stuartarchibald** [comment]
Thanks for the report. Just to check, are the pythons in use on the terminal and inside jupyter exactly the same binary?

**Comment by scratchmex** [comment]
![image](https://user-images.githubusercontent.com/4014888/115879690-923f0380-a40f-11eb-91c5-e3caf3895382.png)

![image](https://user-images.githubusercontent.com/4014888/115879731-9b2fd500-a40f-11eb-933e-cdb3019950e4.png)

**Comment by ChenWuOtt** [comment]
Hello does someone have answer for this issue? I have the same problem for both numba and cupy.
I can import them from python, but cannot import them from Jupyter Lab. it gives:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <module>
----> 1 import numba 
      2 from numba import cuda as numba_cuba
      3 from pyculib.fft import fft, ifft

ModuleNotFoundError: No module named 'numba'
------------------------------------------------------------------------------

But in Windows PS: I have

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS P:\Conda_FastBfft_project> python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> numba.__version__
'0.54.1'
>>>
----------------------------------------------------------------------

**Comment by esc** [comment]
@ChenWuOtt thank you for asking about this. The error message you are seeing and the one reported in this issue are different. For your error, it is likely that `numba` and `jupyterlab` are installed in different Python environments.

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
