### ISSUE TITLE
TBB test_fork_from_non_main_thread failing intermittently

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6963]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Current HEAD 432588b of mainline is failing with:
```
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/tests/test_parallel_backend.py", line 921, in test_fork_from_non_main_thread
    self.assertIn(msg_head, err)
AssertionError: 'Attempted to fork from a non-main thread, the TBB library' not found in ''
```

CC @Hardcode84

**Comment by Hardcode84** [comment]
I saw this couple of times locally, but I never managed to find actual reason.

My theory, that something along objmode lines https://github.com/numba/numba/blob/master/numba/tests/test_parallel_backend.py#L891 sometimes cause python interpreter to create new processes, which will trigger fork check which will properly terminate TBB so next fork check will never get triggered.

**Comment by stuartarchibald** [comment]
This:
```
./runtests.py numba.tests.test_parallel_backend.TestTBBSpecificIssues.test_fork_from_non_main_thread -v
```
fails consistently on https://github.com/numba/numba/pull/6854 and HEAD of mainline (432588b). Not sure why nothing triggered it previously. 

I've also checked Numba 0.52 (uses TBB < 2021) against running the reproducing code:
https://github.com/numba/numba/blob/432588b0dc3c3bf9059f0310cb417366b9875b26/numba/tests/test_parallel_backend.py#L870-L914
and it produces the expected message.

**Comment by stuartarchibald** [comment]
@Hardcode84 your theory is correct :)

This line:
https://github.com/numba/numba/blob/432588b0dc3c3bf9059f0310cb417366b9875b26/numba/core/dispatcher.py#L734
is hit via:
```
  <path>/numba/numba/core/lowering.py(794)_lower_call_ObjModeDispatcher()
-> callee = ObjModeUtils(self.pyapi).load_dispatcher(fnty, argtypes)
  <path>/numba/numba/core/pythonapi.py(1636)load_dispatcher()
-> if serialize.is_serialiable(fnty.dispatcher):
  <path>/numba/numba/core/serialize.py(267)is_serialiable()
-> pickler.dump(obj)
  <path>/numba/numba/core/serialize.py(417)__reduce__()
-> return custom_reduce(self._reduce_class(), self._reduce_states())
  <path>/numba/numba/core/dispatcher.py(1031)_reduce_states()
-> uuid=self._uuid, func_ir=self.func_ir, flags=self.flags,
  <path>/numba/numba/core/dispatcher.py(734)_uuid()
-> u = str(uuid.uuid1())
  <pypath>/lib/python3.8/uuid.py(741)uuid1()
-> _load_system_functions()
  <pypath>/lib/python3.8/uuid.py(607)_load_system_functions()
-> lib = ctypes.CDLL(ctypes.util.find_library(libname))
  <pypath>/lib/python3.8/ctypes/util.py(324)find_library()
-> so_name = _get_soname(_findLib_prefix(name)) or name
  <pypath>/lib/python3.8/ctypes/util.py(169)_get_soname()
-> proc = subprocess.Popen((objdump, '-p', '-j', '.dynamic', f),
  <pypath>/lib/python3.8/subprocess.py(854)__init__()
-> self._execute_child(args, executable, preexec_fn, close_fds,
> <pypath>/lib/python3.8/subprocess.py(1638)_execute_child()
-> self.pid = _posixsubprocess.fork_exec()
```
note the fork at top of stack.

Result is that there's a fork completing during compilation of the function due to the objmode dispatcher being serialized and so the test is failing as suggested.
