### ISSUE TITLE
Error while import

### ISSUE THREAD

**Issue by Benji4564** [numba/numba#6974]
_Traceback (most recent call last):
  File "C:\Users\Benja\Desktop\Cuda\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Benja\Desktop\Cuda\numba\core\typeconv\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Benja\Desktop\Cuda\Main.py", line 2, in <module>
    import numba
  File "C:\Users\Benja\Desktop\Cuda\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "C:\Users\Benja\Desktop\Cuda\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\Benja\Desktop\Cuda\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\Benja\Desktop\Cuda\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\Benja\Desktop\Cuda\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\Benja\Desktop\Cuda\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Benja\Desktop\Cuda\numba\core\typeconv\__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: D:\Programme\Thonny\python.exe_

This is what I get when executing. I don't seem to be the only one  #6973

**Comment by stuartarchibald** [comment]
Thanks for the report. It looks like the above environment could be polluted in some way, the imports are coming from one path but the python in use is on another, this might be valid but could be an error. Have you tried creating an entirely new environment and installing Numba in that?

**Comment by Benji4564** [comment]
What exactly do you mean with new enviroment

**Comment by Benji4564** [comment]
What do you mean with new enviroment

**Comment by esc** [comment]
> What do you mean with new enviroment

A new virtualenvironment or conda-environment, depending on what you use.

**Comment by esc** [comment]
@Benji4564 we haven't hear back from you for a while. I will close this issue now assuming it resolved. If this is not the case, please feel free to comment with any new updates or error logs you may have encountered. Thank you!
