### ISSUE TITLE
AttributeError: 'Array' object has no attribute 'shape'

### ISSUE THREAD

**Issue by azuryl** [numba/numba#6984]
## Reporting a bug
I use @generated_jit(nopython=True)

```python
@generated_jit(nopython=True)
def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True):
    # Resize image to a 32-pixel-multiple rectangle https://github.com/ultralytics/yolov3/issues/232
    shape = img.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better test mAP)
        r = min(r, 1.0)

    # Compute padding
    ratio = r, r  # width, height ratios
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, 64), np.mod(dh, 64)  # wh padding
    elif scaleFill:  # stretch
        dw, dh = 0.0, 0.0
        new_unpad = (new_shape[1], new_shape[0])
        ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return img, ratio, (dw, dh)

```

the error

``` 
img = letterbox(img0, new_shape=self.img_size)[0]
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 439, in _compile_for_args
    raise e
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 372, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 105, in _compile_core
    impl = self._get_implementation(args, {})
  File "/home/delight-gpu/anaconda3/envs/hrnet3dpose/lib/python3.8/site-packages/numba/core/dispatcher.py", line 141, in _get_implementation
    impl = self.py_func(*args, **kws)
  File "/home/azuryl/project/3dpose/V5_dSort_Vibe/yolov5/utils/datasets.py", line 698, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'Array' object has no attribute 'shape'

```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment]
@azuryl thank you for reporting this, it seems the text is malformatted, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). For now, I will modify the submission to fixup the syntax and formatting.

**Comment by esc** [comment]
@azuryl I took a closer look at the issue you submitted. Unfortunately, the example is missing both the appropriate `import` statements and also the lines and data needed to execute the code. In order to take a closer look I would like to run the example  on my machine to reproduce the error. Would you be so kind as to update the example with appropriate `imports` and a line (or lines) that invoke the function in question, thank you!

**Comment by azuryl** [comment]
> @azuryl I took a closer look at the issue you submitted. Unfortunately, the example is missing both the appropriate `import` statements and also the lines and data needed to execute the code. In order to take a closer look I would like to run the example on my machine to reproduce the error. Would you be so kind as to update the example with appropriate `imports` and a line (or lines) that invoke the function in question, thank you!

Dear  esc
my code is from 
[https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py#L821](url)
`
import numba 
from numba import jit,geneated_jit,types

@geneated_jit(nopython=True)
def letterbox(img, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleFill=False, scaleup=True, stride=32):
    # Resize and pad image while meeting stride-multiple constraints
    shape = img.shape[:2]  # current shape [height, width]
    if isinstance(new_shape, types.int64):#**I replaced int by  types.int64**
        new_shape = (new_shape, new_shape)

    # Scale ratio (new / old)
    r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
    if not scaleup:  # only scale down, do not scale up (for better test mAP)
        r = min(r, 1.0)

    # Compute padding
    ratio = r, r  # width, height ratios
    new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
    dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
    if auto:  # minimum rectangle
        dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
    elif scaleFill:  # stretch
        dw, dh = 0.0, 0.0
        new_unpad = (new_shape[1], new_shape[0])
        ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios

    dw /= 2  # divide padding into 2 sides
    dh /= 2

    if shape[::-1] != new_unpad:  # resize
        img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
    left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
    img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
    return img, ratio, (dw, dh)`

**Comment by esc** [comment]
@azuryl thank you for updating this. From what you wrote, I am assuming you would like to try to accelerate  `letterbox` with Numba? If yes, then using `@generated_jit` probably isn't the correct function to use, but instead try to use `@njit`. However, I also see that function includes `cv` library calls that Numba will not be able to handle, so `@njit` may not work either.

It might be worth reading the 5 min guide to Numba here https://numba.readthedocs.io/en/stable/user/5minguide.html -- to get a better picture of how to use Numba and what it can do for you.

**Comment by azuryl** [comment]
Dear esc 

even I am not use opencv lib and use @njit the AttributeError: 'Array' object has no attribute 'shape'  is also occured

**Comment by esc** [comment]
> Dear esc
> 
> even I am not use opencv lib and use @njit the AttributeError: 'Array' object has no attribute 'shape' is also occured

When using `generated_jit` (https://numba.pydata.org/numba-doc/dev/user/generated-jit.html) the structure of the function is:

```
@generated_jit
def fun(ham):
    # typing context, we here have the type object for ham
    def impl(ham):
        # implementation context, we here have the concrete instance of ham
        pass
    return  impl
```

So, what you are seeing in your code is that you try to call `shape` on the type object for the array, not the actual array instance. Type  

This should not happen with `@njit` -- if it does, please do submit a code snippet to illustrate how and where this fails, thank you! (Please remember to include the import statements, the function being executed and some line or lines to call the function itself.)

Hope this helps.

**Comment by gmarkall** [comment]
Closing this as no further follow-up has been received. For further discussion / questions like this, the Discourse group is a good place to post: https://numba.discourse.group
