### ISSUE TITLE
ir not imported

### ISSUE THREAD

**Issue by reazulhoque** [numba/numba#7022]
https://github.com/numba/numba/blob/d4d09f378c471b702c5ec0f9a9f0f32a4637f6c7/numba/core/base.py#L1132 Can not find the ir module in the above file.

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this got accidentally altered in https://github.com/numba/numba/commit/05e9a67c13ca4761b6e58080a43d5622825ccbdc
