### ISSUE TITLE
Using operator module as mapping fails when compiling

### ISSUE THREAD

**Issue by sbushmanov** [numba/numba#7023]
When trying to parse an arbitrary length logic like simplified example below Python version works:

```
from operator import and_, or_
mapping = {'and_':and_, 'or_':or_}
t = (True, 'and_', False)
def f(a,b,c):
    return mapping[b](a,c)
f(*t)
#False
```
whereas compilation fails:

```
@njit
def f(a,b,c):
    mapping = {'and_':and_, 'or_':or_}
    return mapping[b](a,c)

f(*t)
----
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot get{item}() on a literal dictionary, return type cannot be statically determined
During: typing of intrinsic-call at <ipython-input-4-fa8c21a27d10> (5)

File "<ipython-input-4-fa8c21a27d10>", line 5:
def f(a,b,c):
    <source elided>
    mapping = {'and_':and_, 'or_':or_}
    return mapping[b](a,c)
    ^
```
I am not sure if this is a bug, feature request, or intended behaviour.

- [✓] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ✓] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by stuartarchibald** [comment]
Thanks for the report. What you are seeing is intended behaviour. Numba cannot work out the return type of the function as `mapping[b]` depends on the run time value of `b` and not the compile time type. Eventually this could be made to work but it's not supported at present.

If you are new to Numba and want to see if it's a good fit for your use cases, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
