### ISSUE TITLE
Can't call GUfunc with another GUfunc defined with @guvectorize

### ISSUE THREAD

**Issue by BlackBip** [numba/numba#7037]
Hello,
I am unable to call a GUfunc with another GUfunc defined with @guvectorize.
Exemple :
```Python
import numpy as np
import numba
from numba import int64, guvectorize, float64

@guvectorize(["float64[:], float64[:]"], "(i)->()", nopython=True)
def mysum(x, y):
    "Reimplement x.sum(axis=-1)"
    acc = 0
    for xi in x:
        t = np.array([0.])
        mysum2(x,t)
        acc += t[0]
    y[0] = acc

@guvectorize(["float64[:], float64[:]"], "(i)->()", nopython=True)
def mysum2(x, y):
    "Reimplement x.sum(axis=-1)"
    acc = 0
    for xi in x:
        acc += xi
    y[0] = acc


print(mysum(np.array([1.,2.,3.]), np.array([0.])))
```

This raises:
```Untyped global name 'mysum2': cannot determine Numba type of <class 'numpy.ufunc'>```

Swaping the order does not fix the issue.

Thanks

**Comment by gmarkall** [comment]
Copying the answer given in gitter:

> it's a known limitation that `guvectorize` cannot be used in other jit-compiled code. You can rewrite `mysum2` as a `@numba.jit` function. you can probably just replace the decorator on `mysum2` and it should work
