### ISSUE TITLE
```Cannot unify array(float64, 1d, C) and list(float64)<iv=None>```

### ISSUE THREAD

**Issue by alexzhang0825** [numba/numba#7038]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
```
import numpy
from numba import jit

list1 = [1.0, 2.0, 3.0, 4.0, 5.0]
list2 = [1.0, 2.0, 3.0, 4.0, 5.0]
list3 = [1.0, 2.0, 3.0, 4.0, 5.0]
list4 = [1.0, 2.0, 3.0, 4.0, 5.0]
list5 = [1.0, 2.0, 3.0, 4.0, 5.0]

@jit(nopython = True)
def test (list):
  output = []
  for i in range(len(list)):
    for j in range(len(list)):
      for k in range(len(list)):
        t_i = np.array(list[i])
        t_j = np.array(list[j])
        t_k = np.array(list[k])
        if i == j:
            e_ij = [0.0] * len(t_i)
        else:
            e_ij = (t_i - t_j)/np.linalg.norm(t_i - t_j)
        if j == k:
            e_jk = [0.0] * len(t_j)
        else:
            e_jk = (t_j - t_k)/np.linalg.norm(t_j - t_k)
        dot_p = np.dot(e_ij, e_jk)
        t_avg = (t_i + t_j + t_k) / 3
        summation = np.linalg.norm(t_i - t_avg) + np.linalg.norm(t_j - t_avg) + np.linalg.norm(t_k - t_avg)
        angle = dot_p * summation
  return output

list_of_list = [list1, list2, list3, list4, list5]
print(test(list_of_list))
```

The above code would produce the error:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float64, 1d, C) and list(float64)<iv=None> for 'e_ij.2', defined at <ipython-input-59-44235818d5ab> (27)

File "<ipython-input-59-44235818d5ab>", line 27:
def test (list):
    <source elided>
            e_jk = (t_j - t_k)/np.linalg.norm(t_j - t_k)
        dot_p = np.dot(e_ij, e_jk)
        ^

During: typing of assignment at <ipython-input-59-44235818d5ab> (27)

File "<ipython-input-59-44235818d5ab>", line 27:
def test (list):
    <source elided>
            e_jk = (t_j - t_k)/np.linalg.norm(t_j - t_k)
        dot_p = np.dot(e_ij, e_jk)
```
I ran into this when trying to compute a dot product between two numpy arrays that I believe to be of data type float64. I tried manually calculating the product by iterating through the list but the same error occurs.

**Comment by esc** [comment]
@alexzhang0825 thank you for asking about this.  There is an issue with the imports, I believe the correct line is:

```
import numpy as np
```

I believe that if you use arrays instead of lists for the zeros it will work:

```
        if i == j:
            e_ij = np.zeros(len(t_i))
        else:
            e_ij = (t_i - t_j)/np.linalg.norm(t_i - t_j)
        if j == k:
            e_jk = np.zeros(len(t_j))
        else:
            e_jk = (t_j - t_k)/np.linalg.norm(t_j - t_k)
```

However, after fixing this  you will  encounter the following error


``` 

numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot infer the type of variable 'output', have imprecise type: list(undefined)<iv=None>.

For Numba to be able to compile a list, the list must have a known and
precise type that can be inferred from the other variables. Whilst sometimes
the type of empty lists can be inferred, this is not always the case, see this
documentation for help:

https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-an-untyped-list-problem


File "issue7038.py", line 12:
def test (list):
  output = []
  ^

```


This is the result of not writing anything to the `output`  and Numba does n't know how to return an empty untyped list.
 If you append thisngs to output, it will priobably work.

**Comment by stuartarchibald** [comment]
@alexzhang0825 this documentation should help explain the problem regarding unification: https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-has-a-type-unification-problem

**Comment by alexzhang0825** [comment]
@esc apology for the sloppy test code I wrote. I was in a bit of hurry and didn't have time to verify. I tried your fix and it would now prompt me a different error
```/usr/local/lib/python3.7/dist-packages/numba/core/ir_utils.py:2031: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'list' of function 'test'.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "<ipython-input-4-6496b60b2bb4>", line 11:
@jit(nopython = True)
def test (list):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6496b60b2bb4> in <module>()
     33 
     34 list_of_list = [list1, list2, list3, list4, list5]
---> 35 test(list_of_list)

26 frames
/usr/local/lib/python3.7/dist-packages/numba/core/boxing.py in reflect_list(typ, val, c)
    748     if typ.dtype.reflected:
    749         msg = "cannot reflect element of reflected container: {}\n".format(typ)
--> 750         raise TypeError(msg)
    751 
    752     list = listobj.ListInstance(c.context, c.builder, typ, val)

TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot reflect element of reflected container: reflected list(reflected list(float64)<iv=None>)<iv=None>
```
I did a bit digging and figured that might be due to that Numba cannot take list of lists as argument. If that is the case, is there a workaround for this?

**Comment by alexzhang0825** [comment]
@stuartarchibald thanks for the information. However, I cannot quite find a connection between my case and the example provided. The example code has two possible outcomes for the function with each being a different data type than the other. For my case there is only one possible return type regardless of the input, so I'm not sure why there's an error, or am I missing something.

**Comment by stuartarchibald** [comment]
> @stuartarchibald thanks for the information. However, I cannot quite find a connection between my case and the example provided. The example code has two possible outcomes for the function with each being a different data type than the other. For my case there is only one possible return type regardless of the input, so I'm not sure why there's an error, or am I missing something.

@alexzhang0825 no problem. The types have to be unified across all branches as well as the function return type, for example:
```python
from numba import njit

@njit
def foo(n):
  if n > 0:
    a = 'a string'
  else:
    a = (1, 2, 3, 4)
  print(a) # What type is 'a' here? 

foo(10)
```
in the above, depending on the *run time* value of `n`, the variable `a` will either be a string or a tuple. However, at *compile time*, all Numba knows is that `n` is an integer, it has no idea about what the value is. As a result, it cannot compile this function as it's not possible for it to "know" what type `a` will be after the condition is executed and there's no "safe" type that `a` could "unify" into. An example of something that will unify is this:
```python
from numba import njit
import numpy as np

@njit
def foo(n):
  if n > 0:
    a = np.uint8(7)
  else:
    a = np.complex128(3 + 9j)
  print(a, type(a)) # here, 'a' is a complex128

foo(10)
```
and it does so because it's "safe" to cast a `np.uint8` to a `np.complex128`, this becomes the "unified" type of `a` such that `a` can be represented as that type for the rest of the program following the branching.

**Comment by alexzhang0825** [comment]
I see. Well thanks for the detailed explanation. As of right now I have managed to get a working solution so I will close the issue. Thanks to anyone helping me with it.
