### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by esc** [numba/numba#7039]
Following suit for cpython we should rename `master` to `main`. Probably it makes sense to do this after the next (0.54) release so as leave room to deal with any fallout.

**Comment by stuartarchibald** [comment]
Work items (feel free to edit):

 * Create branch `main` based on `master` and push to the numba org repo.
 * Set default branch from github to be `main`.
 * Provide instructions to help contributors and users make the move (need to work out common situations and cover those, custom problems can go via gitter?)
 * Update CI configurations and buildscripts (internal and public).
 * Update `gitdiff` functionality in testing.
 * Update documentation.
 * Update docstrings/internal references to URLs.
 * Anything else?!

**Comment by sklam** [comment]
Yup, make sense to do it as we tag the 0.55.0dev.

**Comment by stuartarchibald** [comment]
This is an 0.55 post release task.

**Comment by gmarkall** [comment]
Should it then be in the 0.56 milestone?

**Comment by stuartarchibald** [comment]
> Should it then be in the 0.56 milestone?

This is a good point. In the 0.55 release burn-down meeting this was discussed and it was decided to keep it in 0.55 as a reminder. As soon as the branch to `release0.55` is created the switch could be made. It was considered that putting it into 0.56 and it joining a lot of other tickets there would result in it potentially being less visible.

**Comment by esc** [comment]
I have created the local renaming PR here: https://github.com/numba/numba/pull/7804

**Comment by esc** [comment]
As we discovered in https://github.com/numba/llvmlite/issues/814 it will probably suffice to:

- [ ] create a PR with all repository changes: https://github.com/numba/numba/pull/7804
- [ ] change the default branch via GitHub UI
- [ ] merge PR with changes

GitHub will take care of changing the existing pull-requests and will issue an update message (pop-up box) on both blessed repo and also each contributors fork. So the burden on the developers is very minimal.

**Comment by esc** [comment]
This is now in porgress: `Branch master will be renamed to main shortly.`

**Comment by esc** [comment]
Ok, rename went through!

**Comment by esc** [comment]
> oh dear, it looks like Azure CI broke and sombody with appropriate permissions must log in to fix it!

works again

**Comment by esc** [comment]
#7804 was merged, closing.
