### ISSUE TITLE
Silent variable creation

### ISSUE THREAD

**Issue by AntSimi** [numba/numba#7045]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (0.53.1).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import numba as nb
import numpy as np

def enum_empty(values):
    # iterate over all values minus last one
    for i, v in enumerate(values[:-1]):
        pass
    print(i, v)

values = np.ones(1)
nb.njit(enum_empty)(values)
enum_empty(values)
```

In this example i want to get last value of `i`, but i didn't think at case when values have a size of one or less.
When you do that with only python you have an error, but with numba there is no warning/error... and you get `0` inplace

Thanks

**Comment by sklam** [comment]
This is a known deviation from python semantic. Numba is not tracking variable liveness at runtime. All variables are zero-initialized instead.

**Comment by stuartarchibald** [comment]
Will add a note to the docs https://numba.readthedocs.io/en/stable/reference/pysemantics.html
