### ISSUE TITLE
Update contribute guide to use python 3.7 instead of python 3.6

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#7048]
As of today, the [contribute guide](https://numba.pydata.org/numba-doc/dev/developer/contributing.html#build-environment) is using Python 3.6 to build the environment. Given that Numba supports Python 3.7 or newer, this must be changed in the docs.

**Comment by guilhermeleobas** [comment]
Hi @sklam, the [numba.pydata.org](https://numba.pydata.org/numba-doc/dev/index.html) page is not in sync with the [readthedocs](https://numba.readthedocs.io/en/stable/index.html) page. The former contains docs for Numba until the 0.52 release while the latter is updated.

**Comment by esc** [comment]
@guilhermeleobas I believe the correct place for  Numba documentation is: https://numba.readthedocs.io/en/stable/ -- IIRC this has changed quite recently.

**Comment by guilhermeleobas** [comment]
I'll close this issue since it is not relevant anymore
