### ISSUE TITLE
ImportError: Numba could not be imported

### ISSUE THREAD

**Issue by AniketSanjayDesai** [numba/numba#7053]
It shows the error: 'ImportError: Numba could not be imported.'
The original error was: 'DLL load failed while importing _typeconv: The operation completed successfully.'

**Comment by rawwar** [comment]
Hi @AniketSanjayDesai , can you give us more information on the issue?  probably version of python, numba, llvm would be great.

**Comment by esc** [comment]
Since we haven't heard anything for 30 days now, I am closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks!
