### ISSUE TITLE
pow() does not work in nopython mode

### ISSUE THREAD

**Issue by gdementen** [numba/numba#707]
As a followup to #167, the only issue left is that pow() does not work in nopython mode / is very slow in a loop. Shouldn't it be translated to the same thing/in the same way than the *\* operator, math.pow and np.power?

``` python
import numpy as np
from numba import jit, __version__

@jit(nopython=True)
def loop_pow(result, a):
    for i in range(len(a)):
        result[i] = pow(a[i], 2)

a = np.random.rand(10)
result = np.empty(10, dtype=np.float64)
loop_pow(result, a)
```

**Comment by AndZhig** [comment]
why does this number give out,, how to fix it?

from numba import jit

@jit #(nopython=True)
def func():
    a = pow(2,1000000)
    b = 2**1000000
    return a,b

print(func())

**(-9223372036854775808, -9223372036854775808)**

without @jit counts normally (but slowly).

Or script from here https://www.rookieslab.com/posts/fast-power-algorithm-exponentiation-by-squaring-cpp-python-implementation

from numba import jit

@jit(nopython=True)
def fast_power(base, power):
    result = 1
    while power > 0:
        if power % 2 == 0:
            power = power / 2
            base = base * base
        else:
            power = power - 1
            result = result * base
            power = power / 2
            base = base * base
    return result

print (fast_power(2, 2048))

**0**

why 0?
