### ISSUE TITLE
Native installation of Numba using pip on M1 macOS 

### ISSUE THREAD

**Issue by saleh-mir** [numba/numba#7071]
I appreciate the package and your affords. 

I understand that you can install NUmba using condo on M1 Macs. But is there a timeline on when we can do this with pip? I tried installing llvmlite with brew, but apparently you you can install only versions 11 and 12 of llvm natively on M1 Macs, and Numba requires 10 in order to compile it. 

I'm running latest version of Python 3.9 installed natively with brew. 

Thank you

**Comment by esc** [comment]
> I appreciate the package and your affords.
> 
> I understand that you can install NUmba using condo on M1 Macs. But is there a timeline on when we can do this with pip? I tried installing llvmlite with brew, but apparently you you can install only versions 11 and 12 of llvm natively on M1 Macs, and Numba requires 10 in order to compile it.

@saleh-mir thank you for asking about this. There is no concrete timeline at present, but I would estimate this functionality (install Numba/llvmlite with pip on M1 apple silicon) to become available within the next 6-12 months.

**Comment by chrisking** [comment]
Can this be reopened, if you are looking to leverage this library outside of a data science / ml notebook environment conda support is not enough.

**Comment by chrisking** [comment]
That worked perfectly! Thank you

**Comment by esc** [comment]
> That worked perfectly! Thank you

Excellent! Thank you for checking and getting back!

**Comment by dbuades** [comment]
> > That worked perfectly! Thank you
> 
> Excellent! Thank you for checking and getting back!

They worked perfectly for me too!
