### ISSUE TITLE
Implement `numpy.broadcast_to` and `numpy.broadcast_arrays`

### ISSUE THREAD

**Issue by brandonwillard** [numba/numba#7078]
NumPy's `numpy.broadcast_to` and `numpy.broadcast_arrays` are incredibly useful functions, and it would be great to have Numba implementations for them.

Currently, we have to jump into object mode when these are used in [Aesara](https://github.com/pymc-devs/aesara).  Since they're introduced in a few important and not uncommon places, and we ultimately want to generate Numba-only functions, I would like to understand the challenges, possible approach, etc., just so we can either start limiting our use of them or start implementing some workarounds in the meantime.

**Comment by sklam** [comment]
There is an internal implementation of similar logic at:
https://github.com/numba/numba/blob/6881dfe3883d1344014ea16185ed87de4b75b9a1/numba/np/arrayobj.py#L1283

**Comment by brandonwillard** [comment]
https://github.com/numba/numba/pull/7119 should close this.

**Comment by vyasr** [comment]
Also related is #3115.

**Comment by gmarkall** [comment]
@brandonwillard #7119 is now merged, but do you still need `broadcast_arrays` as well? (or can this be closed?)

**Comment by brandonwillard** [comment]
> @brandonwillard #7119 is now merged, but do you still need `broadcast_arrays` as well? (or can this be closed?)

`broadcast_arrays` should be just a minor convenience when `broadcast_to` is available, so I'll close this.  Thanks everyone!
