### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY with pinned_array

### ISSUE THREAD

**Issue by aero-108** [numba/numba#7083]
GPU: Tesla T4 16GB
GPU Driver ver: 460.73.01
Host free RAM: 600GB
CUDA ver: 11.2
Numba ver: 0.53.1

```python
import math
from numba import cuda


@cuda.jit
def test(arr):
    row = cuda.grid(1)
    if row < arr.shape[0]:
        for i in range(arr.shape[1]):
            arr[row, i] = 1.0


arr = cuda.pinned_array((50000, 50000), dtype='float64')

threadsperblock = 128
blockspergrid = math.ceil(arr.shape[0] / threadsperblock)
test[threadsperblock, blockspergrid](arr)
```

arr is 20GB.
on 'test' func call throws immediately:
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuMemAlloc results in CUDA_ERROR_OUT_OF_MEMORY

Can anyone help how to use host RAM in case if GPU ram is insufficient.

**Comment by gmarkall** [comment]
A pinned array uses non-pageable host memory, which will run out quickly depending on how much the host supports. I think you probably want to use managed memory - see [Unified Memory for CUDA Beginners](https://developer.nvidia.com/blog/unified-memory-cuda-beginners/) for a general overview, and [cuda.managed_array()](https://numba.readthedocs.io/en/latest/cuda-reference/memory.html#numba.cuda.managed_array) for the Numba API for this.

For your example to use managed memory it could look like:

```python
import math
from numba import cuda


@cuda.jit
def test(arr):
    row = cuda.grid(1)
    if row < arr.shape[0]:
        for i in range(arr.shape[1]):
            arr[row, i] = 1.0


arr = cuda.managed_array((150000, 50000), dtype='float64')

threadsperblock = 128
blockspergrid = math.ceil(arr.shape[0] / threadsperblock)
test[blockspergrid, threadsperblock](arr)
```

Note a couple of other changes:

- This use 60GB of memory (I tested with an RTX 8000 that has 48GB of RAM) - this should still be fine with your Tesla T4 16GB and 600GB of host RAM though.
- The grid and block sizes were mixed up in your reproducer - the size of the grid comes first.

For further questions / help on the usage of Numba, the Discourse forum (https://numba.discourse.group/) is a good place to post, as it has an active user community answering questions.

**Comment by gmarkall** [comment]
Closing as there has been no further feedback received.
