### ISSUE TITLE
Cuda local.array life time problems

### ISSUE THREAD

**Issue by MegaIng** [numba/numba#7090]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG). (tested on master)
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import numpy as np
import numba as nb
from numba import cuda

from numba.cuda.printimpl import print_item

Vector3 = np.dtype([
    ('x', np.float32),
    ('y', np.float32),
    ('z', np.float32)
])


def scalar(dtype, **attributes):
    res = np.rec.array(None, shape=(1,), dtype=dtype)[0]
    for n, v in attributes.items():
        setattr(res, n, v)
    return res


@cuda.jit(inline="always", device=True)
def cuda_scalar(dtype):
    return cuda.local.array((1,), dtype)[0]


cuda.local.scalar = cuda_scalar


def array(dtype, shape):
    return np.rec.array(None, shape=shape, dtype=dtype)


Vector3Numba = nb.typeof(scalar(Vector3))


@cuda.jit(Vector3Numba(nb.float32, nb.float32, nb.float32), device=True)
def vec(x, y, z):
    res = cuda.local.scalar(Vector3Numba)
    res.x = x
    res.y = y
    res.z = z
    return res


@cuda.jit(Vector3Numba(Vector3Numba, Vector3Numba), device=True)
def vec_add(a, b):
    res = cuda.local.scalar(Vector3Numba)
    res.x = a.x + b.x
    res.y = a.y + b.y
    res.z = a.z + b.z
    return res

# A Helper to easily print Records.
@print_item.register(type(Vector3Numba))
def record_print_impl(ty, context, builder, val):
    format_strings = []
    args = []
    for name, data in ty.fields.items():
        field_ty = data.type
        field_get = context.get_getattr(ty, name)
        field_val = field_get(context, builder, ty, val, name)
        field_format, field_args = print_item(field_ty, context, builder, field_val)
        format_strings.append(f"{name}={field_format}")
        args.extend(field_args)
    format_string = "(" + ", ".join(format_strings) + ")"
    return format_string, args


if __name__ == '__main__':
    @cuda.jit(debug=True)
    def test_vec(a, b, c):
        print(a)
        print(b)
        print(c)
        print(vec_add(a, b))
        print(vec_add(vec_add(a, b), c))


    av = scalar(Vector3, x=1, y=0, z=0)
    bv = scalar(Vector3, x=0, y=1, z=0)
    cv = scalar(Vector3, x=0, y=0, z=1)
    test_vec[1, 1](av, bv, cv)

```

The above code should print

```
(x=1.000000, y=0.000000, z=0.000000)
(x=0.000000, y=1.000000, z=0.000000)
(x=0.000000, y=0.000000, z=1.000000)
(x=1.000000, y=1.000000, z=0.000000)
(x=1.000000, y=1.000000, z=1.000000)
```

But it doesn't. It prints

```
(x=1.000000, y=0.000000, z=0.000000)
(x=0.000000, y=1.000000, z=0.000000)
(x=0.000000, y=0.000000, z=1.000000)
(x=1.000000, y=1.000000, z=0.000000)
(x=0.000000, y=0.000000, z=1.000000)
```

Meaning the value from `vec_add(a, b)` does not get correctly passed to the next `vec_add`. I was trying to implement vector types, but this makes it completely unusable, since the same problems occur with chained operator overloads. I am now working around this by using `NamedUniTuple`s instead of `Record`s.

**Comment by gmarkall** [comment]
I don't think this can be expected to work - once the local array is out of the scope of the function it was defined in, I wouldn't expect it to be valid.  @MegaIng If you feel the lifetime should persist beyond the function, can you explain a bit about why please?

**Comment by MegaIng** [comment]
@gmarkall Because it is the only way I found to create a Record Instance on the GPU. And also, because it would mirror the behavior on CPU. If there is another way to create an Record Type on GPU tell me (even if it would require a custom Type/DataModel)

**Comment by gmarkall** [comment]
Thanks for the quick reply!

> And also, because it would mirror the behavior on CPU.

What's the equivalent CPU code you're thinking of here?

**Comment by MegaIng** [comment]
@gmarkall The code from `def scalar`. But I do realize now that that would require some kind of dynamic memory management. I would however like a mutable Vector, which tuples (and apparently all of `StructModel`) can't provide me).

**Comment by gmarkall** [comment]
Yeah, it's unfortunate that we don't yet have any way to support a mutable user-defined struct in the CUDA target at the moment. I'd like to get to the point where we can do that, but there's a fair bit of work to do to get there.

**Comment by gmarkall** [comment]
@MegaIng is there anything unresolved here? Can we close this issue?

**Comment by MegaIng** [comment]
@gmarkall We can close this. I did find a workaround by using a bit of a hack (e.g. rewriting bytecode to transform `a.xy = c` to `a = a._replace("xy", c)` or something similar, which I can then lower using tuples for values). While I would prefer if there is a way to provided a mutable datatype on cuda, I agree that this issue is not directly that request.
