### ISSUE TITLE
numba build fails with TBB

### ISSUE THREAD

**Issue by beew** [numba/numba#7095]
Numba doesn't build with intel's TBB

python setup.py install  

produces the following:
```
Using Intel TBB from: /opt/intel/oneapi/tbb/2021.2.0/env/..
Using OpenMP from: True
running build
got version from expanded keyword {'version': '0.52.0', 'full': '18825058a6e32bb92f3941f3c8d14a818f19279f'}

... many output lines

gcc -pthread -shared build/temp.linux-x86_64-3.8/numba/cuda/cudadrv/_extras.o -o build/lib.linux-x86_64-3.8/numba/cuda/cudadrv/_extras.cpython-38-x86_64-linux-gnu.so
gcc: numba/core/typeconv/typeconv.cpp
g++ -pthread -shared build/temp.linux-x86_64-3.8/numba/_dispatcher.o build/temp.linux-x86_64-3.8/numba/_typeof.o build/temp.linux-x86_64-3.8/numba/_hashtable.o build/temp.linux-x86_64-3.8/numba/_dispatcherimpl.o build/temp.linux-x86_64-3.8/numba/core/typeconv/typeconv.o -L/home/bernard/opt/python38/lib/python3.8/site-packages/numpy/core/lib -lnpymath -lm -o build/lib.linux-x86_64-3.8/numba/_dispatcher.cpython-38-x86_64-linux-gnu.so
numba/np/ufunc/tbbpool.cpp:38:13: error: ‘task_scheduler_init’ in namespace ‘tbb’ does not name a type
   38 | static tbb::task_scheduler_init *tsi = NULL;
      |             ^~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp: In function ‘int get_thread_id()’:
numba/np/ufunc/tbbpool.cpp:78:29: error: ‘current_thread_index’ is not a member of ‘tbb::detail::d1::task_arena’
   78 |     return tbb::task_arena::current_thread_index();
      |                             ^~~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp: In function ‘void ignore_blocking_terminate_assertion(const char*, int, const char*, const char*)’:
numba/np/ufunc/tbbpool.cpp:218:10: error: ‘tbb::internal’ has not been declared
  218 |     tbb::internal::runtime_warning("Unable to wait for threads to shut down before fork(). It can break multithreading in child process\n");
      |          ^~~~~~~~
numba/np/ufunc/tbbpool.cpp: In function ‘void prepare_fork()’:
numba/np/ufunc/tbbpool.cpp:229:8: error: ‘tsi’ was not declared in this scope
  229 |     if(tsi)
      |        ^~~
numba/np/ufunc/tbbpool.cpp:234:13: error: ‘assertion_handler_type’ was not declared in this scope
  234 |             assertion_handler_type orig = tbb::set_assertion_handler(ignore_blocking_terminate_assertion);
      |             ^~~~~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp:236:18: error: ‘set_assertion_handler’ is not a member of ‘tbb’
  236 |             tbb::set_assertion_handler(orig);
      |                  ^~~~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp:236:40: error: ‘orig’ was not declared in this scope
  236 |             tbb::set_assertion_handler(orig);
      |                                        ^~~~
numba/np/ufunc/tbbpool.cpp: In function ‘void reset_after_fork()’:
numba/np/ufunc/tbbpool.cpp:254:8: error: ‘tsi’ was not declared in this scope
  254 |     if(tsi && need_reinit_after_fork)
      |        ^~~
numba/np/ufunc/tbbpool.cpp: In function ‘void unload_tbb()’:
numba/np/ufunc/tbbpool.cpp:265:8: error: ‘tsi’ was not declared in this scope
  265 |     if(tsi)
      |        ^~~
numba/np/ufunc/tbbpool.cpp:274:9: error: ‘assertion_handler_type’ was not declared in this scope
  274 |         assertion_handler_type orig = tbb::set_assertion_handler(ignore_assertion);
      |         ^~~~~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp:276:14: error: ‘set_assertion_handler’ is not a member of ‘tbb’
  276 |         tbb::set_assertion_handler(orig);
      |              ^~~~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp:276:36: error: ‘orig’ was not declared in this scope
  276 |         tbb::set_assertion_handler(orig);
      |                                    ^~~~
numba/np/ufunc/tbbpool.cpp:277:16: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
  277 |         delete tsi;
      |                ^~~
numba/np/ufunc/tbbpool.cpp: In function ‘void launch_threads(int)’:
numba/np/ufunc/tbbpool.cpp:285:8: error: ‘tsi’ was not declared in this scope
  285 |     if(tsi)
      |        ^~~
numba/np/ufunc/tbbpool.cpp:290:22: error: ‘tbb::task_scheduler_init’ has not been declared
  290 |         count = tbb::task_scheduler_init::automatic;
      |                      ^~~~~~~~~~~~~~~~~~~
numba/np/ufunc/tbbpool.cpp:292:5: error: ‘tsi’ was not declared in this scope
  292 |     tsi = new tbb::task_scheduler_init(count);
      |     ^~~
numba/np/ufunc/tbbpool.cpp:292:15: error: expected type-specifier
  292 |     tsi = new tbb::task_scheduler_init(count);

...

error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/intel/oneapi/tbb/2021.2.0/env/../include -I/home/bernard/opt/python38/include/python3.8 -c numba/np/ufunc/tbbpool.cpp -o build/temp.linux-x86_64-3.8/numba/np/ufunc/tbbpool.o -std=c++11" failed with exit status 1

```

numba 0.53.1 (also 0.52.0), python-3.8.10,  TBB from intel oneapi 2021.2.0, OS is Ubuntu 20.04

numba does build with export NUMBA_DISABLE_TBB=1

**Comment by stuartarchibald** [comment]
Thanks for the report. Numba 0.54 (which is in development at present) will be the first release with TBB 2021 support. For Numba 0.52, as per the OP, the constraint is `tbb >=2019.5,<=2020.3 `.

Hope this helps.

**Comment by celinesin** [comment]
hopping on here, as I think I have a very similar problem.

I'm trying to (re)install Numba to use tbb, preferably with pip on Ubuntu 18.04.2 LTS.

What I've tried:

1. pip3 install tbb==2020.0.133
    pip3 install numba==0.53.1
2. pip3 install tbb==2020.0.133
    git clone git://github.com/numba/numba.git
    git checkout release0.53
    python setup.py install

In the first case, i get
`__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.`

In the second case, 
`06:39:59 🤖:numba$ python3 setup.py install
TBB not found
Using OpenMP from: True`


context: I'm trying to serve a small dash app using Flask/wsgi/apache2, and it calls fit_transform() from sci-kit learn.  It runs fine locally, but when it's served, we suspect that the threading between Flask and numba is causing problems.
https://github.com/lmcinnes/umap/issues/665

**Comment by stuartarchibald** [comment]
@celinesin I think the issue you present is a variant on https://github.com/numba/numba/issues/6108, essentially, `pip` installed TBB sometimes cannot be found by Numba ([xref](https://github.com/numba/numba/issues/6108#issuecomment-675365997)) (though in the building from source case you'd also need a wheel equivalent to the conda `tbb-devel` package to get the TBB header files).

Given the context in https://github.com/lmcinnes/umap/issues/665, and that OpenMP is supported on your system, I'd try setting the threading layer to OpenMP ([docs](https://numba.readthedocs.io/en/stable/user/threading-layer.html#selecting-a-named-threading-layer)). Quickest way is via the environment variable `NUMBA_THREADING_LAYER=omp`.

**Comment by celinesin** [comment]
Thanks for the quick reply!  It seems like setting the threading layer to omp still conflicts with something.  I added the following to the beginning of my code:

```from numba import config, njit, threading_layer
# set the threading layer before any parallel target compilation
config.THREADING_LAYER = 'omp'

@njit(parallel=True)
def foo(a, b):
    return a + b

x = np.arange(10.)
y = x.copy()

# this will force the compilation of the function, select a threading layer
# and then execute in parallel
foo(x, y)
# demonstrate the threading layer chosen
print("Threading layer chosen: %s" % threading_layer())```

Run by itself (without flask) I got the expected "Threading layer chosen: omp"
But inside the flask, it doesn't work (and no error messages)


On the strategy of installing tbb, I tried both

1. pip3 install tbb-devel
pip3 install --upgrade --force-reinstall numba==0.53.1
2. pip3 install tbb-devel
git clone git://github.com/numba/numba.git
git checkout release0.53
python setup.py install

but we still don't find tbb (same return as in the previous comment)

**Comment by stuartarchibald** [comment]
> Thanks for the quick reply! It seems like setting the threading layer to omp still conflicts with something. I added the following to the beginning of my code:
> 
> ```python
> from numba import config, njit, threading_layer
> # set the threading layer before any parallel target compilation
> config.THREADING_LAYER = 'omp'
> 
> @njit(parallel=True)
> def foo(a, b):
>     return a + b
> 
> x = np.arange(10.)
> y = x.copy()
> 
> # this will force the compilation of the function, select a threading layer
> # and then execute in parallel
> foo(x, y)
> # demonstrate the threading layer chosen
> print("Threading layer chosen: %s" % threading_layer())
> ```
> 
> Run by itself (without flask) I got the expected "Threading layer chosen: omp"
> But inside the flask, it doesn't work (and no error messages)

Thanks for testing this. Could you please elaborate on the way it "doesn't work"? Also, if you would like some help via real time chat there's Numba engineers here: https://gitter.im/numba/numba

> On the strategy of installing tbb, I tried both
> 
>     1. pip3 install tbb-devel
>        pip3 install --upgrade --force-reinstall numba==0.53.1
> 
>     2. pip3 install tbb-devel
>        git clone git://github.com/numba/numba.git
>        git checkout release0.53
>        python setup.py install
> 
> 
> but we still don't find tbb (same return as in the previous comment)

Did you install both `tbb-devel` and `tbb`? Both are needed at compile time, only the latter at run time.

**Comment by celinesin** [comment]
Just for documentation, I did install both tbb / tbb-devel (although it became 2021.2.0...)
```
09:54:22 🤖:numba$ pip3 show tbb-devel
Name: tbb-devel
Version: 2021.2.0
Summary: Intel® oneAPI Threading Building Blocks (oneTBB)
Home-page: https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onetbb.html
Author: Intel Corporation
Author-email: scripting@intel.com
License: Intel Simplified Software License
Location: /usr/local/lib/python3.6/dist-packages
Requires: tbb
Required-by:
10:16:44 🤖:numba$ pip3 show tbb
Name: tbb
Version: 2021.2.0
Summary: Intel® oneAPI Threading Building Blocks (oneTBB)
Home-page: https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onetbb.html
Author: Intel Corporation
Author-email: scripting@intel.com
License: Intel Simplified Software License
Location: /usr/local/lib/python3.6/dist-packages
Requires:
Required-by: tbb-devel
```

will head over to the gitter and report back later!  Thanks for all your help!

**Comment by stuartarchibald** [comment]
> Just for documentation, I did install both tbb / tbb-devel (although it became 2021.2.0...)

For reference 2021.2.0 is not supported by any released version of Numba (issue described in OP), Numba 0.54 will support TBB 2021.

**Comment by celinesin** [comment]
Just another update:

After much help from @stuartarchibald, we've figured out a few things:
1.  i was unable to install tbb and numba together, but that wasn't needed to begin with, since I had a functioning omp.
2.  contrary to my original hypothesis, numba doesn't actually have a problem with flask, what I called "serving the app locally" was already using flask.  Therefore, the problem may lie somewhere between numba and wsgi or apache2.
3.  the problem is not fundamentally something about running JIT code, but something about Numba's runtime.  I can compile functions, but I can't execute them.

The search continues!  My next hint is: https://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html#

Thanks for all your help!

**Comment by celinesin** [comment]
And, in the end my problem was incorrect wsgi configuration... what a treasure hunt!
It works now, thanks for all the support!

**Comment by stuartarchibald** [comment]
@celinesin thanks for reporting back, glad you now have something that works!

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
