### ISSUE TITLE
Using @overload with types.Callable fails to find compiled implementation at Lowering

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#7111]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,

I was researching ways to implement classmethods for native numba types that represent python classes and found it can be done pretty easily if a type-reference type (i.e. a metaclass from which concrete types are created) is derived from `types.Callable` and low-leve API is used, but the same code fails to compile when `@overload` decorates the type-refence class (i.e. `CallableTypeRef` below). 

The issue can be reproduced with:
```
from numba import types, njit
from numba.core.typing.templates import signature
from numba.core.imputils import lower_constant
from numba.extending import (
    models,
    register_model,
    typeof_impl,
    type_callable,
    lower_builtin,
    overload,
)
from numba.core.typing.typeof import _typeof_type as numba_typeof_type


class MyClass(object):
    pass


@typeof_impl.register(type)
def mynew_typeof_type(val, c):

    print("DEBUG: sdc replaced val=", val)
    if not issubclass(val, MyClass):
        return numba_typeof_type(val, c)
    else:
        return CallableTypeRef(MyClass)


class CallableTypeRef(types.Callable):    ### this needs update from numba to use impl_key for Callables

    def __init__(self, instance_type):
        self.instance_type = instance_type
        self.impl_key = None
        super(CallableTypeRef, self).__init__('callable_type_ref[{}]'.format(self.instance_type))

    def get_call_type(self, context, args, kws):

        # >>> self == callable_type_ref[<class '__main__.MyClass'>]
        # type(self) == <class '__main__.CallableTypeRef'>
        template = context._functions[type(self)][0]  # for simplicity grab the first template
        res = template.apply(args, kws)

        # we have the signature, but also need to update the impl_key
        # that will be searched in get_function() during lowering
        if getattr(template, '_compiled_overloads', None):
            self.impl_key = template._compiled_overloads[args]
        return res

    def get_call_signatures(self):
        return (), True

    def get_impl_key(self, sig):
        return self.impl_key


@lower_constant(CallableTypeRef)
def constant_sdctyperef(context, builder, ty, pyval):
    return context.get_dummy_value()


@register_model(CallableTypeRef)
class CallableTypeModel(models.OpaqueModel):
    def __init__(self, dmm, fe_type):

        models.OpaqueModel.__init__(self, dmm, fe_type)


# first version via low-level API
# @type_callable(CallableTypeRef)
# def typing_callabletype(context):
#     def typer():
#         return types.double
#     return typer
# 
# @lower_builtin(CallableTypeRef, types.VarArg(types.Any))
# def callabletype_impl(context, builder, sig, args):
#     res = context.get_constant(types.double, 42.7)
#     return res


# second version via overloads that fails to compile
@overload(CallableTypeRef)
def callable_type_call_ovld():
    def callable_type_call_impl():
        return 42.5
 
    return callable_type_call_impl


@njit
def test_impl():
    return MyClass()


result = test_impl()
print("DEBUG: result=\n", result)

```

The compilation fails at lowering even though the typing of the overload successfully completed and a compiled function was inserted into the `self._defns` dictionary, but a different key is used in `BaseContext::get_function()` to find the compiled function:
https://github.com/numba/numba/blob/5f6859908e7b73f7e1baf30381bac9e863640210/numba/core/base.py#L544-L550

Here's the debug output from lowering, it can be seen that there are no template versions for `fn == callable_type_ref[<class '__main__.MyClass'>]` as a key, which is selected because, `fn` is neither of these: `(types.Function, types.BoundFunction, types.Dispatcher)`:

```
>>> fn
callable_type_ref[<class '__main__.MyClass'>]
>>> isinstance(fn, (types.Function, types.BoundFunction, types.Dispatcher))
False
>>>
>>> self._defns[fn].versions
[]

>>> type(fn)
<class '__main__.CallableTypeRef'>
>>> self.typing_context._functions[type(fn)]
[<OverloadTemplate_CallableTypeRef C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat\test_mindex_5_1.py:82>]
>>> self.typing_context._functions[type(fn)][0]
<OverloadTemplate_CallableTypeRef C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat\test_mindex_5_1.py:82>
>>> self.typing_context._functions[type(fn)][0]._compiled_overloads
{(): <built-in method callable_type_call_impl of _dynfunc._Closure object at 0x00000285B7F70BA8>}
```

At the same time version written via low-level API decorators works and produces:
> (NUMBA_MASTER_4) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat>python test_typeref_call.py
> DEBUG: result=
>  42.7
> 

since there's a fallback branch that retires with `type(fn)` in `get_function`:
https://github.com/numba/numba/blob/5f6859908e7b73f7e1baf30381bac9e863640210/numba/core/base.py#L556-L559

The problem can be solved with replacing derived types in the key selection logic with the `types.Callable` class itself and adding `get_impl_key `abstract method to it. I can open a PR, if you think it's a good way to solve this. This issue looks very similar to #5885, but I haven't checked proposed solution will help there or not.

Best Regards,
Alexey.

**Comment by sklam** [comment]
I haven't looked deep into the issue but if you are interested in classmethod there is https://github.com/numba/numba/pull/7050
