### ISSUE TITLE
Add chrome-tracing support in event API

### ISSUE THREAD

**Issue by sklam** [numba/numba#7123]
The abandoned PR https://github.com/numba/numba/pull/7073 added some useful debugging tools that we should consider for mainline.

Relevant changes are in: https://github.com/numba/numba/pull/7073/commits/5d0623fe12c1a8cabf8cc1494cfd615d7644a6ae https://github.com/numba/numba/pull/7073/commits/18b8c3d186b1e388bd00f19cf5aaac377fd6dddf https://github.com/numba/numba/pull/7073/commits/1b9a467ada4f1d3d8a721871c949932e970e83b2

These commits dumps a json file that chrome-based browser can load via `chrome://tracing/` (see docs at https://www.chromium.org/developers/how-tos/trace-event-profiling-tool).

It should only take some cleanup to make it a acceptable PR.

If anyone want to grab this task, please leave a note. I may not have time to work on this until later this month.

**Comment by hadia206** [comment]
Hi @sklam 
I will take this task.

**Comment by stuartarchibald** [comment]
Implemented in https://github.com/numba/numba/pull/7537, closing.
