### ISSUE TITLE
Name error - numba doesn't find a function

### ISSUE THREAD

**Issue by Hanni-ui** [numba/numba#7127]
Hi,
there is a very interesting issue. I am using compilation with signature specification, and then there is a name error, because he isn't able to find other functions. The code is like that

```
import numpy as np
import numba

@numba.jit(numba.types.int16(numba.types.int16),nopython=True)
def func1(a):
    a *= 5
    a = func2(a)
    return a

@numba.jit(numba.types.int16(numba.types.int16),nopython=True)
def func2(a):
    a *= 2
    return a

A=2
print(func(A))
```

and the error like that

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'func2' is not defined
```

Thanks for your help

**Comment by esc** [comment]
@Hanni-ui thank you for asking about this on the Numba issue tracker. If you include the signature in the `njit` decorator, you will compile the functions eagerly, i.e. at definition time, thus, `func2` must be defined before it can be used, try:

```python
import numba


@numba.jit(numba.types.int16(numba.types.int16),nopython=True)
def func2(a):
    a *= 2
    return a


@numba.jit(numba.types.int16(numba.types.int16),nopython=True)
def func1(a):
    a *= 5
    a = func2(a)
    return a


A = 2
print(func1(A))
