### ISSUE TITLE
Numbers don't add up?

### ISSUE THREAD

**Issue by HarveyYan** [numba/numba#7133]
```` 
import numpy as np
from numba import prange as parallel_range
from numba import jit

@jit(nopython=True, parallel=True)
def func():
    vector = np.zeros(2)
    for i in parallel_range(2):
        for j in range(2):
            vector[j] += 1
            vector[i] += 1
    return vector

ret = func()
print(ret)
```` 

This very simple example gives [4., 3.]... Where does that additional 1 go?

**Comment by HarveyYan** [comment]
Alright I see it's because of the race condition — multiple threads trying to write to the same slice or element in an array. Linking to an existing issue #3681

**Comment by esc** [comment]
@HarveyYan thank you for asking about this on the Numba issue tracker. I believe your analysis is correct.
