### ISSUE TITLE
NumPy 1.21 support tracker

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7176]
List of known items needed to support NumPy 1.21:

- [x] #7175
- [x] #7423

**Comment by stuartarchibald** [comment]
Fixed by the now merged https://github.com/numba/numba/pull/7483, which includes the C code changes from #7449. Closing.

**Comment by FirefoxMetzger** [comment]
Potentially stupid question: This issue is closed, but the numpy 1.20 issue (https://github.com/numba/numba/issues/6182) is still open. What does this mean for numba and support of numpy 1.20? Should we skip numpy 1.20 when using numba or should we pin numpy<1.20?

**Comment by gmarkall** [comment]
> Potentially stupid question: This issue is closed, but the numpy 1.20 issue (#6182) is still open. What does this mean for numba and support of numpy 1.20? Should we skip numpy 1.20 when using numba or should we pin numpy<1.20?

It's a good question - NumPy 1.20 and 1.21 are supported, but the final bug on the checklist for #6182 is still open and unresolved: #6864 - this is a bug affecting Numba with both NumPy 1.20 and 1.21, so the support for them is equal - but we do need to fix #6864 still.
