### ISSUE TITLE
types.NPDatetime raises AttributeError when used in types.Dict with jitclass

### ISSUE THREAD

**Issue by GEbb4** [numba/numba#7191]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When using the `jitclass` decorator, `NPDatetime` in the spec causes an `AttributeError` because a property is accessed which does not exist. 

Minimum working testcase:
```python
from numba import float64, types, typed
from numba.experimental import jitclass

@jitclass([("values", types.DictType(types.NPDatetime, float64[::1]))])
class HasDictOfDatetime(object):
    def __init__(self):
        self.values = typed.Dict.empty(types.NPDatetime, float64[::1])

if __name__ == "__main__":
    obj = HasDictOfDatetime()
```
Running this results in an error because `type object 'NPDatetime' has no attribute 'name':
```
$ python bug.py
Traceback (most recent call last):
  File "D:\dev\pysolarsail\src\pysolarsail\bug.py", line 8, in <module>
    ("values", types.DictType(types.NPDatetime, float64[::1])),
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\abstract.py", line 66, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\containers.py", line 707, in __init__
    self.keyvalue_type = Tuple([keyty, valty])
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\abstract.py", line 66, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\containers.py", line 316, in __init__
    self.dtype = UnionType(types)
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\abstract.py", line 66, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\containers.py", line 291, in __init__
    self.types = tuple(sorted(set(types), key=lambda x: x.name))
  File "D:\virtualenvs\pysail\lib\site-packages\numba\core\types\containers.py", line 291, in <lambda>
    self.types = tuple(sorted(set(types), key=lambda x: x.name))
AttributeError: type object 'NPDatetime' has no attribute 'name'
```
I tested using `0.53.1` because although `0.54` is in the changelog, I can't find it on either PyPI or as a GitHub release.

**Comment by stuartarchibald** [comment]
Thanks for the report. Whilst this is a bit obscure, the issue is that the dictionary key type in the reproducer is being declared as the raw _class_ `types.NPDatetime` opposed to a concrete instance of the class (a Numba type-system type!). Essentially, the `types.NPDatetime` needs instantiating with a unit to create a specific `datetime64` type.

Example:
```python
from numba import float64, types, typed
from numba.experimental import jitclass

key_ty = types.NPDatetime('m') # ~ dtype('<M8[m]')
value_ty = float64[::1]

@jitclass([("values", types.DictType(key_ty, value_ty))])
class HasDictOfDatetime(object):
    def __init__(self):
        self.values = typed.Dict.empty(key_ty, value_ty)

if __name__ == "__main__":
    obj = HasDictOfDatetime()
```

Unfortunately, even with this fixed, I think https://github.com/numba/numba/pull/7047 will be needed to get this to work as there's currently no `hash` support for datetime types.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!

Also, the MWR in https://github.com/numba/numba/issues/7191#issuecomment-875403189 works against [current mainline](https://github.com/numba/numba/tree/38ab89dd369a14b8826d3fa30d080aa083aed00b).
