### ISSUE TITLE
Request for supporting `np.pad` and `np.argpartition`

### ISSUE THREAD

**Issue by BenjaminChoou** [numba/numba#7198]
---

## Feature request
`np.pad` is a quite common function in NumPy.  Another unsupported function `np.argpartition` is the sister one of `np.partition` which is already supported in Numba. Please take it into consideration in future work.

**Comment by stuartarchibald** [comment]
Thanks for the request. To reduce the effort of managing many feature requests for not-yet-implemented NumPy features, there's a single meta-issue here https://github.com/numba/numba/issues/4074 that is intended to covers all requests. As `np.argpartition` and `np.pad` are listed there, am going close this as a duplicate. Thanks for the feedback.
