### ISSUE TITLE
Setting array elements in parallel after increment fails silently

### ISSUE THREAD

**Issue by lgarrison** [numba/numba#7201]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Setting all elements of an array with the `arr[:] = 1` syntax doesn't seem to work if there is a previous increment statement, *and* the function is compiled with `parallel=True`.  Here's an example:
```python
import numpy as np
import numba

@numba.njit(parallel=True)
def increment_then_set(a):
    a += 1
    a[:] = 3

x = np.ones(1)
increment_then_set(x)
print(x)  # expect 3, get 2
```

Interestingly, numba warns me that no parallel transformations were possible, so I wouldn't expect it to have done anything to the code, but it still seems to introduce the bug!

I saw there were some related-looking parallel bugs in the issue tracker that were fixed by #7171, so I tested on that branch, and it still seems to exhibit the bug (master too).

**Comment by sklam** [comment]
Thank you for reporting the issue. I can confirm that on #7171 and on master (0c499bfff)

**Comment by lgarrison** [comment]
Also fails (might just be a trivial transformation that numba is doing internally in the first example anyway):
```python
import numpy as np
import numba

@numba.njit(parallel=True)
def increment_then_set(a):
    a += 1
    for i in numba.prange(len(a)):
        a[i] = 3

x = np.ones(1)
increment_then_set(x)
print(x)  # expect 3, get 2
```
