### ISSUE TITLE
How to check whether numpy function supported in numba?

### ISSUE THREAD

**Issue by chaoming0625** [numba/numba#7207]
---

## Feature request

Does Numba support to check whether a numpy function is supported?

For example, here I has a NumPy function

```python

import numpy as np
import numba as nb

nb.issupport(np.dot)
```

**Comment by sklam** [comment]
You can find that information at https://numba.readthedocs.io/en/stable/developer/autogen_numpy_listing.html by searching for the numpy function name. You can also use the search in the doc (on the top left of the page). See this [example output](https://numba.readthedocs.io/en/stable/search.html?q=numpy.dot&check_keywords=yes&area=default#) from searching for `numpy.dot`. If it is supported, it will show up in the "Listings".

Internally, the listing pages are generated by something like this:

```python

In [1]: import numba.misc.help.inspector as inspector

In [2]: import numpy as np

In [3]: inspector.inspect_function(np.dot)    # an supported function
Out[3]:
{'numba_type': Function(<function dot at 0x7f8120372dc0>),
 'explained': '',
 'source_infos': {abc.OverloadTemplate_dot: {'kind': 'overload',
   'name': '_OverloadWrapper._build.<locals>.ol_generated',
   'sig': '(*ol_args, **ol_kwargs)',
   'filename': 'numba/core/overload_glue.py',
   'lines': (131, 180),
   'docstring': None},
  abc.OverloadTemplate_dot: {'kind': 'overload',
   'name': '_OverloadWrapper._build.<locals>.ol_generated',
   'sig': '(*ol_args, **ol_kwargs)',
   'filename': 'numba/core/overload_glue.py',
   'lines': (131, 180),
   'docstring': None}}}

In [4]: inspector.inspect_function(np.add_docstring)   # unsupported function
Out[4]: {'numba_type': None, 'explained': 'not supported', 'source_infos': {}}

```
