### ISSUE TITLE
Memory leak bugs in module init functions with PyObject_SetAttrString

### ISSUE THREAD

**Issue by Snape3058** [numba/numba#7210]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**(a static analyzer bug report)**

In file `numba/np/ufunc/omppool.cpp`, `numba/np/ufunc/tbbpool.cpp`, `numba/np/ufunc/_num_threads.c`, and `numba/np/ufunc/workqueue.c`, function `PyObject_SetAttrString` is used to add functions to the module being imported in the way shown below.

```c
PyObject_SetAttrString(m, "function_name", PyLong_FromVoidPtr(&function));
```

As the function `PyLong_FromVoidPtr` returns a new reference, it will lead to a memory leak for the `long` objects returned by `PyLong_FromVoidPtr`.

**Comment by sklam** [comment]
Good catch! Thanks for the report.

**Comment by ysheffer** [comment]
Hi, I'm new and I would like to take this issue, please. 
Basically I should replace:

```
PyObject_SetAttrString(m, "function_name", PyLong_FromVoidPtr(&function));
```
with:


```
tmp = PyLong_FromVoidPtr((void *) &function);
PyObject_SetAttrString(m, "function_name", tmp);
Py_DECREF(tmp);
```

correct?

**Comment by Snape3058** [comment]
LGTM. It seems that the function `PyObject_SetAttrString` will not steal a reference according to the CPython system library usages. 

Maybe it would be better to write this in a macro?
