### ISSUE TITLE
Working with reshape and np.matmul in Numba

### ISSUE THREAD

**Issue by timhdesilva** [numba/numba#7239]
Hi,

I have the following code that I would like to use Numba with. After much trial and error adding ``@jit(nopython=True)``, I realized Numba doesn't support ``np.matmul`` and ``.reshape``. Given this, what's the best way to adjust the function below in order to be able to use it with Numpy?

```
def smm_loop(simdata, m_data, W, perc):
    N = np.shape(simdata)[0]
    smm_objs = np.zeros((N, 1))
    for i in range(N):
        m_model = simdata[i, :].reshape(-1,1)
        if perc:
            m_diff = np.divide(m_model - m_data, m_data)
        else:
            m_diff = m_model - m_data
        val = np.matmul(np.matmul(np.transpose(m_diff), W), m_diff)
        smm_objs[i, 0] = val
    return smm_objs
```

Thanks in advance!

**Comment by esc** [comment]
@timhdesilva thank you for asking about this. Do you perhaps have an error message and perhaps some imports as well so that we can run the code? For `matmul`, maybe `dot` is a possible alternative in this case?

**Comment by gmarkall** [comment]
To add a little note: the reshape function is supported, but only the one-argument form (according to https://numba.readthedocs.io/en/latest/reference/numpysupported.html#other-methods)

**Comment by timhdesilva** [comment]
@gmarkall - thanks for pointing me to that! 

@esc - per your request, here's an example with the associated error below!

```
from numba import jit
import numpy as np

@jit(nopython = True)
def smm_loop(simdata, m_data, W, perc):
    N = np.shape(simdata)[0]
    smm_objs = np.zeros((N, 1))
    for i in range(N):
        m_model = simdata[i, :].reshape((-1,1))
        if perc:
            m_diff = np.divide(m_model - m_data, m_data)
        else:
            m_diff = m_model - m_data
        val = np.matmul(np.matmul(np.transpose(m_diff), W), m_diff)
        smm_objs[i, 0] = val
    return smm_objs


dt = np.random.rand(100,10)
m = np.random.rand(10,1)
W = np.identity(10)
perc = False

out = smm_loop(dt, m, W, perc)
```

```
Traceback (most recent call last):

  File "/Users/timdesilva/Dropbox (MIT)/Projects/202001Options/Code and Data/untitled0.py", line 24, in <module>
    out = smm_loop(dt, m, W, perc)

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')

  File "/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)

TypingError: Use of unsupported NumPy function 'numpy.matmul' or unsupported use of the function.

File "untitled0.py", line 14:
<source missing, REPL/exec in use?>

During: typing of get attribute at /Users/timdesilva/Dropbox (MIT)/Projects/202001Options/Code and Data/untitled0.py (14)
```

**Comment by esc** [comment]
@timhdesilva thank you. Note that there is also a list of missing NumPy functions here:

https://github.com/numba/numba/issues/7239

But it doesn't seem to contain `matmul`?

I think this is now feature request for a deeper implementation of `reshape` and an initial implementation of `matmul`, does that make sense?

**Comment by timhdesilva** [comment]
@esc Thanks for the response. Is there anyway for me to implement ``matmul`` in the meantime?

**Comment by esc** [comment]
> @esc Thanks for the response. Is there anyway for me to implement `matmul` in the meantime?

Yes, there is a guide here on how to implement "missing" NumPy functions in Numba:

https://numba.readthedocs.io/en/stable/extending/overloading-guide.html?highlight=guide%20to%20overloading

Hope this helps?

**Comment by timhdesilva** [comment]
@esc Thanks for sharing the guide! I'm not sure I follow the guide exactly (as I'm new to Numba), but I will do my best to figure it out. Any other suggestions welcome of course!

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
