### ISSUE TITLE
Different behavior when using `@njit` and `@cfunc` with function wrappers

### ISSUE THREAD

**Issue by leopold0favre** [numba/numba#7249]
I'm working on a project that requires using numba functions compiled with different variables, and passing them as other function arguments. It works very well with cfuncs :

```python
import numpy as np
import numba as nb
a = np.array([10], dtype=np.float32)

@nb.cfunc(nb.float32(), nopython=True)
def access_a():
    return a[0]

sig = nb.float32(
        nb.types.FunctionType(nb.float32())
      )

@nb.cfunc(sig, nopython=True)
def wrapper_cfunc(fun):
    return fun()

print(wrapper_cfunc(access_a))
# Output: 10
a[0] = 20
print(wrapper_cfunc(access_a))
# Output: 20
```

However, when passing functions as arguments to `njit`-ed wrappers, the result is not updated :

```python
a = np.array([10], dtype=np.float32)

@nb.cfunc(nb.float32(), nopython=True)
def access_a():
    return a[0]

sig = nb.float32(
        nb.types.FunctionType(nb.float32())
      )

@nb.jit(sig, nopython=True)
def wrapper_njit(fun):
    return fun()

print(wrapper_njit(access_a))
# Output: 10
a[0] = 20
print(wrapper_njit(access_a))
# Output: 10
```
I suppose this is not intended, since it doesn't replicate the vanilla python behavior. Is there an explaination to why this happens ? Maybe a workaround ? It would be great since `@njit` allows a lot more than `@cfunc` in terms of parametrization.

**Comment by esc** [comment]
@leopold0favre thank you for asking about this on the Numba issue tracker. I am curious, usually one would use `cfunc` to create callbacks.

In any case, it doesn't matter very much, since this is an issue about local/(global variables, you can see the same issue with `@njit`:

```
import numpy as np
import numba as nb

a = np.array([10], dtype=np.float32)


@nb.njit
def access_a():
    return a[0]


@nb.njit
def wrapper_njit(fun):
    return fun()


print(wrapper_njit(access_a))
# Output: 10
a[0] = 20
print(wrapper_njit(access_a))
# Output: 10
print(a[0])
# Output: 20
```

My initial guess/hunch would be that `a[0]` becomes a literal instead of an array lookup.

**Comment by esc** [comment]
@leopold0favre you can also pass in the array as an arggument, it will work like so:

```
import numpy as np
import numba as nb

a = np.array([10], dtype=np.float32)


@nb.njit
def access_a(array):
    return array[0]


@nb.njit
def wrapper_njit(fun, array):
    return fun(array)


print(wrapper_njit(access_a, a))
# Output: 10
a[0] = 20
print(wrapper_njit(access_a, a))
# Output: 20
print(a[0])
# Output: 20
```

**Comment by leopold0favre** [comment]
Thank you. The reason i'm not passing the array as argument is because i'm using functions compiled using global variables, because they might have different parameters but I need them to keep the same signature.
And that's because of this issue that i'm using `cfunc` instead of `njit`.

I don't think that there is any transformation into a literal, because this chunk of code has the "same" behavior : 
```python
import numpy as np
import numba as nb
a = np.array([0, 0, 0, 0], dtype=np.float32)

@nb.jit(nopython=True)
def return_a():
    return a

print(a, " -> ", return_a())  # Output : [0. 0. 0. 0.]  ->  [0. 0. 0. 0.]
a[1] = 1
print(a, " -> ", return_a())  # Output : [0. 0. 1. 0.]  ->  [0. 0. 0. 0.]
```

However, I have found a paragraph explaining this in the documentation : 

> In nopython mode, global and closure variables are frozen by Numba: a Numba-compiled function sees the value of those >variables at the time the function was compiled. Also, it is not possible to change their values from the function.

>Numba may or may not copy global variables referenced inside a compiled function. Small global arrays are copied for >potential compiler optimization with immutability assumption. However, large global arrays are not copied to conserve memory. >The definition of “small” and “large” may change.

I think it's nice to have the option of using `cfunc` to bypass this specificity, although it would be a plus to allow an option to also use changing globals in njit.

**Comment by antoniotejada** [comment]
I believe this is the same described in the FAQ at https://numba.pydata.org/numba-doc/latest/user/faq.html?highlight=recompile#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable

If you cannot convert the global into a function argument, it suggests calling recompile() as a workaround.
