### ISSUE TITLE
Update URL in error message to use issue templates

### ISSUE THREAD

**Issue by sklam** [numba/numba#7261]
The Github issue tracker URL in error messages should be updated to use issue templates

_Originally posted by @esc in https://github.com/numba/numba/pull/7223#discussion_r679858426_

**Comment by esc** [comment]
> Hi I am a new contributor, can I take this issue?

go right ahead, please! Welcome to Numba!

**Comment by Stark-developer01** [comment]
> > Hi I am a new contributor, can I take this issue?
> 
> go right ahead, please! Welcome to Numba!

Thank You, I will be navigating the codebase right away after forking.

**Comment by esc** [comment]
Closing as requested.
