### ISSUE TITLE
Ignore type annotations instead of crashing

### ISSUE THREAD

**Issue by LunarLanding** [numba/numba#7269]
---

## Feature request

As it is type annotations in internal functions error out compilation:
```python
import numba as nb
@nb.njit
def f(x):
    def g(x:int):
        return x
    return g(x)
f(1)
``` 
```
...
~/miniconda3/lib/python3.9/site-packages/numba/core/interpreter.py in op_MAKE_FUNCTION(self, inst, name, code, closure, annotations, kwdefaults, defaults, res)
   1685         if annotations is not None:
   1686             msg = "op_MAKE_FUNCTION with annotations is not implemented"
-> 1687             raise NotImplementedError(msg)
   1688         if kwdefaults is not None:
   1689             msg = "op_MAKE_FUNCTION with kwdefaults is not implemented"

NotImplementedError: Failed in nopython mode pipeline (step: analyzing bytecode)
op_MAKE_FUNCTION with annotations is not implemented
```
However annotations enable static analysis tools.
The situation would be improved if numba were to ignore them instead of raising an exception.
In my limited experimentation,commenting out the check seems to work.

**Comment by stuartarchibald** [comment]
Thanks for the report. I've taken a look at the interpreter code and also think that just ignoring them ought to work. I also considered whether raising a warning would be appropriate but think that to be consistent with the use of type annotations at the jit-decorated-function level, ignoring is the way to go.

**Comment by stuartarchibald** [comment]
Good first issue task is to create a patch that removes the above check and leaves a comment in its place that refers to the issue and offers an explanation for ignoring the annotations.
