### ISSUE TITLE
BUG/DOC: Missing definition in docs

### ISSUE THREAD

**Issue by skailasa** [numba/numba#7282]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

'NPM' see [place where used](https://numba.readthedocs.io/en/stable/developer/numba-runtime.html?highlight=NPM#cooperating-with-cpython) and [search results](https://numba.readthedocs.io/en/stable/search.html?q=NPM&check_keywords=yes&area=default) is never defined.

I'm reporting it as a bug, because I don't know what this is, and I imagine many users won't either.

**Comment by stuartarchibald** [comment]
Thanks for the report. `NPM` stands for ["nopython mode"](https://numba.readthedocs.io/en/stable/glossary.html#term-nopython-mode).

Good first issue task is to add the abbreviation `NPM` to the glossary https://numba.readthedocs.io/en/stable/glossary.html and redirect that to the https://numba.readthedocs.io/en/stable/glossary.html#term-nopython-mode entry. Then make references to `NPM` (I think there's 3 in total) in the docs link to the glossary definition.

**Comment by nihalshetty-boop** [comment]
Hi @stuartarchibald, I would love to work on this issue. I'm new to Open-Source so can you just help me out a bit, how do I redirect the NPM abbreviation to the nopython-mode entry?

**Comment by skailasa** [comment]
@nihalshetty-boop , I should think that a link would suffice.

**Comment by nihalshetty-boop** [comment]
Alright, can you direct me to the file where these changes have to be made?

**Comment by HPLegion** [comment]
@nihalshetty-boop I am in the mood to procrastinate on my actual work right now, so if you ping me on numba's Gitter channel I can try to give you some guidance with making a Pull Request for this.

Gitter: https://gitter.im/numba/numba

**Comment by stuartarchibald** [comment]
@nihalshetty-boop Great!

I suggest adding `NPM` as a term here (see how `loop-lifting` and `loop-jitting` refer to the same entry a few lines above if you are unsure how to do it): https://github.com/numba/numba/blame/38ab89dd369a14b8826d3fa30d080aa083aed00b/docs/source/glossary.rst#L49
and then anywhere `NPM` is written in the docs replace it with: 
```
:term:`NPM`
```
so it creates a link. This search shows the 3 places it occurs https://numba.readthedocs.io/en/stable/search.html?q=npm&check_keywords=yes&area=default.

Looks like @HPLegion can give you a hand if you get stuck, thanks @HPLegion :)

**Comment by nihalshetty-boop** [comment]
Cool, thanks a lot @stuartarchibald and @HPLegion!

**Comment by stuartarchibald** [comment]
As a new contributor, some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.

Thanks for your help!

**Comment by HPLegion** [comment]
At the risk of telling you things you already know: Python projects often use so called "Restructured Text / RST / ReST" to write documentation. I personally like to think of it as a more powerful cousin to markdown.

Here is a primer on ReST from the Sphinx project (Sphinx is often used to build the actual docs from the ReST templates): https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

And here is some info on glossary's in ReST: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html

**Comment by nihalshetty-boop** [comment]
I just found out what RST is today, so this is really helpful!
