### ISSUE TITLE
FR: initializing variable-shaped arrays; lists/arrays as arguments to array constructors and other functions

### ISSUE THREAD

**Issue by lzkelley** [numba/numba#7292]
I'm relatively new to numba, so my apologies if this is something trivial that already exists but I haven't been able to find.  I'm trying to create an array with a variable shape, but the (numba-)numpy array constructors (eg. `zeros()`, `ones()`, etc) only accept tuples, but at the same time numba doesn't support casting lists or arrays to tuples.

For example, let's say I have an input ndarray that can have any shape and dimension, and I want to create a new array with one-less entry along each dimension.

```
@numba.njit
def var_shape(data):
    ndim = data.ndim
    shape = data.shape
    new_shape = np.zeros(ndim, dtype=numba.int32)
    for ii in range(ndim):
        new_shape[ii] = shape[ii] - 1

    new_data = np.zeros(new_shape)    # this fails
    return new_data
```

The workaround I've been using is just to use only 1D arrays (i.e. of size `np.prod(shape)`), and ravel multi-dimensional indices into 1D indices.  This works, but can be quite cumbersome.

Would it be difficult to add implementations of the array constructors that accept lists/arrays?

Similarly, in trying to deal with variable-dimensional arrays, I've found a number of numba-implemented numpy functions that don't accept lists/arrays as arguments (e.g. `unravel_index()`, `ravel_multi_index()`).  Is there a systematic reason why these can only accept tuple-like arguments?

**Comment by stuartarchibald** [comment]
Thanks for the feature request.

The key thing in all of this is that Numba has to statically infer the type of every variable at compilation time. It does this by feeding the types of the arguments and a large set of "rules" based on CPython and NumPy semantics this into an iterative type inference algorithm. The result of the type inference algorithm can be see via the `inspect_types` method on the dispatcher objects, e.g.:

```python
from numba import njit
import numpy as np

@njit
def foo(x):
    y = x[0]
    z = x * y
    return z

foo(np.ones(4))
foo.inspect_types()
```

RE: "constructors" accepting tuples/arrays.

With some work I think this is possible, it's just not been implemented yet. The type of `new_shape` is obviously an array but it will have a fixed number of dimensions and the returned array would have to have the same number of dimensions, this would permit type inference to work.

As a work-around the `numba.np.unsafe.nadarray.to_fixed_tuple` routine (in the `unsafe` module for a reason, there's no safety net) can be used.

```python
from numba import njit
from numba.np.unsafe.ndarray import to_fixed_tuple
import numpy as np

@njit
def var_shape(data):
    ndim = data.ndim
    shape = data.shape
    new_shape = np.zeros(ndim, dtype='int32')
    for ii in range(ndim):
        new_shape[ii] = shape[ii] - 1

    new_shape_tuple = to_fixed_tuple(new_shape, ndim)

    new_data = np.zeros(new_shape_tuple)
    return new_data


d = np.ones((2, 3, 5))
ret = var_shape(d)
print(ret.shape)
```
Hope this helps for now?

RE: Would it be difficult to add implementations of the array constructors that accept lists?

I think it would be impossible in all but the literal-list case. As lists are dynamic in size, it's generally not possible at compilation time to statically infer any information in relation to their size for use in functions such as array constructors. Example:

```python
@njit
def foo(x):
    if len(x) > 2:
        x.append(3)
    new_arr = np.zeros(x) # What size is x? this determines the shape of new_arr

foo([1,])
```
the probably quite rare constant-size list could potentially work though, but it's of limited use as a `tuple` already works in this case of prescribing a constant literal valued container.
```python
@njit
def foo():
    const_list = [1, 2, 3]
    # could potentially force `const_list` to be immutable at this point
    new_arr = np.zeros(const_list)
```

RE:
> Similarly, in trying to deal with variable-dimensional arrays, I've found a number of numba-implemented numpy functions that don't accept lists/arrays as arguments (e.g. unravel_index(), ravel_multi_index()). Is there a systematic reason why these can only accept tuple-like arguments?

Would suggest the same reasons as above. Arrays are potentially possible but haven't been implemented, dynamicaly sized containers are likely impossible.

**Comment by lzkelley** [comment]
Thanks @stuartarchibald that's super helpful (both for understanding the situation, and for the `to_fixed_tuple` trick).  I'm still confused about *why* it's problematic to have a dynamic size (or dimension) if the type (e.g. `int`) was clearly defined, but I'll try to learn more about how numba works to understand better.  It sounds like this is at least unfeasible, so I'll close the issue.  Thanks again.

**Comment by stuartarchibald** [comment]
@lzkelley no problem, I'm afraid I made an error in working out whether this was possible generally, I'm afraid it's not, and I've updated my original explanation to cover this. Apologies for any confusion caused.
