### ISSUE TITLE
cannot unify operator.lt and operator.gt

### ISSUE THREAD

**Issue by scottbecker** [numba/numba#7297]
It looks like you can't have a variable that could be either of two functions with identical signatures (operator.lt and operator.gt)

```
import operator
from numba import njit

@njit
def foo(a):
        
        if a==1:
            comparison = operator.gt
        else:
            comparison = operator.lt
        
        comparison(1.9,2.4)    

@njit
def main():
    foo(1)

main()
```

causes exception

```
Cannot unify Function(<built-in function gt>) and Function(<built-in function lt>) for 'comparison.2', defined at /mnt/c/projects/numba_test/jitclass_func_references.py (20)
```

**Comment by scottbecker** [comment]
Here is a workaround for anyone else hitting this issue - use a helper function.

```
import operator
from numba import njit

@njit
def foo(a):
        
    if a==1:
        bar(operator.gt)
    else:
        bar(operator.lt)

@njit
def bar(comparison):
   comparison(1.9,2.4)    

@njit
def main():
    foo(1)

main()

```

**Comment by sklam** [comment]
This is a known limitation. Depending of the usage, functions are not always treated as first-class. In other words, functions cannot always be passed as normal values. The workaround allow `bar()` to be specialized to the comparison function.
