### ISSUE TITLE
A case of improving the "Segmentation fault" error

### ISSUE THREAD

**Issue by Slasher111** [numba/numba#7322]
Although I can't show the code here, I thought it could be useful to share my experience of eliminating the "Segmentation fault" error. It occured during the loop in the `@njit`-decorated function with `parallel=True` , and it seemed to be impossible to fight with. But adding faulthandler and keyword `debug=True` magically helped:
``` python
import faulthandler

faulthandler.enable(all_threads = True)

@njit(debug=True, parallel=True)
```
Memory consumption increased (exactly as it should have been, according to the documentation), but the error disappeared :)

**Comment by gmarkall** [comment]
I suspect this masks the symptom rather than the underlying cause. If you run with:

```python
@njit(boundscheck=True)
```

do you get any errors?

**Comment by Slasher111** [comment]
No, I don't get any errors with `boundscheck=True`. Moreover, in this case computation ends successfully even without `debug=True`. So, I have 3 cases:
1. `@njit(parallel=True)`  - computation fails with segmentation fault error
2. `@njit(boundscheck=True, parallel=True)`  - computation ends succesfully, no errors raised
3.  `@njit(debug=True, parallel=True)`  - computation ends succesfully, no errors raised. Turns out, it works even without `faulthandler`.

Thanks for the tip with `boundscheck=True`! It is not slower and is less memory consumptive than my workaround with `debug=True` :)

**Comment by gmarkall** [comment]
Neither of `boundscheck=True` or `debug=True` are really fixes - a couple more questions:

- Are you using `prange`? If so, is it possible there's a cross-iteration dependency in the code?
- Are you using any typed containers? (e.g. list, dicts, sets)?
- Does your code allocate any memory in the jitted function (e.g. with `np.emtpy`, np.zeros`, etc.)?

**Comment by Slasher111** [comment]
2 -  Yes, I'm using a numpy structured array. I suppose that's not good :)
1 - Yes, I'm using `prange` (as far as I know, there is no sense in using `parallel=True` in a loops without `prange`). But my loop looks like this:
```python
dataset = numpy_structured_array

@njit(parallel=True)
def my_function(array_to_write_results):
   for i in prange(dataset.size):
      row = dataset[i]
      var1 = row.Value1
      var2 = row.Value2
      etc
      #a lot of computations and comparisons and one `while` loop
      array_to_write_results[i] = result
return(array_to_write_results)
```
I mean there is nothing in the jitted function except this loop with `prange`. I supposed this was sufficient for a safe parallelization. Am I wrong?

3 -  No, there is no memory allocation in the jitted function.

**Comment by gmarkall** [comment]
Thanks for the replies and extra detail:

1. Thanks for sharing the code. The other use of `parallel=True` is with array expressions, which can be automatically parallelised.
2. That should work, but if it doesn't then it's a bug.
3. OK.

**Comment by esc** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
