### ISSUE TITLE
Issue with caching in Jupyterlab

### ISSUE THREAD

**Issue by sahil1105** [numba/numba#7325]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'. --> Attaching an NB since that's where the issue is.

Having an issue with `cache=True` when used in a Jupyter Notebook. It works fine in a regular IPython shell or in python scripts.

Attaching a NB since that's where the issue is visible (it wouldn't let me upload a ipynb file, so I renamed it to a txt file; to use it you can download it and rename it as ipynb):

[numba-cache-reproducer.txt](https://github.com/numba/numba/files/7023363/numba-cache-reproducer.txt)

This is a screenshot:

<img width="1256" alt="Screen Shot 2021-08-20 at 1 54 19 PM" src="https://user-images.githubusercontent.com/14302941/130275522-778783fa-09dc-4ff5-923f-bb240d5c8c4d.png">

This is on numba=0.53.1. I noticed that 0.54 has been tagged, but I couldn't find it on conda-forge at the time of creating the issue.

Also attaching the output of `numba -s`:
[numba-s-out.txt](https://github.com/numba/numba/files/7023378/numba-s-out.txt)

I played around a little, and the following diff did _seem_ to fix it (i.e. it doesn't throw an error anymore):
[numba-nb-potential-fix-diff.txt](https://github.com/numba/numba/files/7023379/numba-nb-potential-fix-diff.txt)
but I'm not really sure if it's the right way to do it or if it works in general.

**Comment by stuartarchibald** [comment]
Thanks for the report. This is reproducible and seemingly present only in the 6 series of `ipykernel`.

**Comment by ylieder** [comment]
Furthermore, setting the environment variable `NUMBA_CACHE_DIR` seems not to solve the issue.
