### ISSUE TITLE
Possible misnomer in cuda.local.array memory documentation

### ISSUE THREAD

**Issue by sgbaird** [numba/numba#7328]
Under [Numba Docs: Memory Management](https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html?highlight=cuda.local.array#numba.cuda.local.array), for [`numba.cuda.local.array()`](https://numba.pydata.org/numba-doc/latest/cuda/memory.html#local-memory) it states:
> ### Local Memory
> Local memory is an area of memory private to each thread. Using local
> memory helps allocate some scratchpad area when scalar local variables
> are not enough. The memory is allocated once for the duration of the
> kernel, unlike traditional dynamic memory management.
> 
> __numba.cuda.local.array(shape, type)__
>
> Allocate a local array of the
> given shape and type on the device. shape is either an integer or a
> tuple of integers representing the array’s dimensions and must be a
> simple constant expression. type is a Numba type of the elements
> needing to be stored in the array. The array is private to the current
> thread. An array-like object is returned which can be read and written
> to like any standard array (e.g. through indexing).

It was pointed out that in the comments that use of the term "allocation" in this context may be a misnomer: https://stackoverflow.com/questions/68869806/how-is-performance-affected-by-using-numba-cuda-local-array-compared-with-numb

Should I submit a PR for the docs? Suggestions for what to say?

From the [NVIDIA CUDA docs on memory access](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-memory-accesses):

> ### Local Memory
> Local memory accesses only occur for some automatic variables as mentioned in Variable Memory Space Specifiers. Automatic variables that the compiler is likely to place in local memory are:
> 
> Arrays for which it cannot determine that they are indexed with constant quantities,
> Large structures or arrays that would consume too much register space,
> Any variable if the kernel uses more registers than available (this is also known as register spilling).
> Inspection of the PTX assembly code (obtained by compiling with the -ptx or-keep option) will tell if a variable has been placed in local memory during the first compilation phases as it will be declared using the .local mnemonic and accessed using the ld.local and st.local mnemonics. Even if it has not, subsequent compilation phases might still decide otherwise though if they find it consumes too much register space for the targeted architecture: Inspection of the cubin object using cuobjdump will tell if this is the case. Also, the compiler reports total local memory usage per kernel (lmem) when compiling with the --ptxas-options=-v option. Note that some mathematical functions have implementation paths that might access local memory.
> 
> The local memory space resides in device memory, so local memory accesses have the same high latency and low bandwidth as global memory accesses and are subject to the same requirements for memory coalescing as described in Device Memory Accesses. Local memory is however organized such that consecutive 32-bit words are accessed by consecutive thread IDs. Accesses are therefore fully coalesced as long as all threads in a warp access the same relative address (e.g., same index in an array variable, same member in a structure variable).
> 
> On some devices of compute capability 3.x local memory accesses are always cached in L1 and L2 in the same way as global memory accesses (see Compute Capability 3.x).
> 
> On devices of compute capability 5.x and 6.x, local memory accesses are always cached in L2 in the same way as global memory accesses (see Compute Capability 5.x and Compute Capability 6.x).

**Comment by stuartarchibald** [comment]
More discussion is in https://github.com/numba/numba/pull/7329, suggest closing this ticket once that is merged.

**Comment by gmarkall** [comment]
I've updated #7329 so that it will close this issue when merged.
