### ISSUE TITLE
Create new release for current master to so i could use numpy==1.21.2

### ISSUE THREAD

**Issue by chenvsy** [numba/numba#7334]
---

## Feature request

Latest numpy is 1.21.2, preventing me to use numba with it, due to latests release (0.54.0) has maximum supported version for numpy lower than that version

**Comment by gmarkall** [comment]
NumPy 1.21 is not supported by Numba yet. https://github.com/numba/numba/issues/7176 tracks the status of support for NumPy 1.21.
