### ISSUE TITLE
TypingError: Failed in nopython mode pipeline (step: nopython frontend) Unknown attribute 'File' of type Module(<module 'laspy.file' from 'C:\\Program Files\\Anaconda3\\envs\\geofabrics3\\lib\\site-packages\\laspy\\file.py'>)

### ISSUE THREAD

**Issue by Martin20494** [numba/numba#7351]
Hi team,

I am trying to speed up the code below using @njit but I have the error as above. The file I downloaded from https://portal.opentopography.org/datasets.

Could you please help me with some advices?

    import numpy as np
    import laspy as lp
    
    @njit
    def read_las_file(filename, scale=True):
         # Writing las/las file into arrays
         inFile = lp.file.File(filename, mode='r')

         # Converting points (with x, y, z coordinates values) into rows of an array
         if scale:
               coordinates = np.vstack((inFile.x, inFile.y, inFile.z)).transpose()
         else:
               coordinates = np.vstack((inFile.X, inFile.Y, inFile.Z)).transpose()
         return inFile, coordinates

then run
      
    inFile, coordinates = read_las_file(<filename>, False)

And this is the error:

   ---------------------------------------------------------------------------
   TypingError                               Traceback (most recent call last)
   <timed exec> in <module>
    C:\Program Files\Anaconda3\envs\geofabrics3\lib\site-packages\numba\core\dispatcher.py in 
    _compile_for_args(self, *args, **kws)
    418                 e.patch_message(msg)
    419 
     --> 420             error_rewrite(e, 'typing')
    421         except errors.UnsupportedError as e:
    422             # Something unsupported is present in the user code, add help info
    C:\Program Files\Anaconda3\envs\geofabrics3\lib\site-packages\numba\core\dispatcher.py in 
    error_rewrite(e, issue_type)
    359                 raise e
    360             else:
    --> 361                 raise e.with_traceback(None)
    362 
    363         argtypes = []
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Unknown attribute 'File' of type Module(<module 'laspy.file' from 'C:\\Program 
    Files\\Anaconda3\\envs\\geofabrics3\\lib\\site-packages\\laspy\\file.py'>)
    File "<ipython-input-19-d66f002631e2>", line 19:
    def read_las_file(filename, scale=True):
    <source elided>
    # Writing las/las file into arrays
    inFile = lp.file.File(filename, mode='r')
    ^
    During: typing of get attribute at <ipython-input-19-d66f002631e2> (19)
    File "<ipython-input-19-d66f002631e2>", line 19:
    def read_las_file(filename, scale=True):
    <source elided>
    # Writing las/las file into arrays
    inFile = lp.file.File(filename, mode='r')
    ^

**Comment by esc** [comment]
@Martin20494 thank you for asking about this. Numba does not support compiling code from `laspy` -- so the line:

```
     inFile = lp.file.File(filename, mode='r')
```

Is not permissible in functions decorated with `@njit`. Hope that helps.  

PS: you can read more about what Numba supports here: https://numba.readthedocs.io/en/stable/reference/pysupported.html
