### ISSUE TITLE
Sandbox numba

### ISSUE THREAD

**Issue by rspadim** [numba/numba#7352]
Could be possible to sandbox a python code with numba and restrict functions objects and variable it could access?

**Comment by esc** [comment]
@rspadim thank you for asking about this. Please supply more information about the use-case and what exactly you expect to happen, thank you.

**Comment by gmarkall** [comment]
In general this is going to be extremely difficult / impossible to do and get correct, see e.g. https://stackoverflow.com/questions/3068139/how-can-i-sandbox-python-in-pure-python

I think the answer to this is that it's not possible to do, and isn't an intended use case of Numba.
