### ISSUE TITLE
Debug output for LLVM loop-vectorize needs an LLVM build with assertions

### ISSUE THREAD

**Issue by rhjmoore** [numba/numba#7358]
I see comments suggesting adding this to understand how loops are being handled by numba, and in the their own FAQ (https://numba.pydata.org/numba-doc/latest/user/faq.html)

    from llvmlite import binding as llvm
    llvm.set_option('','--debug-only=loop-vectorize')

You would then create your njit function and run it, and I believe the idea is that it prints debug information about whether (and why) the loop might be vectorized.

    @njit
    def test(a):
        for i in range(a.shape[0]):
            a[i] = a[i] * 2

    print(test(np.asarray([1.0, 2.0, 3.0])

I find that this code changes nothing - there is no additional debug output from llvm indicating whether a loop is being vectorized / enhanced with SSE instructions, or if not why not.

I’ve tried this on Windows, Linux and Mac, all using Anaconda distributions of Python 3.8 and with the conda, conda-forge and numba channels.

numba version 0.53.1
llvmlite version 0.36.0

**Comment by stuartarchibald** [comment]
Thanks for the report. As this is a question on discourse already I've answered it there and will close the ticket: https://numba.discourse.group/t/loop-vectorize-debug/879 should this end up as being a bug we can reopen this. Thanks again!

**Comment by stuartarchibald** [comment]
See https://numba.discourse.group/t/loop-vectorize-debug/879/5, issue title is updated to reflect the problem. Essentially, LLVM needs to be built with assertions enabled for LLVM passes debug output to work. The builds of llvmlite in the Numba channel are linked against an LLVM with assertions enabled (hence output appears), builds of llvmlite in the Anaconda distribution and conda-forge channels are linked against an LLVM without assertions enabled (hence output does not appear).

Issue is reopened as a documentation fix is needed to contain a summary of the above.
