### ISSUE TITLE
Variable name uniqueness issue in inlining (introduced in Numba 0.54)

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#7365]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

`mk_unique_var` was removed from the line below in Numba 0.54. This is causing variable name conflict issues in Bodo due to heavy use of inlining. Reproducer is not easy to provide but possible if necessary (doesn't seem necessary to me at the moment). What was the reason for removing `mk_unique_var`?

https://github.com/numba/numba/blob/7f72315f0bf672729b5a6eaf004aa9061e8bf0f5/numba/core/inline_closurecall.py#L398

**Comment by gmarkall** [comment]
It was removed in this PR: https://github.com/numba/numba/pull/7031

**Comment by gmarkall** [comment]
> Reproducer is not easy to provide but possible if necessary (doesn't seem necessary to me at the moment). 

Can you provide some more detail about the conditions that cause the problem please?

**Comment by ehsantn** [comment]
Variable names of the inlined function clash with the caller.

**Comment by stuartarchibald** [comment]
@ehsantn thanks for reporting this. I think it'd be good to have a reproducer so it's possible to see what is going wrong and from there work out the best way to fix it. A reproducer would also be used as part of the unit tests for any proposed fix with view of preventing similar issues in future. Thanks.

IIRC `mk_unique_var` was removed in favour of using the `scope.redefine` to handle https://github.com/numba/numba/issues/6969#issuecomment-840909275.

**Comment by JSKenyon** [comment]
```python
import numpy as np
from numba import jit, generated_jit, prange

my_jit = jit(cache=True, nogil=True, nopython=True, inline="always")


def factory():

    def impl(col):
        for i in range(col.size):
            col[i] *= 2
        
    return my_jit(impl)


@generated_jit(cache=True, nogil=True, nopython=True, parallel=True)
def outer(a):

    inner = factory()

    def impl(a):
        for i in prange(a.shape[0]):
            inner(a[i])

    return impl


if __name__ == "__main__":

    a = np.arange(100).reshape(10,10)
    outer(a)
```
I am not sure if this is identical, @ehsantn. Is the problem in your case also related to `prange`? I am also running into issues.

**Comment by JSKenyon** [comment]
The traceback for the above is:
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    outer(a)
  File "/venvs/nbenv/lib/python3.8/site-packages/numba/core/dispatcher.py", line 485, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/venvs/nbenv/lib/python3.8/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.UnsupportedRewriteError: Failed in nopython mode pipeline (step: convert to parfors)
Overwrite of parallel loop index

File "test.py", line 10:
    def impl(col):
        for i in range(col.size):
        ^
```

**Comment by stuartarchibald** [comment]
Is this a MWR (based on the above)?
```python
import numpy as np
from numba import njit, prange

@njit(inline="always")
def bar(x):
    for i in range(x.size):
        x[i] += 1

@njit(parallel=True)
def foo(a):
    for i in prange(a.shape[0]):
        bar(a[i])

a = np.ones((10, 10))
foo(a)
```
if so, I think the issue is that the inliner renames the variable `i` in the `bar` function as a version of `i` and adds it to the scope. Then in parfors, the failure comes from here:
https://github.com/numba/numba/blob/7f72315f0bf672729b5a6eaf004aa9061e8bf0f5/numba/parfors/parfor.py#L2673-L2684
where the scope is checked and if it is in the scope the unversioned name is returned and this collides with the unversioned induction var name.

Since #7031, in the inliner uses `scope.redefine` to create a variable with a versioned name and put it in scope, whereas previously the `mk_unique_var` was creating a variable with a similarly versioned name but does not put it into the scope.

I think the code ends up looking a bit like:
```python
import numpy as np
from numba import njit, prange

@njit(parallel=True)
def foo(a):
    for i in prange(a.shape[0]):
        for i in range(a.shape[1]):
            a[i] += 1

a = np.ones((10, 10))
foo(a)
print(a)

```
which is valid and fails the same way under parfors.

**Comment by JSKenyon** [comment]
Thanks for simplifying @stuartarchibald - I threw together that example in a hurry. I am not surprised that that is the source of the error - it is consistent with what I imagined.

Is this to be considered a bug, it is it a user error? I ask because ensuring uniqueness of variable names in complicated code could be challenging.

**Comment by stuartarchibald** [comment]
> Thanks for simplifying @stuartarchibald - I threw together that example in a hurry. I am not surprised that that is the source of the error - it is consistent with what I imagined.

No problem.

> Is this to be considered a bug, it is it a user error?

It's a bug, but one of those bugs where a decision will have to be made about where to fix it. Parfors should probably just handle this use case, but that is easier said than done. CC @DrTodd13 what do you think?

> I ask because ensuring uniqueness of variable names in complicated code could be challenging.

@JSKenyon What's the reason for setting `inline='always'` in your code? Obviously it should "just work" but if you can get away without using it that'd be a work around for this case. Also, it's entirely unreasonable for Numba to expect users to implement a version of SSA (a bit like unique naming) in their code to ensure "uniqueness" of variables, Numba needs to fix this!!

@ehsantn I'm not convinced that the above is the same as the problem you are seeing?

**Comment by JSKenyon** [comment]
> @ehsantn I'm not convinced that the above is the same as the problem you are seeing?

Apologies if I derailed the issue!

> @JSKenyon What's the reason for setting `inline='always'` in your code? Obviously it should "just work" but if you can get away without using it that'd be a work around for this case. Also, it's entirely unreasonable for Numba to expect users to implement a version of SSA (a bit like unique naming) in their code to ensure "uniqueness" of variables, Numba needs to fix this!!

It is not a roadblock for me at present. The `inline='always'` was there because in my real code this is about 7 loop levels deep and I wanted to be sure that the function call was elided. This may be an error on my part - I would be lying if I said I perfectly understood the if and when's of inlining.

**Comment by stuartarchibald** [comment]
> > @ehsantn I'm not convinced that the above is the same as the problem you are seeing?
> 
> Apologies if I derailed the issue!

Not at all, thanks for reporting it, I'm fairly sure it's a related problem, but just perhaps not exactly the one @ehsantn can see. I've opened https://github.com/numba/numba/issues/7380 for more discussion.

> > @JSKenyon What's the reason for setting `inline='always'` in your code? Obviously it should "just work" but if you can get away without using it that'd be a work around for this case. Also, it's entirely unreasonable for Numba to expect users to implement a version of SSA (a bit like unique naming) in their code to ensure "uniqueness" of variables, Numba needs to fix this!!
> 
> It is not a roadblock for me at present. The `inline='always'` was there because in my real code this is about 7 loop levels deep and I wanted to be sure that the function call was elided. This may be an error on my part - I would be lying if I said I perfectly understood the if and when's of inlining.

I see, there's a reasonable chance that LLVM would inline it anyway. There's some notes on what the Numba inliner does (and what LLVM does) here: https://numba.readthedocs.io/en/stable/developer/inlining.html#notes-on-inlining. Feel free to post on https://numba.discourse.group/ if you've any questions about it. Thanks!

**Comment by ehsantn** [comment]
@stuartarchibald your reproducer captures the issue well. I just tried it and adding `mk_unique_var` fixes the issue. The problem is name conflicts during inlining. Bodo has a lot of IR nodes inlined in various ways in several transformations in general.

Just adding an extra `mk_unique_var` in this line doesn't seem to hurt anything. Is the intention to break existing code so everyone is forced to use the `Scope` object properly because it is super critical now?
