### ISSUE TITLE
Compilation Time Increases ~40% with Numba 0.54

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7390]
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello, I am engineer at Bodo and we recently upgraded our Numba version to 0.54. Upon doing so, we noticed significant compilation time increases, including our testing suite taking much longer to run. As a benchmark we ran the whole suite of TPCH queries and noticed that with our 2021.8.1 dev release (using Numba 0.54), compilation took ~565 seconds. However, with our previous release, 2021.8 (using Numba 0.53) this suite of tests only took ~340 seconds to compile.

Unfortunately I don't have a reproducer that can be run purely in Numba, but I've attached a subset of the queries and I've included instructions to install each Bodo version (which can be run with Numba installed from source). On this subset of queries, the Numba 0.54 build took ~200 seconds and Numba 0.53 build took ~112 seconds.

To install Bodo:

```bash
# Install 2021.8
conda create -n BodoNumba53 python
conda activate BodoNumba53
# Build Numba 0.53.0 from source (instructions not included)
conda install bodo=2021.8 -c bodo.ai -c conda-forge
```

```bash
# Install 2021.8.1
conda create -n BodoNumba54 python
conda activate BodoNumba54
# Build Numba 0.54.0 from source (instructions not included)
conda install bodo=2021.8.1 -c bodo.ai/label/dev -c conda-forge
```

To run the example:
```python
python tpch_sample.py --folder sample-data
```
[bodo_example.zip](https://github.com/numba/numba/files/7133056/bodo_example.zip)

**Comment by njriasan** [comment]
I will be investigating various PRs added from Numba 0.53 to Numba 0.54 to gauge their impact on compilation time with this benchmark. If anyone has any suggestions on which PRs to explore I would highly appreciate it. Thanks!

**Comment by sklam** [comment]
@njriasan, I am guessing the overload glue PRs, e.g. https://github.com/numba/numba/pull/6762, https://github.com/numba/numba/pull/6961, https://github.com/numba/numba/pull/7049, etc) will have the biggest impact if Bodo is compiling a lot of small functions.

**Comment by njriasan** [comment]
> @njriasan, I am guessing the overload glue PRs, e.g. #6762, #6961, #7049, etc will have the biggest impact if Bodo is compiling a lot of small functions.

Thanks @sklam I took a look at these PRs and I tested reverting the overload glue. It seemed to have an impact on the full suite (~30 seconds), although timings can vary. One thing I've noticed is that the code seems to spend much longer in `with_lifting` than previously, despite no code moving to objmode. From my timing this went from ~3 seconds -> ~33 seconds. Any ideas?

**Comment by sklam** [comment]
hm... `with_lifting`, i'll take a look into it. Can you give me the specifics on how to measure the `~3 seconds -> ~33 seconds`? Like which commits you are comparing and what test

**Comment by njriasan** [comment]
> hm... `with_lifting`, i'll take a look into it. Can you give me the specifics on how to measure the `~3 seconds -> ~33 seconds`? Like which commits you are comparing and what test

So to measure compilation time I'm using a Numba branch I have that tracks where time is actually being executed in recursive compilation. https://github.com/njriasan/numba/tree/nick/stack_timers. I will get a dev version available that's compatible with Bodo 2021.8 and 2021.8.1 and create separate branches for Numba 0.53 and Numba 0.54.

Once this is finished I'll update this issue and include instructions on how to set this up.

>  Like which commits you are comparing and what test

I got these numbers from running my full suite of TPCH queries (22 in total), which I can provide. On this subset of 4 queries I still see ~(3-4) seconds, which still seems too large.

**Comment by stuartarchibald** [comment]
@njriasan can the issue with `with_lifting` be reproduced outside of the Bodo code base?

**Comment by ehsantn** [comment]
Why is reproducing outside Bodo necessary? From Numba point of view, Bodo just adds a few compiler passes which are mostly after `with_lifting`. The IR and compiler pipeline are visible. Unfortunately, it's hard to reproduce complex enough examples to reproduce these issues outside Bodo.

**Comment by njriasan** [comment]
> @njriasan can the issue with `with_lifting` be reproduced outside of the Bodo code base?

If you have a suite of relevant large examples, I'm happy to explore them in pure Numba. However as @ehsantn said it would be very difficult for me to construct an example in pure Numba. We don't have any large examples that can be run purely in Numba.

**Comment by njriasan** [comment]
> > hm... `with_lifting`, i'll take a look into it. Can you give me the specifics on how to measure the `~3 seconds -> ~33 seconds`? Like which commits you are comparing and what test
> 
> So to measure compilation time I'm using a Numba branch I have that tracks where time is actually being executed in recursive compilation. https://github.com/njriasan/numba/tree/nick/stack_timers. I will get a dev version available that's compatible with Bodo 2021.8 and 2021.8.1 and create separate branches for Numba 0.53 and Numba 0.54.
> 
> Once this is finished I'll update this issue and include instructions on how to set this up.
> 

I've finished uploading and testing builds for both Numba 0.53 and Numba 0.54. Here are installation instructions

Numba 0.53:
```shell
# Create a conda env
conda create -n BodoNumba53 python
conda activate BodoNumba53
# Install Bodo with Timers
conda install bodo=2021.8.0timers -c bodo.ai/label/dev -c conda-forge
# Install compilers to build Numba from source 
# Linux:
conda install 'gcc_linux-64>=9' 'gxx_linux-64>=9' -c conda-forge
# MacOS:
conda install clang_osx-64 clangxx_osx-64 -c conda-forge
# Uninstall the version of Numba included in the Bodo installation
conda uninstall numba --force
# Build Numba from source
# https://github.com/njriasan/numba/tree/nick/stack_timers_numba53
```

Numba 0.54:
```shell
# Create a conda env
conda create -n BodoNumba54 python
conda activate BodoNumba54
# Install Bodo with Timers
conda install bodo=2021.8.1timers -c bodo.ai/label/dev -c conda-forge
# Install compilers to build Numba from source 
# Linux:
conda install 'gcc_linux-64>=9' 'gxx_linux-64>=9' -c conda-forge
# MacOS:
conda install clang_osx-64 clangxx_osx-64 -c conda-forge
# Uninstall the version of Numba included in the Bodo installation
conda uninstall numba --force
# Build Numba from source
# https://github.com/njriasan/numba/tree/nick/stack_timers_numba54
```

**Comment by njriasan** [comment]
In addition I've simplified the reproducers to two queries showing different issues. `parfor_increase.py` is the most expensive query and parfor pass is the most relevant stage. It increases by ~20 seconds in parfor pass alone between version. `with_lifting_increase.py` Is a smaller increase (only ~20%), but it shows with lifting nearly tripling in time (from ~1 -> ~2.8 seconds) and in general shows overhead increasing in most stages.

You can run any of these files with `python <PYFILE> --folder sample-data`. The result will print the total time and a breakdown of each stage using my timers. If any part of this is unclear, I'd be happy to hop on a call or move a more detailed conversation to gitter.

[bodo_example.zip](https://github.com/numba/numba/files/7145153/bodo_example.zip)

**Comment by sklam** [comment]
I am finding with `cProfile` that `ir_utils.py:1536(build_definitions)` and `ir.py:313(_rec_list_vars)` is running more often in 0.54.0

**Comment by sklam** [comment]
Here's some example of extra compilation in 0.54:

```
Counter({'dead_branch_prune [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'nopython_supported_feature_validation [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'native_lowering [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'nopython_supported_feature_validation [create_binary_op_overload.<locals>.overload_series_binary_op.<locals>.impl]': 43,
         'native_lowering [create_binary_op_overload.<locals>.overload_series_binary_op.<locals>.impl]': 43,
         'translate_bytecode [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'fixup_args [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'ir_processing [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'with_lifting [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         ...
```

**Comment by sklam** [comment]
@njriasan

The extra `overload_get_array_if_series_or_index` compilation is happening under `bodo_series_pass`. In the images below, all `overload_get_array_if_series_or_index` compiler pass execution is colored (not greyed out).

0.53:
![0.53](https://user-images.githubusercontent.com/1929845/133480776-35544430-f35a-468b-8840-17e1ac3a10bd.png)

0.54:
![0.54](https://user-images.githubusercontent.com/1929845/133480771-ed375893-f7ea-45f8-beb7-08e77191ee81.png)

In 0.53, there are no compilation of `overload_get_array_if_series_or_index` and there are far fewer compilation.

(This data is gathered from `parfor_increase.py`)

**Comment by njriasan** [comment]
@sklam Thank you so much! This is extremely helpful. I will use this information to investigate further within Bodo. Could you provide instructions on how you constructed the `Counter ` and Chrome trace information so that I can replicate these results?

I also wanted to share the numbers from my timer method for q19 in case it can provide any additional information. We do see a large difference in series pass, but I was wondering if you also observed the increases in these other passes as well.

Numba 0.53:
```python
Total Execution time (s):  0.8410214659525082
Total Time (compilation + execution) :  91.65739727020264
('parfor_pass', 31.029525841000012)
('native_lowering', 21.47861191799966)
('bodo_series_pass', 15.351761850999958)
('bodo_distributed_pass', 13.214189389999945)
('bodo_untyped_pass', 2.2996811240000143)
('nopython_type_inference', 1.6870447590001243)
('nopython_rewrites', 1.2671201979999953)
('generic_rewrites', 0.7097297370000462)
('ir_legalization', 0.48280118499998537)
('with_lifting', 0.44029588400000375)
('translate_bytecode', 0.3876253470000126)
('reconstruct_ssa', 0.3173415589999822)
('object_mode_back_end', 0.30824496700000026)
('bodo_type_inference', 0.3028662159999751)
('inline_closure_likes', 0.27792388400001133)
('nopython_backend', 0.22969883800003377)
('inline_overloads', 0.16718759699996966)
('strip_phis', 0.13382222700005109)
('annotate_types', 0.13066375299996036)
('pre_parfor_pass', 0.07900614699999053)
('ir_processing', 0.07563272500003038)
('extract_bytecode', 0.03806389000000632)
('dead_branch_prune', 0.030411100000021563)
('inline_inlinables', 0.019057120000055328)
('rewrite_semantic_constants', 0.011980929000055873)
('find_literally', 0.010688315000050963)
('make_function_op_code_to_jit_function', 0.003478625999998819)
('literal_unroll', 0.0031012770000540257)
('dump_parfor_diagnostics', 0.002313894000008254)
('fixup_args', 0.0009144899999853351)
('canonicalize_loop_entry', 0.0003276440000004044)
('canonicalize_loop_exit', 0.0002465489999998738)
('object_mode_front_end', 6.218800000112878e-05)
('bodo_dump_diagnostics_pass', 3.661899999229945e-05)
```

Numba 0.54:
```python
Total Execution time (s):  0.41128942399518564
Total Time (compilation + execution) :  151.06338906288147
('parfor_pass', 52.92214442899997)
('native_lowering', 28.04369702199987)
('bodo_distributed_pass', 27.251238342999784)
('bodo_series_pass', 27.16622854500007)
('nopython_type_inference', 3.272438191999915)
('nopython_rewrites', 2.4022493040000867)
('bodo_untyped_pass', 2.3593873479999825)
('ir_legalization', 1.5455559790000803)
('generic_rewrites', 1.3215699029999906)
('translate_bytecode', 0.6650102849999868)
('inline_closure_likes', 0.6098217000000368)
('bodo_type_inference', 0.43325666700001175)
('reconstruct_ssa', 0.4122600060000394)
('with_lifting', 0.4025203610000725)
('object_mode_back_end', 0.33093803400000077)
('inline_overloads', 0.2748806939999868)
('annotate_types', 0.18842557899999157)
('strip_phis', 0.1824076709999467)
('pre_parfor_pass', 0.1194804579999964)
('ir_processing', 0.11711764199992025)
('dead_branch_prune', 0.047103572999954046)
('extract_bytecode', 0.04630535000003455)
('nopython_supported_feature_validation', 0.03043051200012048)
('inline_inlinables', 0.02649282600004277)
('rewrite_semantic_constants', 0.017162548000023925)
('find_literally', 0.015436225000025061)
('nopython_backend', 0.01511169499996079)
('make_function_op_code_to_jit_function', 0.005100341000045638)
('literal_unroll', 0.004403586000044868)
('dump_parfor_diagnostics', 0.00292966700000985)
('fixup_args', 0.0013143080000048712)
('canonicalize_loop_entry', 0.0003241600000016831)
('canonicalize_loop_exit', 0.00020935999999771582)
('object_mode_front_end', 5.750299999895958e-05)
('bodo_dump_diagnostics_pass', 3.927799998137971e-05)
```

**Comment by sklam** [comment]
I added the chrome event trace on top of your stacktimer branch. The patch is in https://gist.github.com/sklam/a049c859202df87f2b555dada2b31f07. With the patch, each run will generate a `perf.json`. You can read it with:

```python
import json
def check_json(filename):
    with open(filename) as fin:
        d = json.load(fin)

    pns = [rec["name"] for rec in d if rec["ph"] == "B"]
    # pprint(pns)
    ctr = Counter()
    for k in pns:
        ctr[k] += 1

    return ctr
```

for example:

```python
>>> before = check_json("bodo053_perf.json")
>>> after = check_json("bodo054_perf.json")
>>> d = after - before
>>> pprint(d)
Counter({'dead_branch_prune [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'nopython_supported_feature_validation [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'native_lowering [overload_get_array_if_series_or_index.<locals>.<lambda>]': 70,
         'nopython_supported_feature_validation [create_binary_op_overload.<locals>.overload_series_binary_op.<locals>.impl]': 43,
         'native_lowering [create_binary_op_overload.<locals>.overload_series_binary_op.<locals>.impl]': 43,
         'translate_bytecode [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'fixup_args [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'ir_processing [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
         'with_lifting [overload_get_array_if_series_or_index.<locals>.<lambda>]': 35,
```

**Comment by njriasan** [comment]
Thank you @sklam! I will use this information to continue the investigation.

I also wanted to inform you that one of our engineers found a bug in my stack timer code where it wasn't properly handling exceptions and thus was incorrectly tracking the amount of time spent in certain passes (such as `with_lifting`). I have updated those branches and reran the example.


Numba 0.53:

```python
Total Execution time (s):  1.4417204950004816
Total Time (compilation + execution) :  107.03707194328308
('parfor_pass', 34.42634949199999)
('native_lowering', 28.090192700000017)
('bodo_series_pass', 17.272455585000046)
('bodo_distributed_pass', 16.10360421999983)
('bodo_type_inference', 2.2662342680000203)
('nopython_type_inference', 1.638927806999952)
('nopython_rewrites', 1.4205396470000506)
('translate_bytecode', 0.7174187379999908)
('ir_legalization', 0.5287197569999851)
('reconstruct_ssa', 0.45428237800006155)
('generic_rewrites', 0.40123405000004153)
('object_mode_back_end', 0.38869873400000277)
('inline_closure_likes', 0.27775072099999054)
('inline_overloads', 0.2648940699999658)
('bodo_untyped_pass', 0.19984542399999716)
('strip_phis', 0.19380119500005044)
('annotate_types', 0.1610410759999592)
('nopython_backend', 0.15329947599995153)
('with_lifting', 0.1260051700000182)
('pre_parfor_pass', 0.11802548200001173)
('ir_processing', 0.10172064299998906)
('dead_branch_prune', 0.04183400700005091)
('extract_bytecode', 0.03843901800000049)
('inline_inlinables', 0.02557012200002573)
('rewrite_semantic_constants', 0.01600766200003445)
('find_literally', 0.014975576999997298)
('make_function_op_code_to_jit_function', 0.004992687999993972)
('literal_unroll', 0.004636798999969383)
('dump_parfor_diagnostics', 0.002790185999990147)
('fixup_args', 0.0012225720000111906)
('canonicalize_loop_entry', 0.00034200999999622894)
('canonicalize_loop_exit', 0.000282665000001181)
('object_mode_front_end', 8.200600000218827e-05)
('bodo_dump_diagnostics_pass', 5.6394999994324735e-05)
```

Numba 0.54:
```python
Total Execution time (s):  1.1321604090044275
Total Time (compilation + execution) :  163.2104036808014
('parfor_pass', 54.87726784599997)
('native_lowering', 35.563759737999995)
('bodo_distributed_pass', 28.75432694699992)
('bodo_series_pass', 28.16547812700017)
('nopython_type_inference', 3.297235068999974)
('nopython_rewrites', 2.3003080479999816)
('bodo_type_inference', 2.1614064979999887)
('ir_legalization', 1.7352933719999584)
('generic_rewrites', 0.9008159440001089)
('translate_bytecode', 0.6971451540000575)
('object_mode_back_end', 0.6776436869999936)
('reconstruct_ssa', 0.5521256849997642)
('inline_closure_likes', 0.4568376090000279)
('inline_overloads', 0.3772020190000296)
('strip_phis', 0.2509862210000624)
('annotate_types', 0.23121956799998422)
('pre_parfor_pass', 0.196688556999975)
('ir_processing', 0.14909273800001088)
('bodo_untyped_pass', 0.12990868700000568)
('dead_branch_prune', 0.0646931089999696)
('extract_bytecode', 0.05065552800000317)
('with_lifting', 0.04004197199994053)
('nopython_supported_feature_validation', 0.03793517799999169)
('inline_inlinables', 0.03391374800000513)
('rewrite_semantic_constants', 0.021252780000026394)
('find_literally', 0.01933112500007006)
('nopython_backend', 0.017038347999995818)
('make_function_op_code_to_jit_function', 0.007188762000039706)
('literal_unroll', 0.006289827999997222)
('dump_parfor_diagnostics', 0.0031043940000081705)
('fixup_args', 0.0017922119999678188)
('canonicalize_loop_entry', 0.0005926919999952318)
('canonicalize_loop_exit', 0.00048485099999950876)
('object_mode_front_end', 0.00013525299999805895)
('bodo_dump_diagnostics_pass', 5.221299998048323e-05)
```

Based on this information I'm inclined to believe this extra compilation is most likely the source of our issue. Thank you for your help.

**Comment by njriasan** [comment]
Just wanted to give you an update. While we haven't fully resolved this issue, we believe the extra compilation is the result of our inlining step getting a cache miss. Now that compiler flags are part of the `cache_key`, at least some of this extra compilation comes from extra misses from mismatching values for `no_cpython_wrapper` (set to true by overload).

This comes at least partially from a call to `inline_closure_call`, so while I don't believe this is a Numba issue, I wanted to share this information in case it impacts other Numba code paths.

**Comment by njriasan** [comment]
We confirmed the only Numba related issue we were seeing was the caching change. I'm closing this issue. Thank you so much for all of your help.

**Comment by esc** [comment]
@njriasan thank you for following up and closing this issue.
