### ISSUE TITLE
Can Python3.6 use for numba?

### ISSUE THREAD

**Issue by siqi-zZ** [numba/numba#7391]
Hi, I used python3.6 install numba(pip3 install numba==0.48.0), 
```
Requirement already satisfied: numba==0.48.0 in /anaconda2/envs/flask/lib/python3.6/site-packages (0.48.0)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (0.31.0)
Requirement already satisfied: setuptools in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (49.2.0.post20200714)
Requirement already satisfied: numpy>=1.15 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (1.19.1)

```
but when I try 
`import numba`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/__init__.py", line 29, in <module>
    import numba.core.types as types
AttributeError: module 'numba' has no attribute 'core'

Is numba can't use in python3.6?

**Comment by esc** [comment]
> Hi, I used python3.6 install numba(pip3 install numba==0.48.0),
> 
> ```
> Requirement already satisfied: numba==0.48.0 in /anaconda2/envs/flask/lib/python3.6/site-packages (0.48.0)
> Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (0.31.0)
> Requirement already satisfied: setuptools in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (49.2.0.post20200714)
> Requirement already satisfied: numpy>=1.15 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.48.0) (1.19.1)
> ```
> 
> but when I try
> `import numba`
> Traceback (most recent call last):
> File "", line 1, in
> File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/**init**.py", line 29, in
> import numba.core.types as types
> AttributeError: module 'numba' has no attribute 'core'
> 
> Is numba can't use in python3.6?

Python 3.6 is indeed supported. The issue here is that you need to setup a new virtual environment and install a fresh version of Numba. Latest is 0.54.0.

**Comment by siqi-zZ** [comment]
Think you, I see 
```
Dependencies
Python versions: 3.7-3.9
```in Latest  Numba,so not sure can use in python3.6.
But not sure for "setup a new virtual environment"
Do you mean "python3 -m venv /path/to/new/virtual/environment"?

And I try for latest it's did not work.
```
pip3 install numba==0.54
ERROR: Could not find a version that satisfies the requirement numba==0.54 (from versions: 0.1, 0.2, 0.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.18.1, 0.18.2, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.1, 0.29.0, 0.30.0, 0.30.1, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.1, 0.36.2, 0.37.0, 0.38.0, 0.38.1, 0.39.0, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.42.1, 0.43.0, 0.43.1, 0.44.0, 0.44.1, 0.45.0, 0.45.1, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.49.1rc1, 0.49.1, 0.50.0rc1, 0.50.0, 0.50.1, 0.51.0rc1, 0.51.0, 0.51.1, 0.51.2, 0.52.0rc2, 0.52.0rc3, 0.52.0, 0.53.0rc1.post1, 0.53.0rc2, 0.53.0rc3, 0.53.0, 0.53.1)
ERROR: No matching distribution found for numba==0.54
yoursweet:~ z$ pip3 install numba==0.53.1
Processing ./Library/Caches/pip/wheels/43/a1/40/70e530c4c52873514cfdce6bed1cbdc4cd1e8f199f01c8017d/numba-0.53.1-cp36-cp36m-macosx_10_12_x86_64.whl
Requirement already satisfied: setuptools in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (49.2.0.post20200714)
Requirement already satisfied: numpy>=1.15 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (1.19.1)
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0-cp36-cp36m-macosx_10_9_x86_64.whl (18.5 MB)
Installing collected packages: llvmlite, numba
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.31.0
    Uninstalling llvmlite-0.31.0:
      Successfully uninstalled llvmlite-0.31.0
  Attempting uninstall: numba
    Found existing installation: numba 0.48.0
    Uninstalling numba-0.48.0:
      Successfully uninstalled numba-0.48.0
Successfully installed llvmlite-0.36.0 numba-0.53.1
yoursweet:~ z$ python3
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import umap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/umap_.py", line 27, in <module>
    import numba
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/__init__.py", line 131, in <module>
    importlib.import_module(_old_mod)
  File "/anaconda2/envs/test_py3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/__init__.py", line 1, in <module>
    from .castgraph import Conversion
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/castgraph.py", line 6, in <module>
    from numba.utils import total_ordering
ImportError: cannot import name 'total_ordering'
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/__init__.py", line 29, in <module>
    import numba.core.types as types
AttributeError: module 'numba' has no attribute 'core'

```

**Comment by esc** [comment]
> Think you, I see
> 
> ```
> Dependencies
> Python versions: 3.7-3.9
> ```in Latest  Numba,so not sure can use in python3.6.
> But not sure for "setup a new virtual environment"
> Do you mean "python3 -m venv /path/to/new/virtual/environment"?
> 
> And I try for latest it's did not work.
> ```
> 
> pip3 install numba==0.54
> ERROR: Could not find a version that satisfies the requirement numba==0.54 (from versions: 0.1, 0.2, 0.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.18.1, 0.18.2, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.1, 0.29.0, 0.30.0, 0.30.1, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.1, 0.36.2, 0.37.0, 0.38.0, 0.38.1, 0.39.0, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.42.1, 0.43.0, 0.43.1, 0.44.0, 0.44.1, 0.45.0, 0.45.1, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.49.1rc1, 0.49.1, 0.50.0rc1, 0.50.0, 0.50.1, 0.51.0rc1, 0.51.0, 0.51.1, 0.51.2, 0.52.0rc2, 0.52.0rc3, 0.52.0, 0.53.0rc1.post1, 0.53.0rc2, 0.53.0rc3, 0.53.0, 0.53.1)
> ERROR: No matching distribution found for numba==0.54
> yoursweet:~ z$ pip3 install numba==0.53.1
> Processing ./Library/Caches/pip/wheels/43/a1/40/70e530c4c52873514cfdce6bed1cbdc4cd1e8f199f01c8017d/numba-0.53.1-cp36-cp36m-macosx_10_12_x86_64.whl
> Requirement already satisfied: setuptools in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (49.2.0.post20200714)
> Requirement already satisfied: numpy>=1.15 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (1.19.1)
> Collecting llvmlite<0.37,>=0.36.0rc1
> Using cached llvmlite-0.36.0-cp36-cp36m-macosx_10_9_x86_64.whl (18.5 MB)
> Installing collected packages: llvmlite, numba
> Attempting uninstall: llvmlite
> Found existing installation: llvmlite 0.31.0
> Uninstalling llvmlite-0.31.0:
> Successfully uninstalled llvmlite-0.31.0
> Attempting uninstall: numba
> Found existing installation: numba 0.48.0
> Uninstalling numba-0.48.0:
> Successfully uninstalled numba-0.48.0
> Successfully installed llvmlite-0.36.0 numba-0.53.1
> yoursweet:~ z$ python3
> Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import umap
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/**init**.py", line 1, in 
> > > > from .umap_ import UMAP
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/umap_.py", line 27, in 
> > > > import numba
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/**init**.py", line 131, in 
> > > > importlib.import_module(_old_mod)
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/importlib/**init**.py", line 126, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/**init**.py", line 1, in 
> > > > from .castgraph import Conversion
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/castgraph.py", line 6, in 
> > > > from numba.utils import total_ordering
> > > > ImportError: cannot import name 'total_ordering'
> > > > import numba
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/**init**.py", line 29, in 
> > > > import numba.core.types as types
> > > > AttributeError: module 'numba' has no attribute 'core'

If you use `conda` you can make a new environment with Numba using:

```
conda create -c numba -n numbaenv python=3.9 numba
```

And then activate with

```
conda activate numbaenv
```

Let us know if this works.

**Comment by siqi-zZ** [comment]
hahahaha It's work !!!! Thank you very much~

**Comment by siqi-zZ** [comment]
> > Think you, I see
> > ```
> > Dependencies
> > Python versions: 3.7-3.9
> > ```in Latest  Numba,so not sure can use in python3.6.
> > But not sure for "setup a new virtual environment"
> > Do you mean "python3 -m venv /path/to/new/virtual/environment"?
> > 
> > And I try for latest it's did not work.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pip3 install numba==0.54
> > ERROR: Could not find a version that satisfies the requirement numba==0.54 (from versions: 0.1, 0.2, 0.3, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.18.1, 0.18.2, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.1, 0.29.0, 0.30.0, 0.30.1, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.1, 0.36.2, 0.37.0, 0.38.0, 0.38.1, 0.39.0, 0.40.0, 0.40.1, 0.41.0, 0.42.0, 0.42.1, 0.43.0, 0.43.1, 0.44.0, 0.44.1, 0.45.0, 0.45.1, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.49.1rc1, 0.49.1, 0.50.0rc1, 0.50.0, 0.50.1, 0.51.0rc1, 0.51.0, 0.51.1, 0.51.2, 0.52.0rc2, 0.52.0rc3, 0.52.0, 0.53.0rc1.post1, 0.53.0rc2, 0.53.0rc3, 0.53.0, 0.53.1)
> > ERROR: No matching distribution found for numba==0.54
> > yoursweet:~ z$ pip3 install numba==0.53.1
> > Processing ./Library/Caches/pip/wheels/43/a1/40/70e530c4c52873514cfdce6bed1cbdc4cd1e8f199f01c8017d/numba-0.53.1-cp36-cp36m-macosx_10_12_x86_64.whl
> > Requirement already satisfied: setuptools in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (49.2.0.post20200714)
> > Requirement already satisfied: numpy>=1.15 in /anaconda2/envs/flask/lib/python3.6/site-packages (from numba==0.53.1) (1.19.1)
> > Collecting llvmlite<0.37,>=0.36.0rc1
> > Using cached llvmlite-0.36.0-cp36-cp36m-macosx_10_9_x86_64.whl (18.5 MB)
> > Installing collected packages: llvmlite, numba
> > Attempting uninstall: llvmlite
> > Found existing installation: llvmlite 0.31.0
> > Uninstalling llvmlite-0.31.0:
> > Successfully uninstalled llvmlite-0.31.0
> > Attempting uninstall: numba
> > Found existing installation: numba 0.48.0
> > Uninstalling numba-0.48.0:
> > Successfully uninstalled numba-0.48.0
> > Successfully installed llvmlite-0.36.0 numba-0.53.1
> > yoursweet:~ z$ python3
> > Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
> > [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> > Type "help", "copyright", "credits" or "license" for more information.
> > > > > import umap
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/**init**.py", line 1, in
> > > > > from .umap_ import UMAP
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/umap/umap_.py", line 27, in
> > > > > import numba
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/**init**.py", line 131, in
> > > > > importlib.import_module(_old_mod)
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/importlib/**init**.py", line 126, in import_module
> > > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/**init**.py", line 1, in
> > > > > from .castgraph import Conversion
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/typeconv/castgraph.py", line 6, in
> > > > > from numba.utils import total_ordering
> > > > > ImportError: cannot import name 'total_ordering'
> > > > > import numba
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "/anaconda2/envs/test_py3/lib/python3.6/site-packages/numba/**init**.py", line 29, in
> > > > > import numba.core.types as types
> > > > > AttributeError: module 'numba' has no attribute 'core'
> 
> If you use `conda` you can make a new environment with Numba using:
> 
> ```
> conda create -c numba -n numbaenv python=3.9 numba
> ```
> 
> And then activate with
> 
> ```
> conda activate numbaenv
> ```
> 
> Let us know if this works.

It's working!!! thank you very much

**Comment by esc** [comment]
> > Let us know if this works.
> 
> It's working!!! thank you very much

You are welcome, thank you for using Numba!
