### ISSUE TITLE
if statement inside a for loop fails 

### ISSUE THREAD

**Issue by phanirohith** [numba/numba#7396]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Putting an if statement fails inside of a for a loop.
I was writing a code to append the values into an list with an if condition and the if statement is getting failed.
Also, I tried the same with different versions (0.48.0, 0.51.1) of Numba and still the same behaviour.  \

`lst = []
for i in (range(10):
  for j in range(10):
    if (i<j):
          lst.append(i+j)

**Comment by gmarkall** [comment]
The code alone doesn't work - there is no definition of `similar_sen`.

Could you please try with Numba 0.54, and if your code still doesn't work, paste an executable piece of code that reproduces the issue?

**Comment by phanirohith** [comment]
Hello gmarkall, can you check the edited version of the code now?

**Comment by gmarkall** [comment]
The following has no issues for me with Numba 0.54:

```python
from numba import njit

@njit
def f():
    lst = []
    for i in range(10):
        for j in range(10):
            if (i < j):
                lst.append(i + j)

f()
```

What are you observing?

(BTW, if you need to paste code, enclose it in triple backticks on a line by themselves: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks )

**Comment by phanirohith** [comment]
It is working fine with Numba 0.54. Thank you gmarkall.
