### ISSUE TITLE
Support for Python bytes and bytesarray objects

### ISSUE THREAD

**Issue by seibert** [numba/numba#740]
Python `bytes` (`str` in Python 2) is a frequently requested type for nopython mode.  This would be pretty straightforward to do, as the `bytes` object can be natively represented as a length and a data pointer.  A minimal set of operations to support for `bytes` would include
- `__getitem__`
- `__eq__`
- `__ne__`

For `bytesarray`, we would add:
- `__setitem__`

Note that unicode strings (`str` in Python 3) are a very complex beast, and we do not want to deal with them in Numba unless there is a very compelling use case.

**Comment by lgautier** [comment]
Support for the buffer protocol (issue #989) would also address this, I believe.

**Comment by stuartarchibald** [comment]
Closing as I think this is all now supported. Please reopen if not.
