### ISSUE TITLE
guvectorize does not implement the numpy ufunc interface in versions 0.53+

### ISSUE THREAD

**Issue by iguinn** [numba/numba#7402]
Hi, after upgrading numba from version 0.52.0 to either versions 0.53.0 or 0.54.0, I have found that the signature field of functions compiled using @guvectorize no longer is implemented.

Tested with:
numpy version 1.20.0
numba version 0.52.0, 0.53.0, 0.54.0

Here is a minimal working example:
```
from numba import guvectorize

@guvectorize(["void(float64[:], float64[:], float64[:])"],
             "(n),(n)->()", nopython=True, cache=True)
def test(a, b, c):
    c[0]=0
    for i in range(len(a)):
        c[0] += a[i]*b[i]
```
When I try using this, here's what happens with 0.52.0:
```
In [1]: import test_gufunc                                                      

In [2]: test_gufunc.test.signature                                              
Out[2]: '(n),(n)->()'
```
And here's what I get with the newer versions:
```
In [1]: import test_gufunc                                                      

In [2]: test_gufunc.test.signature                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d4d284438f75> in <module>
----> 1 test_gufunc.test.signature

AttributeError: 'GUFunc' object has no attribute 'signature'
```

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by gmarkall** [comment]
I can reproduce this. The commit that introduced the issue is 925fd4c583094f4ea6852922c6bc9b86adf214b9.

**Comment by gmarkall** [comment]
The commit was in this PR: https://github.com/numba/numba/pull/5938

@guilhermeleobas Is it possible to add the `signature` property for dynamic gufuncs?

@iguinn Forgot to say earlier - many thanks for the report!

**Comment by gmarkall** [comment]
I've put this in the 0.55 milestone as we're so close to tagging 0.54.1, and this wasn't a regression specifically introduced in 0.54.0.

**Comment by guilhermeleobas** [comment]
Hi @gmarkall, yes, that's possible. I'll send a PR shortly. @iguinn, thanks for reporting this bug!

**Comment by iguinn** [comment]
Thanks for fixing this! I'll be looking forward to the next release.
