### ISSUE TITLE
Support for Numpy convolve mode 'valid'

### ISSUE THREAD

**Issue by danilo-bc** [numba/numba#7406]
## Feature request

I've been working with model simulations and there's the need for `np.convolve(a, k, mode='valid')`.

I wish to have support for this for use with `@jit`/`@njit` decorators.

I have this example implementation from one of the discussions about using Numba for such situation, but I'd rather not have to resort to it in projects which require valid mode.
```python
def numba_convolve_mode_valid_as_loop(arr, kernel):
        m = arr.size
        n = kernel.size
        out_size = m - n + 1
        out = np.empty(out_size, dtype=np.complex128)
        kernel = np.flip(kernel)  # wrong results otherwise
        for i in range(out_size):
            out[i] = np.dot(arr[i:i + n], kernel)
        return out
```

**Comment by gmarkall** [comment]
Labelling as "good second issue" as most of the parts needed for the implementation are already present, but need connecting together. Se e.g. https://github.com/numba/numba/blob/master/numba/np/arraymath.py#L4230-L4251.

**Comment by danilo-bc** [comment]
Thanks for pointing it out! I'd need to set a test environment for that.

A simple
```python
@njit 
def convolve_valid(a, v):
    return np.convolve(a, v, mode='valid) 
```
seems sufficient, right?

Either Numba will compile, or it will throw an error. Then the results should be easily testable with a couple more tests.

That said, I'd need to compile and use my personal version of Numba for those, and I'm definitely pretty lost in that regard. I currently installed it via `pip`.

**Comment by jeertmans** [comment]
Hello @danilo-bc, are you still working on this ? Otherwise, I would gladly give it a try!

**Comment by danilo-bc** [comment]
> Hello @danilo-bc, are you still working on this ? Otherwise, I would gladly give it a try!

Please feel free to take it over. I've had a few unexpected problems in the meantime.

**Comment by jeertmans** [comment]
> > Hello @danilo-bc, are you still working on this ? Otherwise, I would gladly give it a try!
> 
> Please feel free to take it over. I've had a few unexpected problems in the meantime.

Thanks for the quick reply! I will try it myself then.
