### ISSUE TITLE
Untyped global name 'dblquad': Cannot determine Numba type of <class 'function'> : Scipy dblquad not work in Numba

### ISSUE THREAD

**Issue by vantainguyen** [numba/numba#7407]
There is an error when I try to use scipy.dblquad in @njit function. How can I fix it?

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by vantainguyen** [comment]
Here are the codes!
# Import necessary library
from numpy import sqrt, sin, cos, pi, log, tan, pi
from scipy.integrate import quad, dblquad, tplquad
import numba
from numba import njit, jit

mu0 = 4*pi*10**-7


# Auxilliary function
@njit()
def main_func_Ha_1(H, a, r, z, delta, r1, theta):
    

    z1 = a*(r1*1000)**2/1000
        
    main_11 = -(z - z1)*r1
    main_21 = (r1**2 + r**2 - 2*r1*r*cos(delta - theta) + (z - z1)**2)**1.5
    
    return main_11/main_21

@njit()
def main_func_Ha_2(H, a, r, z, delta, r2, theta):
    
    main_12 = (z - H)*r2
    main_22 = (r2**2 + r**2 - 2*r2*r*cos(delta - theta) + (z - H)**2)**1.5
    
    return main_12/main_22

@njit()
def inte_1(r1, theta):
    return main_func_Ha_1(H, a, r, z, delta, r1, theta)

@njit()
def inte_2(r2, theta):
    return main_func_Ha_2(H, a, r, z, delta, r2, theta)

@njit()
def B_paraboloid_axial_axial(J, H, a, r, z, delta):
    
    
    r_b = sqrt(H*1000/a)/1000
    
        
    integral_B_1 = dblquad(inte_1, 0, 2*pi, 0, r_b)[0]

    integral_B_2 = dblquad(inte_2, 0, 2*pi, 0, r_b)[0]
          
    return J*(integral_B_1 + integral_B_2)/4/pi

# Main programm

from matplotlib import pyplot as plt
import numpy as np
import plotly.graph_objects as go
import pandas as pd
import time
from MagField_2_numba_2 import B_paraboloid_axial_axial 
from numpy import pi
import numba
from numba import prange, njit
import multiprocessing as mp

#%%

image_dim = 40

mu0 = 4*pi*10**-7

J = 1 #10**4
H = 12.8/1000 
L = H
a = .4

r_ = np.linspace(-20, 20, image_dim)/1000
z_ = np.linspace(-20, 20, image_dim)/1000 

alpha = pi/3
delta = pi/6



H_field_axial = np.zeros((image_dim, image_dim), dtype=np.float32)
    
#def data_generation_4H(image_dim):
@njit(parallel=True, nogil=True) #does not work 
def data_generation_4H_nopa(image_dim, H_field_axial):
    for z in prange(image_dim):
        for r in prange(image_dim):
            
            H_field_axial[z, r] = B_paraboloid_axial_axial(J, H, a, abs(r_[r]), z_[z], delta)/mu0
            
    return H_field_axial 


start_time = time.process_time()

aa = data_generation_4H_nopa(image_dim, H_field_axial)

used_time_nopa = time.process_time() - start_time

**Comment by gmarkall** [comment]
Have you got [numba-scipy](https://github.com/numba/numba-scipy) installed?

**Comment by vantainguyen** [comment]
I have tried to install the numba-scipy package, but it was unsuccessful and the error as below:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\s4612643\\AppData\\Local\\Temp\\pip-uninstall-pybzu4hu\\integrate\\lsoda.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

How can I resolve this please?

**Comment by gmarkall** [comment]
As the error message suggests, you could try installing to the user site: https://packaging.python.org/tutorials/installing-packages/#installing-to-the-user-site

**Comment by vantainguyen** [comment]
I have used pip3 and installed numba-scipy successfully, and added "import numba_scipy" in the code.  But, the error still the same.

**Comment by gmarkall** [comment]
I tried to run your code without `@njit` and I got this traceback:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/7407/main.py", line 41, in <module>
    aa = data_generation_4H_nopa(image_dim, H_field_axial)
  File "/home/gmarkall/numbadev/issues/7407/main.py", line 34, in data_generation_4H_nopa
    H_field_axial[z, r] = B_paraboloid_axial_axial(J, H, a, abs(r_[r]), z_[z], delta)/mu0
  File "/home/gmarkall/numbadev/issues/7407/repro.py", line 43, in B_paraboloid_axial_axial
    integral_B_1 = dblquad(inte_1, 0, 2*pi, 0, r_b)[0]
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 601, in dblquad
    return nquad(func, [temp_ranges, [a, b]], args=args,
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 825, in nquad
    return _NQuad(func, ranges, opts, full_output).integrate(*args)
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 879, in integrate
    quad_r = quad(f, low, high, args=args, full_output=self.full_output,
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 351, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 463, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 879, in integrate
    quad_r = quad(f, low, high, args=args, full_output=self.full_output,
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 351, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/scipy/integrate/quadpack.py", line 463, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
  File "/home/gmarkall/numbadev/issues/7407/repro.py", line 31, in inte_1
    return main_func_Ha_1(H, a, r, z, delta, r1, theta)
NameError: name 'H' is not defined
```

**Comment by vantainguyen** [comment]
Can you please replace two functions inte_1 and inte_2 in the code with those below:

@njit()
def inte_1(r1, theta, H=0., a=0., r=0., z=0., delta=0.):
    return main_func_Ha_1(H, a, r, z, delta, r1, theta)

@njit()
def inte_2(r2, theta, H=0., a=0., r=0., z=0., delta=0.):
    return main_func_Ha_2(H, a, r, z, delta, r2, theta)

**Comment by gmarkall** [comment]
It sounds like somehow `numba-scipy` is not installed properly - your script now works for me (completes without error) with `@njit` and the changes above. What is the output of `numba -s`?

**Comment by gmarkall** [comment]
After a little more research, it turns out that `dblquad` is not supported by numba-scipy - You may open a feature request in numba-scipy if you'd like to request / track support for it: https://github.com/numba/numba-scipy/issues

**Comment by vantainguyen** [comment]
what advice for me to solve the problem with double integral like dblquad? how can I still use numba?

**Comment by gmarkall** [comment]
I'd suggest creating a post on the Discourse group (https://numba.discourse.group) explaining what you're trying to do (with your example code), and ask if people have suggestions for what to do.
