### ISSUE TITLE
`numba.vectorize` interface inconsistency between `target="cpu"` and `target="parallel"`

### ISSUE THREAD

**Issue by brandonwillard** [numba/numba#7409]
`numba.vectorize` on 4911192c5 (and further back) appears to have the following interface inconsistency:
```python
import numpy as np
import numba as nb


@nb.jit
def add(x, y):
    return x + y


custom_vectorize = nb.vectorize([], identity=None, target="cpu")

# No problem here
test_fn = custom_vectorize(add)

custom_vectorize_2 = nb.vectorize([], identity=None, target="parallel")

# Problem here
test_fn_2 = custom_vectorize_2(add)

# TypeError: A jit decorator was called on an already jitted function CPUDispatcher(<function add at 0x7fa399ca2ef0>).  If trying to access the original python function, use the CPUDispatcher(<function add at 0x7fa399ca2ef0>).py_func attribute.
```

**Comment by gmarkall** [comment]
I can reproduce this.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think something like this needs doing for the parallel target (fairly sure the below is why the `'cpu'` target works):
https://github.com/numba/numba/blob/4911192c5b51f3ecbb76a12b74372979378c43a1/numba/np/ufunc/dufunc.py#L80-L81
but it can probably just use the extension API for the determination of whether the function is already `@jit` wrapped: https://numba.readthedocs.io/en/stable/extending/high-level.html#numba.extending.is_jitted
