### ISSUE TITLE
jit(locals) are propagated to inline functions with same variable names

### ISSUE THREAD

**Issue by voegtlel** [numba/numba#7411]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG). (version is 0.54.0)
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello there,
I'm trying to inline a very small function, and have set the `locals`, but it seems that the type of the locals is propagated to inline functions:

```py
import numba as nb

@nb.jit(
    nb.void(
        nb.int32,
    ),
    inline='always',  # if removed, everything works as expected
    locals={  # is ignored
        'a': nb.int32,
    },
)
def fn_a(a: nb.int32):
    print("a:", a)


@nb.jit(
    nb.void(
        nb.float32,
    ),
    locals={
        'a': nb.float32,
    },
)
def fn_b(a: nb.float32):
    print("a:", a)
    fn_a(nb.int32(a))


if __name__ == '__main__':
    fn_b(5.0)

```
Output:
```
a: 5.0
a: 5.0
```
Expected:
```
a: 5.0
a: 5
```

Removing `inline="always"` resolves the issue.

Thank you!

**Comment by gmarkall** [comment]
I can reproduce this.

It's also noted during discussion at the triage meeting that it's odd that the case to `nb.int32` seems not to be helping in this case.

**Comment by HPLegion** [comment]
I had not time to check this, but could it be related to #5809 ?

**Comment by stuartarchibald** [comment]
This doesn't reproduce on `main`, think it was fixed by https://github.com/numba/numba/pull/7552. Closing.
