### ISSUE TITLE
dump-llvm hangs

### ISSUE THREAD

**Issue by gystar** [numba/numba#7433]
test.py:
`a=int(input())
b=int(input())
print(a-b)`

I want convert test.py to llvm ir. But it hangs and does nothing, the commandline is :
`numba --dump-llvm test.py`

Iinfomation:
Name: numba
Version: 0.53.1
Summary: compiling Python code using LLVM

**Comment by esc** [comment]
> test.py:
> `a=int(input()) b=int(input()) print(a-b)`
> 
> I want convert test.py to llvm ir. But it hangs and does nothing, the commandline is :
> `numba --dump-llvm test.py`
> 
> Iinfomation:
> Name: numba
> Version: 0.53.1
> Summary: compiling Python code using LLVM

Thank you for asking about this @gystar -- I am not sure what you are trying to achieve. The Python code you listed is syntactically incorrect, perhaps that is the reason that `numba` hangs?

```
 💣 zsh» python issue7433.py
  File "issue7433.py", line 1
    a=int(input()) b=int(input()) print(a-b)
                   ^
SyntaxError: invalid syntax
```

I would suggest crafting a syntactically correct Python file first and then trying Numba on that.

**Comment by gystar** [comment]
Thanks!

Test.py :
a=int(input()) 
b=int(input()) 
print(a-b)

I want to use numba to generate llvm ir from test.py.

**Comment by gystar** [comment]
> > test.py:
> > `a=int(input()) b=int(input()) print(a-b)`
> > I want convert test.py to llvm ir. But it hangs and does nothing, the commandline is :
> > `numba --dump-llvm test.py`
> > Iinfomation:
> > Name: numba
> > Version: 0.53.1
> > Summary: compiling Python code using LLVM
> 
> Thank you for asking about this @gystar -- I am not sure what you are trying to achieve. The Python code you listed is syntactically incorrect, perhaps that is the reason that `numba` hangs?
> 
> ```
>  💣 zsh» python issue7433.py
>   File "issue7433.py", line 1
>     a=int(input()) b=int(input()) print(a-b)
>                    ^
> SyntaxError: invalid syntax
> ```
> 
> I would suggest crafting a syntactically correct Python file first and then trying Numba on that.


I find that numba will run Test.py first , and then print the output (inculde LLVM IR of some functions decorated by jit )
So is hangs because Test.py need some input.
But how can I get LLVM IR for the following python code:

a=1
b=2
print(a-b)

**Comment by esc** [comment]
> > > test.py:
> > > `a=int(input()) b=int(input()) print(a-b)`
> > > I want convert test.py to llvm ir. But it hangs and does nothing, the commandline is :
> > > `numba --dump-llvm test.py`
> > > Iinfomation:
> > > Name: numba
> > > Version: 0.53.1
> > > Summary: compiling Python code using LLVM
> > 
> > 
> > Thank you for asking about this @gystar -- I am not sure what you are trying to achieve. The Python code you listed is syntactically incorrect, perhaps that is the reason that `numba` hangs?
> > ```
> >  💣 zsh» python issue7433.py
> >   File "issue7433.py", line 1
> >     a=int(input()) b=int(input()) print(a-b)
> >                    ^
> > SyntaxError: invalid syntax
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would suggest crafting a syntactically correct Python file first and then trying Numba on that.
> 
> I find that numba will run Test.py first , and then print the output (inculde LLVM IR of some functions decorated by jit )
> So it hangs because Test.py need some input.
> But how can I get LLVM IR for the following python code without running it:
> 
> a=1
> b=2
> print(a-b)

Numba is a Just In Time (JIT) compiler, so you need to run the code once for it to be compiled.

```
 💣 zsh» cat issue7433.py
from numba import njit


@njit
def foo():
    a = 1
    b = 2
    print(a-b)

foo()
```

```
 💣 zsh» python issue7433.py
-1
```

And then finally:

```
 💣 zsh» numba --dump-llvm  issue7433.py
--------------------LLVM DUMP <function descriptor 'foo$1'>---------------------
; ModuleID = "foo$1"
target triple = "x86_64-apple-darwin19.6.0"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

@"_ZN08NumbaEnv8__main__7foo$241E" = common global i8* null
define i32 @"_ZN8__main__7foo$241E"(i8** noalias nocapture %"retptr", {i8*, i32, i8*}** noalias nocapture %"excinfo")
{
entry:
  %".5" = alloca i32
  store i32 0, i32* %".5"
  %"try_state" = alloca i64
  store i64 0, i64* %"try_state"
  %".22" = alloca i8*
  store i8* null, i8** %".22"
  br label %"B0"
B0:
  %".4" = sub nsw i64 1, 2
  call void @"numba_gil_ensure"(i32* %".5")
  %".8" = load i8*, i8** @"_ZN08NumbaEnv8__main__7foo$241E"
  %".9" = icmp eq i8* null, %".8"
  br i1 %".9", label %"B0.if", label %"B0.endif", !prof !0
B0.if:
  store {i8*, i32, i8*}* @".const.picklebuf.140714831343296", {i8*, i32, i8*}** %"excinfo"
  store i64 0, i64* %"try_state"
  %".14" = load i64, i64* %"try_state"
  %".15" = icmp ugt i64 %".14", 0
  %".16" = load {i8*, i32, i8*}*, {i8*, i32, i8*}** %"excinfo"
  ret i32 1, !ret_is_raise !1
B0.endif:
  %".18" = ptrtoint i8* %".8" to i64
  %".19" = add i64 %".18", 16
  %".20" = inttoptr i64 %".19" to i8*
  %".21" = bitcast i8* %".20" to {i8*, i8*}*
  %".24" = call i8* @"PyLong_FromLongLong"(i64 %".4")
  store i8* %".24", i8** %".22"
  %".26" = load i8*, i8** %".22"
  %".27" = icmp ne i8* null, %".26"
  br i1 %".27", label %"B0.endif.if", label %"B0.endif.else", !prof !2
B0.endif.if:
  %".29" = call i8* @"PyObject_Str"(i8* %".26")
  %".30" = call i8* @"PyUnicode_AsUTF8"(i8* %".29")
  call void (i8*, ...) @"PySys_FormatStdout"(i8* bitcast ([3 x i8]* @".const.%s" to i8*), i8* %".30")
  call void @"Py_DecRef"(i8* %".29")
  call void @"Py_DecRef"(i8* %".26")
  br label %"B0.endif.endif"
B0.endif.else:
  %".35" = call i8* @"PyUnicode_FromString"(i8* bitcast ([21 x i8]* @".const.the print() function" to i8*))
  call void @"PyErr_WriteUnraisable"(i8* %".35")
  call void @"Py_DecRef"(i8* %".35")
  br label %"B0.endif.endif"
B0.endif.endif:
  call void (i8*, ...) @"PySys_FormatStdout"(i8* bitcast ([2 x i8]* @".const.
" to i8*))
  call void @"numba_gil_release"(i32* %".5")
  store i8* null, i8** %"retptr"
  ret i32 0
}

declare void @"numba_gil_ensure"(i32* %".1")

@".const.pickledata.140714831343296" = internal constant [100 x i8] c"\80\04\95Y\00\00\00\00\00\00\00\8c\08builtins\94\8c\0cRuntimeError\94\93\94\8c4missing Environment: _ZN08NumbaEnv8__main__7foo$241E\94\85\94N\87\94."
@".const.pickledata.140714831343296.sha1" = internal constant [20 x i8] c"\1d\da:m\88\86I\eb\06\fc\144F\0e\cbHpz\00\e5"
@".const.picklebuf.140714831343296" = internal constant {i8*, i32, i8*} {i8* bitcast ([100 x i8]* @".const.pickledata.140714831343296" to i8*), i32 100, i8* bitcast ([20 x i8]* @".const.pickledata.140714831343296.sha1" to i8*)}
declare i8* @"PyLong_FromLongLong"(i64 %".1")

declare i8* @"PyObject_Str"(i8* %".1")

declare i8* @"PyUnicode_AsUTF8"(i8* %".1")

@".const.%s" = internal constant [3 x i8] c"%s\00"
declare void @"PySys_FormatStdout"(i8* %".1", ...)

declare void @"Py_DecRef"(i8* %".1")

@".const.the print() function" = internal constant [21 x i8] c"the print() function\00"
declare i8* @"PyUnicode_FromString"(i8* %".1")

declare void @"PyErr_WriteUnraisable"(i8* %".1")

@".const.
" = internal constant [2 x i8] c"\0a\00"
declare void @"numba_gil_release"(i32* %".1")

!0 = !{ !"branch_weights", i32 1, i32 99 }
!1 = !{ i1 1 }
!2 = !{ !"branch_weights", i32 99, i32 1 }
================================================================================
-1
```

**Comment by gystar** [comment]
> > > > test.py:
> > > > `a=int(input()) b=int(input()) print(a-b)`
> > > > I want convert test.py to llvm ir. But it hangs and does nothing, the commandline is :
> > > > `numba --dump-llvm test.py`
> > > > Iinfomation:
> > > > Name: numba
> > > > Version: 0.53.1
> > > > Summary: compiling Python code using LLVM
> > > 
> > > 
> > > Thank you for asking about this @gystar -- I am not sure what you are trying to achieve. The Python code you listed is syntactically incorrect, perhaps that is the reason that `numba` hangs?
> > > ```
> > >  💣 zsh» python issue7433.py
> > >   File "issue7433.py", line 1
> > >     a=int(input()) b=int(input()) print(a-b)
> > >                    ^
> > > SyntaxError: invalid syntax
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I would suggest crafting a syntactically correct Python file first and then trying Numba on that.
> > 
> > 
> > I find that numba will run Test.py first , and then print the output (inculde LLVM IR of some functions decorated by jit )
> > So it hangs because Test.py need some input.
> > But how can I get LLVM IR for the following python code without running it:
> > a=1
> > b=2
> > print(a-b)
> 
> Numba is a Just In Time (JIT) compiler, so you need to run the code once for it to be compiled.
> 
> ```
>  💣 zsh» cat issue7433.py
> from numba import njit
> 
> 
> @njit
> def foo():
>     a = 1
>     b = 2
>     print(a-b)
> 
> foo()
> ```
> 
> ```
>  💣 zsh» python issue7433.py
> -1
> ```
> 
> And then finally:
> 
> ```
>  💣 zsh» numba --dump-llvm  issue7433.py
> --------------------LLVM DUMP <function descriptor 'foo$1'>---------------------
> ; ModuleID = "foo$1"
> target triple = "x86_64-apple-darwin19.6.0"
> target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
> 
> @"_ZN08NumbaEnv8__main__7foo$241E" = common global i8* null
> define i32 @"_ZN8__main__7foo$241E"(i8** noalias nocapture %"retptr", {i8*, i32, i8*}** noalias nocapture %"excinfo")
> {
> entry:
>   %".5" = alloca i32
>   store i32 0, i32* %".5"
>   %"try_state" = alloca i64
>   store i64 0, i64* %"try_state"
>   %".22" = alloca i8*
>   store i8* null, i8** %".22"
>   br label %"B0"
> B0:
>   %".4" = sub nsw i64 1, 2
>   call void @"numba_gil_ensure"(i32* %".5")
>   %".8" = load i8*, i8** @"_ZN08NumbaEnv8__main__7foo$241E"
>   %".9" = icmp eq i8* null, %".8"
>   br i1 %".9", label %"B0.if", label %"B0.endif", !prof !0
> B0.if:
>   store {i8*, i32, i8*}* @".const.picklebuf.140714831343296", {i8*, i32, i8*}** %"excinfo"
>   store i64 0, i64* %"try_state"
>   %".14" = load i64, i64* %"try_state"
>   %".15" = icmp ugt i64 %".14", 0
>   %".16" = load {i8*, i32, i8*}*, {i8*, i32, i8*}** %"excinfo"
>   ret i32 1, !ret_is_raise !1
> B0.endif:
>   %".18" = ptrtoint i8* %".8" to i64
>   %".19" = add i64 %".18", 16
>   %".20" = inttoptr i64 %".19" to i8*
>   %".21" = bitcast i8* %".20" to {i8*, i8*}*
>   %".24" = call i8* @"PyLong_FromLongLong"(i64 %".4")
>   store i8* %".24", i8** %".22"
>   %".26" = load i8*, i8** %".22"
>   %".27" = icmp ne i8* null, %".26"
>   br i1 %".27", label %"B0.endif.if", label %"B0.endif.else", !prof !2
> B0.endif.if:
>   %".29" = call i8* @"PyObject_Str"(i8* %".26")
>   %".30" = call i8* @"PyUnicode_AsUTF8"(i8* %".29")
>   call void (i8*, ...) @"PySys_FormatStdout"(i8* bitcast ([3 x i8]* @".const.%s" to i8*), i8* %".30")
>   call void @"Py_DecRef"(i8* %".29")
>   call void @"Py_DecRef"(i8* %".26")
>   br label %"B0.endif.endif"
> B0.endif.else:
>   %".35" = call i8* @"PyUnicode_FromString"(i8* bitcast ([21 x i8]* @".const.the print() function" to i8*))
>   call void @"PyErr_WriteUnraisable"(i8* %".35")
>   call void @"Py_DecRef"(i8* %".35")
>   br label %"B0.endif.endif"
> B0.endif.endif:
>   call void (i8*, ...) @"PySys_FormatStdout"(i8* bitcast ([2 x i8]* @".const.
> " to i8*))
>   call void @"numba_gil_release"(i32* %".5")
>   store i8* null, i8** %"retptr"
>   ret i32 0
> }
> 
> declare void @"numba_gil_ensure"(i32* %".1")
> 
> @".const.pickledata.140714831343296" = internal constant [100 x i8] c"\80\04\95Y\00\00\00\00\00\00\00\8c\08builtins\94\8c\0cRuntimeError\94\93\94\8c4missing Environment: _ZN08NumbaEnv8__main__7foo$241E\94\85\94N\87\94."
> @".const.pickledata.140714831343296.sha1" = internal constant [20 x i8] c"\1d\da:m\88\86I\eb\06\fc\144F\0e\cbHpz\00\e5"
> @".const.picklebuf.140714831343296" = internal constant {i8*, i32, i8*} {i8* bitcast ([100 x i8]* @".const.pickledata.140714831343296" to i8*), i32 100, i8* bitcast ([20 x i8]* @".const.pickledata.140714831343296.sha1" to i8*)}
> declare i8* @"PyLong_FromLongLong"(i64 %".1")
> 
> declare i8* @"PyObject_Str"(i8* %".1")
> 
> declare i8* @"PyUnicode_AsUTF8"(i8* %".1")
> 
> @".const.%s" = internal constant [3 x i8] c"%s\00"
> declare void @"PySys_FormatStdout"(i8* %".1", ...)
> 
> declare void @"Py_DecRef"(i8* %".1")
> 
> @".const.the print() function" = internal constant [21 x i8] c"the print() function\00"
> declare i8* @"PyUnicode_FromString"(i8* %".1")
> 
> declare void @"PyErr_WriteUnraisable"(i8* %".1")
> 
> @".const.
> " = internal constant [2 x i8] c"\0a\00"
> declare void @"numba_gil_release"(i32* %".1")
> 
> !0 = !{ !"branch_weights", i32 1, i32 99 }
> !1 = !{ i1 1 }
> !2 = !{ !"branch_weights", i32 99, i32 1 }
> ================================================================================
> -1
> ```
Thanks.

**Comment by esc** [comment]
> Thanks.

No Problem and thank you for using Numba!
