### ISSUE TITLE
https://github.com/numba/numba/issues/new

### ISSUE THREAD

**Issue by SYKAMR** [numba/numba#7450]
ant merge !! sorry
Traceback (most recent call last):
  File "C:\Users\SYKAMR\OneDrive - Pfizer\SYKAMR\ELN_Signals\Python requirements\AttachingPdfs\MergingPdfs.py", line 36, in <module>
    Pdf_Write()
  File "C:\ANACONDA3\lib\site-packages\numba\dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\ANACONDA3\lib\site-packages\numba\dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "C:\ANACONDA3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1mUntyped global name 'merger':[0m [1m[1mcannot determine Numba type of <class 'PyPDF4.merger.PdfFileMerger'>[0m
[1m
File "..\MergingPdfs.py", line 32:[0m
[1mdef Pdf_Write():
[1m    merger.write("Merged_doc_using_PyPDF4.pdf")
[0m    [1m^[0m[0m
[0m
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

[Finished in 34.0s]

**Comment by esc** [comment]
@SYKAMR thank you for asking about this. Numba does not have native support for compiling `PyPDF4.merger.PdfFileMerger` so this is not the correct place for asking about this. I would suggest opening an issue on:

https://github.com/claird/PyPDF4

Perhaps?
