### ISSUE TITLE
Non-deterministic hang when testing set membership

### ISSUE THREAD

**Issue by hennels** [numba/numba#7455]
## Reporting a bug

When repeatedly checking `set` membership I have a program seems to hang indefinitely. This seems to happen non-deterministically on my machine. The program hangs every time I run it, but the iteration in which it hangs in seems to be random. I have attached a snippet of code that experiences the same issue. I have tested this on `0.54.0` and `0.53.1` and both seem to behave similarly.

By throwing in a bunch of `print` functions it seems to hang on the `new_number in state` check. The final printed line always ends with a 2. Interestingly this never seems to hang for relatively small values of `n` even though there is no iteration over `n`. For example `set_check(10, iters=1000)` never hung but `set_check(1000, iters=1000)` always has.

Running the following code always produces the issue for me. Without the `@numba.njit()` line it never hangs and behaves as expected (not hanging indefinitely). **Can anyone else replicate this?**  Am I doing something wrong and somehow getting undefined behavior?

```python
import numba
import numpy as np

@numba.njit()
def set_check(n, iters=100):
    state = set()
    current_value = np.random.randint(n)
    state.add(current_value)
    for i in range(iters):
        print(i, 1)
        new_number = np.random.randint(n)
        print(i, 2)
        if new_number in state:
            print(i, 3)
            continue
        print(i, 4)
        state.remove(current_value)
        state.add(new_number)
        current_value = new_number
    return state

np.random.seed(0)
set_check(1000, iters=1000)
```

**Comment by esc** [comment]
@hennels thank you for reporting this bug, it appears very similar to:

https://github.com/numba/numba/issues/6543

**Comment by stuartarchibald** [comment]
@esc I agree, suspect this is caused by the same underlying issue in #6543.

**Comment by hennels** [comment]
Sorry, I didn't see that issue when I was searching. Feel free to close this if it doesn't add anything new.

Interesting to see there are multiple ways to get to this behavior though. In  #6543 there are multiple elements in the set at a time, and here the same behavior occurs even though set only ever has 0 or 1 elements.

**Comment by stuartarchibald** [comment]
> Sorry, I didn't see that issue when I was searching. Feel free to close this if it doesn't add anything new.

No problem, thanks again for reporting it, extra examples/tests are always useful as one might contain less code/data which makes it easier to debug. It just so happens that this bug is in recent memory hence was relatively easy to spot as probably the same as #6543!

> Interesting to see there are multiple ways to get to this behavior though. In #6543 there are multiple elements in the set at a time, and here the same behavior occurs even though set only ever has 0 or 1 elements.

From memory, we think there's probably a couple of problem present and individually they are "ok" (issues are minimal/not seen) but there's certain conditions that result in a state where both problems are hit and the above happens.
