### ISSUE TITLE
Building w/OpenMP on macOS

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#7468]
This changeset ( https://github.com/numba/numba/commit/a23bc195096178e5849ebc0fb6dcedbd6f0cbeea ) was added to fix building on macOS previously. While packaging 0.54.1, we needed to switch to `llvm-openmp`. This seemed to work well despite issues previously. Given this, am wondering do we still need the custom handling here for macOS?

**Comment by stuartarchibald** [comment]
This PR attempts to remove the `intel-openmp` dependency: https://github.com/numba/numba/pull/7786 will have to see how it does in testing etc.
