### ISSUE TITLE
Wrongly evaluated equality comparison

### ISSUE THREAD

**Issue by bluenote10** [numba/numba#7474]
## Reporting a bug

- [x] I have tried using the latest released version of Numba: yes, using version 0.54.1 (7 October, 2021)
- [x] I have included a self contained code sample to reproduce the problem.

**`bug.py`**

```python
from numba import njit


@njit
def func(x: float):
    print("x:", x)

    if x > 1:
        action = "a"
    elif x < -1:
        action = "b"
    else:
        action = None

    print("action:", action, action == "a", action == "b")

    if action == "a":
        print("performing action a")
    elif action == "b":
        print("performing action b")


func(1.2)
```

**Output**

```
x: 1.2
action: a False False
```

Apparently the condition `action == "a"` is wrongly evaluated.

**Expected Output**

This is the output when running with plain Python, i.e., removing `@njit`:

```
x: 1.2
action: a True False
performing action a
```

**Comment by esc** [comment]
@bluenote10 thank you for reporting this. It seems like this is the result of Numba being sensitive to typing. It is either because the final `else` clause assigns a `None` or because the predicate compares against floating point. Here is a suitable workaround:

```
from numba import njit


@njit
def func(x: float):
    print("x:", x)

    if x > 1.0:
        action = "a"
    elif x < -1.0:
        action = "b"

    print("action:", action, action == "a", action == "b")

    if action == "a":
        print("performing action a")
    elif action == "b":
        print("performing action b")


func(1.2)

```
