### ISSUE TITLE
@jit np.stack and np.concatenate - tuples only - unlike numpy

### ISSUE THREAD

**Issue by fraseriainlewis** [numba/numba#7476]
Hi, 
this might be on the to-do list but in case not, calls to np.stack() and np.concatenate() appear to fail when using @jit decorator and passing a "sequence of array like" which are lists rather than tuples. I didn't see this restriction in the numba docs (https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html)? Minimal example is below. I'm a bit of a python newbie and this tripped me up for a while as numpy allows lists, jit/numba only seems to support tuples. Easy workaround of course, but perhaps worth adding into the docs?  

Minimal example:

@jit
def f1(i,j):
    ij=np.stack([i,j]) ## this does NOT work
    #ij=np.stack((i,j)) ##  this does work 
    print(ij)

@jit
def f2(k):
    kk=np.concatenate([k,k],axis=0) ## this does NOT work
    #kk=np.concatenate((k,k),axis=0) ## this does work
    print(kk)

i_o=np.array(0)
j_o=np.array(1)
k_o=np.array([2,3])

f1(i_o,j_o)
f2(k_o)

The errors are  
"TypeError: np.concatenate(): expecting a non-empty tuple of arrays"
"TypeError: np.stack(): expecting a non-empty tuple of arrays"

**Comment by esc** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by 46319943** [comment]
> Thanks for the report. The issue here is that Numba has to be able to statically determine all the variable types in a function. In general it's not possible to work out the dimension of the array returned by `np.stack/np.concatenate` if the input is a list as the dimension of the returned array will depend on the length of the list, which is only known at runtime. In the case of tuples, their length/size is known at compile time as they are immutable containers and so the return type for `np.stack/concatenate` with such an input type can be determined statically. Hope this helps.

You mean **the length of the list** or actually the **dimension of the items in the list**?

Because the dimension of the list is only one, which means it will only add one more dimension to the dimension of the items. But the dimension of the items is only determined during runtime, which makes the shape of the output array unable to determine.

Code to stack array with known shape but with list having unknown length:
```python
from numba import njit, prange
import numpy as np


@njit()
def test_list_stack(i):
    array_to_be_stacked = np.ones((2, 3))
    list_of_array = [array_to_be_stacked] * i
    stacked_array = np.empty((i, array_to_be_stacked.shape[0], array_to_be_stacked.shape[1]))
    for j in prange(i):
        stacked_array[j] = list_of_array[j]
    return stacked_array


if __name__ == "__main__":
    test_list_stack(10)
```

It can be seen that the length of list doesn't matter, but the shape of the array to be stacked really matters. If the shape of the array isn't determined, the shape of `stacked_array` can't therefore be determined.

**Comment by 46319943** [comment]
After a while, I find that the dimension actually can be determined during the lazy compilation.

```python
from numba import njit, prange
import numpy as np


@njit()
def test_list_stack(i, array_to_be_stacked):
    shape = (i,) + array_to_be_stacked.shape
    list_of_array = [array_to_be_stacked] * i
    stacked_array = np.empty(shape)
    for j in prange(i):
        stacked_array[j] = list_of_array[j]
    return stacked_array


if __name__ == "__main__":
    test_list_stack(10, np.ones((2, 3)))
```

`hstack` may should support `list` as input, as the functionality can be implemented as above.

**Comment by 46319943** [comment]
I implement a custom stack function, hoping it will help for anyone else having the same problem:

```python
from numba import njit, prange
from numba.typed import List
import numpy as np

@njit()
def stack(list_of_array):
    shape = (len(list_of_array),) + list_of_array[0].shape
    stacked_array = np.empty(shape)
    for j in prange(len(list_of_array)):
        stacked_array[j] = list_of_array[j]
    return stacked_array

if __name__ == "__main__":
    # Note that you have to use typed list provided by numba here.
    typed_list = List()
    [typed_list.append(np.ones((2, 3))) for _ in range(10)]
    stack(typed_list)
    print()
```
