### ISSUE TITLE
Error importing numba

### ISSUE THREAD

**Issue by asdouglass** [numba/numba#7486]
If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\dougl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numba\core\typeconv\__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Program Files\Spyder\Python\python.exe

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
