### ISSUE TITLE
Nooby needs help 

### ISSUE THREAD

**Issue by fraygeyst** [numba/numba#7510]
Hey there, 

I tried today everything to get my project to numba, but I have still the same problem and I hope you can help me. 

by compiling I get this: 

tweetSentiment.py
C:\Users\marc_\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py:153: NumbaDeprecationWarning: The 'target' keyword argument is deprecated.
  warnings.warn("The 'target' keyword argument is deprecated.", NumbaDeprecationWarning)
Traceback (most recent call last):
  File "..\tweetSentiment.py", line 22, in <module>
    def func():
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py", line 215, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
TypeError: __init__() got an unexpected keyword argument 'locals'

Hope you can help

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
