### ISSUE TITLE
GDB doesn't work with parallel=True.

### ISSUE THREAD

**Issue by DrTodd13** [numba/numba#7519]
```
import numba
import numpy as np

@numba.njit(debug=True, cache=True, parallel=True)
def test(a):
    b = a+5
    print(b.shape)
    numba.gdb()
    return b

a = np.ones(1000)
b = test(a)
print(b.shape)
```

It seems that the sched parameter introduced by parallel=True isn't in the fndesc typemap so you get a KeyError in debuginfo.py, mark_subprogram.

**Comment by sklam** [comment]
I tried running this but I didn't get any `KeyError`.

**Comment by stuartarchibald** [comment]
Thanks for the report. I cannot seem reproduce either. I also wonder if it's actually that `parallel=True` does not work with `DebugInfo` support, shouldn't the typemap always be valid?

**Comment by gmarkall** [comment]
I also don't get any `KeyError` running this. @DrTodd13 can you provide some additional info on how to reproduce this please?

Or, can it be closed?

**Comment by gmarkall** [comment]
I still can't reproduce this - if this no longer reproduces, can we close the issue?

**Comment by stuartarchibald** [comment]
> I still can't reproduce this - if this no longer reproduces, can we close the issue?

I cannot reproduce either for the OP, or the the OP with/without `NUMBA_DEBUGINFO=1`. Closing assumed fixed/something dev environment related. @DrTodd13 if this becomes reproducible/you see it again please do reopen this, many thanks.
