### ISSUE TITLE
trying to pick random numbers on a simple array fails

### ISSUE THREAD

**Issue by maallen3** [numba/numba#7520]
import numpy as np

@njit()
def rand_choice_nb_bool(boolval, *arr_prob):
    arr = arr_prob[0]
    prob = arr_prob[1]
    if boolval==1:
        return arr[np.searchsorted(np.cumsum(prob), np.random.random(), side="right")]
    else:
        return 0

    
x = np.array([0, 1, 0,1,1])
f = lambda x: rand_choice_nb_bool(x,np.array([1,2,3,4]),np.array([0.25,0.25, 0.25,0.25]))
vals = f(x)

**Comment by maallen3** [comment]
Ignore the docstrings, they are old.

**Comment by stuartarchibald** [comment]
@maallen3 thanks for reporting this, I presume as this is closed the problem was resolved? Thanks again!
