### ISSUE TITLE
numpy.clip accept numpy.array for a_max

### ISSUE THREAD

**Issue by Twomem** [numba/numba#7521]
---
Hi Numba team,
Thanks for your contributions. Please could you add support of numpy.clip() so that it can accept a numpy.array() as the a_max and a_min?

The example code below works when running normally, but does not work when using @njit.

`mask = a > b;
out[mask] = (np.clip(c, 0, d)[mask])
`
where mask is a boolean of length 1000
c.shape = (1000, 10, 10)
d.shape = (1000, 10, 10) (i.e. not just a number)

I get this error when running with @jit(nopython=True)
"numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function clip at 0x000001F8477D5C10>) found for signature:
 
 >>> clip(array(float64, 3d, C), Literal[int](0), array(int32, 3d, C))
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload in function 'np_clip': File: numba\np\arrayobj.py: Line 1805.
     With argument(s): '(array(float64, 3d, C), int64, array(int32, 3d, C))':
    Rejected as the implementation raised a specific error:
      TypingError: The argument "a_max" must be a number"

**Comment by gmarkall** [comment]
Marking as a feature request. It may be a good second issue for someone who's already had a little success in extending Numba.

**Comment by Twomem** [comment]
Thanks, gmarkall, for acknowledging this request :) Do you have any idea when this update might be implemented?

**Comment by jeertmans** [comment]
Hello @Twomem, I think the best way to implement this would be to stick to Numpy's way, i.e. broadcasting `a_min` and `a_max` into the same shape as input array `a`. Then, one could simply changes a few lines in [L1901-L1940](https://github.com/numba/numba/blob/master/numba/np/arrayobj.py#L1901-L1940): https://github.com/numba/numba/blob/f41b7e3292bfc7adc230fac694fb3429259bdab3/numba/np/arrayobj.py#L1901-L1940

However, it seems like Numba does not currently support broadcasting, i.e., `broadcast_to`, which would make the task harder.

Maybe a temporary solution would be to allow both scalar inputs and inputs that have the exact same shape as `a`?

**Comment by gmarkall** [comment]
Support for `broadcast_to` was merged recently: https://github.com/numba/numba/pull/7119

**Comment by Twomem** [comment]
Hi @jeertmans and @gmarkall , thanks for getting back to me. Great to know broadcasting is now supported. Could you clarify what you mean by "one could simply change(s) a few lines in L1901-1940"? would this be to just comment out L1905-L1909? I am unsure whether you mean that np.clip can take ndarrays in the a_max and a_min as this seemed to cause the original error, not the broadcasting issue?

**Comment by gmarkall** [comment]
I think @jeertmans might have been suggesting that the `isinstance` checks could be modified such that they check whether `a_min` and `a_max` are either `None`, a number, or an array with the same shape as the input. I'd expect the implementation would also need modifying for the case where the min/max values are an array of the same shape as the input too.

**Comment by jeertmans** [comment]
Hi @Twomem, based on [the following](https://numpy.org/doc/stable/reference/generated/numpy.clip.html)
```
a_min, a_maxarray_like or None
    Minimum and maximum value. If None, clipping is not performed on the corresponding edge. Only one of a_min and a_max 
    may be None. Both are broadcast against a.
```
you should only consider two cases: `None` and array-like (scalars and ndarrays) objects. For the second, you can simply (1) broadcast `a_min` and `a_max` against `a`, then iterate through each triplet of values using, e.g., `array.iter` so that the shape does not matter anymore.

Hope it helps!

**Comment by czgdp1807** [comment]
I think I can work on this. Please let me know if that's okay.

**Comment by Twomem** [comment]
Hi @czgdp1807 , that would be great if you could look into this, thanks! Would it be possible to make similar edits to numpy.minimum as well? I am working on a project which uses these two numpy functions in the computation, if I could get this project to work with numba and I can achieve a performance enhancement, I would use this to pitch numba to my company to explored further and incorporated in our modelling. For context, I work at a energy market modelling company where we have several models, all of which have run times on the order or hours or days so if I can demonstrate numba working, this could be pivotal for our company! Many thanks :)

**Comment by czgdp1807** [comment]
Sure. I would start working on this on Wednesday if no objections raised or blockers found until then.

**Comment by Twomem** [comment]
Great, thanks @czgdp1807 !
