### ISSUE TITLE
[Docs] Jitclass support for type annotation not documented on main page

### ISSUE THREAD

**Issue by jeertmans** [numba/numba#7540]
Hello,

In my opinion, the fact that the `jitclass` decorator supports type annotation (see #5609) inference should be documented on [this page](https://numba.pydata.org/numba-doc/dev/user/jitclass.html). When searching for reference about jitting Python classes, this is the first page that appears, so I think it's best to document this feature there too ;-)

Or Maybe it was done with purpose due to the experimental state of this feature?

If you need someone to document this, I can do it!

Thanks in advance

**Comment by esc** [comment]
@jeertmans thank you for asking about this. We did have some SEO issues in the past, which is probably why you ended up on the documentation for Numba 0.52 -- not 0.54.

There is a ticket open about this here:

https://github.com/numba/numba/issues/6677

So, I believe, what you are looking for is already documented here:

https://numba.readthedocs.io/en/stable/user/jitclass.html?highlight=jitclass#inferred-class-member-types-from-type-annotations-with-as-numba-type

Is this correct?

**Comment by jeertmans** [comment]
Indeed @esc it seems to be related to that problem. I will be more careful next time and I hope that search engines will update to refer to the correct site :)

I think I can close this then.

**Comment by esc** [comment]
> Indeed @esc it seems to be related to that problem. I will be more careful next time and I hope that search engines will update to refer to the correct site :)

No worries, this is a "gotcha" for many people. It's quite unfortunate. 

> I think I can close this then.

Thank you for following up and thank you for your effort.
