### ISSUE TITLE
List.insert() crashes for Numpy arrays

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#7553]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This code segfaults for me (on Mac OS). Didn't see an obvious issue in insert's implementation with a quick look.
```python
import numpy as np
import numba

@numba.njit
def f():
    l = [np.ones(3)]
    l.insert(0, np.ones(3))
    return l

f()
```

**Comment by ehsantn** [comment]
I think I found the issue. The setitem call here decrefs the old value but it shouldn't. I'd be happy to submit a PR if this sounds correct.
https://github.com/numba/numba/blob/805e24fbd895d90634cca68c13f4c439609e9286/numba/cpython/listobj.py#L982

**Comment by esc** [comment]
@ehsantn thank you for raising this. Will the suggested fix take care of the segfault? If so, please do prepare a PR so we can run it though CI? What kind of patch would you propose?

BTW: I can confirm I am able to reproduce this on OSX with Python 3.9 and current `HEAD` at `5fc9d3c56da4e4c6aef7189e588ce9c44263d4a6`.

**Comment by ehsantn** [comment]
Yes, it fixes the segfault. It's a small change. Will open a PR soon.

**Comment by esc** [comment]
> Yes, it fixes the segfault. It's a small change. Will open a PR soon.

Thank you! 🙏

**Comment by ehsantn** [comment]
Linking a pull request doesn't count as activity?

**Comment by esc** [comment]
@ehsantn apparently not, no.

**Comment by esc** [comment]
it was the `needtriage` label that triggered stale-bot, I have removed it now.
