### ISSUE TITLE
Unknown attribute 'to_device' module 'numba.cuda'

### ISSUE THREAD

**Issue by louisadamian** [numba/numba#7555]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When trying to use numba.cuda.jit moving ndarrays to the gpu I get the error `Unknown attribute 'to_device'` I am not sure what is wrong.

```python
import numpy as np 
from numba import cuda
   @cuda.jit 
def cuda_func( output: np.ndarray, ):
     out_shared = cuda.to_device(output) 
    for i in range(len(output)):
         pass


   if __name__ == '__main__': 
    tpb = 32     output = np.zeros(shape=(3, 3), dtype=np.bool_)
     cuda_func[32 + (tpb - 1) // tpb, tpb](output) 
```

**Comment by gmarkall** [comment]
You can't transfer data to the device inside a kernel - you need to transfer it outside the kernel, prior to the launch.

It's probably worth working through the CUDA tutorial to get an idea of how to get started with the CUDA target: https://github.com/numba/nvidia-cuda-tutorial

**Comment by louisadamian** [comment]
Thank you, Will do.
