### ISSUE TITLE
No correct way to write a vectorized cuda kernel

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [numba/numba#7558]
It seems that eager compilation is depreciated as the example from the docs raises an error.
```python
import math
from numba import vectorize, cuda
import numpy as np

@vectorize(['float32(float32, float32, float32)',
            'float64(float64, float64, float64)'],
           target='cuda')
def cu_discriminant(a, b, c):
    return math.sqrt(b ** 2 - 4 * a * c)

N = 10000
dtype = np.float32

# prepare the input
A = np.array(np.random.sample(N), dtype=dtype)
B = np.array(np.random.sample(N) + 10, dtype=dtype)
C = np.array(np.random.sample(N), dtype=dtype)

D = cu_discriminant(A, B, C)
```

The official mitigation for this depreciation is to remove the signature. However when doing this we get an error:

```python
import math
from numba import vectorize, cuda
import numpy as np

@vectorize(target='cuda')
def cu_discriminant(a, b, c):
    return math.sqrt(b ** 2 - 4 * a * c)

N = 10000
dtype = np.float32

# prepare the input
A = np.array(np.random.sample(N), dtype=dtype)
B = np.array(np.random.sample(N) + 10, dtype=dtype)
C = np.array(np.random.sample(N), dtype=dtype)

D = cu_discriminant(A, B, C)
```
raises: `No matching version.  GPU ufunc requires array arguments to have the exact types.  This behaves like regular ufunc with casting='no'`

(ran with '0.54.1')

**Comment by esc** [comment]
@GuillaumeLeclerc thank you for raising this! @gmarkall would you be able to take a look at this?

**Comment by gmarkall** [comment]
The current version of Numba master doesn't raise the error anymore. We should check when the RC is cut that it still doesn't occur, then close this issue if that's the case at that point. For that reason, I'm adding this to the 0.55RC milestone, but no action is needed right now.

**Comment by gmarkall** [comment]
I can confirm the behaviour has not changed (and is not planned to change) so I'm closing this now as the error doesn't appear with the reproducer on master.
