### ISSUE TITLE
Documentation Cuda example wrong indentation

### ISSUE THREAD

**Issue by athompson673** [numba/numba#7571]
I am just reading up about Cuda for the first time, so I may be wrong here, but it seems there's a typo in the [cuda example](https://numba.pydata.org/numba-doc/latest/cuda/examples.html) in the documentation:

```
    # Each thread computes one element in the result matrix.
    # The dot product is chunked into dot products of TPB-long vectors.
    tmp = 0.
    for i in range(bpg):
        # Preload data into shared memory
        sA[tx, ty] = A[x, ty + i * TPB]
        sB[tx, ty] = B[tx + i * TPB, y]

        # Wait until all threads finish preloading
        cuda.syncthreads()

        # Computes partial product on the shared memory
        for j in range(TPB):
            tmp += sA[tx, j] * sB[j, ty]

        # Wait until all threads finish computing
        cuda.syncthreads()

    C[x, y] = tmp
```

should be: (indentation of syncthreads and partial product computation)

```
    # Each thread computes one element in the result matrix.
    # The dot product is chunked into dot products of TPB-long vectors.
    tmp = 0.
    for i in range(bpg):
        # Preload data into shared memory
        sA[tx, ty] = A[x, ty + i * TPB]
        sB[tx, ty] = B[tx + i * TPB, y]

    # Wait until all threads finish preloading
    cuda.syncthreads()

    # Computes partial product on the shared memory
    for j in range(TPB):
        tmp += sA[tx, j] * sB[j, ty]

    # Wait until all threads finish computing
    cuda.syncthreads()

    C[x, y] = tmp
```

It would seem the source on [master](https://github.com/numba/numba/blob/master/numba/cuda/tests/doc_examples/test_matmul.py#L77-L84) is somewhat different to the currently live docs, but still has a similar issue.

**Comment by gmarkall** [comment]
The documentation linked in the issue is for Numba 0.50 - it has since been modified, and the latest version is at: https://numba.readthedocs.io/en/latest/cuda/examples.html - PR #7330 also added CI testing of this example.

Does the code in the latest version still look incorrect?

**Comment by gmarkall** [comment]
Closing as I believe the issue is resolved.
