### ISSUE TITLE
numba 0.54.1 casting IntEnum regression

### ISSUE THREAD

**Issue by nelson2005** [numba/numba#7573]
numba 0.54.1
python 3.7.3
windows 10

This was first reported in [discourse](https://numba.discourse.group/t/casting-intenum-to-numba-int16/1005)

This code works in plain python and numba 0.53.1 but fails with numba 0.54.1

```python
from enum import IntEnum
import numba

class PmtType(IntEnum):
    LEVELA = 1
    LEVELB = 2

@numba.njit
def tester():
    return numba.int16(PmtType.LEVELA)

print(tester())
```
Error is

> File “int_enum.py”, line 16, in
> print(tester())
> File “C:\work\git\mims\venv\lib\site-packages\numba\core\dispatcher.py”, line 482, in _compile_for_args
> error_rewrite(e, ‘typing’)
> File “C:\work\git\mims\venv\lib\site-packages\numba\core\dispatcher.py”, line 423, in error_rewrite
> raise e.with_traceback(None)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(int16) found for signature:
> 
> (IntEnum(PmtType))
> 
> There are 2 candidate implementations:
> 
> Of which 2 did not match due to:
> Overload in function ‘make_callable_template..generic’: File: numba\core\typing\templates.py: Line 174.
> With argument(s): ‘(IntEnum(PmtType))’:
> Rejected as the implementation raised a specific error:
> TypingError: Casting IntEnum(PmtType) to int16 directly is unsupported.
> raised from C:\work\git\mims\venv\lib\site-packages\numba\core\typing\builtins.py:818
> During: resolving callee type: class(int16)
> During: typing of call at C:/work/git/ims_core/playground/erik/discourse/int_enum.py (14)
> 
> File “int_enum.py”, line 14:
> def tester():
> return numba.int16(PmtType.LEVELA)
> ^
> Process finished with exit code 1
>

**Comment by gmarkall** [comment]
I can reproduce this. This was introduced by f2311d20934a883dde3a2050ff947ff0f5d07977.

**Comment by gmarkall** [comment]
(cc @testhound)
