### ISSUE TITLE
values in a list become odd in nopython mode and no warning or error reported

### ISSUE THREAD

**Issue by dlee992** [numba/numba#7577]
## Reporting a bug

```
In [1]: from numba import njit
   ...: @njit
   ...: def f():
   ...:     lst = []
   ...:     lst.append(1)
   ...:     lst.append(None)
   ...:     a = 0.2
   ...:     lst.append(0.1 if a < 1 else None)
   ...:     return lst
   ...:

In [2]: f()
Out[2]: [5e-324, None, 0.1]  ## should be [1.0, None, 0.1]
```

I use python 3.8.8 & numba 0.54.0 & llvmlite 0.37.0 and tested this code snippet in my macbook pro.

I think this is a type inference error in numba internal.

Besides, my purpose is that a list can store float or None, I think numba.typed.List cannot store None value, so I have to use reflected list as above. Any other option to implement my purpose?

I would like to contribute a PR about this error if you guys confirm this is really a bug. Please give me some hints about how to fix this in numba internal.

**Comment by esc** [comment]
@dlee992 thank you for asking about this. You can try to use `1.0` instead of `1`:

```
from numba import njit

@njit
def f():
    lst = []
    lst.append(1.0)
    lst.append(None)
    a = 0.2
    lst.append(0.1 if a < 1 else None)
    return lst

print(f())
```

**Comment by dlee992** [comment]
@esc , Yes, it does. But I can make up another bug like this (Actually, maybe I can make up a lot of bugs like this):

```
In [1]: from numba import njit

In [2]: @njit
   ...: def g():
   ...:     return 0.1
   ...:

In [3]: @njit
   ...: def f():
   ...:     lst = []
   ...:     # lst.append(None)
   ...:     # lst.append(None)
   ...:     a = g()
   ...:     lst.append(0.1 if a < 1 else None)
   ...:     lst.append(0.1)
   ...:     for _ in range(1):
   ...:         lst.append(None)
   ...:     return lst
   ...:

In [4]: f()
Out[4]: [0.1, None, None]  ## should be [0.1, 0.1, None]
```

How to workaround this?

**Comment by dlee992** [comment]
I really met this kind of bug in my project, which really contains similar code structure as above. -_-

**Comment by esc** [comment]
> I really met this kind of bug in my project, which really contains similar code structure as above. -_-

Interesting! Thank you for raising this. I can reproduce! This may indeed be a genuine bug.

**Comment by stuartarchibald** [comment]
I think this points towards the root cause of this:
```python
from numba import njit
@njit
def f():
    lst = []
    a = 0.2
    lst.append(None)
    # In [2]: np.float64(1.23).view(np.int64)
    # Out[2]: 4608218246714312622
    lst.append(4608218246714312622) # float 1.23
    lst.append(0.1 if a < 1 else None)
    return lst

print(f())

```
the list is typed as `list(OptionalType(float64))`, but in appending an integer, it seems like no cast is made.

**Comment by stuartarchibald** [comment]
It also looks like each `list.append` call is being typed as a different Optional type, either `float64` or `intp`.

**Comment by dlee992** [comment]
@stuartarchibald , very cool! The `list` in `list(OptionalType(float64))` means which, `reflected list` or `typed list`? Can we declare sth like `lst = list(OptionalType(float64))` instead of `lst = []`, to tell numba the specifc type? In my second buggy case, numba transfer `0.1` to `None`, which is more surprising. Would you will fix this bug asap? I don't know whether I could fix this bug, but I will also give it a try.

**Comment by dlee992** [comment]
@esc @stuartarchibald , right now, do we have any idea to workaround this kind of case before fixing it? I try to append -0.1234 instead of None, but it still fails to return correct list ... -_-

**Comment by stuartarchibald** [comment]
@dlee992 this was discussed at the triage meeting the other day. Conclusion was that because the (reflected) `list` implementation predates `Optional` it cannot safely handle your case as there's no type casting present, further, `numba.typed.List` explicitly rejects the handling of `Optional` types. This unfortunately means that there's no work around at present but you may be able to get away with it if you have a type stable `Optional`, i.e. everything added is either `None` or "some consistent type" (e.g. everything added is a `float64`).

Example: this works as everything is `None` or `float64`:
```python
from numba import njit
@njit
def f():
    lst = []
    a = 0.2
    lst.append(None)
    lst.append(1.23)
    lst.append(0.1 if a < 1 else None)
    lst.append(None)
    lst.append(4.56)
    return lst

print(f())
```

**Comment by dlee992** [comment]
@stuartarchibald , thanks, it makes sense.

**Comment by dlee992** [comment]
since the explanation in https://github.com/numba/numba/issues/8637, I will close this one too.
