### ISSUE TITLE
Compilation with `parallel=True` gives garbage results for a very simply parallelizable function

### ISSUE THREAD

**Issue by sztal** [numba/numba#7578]
I have a relatively simple (and seemingly easily parallelizable) function for which I get different results when compiling with `parallel=True` and `parallel=False`. I guess that there must be some race conditions at play, but I really cannot see why.

I am not 100% sure whether it is a bug or just some fault in my code, but it was suggested to me on [SO](https://stackoverflow.com/questions/69958049/numba-parallel-true-produces-corrupted-results) that this might be a bug.

Below is a reproducible example.

```python
import numpy as np
from numba import njit, prange

def ubcm_jacobian(
    D: np.ndarray,
    b: np.ndarray
) -> np.ndarray:
    """Jacobian of UBCM negative log-likelihood.

    Parameters
    ----------
    D
        Degree sequence array.
    b
        Model parameters.
    """
    B = np.empty_like(b)
    b = np.exp(b)

    for i in prange(len(b)):
        bi   = b[i]
        x    = bi * b
        B[i] = (x / (1 + x)).sum()

    b2 = b**2
    B -= b2 / (1 + b2)

    return B - D


ubcm_not_parallel = njit(ubcm_jacobian, boundscheck=False, nogil=True, parallel=False)
ubcm_parallel = njit(ubcm_jacobian, boundscheck=False, nogil=True, parallel=True)

# Sample data
D = np.arange(1, 11)
b = np.log(D)

# Results
x1 = ubcm_not_parallel(D, b)
x2 = ubcm_parallel(D, b)

assert np.allclose(x1, x2), "results are not equal"
```

# Expected behavior

Of course the expected behavior is that the function should return identical results (up to the floating point precision) in both cases.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. MWR:
```python
import numpy as np
from numba import njit, prange

def foo(x):
    A = np.zeros_like(x)
    tmp = np.cos(x) # this can be any 1-arity ufunc

    for i in prange(len(x)):
        A[i] = tmp.sum()

    return A

foo_serial = njit(foo)
foo_parallel = njit(foo, parallel=True)

x = np.arange(10.)

x1 = foo(x)
x2 = foo_serial(x)
x3 = foo_parallel(x)

print(f"Python:\n{x1}")
print(f"Serial:\n{x2}")
print(f"Parallel:\n{x3}")

assert np.allclose(x1, x2), "results are not equal, serial"
assert np.allclose(x1, x3), "results are not equal, parallel"
```
gives:
```
$ python issue7578.py 
Python:
[0.42162378 0.42162378 0.42162378 0.42162378 0.42162378 0.42162378
 0.42162378 0.42162378 0.42162378 0.42162378]
Serial:
[0.42162378 0.42162378 0.42162378 0.42162378 0.42162378 0.42162378
 0.42162378 0.42162378 0.42162378 0.42162378]
Parallel:
[-1.22680415e+58 -1.09049258e+58 -9.54181004e+57 -8.17869432e+57
 -6.81557860e+57 -5.45246288e+57 -4.08934716e+57 -2.72623144e+57
 -1.36311572e+57  4.21623783e-01]
Traceback (most recent call last):
  File "issue7578.py", line 27, in <module>
    assert np.allclose(x1, x3), "results are not equal, parallel"
AssertionError: results are not equal, parallel
```
CC @DrTodd13

**Comment by sztal** [comment]
Thanks for looking at this so quickly! I have one more remark (just in case it matters).

In my function the out-of-loop array `B` which is populated with values by the main loop is initialized to _empty_ values. In your reprex it is initialized to zeros. This probably does not matter for testing the problem, but I am mentioning this in case it may matter. And in practice this is sometimes important as initializing _empty_ arrays is much faster than zero arrays.

**Comment by stuartarchibald** [comment]
> Thanks for looking at this so quickly! I have one more remark (just in case it matters).
> 
> In my function the out-of-loop array `B` which is populated with values by the main loop is initialized to _empty_ values. In your reprex it is initialized to zeros. This probably does not matter for testing the problem, but I am mentioning this in case it may matter. And in practice this is sometimes important as initializing _empty_ arrays is much faster than zero arrays.

Thanks for the note. I made it zeros to flush the memory to try and see if it was junk from the original uninitialised memory or junk from something else. Indeed, for performance, don't allocate zeros unless you _really_ need to!

**Comment by stuartarchibald** [comment]
Also, @DrTodd13, I think this is an issue with loop fusion, the `np.cos()` loop is being fused with the `prange`, but the `prange` body has a reduction on the result. Adding in a function call to prevent fusion leads to the MWR working:
```python
import numpy as np
from numba import njit, prange

@njit
def sink():
    pass

def foo(x):
    A = np.zeros_like(x)
    tmp = np.cos(x) # this can be any 1-arity ufunc
    sink()
    for i in prange(len(x)):
        A[i] = tmp.sum()

    return A

foo_serial = njit(foo)
foo_parallel = njit(foo, parallel=True)

x = np.arange(10.)

x1 = foo(x)
x2 = foo_serial(x)
x3 = foo_parallel(x)

print(f"Python:\n{x1}")
print(f"Serial:\n{x2}")
print(f"Parallel:\n{x3}")

print(foo_parallel.parallel_diagnostics(level=4))

assert np.allclose(x1, x2), "results are not equal, serial"
assert np.allclose(x1, x3), "results are not equal, parallel"
```
