### ISSUE TITLE
Initializing and returning a custom dtype array/record from njit causes garbled data

### ISSUE THREAD

**Issue by tpitkanen** [numba/numba#7599]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,

I found the following issue: Numba allows initializing a custom `numpy.dtype` array/record with `numpy.zeros()` inside a `numba.njit` function, but the values are sometimes non-zero.

Unlike `numpy.zeros()`, `numpy.ones()` and `numpy.full()` throw a `Numba.TypingError` ("No implementation of function Function(<function ones at 0x00000182EACAD9D0>) found for signature: ..." etc.).

The [Supported NumPy features page](https://numba.readthedocs.io/en/0.54.1/reference/numpysupported.html) states that "`numpy.zeros()` (only the 2 first arguments)" is supported, but I think this only applies for simple dtypes like `numpy.float64`.

I discovered the issue when a program that should have been deterministic was randomly crashing or getting stuck.

Version information: 64-bit Python 3.8.10 and Numba 0.54.1 on Windows 10.

```python
import numba
import numpy as np


point_dtype = np.dtype([
    ("x", np.float64),
    ("y", np.float64),
    ("z", np.float64)
])


@numba.njit()
def zeros_array():
    # [(0., 0., 0.)]
    point = np.zeros((1,), dtype=point_dtype)
    return point


@numba.njit()
def zeros_array2():
    # [(1., 2., 3.)]
    point = np.zeros((1,), dtype=point_dtype)
    point[0]["x"] = 1.0
    point[0]["y"] = 2.0
    point[0]["z"] = 3.0
    return point


@numba.njit()
def zeros_array_print():
    # [(0., 0., 0.)]
    # -9.868309920863368e+148
    point = np.zeros((1,), dtype=point_dtype)
    print(point)
    print(point[0]["x"])


@numba.njit()
def zeros_array_print2():
    # [(0., 0., 0.)]
    # 0.0
    # [(0., 0., 0.)]
    point = np.zeros((1,), dtype=point_dtype)
    print(point)
    print(point[0]["x"])
    print(point)


@numba.njit()
def zeros_record():
    # (-9.86830992e+148, -9.86830992e+148, -9.86830992e+148)
    point = np.zeros((1,), dtype=point_dtype)[0]
    return point


@numba.njit()
def ones_array():
    # numba.TypingError
    point = np.ones((1,), dtype=point_dtype)
    return point


@numba.njit()
def ones_record():
    # numba.TypingError
    point = np.ones((1,), dtype=point_dtype)[0]
    return point


@numba.njit()
def full_array():
    # numba.TypingError
    point = np.full((1,), 0, dtype=point_dtype)
    return point


@numba.njit()
def full_record():
    # numba.TypingError
    point = np.full((1,), 0, dtype=point_dtype)[0]
    return point


def main():
    za = zeros_array()
    print(za)
    print()

    za2 = zeros_array2()
    print(za2)
    print()

    zeros_array_print()
    print()

    zeros_array_print2()
    print()

    zr = zeros_record()
    print(zr)
    print()

    try:
        oa = ones_array()
        print(oa)
    except numba.TypingError as e:
        print(e)
    print()

    try:
        or_ = ones_record()
        print(or_)
    except numba.TypingError as e:
        print()
    print()

    try:
        fa = full_array()
        print(fa)
    except numba.TypingError as e:
        print(e)
    print()

    try:
        fr = full_record()
        print(fr)
    except numba.TypingError as e:
        print()
    print()


if __name__ == "__main__":
    main()

```

**Comment by tpitkanen** [comment]
From [#5853](https://github.com/numba/numba/issues/5853#issuecomment-893275330):

> The issue is that the structured type has its reference count decremented while there's still something pointing at one of its members.

That explains why `zeros_array_print2` works and `zeros_array_print` doesn't.

I would have expected `zeros` to behave like `ones` and `full` do and throw a `TypingError`, but I guess those are different.

Closing this as a duplicate, thanks.

**Comment by stuartarchibald** [comment]
> I would have expected zeros to behave like ones and full do and throw a TypingError, but I guess those are different.

IIRC `np.zeros` goes via `memset(3)`, whereas `np.ones` is doing `np.empty` and then assigning a `1` into each element, the typing error is coming from the `setitem` associated with this assignment.

Thanks for closing this as a duplicate.
