### ISSUE TITLE
njit with parallel=True causes fatal Python error and aborted

### ISSUE THREAD

**Issue by dlee992** [numba/numba#7611]
# Reporting a bug

```
import time
import unittest
import pandas as pd
import numpy as np
from numba import njit, prange, typed

num_columns, num_rows, num_borders = 50, 100_000, 20
target_col = 'col0'

features = [f'col{i}' for i in range(num_columns)]
input_df = pd.DataFrame(np.random.rand(num_rows, num_columns), columns=features)
borders = tuple([x/100 for x in range(0, 100, 3)][:num_borders])


# ndarray_2d: N * M, ndarray_1d: N
def _compute(ndarray_2d, ndarray_1d, numba_list):
    for i in prange(len(borders)):
        filtered = (ndarray_2d >= borders[i]).astype(np.int_) # filtered: N * M
        filtered_1d = filtered.sum(axis=0).astype(np.float_) # filtered_1d: M
        another_filtered_1d = (filtered.transpose() * ndarray_1d).sum(axis=1) # another_filtered_1d: M
        for item in zip(filtered_1d, another_filtered_1d):
            numba_list.extend(item)


class MyTestCase(unittest.TestCase):
    @staticmethod
    def test_something():
        numba_list = typed.List()
        numba_list.append(0.1)
        ndarray_2d = input_df.to_numpy()
        ndarray_1d = input_df[target_col].to_numpy()

        njit_parallel_func = njit(parallel=True)(_compute)
        # njit_parallel_func(ndarray_2d, ndarray_1d, numba_list)

        python_func = _compute
        numba_list = []
        start_time = time.time()
        python_func(ndarray_2d, ndarray_1d, numba_list)
        print(f'python time = {time.time() - start_time}s')

        njit_func = njit(_compute)
        for _ in range(5):
            numba_list = typed.List()
            numba_list.append(0.1)
            middle_time = time.time()
            njit_func(ndarray_2d, ndarray_1d, numba_list)
            print(f'njit time = {time.time() - middle_time}s')


if __name__ == '__main__':
    unittest.main()

```

In this test code:

1. if uncomment `njit_parallel_func(ndarray_2d, ndarray_1d, numba_list)`, python process will be killed by sth bad happend in numba internal.
```
test_parallel.py::MyTestCase::test_something Fatal Python error: Aborted

Thread 0x000000011094f600 (most recent call first):
  File "/Users/.../debug-numba/test_parallel.py", line 36 in test_something
  File "/usr/local/anaconda3/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
  File 
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
I think this is a bug with `parallel=True`

2. Besides, the function `_compute()` run much slower than pure python, I couldn't figure it out where I don't write well for numba compilation.
```
python time = 0.7888021469116211s
njit time = 8.057817935943604s
njit time = 4.105954885482788s
njit time = 4.527366876602173s
njit time = 4.559357166290283s
njit time = 4.574266672134399s
```

3. I haven't check out whether the final `numba_list`s are equal.

Mac & conda env: Python 3.8.8 & numba  0.54.0 & numpy 1.19.5

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect this is due to mutating a list in a parallel region, which is not supported as such containers are not threadsafe. xref docs: https://numba.readthedocs.io/en/stable/user/parallel.html#unsupported-operations.

**Comment by sklam** [comment]
> if uncomment njit_parallel_func(ndarray_2d, ndarray_1d, numba_list), python process will be killed by sth bad happend in numba internal.

Pretty sure it is problem due to mutating list in parallel region as noted by @stuartarchibald. This issue is tracking at https://github.com/numba/numba/issues/2408

> Besides, the function _compute() run much slower than pure python, I couldn't figure it out where I don't write well for numba compilation.

Problem seems to come from:
```python
another_filtered_1d = (filtered.transpose() * ndarray_1d).sum(axis=1)
```
`filtered` and `ndarray_1d` end up being strided by 400 bytes. The numba implementation is generating a loop that operates on such layout and is very inefficient. 

I believe nowadays numpy would do a better job here with chunking. Something that Numba needs to starting doing to stay competitive on strided arrays.

**Comment by dlee992** [comment]
Did https://github.com/numba/numba/pull/7622 fix this issue?

**Comment by dlee992** [comment]
close it for now.
