### ISSUE TITLE
clamp tbb to 2021 on the 0.55 release branch

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#7620]
Reminder to clamp TBB to 2021 on the 0.55 release branch.
Here:
https://github.com/numba/numba/blob/db8defef546009694491a03837acf8e91a7195b5/buildscripts/condarecipe.local/meta.yaml#L52
and here:
https://github.com/numba/numba/blob/db8defef546009694491a03837acf8e91a7195b5/buildscripts/condarecipe.local/meta.yaml#L43
and here:
https://github.com/numba/numba/blob/db8defef546009694491a03837acf8e91a7195b5/buildscripts/condarecipe.local/meta.yaml#L69

**Comment by sklam** [comment]
closed by https://github.com/numba/numba/pull/7661
