### ISSUE TITLE
NumbaIRAssumptionWarning: variable 'a.1.1' is not in scope.

### ISSUE THREAD

**Issue by mhostetter** [numba/numba#7623]
I encountered this warning (bug?) with Numba 0.54.0 and 0.54.1 in my Python package https://github.com/mhostetter/galois/issues/178. A minimal reproducer is included below.

I'm not sure why the "pedantic check" is complaining, but it seems related to the lambda function and the fact the lambda arguments `a` and `b` are the same as the JIT function arguments. When the lamba arguments are renamed to `aa` and `bb`, the warnings go away.

## Minimal Example

```python
import numpy as np
print("numpy version:", np.__version__)

import numba
print("numba version:", numba.__version__)


@numba.extending.register_jitable(inline="always")
def my_xor(a, b):
    a <<= 1
    return a ^ b

x = np.array([1, 2, 3, 4, 5, 6], dtype=np.int64)
y = np.array([2, 2, 2, 2, 2, 2], dtype=np.int64)

print("Test Case 1: Default")
ufunc = numba.vectorize(["int64(int64, int64)"], nopython=True)(my_xor)
print(ufunc(x, y), "\n")

print("Test Case 2: Lambda same names")
ufunc = numba.vectorize(["int64(int64, int64)"], nopython=True)(lambda a, b: my_xor(a, b))
print(ufunc(x, y), "\n")

print("Test Case 3: Lambda different names")
ufunc = numba.vectorize(["int64(int64, int64)"], nopython=True)(lambda aa, bb: my_xor(aa, bb))
print(ufunc(x, y), "\n")
```

## Numba 0.53.1 Output

```python
numpy version: 1.20.3
numba version: 0.53.1
Test Case 1: Default
[ 0  6  4 10  8 14] 

Test Case 2: Lambda same names
[ 0  6  4 10  8 14] 

Test Case 3: Lambda different names
[ 0  6  4 10  8 14]
```

## Numba 0.54.1 Output

```python
numpy version: 1.20.3
numba version: 0.54.1
Test Case 1: Default
[ 0  6  4 10  8 14] 

Test Case 2: Lambda same names
/home/matt/.local/lib/python3.8/site-packages/numba/core/ssa.py:272: NumbaIRAssumptionWarning: variable 'a.1.1' is not in scope.

This warning came from an internal pedantic check. Please report the warning
message and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new?template=bug_report.md

  warnings.warn(errors.NumbaIRAssumptionWarning(wmsg,
[ 0  6  4 10  8 14] 

Test Case 3: Lambda different names
[ 0  6  4 10  8 14]
```

**Comment by esc** [comment]
> Yes, I can confirm current `master` ([4469f04](https://github.com/numba/numba/commit/4469f04e0f4916d2541e15b38d71d10268fca73f)) does not manifest this warning.
> 
> ```python
> numpy version: 1.20.3
> numba version: 0.55.0dev0+877.g4469f04e0
> Test Case 1: Default
> [ 0  6  4 10  8 14] 
> 
> Test Case 2: Lambda same names
> [ 0  6  4 10  8 14] 
> 
> Test Case 3: Lambda different names
> [ 0  6  4 10  8 14]
> ```
> 
> I have a workaround for my library (changing the variable names in the lambda), but thought I'd raise it here. I wasn't sure if there should be warnings for any case, none, or all?

OK, thank you. I assume that there should never have been a warning and that this was probably fixed during the latest (0.55) development cycle. I will close this issue now. It should be fixed with the upcoming 0.55 (soon). Thank you again for reporting this, your help to improve Numba is appreciated.
