### ISSUE TITLE
Caching doesn't work in Jupyter notebook on macOS

### ISSUE THREAD

**Issue by ylieder** [numba/numba#7646]
When trying to compile a Numba function with `cache=True` in a Jupyter notebook, the following error occurs:

```
RuntimeError: cannot cache function 'func': no locator available for file '/var/folders/xc/gg95jg7j1z94g_qds0gqpxxc0000gn/T/ipykernel_9751/3025015800.py'
```

- Python version: 3.8.9
- Numba version: 0.54.1
- OS: macOS Big Sur
- notebook version: 6.4.6

Numba and notebook are installed both in a virtual environment.
When running numba functions without caching in the notebook it works without problems. When running numba functions with caching within the same environment, but from a python script, it also works fine.

**Steps to reproduce:**
1. Create virtual environment `python3 -m venv ./.venv`
2. Install numba and notebook after activating the env `pip install numba=0.54.1 notebook==6.4.6`
3. Starting a notebook server and creating the following function
    ```
    from numba import jit

    @jit(nopython=True, cache=True)
    def func():
        return 3
    ```
4. Try to execute the cell

**Checklist:**
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Full stack trace:**
```
/var/folders/xc/gg95jg7j1z94g_qds0gqpxxc0000gn/T/ipykernel_9751/3025015800.py in <module>
      1 @jit(nopython=True, cache=True)
----> 2 def func():
      3     return 3

~/.../lib/python3.8/site-packages/numba/core/decorators.py in wrapper(func)
    217                           **dispatcher_args)
    218         if cache:
--> 219             disp.enable_caching()
    220         if sigs is not None:
    221             # Register the Dispatcher to the type inference mechanism,

~/.../lib/python3.8/site-packages/numba/core/dispatcher.py in enable_caching(self)
    875 
    876     def enable_caching(self):
--> 877         self._cache = FunctionCache(self.py_func)
    878 
    879     def __get__(self, obj, objtype=None):

~/.../lib/python3.8/site-packages/numba/core/caching.py in __init__(self, py_func)
    608         self._py_func = py_func
    609         self._impl = self._impl_class(py_func)
--> 610         self._cache_path = self._impl.locator.get_cache_path()
    611         # This may be a bit strict but avoids us maintaining a magic number
    612         source_stamp = self._impl.locator.get_source_stamp()

~/.../lib/python3.8/site-packages/numba/core/caching.py in __init__(self, py_func)
    345         else:
    346             raise RuntimeError("cannot cache function %r: no locator available "
--> 347                                "for file %r" % (qualname, source_path))
    348         self._locator = locator
    349         # Use filename base name as module name to avoid conflict between

RuntimeError: cannot cache function 'func': no locator available for file '/var/folders/xc/gg95jg7j1z94g_qds0gqpxxc0000gn/T/ipykernel_9751/3025015800.py'
```

**Comment by esc** [comment]
@ylieder thank you for reporting this! I believe there is an error in the reproduction instructions. The command to install the dependencies should be:

```
pip install numba==0.54.1 notebook==6.4.6
```

Unlike `conda`, `pip` does not support the single equals `=` syntax.

**Comment by esc** [comment]
@ylieder thank you again for reporting this. With the modified installation line as above I was able to reproduce this:

<img width="761" alt="Screen Shot 2021-12-13 at 12 06 48" src="https://user-images.githubusercontent.com/41563/145801663-fea5c5aa-0f93-49f8-ad42-68ac56214fe7.png">

**Comment by esc** [comment]
@ylieder I tried this with the `master` from today at: 8f3cd87a07 and it seems to work fine:

<img width="761" alt="Screen Shot 2021-12-13 at 12 14 20" src="https://user-images.githubusercontent.com/41563/145802705-74cc1573-60ad-4844-91a6-57b9c0f1b3fe.png">

I would assume that a pull-request during the current development cycle has fixed this and would assume that this will no longer be an issue with the upcoming 0.55 release.

**Comment by esc** [comment]
I am closing this issue now, assuming resolved. If this does persist after the release of 0.55.0 please don't hesitate to re-open this issue, thank you for your help to improve Numba!

**Comment by gmarkall** [comment]
Quick note: I would guess this was resolved by https://github.com/numba/numba/pull/7345
