### ISSUE TITLE
TypingError: No implementation of function Function(<function runtime_broadcast_assert_shapes at 0x7f8071985280>) found for signature: runtime_broadcast_assert_shapes(Literal[int](1), array(float64, 1d, C))

### ISSUE THREAD

**Issue by YYT1002** [numba/numba#7647]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba 0.54.1

TypingError: No implementation of function Function(<function runtime_broadcast_assert_shapes at 0x7f8071985280>) found for signature: runtime_broadcast_assert_shapes(Literal[int](1), array(float64, 1d, C))
 There are 2 candidate implementations: - Of which 2 did not match due to: Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 159. With argument(s): '(int64, array(float64, 1d, C))': Rejected as the implementation raised a specific error: TypeError: missing a required argument: 'arg1' raised from /Users/uqyyao4/anaconda3/lib/python3.8/inspect.py:2940

**Comment by esc** [comment]
@YYT1002 thank you for reporting this. Unfortunately we are not able to debug this given the limited amount of debugging information. May I kindly request you update the ticket with:

a) the code you were trying to run (or something that approximates it to give the same error)
b) what you expected
c) what happened instead (with a copy and paste of the full output including the original command)

Thank you in advance for your efforts to improve Numba!

**Comment by gmarkall** [comment]
Closing as the issue cannot be reproduced and no further information has been received.
