### ISSUE TITLE
Numba fails to install on Windows due to llvmlite error

### ISSUE THREAD

**Issue by ingframin** [numba/numba#7656]
I tried to install Numba using pip on Windows 10.
I have Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) .

I have Clang installed on my computer:
PS C:\Users\ingframin> clang -v
clang version 11.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw64\bin

Yet the installation of llvmlite fails with the error here below.
I don't understand what file is missing or what setting is wrong.
Installing from https://www.lfd.uci.edu/~gohlke/pythonlibs/ fails as there is no llvmlite or numba for Python 3.10.
Error:
```
PS C:\Users\ingframin> pip install numba
WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15 in c:\python310\lib\site-packages (from numba) (1.21.3)
Requirement already satisfied: setuptools in c:\python310\lib\site-packages (from numba) (59.2.0)
Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ingframin\AppData\Local\Temp\pip-record-5oeve_px\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\llvmlite'
         cwd: C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\
    Complete output (29 lines):
    running install
    C:\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    C:\Python310\python.exe C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py
    Trying generator 'Visual Studio 15 2017 Win64'
    Traceback (most recent call last):
      File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 191, in <module>
        main()
      File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 179, in main
        main_win32()
      File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Python310\lib\subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Python310\lib\subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'C:\\Python310\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ingframin\AppData\Local\Temp\pip-record-5oeve_px\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\llvmlite' Check the logs for full command output.

```

**Comment by esc** [comment]
> I tried to install Numba using pip on Windows 10. I have Python 3.10.1 (tags/v3.10.1:2cd268a, Dec 6 2021, 19:10:37) .
> 
> I have Clang installed on my computer: PS C:\Users\ingframin> clang -v clang version 11.0.0 Target: x86_64-w64-windows-gnu Thread model: posix InstalledDir: C:\msys64\mingw64\bin
> 
> Yet the installation of llvmlite fails with the error here below. I don't understand what file is missing or what setting is wrong. Installing from https://www.lfd.uci.edu/~gohlke/pythonlibs/ fails as there is no llvmlite or numba for Python 3.10. Error:
> 
> ```
> PS C:\Users\ingframin> pip install numba
> WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
> Collecting numba
>   Using cached numba-0.51.2.tar.gz (2.1 MB)
>   Preparing metadata (setup.py) ... done
> Collecting llvmlite<0.35,>=0.34.0.dev0
>   Using cached llvmlite-0.34.0.tar.gz (107 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: numpy>=1.15 in c:\python310\lib\site-packages (from numba) (1.21.3)
> Requirement already satisfied: setuptools in c:\python310\lib\site-packages (from numba) (59.2.0)
> Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
> WARNING: Ignoring invalid distribution -yinstaller (c:\python310\lib\site-packages)
> Installing collected packages: llvmlite, numba
>     Running setup.py install for llvmlite ... error
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ingframin\AppData\Local\Temp\pip-record-5oeve_px\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\llvmlite'
>          cwd: C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\
>     Complete output (29 lines):
>     running install
>     C:\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     running build
>     got version from file C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
>     running build_ext
>     C:\Python310\python.exe C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py
>     Trying generator 'Visual Studio 15 2017 Win64'
>     Traceback (most recent call last):
>       File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 191, in <module>
>         main()
>       File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 179, in main
>         main_win32()
>       File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 88, in main_win32
>         generator = find_win32_generator()
>       File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 76, in find_win32_generator
>         try_cmake(cmake_dir, build_dir, generator)
>       File "C:\Users\ingframin\AppData\Local\Temp\pip-install-ohsks9f9\llvmlite_c07807dc14084096ad685c995948196a\ffi\build.py", line 28, in try_cmake
>         subprocess.check_call(['cmake', '-G', generator, cmake_dir])
>       File "C:\Python310\lib\subprocess.py", line 364, in check_call
>         retcode = call(*popenargs, **kwargs)
>       File "C:\Python310\lib\subprocess.py", line 345, in call
>         with Popen(*popenargs, **kwargs) as p:
>       File "C:\Python310\lib\subprocess.py", line 966, in __init__
>         self._execute_child(args, executable, preexec_fn, close_fds,
>       File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
>         hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>     FileNotFoundError: [WinError 2] The system cannot find the file specified
>     error: command 'C:\\Python310\\python.exe' failed with exit code 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ingframin\\AppData\\Local\\Temp\\pip-install-ohsks9f9\\llvmlite_c07807dc14084096ad685c995948196a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ingframin\AppData\Local\Temp\pip-record-5oeve_px\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\llvmlite' Check the logs for full command output.
> ```

Thank you for asking about this. Numba/llvmlite do not support Python 3.10 at present. The new versions 0.55 and 0.38 to be released soon (release candidates before Christmas and finals after) however will. The reason you are seeing this error is because Numba 0.51 is the last version of Numba to not enforce an upper limit on the version numbers. Hence, `pip` will assume that this older version must be 3.10 compatible, download the source and then try to compile it. The result is the error message. My recommendation would be to use 3.9 for the time being if possible or otherwise wait until a 0.55 release candidate is out and then try to use that.

**Comment by FapAgent** [comment]
Cool
