### ISSUE TITLE
@jit method return two-dimentional array with wrong shape

### ISSUE THREAD

**Issue by liudaoqiangtj** [numba/numba#7667]
This is my problem:

version: numba==0.54.1 

@numba.jit
def average(times,  names, ods,  sizes,  numbers, locations, ops, dds):
     # all arguments are numpy array(float64, 1d, C) with same length, just as 20000 
     times_,  names_, ods_,  sizes_,  numbers_, locations_, ops_, dds_ = [], [], [], [], [], [], [], []
     .......
    # need to return a list with 8 sublists with length 20000. 
     return [times_,  names_, ods_,  sizes_,  numbers_, locations_, ops_, dds_]
   

The return is nested list with type float64. The question is, it return with a nested list just as blow:
[[1.1,1.1,1.1,1.1,...], [0], [nan], [nan], [8.2], [8.2], [8.2], [8.2]] ,
 the length of first sub-list is 20000 while other 7 sublists lengths are all 1.
And I don't get any warnning. I want to know how this happens?

**Comment by gmarkall** [comment]
Can you post some code that can be executed to reproduce the problem please? My best guess at something like this based on your example was:

```python
from numba import njit
import numpy as np

@njit
def average(times, names, ods, sizes, numbers, locations, ops, dds):
    # all arguments are numpy array(float64, 1d, C) with same length, just as 20000
    times_, names_, ods_, sizes_, numbers_, locations_, ops_, dds_ = [], [], [], [], [], [], [], []
    # need to return a list with 8 sublists with length 20000.
    return [times_, names_, ods_, sizes_, numbers_, locations_, ops_, dds_]


times = np.arange(20000).astype(np.float64)
names = times.copy()
ods = times.copy()
sizes = times.copy()
numbers = times.copy()
locations = times.copy()
ops = times.copy()
dds = times.copy()

print(average(times, names, ods, sizes, numbers, locations, ops, dds))
```

but this isn't executable. Note that you can format code in Github Issues using Markdown so it's easier to read: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by gmarkall** [comment]
Closing as the original issue cannot be reproduced and no further information has been received.
