### ISSUE TITLE
implementing n-tree is not possible

### ISSUE THREAD

**Issue by abdullahkavakli** [numba/numba#7671]
I want to implement n-tree by using list of nodes and jitclass but using deferred type for list but it is not possible(error is this:) 
TypingError: List.item_type cannot be of type OptionalType(DeferredType#1744333178288) i.e. the type 'DeferredType#1744333178288 or None'
```python
node_type = deferred_type()
    
@jitclass([('data', int32), ('children', types.ListType(optional(node_type)))])
class Node(object):
    
    def __init__(self,key):
        self.data=key
        self.children=[]
    
node_type.define(Node.class_type.instance_type)            
 ```
Can we handle this?
(if i don't use optinal() function it gives this error:
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot infer the type of variable '$8build_list.2' (temporary variable), have imprecise type: list(undefined)<iv=None>. 

For Numba to be able to compile a list, the list must have a known and
precise type that can be inferred from the other variables. Whilst sometimes
the type of empty lists can be inferred, this is not always the case, see this
documentation for help:https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-an-untyped-list-problem
) )

**Comment by gmarkall** [comment]
For help implementing an n-tree in Numba, it would be best to start a post on the [Numba Discourse](https://numba.discourse.group) - there are more active users there, so it is more likely someone will be able to suggest a way around this.

(I'm going to close this as a question - if it turns out that additional functionality is needed in Numba, please do open a feature request issue with the specific functionality that is needed, along with links to any prior discussion on the Discourse group)

**Comment by abdullahkavakli** [comment]
Hi @gmarkall, I asked the question bu no one answerd. I guess it is not supported. How can we handle?

**Comment by gmarkall** [comment]
> Hi @gmarkall, I asked the question bu no one answerd. I guess it is not supported. How can we handle?

It is the holiday period for a lot of people, so it might be at least a few more days before someone might reply.

**Comment by abdullahkavakli** [comment]
How about now? No one answered in numba discourse @gmarkall

**Comment by gmarkall** [comment]
@abdullahkavakli Would you like to link to the post?

**Comment by abdullahkavakli** [comment]
Of course, @gmarkall. It's here: https://numba.discourse.group/t/implementing-n-tree-with-list/1091

**Comment by gmarkall** [comment]
I've responded on the Discourse post.
