### ISSUE TITLE
Numpy matrix inside a method

### ISSUE THREAD

**Issue by nsarpangala** [numba/numba#7673]
Dear Numba community,

I want to @jit complie in nopython mode the following method:

    ```
    @jit(nopython=True)
    def  output_matrix(a,b):
        [x,y,z] = a / b
        o_tilde=np.matrix([[0,-z,y],[z,0,-x],[-y,x,0]])
        return o_tilde*np.sin(b)+(o_tilde**2)*(1-np.cos(b))
```

However, as you know any numpy array creation is not allowed in nopython mode. Do you have any ideas on how I can get around this issue while still maintaining the speed?

**Comment by gmarkall** [comment]
Array creation has been permitted inside nopython mode for a long time now - see for example the functions listed in https://numba.readthedocs.io/en/latest/reference/numpysupported.html#other-functions

However, `numpy.matrix` is not supported, as it's not recommended that it is used. See: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html - for your example you should be able to use `np.array` instead.

**Comment by gmarkall** [comment]
I'm going to close this issue - if you have any further difficulties using Numba I'd suggest starting a post on the [Numba Discourse](https://numba.discourse.group) to ask for help, as there are more active users answering questions there.
