### ISSUE TITLE
FR: Support `numpy.lib.stride_tricks.sliding_window_view`

### ISSUE THREAD

**Issue by erezinman** [numba/numba#7674]
Hi.
Please add support for numpy's `sliding_window_view` ([docs](https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html#numpy.lib.stride_tricks.sliding_window_view)). It is essentially a safe and useful wrapper to `.as_strided()` that you already support so that shouldn't be much of an issue. 

Thanks!

**Comment by gmarkall** [comment]
Many thanks for the request! I'll label this issue as such.
