### ISSUE TITLE
Error installing numba 0.51.2

### ISSUE THREAD

**Issue by StefanCaemmerer** [numba/numba#7692]
Hello,
I'm having trouble installing numba due to some errors.
I shortened the output a little bit by leaving occuring copy-entries.
I hope, you can help me with this.
Thank you in advance!

PS C:\WINDOWS\system32> pip install numba
Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.15 in c:\users\stefan\appdata\local\programs\python\python310\lib\site-packages (from numba) (1.21.5)
Requirement already satisfied: setuptools in c:\users\stefan\appdata\local\programs\python\python310\lib\site-packages (from numba) (60.1.0)
Building wheels for collected packages: numba, llvmlite
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\numba_703e47244a0048479ec026db670f6ee4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\numba_703e47244a0048479ec026db670f6ee4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Stefan\AppData\Local\Temp\pip-wheel-hve0jfsb'
       cwd: C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\numba_703e47244a0048479ec026db670f6ee4\
  Complete output (778 lines):
  TBB not found
  Using OpenMP from: True
  running bdist_wheel
  running build
  got version from file C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\numba_703e47244a0048479ec026db670f6ee4\numba/_version.py {'version': '0.51.2', 'full': '9d570961590c09a1eba748c9c37e91d1224fc9ad'}
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\numba
  copying numba\extending.py -> build\lib.win-amd64-3.10\numba
  ...
  creating build\lib.win-amd64-3.10\numba\cext
  copying numba\cext\__init__.py -> build\lib.win-amd64-3.10\numba\cext
  creating build\lib.win-amd64-3.10\numba\core
  copying numba\core\analysis.py -> build\lib.win-amd64-3.10\numba\core
  ...
  creating build\lib.win-amd64-3.10\numba\cpython
  copying numba\cpython\builtins.py -> build\lib.win-amd64-3.10\numba\cpython
  ...
  creating build\lib.win-amd64-3.10\numba\cuda
  copying numba\cuda\api.py -> build\lib.win-amd64-3.10\numba\cuda
  ...
  creating build\lib.win-amd64-3.10\numba\experimental
  copying numba\experimental\function_type.py -> build\lib.win-amd64-3.10\numba\experimental
  ...
  creating build\lib.win-amd64-3.10\numba\misc
  copying numba\misc\appdirs.py -> build\lib.win-amd64-3.10\numba\misc
  ...
  creating build\lib.win-amd64-3.10\numba\np
  copying numba\np\arraymath.py -> build\lib.win-amd64-3.10\numba\np
  ...
  creating build\lib.win-amd64-3.10\numba\parfors
  copying numba\parfors\array_analysis.py -> build\lib.win-amd64-3.10\numba\parfors
  ...
  creating build\lib.win-amd64-3.10\numba\pycc
  copying numba\pycc\cc.py -> build\lib.win-amd64-3.10\numba\pycc
  ...
  creating build\lib.win-amd64-3.10\numba\roc
  copying numba\roc\api.py -> build\lib.win-amd64-3.10\numba\roc
  ...
  creating build\lib.win-amd64-3.10\numba\scripts
  copying numba\scripts\generate_lower_listing.py -> build\lib.win-amd64-3.10\numba\scripts
  ...
  creating build\lib.win-amd64-3.10\numba\stencils
  copying numba\stencils\stencil.py -> build\lib.win-amd64-3.10\numba\stencils
  ...
  creating build\lib.win-amd64-3.10\numba\testing
  copying numba\testing\loader.py -> build\lib.win-amd64-3.10\numba\testing
  ...
  creating build\lib.win-amd64-3.10\numba\tests
  copying numba\tests\annotation_usecases.py -> build\lib.win-amd64-3.10\numba\tests
  ...
  creating build\lib.win-amd64-3.10\numba\typed
  copying numba\typed\dictimpl.py -> build\lib.win-amd64-3.10\numba\typed
  ...
  creating build\lib.win-amd64-3.10\numba\types
  copying numba\types\__init__.py -> build\lib.win-amd64-3.10\numba\types
  creating build\lib.win-amd64-3.10\numba\core\annotations
  copying numba\core\annotations\pretty_annotate.py -> build\lib.win-amd64-3.10\numba\core\annotations
  ...
  creating build\lib.win-amd64-3.10\numba\core\datamodel
  copying numba\core\datamodel\manager.py -> build\lib.win-amd64-3.10\numba\core\datamodel
  ...
  creating build\lib.win-amd64-3.10\numba\core\rewrites
  copying numba\core\rewrites\ir_print.py -> build\lib.win-amd64-3.10\numba\core\rewrites
  ...
  creating build\lib.win-amd64-3.10\numba\core\runtime
  copying numba\core\runtime\context.py -> build\lib.win-amd64-3.10\numba\core\runtime
  ...
  creating build\lib.win-amd64-3.10\numba\core\typeconv
  copying numba\core\typeconv\castgraph.py -> build\lib.win-amd64-3.10\numba\core\typeconv
  ...
  creating build\lib.win-amd64-3.10\numba\core\types
  copying numba\core\types\abstract.py -> build\lib.win-amd64-3.10\numba\core\types
  ...
  creating build\lib.win-amd64-3.10\numba\core\typing
  copying numba\core\typing\arraydecl.py -> build\lib.win-amd64-3.10\numba\core\typing
  ...
  creating build\lib.win-amd64-3.10\numba\core\unsafe
  copying numba\core\unsafe\bytes.py -> build\lib.win-amd64-3.10\numba\core\unsafe
  ...
  creating build\lib.win-amd64-3.10\numba\cpython\unsafe
  copying numba\cpython\unsafe\numbers.py -> build\lib.win-amd64-3.10\numba\cpython\unsafe
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\cudadrv
  copying numba\cuda\cudadrv\devicearray.py -> build\lib.win-amd64-3.10\numba\cuda\cudadrv
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\kernels
  copying numba\cuda\kernels\reduction.py -> build\lib.win-amd64-3.10\numba\cuda\kernels
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\simulator
  copying numba\cuda\simulator\api.py -> build\lib.win-amd64-3.10\numba\cuda\simulator
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests
  copying numba\cuda\tests\__init__.py -> build\lib.win-amd64-3.10\numba\cuda\tests
  creating build\lib.win-amd64-3.10\numba\cuda\simulator\cudadrv
  copying numba\cuda\simulator\cudadrv\devicearray.py -> build\lib.win-amd64-3.10\numba\cuda\simulator\cudadrv
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests\cudadrv
  copying numba\cuda\tests\cudadrv\test_array_attr.py -> build\lib.win-amd64-3.10\numba\cuda\tests\cudadrv
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests\cudapy
  copying numba\cuda\tests\cudapy\test_alignment.py -> build\lib.win-amd64-3.10\numba\cuda\tests\cudapy
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests\cudasim
  copying numba\cuda\tests\cudasim\support.py -> build\lib.win-amd64-3.10\numba\cuda\tests\cudasim
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests\nocuda
  copying numba\cuda\tests\nocuda\test_library_lookup.py -> build\lib.win-amd64-3.10\numba\cuda\tests\nocuda
  ...
  creating build\lib.win-amd64-3.10\numba\cuda\tests\cudadrv\data
  copying numba\cuda\tests\cudadrv\data\__init__.py -> build\lib.win-amd64-3.10\numba\cuda\tests\cudadrv\data
  creating build\lib.win-amd64-3.10\numba\experimental\jitclass
  copying numba\experimental\jitclass\base.py -> build\lib.win-amd64-3.10\numba\experimental\jitclass
  ...
  creating build\lib.win-amd64-3.10\numba\misc\help
  copying numba\misc\help\inspector.py -> build\lib.win-amd64-3.10\numba\misc\help
  ...
  creating build\lib.win-amd64-3.10\numba\np\ufunc
  copying numba\np\ufunc\array_exprs.py -> build\lib.win-amd64-3.10\numba\np\ufunc
  ...
  creating build\lib.win-amd64-3.10\numba\np\unsafe
  copying numba\np\unsafe\ndarray.py -> build\lib.win-amd64-3.10\numba\np\unsafe
  ...
  creating build\lib.win-amd64-3.10\numba\roc\hlc
  copying numba\roc\hlc\common.py -> build\lib.win-amd64-3.10\numba\roc\hlc
  ...
  creating build\lib.win-amd64-3.10\numba\roc\hsadrv
  copying numba\roc\hsadrv\devicearray.py -> build\lib.win-amd64-3.10\numba\roc\hsadrv
  ...
  creating build\lib.win-amd64-3.10\numba\roc\servicelib
  copying numba\roc\servicelib\service.py -> build\lib.win-amd64-3.10\numba\roc\servicelib
  ...
  creating build\lib.win-amd64-3.10\numba\roc\tests
  copying numba\roc\tests\__init__.py -> build\lib.win-amd64-3.10\numba\roc\tests
  creating build\lib.win-amd64-3.10\numba\roc\tests\hsadrv
  copying numba\roc\tests\hsadrv\test_async.py -> build\lib.win-amd64-3.10\numba\roc\tests\hsadrv
  ...
  creating build\lib.win-amd64-3.10\numba\roc\tests\hsapy
  copying numba\roc\tests\hsapy\run_far_branch.py -> build\lib.win-amd64-3.10\numba\roc\tests\hsapy
  ...
  creating build\lib.win-amd64-3.10\numba\tests\doc_examples
  copying numba\tests\doc_examples\test_examples.py -> build\lib.win-amd64-3.10\numba\tests\doc_examples
  ...
  creating build\lib.win-amd64-3.10\numba\tests\npyufunc
  copying numba\tests\npyufunc\cache_usecases.py -> build\lib.win-amd64-3.10\numba\tests\npyufunc
  ...
  creating build\lib.win-amd64-3.10\numba\tests\pycc_distutils_usecase
  copying numba\tests\pycc_distutils_usecase\setup_distutils.py -> build\lib.win-amd64-3.10\numba\tests\pycc_distutils_usecase
  ...
  creating build\lib.win-amd64-3.10\numba\tests\pycc_distutils_usecase\nested
  copying numba\tests\pycc_distutils_usecase\nested\source_module.py -> build\lib.win-amd64-3.10\numba\tests\pycc_distutils_usecase\nested
  ...
  running build_ext
  creating build\temp.win-amd64-3.10
  creating build\temp.win-amd64-3.10\Release
  creating build\temp.win-amd64-3.10\Release\numba
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py:528: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
    warnings.warn(
  cl : Befehlszeile warning D9002 : Unbekannte Option "-g" wird ignoriert.
  creating build\temp.win-amd64-3.10\Release\numba\core
  creating build\temp.win-amd64-3.10\Release\numba\core\typeconv
  _dispatcher.c
  numba/_dispatcher.c(26): error C2039: "use_tracing" ist kein Member von "_ts".
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\include\cpython/pystate.h(62): note: Siehe Deklaration von "_ts"
  numba/_dispatcher.c(28): error C2039: "use_tracing" ist kein Member von "_ts".
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\include\cpython/pystate.h(62): note: Siehe Deklaration von "_ts"
  numba/_dispatcher.c(199): warning C4244: "=": Konvertierung von "Py_ssize_t" in "int", m”glicher Datenverlust
  numba/_dispatcher.c(303): error C2039: "use_tracing" ist kein Member von "_ts".
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\include\cpython/pystate.h(62): note: Siehe Deklaration von "_ts"
  numba/_dispatcher.c(512): error C2039: "use_tracing" ist kein Member von "_ts".
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\include\cpython/pystate.h(62): note: Siehe Deklaration von "_ts"
  numba/_dispatcher.c(526): warning C4244: "=": Konvertierung von "Py_ssize_t" in "int", m”glicher Datenverlust
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\\Users\\Stefan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\core\\include -IC:\Users\Stefan\AppData\Local\Programs\Python\Python310\include -IC:\Users\Stefan\AppData\Local\Programs\Python\Python310\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcnumba/_dispatcher.c /Fobuild\temp.win-amd64-3.10\Release\numba/_dispatcher.obj" failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Stefan\AppData\Local\Temp\pip-wheel-5qd6lpbq'
       cwd: C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\
  Complete output (24 lines):
  running bdist_wheel
  C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py
  Trying generator 'Visual Studio 15 2017 Win64'
  Traceback (most recent call last):
    File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 191, in <module>
      main()
    File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 179, in main
      main_win32()
    File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 88, in main_win32
      generator = find_win32_generator()
    File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 76, in find_win32_generator
      try_cmake(cmake_dir, build_dir, generator)
    File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 28, in try_cmake
      subprocess.check_call(['cmake', '-G', generator, cmake_dir])
    File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
      retcode = call(*popenargs, **kwargs)
    File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
      with Popen(*popenargs, **kwargs) as p:
    File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
  error: command 'C:\\Users\\Stefan\\AppData\\Local\\Programs\\Python\\Python310\\python.exe' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stefan\AppData\Local\Temp\pip-record-elp4rcyx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\Include\llvmlite'
         cwd: C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\
    Complete output (29 lines):
    running install
    C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py
    Trying generator 'Visual Studio 15 2017 Win64'
    Traceback (most recent call last):
      File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 191, in <module>
        main()
      File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 179, in main
        main_win32()
      File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\Stefan\AppData\Local\Temp\pip-install-du29006z\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Stefan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
    error: command 'C:\\Users\\Stefan\\AppData\\Local\\Programs\\Python\\Python310\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-install-du29006z\\llvmlite_cf27ea07f7d443519a9b18e0bfa5364d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stefan\AppData\Local\Temp\pip-record-elp4rcyx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Stefan\AppData\Local\Programs\Python\Python310\Include\llvmlite' Check the logs for full command output.

**Comment by gmarkall** [comment]
This looks like you are trying to install Numba on Python 3.10, but there isn't a released version of Numba that supports Python 3.10. You can try out the 0.55 release candidate which does support Python 3.10 with:

```
pip install numba==0.55.0rc1
```

See https://numba.discourse.group/t/numba-0-55-0-rc1/1075 for more info on the RC.

**Comment by esc** [comment]
> This looks like you are trying to install Numba on Python 3.10, but there isn't a released version of Numba that supports Python 3.10. You can try out the 0.55 release candidate which does support Python 3.10 with:
> 
> ```
> pip install numba==0.55.0rc1
> ```
> 
> See https://numba.discourse.group/t/numba-0-55-0-rc1/1075 for more info on the RC.

I should also note that as of today (05 Jan 2021) there are no binary wheels for Windows for Python 3.10 so the above command is expected to fail too.

**Comment by esc** [comment]
I will close this as a duplicate as we continue to solidify the 3.10 experience with our next release candidate.
