### ISSUE TITLE
GLIBC version error in 0.55RC1 on AArch64

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7694]
Cross-post from https://numba.discourse.group/t/numba-0-55-0-rc1/1075/2?u=gmarkall for tracking

On a Jetson AGX Xavier (AArch64, Ubuntu 18.04), I create an environment with:

```
conda create -n testnumba055 python=3.9 numba::numba=0.55.0rc1 ipython
```

Then when running Numba in the environment I get:

```
(testnumba055) gmarkall@gm-agx:~$ python -c "import numba"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /data/gmarkall/miniforge/envs/testnumba055/lib/python3.9/site-packages/numba/_helperlib.cpython-39-aarch64-linux-gnu.so)
```

**Comment by seibert** [comment]
Ah, it looks like the Dockerfile we use to create the build environment is set to `arm64v8/ubuntu:latest`, which means whenever we last built it, it was updated.  @esc should be able to rebuild the image pinned to an older ubuntu to improve compatibility.

**Comment by esc** [comment]
> Ah, it looks like the Dockerfile we use to create the build environment is set to `arm64v8/ubuntu:latest`, which means whenever we last built it, it was updated. @esc should be able to rebuild the image pinned to an older ubuntu to improve compatibility.

This is correct, the numba-ci docker images will need a rebuild.

**Comment by esc** [comment]
<img width="812" alt="Screen Shot 2022-01-07 at 20 04 54" src="https://user-images.githubusercontent.com/41563/148594255-a9113121-9001-4f6e-94fe-3e4769c2a980.png">

20.04 it is! https://wiki.ubuntu.com/Releases

**Comment by seibert** [comment]
The system Graham is using is 18.04 (which is still supported).  Can we use that?

**Comment by esc** [comment]
> The system Graham is using is 18.04 (which is still supported). Can we use that?

Sure, will use that instead!

**Comment by esc** [comment]
@seibert should I update the other architectures that use `latest` too?

**Comment by seibert** [comment]
Yes, I think that would be good to avoid surprises in the future.

**Comment by esc** [comment]
> Yes, I think that would be good to avoid surprises in the future.

Sound good!

**Comment by esc** [comment]
@gmarkall my plan is to build a new image locally, use that to build a new conda package for Numba and then we can try and see if it's good. I'd like to proceed with caution here before uploading anything new to docker-hub.

**Comment by esc** [comment]
I have placed the file at: `esc/label/ubuntu_18.04` on anaconda.org:

https://anaconda.org/esc/numba/files

**Comment by gmarkall** [comment]
I created an enviroment with:

```
conda create -n val-numba-rc esc/label/ubuntu_18.04::numba numba/label/dev::llvmlite=0.38.0rc1 numpy=1.19
```

- All CUDA tests pass
- I started running the whole testsuite and have not encountered any issues yet.

So, it looks like this particular issue is resolved by the way you built the recent package.

**Comment by esc** [comment]
> I created an enviroment with:
> 
> ```
> conda create -n val-numba-rc esc/label/ubuntu_18.04::numba numba/label/dev::llvmlite=0.38.0rc1 numpy=1.19
> ```
> 
> * All CUDA tests pass
> * I started running the whole testsuite and have not encountered any issues yet.
> 
> So, it looks like this particular issue is resolved by the way you built the recent package.

Splendid, thank you, I will work on deploying the new image to dockerhub and themn the build farm tomorrow. @seibert let's discuss OOB how to manage that internally.

**Comment by esc** [comment]
This should be fixed in the 0.55.0 release, so we can probably close this. @gmarkall do you concur?

**Comment by gmarkall** [comment]
I'll test tomorrow to make sure.

**Comment by gmarkall** [comment]
I created an env with

```
conda create -n testnumba055rel python=3.9 numba::numba=0.55.0
```

and I can use Numba, so I believe this is now resolved!

**Comment by esc** [comment]
@gmarkall excellent, thank you for following up!
