### ISSUE TITLE
methods of numpy.random can not reproduce the same probability with the same random seed under the nopython=True

### ISSUE THREAD

**Issue by hIxiIan** [numba/numba#7715]
numpy.random.seed method seem to be failed under the func with the nopython=True mode.
windows
numba version '0.53.1'
numpy version '1.19.5'

Codes for this problem are as follows, thanks:
```python
import numpy as np
from numba import jit

def _normal(K=2):
    print(np.random.randint(K), np.random.rand())
    
@jit(nopython=True)
def _numba(K=2):
    print(np.random.randint(K), np.random.rand())
```

Test1:
```python
np.random.seed(2022)
_normal()
np.random.seed(2022)
_normal()
```

Test1 output:
0 0.009358613807764704
0 0.009358613807764704

Test2:
```python
np.random.seed(2022)
_numba()
np.random.seed(2022)
_numba()
```
Test2 output:
0 0.9014572675655993
0 0.6993665754033217

**Comment by stuartarchibald** [comment]
Thanks for the report. This is known behaviour (docs: https://numba.readthedocs.io/en/stable/reference/numpysupported.html#random), the Numba RNG state and NumPy RNG states are entirely separate. Therefore calling `np.random.seed()` will only impact the NumPy RNG seed and this explains the behaviour in the above. To make Numba's RNG state the same as NumPy's, the `np.random.seed()` function needs calling from within a JIT compiled region, for example:
```python
import numpy as np
from numba import jit
from numba.extending import register_jitable

# Fixed version, use a set_seed function and register_jitable

@register_jitable # This will run in JIT mode only if called from a JIT function
def set_seed_compat(x):
    np.random.seed(x)

@jit(nopython=True)
def baz(K=2):
    set_seed_compat(2022)
    print(np.random.randint(K), np.random.rand())

print("\nfixed:\n")

# Python version
baz.py_func()
baz.py_func()

# JIT version
baz()
baz()
```
Hope this helps?

**Comment by stuartarchibald** [comment]
> Thanks!

No problem, thanks for closing.
