### ISSUE TITLE
The ability to set nogil and parallel options for cc.export

### ISSUE THREAD

**Issue by marioroy** [numba/numba#7720]
I wish to be able to set ```nogil and parallel``` options using ```cc.export```. If parallel is not possible, at the very least ```nogil```.

I learned about [compiling code ahead of time](https://numba.pydata.org/numba-doc/dev/user/pycc.html) and gave it a try. Unfortunately, passing ```nogil=True``` is not allowed. Ditto for ```parallel=True```.

```python
@cc.export('mandelbrot1', 'void(u1[:,:,:], i2[:,:], UniTuple(i4,2), f8, f8, f8, f8, i4)', nogil=True)
def mandelbrot1(output, colors, seq, min_x, min_y, step_x, step_y, max_iters):

    width = output.shape[1]

    for y in range(seq[0], seq[1]):
        cimag = min_y + (y * step_y)
        for x in range(width):
            creal = min_x + (x * step_x)
            output[y,x] = mandel1(colors, creal, cimag, max_iters)
```

**Comment by gmarkall** [comment]
Many thanks for the request! I believe this duplicates the following issues:

- #7696 
- #6382 
- #3336 

Could you please follow these issues for info / progress?
