### ISSUE TITLE
SortedDicts()

### ISSUE THREAD

**Issue by kvak** [numba/numba#7721]
## Feature request

Hello all. A sorted dict is a sorted mutable mapping.

Sorted dict keys are maintained in sorted order. The design of sorted dict is simple: sorted dict inherits from dict to store items and maintains a sorted list of keys.

They are implemented in a variety of Python libs (and the in c++ stl), but to the best of my understanding, not in numba. Is this something you guys considering adding at some point?

Thanks in advance,

**Comment by stuartarchibald** [comment]
Thanks for the request. I don't think that this is in the scope of Numba as IIRC a sorted dictionary matching your description is not part of the standard python library (or NumPy)? and Numba is quite strict about this being the scope of what is supported.

Numba does provide an extension API to permit "overloading" an implementation from another library (writing an implementation of an existing API that Numba can compile) if that could work for you? Docs on the extension API are here: https://numba.readthedocs.io/en/stable/extending/high-level.html and an example of using it is here: https://numba.readthedocs.io/en/stable/extending/overloading-guide.html

**Comment by esc** [comment]
@stuartarchibald thank you for following up on this. Given that this feature is most likely beyond the scope of Numba, should we close this issue?

**Comment by kvak** [comment]
@stuartarchibald  thanks for the info about the scope of the project. In light of what you wrote my feature request is out of scope.

**Comment by esc** [comment]
@kvak thank you for the feedback! Will close the issue now. Maybe this could indeed be implemented as an extension!
