### ISSUE TITLE
File permissions in 0.55.1 tarball

### ISSUE THREAD

**Issue by atsampson** [numba/numba#7800]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The file permissions in the `numba-0.55.1.tar.gz` tarball [on PyPI](https://files.pythonhosted.org/packages/69/df/bd36068b2c1d0d34794f8ac0c222f9c4ad88dc710b400e65dbb3b59ea57e/numba-0.55.1.tar.gz) aren't right - the files and directories are only readable by the owner. This was OK in previous releases. Compare:

```
$ tar tvf numba-0.54.1.tar.gz | grep _lapack.c
-rw-r--r-- siu/staff     55079 2021-10-08 18:12 numba-0.54.1/numba/_lapack.c
$ tar tvf numba-0.55.0.tar.gz | grep _lapack.c
-rw-r--r-- sseibert/staff  55079 2022-01-14 01:24 numba-0.55.0/numba/_lapack.c
$ tar tvf numba-0.55.1.tar.gz | grep _lapack.c
-rw------- vhaenel/staff  55079 2021-03-26 13:28 numba-0.55.1/numba/_lapack.c
```

Since numba's installation process preserves permissions when installing some files, this can result in an installation (or distribution packages) with several files that aren't readable by regular users. For example, here's the installed version of the file above:

```
-rw------- 1 root root 55079 Mar 26  2021 pkg/lib/python3.10/site-packages/numba/_lapack.c
```

(My packaging tools check for this, but others might not...)

**Comment by seibert** [comment]
Since this part isn't automated in our release process, it looks like this is due to differences in the default umask for @sklam and I vs. @esc.  We should automate this to get consistent results.

In practice, is this causing any issue?  I'm not sure how to reupload an sdist without tagging a new version.  (Different than wheels, which have a build tag we can increment.)

**Comment by atsampson** [comment]
I've work around it easily enough, but it might affect other distribution packagers building packages from that tarball, if their tools don't check for broken permissions after installation. I'd probably add it to the checklist for the next release rather than trying to respin this one...

**Comment by seibert** [comment]
OK, will do.  Thanks for letting us know!

**Comment by esc** [comment]
@atsampson thank you for letting us know, this is indeed due to my local umask  of `077`. I wonder if there is an option for `setup.py sdist` to sanitize the owner and permission?

**Comment by esc** [comment]
It looks like group and owner can be changed, and we should do this, but it seems we need to set the `umask` manually before running the command?

```
python setup.py sdist -h
...
  --owner (-u)           Owner name used when creating a tar file [default:
                         current user]
  --group (-g)           Group name used when creating a tar file [default:
                         current group]
...
```

**Comment by esc** [comment]
Adding to checklist here: https://github.com/numba/numba/pull/7801

**Comment by esc** [comment]
The addition to the checklist has been merged. @atsampson thank you for the ping and do let us know if the next release still has this issue (I hope not).
