### ISSUE TITLE
pickle issue

### ISSUE THREAD

**Issue by wkerzendorf** [numba/numba#7807]
somehow pickle5 and numba=0.55 are not quite compatible.

```python
../../miniconda/envs/tardis-devel/lib/python3.7/site-packages/numba/cloudpickle/cloudpickle.py:59: in <module>
from pickle import _getattribute E   ImportError: cannot import name '_getattribute' from 'pickle5' (/Users/wkerzend/miniconda/envs/tardis-devel/lib/python3.7/site-packages/pickle5/__init__.py)
```

**Comment by wkerzendorf** [comment]
from your friendly neighborhood TARDIS devs

**Comment by esc** [comment]
@wkerzendorf thank you for reporting this. I believe that Numba has a vendored version of cloudpickle:

https://github.com/numba/numba/tree/main/numba/cloudpickle

Perhaps that is what is causing the issue. Maybe you need to uninstall the pickle you have?

**Comment by wkerzendorf** [comment]
we need to use the pickle that we have installed for other software. Not sure if `numba` can ensure that it uses its own pickle.

**Comment by wkerzendorf** [comment]
@esc let me know if we can help further?

**Comment by esc** [comment]
> @esc let me know if we can help further?

Yes, I am not sure how to proceed here. We will most likely discuss this during the triage meeting today and hopefully we can have some more pointers for you then. Thank you in advance for your patience.

**Comment by stuartarchibald** [comment]
I suspect this is the problem:
https://github.com/tardis-sn/tardis/blob/c70594674b4e0998f3ea8a349911c1096e877331/tardis/__init__.py#L26-L29
```python
if sys.version_info < (3, 8, 3):
    import pickle5

    sys.modules["pickle"] = pickle5
```
The system module "pickle" has been overridden.

**Comment by wkerzendorf** [comment]
I will scold the responsible party 🤣

**Comment by stuartarchibald** [comment]
Thanks for following up on this @wkerzendorf, I've added an idea for a workaround to the linked issued: https://github.com/tardis-sn/tardis/issues/1895.
