### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by tdekelver** [numba/numba#7810]
Hi,

Thanks for this great library!
In the documentation site there is still one import `from numba.core import types` but this does not exist anymore and has been moved to `from numba import types`. Could you correct this?
It is located over [here](https://numba.readthedocs.io/en/stable/reference/pysupported.html#id9) 

Thanks!

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm afraid that I can't seem to reproduce this:
```
$ python -c 'from numba.core import types; import numba; print(numba.version_info)'
version_info(major=0, minor=55, patch=1, short=(0, 55), full=(0, 55, 1), string='0.55.1', tuple=('0', '55', '1'), git_revision=None)
```
Numba re-exports `numba.core.types` as `numba.types`, so both should work ok?
https://github.com/numba/numba/blob/5762304d8896defcb4f858992a2da8824155989e/numba/__init__.py#L31-L32
and `numba.core.types` exists, it's here: https://github.com/numba/numba/tree/5762304d8896defcb4f858992a2da8824155989e/numba/core/types

I agree that the docs ought to be updated to reflect the preference to import from `numba` opposed to `numba.core` when possible. Patches are welcome, think it's these two lines that need a change:
https://github.com/numba/numba/blob/5762304d8896defcb4f858992a2da8824155989e/numba/tests/doc_examples/test_typed_dict_usage.py#L15
https://github.com/numba/numba/blob/5762304d8896defcb4f858992a2da8824155989e/numba/tests/doc_examples/test_typed_dict_usage.py#L57

**Comment by tdekelver** [comment]
Hi @stuartarchibald 

Thanks for the reply, indeed it works in numba 0.55.1, I was still using version 0.48.0. My bad.

Kind regards,
Thomas
