### ISSUE TITLE
Python sets as arguments to jitted functions

### ISSUE THREAD

**Issue by Hvass-Labs** [numba/numba#7816]
As always, thanks very much for making Numba!

## Versions

Numba: 0.55.1
Numpy: 1.20.3
Python: 3.8.12

## Problem

I need to pass a "set" data-structure to a Numba jitted function, but I get the following deprecation warning:

    NumbaPendingDeprecationWarning: 
    Encountered the use of a type that is scheduled for deprecation: type 'reflected set' found for argument 's' of function 'remove_even_numbers'.

    For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

    File "../../../../tmp/ipykernel_7231/4119407410.py", line 1:
    <source missing, REPL/exec in use?>

      warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))

## Example

    import numba
    from numba import njit

    @njit
    def remove_even_numbers(s):
        # In Python we need to iterate over a copy of the set for this to work,
        # but that is apparently not necessary in Numba. We do it anyway.
        for i in s.copy():
            # If the current number is even.
            if i % 2 == 0:
                # Remove the current number from the actual set.
                s.remove(i)

    s = set(range(10))
    # We now have: s == {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

    remove_even_numbers(s=s)
    # This creates the warning shown above.
    # We now have: s == {1, 3, 5, 7, 9}

    %timeit set(range(1000))
    # 17.7 µs ± 455 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

    %timeit remove_even_numbers(s=set(range(1000)))
    # 66.7 µs ± 4.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

This shows that the function `remove_even_numbers` takes around 50 µs which is super-fast. So whatever Numba is doing to copy back/forth with the "reflected set", it is not a problem at all. So why is this being deprecated?

I was then looking for `numba.typed.Set` similar to `numba.typed.List` but it is not implemented. There is one called `numba.types.Set` (note it is `numba.typeS` instead of `numba.typeD`) but calling `numba.types.Set(s)` raises an `AssertionError` without any comment.

What is the recommend way of passing sets to jitted functions? And why is the "reflected set" being deprecated when it is apparently super-fast?

Thanks!

**Comment by esc** [comment]
@Hvass-Labs thank you for asking about this. The reflected set was deprecated at a time when a typed set seemed to be imminently on the horizon. However, the typed Set has not materialized yet and so perhaps it should be un-deprecated. A caveat to this however, is that the reflected set has (at least) one long-standing, critical bug here: https://github.com/numba/numba/issues/6543 <--- and this issue is still looking for a champion. 

If you think that un-deprecating reflected set is a good idea, I encourage you to open a new feature request, or perhaps we can rephrase this issue to reflect that ask?

**Comment by stuartarchibald** [comment]
Just a quick note... it's not actually "Deprecated", it is "Pending Deprecation", as per the warning name `NumbaPendingDeprecationWarning`, but perhaps this isn't sufficiently prominent in the message string or docs. The purpose of this is to provide users plenty of notice about what will be deprecated sometime in the future such that they can assess whether they are happy using such a feature.

**Comment by stuartarchibald** [comment]
> And why is the "reflected set" being deprecated when it is apparently super-fast?

It has numerous issues to do with nesting https://numba.readthedocs.io/en/stable/reference/deprecation.html#reason-for-deprecation

**Comment by esc** [comment]
> I was then looking for `numba.typed.Set` similar to `numba.typed.List` but it is not implemented. There is one called `numba.types.Set` (note it is `numba.typeS` instead of `numba.typeD`) but calling `numba.types.Set(s)` raises an `AssertionError` without any comment.

The module `numba.types` contains the type (as in type-system) definitions for the containers. The implementation of the containers (both the LLVM builder code and the high-level Python code) themselves is in `numba.typed`. For example the type for the reflected list is `numba.types.List` whereas the type for the  `numba.typed.List` is actually `numba.types.ListType`. I hope that makes sense.

**Comment by Hvass-Labs** [comment]
Thanks for the quick and detailed reply! And I apologize for my late response; I was finishing an R&D project of my own (where Numba Jit gave me a 50x speed-up over pure Python, by the way!)

I have a few comments:

- When I read the warning in my Numba Jitted function for using Python's native `list` and `set` data-types, it was not clear to me that it is only *maybe* going to be deprecated in the future. I thought it was a certainty it was eventually going to be deprecated. But considering that `numba.typed.List` is still experimental (and very slow in some cases, as we have discussed elsewhere), and you apparently don't have any replacement for the Python `set` at all, I think it is problematic to flag them as being deprecated or "maybe" deprecated in the future. Not only does it raise uncertainty about how I should implement it, but as I use Numba in Python packages, the warning will show up for the end-user who will also get confused.

- As I have also discussed elsewhere, a lot of times my Numba Jitted functions are "read only", so they will not modify the data inside the jitted function - or at least I won't need the changes back in my Python code. I don't know if it will help performance, but if I could somehow signal this to the jit compiler, then perhaps the reflection layer could be made simpler and more efficient. Something like this:

    @jit(readonly=True)
    def foo(x, y):
        # Only read from x and y.

- Another suggestion might be that Numba only provides support for simple versions of `list` and `set`, e.g. where all the data must have the same type and there are limits on the nesting debt.

- Your last comment about the difference between `numba.types` and `numba.typed` actually was quite confusing :-) But I figured it had to do with internal vs. external data-types.

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
