### ISSUE TITLE
Support for multidimensional sparse arrays (Pydata/sparse)

### ISSUE THREAD

**Issue by jodemaey** [numba/numba#7852]
---

## Feature request

Dear Numba developers,

A long time ago, I have asked the sparse developers if it is possible to use [pydata/sparse](https://github.com/pydata/sparse) arrays inside a Numba njitted function here : https://github.com/pydata/sparse/issues/378 .

What I get from their answer is that they use Numba inside the library, but of course they are not responsible for making sparse array compatible with Numba. So I kind of figured out that I should rather ask here if this feature could be implemented.

My point for having sparse compatible with Numba is that it is presently (as far as I know) the only dedicated multidimensional sparse array library available for Python, so that would make sense to have that as a nice new feature.

Of course I'm also asking that because that would help me lot in my codes since I use Numba (see [here](https://github.com/Climdyn/qgs)) to accelerate integration loops with multidimensional sparse arrays inside, but that might also helps other. I'm not familiar with the details, but since Pydata/sparse is already written with Numba, I guess this is achievable.

I have checked and I did not find a related issue. Sorry if there is already one and I've missed it.

Thank you in advance for considering this request.

**Comment by stuartarchibald** [comment]
Thanks for opening this @jodemaey. Adding support for packages such as `pydata/sparse` is unfortunately outside of Numba's scope. Numba concentrates on providing support for the Python language and NumPy. Packages that use Numba can add support for their data-types, there's extension APIs in Numba designed to help with this. If those involved with the Numba data-type support in `pydata/sparse` need assistance, feel free to reach out through Numba's standard help channels (if you try opening an issue on Numba's issue tracker there's links in there). Thanks again!
