### ISSUE TITLE
numpy.argmin(arr, axis=int64), where (arr.ndim > 1), returns passes through the dtype of arr

### ISSUE THREAD

**Issue by QuaternionsRock** [numba/numba#7853]
When operating on a 1D array within a JIT-ed function, `numpy.argmin` always returns an array of type int64, regardless of whether or not you specify `axis=0`. However, when operating on a higher-dimension array, the dtype of the array is passed through to the return value. Here is a simple demonstration script:

```python
import numpy as np
from numba import njit


def test():
    one = np.argmin(np.arange(1024) < 512, axis=0)
    two_zero = np.argmin(np.arange(9).reshape((3, 3)).T < 5, axis=0)
    two_one = np.argmin(np.arange(9).reshape((3, 3)) < 4, axis=1)
    x = (np.arange(1023, -1, -1).reshape((512, 2)) // 4).astype(np.uint8)
    another_test = np.argmin(x, axis=0)
    return one, two_zero, two_one, another_test


if __name__ == '__main__':
    print(test())  # (512, array([0, 2, 0], dtype=int64), array([0, 1, 0], dtype=int64), array([510, 510], dtype=int64))
    print(njit(test)())  # (512, array([False,  True, False]), array([False,  True, False]), array([254, 254], dtype=uint8))
```

This can be avoided by casting the array with `.astype('int64')`, but its rather strange that you would need to do this.

**Comment by sklam** [comment]
Bug confirmed. `np.argmin` return type should not be based on the input array type: https://github.com/numba/numba/blob/290bcaa63804fb99b1fe238b0f8fe1caf7686899/numba/np/arraymath.py#L798
