### ISSUE TITLE
Strange Behaviour on Advanced Indexing

### ISSUE THREAD

**Issue by HikariS97** [numba/numba#7869]
Thanks for your work, it helps me to speed up in preprocessing state during pytorch training.

Description is contained in code comment.
Code: (Could be copied and run)
```
import numba as nb
import numpy as np

@nb.jit(nopython=True)
def randomize(input, H, W, Z, H_indices, W_indices, Z_indices):
    W_indices[:] = np.random.permutation(W)
    input = input[:, W_indices, :, :]
    for w_i in range(W):
        Z_indices[w_i, :] = np.random.permutation(Z)
        # FIXME: Numba Bug?
        # x_wi_x_x = input[:, w_i, :, :] # GOOD
        # input[:, w_i, :, :] = x_wi_x_x[:, Z_indices[w_i, :], :] # GOOD
        input[:, w_i, :, :] = input[:, w_i, Z_indices[w_i, :], :]  # ERROR
        for z_i in range(Z):
            H_indices[w_i, z_i, :] = np.random.permutation(H)
            input[:, w_i, z_i, :] = input[H_indices[w_i, z_i, :], w_i, z_i, :]  # But this line is fine?

    return input, H_indices, W_indices, Z_indices


H = 10
W = 10
Z = 10

W_indices = np.empty((W), dtype=np.int32)
Z_indices = np.empty((W, Z), dtype=np.int32)
H_indices = np.empty((W, Z, H), dtype=np.int32)

input = np.random.rand(H, W, Z, 7)

input, H_indices, W_indices, Z_indices = randomize(input, H, W, Z, H_indices, W_indices, Z_indices)

print(input)
```

Error:
```
Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array(float64, 4d, C), Tuple(slice<a:b>, int64, array(int32, 1d, C), slice<a:b>))
 
There are 22 candidate implementations:
[1m  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(float64, 4d, C), Tuple(slice<a:b>, int64, array(int32, 1d, C), slice<a:b>))':[0m
[1m   No match.[0m
[1m  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 166.
    With argument(s): '(array(float64, 4d, C), Tuple(slice<a:b>, int64, array(int32, 1d, C), slice<a:b>))':[0m
[1m   Rejected as the implementation raised a specific error:
     NumbaNotImplementedError: [1monly one advanced index supported[0m[0m
  raised from /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/numba/core/typing/arraydecl.py:69
[0m
[0m[1mDuring: typing of intrinsic-call at [/Users/krill/Desktop/numba_bug_report.py]() (13)[0m
[1m
File "numba_bug_report.py", line 13:[0m
[1mdef randomize(input, H, W, Z, H_indices, W_indices, Z_indices):
    <source elided>
        # input[:, w_i, :, :] = x_wi_x_x[:, Z_indices[w_i, :], :]
[1m        input[:, w_i, :, :] = input[:, w_i, Z_indices[w_i, :], :]
[0m        [1m^[0m[0m
  File "/Users/krill/Desktop/numba_bug_report.py", line 31, in <module>
    input, H_indices, W_indices, Z_indices = randomize(input, H, W, Z, H_indices, W_indices, Z_indices)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect this is due to a limitation in Numba's "advanced indexing" support, in the error message there is:
```
Rejected as the implementation raised a specific error:
     NumbaNotImplementedError: only one advanced index supported
```

**Comment by HikariS97** [comment]
> Thanks for the report. I suspect this is due to a limitation in Numba's "advanced indexing" support, in the error message there is:
> 
> ```
> Rejected as the implementation raised a specific error:
>      NumbaNotImplementedError: only one advanced index supported
> ```

Thanks for the quick reply. I'm not sure, could you give some clues on difference between the two sentences below?
1. `input[:, w_i, Z_indices[w_i, :], :]`
2. `input[H_indices[w_i, z_i, :], w_i, z_i, :]`

Actually, `Z_indices[w_i, :]` and `H_indices[w_i, z_i, :]` are one dimensional numpy array, and `w_i` and `z_i` are both of type `int`.  I'm confused, why the sentence 2 can be compiled without error, but line 1 should be adjusted in order to avoid the `NumbaNotImplementedError`?

I'm from head to heels a newbee to python, hope some helps on it, thank you.

**Comment by stuartarchibald** [comment]
@HikariS97 it's to do with the way Numba compiles code. The first thing Numba has to do when it compiles code is work out the types of every variable and call in the code it is given. It does this through a process of "type inference", which is an algorithm that combines information about the types of the arguments to the function, known constant types declared in the function and a load of rules about what functions called in the code will do for given argument types (some docs: https://numba.readthedocs.io/en/stable/developer/architecture.html#stage-4-infer-types). In the cases above:
1. Has a `__getitem__()` with argument of type:
    `Tuple(slice<a:b>, int64, array(int32, 1d, C), slice<a:b>)`
    if there's an array index then the integer index also counts as an advanced index, this is what is unsupported. The adjustment you made to your code split the indexing into two parts such that only one "advanced index" existed in each `__getitem__` and as a result Numba managed to compile it.
2. Has a `__getitem__()` with argument of type:
    `Tuple(slice<a:b>, int64, int64, slice<a:b>)`
    which has no array index and so the two integers don't count and "advanced" indexes and this is fine.

**Comment by HikariS97** [comment]
@stuartarchibald 
`Z_indices[w_i, :]` and `H_indices[w_i, z_i, :]` are same in Numpy type, but inferred as `slice<a:b>` and `array(int32, 1d, C)' as two different types correspondingly?

**Comment by kc611** [comment]
This will be resolved once all the PRs listed in https://github.com/numba/numba/issues/8616 goes through.

We can now close this particular issue as a duplicate.
