### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'jit'

### ISSUE THREAD

**Issue by Kraven0829** [numba/numba#7873]
Hi, i try to use librosa but i've got lots of problems.

It shows me this error when i try to run a program using librosa
AttributeError: module 'numba' has no attribute 'jit' 

I checked numba is in 0.55.1 version and i can't downgrade it, otherwise, there is this type of error when I try to install numba in 0.48.0 for example :  error legacy install failure.

I use spyder, and my Pc is in Windows 8 I think.
Thank you

**Comment by esc** [comment]
> Hi, i try to use librosa but i've got lots of problems.
> 
> It shows me this error when i try to run a program using librosa AttributeError: module 'numba' has no attribute 'jit'
> 
> I checked numba is in 0.55.1 version and i can't downgrade it, otherwise, there is this type of error when I try to install numba in 0.48.0 for example : error legacy install failure.
> 
> I use spyder, and my Pc is in Windows 8 I think. Thank you

@Kraven0829 thank you for asking about this. It sounds like an installation failure. The `numba` module should have a `jit` attribute for sure. I would recommend a re-installation by whatever means you used to install librosa. Also, perhaps ask the librosa developers for installation advice?

**Comment by esc** [comment]
> I give you all the error message, that has changed by the way. Maybe it would help you
> 
> Reloaded modules: librosa.version, librosa._cache, joblib, joblib.memory, joblib.hashing, joblib.func_inspect, joblib.logger, joblib.disk, joblib._store_backends, joblib.backports, joblib.numpy_pickle, joblib.compressor, joblib.numpy_pickle_utils, joblib.numpy_pickle_compat, joblib.parallel, joblib._multiprocessing_helpers, joblib._parallel_backends, joblib.my_exceptions, joblib._deprecated_my_exceptions, joblib.pool, joblib._memmapping_reducer, joblib.externals, joblib.externals.loky, joblib.externals.loky._base, joblib.externals.loky.backend, joblib.externals.loky.backend.context, joblib.externals.loky.backend.process, joblib.externals.loky.backend.compat, joblib.externals.loky.backend.compat_win32, joblib.externals.loky.backend.reduction, joblib.externals.loky.backend._win_reduction, joblib.externals.cloudpickle, joblib.externals.cloudpickle.cloudpickle, joblib.externals.cloudpickle.compat, joblib.externals.cloudpickle.cloudpickle_fast, joblib.externals.loky.reusable_executor, joblib.externals.loky.process_executor, joblib.externals.loky.backend.queues, joblib.externals.loky.backend.utils, joblib.externals.loky.initializers, joblib.externals.loky.cloudpickle_wrapper, joblib.externals.loky.backend.resource_tracker, joblib.externals.loky.backend.spawn, joblib.executor, numba._version, numba.misc, numba.misc.init_utils, numba.core, numba.core.config, llvmlite, llvmlite._version, llvmlite.binding, llvmlite.binding.dylib, llvmlite.binding.ffi, llvmlite.binding.common, llvmlite.utils, llvmlite.binding.executionengine, llvmlite.binding.targets, llvmlite.binding.object_file, llvmlite.binding.initfini, llvmlite.binding.linker, llvmlite.binding.module, llvmlite.binding.value, llvmlite.binding.context, llvmlite.binding.options, llvmlite.binding.passmanagers, llvmlite.binding.transforms, llvmlite.binding.analysis, llvmlite.ir, llvmlite.ir.types, llvmlite.ir._utils, llvmlite.ir.values, llvmlite.ir.module, llvmlite.ir.context, llvmlite.ir.builder, llvmlite.ir.instructions, llvmlite.ir.transforms, numba.core.types, numba.core.utils, numba.core.types.abstract, numba.core.types.containers, numba.core.types.common, numba.core.errors, numba.core.types.misc, numba.core.typeconv, numba.core.typeconv.castgraph, numba.core.ir, numba.core.consts, numba.core.types.functions, numba.core.types.iterators, numba.core.types.npytypes, numba.core.types.scalars, numba.np, numba.np.npdatetime_helpers, numba.core.types.function_type Traceback (most recent call last):
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in from numba.core.typeconv import _typeconv
> 
> ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typeconv__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
> File "C:\Users\Marjolaine.spyder-py3\Projet Expérimental\sanstitre0.py", line 1, in import librosa as lr
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa__init__.py", line 209, in from . import core
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa\core__init__.py", line 5, in from .convert import * # pylint: disable=wildcard-import
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa\core\convert.py", line 7, in from . import notation
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa\core\notation.py", line 8, in from ..util.exceptions import ParameterError
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa\util__init__.py", line 77, in from .utils import * # pylint: disable=wildcard-import
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa\util\utils.py", line 9, in import numba
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba__init__.py", line 23, in from numba.misc.special import (
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\misc\special.py", line 3, in from numba.core.typing.typeof import typeof
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typing__init__.py", line 1, in from .context import BaseContext, Context
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typing\context.py", line 11, in from numba.core.typeconv import Conversion, rules
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typeconv\rules.py", line 2, in from .typeconv import TypeManager, TypeCastingRules
> 
> File "C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typeconv\typeconv.py", line 16, in raise ImportError(msg)
> 
> ## ImportError: Numba could not be imported.
> If you are seeing this message and are undertaking Numba development work, you may need to rebuild Numba. Please see the development set up guide:
> 
> https://numba.readthedocs.io/en/stable/developer/contributing.html.
> 
> If you are not working on Numba development, the original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Marjolaine\AppData\Local\Programs\Python\Python310\Lib\site-packages\numba\core\typeconv__init__.py)'. For help, please visit:
> 
> https://numba.readthedocs.io/en/stable/user/faq.html#numba-could-not-be-imported

Thank you for adding this. This does indeed seem like an installation issue. It seems like some parts of Numba were not correctly installed.

**Comment by esc** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
