### ISSUE TITLE
Improve error message in Numpy advanced indexing

### ISSUE THREAD

**Issue by sklam** [numba/numba#7874]
Inspired by https://github.com/numba/numba/issues/7869

Ideas:
- improve error message to say which element in the index tuple will cause advanced indexing.

**Comment by kc611** [comment]
This will be resolved once the PRs listed in https://github.com/numba/numba/issues/8616 goes through since all kinds of allowed indices will be supported and there won't be the above stated failure at all.

We can now close this particular issue as a duplicate.
