### ISSUE TITLE
Problem unifying return-types for Numpy arrays

### ISSUE THREAD

**Issue by Hvass-Labs** [numba/numba#7880]
As always, thanks very much for making Numba!

## Versions

Numba: 0.55.1
Numpy: 1.20.3
Python: 3.8.12

## Problem

I often have functions that can either work on 1-dim or 2-dim Numpy arrays and will return either a 1-dim or 2-dim Numpy array as the result. They have the same dtypes, only the shape of the array is different. This does not seem to be supported by Numba, which gives a cryptic error-message as shown below. Is there a technical reason why this is not supported? It would seem to me that as long as the return-types are Numpy arrays with the same dtype, then it ought to work?

I haven't been able to find a previous post with this exact problem, and the official docs only seem to mention the problem [here](https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem).

## Example

The following "dummy" example works with Numba:

    from numba import njit
    import numpy as np

    # Test arrays.
    x1 = np.arange(3)
    x2 = np.arange(8).reshape((2, 4))

    # This "dummy" function works with Numba.
    def foo(x):
        if len(x.shape) == 1:
            return x
        else:
            return x
    foo_jit = njit(foo)

    # This works.
    foo(x1) == foo_jit(x1)
    foo(x2) == foo_jit(x2)

The following function does NOT work with Numba:

    def bar(x):
        if len(x.shape) == 1:
            return x
        else:
            return np.sum(x, axis=0)
    bar_jit = njit(bar)

    # This works.
    bar(x1)
    bar(x2)

    # This does NOT work.
    bar_jit(x1)
    # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    # Can't unify return type from the following types: array(int64, 1d, C), int64

    # This also does NOT work.
    bar_jit(x2)
    # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    # Can't unify return type from the following types: array(int64, 1d, C), array(int64, 2d, C)

In the case of `bar_jit(x1)` the Numba Jit compiler cannot reconcile a return-type that is a Numpy 1-dim array and an integer.

In the case of `bar_jit(x2)` the Numba Jit compiler cannot reconcile a return-type that is a Numpy 1-dim array with a 2-dim array of the same dtypes.

Would it be possible for the Numba Jit compiler to support return-types that are Numpy arrays of different shapes?

Thanks!

**Comment by esc** [comment]
> As always, thanks very much for making Numba!
> 
> ## Versions
> Numba: 0.55.1 Numpy: 1.20.3 Python: 3.8.12
> 
> ## Problem
> I often have functions that can either work on 1-dim or 2-dim Numpy arrays and will return either a 1-dim or 2-dim Numpy array as the result. They have the same dtypes, only the shape of the array is different. This does not seem to be supported by Numba, which gives a cryptic error-message as shown below. Is there a technical reason why this is not supported? It would seem to me that as long as the return-types are Numpy arrays with the same dtype, then it ought to work?
> 
> I haven't been able to find a previous post with this exact problem, and the official docs only seem to mention the problem [here](https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem).
> 
> ## Example
> The following "dummy" example works with Numba:
> 
> ```
> from numba import njit
> import numpy as np
> 
> # Test arrays.
> x1 = np.arange(3)
> x2 = np.arange(8).reshape((2, 4))
> 
> # This "dummy" function works with Numba.
> def foo(x):
>     if len(x.shape) == 1:
>         return x
>     else:
>         return x
> foo_jit = njit(foo)
> 
> # This works.
> foo(x1) == foo_jit(x1)
> foo(x2) == foo_jit(x2)
> ```
> 
> The following function does NOT work with Numba:
> 
> ```
> def bar(x):
>     if len(x.shape) == 1:
>         return x
>     else:
>         return np.sum(x, axis=0)
> bar_jit = njit(bar)
> 
> # This works.
> bar(x1)
> bar(x2)
> 
> # This does NOT work.
> bar_jit(x1)
> # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> # Can't unify return type from the following types: array(int64, 1d, C), int64
> 
> # This also does NOT work.
> bar_jit(x2)
> # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> # Can't unify return type from the following types: array(int64, 1d, C), array(int64, 2d, C)
> ```
> 
> In the case of `bar_jit(x1)` the Numba Jit compiler cannot reconcile a return-type that is a Numpy 1-dim array and an integer.
> 
> In the case of `bar_jit(x2)` the Numba Jit compiler cannot reconcile a return-type that is a Numpy 1-dim array with a 2-dim array of the same dtypes.
> 
> Would it be possible for the Numba Jit compiler to support return-types that are Numpy arrays of different shapes?
> 
> Thanks!

Hi @Hvass-Labs -- it seems like you now hit a long-standing issue with Numba and Numpy functions whos signature changes based on the value of the input. For Numba to compile something it looks at the types of the input and determines the type of the output. The dimensionality (bit not the shape) of a NumPy array is considered part of the type interface. In fact, this is also an issue when we implement some of the Numpy functions in Numba since some of them exhibit this kind of behaviour too.

I think there are some issues on the tracker about this already, one of which contains a better explanation of the above. I'll see if I can dig it out. Or maybe @stuartarchibald or @seibert can recall?

Anyway, probably something worth mentioning in the future "Numba best practices" documentation.

**Comment by stuartarchibald** [comment]
There's a bit of discussion about value based specialisation here: https://github.com/numba/numba/issues/2949

Numba of at least 0.55.1 can spot things like `len(<direct reference to a tuple>)` and `array.ndim` as special cases, it can also do some form of branch pruning based on constant values e.g. 
```
if array.ndim == 2: 
   ...
```
would get evaluated into  `if True/False:... ` and then the body of the `if` would be either unconditionally executed or removed depending on True/False.

Updating `bar` above to:
```python
def bar(x):
    if x.ndim == 1:
        return x
    else:
        return np.sum(x, axis=0)
```
would let it work.

**Comment by Hvass-Labs** [comment]
I apologize for my late response.

Thanks for the tip on using `x.ndim` instead of `len(x.shape)` I will do that in all my code from now on :-)

However, the main problem I am having still seems to be there, namely that Jitted functions cannot return Numpy arrays of different shapes, even when the dtype is the same. Perhaps my example above was a bit too contrived. Let's consider this example instead:

    def baz(x):
        if x>0:
            return np.zeros(shape=(2, 3), dtype=np.float64)
        else:
            return np.zeros(shape=4, dtype=np.float64)

    baz_jit = njit(baz)

    baz(123)
    # array([[0., 0., 0.],
    #        [0., 0., 0.]])

    baz(-456)
    # array([0., 0., 0., 0.])

    baz_jit(123)
    # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    # Can't unify return type from the following types: array(float64, 1d, C), array(float64, 2d, C)

    baz_jit(-456)
    # TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    # Can't unify return type from the following types: array(float64, 1d, C), array(float64, 2d, C)

The reason I would like to be able to return a Numpy array with different shapes depending on the arguments to the function, is that I often make Jitted functions that can either work on 1-dim or 2-dim arrays, e.g. to work on the contents of either a Pandas Series or DataFrame. Because of Numba's limitation on return-types, I must always return 2-dim arrays and then make some wrapper-code that converts that into a 1-dim array. That is not so elegant.

It seems to me that the return-type is exactly the same, in the sense that they're both Numpy arrays with the same dtype, it is just the shape that differs. So it seems strange to me that Numba Jit won't accept this?

Thanks again!

**Comment by stuartarchibald** [comment]
@Hvass-Labs in Numba's type system the dimensionality of the array is part of the type. e.g.
```python
In [1]: from numba import types

In [2]: types.float64[::1]
Out[2]: array(float64, 1d, C)

In [3]: types.float64[:,::1]
Out[3]: array(float64, 2d, C)

In [4]: types.float64[:,:,::1]
Out[4]: array(float64, 3d, C)

In [5]: import numpy as np

In [6]: from numba import typeof

In [7]: typeof(np.zeros((1,)))
Out[7]: array(float64, 1d, C)

In [8]: typeof(np.zeros((1, 1)))
Out[8]: array(float64, 2d, C)

In [9]: typeof(np.zeros((1, 1, 1)))
Out[9]: array(float64, 3d, C)
```
as a result, when unifying an array type, the dimensionality has to the same as it's part of the type and e.g. there's no type that would satisfy the semantics of both a 1D and 2D array.

If your predicate i.e. `x > 0` in the above, is a compile time constant there's a workaround for this, but if it is only known at runtime, then there is not.

**Comment by seibert** [comment]
Unfortunately, the limitation is hard to remove because much of the code generation assumes the loop nesting for a particular dimension array can be computed at compile time.  There are definitely use cases for "unranked" arrays, but it is a lot of work to make them work smoothly throughout Numba.  Numba is happy to generate as many function specializations as needed, so the need for unranked arrays only arises when the number of dimensions depends on the value of the input.

**Comment by Hvass-Labs** [comment]
OK, thanks for the explanation.

If I understand correctly, when a Numba jitted function receives 1-dim or 2-dim numpy arrays as input, Numba just recompiles the function with the new dimensionality of the input arrays. But when the return-type is an array of varying dimensions, the Numba jit compiler may have trouble figuring out how to determine the dimensionality of the array at compile-time, and therefore it raises an error.

As we have discussed elsewhere, this is something that would be really good to explain in a tutorial on Numba best practises, because it took me quite a while to figure out first what the error means, and then how to work around the limitation in a graceful manner.

Also, if you feel this is something that will never get changed in the Numba compiler, then I suppose you can just close this issue.
