### ISSUE TITLE
pyspark, cluster mode, cannot cache function '__shear_dense': no locator available

### ISSUE THREAD

**Issue by ShituanHu** [numba/numba#7883]
I have a problem, need help:
when I use pyspark in aws, in Local mode, it worked; but cluster mode, it doesn't,and have problem:

```
File "/mnt/yarn/usercache/hadoop/appcache/application_1646288077921_0008/container_1646288077921_0008_01_000002/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1646288077921_0008/container_1646288077921_0008_01_000002/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1646288077921_0008/container_1646288077921_0008_01_000002/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1646288077921_0008/container_1646288077921_0008_01_000002/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1646288077921_0008/container_1646288077921_0008_01_000002/pyspark.zip/pyspark/cloudpickle.py", line 875, in subimport
    __import__(name)
  File "/usr/local/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.7/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/usr/local/lib/python3.7/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.7/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.7/site-packages/librosa/util/utils.py", line 1848, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/usr/local/lib64/python3.7/site-packages/numba/core/decorators.py", line 214, in wrapper
    disp.enable_caching()
  File "/usr/local/lib64/python3.7/site-packages/numba/core/dispatcher.py", line 812, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/local/lib64/python3.7/site-packages/numba/core/caching.py", line 610, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/local/lib64/python3.7/site-packages/numba/core/caching.py", line 348, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.7/site-packages/librosa/util/utils.py'
```
I also try to set 'ENV NUMBA_CACHE_DIR=/tmp/NUMBA_CACHE_DIR/' in root, but it didn't work

**Comment by ShituanHu** [comment]
the version is :
librosa                    0.8.1
numba                      0.53.0

**Comment by esc** [comment]
@ShituanHu thank you for posting this!

RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by esc** [comment]
There are similar reports here:

https://gitter.im/numba/numba?at=621a33019bd1c71eca79047b

And here:

https://github.com/numba/numba/issues/5566

**Comment by ShituanHu** [comment]
I also use librosa 0.7.2 instead of 0.8.1, but it didn't work.
So how to solve?

**Comment by ShituanHu** [comment]
the simple code is likely this:
```python
import librosa

def extract_fea(item):
    url = item[5]
    data = mp3towav_url_byteio(url)
    y, sr = librosa.load(BytesIO(data))
    chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)  # 声谱图
    return (chroma_stft)

def mp3towav_url_byteio(url):
    cmd = ['/home/hadoop/ffmpeg-4.4-amd64-static/ffmpeg', '-n', '-i', url, '-f', 'wav', 'pipe:']
    p = Popen(cmd, stdout=PIPE, stderr=PIPE, bufsize=-1)
    out, _ = p.communicate()
    return out if out.startswith(b'RIFF\xff\xff\xff') else None

if __name__ == '__main__':
    result_df_sub = df_sub.rdd.repartition(map_partitions).map(lambda x: extract_fea(x)).toDF(columns)
```

**Comment by ShituanHu** [comment]
when spark-submit local, it work:
spark-submit --master local[*] test.py
but when spark-submit yarn, it not:
spark-submit --master yarn test.py
------------------
the run environment is in AWS EMR

**Comment by ShituanHu** [comment]
As I know, when spark-submit local, the user is 'hadoop'; 
but when spark-submit yarn, the excutor node user is 'yarn'.
so which user environment val should I set?
 I try to set 'NUMBA_CACHE_DIR' in 'hadoop', 'yarn' and 'root', but all of them didn't work

**Comment by ShituanHu** [comment]
when I use spark-submit yarn mode,
I have noticed that in master node, the directory '/tmp/NUMBA_CACHE_DIR/' have new file after run spark task. But core node '/tmp/NUMBA_CACHE_DIR/' is empty.
 I thought both of them should have file? But why core node's '/tmp/NUMBA_CACHE_DIR/' is empty ?

**Comment by esc** [comment]
> when I use spark-submit yarn mode, I have noticed that in master node, the directory '/tmp/NUMBA_CACHE_DIR/' have new file after run spark task. But core node '/tmp/NUMBA_CACHE_DIR/' is empty. I thought both of them should have file? But why core node's '/tmp/NUMBA_CACHE_DIR/' is empty ?

It sounds like the function was perhaps compiled on the wrong node. I am guessing here because I have no familiarity with `spark`.

**Comment by sklam** [comment]
Additional note from triage meeting:

The error on `no locator available` could also mean the Numba cannot find a writeable path on the node. Maybe it is worth adding an option to globally disable caching for some distributed use-cases.

**Comment by ShituanHu** [comment]
Aha, I have solve the problem. Here is my steps ：
1. make directories in all nodes: mkdir -m 777 /tmp/NUMBA_CACHE_DIR
2. config environment_value in code, not in nodes
```python
import os

def extract_fea(item):
    os.environ["NUMBA_CACHE_DIR"] = "/tmp/NUMBA_CACHE_DIR/"
    import librosa
    url = item[5]
    data = mp3towav_url_byteio(url)
    y, sr = librosa.load(BytesIO(data))
    chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)  # 声谱图
    return (chroma_stft)

def mp3towav_url_byteio(url):
    cmd = ['/home/hadoop/ffmpeg-4.4-amd64-static/ffmpeg', '-n', '-i', url, '-f', 'wav', 'pipe:']
    p = Popen(cmd, stdout=PIPE, stderr=PIPE, bufsize=-1)
    out, _ = p.communicate()
    return out if out.startswith(b'RIFF\xff\xff\xff') else None

if __name__ == '__main__':
    result_df_sub = df_sub.rdd.repartition(map_partitions).map(lambda x: extract_fea(x)).toDF(columns)
```
It works !
Be attention, set "NUMBA_CACHE_DIR" and 'import librosa' should be in the UDF 'extract_fea', otherwise it doesn't work!
The problem is in this UDF. When core nodes running the task, use this UDF, then need to use 'librosa'. It's time to import 'librosa'. At this time, set  environment_value and import librosa, it works!
Actionly I don't know why set environment_value in core nodes doesn't work. Maybe it's about spark running principle.
That all, hope can help others who meet the same problem as I have.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
