### ISSUE TITLE
Performance of Numba Runtime Allocations

### ISSUE THREAD

**Issue by zephyr111** [numba/numba#7887]
Hello,

I have tested the performance creating very short Numpy array in Numba  njit function and I am a bit surprised of the computation time. I found out that a significant part of the time is spent in NRT functions defined in `core/runtime/nrt.c`, and more specifically, in `memset` calls (in `NRT_MemInfo_alloc_safe_aligned` and `nrt_internal_dtor_safe`) that appear to only be useful for debugging purpose. Is it the case? If so, I propose to add a debug boolean parameter to the function so to enable this only in debug mode. A faster alternative solution is to add functions with the _debug prefix that can be called by the JIT only in debug mode. Such `memset` calls takes 20-25% of the time of very short Numpy allocations on my machine (with a i5-9600KF processor).

Additionally, I am wondering why such calls are not inlined by the JIT. Some calls like this could be faster if they were inlined because of constant propagation and the expression optimization of the provided function arguments. Is this behavior intended?

Finally, I found that `nrt_allocate_meminfo_and_data_align` performs a modulus that tends to be quite slow. Since the divider is the memory alignment which is generally a power of two, this modulus can be optimized. We can check if the alignment is a power of two with `if((align & (align - 1)) == 0)`, and if this is the case, then use a simple `remainder = intptr & (align - 1)`. Otherwise, a modulus can be used (rare case so the processor can predict the conditional). If the alignment is guaranteed to be always a power of two, then the conditional can even be removed! Note that this strategy is already used by most compilers for stack alignment of optimized programs and optimized memory allocators.

Here is a simple code to test this:

```python
import numba as nb
import numpy as np

@nb.njit('void()')
def test():
    for i in range(1000):
        np.empty(2)

%timeit  -n 20_000 test()
```

**Comment by stuartarchibald** [comment]
@zephyr111 thanks for the report.

> I have tested the performance creating very short Numpy array in Numba njit function and I am a bit surprised of the computation time. I found out that a significant part of the time is spent in NRT functions defined in `core/runtime/nrt.c`, and more specifically, in `memset` calls (in `NRT_MemInfo_alloc_safe_aligned` and `nrt_internal_dtor_safe`) that appear to only be useful for debugging purpose. Is it the case? If so, I propose to add a debug boolean parameter to the function so to enable this only in debug mode. A faster alternative solution is to add functions with the _debug prefix that can be called by the JIT only in debug mode. Such `memset` calls takes 20-25% of the time of very short Numpy allocations on my machine (with a i5-9600KF processor).

Running something like the above:
```python
import numba as nb
import numpy as np

@nb.njit('void()')
def test():
    for i in range(1000):
        np.empty(2)

n = 20000
for x in range(n):
    test()

```
Removing all those `memset` calls does lead to a faster alloc/dealloc loop, locally 4.1s with `memset`, 3.8s without `memset`. Looking at the machine code, seems like the `memset` is inlined, but it obviously still has a cost. Will raise this at the development meeting tomorrow. Is there a specific use case for a tight loop with small heap allocations (that couldn't just be reused) like in the above?

> Additionally, I am wondering why such calls are not inlined by the JIT. Some calls like this could be faster if they were inlined because of constant propagation and the expression optimization of the provided function arguments. Is this behavior intended?

The JIT is generating LLVM IR which is then compiled just-in-time by LLVM, this is C code compiled to a library, the symbols of which are called in the LLVM IR, so it can't be inlined.

> Finally, I found that nrt_allocate_meminfo_and_data_align performs a modulus that tends to be quite slow. Since the divider is the memory alignment which is generally a power of two, this modulus can be optimized. We can check if the alignment is a power of two with if((align & (align - 1)) == 0), and if this is the case, then use a simple remainder = intptr & (align - 1). Otherwise, a modulus can be used (rare case so the processor can predict the conditional). If the alignment is guaranteed to be always a power of two, then the conditional can even be removed! Note that this strategy is already used by most compilers for stack alignment of optimized programs and optimized memory allocators.

I think that this could be improved as suggested, a patch would be welcomed.

**Comment by stuartarchibald** [comment]
@zephyr111 I wrote up some more information on this here: https://github.com/numba/numba/issues/8101#issuecomment-1135597413
