### ISSUE TITLE
`numba.tests.test_builtins.TestIsinstanceBuiltin.test_experimental_warning` fail on main

### ISSUE THREAD

**Issue by sklam** [numba/numba#7891]
I got a test failure when I run `python runtests.py numba/tests/test_builtins.py`

```
FAIL: test_experimental_warning (numba.tests.test_builtins.TestIsinstanceBuiltin)
```

_Originally posted by @sklam in https://github.com/numba/numba/issues/7884#issuecomment-1059578627_

**Comment by sklam** [comment]
Note: may not always reproduce

**Comment by stuartarchibald** [comment]
Locally, on Python 3.8, this is enough to trigger the failure:
```
./runtests.py numba.tests.test_builtins.TestIsinstanceBuiltin.test_combinations numba.tests.test_builtins.TestIsinstanceBuiltin.test_isinstance_exceptions
```
but the same does not happen on Python 3.9.

**Comment by stuartarchibald** [comment]
Fixed in https://github.com/numba/numba/pull/8197
