### ISSUE TITLE
TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by tianlinzx** [numba/numba#7906]
`@numba.jit(nopython=True, parallel=True)
def black_scholes(P, S, T, rate, vol):
    a = np.log(P / S)
    b = T * -rate

    z = T * (vol * vol * 2)
    c = 0.25 * z
    y = 1.0 / np.sqrt(z)

    w1 = (a - b + c) * y
    w2 = (a - b - c) * y

    d1 = 0.5 + 0.5 * erf(w1)
    d2 = 0.5 + 0.5 * erf(w2)
    Se = np.exp(b) * S

    call = P * d1 - Se * d2
    put = call - P + Se
    return call, put
N = 5000000
price = np.random.uniform(10.0, 50.0, N)
strike = np.random.uniform(10.0, 50.0, N)
t = np.random.uniform(1.0, 2.0, N)
black_scholes(price, strike, t, 0.1, 0.2)`

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

 5 black_scholes(price, strike, t, 0.1, 0.2)

/srv/conda/envs/notebook/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    480                 e.patch_message(msg)
    481 
--> 482             error_rewrite(e, 'typing')
    483         except errors.UnsupportedError as e:
    484             # Something unsupported is present in the user code, add help info

/srv/conda/envs/notebook/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    421                 raise e
    422             else:
--> 423                 raise e.with_traceback(None)
    424 
    425         argtypes = []

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<ufunc 'erf'>) found for signature:
 
 >>> erf(array(float64, 1d, C))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'erf': File: numba_scipy/special/overloads.py: Line 9.
        With argument(s): '(array(float64, 1d, C))':
       No match.

During: resolving callee type: Function(<ufunc 'erf'>)
During: typing of call at /tmp/ipykernel_61/1298500731.py (13)

File "../../../tmp/ipykernel_61/1298500731.py", line 13:
<source missing, REPL/exec in use?>
-->

**Comment by tianlinzx** [comment]
This is the full trace of error
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
/tmp/ipykernel_86/2146507666.py in <module>
      3 strike = np.random.uniform(10.0, 50.0, N)
      4 t = np.random.uniform(1.0, 2.0, N)
----> 5 black_scholes(price, strike, t, 0.1, 0.2)

/srv/conda/envs/notebook/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    480                 e.patch_message(msg)
    481 
--> 482             error_rewrite(e, 'typing')
    483         except errors.UnsupportedError as e:
    484             # Something unsupported is present in the user code, add help info

/srv/conda/envs/notebook/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    421                 raise e
    422             else:
--> 423                 raise e.with_traceback(None)
    424 
    425         argtypes = []

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<ufunc 'erf'>) found for signature:
 
 >>> erf(array(float64, 1d, C))
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload of function 'erf': File: numba_scipy/special/overloads.py: Line 9.
     With argument(s): '(array(float64, 1d, C))':
    No match.

During: resolving callee type: Function(<ufunc 'erf'>)
During: typing of call at /tmp/ipykernel_86/2906401730.py (12)


File "../../../tmp/ipykernel_86/2906401730.py", line 12:
<source missing, REPL/exec in use?>

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the exception reported is coming from `numba-scipy`, and the lack of support for vectorized versions of the `scipy.special` module. xref this ticket requesting it: https://github.com/numba/numba-scipy/issues/56 and this PR which implements: https://github.com/numba/numba-scipy/pull/58

I suggest following up on/subscribing to the `numba-scipy` issues if this is important to you.

**Comment by gmarkall** [comment]
Closing as this is related to numba-scipy rather than directly a Numba issue
