### ISSUE TITLE
Delays on first operations with numba objects

### ISSUE THREAD

**Issue by ostruk** [numba/numba#7909]
I noticed that first operations on numba objects (virtually of any kind) in python result in delays. If an application has time critical functions buried somewhere deep in the project, first calls to those functions will be slow. I'm on numba 0.53.1, python 3.9.5.

```python
from numba import types
from numba.typed import Dict

from utils import timeStart, timeEnd

timeStart()

config = Dict.empty(
    key_type=types.unicode_type,
    value_type=types.float64,
)
timeEnd('created dict')

config['a']=0.34
timeEnd('set first')

config['b']=0.34
timeEnd('set second')

config['c']=1
timeEnd('first int cast')

config['d']=1
timeEnd('second int cast')
```
Produces output:
```
TIMING: 443.9735412597656 : created dict
TIMING: 1251.4581680297852 : set first
TIMING: 0.0 : set second
TIMING: 227.9815673828125 : first int cast
TIMING: 0.0 : second int cast
```

To deal with this I have to create a file that gets included with the project that contains code to "kick" numba to initialize any of the operations I may use in code later:

```python
strStrDict = Dict.empty(key_type=unicode_type,value_type=unicode_type)
strStrDict['a']='a'
strFloatArrDict = Dict.empty(key_type=unicode_type,value_type=floatListType)
strFloatArrDict['a']=List([0.1])
dictIntArr= Dict.empty(key_type=int64,value_type=arrayType1dF)
dictIntArr[2]=np.zeros(2, dtype=np.float64)
...
```

This file itself now takes about 15 seconds to parse and is obviously a cumbersome way of dealing with the issue.

Why does this happen and are there any work arounds? 

Thanks.

**Comment by guilhermeleobas** [comment]
Hi @ostruk,

It is likely this overhead is due to Numba compiling the typed dictionary for the given key and value types. So, whenever you call a function for the first time, Numba has to compile it for the given types.

```python
from numba import types
from numba.typed import Dict
from time import time

t = time()
print('start')

config = Dict.empty(
    key_type=types.unicode_type,
    value_type=types.float64,
)
print(f'created dict {time() - t}')

config['a']=0.34
print(f'set first {time() - t}')

config['b']=0.34
print(f'set second {time() - t}')

config['c']=1
print(f'first int cast {time() - t}')

config['d']=1
print(f'second int cast {time() - t}')
```
If one runs this file with `NUMBA_DISABLE_JIT=1 python file.py`, the overhead is unnoticeable.

Something you can try is to move initialization to a jitted function with [caching enabled](https://numba.readthedocs.io/en/stable/developer/caching.html?highlight=caching#notes-on-caching) (`@njit(cache=True)`). If caching succeeds, Numba will compile the init function only once and reuse it in subsequent executions.

```python
# run with:
# mkdir tmp
# NUMBA_CACHE_DIR=tmp NUMBA_DEBUG_CACHE=1 python file.py
from numba import types
from numba.typed import Dict
from time import time
from numba import njit

@njit(cache=True)
def foo():
    config = Dict.empty(
        key_type=types.unicode_type,
        value_type=types.float64,
    )
    config['a']=0.34
    config['b']=0.34
    config['c']=1
    config['d']=1
    return config

t = time()
print(foo())
print(time() - t)
```

**Comment by guilhermeleobas** [comment]
> This file itself now takes about 15 seconds to parse and is obviously a cumbersome way of dealing with the issue.

@ostruk, can you share an example where this issue happen?

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
