### ISSUE TITLE
NUMBA_DUMP_IR generate duplicates

### ISSUE THREAD

**Issue by sfornengo** [numba/numba#7912]
for eg test.py:

```
import numba as nb

@nb.njit()
def test(i) :
    return i+1

print(test(2))
```

I am using:
NUMBA_DUMP_IR=1 python test.py > test.ll

In test.ll I find function test is generated 2 times:

```
---------------------------------IR DUMP: test----------------------------------
label 0:
    i = arg(0, name=i)                       ['i']
    $const4.1 = const(int, 1)                ['$const4.1']
    $6binary_add.2 = i + $const4.1           ['$6binary_add.2', '$const4.1', 'i']
    $8return_value.3 = cast(value=$6binary_add.2) ['$6binary_add.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']

---------------------------------IR DUMP: test----------------------------------
label 0:
    i = arg(0, name=i)                       ['i']
    $const4.1 = const(int, 1)                ['$const4.1']
    $6binary_add.2 = i + $const4.1           ['$6binary_add.2', '$const4.1', 'i']
    $8return_value.3 = cast(value=$6binary_add.2) ['$6binary_add.2', '$8return_value.3']
    return $8return_value.3                  ['$8return_value.3']

3
```

Is this normal ?
On bigger code functions are even generated 4 times producing very big dump file...

**Comment by sfornengo** [comment]
Simplest example:

```
import numba as nb

@nb.njit()
def test(s) :
    print(s)

print(test('hello'))
```
NUMBA_DUMP_IR=1 python test.py > test.ll

---------------------------------IR DUMP: test----------------------------------
label 0:
    s = arg(0, name=s)                       ['s']
    $2load_global.0 = global(print: <built-in function print>) ['$2load_global.0']
    $6call_function.2 = call $2load_global.0(s, func=$2load_global.0, args=[Var(s, test.py:5)], kws=(), vararg=None, target=None) ['$2load_global.0', '$6call_function.2', 's']
    $const10.3 = const(NoneType, None)       ['$const10.3']
    $12return_value.4 = cast(value=$const10.3) ['$12return_value.4', '$const10.3']
    return $12return_value.4                 ['$12return_value.4']

---------------------------------IR DUMP: test----------------------------------
label 0:
    s = arg(0, name=s)                       ['s']
    $2load_global.0 = global(print: <built-in function print>) ['$2load_global.0']
    $6call_function.2 = call $2load_global.0(s, func=$2load_global.0, args=[Var(s, test.py:5)], kws=(), vararg=None, target=None) ['$2load_global.0', '$6call_function.2', 's']
    $const10.3 = const(NoneType, None)       ['$const10.3']
    $12return_value.4 = cast(value=$const10.3) ['$12return_value.4', '$const10.3']
    return $12return_value.4                 ['$12return_value.4']

______________________________________________________________________
REWRITING (RewritePrintCalls):
    s = arg(0, name=s)                       ['s']
    $2load_global.0 = global(print: <built-in function print>) ['$2load_global.0']
    $6call_function.2 = call $2load_global.0(s, func=$2load_global.0, args=[Var(s, test.py:5)], kws=(), vararg=None, target=None) ['$2load_global.0', '$6call_function.2', 's']
    $const10.3 = const(NoneType, None)       ['$const10.3']
    $12return_value.4 = cast(value=$const10.3) ['$12return_value.4', '$const10.3']
    return $12return_value.4                 ['$12return_value.4']
____________________________________________________________
    s = arg(0, name=s)                       ['s']
    $2load_global.0 = global(print: <built-in function print>) ['$2load_global.0']
    print(s)                                 ['s']
    $6call_function.2 = const(NoneType, None) ['$6call_function.2']
    $const10.3 = const(NoneType, None)       ['$const10.3']
    $12return_value.4 = cast(value=$const10.3) ['$12return_value.4', '$const10.3']
    return $12return_value.4                 ['$12return_value.4']
______________________________________________________________________
hello
None

test IR are duplicated...

**Comment by guilhermeleobas** [comment]
Hi @sfornengo, thanks for the report.

This is normal. The first `IR DUMP` you see is from right after Numba runs the IR Processing function pass. The second one is after `InlineClosureLikes`. There are other places in this file which dumps the IR if one sets the `NUMBA_DEBUG=1`. See:

https://github.com/numba/numba/blob/181f57c22e8b9708f5864196ef4f254895181374/numba/core/untyped_passes.py#L123-L130

https://github.com/numba/numba/blob/181f57c22e8b9708f5864196ef4f254895181374/numba/core/untyped_passes.py#L214-L217

But there's should be a text indicating where this IR is coming from (i.e. `--IR DUMP [InlineClosureLikes]: test--`)

>  On bigger code functions are even generated 4 times producing very big dump file...

As I see it, the flags `DEBUG` and `DUMP_IR` should have the behavior described below. This would reduce the size dump you're seeing.
* `NUMBA_DEBUG=1` dumps the IR after every function pass.
* `NUMBA_DUMP_IR=1` should dump the unoptimized IR (after `IRProcessing`) and the optimized one (before code generation).

I'll mark this for discussion at the next triage meeting.
