### ISSUE TITLE
llvmlite too low version

### ISSUE THREAD

**Issue by jinfagang** [numba/numba#7931]
Please stop fix llvm version in llvmlite, the latest version 13.1 was out for many years.... this fixed requirements stops a lot of building requires numba

**Comment by seibert** [comment]
Hi, we appreciate that not using the latest LLVM can be frustrating, but we have found from past experience that new releases of LLVM sometimes cause unexpected problems with llvmlite or Numba.  As a result, we only update the supported LLVM version once we have been able to thoroughly test it.  We hope to be able to do these updates more quickly in the future as we have a new developer who will focus on the LLVM-related parts of Numba.

Is there a specific feature in LLVM 13 that you need?

**Comment by sklam** [comment]
The LLVM version requirement should only affect the build. Llvmlite can statically link to LLVM to prevent having a runtime dependency of LLVM. This will allow you to have multiple versions of LLVM more easily. 

Numba needs a patched version of LLVM for some feature to work correctly. See current set of patches at: https://github.com/numba/llvmlite/blob/f27ac6f9d72c139ffce738633eabfc712ca5238f/conda-recipes/llvmdev/meta.yaml#L16-L24

More info can be found at https://llvmlite.readthedocs.io/en/latest/faqs.html#why-doesn-t-llvmlite-always-support-the-latest-release-s-of-llvm .

**Comment by jinfagang** [comment]
@sklam @seibert thanks for your reply. it was because of my system installed llvm 13, and bundled with a bounch of libs like tvm etc. it's not likely easily to uninstall and reinstall which is cubersome. 
But numba requires exactly llvm version of 11. 

However, I have solved it by using conda.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
