### ISSUE TITLE
Incorrect prange loop index typing, but only in parallel mode

### ISSUE THREAD

**Issue by jisaacsNRL** [numba/numba#7934]
(Numba 55.1, Python 3.9.10, both from the conda-forge channel, running in MacOS 12.2.1)

I'm trying to conditionally loop over an array in reverse order. For context, it doesn't make sense in the actual project to modify the range parameters to achieve the same effect.

Example:

```
from numba import njit, prange
import numpy as np

testarray = np.empty(100)

@njit(parallel=True)
def test(arrayin, backward):
    nx = len(arrayin)
    for ix in prange(nx):
        if backward:
            ixA = nx - ix - 1
        else:
            ixA = ix
        arrayin[ixA] = ix

test(testarray, False)
```

This produces the following message:

```
[TypingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(array(float64, 1d, C), float64, uint64)
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(array(float64, 1d, C), float64, uint64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 176.
    With argument(s): '(array(float64, 1d, C), float64, uint64)':
   Rejected as the implementation raised a specific error:
     NumbaTypeError: unsupported array index type float64 in [float64]
  raised from /Users/joshmac/opt/anaconda3/envs/pycap/lib/python3.9/site-packages/numba/core/typing/arraydecl.py:72

During: typing of setitem at <ipython-input-113-5a0a8045804f> (11)

File "<ipython-input-113-5a0a8045804f>", line 11:
def test(arrayin, backward):
    <source elided>
            ixA = ix
        arrayin[ixA] = ix
        ^

During: lowering "id=7[LoopNest(index_variable = parfor_index.540, range = (0, arrayin_size0.539, 1))]{40: <ir.Block at <ipython-input-113-5a0a8045804f> (10)>, 44: <ir.Block at <ipython-input-113-5a0a8045804f> (11)>, 20: <ir.Block at <ipython-input-113-5a0a8045804f> (6)>, 26: <ir.Block at <ipython-input-113-5a0a8045804f> (8)>}Var(parfor_index.540, <ipython-input-113-5a0a8045804f>:6)" at <ipython-input-113-5a0a8045804f> (6)]()
```

The code works with parallel=True, fails compilation with parallel=False. Forcing explicit typing of ixA in the array access (i.e. `arrayin[numba.types.int64(ixA)]`) works as a stopgap, so this isn't personally urgent.

**Comment by sklam** [comment]
> The code works with parallel=True, fails compilation with parallel=False

Probably a typo. It works with `parallel=False` and fails with `parallel=True`.

**Comment by DrTodd13** [comment]
Not a bug.  In parallel=True, ix is typed as unsigned.  So, when you do nx - ix you have "signed - unsigned" and the type unification of that is float.  Then, you can't index an array with a float.   In general, index calculations should be avoided in parallel=True.  Better perhaps is something like the following.  

```
@njit(parallel=True)
def test(arrayin, backward):
    nx = len(arrayin)
    for ix in prange(nx):
        if backward:
            arrayin[ix] = nx - ix - 1
        else:
            arrayin[ix] = ix
```

If you want to keep your code largely as it is then I'd cast ix as signed immediately inside the loop.  This code will be slower because you have to do negative index checks on the arrayin access.  Unsigned indices are faster when possible.

```
@njit(parallel=True)
def test(arrayin, backward):
    nx = len(arrayin)
    for ix in prange(nx):
        six = numba.types.int64(ix)
        if backward:
            ixA = nx - six - 1
        else:
            ixA = six
        arrayin[ixA] = ix
```

**Comment by jisaacsNRL** [comment]
Thank you for the clarification.

I will say, it is rather unintuitive that the typing of ix is different between parallel=True and parallel=False. I would recommend this tidbit be included in the numba documentation for automatic parallelization (assuming it is not already I and just haven't been able to find it).

**Comment by stuartarchibald** [comment]
I've written up a potential improvement that needs investigating here https://github.com/numba/numba/issues/7935
