### ISSUE TITLE
Cache temp filename not unique across nodes

### ISSUE THREAD

**Issue by markweissman** [numba/numba#7952]
## Feature request

In numba/core/caching.py, tmpname is supposed to be unique to avoid race conditions.
Please change this to use uuid.uuid1() instead of os.getpid().  I'm using numba in either
a slurm or ray cluster where jobs on different nodes may have the same pid.

Thanks, Mark W

    def _open_for_write(self, filepath):
         tmpname = '%s.tmp.%d' % (filepath, os.getpid().)

should be:

    def _open_for_write(self, filepath):
         tmpname = '%s.tmp.%s' % (filepath, uuid.uuid1())

**Comment by markweissman** [comment]
That is exactly the problem.  I saw this occasionally on our Slurm cluster but I see it all the time with ray autoscaling clusters.
Its exacerbated by the short life of the worker nodes, which start at the same time and have low PIDs for all jobs.
UUID4 would be fine, and you could probably get away with just using socket.gethostname() and PID.

**Comment by stuartarchibald** [comment]
@markweissman Many thanks for confirming, I think this is a bug as writing to a shared cache location is potentially broken in a such an environment (potentially quite common in HPC use cases). A patch to fix would be welcomed.
