### ISSUE TITLE
insert() casting entire list 

### ISSUE THREAD

**Issue by adam-jb** [numba/numba#7953]
Inserting an int32 into a list of int32s casts all items in the list to int. I'd expect all objects in the list to be int32. Is this an error or by design?

Numba Version: 0.55.1
Python Version: 3.8

-----Code
from numba.core.types import int32
from numba import njit

input_list = [int32(i) for i in range(3)]

for k in input_list:
    print(type(k))

    
@njit
def single_insert(input_list):
    return input_list.insert( int32(2), int32(500) ) 

single_insert(input_list)

for k in input_list:
    print(type(k))
-----End of code

The first print statement shows all values in the list are int32's:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>

The 2nd print statement shows all values in the list have been casted to int's:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

**Comment by esc** [comment]
> Inserting an int32 into a list of int32s casts all items in the list to int. I'd expect all objects in the list to be int32. Is this an error or by design?
> 
> Numba Version: 0.55.1 Python Version: 3.8
> 
> -----Code from numba.core.types import int32 from numba import njit
> 
> input_list = [int32(i) for i in range(3)]
> 
> for k in input_list: print(type(k))
> 
> @njit def single_insert(input_list): return input_list.insert( int32(2), int32(500) )
> 
> single_insert(input_list)
> 
> for k in input_list: print(type(k)) -----End of code
> 
> The first print statement shows all values in the list are int32's: <class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
> 
> The 2nd print statement shows all values in the list have been casted to int's: <class 'int'> <class 'int'> <class 'int'> <class 'int'>

Thank you, I can reproduce this. My guess is that during the "reflection" process, which updates the returned list with any changes made, will box all of the integers contained within the list and so they end up becoming native Python `int`s. My further guess is that this may be by accident and that perhaps the case of using `numpy` integers in a reflected list was not considered.

**Comment by seibert** [comment]
This is another instance of the tension in Numba between NumPy types and Python types.  A typed list behaves kind of like Numpy array storage with the API of the Python list, so one could argue for either convention.  We have this problem in general with boxing scalar integer types in Numba:
``` python
In [1]: import numba

In [2]: import numpy as np

In [3]: @numba.njit
   ...: def return_one():
   ...:     return np.int32(1)
   ...:

In [4]: return_one()
Out[4]: 1

In [5]: type(return_one())
Out[5]: int
```

**Comment by adam-jb** [comment]
Thanks all, this has been tremendously helpful! I've rewritten my code using typed lists rather than reflected, and all is good!

**Comment by adam-jb** [comment]
However! On converting a function based on reflected lists to use typed lists, it now takes 25x longer to execute. The code involves inserts and deletions. Are these specific ways to do this which gives the same performance as reflected lists? (eg: some guidance on why this happens and how to avoid it)

Thanks again for your help so far

**Comment by esc** [comment]
> However! On converting a function based on reflected lists to use typed lists, it now takes 25x longer to execute. The code involves inserts and deletions. Are these specific ways to do this which gives the same performance as reflected lists? (eg: some guidance on why this happens and how to avoid it)
> 
> Thanks again for your help so far

Unfortunately the typed-list still suffers from some performance concerns. There are quite a few open issues on GitHub about this already, perhaps you can find some additional insights there. Otherwise, you can post the code on Discourse and we can start a discussion on how to accelerate it.
