### ISSUE TITLE
Numba not working in containerized environment, like Sagemaker

### ISSUE THREAD

**Issue by roccopietrini** [numba/numba#7970]
- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I'm trying to migrate some code from Google Colab to AWS Sagemaker. I have a training script and at the end of the training I evaluate results using some functions, here comes the problem. I have troubles using numba. I have this function for cosine similarity:

```
@jit(nopython=True)
def fast_cosine(u, v):
    m = u.shape[0]
    udotv = 0
    u_norm = 0
    v_norm = 0
    for i in range(m):
        if (np.isnan(u[i])) or (np.isnan(v[i])):
            continue

        udotv += u[i] * v[i]
        u_norm += u[i] * u[i]
        v_norm += v[i] * v[i]

    u_norm = np.sqrt(u_norm)
    v_norm = np.sqrt(v_norm)

    if (u_norm == 0) or (v_norm == 0):
        ratio = 1.0
    else:
        ratio = udotv / (u_norm * v_norm)
    return ratio
```
That function works flawlessy in Google Colab, taking couple of minutes to complete. When I use the same in Sagemaker, it takes hours. I also tried to add `cache=True` and to set `NUMBA_CACHE_DIR `to a path surely writable, in my case `/opt/ml/model`. I also set `NUMBA_DEBUG_CACHE `but the only output I get is this:

```
[cache] index saved to '/opt/ml/model/code_ec9d94cfa840991722b08139d5ab141658f37feb/train.fast_cosine-199.py38.nbi'
[cache] data saved to '/opt/ml/model/code_ec9d94cfa840991722b08139d5ab141658f37feb/train.fast_cosine-199.py38.1.nbc'
```

This function takes ages on AWS Sagemaker, while it takes only couple of minutes in Google Colab (where it takes much more without using Numba).

**Comment by stuartarchibald** [comment]
Thanks for the report. Does the function above actually run to completion on Sagemaker i.e. it works, it's just slow?

**Comment by roccopietrini** [comment]
Yes it completes, but It takes 2 hours instead of 2 minutes.. so I guess numba is not working in the sense that the function get executed without numba optimization. In addition the same happens if I replace numba with functions from fastdist library (which internally uses numba), they are super-slow..

**Comment by gmarkall** [comment]
Can you provide the output of `numba -s` on Sagemaker?

**Comment by roccopietrini** [comment]
Sure, here the output


System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2022-04-08 12:49:20.588156
UTC start time                                : 2022-04-08 12:49:20.588163
Running time (s)                              : 1.40637
__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : broadwell
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7
CFS Restrictions (CPUs worth of runtime)      : None
CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                cmov cx16 cx8 f16c fma fsgsbase
                                                fxsr invpcid lzcnt mmx movbe
                                                pclmul popcnt prfchw rdrnd rdseed
                                                rtm sahf sse sse2 sse3 sse4.1
                                                sse4.2 ssse3 xsave xsaveopt
Memory Total (MB)                             : 61400
Memory Available (MB)                         : 58846
__OS Information__
Platform Name                                 : Linux-4.14.268-139.500.amzn1.x86_64-x86_64-with-glibc2.31
Platform Release                              : 4.14.268-139.500.amzn1.x86_64
OS Name                                       : Linux
OS Version                                    : #1 SMP Wed Mar 2 18:48:10 UTC 2022
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31
__Python Information__
Python Compiler                               : GCC 9.4.0
Python Implementation                         : CPython
Python Version                                : 3.9.10
Python Locale                                 : en_US.UTF-8
__LLVM Information__
LLVM Version                                  : 10.0.1
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11040
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'Tesla V100-SXM2-16GB'                              [SUPPORTED]
                      compute capability: 7.0
                           pci device id: 30
                              pci bus id: 0
Summary:
#0111/1 devices are supported
CUDA Libraries Test Output:
Finding cublas from System
#011named  libcublas.so.11.4.1.1043
#011trying to open library...#011ok
Finding cusparse from System
#011named  libcusparse.so.11.4.1.1152
#011trying to open library...#011ok
Finding cufft from System
#011named  libcufft.so.10.4.1.152
#011trying to open library...#011ok
Finding curand from System
#011named  libcurand.so.10.2.3.152
#011trying to open library...#011ok
Finding nvvm from System
#011named  libnvvm.so.4.0.0
#011trying to open library...#011ok
Finding cudart from System
#011named  libcudart.so.11.2.152
#011trying to open library...#011ok
Finding cudadevrt from System
#011named  libcudadevrt.a
Finding libdevice from System
#011searching for compute_20...#011ok
#011searching for compute_30...#011ok
#011searching for compute_35...#011ok
#011searching for compute_50...#011ok
__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None
__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False
__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
__Numba Environment Variable Information__
NUMBA_DEBUG_CACHE                             : 1
NUMBA_CACHE_DIR                               : /opt/ml/model
__Conda Information__
Conda not available.
__Installed Packages__
Package                              Version
------------------------------------ ---------------
absl-py                              0.10.0
argon2-cffi                          21.3.0
argon2-cffi-bindings                 21.2.0
asttokens                            2.0.5
astunparse                           1.6.3
attrs                                20.3.0
autovizwidget                        0.19.1
awscli                               1.22.72
backcall                             0.2.0
bcrypt                               3.2.0
bleach                               4.1.0
bokeh                                2.4.2
boto3                                1.21.17
botocore                             1.24.17
cachetools                           5.0.0
certifi                              2021.10.8
cffi                                 1.15.0
charset-normalizer                   2.0.12
cloudpickle                          2.0.0
cmake                                3.18.2.post1
colorama                             0.4.3
cryptography                         36.0.1
cycler                               0.11.0
decorator                            5.1.1
defusedxml                           0.7.1
dill                                 0.3.4
docutils                             0.15.2
entrypoints                          0.4
executing                            0.8.3
filelock                             3.6.0
flatbuffers                          2.0
fonttools                            4.30.0
fsspec                               2022.2.0
gast                                 0.5.3
gevent                               21.12.0
google-auth                          2.6.0
google-auth-oauthlib                 0.4.6
google-pasta                         0.2.0
googleapis-common-protos             1.55.0
greenlet                             1.1.2
grpcio                               1.44.0
gssapi                               1.7.3
h5py                                 3.1.0
hdijupyterutils                      0.19.1
horovod                              0.23.0
idna                                 3.3
imageio                              2.16.1
importlib-metadata                   4.11.2
inotify-simple                       1.2.1
ipykernel                            5.5.6
ipython                              8.1.1
ipython-genutils                     0.2.0
ipywidgets                           7.6.5
jedi                                 0.18.1
Jinja2                               3.0.3
jmespath                             0.10.0
joblib                               1.1.0
jsonschema                           4.4.0
jupyter                              1.0.0
jupyter-client                       7.1.2
jupyter-console                      6.4.3
jupyter-core                         4.9.2
jupyterlab-pygments                  0.1.2
jupyterlab-widgets                   1.0.2
keras                                2.8.0
Keras-Preprocessing                  1.1.2
kiwisolver                           1.3.2
krb5                                 0.3.0
libclang                             13.0.0
llvmlite                             0.36.0
Markdown                             3.3.6
MarkupSafe                           2.1.0
matplotlib                           3.5.1
matplotlib-inline                    0.1.3
mistune                              0.8.4
mock                                 4.0.3
mpi4py                               3.0.3
multiprocess                         0.70.12.2
nbclient                             0.5.12
nbconvert                            6.4.2
nbformat                             5.2.0
nest-asyncio                         1.5.4
nose                                 1.3.7
notebook                             6.4.8
numba                                0.53.1
numpy                                1.22.3
oauthlib                             3.2.0
opencv-python                        4.5.5.64
opt-einsum                           3.3.0
packaging                            21.3
pandas                               1.4.1
pandocfilters                        1.5.0
paramiko                             2.9.2
parso                                0.8.3
pathos                               0.2.8
pexpect                              4.8.0
pickleshare                          0.7.5
Pillow                               9.0.1
pip                                  22.0.4
plotly                               5.6.0
pox                                  0.3.0
ppft                                 1.6.6.4
prometheus-client                    0.13.1
promise                              2.3
prompt-toolkit                       3.0.28
protobuf                             3.19.4
protobuf3-to-dict                    0.1.5
psutil                               5.9.0
ptyprocess                           0.7.0
pure-eval                            0.2.2
pyarrow                              7.0.0
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pybind11                             2.9.1
pycparser                            2.21
pyfunctional                         1.4.3
Pygments                             2.11.2
pyinstrument                         3.4.2
pyinstrument-cext                    0.2.4
PyNaCl                               1.5.0
pyparsing                            3.0.7
pyrsistent                           0.18.1
pyspnego                             0.5.0
python-dateutil                      2.8.1
pytz                                 2021.3
PyYAML                               5.4.1
pyzmq                                22.3.0
qtconsole                            5.2.2
QtPy                                 2.0.1
requests                             2.27.1
requests-kerberos                    0.14.0
requests-oauthlib                    1.3.1
retrying                             1.3.3
rsa                                  4.7.2
s3fs                                 0.4.2
s3transfer                           0.5.2
sagemaker                            2.78.0
sagemaker-experiments                0.1.35
sagemaker-studio-analytics-extension 0.0.2
sagemaker-studio-sparkmagic-lib      0.1.3
sagemaker-tensorflow                 2.8.0.1.14.0
sagemaker-tensorflow-training        20.3.0
sagemaker-training                   4.0.1
scikit-learn                         1.0.2
scipy                                1.7.0
seaborn                              0.11.2
Send2Trash                           1.8.0
setuptools                           60.9.3
shap                                 0.40.0
six                                  1.16.0
sklearn                              0.0
slicer                               0.0.7
smclarify                            0.2
smdebug                              1.0.14b20220311
smdebug-rulesconfig                  1.0.1
smdistributed-dataparallel           1.3.0
sparkmagic                           0.19.1
stack-data                           0.2.0
tabulate                             0.8.9
tenacity                             8.0.1
tensorboard                          2.8.0
tensorboard-data-server              0.6.1
tensorboard-plugin-wit               1.8.1
tensorflow-addons                    0.16.1
tensorflow-datasets                  4.5.2
tensorflow-estimator                 2.8.0
tensorflow-gpu                       2.8.0
tensorflow-io                        0.24.0
tensorflow-io-gcs-filesystem         0.24.0
tensorflow-metadata                  1.7.0
termcolor                            1.1.0
terminado                            0.13.3
testpath                             0.6.0
threadpoolctl                        3.1.0
tornado                              6.1
tqdm                                 4.63.0
traitlets                            5.1.1
typeguard                            2.13.3
typing_extensions                    4.1.1
urllib3                              1.26.8
wcwidth                              0.2.5
webencodings                         0.5.1
Werkzeug                             2.0.3
wheel                                0.37.1
widgetsnbextension                   3.5.2
wrapt                                1.14.0
zipp                                 3.7.0
zope.event                           4.5.0
zope.interface                       5.4.0
No errors reported.
__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.
=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
0

**Comment by roccopietrini** [comment]
Here the output:

```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2022-04-08 12:49:20.588156
UTC start time                                : 2022-04-08 12:49:20.588163
Running time (s)                              : 1.40637
__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : broadwell
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7
CFS Restrictions (CPUs worth of runtime)      : None
CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                cmov cx16 cx8 f16c fma fsgsbase
                                                fxsr invpcid lzcnt mmx movbe
                                                pclmul popcnt prfchw rdrnd rdseed
                                                rtm sahf sse sse2 sse3 sse4.1
                                                sse4.2 ssse3 xsave xsaveopt
Memory Total (MB)                             : 61400
Memory Available (MB)                         : 58846
__OS Information__
Platform Name                                 : Linux-4.14.268-139.500.amzn1.x86_64-x86_64-with-glibc2.31
Platform Release                              : 4.14.268-139.500.amzn1.x86_64
OS Name                                       : Linux
OS Version                                    : #1 SMP Wed Mar 2 18:48:10 UTC 2022
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31
__Python Information__
Python Compiler                               : GCC 9.4.0
Python Implementation                         : CPython
Python Version                                : 3.9.10
Python Locale                                 : en_US.UTF-8
__LLVM Information__
LLVM Version                                  : 10.0.1
__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 11040
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'Tesla V100-SXM2-16GB'                              [SUPPORTED]
                      compute capability: 7.0
                           pci device id: 30
                              pci bus id: 0
Summary:
	1/1 devices are supported
CUDA Libraries Test Output:
Finding cublas from System
	named  libcublas.so.11.4.1.1043
	trying to open library...	ok
Finding cusparse from System
	named  libcusparse.so.11.4.1.1152
	trying to open library...	ok
Finding cufft from System
	named  libcufft.so.10.4.1.152
	trying to open library...	ok
Finding curand from System
	named  libcurand.so.10.2.3.152
	trying to open library...	ok
Finding nvvm from System
	named  libnvvm.so.4.0.0
	trying to open library...	ok
Finding cudart from System
	named  libcudart.so.11.2.152
	trying to open library...	ok
Finding cudadevrt from System
	named  libcudadevrt.a
Finding libdevice from System
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok
__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None
__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False
__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
__Numba Environment Variable Information__
NUMBA_DEBUG_CACHE                             : 1
NUMBA_CACHE_DIR                               : /opt/ml/model
__Conda Information__
Conda not available.
__Installed Packages__
Package                              Version
------------------------------------ ---------------
absl-py                              0.10.0
argon2-cffi                          21.3.0
argon2-cffi-bindings                 21.2.0
asttokens                            2.0.5
astunparse                           1.6.3
attrs                                20.3.0
autovizwidget                        0.19.1
awscli                               1.22.72
backcall                             0.2.0
bcrypt                               3.2.0
bleach                               4.1.0
bokeh                                2.4.2
boto3                                1.21.17
botocore                             1.24.17
cachetools                           5.0.0
certifi                              2021.10.8
cffi                                 1.15.0
charset-normalizer                   2.0.12
cloudpickle                          2.0.0
cmake                                3.18.2.post1
colorama                             0.4.3
cryptography                         36.0.1
cycler                               0.11.0
decorator                            5.1.1
defusedxml                           0.7.1
dill                                 0.3.4
docutils                             0.15.2
entrypoints                          0.4
executing                            0.8.3
filelock                             3.6.0
flatbuffers                          2.0
fonttools                            4.30.0
fsspec                               2022.2.0
gast                                 0.5.3
gevent                               21.12.0
google-auth                          2.6.0
google-auth-oauthlib                 0.4.6
google-pasta                         0.2.0
googleapis-common-protos             1.55.0
greenlet                             1.1.2
grpcio                               1.44.0
gssapi                               1.7.3
h5py                                 3.1.0
hdijupyterutils                      0.19.1
horovod                              0.23.0
idna                                 3.3
imageio                              2.16.1
importlib-metadata                   4.11.2
inotify-simple                       1.2.1
ipykernel                            5.5.6
ipython                              8.1.1
ipython-genutils                     0.2.0
ipywidgets                           7.6.5
jedi                                 0.18.1
Jinja2                               3.0.3
jmespath                             0.10.0
joblib                               1.1.0
jsonschema                           4.4.0
jupyter                              1.0.0
jupyter-client                       7.1.2
jupyter-console                      6.4.3
jupyter-core                         4.9.2
jupyterlab-pygments                  0.1.2
jupyterlab-widgets                   1.0.2
keras                                2.8.0
Keras-Preprocessing                  1.1.2
kiwisolver                           1.3.2
krb5                                 0.3.0
libclang                             13.0.0
llvmlite                             0.36.0
Markdown                             3.3.6
MarkupSafe                           2.1.0
matplotlib                           3.5.1
matplotlib-inline                    0.1.3
mistune                              0.8.4
mock                                 4.0.3
mpi4py                               3.0.3
multiprocess                         0.70.12.2
nbclient                             0.5.12
nbconvert                            6.4.2
nbformat                             5.2.0
nest-asyncio                         1.5.4
nose                                 1.3.7
notebook                             6.4.8
numba                                0.53.1
numpy                                1.22.3
oauthlib                             3.2.0
opencv-python                        4.5.5.64
opt-einsum                           3.3.0
packaging                            21.3
pandas                               1.4.1
pandocfilters                        1.5.0
paramiko                             2.9.2
parso                                0.8.3
pathos                               0.2.8
pexpect                              4.8.0
pickleshare                          0.7.5
Pillow                               9.0.1
pip                                  22.0.4
plotly                               5.6.0
pox                                  0.3.0
ppft                                 1.6.6.4
prometheus-client                    0.13.1
promise                              2.3
prompt-toolkit                       3.0.28
protobuf                             3.19.4
protobuf3-to-dict                    0.1.5
psutil                               5.9.0
ptyprocess                           0.7.0
pure-eval                            0.2.2
pyarrow                              7.0.0
pyasn1                               0.4.8
pyasn1-modules                       0.2.8
pybind11                             2.9.1
pycparser                            2.21
pyfunctional                         1.4.3
Pygments                             2.11.2
pyinstrument                         3.4.2
pyinstrument-cext                    0.2.4
PyNaCl                               1.5.0
pyparsing                            3.0.7
pyrsistent                           0.18.1
pyspnego                             0.5.0
python-dateutil                      2.8.1
pytz                                 2021.3
PyYAML                               5.4.1
pyzmq                                22.3.0
qtconsole                            5.2.2
QtPy                                 2.0.1
requests                             2.27.1
requests-kerberos                    0.14.0
requests-oauthlib                    1.3.1
retrying                             1.3.3
rsa                                  4.7.2
s3fs                                 0.4.2
s3transfer                           0.5.2
sagemaker                            2.78.0
sagemaker-experiments                0.1.35
sagemaker-studio-analytics-extension 0.0.2
sagemaker-studio-sparkmagic-lib      0.1.3
sagemaker-tensorflow                 2.8.0.1.14.0
sagemaker-tensorflow-training        20.3.0
sagemaker-training                   4.0.1
scikit-learn                         1.0.2
scipy                                1.7.0
seaborn                              0.11.2
Send2Trash                           1.8.0
setuptools                           60.9.3
shap                                 0.40.0
six                                  1.16.0
sklearn                              0.0
slicer                               0.0.7
smclarify                            0.2
smdebug                              1.0.14b20220311
smdebug-rulesconfig                  1.0.1
smdistributed-dataparallel           1.3.0
sparkmagic                           0.19.1
stack-data                           0.2.0
tabulate                             0.8.9
tenacity                             8.0.1
tensorboard                          2.8.0
tensorboard-data-server              0.6.1
tensorboard-plugin-wit               1.8.1
tensorflow-addons                    0.16.1
tensorflow-datasets                  4.5.2
tensorflow-estimator                 2.8.0
tensorflow-gpu                       2.8.0
tensorflow-io                        0.24.0
tensorflow-io-gcs-filesystem         0.24.0
tensorflow-metadata                  1.7.0
termcolor                            1.1.0
terminado                            0.13.3
testpath                             0.6.0
threadpoolctl                        3.1.0
tornado                              6.1
tqdm                                 4.63.0
traitlets                            5.1.1
typeguard                            2.13.3
typing_extensions                    4.1.1
urllib3                              1.26.8
wcwidth                              0.2.5
webencodings                         0.5.1
Werkzeug                             2.0.3
wheel                                0.37.1
widgetsnbextension                   3.5.2
wrapt                                1.14.0
zipp                                 3.7.0
zope.event                           4.5.0
zope.interface                       5.4.0
No errors reported.
__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.
=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
0
```

**Comment by stuartarchibald** [comment]
@roccopietrini Thanks, some questions:

1. If you create a new environment with just Numba 0.55.1 and NumPy 1.21 in it, does it reproduce in that?
2. What size is your data set? Is it near the memory allocation limit?
3. If you run e.g. a 1 element array as `u` and `v` through the function in the OP does the result come back quickly?

**Comment by gmarkall** [comment]
No problem, thanks for following up!
