### ISSUE TITLE
Cannot import numba on AWS Lambda:'cannot import name '_typeconv' from 'numba.typeconv' (/mnt/access/numba/typeconv/__init__.py)'

### ISSUE THREAD

**Issue by mtfbs** [numba/numba#7975]
I have an AWS Lambda function with Python 3.7 runtime and AWSLambda-Python37-SciPy1x lambda layer added.
I have my python dependencies (such as numba) installed on a EFS directory that I add to the path that the Lambda function can access.

I can inport numpy, but trying to import numba gives the following error:

```
Runtime.ImportModuleError: Unable to import module 'lambda_function': Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:
python setup.py build_ext --inplace
(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)
If you are not working on Numba development:
Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new
If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba
Thanks in advance for your help in improving Numba!
The original error was: 'cannot import name '_typeconv' from 'numba.typeconv' (/mnt/access/numba/typeconv/__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:
sys.executable: /var/lang/bin/python3.7
Traceback (most recent call last):
```

I tried with the numba versions 0.45.0, 0.47.0, 0.48.0, 0.49.0, 0.49.1, 0.55.1 and the error is the same in all versions.

I saw [this response](https://github.com/numba/numba/issues/6973#issuecomment-988581265), but when I delete de numba files from the EFS directory, i get a ```No module named 'numba'``` error, which indicates that there is no other numba version installed.

Below is the full code of the AWS Lambda function:

```
import sys

sys.path.append("/mnt/access")

import os, json, sys

import numba 


def lambda_handler(event, context):

    return {
        'statusCode': 200,
        'body': json.dumps('All OK')
    }


```

**Comment by guilhermeleobas** [comment]
Hi, @mtfbs. Can you share how did you install Numba in the EFS directory? It was from source or it was via pip/conda?

**Comment by mtfbs** [comment]
Hi @guilhermeleobas, i did it exactly with ```pip install --target . numba==0.47.0```, for version 0.47.0, for example

**Comment by mtfbs** [comment]
Ok, thanks for answering. I've created [a post about this in the AWS re:Post forum](https://repost.aws/questions/QUbuqOvYb-TMS5-wEzOu7pbQ/cannot-import-numba-python-package-inside-aws-lambda-function). If I get any help, I'll post here relevant updates.

**Comment by ogencoglu** [comment]
I get to manage numba running on AWS Lambda but it fails only on large arrays (`@njit(parallel=True)`). Is there a logic in `parallel=True` so that it sometimes try to parallelize (problem for Lambda) and sometimes not depending on its own logic?

**Comment by guilhermeleobas** [comment]
AFAIK, depending on what you're doing, parallel can be nondeterministic. Is the code returning a different result? Can you open a new issue for this with a reproducer?

**Comment by ogencoglu** [comment]
@guilhermeleobas Do you mean the logic to parallelize or not when `parallel=True` is non-deterministic or the actual results of the numba code? If latter, how can the results be non-deterministic if the pure numpy version is deterministic? Never assumed this would be possible therefore I did not check that. Sounds like a big deal to be honest.

**Comment by guilhermeleobas** [comment]
Can you open a new issue with a reproducer of what are you trying to achieve?

> actual results of the numba code?

My knowledge of the parallel target is limited, so, read my comment with a grain of salt. But the generated code can have unpredicted behavior when you have race conditions:
https://numba.readthedocs.io/en/stable/user/parallel.html#unsupported-operations
