### ISSUE TITLE
np.full ignores keyword argument names

### ISSUE THREAD

**Issue by charelF** [numba/numba#7982]
## In `np.full`, numba ignores the named keyword arguments. 

```python
import numba
import numpy as np

@numba.jit(nopython=True)
def test1():
    x = np.full(shape=123, fill_value=456)
    print(x.shape)

@numba.jit(nopython=True)
def test2():
    x = np.full(fill_value=456, shape=123)
    print(x.shape)

test1()
test2()
```

outputs

```python
(123,)
(456,)  # WRONG! The shape is given as `shape=123` in the function call!
```

## Bug

Both `test1` and `test2` would be interpereted the same by numpy alone. The only difference between them is the order of the keyword arguments `fill_value` and `shape`. Numba seems to silently ignore this order. I am not sure this is a bug, but this just cost me nearly one hour of debugging. (I am still a very happy Numba user)

## Numba version

```numba                0.55.1```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by guilhermeleobas** [comment]
Thanks for the report @charelF. I can reproduce the error.

**Comment by czgdp1807** [comment]
I think the problem is in the following code where we define `full` function and compile it later. It always assumes that `args[0]` is `shape` and `args[1]` is `fill_value`. I applied the diff (see below) and then it started giving correct results.

https://github.com/numba/numba/blob/63837c7e557db841ad8523b959798635fc7a4ddf/numba/np/arrayobj.py#L3882-L3892

```diff
diff --git a/numba/np/arrayobj.py b/numba/np/arrayobj.py
index 6d5d2f042..25894b5dc 100644
--- a/numba/np/arrayobj.py
+++ b/numba/np/arrayobj.py
@@ -3881,15 +3881,27 @@ def numpy_zeros_like_nd(context, builder, sig, args):
 @glue_lowering(np.full, types.Any, types.Any)
 def numpy_full_nd(context, builder, sig, args):
 
-    def full(shape, value):
-        arr = np.empty(shape, type(value))
-        arr_flat = arr.flat
-        for idx in range(len(arr_flat)):
-            arr_flat[idx] = value
-        return arr
+    if "shape" in args[0].name and "fill_value" in args[1].name:
+        def full(shape, value):
+            arr = np.empty(shape, type(value))
+            arr_flat = arr.flat
+            for idx in range(len(arr_flat)):
+                arr_flat[idx] = value
+            return arr
+
+        res = context.compile_internal(builder, full, sig, args)
+        return impl_ret_new_ref(context, builder, sig.return_type, res)
+    elif "fill_value" in args[0].name and "shape" in args[1].name:
+        def full(value, shape):
+            arr = np.empty(shape, type(value))
+            arr_flat = arr.flat
+            for idx in range(len(arr_flat)):
+                arr_flat[idx] = value
+            return arr
+
+        res = context.compile_internal(builder, full, sig, args)
+        return impl_ret_new_ref(context, builder, sig.return_type, res)
 
-    res = context.compile_internal(builder, full, sig, args)
-    return impl_ret_new_ref(context, builder, sig.return_type, res)
 
 
 @glue_lowering(np.full, types.Any, types.Any, types.DTypeSpec)
```

**Comment by stuartarchibald** [comment]
This is probably `@overload_glue` related, it worked fine until version 0.54. Also, the use of the standard `@overload` works fine:
```python
from numba import njit
import numpy as np
from numba.extending import overload

# This is ok
@njit
def foo(x, y):
    print(x, y)

foo(x=1, y=2j)
foo(y=3j, x=4)

def func(a, b):
    pass

# This is also ok
@overload(func)
def ol_func(a, b):
    def impl(a, b):
        print(a, b)
    return impl

@njit
def bar(x, y):
    func(a=x, b=y)
    func(b=y, a=x)

bar(1, 2j)
```

**Comment by stuartarchibald** [comment]
Think the problem is here:
https://github.com/numba/numba/blob/63837c7e557db841ad8523b959798635fc7a4ddf/numba/core/overload_glue.py#L157-L162
the order of the keys has to match the lowering, but that isn't known at this point (it probably can be known, it's just not written like that). It's also currently relying on insertion order preservation, which is not ideal.

**Comment by czgdp1807** [comment]
I went to the above code section and did some debugging. I found that the call_str and kws_str matches. So, why `full` (inside `numpy_full_nd`) is treating wrong keyword argument ordering. 

```bash
arg_str: , kws_str: shape,fill_value, call_str: shape,fill_value, ol_kwargs: {'shape': int64, 'fill_value': int64}
arg_str: tmp0,tmp1, kws_str: , call_str: tmp0,tmp1, ol_kwargs: {}
output:  (123,)
arg_str: , kws_str: fill_value,shape, call_str: fill_value,shape, ol_kwargs: {'fill_value': int64, 'shape': int64} # The order switches here but still `fill_value` is treated as `shape` and `shape` as `fill_value`.
output:  (456,)
```

**Comment by stuartarchibald** [comment]
I think the caller will be the function calling the NumPy implementation, i.e. user code.

This "overload glue" module is a load of temporary code shims to "glue" together old style split typing and lowering APIs into the new style `@overload` API, it is generating a Python function wrapper around an `@intrinsic` which is done here: https://github.com/numba/numba/blob/63837c7e557db841ad8523b959798635fc7a4ddf/numba/core/overload_glue.py#L175-L181
then this is returned as the implementing function of the `@overload`. There's a guide to using `@overload` here: https://numba.readthedocs.io/en/stable/extending/overloading-guide.html

This is potentially quite a hard problem to deal with, I suspect it's going to require typing information earlier than it's typically available/from a place where it's hard to get it, so as to generate the call site correctly.

**Comment by guilhermeleobas** [comment]
Stuart, does it make sense to start migrating old code to use overload, instead of attempt to fix the "overload glue" part?

**Comment by stuartarchibald** [comment]
> Stuart, does it make sense to start migrating old code to use overload, instead of attempt to fix the "overload glue" part?

@guilhermeleobas Probably something for discussion at the next triage meeting? I've got a patch that migrates `np.empty`, `np.zeros` and `np.ones` already. Translating these functions is quite a detail heavy task but potentially a better place to spend effort. I would hope once the common translation patterns become clear it can progress reasonably quickly and the shim code can be removed.
