### ISSUE TITLE
Numba 0.55.1 runtime error with numpy 1.21.6

### ISSUE THREAD

**Issue by Zaba107** [numba/numba#7995]
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When numba 0.55.1 is installed with numpy 1.21.6 we get an runtime error:
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Numba 0.55.0 with 1.21.6 does not have the runtime error. 
Python 3.10.2
compiled against LLVM@11
Running in poetry shell on M1

**Comment by apmasell** [comment]
Hi. Can you provide me some more details on your environment?

MacOS seems to come with Python 3.9.7. How did you install Python 3.10.2?

Are you using poetry shell to install Numba and NumPy? How was LLVM installed?

**Comment by Zaba107** [comment]
Python 3.10.2 is installed via brew
Poetry to install Numba and NumPy.
LLVM was installed also with brew. 
LLVM_CONFIG=/opt/homebrew/opt/llvm@11/bin/llvm-config pip install llvmlite

**Comment by apmasell** [comment]
Hmm, I'm not able to reproduce this bug. Here is my `pyproject.toml`:
```
[tool.poetry]
name = "bug7995"
version = "0.1.0"
description = ""
authors = ["Andre Masella <andre@masella.name>"]

[tool.poetry.dependencies]
python = "3.10.2"
numpy="1.21.6"
numba="0.55.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I didn't install llvmlite directly though. Did you do that inside the Poetry environment or outside?

I suspect there is a copy outside the Poetry environment that is conflicting. Try running `python3 -m site` inside the Poetry environment to see where it is looking.

**Comment by Zaba107** [comment]
Are you running on M1 arm64? llvmlite won't install via poetry/pip. Could you share your llvmlite install version? Thanks

**Comment by apmasell** [comment]
Brew switched me onto a x86-64 Python for some reason. I forced it back to ARM64 and then had to compile llvmlite as you instructed, but I still do not receive any errors when using Numba.

Try running `python3 -m site` inside the Poetry environment to see where it is looking.

My environment looks like this:
```
sys.path = [
    '/Users/amasella/bug7995',
    '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python310.zip',
    '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10',
    '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload',
    '/Users/amasella/Library/Caches/pypoetry/virtualenvs/bug7995-IA9nZqke-py3.10/lib/python3.10/site-packages',
]
USER_BASE: '/Users/amasella/Library/Python/3.10' (exists)
USER_SITE: '/Users/amasella/Library/Python/3.10/lib/python/site-packages' (doesn't exist)
ENABLE_USER_SITE: False
```

**Comment by gmarkall** [comment]
Closing as the issue is now stale and no further information has been received. @Zaba107 If you are still experiencing an issue, please feel free to re-open this issue.
