### ISSUE TITLE
Indexing a tuple/list of function raises an error

### ISSUE THREAD

**Issue by duynguyenms2011** [numba/numba#7997]
I have been looking in the Numba issues, but I have not found an issue that is related to this bug. Basically, indexing a list of function in a python loop raises an error when compiling (I have included a .py file recreating this bug). This is a quick snippet of the code:
```
@jit(nopython=True)
def f1():
    return 1

@jit(nopython=True)
def f2():
    return 2

@jit(nopython=True)
def f3():
    return 3

@jit(nopython=True)
def f4():
    return 4

func_tuple = (f1, f2, f3, f4)
# this works:
@jit(nopython=True)
def do_stuff(func_tuple):
    results = []
    results.append(func_tuple[0]())
    results.append(func_tuple[1]())
    results.append(func_tuple[2]())
    results.append(func_tuple[3]())
    return results

# but this does not:
@jit(nopython=True)
def do_stuff_2(func_tuple):
    results = []
    for i in range(4):
        results.append(func_tuple[i]())
    return results
```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by duynguyenms2011** [comment]
[bug_numba.txt](https://github.com/numba/numba/files/8526017/bug_numba.txt)

**Comment by sklam** [comment]
This relates to the limited first-class function support. For your case, the tuple of function must be explicitly typed. See example in https://github.com/numba/numba/blob/main/numba/tests/test_function_type.py#L1221-L1257

**Comment by stuartarchibald** [comment]
`numba.literal_unroll` can also be used to version the loop body for each type in a heterogeneous tuple, docs: https://numba.readthedocs.io/en/stable/reference/pysupported.html#heterogeneous-tuples
