### ISSUE TITLE
Allow registering and using extra jit options in Numba

### ISSUE THREAD

**Issue by dlee992** [numba/numba#7998]
## Feature request
Hi, recently, I met a problem when coding SDC, but I think this is a general issue for Numba. Pandas have a flexible way to handle `series["A"]`:
```
import pandas as pd
s1 = pd.Series([1,2,3,4], index=list("ABCD"))
print(s1["A"])
1
s2 = pd.Series([1,2,3,4], index=list("AAAD"))
print(s2["A"])
A    1
A    2
A    3
dtype: int64
```
But when I implement this behavior on SDC, I cannot decide to return which type without runtime info. So I want to let users to tell compiler whether return series or not. 
Basically, I want to use extra options for type infer pass, since Numba doesn't allow one function with the same type inputs to return different types of outputs as above.

Can we open a "gate" to allow developers to register extra jit options in Numba? I still want to compile this function in CPU target. I don't want to override the whole Compiler class just for this simple purpose, as CUDACompiler class does.

```
class CUDAFlags(Flags):
    nvvm_options = Option(
        type=_nvvm_options_type,
        default=None,
        doc="NVVM options",
    )

@global_compiler_lock
def compile_cuda(pyfunc, return_type, args, debug=False, lineinfo=False,
                 inline=False, fastmath=False, nvvm_options=None):
    from .descriptor import cuda_target
    typingctx = cuda_target.typing_context
    targetctx = cuda_target.target_context

    flags = CUDAFlags()
```

If I misunderstand sth, please correct me. If I am right, I can help to extend Numba in this aspect.

**Comment by sklam** [comment]
For the usecase described here, I would imagine the need for a custom compiler pass.  Perhaps, compiler passes should be able to export compiler flags.

**Comment by dlee992** [comment]
@sklam , but Numba will throw an exception before any compiler pass goes on, since it will check options first before compiling.
```
        unused = set(options) - used
        if unused:
            # Unread options?
            m = (f"Unrecognized options: {unused}. "
                 f"Known options are {mappings.keys()}")
>           raise KeyError(m)
E           KeyError: ...
```
