### ISSUE TITLE
Use with construct to compile  one time use blocks of code

### ISSUE THREAD

**Issue by WiseroOrb** [numba/numba#8011]
In some projects I find the need to compile some "one time use" block of code, so i need to package it into a function and then call it.
I propose to use the `with`  statement to directly compile some block of code and execute it.

Example:

```python

...some code...

with jit(arguments):
    ...code to be compiled...

```

**Comment by apmasell** [comment]
Unfortunately, this isn't possible. `with` blocks aren't real entities in the output bytecode produced by the Python compiler and it does certain rearrangements of the code, so what you specified as "to be compiled" may be moved to the wrong side of the boundary.

Functions are the only entities Python treats as real entities Numba can work with. For this kind of code, the best option is to do some kind of:

```
...some code...

@numba.njit
def jitted_fun(p1, p2, ...):
    ...code to be compiled...
    return (mutated variables)

(v1, v2, ...) = jitted_fun(arguments)
```

**Comment by WiseroOrb** [comment]
Didn't know that. Thanks for the explanation.
