### ISSUE TITLE
"resize" attribute of numpy array

### ISSUE THREAD

**Issue by Rinoahu** [numba/numba#8015]
## Feature request
Dear Developer Team,

Could you please add the "resize" attribute to numpy arrays? When increasing the size of a numpy array, "resize" seems to be more memory-efficient than creating a new numpy array and deleting the old one.

Best,

R.H.

**Comment by czgdp1807** [comment]
Maybe I can try working on this? @guilhermeleobas @stuartarchibald

**Comment by czgdp1807** [comment]
I think both `np.resize` and `array.resize` are not present. Should we implement both? I can do that.

**Comment by Rinoahu** [comment]
np.resize seems a pure python function. ndarray.resize is different.

**Comment by czgdp1807** [comment]
Okay. I will prioritise `ndarray.resize` first then.

**Comment by stuartarchibald** [comment]
> Maybe I can try working on this? @guilhermeleobas @stuartarchibald

@czgdp1807 I don't recall there being/can't find any open PR doing the same, so if it's something you'd like to work on, then patches are welcomed, thanks!

Also, as noted, `np.resize` and `np.ndarray.resize` do different things. I think the request here is for the latter.

**Comment by czgdp1807** [comment]
Great. I am working on it. Will open a PR soon (a couple of days may be).

**Comment by czgdp1807** [comment]
@Rinoahu N.B. - https://github.com/numba/numba/pull/8020#issuecomment-1118771454

**Comment by mtsokol** [comment]
Hi @stuartarchibald! Would you consider reopening this issue? I'm willing to give it a try, and follow what you already described in https://github.com/numba/numba/pull/8020#issuecomment-1118771454 and https://github.com/numba/numba/pull/8020#issuecomment-1118791450.

In my case I'm looking for even more constrained version of `ndarray.resize` for nopython mode:
- Support only 1-D ndarrays, so the signature `Array(dtype, 1, 'A', False)` never changes,
- Allow only to increase the size of an array,
- I doesn't need to repeat existing array - for the first version it can be zero-initialized.

So, in a nutshell it's sort of "realloc" for 1-D arrays.
The `np.resize()` always creates a copy of the input array. Numba's `overload` for it uses `np.concatenate` which allocates a new array as well.

Do you have an intuition if that is feasible?
In Numba codebase I see `_empty_nd_impl` uses `intrin_alloc` which calls  `meminfo_alloc_aligned` for allocating the memory. As it calls `NRT_MemInfo_alloc_aligned` we could have `NRT_MemInfo_realloc_aligned` for resizing, assuming that:
- the array which is resized owns the memory.
- I'm not familiar how Numba handles NDArrays passed to to nopython function vs the ones allocated within it. Does Numba treat NDArrays passed as arguments as immutable?

Any comments will be helpful!
