### ISSUE TITLE
No error when getting out of bounds index

### ISSUE THREAD

**Issue by Anthony-C31** [numba/numba#8028]
Hello,
I'm not sure whether this is a real bug or an expected behavior.
Let's say I have an array of X elements, when I try to get an element outside of [0; X-1], I won't get any error when executing this with numba, whereas I get an error without numba.

The following code lines will help understand:

import numba as nb
import numpy as np

@nb.njit
def numba_fun():
    a = np.zeros(5, dtype=np.float64)
    b = a[10]
    return b

b = numba_fun()
print(b)

with numba it prints "2.7802862959848e-310"
without numba: "IndexError: index 10 is out of bounds for axis 0 with size 5"

Thank you for helping me understand if there is a way to correct this, or if I just have to live with this

**Comment by JacobHayes** [comment]
Does this happen with [`@nb.njit(boundscheck=False)`](https://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#jit-functions)?

**Comment by Anthony-C31** [comment]
I didn't know this option existed...
Problem solved :)
Thank you
