### ISSUE TITLE
np.random.randint with size

### ISSUE THREAD

**Issue by feluelle** [numba/numba#8039]
## Feature request

I would like to be able to use something like `np.random.randint(..., size=(..., ...))` to create a **matrix**.

**Comment by rishi-kulkarni** [comment]
This is possible on 0.56.0 dev per #7684 and probably before that - the docs are a bit misleading:

```
import numpy as np
import numba as nb

@nb.jit(nopython=True)
def nb_randint(low, high=None, size=None):
    return np.random.randint(low, high, size)

nb_randint(0, 10, size=(3, 3))
```
