### ISSUE TITLE
TypingError: Cannot unify ListType[int64] and list(int64)<iv=None> during using list comprehension

### ISSUE THREAD

**Issue by dlee992** [numba/numba#8048]
```
def test_misc6():

    @njit
    def foo(reflect_list):
        typed_list = typed.List.empty_list(types.int64)
        typed_list.append(1)

        for item1 in reflect_list:
            typed_list = [item1 if item1 == item2 else item2 for item2 in typed_list]

        return typed_list

    foo.py_func([1, 2])
    foo([1, 2])
```
TypingError is reported, and I think the line is incorrect. The real casue should come from the line `typed_list = [item1 if item1 == item2 else item2 for item2 in typed_list]`, rather than `for item1 in reflect_list:`.
```
E                   numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E                   Cannot unify ListType[int64] and list(int64)<iv=None> for 'typed_list.2', defined at /home/dali.da/code/asdc/sdc/tests/tests_ant/test_deque.py (737)
E                   
E                   File "test_deque.py", line 737:
E                       def foo(reflect_list):
E                           <source elided>
E                   
E                           for item1 in reflect_list:
E                           ^
E
```
If I change the loop body as below:
```
        for item1 in reflect_list:
            for index in range(len(typed_list)):
                if item1 == typed_list[index]:
                    typed_list[index] = item1
```
Typing is ok.

Maybe it's an unimplemented feature? or a bug related list comprehension.

**Comment by dlee992** [comment]
Oh, I guess `list comprehension` returns an instance of `list(int64)`, and numba cannot allow `list(int64)` convert/unify to `listtype(int64)`, which causes this `TypingError`.

**Comment by esc** [comment]
The problem here is that the list comprehension returns a reflected list. Thus when attempting to unify the types for that variable you end up with an error.

The following fixes this:

```
from numba import njit, typed, types


@njit
def foo(reflect_list):
    typed_list = typed.List.empty_list(types.int64)
    typed_list.append(1)

    for item1 in reflect_list:
        typed_list = typed.List([item1 if item1 == item2 else item2 for
                                    item2 in typed_list])

    return typed_list

foo.py_func([1, 2])
foo([1, 2])
```

**Comment by dlee992** [comment]
Thanks for ur quick response! In fact, it is also related with the loop. If we remove the loop like this: 
```
@njit
def foo(reflect_list):
    typed_list = typed.List.empty_list(types.int64)
    typed_list.append(1)

    item1 = -1
    typed_list = [item1 if item1 == item2 else item2 foritem2 in typed_list]

    return typed_list
```
This works.

BTW, could u spare some time to review my PR [#8029](https://github.com/numba/numba/pull/8029), thanks.

BTW again, I want to contribute a small PR about supporting using `str(bool_variable)`, since I used this in my own njit code. I think I can add some logic for boolean type in the method `integer_str` in `unicode.py`.

**Comment by esc** [comment]
> @esc, Thanks for ur quick response! In fact, it is also related with the loop. If we remove the loop like this:
> 
> ```
> @njit
> def foo(reflect_list):
>     typed_list = typed.List.empty_list(types.int64)
>     typed_list.append(1)
> 
>     item1 = -1
>     typed_list = [item1 if item1 == item2 else item2 foritem2 in typed_list]
> 
>     return typed_list
> ```
> 
> This works.

Indeed. The reason the loop breaks the code is due SSA (https://en.wikipedia.org/wiki/Static_single_assignment_form). You can imagine the loop to also act like a branch. In the sense that if the `reflected_list` is empty the loop will not execute and the `typed_list` will remain a `numba.typed.List`. Otherwise it will become a reflected list due to the list comprehension. This means, that the return type of the function `foo` is determined by the value of the argument `reflect_list` -- and so the compiler can't work out the signature of the function to compiler and hence will error out with a type unification error.

This is generally an issue, a more illustrative way to show this would be:

```
In [1]: from numba import njit

In [2]: @njit
   ...: def foo(val):
   ...:     if val:
   ...:         return [1]
   ...:     else:
   ...:         return 1
   ...:

In [3]: foo(True)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 foo(True)

File ~/git/numba/numba/core/dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File ~/git/numba/numba/core/dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Can't unify return type from the following types: Literal[int](1), list(int64)<iv=[1]>
Return of: IR name '$10return_value.2', type 'list(int64)<iv=[1]>', location:
File "<ipython-input-2-ba37f6e3cdce>", line 4:
def foo(val):
    <source elided>
    if val:
        return [1]
        ^
Return of: IR name '$14return_value.1', type 'Literal[int](1)', location:
File "<ipython-input-2-ba37f6e3cdce>", line 6:
def foo(val):
    <source elided>
    else:
        return 1
```

Hope that helps?

> BTW, could u spare some time to review my PR [#8029](https://github.com/numba/numba/pull/8029), thanks.

Not at this time no, but I can update the labels.

> BTW again, I want to contribute a small PR about supporting using `str(bool_variable)`, since I used this in my own njit code. I think I can add some logic for boolean type in the method `integer_str` in `unicode.py`.

Yes I saw, this is straightforward, thank you.

**Comment by esc** [comment]
@dlee992 I am not sure much can be done about this issue, do you think we can close it?

**Comment by dlee992** [comment]
Yes, I think unification of (reflect) list and typedlist cannot be implemented right now in Numba. Can close this.
