### ISSUE TITLE
Corrupted(?) return values from record arrays

### ISSUE THREAD

**Issue by pwuertz** [numba/numba#8051]
Returned values from record arrays seem to be corrupted:
```python
import numpy as np
import numba as nb

dt = np.dtype([("a", np.uint8), ("b", np.uint8)])

@nb.njit
def test():
    z = np.zeros(1, dtype=dt)
    return z[0]

print(test())
# prints: (222, 222)
```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).

**Comment by gmarkall** [comment]
@pwuertz Many thanks for the report - I think that this is a known issue, in that there is a refcount bug causing `z` to be deallocated and the memory underlying the return value being reused.

xrefs: 

- #7470
- #7469
- #6835
- https://github.com/numba/numba/issues/5853#issuecomment-893275330

**Comment by gmarkall** [comment]
Given that this is surprising and has received multiple reports, and isn't easily fixed, I think we should at least try to document this gotcha / bug - adding to 0.56RC to aim to update the docs for it.
