### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.misc'

### ISSUE THREAD

**Issue by zachyboy12** [numba/numba#8087]
Hi,
I was using numba, and an error appeared. It said,
ModuleNotFoundError: No module named 'numba.misc'
Please help!

**Comment by esc** [comment]
> Hi, I was using numba, and an error appeared. It said, ModuleNotFoundError: No module named 'numba.misc' Please help!

@zachyboy12 thank you for submitting this. This is most unusual and shouldn't be happening. My recommendation would be to re-install Numba, as the error may hint at a failed installation, or something having gone wrong with the existing installation. 

If that doesn't work, please say something about your environment, which operating system you are on, what architecture it has, how you installed Python, how you installed Numba and if there was anything you did before the error started to appear!

**Comment by zachyboy12** [comment]
@esc I tried reinstalling numba, but it did not work.
I am running on virtualenv, operating system on MacOs, (
forgot how I installed python), I tried installing using pip3 and git clone. pip3 gave me a module not found error, git clone gave me the same issue as described above.

**Comment by esc** [comment]
> @esc I tried reinstalling numba, but it did not work. I am running on virtualenv, operating system on MacOs, ( forgot how I installed python), I tried installing using pip3 and git clone. pip3 gave me a module not found error, git clone gave me the same issue as described above. I did not do anything before the error started to appear.

OK, has it ever worked for you, or is this a fresh installation? Also, what kind of Mac is it? Is it a new one with the M1 architecture? Can you copy and paste the exact `pip3` and `git clone` commands you used?

**Comment by zachyboy12** [comment]
This is a fresh installation. Big sur, to be excact. Here are the commands:
pip3 install numba
git clone https://github.com/numba/numba.git

**Comment by esc** [comment]
> This is a fresh installation. Big sur, to be exact. Here are the commands: pip3 install numba git clone https://github.com/numba/numba.git

OK, can you list what kind of processor this machine has? You can find this information by clicking on the Apple logo in the top right hand corner and then selecting "About this Mac".

**Comment by zachyboy12** [comment]
Here is the processer: 3.3 GHz 6-Core Intel Core i5

**Comment by esc** [comment]
> 3.3 GHz 6-Core Intel Core i5

OK, that is a x86_64 processor. I am not sure why you are seeing this error. This will be quite difficult to debug. Here are the next things to try:

a) Doing a `git clone https://github.com/numba/numba.git` will only download the source code for Numba but not compile it for you. I would recommend to delete the clone again. You can can do so by issuing a `cd` command to the directory in which you originally executed the `git clone` command and then using `rm -rv numba` to removed the cloned files.

b) After that, run the command `pip3 install numba` again and list the complete output including the command itself and any error messages received. That should  yield more hints as to what is going wrong in your case.

**Comment by zachyboy12** [comment]
Here:
Defaulting to user installation because normal site-packages is not writeable
Collecting numba
  Downloading numba-0.55.2-cp38-cp38-macosx_10_14_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 20.1 MB/s eta 0:00:00
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /Users/zachyboy/Library/Python/3.8/lib/python/site-packages (from numba) (0.38.1)
Requirement already satisfied: numpy<1.23,>=1.18 in /Users/zachyboy/Library/Python/3.8/lib/python/site-packages (from numba) (1.21.6)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from numba) (49.2.1)
Installing collected packages: numba
Successfully installed numba-0.55.2
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by esc** [comment]
> Here: Defaulting to user installation because normal site-packages is not writeable Collecting numba Downloading numba-0.55.2-cp38-cp38-macosx_10_14_x86_64.whl (2.3 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 20.1 MB/s eta 0:00:00 Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /Users/zachyboy/Library/Python/3.8/lib/python/site-packages (from numba) (0.38.1) Requirement already satisfied: numpy<1.23,>=1.18 in /Users/zachyboy/Library/Python/3.8/lib/python/site-packages (from numba) (1.21.6) Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from numba) (49.2.1) Installing collected packages: numba Successfully installed numba-0.55.2 WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available. You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

Thank you for posting this. Looks like the installation was fine. Now what happens when you type `python` and then `import numba`?

**Comment by zachyboy12** [comment]
My command: python3 import numba \
Result: \
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file 'import': [Errno 2] No such file or directory

**Comment by esc** [comment]
> My command: python3 import numba Result: /Library/Developer/CommandLineTools/usr/bin/python3: can't open file 'import': [Errno 2] No such file or directory

The correct command would be: `python -c "import numba"

**Comment by zachyboy12** [comment]
Thank you for your correction. \
It worked fine. But when I start coding in the file, it doesn't work.

**Comment by esc** [comment]
> When I start coding in the text editor, it gives a ModueNotFoundError.

OK; what is the name of the file and what is the contents?

**Comment by zachyboy12** [comment]
The name is __init__.py 
It is in a directory called rplus

The contents:

from random import randint as __randint
from time import time as __time, strftime as __strftime
from secrets import choice as __choice
import numba.numba

@numba.numba.jit()
def randomnumbergen1(path_to_rplus: str, low: int, high: int, more_random_but_slow=False, return_speed=False):
    start_time = __time()
    try:
        open(path_to_rplus + '/numcache.txt')
    except:
        open(path_to_rplus + '/numcache.txt', 'w').write('1')
    # Checking if user wants randomer numbers
    if more_random_but_slow is True:
        performance = 4000000  # The con of randomer numbers is that it is very slow
    elif more_random_but_slow is False:
        performance = 1000000
    cache = open(f'{path_to_rplus}/numcache.txt').read()  # Information of earlier calculated numbers
    rnums = []  # The random numbers to choose from
    for i in range(performance):  # Performance depends if more_random_but_slow is True or is False
        rnums.append(__randint(low, high))  # Appending semi-random numbers
    rnum = __choice(rnums)  # The random number
    if str(rnum) == cache:  # Checking if random number is equal to the previous random number
        if high - low == 1:
            pass
        else:
            rnum = __choice(rnums)  # Resetting rnum
    open(f'{path_to_rplus}/numcache.txt', 'w').write(str(rnum))  # Write rnum to numcache.txt
    end_time = __time()
    if return_speed is True:
        return end_time - start_time, rnum
    elif return_speed is False:
        return rnum
    
    
def randomnumbergen2(path_to_rplus: str, return_speed=False):
    start_time = __time()
    rnum = int(__strftime('%S')) + int(__strftime('%I'))
    end_time = __time()
    if return_speed is True:
        return end_time - start_time, rnum
    elif return_speed is False:
        return rnum
    
    
def randompassword(path_to_rplus: str, numberofletters=12, return_speed=False):
    start_time = __time()
    rpl = []
    p = ''
    for i in range(numberofletters + 1):
        lon = __choice(['l', 'n'])
        word = __choice(open('/usr/share/dict/words').read().splitlines())
        if lon == 'l':
            rpl.append(word[0])
        else:
            rpl.append(randomnumbergen1(path_to_rplus, 0, 9))
    for j in rpl:
        p += str(j)
    end_time = __time()
    if return_speed is True:
        return end_time - start_time, p
    elif return_speed is False:
        return p
    
    
def randomwordgen1(numberofletters: int, return_speed=False):
    start_time = __time()
    for word in open('/usr/share/dict/words').read().splitlines():
        if len(word) != numberofletters:
            continue
        else:
            break
    end_time = __time()
    if return_speed is False:
        return word
    elif return_speed is True:
        return end_time - start_time, word


def randomwordgen2(return_speed=False):
    start_time = __time()
    word = __choice(open('/usr/share/dict/words').read().splitlines())
    end_time = __time()
    if return_speed is True:
        return end_time - start_time, word
    elif return_speed is False:
        return word

**Comment by esc** [comment]
> The name is **init**.py It is in a directory called rplus
> 
> The contents: (Bad indent)
> 
> from random import randint as __randint from time import time as __time, strftime as __strftime from secrets import choice as __choice import numba.numba

I don't think that `import numba.numba` is supposed to work. I think you need to do `import numba` only.

**Comment by zachyboy12** [comment]
When I tried doing numba only, it raised an AttributeError

**Comment by zachyboy12** [comment]
Traceback (most recent call last):
  File "/Applications/griffin/asdf.py", line 2, in <module>
    @numba.jit()
AttributeError: module 'numba' has no attribute 'jit'

**Comment by esc** [comment]
> Traceback (most recent call last): File "/Applications/griffin/asdf.py", line 2, in @numba.jit() AttributeError: module 'numba' has no attribute 'jit'

This is all very bizzare. At this point I am not convinced this is a bug in Numba but that there are some kind of installation issues in your case. The Numba issue tracker is meant to track issues/bugs that affect Numba. I am going to close this issue now and kindly recommend to open a new thread on https://numba.discourse.group/ -- with as much information about the issues your encounter. Thank you!
