### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by songololo** [numba/numba#8112]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.

This seems to be an environment path resolution issue so it is not possible to provide an example that will reproduce the issue on other systems.

Background:

Trying to setup `Numba` on an M1 Mac:
- `llvmlite` successfully installed.
- `numpy` v1.21.6 installed in working environment.
- `brew` has it's own numpy v1.22 installed.

When trying to run `numba` from python, various modules end up trying to import `_helperlib`, which triggers the following error:

```python
import numba  # triggers error
from numba import _helperlib  # source of error
```

```bash
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/Users/gareth/dev/cityseer-api/__pypackages__/3.9/lib/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import
```

I'm wondering if the issue is probably because `_helperlib` might be finding the wrong version of `numpy`, i.e. is somehow missing the version in the local environment / or on the local `PYTHONPATH` and finding the version installed by `brew` instead?

**Comment by songololo** [comment]
PS - I've uninstalled v1.22 from brew and the problem still occurs. So I'm not sure how to further debug this.

**Comment by pzsette** [comment]
I'm facing the same problem

**Comment by songololo** [comment]
Closing because this appears to be a duplicate.

Solved issue by installing via:
```bash
pip3 install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple numba
```

See related issues, e.g.
- https://github.com/numba/llvmlite/issues/799

**Comment by esc** [comment]
@songololo "official" M1 wheels are coming to PyPi very soon, see: https://github.com/numba/numba/issues/8066

**Comment by Pel1974** [comment]
I solved it by using:

pip uninstall numba
conda install numba
