### ISSUE TITLE
No out of bounds check during advanced array indexing

### ISSUE THREAD

**Issue by kc611** [numba/numba#8127]
Numba ignores any indices that are out of bounds for a given array shape. This behavior is present in both basic and advanced indexing. 

```python 
import numpy as np
import numba

@numba.njit
def something():
    arr = np.ones((3,3))
    arr[100] = 0
    arr[:, np.array([2,3,5,100])] = 0
    return arr

print(something()) # Does not raise error, ignores the out of bound indices completely.
print(something.py_func()) # Raises out of bounds error
```

Not sure if we should be considering this as a bug or a feature :-) 

Should be easily fixed by adding a bounds check during indexing during function runtime.

**Comment by esc** [comment]
@kc611 thank you for reporting this. IIRC there is a keyword argument that can be passed to the `njit` decorator:

https://numba.readthedocs.io/en/stable/reference/pysemantics.html?highlight=boundscheck#bounds-checking

Is this perhaps what you are looking for?

**Comment by kc611** [comment]
Thank you that was exactly what I was looking for.

**Comment by kc611** [comment]
Marking this as a good first issue for any newcomer.
