### ISSUE TITLE
Numerical differences in latest numba with NumPy 1.21 vs 1.22

### ISSUE THREAD

**Issue by astrojuanlu** [numba/numba#8141]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I observe numerical differences with latest numba when using NumPy 1.21 vs 1.22:

```python
# Adapted from https://github.com/poliastro/poliastro/blob/8ac93be/tests/test_stumpff.py
from math import gamma

import numpy as np
from numpy.testing import assert_equal
from numba import njit


@njit
def stumpff_c2(psi):
    r"""Second Stumpff function.

    For positive arguments:

    .. math::

        c_2(\psi) = \frac{1 - \cos{\sqrt{\psi}}}{\psi}

    """
    eps = 1.0
    if psi > eps:
        res = (1 - np.cos(np.sqrt(psi))) / psi
    elif psi < -eps:
        res = (np.cosh(np.sqrt(-psi)) - 1) / (-psi)
    else:
        res = 1.0 / 2.0
        delta = (-psi) / gamma(2 + 2 + 1)
        k = 1
        while res + delta != res:
            res = res + delta
            k += 1
            delta = (-psi) ** k / gamma(2 * k + 2 + 1)

    return res


if __name__ == "__main__":
    psi = -3.0
    expected_c2 = (np.cosh((-psi) ** 0.5) - 1) / (-psi)

    assert_equal(stumpff_c2(psi), expected_c2)

```

With these dependencies, the assertion passes silently:

```
$ cat good_requirements.txt 
numba==0.55.2
numpy==1.21.6
```

But with these, the test fails:

```
$ cat bad_requirements.txt 
numba==0.55.2
numpy==1.22.4
$ python test_numba.py 
Traceback (most recent call last):
  File "/tmp/numba-weird/test_numba.py", line 40, in <module>
    assert_equal(stumpff_c2(psi), expected_c2)
  File "/tmp/numba-weird/.venv310/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 425, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0.6381924800586426
 DESIRED: 0.6381924800586427
```

Tested with Python 3.8 and 3.10. The numerical failure happens with all micro versions of NumPy 1.22 (1.22.0 to 1.22.4).

I _know_ it's generally unreasonable to test floating point equality 😓 but I'm reporting this because this particular test has been working fine for a few years until now, just in case it's worth looking into it.

**Comment by gmarkall** [comment]
Could this change in NumPy 1.22 be the reason? https://github.com/numpy/numpy/pull/19478

**Comment by stuartarchibald** [comment]
Thanks for the report @astrojuanlu. I suspect what @gmarkall suggests is potentially the cause. Would you happen to be running this on an x86_64 skylake or later chip (if you run `numba -s` the `__Hardware Information__` section has a `CPU Name` in it)? The reason I'm asking is that NumPy 1.22 now dispatches to lower precision SVML functions for various `libm` ufunc loops and Numba test suite also caught this, the workaround I put in is here:
https://github.com/numba/numba/blob/65cbe1cab01cc186ce873a65d94b5096acbf07f3/buildscripts/incremental/test.sh#L29-L41
if this describes your situation then setting the environment variable to disable it via `export NPY_DISABLE_CPU_FEATURES="AVX512_SKX" ` may "fix" the problem.

**Comment by astrojuanlu** [comment]
Thanks for the blazing fast response folks! Indeed, I'm on `tigerlake` architecture as per `numba -s`, and I confirm that this is the culprit:

```
(.venv) juanlu at valinor in /tmp/numba-weird
$ python test_numba.py 
Traceback (most recent call last):
  File "test_numba.py", line 40, in <module>
    assert_equal(stumpff_c2(psi), expected_c2)
  File "/tmp/numba-weird/.venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 425, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0.6381924800586426
 DESIRED: 0.6381924800586427
(.venv) juanlu at valinor in /tmp/numba-weird
$ NPY_DISABLE_CPU_FEATURES="AVX512_SKX" python test_numba.py
$ 
```

I guess that we'll have to adapt our CI as well. Feel free to close this issue if there is no alternative.

**Comment by stuartarchibald** [comment]
@astrojuanlu no problem, thanks for confirming. This is the bit of code Numba's using to detect the issue/what NumPy is aware of:
https://github.com/numba/numba/blob/65cbe1cab01cc186ce873a65d94b5096acbf07f3/numba/misc/numba_sysinfo.py#L387-L402
the `_numpy_AVX512_SKX_detected` key in the `sys_info` dictionary essentially maps to the "NumPy is probably using the lower precision SVML ufunc loops, need to disable dispatch to that" situation (if NumPy version>=1.22).
