### ISSUE TITLE
numba.pydata.org landing page needs an update

### ISSUE THREAD

**Issue by esc** [numba/numba#8159]
The landing page at: https://numba.pydata.org/ needs an update. For example it claims that ROCm is still supported which it isn't.

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment]
> See [numba/numba.github.com#5](https://github.com/numba/numba.github.com/pull/5) and [numba/numba.github.com#6](https://github.com/numba/numba.github.com/pull/6)

Thank you, merged!

**Comment by esc** [comment]
Other things to consider:

* update the supported Python versions (or not mention any at all)
* convert the examples to use `njit` over `jit(nopython=True)`
* update copyright
* mention explicitly that we also support the M1

**Comment by esc** [comment]
@gmarkall can you review: https://github.com/numba/numba.github.com/pull/7 -- I've added some more updates.

**Comment by esc** [comment]
@stuartarchibald : @gmarkall and I have updated the website landing page. IT's now up-to-date as of 2022.

https://numba.pydata.org/

**Comment by stuartarchibald** [comment]
Thanks @esc and @gmarkall, much appreciated.
