### ISSUE TITLE
numba parallel on mac, not working

### ISSUE THREAD

**Issue by RunxingZhong** [numba/numba#8166]
```
import numba
print(numba.__version__)
numba.set_num_threads(4)
numba.config.NUMBA_NUM_THREADS = 4
import time

@numba.njit(parallel=True)
def f(n):
    s = 0
    for i in numba.prange(n):
        for j in range(n):
            for k in range(n):
                s += (i * k < j * j) - (i * k > j * j)
    return s


t1 = time.time()
f(5000)
t2 = time.time()
print(t2-t1)
```
<img width="688" alt="image" src="https://user-images.githubusercontent.com/13879734/173883215-93daa2d4-6aa4-4c02-9163-38db1f93375f.png">

my test code as above. numba==0.55.0
I have run on my mac, and linux
1) on mac, only use 1 cpu = 100%
2) on linux, can use 400%

how to use multi cpus on mac?
thanks!

**Comment by guilhermeleobas** [comment]
Hi @RunxingZhong, thanks for the report. I just tried the code above, and I can see on htop numba using all four cores in a Mac.

Can you post the output of [`numba -s`](https://numba.pydata.org/numba-doc/dev/user/cli.html#system-information) command?

**Comment by guilhermeleobas** [comment]
try `python -m numba -s`

**Comment by RunxingZhong** [comment]
> try `python -m numba -s`

hi, sorry reply late.
after I uninstall and 
conda install 
everything work!

thanks
