### ISSUE TITLE
Feature Request: add ability to run -03 twice

### ISSUE THREAD

**Issue by max9111** [numba/numba#8172]
This bug first occurs in version 0.54 (0.49-0.53 are OK). This results in a performance decrease of a factor of 4 in a bit optimized summation and a factor of 2 in a naive implementation.

**Example**

```python
import numpy as np
import numba as nb
import time


f = np.random.rand(32,33,2000,64)
b = np.random.rand(32,64)

@nb.njit(fastmath=True)
def test_numba_1(f,b):
    fnew = np.zeros((f.shape[1],f.shape[2]))
    
    for i in range(f.shape[0]):
        for j in range(f.shape[1]):
            for k in range(f.shape[2]):
                for l in range(f.shape[3]):
                    fnew[j,k] += f[i,j,k,l] * b[i,l]
    return fnew

@nb.njit(fastmath=True)
def test_numba_2(f,b):
    fnew = np.zeros((f.shape[1],f.shape[2])) 
    
    for i in range(f.shape[0]):
        for j in range(f.shape[1]):
            for k in range(f.shape[2]):
                acc=fnew[j,k]
                for l in range(f.shape[3]):
                    acc += f[i,j,k,l] * b[i,l]
                fnew[j,k]=acc
    return fnew

%timeit test_numba_1(f,b)
%timeit test_numba_2(f,b)

#'0.53.1' Last version without bug
#108 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
#53.9 ms ± 809 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

#'0.54.0' First version with bug
#216 ms ± 4.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
#200 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

#'0.55.0'
#218 ms ± 5.36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
#201 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Another question would be if, a rewrite pass is possible in Numba to optimize `test_numba_1` automatically to `test_numba_2`. Clang shows exactly the same behavior as Numba before version 0.54, therefore this likely has to be fixed before generating LLVM-IR.

```c
//clang v11
//clang -shared -O3 -march=native -ffast-math -o summation.dll summation.c
__declspec(dllexport) void eq_nb_1(size_t s0,size_t s1,size_t s2,size_t s3,double f[][s1][s2][s3],double b[][s3],double fnew[][s2])
{
  for (size_t i=0;i<s0;i++){
    for (size_t j=0;j<s1;j++){
      for (size_t k=0;k<s2;k++){
         for (size_t l=0;l<s3;l++){
           fnew[j][k]+=f[i][j][k][l]*b[i][l];
         }
      }
    }
  }
}

__declspec(dllexport) void eq_nb_2(size_t s0,size_t s1,size_t s2,size_t s3,double f[][s1][s2][s3],double b[][s3],double fnew[][s2])
{
  for (size_t i=0;i<s0;i++){
    for (size_t j=0;j<s1;j++){
      for (size_t k=0;k<s2;k++){
         double acc=fnew[j][k];
         for (size_t l=0;l<s3;l++){
           acc+=f[i][j][k][l]*b[i][l];
         }
         fnew[j][k]=acc;
      }
    }
  }
}
```
```python
import numpy as np
import ctypes

lib = ctypes.cdll.LoadLibrary("summation.dll")

def eq_nb_1(f,b):
    fnew = np.zeros((f.shape[1],f.shape[2]))
    s_0=ctypes.c_size_t(f.shape[0])
    s_1=ctypes.c_size_t(f.shape[1])
    s_2=ctypes.c_size_t(f.shape[2])
    s_3=ctypes.c_size_t(f.shape[3])
    
    f_p   =f.ctypes
    b_p   =b.ctypes
    fnew_p=fnew.ctypes
    
    lib.eq_nb_1(s_0,s_1,s_2,s_3,f_p,b_p,fnew_p)
    return fnew

def eq_nb_2(f,b):
    fnew = np.zeros((f.shape[1],f.shape[2]))
    s_0=ctypes.c_size_t(f.shape[0])
    s_1=ctypes.c_size_t(f.shape[1])
    s_2=ctypes.c_size_t(f.shape[2])
    s_3=ctypes.c_size_t(f.shape[3])
    
    f_p   =f.ctypes
    b_p   =b.ctypes
    fnew_p=fnew.ctypes
    
    lib.eq_nb_2(s_0,s_1,s_2,s_3,f_p,b_p,fnew_p)
    return fnew

%timeit eq_nb_1(f,b)
%timeit eq_nb_2(f,b)
#100 ms ± 311 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
#50.5 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by guilhermeleobas** [comment]
Hi @max9111, thanks for the report. I can confirm there's a performance regression when moving from Numba 0.53 to newer versions. I'll mark this for discussion at the next triage meeting, which will happen next Tuesday.

**Comment by stuartarchibald** [comment]
IIRC 0.54 was the first version using LLVM 11 and there were some things to do with missed vectorization that Numba encountered when the upgrade was undertaken (which were fixed, but I guess this one was missed).

This diff recovers the 0.53 performance, but at the cost of increased compilation effort:
```diff
diff --git a/numba/core/codegen.py b/numba/core/codegen.py
--- a/numba/core/codegen.py
+++ b/numba/core/codegen.py
@@ -1189,7 +1189,7 @@ class CPUCodegen(Codegen):
         self._data_layout = str(self._target_data)
         self._mpm_cheap = self._module_pass_manager(loop_vectorize=False,
                                                     slp_vectorize=False,
-                                                    opt=0,
+                                                    opt=2,
                                                     cost="cheap")
         self._mpm_full = self._module_pass_manager()

```
which suggests it's still possible to do the expected optimisation and it's just a question of working out precisely what combination of passes that is!

**Comment by lesshaste** [comment]
What appears to be the same performance bug has just been reported to https://stackoverflow.com/questions/75833328/why-do-these-two-different-ways-to-sum-a-2d-array-have-such-different-performanc . It's the fix planned for the next release?

**Comment by stuartarchibald** [comment]
This issue was raised at the Numba public meeting on 2023-03-28. The outcome is that the 0.58 release series will have support for an environment variable that if set will reinstate the previous behaviour (effectively running `-O3` twice).

**Comment by esc** [comment]
I have updated the title of this Issue to reflect it's change in state. It is now a feature request scheduled for inclusion in Numba 0.58.

The feature request is: as a Numba user I want to be able to set the environment variable `NUMBA_RUN_O3_TWICE` which will effectively "run -O3 twice" and run the code path from the patch at: https://github.com/numba/numba/issues/8172#issuecomment-1160474583

**Comment by max9111** [comment]
I have a general question:

**Why is that the new default?**

A real-world function without a severe performance drop (factor 1,5-5x) is hard to find. The improvement of compilation time is usually neglectable, it's often a few percent, with caching it doesn’t matter at all.
What is the reason for this? It absolutely makes no sense at all. Compilation times can be high in heavily NumPy - vectorized codes. If Numba is able to compile that at all (quite some features missing, but anyway extremely complicate to optimize this code) the perfomance benefit is quite often neglectable (no real usecase). Usually there is some simple (or maybe not as simple but doable)  rewrite necessary to get a good result in this case.
All this without reimplementation in (C/Fortran)+Wrapper+Dependencies, which is a different story in terms of effort. That's the beauty of Numba.

I really don't get the point to make this bug or “feature” as a default. To my opinion it is one of the most significant bugs in the last years.

**Comment by max9111** [comment]
> The patch from [#8172 (comment)](https://github.com/numba/numba/issues/8172#issuecomment-1160474583) slows down the fast variant in the reproducer from #9038. Without the patch, `dist_cityblock_2()` runs in:
> 
> ```
> 2.34 µs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
> ```
> 
> With the patch, it runs in:
> 
> ```
> 4.05 µs ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
> ```
> 
> so applying the patch above does not look like it would universally improve performance. I can see why a user would want the option to use `opt=2` at their discretion though.

Numba 0.57 seems to change the behavoir, on 0.56 I can't reproduce this behaviour:

    %timeit dist_cityblock_1(x, y)
    #0.56, windows installed via pip (default)
    #3.82 µs ± 1.45 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
    #0.56, windows installed via pip (opt=2)
    #2.02 µs ± 24.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

    #0.57, windows installed via pip (default)
    #3.76 µs ± 0.962 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
    #0.57, windows installed via pip (opt=2)
    #4.13 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
    
    %timeit dist_cityblock_2(x, y)
    #0.56, windows installed via pip (default)
    #6.56 µs ± 4.09 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
    #0.56, windows installed via pip (opt=2)
    #2.02 µs ± 24.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

    #0.57, windows installed via pip (default)
    #2.09 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
    #0.57, windows installed via pip (opt=2)
    #5.61 µs ± 2.13 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

The issue with the initial question seems to be fixed with 0.57, but opt=2 seems to be slower than the default now:

    %timeit test_numba_1(f,b)
    #0.56, windows installed via pip (default)
    #123 ms ± 290 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
    #0.56, windows installed via pip (opt=2)
    #78.1 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

    #0.57, windows installed via pip (default)
    #77.3 ms ± 499 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
    #0.57, windows installed via pip (opt=2)
    #77.6 ms ± 491 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

    %timeit test_numba_2(f,b)
    #0.56, windows installed via pip (default)
    #120 ms ± 914 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
    #0.56, windows installed via pip (opt=2)
    #36.2 ms ± 556 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


    #0.57, windows installed via pip (default)
    #38 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    #0.57, windows installed via pip (opt=2)
    #71 ms ± 341 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

On other [examples](https://stackoverflow.com/a/76583728/4045774), there seems to be still a bit slower timings with 0.57 (default) to previous versions with (opt=2).

**Comment by lesshaste** [comment]
It does look like 0.57.0 has sped up the problematic code at https://stackoverflow.com/questions/75833328/why-do-these-two-different-ways-to-sum-a-2d-array-have-such-different-performanc as well.  %timeit sum_array_slow(a) is now the same speed as %timeit sum_array_fast(a) more or less.  I had been expecting to have to wait for this 0.58 to see this speed up.

**Comment by gmarkall** [comment]
> Numba 0.57 seems to change the behavoir

Numba 0.57 went from LLVM 11 to 14, so that might explain a lot of changes - unfortunately it does make it hard to directly compare the two.
