### ISSUE TITLE
Code breaks down without throwing any error

### ISSUE THREAD

**Issue by Badr-MOUFAD** [numba/numba#8194]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

## Minimal script to reproduce and logs

Running the code below will neither continue to execute nor throw an error.

**script**

```python
import numpy as np
from numba import float64
from numba.experimental import jitclass

@jitclass([('Xty', float64[:])])
class Quadratic:
    def __init__(self):
        pass

    def gradient_scalar(self, X, Xw, j):
        return (X[:, j] @ Xw - self.Xty[j]) / len(Xw)

X = np.ones((2, 5))
Xw = np.zeros(2)

Quadratic().gradient_scalar(X, Xw, 0)

print("This line will never be printed")
```

**logs**

```shell
<string>:3: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
<string>:3: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
```

## Expected behavior

A normal behavior of the code would be to raise an ``AttributeError``, which I get when I remove ``jitclass`` decorator.

--------------------

**P.S:** This issue is related to https://github.com/scikit-learn-contrib/skglm/issues/35

**Comment by PABannier** [comment]
I can reproduce the bug with a segmentation fault on my machine.
This behavior is expected since the compiled code is accessing a non-existing element in memory (`self.Xty`).
A simple fix would consist in calling `hasattr` on `self`, but Numba does not recognize built-in Python functions like `hasattr`.

**Comment by gmarkall** [comment]
@PABannier Thanks for identifying the issue!

One thing worth trying in general when Numba-compiled code segfaults is to run without the JIT and check for any Python examples. This can be done by setting the environment variable `NUMBA_DISABLE_JIT` to `1`. For example with this issue I get:

```
$ NUMBA_DISABLE_JIT=1 python repro.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/8194/repro.py", line 16, in <module>
    Quadratic().gradient_scalar(X, Xw, 0)
  File "/home/gmarkall/numbadev/issues/8194/repro.py", line 11, in gradient_scalar
    return (X[:, j] @ Xw - self.Xty[j]) / len(Xw)
AttributeError: 'Quadratic' object has no attribute 'Xty'
```

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Thanks!
