### ISSUE TITLE
Support compiled functions as arguments in nopython mode

### ISSUE THREAD

**Issue by seibert** [numba/numba#821]
We would like to be able to support Numba-compiled implementations of algorithms (like solvers) that can call user-supplied JIT functions (or ctypes/cffi wrappped functions) without any Python overhead.

The primary use case is for automatic jitting, although we will need a syntax to specify an argument function type explicitly in type signature.

**Comment by stuartarchibald** [comment]
@seibert is this sufficiently covered by `@cfunc`, `ctypes/cffi` support and now passing compiled functions as args/in containers to close this? Or do you want to keep it open for the notion of automatic-inlining/recompilation?
