### ISSUE TITLE
Repository still tagged rocm

### ISSUE THREAD

**Issue by annanyearian** [numba/numba#8224]
From what I understand rocm is no longer supported but repository is still tagged with it. 

![image](https://user-images.githubusercontent.com/80974897/177355351-5dc167a0-d373-4462-a4dd-c6554559aeb6.png)

Also the ROCM docs still mentions this as an available library. Anyone know how to get in contact with whoever maintains that documentation? Would be nice to let them know an update is needed: https://rocmdocs.amd.com/en/latest/Programming_Guides/LanguageInto.html

**Comment by esc** [comment]
@annanyearian thank you for reporting this. I have removed the tag. As for the ROCm docs, the newer docs for ROCm (version 5.0 and beyond) are here:

https://docs.amd.com/

And they don't seem to mention Numba anymore, so I think we are fine for now.
