### ISSUE TITLE
vectorize docstring example has incorrect identity

### ISSUE THREAD

**Issue by bmcfee** [numba/numba#8227]
## Reporting a bug

This is a documentation bug more than a functionality bug, so reproducibility does not exactly apply.

The docstring example in `vectorize` provides a ufunc of `sum` that has `identity=1`.  I believe this should be `0` (additive identity):

https://github.com/numba/numba/blob/15e48788660f5c387d8d1160cc4be5d2363510fc/numba/np/ufunc/decorators.py#L100-L103

The later example for `mul` correctly sets `identity=1`.

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] ~I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.~ N/A

**Comment by esc** [comment]
@bmcfee thank you for bringing this to our attention. This seems correct as the identity for addition is indeed `0`.
