### ISSUE TITLE
Using vectorize with nopython argument raises error when used without decorator syntax

### ISSUE THREAD

**Issue by timothymillar** [numba/numba#8231]
## Reporting a bug

When calling `vectorize` **without** decorator syntax any use of the `nopython` argument results in a type error due to `unexpected keyword argument 'nopython'`.

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Minimal example:
```python
from numba import vectorize

# this works
@vectorize(nopython=True)
def foo(x):
    return x + 1

# this doesn't
def bar(x):
    return x + 1
vectorize(bar, nopython=True)
```

Traceback:
```
TypeError                                 Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 vectorize(bar, nopython=True)

File ~/miniconda3/envs/numba/lib/python3.9/site-packages/numba/np/ufunc/decorators.py:118, in vectorize(ftylist_or_function, **kws)
    116     ftylist = [ftylist_or_function]
    117 elif inspect.isfunction(ftylist_or_function):
--> 118     return dufunc.DUFunc(ftylist_or_function, **kws)
    119 elif ftylist_or_function is not None:
    120     ftylist = ftylist_or_function

TypeError: __init__() got an unexpected keyword argument 'nopython'
```

This doesn't seem to be an issue with the `jit` or `guvectorize` decorators and it's not an issue when using the `cache` argument for `vectorize`

**Comment by esc** [comment]
FWIW: here is an example that attempts to execute the resulting ufunc:

```
import numpy as np
from numba import vectorize


# this works
@vectorize(nopython=True)
def foo(x):
    return x + 1


# this doesn't
def bar(x):
    return x + 1


bar = vectorize(bar, nopython=True)

a = np.ones(42)

print(foo(a))
print(bar(a))
```

Using the following patch:

```
diff --git i/numba/np/ufunc/decorators.py w/numba/np/ufunc/decorators.py
index 57776a466d..9fffd9f9d2 100644
--- i/numba/np/ufunc/decorators.py
+++ w/numba/np/ufunc/decorators.py
@@ -115,7 +115,8 @@ def vectorize(ftylist_or_function=(), **kws):
         # Common user mistake
         ftylist = [ftylist_or_function]
     elif inspect.isfunction(ftylist_or_function):
-        return dufunc.DUFunc(ftylist_or_function, **kws)
+        vec = Vectorize(ftylist_or_function, **kws)
+        return vec.build_ufunc()
     elif ftylist_or_function is not None:
         ftylist = ftylist_or_function
```

I can get the code to run and both `print` statements yield the same output, which is a good indication. 

@stuartarchibald @sklam does this look like an appropriate fix? If yes, I can stage a PR with an accompanying test.

**Comment by esc** [comment]
@timothymillar we discussed this in our weekly meeting today and it seems like the semantics of the `vectorize` decorator are different from the `@njit` decorator.

Doing the following instead will yield the result you are expecting:

```python
import numpy as np
from numba import vectorize


# this works
@vectorize(nopython=True)
def foo(x):
    return x + 1


# this doesn't
def bar(x):
    return x + 1


bar = vectorize(nopython=True)(bar)

a = np.ones(42)

print(foo(a))
print(bar(a))
```

**Comment by timothymillar** [comment]
Great, thanks @esc!
