### ISSUE TITLE
global name 'range_iter_len' is not defined when using Numba for Image Manipulation

### ISSUE THREAD

**Issue by rareguy** [numba/numba#8237]
I was working with massive image manipulation using OpenCV2 and have the idea to use GPU instead of CPU to speed up the computation. I'm using [Pointillism][1] to manipulate the image and it involves quite some math and library (OpenCV, NumPy, sklearn), it took significant time to finish processing each image. Here's the code:
```
@jit
def toPointillismPainting(img):
	stroke_scale = int(math.ceil(max(img.shape) / 250))
	#print("Automatically chosen stroke scale: %d" % stroke_scale)
	
	gradient_smoothing_radius = int(round(max(img.shape) / 50))
	#print("Automatically chosen gradient smoothing radius: %d" % gradient_smoothing_radius)

	# convert the image to grayscale to compute the gradient
	gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

	#print("Computing color palette...")
	palette = ColorPalette.from_image(img, 20)

	#print("Extending color palette...")
	palette = palette.extend([(0, 50, 0), (15, 30, 0), (-15, 30, 0)])

	#print("Computing gradient...")
	gradient = VectorField.from_gradient(gray)

	#print("Smoothing gradient...")
	gradient.smooth(gradient_smoothing_radius)

	#print("Drawing image...")
	# create a "cartonized" version of the image to use as a base for the painting
	res = cv2.medianBlur(img, 11)
	# define a randomized grid of locations for the brush strokes
	grid = randomized_grid(img.shape[0], img.shape[1], scale=3)
	batch_size = 10000

	#bar = progressbar.ProgressBar()
	for h in range(0, len(grid), batch_size):
		# get the pixel colors at each point of the grid
		pixels = np.array([img[x[0], x[1]] for x in grid[h:min(h + batch_size, len(grid))]])
		# precompute the probabilities for each color in the palette
		# lower values of k means more randomnes
		color_probabilities = compute_color_probabilities(pixels, palette, k=9)

		for i, (y, x) in enumerate(grid[h:min(h + batch_size, len(grid))]):
			color = color_select(color_probabilities[i], palette)
			angle = math.degrees(gradient.direction(y, x)) + 90
			length = int(round(stroke_scale + stroke_scale * math.sqrt(gradient.magnitude(y, x))))

			# draw the brush stroke
			cv2.ellipse(res, (x, y), (length, stroke_scale), angle, 0, 360, color, -1, cv2.LINE_AA)

	return res
```
This returned me an error which usually didn't happen when I'm not using `@jit` decorator.
```
global name 'range_iter_len' is not defined
Traceback (most recent call last):
  File "[projectname]", line 201, in <module>
    res = toPointillismPainting(img)
NameError: global name 'range_iter_len' is not defined
removed temporary images
```

When debugging, I realized that this `range_iter_len` variable is nowhere used in my project nor the Pointillism code itself. And I only found [a single github][2] issue on Numba and it doesn't seem to have similar root cause. Any help would be appreciated.

  [1]: https://github.com/matteo-ronchetti/Pointillism
  [2]: https://github.com/numba/numba/issues/3659

**Comment by esc** [comment]
> I was working with massive image manipulation using OpenCV2 and have the idea to use GPU instead of CPU to speed up the computation. I'm using [Pointillism](https://github.com/matteo-ronchetti/Pointillism) to manipulate the image and it involves quite some math and library (OpenCV, NumPy, sklearn), it took significant time to finish processing each image. 
..
> When debugging, I realized that this `range_iter_len` variable is nowhere used in my project nor the Pointillism code itself. And I only found [a single github](https://github.com/numba/numba/issues/3659) issue on Numba and it doesn't seem to have similar root cause. Any help would be appreciated.

@rareguy thank you for asking about this. Numba only supports some Python syntax and NumPy, additional libraries auch as sklearn or opencv are not supported for compilation. You can to use `@njit` (which is short for nopython-jit):

https://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode

And see what kind of error messages you get.

If you would like us to debug this further, please do submit a minimal working reproducer:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Thank you for using Numba!
