### ISSUE TITLE
Dependency conflict with `numpy` 1.23 

### ISSUE THREAD

**Issue by kerstin921** [numba/numba#8242]
I'm getting a dependency conflict reported by `pipdeptree`:

`numba 0.55.2 requires numpy<1.23,>=1.18, but you have numpy 1.23.1 which is incompatible.`

Confirmed by `pip` doing `python -m pip install --upgrade numpy`:

```
Collecting numpy
  Using cached numpy-1.23.1-cp38-cp38-win_amd64.whl (14.7 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed.
 This behaviour is the source of the following dependency conflicts.
numba 0.55.2 requires numpy<1.23,>=1.18, but you have numpy 1.23.1 which is incompatible.
Successfully installed numpy-1.23.1
```

I have the latest versions of both `numba` and `numpy` installed on a Windows 7 machine.

**Comment by sklam** [comment]
Neither Numba 0.55.2 and the current RC 0.56.0rc1 support NumPy 1.23. NumPy 1.23 support is planned for the next release (0.57).

**Comment by kerstin921** [comment]
Ok, any idea when 0.57 will be released?

**Comment by sklam** [comment]
Just talked with the team, 0.57 will probably be in Jan 2023. We should make a Numba 0.56.1 release for NumPy 1.23. We are still waiting for the conda package builds for NumPy 1.23. A early testing patch for NumPy 1.23 is at https://github.com/numba/numba/pull/8206.

**Comment by sklam** [comment]
superseded by https://github.com/numba/numba/issues/8263

**Comment by kerstin921** [comment]
Okay, thanks!!

**Comment by kerstin921** [comment]
Ah, so where can I look up if `numba` 0.56.1 is "online" (i.e. will be automatically installed via `pip install numba`)? Sorry for dumb question, I'm just relatively new to Github

**Comment by kerstin921** [comment]
...this would be my `python -m pip index versions numba` output:

```
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
numba (0.55.2)
Available versions: 0.55.2, 0.55.1, 0.55.0, 0.54.1, 0.54.0, 0.53.1, 0.53.0, 0.52.0, 0.51.2, 0.51.1, 0.51.0, 0.50.1, 0.50.0, 0.49
.1, 0.49.0, 0.48.0, 0.47.0, 0.46.0, 0.45.1, 0.45.0, 0.44.1, 0.44.0, 0.43.1, 0.43.0, 0.42.1, 0.42.0, 0.41.0, 0.40.1, 0.40.0, 0.39
.0, 0.38.1, 0.38.0, 0.37.0, 0.36.2, 0.36.1, 0.35.0, 0.34.0, 0.33.0, 0.32.0, 0.31.0, 0.30.1, 0.30.0, 0.29.0, 0.28.1, 0.27.0, 0.26
.0, 0.25.0, 0.24.0, 0.23.1, 0.23.0, 0.22.1, 0.22.0, 0.21.0, 0.20.0, 0.19.2, 0.19.1, 0.18.2, 0.18.1, 0.17.0, 0.16.0, 0.15.1, 0.14
.0, 0.13.4, 0.13.3, 0.13.2, 0.13.0, 0.12.2, 0.12.1, 0.12.0, 0.11.0, 0.10.1, 0.10.0, 0.9.0, 0.8.1, 0.8.0, 0.7.2, 0.7.1, 0.7.0, 0.
6.0, 0.5.0, 0.3, 0.2, 0.1
```

**Comment by esc** [comment]
> ...this would be my `python -m pip index versions numba` output:
> 
> ```
> WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
> numba (0.55.2)
> Available versions: 0.55.2, 0.55.1, 0.55.0, 0.54.1, 0.54.0, 0.53.1, 0.53.0, 0.52.0, 0.51.2, 0.51.1, 0.51.0, 0.50.1, 0.50.0, 0.49
> .1, 0.49.0, 0.48.0, 0.47.0, 0.46.0, 0.45.1, 0.45.0, 0.44.1, 0.44.0, 0.43.1, 0.43.0, 0.42.1, 0.42.0, 0.41.0, 0.40.1, 0.40.0, 0.39
> .0, 0.38.1, 0.38.0, 0.37.0, 0.36.2, 0.36.1, 0.35.0, 0.34.0, 0.33.0, 0.32.0, 0.31.0, 0.30.1, 0.30.0, 0.29.0, 0.28.1, 0.27.0, 0.26
> .0, 0.25.0, 0.24.0, 0.23.1, 0.23.0, 0.22.1, 0.22.0, 0.21.0, 0.20.0, 0.19.2, 0.19.1, 0.18.2, 0.18.1, 0.17.0, 0.16.0, 0.15.1, 0.14
> .0, 0.13.4, 0.13.3, 0.13.2, 0.13.0, 0.12.2, 0.12.1, 0.12.0, 0.11.0, 0.10.1, 0.10.0, 0.9.0, 0.8.1, 0.8.0, 0.7.2, 0.7.1, 0.7.0, 0.
> 6.0, 0.5.0, 0.3, 0.2, 0.1
> ```
> 
> So there is `numba==0.55.2` available and you'll be publishing `0.57` next. Does this mean you were going to skip `0.56`?

0.56.0 is currently available as a release candidate:

https://numba.discourse.group/t/ann-numba-0-56-0-rc1/1417

we hope to release it soon. 

FWIW: you can also check on the pypi.org website, which releases are available:

https://pypi.org/project/numba/#history

**Comment by kerstin921** [comment]
@esc This doesn't work, could you please check? I followed the instructions and first installed `llvmlite==0.39.0rc1', but when trying to install `numba==0.56.0rc1` afterwards, I'm getting

```
C:\Users\User\Desktop>python -m pip install numba==0.56.0rc1
Collecting numba==0.56.0rc1
  Using cached numba-0.56.0rc1-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting numpy<1.23,>=1.18
  Using cached numpy-1.22.4-cp38-cp38-win_amd64.whl (14.8 MB)
Collecting setuptools
  Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
Collecting importlib-metadata
  Downloading importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement llvmlite<0.40,>=0.39.0dev0 (from numba) (from versions: 0.2.0, 0.
2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0,
0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0,
0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.38.1)
ERROR: No matching distribution found for llvmlite<0.40,>=0.39.0dev0
```

**Comment by kerstin921** [comment]
@esc Can confirm that `llvmlite==0.39.0rc1` has been successfully. This is the content of `_version.py`:

```
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.39.0rc1'
version_full = '0014f1f78db9f457a6dfdba45de7b341f803d82f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}
```

**Comment by kerstin921** [comment]
Ahh, this sucks...

**Comment by esc** [comment]
> Ahh, this sucks...

Sorry to hear that this is troubling you. There should be a new release early next week, we hope, which ought to alleviate your installation troubles.

**Comment by kerstin921** [comment]
@esc So this is a bug in `numba` and **not** caused by my system? I did a complete, clean reinstall of my Python framework because of similar problems (with other packages) and was worried there are still issues...if that is not the case, I'm somewhat relieved

**Comment by esc** [comment]
> @esc So this is a bug in `numba` and **not** caused by my system? I did a complete, clean reinstall of my Python framework because of similar problems (with other packages) and was worried there are still issues...if that is not the case, I'm somewhat relieved

No, I believe this is caused by an incorrect installation. However, this RC was tricky to install since we were not able to post the llvmlite wheels to PyPi. I believe the final should be easier to install since we will be able to post the llvmlite wheels to PyPi again.

**Comment by kerstin921** [comment]
Could you please explain what you mean by _"incorrect installation"_? I.e. can you point me towards where I did a mistake?

FYI, I've uninstalled and (cleanly) reinstalled `numba` + `numpy` + `llvmlite` + `setuptools` about 30 times in all conceivable combinations of order, versions, and directories. I can stop `pipdeptree` complaining about version conflict when first uninstalling `numba` and then have the `numba` installation install the required `numba` version along.

Also, I've faithfully followed the instructions on

https://numba.discourse.group/t/ann-numba-0-56-0-rc1/1417

Did you check those instructions on your systems (first installing `llvmlite`, then `numba`), i.e. do they work for you? Also, does it make any difference whether you use `conda` or `pip`, e.g. should I try installing `numba` using `pip` via the `conda` package (doing `pip install -i`)?

**Comment by kerstin921** [comment]
Btw, you should leave this issue open until it is _actually_ resolved

**Comment by kerstin921** [comment]
@esc Could you provide a `conda` link for the `numba` wheel, similar to what you posted for `llvmlite==0.39.0rc1` (i.e. `pip install -i https://pypi.anaconda.org/numba/label/wheels/simple llvmlite==0.39.0rc1`)?

**Comment by kerstin921** [comment]
@esc I checked on your Anaconda channel and there is no match for

https://anaconda.org/numba/numba/files?version=0.56.0rc1&type=pypi

**Comment by esc** [comment]
@kerstin921 here is a transcript, it worked for me and for everyone else so far, hence I believe the issue is on your end:

```
 zsh» pip install -i https://pypi.anaconda.org/numba/label/wheels/simple llvmlite==0.39.0rc1
Looking in indexes: https://pypi.anaconda.org/numba/label/wheels/simple
Collecting llvmlite==0.39.0rc1
  Downloading https://pypi.anaconda.org/numba/label/wheels/simple/llvmlite/0.39.0rc1/llvmlite-0.39.0rc1-cp310-cp310-macosx_10_9_x86_64.whl (25.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 5.5 MB/s eta 0:00:00
Installing collected packages: llvmlite
Successfully installed llvmlite-0.39.0rc1
WARNING: There was an error checking the latest version of pip.
zsh» pip install numba==0.56.0rc1

Collecting numba==0.56.0rc1
  Using cached numba-0.56.0rc1-cp310-cp310-macosx_10_11_x86_64.whl (2.4 MB)
Collecting numpy<1.23,>=1.18
  Using cached numpy-1.22.4-cp310-cp310-macosx_10_15_x86_64.whl (17.7 MB)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./miniconda3/envs/numba-wheel-test/lib/python3.10/site-packages (from numba==0.56.0rc1) (0.39.0rc1)
Requirement already satisfied: setuptools in ./miniconda3/envs/numba-wheel-test/lib/python3.10/site-packages (from numba==0.56.0rc1) (61.2.0)
Installing collected packages: numpy, numba
Successfully installed numba-0.56.0rc1 numpy-1.22.4
pip install numba==0.56.0rc1  6.10s user 1.61s system 87% cpu 8.785 total
zsh» python
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
i>>> import numba
>>> numba.__version__
'0.56.0rc1'
```

**Comment by esc** [comment]
@kerstin921 I you still believe this to be an error, please do post a complete terminal transcript of:

* setting up the environment
* installing llvmlite from anaconda.org
* installing numba from pypi

Thank you 🙏

**Comment by esc** [comment]
@kerstin921 I saw you also opened a new issue here: https://github.com/numba/numba/issues/8278 thank you. I will lock this issue now to prevent further reduction on signal to noise ratio (this issue was originally about NumPy 1.23).

**Comment by esc** [comment]
The issue to track NumPy 1.23 support is here: https://github.com/numba/numba/issues/8263
