### ISSUE TITLE
Numba/llvmlite issue when listing numba in install_requires in setup.py

### ISSUE THREAD

**Issue by webbjj** [numba/numba#8244]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello, I have numba as a required package in my own personal python package (https://clustertools.readthedocs.io/en/latest/index.html). The setup.py file looks as below

import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="clustertools",
    version="1.0",
    author="Jeremy J. Webb",
    author_email="webb@astro.utoronto.ca",
    description="A python packaged for analysing star clusters",
    long_description=long_description,
    long_description_content_type='text/markdown',
    license='MIT',
    packages=["clustertools","clustertools/analysis","clustertools/cluster","clustertools/io","clustertools/io/data","clustertools/tidaltail","clustertools/util"],
    setup_requires=['numpy>=1.8','scipy'],
    install_requires=['galpy','seaborn','numba'],
    include_package_data=True,
    )

However when I try to install my python package, there seems to be an error related to numba looking for a version of llvmlite that can't be found:

Installed /usr/local/lib/python3.9/site-packages/clustertools-1.0-py3.9.egg
Processing dependencies for clustertools==1.0
Searching for numba
Reading https://pypi.org/simple/numba/
Downloading https://files.pythonhosted.org/packages/e0/7b/550dd295f45a3039e0c52347fdcf88d8304c35ddfbac8297419226bed267/numba-0.56.0rc1-cp39-cp39-macosx_10_11_x86_64.whl#sha256=4c58f0b9383d7da543005940d7e6b85f49b559bfbd0d7ff7b415792c51d06a6b
Best match: numba 0.56.0rc1
Processing numba-0.56.0rc1-cp39-cp39-macosx_10_11_x86_64.whl
Installing numba-0.56.0rc1-cp39-cp39-macosx_10_11_x86_64.whl to /usr/local/lib/python3.9/site-packages
Adding numba 0.56.0rc1 to easy-install.pth file
Installing pycc script to /usr/local/bin
Installing numba script to /usr/local/bin

Installed /usr/local/lib/python3.9/site-packages/numba-0.56.0rc1-py3.9-macosx-10.15-x86_64.egg
Searching for llvmlite<0.40,>=0.39.0dev0
Reading https://pypi.org/simple/llvmlite/
No local packages or working download links found for llvmlite<0.40,>=0.39.0dev0
error: Could not find suitable distribution for Requirement.parse('llvmlite<0.40,>=0.39.0dev0')

This issue does not happen when I just pip install numba on its own, as the command eventually returns

Successfully installed llvmlite-0.38.1 numba-0.55.2

I did try specifying install_requires=['galpy','seaborn','numba>=0.55.2'] in setup.py but this doesn't fix it either. 

So I think there is a bug somewhere that requires this version of llvmlite. 

Thanks

**Comment by webbjj** [comment]
Just to add to the above, everything seems to work if I force the numba version to 0.55.2

install_requires=['galpy','seaborn','numba>=0.55.2']

If there are other versions that don't require 'llvmlite<0.40,>=0.39.0dev0' it would be beneficial to clear up that requirement

**Comment by sklam** [comment]
Once we clear the RC period, the stable wheels will go on to PyPI normally. For now, try to avoid using the release candidates unless you are testing them.
