### ISSUE TITLE
Bug: numba implicit tuple return converts types of floats

### ISSUE THREAD

**Issue by shaunc** [numba/numba#8248]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is 0.55.2
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```py
In [7]: @nb.njit
   ...: def f():
   ...:     return np.float32(0), np.float32(0)
   ...: 

In [8]: f()
Out[8]: (0.0, 0.0)

In [9]: type(f()[0])
Out[9]: float
```
The last statement should output `<class 'numpy.float32'>`.

**Comment by sklam** [comment]
This is a known problem and a design shortcut that Numba took. Numpy scalar types are known to be very slow in the interpreter, so all numeric types are cast to their Python equivalents.
