### ISSUE TITLE
Segfault in np.split with negative axis

### ISSUE THREAD

**Issue by aseyboldt** [numba/numba#8257]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import numba
import numpy as np

@numba.njit
def foo():
    return np.split(np.zeros((10, 10)), np.array([5]), axis=-1)

foo()  # segfault
```

According to gdb the segfault occurs [in this function](https://github.com/numba/numba/blob/61ec1fd0f69aeadece218dccf4c39ebc5c7dfbc4/numba/core/runtime/_nrt_python.c#L332)

numba version '0.55.2'

**Comment by stuartarchibald** [comment]
Thanks for the report, the above reproduces. The issue is in here:
https://github.com/numba/numba/blob/88fef5b350f5b9b26b26ec963147c9dbaf3d0998/numba/np/arrayobj.py#L5642-L5653
I think the negative axis should be wrapped around before handing it to `tuple_setitem`, something like:
```diff
diff --git a/numba/np/arrayobj.py b/numba/np/arrayobj.py
--- a/numba/np/arrayobj.py
+++ b/numba/np/arrayobj.py
@@ -5643,6 +5643,8 @@ def np_array_split(ary, indices_or_sections, axis=0):
             slice_tup = build_full_slice_tuple(ary.ndim)
             out = list()
             prev = 0
+            if axis < 0:
+                axis += ary.ndim
             for cur in indices_or_sections:
                 idx = tuple_setitem(slice_tup, axis, slice(prev, cur))
                 out.append(ary[idx])
```
should fix.

**Comment by aseyboldt** [comment]
That would still segfault for `axis = -3`.
Maybe there should be a helper function that checks axis arguments and raises errors?

```python
def normalize_axis(ndim, axis):
    if axis < 0:
        axis += ndim
    if axis < 0 or axis >= ndim:
        raise IndexError("Invalid axis argument")
    return axis
```

**Comment by aseyboldt** [comment]
Ah, maybe this one looks right? https://github.com/numba/numba/blob/main/numba/np/arrayobj.py#L4990

**Comment by stuartarchibald** [comment]
> Ah, maybe this one looks right? https://github.com/numba/numba/blob/main/numba/np/arrayobj.py#L4990
> 
> I'm not really sure about how this should be used in the split implementation.

It'll need wrapping in a `numba.extending.intrinsic` and then it can just be called within the `np_array_split` implementation.
