### ISSUE TITLE
numba slower than example

### ISSUE THREAD

**Issue by aloctavodia** [numba/numba#826]
I just installed numba 0.15 on ubuntu 14.10 (beta) following this instructions http://blogs.bu.edu/mhirsch/2014/07/installing-llvm-py-and-numba-on-ubuntu-14-04/

I download the notebook from here http://jakevdp.github.io/blog/2013/06/15/numba-vs-cython-take-2/
and instead of getting an speeds up of ~1400 I just get an speed up in the order of~330.

I tried installing numba 0.13 and 0.14 with the same results. Is this issue related to numba or maybe with the dependencies?

thanks in advance!

**Comment by aloctavodia** [comment]
Hi I just have installed numba 0.17, now I get an speedup of ~450 (a little better than before) I also try numba with simple function like 
```python
x = np.arange(10000)
@jit
def func2(x):
    return x*x
```
and I get no speed up (~25 us for the function without numba and ~26.5 us with the decorator). I was running the code inside a IPython notebook and checking the running time with the _%%timeit_. Do you have any tip to diagnose the problem?

**Comment by seibert** [comment]
At the moment, Numba does not do anything special with array expressions in `@jit` functions, so you will see no performance improvement.

When trying to speed up an array expression, the current best practice is to use the `@vectorize` decorator to create a ufunc for the expression:
``` python
@numba.vectorize(['int64(int64)'])
def func2_ufunc(x):
    return x*x
```
(See http://numba.pydata.org/numba-doc/0.17.0/user/vectorize.html for more details.)  On my system, I get these timings:
```
%timeit x*x
%timeit func2(x)
%timeit func2_ufunc(x)

100000 loops, best of 3: 7.68 µs per loop
100000 loops, best of 3: 8.11 µs per loop
100000 loops, best of 3: 5.87 µs per loop
```

**Comment by pitrou** [comment]
I don't think it's useful to keep this issue open. It's more of a general use question for the mailing-list.
