### ISSUE TITLE
NumPy 1.23 support

### ISSUE THREAD

**Issue by sklam** [numba/numba#8263]
This issue tracks the NumPy 1.23 support. 

The plan is to do a Numba 0.56.1 release for NumPy 1.23 support. 

Pending:
- [x] conda packages for NumPy 1.23
- [x] patch for NumPy 1.23 (https://github.com/numba/numba/pull/8377)
- [x] update buildfarm 

Related:
- https://github.com/numba/numba/pull/8206
- https://github.com/numba/numba/pull/8345

**Comment by cdeepali** [comment]
conda packages for numpy v1.23 are now available.  So do you think this can be taken up sometime soon.

**Comment by esc** [comment]
> conda packages for numpy v1.23 are now available. So do you think this can be taken up sometime soon.

Yes, we plan to release 0.56.1 with NumPy 1.23 support soon (if I had to guess, I would say within the next few weeks).

**Comment by alexlang74** [comment]
Hi @esc , 
would you have a more detailed outlook when 0.56.1 will be available? Will it "only" include the changes in #8345 , or do you expect additional changes to be required?

thanks in advance!

**Comment by stuartarchibald** [comment]
#8349 is the current work-in-progress patch for NumPy 1.23. It is waiting on the availability of NumPy 1.23 compatible SciPy conda packages. Once they are available the patch will need to be reviewed and thoroughly tested, and any issues resolved. After which, the main blocking feature for 0.56.1 will be done.

Other items for 0.56.1 are in the milestone (currently includes fixing a regression on the CUDA target, and some CI related patches).

**Comment by alexlang74** [comment]
Thank you for the prompt response, @stuartarchibald !

**Comment by stuartarchibald** [comment]
> Thank you for the prompt response, @stuartarchibald !

No problem @alexlang74 !

**Comment by esc** [comment]
Release 0.56.2 includes support for NumPy 1.23

**Comment by abianco88** [comment]
Hi guys! I know the issue has been closed, but I am wondering if release 0.56.2 will be available as a `conda` package. Thanks!

**Comment by esc** [comment]
> Hi guys! I know the issue has been closed, but I am wondering if release 0.56.2 will be available as a `conda` package. Thanks!

For now, you can install it with:

```
conda install -c numba numba=0.56.2
```

It will become available on main/defaults at some point, you can probably track progress here:

https://github.com/AnacondaRecipes/numba-feedstock/pull/9
