### ISSUE TITLE
Erratic warnings (NumbaPerformanceWarning: Grid size) when using `@numba.vectorize(target = 'cuda')` 

### ISSUE THREAD

**Issue by s-m-e** [numba/numba#8273]
# Issue

The following minimal example illustrates the issue (on my system at least):

```python
from math import sin, cos

import numpy as np
import numba as nb
from numba import cuda

@cuda.jit('f8(f8)', device = True, inline = True)
def vectorized_cuda_dummy(scalar: float) -> float:
    res: float = 0.0
    for idx in range(round(scalar)):
        if idx % 2 == 0:
            res += sin(idx)
        else:
            res -= cos(idx)
    return res

@nb.vectorize('f8(f8)', target = 'cuda')
def vectorized_cuda(d: float) -> float:
    return vectorized_cuda_dummy(d)

for exp in range(2, 20):
    print(f'Testing size==2**{exp:d} ...')
    data = np.arange(0, 2 ** exp, dtype = 'f8')
    result = vectorized_cuda(data)
    print('... finished.')
```

It calls a dumy test function, `vectorized_cuda`, with different amounts of input data (and increasing computational complexity). I'll get output somewhere along the lines of:

```
Testing size==2**2 ...
... finished.
Testing size==2**3 ...
... finished.
Testing size==2**4 ...
... finished.
Testing size==2**5 ...
... finished.
Testing size==2**6 ...
... finished.
Testing size==2**7 ...
... finished.
Testing size==2**8 ...
... finished.
Testing size==2**9 ...
... finished.
Testing size==2**10 ...
... finished.
Testing size==2**11 ...
... finished.
Testing size==2**12 ...
... finished.
Testing size==2**13 ...
... finished.
Testing size==2**14 ...

/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (1) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (2) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (4) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (7) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (13) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (26) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (52) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))

... finished.
Testing size==2**15 ...
... finished.
Testing size==2**16 ...

/env310/lib/python3.10/site-packages/numba/cuda/compiler.py:726: NumbaPerformanceWarning: Grid size (103) < 2 * SM count (128) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))

... finished.
Testing size==2**17 ...
... finished.
Testing size==2**18 ...
... finished.
Testing size==2**19 ...
... finished.
```

The warnings show up in a non-deterministic fashion. If I re-run the above example, they might show up at different places or, sometimes, not at all. It is my understanding that the grid must be configured when invoking a cuda kernel directly. However, I am also under the impression that `@numba.vectorize(target = 'cuda')` is more of an (fully?) automated thing, although the documentation on this is really vague.

What's going on with those warnings? Does `@numba.vectorize(target = 'cuda')` actually allow to configure the grid and I just overlooked it?

# Context

- CPython == 3.10.5 (Linux, x86_64)
- numba == 0.55.2
- llvmlite == 0.38.1
- Cuda toolkit == 11.3.109

Card: A5000

**Comment by s-m-e** [comment]
The above originated from an [experiment on scaling behavior](https://github.com/pleiszenburg/bulk_propagate/blob/master/test_03.ipynb). I essentially ran the same task across different array sizes (similar to the above code) but also for different settings / modes of usage of `numba`. Plots in the bottom of the notebook. The cuda version of this code does some weird stuff (see section between arrays of size 10**3 to 10**4 plus change) and seems to under-perform on sufficiently large datasets (i.e. where I'd expect it to perform better). Related to the potential grid size issue above or am I misunderstanding something?

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect that the "erratic" location of warnings etc is related to synchronisation and buffered/interleaved std streams. @gmarkall please could you take a look at this? Thanks.

**Comment by gmarkall** [comment]
> The warnings show up in a non-deterministic fashion. If I re-run the above example, they might show up at different places or, sometimes, not at all.

The warnings go to stderr, and the output goes to stdout, so you can see different interleavings of them.

Do you get some runs where the warnings never appear when running on the command line, and not in the notebook? If so, could you check that you still see the same behaviour with Numba 0.56? There have been some recent changes to the generation of that warning.

> It is my understanding that the grid must be configured when invoking a cuda kernel directly. However, I am also under the impression that @numba.vectorize(target = 'cuda') is more of an (fully?) automated thing, although the documentation on this is really vague.

Your understanding is correct, when you launch a kernel directly you specify the configuration in square brackets as in `kernel[grid_dim, block_dim](...)`. With `@vectorize(target='cuda')` the configuration is determined automatically based on the complexity of the kernel (the number of registers it uses and therefore the maximum occupancy) and the size of the input data.

**Comment by gmarkall** [comment]
> The cuda version of this code does some weird stuff (see section between arrays of size `10**3` to `10**4` plus change) and seems to under-perform on sufficiently large datasets (i.e. where I'd expect it to perform better). Related to the potential grid size issue above or am I misunderstanding something?

Running the benchmark on data that resides on the host will reduce performance because it forces copying of data between the host and device to invoke the vectorized function, which carries a large overhead. If this is how it will be used in your application then this could be representative of the performance you'll get, but in general it's best to try and keep your data on the device and do all / as much computation as possible there to avoid the overhead of data transfer and synchronization that are necessary when splitting the computation between the host and device.

**Comment by s-m-e** [comment]
> The warnings go to stderr, and the output goes to stdout, so you can see different interleavings of them.

This explains the "erratic" part - thanks.

> Do you get some runs where the warnings never appear when running on the command line, and not in the notebook?

For 0.55.2 yes, I did, though the warnings missing entirely happened rarely. One in 20 runs perhaps. For 0.56.0, the output is now, about 20 re-runs later, absolutely consistent:

```
Testing size==2**2 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**3 ...
... finished.
Testing size==2**4 ...
... finished.
Testing size==2**5 ...
... finished.
Testing size==2**6 ...
... finished.
Testing size==2**7 ...
... finished.
Testing size==2**8 ...
... finished.
Testing size==2**9 ...
... finished.
Testing size==2**10 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**11 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 4 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**12 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 7 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**13 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 13 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**14 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 26 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**15 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 52 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**16 ...
/env310/lib/python3.10/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 103 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
... finished.
Testing size==2**17 ...
... finished.
Testing size==2**18 ...
... finished.
Testing size==2**19 ...
... finished.
```

> With @vectorize(target='cuda') the configuration is determined automatically based on the complexity of the kernel (the number of registers it uses and therefore the maximum occupancy) and the size of the input data.

I'd suggest to add this clarification to the documentation, especially the part with "the number of registers it uses" :) It explains some odd stuff.

> Running the benchmark [...] overhead of data transfer and synchronization [...]

The following graph ...

![plot_all_highlighted](https://user-images.githubusercontent.com/16851110/181071603-9ed91678-40ff-4e5a-b7c8-a1b590546f9e.jpg)

... shows runtimes for loads generated with ...

```python
COMPLEXITY = 2 ** 11

@cuda.jit('f8(f8)', device = True, inline = True)
def vectorized_cuda_dummy(scalar: float) -> float:
    res: float = 0.0
    for idx in range(COMPLEXITY):
        if idx % 2 == round(scalar) % 2:
            res += sin(idx)
        else:
            res -= cos(idx)
    return res

@nb.vectorize('f8(f8)', target = 'cuda')
def vectorized_cuda(d: float) -> float:
    return vectorized_cuda_dummy(d)
```

... where the x-axis represents the length of `d`. The section "labeled" as *B* is where the data transfers kick in (I guess), creating a "hard boundary" for this particular problem. What I do not quite understand is the section labeled as "A". The run-time literally plateaus. Is is related to the "complexity of the kernel" you mentioned earlier?

**Comment by gmarkall** [comment]
> What I do not quite understand is the section labeled as "A". The run-time literally plateaus. Is it related to the "complexity of the kernel" you mentioned earlier?

I think it's both difficult and not that useful to analyse performance for smaller input data (generally you need a lot to make best use of a GPU), but I'll take a guess:

In this region the input array is relatively small, so the grid configuration can be handled in different ways by the driver around this region - I suspect that at the leftmost point of this region, not all SMs are used. As you increase the input size, more SMs might get allocated so more work gets done, but with around the same runtime. Then at the right, there are no more SMs available so the runtime starts increasing with the size of the grid again. I believe this kind of scheduling is motivated by the GPU being able to run multiple kernels at once, so for small grids it's probably a generally better scheduling decision not to allocate an entire GPU to a smaller grid, and leave some SMs free for other kernels.

Note that all the above is my speculation / guesswork based on observed behaviour / experience - I have no special insight into what is actually going on at this level, and I've generally not looked into it too deep - I think performance analysis for smaller data on the GPU is not very useful for most applications.

Additionally, I tried to reproduce this locally - I took your benchmark code and edited it a bit:

```python
from math import sin, cos

import numpy as np
from numba import config, cuda, njit, vectorize

from time import perf_counter

config.CUDA_LOW_OCCUPANCY_WARNINGS = False

sigs = ['f8(f8)']


@njit
def vectorized_dummy(scalar: float) -> float:
    res: float = 0.0
    for idx in range(round(scalar)):
        if idx % 2 == 0:
            res += sin(idx)
        else:
            res -= cos(idx)
    return res


@vectorize(sigs)
def vectorized_cpu(d: float) -> float:
    return vectorized_dummy(d)


@vectorize(sigs, target='parallel')
def vectorized_parallel(d: float) -> float:
    return vectorized_dummy(d)


@vectorize(sigs, target='cuda')
def vectorized_cuda(d: float) -> float:
    return vectorized_dummy(d)


# Make one CUDA kernel launch to initialize CUDA first
cuda.jit('void()')(lambda: None)[1, 1]()


fns = {
    'cpu': vectorized_cpu,
    'parallel': vectorized_parallel,
    'cuda': vectorized_cuda,
}


for size in range(1000, 20000, 1000):
    print(f'Size: {size} | ', end="")
    data = np.arange(0, size, dtype='f8')
    results = {}

    for name, fn in fns.items():
        start = perf_counter()
        results[name] = fn(data)
        end = perf_counter()

        print(f"{name}: {end - start} | ", end="")

    np.testing.assert_allclose(results['cpu'], results['parallel'])
    np.testing.assert_allclose(results['cpu'], results['cuda'])

    print(' ... OK!')
```

which produces on my system (Quadro RTX 8000, i7-6700K):

```
Size: 1000 | cpu: 0.008742564000385755 | parallel: 0.002360587000111991 | cuda: 0.06185015099981683 |  ... OK!
Size: 2000 | cpu: 0.034558567000203766 | parallel: 0.00864913500026887 | cuda: 0.012827630999709072 |  ... OK!
Size: 3000 | cpu: 0.07755890299995372 | parallel: 0.020744178000313696 | cuda: 0.01967642399995384 |  ... OK!
Size: 4000 | cpu: 0.1380055440004071 | parallel: 0.03585525600010442 | cuda: 0.026290732999768807 |  ... OK!
Size: 5000 | cpu: 0.21356650000052468 | parallel: 0.055731114000082016 | cuda: 0.033585000000130094 |  ... OK!
Size: 6000 | cpu: 0.31004746300004626 | parallel: 0.08290680499976588 | cuda: 0.03990221799995197 |  ... OK!
Size: 7000 | cpu: 0.42018787100005284 | parallel: 0.11160409200056165 | cuda: 0.04593309100073384 |  ... OK!
Size: 8000 | cpu: 0.5532640460005496 | parallel: 0.14478256599977612 | cuda: 0.05352534199937509 |  ... OK!
Size: 9000 | cpu: 0.7005461529997774 | parallel: 0.18808946299941454 | cuda: 0.06161818000055064 |  ... OK!
Size: 10000 | cpu: 0.859400860000278 | parallel: 0.22749632600061886 | cuda: 0.06970949700007623 |  ... OK!
Size: 11000 | cpu: 1.0504429590000655 | parallel: 0.2604702369999359 | cuda: 0.07796688100006577 |  ... OK!
Size: 12000 | cpu: 1.249685789999603 | parallel: 0.3220928079999794 | cuda: 0.08601815699967119 |  ... OK!
Size: 13000 | cpu: 1.458789849999448 | parallel: 0.3750138750001497 | cuda: 0.09505723699930968 |  ... OK!
Size: 14000 | cpu: 1.7031451829998332 | parallel: 0.4229498920003607 | cuda: 0.10212129899991851 |  ... OK!
Size: 15000 | cpu: 1.9544119060001321 | parallel: 0.49179622100018605 | cuda: 0.11020449099942198 |  ... OK!
Size: 16000 | cpu: 2.2432095609992757 | parallel: 0.5659488400006012 | cuda: 0.11726750900015759 |  ... OK!
Size: 17000 | cpu: 2.5068929409999328 | parallel: 0.6246640930003196 | cuda: 0.12637305599946558 |  ... OK!
Size: 18000 | cpu: 2.8117863790002957 | parallel: 0.7085515150001811 | cuda: 0.134491646999777 |  ... OK!
Size: 19000 | cpu: 3.1075477829999727 | parallel: 0.7618600329997207 | cuda: 0.14306364200001553 |  ... OK!
```

So the execution time of CUDA looks like a steady gradient, with some overhead on the first call of the vectorized function:

![image](https://user-images.githubusercontent.com/535640/186879278-9a178a8f-9721-41c5-b69a-f3ee0f33ec5a.png)

Do you get a plateau with this example on your system?
