### ISSUE TITLE
Installation of `numba==0.56.0rc1` not possible: `ERROR: No matching distribution found for llvmlite<0.40,>=0.39.0dev0`

### ISSUE THREAD

**Issue by kerstin921** [numba/numba#8278]
I followed the installation instructions for `numba==0.56.0rc1` [here](https://numba.discourse.group/t/ann-numba-0-56-0-rc1/1417), but despite having successfully installed `llvmlite==0.39.0rc1` by doing `pip install -i https://pypi.anaconda.org/numba/label/wheels/simple llvmlite==0.39.0rc1`, `pip` keeps complaining that it cannot find a matching version:

```
C:\Users\Username>python -m pip install numba==0.56.0rc1
Collecting numba==0.56.0rc1
  Using cached numba-0.56.0rc1-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting setuptools
  Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
Collecting numpy<1.23,>=1.18
  Using cached numpy-1.22.4-cp38-cp38-win_amd64.whl (14.8 MB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement llvmlite<0.40,>=0.39.0dev0 (from numba) (from versions: 0.2.0, 0.
2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0,
0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0,
0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.38.1)
ERROR: No matching distribution found for llvmlite<0.40,>=0.39.0dev0
```

However, `llvmlite==0.39.0rc1` **was** successfully installed as you can see from its `_version.py`:

```
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.39.0rc1'
version_full = '0014f1f78db9f457a6dfdba45de7b341f803d82f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I cannot reproduce this when following the linked instructions presented on discourse (with Python 3.8, pip=22.1.2).

**Comment by stuartarchibald** [comment]
Differences that may need looking at include:
* linux vs windows
* pip versions
* what the installation environment is (conda env, virtual env, something else)

**Comment by kerstin921** [comment]
The commands used were

`pip install -i https://pypi.anaconda.org/numba/label/wheels/simple llvmlite==0.39.0rc1`

followed by

`pip install numba==0.56.0rc1`.

Can't you pinpoint from which file, maybe which line of code, the above exception originates? Unfortunately, I don't know much about the inner workings of Python/`pip` dependency checks and resolution mechanism, but having created this package, you guys should have much better understanding. Since there appears to be no problem with the actual `llvmlite==0.39.0rc1` installation, I'm suspecting that this is merely a small code error that handles `numba` requirements, possibly a typo or a wrongly set search path?

**Comment by kerstin921** [comment]
...apropos path, I'm using a system-wide installation of Python, meaning that all my packages go into

`C:\Program Files\Python38\Lib\site-packages`.

If this `numba` version happens to look for packages elsewhere (e.g. in `%APPDATA` or other user sites), this obviously will fail!

So please check your environment variables as a first step.

**Comment by esc** [comment]
FWIW: I tried this using Python 3.8 on Windows and was unable to reproduce:

<img width="945" alt="Screen Shot 2022-07-26 at 10 24 28" src="https://user-images.githubusercontent.com/41563/180959912-ed40b9b5-1dc3-464d-8fef-5dc66a3a1705.png">


<img width="945" alt="Screen Shot 2022-07-26 at 10 24 41" src="https://user-images.githubusercontent.com/41563/180959933-994d25ac-6cc6-4103-bea1-9c5e8ab7ccf8.png">

@kerstin921 I you still believe this to be an error, please do post a complete terminal transcript of:

* setting up the environment
* installing llvmlite from anaconda.org
* installing numba from pypi

Thank you 🙏

**Comment by esc** [comment]
Both Numba 0.56.0 and llvmlite 0.39.0 have been released:

https://numba.discourse.group/t/ann-numba-0-56-0/1461

https://numba.discourse.group/t/ann-llvmlite-0-39-0/1460

@kerstin921 we hope that this should make it less troublesome to get Numba installed.

**Comment by jorenham** [comment]
This still occurs for numba 0.56.0 with python-poetry:

```
$ poetry update                    
Updating dependencies
Resolving dependencies... (27.5s)

  SolverProblemError

  Because numba (0.56.0) depends on llvmlite (>=0.39.0dev0,<0.40) which doesn't match any versions, numba is forbidden.
  So, because cf-owl depends on numba (0.56.0), version solving failed.

  at ~/.local/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

```

**Comment by esc** [comment]
> This still occurs for numba 0.56.0 with python-poetry:

Can you provide additional details? That would be great since we have been unable to reproduce this so far.

**Comment by esc** [comment]
> > This still occurs for numba 0.56.0 with python-poetry:
> 
> Can you provide additional details? That would be great since we have been unable to reproduce this so far.

I just tried the following to confirm that llvmlite 0.39.0 is indeed available from PyPi:

```
zsh» python -m pip index versions llvmlite
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
llvmlite (0.39.0)
Available versions: 0.39.0, 0.38.1, 0.38.0, 0.35.0, 0.34.0, 0.33.0, 0.32.1, 0.32.0, 0.31.0, 0.30.0, 0.29.0, 0.28.0, 0.27.1, 0.27.0, 0.26.0, 0.25.0, 0.24.0, 0.23.2, 0.23.0, 0.22.0, 0.21.0, 0.20.0, 0.19.0, 0.18.0, 0.17.1, 0.17.0, 0.16.0, 0.15.0, 0.14.0, 0.13.0, 0.12.1, 0.12.0.1, 0.11.0, 0.10.0, 0.9.0, 0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.2.2, 0.2.1, 0.2.0
```

Any additional input you have here, @kerstin921 @jorenham would be good, thank you!

**Comment by jorenham** [comment]
@esc It could be a python-poetry bug, as it seems to assume that `0.39.0dev0 > 0.39.0`

**Comment by esc** [comment]
> @esc It could be a python-poetry bug, as it seems to assume that `0.39.0dev0 > 0.39.0`

This may very well be..

I tried  https://packaging.pypa.io/en/latest/version.html and observed the following:

```
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version, parse
>>> v1 = parse("0.39.0dev0")
>>> v2 = parse("0.39.0")
>>> v2 >= v1
True
```

**Comment by esc** [comment]
@dimbleby can you take a look here. The above is about poetry and llvmlite in combination causing issues. Thank you 🙏

**Comment by dimbleby** [comment]
no

**Comment by dimbleby** [comment]
but I will say that you should try with the latest poetry beta, if you're not already

**Comment by esc** [comment]
> @esc It could be a python-poetry bug, as it seems to assume that `0.39.0dev0 > 0.39.0`

@jorenham can you say, how you came to that conclusion. (Terminal commands, python code, anything??). That would be most helpful.

**Comment by jorenham** [comment]
> > @esc It could be a python-poetry bug, as it seems to assume that `0.39.0dev0 > 0.39.0`
> 
> @jorenham can you say, how you came to that conclusion. (Terminal commands, python code, anything??). That would be most helpful.

This:

```
$ poetry update                    
Updating dependencies
Resolving dependencies... (27.5s)

  SolverProblemError

  Because numba (0.56.0) depends on llvmlite (>=0.39.0dev0,<0.40) which doesn't match any versions, numba is forbidden.
  So, because cf-owl depends on numba (0.56.0), version solving failed.

  at ~/.local/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by esc** [comment]
> > > @esc It could be a python-poetry bug, as it seems to assume that `0.39.0dev0 > 0.39.0`
> > 
> > 
> > @jorenham can you say, how you came to that conclusion. (Terminal commands, python code, anything??). That would be most helpful.
> 
> This:
> 
> ```
> $ poetry update                    
> Updating dependencies
> Resolving dependencies... (27.5s)
> 
>   SolverProblemError
> 
>   Because numba (0.56.0) depends on llvmlite (>=0.39.0dev0,<0.40) which doesn't match any versions, numba is forbidden.
>   So, because cf-owl depends on numba (0.56.0), version solving failed.
> 
>   at ~/.local/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
>       237│             packages = result.packages
>       238│         except OverrideNeeded as e:
>       239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
>       240│         except SolveFailure as e:
>     → 241│             raise SolverProblemError(e)
>       242│ 
>       243│         results = dict(
>       244│             depth_first_search(
>       245│                 PackageNode(self._package, packages), aggregate_package_nodes
> ```

Thank you, can you perhaps provide instructions on how to reproduce this? Is  there a cf-owl repo I should be looking at?

**Comment by jorenham** [comment]
@esc this particular repo is private, but I'll take a look at creating a minimal example that reproduces this issue

**Comment by jorenham** [comment]
@esc While trying to reproduce the problem, it appears to work ok now. I suspect it must have been a stale cache 🤷🏻‍♂️ .

For reference: running `poetry install` works fine for a project with this `pyproject.toml` :

```toml
[tool.poetry]
name = "numba_0_56_0_poetry"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
numba = "0.56.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by esc** [comment]
@kerstin921 @jorenham as no further updates were provided, I am assuming this issue is now resolved. If any future issues with Numba and poetry should arise, please don't hesitate to reach out again!
