### ISSUE TITLE
Typo in Python demonstration on the web

### ISSUE THREAD

**Issue by marioroy** [numba/numba#8281]
URL: [https://numba.pydata.org/](https://numba.pydata.org/)

Replace line `from numba import jit` with `from numba import njit`.

```python
from numba import njit
import random

@njit
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples
```

**Comment by stuartarchibald** [comment]
Thanks for the report. That does indeed look like a typo!

**Comment by esc** [comment]
duplicate of https://github.com/numba/numba.github.com/issues/8

**Comment by esc** [comment]
fix is here: https://github.com/numba/numba.github.com/pull/9

**Comment by esc** [comment]
Fix is merged.
