### ISSUE TITLE
Add an option to set ufunc identity with vectorize?

### ISSUE THREAD

**Issue by shoyer** [numba/numba#829]
Another way to write (some) custom aggregation functions, other than my suggested approach in #825, would be use plain old ufuncs.

This has the advantage of passing off the axis handling/looping to numpy's `ufunc.reduce` method. And in fact, it already *almost* works:

```
@vectorize(['float64(float64, float64)'])
def _nanadd(a, b):
    if np.isnan(b):
        return a
    else:
        return a + b

nansum = _nanadd.reduce
```

As a bonus, this method is consistently fast. It's generally slightly (~20%) slower than bottleneck, but it has better worst case performance: `bottleneck.nansum` slows down by a factor of 4x when aggregating over a non-contiguous dimension (e.g., `axis=0` for a 2-dimensional C contiguous array), but the nansum ufunc doesn't miss a beat. I suspect this is because numpy has some clever logic for picking the optimal ordering for nested iteration for ufunc.reduce.

What's missing? There's no way to set `_nanadd.identity = 0.0`, which we would need to ensure that the calculation is correct if any of the first values are missing.

So I propose that `vectorize` should gain the optional keyword argument `identity` to set this variable. Right now it is always set to `None`: https://github.com/numba/numba/blob/1f4bee0a86edc20c9d3de07046af0d77dfa75469/numba/npyufunc/_ufunc.c#L5

**Comment by pitrou** [comment]
Or perhaps make the identity attribute writable, to avoid adding another parameter to ``vectorize``?

**Comment by pitrou** [comment]
Ah, but that doesn't work due to the attribute not being writable on numpy ufuncs. Scratch that.

**Comment by pitrou** [comment]
Ok, Numpy allows for four different identity (or unit) values:
* zero
* one
* none, meaning no unit, and the order of operations cannot be reordered (sic); for example `subtract`, `divide`, `power`
* reorderable none, no unit, and the order of operations can be reordered (sic); for example `maximum` and `minimum`

All cases except "none" allow reduction with multiple axes at once.

**Comment by shoyer** [comment]
Interesting-- does numpy really only allow those specific values? I can see other also being potentially useful, e.g., -1 or NaN as sentinel values.

**Comment by seibert** [comment]
I was surprised too:

https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ufuncobject.h#L141-L142
https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/ufuncobject.h#L271-L290

**Comment by shoyer** [comment]
I guess numba would need to define a `ReorderableNone` constant in order to allow the last case? It looks like there is no python exposure of that constant in numpy.

**Comment by pitrou** [comment]
> I guess numba would need to define a ReorderableNone constant in order to allow the last case?

I was thinking a string (e.g. "reorderable") would be sufficient.
