### ISSUE TITLE
numba's `np.full_like` is inconsistent with numpy's

### ISSUE THREAD

**Issue by ngam** [numba/numba#8312]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

In numpy, [`np.full_like`](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html) expects two `array_like` objects for the first two arguments. As a result, 
- `np.full_like(np.asarray([1,2,3]), 0)` yields `array([0, 0, 0])`
- `np.full_like(np.asarray([1,2,3]), np.asarray([-1,-2,-3]))` yields `array([-1, -2, -3])`
- `np.full_like(np.asarray([1,2,3]), np.asarray([-1]))` yields `array([-1, -1, -1])`
- `np.full_like(np.asarray([1,2,3]), np.asarray(-1))` yields `array([-1, -1, -1])`

and so on... (one could even specify a scalar for the first argument)

However, the [numba implementation](https://github.com/numba/numba/blob/551f072133b87e9cb03727cd5933c5478e69cded/numba/np/arrayobj.py#L4198-L4224) of `np.full_like` strictly expects a scalar for the second argument. Hence, something like the snippet code below would fail unless `term_util` is given a scalar in the first argument below (corresponding to the second argument in `np.full_like`). It does NOT even accept `np.asarray(1)`.

```python
import numpy as np
from numba import jit

@jit(nopython=True, parallel=True)
def term_util(term, orig):
    return np.full_like(orig, term)
```

This is likely due to the flattening and filling in the numba implementation. Note that numpy's implementation seems to differ significantly.

**Comment by esc** [comment]
@ngam thank you for opening this. May I ask what happened here and why was the issue closed again?
