### ISSUE TITLE
Segfault in nested loop with aliased array

### ISSUE THREAD

**Issue by aseyboldt** [numba/numba#8313]
```python
import numpy as np
import numba

a = np.ones((100, 4000))
out = np.zeros((100, 4000))


@numba.njit(fastmath=True)
def foo(a, out):
    n, m = a.shape
    for i in range(n):
        # Create a reference to part of the array that isn't used anywhere
        out_tmp = out[i]
        a_tmp = a[i]
        for j in range(m):
            out[j] = a[j]

foo(a, out)  # segfault
```

This is on Linux python3.9 with the development version of numba from the numba channel:

```
> mamba list | rg numba
icc_rt                    2020.2                intel_254    numba/label/dev
llvmlite                  0.40.0dev0       py39he1b5a44_9    numba/label/dev
numba                     0.57.0.dev0+170.gce9bdacc7           dev_0    <develop>
```

**Comment by esc** [comment]
@aseyboldt thank you for submitting this. I tried to add `boundscheck=True` and noticed out of bounds errors. I also tried to comment out the `@jit` decorators and received:

```
Traceback (most recent call last):
  File "/Users/esc/git/numba/issue_8313.py", line 18, in <module>
    foo(my_a, my_out)  # segfault
  File "/Users/esc/git/numba/issue_8313.py", line 16, in foo
    out[j] = a[j]
IndexError: index 100 is out of bounds for axis 0 with size 100
```

Fixing the indexing as follows:

```
import numpy as np
import numba

my_a = np.ones((100, 4000))
my_out = np.zeros((100, 4000))


@numba.njit(fastmath=True, boundscheck=True)
def foo(a, out):
    n, m = a.shape
    for i in range(n):
        # Create a reference to part of the array that isn't used anywhere
        out_tmp = out[i]
        a_tmp = a[i]
        for j in range(m):
            out[i,j] = a[i,j]

foo(my_a, my_out)  # segfault
print(my_out)
```

Seems to make it work fine. Can you check if I missed something?

**Comment by aseyboldt** [comment]
Oh! I can't believe I missed that out of bounds access. I was playing with different versions of that loop due to missing vectorization, and apparently got somewhat confused in the process.
Sorry for the noise, closing this.

**Comment by esc** [comment]
> Oh! I can't believe I missed that out of bounds access. I was playing with different versions of that loop due to missing vectorization, and apparently got somewhat confused in the process. Sorry for the noise, closing this.

`Errare Humanum Est.` No worries and thank you for following up.
