### ISSUE TITLE
LoweringError

### ISSUE THREAD

**Issue by zzh51129** [numba/numba#8317]
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Operands must be the same type, got (i64, i32)

File "F:\Anaconda3_steup\lib\site-packages\esda\crand.py", line 61:
def vec_permutations(max_card: int, n: int, k_replications: int, seed: int):
    <source elided>
    np.random.seed(seed)
    result = np.empty((k_replications, max_card), dtype=np.int64)
    ^

[1] During: lowering "$0.14 = call $0.7($0.10, func=$0.7, args=[Var($0.10, F:\Anaconda3_steup\lib\site-packages\esda\crand.py (61))], kws=[('dtype', Var($0.12, F:\Anaconda3_steup\lib\site-packages\esda\crand.py (61)))], vararg=None)" at F:\Anaconda3_steup\lib\site-packages\esda\crand.py (61)

**Comment by esc** [comment]
@zzh51129 thank you for opening this issue. In order to diagnose this further, please submit more information. You can read about how to do this here: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by stuartarchibald** [comment]
@zzh51129 which version of Numba do you have? There was a bug in the handling of mixed width integers as arguments to `np.empty` a while back, if you aren't using a recent version of Numba (0.55 or 0.56) perhaps try updating to see if it is fixed already?

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
