### ISSUE TITLE
Obsolete pycc script/code

### ISSUE THREAD

**Issue by firai** [numba/numba#8322]
Since `pycc.main()` has been deprecated for almost 7 years (https://github.com/numba/numba/commit/7342cb9aa7aded02209605299dbbdbe377794078), it seems that the `pycc` script (shown below) should be removed or at least be archived in a way that does not deploy it to new installations. For that matter, is there a reason to keep `pycc.main()` around, or should removal/archival of the function be considered?

https://github.com/numba/numba/blob/61ec1fd0f69aeadece218dccf4c39ebc5c7dfbc4/numba/pycc/pycc#L1-L3

https://github.com/numba/numba/blob/61ec1fd0f69aeadece218dccf4c39ebc5c7dfbc4/numba/pycc/__init__.py#L26-L100

**Comment by esc** [comment]
@firai thank you for this suggestion. As discussed in the developer meeting last night (https://github.com/numba/numba/wiki/Minutes_2022_08_09) this can indeed be removed.

**Comment by stuartarchibald** [comment]
Removed in #8335.
