### ISSUE TITLE
Get the optimized bytecode from IR

### ISSUE THREAD

**Issue by shiyu22** [numba/numba#8330]
## Feature request
Can numba get the optimized bytecode from intermediate representation (IR)?

**Comment by esc** [comment]
> ## Feature request
> Can numba get the optimized bytecode from intermediate representation (IR)?

Probably not, no. Although, to be able to answer your question, please do say which optimized bytecode and which intermediate representation? If you want to create Python Bytecode from Numba IR, that's a no. If you want to create Python bytecode from LLVM IR, that's also a no.

**Comment by shiyu22** [comment]
Got it, thanks anyway.
