### ISSUE TITLE
Add `inspect_llvm(signature)` method to the Overloaded class

### ISSUE THREAD

**Issue by seibert** [numba/numba#837]
We need a way to fetch the generated LLVM for a given type specialization of a compiled function.  This can be exposed by adding an `inspect_llvm` function to the Overloaded (or perhaps OverloadedBase) that takes the type signature of the desired instance and returns the LLVM IR string.

This feature will also likely be used by future support for inlining one JIT function into another one.

**Comment by pitrou** [comment]
@meawoppl, are you willing to work on this one?

**Comment by meawoppl** [comment]
Sure.  I got a bit derailed after the last epic-PR.  Lemme review my notes on this.  I will post my planned trajectory in an hour or so.

**Comment by meawoppl** [comment]
I was hoping to nail this over the weekend, but I can't seem to figure out how to get a handle to the LLVM "module" from the _compileinfos mentioned in the comments above.  It seems to just be a c-resource type object, without a clear link back to the parent module.  Is there a clean way to do this?

**Comment by pitrou** [comment]
If you look up the `library` attribute, you should get a `CodeLibrary` object able to give you the desired info (see `numba.targets.codegen`).
