### ISSUE TITLE
slow performance observed in np.sort() with nan arrays

### ISSUE THREAD

**Issue by auderson** [numba/numba#8382]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

As title.
```python
from numba import njit
import numpy as np

@njit
def test(a):
    return np.sort(a)

arr = np.full(100_000, np.nan)
# compile it
test(arr[:10])

%%time
test(arr)
# CPU times: user 3.81 s, sys: 40.4 ms, total: 3.85 s
# Wall time: 3.82 s
# array([nan, nan, nan, ..., nan, nan, nan])

%%time
test.py_func(arr)
# CPU times: user 5.55 ms, sys: 0 ns, total: 5.55 ms
# Wall time: 4.17 ms
# array([nan, nan, nan, ..., nan, nan, nan])

```

**Comment by gmarkall** [comment]
Thanks for the report and nice reproducer - I can reproduce the observed performance.

**Comment by sklam** [comment]
The problem is NaN specific. We might need a specialized comparison for float types following what numpy did in https://github.com/numpy/numpy/commit/717c7acf14d04be79d7a1c098d83cac69481e0af
