### ISSUE TITLE
Strange Result for np.nanstd in njit function

### ISSUE THREAD

**Issue by Ziffer-yan** [numba/numba#8403]
When I try to use numba's njit function to calculate the pearson correlation coefficient, strange result happened.

Codes are like this:

```
import numpy as np
import numba as nb

np.random.seed(0)
x1 = np.random.randn(20)
np.random.seed(1)
x2 = np.random.randn(20)
y1,y2 = x1.copy(), x2.copy()
y1[0], y2[-1] = np.nan, np.nan

@nb.njit([nb.f8(nb.f8[:], nb.f8[:]), nb.f8(nb.i4[:], nb.i4[:])])
def np_paircorr(x1, x2):
    nmrt = np.nanmean(x1*x2) - np.nanmean(x1)*np.nanmean(x2)
    dnmt = np.nanstd(x1) * np.nanstd(x2)
    
    if dnmt == 0.0:
        print(0, x1, x2) #print to tell whether x1, x2 has been changed in this function or not after finding the bug
        print(nmrt, dnmt)
        return np.nan
    else:
        print(1, x1, x2)
        print(nmrt, dnmt)
        return nmrt/dnmt

print(np_paircorr(x1, x2))
print()
print(np_paircorr(y1, y2))
```

And the results are like this 

```
0 [ 1.76405235  0.40015721  0.97873798  2.2408932  1.86755799  -0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351   0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826 0.3130677  -0.85409574] [ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127 0.17242821 -0.87785842 0.04221375  0.58281521]
0.16087841186274332 0.0
nan

1 [        nan  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351 0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826 0.3130677  -0.85409574] [ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127 -0.17242821 -0.87785842 0.04221375         nan]
0.04948528609069712 nan
nan
```

It can be seen clearly that the np.nanstd() function in the njit function doesn't work correctly. And if I hoist the `print(nmrt, dnmt)` right after the `dnmt = np.nanstd(x1) * np.nanstd(x2)` , the `np_paircorr` can work correctly.

Even more strangely, if I put the `dnmt = ***` before `nmrt = np.nanmean(x1*x2) - np.nanmean(x1)*np.nanmean(x2)` , it can also work correctly.

So, I guess maybe during the optimization of the njit function, some calculation inside the `np.nanstd` is broken. And I hope whoever can solve this problem tells me how. Thanks a lot. 

My python environment is listed below:
| Name           |         Version       |            Build |
| ---- | ---- | ---- |
| ipython        |           7.29.0      |     py39hd4e2768_0 |
| python         |           3.9.7          |      h6244533_1 |
| numpy          |           1.20.3        |   py39ha4e8547_0 |
| numpy-base  |              1.20.3     |      py39hc2deb75_0 |
| numpydoc      |            1.1.0         |     pyhd3eb1b0_1 |
| numba             |        0.54.1         |  py39hf11a4ad_0 |

**Comment by Ziffer-yan** [comment]
The correct result for `np_paircorr(x1,x2)` is `0.17205590580162294`, and the correct result for `np_paircorr(y1,y2)` is `0.03970556476881301`

**Comment by gmarkall** [comment]
Can you try Numba 0.56? I'm getting the same results from Numba and NumPy with Numba main and NumPy 1.22.4.

**Comment by Ziffer-yan** [comment]
After I updated numpy to 1.22.4 and numba to 0.56.0, the bug still remained.

**Comment by sklam** [comment]
I cannot replicate the problem on mainline or 0.54.1 on OSX.

**Comment by Ziffer-yan** [comment]
yeah, My OS is win11, if this strange bug can not be replicated on other OSs, I'll close the issue.
