### ISSUE TITLE
ImportError: cannot import name 'set_parallel_chunksize' from 'numba.np.ufunc' 

### ISSUE THREAD

**Issue by astro-kevin** [numba/numba#8416]
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

On running `from numba import jit, njit`
This error occurs
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [49], in <cell line: 5>()
      3 import numpy as np
      4 import h5py
----> 5 from numba import jit, njit

File ~/anaconda3/envs/p3.10/lib/python3.10/site-packages/numba/__init__.py:42, in <module>
     38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     39                                    jit_module)
     41 # Re-export vectorize decorators and the thread layer querying function
---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     43                             get_num_threads, set_num_threads)
     45 # Re-export Numpy helpers
     46 from numba.np.numpy_support import carray, farray, from_dtype

ImportError: cannot import name 'set_parallel_chunksize' from 'numba.np.ufunc' (/home/kevin/anaconda3/envs/p3.10/lib/python3.10/site-packages/numba/np/ufunc/__init__.py)
```

Numba v0.56.2
Numpy v1.23.2
Python v3.10.4
All installed via conda

**Comment by esc** [comment]
> ## Reporting a bug
> * [ x] I have tried using the latest released version of Numba (most recent is
>   visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
> * [ x] I have included a self contained code sample to reproduce the problem.
>   i.e. it's possible to run as 'python bug.py'.
> 
> On running `from numba import jit, njit` This error occurs `--------------------------------------------------------------------------- ImportError Traceback (most recent call last) Input In [49], in <cell line: 5>() 3 import numpy as np 4 import h5py ----> 5 from numba import jit, njit
> 
> File ~/anaconda3/envs/p3.10/lib/python3.10/site-packages/numba/**init**.py:42, in 38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil, 39 jit_module) 41 # Re-export vectorize decorators and the thread layer querying function ---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer, 43 get_num_threads, set_num_threads) 45 # Re-export Numpy helpers 46 from numba.np.numpy_support import carray, farray, from_dtype
> 
> ImportError: cannot import name 'set_parallel_chunksize' from 'numba.np.ufunc' (/home/kevin/anaconda3/envs/p3.10/lib/python3.10/site-packages/numba/np/ufunc/**init**.py)`
> 
> Numba v0.56.2 Numpy v1.23.2 All installed via conda

@astro-kevin : Thank you for reporting this. Which operating system (platform) and Python version do you experience this with?

**Comment by astro-kevin** [comment]
python v3.10.4

OS:
`NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`

**Comment by esc** [comment]
@astro-kevin judging from the error, I am assuming this is linux-64 and python 3.10? I tried to reproduce this using the docker container `numba/ci-linux-64:latest`. I setup the environment using:

```
conda create -n TEST -c numba numba=0.56.2
```

But was not able to reproduce the error you are experiencing:

```
(base) root@6d1f4404ac56:/# conda activate TEST
(TEST) root@6d1f4404ac56:/# python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> numba.__version__
'0.56.2'
>>> from numba import jit, njit
>>>
```

Do you perhaps have a `conda` command to setup an environment?

**Comment by astro-kevin** [comment]
I have found that the error doesn't occur when running from terminal--i.e.

```
>>> from numba import jit, njit
>>>
```

But does occur when running from a jupyter notebook running in the same environment.

**Comment by gmarkall** [comment]
The line in the traceback :

```
---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     43                             get_num_threads, set_num_threads)
```

matches the code for 0.55.2:

https://github.com/numba/numba/blob/2298ad6186d177f39c564046890263b0f1c74ecc/numba/__init__.py#L42-L43

It looks different in 0.56.2:

https://github.com/numba/numba/blob/d6731f6d22f6695ee7abc305f81f81115639e2a4/numba/__init__.py#L42-L46

So it looks like the environment is somehow corrupted and parts of 0.55.2 and 0.56.2 are mixed together.

**Comment by gmarkall** [comment]
Perhaps Jupyter is not running from the activated environment, whereas terminal apps are?

**Comment by astro-kevin** [comment]
I've deleted the environment and re-created it. Everything works now. Thanks!

**Comment by esc** [comment]
@astro-kevin thank you for following up!
