### ISSUE TITLE
Wrong value returned when multiple functions have the same name

### ISSUE THREAD

**Issue by wluker** [numba/numba#842]
Hello,
I'm using numba version 0.15.1 on Linux64. On my machine the following code fails the assert statement:

    import numba

    def factory1():
      def fn():
        return 1.0
      return fn

    def factory2():
      def fn():
        return 2.0
      return fn

    jitted_fn1 = numba.jit(nopython=True)(factory1())
    jitted_fn2 = numba.jit(nopython=True)(factory2())

    @numba.jit(nopython=True)
    def calling_fn():
      x = jitted_fn1()
      y = jitted_fn2()
      return x

    calling_fn()
    print "llvm code::"
    print calling_fn._compileinfos[tuple()].llvm_func
    # the issue seems to be related to llvm code line
    #%2 = call i32 @__main__.fn.(double* %0, i8* null)
    # it could be calling factory1::fn or factory2::fn

    ## this fails because 2.0 is actually returned
    assert calling_fn() == 1.0

If the function names returned by each factory are unique, then the assert statement passes.

I believe the issue is related to llvm code such as "%2 = call i32 @__main__.**fn**.(double* %0, i8* null)". Maybe something like @__main__.**fn+uniqueID**.(double* %0, i8* null) would fix the issue.

**Comment by pitrou** [comment]
This is now fixed (see changeset 7b11a70436e5b8a16570672767bafd39cb1f5cd1 for the final nail in this bug's coffin).
