### ISSUE TITLE
Blunder when accessing a list item in a loop

### ISSUE THREAD

**Issue by Vlod-github** [numba/numba#8428]
In the for loop, list[?] is randomly returned instead of list[i]

```python
from numba import njit


@njit(cache=True)
def lcg():
	seed = 0
	while True:
		seed = (3*seed+3) % 5
		yield seed

@njit(cache=True)
def mix(gen, data):
	for i in range(0, len(data)):
		ri = next(gen) # ri [0..4]
		data[i], data[ri] = data[ri], data[i]
	return data

@njit()
def test():
	gen = lcg()

	data = [i for i in range(5)]
	start_data = [list(mix(gen, data)) for i in range(9)]
	dynamic_data = list(start_data)
	count = 0
	while True:
		count += 1
		data = mix(gen, data)

		print('count', count)
		if count > 14:
			break

		dynamic_data.pop(0)
		dynamic_data.append(list(data))
		flag = True
		for i in range(len(start_data)-1, -1, -1):
			flag = flag and dynamic_data[i] == start_data[i] # <-- error, comparison [i] and [i-1] item
			if count == 12:
				print(dynamic_data[i] == start_data[i])
				print(i, dynamic_data[i])
				print(i, start_data[i])
			if not flag:
				break
		if flag:
			break

	return count

test()
```
The *mix* function mixes the elements in the block. After 12 cycles, the mixing is repeated and the *test* function shuts down. In the code ``dynamic_data[i] == start_data[i]`` the wrong element is randomly returned, which breaks the check.

When we run the same code every time, a miss when accessing the list occurs at different values of i. For example, when i is equal to 6 or 1, which is why the error is random.

Example with numba
```
count 1           
count 2           
count 3           
count 4           
count 5           
count 6           
count 7           
count 8           
count 9           
count 10          
count 11          
count 12          
True              
8 [3, 2, 0, 1, 4] 
8 [3, 2, 0, 1, 4] 
True              
7 [3, 1, 2, 4, 0] 
7 [3, 1, 2, 4, 0] 
False             
6 [3, 2, 0, 1, 4] 
6 [0, 3, 2, 1, 4] 
count 13          
count 14          
count 15                
```
Example without numba
```
count 1          
count 2          
count 3          
count 4          
count 5          
count 6          
count 7          
count 8          
count 9          
count 10         
count 11         
count 12         
True             
8 [3, 2, 0, 1, 4]
8 [3, 2, 0, 1, 4]
True             
7 [3, 1, 2, 4, 0]
7 [3, 1, 2, 4, 0]
True             
6 [0, 3, 2, 1, 4]
6 [0, 3, 2, 1, 4]
True             
5 [4, 0, 2, 1, 3]
5 [4, 0, 2, 1, 3]
True             
4 [4, 2, 3, 1, 0]
4 [4, 2, 3, 1, 0]
True             
3 [4, 1, 2, 0, 3]
3 [4, 1, 2, 0, 3]
True             
2 [3, 4, 2, 1, 0]
2 [3, 4, 2, 1, 0]
True             
1 [0, 3, 2, 1, 4]
1 [0, 3, 2, 1, 4]
True             
0 [0, 2, 4, 1, 3]
0 [0, 2, 4, 1, 3]
```
If you have an error during the check as shown below, then disable *cache=True* It seems numba compiles functions into different code every time, otherwise it is not clear why this error also happens by accident
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x00000124E4DB4940>.    
Failed in nopython mode pipeline (step: native lowering)                                 
int64 generator(func=<function lcg at 0x0000017B86B3E290>, args=(), has_finalizer=True)  
                                                                                         
File "num.py", line 17:                                                                  
def mix(gen, data):                                                                      
    <source elided>                                                                      
        for i in range(0, len(data)):                                                    
                ri = next(gen) # ri [0..4]                                               
  ^                                                                                      
  ...
```

**Comment by Vlod-github** [comment]
@esc, yes, it worked, thanks for responding so quickly. After the replacement, the performance dropped by ~40%, so I'll have to choose pypy. And still it seems strange to me that after importing numba, the behavior of standard python objects changes

**Comment by esc** [comment]
> @esc, yes, it worked, thanks for responding so quickly. After the replacement, the performance dropped by ~40%, so I'll have to choose pypy. And still it seems strange to me that after importing numba, the behavior of standard python objects changes

OK, feel free to close and thank you for following up.

**Comment by esc** [comment]
note: I suspect this is related to reflected list and using a nested reflected list. I actually received segfaults on this one for my machine. Given that the reflected is deprecated and subject to removal over the next few years, I don't think it will be worthwhile to invest any time into fixing this issue. Rather, time should be spent improving the performance of the `numba.typed.List` moving forward.

**Comment by Vlod-github** [comment]
Whether to maintain a reflected list is entirely your decision, but you can notify users that the standard python-list is not supported, I think it's better than people will get random bugs
