### ISSUE TITLE
Allow indexing with () for scalar arrays

### ISSUE THREAD

**Issue by shoyer** [numba/numba#843]
Currently, Numba requires indexing scalar arrays like `out[0]` in order to support scalar values in gufuncs:
https://github.com/numba/numba/blob/master/numba/tests/test_guvectorize_scalar.py

This is awkward because it means code written for numba will not run unmodified with numpy (the index 0 is actually out of bounds).

Instead, it would be nice to support valid syntax for numpy, e.g., the empty tuple `()` (to unbox an array), or `...` to index all values in an array (even if it's 0-dimensional).

Another option would be to automatically unbox/box scalar array input/output. I think I would like this option best, but I can imagine hypothetical (if unlikely) cases where that could yield inconsistent results, e.g., if the gufunc is not a pure function.

**Comment by pitrou** [comment]
PR #925 allows for indexing of 0-d arrays only. I'm not sure anything else is needed?
