### ISSUE TITLE
FakeCUDAModule has no attribute shfl_down_sync

### ISSUE THREAD

**Issue by sebastienwood** [numba/numba#8433]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi !
I'm trying to reproduce the code presented in this article using Numba: https://developer.nvidia.com/blog/faster-parallel-reductions-kepler/
In short, they use warp level intrinsics (`__shfl_down`) to perform reductions.
I am aware of the `Reduce` helper (https://github.com/numba/numba/blob/main/numba/cuda/kernels/reduction.py) but it does not seems to use this instruction at first glance / it is interesting to try and implement it by myself either way (except if I'm missing some concept I understood this function is the most performant for this task).
A first issue I found is that there is no `__shfl_down` in Numba, but rather `shfl_down_sync` to which I understand passing `cuda.activemask()` as first argument allows us to falls back to the original `__shfl_down`.

A second issue arise when I want to compile my kernel for regular use, it throws the error `numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE`
Here, I try to set the env. variable `NUMBA_ENABLE_CUDASIM` to True, but it then throws the following error:
`AttributeError: tid=[302, 0, 0] ctaid=[0, 0, 0]: 'FakeCUDAModule' object has no attribute 'shfl_down_sync'`

I managed to reproduce this error with the following snippet:

```
import os
os.environ['NUMBA_ENABLE_CUDASIM'] = '1'
import torch
from numba import cuda
bs = 8
ch = 3
who = 8
input = torch.rand(bs, ch, who, who, ch, who, who)
@cuda.jit
def shfl(val):
        offset = _WARPSIZE // 2
        while offset:
            val += cuda.shfl_down_sync(cuda.activemask(), val, offset)
            offset //= 2
        return val
shfl[1, 1024](input)
```

My Numba version is 0.56.2. Let me know if I can provide further details !

**Comment by guilhermeleobas** [comment]
Hi @sebastienwood, I tried to execute your code but a few variables are not defined. Nevertheless, I defined some random values for it in order to reproduce your error. Please, let me know if the following code is a valid reproducer:

```python
import torch
from numba import cuda
bs = 5
ch = 5
who = 5
input = torch.rand((bs, ch, who), device="cuda")

_WARPSIZE = 32

@cuda.jit
def shfl(val):
    offset = _WARPSIZE // 2
    while offset:
        val += cuda.shfl_down_sync(cuda.activemask(), val, offset)
        offset //= 2
    return val
shfl[1, 1024](cuda.as_cuda_array(input))
```

The code above fails with the following error
```
Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'numba.cuda.stubs.shfl_sync_intrinsic'>) found for signature:

 >>> shfl_sync_intrinsic(uint32, Literal[int](2), array(float32, 3d, C), int64, Literal[int](31))

There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Type Restricted Function in function 'shfl_sync_intrinsic': File: unknown: Line unknown.
      With argument(s): '(uint32, int64, array(float32, 3d, C), int64, int64)':
     No match for registered cases:
      * (int32, int32, int32, int32, int32) -> Tuple(int32, bool)
      * (int32, int32, int64, int32, int32) -> Tuple(int64, bool)
      * (int32, int32, float32, int32, int32) -> Tuple(float32, bool)
      * (int32, int32, float64, int32, int32) -> Tuple(float64, bool)

During: resolving callee type: Function(<class 'numba.cuda.stubs.shfl_sync_intrinsic'>)
During: typing of call at /home/guilhermel/git/numba/numba/cuda/intrinsic_wrapper.py (68)


File "numba/cuda/intrinsic_wrapper.py", line 68:
def shfl_down_sync(mask, value, delta):
    <source elided>
    """
    return numba.cuda.shfl_sync_intrinsic(mask, 2, value, delta, 0x1f)[0]
    ^

During: resolving callee type: type(CUDADispatcher(<function shfl_down_sync at 0x7f5c93ed3310>))
During: typing of call at /home/guilhermel/git/numba/a.py (14)


File "a.py", line 14:
def shfl(val):
    <source elided>
    while offset:
        val += cuda.shfl_down_sync(cuda.activemask(), val, offset)
```

The second argument to `cuda.shfl_down_sync` requires an integer or floating-point variable. But in your case, it is a torch tensor.

**Comment by sebastienwood** [comment]
Indeed, my bad for forgetting those ! (I'll edit the original MWE). Have you set NUMBA_ENABLE_CUDASIM to 1 on your side ? (I'll also add it at the beginning of the MWE)

**Comment by guilhermeleobas** [comment]
I can reproduce the error now. I had to set `_WARPSIZE = 32` to make the code compilable.

The function you're trying to execute is indeed not support in the CUDA simulator yet as per the [docs](https://numba.readthedocs.io/en/stable/cuda/simulator.html#supported-features) says:

```
Warps and warp-level operations are not yet implemented.
```

**Comment by sebastienwood** [comment]
Many thanks perfect ! :)

**Comment by stuartarchibald** [comment]
@gmarkall any thoughts on whether, under the CUDA simulator, unsupported CUDA API calls ought to raise `NotImplementedError` or perhaps `numba.errors.UnsupportedError` with some error message specific to the simulator? Example:
```python
from numba import cuda
import numpy as np


@cuda.jit
def foo(x):
    cuda.shfl_down_sync(cuda.activemask(), x, 2)


foo[1, 1](np.ones(4))
```
Currently gives:
```
$ NUMBA_ENABLE_CUDASIM=1 python issue8433.py 
...
issue8433.py", line 7, in foo
    cuda.shfl_down_sync(cuda.activemask(), x, 2)
AttributeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: 'FakeCUDAModule' object has no attribute 'shfl_down_sync'
```
