### ISSUE TITLE
Remove user name scraping from changelog generator

### ISSUE THREAD

**Issue by sklam** [numba/numba#8437]
Referring to https://github.com/numba/numba/pull/8429 and roughly this part https://github.com/numba/numba/pull/8429/files#diff-c07552e1b5f50e764b6bba45566846cd148aabdb103ba23bb82a993eeea38fcdR34-R37

To remove scraping of user profile information from Github and to only rely on user name in the git log.

**Comment by esc** [comment]
closing as #8450 has been merged!
