### ISSUE TITLE
Iterables of jitclasses?

### ISSUE THREAD

**Issue by penguinshin** [numba/numba#8445]
Is there a way to currently create an iterable of some kind that contains jitclasses? For example, what I would like to be able to do is this:
```

@jitclass
class NumbaObject:
    size: int32
    def __init__(self, size):
        self.size = size

    def do_something(self):
        self.size += 1

iterable = numba.typed.List([NumbaObject(1)])

@njit
def loop(iterable):
    for obj in iterable:
        obj.do_something()

```

Or an equivalent with numba.typed.Dictionary...

Basically, I'd like to be able to have iterables of numba objects that can have state beyond the usual primitives (ndarray)

**Comment by esc** [comment]
@penguinshin thank you for asking about this. Ideally, the Numba issue tracker should contain only bug-reports and identified issues regarding Numba. Usually, questions around "what is the best way to..." or "how do I ..... with Numba" are best asked on our Discourse forum https://numba.discourse.group/.

I did try your example above, and modified it as follows:

```python
from numba import njit, int32, typed
from numba.experimental import jitclass

@jitclass
class NumbaObject:
    size: int32
    def __init__(self, size):
        self.size = size

    def do_something(self):
        self.size += 1
        print(self.size)

i = typed.List([NumbaObject(1)])

@njit
def loop(iterable):
    for obj in iterable:
        obj.do_something()


loop(i)
loop(i)
loop(i)

```

It seems to compile fine and work. Did you experience any issues?

Jitclass can be somewhat "unforgiving" sometimes, we regularly receive bug-reports related to it. A less complex alternative may be a `StructRef`, you can read about it here:

https://numba.pydata.org/numba-doc/dev/extending/high-level.html#implementing-mutable-structures

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Thanks!
