### ISSUE TITLE
Compiler name mangler does not ensure unique names in py2

### ISSUE THREAD

**Issue by meawoppl** [numba/numba#845]
Compiled functions that:
* have the same name
* are in the same module

will fail to compile in python 2.6 and 2.7.  

Name mangling logic based on ```__name__``` vs ```__qualname__``` (available in >=3.3 only)
will cause a name-collision and eventually assertion error [here](https://github.com/numba/numba/blob/master/numba/targets/cpu.py#L106).

This will cause to compiler to fail lowering to nopython and provide a confusing line-number reference pointing to the original function compiled.  

Relevent code in compiler is found [here](https://github.com/numba/numba/blob/c34d1e3f4ae59c8f13c3d3a5cd18795a2dc25b2e/numba/bytecode.py#L322) and [here](https://github.com/numba/numba/blob/master/numba/lowering.py#L55).

**Comment by pitrou** [comment]
This should have been fixed by changeset 7b11a70436e5b8a16570672767bafd39cb1f5cd1.
