### ISSUE TITLE
Documentation doesn't explain how to run tests

### ISSUE THREAD

**Issue by yurivict** [numba/numba#8452]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The [installing section](https://numba.readthedocs.io/en/stable/user/installing.html) in the docs doesn't explain how to run tests.

I guessed that the script might be ```runtests.py```. But it doesn't print progress info, unlike pytest does.

Documentation should have the command that runs tests.

**Comment by stuartarchibald** [comment]
Thanks for the report. How to run tests is extensively documented in the developer/contributing part of the docs:
https://github.com/numba/numba/blob/60723cb5a31d0b6ef516af95602a463322991420/docs/source/developer/contributing.rst?plain=1#L153-L211

I think a small addition to the installation docs explaining "this is how to test your installation" would be a good idea. A link to the developer docs for more advanced testing commands could also be included.

> I guessed that the script might be runtests.py. But it doesn't print progress info, unlike pytest does.

This script can be used from a local checkout. It prints a literal `.` for each test that ran, or with the `-v` flag it shows the test names as they run, but does not show e.g. "M out of N" tests have run. The testing framework is based on `unittest` and inherits a lot of the default behaviours from there.
