### ISSUE TITLE
pythonapi function for PyBytes_AsStringAndSize?

### ISSUE THREAD

**Issue by jpivarski** [numba/numba#8455]
It looks like [pythonapi.py](https://github.com/numba/numba/blob/main/numba/core/pythonapi.py) doesn't have a function for [PyBytes_AsStringAndSize](https://docs.python.org/3/c-api/bytes.html#c.PyBytes_AsStringAndSize) (or `PyBytes_AsString` or `PyBytes_Size`, for that matter).

We could implement it manually, following an example like

https://github.com/numba/numba/blob/60723cb5a31d0b6ef516af95602a463322991420/numba/core/pythonapi.py#L470-L475

But are there any plans to fill out this part of the `PythonAPI` class with these methods?

Thanks!

Cc: @ianna

**Comment by apmasell** [comment]
No plans, but I know some of these were driven by requests, so I'll check if there's any reason we didn't.

**Comment by ianna** [comment]
I'd be happy to create a PR for it. Thanks!

**Comment by stuartarchibald** [comment]
Closing as implemented in #8462 with thanks to @ianna!
