### ISSUE TITLE
OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by laleye** [numba/numba#8460]
Whatever version 0.47 to 0.56 is installed, I get the following error. 

```
OSError: Could not load shared object file: libllvmlite.so
Errors were: [OSError('python3.7/site-packages/llvmlite/binding/libllvmlite.so: 
undefined symbol: _ZN4llvm16JITEventListener27createIntelJITEventListenerEv, version LLVM_11'),
 OSError('libllvmlite.so: cannot open shared object file: No such file or directory'), 
OSError('./libllvmlite.so: cannot open shared object file: No such file or directory'), 
OSError('python3.7/site-packages/llvmlite/binding/libllvmlite.so: 
undefined symbol: _ZN4llvm16JITEventListener27createIntelJITEventListenerEv, version LLVM_11')]
```

Maybe someone has encountered this problem and has a solution for me. Thanks

**Comment by apmasell** [comment]
How did you install them and what OS are you using?

**Comment by laleye** [comment]
@apmasell  I installed it on Linox OS (Kde neon) with this command: `conda install conda`

**Comment by apmasell** [comment]
Okay. It looks like something is mixing the system LLVM with the one in the Conda environment. Numba only supports LLVM 10, so it shouldn't be loading LLVM 11.

Could you try doing `ldd lib/python3.7/site-packages/llvmlite/binding/libllvmlite.so` in your conda environment?

I suspect the easiest fix will be to delete the conda environment and create a new one.

**Comment by esc** [comment]
> I suspect the easiest fix will be to delete the conda environment and create a new one.

I would also recommend trying to setup a new environment.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
