### ISSUE TITLE
ImportError: Numba requires at least version 0.40.0 of llvmlite.

### ISSUE THREAD

**Issue by dbl001** [numba/numba#8481]
ImportError: Numba requires at least version 0.40.0 of llvmlite.
Installed version is 0.39.1.
Please update llvmlite.

The latest version of llvmlit is: 0.39.1

% pip show numba      
Name: numba
Version: 0.57.0.dev0+540.g061f21a73.dirty
Summary: compiling Python code using LLVM
Home-page: https://numba.pydata.org
Author: 
Author-email: 
License: BSD
Location: /Users/davidlaxer/tensorflow/lib/python3.8/site-packages/numba-0.57.0.dev0+540.g061f21a73.dirty-py3.8-macosx-10.9-x86_64.egg
Requires: importlib_metadata, llvmlite, numpy, setuptools
Required-by: datashader, pynndescent, umap-learn
(tensorflow) davidlaxer@x86_64-apple-darwin13 numba % pip show llvmlite
Name: llvmlite
Version: 0.39.1
Summary: lightweight wrapper around basic LLVM functionality
Home-page: http://llvmlite.readthedocs.io
Author: 
Author-email: 
License: BSD
Location: /Users/davidlaxer/tensorflow/lib/python3.8/site-packages
Requires: 
Required-by: numba, pynndescent

**Comment by gmarkall** [comment]
You appear to be running a dev version of Numba, so you will also need to install llvmlite from source (as I think you are using pip - if you're using conda, you can install an llvmlite nightly with `conda install -c numba llvmlite`).

**Comment by dbl001** [comment]
Ok, thanks.  Will Numba ever support Metal Performance Shader ('MPS')

**Comment by stuartarchibald** [comment]
> Ok, thanks. Will Numba ever support Metal Performance Shader ('MPS')

@dbl001 please see the discussion in #5706. Thanks.

Am going to close this as resolved. Many thanks.
