### ISSUE TITLE
I want to get Numba IR detail of the function in other libraries

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [numba/numba#8516]
Hi!
I want to translate my python3 code into LLVM IR, I find out from the official document that I should translate it into Numba IR, then translate it into LLVM IR by llvmlite.
Like the code in the red box below, I succeeded to translate it into Numba IR，but when I try to Call functions in other libraries like np.array, Numba can't give me the detail of this function.
![image](https://user-images.githubusercontent.com/82520400/196039208-82820586-4c5a-4b07-88ef-ce00731653f3.png)
I have already ask about this function in the [Numba room](https://gitter.im/numba/numba?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications) and nobody anwser me, and I can't find it in the official document, so I have to ask this question here. If Numba has already finish this function, please accept my apology and tell me where can I find it, if you can't do that for a while, pleace tell me where I can find this kind of function, I will be very greatful too

**Comment by guilhermeleobas** [comment]
Hi @Lost-little-dinosaur

> Hi! I want to translate my python3 code into LLVM IR, I find out from the official document that I should translate it into Numba IR, then translate it into LLVM IR by llvmlite. Like the code in the red box below, I succeeded to translate it into Numba IR，but when I try to Call functions in other libraries like np.array, Numba can't give me the detail of this function. ![image](https://user-images.githubusercontent.com/82520400/196039208-82820586-4c5a-4b07-88ef-ce00731653f3.png)

The output you're seeing in the image is not NUMBA or LLVM IR, but the [python bytecode](https://docs.python.org/3/library/dis.html). To use Numba, you must annotate the function with the `@jit` decorator. Take a look at the [introduction guide](https://numba.pydata.org/numba-doc/dev/user/5minguide.html) that describe how to get and use Numba.

Once you have installed Numba, you can get the LLVM IR by defining the NUMBA_DUMP_OPTIMIZED=1` flag. Or programatically:

```python
from numba import njit

@njit
def test1(a, b):
    return a + b

# first call test1
test1(2, 3)

# get the llvm ir:
print(test1.inspect_llvm(test1.signatures[0]))
```

To better answer your question, are you looking for something specific in Numba?

**Comment by Lost-little-dinosaur** [comment]
Oh, thank you, that is really helpful.
Yeah, I want to translate my python3 code into LLVM IR, I first try llvmlite and it didn't work, then one kind man told me to try Numba, so here I am.
Anyway, thank you for your help.

**Comment by Lost-little-dinosaur** [comment]
I come back again......
I recive this error when I try to translate my python3 code into LLVM IR
![image](https://user-images.githubusercontent.com/82520400/196100081-6be1896c-dec1-4ca3-8eda-5d616571cf56.png)
(I have already try to run @jit in object mode.
I search on Google and official document, I found that Numba do a really good job on accelerating the computation, but also many python code such as lambda can't translate it into LLVM IR.
I only want to translate my python3 code into LLVM IR so that I can draw a CFG gragh for my python project. So I wonder whether there a tool can translate py3 code whether what the code looks like. If you have one, pleace tell me.

**Comment by guilhermeleobas** [comment]
Hi @Lost-little-dinosaur, not all Python code is supported in Numba. See [this](https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-doesn-t-compile) section in the docs.

>  ![image](https://user-images.githubusercontent.com/82520400/196100081-6be1896c-dec1-4ca3-8eda-5d616571cf56.png) 

For the code you're displaying in this image, Numba will not be able to produce an LLVM IR.

**Comment by Lost-little-dinosaur** [comment]
OK, thank you for your reply
