### ISSUE TITLE
Cannot overwrite the __str__ method in jitclass

### ISSUE THREAD

**Issue by pietrodantuono** [numba/numba#8531]
Hello,

I am not able to overwrite the string representation of a jitclass. I do not know if this is a wanted behaviour though.

```python
from numba.experimental import jitclass
from numba import float64

spec = [("alpha", float64)]


@jitclass(spec)
class Foo:
    def __init__(self, alpha):
        self.alpha = alpha
    
    def __str__(self):
        return "Class Foo"


foo = Foo(1.)

print(str(foo))
```

Produces:
```bash
<numba.experimental.jitclass.boxing.Foo object at 0xS0M3wh3r3>
```

Expected:
```bash
Class Foo
```

It seems that the `__str__()` method is skipped entirely, in fact the following does not produce any `ZeroDivisionError`.

```python
...
    def __str__(self):
        return 0 ** (-2)

``` 

Tested on:
```bash
Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python version: 3.9.7 (default, Sep 20 2022, 16:21:01) 
[GCC 11.2.0]

Numba version: 0.55.2
```

**Comment by pietrodantuono** [comment]
Thank you @stuartarchibald! After updating to 0.56.3, the `__str__` method works!

My bad, I did not notice it from the Release notes

> Numba specific feature enhancements:
> 
> The experimental `jitclass` feature gains support for a large number of `builtin` methods e.g. declaring `__hash__` or `__getitem__` for a `jitclass` type.

(https://numba.readthedocs.io/en/stable/release-notes.html#version-0-56-0-25-july-2022)

Next question: what about `__repr__`? Any possibility for it to be implemented in a future release?
It'd be really nice to have it for usage within Jupyter Notebook.

**Comment by stuartarchibald** [comment]
> Thank you @stuartarchibald! After updating to 0.56.3, the `__str__` method works!
> 
> My bad, I did not notice it from the Release notes

No problem, glad it is working now.

> Next question: what about `__repr__`? Any possibility for it to be implemented in a future release? It'd be really nice to have it for usage within Jupyter Notebook.

I suggest opening a feature request if it is important to you. I think it's technically possible to support it.

**Comment by pietrodantuono** [comment]
Done!

Ref. #8533

**Comment by stuartarchibald** [comment]
> Done!
> 
> Ref. #8533

Great, many thanks. I'll close this issue as resolved.
