### ISSUE TITLE
Numba's `np.broadcast_to` doesn't change the size of the array

### ISSUE THREAD

**Issue by kc611** [numba/numba#8534]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

As titled, Numba's `np.broadcast_to` doesn't update the size of an array after broadcasting it. 

MWE as follows:

```python
import numpy as np
import numba

@numba.njit     
def bdcast(array):
    bdcast_array = np.broadcast_to(array, (2, 3))
    return bdcast_array.size

array = np.array([1,2,0])

expected = bdcast.py_func(array)
got = bdcast(array)

# Initial size of array
print(array.size) # 3

# Expected size after broadcast
print(expected) # 6
# Returned size after broadcast
print(got) # 3

np.testing.assert_equal(got, expected)

```

**Comment by stuartarchibald** [comment]
Thanks for the report. Seems like `size` attr is incorrect in the compiled code:
```python
from numba import njit
import numpy as np

@njit
def foo(arr):
    ret = np.broadcast_to(arr, (2, 3))
    return ret, ret.size, ret.shape

arr = np.arange(3)

def dump(where, x, sz, shp):
    print(where)
    print(x)
    print(x.size)
    print(x.shape)
    print(sz)
    print(shp)
    print("")

dump("pyfunc", *foo.py_func(arr))
dump("numba ", *foo(arr))
```
gives:
```
pyfunc
[[0 1 2]
 [0 1 2]]
6
(2, 3)
6
(2, 3)

numba 
[[0 1 2]
 [0 1 2]]
6
(2, 3)
3
(2, 3)
```
the returned array seems correct, it's the `.size` attr in the compiled region that's incorrect.
