### ISSUE TITLE
workqueue threading layer "safety" mechanism aliases nesting and concurrent access

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8563]
The `workqueue` threading layer itself is not thread safe. There is a weak guard in the implementing code to prevent concurrent access by multiple threads which essentially checks the value of a global in the DSO to make sure that it has value `<=1` i.e. not set or one thread accessing the library, and raises `SIGABRT` for safety to prevent corruption if this condition is violated.
https://github.com/numba/numba/blob/bdb238410946f5ef26c83629f36b5ec3cc6cf336/numba/np/ufunc/workqueue.c#L377-L384

This was put in place largely to handle the use case of "nested parallelism" where the threads of the threading layer itself would concurrently access the threading layer to launch their own thread pools etc, e.g.
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def bar(x):
    acc = 0
    n = len(x)
    for i in prange(n):
        acc += i
    return acc / n

@njit(parallel=True)
def foo(x):
    xcp = x.copy()
    for i in prange(len(x)):
        # parallel region calling parallel function... therefore nested!
        x[i] = bar(xcp)

n = 100000
tmp = np.ones(n)
foo(tmp)
```
Text on `stdout`:
```
Terminating: Nested parallel kernel launch detected, the workqueue threading layer does not supported nested parallelism. Try the TBB threading layer.
Aborted
```
However, a similar condition can be achieved through concurrent access at the Python level which results in the same message. e.g.
```python
from threading import Thread
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def foo(x):
    for i in prange(len(x)):
        x[i] = np.cos(x[i]) * np.cos(x[i]) + np.sin(x[i]) * np.sin(x[i])

n = 100000
tmp = np.ones(n)
foo(tmp)

nthreads = 5
threads = []
for i in range(nthreads):
    threads.append(Thread(target=foo, name=f"thread-{i}", args=(tmp,)))

for t in threads:
    t.start()
for t in threads:
    t.join()
```
It would be a good idea to update this error message to note that the issue is concurrent access in general, of which one example is nested parallelism as the case is not unique to nesting.

**Comment by gmarkall** [comment]
Related Discourse post: https://numba.discourse.group/t/terminating-nested-parallel-kernel-launch-detected-the-workqueue-threading-layer-does-not-supported-nested-parallelism/1621/4
