### ISSUE TITLE
Make Numba's `captured_errors="new_style"` by default.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8564]
Following on from discussion at today's public Numba meeting (01 November, 2022). @guilhermeleobas suggested that it would be good to make Numba's "error capturing" use the "new style" by default, there was general agreement that this would be a good idea. The "new style" error capturing was implemented in Numba 0.55 via #7397 and has been used in Numba's CI systems ever since. The implications of the `captured_errors` style are discussed in the text accompanying #7397. Steps to make this change:

1. Issue deprecation warnings and create a deprecation cycle in relation to the use of the `old_style` error capturing behaviour.
2. Schedule removal and remove the `old_style` error capturing behaviour once the deprecation period ends.

**Comment by esc** [comment]
Closing as #9090 has been merged

**Comment by Seairth** [comment]
See my comment at https://github.com/numba/numba/issues/9091#issuecomment-1693344159.  It appears that deprecation notices have been added, but the default in config.py has _not_ been updated to be `new_style`.
