### ISSUE TITLE
The 0.56.3 release broke poetry dependency resolution

### ISSUE THREAD

**Issue by fulii** [numba/numba#8568]
Hi!

After the 0.56.3 release poetry no longer resolves correct depndencies for numba package.
`python --version`:  Python 3.8.13
`poetry --version`: Poetry (version 1.2.2)

`poetry show numba` command output with numba pinned to `0.56.2`:
```
 name         : numba
 version      : 0.56.2
 description  : compiling Python code using LLVM

dependencies
 - importlib_metadata *
 - llvmlite >=0.39.0dev0,<0.40
 - numpy >=1.18,<1.24
 - setuptools <60

required by
 - shap *
```

`poetry show numba` command output with no version constraint:
```
 name         : numba
 version      : 0.56.3
 description  : compiling Python code using LLVM

required by
 - shap *
```

**Comment by fulii** [comment]
Hi!
Thanks for the suggestion.

After running the `poetry lock --no-cache` command, numba dependencies showing correctly.
```
 name         : numba
 version      : 0.56.3
 description  : compiling Python code using LLVM

dependencies
 - importlib-metadata *
 - llvmlite >=0.39.0dev0,<0.40
 - numpy >=1.18,<1.24
 - setuptools *

required by
 - shap *
```

However, I could not find anything in the open or closed issues which has this exact resolution.

**Comment by esc** [comment]
> However, I could not find anything in the open or closed issues which has this exact resolution.

I think it was this one, perhaps: https://github.com/numba/numba/issues/8278#issuecomment-1198104331

**Comment by esc** [comment]
@fulii thank you for following up and closing!
