### ISSUE TITLE
1d array, column of fortran array, with F and C contiguity, raises error for not being C-contiguous.

### ISSUE THREAD

**Issue by javierttgg** [numba/numba#8576]
Thank you for this great and useful library :)

I have noticed that functions like the following `foo` do not compile:

```python
from numba import njit
import numpy as np


@njit('f8[::1](f8[::1])')
def foo2(b):
    return b

@njit('f8[::1](f8[::1,:])')
def foo(a):
    return foo2(a[:, 0])
```

The following error is raised:

```python
TypingError: Invalid use of type(CPUDispatcher(<function foo2 at 0x000001759D4C7550>)) with parameters (array(float64, 1d, F))
Known signatures:
 * (array(float64, 1d, C),) -> array(float64, 1d, C)
During: resolving callee type: type(CPUDispatcher(<function foo2 at 0x000001759D4C7550>))
```

It indicates that the input argument given to function `foo2` is not C-contiguous.

However, by checking the flags of fortran-arrays columns, we can see that they present both contiguities,  e.g.:

```python
arr = np.array([[1.0, 2.0], [3.0, 4.0]], order='F')
print(f'{arr[:, 0].flags}\n{arr[:, 1].flags}')
```
```shell
C_CONTIGUOUS : True
F_CONTIGUOUS : True
OWNDATA : False
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
UPDATEIFCOPY : False

C_CONTIGUOUS : True
F_CONTIGUOUS : True
OWNDATA : False
WRITEABLE : True
ALIGNED : True
WRITEBACKIFCOPY : False
UPDATEIFCOPY : False
```

I think this is related to #5967. There a similiar problem appeared when using empty arrays with F-order.

**Numba version**: 0.56.3 (latest as of today).

**Comment by gmarkall** [comment]
Thanks for the report - I can reproduce the behavior you've described.

**Comment by stuartarchibald** [comment]
Within the current Numba type system, I think that this is expected behaviour. The function `foo2` is called with `a[:, 0]`, where `a` is type `array(float64, 2d, F)` and the type of the slice `a[:, 0]` is `array(float64, 1d, F)`. As `foo2` is compiled for an  `f8[::1]` argument, i.e. type `array(float64, 1d, C)`, there is no version of this function available for the presented argument.

As discussed in the noted #5967, in Numba's type system there is no `CF` type and `C`/`F` ordering are considered mutually exclusive. This is a limitation of the current system. There is the `'A'` ordering which is "accept either C or F" but this can lead to less optimal code generation because there is less information available about data layouts/access patterns.

**Comment by javierttgg** [comment]
Got it, thank you for the prompt replies! 

So, at the moment, in Numba we can not define a signature for F-order-1d arrays as input arguments? I think that kind of signature in `foo2` would solve this issue, but I'm not sure if that's possible after reading the docs.

**Comment by stuartarchibald** [comment]
> Got it, thank you for the prompt replies!

No problem.

I don't think you can define it using the `__getitem__` syntax on the types, but the "full" spelling should work, e.g.
```python
from numba import njit
import numpy as np

@njit('Array(f8, 1, "F")(Array(f8, 1, "F"))')
def foo2(b):
    return b

@njit('Array(f8, 1, "F")(f8[::1, :])')
def foo(a):
    return foo2(a[:, 0])
```
another option is to "spell" types using the `numba.types` themselves opposed to strings, e.g.
```python
from numba import njit, types
import numpy as np

array1d_f = types.Array(types.float64, 1, "F")

@njit(array1d_f(array1d_f))
def foo2(b):
    return b

@njit(array1d_f(types.Array(types.float64, 2, "F")))
def foo(a):
    tmp = a[:, 0]
    return foo2(tmp)
```
Hope this helps?

**Comment by javierttgg** [comment]
That's really helpful, thanks again!, and my bad for not realising that I could have used that kind of type signature.

**Comment by stuartarchibald** [comment]
> That's really helpful, thanks again!, and my bad for not realising that I could have used that kind of type signature.

No problem. Typically signatures are not needed as type inference just "works it out", but those options above present the methods of describing just about anything within the type system if needed.
