### ISSUE TITLE
Deal with masked array

### ISSUE THREAD

**Issue by zxdawn** [numba/numba#8589]
## Reporting a bug

When the array is a masked array, the arithmetic operation is different from that calculated by numpy.

```
from numba import jit
import numpy.ma as ma

@jit(nopython=True)
def calc_numba(data):
    return data.sum()

def calc_numpy(data):
    return data.sum()

data = ma.masked_array(np.array([1, 2e10]), mask=[0, 1])
print(calc_numba(data), calc_numpy(data))
```

Result: 20000000001.0 1.0

## Question

Is it possible to get `1.0` like numpy? Note that masked values can be multiple different values.

**Comment by apmasell** [comment]
Numba doesn't support masked arrays at this time. See #1834
