### ISSUE TITLE
getitem(array(float64, 2d, C), UniTuple(array(int64, 1d, C) x 2))

### ISSUE THREAD

**Issue by GitMew** [numba/numba#8607]
I'm quite new to `numba`. I would have thought the following basic `numpy` code would compile, yet it results in `No implementation of function Function(<built-in function getitem>) found`.

```
@numba.njit
def length(graph=np.array([[]]), path=np.array([])):
    return np.sum(graph[path, np.roll(path, -1)])
```

The goal of the function is to calculate the weight of a cyclic path in a weighted, directed graph (whose weights are given by an N x N matrix) given a permutation of the vertices 0 to N - 1.

The expanded error reads:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array(float64, 2d, C), UniTuple(array(int64, 1d, C) x 2))
 
There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(float64, 2d, C), UniTuple(array(int64, 1d, C) x 2))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 166.
    With argument(s): '(array(float64, 2d, C), UniTuple(array(int64, 1d, C) x 2))':
   Rejected as the implementation raised a specific error:
     NumbaNotImplementedError: only one advanced index supported
  raised from C:\Users\Mew\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\typing\arraydecl.py:69

During: typing of intrinsic-call at ...
```

**Comment by GitMew** [comment]
@ogauthe I don't quite understand. Do you mean: 
1. `numba` can't index an array of floats (because indexing in batch requires an array of ints, which aren't floats), or
2. that my index array is heterogeneous?
(1) is hard to believe, and (2) is clearly wrong (the index array consists of integers).

**Comment by ogauthe** [comment]
Sorry I was wrong. The error here is the type of your index, mot a problem of tuple.

**Comment by sklam** [comment]
Thank you for reporting the issue.

This is an unsupported feature as described by the error message:

```
     NumbaNotImplementedError: only one advanced index supported
```

Numba do not support all of numpy's fancy indexing. In this case, Numba does not know how to index an array with two array as indices. For instance, `graph[array1, array2]` is not supported, but `graph[array1]` is ok.

**Comment by stuartarchibald** [comment]
Something like this might work as a workaround (the `np.sum` can be applied to `return ret` if desired):
```python
from numba import njit
import numpy as np

@njit
def foo(graph, path):
    ret =  np.zeros_like(path, dtype=graph.dtype)
    for idx, (x, y) in enumerate(zip(path, np.roll(path, -1))):
        ret[idx] = graph[x, y]
    return ret

print(foo(np.arange(20).reshape((4, 5)), np.array([1, 3])))
```

**Comment by kc611** [comment]
Support for multiple array indices in `getitem` for arrays is now being tracked at https://github.com/numba/numba/issues/8616. 

Hence we can close this particular issue as a duplicate.
