### ISSUE TITLE
numba for pytorch Tensor for multiple gpus

### ISSUE THREAD

**Issue by xuxy09** [numba/numba#8612]
## Reporting a bug

- [yes] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [yes] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I want to use numba for pytorch Tensors. I have two gpus. The following code works Okay for device-0 but not for device-1.
When I run the following code, I get an error similar to [issue #4092](https://github.com/numba/numba/issues/4092)

``` python
from numba import cuda
import torch

@cuda.jit
def addone(out):
    idx = cuda.grid(1)
    out[idx] = out[idx] + 1

a = torch.zeros(10).cuda(1)
addone[1, 10](cuda.as_cuda_array(a.data))
print(a)
```

The error is: 
```
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuPointerGetAttribute results in CUDA_ERROR_INVALID_VALUE
```

I am using numba=0.53.1. I can solve the error by "cuda.select_device(1)", however I assume this is not the ideal way.

**Comment by sklam** [comment]
@xuxy09, to help us diagnosis the problem, can you paste the output from running `numba -s` from the terminal?
