### ISSUE TITLE
Investigate/discuss setuptools build and runtime dependency versions.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8617]
xref: https://github.com/numba/numba/pull/8475#issuecomment-1324089177, with thanks to @mbargull for raising this.

Seems like `setuptools=65.6.0` has broken `numpy.distutils` (same way as last time #8355), the NumPy tracking issue is here https://github.com/numpy/numpy/issues/22623. 

NumPy folks have pinned to `setuptools=59.2` https://github.com/numpy/numpy/issues/22623#issuecomment-1320890687 and are not supporting 60+ https://github.com/numpy/numpy/issues/22623#issuecomment-1321012633.

I think that #8544 removes all most all of Numba's reliance on `numpy.distutils` which is the part that keeps on being broken. Only the to-be-deprecated-in-0.57 `pycc` module has reference to `numpy.distutils` still.

Further xref: #8476 which needs work but makes `setuptools` optional at runtime.

**Comment by mbargull** [comment]
Ah, I didn't realize gh-8544 replaced `numpy.distutils.misc_util.get_info('npymath')` with `numpy.get_include()` (plus the accompanying changes). Yes, that'd probably take care of the build-time dependencies, thanks!

**Comment by stuartarchibald** [comment]
> Ah, I didn't realize [gh-8544](https://github.com/numba/numba/pull/8544) replaced `numpy.distutils.misc_util.get_info('npymath')` with `numpy.get_include()` (plus the accompanying changes). Yes, that'd probably take care of the build-time dependencies, thanks!

@mbargull No worries, raising this is really helpful, esp. the part about NumPy's policy, thanks again for that! The original intention of #8544 was to remove use of `npymath.a` and to fix up some ufunc loops, but having done this I realised the side effect was being able to largely drop use of `numpy.distutils` etc. As noted, hopefully this will prevent related future build-time issues!

**Comment by stuartarchibald** [comment]
#8544 drops `numpy.distutils` as noted previously, then #8476 and #8842 make `setuptools` optional at runtime. Closing as fixed!
