### ISSUE TITLE
`getitem` access with `str` value to a struct array causes impl "no match"

### ISSUE THREAD

**Issue by goodboy** [numba/numba#8622]
Hopefully this isn't a case of doing something obviously naive but, more or less the issue is that this compile error is the result of passing in a `str` argument (to an `@njit`-ed `@staticmethod`) to read a (`numpy`) struct-array via field name:
```python
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(Record(time[type=float64;offset=0],open[type=float64;offset=8],high[type=float64;offset=16],low[type=float64;offset=24],close[type=float64;offset=32],volume[type=float64;offset=40],bar_wap[type=float64;offset=48];56;False), unicode_type)

There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(Record(time[type=float64;offset=0],open[type=float64;offset=8],high[type=float64;offset=16],low[type=float64;offset=24],close[type=float64;offset=32],volume[type=float64;offset=40],bar_wap[type=float64;offset=48];56;False), unicode_type)':
   No match.

During: typing of intrinsic-call at /home/goodboy/repos/piker/piker/data/_pathops.py (562)

File "piker/data/_pathops.py", line 562:
    def path_arrays_from_ohlc(
        <source elided>
            close = q['close']
            index = float64(q[index_field])
            ^
```
---
Yes, i'm on ` 0.56.4`.

---

source code function which triggers this is here:
https://github.com/pikers/piker/blob/8ee964451b085dfb957160465018f4d4bd8ab696/piker/data/_pathops.py#L526

More  or less it seems that there is an issue with the type signature matching of the input struct-array both in terms of inferred (unspecified in `numba` terms) type sig as well as a manual spec.

For eg. I've tried something like

```python
    @staticmethod
    @njit(
        # TODO: need to construct this manually for readonly
        # arrays, see https://github.com/numba/numba/issues/4511
        (
            types.Array(
                numba_ohlc_dtype,
                1,
                'C',
                readonly=True,
            ),
            int64,
            types.unicode_type,
            optional(float64),
        ),
        nogil=True
    )
    def path_arrays_from_ohlc(
        data: np.ndarray,
        start: int64,
        index_field: str,
        bar_gap: float64 = 0.43,

    ) -> tuple[
        np.ndarray,
        np.ndarray,
        np.ndarray,
    ]:
```
And still get the same error.

---
Likely related issues include:
- https://github.com/numba/numba/issues/5756
- https://github.com/numba/numba/issues/5753
- https://github.com/numba/numba/issues/4098
- https://github.com/numba/numba/issues/4511 (`data`  is this.)

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this potentially demonstrates what it is you are seeing:
```python
from numba import njit
import numpy as np

dt = np.dtype([('field_a', np.float32), ('field_b', np.int8)])

@njit
def foo(record, field):
    x = record[field] # What type is x ?
    return x

arr = np.ones(1, dt)

print(foo(arr, 'field_a'))
```
the issue is essentially that Numba sees the type of `field` as a `types.unicode_type`, it doesn't know at compile time to which field in the `dt` `dtype` this corresponds. As a result it cannot work out a return type of the `getitem` call which manifests as a typing error similar to that in the OP.

The following case does work because the types can be resolved at compile time through the use of a compile-time-constant string that addresses the field:
```python
from numba import njit
import numpy as np

dt = np.dtype([('field_a', np.float32), ('field_b', np.int8)])

@njit
def foo(record):
    # access 'field_a' with a compile time constant string...
    # the type of x is known to be the type of that specific field
    x = record['field_a']
    return x

arr = np.ones(1, dt)

print(foo(arr))
```

**Comment by goodboy** [comment]
> The following case does work because the types can be resolved at compile time through the use of a compile-time-constant string that addresses the field:

Yes, exactly this is the way the code was originally written and worked; the change was to allow specifying the "index" field by variable input. More specifically in our case to use an epoch `'time'` field for time series slicing.

Is there any way to work around this using the variable `field` input or does it just have to be hardcoded for now?

**Comment by stuartarchibald** [comment]
It might be possible to use `numba.literally` to force dispatch on the literal value. Example:
```python
from numba import njit, literally
import numpy as np

dt = np.dtype([('field_a', np.float32), ('field_b', np.int8)])

@njit
def foo(record, field):
    literal_field = literally(field)
    x = record[1, 1][literal_field]
    return x


arr = np.ones((3, 2), dt)

print(foo(arr, 'field_a'))
```
this will however cause specialisations to be created for every variation of `field` passed to this function.

NOTE: In the example https://github.com/numba/numba/issues/8622#issuecomment-1327442963, I think the use of a 0d array is also causing some problems in type inference for `getitem` using a field, this is a separate issue however to the more general "will not specialise on non-constant fields".

**Comment by goodboy** [comment]
> this will however cause specialisations to be created for every variation of field passed to this function.

In our case this isn't a problem since the field should normally only be set once globally at program boot, the idea being that the user is either choosing time based or array based indexing.

**Comment by goodboy** [comment]
```python
   class OHLCBarsFmtr(IncrementalFormatter):
  File "/home/goodboy/repos/piker/piker/data/_pathops.py", line 538, in OHLCBarsFmtr
    def path_arrays_from_ohlc(
  File "/home/goodboy/.virtualenvs/piker310/lib/python3.10/site-packages/numba/core/decorators.py", line 219, in wrapper
    disp.compile(sig)
  File "/home/goodboy/.virtualenvs/piker310/lib/python3.10/site-packages/numba/core/dispatcher.py", line 970, in compile
    raise e.bind_fold_arguments(folded)
numba.core.errors.ForceLiteralArg: Pseudo-exception to force literal arguments in the dispatcher

File "piker/data/_pathops.py", line 564:
    def path_arrays_from_ohlc(
        <source elided>

        lit_index_field = literally(index_field)
        ^
```
😿

**Comment by stuartarchibald** [comment]
`ForceLiteralArg` is a pseudo-exception to try and make the compilation stack unwind so as to allow re-dispatch of the computation with literal values. If it's not working, the cause of the problem potentially not this exception.

**Comment by goodboy** [comment]
>  If it's not working, the cause of the problem potentially not this exception.

So *pseudo-exception* means I can somehow avoid this error raising?

> If it's not working, the cause of the problem potentially not this exception.

Well this **is** raising, so I don't know if that counts as *not working*?

What do you recommend?

**Comment by goodboy** [comment]
Also on a related note, I've seen this same error raised for different "styled" getitem access (though in the same routine in the client project) where the literal field `str`s **are provided directly** and the read is using so called [accessing multiple fields](https://numpy.org/doc/stable/user/basics.rec.html#accessing-multiple-fields) style from ``numpy``:

Note, this is from the same context of the original [linked code](https://github.com/pikers/piker/blob/8ee964451b085dfb957160465018f4d4bd8ab696/piker/data/_pathops.py#L526):
```python
    for i, q in enumerate(data[start:], start):

        # open = q['open']
        # high = q['high']
        # low = q['low']
        # close = q['close']
        # index = float64(q['index'])

        # XXX: ``numba`` issue: https://github.com/numba/numba/issues/8622
        # index = float64(q[index_field])
        
         # XXX: this "multiple field access" style from ``numpy`` also causes the same error?
         open, high, low, close, index = q[
            ['open', 'high', 'low', 'close', 'index']]

``` 

Which raises a nearly identical error:

```python
umba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(Record(index[type=int64;offset=0],time[type=int64;offset=8],open[type=float64;offset=16],high[type=float64;offset=24],low[type=float64;offset=32],close[type=float64;offset=40],volume[type=float64;offset=48],bar_wap[type=float64;offset=56];64;False), list(unicode_type)<iv=['open', 'high', 'low', 'close', 'index']>)

There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(Record(index[type=int64;offset=0],time[type=int64;offset=8],open[type=float64;offset=16],high[type=float64;offset=24],low[type=float64;offset=32],close[type=float64;offset=40],volume[type=float64;offset=48],bar_wap[type=float64;offset=56];64;False), list(unicode_type)<iv=None>)':
   No match.

During: typing of intrinsic-call at /home/goodboy/repos/piker/piker/data/_pathops.py (129)
During: typing of static-get-item at /home/goodboy/repos/piker/piker/data/_pathops.py (129)

File "piker/data/_pathops.py", line 129:
def path_arrays_from_ohlc(
    <source elided>

        open, high, low, close, index = q[
        ^
```

**Comment by stuartarchibald** [comment]
@goodboy I don't think list based access to the fields is supported. If the list is declared as in the above, then it has an `initial_value` (the `<iv=[...]>` part of the type) which would potentially make it possible to implement this kind of indexing. If this is important to you then perhaps open a feature request? Many thanks.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.

**Comment by goodboy** [comment]
@stuartarchibald i don't *think* it's fixed?

Afaict there never was a real solution nor an attempt at one 😂
