### ISSUE TITLE
Reminder to revert changes to CI before merging py3.11 branch

### ISSUE THREAD

**Issue by sklam** [numba/numba#8629]
Suggest the patches that make these temporary changes are tracked somewhere so that it's clear what needs reverting.

_Originally posted by @stuartarchibald in https://github.com/numba/numba/pull/8545#discussion_r1027843809_

**Comment by stuartarchibald** [comment]
Closing. `main` as of at least 9878790 contains a stable and suitable CI matrix with respect to Python 3.11.
