### ISSUE TITLE
Feature Request: Supporting unboxing list(optional(concrete_type))

### ISSUE THREAD

**Issue by dlee992** [numba/numba#8637]
```python
# https://github.com/numba/numba/blob/main/numba/tests/test_lists.py#L387
# insert two testcases into TestLists below
class TestLists(MemoryLeakMixin, TestCase):

    def test_outer_optional_list(self):
        @njit
        def foo(l):
            return l

        l = [1, None]
        print(foo(l))

    def test_inner_optional_list(self):
        @njit
        def foo():
            l = []
            l.append(None)
            l.append(1)
            return l

        print(foo())
```

The first testcase will report an error: `TypeError: can't unbox heterogeneous list: int64 != none`

But the second testcase can run smoothly.

So, I think fixing the first testcase is a feature request that making `types.list` supports `optional(concrete_type)`. I would like to give a PR about this if I can fix it soon.

**Comment by dlee992** [comment]
BTW, when using `types.List`, a warning keeps coming out: 
`NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found`.

Do we really have a plan to remove it? I kind of feel we couldn't remove it, since `types.ListType` doesn't support `Optional` item at all.

Or maybe I shouldn't fix the issue above. Instead, we should help `types.ListType` support `Optional(concrete_type)`, then we can move forward to the goal of removing `reflected list`.

Any decision?

**Comment by guilhermeleobas** [comment]
HI @dlee992, thanks for the report. I'll put this feature request for discussion at the meeting tomorrow. Nevertheless, reflected lists are [schedule for deprecation for a while](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types). I wonder if it makes sense to put an effort on something that will be deprecated in the future.

**Comment by dlee992** [comment]
Yeah, the reason for deprecation makes sense. I feel we won't need to support `optional(concrete_type)` for `reflected list`, but we could try to implement support for `typed list`.

**Comment by guilhermeleobas** [comment]
Hi @dlee992, from the Numba meeting today, the consensus was that to not put that much of an effort on this as reflected lists are deprecated.

**Comment by dlee992** [comment]
Okay, make sense. I will close this one. At the same time, I'm considering supporting `typed list(optional(...))` to meet my requirements.
