### ISSUE TITLE
[FEA] Add Support for linking C/C++ with `@numba.jit` functions

### ISSUE THREAD

**Issue by dlee992** [numba/numba#8658]
Hi, I think supporting for linking C/C++ with `@numba.jit` functions could be beneficial for some situations, for example, when we can't use Python / Numba / llvmlite interface to write certain kinds of functionality, especially if this functionality depends on some C/C++ libraries.

And without this feature, LLVM can't do many optimizations when calling from LLVM IR to the shared library including the related C/C++ code, which does hurt the performance, I guess.

Just as graham has already done in #7621, I think we need it also for CPU target in the future.

**Comment by esc** [comment]
@dlee992 thank you for the request, I have labelled it as feature request accordingly.

**Comment by dlee992** [comment]
close it for now.
