### ISSUE TITLE
Create Dockerfile to allow easy access/testing of Numba with Python 3.11 support

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8667]
As title, maintainers feel free to edit.

Steps to include:
* [x] Making a Python 3.11 branch on `numba-hatchery`

   * [x] Fixing `numba-hatchery` to "just compile and not test" https://github.com/numba/numba-hatchery/pull/1.
   * [x] Adjust `numba-hatchery` to refer to the `py3.11` branch (at a specific hash) of Numba and the corresponding `llvmlite` PR. (https://github.com/numba/numba-hatchery/pull/2)
   * [x] Adjust `numba-hatchery` to use a non pre-release Python 3.11 docker image. (https://github.com/numba/numba-hatchery/pull/2)
   * [x] Adjust `numba-hatchery` to work on x86_64/amd64 only. (https://github.com/numba/numba-hatchery/pull/4)
       
* [x] Posting to discourse, explicitly note the few things that are known to be not working yet.
    * [x] https://numba.discourse.group/t/ann-docker-image-for-early-testing-numba-on-python-3-11/1698

**Comment by esc** [comment]
Completed!
