### ISSUE TITLE
Can we add the jitclass into the signature

### ISSUE THREAD

**Issue by Nanase-Nishino** [numba/numba#8684]

**Comment by Nanase-Nishino** [comment]
Thanks for the high performance of numba. 
I have a question when use a class with @jitclass decorator as a parameter of a function with @jit decorator.
The question is that what is the signature for the class with @jitclass decorator.
My code is here:
`from numba.experimental import jitclass
from numba import float64

spec = [
    ("x", float64),
    ("y", float64[:, :])
]

@jitclass()
class t:

    y : float64[:, :]

    def __init__(self):
        self.y = np.array([[1., 2., 3.]])

    def get(self, ind) -> np.ndarray:
        # self.x.append([1.0, 2.0, 3.0])
        # x = np.array(self.x)
        return self.y

@numba.jit(f"float64[:,:](Any)")
def f(x):
    return x.y

t = t()
print(f(t))`

**Comment by Nanase-Nishino** [comment]
Thanks for the high performance of numba.
I have a question when use a class with @jitclass decorator as a parameter of a function with @jit decorator.
The question is that what is the signature for the class with @jitclass decorator.
My code is here:
'
from numba.experimental import jitclass
from numba import float64

spec = [
    ("x", float64),
    ("y", float64[:, :])
]

@jitclass()
class t:

    y : float64[:, :]

    def __init__(self):
        self.y = np.array([[1., 2., 3.]])

    def get(self, ind) -> np.ndarray:
        # self.x.append([1.0, 2.0, 3.0])
        # x = np.array(self.x)
        return self.y

@numba.jit(f"float64[:,:](Any)")
def f(x):
    return x.y

t = t()
print(f(t))
`

**Comment by gmarkall** [comment]
You can call `numba.typeof` to get the type of a jitclass instance, e.g.:

```python
from numba.experimental import jitclass
from numba import float64, njit, typeof
import numpy as np

spec = [
    ("x", float64),
    ("y", float64[:, :])
]


@jitclass
class t:

    y: float64[:, :]

    def __init__(self):
        self.y = np.array([[1., 2., 3.]])

    def get(self, ind) -> np.ndarray:
        # self.x.append([1.0, 2.0, 3.0])
        # x = np.array(self.x)
        return self.y


t = t()
t_ty = typeof(t)


@njit(float64[:, :](t_ty))
def f(x):
    return x.y


print(f(t))
```

... However - why do you want to explicitly specify the signature? This is usually not a good idea.

**Comment by Nanase-Nishino** [comment]
> You can call `numba.typeof` to get the type of a jitclass instance, e.g.:
> 
> ```python
> from numba.experimental import jitclass
> from numba import float64, njit, typeof
> import numpy as np
> 
> spec = [
>     ("x", float64),
>     ("y", float64[:, :])
> ]
> 
> 
> @jitclass
> class t:
> 
>     y: float64[:, :]
> 
>     def __init__(self):
>         self.y = np.array([[1., 2., 3.]])
> 
>     def get(self, ind) -> np.ndarray:
>         # self.x.append([1.0, 2.0, 3.0])
>         # x = np.array(self.x)
>         return self.y
> 
> 
> t = t()
> t_ty = typeof(t)
> 
> 
> @njit(float64[:, :](t_ty))
> def f(x):
>     return x.y
> 
> 
> print(f(t))
> ```
> 
> ... However - why do you want to explicitly specify the signature? This is usually not a good idea.

wow!! thanks for your help!!!
In fact, I put an instance of jitclass into a function with njit. However, the run time has increased. 
Therefore, I think the problem could be the explicitly specify the signature.
All in all, I write a complexity program for some people who is not good at debugging, I think maybe fix the signature can prevent them from the error of type.

**Comment by Nanase-Nishino** [comment]
``> You can call `numba.typeof` to get the type of a jitclass instance, e.g.:
> 
> ```python
> from numba.experimental import jitclass
> from numba import float64, njit, typeof
> import numpy as np
> 
> spec = [
>     ("x", float64),
>     ("y", float64[:, :])
> ]
> 
> 
> @jitclass
> class t:
> 
>     y: float64[:, :]
> 
>     def __init__(self):
>         self.y = np.array([[1., 2., 3.]])
> 
>     def get(self, ind) -> np.ndarray:
>         # self.x.append([1.0, 2.0, 3.0])
>         # x = np.array(self.x)
>         return self.y
> 
> 
> t = t()
> t_ty = typeof(t)
> 
> 
> @njit(float64[:, :](t_ty))
> def f(x):
>     return x.y
> 
> 
> print(f(t))
> ```
> 
> ... However - why do you want to explicitly specify the signature? This is usually not a good idea.

wow!! thanks for your help!!!
In fact, I put an instance of jitclass into a function with njit. However, the run time has increased.
Therefore, I think the problem could be the explicitly specify the signature.
All in all, I write a complexity program for some people who is not good at debugging, I think maybe fix the signature can prevent them from the error of type.
one of function is here:

```
def CpdAirSystem_obj(Strategy, System, Date, ConditionTable, eta_s=0.8, p_low=800):

    length = int(len(Strategy) / 2)
    StrategyTimeTable = np.zeros((length, 3))

    StrategyTimeTable[:, 0] = np.trunc(Strategy[0:length])
    StrategyTimeTable[:, 1] = (Strategy[0:length] - np.trunc(Strategy[0:length])) * 60
    StrategyTimeTable[:, 2] = Strategy[length:]

    isSupEnded = np.zeros(length)
    Pow, P_uesr = CpdAirSystem_Simulation(Date, System, ConditionTable, StrategyTimeTable, isSupEnded)
    
    if np.min(P_uesr) < p_low:
        return 1000000

    return Pow
```

**Comment by gmarkall** [comment]
> wow!! thanks for your help!!!

You're welcome :slightly_smiling_face: 

> In fact, I put an instance of jitclass into a function with njit. However, the run time has increased.
> Therefore, I think the problem could be the explicitly specify the signature.

I'd imagine it's not likely to be related to the signature (or lack of), but more that you get different code generated when you use a jitclass, which will be more complex with the jitclass. You can get an idea of what changed by dumping the optimized LLVM IR or the generated assembly with the environment variables `NUMBA_DUMP_OPTIMIZED=1` or `NUMBA_DUMP_ASSEMBLY=1`. I imagine you will see more complex code generated with the jitclass. 

You might want to explore using alternative types to the jitclass if you can - e.g. record arrays or named tuples, if you can substitute your use of jitclasses for one of these. I would imagine it might be possible to cut down the runtime by using these (though it's hard to guarantee it of course, especially without me really understanding your code :slightly_smiling_face: ).

> All in all, I write a complexity program for some people who is not good at debugging, I think maybe fix the signature can prevent them from the error of type.

This could avoid the class of errors where an incorrect type is passed, but if your users are not good at debugging, it might also be hard for them to interpret the Numba-generated error about the arguments not matching the signature. Within your program, is it practical for you to write a non-jitted wrapper function that checks types and raises an appropriate error if the wrong type is passed in, then calls the jitted function if all the arguments are OK?

**Comment by Nanase-Nishino** [comment]
> > wow!! thanks for your help!!!
> 
> You're welcome 🙂
> 
> > In fact, I put an instance of jitclass into a function with njit. However, the run time has increased.
> > Therefore, I think the problem could be the explicitly specify the signature.
> 
> I'd imagine it's not likely to be related to the signature (or lack of), but more that you get different code generated when you use a jitclass, which will be more complex with the jitclass. You can get an idea of what changed by dumping the optimized LLVM IR or the generated assembly with the environment variables `NUMBA_DUMP_OPTIMIZED=1` or `NUMBA_DUMP_ASSEMBLY=1`. I imagine you will see more complex code generated with the jitclass.
> 
> You might want to explore using alternative types to the jitclass if you can - e.g. record arrays or named tuples, if you can substitute your use of jitclasses for one of these. I would imagine it might be possible to cut down the runtime by using these (though it's hard to guarantee it of course, especially without me really understanding your code 🙂 ).
> 
> > All in all, I write a complexity program for some people who is not good at debugging, I think maybe fix the signature can prevent them from the error of type.
> 
> This could avoid the class of errors where an incorrect type is passed, but if your users are not good at debugging, it might also be hard for them to interpret the Numba-generated error about the arguments not matching the signature. Within your program, is it practical for you to write a non-jitted wrapper function that checks types and raises an appropriate error if the wrong type is passed in, then calls the jitted function if all the arguments are OK?

thanks for ur explanation and gives me a deeper understanding of numba.
WIth ur suggestion, I has tried to build a type checker program and that is very interesting to me.
have a nice day !🙂

**Comment by Nanase-Nishino** [comment]
okkkkk
I would close this issue
happy new year
