### ISSUE TITLE
pytest doctest can't discover functions with @vectorize decorator

### ISSUE THREAD

**Issue by TomVincentUK** [numba/numba#8694]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This problem seems very similar to the issue raised in #6308, which has already been fixed.

Here's my minimum working example:

```python
"""
Test that all docstrings are the same:

>>> len({f.__doc__ for f in (a, b, c, d)})
1
"""
from numba import guvectorize, int64, njit, vectorize


def a():
    """>>> x = 1"""
    return 1


@njit
def b():
    """>>> x = 1"""
    return 1


@guvectorize([(int64[:], int64, int64[:])], "(n),()->(n)")
def c(x, y, res):
    """>>> x = 1"""
    for i in range(x.shape[0]):
        res[i] = x[i] + y


@vectorize([int64(int64, int64)])
def d(x, y):
    """>>> x = 1"""
    return x + y

```

When I run pytest I get the following results:

```
pytest -rs -sv --doctest-modules mwe.py
============================== test session starts ===============================
platform win32 -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0 -- C:\Users\MYUSER\Miniconda3\envs\fdm\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\MYUSER\local_work\sketches\temp
plugins: cov-4.0.0
collected 4 items

mwe.py::mwe PASSED
mwe.py::mwe.a PASSED
mwe.py::mwe.b PASSED
mwe.py::mwe.c PASSED

=============================== 4 passed in 0.71s ================================
```
As all docstrings are the same, I would expect pytest to run a doctest for the function `d`, as it did for `a`, `b`, and `c`.

**Comment by sklam** [comment]
I think doctest will only pickup functions. The `@vectorize` decorator transforms functions into some callable objects.

**Comment by gmarkall** [comment]
Does any of the information / code in #5755 help here with this issue?
