### ISSUE TITLE
numpy array layout is not determined correctly when passed as jitclass property

### ISSUE THREAD

**Issue by GeorgWa** [numba/numba#8710]
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I  would like to use the jitclass feature to create a dataclass. Unfortunately, numpy arrays show weird behavior, where their memory layout is changed or missunderstood during type inference. 

Assuming I want to reshape a 1D int64 array:

```python

from numba import njit
from numba.experimental import jitclass
from numba.types import int64

x = np.array([1,1,1,1])

@jitclass([('x', int64[:])])    
class data(object):
    def __init__(self, x):
        self.x = x

    def reshape_self(self):
        return self.x.reshape(2,2)
       
@njit()
def reshape_jitclass(data):
    return data.x.reshape(2,2)

@njit()
def reshape(x):
    return x.reshape(2,2)
```

The following works as expected:
```python
reshape(x)
reshape(instance.x)
```

If I try the same passing the object instance or calling the class method, it fails:
```python
reshape_jitclass(instance)
instance.reshape_self()
```

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Cell In [21], line 1
----> 1 reshape_jitclass(instance)
      2 instance.reshape_self()

File ~/miniconda3/envs/alpha/lib/python3.9/site-packages/numba/core/dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File ~/miniconda3/envs/alpha/lib/python3.9/site-packages/numba/core/dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
reshape() supports contiguous array only
- Resolution failure for non-literal arguments:
reshape() supports contiguous array only

During: resolving callee type: BoundFunction(array.reshape for array(int64, 1d, A))
During: typing of call at /var/folders/lc/9594t94d5b5_gn0y04w1jh980000gn/T/ipykernel_76846/642122831.py (19)


File "../../../../../../var/folders/lc/9594t94d5b5_gn0y04w1jh980000gn/T/ipykernel_76846/642122831.py", line 19:
<source missing, REPL/exec in use?>
```

As it's a 1D array it would be very surprising if this is not the case. It does not seem like the flags are being changed, more like there is a bug during type inference:

```
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

```
instance.x.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
```

Thank you for your work and the great library!

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue is in the `jitclass` specification, which has `x` declared as an `int64[:]` type. If you `print(int64[:])` it's apparent that it's an array of type `array(int64, 1d, A)`, i.e. it's `A` (any) order, which is not guaranteed at type inference time as contiguous. To specify a 'C' contiguous array perhaps try using `int64[::1]`, this will be identified as contiguous in the type system and should work fine. Hope this helps?

**Comment by GeorgWa** [comment]
Thank you a lot! This solved the issue. 

It would be great if this information becomes part of the documentation as the behaviour is unexpected if you are used to njit functions.

**Comment by stuartarchibald** [comment]
> Thank you a lot! This solved the issue.

No problem, glad it's working for you.

> It would be great if this information becomes part of the documentation as the behaviour is unexpected if you are used to njit functions.

Please feel free to open a patch with an update to the docs. It's also quite common to use `numba.typeof` to tell you the Numba type of something. The use of the "getitem" syntax on a type to create arrays is hopefully covered by the existing docs here: https://github.com/numba/numba/blob/edca9fb6015be964d97709e997aa94c6cf86690d/docs/source/reference/types.rst?plain=1#L78-L103

**Comment by sklam** [comment]
reshape can also take advantage of the runtime layout flag

**Comment by GeorgWa** [comment]
I will think about proposing a patch for the jitclass page with an example.
Now looking at the array type documentiation it's quite obvious, but somehow I did not thought about the type defintion beeing the issue.
