### ISSUE TITLE
NvvmError: Failed to compile IR version 1.6 incompatible with current version 2.0 <unnamed>: error: incompatible IR detected. Possible mix of compiler/IR from different releases. NVVM_ERROR_IR_VERSION_MISMATCH

### ISSUE THREAD

**Issue by david2588e** [numba/numba#8714]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

in 2 - CUDA Basics
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

np.add(a, b)

from numba import vectorize

@vectorize(['int32(int32, int32)'], target='cuda')
def add_ufunc(x, y):
    return x + y

print('a+b:\n', add_ufunc(a, b))
print()
print('b_col + c:\n', add_ufunc(b_col, c))

NvvmError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_12136\3000442271.py in <module>
----> 1 print('a+b:\n', add_ufunc(a, b))
      2 print()
      3 print('b_col + c:\n', add_ufunc(b_col, c))

~\Anaconda3\lib\site-packages\numba\cuda\dispatcher.py in __call__(self, *args, **kws)
     35                       the input arguments.
     36         """
---> 37         return CUDAUFuncMechanism.call(self.functions, args, kws)
     38 
     39     def reduce(self, arg, stream=0):

~\Anaconda3\lib\site-packages\numba\np\ufunc\deviceufunc.py in call(cls, typemap, args, kws)
    295 
    296             devarys.extend([devout])
--> 297             cr.launch(func, shape[0], stream, devarys)
    298 
    299             if any_device:

~\Anaconda3\lib\site-packages\numba\cuda\dispatcher.py in launch(self, func, count, stream, args)
    153 
    154     def launch(self, func, count, stream, args):
--> 155         func.forall(count, stream=stream)(*args)
    156 
    157     def is_device_array(self, obj):

~\Anaconda3\lib\site-packages\numba\cuda\compiler.py in __call__(self, *args)
    334             kernel = self.kernel
    335         else:
--> 336             kernel = self.kernel.specialize(*args)
    337         blockdim = self._compute_thread_per_block(kernel)
    338         griddim = (self.ntasks + blockdim - 1) // blockdim

~\Anaconda3\lib\site-packages\numba\cuda\compiler.py in specialize(self, *args)
    972         targetoptions = self.targetoptions
    973         targetoptions['link'] = self.link
--> 974         specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
    975                                     targetoptions)
    976         self.specializations[cc, argtypes] = specialization

~\Anaconda3\lib\site-packages\numba\cuda\compiler.py in __init__(self, py_func, sigs, targetoptions)
    805                 self.compile_device(argtypes)
    806             else:
--> 807                 self.compile(sigs[0])
    808 
    809             self._can_compile = False

~\Anaconda3\lib\site-packages\numba\cuda\compiler.py in compile(self, sig)
   1084             if not self._can_compile:
   1085                 raise RuntimeError("Compilation disabled")
-> 1086             kernel = _Kernel(self.py_func, argtypes, link=self.link,
   1087                              **self.targetoptions)
   1088             # Inspired by _DispatcherBase.add_overload, but differs slightly

~\Anaconda3\lib\site-packages\numba\core\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37 

~\Anaconda3\lib\site-packages\numba\cuda\compiler.py in __init__(self, py_func, argtypes, link, debug, lineinfo, inline, fastmath, extensions, max_registers, opt, device)
    409 
    410         # A kernel needs cooperative launch if grid_sync is being used.
--> 411         self.cooperative = 'cudaCGGetIntrinsicHandle' in lib.get_asm_str()
    412         # We need to link against cudadevrt if grid sync is being used.
    413         if self.cooperative:

~\Anaconda3\lib\site-packages\numba\cuda\codegen.py in get_asm_str(self, cc)
    101 
    102     def get_asm_str(self, cc=None):
--> 103         return self._join_ptxes(self._get_ptxes(cc=cc))
    104 
    105     def _get_ptxes(self, cc=None):

~\Anaconda3\lib\site-packages\numba\cuda\codegen.py in _get_ptxes(self, cc)
    139             # Otherwise, we compile all modules with NVVM at once because this
    140             # results in better optimization than separate compilation.
--> 141             ptxes = [nvvm.llvm_to_ptx(irs, **options)]
    142 
    143         # Sometimes the result from NVVM contains trailing whitespace and

~\Anaconda3\lib\site-packages\numba\cuda\cudadrv\nvvm.py in llvm_to_ptx(llvmir, **opts)
    709     cu.lazy_add_module(libdevice.get())
    710 
--> 711     return cu.compile(**opts)
    712 
    713 

~\Anaconda3\lib\site-packages\numba\cuda\cudadrv\nvvm.py in compile(self, **options)
    295                                           for x in opts])
    296         err = self.driver.nvvmCompileProgram(self._handle, len(opts), c_opts)
--> 297         self._try_error(err, 'Failed to compile\n')
    298 
    299         # get result

~\Anaconda3\lib\site-packages\numba\cuda\cudadrv\nvvm.py in _try_error(self, err, msg)
    313 
    314     def _try_error(self, err, msg):
--> 315         self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
    316 
    317     def get_log(self):

~\Anaconda3\lib\site-packages\numba\cuda\cudadrv\nvvm.py in check_error(self, error, msg, exit)
    190                 sys.exit(1)
    191             else:
--> 192                 raise exc
    193 
    194 

NvvmError: Failed to compile

IR version 1.6 incompatible with current version 2.0
<unnamed>: error: incompatible IR detected. Possible mix of compiler/IR from different releases.
NVVM_ERROR_IR_VERSION_MISMATCH

**Comment by gmarkall** [comment]
Same issue as #8715, closing as a duplicate.
