### ISSUE TITLE
Support for CUDA 12.0

### ISSUE THREAD

**Issue by samsamoa** [numba/numba#8715]
- [x] I have tried using the latest released version of Numba -> I have tried 0.56.4
- [x] I have included a self contained code sample to reproduce the problem. i.e. it's possible to run as 'python bug.py'.

numba 0.56.4 appears to be incompatible with CUDA 12.0.  This error is generated:
```
numba.cuda.cudadrv.error.NvvmError: Failed to compile

IR version 1.6 incompatible with current version 2.0
<unnamed>: error: incompatible IR detected. Possible mix of compiler/IR from different releases.
NVVM_ERROR_IR_VERSION_MISMATCH
```

Example reproduction script:
```
from numba import cuda
import numpy as np
@cuda.jit
def f(x):
     x[0] = 1

c = cuda.device_array((1,), np.float32)
f[1,1](c)
```

Another report here: https://stackoverflow.com/questions/74768750/numba-cuda-possible-mix-of-compiler-ir-from-different-releases

**Comment by ivan1993spb** [comment]
@ramkikannan it looks like numba was a little behind this nvidia cudatoolkit update.
As a solution you could use conda, or just install an earlier version of cudatoolkit from their archive https://developer.nvidia.com/cuda-toolkit-archive

**Comment by alpha027** [comment]
the command `conda install numba/label/dev::numba` still has not solved my issue yet, I am on cuda 12 ubuntu 22.04.02 LTS

**Comment by gmarkall** [comment]
> the command `conda install numba/label/dev::numba` still has not solved my issue yet, I am on cuda 12 ubuntu 22.04.02 LTS and using numba version 0.56.0, python 3.8

If you're on Numba 0.56.0 then you don't have the latest package from the dev channel. Did your installation from the dev channel appear to succeed?

**Comment by alpha027** [comment]
I upgraded to 0.56.4 and did not have the error anymore, I have got another one:
` ptxas application ptx input, line 9; fatal   : Unsupported .version 8.1; current version is '8.0'`
I used the following command: `conda install cudatoolkit` and it solved the issue. :+1:

**Comment by gmarkall** [comment]
@alpha027 that message implies you have the cuda 12.1 sdk but only a 12.0 driver. Installing a toolkit with Conda will have brought in an older version that numba finds first, enabling it to work within your current setup.

**Comment by zhimengfan1990** [comment]
Hello I'm trying to build from source as we are using pip(not conda). Then I can get numba-0+unknown-py38-xxx.whl. The version 0+unknown breaks dependency of other packages in our code base. Also it requires a llvmlite that is only available on conda too. So with pip, we also have to build llvmlite from source too. 

To make life easy with pip, can numba team officially release the 0.57 version?

**Comment by gmarkall** [comment]
Also, this issue should be closed because CUDA 12.0 support is present on `main`.

**Comment by zhimengf** [comment]
> How are you installing with pip? If I use:
> 
> ```
> $ pip install git+https://github.com/numba/numba.git
> ```
> 
> then I get:
> 
> ```
> Collecting git+https://github.com/numba/numba.git
>   Cloning https://github.com/numba/numba.git to /tmp/pip-req-build-khqrcye2
>   Running command git clone --filter=blob:none --quiet https://github.com/numba/numba.git /tmp/pip-req-build-khqrcye2
>   Resolved https://github.com/numba/numba.git to commit 9878790437b16718ac18cb38e9ee1a711b8a9017
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in ./mambaforge/envs/py38numbawheel/lib/python3.8/site-packages (from numba==0.57.0.dev0+1661.g987879043) (0.40.0.dev0+95.g6c9aee9)
> Requirement already satisfied: numpy>=1.21 in ./mambaforge/envs/py38numbawheel/lib/python3.8/site-packages (from numba==0.57.0.dev0+1661.g987879043) (1.24.2)
> Collecting importlib_metadata
>   Using cached importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
> Collecting zipp>=0.5
>   Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
> Building wheels for collected packages: numba
>   Building wheel for numba (setup.py) ... done
>   Created wheel for numba: filename=numba-0.57.0.dev0+1661.g987879043-cp38-cp38-linux_x86_64.whl size=2540742 sha256=a147f1d5eb68b295e277e522e23b2778aa4f1e8b012ce2ee01ccb6eba5a935a8
>   Stored in directory: /tmp/pip-ephem-wheel-cache-ly8ko6gp/wheels/4a/2b/dc/7fc95e5b103b6774dfdc96576c035ee276b1d316caf5db1d54
> Successfully built numba
> Installing collected packages: zipp, importlib_metadata, numba
> Successfully installed importlib_metadata-6.1.0 numba-0.57.0.dev0+1661.g987879043 zipp-3.15.0
> ```
> 
> and the `__version__` seems to align with this:
> 
> ```python
> In [1]: import numba
> 
> In [2]: numba.__version__
> Out[2]: '0.57.0dev0+1661.g987879043'
> ```
> 
> (Anyway, we're just working on the 0.57 release now, so it shouldn't be too much longer - first there will be an RC, then the actual release once we've received some feedback on that)

I followed this. However it failed.
```
root@5c0cb7f4cb54:/tao-pt# pip install git+https://github.com/numba/numba.git
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/numba/numba.git
  Cloning https://github.com/numba/numba.git to /tmp/pip-req-build-9d3pddsk
  Running command git clone -q https://github.com/numba/numba.git /tmp/pip-req-build-9d3pddsk
  Resolved https://github.com/numba/numba.git to commit e7a1e8315d74b0f92ba8b26a40bbb1f28db94ba2
ERROR: Could not find a version that satisfies the requirement llvmlite<0.41,>=0.40.0dev0 (from numba) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0, 0.34.0, 0.35.0, 0.36.0, 0.37.0, 0.38.0, 0.38.1, 0.39.0, 0.39.1)
ERROR: No matching distribution found for llvmlite<0.41,>=0.40.0dev0
```
Then I try to install llvmlite from source too. Also failed.
```
root@5c0cb7f4cb54:/tao-pt# pip install git+https://github.com/numba/llvmlite.git
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/numba/llvmlite.git
  Cloning https://github.com/numba/llvmlite.git to /tmp/pip-req-build-lceybxfm
  Running command git clone -q https://github.com/numba/llvmlite.git /tmp/pip-req-build-lceybxfm
  Resolved https://github.com/numba/llvmlite.git to commit 6f95465cbea8036a6bd9a450a4655b484521d842
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lceybxfm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lceybxfm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l6wto69v
       cwd: /tmp/pip-req-build-lceybxfm/
  Complete output (13 lines):
  /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:547: UserWarning: Normalizing '0.40.0dev0+102.g6f95465' to '0.40.0.dev0+102.g6f95465'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  /usr/bin/python /tmp/pip-req-build-lceybxfm/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-req-build-lceybxfm/ffi/build.py", line 227, in <module>
      main()
    File "/tmp/pip-req-build-lceybxfm/ffi/build.py", line 217, in main
      main_posix('linux', '.so')
    File "/tmp/pip-req-build-lceybxfm/ffi/build.py", line 135, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
```

**Comment by egaebel** [comment]
@zhimengfan1990 do you have a link to the issue you opened on the numba issue tracker?
