### ISSUE TITLE
Unwanted numba rounding vs native sum

### ISSUE THREAD

**Issue by dbdimitrov** [numba/numba#8749]
Hey,

I get an unwanted round up issue with numba when parallelizing.
I noticed that this also happens when I use `np.sum`.

So, I explicitly tried to avoid using `np.sum` but still get different results when using parallel = True.

(both numba and numpy seem to overestimate w.r.t. native)

```

@nb.njit(nb.float64(nb.float64[:]))
def nb_sum(a):
    return sum(a)


@nb.njit(nb.float64[:](nb.float64[:,:]), parallel=True)
def nb_sum_parallel(a):
    
    a0 = np.zeros(a.shape[1], dtype=nb.float64)
    
    for i in nb.prange(a.shape[1]):
        a0[i] = sum(a[:,i])
        
    return a0

# random array
rng = np.random.default_rng(seed=0)
a = rng.random((100000, 1), dtype=np.float64)
```

In this case, numba works as intended - i.e. it's consistent with the native sum:

Numpy
```
np.sum(a[:,0])
# 50078.714844845796
```

Native
```
sum(a[:,0])
# 50078.71484484553
```

Numba with Native
```
nb_sum(a[:,0])
# 50078.71484484553
```

Numba with Native and being called from another function /w nb.prange:
```
nb_sum_parallel(a)
# array([50078.71484485, 49779.23691987, 49989.58522751])
```

Versions:
numpy = '1.22.4'
numba = '0.55.2'

Any idea how I could avoid this behavour?

**Comment by apmasell** [comment]
I am able to reproduce on a Mac M1 with the current numba. I think this is just compounding floating point error and there's probably not much that can be done.

For instance, if I take your program and shuffle the input, and then re-run the sums, like this:
```
import numba as nb
import numpy as np

@nb.njit(nb.float64(nb.float64[:]))
def nb_sum(a):
    return sum(a)


@nb.njit(nb.float64[:](nb.float64[:,:]), parallel=True)
def nb_sum_parallel(a):
    
    a0 = np.zeros(a.shape[1], dtype=nb.float64)
    
    for i in nb.prange(a.shape[1]):
        a0[i] = sum(a[:,i])
        
    return a0

# random array
rng = np.random.default_rng(seed=0)
a = rng.random((100000, 1), dtype=np.float64)

print(np.sum(a[:,0]))
print(sum(a[:,0]))
print(nb_sum(a[:,0]))
print(nb_sum_parallel(a))

np.random.shuffle(a)
print(np.sum(a[:,0]))
print(sum(a[:,0]))
print(nb_sum(a[:,0]))
print(nb_sum_parallel(a))
```
I get slightly different values:
```
49957.42678160858
49957.42678160842
49957.42678160842
[49957.42678161]
49957.42678160859
49957.42678160871
49957.42678160871
[49957.42678161]
```
Floating point arithmetic isn't truly commutative and doing it in parallel will make the error much larger. It also depends on the magnitude differences between the numbers.

**Comment by stuartarchibald** [comment]
IIRC NumPy uses pairwise summation which still achieves good performance but exhibits better properties in rounding error than a naive summation loop. Implementing that might be another option to mitigate the behaviour in the OP. xref: #3046.
