### ISSUE TITLE
Packaging issue caused due to llvm14 RuntimeDyLd issue on linux-aarch64

### ISSUE THREAD

**Issue by sklam** [numba/numba#8756]
Packaging issue caused by [llvm14 issue on linux-aarch64](#8738) requires us to avoid llvm14 on that platform. This issue captures the options that we explored in [today's meeting](https://github.com/numba/numba/wiki/Minutes_2023_02_14). 

- option 1: llvmlite split builds in 0.40.0 so that linux-aarch64 uses llvm11 and other platform uses llvm14.
    - problems:
        - we are forcing all llvmlite users on linux-aarch64 to use llvm11 regardless of whether they will be impacted by MCJIT/RuntimeDyLd issue.
- option 2: llvmlite 0.40.0 will use llvm14 on all platforms, but numba will pin to llvmlite 0.39.0 on linux-aarch64 to use llvm 11.
    - problems:
        - confusion for Numba package maintainer (conda-forge, linux distro...) 
        - setup.py dependency is dynamic. Depends on the executing platform
        - No py3.11 support on linux-aarch64 because that is added in llvmlite 0.40.0
- option 3: Wait for OrcJIT? Maybe it is better.
    - problems:
        - It's a risky gamble. We should do the experiment but that should not block the release.
   
**Conclusion**: In the triage meeting today, we agree that option 1 is the least horrible.

**Comment by gmarkall** [comment]
I think we're gone with "fix LLVM 14 and use it on all platforms instead" - can this now be closed?

**Comment by gmarkall** [comment]
Closing this as I'm pretty sure it's no longer relevant.
