### ISSUE TITLE
how to turn the code into numba style?

### ISSUE THREAD

**Issue by 137ck** [numba/numba#8763]
import random

import numpy as np
from numba import *

inliers = []
equation = []

#@jit(fastmath=True,looplift=True)
def fit(pts, thresh=0.05, minPoints=100, maxIteration=1000):
    n_points = pts.shape[0]
    best_eq = []
    best_inliers = []

    for it in range(maxIteration):

        # Samples 3 random points
        id_samples = random.sample(range(0, n_points), 3)
        #print('id_samples:',id_samples)
        pt_samples = pts[id_samples]
        #print('pt_samples:',pt_samples)

        # We have to find the plane equation described by those 3 points
        # We find first 2 vectors that are part of this plane
        # A = pt2 - pt1
        # B = pt3 - pt1

        vecA = pt_samples[1, :] - pt_samples[0, :]
        vecB = pt_samples[2, :] - pt_samples[0, :]

        # Now we compute the cross product of vecA and vecB to get vecC which is normal to the plane
        vecC = np.cross(vecA, vecB)

        # The plane equation will be vecC[0]*x + vecC[1]*y + vecC[0]*z = -k
        # We have to use a point to find k
        vecC = vecC / np.linalg.norm(vecC)
        k = -np.sum(np.multiply(vecC, pt_samples[1, :]))
        plane_eq = [vecC[0], vecC[1], vecC[2], k]

        # Distance from a point to a plane
        # https://mathworld.wolfram.com/Point-PlaneDistance.html
        pt_id_inliers = []  # list of inliers ids
        dist_pt = (
            plane_eq[0] * pts[:, 0] + plane_eq[1] * pts[:, 1] + plane_eq[2] * pts[:, 2] + plane_eq[3]
        ) / np.sqrt(plane_eq[0] ** 2 + plane_eq[1] ** 2 + plane_eq[2] ** 2)

        # Select indexes where distance is biggers than the threshold
        pt_id_inliers = np.where(np.abs(dist_pt) <= thresh)[0]
        if len(pt_id_inliers) > len(best_inliers):
            best_eq = plane_eq
            best_inliers = pt_id_inliers
        inliers = best_inliers
        equation = best_eq

    return equation, inliers

**Comment by gmarkall** [comment]
This is a question best posed on the Discourse group: https://numba.discourse.group/ - I think you will be able to get some helpful pointers there.
