### ISSUE TITLE
Prune instructions that are unused at runtime 

### ISSUE THREAD

**Issue by sklam** [numba/numba#877]
Instructions used only by macro expansion can be pruned as they are not executed at runtime.  This allows us to accept a constant list creation for use as macro argument even if list is not supported at runtime.

Related to https://github.com/numba/numba/pull/867

**Comment by stuartarchibald** [comment]
@gmarkall this can be closed? IIRC macros were removed in https://github.com/numba/numba/pull/5481.

**Comment by gmarkall** [comment]
Yes - another little step on the road to Numba 1.0! :-)
