### ISSUE TITLE
Numba TBB threading layer doesnt work when libtbb is installed before installing tbb

### ISSUE THREAD

**Issue by rainbowdashlabs** [numba/numba#8777]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

While working with numba and setting up an docker environment with TBB i noticed a weird behaviour. First of all only installing the _tbb_ package from pypi alone like described in the wiki is not enough. I additionally needed to install the debian package _libtbb-dev_

First setup without libtbb-dev.
```docker
FROM python:3.10.10-slim-bullseye
RUN pip install --upgrade pip && pip install numba tbb
CMD echo 'Threading' \
    && numba -s | grep -A 1 Threading \
    && echo '\nInstalled Version:' \
    && numba -s | grep "^tbb" \
    && echo "\n$(pip show numba)" \
    && echo "\n$(pip show tbb)" \
    && echo "\nlibtbb found in" \
    && find / -name "libtbb.so*" \
    && whereis tbb
```
TBB is not enabled because of the missing libtbb-dev package.

So far so good. Everyone will figure this out after some time probably. What really confused me was that the installation order matters. I usually install all debian packages like gcc and python-dev which I need to install some python modules at the same time. **Before** I install the python libs. So I added libtbb-dev there as well.

```docker
FROM python:3.10.10-slim-bullseye
RUN apt-get update && apt-get install -y --no-install-recommends libtbb-dev # some addition packages might be added here as well
RUN pip install --upgrade pip && pip install numba tbb
CMD echo 'Threading' \
    && numba -s | grep -A 1 Threading \
    && echo '\nInstalled Version:' \
    && numba -s | grep "^tbb" \
    && echo "\n$(pip show numba)" \
    && echo "\n$(pip show tbb)" \
    && echo "\nlibtbb found in" \
    && find / -name "libtbb.so*" \
    && whereis tbb
```
TBB is still not enabled, although tbb python and libtbb-dev are both installed. `whereis tbb` also shows that the lib is there and `find` lists several available sockets.

The solution for this problem is simple. All that needed is that the `libtbb-dev` package is installed **after** the tbb python package.

```docker
FROM python:3.10.10-slim-bullseye
RUN pip install --upgrade pip && pip install numba tbb
RUN apt-get update && apt-get install -y --no-install-recommends libtbb-dev
CMD echo 'Threading' \
    && numba -s | grep -A 1 Threading \
    && echo '\nInstalled Version:' \
    && numba -s | grep "^tbb" \
    && echo "\n$(pip show numba)" \
    && echo "\n$(pip show tbb)" \
    && echo "\nlibtbb found in" \
    && find / -name "libtbb.so*" \
    && whereis tbb
```
Now numba recognizes tbb as an available threading layer. All that changed to the previous setup was that libtbb is installed after the python module tbb.

_Note:_ Someone pointed out that it might be caused by different layers, but thats not the case. even when everything is executed in the same RUN the installation order matters.

I am not entirely sure which is the deeper reason behind this. Sure there has be some difference. Maybe it is the fault of the tbb module. But I thought I might report it here. Maybe there is a fix on the numba side or others will find this solution as well.

**Comment by stuartarchibald** [comment]
Thanks for the report, will take a look. xref: #6108 which is probably related.

**Comment by stuartarchibald** [comment]
In linux wheel, Numba's TBB threading layer is shipped as the library: `numba/np/ufunc/tbbpool.cpython-<version>-<arch>.so`, running `readelf -d` on that shows that `libtbb.so.12` is `DT_NEEDED`, so this is the TBB library that the Numba TBB threading layer needs. With regards to `numba -s` output, it's checking that the `tbbpool` module loads ok and that the link-loaded tbb library is also compatible:
https://github.com/numba/numba/blob/7b2637f875901d27513550c92c44541dfebad74e/numba/misc/numba_sysinfo.py#L444-L451
the check for compatibility is here:
https://github.com/numba/numba/blob/7b2637f875901d27513550c92c44541dfebad74e/numba/np/ufunc/parallel.py#L344-L375

I'm not sure what's going on in description in the OP. However, I do seem to recall that `pip` installed `tbb` may not be found by Numba (as the system dynamic linker can't find it). If you want to debug it further, perhaps set the `LD_DEBUG` environment variable to something appropriate to see what the linker is doing whilst trying to resolve the library linkage?
