### ISSUE TITLE
Could this be a bug with caching ?

### ISSUE THREAD

**Issue by gabrielfougeron** [numba/numba#8778]
Hi,

While  working my way up to understanding a bug in my code, I created the following minimal (non-)working example.

```
import numba as nb

# define a function that goes through an iterator with a single argument
def go_through_all(the_it,the_it_arg):

    for i in the_it(the_it_arg):
        pass

go_through_all_nb = nb.njit(go_through_all)
go_through_all_nb_cached = nb.njit(go_through_all,cache=True)

# define an iterator
def my_bad_range(the_max):
    
    i = 0
    while i < the_max:
        yield i
        i +=1

my_bad_range_nb = nb.njit(my_bad_range)
my_bad_range_nb_cached = nb.njit(my_bad_range,cache=True)

go_through_all(my_bad_range,3)

go_through_all(my_bad_range_nb,3)
go_through_all_nb(my_bad_range_nb,3)
go_through_all_nb_cached(my_bad_range_nb,3)

go_through_all(my_bad_range_nb_cached,3)
go_through_all_nb(my_bad_range_nb_cached,3)         # Those two lines fail the second time
go_through_all_nb_cached(my_bad_range_nb_cached,3)  # Those two lines fail the second time
````

When the cached jitted version of the iterator is used with a jitted function, then the script fails **but only on the second run**!

I'm not too sure how caching in numba is supposed to work, so if there is an explaination for this (surprizing) behavior, I'd be thrilled to hear (read) it.
If not, I think this might be a bug ...

Thank you for your time,

**Comment by kc611** [comment]
Thank you for reporting this @gabrielfougeron. I can reproduce this on my local machine. 

MWR:
```python
import numba as nb
from numba import njit

# define an iterator
@njit(cache=True)
def iterator():
    for i in range(3):
        yield i

# define a go through function
@njit
def go_through(iter):
    for i in iter():
        pass

go_through(iterator)         # Only fails when run the second time, so it's a caching issue

```

**Comment by gabrielfougeron** [comment]
Thank you very much for your quick responses. I'm relieved your investigations confirm this is indeed a bug.
Should I close the issue as a duplicate?

**Comment by stuartarchibald** [comment]
> Thank you very much for your quick responses.

No problem, thanks @kc611 !

> I'm relieved your investigations confirm this is indeed a bug. Should I close the issue as a duplicate?

Yes please if you are happy to do so. Many thanks.
