### ISSUE TITLE
Combining regular `numba.jit` / `njit` with CUDA array interface?

### ISSUE THREAD

**Issue by bluenote10** [numba/numba#8784]
## Feature request

It is currently a bit unclear if compiling to a non-CUDA target, i.e., using the regular `@numba.jit` or `@numba.njit` decorator is supposed to work with the CUDA array interface. A minimal example would look like.

```py
import numba
import numba.cuda
import torch

@numba.njit
def numba_test_func(tensor):
    # Can we work with CUDA tensors from CPU?
    ...

# Create some tensor on GPU
device = torch.device("cuda:0")
tensor = torch.tensor([1.0, 2.0, 3.0], device=device)

# Convert it to the underlying CUDA array interface, and try to pass to numba function:
tensor_view = numba.cuda.as_cuda_array(tensor.detach())
numba_test_func(tensor_view)
```

This currently fails at runtime with:

```
TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type
```

I not really sure if this is expected to work, or whether the CUDA array interface is only supposed to work with `@numba.cuda.jit`.

In the pytorch context it would be convenient if this was possible, because pytorch in general tries to be agnostic whether a tensor resided on CPU or GPU. It would be nice to just give some Python code a boost without having to write two numba jit versions, one for CPU and a true CUDA kernel for GPU. I came across this issue when [trying to answer this StackOverflow question](https://stackoverflow.com/a/75580380/1804173), which also demonstrates a suggested work-around if this wasn't possible.

If this is not supposed to work, it would be great if this could be clarified in the docs, perhaps also with a slightly more explicit error message at runtime.

**Comment by diptorupd** [comment]
@bluenote10 As far as I know unboxing of a PyTorch tensor into a Numba `array` type should not be possible. The Numba `array` type is specifically tied to `numpy.ndarray` and the error you are getting is basically telling you that PyTorch tensor has a different type and Numba does not know how to convert from a `tensor` to an `array`. 

Does you example work if you change the tensor to be defined on a `cpu` device?

I will also like to point you to a new numba extension [numba-dpex](https://github.com/IntelPython/numba-dpex) that my team in Intel is developing with guidance from the core Numba developers. One of our goals is to support the exact use case you are describing.

Numba-dpex extends `numba.njit` to compile [dpnp](https://github.com/IntelPython/dpnp). Dpnp is a proto-drop-in NumPy replacement based on [Intel oneAPI](https://www.intel.com/content/www/us/en/developer/tools/oneapi/overview.html) and the [SYCL language](https://sycl.tech/). Dpnp supports multiple types of devices that for now are restricted to Intel CPUs, Intel discrete GPUs, Intel integrated GPUs. In future, CUDA and AMDGPU devices may be supported as well once the support for these types of devices becomes more mature in oneAPI (reference: [ongoing work to add CUDA and AMDGPU support to oneAPI](https://codeplay.com/portal/blogs/2022/12/16/bringing-nvidia-and-amd-support-to-oneapi.html)).

Dpnp already supports the [dlpack protocol](https://github.com/dmlc/dlpack) and it is possible to "zero-copy" (_i.e.,_ take ownership of the underlying memory without copying data) a `torch.tensor` into a `dpnp.ndarray`.

Thus, to solve your example first the `torch.tensor` will have to be converted to a `dpnp.ndarray` using dlpack and then passed to a numba-dpex's JIT decorated function. Numba-dpex will then automatically detect the device of the `dpnp.ndarray` and compile the operations on the `dpnp.ndarray` to device-specific code. The approach will work not just for `dpnp` ufuncs, but even `prange` loops.

Do note that `numba-dpex` and `dpnp` are still pre-beta and lots of features are missing, but both projects are under heavy development and rapidly gaining features. If you are interested, feel free to come and discuss with us on the numba-dpex repo.

**Comment by bluenote10** [comment]
@gmarkall I'm still rather confused how it is supposed to work in general. In the linked example the `@njit` function is basically a "scalar only" function. However, if the `@njit` function also needs to operate on full arrays, just calling the `@njit` function for the CUDA kernel doesn't seem to work. For instance, the following will crash:

```py
import numba.cuda
import numpy as np

@numba.njit
def f_cpu(array):
    array[:, 1] += 1.0

@numba.cuda.jit
def f_gpu(array):
    f_cpu(array)

if __name__ == "__main__":
    array_cpu = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
    array_gpu = numba.cuda.to_device(array_cpu)

    print("\nRunning on CPU:")
    f_cpu(array_cpu)
    print(array_cpu)

    print("\nRunning on GPU:")
    f_gpu[1, 1](array_gpu)  # type: ignore
    print(array_gpu)
```

I've raised a separate issue https://github.com/numba/numba/issues/9324 to clarify if this is just a bug.
