### ISSUE TITLE
Support python sortedcontainers in nopython mode

### ISSUE THREAD

**Issue by wenyuC94** [numba/numba#8798]
I am wondering if it is possible to support SortedList and SortedDict in python sortedcontainers. Thanks!

**Comment by guilhermeleobas** [comment]
Hi @wenyuC94, thanks for the report. I'll mark this issue as a feature request. Also, the containers you are referring to are the ones listed in https://grantjenks.com/docs/sortedcontainers/?

**Comment by wenyuC94** [comment]
Yes, thanks!

**Comment by stuartarchibald** [comment]
This will be discussed at the triage meeting next week, but I think that this is probably outside of the scope of Numba itself. From the mission statement:
https://github.com/numba/numba/blob/291269b7a256f44ae3af84aef611de87eb5a8433/docs/source/developer/mission.rst?plain=1#L56-L66
and the request is not for a standard library feature and is not part of NumPy.

It might be possible to support these containers through the use of Numba's extension API (`numba.extending.*`) via a separate package if someone were willing to write that (or the implementation could just be written locally)?

**Comment by apmasell** [comment]
Sorry, this out of scope for Numba.
