### ISSUE TITLE
why @numba.jit(nopython=True)  cause memory leak, thanks

### ISSUE THREAD

**Issue by Creazy-MR** [numba/numba#8832]
## Reporting a bug

 I have tried using the latest released version of Numba v0.56.4

thanks!!!

**Comment by Creazy-MR** [comment]
![image](https://user-images.githubusercontent.com/59354418/226551936-1c6df76d-4443-4a6e-ba19-5bf9f56f359e.png)

**Comment by sklam** [comment]
Thanks for reporting the issue.
I don't recognize the tool that you are using. Can you tell us more about how you are detecting memory leak? That will help us diagnosis the problem.

**Comment by Creazy-MR** [comment]
@sklam Thanks for your reply! I used 'objgraph' to check for the leaks. I put the relevant code in the 'for loops'. In the end , i found that the problem occurred here. My python version is 3.9, and my numpy version is 1.21.5, If I remove the @numba.jit() before the code, the leaks will not occur.

**Comment by Creazy-MR** [comment]
This issue still needs to be addressed,thanks!

**Comment by jack-mcivor** [comment]
@Creazy-MR are you able to share a fully reproducible example? It would be useful to see what the input data looks like & how you are invoking that function. It's helpful to put code into a python code block, which makes it easier to reproduce and debug

eg.
```python
import numba

@numba.jit(nopython=True)
def update_H(*args, **kwargs):
    ....
```

**Comment by Creazy-MR** [comment]
@jack-mcivor I am sorry for not replying for a long time. Due to project confidentiality, I am unable to provide a complete program. However, in the function mentioned above, the input U and H are numpy arrays.

**Comment by Creazy-MR** [comment]
@jack-mcivor I am sorry for not replying for a long time. Due to project confidentiality, I am unable to provide a complete program. However, in the function mentioned above, the input U，sum_tpo, sum_down and H are numpy arrays,The others are float32 or integer.thanks
