### ISSUE TITLE
Clean up AzureCI matrix

### ISSUE THREAD

**Issue by sklam** [numba/numba#8834]
> The CI matrix will probably need some further adjustment, as will general build configuration, but not for this PR as it seems out of scope.

_Originally posted by @stuartarchibald in https://github.com/numba/numba/issues/8822#issuecomment-1478350653_

#8822 PR may have increased the number of CI configuration too much. We should consider reducing it and perhaps remove testing of older python versions.

**Comment by stuartarchibald** [comment]
Currently looks like this:
```
$ python -c 'import numba.tests.support; numba.tests.support.print_azure_matrix()'
NumPy | Python | Count
-----------------------
 1.21 |  3.8   |   4
 1.22 |  3.8   |   4
 1.22 |  3.9   |   1
 1.23 |  3.8   |   2
 1.23 |  3.9   |   2
 1.23 |  3.10  |   1
 1.24 |  3.10  |   3
 1.24 |  3.11  |   3
 1.24 |  3.8   |   1
 1.24 |  3.9   |   1
```
