### ISSUE TITLE
TypeError: No matching definition doesn't give enough useful information

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#884]
When a matching definition can't be found by the dispatcher, the message received is:

```
TypeError: No matching definition
```

It would probably be helpful if the definition required were printed, and a list of existing defininitions as well.

**Comment by jasongrout** [comment]
A big +1 to this.  I was just about to open an issue for this too.

**Comment by gmarkall** [comment]
Do you have a small bit of code that replicates the issue handy? It looks like when I opened this issue I was in a bit of a hurry and failed to include a reproducer.

**Comment by ml31415** [comment]
```python
from numba import *
@jit(boolean(float32[:]))
def demo(x):
    return False
demo(np.arange(100, dtype=float))
```

**Comment by gmarkall** [comment]
Thanks for the reproducer. 

Just as a note (based on a quick glance at the relevant code), I think the message is coming from `Dispatcher_call` in `numba/_dispatcher.c`. At this point the typecodes of args have been used to find (or fail to find) a matching implementation, so there would be a bit of work necessary to allow a human-readable list of available overloads and the arguments of the inputs to be presented as part of the message.

**Comment by ml31415** [comment]
Awesome, thanks!

**Comment by jasongrout** [comment]
Yes, thanks!
