### ISSUE TITLE
Nested calls are not tracked

### ISSUE THREAD

**Issue by felixhekhorn** [numba/numba#8851]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG)

the scripts resolve here to `created virtual environment CPython3.10.9.final.0-64` and `Successfully installed llvmlite-0.39.1 numba-0.56.4 numpy-1.23.5`

- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as ~~'python bug.py'~~.

as this is a multi-file problem I supply two bash script, which should run as `bash file.sh` (most likely any other shell will do as well)

## The Problem

When calling a numba decorated function within another numba decorated function the upper does not reliably detect if the lower has changed. I believe I can provide two different symptoms demonstrating this problem. The example below consists of two files residing in two function `u` (for upper) and `l` (for lower) with `u` calling `l`. Then changing `l` and calling `u` can result in unpredicted behaviour. Note there is no `cache=True` and no `njit` .

### Files with same time

<details>
<summary>Script to run</summary>

```bash
# setup
mkdir test-numba-call-tree
cd test-numba-call-tree
python3.10 -m virtualenv env
. env/bin/activate
pip install numba

# calling file
cat << EOF > u.py
import numba as nb;
import l
@nb.jit
def u(): return l.l(1,0)
print(u())
EOF

for i in $(seq 1 10)
do
    echo "Loop Nr. $i"
    # cleanup
    rm -f __pycache__/*.pyc

    # lower file
    cat << EOF > l.py
import numba as nb;
@nb.jit
def l(x,y): return x+y
EOF

    # check is 1
    python u.py

    # without either "hack the result remains at random times 1
    # sleep 1
    # rm __pycache__/*.pyc

    # change lower
    cat << EOF > l.py
import numba as nb;
@nb.jit
def l(x,y): return x*y
EOF

    # should be always 0 now, but is still randomly 1
    python u.py

done
```

</details>

- the expected output is alternating 1 and 0
- instead the numbers seem to be random - that's why I added the loop
- as written in the script: a possible solution is the `sleep` such that the timestamp of the file changes
- this looks like only the time down to seconds is actually tracked - I guess this is fine for most of the time, but I wonder if there is a way to improve ... for large scale projects this is not always reliable ...

### Files under git

<details>
<summary>Script to run</summary>

```bash
# setup
mkdir test-numba-call-tree-git
cd test-numba-call-tree-git
git init
python3.10 -m virtualenv env
. env/bin/activate
pip install numba

# calling file
cat << EOF > u.py
import numba as nb;
import l
@nb.jit
def u(): return l.l(1,0)
print(u())
EOF

git add u.py
git commit -m "Add upper file"

git switch -c l-add

# lower file
cat << EOF > l.py
import numba as nb;
@nb.jit
def l(x,y): return x+y
EOF

# check is 1
python u.py
git add l.py
git commit -m "Add lower with +"

git switch main
sleep 1
git switch -c l-mult

# change lower
cat << EOF > l.py
import numba as nb;
@nb.jit
def l(x,y): return x*y
EOF

python u.py
git add l.py
git commit -m "Add lower with *"

for i in $(seq 1 10)
do
    # without this "hack the result is random - of course needs to be active also below!
    # rm __pycache__/*.pyc
    git switch l-add
    python u.py
    # rm __pycache__/*.pyc
    git switch l-mult
    python u.py
done
```

</details>

- the expected output is alternating 1 and 0
- instead the numbers seem to be random - that's why I added the loop
- note that the `sleep` fix from above is in place, but still the script fails

## Possible solutions?

I've no idea about the numba internals, but maybe would it be possible to either track files by nanoseconds (I guess that can be a problem for Windows) or simply by their md5/sha/... value?

---
EDIT:
- stupid me forgot decorators :innocent: - but the result is still the same ...
- changed `virtualenv` to `venv`

**Comment by sklam** [comment]
Without `cache=True`, Numba do not perserve any state once the python process terminates. Can you confirm that the problem only occurs when the function is decorated with `numba.jit`?

**Comment by sklam** [comment]
Additional question: are the files on network filesystem?

**Comment by felixhekhorn** [comment]
> Without `cache=True`, Numba do not perserve any state once the python process terminates. Can you confirm that the problem only occurs when the function is decorated with `numba.jit`?

you suspicion is correct - the problems (both) are present even without numba! This is even more weird (in fact, I didn't even consider that possibility) ... maybe I'm misunderstanding something in the way Python works? Mmm .... this can not possibly be a Python bug, can it? 

anyway, as this does not seem to be numba related, I guess I should close this issue here, right?

> Additional question: are the files on network filesystem?

no - I use my ordinary local filesystem ...

**Comment by sklam** [comment]
> Mmm .... this can not possibly be a Python bug, can it?
>
> anyway, as this does not seem to be numba related, I guess I should close this issue here, right?
> 

This is either a platform specific bug in Python or something odd with the filesystem. I have never seen this before and i'm afraid i can't help much. I'll suggest asking in the cpython community to see if anyone have seen this.

**Comment by felixhekhorn** [comment]
As said I've no idea about numba internal, but reading a bit diagonal [in the caching module](https://github.com/numba/numba/blob/288a38bbd5a15418a211bf067878dfdf3c139509/numba/core/caching.py#L495) and playing a bit with the debugger, I find
```
(Pdb++) where
[0]   /bla/bla/test-call-tree-git/u.py(5)<module>()
-> print(u())
[1]   /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/dispatcher.py(420)_compile_for_args()
-> return_val = self.compile(tuple(argtypes))
[2]   /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/dispatcher.py(946)compile()
-> cres = self._cache.load_overload(sig, self.targetctx)
[3]   /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/caching.py(637)load_overload()
-> return self._load_overload(sig, target_context)
[4]   /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/caching.py(644)_load_overload()
-> data = self._cache_file.load(key)
[5]   /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/caching.py(486)load()
-> overloads = self._load_index()
[6] > /bla/bla/test-call-tree-git/env/lib/python3.10/site-packages/numba/core/caching.py(514)_load_index()
-> _cache_log("[cache] index loaded from %r", self._index_path)
(Pdb++) self._index_path
'/bla/bla/test-call-tree-git/__pycache__/u.u-3.py310.nbi'
``` 
so `Cache._load_index`, the function that can invalidate the cache is only called inside `compile`. But there you only have informations about my `u` function (the upper), but not the `l` function (the lower one). It seems to me the index file contains only information about the functions defined in this very file (`u` inside `u.py`) and that has indeed not changed, so it is fine to keep that cache. But the "library" (meaning the one "external" function call) this function is relying on has changed and we can not know here.

I can see this problem having a potentially long tail (since one would need to keep track of the full calling tree), but I believe this to be a (big) problem, because it makes numba caching basically impossible to use inside git. Now, that is not completely fair, because you "just" have to force the recompilation by deleting the correct folder, which, however, can be non-trivial, but you may say this is a user problem. Given that caching is a very relevant feature (in practice it saves me 15min), I believe you should do "something":
- first, put a big warning in a prominent place saying there are problem
- then either do a proper fix (as said might be difficult)
- or, e.g., you could expose a environment variable to force recompilation?

What do you think @sklam ?
