### ISSUE TITLE
--dump-assembly and --dump-optimized don't do anything

### ISSUE THREAD

**Issue by jeremyherbert** [numba/numba#887]
Hi,

I'm running the latest numbapro (numba: 0.15.1, numbapro: 0.16.0) from anaconda with python3.4. If I use either the --dump-assembly or the --dump-optimized flags, I don't actually get any assembly output, and according to my quick strace it is not writing files anywhere. I'm running https://github.com/ContinuumIO/numbapro-examples/blob/master/cuda_memory/pinned.py with

numba --dump-optimized pinned.py

What am I doing wrong?

**Comment by stuartarchibald** [comment]
As of 0.37, using the noted sample, `--dump-optimized` and `--dump-assembly` both work. Closing. If this is still a problem please reopen.

**Comment by AndiH** [comment]
Using 0.39.0, there's still some issues with dumping LLVM information. Not all environment variables seem to work. Namely  `NUMBA_DUMP_ANNOTATION`, `NUMBA_DUMP_ASSEMBLY`, `NUMBA_DUMP_LLVM`, and `NUMBA_DUMP_OPTIMIZED`.

Using same `pinned.py` example file from above:
```bash
$ for e in BYTECODE CFG IR ANNOTATION ASSEMBLY LLVM FUNC_OPT OPTIMIZED; do echo $e; eval "NUMBA_DUMP_$e"=1 numba pinned.py | grep -v regular | grep -v pinned | wc -l; done
BYTECODE
24
CFG
22
IR
182
ANNOTATION
0
ASSEMBLY
0
LLVM
0
FUNC_OPT
376
OPTIMIZED
0
```

Browsing the source code, I see that these exact environment variables are used in [numba_entry.py:L255-257](https://github.com/numba/numba/blob/0.39.0/numba/numba_entry.py#L255-L257) and set to their command-lines alternatives. To me, this sound like a bug. IMHO they should only be set to their command-line counterparts if the counterparts themselves are defined – and even then this behaviour should be noted somewhere.

**Comment by stuartarchibald** [comment]
@AndiH thanks. Please open a new ticket to track the specific `DUMP_` options that are not working. I believe they are ok for CPU targets so it's probably something in the CUDA backend that either needs to raise as they aren't supported and be declared as such, or actually work.

**Comment by AndiH** [comment]
Done! See https://github.com/numba/numba/issues/3105!

**Comment by stuartarchibald** [comment]
Great, thanks @AndiH
