### ISSUE TITLE
I cannot install numba with pip

### ISSUE THREAD

**Issue by Simiao03** [numba/numba#8894]
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When I tried to install numba on my machine with pip on pycharm I get error: subprocess-exited-with-error message. Here is the whole code I inputted and got, this happened even when I made sure my machine had all its software up to date:
(venv) PS C:\Users\cshang\PycharmProjects\if\read\Mode7-main> pip install numba    
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\cshang\AppData\Local\Temp\pip-install-5se5vfyt\numba_251d753
db3434bd8847b799498682482\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\cshang\AppData\Local\Temp\pip-install-5se5vfyt\numba_251d753
db3434bd8847b799498682482\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3
.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with p
ip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(venv) PS C:\Users\cshang\PycharmProjects\if\read\Mode7-main>

**Comment by Simiao03** [comment]
When will numba support py3.11?

**Comment by guilhermeleobas** [comment]
> When will numba support py3.11?

Hi @Simiao03, [Numba 0.57.0 RC 1 was released on Monday](https://numba.discourse.group/t/ann-numba-0-57-0rc1-and-llvmlite-0-40-0rc1/1879/2) which contains support for Python 3.11. As far as I know, there's not a specific date for the final release of Numba 0.57.0.

**Comment by stuartarchibald** [comment]
Closing this question as it appears to be resolved. Thanks.

**Comment by mehmetkadri** [comment]
> Hi, the py3.11 support is only available in the current release candidate (0.57.0rc1). You'll need to specific the `--pre` option to get the pre-release; e.g. `pip install --pre numba`. In your log, `pip` downloaded 0.56.4 which does not have py3.11 support yet.

You are a LIFE SAVER thank you so much!
