### ISSUE TITLE
Unable to install shap on python 3.11 doubt to numba cannot install on Python version 3.11.2

### ISSUE THREAD

**Issue by AlexNoelHdz** [numba/numba#8899]
Describe the bug
Unable to install shap on python 3.11 doubt to numba cannot install on Python version 3.11.2

To Reproduce
pip install shap
Collecting shap
Downloading shap-0.41.0.tar.gz (380 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 394.7 kB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.24.2)
Requirement already satisfied: scipy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.10.1)
Requirement already satisfied: scikit-learn in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.2.2)
Requirement already satisfied: pandas in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.5.3)
Collecting tqdm>4.25.0
Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 711.2 kB/s eta 0:00:00
Requirement already satisfied: packaging>20.9 in c:\users\anhernan\appdata\roaming\python\python311\site-packages (from shap) (23.0)
Collecting slicer==0.0.7
Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting numba
Downloading numba-0.56.4.tar.gz (2.4 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 1.0 MB/s eta 0:00:00
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
│ exit code: 1
╰─> [8 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\anhernan\AppData\Local\Temp\pip-install-j5quxlxv\numba_465c650efbd849728c6dbd5826d7dbea\setup.py", line 51, in
_guard_py_ver()
File "C:\Users\anhernan\AppData\Local\Temp\pip-install-j5quxlxv\numba_465c650efbd849728c6dbd5826d7dbea\setup.py", line 48, in _guard_py_ver
raise RuntimeError(msg.format(cur_py, min_py, max_py))
RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Expected behavior
Being able to install shap

System

OS and version: Windows 11

**Comment by sklam** [comment]
Thank you for the report.

From the provided log:
```
Collecting numba
Downloading numba-0.56.4.tar.gz (2.4 MB)
```
it appears that it is not getting the latest 0.57.0rc1 version, which is the first available version with py3.11 support. You will need to run with `pip install --pre ...` to get the pre-release.

**Comment by AlexNoelHdz** [comment]
yeah I made this stuff pip install -- numba and works, but when tried pip install shap this happen:

C:\Windows\System32>pip install shap
Collecting shap
  Using cached shap-0.41.0.tar.gz (380 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.24.2)
Requirement already satisfied: scipy in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.10.1)
Requirement already satisfied: scikit-learn in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.2.2)
Requirement already satisfied: pandas in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (1.5.3)
Requirement already satisfied: tqdm>4.25.0 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (4.65.0)
Requirement already satisfied: packaging>20.9 in c:\users\anhernan\appdata\roaming\python\python311\site-packages (from shap) (23.0)
Collecting slicer==0.0.7
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: numba in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (0.57.0rc1)
Requirement already satisfied: cloudpickle in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from shap) (2.2.1)
Requirement already satisfied: colorama in c:\users\anhernan\appdata\roaming\python\python311\site-packages (from tqdm>4.25.0->shap) (0.4.6)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from numba->shap) (0.40.0rc1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from pandas->shap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from pandas->shap) (2023.3)
Requirement already satisfied: joblib>=1.1.1 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn->shap) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn->shap) (3.1.0)
Requirement already satisfied: six>=1.5 in c:\users\anhernan\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas->shap) (1.16.0)
Building wheels for collected packages: shap
  Building wheel for shap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for shap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      The nvcc binary could not be located in your $PATH. Either  add it to your path, or set $CUDAHOME to enable CUDA
      Error building cuda module: TypeError('cannot unpack non-iterable NoneType object')
      WARNING: Could not compile cuda extensions
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\shap
      copying shap\datasets.py -> build\lib.win-amd64-cpython-311\shap
      copying shap\links.py -> build\lib.win-amd64-cpython-311\shap
      copying shap\_explanation.py -> build\lib.win-amd64-cpython-311\shap
      copying shap\_serializable.py -> build\lib.win-amd64-cpython-311\shap
      copying shap\__init__.py -> build\lib.win-amd64-cpython-311\shap
      creating build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\mimic.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\pytree.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\tf_utils.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_additive.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_exact.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_explainer.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_gpu_tree.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_gradient.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_kernel.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_linear.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_partition.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_permutation.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_sampling.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\_tree.py -> build\lib.win-amd64-cpython-311\shap\explainers
      copying shap\explainers\__init__.py -> build\lib.win-amd64-cpython-311\shap\explainers
      creating build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\_coefficent.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\_lime.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\_maple.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\_random.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\_treegain.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      copying shap\explainers\other\__init__.py -> build\lib.win-amd64-cpython-311\shap\explainers\other
      creating build\lib.win-amd64-cpython-311\shap\explainers\_deep
      copying shap\explainers\_deep\deep_pytorch.py -> build\lib.win-amd64-cpython-311\shap\explainers\_deep
      copying shap\explainers\_deep\deep_tf.py -> build\lib.win-amd64-cpython-311\shap\explainers\_deep
      copying shap\explainers\_deep\__init__.py -> build\lib.win-amd64-cpython-311\shap\explainers\_deep
      creating build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_bar.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_beeswarm.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_benchmark.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_decision.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_embedding.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_force.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_force_matplotlib.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_group_difference.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_heatmap.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_image.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_labels.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_monitoring.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_partial_dependence.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_scatter.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_text.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_utils.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_violin.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\_waterfall.py -> build\lib.win-amd64-cpython-311\shap\plots
      copying shap\plots\__init__.py -> build\lib.win-amd64-cpython-311\shap\plots
      creating build\lib.win-amd64-cpython-311\shap\plots\colors
      copying shap\plots\colors\_colorconv.py -> build\lib.win-amd64-cpython-311\shap\plots\colors
      copying shap\plots\colors\_colors.py -> build\lib.win-amd64-cpython-311\shap\plots\colors
      copying shap\plots\colors\__init__.py -> build\lib.win-amd64-cpython-311\shap\plots\colors
      creating build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\experiments.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\framework.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\measures.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\methods.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\metrics.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\models.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\plots.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\_compute.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\_explanation_error.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\_result.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\_sequential.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      copying shap\benchmark\__init__.py -> build\lib.win-amd64-cpython-311\shap\benchmark
      creating build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_composite.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_fixed.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_fixed_composite.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_image.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_masker.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_output_composite.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_tabular.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\_text.py -> build\lib.win-amd64-cpython-311\shap\maskers
      copying shap\maskers\__init__.py -> build\lib.win-amd64-cpython-311\shap\maskers
      creating build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\image.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\transformers.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_clustering.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_exceptions.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_general.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_keras.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_legacy.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_masked_model.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\_show_progress.py -> build\lib.win-amd64-cpython-311\shap\utils
      copying shap\utils\__init__.py -> build\lib.win-amd64-cpython-311\shap\utils
      creating build\lib.win-amd64-cpython-311\shap\actions
      copying shap\actions\_action.py -> build\lib.win-amd64-cpython-311\shap\actions
      copying shap\actions\_optimizer.py -> build\lib.win-amd64-cpython-311\shap\actions
      copying shap\actions\__init__.py -> build\lib.win-amd64-cpython-311\shap\actions
      creating build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\_model.py -> build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\_teacher_forcing.py -> build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\_text_generation.py -> build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\_topk_lm.py -> build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\_transformers_pipeline.py -> build\lib.win-amd64-cpython-311\shap\models
      copying shap\models\__init__.py -> build\lib.win-amd64-cpython-311\shap\models
      creating build\lib.win-amd64-cpython-311\shap\plots\resources
      copying shap\plots\resources\bundle.js -> build\lib.win-amd64-cpython-311\shap\plots\resources
      copying shap\plots\resources\logoSmallGray.png -> build\lib.win-amd64-cpython-311\shap\plots\resources
      creating build\lib.win-amd64-cpython-311\shap\cext
      copying shap\cext\tree_shap.h -> build\lib.win-amd64-cpython-311\shap\cext
      running build_ext
      numpy.get_include() C:\Users\anhernan\AppData\Local\Temp\pip-build-env-tmhz95xc\overlay\Lib\site-packages\numpy\core\include
      building 'shap._cext' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shap
Failed to build shap
ERROR: Could not build wheels for shap, which is required to install pyproject.toml-based projects

**Comment by guilhermeleobas** [comment]
Hi @AlexNoelHdz, does running `pip install shap --pre` works for you? Also, do you need to use Python 3.11? If not, switching to Python 3.10 might be a better option.

```bash
$ pip install shap --pre
Collecting shap
  Using cached shap-0.41.0.tar.gz (380 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from shap)
  Using cached numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting scipy (from shap)
  Using cached scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Collecting scikit-learn (from shap)
  Using cached scikit_learn-1.2.2-cp311-cp311-macosx_12_0_arm64.whl (8.4 MB)
Collecting pandas (from shap)
  Using cached pandas-2.0.0-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
Collecting tqdm>4.25.0 (from shap)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting packaging>20.9 (from shap)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting slicer==0.0.7 (from shap)
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting numba (from shap)
  Downloading numba-0.57.0rc1-cp311-cp311-macosx_11_0_arm64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 3.4 MB/s eta 0:00:00
Collecting cloudpickle (from shap)
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting llvmlite<0.41,>=0.40.0dev0 (from numba->shap)
  Downloading llvmlite-0.40.0rc1-1-cp311-cp311-macosx_11_0_arm64.whl (28.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.1/28.1 MB 4.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2 (from pandas->shap)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas->shap)
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 16.6 MB/s eta 0:00:00
Collecting tzdata>=2022.1 (from pandas->shap)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 11.6 MB/s eta 0:00:00
Collecting joblib>=1.1.1 (from scikit-learn->shap)
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 11.8 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0 (from scikit-learn->shap)
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->shap)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: shap
  Building wheel for shap (pyproject.toml) ... done
  Created wheel for shap: filename=shap-0.41.0-cp311-cp311-macosx_11_0_arm64.whl size=431142 sha256=160311f3865582922a6e0971d1d13204f771d359b80f1effbabd63e6b84c83b0
  Stored in directory: /Users/guilhermeleobas/Library/Caches/pip/wheels/2a/ca/9d/d8f6a34c245842f4ad8e5afb5e8f217b8914f6d957d9e302fd
Successfully built shap
Installing collected packages: pytz, tzdata, tqdm, threadpoolctl, slicer, six, packaging, numpy, llvmlite, joblib, cloudpickle, scipy, python-dateutil, numba, scikit-learn, pandas, shap
Successfully installed cloudpickle-2.2.1 joblib-1.2.0 llvmlite-0.40.0rc1 numba-0.57.0rc1 numpy-1.24.2 packaging-23.1 pandas-2.0.0 python-dateutil-2.8.2 pytz-2023.3 scikit-learn-1.2.2 scipy-1.10.1 shap-0.41.0 six-1.16.0 slicer-0.0.7 threadpoolctl-3.1.0 tqdm-4.65.0 tzdata-2023.3
```

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved from the Numba installation point of view. Thanks!
