### ISSUE TITLE
Numba could not report the error of out of array in njit?

### ISSUE THREAD

**Issue by Nanase-Nishino** [numba/numba#8914]
My code is here:

```
@numba.njit
def f():
    a = np.zeros(10)
    print(a[10])

f()
```

this program can work and print "1.3351156154062717e-306"

the numba version is 0.54.0
python version is 3.8.10
numpy version is 1.20.3

**Comment by esc** [comment]
> Generally `boundscheck=True` is slower than running without it, so it would usually only be used for debugging purposes.

Indeed, the relevant docs are here: https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html?highlight=boundscheck#bounds-checking

**Comment by Nanase-Nishino** [comment]
> > Generally `boundscheck=True` is slower than running without it, so it would usually only be used for debugging purposes.
> 
> Indeed, the relevant docs are here: https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html?highlight=boundscheck#bounds-checking

thanks! I learn a lot from the docs.

**Comment by Nanase-Nishino** [comment]
> An array with 10 elements has indices 0-9 - if you print the element at index 10 this is a value beyond the end of the array. You can catch errors like this with the `boundscheck` kwarg to the `@njit` decorator:
> 
> ```python
> import numba
> import numpy as np
> 
> @numba.njit(boundscheck=True)
> def f():
>     a = np.zeros(10)
>     print(a[10])
> 
> f()
> ```
> 
> prints:
> 
> ```
> $ python repro.py 
> debug: IndexError: index 10 is out of bounds for axis 0 with size 10
> Traceback (most recent call last):
>   File "/home/gmarkall/numbadev/issues/8914/repro.py", line 10, in <module>
>     f()
> IndexError: index is out of bounds
> ```
> 
> Generally `boundscheck=True` is slower than running without it, so it would usually only be used for debugging purposes.

thanks a lot.
Futhermore, could you please explain why numba is not design with a boundary check, which seems like a fundmental work of coding.

**Comment by Nanase-Nishino** [comment]
> 

thanks a lot!
I learn a lot from these setting and will consider how to apply it to accelerate my structure of evolutionary algorithm.
In addition, I sincerely thanks all members of numba, because of numba, i can accelerate my code and finally my papar is accepted by a journal with if=8.653.
repect to you all!
