### ISSUE TITLE
Make is so that nothing is compiled in the process of listing the available tests.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8919]
The command `python -m numba.runtests` currently compiles various things just to list the tests. This is largely due to tests with signatures on the import paths which lead to point-of-declaration compilation. This ticket tracks:
* Preventing this from happening now.
* Asserting it doesn't happen in future.

**Comment by gmarkall** [comment]
A potential starting point to tackle this issue:

- Place a raise statement somewhere in the critical path for compilation.
- Run the test listing, and see what triggers the raise.
- Modify the test suite such that the raise no longer occurs.
- Repeat this process until there is no longer a raise from the test listing, then remove the raise statement.

**Comment by stuartarchibald** [comment]
Fixed in #9309, closing.
