### ISSUE TITLE
GPU support for `jitclass`

### ISSUE THREAD

**Issue by remydubois** [numba/numba#8946]
## Feature request

Hello,

Thank you for developing and maintaining Numba !

I see on [Numba's doc](https://numba.pydata.org/numba-doc/latest/user/jitclass.html) that GPU support for jitclasses was to be released in future versions. Is there an estimate of when this feature could eventually be released ?

**Comment by gmarkall** [comment]
There isn't - given that `StructRef` looks like it will take over jitclasses in the long-term (https://numba.discourse.group/t/what-is-the-future-of-jitclass-and-structref/1900/2), that will likely be the route by which support for it on GPUs takes place. I'm hoping that we could have support for `StructRef` on CUDA within the next couple of releases (i.e. within about a year) but there's no promise / guarantee of that - it depends on getting the Numba Runtime (the memory management / reference counting mechanism used in Numba-compiled code) working in CUDA.

**Comment by remydubois** [comment]
Thank you very much for your answer, I will keep an eye out on `StructRef` then :)
