### ISSUE TITLE
`np.angle` returns incorrect type since `0.57.0`

### ISSUE THREAD

**Issue by AngelFP** [numba/numba#8949]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

As the title says, I've noticed that since the last release `np.angle` seems to be returning arrays with incorrect type when jitted with numba. Instead of the expected `float64`, the arrays are `complex128`.

This is causing issues on my side, with some jitted methods that no longer compile due to the wrong types.

The code below reproduces the issue:
```python
import numpy as np
from numba import njit


def numpy_angle(x):
    theta = np.angle(x)
    print(theta.dtype)


@njit()
def numba_angle(x):
    theta = np.angle(x)
    print(theta.dtype)


x = np.array([[1+2j,1+3j],[5+6j,3+8j]])
numpy_angle(x)
numba_angle(x)
```

output with numba `0.56.4`:
```
float64
float64
```
output with numba `0.57.0`:
```
float64
complex128
```

**Comment by gmarkall** [comment]
Many thanks for the report and nice reproducer! This was introduced by a523ecff7ce9aee5dc86ae465236420024c3e651 in #8234.

**Comment by AngelFP** [comment]
Thanks for looking into it!

**Comment by esc** [comment]
I looked into this issue.

Looking at this, which was removed in #8234:

<img width="523" alt="Screen Shot 2023-05-15 at 12 52 13" src="https://github.com/numba/numba/assets/41563/c4f7cd20-4fa4-46aa-87bb-c17b46bbceee">

And this, which is what the `np.angle` implentation looked like post-refactor:


<img width="587" alt="Screen Shot 2023-05-15 at 12 52 26" src="https://github.com/numba/numba/assets/41563/d222cd5a-4f56-4d4a-8d18-81542f6bbdce">


I tried the following patch, which does indeed fix the reproducer submitted? Can anyone confirm?

```
diff --git i/numba/np/arraymath.py w/numba/np/arraymath.py
index 537c226ce8..fc27dfb639 100644
--- i/numba/np/arraymath.py
+++ w/numba/np/arraymath.py
@@ -3212,8 +3212,13 @@ def ov_np_angle(z, deg=False):
                 return np.arctan2(z.imag, z.real)
         return impl
     elif isinstance(z, types.Array):
-        ret_dtype = z.dtype
-
+        dtype = z.dtype
+        if isinstance(dtype, types.Complex):
+            ret_dtype = dtype.underlying_float
+        elif isinstance(dtype, types.Float):
+            ret_dtype = dtype
+        else:
+            return
         def impl(z, deg=False):
             out = np.zeros_like(z, dtype=ret_dtype)
             for index, val in np.ndenumerate(z):
```

**Comment by guilhermeleobas** [comment]
Fixed in https://github.com/numba/numba/pull/8965

**Comment by esc** [comment]
closing this as #8965 has been merged which fixes this issue.
