### ISSUE TITLE
Weird behavior while using numba on a raspberry pi zero

### ISSUE THREAD

**Issue by CodeOfSascha** [numba/numba#8956]
Hi,

I'm using numba on a raspberry pi zero wh and i get some weird behaviour, which i already described on [stackoverflow](https://stackoverflow.com/questions/76221442/weird-behavior-while-using-numba-on-a-raspberry-pi-zero).

I can reproduce the behavior with this code:

`import numba

@numba.jit(nopython=True)
def numtesting(n):
    print(n)
    print(n)

numtesting(1.0)`

I would expect
- 1.0
- 1.0

Instead i get:
- 1.0
- 0.031326431754716

Any ideas what's happening?

**Comment by esc** [comment]
It may be related to 32-bit, what kind of RPi Zero do you have.

Numba/llvmlite is known to cause installation trouble on 32-bit hardware:

https://github.com/numba/llvmlite/issues/604

**Comment by CodeOfSascha** [comment]
Im using the first generation RPi Zero: https://www.raspberrypi.com/products/raspberry-pi-zero-w/

**Comment by esc** [comment]
> It may be related to 32-bit, what kind of RPi Zero do you have?
> 
> Numba/llvmlite is known to cause installation trouble on 32-bit hardware:
> 
> [numba/llvmlite#604](https://github.com/numba/llvmlite/issues/604)

https://numba.readthedocs.io/en/stable/user/installing.html#checking-your-installation

**Comment by CodeOfSascha** [comment]
`numba --sysinfo` produces the following outout:

(venv) pi@raso:~/workingdir $ numba --sysinfo
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2023-05-13 11:17:00.258428
UTC start time                                : 2023-05-13 10:17:00.258494
Running time (s)                              : 16.379162

__Hardware Information__
Machine                                       : armv6l
CPU Name                                      : arm1176jz-s
CPU Count                                     : 1
Number of accessible CPUs                     : 1
List of accessible CPUs cores                 : 0
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : fp16

Memory Total (MB)                             : 429
Memory Available (MB)                         : 295

__OS Information__
Platform Name                                 : Linux-6.1.21+-armv6l-with-glibc2.31
Platform Release                              : 6.1.21+
OS Name                                       : Linux
OS Version                                    : #1642 Mon Apr  3 17:19:14 BST 2023
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 10.2.1 20210110
Python Implementation                         : CPython
Python Version                                : 3.9.2
Python Locale                                 : en_GB.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.56.4
llvmlite Version                              : 0.39.1

__LLVM Information__
LLVM Version                                  : 11.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__NumPy Information__
NumPy Version                                 : 1.23.5
NumPy Supported SIMD features                 : ('None found.',)
NumPy Supported SIMD dispatch                 : ('None found.',)
NumPy Supported SIMD baseline                 : ('None found.',)
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : False
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package            Version
------------------ ------------
blinker            1.6.2
certifi            2023.5.7
charset-normalizer 3.1.0
click              8.1.3
Flask              2.3.2
idna               3.4
importlib-metadata 6.6.0
itsdangerous       2.1.2
Jinja2             3.1.2
llvmlite           0.39.1
MarkupSafe         2.1.2
numba              0.56.4
numpy              1.23.5
Pillow             9.5.0
pip                23.1.2
pypng              0.20220715.0
qrcode             7.4.2
requests           2.30.0
RPi.GPIO           0.7.1
setuptools         67.7.2
spidev             3.6
typing_extensions  4.5.0
urllib3            2.0.2
Werkzeug           2.3.3
wheel              0.40.0
zipp               3.15.0

No errors reported.


__Warning log__
Warning (cuda): CUDA is disabled or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'

Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

**Comment by esc** [comment]
How did you install Numba?

**Comment by CodeOfSascha** [comment]
after activating the virtual environment, I used `pip install numba==0.56.4`

**Comment by esc** [comment]
Interesting, most people report issues doing `pip install on a 32 bit RPi zero` -- what distribution are you using and how did you install Python itself?

Unfortunately, I can't reproduce this as I don't have the required hardware. But it does look like you may have hit a Numba bug.

**Comment by esc** [comment]
The other thing you could try is to run the test-suite of the Numba installation, to check if this yields anything:

```
python -m numba.runtests
```

But be warned. Even on an up-to-date laptop, running the test-suite in parallel will take about an hour. I suspect running this on a RPi zero in serial will take much, much longer. I don't know how long, but I would estimate anywhere from a couple of hours to a day at the most (hopefully not longer). It's a bit of a lift, but this will tell you more about your installation and if Numba is functioning correctly on your system. If you have the time and motivation it may be worth a shot.

**Comment by CodeOfSascha** [comment]
> Interesting, most people report issues doing `pip install` on a 32 bit RPi zero -- what distribution are you using and how did you install Python itself?
> 
> Unfortunately, I can't reproduce this as I don't have the required hardware. But it does look like you may have hit a Numba bug.

I had the same issues. With a lot of googling, reading on Stackoverflow and using Chat-GPT, I found a way that works for me (Tested on a RPi 3 and the RPi zero):
`sudo apt-get install libllvm-9-ocaml-dev libllvm9 llvm-9 llvm-9-dev lllvm-9-runtimelvm-9-doc llvm-9-examples`
`sudo apt install llvm`
`sudo apt-get install libopenjp2-7`
`sudo apt-get install libatlas-base-dev `

**Comment by CodeOfSascha** [comment]
> The other thing you could try is to run the test-suite of the Numba installation, to check if this yields anything:
> 
> ```
> python -m numba.runtests
> ```
> 
> But be warned. Even on an up-to-date laptop, running the test-suite in parallel will take about an hour. I suspect running this on a RPi zero in serial will take much, much longer. I don't know how long, but I would estimate anywhere from a couple of hours to a day at the most (hopefully not longer). It's a bit of a lift, but this will tell you more about your installation and if Numba is functioning correctly on your system. If you have the time and motivation it may be worth a shot.

Interesting. Test was over after a couple of minutes and ended with `Killed`:

(venv) pi@eink:~/ePaper $ python -m numba.runtests
skipped CUDA tests
skipped CUDA tests
ss.ssss.............F../home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:53: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "foo" failed type inference due to: Untyped global name 'bar': Cannot determine Numba type of <class 'function'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 60:
        def foo(x):
            <source elided>
            if x:
                h = h - bar(x)
                ^

  def foo(x):
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:53: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "foo" failed type inference due to: Cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 55:
        def foo(x):
            <source elided>
            h = 0.
            for i in range(x): # py 38 needs two loops for one to lift?!
            ^

  def foo(x):
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "foo" was compiled in object mode without forceobj=True, but has lifted loops.

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 54:
        def foo(x):
            h = 0.
            ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 54:
        def foo(x):
            h = 0.
            ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
.../home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:83: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "udt" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  @numba.jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:83: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "udt" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  @numba.jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "udt" was compiled in object mode without forceobj=True, but has lifted loops.

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:83: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "udt" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  @numba.jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_annotations.py:83: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "udt" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  @numba.jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "udt" was compiled in object mode without forceobj=True, but has lifted loops.

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_annotations.py", line 85:
        def udt(x):
            object()  # to force object mode
            ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
.../home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_analysis.py:1004: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "impl" failed type inference due to: Untyped global name 'object': Cannot determine Numba type of <class 'type'>

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 1008:
        def impl(fa):
            <source elided>
            else:
                object()
                ^

  def impl(fa):
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "impl" was compiled in object mode without forceobj=True.

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 1004:

        def impl(fa):
        ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 1004:

        def impl(fa):
        ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
./home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_analysis.py:414: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "bug" failed type inference due to: Cannot infer the type of variable '$22call_function.1' (temporary variable), have imprecise type: DictType[undefined,undefined]<iv=None>. 

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 418:
        def bug(a, b):
            <source elided>
                if b is None:
                    return dict()
                    ^

  @jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "bug" was compiled in object mode without forceobj=True.

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_analysis.py:414: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "bug" failed type inference due to: Cannot infer the type of variable '$22call_function.1' (temporary variable), have imprecise type: DictType[undefined,undefined]<iv=None>. 

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 418:
        def bug(a, b):
            <source elided>
                if b is None:
                    return dict()
                    ^

  @jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "bug" was compiled in object mode without forceobj=True.

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_analysis.py:414: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "bug" failed type inference due to: Cannot infer the type of variable '$30build_list.0' (temporary variable), have imprecise type: list(undefined)<iv=None>. 

For Numba to be able to compile a list, the list must have a known and
precise type that can be inferred from the other variables. Whilst sometimes
the type of empty lists can be inferred, this is not always the case, see this
documentation for help:

https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-has-an-untyped-list-problem


File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 420:
        def bug(a, b):
            <source elided>
                return 12
            return []
            ^

  @jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "bug" was compiled in object mode without forceobj=True.

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/tests/test_analysis.py:414: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "bug" failed type inference due to: Cannot infer the type of variable '$30build_list.0' (temporary variable), have imprecise type: list(undefined)<iv=None>. 

For Numba to be able to compile a list, the list must have a known and
precise type that can be inferred from the other variables. Whilst sometimes
the type of empty lists can be inferred, this is not always the case, see this
documentation for help:

https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-has-an-untyped-list-problem


File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 420:
        def bug(a, b):
            <source elided>
                return 12
            return []
            ^

  @jit
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "bug" was compiled in object mode without forceobj=True.

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "venv/lib/python3.9/site-packages/numba/tests/test_analysis.py", line 415:
        @jit
        def bug(a, b):
        ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
.s.....FFFFFFFFFFF.FFFFF......ss.ss...s/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/decorators.py:253: RuntimeWarning: nopython is set for njit and is ignored
  warnings.warn('nopython is set for njit and is ignored', RuntimeWarning)
/home/pi/ePaper/venv/lib/python3.9/site-packages/numba/core/decorators.py:255: RuntimeWarning: forceobj is set for njit and is ignored
  warnings.warn('forceobj is set for njit and is ignored', RuntimeWarning)
..s.ss........s.........................Killed

**Comment by esc** [comment]
> Interesting. Test was over after a couple of minutes and ended with `Killed`:

Yeah, I would tend to hypothesize, that the installation was unsuccessful, somehow. The best advice I can offer you now is to re-attempt the installation using the instructions at:

https://github.com/numba/llvmlite/issues/604
