### ISSUE TITLE
A method to free the memory used by the device arrays after computations on GPU

### ISSUE THREAD

**Issue by AkshayRoyal** [numba/numba#8959]
## Feature request
A method to free the memory used by the device arrays after computations on GPU

## Use Case
The use case is pretty common, if this method is not there, the memory utilization of the GPU is non-decreasing and will increase everytime a new device array is made. The ideal case should be to give control to the users to decide when to remove the device array from GPU.

Example
```
import numpy as np
from numba import cuda

n=9999999
array = np.arange(n)
#check the memory usage here using nvidia-smi -l 1
device_array = cuda.to_device(array)  #either rerun this line or run the next line of code
device_array1 = cuda.to_device(array)  
#observe that the GPU memory usage increases
```

**Comment by gmarkall** [comment]
Memory underlying device arrays is marked for cleanup when they are garbage-collected. See https://numba.readthedocs.io/en/stable/cuda/memory.html#deallocation-behavior

There is some additional coverage of this topic in https://github.com/numba/nvidia-cuda-tutorial/blob/main/session-5/session-5-with-notes.pdf.

**Comment by gmarkall** [comment]
Closing as no further follow-up received.
