### ISSUE TITLE
Unsupported .version 8.1

### ISSUE THREAD

**Issue by pauljurczak** [numba/numba#8961]
I'm using Python 3.11.3 on Ubuntu 22.04.2 amd64 with numba 0.57.0 and cuda-python 12.1.0. Cuda scripts were working fine with cuda-toolkit-11.5. After upgrade to cuda-toolkit-12.1, I'm getting this error:
```
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 8.1; current version is '8.0'
```

**Comment by seibert** [comment]
When you installed the CUDA toolkit 12.1, did the installer also update the NVIDIA graphics driver?  This first looks to me like the toolkit has bene updated but the system driver has not.

**Comment by pauljurczak** [comment]
I opted not to update NVIDIA graphics driver, because I had problems with such an update before. Should I update the driver too, in order for Numba to work?

**Comment by pauljurczak** [comment]
I finally managed to update the driver to version 530.30.02 and `@cuda.jit` works fine now.

**Comment by nablabits** [comment]
I also ran into the same problem and as @pauljurczak I finally fixed it by installing a more recent driver (in my case the 545). These are my findings so far in case it helps someone else:
525 -> 8.0
530 -> 8.1
535 -> 8.2
545 -> 8.3
