### ISSUE TITLE
f-String and Float: 

### ISSUE THREAD

**Issue by jcnelson30** [numba/numba#8969]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG). **I am on 0.56.4 due to Conda issues**
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am currently on 0.56.4 (I know 0.57.0 is out, but having some issues updating my Conda environment). Anyways, I have a simple example that fails with f-strings and in particular floats:

```python
@njit
def test_string():
    num = 1.00
    return f'Test: {num}

print(test_string())
```

this fails with the following:

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'str'>) found for signature:
 
 >>> str(float64)
 
There are 10 candidate implementations:
  - Of which 10 did not match due to:
  Overload of function 'str': File: <numerous>: Line N/A.
    With argument(s): '(float64)':
   No match.
```

For all of the following versions of the variable `num` as:

- `num = "test"`
- `num = 1`
- `num = True`

I get the following outputs respectively:

- `Test: test`
- `Test: 1`
- `Test: True`

I'm unsure if it has something to do with how floats are formatted as I know `{num:.4}` formatting is not currently supported.

**Comment by jcnelson30** [comment]
Ahhh... Reviewing the footer at the bottom of this section here: https://numba.readthedocs.io/en/stable/reference/pysupported.html#str

It seems floats are not supported.

I don't use this conversion (float -> str) for a big performance gains, my main use of this is so I can print out some debug information when I'm trying to fix segments of my code.

**Comment by stuartarchibald** [comment]
Thanks for the report. This comment https://github.com/numba/numba/issues/8969#issuecomment-1551896044 is indeed the reason why you are seeing the error in the OP, essentially `str(float)` isn't supported and Numba's `f-string` support relies on `str()` to convert the interpolated arguments into strings.

If you really want to print/interpolate a float and this is not on a performance critical path, one option is to use an `objmode` block. This is a `with-context` managed region where the code will run in the interpreter. e.g.
```python
from numba import njit, objmode, types
import numpy as np

@njit
def foo():
    num = 1.0
    with objmode(string=types.unicode_type): # declare that the "escaping" string variable is of unicode type.
        string = f'Test: {num}'
    return string

print(foo())
```

**Comment by MatteoLacki** [comment]
On numba==0.59.1 there is a bug in as much calling str on a floating point number does not result in an error, but a strange behaviour:
```python
In [64]: @numba.njit
    ...: def test_string(_float):
    ...:     return str(_float)

In [65]: test_string(10.0)
Out[65]: '<object type:float64>'
```
