### ISSUE TITLE
2023 Q2-Q4 roadmap gantt chart for major tasks.

### ISSUE THREAD

**Issue by sklam** [numba/numba#8971]
The following gantt chart includes:

- release schedule of dependency
- release schedule of Numba
- major tasks
- release schedule of packages support future Numba (temporarily named as "Numba++")

Maintenance tasks and low risk tasks are not included.

```mermaid
gantt
    title Numba Roadmap 2023 Q2-Q4
    axisFormat %Y-%m

    section Deps
    Python-3.12        :py312, 2023-10, 1w
    LLVM-16            :llvm16, 2023-03, 1w
    NumPy-1.25         :npy125, 2023-06, 1w
    LLVM-17            :llvm17, 2023-09, 1w
    NumPy-2.00         :npy20, 2024-01, 1w
    #LLVM-18            :llvm18, 2024-03, 1w
    #NumPy-2.10         :npy21, 2024-06, 1w

    section Releases
    Numba_0.57         :crit, nb057, 2023-05, 1w
    Numba_0.58         :crit, nb058, 2023-08, 1w
    Numba_0.59         :crit, nb059, 2023-11, 1w
    Numba_0.60         :crit, nb060, 2024-02, 1w
        
    section Tasks
    RVSDG-0.1          :active, rvsdg01, 2023-05, 8w
    NB_RVSDG_integrate :active, 2023-05, 8w
    OrcJIT             :active, 2023-05, 8w
    PIXIE              :active, pixie, 2023-05, 4w
    %% Numba Py3.12 upgrade
    Numba_py312        :nbpy312, after rvsdg01, 6w
    %% Remove ObjMode fallback
    Numba_rmObjMode    :nbrmObjMode, after nbpy312, 6w
    %% Work to support Numpy2.0 
    NB_NPY20           :nbnpy20, 2023-12, 8w
    
    section Numba++ Rel
    PIXIE-0.1          :pixie01, 2023-11, 1w
    Numba++AOT         :crit, 2024-01, 1w
    NIL-0.1            :nil01, 2024-02, 1w
```

- `Numba_rmObjMode` is work to remove compiler objectmode fallback behavior.
- `NB_NPY20` is work to support Numpy2.0. Including differentiating NumPy and Python integer types.

The schedule presented here is not a guarantee. Actual timing will change and the content will be updated periodically.

**Comment by gmarkall** [comment]
Coming back to look at this, I realise I don't recall what things like "NB_NPY20" mean - can we add a key that explains what each item is, for the non-obvious items?

**Comment by sklam** [comment]
@gmarkall, I've updated the chart and added explanations. The numpy2.0 work is also moved to a more accurate timeframe around late Q4 and early Q1 as that is roughly when it will be available.

**Comment by esc** [comment]
I have cleaned up the milestones and added provisionary dates for the upcoming releases:

* `NEXT` releases to be tagged week starting 07 Aug 2023
  * Numba 0.58 https://github.com/numba/numba/milestone/69
  * llvmlite 0.41 https://github.com/numba/llvmlite/milestone/19
* `NEXT-NEXT` releases to be tagged week starting 06 Nov 2023
  * Numba 0.59 https://github.com/numba/numba/milestone/73
  * llvmlite 0.42 https://github.com/numba/llvmlite/milestone/22

**Comment by stonebig** [comment]
maybe redo the roadmap ? Numpy-2.0 is now retimed for March 15th 2024

**Comment by gmarkall** [comment]
This is probably worth re-visiting following the 0.59 release (which is a priority and consuming all available time right now).

**Comment by sklam** [comment]
superseded by https://github.com/numba/numba/issues/9540
