### ISSUE TITLE
BUG: Windows11 VSCode Numba llvmlite OSError

### ISSUE THREAD

**Issue by PONY1ST** [numba/numba#8986]
I have read a lot of posts about this error but it is still unresolved. I could not make it work on my windows 11 computer.

To recreate the error:
1. Open Visual Studio Code.
2. Create a fresh new python pip virtual environment using `python -m venv work_env`
3. I did `pip install numpy` first, then `pip install numba`. numba has version 0.57.0, numpy has version 1.24.3, llvmlite has version 0.40.0, and python has version 3.11.3.
4. Import numba yields the OSError could not find module llvmlite.dll, although the dll is indeed present in my environment folder.

If possible, I would like a solution using pip only. 

I attempted to use the rc1 versions of numba/llvmlite, but it does not work in the sense that the error is the same even if the installation is successful. 

Finally, one curious observation:
I first code one module:

```
#first_module.py
import numba

@numba.njit
    def foo():
        ...
```

And I import this module in another file at the same folder:

```
#another_module.py
import first_module

...
first_module.foo()
...
```

Then, surprisingly, the second module runs without error and it seems that numba speeds `foo` up despite the fact that clicking run on the file `first_module.py` will yield the error explained above .

**Comment by gmarkall** [comment]
Do you have the same problem if you install with `python -m pip install numba` instead?

**Comment by PONY1ST** [comment]
none of the `python -m pip install numba`, reopen vscode, or pip no cache works. The bug remains as usual.

**Comment by sklam** [comment]
This is likely related to missing DLL dependency as in https://github.com/numba/llvmlite/issues/933. We removed the zlib.dll dependency, but the OP's issue might be caused by missing visual studio runtime; See https://github.com/numba/numba/issues/8841#issuecomment-1502036638

**Comment by PONY1ST** [comment]
I have read the post 8841 and did what it asks. The same error remains.

**Comment by esc** [comment]
It is tricky to diagnose this issue w/o being able to reproduce it. Question to the community: can anyone else reproduce this?

**Comment by evanokeeffe** [comment]
issue can be replicated 
Windows 11 VM , PyCharm 2023.3.2 
runtime version 17.0.9+7-b1087.9 amd64

go into pycharm packages using interpreter 3.11 
install numpy numba llvmlite from the package manager and it'll give this code

C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\distributed\protocol\utils.py:28: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  import numpy
Traceback (most recent call last):
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\ffi.py", line 134, in __getattr__
    return self._fntab[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'LLVMPY_AddSymbol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\ffi.py", line 115, in _load_lib
    self._lib_handle = ctypes.CDLL(str(lib_path))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rwhet\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\llvmlite.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rwhet\PycharmProjects\test\insar.py", line 5, in <module>
    from pygmtsar import SBAS
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\__init__.py", line 18, in <module>
    from .Stack import Stack
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack.py", line 10, in <module>
    from .Stack_ps import Stack_ps
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_ps.py", line 10, in <module>
    from .Stack_stl import Stack_stl
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_stl.py", line 10, in <module>
    from .Stack_tidal import Stack_tidal
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_tidal.py", line 10, in <module>
    from .Stack_incidence import Stack_incidence
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_incidence.py", line 10, in <module>
    from .Stack_geocode import Stack_geocode
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_geocode.py", line 10, in <module>
    from .Stack_sbas import Stack_sbas
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_sbas.py", line 10, in <module>
    from .Stack_detrend import Stack_detrend
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_detrend.py", line 10, in <module>
    from .Stack_unwrap import Stack_unwrap
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\pygmtsar\Stack_unwrap.py", line 12, in <module>
    from numba import jit
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\numba\__init__.py", line 69, in <module>
    from numba.core import config
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\numba\core\config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\dylib.py", line 36, in <module>
    ffi.lib.LLVMPY_AddSymbol.argtypes = [
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\ffi.py", line 137, in __getattr__
    cfn = getattr(self._lib, name)
                  ^^^^^^^^^
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\ffi.py", line 129, in _lib
    self._load_lib()
  File "C:\Users\rwhet\PycharmProjects\test\.venv\Lib\site-packages\llvmlite\binding\ffi.py", line 123, in _load_lib
    raise OSError("Could not find/load shared object file") from e
OSError: Could not find/load shared object file

Process finished with exit code 1

**Comment by esc** [comment]
@evanokeeffe you are using PyCharm, this issue is about VSCode. Please open a new issue. Also, I would highly recommend reading the documentation on formatting github issues here:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by marcoaaz** [comment]
> This is likely related to missing DLL dependency as in [numba/llvmlite#933](https://github.com/numba/llvmlite/issues/933). We removed the zlib.dll dependency, but the OP's issue might be caused by missing visual studio runtime; See [#8841 (comment)](https://github.com/numba/numba/issues/8841#issuecomment-1502036638)

Hi, I am experiencing the same issue in VSCode using Python 3.13.7
numba                     0.62.0
llvmlite                  0.45.0

If someone have figured out how to fix it, please, let me know. Ty.

**Comment by esc** [comment]
> > This is likely related to missing DLL dependency as in [numba/llvmlite#933](https://github.com/numba/llvmlite/issues/933). We removed the zlib.dll dependency, but the OP's issue might be caused by missing visual studio runtime; See [#8841 (comment)](https://github.com/numba/numba/issues/8841#issuecomment-1502036638)
> 
> Hi, I am experiencing the same issue in VSCode using Python 3.13.7 numba 0.62.0 llvmlite 0.45.0
> 
> If someone have figured out how to fix it, please, let me know. Ty.

which OS is this? llvmlite Windows wheels for 0.45.0 are broken under certain conditions:

https://github.com/numba/llvmlite/issues/1297

could you be experiencing that? Does 0.44.* work?

**Comment by marcoaaz** [comment]
> > > This is likely related to missing DLL dependency as in [numba/llvmlite#933](https://github.com/numba/llvmlite/issues/933). We removed the zlib.dll dependency, but the OP's issue might be caused by missing visual studio runtime; See [#8841 (comment)](https://github.com/numba/numba/issues/8841#issuecomment-1502036638)
> > 
> > 
> > Hi, I am experiencing the same issue in VSCode using Python 3.13.7 numba 0.62.0 llvmlite 0.45.0
> > If someone have figured out how to fix it, please, let me know. Ty.
> 
> which OS is this? llvmlite Windows wheels for 0.45.0 are broken under certain conditions:
> 
> [numba/llvmlite#1297](https://github.com/numba/llvmlite/issues/1297)
> 
> could you be experiencing that? Does 0.44.* work?

Dear @esc ,

My system is Windows 11. I found out that reinstalling all the dependencies in a python v3.9.13 environment (VSCode) solved the issue when importing numba. Python 3.13.7 seemed to fail and required to do:
`import numba
from PyQt5.QtWidgets import QMainWindow`

In order for my application to run. It was crashing if importing numba after PyQt5 or within the __main__ statement of the application (pyinstaller).

For solving the issue with llvmlite, I used this main.spec file
`a = Analysis(
    ['main.py'],
    pathex=["helperFunctions", "."],
    binaries=[],
    datas=[
        ("icons", "icons"),        
        ("c:/vips-dev-8.16/bin", "vips"),                
        ("E:/Alienware_March 22/current work/00-new code May_22/dimReduction_v2/chemSimplifier2/Lib/site-packages/llvmlite/*", "llvmlite"),        
        ("E:/Alienware_March 22/current work/00-new code May_22/dimReduction_v2/chemSimplifier2/Lib/site-packages/llvmlite/binding/*", "llvmlite/binding"),
        ],
    hiddenimports=['numba.core.runtime', 'numba.core.registry'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ChemistrySimplifier',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="icons/colour_wheel.ico"
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Chemistry Simplifier v1',
)`

So, one needed to ensure llvmlite packages were included and findable from the application (frozen run).

Thanks for the advanced solution that you provided anyway.

Cheers,
Marco
