### ISSUE TITLE
Indexing subspace regression

### ISSUE THREAD

**Issue by JSKenyon** [numba/numba#8999]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Code which compiles and runs under `numba==0.56.4` no longer compiles and runs under `numba==0.57.0`. MRE is as follows:

```python 
import numpy as np
from numba import njit


@njit
def f(data):

    sel = np.zeros((1,), dtype=np.int64)

    return data[sel, :, 0]


if __name__ == "__main__":

    data = np.random.random((1, 1, 1))

    print(f(data))
```
This produces the following error with `numba==0.57.0`:
```
NumbaTypeError: Using more than one indexing subspace is unsupported. An indexing subspace is a group of one or more consecutive indices comprising integer or array types.
```

**Comment by esc** [comment]
@JSKenyon thank you for the report, it seems as though the code was not correct in the first place and now Numba refuses to compile this with 0.57.0.

Essentially, this is analogous to the second situation in:

https://github.com/numba/numba/pull/8238#issue-1299914324

**Comment by JSKenyon** [comment]
Would it have produced incorrect results previously? I have already implemented a fix so it isn't a problem. Just interested.

**Comment by esc** [comment]
@JSKenyon will close this for now. You could take a look at:

https://github.com/numba/numba/issues/8491

Which will implement support for the feature you need. Hopefully part of 0.58
