### ISSUE TITLE
Support multiple explicit signatures with jit

### ISSUE THREAD

**Issue by shoyer** [numba/numba#901]
`jit` currently can ether infer dtypes, or take a single given function signature.

For [numbagg](https://github.com/shoyer/numbagg), I would like to write functions with signatures like `float32->float32`/`float64->float64`, where the output type depends on the type of the input. I think the easiest way to do this with numba would be if `jit` could handle a list of dtypes, similar to the existing functionality for `vectorize` and `guvectorize`. Thoughts?

**Comment by ml31415** [comment]
Yes, In general it would be really nice, when `vectorize` and `jit` decorators would understand the same inputs. `vectorize` seems to require a list right now, where `jit` insists of a single signature. Would be nice if both could be called in both variants.
