### ISSUE TITLE
Memory leak when use typed.List in jited function

### ISSUE THREAD

**Issue by yuguoshao** [numba/numba#9015]
I'm using numba 0.57.0 and python 3.9.6.
As title says, when I use a jited function to construct typed.List, the memory will leak.
Here is a working example to reproduce it

```
import numpy as np
from memory_profiler import profile
from numba import njit
from numba.typed import List
@njit(parallel=False)
def creat(n):
    X=List([np.zeros(2**2) for i in range(n)])
    return X
@profile
def main():
    Y=creat(2**25)
    Y=0
if __name__ == '__main__':
    main()
```

The output is
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    10     83.7 MiB     83.7 MiB           1   @profile
    11                                         def main():
    12   3264.6 MiB   3180.9 MiB           1       Y=creat(2**25)
    13   4233.2 MiB    968.5 MiB           1       Y=0

```

**Comment by apmasell** [comment]
This doesn't necessarily indicate a memory leak. Numba will have to compile your function `creat` on line 12 for the parameters you've provided and that will consume some memory that won't be returned. Also, this is measuring process memory which is going to be heavily dependant on the Python garbage collector. When I run your sample, it does return the memory from construction of the list:
```
Filename: /Users/amasella/Documents/issue_9015.py

Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     9     74.4 MiB     74.4 MiB           1   @profile
    10                                         def main():
    11   6037.8 MiB   5963.4 MiB           1       Y=creat(2**25)
    12   4714.6 MiB  -1323.2 MiB           1       Y=0
```

Try inserting `del Y` before `Y=0` to trigger more immediate cleanup of the memory:
```
============================================================
     9     74.2 MiB     74.2 MiB           1   @profile
    10                                         def main():
    11   6265.6 MiB   6191.3 MiB           1       Y=creat(2**25)
    12   4775.6 MiB  -1490.0 MiB           1       del Y
    13   4775.6 MiB      0.0 MiB           1       Y=0
    ```

You'll notice the memory reclaimed isn't all that was used when calling `creat` due to the overhead of compiling the function.

**Comment by apmasell** [comment]
I am running on a Macintosh M1 with Numba 0.57 on Python 3.9 in a Conda environment. The 1.5GB is likely the compilation of `creat`. Also, measuring process memory is not going to accurately determine whether something is freed on a line-by-line basis. Try using valgrind to get a more accurate understanding of where memory is allocated and freed.

**Comment by yuguoshao** [comment]
😂 Well, we have the same env.
But I still can't understand this behavior is normal, the List constructed by jited function uses more and more memory and I can't free them. 
Using valgrind is beyond my capacity,  maybe there is anything else I can do about it.

**Comment by apmasell** [comment]
valgrind unfortunately doesn't work on the Mac M1.

**Comment by apmasell** [comment]
You can track the memory allocations done by Numba using `get_allocation_stats`; see https://numba.pydata.org/numba-doc/latest/developer/numba-runtime.html#debugging-leaks
If there's a leak, the NRT stats should show it.
