### ISSUE TITLE
mpi for Numba

### ISSUE THREAD

**Issue by Konjkov** [numba/numba#9016]
## Feature request
Dear Numba team,

there is already a python package that implements this functionality https://pypi.org/project/numba-mpi/ however the MPI functions are not cached:

```
numba_mpi/api/size.py:15: NumbaWarning: Cannot cache compiled function "size" as it uses dynamic globals (such as ctypes pointers and large global arrays)
  @numba.njit('int64()', cache=True)
```

is it possible to integrate this package into Numba and improve caching?

**Comment by apmasell** [comment]
There is no plan to integrate this package into Numba as it is developed independently. Numba can do a better job with caching in a way that would help numba-mpi. I've filed #9019 for that request.
