### ISSUE TITLE
miss cache if define and use `structref` in the same file

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9030]
Hi, guys. I have an interesting issue when enabling cache and using structref, here is a minimum reproducer:
```python
# %%
import numpy as np
from numba import types, njit
from numba.experimental import structref
import os

os.environ['NUMBA_DEBUG_CACHE'] = '1'


# define a structref
@structref.register
class StructType(types.StructRef):

    def preprocess_fields(self, fields):
        return tuple((nam, types.unliteral(typ)) for nam, typ in fields)


class Struct(structref.StructRefProxy):

    def __new__(cls, field):
        return structref.StructRefProxy.__new__(cls, field)

    @property
    def field(self):
        return Struct_get_field(self)


@njit(cache=True)
def Struct_get_field(self):
    # In jit-code, the StructRef's attribute is exposed via
    # structref.register
    return self.field


structref.define_proxy(Struct, StructType, [
    "field",
])


# define jit functions
@njit(cache=True)
def foo(struct):
    return struct.field


@njit(cache=True)
def goo(a):
    return a.shape


# call foo and goo
print("separate".center(20, '!'))

my_struct = Struct(0)
foo(my_struct)

my_a = np.zeros(10)
goo(my_a)
```
When executing this file, first time, everything is new, so need to save index and data:
```
!!!!!!separate!!!!!!
[cache] index saved to '.../define.foo-41.py38.nbi'
[cache] data saved to '.../define.foo-41.py38.1.nbc'
[cache] index saved to '.../define.goo-46.py38.nbi'
[cache] data saved to '.../define.goo-46.py38.1.nbc'
```
second time, rerun this python file and `foo`'s cache misses! At the same time, `goo`'s cache does hit:
```
!!!!!!separate!!!!!!
[cache] index loaded from '.../define.foo-41.py38.nbi'
[cache] index loaded from '.../define.foo-41.py38.nbi'
[cache] index saved to '.../define.foo-41.py38.nbi'
[cache] data saved to '.../define.foo-41.py38.2.nbc'
[cache] index loaded from '.../define.goo-46.py38.nbi'
[cache] data loaded from '.../define.goo-46.py38.1.nbc'
```
If moving these lines below to another file and importing `Struct`, `foo`, and `goo`, `foo`'s cache will hit!
```python
my_struct = Struct(0)
foo(my_struct)

my_a = np.zeros(10)
goo(my_a)
```
I haven't find the root cause, any pointer or insight will be helpful!

Tested with Numba 0.56.4

**Comment by gmarkall** [comment]
I can reproduce this with `main`. I suspect that the struct ref types are considered distinct across each run of the code.

**Comment by gmarkall** [comment]
@dlee992 Does undoing the changes from #7388 fix this issue for you?

**Comment by dlee992** [comment]
Didn't try to revert. I mean #7388 mentioned similar issues as I met in this case, especially this comment ` "Test cannot run as when module is __main__"`. I do remember my traceback prints `__main__`. Maybe it's a known limitation of `cloudpickle`.

**Comment by sklam** [comment]
I've taken a look into this. This is not specific to `structref` but instead a known pickle problem. Globals in the `__main__` module is considered as not pickleable. That is why:

> If moving these lines below to another file and importing `Struct`, `foo`, and `goo`, `foo`'s cache will hit!
> 
> ```python
> my_struct = Struct(0)
> foo(my_struct)
> 
> my_a = np.zeros(10)
> goo(my_a)
> ```

This behavior comes from: https://github.com/cloudpipe/cloudpickle/blame/master/cloudpickle/cloudpickle.py#L294.
