### ISSUE TITLE
Feature Request: include `numba-rvsdg` as a soft dependency

### ISSUE THREAD

**Issue by esc** [numba/numba#9043]
The Numba team has been working on a new library called numba-rvsdg: https://github.com/numba/numba-rvsdg (please view the repository for more information). The 0.58 release is scheduled to include numba-rvsdg as a soft dependency. That is to say: it is optional and as a user I can install and elect to use the library, but it's not "on" by default. The usage will be accessible via a feature flag (probably an environment variable). Work needs to be done to enable this.

* [x] Include numba-rvsdg in continuous integration.
* [x] update recipes and wheel building and such to include this dependency. https://github.com/numba/numba/pull/9120
* [x] Review and merge https://github.com/numba/numba/pull/9012.
* [x] Include ability to activate usage via a feature flag / environment variable.

**Comment by sklam** [comment]
I have a branch to add buildscript at https://github.com/sklam/numba/tree/enh/py311rvsdg_buildscript but it's pending https://github.com/numba/numba-rvsdg/issues/86

**Comment by esc** [comment]
With #9012 and #9120 merged to `main` one can now use:

```
NUMBA_USE_RVSDG_FRONTEND=1 python loop.py
```

to activate and use the new frontend on dev builds. 

🎉
