### ISSUE TITLE
numba.core.errors.NotDefinedError: Failed in nopython mode pipeline (step: analyzing bytecode) The compiler failed to analyze the bytecode. Variable '$1730setup_with.1' is not defined.

### ISSUE THREAD

**Issue by rdua3521** [numba/numba#9054]
###I am using  numba  0.57.1 and Ubuntu 22.04.2 LTS in server 
I try to run my code faster using Numba Library with the help of GPU Cores.

File "/var/www/html/Plan/bars/lib/python3.7/site-packages/numba/core/dispatcher.py", line 428, in _compile_for_args
    error_rewrite(e, 'interpreter')
  File "/var/www/html/Plan/bars/lib/python3.7/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.NotDefinedError: Failed in nopython mode pipeline (step: analyzing bytecode)
The compiler failed to analyze the bytecode. Variable '$1730setup_with.1' is not defined.

**Comment by esc** [comment]
@rdua3521 thank you for posting this. Please add the code your are trying to run. We can not debug your issue without seeing what it is your trying to do.

**Comment by esc** [comment]
Closing now as no updates have been received. If the problem persists please comment with more information about the code which is being run.
