### ISSUE TITLE
Extension Type with prange

### ISSUE THREAD

**Issue by lithomas1** [numba/numba#9062]
## Feature request

I've been working lately on enabling more numba with pandas(most recently in Groupby.apply and firends), and to do this I've decided to use extension types to allow users to use DataFrames/Series/Index in numba jittted code. 

(My implementation is mostly borrowed from https://github.com/numba/numba/blob/main/numba/tests/pdlike_usecase.py)

The code runs fine in single threaded mode, but when using prange and specifying ``parallel=True`` I get
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native parfor lowering)
scalar type dataframe(int64, indextype(int64, 1d, C), F) given for non scalar argument #2

File "pandas/core/groupby/numba_.py", line 178:
    def group_apply(
        <source elided>

        for i in numba.prange(num_groups):
        ^
```

group_apply is defined here.
https://github.com/pandas-dev/pandas/pull/53988/files#diff-3a8fc07bf0dc4dafe51d03c789a66eb9db3cbce582824fdaa96e05e618c5cb36R162-R193

(``numba_func`` in that function is the user defined function passed in that takes a dataframe in as an argument).

From other issues, it looks like numba tries to turn the loop into gufunc and fails.

Is there a way for me to use the extension API to override the default lowering?

I would be fine if the DataFrame was lowered like a tuple (Right now, it is a struct model with values and index ndarrays), since I haven't implemented any additional methods on it.

**Comment by DrTodd13** [comment]
@lithomas1 Are you familiar with Intel's scalable dataframe compiler (SDC) that integrates with Numba?  [SDC](https://github.com/IntelPython/sdc)  I wonder how much of what you are doing has already been done there.  The general strategy there was to convert almost everything to arrays internally so that Numba would function normally and allow fusion of pandas and numpy operations.

For your specific problem, I'd need more info.  Can you run with NUMBA_DEBUG_ARRAY_OPT=2 and post it?

**Comment by lithomas1** [comment]
Thanks for the quick reply. 

Here's the output [output.txt](https://github.com/numba/numba/files/11974175/output.txt)

For reference, this is the data model of the DataFrame in question
<details>

```

# Backend extensions for Index and Series and Frame
@register_model(IndexType)
class IndexModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [("data", fe_type.as_array)]
        models.StructModel.__init__(self, dmm, fe_type, members)


@register_model(SeriesType)
class SeriesModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [
            ("index", fe_type.index),
            ("values", fe_type.as_array),
        ]
        models.StructModel.__init__(self, dmm, fe_type, members)


@register_model(DataFrameType)
class DataFrameModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [
            ("index", fe_type.index),
            ("values", fe_type.as_array),
        ]
        models.StructModel.__init__(self, dmm, fe_type, members)
```

</details>

I had a look at SDC, and it seems like it doesn't support UDFs (none of agg, apply, or transform) are supported, which is what I'm focusing on right now.

In the future, I think I'd be pretty interested having some of that upstreamed into pandas if possible, assuming there's a fix for the parallel issue here.

**Comment by lithomas1** [comment]
Just a quick update, it works if I access the values and index members of the DataFrame struct outside of the prange loop.

e.g. I changed it to
```python
values = df.values
index = df.index._data

for i in prange(...): 
     group = pd.DataFrame(
         values[starts[i] : ends[i]],
         index=pd.Index(index[starts[i]: ends[i]]),
     )
```
instead of directly accessing with ``df.values[starts[i]: ends[i]]`` inside the loop.
