### ISSUE TITLE
`FunctionType` usage throws `TypingError` of arg type mismatch 

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9065]
```python
from numba import njit, types
from numba.types import uint32

func_type = types.FunctionType(uint32(uint32,))

@njit(uint32(func_type))
# @njit
def f(g):
    return g(1)
    # return g(1.1)

@njit(uint32(uint32))
def g(a):
    return a + 1

print(f(g))
```
Will throw `mismatch of int64 and uint32`. But if I don't specify `func_type`, in that case, `g` is a dispatcher, not an instance of FunctionType, then no error.
But I think `FunctionType` should allow this usage, which allow `FunctionType` accepts `Literal[int](1)` as an `uint32` argument. It's more like a feature request, rather than a bug.
Tested with Numba 0.56.3.

The related code is here:
https://github.com/numba/numba/blob/afb5246e5a512d9defd55d7326dfb27174ce0190/numba/core/types/function_type.py#L64L73
```python
        for atype, sig_atype in zip(args, sig.args):
            atype = types.unliteral(atype)
            if sig_atype.is_precise():
                conv_score = context.context.can_convert(
                    fromty=atype, toty=sig_atype
                )
                if conv_score is None \
                   or conv_score > typing.context.Conversion.safe:
                    raise ValueError(
                        f'mismatch of argument types: {atype} vs {sig_atype}')
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue here is that Numba's type system type infers literal integers as `int64` type and there's no safe conversion to `uint32`.

**Comment by dlee992** [comment]
Yes, but if g is a dispatcher, Numba can already do this conversion nicely. So I guess there has already existed a way for FunctionType instance as well. 
BTW, and it throws the similar issue if we replace the integer literal with float literal.

**Comment by dlee992** [comment]
@stuartarchibald , hello. So should this issue be marked as a bug?

**Comment by sklam** [comment]
> ```python
>                 if conv_score is None \
>                    or conv_score > typing.context.Conversion.safe:
> ```

This is unusually restrictive by only allowing promotion or exact type. Needs investigating

**Comment by dlee992** [comment]
Yes, @sklam . My ad-hoc fix is to remove `conv_score > typing.context.Conversion.safe` for allowing unsafe conversion...

**Comment by dlee992** [comment]
Hi, any update about this? I think this needs a fix as well. @sklam

**Comment by dlee992** [comment]
Hi, Siu. I feel this one can be marked as `enhancement`, at least shouldn't be closed by bot... @sklam
