### ISSUE TITLE
Using a generator in njit can sometimes lead to a potential memory leak.

### ISSUE THREAD

**Issue by 852023301** [numba/numba#9079]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

#### Environment
python 3.8
numba 0.57.0
numpy 1.24.3

####  Reporting a bug

Using a generator in njit can sometimes lead to a potential memory leak. I will provide a minimal reproducible example below:

```python
from numba import njit


@njit
def gen_item():
    for k in range(10_0000):
        yield [i for i in range(5)]


@njit
def f1():
    return list(gen_item())


@njit
def f2():
    ls = []
    for i in range(10_0000):
        ls.append([j for j in range(5)])
    return ls


for _ in range(5000):
    f1()


```

Function `f1` and `f2` are used to generate some list of list. But `f1` uses generator while `f2` don't. When I use `f1` ,the memory usage will keep increasing, and it's not freed even after finishing. As for `f2`, the memory will be freed when the loop finished..
Not sure if this is about generator.

**Comment by sklam** [comment]
This is most likely a duplicate of issues like:

- https://github.com/numba/numba/issues/5350
- https://github.com/numba/numba/issues/6993

**Comment by 852023301** [comment]
> @852023301 thank you for the comment. Can you add also, how you are measuring the potential memory leak?

In fact, I wrote a code that uses `psutil` to record the memory usage of each loop. It can be seen that Figure 1 shows that the memory cost of `f1` increases linearly, while Figure 2 shows that the memory cost of  `f2` does not increase linearly and the growth rate is significantly lower.

![1](https://github.com/numba/numba/assets/22229645/7a8f0ef3-3057-4f94-b5f4-c7ac5dad0b44)

![2](https://github.com/numba/numba/assets/22229645/885993fb-6abb-444a-8518-4c91d366a4cf)


```python
from numba import njit
import os
import psutil
import matplotlib.pyplot as plt

pid = os.getpid()

p = psutil.Process(pid)


@njit
def gen_item():
    for k in range(100_0000):
        yield [i for i in range(5)]


@njit
def f1():
    return list(gen_item())


@njit
def f2():
    ls = []
    for i in range(100_0000):
        ls.append([j for j in range(5)])
    return ls


mem_usage = []
x_label = range(100)

for _ in x_label:
    f1()
    mem_usage.append(p.memory_full_info().uss / 1024 ** 3)

plt.plot(x_label,mem_usage)
plt.xlabel('Number of cycles')
plt.ylabel('Memory usage per cycle(G)')
plt.title("Memory usage ")
# plt.savefig('2.png')
plt.show()

```
