### ISSUE TITLE
Result types of integer division and multiplication not intuitive (are float, should be int)

### ISSUE THREAD

**Issue by svenrahmann** [numba/numba#909]
When I integer divide an `uint64` by a positive constant (such as 64), I would expect that the return type is also `uint64`.
However, as inspection of the function `f1` in the code example below shows, a `float64` is generated.

This is unexpected and harmful, as I may want to use the result as an index into an array, or to perform further bitwise manipulations.

I currently have a workaround by assigning the divisor to a local variable, which I explicitly type as `uint64`, using locals in the decorator (see inspection of function f2 below).

Thus the problem seems to be that the constant 64 is interpreted as an `int32`, and  `uint64 // int32 = float64` (which does not make sense at all, as I am doing integer division, not float division!), while `uint64 // uint64 = uint64`, as expected.

As f3 below shows, explicit casting of 64 into `uint64` works as well, but seems to introduce a function call instead of only casting the type.

The easiest solution would be to recognize that the constant 64 is an `uint64`, not an `int32` in this piece of code, but I see no way to explicitly provide type annotations for constants except using the slightly verbose `locals` detour taken with f2. A real solution would be to fix the type inference of integer division.

I saw a similar problem (result type being float) with integer multiplication (and shift left).

This code snippet can be run to see the inferred types:
```python
from numba import jit, uint64

@jit('u8(u8)')
def f1(x):
    return x // 64
    
@jit('u8(u8)', locals={'div':uint64})
def f2(x):
    div = 64
    return x // div

@jit('u8(u8)', nopython=True)
def f3(x):
    return x // uint64(64)

f1.inspect_types()
f2.inspect_types()
f3.inspect_types()
```

**Comment by pitrou** [comment]
This is fixed now that [NBEP 1](http://numba.pydata.org/numba-doc/dev/proposals/integer-typing.html) has been implemented.
