### ISSUE TITLE
Reminder to add deprecation warning for old_style error capture

### ISSUE THREAD

**Issue by sklam** [numba/numba#9091]
Deprecation of new_style error capture is scheduled at https://github.com/numba/numba/pull/9090

- warn when user set `config.CAPTURED_ERRORS == "old_style"`. 
    - differentiate between explicit setting to "old_style" versus by default.
- warn when errors are captured due to `old_style` settings.

**Comment by Seairth** [comment]
Why is a deprecation warning being added when the [default in config.py appears to still be `old_style`](https://github.com/numba/numba/blob/bd7ebcfd4b850208b627a3f75d4706000be36275/numba/core/config.py#L410)?  Shouldn't that be defaulted to `new_style`?

**Comment by sklam** [comment]
closed by #9346

**Comment by sklam** [comment]
RE: https://github.com/numba/numba/issues/9091#issuecomment-1693344159

We are slow rolling the deprecation. see https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-old-style-numba-captured-errors for details.
