### ISSUE TITLE
Still problematic: non-deterministic NaN values in scipy.integrate.solve_ivp when compiling function with numba #8931

### ISSUE THREAD

**Issue by mhechthz** [numba/numba#9092]
I found the thread from title since I faced the same unstable behaviour. But the thread was closed.

I run an ODE-solver with solve_ivp and have some functions decorated with numba (Numba 0.57.1, Python 3.11.4/3.10.11/3.9.9, **Windows 10**). The problem can be solved with identical data about any 5th run of the program. In other cases I get the information of a matrix singularity and NaN values.

Surprisingly I have the opposite behaviour as decribed in #8931 :  For me I have problems on Windows 10 but all works toally stable on **WSL** at the same machine. The WSL runs Ubuntu 22.04 with Python 3.10.6 and Numba 0.57.1.

**Comment by guilhermeleobas** [comment]
Hi @mhechthz, thanks for the report. Does the code shared on #8931 replicates the problem you're having?

```
import scipy.integrate
import numba
import numpy as np
import warnings

@numba.njit("int32(int32)")
def jitted_fun(x):
    return 1

def f(_, y):
  return np.zeros_like(y)

y0 = np.ones(2)

with warnings.catch_warnings(record=True):
    warnings.simplefilter("error")
    for _ in range(100):
        scipy.integrate.solve_ivp(fun=f, t_span=(0, 1), y0=y0, method="BDF")
```

**Comment by mhechthz** [comment]
The posted code runs without problems on Windows. 

The code I have is a quite complex research code, so posting is no option. Nevertheless, I informed the corresponding research institute and they got the same problem with Python 3.11. Before, they have been on Python 3.8 with Numba 0.57.1 and had no problems. 

On setting NUMBA_DISABLE_JIT=1 on Windows, the code runs without problems but quite slow.

If I run on my WSL with Python 3.11.rc0 (WSL has no higher version) I get a Segmentation fault, but this might be because of rc0 state. I also get problems here with NUMBA_DISABLE_JIT=1. Nevertheless, I cannot check the behaviour of Python 3.11 on WSL.

**Comment by guilhermeleobas** [comment]
Would it be possible to share a small reproducer for the problem you're facing? Doesn't have to be the research code you're running. Just a small reproducer that captures the bug.

**Comment by mhechthz** [comment]
I contacted the authors of the code. They will get in touch with you.

Furthermore I checked to change '**BDF**' solver to '**LSODA**' and now it runs without errors, but unfortunately LSODA is much slower than BDF, so I loose lot of the acceleration from numba..
