### ISSUE TITLE
Potential memory leak? (Potentially related to `Generator` type)

### ISSUE THREAD

**Issue by thomasWeise** [numba/numba#9103]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Dear numba Team.

I am not sure whether I found an actual error or whether the error is on my side.
Therefore, I am sorry to disturb your work and take your time.

If I execute the code below, then the python process will slowly consume more and more memory until it eventually crashes.
Notice the program has an endless loop, but it does not explicitly allocate any new object.

Expectation: Program runs forever but does not consume excessive memory.

Observation: The memory consumption is ever-increasing (found with the `top` program).

Note: If I remove the `@numba.njit`, the memory consumption remains normal.

```python

from typing import Final

import numba  # type: ignore
import numpy as np
from numpy.random import Generator


@numba.njit
def swap_2_or_flip(random: Generator, dest: np.ndarray,
                   x: np.ndarray) -> None:
    """
    Copy `x` into `dest` and swap two different values or flip a sign.

    :param random: the random number generator
    :param dest: the array to receive the modified copy of `x`
    :param x: the existing point in the search space
    """
    dest[:] = x[:]  # First, we copy `x` to `dest`.
    length: Final[int] = len(dest)  # Get the length of `dest`.

    i1: Final[int] = random.integers(0, length)  # first random index.
    v1: Final = dest[i1]  # Get the value at the first index.

    if random.integers(0, 2) == 0:  # With p=0.5, we flip the sign of v1.
        dest[i1] = -v1  # Flip the sign of v1 and store it back at i1.
        return  # Quit.

# Swap two values. Now, normally we would repeat the loop until we find a
# different value. However, if we have signed permutations, it may be
# possible that all values currently are the same. To avoid an endless loop,
# we therefore use a sufficiently large range.
    for _ in range(10 + length):
        i2: int = random.integers(0, length)  # Get the second random index.
        v2 = dest[i2]  # Get the value at the second index.
        if v1 != v2:  # If both values different...
            dest[i2] = v1  # store v1 where v2 was
            dest[i1] = v2  # store v2 where v1 was
            return  # Exit function: we are finished.
    # If we get here, probably all elements are the same, so we just...
    dest[i1] = -v1  # ...flip the sign of v1 and store it back at i1.


rand = np.random.default_rng(10)
xx = np.array(range(10), int)
out = np.empty(len(xx), int)

while True:
    swap_2_or_flip(rand, out, xx)
```

Interestingly, the same issue (increased memory consumption) still happens if I just do

```python
import numba  # type: ignore
import numpy as np
from numpy.random import Generator


@numba.njit
def swap_2_or_flip(random: Generator, dest: np.ndarray,
                   x: np.ndarray) -> None:
    i = len(dest)

rand = np.random.default_rng(10)
xx = np.array(range(10), int)
out = np.empty(len(xx), int)

while True:
    swap_2_or_flip(rand, out, xx)
```

It stops happening if I do:

```python
import numba  # type: ignore
import numpy as np
from numpy.random import Generator


@numba.njit
def swap_2_or_flip(dest: np.ndarray,
                   x: np.ndarray) -> None:
    i = len(dest)

rand = np.random.default_rng(10)
xx = np.array(range(10), int)
out = np.empty(len(xx), int)

while True:
    swap_2_or_flip(out, xx)
```

Therefore, I think, the problem *might* be related to the `Generator` type?

Here you can find the versions of libraries potentially related to the issue:

```
numpy 1.24.4
numba 0.57.1
intel-cmplr-lib-rt 2023.2.0
matplotlib 3.7.2
psutil 5.9.5
scikit-learn 1.3.0
scipy 1.11.1
```

My Ubuntu Linux system information is as follows:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

os.name: Linux
os.release: 5.19.0-50-generic
os.version: 50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023
```

My python version is as follows:

```
Python 3.10.6
python.version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
python.implementation: CPython
```

Other software versions are:

```
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Again, I am not sure whether any of this is relevant or whether the mistake is on my side.

All the best,
   Thomas.

[bug.zip](https://github.com/numba/numba/files/12190661/bug.zip)

**Comment by guilhermeleobas** [comment]
Hi @thomasWeise, thanks for the report. I can confirm the bug.

Reproducer:

```python
import numba  # type: ignore
import numpy as np
from numpy.random import Generator


@numba.njit
def swap_2_or_flip(random: Generator):
    return

rand = np.random.default_rng(10)

while True:
    swap_2_or_flip(rand)
```

Upon inspecting NRT stats, all allocations using the Numba runtime are freed:

```
import numba  # type: ignore
import numpy as np
from numpy.random import Generator
from numba.core.runtime import rtsys, _nrt_python

_nrt_python.memsys_enable_stats()

@numba.njit(no_cfunc_wrapper=True)
def foo(random: Generator):
    return

rand = np.random.default_rng(10)

for i in range(1000):
    foo(rand)
new_stats = rtsys.get_allocation_stats()
print(new_stats)
# nrt_mstats(alloc=1000, free=1000, mi_alloc=1000, mi_free=1000)
```

Wonder if the memory leak happens at the CPython wrapper.

**Comment by thomasWeise** [comment]
Thank you, @guilhermeleobas.

**Comment by guilhermeleobas** [comment]
@kc611, you worked on the NumPy generator. Do you have any idea where the leak is happening?

**Comment by thomasWeise** [comment]
Hi.
With numba 58.1, I can still reproduce this problem.
Is there any way to work around it?

**Comment by guilhermeleobas** [comment]
Sorry Thomas, I am not aware of any work around.

cc @kc611 for visibility

**Comment by thomasWeise** [comment]
Thank you @guilhermeleobas.

I admit I just wanted to ping this issue in the hope that it will not fall out of focus.
On my side, I think the possibility to use `Generator`s directly in `numba` code is incredibly cool.
It would make my code much faster.
It is exactly what I want.

The fact that this very cool feature is basically not usable because it will crash my Python, take down the executing shell, and sometimes even the computer running it ... is saddening.
It means that this beautiful feature is sitting right there but it cannot be used in *any* application.
The only reason why compiling code using `Generator`s would make any sense is if that code is run often.
But if it runs often, it will cause the programs to crash.

Could you point me to wherever this compilation happens?
I do not understand the numby project structure, but if you could tell in which repo/file stuff happens, maybe I can weasel myself into it? (estimated <10% chance of success)
I assume that it will do some `C` magic somewhere.
Now my `C` is very rusty (over 20 years old), but maybe it won't hurt if another set of eyes look over the code.
While I think I can most likely not be of any help, I''d be glad to at least take a look and try...

**Comment by tsangwpx** [comment]
confirm this on v59.0

**Comment by andryandrew** [comment]
I'm also affected by this bug. A partial workaround, if the code structure permits it, is to put the repeated calls to the function into another `jit`'ed function.

**Comment by andryandrew** [comment]
I found another workaround. It is possible to unpack the `BitGenerator` manually and define a custom random generator function by passing the ctypes state, like is done [here](https://numpy.org/doc/stable/reference/random/examples/numba.html) (example ♯2 for a substitute of the OP's `rng.integer` support). By copying from https://github.com/numba/numba/blob/main/numba/np/random/new_distributions.py , it is possible to adapt all the other methods too. In my case, I needed the `standard_exponential` which worked like a charm.

**Comment by thomasWeise** [comment]
From my perspective, I'd say the jitting of numpy.random.Generator parameters should no longer be permitted.
There might be dozens of libraries and programs out there that now have memory leaks and maybe don't even know it.

It would be better if trying to jit a function with a numpy.random.Generator directly raises an exception.
Then people can immediately see: OK, I cannot jit this function.
Then it will run a bit slower.
That's OK.

At least it seems to me that there always is the memory leak when you jit such a function.
This means that anybody doing this will have a memory leak in their code.
Compared to simply not being able to jit the function, that's a much bigger problem.
Maybe it does not show up in unit tests but crashes the real application after half an hour when you are no longer looking (as it was the case for me), maybe after hours, maybe after days.
Finding this problem is then very hard.

My suggestion would be that if fixing the problem is not feasible right now (which is totally OK and fine), then maybe for now the feature could be disabled altogether.

**Comment by stuartarchibald** [comment]
Thanks for the report. I debugged this a bit, seems like there's a few reference leaks in the unboxing code for the `BitGenerator`:
https://github.com/numba/numba/blob/301ba23116864ef66a2caccfab7c7123e7bcbcfc/numba/core/old_boxing.py#L1147-L1148
here:
https://github.com/numba/numba/blob/301ba23116864ef66a2caccfab7c7123e7bcbcfc/numba/core/old_boxing.py#L1241
and here:
https://github.com/numba/numba/blob/301ba23116864ef66a2caccfab7c7123e7bcbcfc/numba/core/old_boxing.py#L1246

Patching these locally seems to prevent most of the issue, but I then noticed a smaller continuous consumption of memory (filed as #9733). I have patches locally and plan on fixing both for 0.61.

**Comment by thomasWeise** [comment]
Dude, you are a hero.
I really, really like this feature, because it is basically what I need to make my code much much faster.
I was so sad when it turned out to kill my code instead (after passing all unit tests just fine).
If that works with the next release, it would just be awesome.
Many thanks.

**Comment by stuartarchibald** [comment]
No problem, the leaks should be fixed via the PRs referenced above. They are in the 0.61.0-rc1 milestone (upcoming release) which means as long as there's nothing unexpected, 0.60.0 will contain fixes for this issue. Thanks for using Numba!
