### ISSUE TITLE
jit() on exec() code doesn't find modules properly

### ISSUE THREAD

**Issue by jason-s** [numba/numba#911]
I get this error when referring to numba.types in jit(exec(sourcecode)) where sourcecode imports numba.types:

```
AttributeError: Failed at analyzing bytecode
'object' object has no attribute 'types'
```

If I bail on trying to exec() sourcecode and use a function directly defined in Python, I don't have this problem. Here are two files that show the issue:

https://gist.github.com/jason-s/bc7cf5742de14ab52479

This is numba 0.16.0 running on Windows 7

**Comment by pitrou** [comment]
@jason-s, can you confirm the suggestion above fixes your issue?
