### ISSUE TITLE
 ValueError: cannot compute fingerprint of empty list

### ISSUE THREAD

**Issue by Peter230655** [numba/numba#9110]
When I try to run the program below. I get this error:
_ValueError: cannot compute fingerprint of empty list_
I am using numba version 0.57.0
I believe, this issue was adressed in issue #4280, which was closed.
Still, I am getting this error.

Thanks for any help!

```
# Tower of Hanoi'''

n = 25  # Number of rings

start = time.time()

@njit
def hanoi(n, source, helper, target):
    global k
    
    k += 1    # number of iterations through hanoi
    if n > 0:
# move tower of size n-1 from source to helper
        hanoi(n - 1, source, target, helper)
# move disk from source to target
        if source:
            target.append(source.pop())
# move tower of size n-1 from helper to target
        hanoi(n - 1, helper, source, target)
    
def kurve(x, a, b):   # curve to fit the running times
    return a * np.exp(b * x)

laufzeiten = []
iterations = []
for i in range(n):
    anfang = time.time()
    source = list(reversed(range(1, i+2)))
    target = []
    helper = []
    k = 0       # counts the number of iterations = how often hanoi is called
    hanoi(len(source), source, helper, target)
    laufzeiten.append(time.time() - anfang)
    iterations.append(k)

popt, _ = curve_fit(kurve, np.array(range(1, n+1)), np.array(laufzeiten))

fig, ax = plt.subplots(figsize=(12,8))
ax.plot(range(1, n+1), kurve(np.array(range(1, n+1)), popt[0], popt[1]), color='blue', label='Curve to fit running time')
ax.scatter(range(1, n+1), laufzeiten, marker='s', color='green', label='Running time in sec')
ax.tick_params(axis='y', labelcolor='blue')
ax.set_xlabel('Number of pieces in the tower', fontsize=15)
ax.set_ylabel('Running time on iPad in sec', fontsize=15, color='blue')
ax.legend()

ax1 = ax.twinx()
ax1.scatter(range(1, n+1), iterations, marker='>', color='red', label='Iterationen')
ax1.tick_params(labelcolor='red')
ax1.set_ylabel('Number of moves of pieces', fontsize=15, color='red')
fig.tight_layout()
ax1.legend(loc='center left')

print('Curve_fit estimates are a = {:.9f} and b = {:.4f}'.format(popt[0], popt[1]))
print('Target post filled, only for last n: ',target)
print('\n')
print('it took {:.3f} sec to run the program'.format(time.time() - start))
```

Thanks for opening an issue! To help the Numba team handle your information
efficiently, please first ensure that there is no other issue present that
already describes the issue you have
(search at https://github.com/numba/numba/issues?&q=is%3Aissue).

-->

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by guilhermeleobas** [comment]
Hi @Peter230655, thanks for the report. 

The problem you're seeing is because Numba cannot infer the type of empty lists. To circumvent this limitation, you can replace list by [typed list](https://numba.readthedocs.io/en/stable/reference/pysupported.html#typed-list).

```python
import time
import numpy as np
from numba import njit
from numba.typed import List
from numba import types

# Tower of Hanoi'''

n = 25  # Number of rings

start = time.time()


@njit
def hanoi(n, source, helper, target):
    if n > 0:
        # move tower of size n-1 from source to helper
        hanoi(n - 1, source, target, helper)
        # move disk from source to target
        if source:
            target.append(source.pop())
        # move tower of size n-1 from helper to target
        hanoi(n - 1, helper, source, target)


def kurve(x, a, b):   # curve to fit the running times
    return a * np.exp(b * x)


laufzeiten = []
iterations = []
for i in range(n):
    anfang = time.time()
    source = List(reversed(range(1, i+2)))
    target = List.empty_list(types.int64)
    helper = List.empty_list(types.int64)
    hanoi(len(source), source, helper, target)
    laufzeiten.append(time.time() - anfang)
    iterations.append(i)
```

**Comment by Peter230655** [comment]
Thanks a lot!!
It sped up the calculations by a factor of  3 in my example of 25 rings - MUCH more with more rings.

I had a global variable k to count the number of iterantions, which you kicked out.
When I put it back in, I got this error message:

_UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (STORE_GLOBAL) found_

Again, thanks a lot!

**Comment by guilhermeleobas** [comment]
> UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (STORE_GLOBAL) found

It doesn't seem to be possible to mutate a global variable inside a jit region.

**Comment by Peter230655** [comment]
Thanks!
I am absolutely new to numba. I interpret your reply to say that 'global' does not normally work with numba.
( I have read somewhere, that using 'global' is to be avoided anyway in good programming. )

**Comment by guilhermeleobas** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
