### ISSUE TITLE
'import numba' fails: SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by yurivict** [numba/numba#9130]
```
Traceback (most recent call last):
  File "/usr/ports/science/py-hiphive/x.py", line 5, in <module>
    import numba
  File "/usr/local/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

I couldn't try numba-0.57.1 because of this error:
> ImportError: Numba needs NumPy 1.24 or less

and we have numpy-1.25.0 in the ports tree.

numba-0.56.2
FreeBSD 13.2

**Comment by esc** [comment]
@yurivict thank you for reporting this. Currently, no released version of Numba supports NumPy 1.25.

**Comment by esc** [comment]
We will close this now. Next release of Numba 0.58 will support 1.25.

**Comment by yurivict** [comment]
@esc Do you know when the next release is due?

**Comment by VitaliyaIoffe** [comment]
> @esc Do you know when the next release is due?

+1, waiting for the release

**Comment by timohouben** [comment]
+1

**Comment by esc** [comment]
An RC2 was published recently: https://numba.discourse.group/t/ann-numba-0-58-0rc1-and-llvmlite-0-41-0rc1/2078/4
