### ISSUE TITLE
Delegate np.zeros to numpy

### ISSUE THREAD

**Issue by fingoldo** [numba/numba#9132]
Got myself in a situation when after jitting np.zeros becomes much slower.
Can we please delegate the call to numpy's implementation?

I love how numba's a[:, :] = 0 outperforms everything else when zeroing an existing array, but creation of new one is not great. This has been [noticed](https://stackoverflow.com/questions/61359606/numba-and-numpy-array-allocation-why-is-it-so-slow) and [explained](https://stackoverflow.com/questions/44487786/performance-of-zeros-function-in-numpy) by numpy using the _culloc_ func. .fill() is also for some reason twice slower inside njit, but .zeros() is even more so.

```python
shape = (10000, 10000)
a = np.zeros(shape, dtype=np.int64)

def alloc_new(a):
    for _ in range(10):
        a = np.zeros(shape, dtype=np.int64)
        a[500, 500] = 1
    return a

def numpy_fancy_assign(a):
    for _ in range(10):
        a[:, :] = 0
        a[500, 500] = 1
    return a

def numpy_fill(a):
    for _ in range(10):
        a.fill(0)
        a[500, 500] = 1
    return a

def cyclces_assign(a):
    for _ in range(10):
        for i in range(a.shape[0]):
            for j in range(a.shape[1]):
                a[i, j] = 0
        a[500, 500] = 1
    return a

njitted_funcs = []
funcs = (alloc_new, numpy_fancy_assign, numpy_fill, cyclces_assign)
for func in funcs:
    njitted_func = njit(func)
    njitted_func(a)  # test call
    njitted_funcs.append(njitted_func)
```

%timeit njitted_funcs[0](a)
**2.28 s** ± 42.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit njitted_funcs[1](a)
_58.2 ms_ ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit njitted_funcs[2](a)
563 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit njitted_funcs[3](a)
603 ms ± 41.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit funcs[0](a)
**357 µs** ± 41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit funcs[1](a)
305 ms ± 9.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit funcs[2](a)
305 ms ± 7.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by esc** [comment]
@fingoldo thank you for submitting this. Unfortunately the script has the imports and the timing calls omitted. To ease with reproduction, please edit the submission here is a single self-contained script, (needs to be executed with ipython):

```
import numpy as np
from numba import njit

shape = (10000, 10000)
a = np.zeros(shape, dtype=np.int64)


def alloc_new(a):
    for _ in range(10):
        a = np.zeros(shape, dtype=np.int64)
        a[500, 500] = 1
    return a


def numpy_fancy_assign(a):
    for _ in range(10):
        a[:, :] = 0
        a[500, 500] = 1
    return a


def numpy_fill(a):
    for _ in range(10):
        a.fill(0)
        a[500, 500] = 1
    return a


def cyclces_assign(a):
    for _ in range(10):
        for i in range(a.shape[0]):
            for j in range(a.shape[1]):
                a[i, j] = 0
        a[500, 500] = 1
    return a


njitted_funcs = []
funcs = (alloc_new, numpy_fancy_assign, numpy_fill, cyclces_assign)
for func in funcs:
    njitted_func = njit(func)
    njitted_func(a)  # test call
    njitted_funcs.append(njitted_func)

print("%timeit njitted_funcs[0]")
%timeit njitted_funcs[0]

print("%timeit njitted_funcs[1]")
%timeit njitted_funcs[1]

print("%timeit njitted_funcs[2]")
%timeit njitted_funcs[2]

print("%timeit njitted_funcs[3]")
%timeit njitted_funcs[3]

print("%timeit funcs[0]")
%timeit funcs[0]

print("%timeit funcs[1]")
%timeit funcs[1]

print("%timeit funcs[2]")
%timeit funcs[2]
```

**Comment by esc** [comment]
Here are the results for my machine:

```
%timeit njitted_funcs[0]
676 ms ± 18.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit njitted_funcs[1]
13.6 ms ± 496 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit njitted_funcs[2]
136 ms ± 4.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit njitted_funcs[3]
260 ms ± 16.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit funcs[0]
131 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
%timeit funcs[1]
272 ms ± 4.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit funcs[2]
273 ms ± 18.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
ipython issue_9132.ipy  50.11s user 15.65s system 100% cpu 1:05.62 total
```

**Comment by esc** [comment]
@gmarkall thank you, closing as duplicate.
