### ISSUE TITLE
Incorrect type inference for shift operators

### ISSUE THREAD

**Issue by ovolve** [numba/numba#9133]
## Reporting a bug

- [ x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The following code fails to compile with the error
**No implementation of function Function(<built-in function rshift>) found for signature: >>> rshift(float64, Literal\[int\](1))**, incorrectly inferring that `x` is a `float64` when it should be a `uint64`.

```
@jitclass
class Class:
    x: uint64
    def __init__(self, x: uint64):
        self.x = x

@njit
def f() -> uint64:
    obj = Class(1)
    x = obj.x
    for _ in range(1):
        x = x >> 1  # or <<
        x = x + 1
    return x

f()
```

As far as I can tell, all of the following components are necessary to trigger the bug:
* The variable is a member of a `jitclass` 
* The shift is in a loop
* There is another operation in the loop

**Comment by ovolve** [comment]
Yes, that works, and in fact it also works without annotating the `1` on the `x >> 1`. It only needs either
`x = unit64(x) >> 1`
or
`x = x + uint64(1)`
and it works as expected.

**Comment by gmarkall** [comment]
I think what you are seeing is the result of how Numba infers types - I think the rationale behind this is explained in https://numba.readthedocs.io/en/stable/proposals/integer-typing.html

**Comment by ovolve** [comment]
Thank you for the link. I read through it and didn't see how it would explain this behavior. In fact, this appears to resemble a situation described in _Current semantics_, which the proposal is intended to rectify:

>In trying to follow the correctness over predictability rule, some values can actually leave the integer realm. For example, int64 + uint64 is typed float64 in order to avoid magnitude losses (but incidentally will lose precision on large integer values…), again following Numpy’s semantics for scalars. This is usually not intended by the user.

All of the behaviors described under _Proposal: predictable width-conserving typing_ suggest to me that it should be inferred to be an `int`.
