### ISSUE TITLE
Check reduction variables for Parfor Fusion

### ISSUE THREAD

**Issue by njriasan** [numba/numba#9139]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The follow kernel produces incorrect Parfor Loop fusion:

```python
@numba.jit(parallel=True)
def impl(A):
        return A / A.max() 

impl(np.linspace(0, 3, 3))
```

This should ouptput
```python
array([0. , 0.5, 1. ])
```
Instead it outputs
```python
array([nan,  1.,  1.])
```
This happens because the `max()` and `/` loops are being fused together. The problem is that inside `try_fuse` there is a comment that says:

```python
# TODO: make sure parfor1's reduction output is not used in parfor2
# only data parallel loops
```

This appears to match this exact case.

**Comment by njriasan** [comment]
@DrTodd13 I would like to submit a PR to fix this issue. I was able to locally verify it works by making the following changes:

1. Adding `get_parfor_params()` to `try_fuse`
2. Adding `get_parfor_reductions()` to `try_fuse`
3. At the end of `try_fuse` adding a check for the reductions that no output reduction from `get_parfor_reductions()` is inside the parfor2 uses.

Conceptually steps 2 and 3 make sense to me, but step 1 seems incorrect. I see that inside `ParforPass.run()` there is a similar call to `get_parfor_params()` with a comment that says:

```python
# prepare for parallel lowering
# add parfor params to parfors here since lowering is destructive
# changing the IR after this is not allowed
```

This suggests to me that this call to params is perhaps unsafe and should happen elsewhere. So my question is, what is the proper way to get the parameters for parfor1 to successfully determine the reduction? I'm happy to add any testing to help with this process.

**Comment by DrTodd13** [comment]
@njriasan Make sure this isn't fixed in main.  If not, then check my recent PRs because I remember that I did something recently on this topic.  It may have been a similar issue and so wasn't associated in github with this one.

You can use get_parfor_params() as many times as you want before lowering and it should be safe.

**Comment by njriasan** [comment]
Looks like this is fixed on main. Thank you @DrTodd13!
