### ISSUE TITLE
NaN inverse raises unexpected ZeroDivisionError

### ISSUE THREAD

**Issue by Ranfir** [numba/numba#9146]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return x**-1

foo(np.array([np.nan])) # array([nan])
foo(np.array([np.nan], np.float32)) # ZeroDivisionError: division by zero
```
Tested under python 3.10.9. This behavior appears in 0.57.1, but is not present in 0.56.4. Setting `fastmath=False` per #8889 doesn't change this behavior.

**Comment by stuartarchibald** [comment]
Thanks for the report. Unfortunately this doesn't seem to reproduce for me, I've tested it on a couple of systems with different configurations. There are some issues with `pow` as noted in #7012, it might be another issue in the implementation that moving to LLVM 14 has highlighted.
