### ISSUE TITLE
Mismatching `@jit` signature falls back on object mode

### ISSUE THREAD

**Issue by pitrou** [numba/numba#915]
This is a bit surprising and confusing:

```
>>> def f(x, y): return x+y
... 
>>> jit(int32(int32,))(f)
CPUOverloaded(<function f at 0x7fafa3c3fbf8>)
```

Here, the signature is obviously wrong (one argument type is given for a two-arguments function), but Numba just goes ahead and falls back on object mode. It would be more helpful to raise an error.

**Comment by pitrou** [comment]
Apparently this error is allowed in object mode... test_blackscholes relies on it. Do we want to support it?

**Comment by seibert** [comment]
I'm assuming that blacksholes relies on this behavior on accident due to a bug in the test as well.  We should fix the bug and raise a proper error when the signature doesn't match.
