### ISSUE TITLE
add optional argument to jit() to allow export of generated LLVM code

### ISSUE THREAD

**Issue by jason-s** [numba/numba#916]
from discussion group: I would really like to see exactly what LLVM code was generated by the specific `jit()` action, and not have to use a different unrelated action (`compile_isolated`) to get at the LLVM code.

-----

The `compile_isolated` feature of `numba.compiler.compile_isolated` works nicely, but it leaves me somewhat nervous and unsatisfied that in order to use a function, I have to call/decorate with `numba.jit()` but if I want to read the LLVM I have to use an entirely different mechanism.

Any chance you could add an argument to `numba.jit` like this:

```
@jit(llvm_sink=mysink)
def myfunc(dasher, dancer, prancer, vixen):
   ...
```

where `mysink` just has to meet some simple requirement of your choice (function accepting a string, or a class with a method accepting string, or something that makes sense), and it will receive the LLVM assembly as a byproduct of the `jit()` process? Or lacking that, just a filename:
```
@jit(llvm_log='myfunc.llvm.txt')
def myfunc(dasher, dancer, prancer, vixen):
   ...
```
I would really like to see exactly what LLVM code was generated by the specific `jit()` action.

**Comment by pitrou** [comment]
This was fixed in a different way by #960. Basically you now have `inspect_llvm` and `inspect_asm` methods over compiled functions, which will give you the desired info.
