### ISSUE TITLE
`template.path` doesn't point to source code location in `overload_method`

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9162]
when testing with `overload_method`, it turns out that the type template of `overload_method` has a wrong implementation in `get_source_code_info`, since the attribute `path` in it will point to `numba/core/typing/templates.py`, rather than the real source code file path which the `overload_method`-ed function is defined.

Need to give you a reproducer later..

And it's related to proceed the cache PR https://github.com/numba/numba/pull/8396, I think.

**Comment by sklam** [comment]
A reproducer will be useful
