### ISSUE TITLE
segfault (crash) when calling numpy np.isnan repeatedly in nopython parallel function

### ISSUE THREAD

**Issue by limwz01** [numba/numba#9167]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

numba crashes when calling numpy `np.isnan` repeatedly in nopython parallel function:
```python
#!/usr/bin/env python3
import numba
import numpy as np


def main():
    bug()


@numba.njit(parallel=True)
def bug():
    for j in range(50000):
        np.isnan(np.full(1, 0.0))


if __name__ == "__main__":
    main()
```

Result with Python 3.8 on Ubuntu 20.04 (other versions may need different number of iterations?):
```
Segmentation fault (core dumped)
```

**Comment by sklam** [comment]
I can confirm the segfault on OSX with py3.9 after increasing number of iteration to `5000000`.

**Comment by sklam** [comment]
This is another instance of https://github.com/numba/numba/issues/9029 and will be fixed by https://github.com/numba/numba/pull/9048.
