### ISSUE TITLE
[Discuss] generates extra branches in LLVM IR 0.57.1

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9186]
Coming from https://matrix.to/#/!kKkfrNhBPczqpCPTmY:gitter.im/$e-ljAvw88hxAaomrKJY4kZ7b8z9PUcTCkRDHyi9wWbk?via=gitter.im&via=tryp.io&via=matrix.org,

I compared the LLVM IR and ASM between 0.56.3 and 0.57.1. They have a big difference, which I think it could(?) hurt the performance in 0.57.1:

In LLVM IR for many user-defined functions in 0.57.1, it has a branch `common.ret`, which contains a new phi node; but in 0.56.3, different branches can return by its own. (this `common.ret` branch is generated in many (or most) functions in my large benchmark)

And I checked related ASM for user-defined functions, I believed that the ASM in 0.57.1 does have more branches than 0.56.3.

I think it should be related to `excinfo` logic changes in numba and llvmlite, and also related to llvm upgrade from 11 to 14. Any idea about this? 
gentle cc @sklam @apmasell

**Comment by dlee992** [comment]
For my end, 
1. I has a workaround to optimize the point 1, by using `opt=1` in codegen.py. 
2. But don't know how to optimize the point 2.

And another question about `excinfo`, why and which PR is the change from `{ i8*, i32, i8* }** noalias nocapture %excinfo` to `{ i8*, i32, i8*, i8*, i32 }** noalias nocapture writeonly %excinfo`?

**Comment by dlee992** [comment]
After some digging, `excinfo` changes should be related to 2 PRs which changes some logic in `callconv.py`

1. #8134
2. #8535

**Comment by dlee992** [comment]
For the point 1, another workaround is removing `pm.add_jump_threading_pass()` in `codegen.py` for llvm14. It can remove  some branches and generate select IR for this example as well.

**Comment by guilhermeleobas** [comment]
Hi @dlee992, the `excinfo` changed in https://github.com/numba/numba/pull/8134 to support dynamic exceptions. You can see the details in the pull request, but basically Numba added two new fields to the existing struct to store dynamic values. 

> For example, I noticed in IR for NRT_incref, which has the new branch common.ret, compared to 0.56.3

The [code](https://github.com/numba/numba/blame/main/numba/core/runtime/nrtdynmod.py#L41-L60) for `NRT_incref` hasn't changed in 8 years. Perhaps LLVM was able to optimize away the `common.ret` branch? By the way, this is the LLVM IR I get in Numba 0.55/0.56:
```llvm; Function Attrs: nofree noinline norecurse nounwind
define linkonce_odr void @NRT_incref(i8* %.1) local_unnamed_addr #2 {
.3:
  %.4 = icmp eq i8* %.1, null
  br i1 %.4, label %.3.if, label %.3.endif, !prof !1

.3.if:                                            ; preds = %atomicrmw.start, %.3
  ret void

.3.endif:                                         ; preds = %.3
  br label %atomicrmw.start

atomicrmw.start:                                  ; preds = %atomicrmw.start, %.3.endif
  %0 = bitcast i8* %.1 to i64*
  %1 = tail call i64 @llvm.aarch64.ldxr.p0i64(i64* nonnull %0)
  %new = add i64 %1, 1
  %2 = tail call i32 @llvm.aarch64.stxr.p0i64(i64 %new, i64* nonnull %0)
  %tryagain.not = icmp eq i32 %2, 0
  br i1 %tryagain.not, label %.3.if, label %atomicrmw.start
}
```

**Comment by stuartarchibald** [comment]
I'm pretty sure that generation of "common" return blocks came from adoption of/upgrade to LLVM 14, it's "block tail merging" from `Transforms::Scalar::SimplifyCFGPass::performBlockTailMerging`. Numba's reference pruning passes in `llvmlite` had to be updated to accommodate this.

**Comment by gmarkall** [comment]
Related option: https://github.com/numba/numba/issues/8430 ?

**Comment by dlee992** [comment]
Really hard to provide an example to show IR/ASM diff and performance degradation at the same time. I will try...

But could you show me how to remove `common.ret` branch, instead let each branch coming to this just directly returns for itself. How to hack numba, llvmlite, or llvm? Literally, reverse the impact of `Transforms::Scalar::SimplifyCFGPass::performBlockTailMerging`, unmerge it... If I can do this, then I can rerun latency test, then  we can indirectly check if this extra branch hurts the performance?

**Comment by dlee992** [comment]
Hi, @gmarkall @guilhermeleobas @gmarkall . 

I tried to provide an example to show the IR diff and performance regression.

Here includes 4 files https://gist.github.com/dlee992/ba3db06e6561ca7d91490f2c38c2ed27
One is the python file, what is running the gaussian function, others are testing cmd, IR&ASM for 0.56.4 and 0.58.0.
Basically, you can see ~ 4% performance regression when running this script multiple times.
I have to say, the `timeit` is not very stable, sometimes, 0.58.0 is faster than 0.56.4. But in most cases, I feel 0.56.4 is faster.

And I think the main cause is the extra branch `common.ret`, it also affects the ASM, makes the ASM have extra branch as well.

**Comment by sklam** [comment]
@dlee992, I tried your script. At first, I am getting the 4% difference. After trying different llvmlite versions and numba versions, suddenly the script no longer produces the 4% difference. In fact, sometimes it's the newer numba and llvmlite versions that are producing better performance.  

<details>
<summary>The modified script:</summary>

```python
import math
import os
from timeit import timeit
from functools import partial
import numpy as np

import numba
from numba import njit

os.environ["NUMBA_DUMP_OPTIMIZED"] = "1"
os.environ["NUMBA_DUMP_ASSEMBLY"] = "1"

@njit
def gaussian(x, mu, sigma):
    coefficient = 1 / (sigma * math.sqrt(2 * math.pi))
    exponent = -((x - mu) ** 2) / (2 * (sigma ** 2))
    return coefficient * math.exp(exponent)

mean = 0.0
std_deviation = 1.0
x = 1.0
result = gaussian(x, mean, std_deviation)
print(f"f({x}) = {result:.6f}")

ga = partial(gaussian, x, mean, std_deviation)


print(f"{numba.__version__}: {timeit(ga, number=50_000_000)}")

times = []
for _ in range(10):
    times.append(timeit(ga, number=50_000_000))

print(times)
print("mean", np.mean(times))
print("stddev", np.std(times))
```

</details>


To help reduce the noise, I slightly modified your script to repeat the `timeit()` for 10 times, and ran it on the follow configurations:

|             | numba | llvmlite | llvm |
|--------|--------|--------|------|
| config 1 | 0.58.0 | 0.41.0 | (14, 0, 6) |
| config 2 | 0.56.4 | 0.40.0 | (14, 0, 6) |
| config 3 | 0.56.4 | 0.39.1 | (11, 1, 0) |

Result samples:

On config 1:

```
[7.662383125, 7.647548916999998, 7.654502375, 7.634112834, 7.629486333000003, 7.6543646249999995, 7.6237393749999995, 7.6474195420000015, 7.652181208000002, 7.639226874999991]
mean 7.644496520900001
stddev 0.01177326530497024
```

On config 2:

```
[7.287940832999999, 7.278479667000001, 7.291535959000001, 7.227093457999999, 7.355575459000001, 7.330579374999999, 7.2697380839999965, 7.290797332999993, 7.285666165999999, 7.288532500000002]
mean 7.290593883399998
stddev 0.032360418128370004
```


On config 3:
```
[7.611829208, 7.632908708000002, 7.620016458999999, 7.626093874999999, 7.6489904999999965, 7.701432208, 7.699524124999996, 7.635975916, 7.619798625000001, 7.609852082999993]
mean 7.6406421707
stddev 0.03188029291876236
```

Even with the repeated `timeit`, the script is still quite sensitive to system load. The numbers can change quite a bit between execution. I cannot determine if there is a difference given the noise.

When comparing the assembly, there are small differences between llvm 14 vs llvm 11 but I am not sure it would have an observable impact to the runtimes.

**Comment by dlee992** [comment]
Thanks for your detailed testing! Sry for providing this unstable script. 

but does the result of config 2 show that 0.56.4 is a little better than 0.58.0 for this script? It's similar as I did in my customized numba, I use numba 0.57.1 but revert #8130 and #8535 (which makes it nearly equals to 0.56.4), llvmlite 0.39.1, and llvm 11.1.0. 
But I didn't expect config 2 is better, but config 3 is similar as config 1. Hard to explain.
I will keep an eye on this issue, and if I find a more stable script, will provide it again.

**Comment by dlee992** [comment]
Then maybe we should close this for now?

**Comment by sklam** [comment]
> I use numba 0.57.1 but revert #8130

I think you mean https://github.com/numba/numba/pull/8134

**Comment by dlee992** [comment]
Hi, @sklam. Thanks again! This time, I brought more experimental results to show the version regression.

Based on your revised script, I tried to plot the distribution of running time with different configs. And most importantly, I **pin the CPU** to run these experiments (using an isolating CPU) to avoid the noise and make it more **statistically sound** as best as I can. And I think this result can be stably reproducible.

Here is my revised script, main change is that I adjust the iteration times of the outer loop and the inner timeit.
```python
import math
import os
from timeit import timeit
from functools import partial
import numpy as np
import pandas as pd
import numba
from numba import njit

@njit
def gaussian(x, mu, sigma):
    coefficient = 1 / (sigma * math.sqrt(2 * math.pi))
    exponent = -((x - mu)**2) / (2 * (sigma**2))
    return coefficient * math.exp(exponent)

mean = 0.0
std_deviation = 1.0
x = 1.0
result = gaussian(x, mean, std_deviation)
print(f"f({x}) = {result:.6f}")

ga = partial(gaussian, x, mean, std_deviation)

print(f"{numba.__version__}: {timeit(ga, number=50_000)}")  # run first time

times = []
for _ in range(int(1e4)):
    times.append(timeit(ga, number=50_000))

# print(times)
print("mean", np.mean(times))
print("stddev", np.std(times))
```
Then I plot the distribution of 3 configs as you listed:
![image](https://github.com/numba/numba/assets/8125675/7f53b5bf-385b-46db-a968-b6e1656a317f)

In this result, config 1 (0.58.0) has 10% performance regression compared with config 3 (0.56.4), and config 2 is the slowest. I didn't expect 10%, maybe we can turn on some acceleration options, such as `FASTMATH`, etc. But the regression should still exist if we keep the same acceleration options for different configs.

**Comment by sklam** [comment]
That's very useful for debugging the problem. As previously i tried to revert commits and git bisect to find the source but it is very hard to pick from the noise. Let me see if i can replicate your results on my machine.

**Comment by sklam** [comment]
@dlee992, here's my result:

![Screenshot 2023-09-29 at 8 59 52 AM](https://github.com/numba/numba/assets/1929845/be6b538e-7cb7-4855-876a-65a4623cb5d5)

Note the `dev0` ones are mesuring on the dev label. A `0.57.0dev0` will be one commit after the branching of `0.56.0`. The `0.59.0dev0` label will be right after the 0.58 release.

I don't think this benchmark is revealing anything here. For instance:
- `nb57dev0-llvm14`, which is the same as 0.56, has a different performance than 0.56 with either llvm versions.
- The start of the 0.58 cycle (`nb58dev0-llvm14`) is worst but by the end of the release cycle (`nb59dev0-llvm14`) it becomes better again.

I think we are measuring CPU throttling.

**Comment by dlee992** [comment]
Thanks! I don't know why my results show `nb56_4 `(`config 3`) is better than `nb58_0` (`config 1`), but your results always don't. But anyway, appreciate for your following up! Maybe new version has already overcame this issue for me. Will try upgrade again.

**Comment by stuartarchibald** [comment]
I managed to reproduce the performance difference noted in the OP. I then looked at the assembly reported by LLVM (via `.inspect_asm()` on the dispatcher) and noted that the only material difference was in the `cpython` wrapper, the `nopython` function was the same. I then tested the performance running the code on HEAD and 0.56 via the `cfunc` wrapper and the performance was the same, which suggested the difference was in the `cpython` wrapper. I then started reducing the code and found that a simple NOP function exhibited the same behaviour (locally).
```python
from functools import partial
from timeit import timeit
from numba import njit

def gauss():
    pass

ga = partial(gauss())
print("time = ", timeit(ga, number=50_000_000)
```
The main differences between HEAD and 0.56 are 1. the change to the exception handling 2. that LLVM 14 generates common return blocks in the IR, so I started looking at the impact of this. I then disassembled the in-memory binary as linked by MCJIT for HEAD and 0.56 to try and see what was going on. I did it at this level to make sure that e.g. padding and layout were taken into consideration. Having looked at the binaries, it seems like HEAD generates machine code for the wrapper where the "exception" from unboxing the args tuple and the "success" return path are a) shared and b) is located immediately after assembly of the item to return. In pseudo code it looks like this:
```
    call PyArg_UnpackTuple
    if call failed goto 10
    test for env pointer
    if failed goto 20
    call main()
    call PyIncRef on Py_NoneStruct
10  do return stuff # shared path for PyArg_UnpackTuple and "success"
    return
20  do stuff for return env pointer missing
    return
```
whereas in 0.56 the unboxing from the args tuple and the "success" return path are a) separate and essentially duplicated and b) the "exception" return is located after the standard return. In pseudo code it looks like this:
```
    call PyArg_UnpackTuple
    if call failed goto 20
    test for env pointer
    if failed goto 10
    call main()
    call PyIncRef on Py_NoneStruct
    do return stuff for "success"
    return
10  do return stuff for env pointer missing
    return
20  do return stuff for failed PyArg_UnpackTuple
    return
```
From this I guessed at it being potentially to do with branch prediction/binary layout, so ran the sample through `perf stat` and found that the on 0.56 0.33% of all branches are branch-misses whereas on HEAD it's 0.46%.  I guess this is enough to cause the minor differences and also to perhaps make it quite hard to track and potentially hardware and hardware-state specific.

**Comment by dlee992** [comment]
Wonderful explanation! @stuartarchibald then this is a `feature` in the new version or a `bug`/`enhancement` which could be fixed or improved? A very interesting and subtle case!

**Comment by dlee992** [comment]
Updates for my internal tests: I tried to upgrade numba to 0.58.1 and remove the changes in `callconv.py` in #8535 , but keep using llvmlite 0.39.1 with llvm 11.1.0. The performance doesn't have degradation. Just in case anyone meets the same issue as me.

**Comment by dlee992** [comment]
Update again: After I tried another customised/tricky optimization internally, this issue doesn't stand any more. I can get the same speed with the numba 0.58.1 and corresponding llvmlite and llvm. 
I think I can close this for now.
