### ISSUE TITLE
`get_allocation_stats` needs an init guard in 0.57.x, since new envvar `NRT_STATS`

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9188]
```python
    def get_allocation_stats(self):
        """
        Returns a namedtuple of (alloc, free, mi_alloc, mi_free) for count of
        each memory operations.
        """
        # No init guard needed to access stats members <--------- this assumption is broken in 0.57.1, I think, since stuart's new PR about NRT_STATS
        return _nrt_mstats(alloc=_nrt.memsys_get_stats_alloc(),
                           free=_nrt.memsys_get_stats_free(),
                           mi_alloc=_nrt.memsys_get_stats_mi_alloc(),
                           mi_free=_nrt.memsys_get_stats_mi_free())

```
When you try this:
```bash
python -c "import os; os.environ['NUMBA_NRT_STATS'] = '1'; from numba import config; print(config.NRT_STATS); import numba; rtsys = numba.core.runtime.rtsys; print('[NRT] before:' + str(rtsys.get_allocation_stats())); print('numba.__version__', numba.__version__)"
1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "numba/core/runtime/nrt.py", line 110, in get_allocation_stats
    return _nrt_mstats(alloc=_nrt.memsys_get_stats_alloc(),
RuntimeError: NRT stats are disabled.
```

Related with #8235 , in 0.56.x, this bash won't have this exception.

gentle cc @stuartarchibald

**Comment by dlee992** [comment]
But `rtsys.initialize(...)` need a context argument, not sure which fix is better for this issue. Maybe we need a dummy context, or a separate method for opening NRT_STATS for nrt.

**Comment by guilhermeleobas** [comment]
Hi @dlee992, could you share a code sample that reproduces this error?

**Comment by dlee992** [comment]
@guilhermeleobas 
Execute this cmd `python -c "import os; os.environ['NUMBA_NRT_STATS'] = '1'; from numba import config; print(config.NRT_STATS); import numba; rtsys = numba.core.runtime.rtsys; print('[NRT] before:' + str(rtsys.get_allocation_stats())); print('numba.__version__', numba.__version__)"`
I think you will see the same error like me?

**Comment by guilhermeleobas** [comment]
Yes, sorry! I forgot you shared this example before. 

I think this happens because the NRT was never initialized:
https://github.com/numba/numba/blob/f4c4afcb180193064a0c985246c7c71d007c6b1d/numba/core/cpu.py#L61-L66

If you call any jitted function, the NRT is initialized and your example works:
```python
import os
import numba
import numpy as np
from numba import config

os.environ['NUMBA_NRT_STATS'] = '1'
print(config.NRT_STATS)

rtsys = numba.core.runtime.rtsys

@numba.njit
def foo():
    return np.arange(5)
foo()

print('[NRT] before:' + str(rtsys.get_allocation_stats()))
print('numba.__version__', numba.__version__)
```

**Comment by dlee992** [comment]
Yes, thanks for your time. But before 0.57, NRT can be used without calling any jitted function first, and in principle, NRT stats should be a global stats, no need to call jitted function first? So I want to discuss whether we can keep this behaviour as before.

**Comment by stuartarchibald** [comment]
The NRT initialisation was made lazy in 0.57 to improve import time (so as to not start compiling things just because an `@njit` decorated function is encountered) and also compilation time in the case of compiling for a target where the NRT is not used, xref #8438. The NRT cannot be used without being initialised and I don't think there's any guarantee made by Numba about the state of it. I think it's fine to make a change so it's more clear what the problem is in the above case. Let's discuss at the meetings as noted by @guilhermeleobas.

**Comment by dlee992** [comment]
close this for now. looks like no similar complaint about this.

**Comment by nelson2005** [comment]
This bit me as well in 0.60.0.  it's pretty unintuitive.
