### ISSUE TITLE
Numba needs NumPy 1.25 or less

### ISSUE THREAD

**Issue by afuentes09651** [numba/numba#9201]
## Feature request

I am trying to use DeepSurv, which has a dependency on Numba. When I run it on my databricks platform, I am getting an error message stating that Numba needs NumPy 1.25 or less. Is there a chance that Numba could support the latest NumPy? I'm afraid I'm unable to downgrade my own, but I believe supporting later NumPy would be beneficial anyways to many people.

**Comment by blakeNaccarato** [comment]
I've been tracking this awhile myself, and [Numpy 1.25 support](https://github.com/numba/numba/issues/8698) is coming in release 0.58.0, slated for "sometime near the middle 2023". We can see that [0.58.0rc2](https://github.com/numba/numba/tree/0.58.0rc2) supports Numpy 1.25 already. It looks to me like the release of 0.58.0 is around the corner, so some alternative solution could be used in the meantime. Maybe:

- Install numba 0.58.0rc2 along with numpy 1.25, and DeepSurv. Possibly using `--no-deps` in installing some of these packages and manually orchestrating dependencies until 0.58.0 is properly out.
- Alternatively, pin your DeepSurv dependency to an earlier version prior to numpy 1.25 for now, and roll it up when 0.58.0 is out?

I'm sure that dependency management is a bit different in databricks, so I'm not sure exactly how this process looks like in that environment. But it looks like the ball is rolling on 0.58.0 so it probably won't be a problem for much longer!

**Comment by gmarkall** [comment]
The latest version of NumPy is 1.26, released two days ago. We are already in the RC phase for Numba 0.58, so NumPy 1.26 support will not make it for 0.58. I will post an update here on NumPy 1.26 plans following the Numba maintainer meeting tomorrow.

**Comment by gmarkall** [comment]
Testing in #9202.

**Comment by gmarkall** [comment]
Summary from the maintainers' discussion:

* Once #9202 has been merged, a new 0.58 point release will be made to provide support for NumPy 1.26 prior to the release of Numba 0.59.
* Doing a point release ASAP isn't something we'd always plan to do for a new NumPy release, but given the timing of this NumPy release and the relatively small set of changes between NumPy 1.25 and 1.26, the effort is estimated to be low enough for it to be feasible and worthwhile.

**Comment by gmarkall** [comment]
Adding to the (newly-created) 0.58.1 milestone.

**Comment by esc** [comment]
> Adding to the (newly-created) 0.58.1 milestone.

Thank you @gmarkall

**Comment by RoyiAvital** [comment]
Thanks to the effort. Having Numba compatible with the latest NumPy in such short time frame is great.

**Comment by esc** [comment]
Please track the 0.58.1 release here: https://github.com/numba/numba/pull/9240/commits it will include NumPy 1.26 support.

**Comment by esc** [comment]
0.58.1 is out now, with 1.26 support:

https://numba.discourse.group/t/ann-numba-0-58-1-and-llvmlite-0-41-1/2219
