### ISSUE TITLE
Memory leak when the @njit decorator is applied

### ISSUE THREAD

**Issue by CCranney** [numba/numba#9212]
# Reporting a bug

## Checklist

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

## package versions

`Python 3.11.4`

For reference, this is what I get when I enter `pip list` at the terminal:
```
Package         Version
--------------- ------------
llvmlite        0.41.0
numba           0.58.0
numpy           1.25.2
pandas          2.1.1
pip             22.3.1
python-dateutil 2.8.2
pytz            2023.3.post1
setuptools      65.5.1
six             1.16.0
tzdata          2023.3
wheel           0.38.4
```

## Description
Hi,

I believe I have found a memory leak issue with numba. In my program it crops up when I use large files, and found it while trying to identify why the memory pressure would get so impactful. I've extracted the necessary code into a self-contained script and boiled it down as best as I could. I apologize it is still about 80 lines long - I tried to reduce that number further, but it then stops capturing the issue.

```python
import tracemalloc
import numpy as np
from numba import njit

def main():
    tracemalloc.start()
    rng = np.random.default_rng()

    originalSequence = sorted(rng.standard_normal(int(1e5)))
    for i in range(1, 3):
        print(f'round{i}')
        for _ in range(100):
            libMzs = originalSequence[:]
            queMzs = originalSequence[:]
            match_library_to_query_pooled_spectra(libMzs, queMzs)
        snapshot = tracemalloc.take_snapshot()
        for x in snapshot.statistics('traceback')[:4]:
            print(x)


@njit
def calculate_parts_per_million_relative_difference(referenceMz, targetMz):
    return (referenceMz - targetMz) * (1e6) / referenceMz


@njit
def is_within_tolerance(ppm, tolerance):
    return abs(ppm) <= tolerance


@njit
def match_query_peak_to_all_succeeding_library_peaks_within_tolerance(
        baselineLibraryIdx: int, libraryPeaks, queryPeak, ppmTolerance
):
    tempLibraryIdx = baselineLibraryIdx + 0

    while tempLibraryIdx < len(libraryPeaks):
        ppm = calculate_parts_per_million_relative_difference(
            libraryPeaks[tempLibraryIdx], queryPeak
        )
        if not is_within_tolerance(ppm, ppmTolerance):
            return
        yield ppm
        tempLibraryIdx += 1
    return

@njit
def numba_enhanced_matching_of_library_to_query_pooled_spectra(
    libraryPeaks, queryPeaks, ppmTolerance
):
    rowNum = 10000000
    data = np.empty(shape=(rowNum,))
    dataInsertIdx = 0
    for baselineLibraryIdx in range(len(libraryPeaks)):
        baselineQueryIdx = baselineLibraryIdx
        libraryPeak = libraryPeaks[baselineLibraryIdx]
        queryPeak = queryPeaks[baselineQueryIdx]
        for match in match_query_peak_to_all_succeeding_library_peaks_within_tolerance(
            baselineLibraryIdx,
            libraryPeaks,
            queryPeak,
            ppmTolerance,
        ):
            data[dataInsertIdx] = match
            dataInsertIdx += 1
            if dataInsertIdx == rowNum:
                return data
    return data


def match_library_to_query_pooled_spectra(libraryPeaks, queryPeaks, ppmTolerance=30):
    libraryArray = np.array(libraryPeaks)
    queryArray = np.array(queryPeaks)
    data = numba_enhanced_matching_of_library_to_query_pooled_spectra(
            libraryArray, queryArray, ppmTolerance
        )
    return data


if __name__ == "__main__":
    main()
```

When I run the above code, I get the following output. Note the top memory issue as indicated by tracemalloc effectively doubles in memory after the code is run a second time (`round1` and `round2` are loops of the same code).

```
round1
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:71: size=76.3 MiB, count=200, average=391 KiB
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:9: size=3125 KiB, count=100001, average=32 B
<frozen importlib._bootstrap_external>:647: size=2507 KiB, count=27807, average=92 B
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/abc.py:106: size=2211 KiB, count=8007, average=283 B
round2
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:71: size=153 MiB, count=400, average=391 KiB
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:9: size=3125 KiB, count=100001, average=32 B
<frozen importlib._bootstrap_external>:647: size=2507 KiB, count=27807, average=92 B
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/abc.py:106: size=2211 KiB, count=8005, average=283 B
```

However, if you remove the `@njit` decorator from the `numba_enhanced_matching_of_library_to_query_pooled_spectra` function, you get the following output instead. I included the top 4 memory issues so you can see the original problem no longer exists, all traceback lines indicate the same memory allocation.

```
round1
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:9: size=3125 KiB, count=100001, average=32 B
<frozen importlib._bootstrap_external>:647: size=2507 KiB, count=27803, average=92 B
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/abc.py:106: size=2207 KiB, count=7993, average=283 B
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:14: size=781 KiB, count=1, average=781 KiB
round2
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:9: size=3125 KiB, count=100001, average=32 B
<frozen importlib._bootstrap_external>:647: size=2506 KiB, count=27801, average=92 B
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/abc.py:106: size=2207 KiB, count=7991, average=283 B
/Users/cranneyc/PycharmProjects/pythonProject/main_zodiaq_simplified4.py:13: size=781 KiB, count=2, average=391 KiB
```

I've tried a few things, including changing all `@njit` decorators to `@njit(cache=True)`, which was a long shot that did not work. I suspect the error occurs in relation to the `match_query_peak_to_all_succeeding_library_peaks_within_tolerance` function above - my attempts to replace it's use with simpler code always eliminated the problem, though it cannot be replaced in my original code.

## Project Context
The original code tries to compare float values between two lists and return significantly-close matches between the two. Specifically, this is comparing mass-to-charge values (m/z) from spectra as output from a mass spectrometer (the 'query' list) to spectra of known componds (the 'library' list). These spectra include other values other than the m/z value, but I removed the other values for simplifying this code. If it is helpful, I can provide a longer code file and inputs for an exact replica of this problem rather than the reduced version above.

**Comment by sklam** [comment]
Thank you for the detailed report. I can see the same thing on py3.9 and numba on main.

**Comment by sklam** [comment]
It's the generator in `match_query_peak_to_all_succeeding_library_peaks_within_tolerance`. I will suggest avoid generators since there are other memory leak issues with it (https://github.com/numba/numba/issues?q=is%3Aissue+is%3Aopen+generator+label%3A%22bug+-+memory+leak%22).  

If I replace the generator with:

```python
@njit
def match_query_peak_to_all_succeeding_library_peaks_within_tolerance(
        baselineLibraryIdx: int, libraryPeaks, queryPeak, ppmTolerance
):
    tempLibraryIdx = baselineLibraryIdx + 0

    out = []
    while tempLibraryIdx < len(libraryPeaks):
        ppm = calculate_parts_per_million_relative_difference(
            libraryPeaks[tempLibraryIdx], queryPeak
        )
        if not is_within_tolerance(ppm, ppmTolerance):
            break
        out.append(ppm)
        tempLibraryIdx += 1
    return out
```,

the leak is gone.

```
round1
<frozen importlib._bootstrap_external>:647: size=4013 KiB, count=40956, average=100 B
/path/to/numba/iss9212.py:9: size=3125 KiB, count=100001, average=32 B
/path/to/numba.py39.conda/lib/python3.9/abc.py:85: size=2238 KiB, count=8140, average=281 B
/path/to/numba.py39.conda/lib/python3.9/abc.py:102: size=921 KiB, count=9589, average=98 B
round2
<frozen importlib._bootstrap_external>:647: size=4013 KiB, count=40955, average=100 B
/path/to/numba/iss9212.py:9: size=3125 KiB, count=100001, average=32 B
/path/to/numba.py39.conda/lib/python3.9/abc.py:85: size=2233 KiB, count=8114, average=282 B
/path/to/numba.py39.conda/lib/python3.9/abc.py:102: size=921 KiB, count=9587, average=98 B
```

**Comment by CCranney** [comment]
Sounds great! I'll implement a similar change in my code while this is investigated, thank you!

**Comment by CCranney** [comment]
Because this is technically addressed in another issue, do you want me to close this? Or does it serve as a good test case for when the fixes are made that you'd want to review before doing so?
