### ISSUE TITLE
`overload_method` can't remove unnecessary `NRT_incref/decref`

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9213]
```python
import os

import numpy as np
from numba import njit
from numba.core import types
from numba.core.extending import overload_method
from numba.experimental import structref

os.environ["NUMBA_DUMP_OPTIMIZED"] = "1"

@structref.register
class SRType(types.StructRef):
    pass

class SR(structref.StructRefProxy):
    def __new__(cls, arr, value):
        return structref.StructRefProxy.__new__(cls, arr, value)

structref.define_proxy(SR, SRType, ["arr", "value"])


@overload_method(SRType, "method")
def ol_method(self, flag):
    def method(self, flag):
        if flag:
            start = self.value
            index = 0
            for i in range(5):
                if self.arr[start] >= 5:
                    index = start
                    break
                start += 1
            for i in range(5):
                if self.arr[start] >= 5:
                    index = start
                    break
                start += 1

            if self.value >= 0:
                self.arr[0] = 0
                return True
            else:
                for i in range(start, index, -1):
                    self.arr[i] = self.arr[i - 1]
                self.value += 1
                self.arr[index] = 0
                return True
        else:
            return False

    return method


@njit
def method2(self, flag):
    if flag:
        start = self.value
        index = 0
        for i in range(5):
            if self.arr[start] >= 5:
                index = start
                break
            start += 1
        for i in range(5):
            if self.arr[start] >= 5:
                index = start
                break
            start += 1

        if self.value >= 0:
            self.arr[0] = 0
            return True
        else:
            for i in range(start, index, -1):
                self.arr[i] = self.arr[i - 1]
            self.value += 1
            self.arr[index] = 0
            return True
    else:
        return False


@njit
def foo(sr):
    sr.method(True)

@njit
def goo(sr):
    method2(sr, True)

sr = SR(np.zeros(2),0)
foo(sr)
goo(sr)
```
Here, the `SR` has a `method` via `overload_method`, and `method2` does the same thing as `method`, but uses `njit` to decorate.
When we check the LLVM IR, `method` contains extra `NRT_incref` and `NRT_decref` calling. But `method2` doesn't contain any.
```
entry:
  %.8.not = icmp eq i8 %arg.flag, 0
  tail call void @NRT_incref(i8* %arg.self.0)
  br i1 %.8.not, label %B196, label %B6

...

B166:                                             ; preds = %B166.loopexit, %B128
  ...
  tail call void @NRT_decref(i8* nonnull %arg.self.0)
  ret i32 0

B196:                                             ; preds = %entry
  tail call void @NRT_decref(i8* %arg.self.0)
  store i8 0, i8* %retptr, align 1
  ret i32 0
```
BTW, the body of `method` is nonsense, just for reproducing this issue.
tested on 0.57.1

**Comment by dlee992** [comment]
I guess somehow we didn't cover this case for overload_method in the ref pruning pass.

**Comment by sklam** [comment]
I tested on 0.57.1 and on main. I am seeing different LLVM IR but can confirm seeing a prune-able incref-decref from `foo.inspect_cfg(foo.signatures[0]).display(view=True)`

![foo.inspect_cfg(foo.signatures[0]).display()](https://github.com/numba/numba/assets/1929845/387a0fcf-93b0-4a21-8e2a-2239fef77441)

The lack of decref on the exception raising branch () should have been ignored and the incref-decref pair should have been pruned.

**Comment by dlee992** [comment]
But an interesting thing is if we choose to modify the style, i.e., use `goo` and `method2` decorated by `njit`, then no prune-able incref-decref will be generated for this case, even with llvmlite 0.39.1.

**Comment by dlee992** [comment]
Copying from public meeting:

> Note: first we need to isolate the reason.

1. > Is it a pattern that occurs after pruning + optimization, such that it requires a 2nd run of the pruner?

2. > Is it a failure in llvmlite refpruner implementation? The impl is at: https://github.com/numba/llvmlite/blob/06fb732e846dd3b4d922562c0c1bd00a96c2e4c9/ffi/custom_passes.cpp#L161

**Comment by dlee992** [comment]
@sklam some updates: after I change this config from `15` to `30`,
```c++
    // Fixed size for how deep to recurse in the fanout case prior to giving up.
    static const size_t FANOUT_RECURSE_DEPTH = 30;
```
`RefPrunePass` works for this case.

**Comment by sklam** [comment]
RE: https://github.com/numba/numba/issues/9213#issuecomment-1854847670

I don't see `FANOUT_RECURSE_DEPTH` has any effect to this case. I see the same graph as https://github.com/numba/numba/issues/9213#issuecomment-1735551415. Are you perhaps looking into a different situation?

**Comment by dlee992** [comment]
> RE: [#9213 (comment)](https://github.com/numba/numba/issues/9213#issuecomment-1854847670)
> 
> I don't see `FANOUT_RECURSE_DEPTH` has any effect to this case. I see the same graph as [#9213 (comment)](https://github.com/numba/numba/issues/9213#issuecomment-1735551415). Are you perhaps looking into a different situation?

I think it's because I still use llvmlite 0.39.1 and llvm 11.1.0?

**Comment by dlee992** [comment]
> I don't see FANOUT_RECURSE_DEPTH has any effect to this case.

Then, I think we can close this issue? I don't have this issue in my customised numba repo as well.
