### ISSUE TITLE
Report error when use np.sum on a specified dimension(setting axis parameters)

### ISSUE THREAD

**Issue by ruoqiu6** [numba/numba#9217]
I want to use numpy to implement a convolutional layer. The code is run good when I don't use jlt to speed up my running time, but when I want to run it on jlt bug report reported, the report is as follows:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(array(float32, 2d, A), array(float32, 4d, C))
 
There are 18 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'iadd': File: <numerous>: Line N/A.
    With argument(s): '(array(float32, 2d, A), array(float32, 4d, C))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'NumpyRulesInplaceArrayOperator.generic': File: numba\core\typing\npydecl.py: Line 243.
    With argument(s): '(array(float32, 2d, A), array(float32, 4d, C))':
   Rejected as the implementation raised a specific error:
     AttributeError: 'NoneType' object has no attribute 'args'
  raised from E:\anaconda\envs\mytorch\lib\site-packages\numba\core\typing\npydecl.py:254
  - Of which 2 did not match due to:
  Operator Overload in function 'iadd': File: unknown: Line unknown.
    With argument(s): '(array(float32, 2d, A), array(float32, 4d, C))':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at D:\layer.py

File "layer.py", line 94:
    def _conv(inputs_pad, outputs, weight, bias, kernel_size, stride):
        <source elided>
                tmp = inputs_pad[:, :, h * stride:h * stride + kernel_size, w * stride:w * stride + kernel_size] * weight[None, :]
                outputs[:, :, h, w] += np.sum(inputs_pad[:, :, h * stride:h * stride + kernel_size, w * stride:w * stride + kernel_size] * weight[None, :], axis=(2, 3))
                ^
```
the code is as follows:
```
outputs[:, :, h, w] += np.sum(inputs_pad[:, :, h * stride:h * stride + kernel_size, w * stride:w * stride + kernel_size] * weight[None, :], axis=(2, 3))
```
weight is kernel of convolutional layer and inputs pad is padded inputs matrix.
I'm not sure if this is a bug, but I really want an explanation

**Comment by stuartarchibald** [comment]
Thanks for the report. As part of Numba's compilation process it has to work out the "type" of every single variable so that it can compile a specialisation based on this. The above exception is caused by Numba not being able to find an implementation for the `iadd` (`+=`, in place addition) operation for input of type float32-2d-A-ordered-array having a float32-4d-C-ordered-array added to it. It may be a bug in Numba's type inference or simply something unsupported. Providing a minimal working reproducer (code and input, even if it's just dummy input) would make it possible to diagnose this issue further. Thanks for your help.

**Comment by ruoqiu6** [comment]
> Thanks for the report. As part of Numba's compilation process it has to work out the "type" of every single variable so that it can compile a specialisation based on this. The above exception is caused by Numba not being able to find an implementation for the `iadd` (`+=`, in place addition) operation for input of type float32-2d-A-ordered-array having a float32-4d-C-ordered-array added to it. It may be a bug in Numba's type inference or simply something unsupported. Providing a minimal working reproducer (code and input, even if it's just dummy input) would make it possible to diagnose this issue further. Thanks for your help.

Thank you very much for your answer, I found that this bug is caused by using np.sum on multiple dimensions, and if reshape is used before summing, there will be no problem. Thanks very much.
