### ISSUE TITLE
Invalid closure handling in _create_function_from_code_obj

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#9222]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Closure handling was updated as part of Python 3.11 upgrade to include [this line](https://github.com/numba/numba/blob/9f74128def1ca51deebfadecc663f0b80f641c57/numba/core/ir_utils.py#L1743) (`func_arg = func_arg.replace('.', '_')`), which replaces dots in function argument signature (to fix generated argument names I assume). However, this is invalid for default values that are float constants as demonstrated below (removed `InlineClosureLikes` to go through `MakeFunctionToJitFunction` code path which passes default values).

The commit that made this change ([here](https://github.com/numba/numba/commit/77c2672e22be8cb33e47f44884385fd75906881c)), mentions fixing `numba.tests.test_looplifting.TestLoopLiftingInAction.test_lift_listcomp_block0` but the test works with or without this change. Seems like the motivating problem may have been solved in the upstream calls and we can just remove the `func_arg = func_arg.replace('.', '_')` line. Is this correct?

```python
import numba
from numba.core.compiler import DefaultPassBuilder
from numba.core.untyped_passes import InlineClosureLikes

class TestPipeline(numba.core.compiler.CompilerBase):
    def define_pipelines(self):
        pm = DefaultPassBuilder.define_nopython_pipeline(self.state, "TestPipeline")
        for idx, (x, _) in enumerate(pm.passes):
            if x == InlineClosureLikes:
                break
        else:
            raise Exception("Could not find pass %s" % location)
        pm.passes.pop(idx)
        pm.finalize()
        return [pm]

@numba.njit(pipeline_class=TestPipeline)
def f(a):
    def g(x, y=1.1):
        return x+y
    return g(a)

# prints 15 instead of 5.1
print(f(4))
```

**Comment by gmarkall** [comment]
I can reproduce this locally, and also with a simpler example suggested by @stuartarchibald:

```python
from numba import njit

@njit
def foo():
    def bar(x, y=1.1):
        return x + y
    return bar

@njit
def consume():
    return foo()(4)

print(consume())
```

The suggested fix seems to also fix both of these cases in local testing, so I'm trying the fix on CI and also locally doing the full test run with Python 3.11.
