### ISSUE TITLE
GitHub Actions: fix towncrier workflow to re-run on adding skip label

### ISSUE THREAD

**Issue by esc** [numba/numba#9231]
Currently the towncrier workflow will fail if the `skip_release_notes` label isn't set. It seems like there is no way to re-run this workflow after adding the label, other than to open/close it. It would be nice if the workflow was runnable after adding the `skip_release_notes` label such that we don't have to open/close the PRs anymore.

**Comment by sklam** [comment]
Potential solution: https://github.com/orgs/community/discussions/39062#discussioncomment-4138177

**Comment by esc** [comment]
Fixed by: https://github.com/numba/numba/pull/9666
