### ISSUE TITLE
How to cache function which with arguments function 

### ISSUE THREAD

**Issue by RunxingZhong** [numba/numba#9237]
Hi, 
I need to re-run many times for specify functions, so I set cache = True, which work correctly as I want.
However, when cache for function which with arguments function, caching is failed.
please check, how to cache it correctly.
for simplify, I can provide a reproduce code as follow.

```
import time
import numpy as np
import numba

@numba.njit(nopython=True, cache=True)
def func(x):
    return x

@numba.njit(nopython=True, cache=True)
def roll(op, a):
    s = 0
    for i in range(len(a)):
        s += op(a[i])
    return s

np.random.seed(42)
a = np.random.random(10)

for i in range(3):
    t1 = time.time()
    roll(func, a)
    t2 = time.time()
    print(t2 - t1)
```
```
NUMBA_DEBUG_CACHE=1 python debug.py
```

by ll __pycache__/ we can seed that
debug.func-xxxxxxx.nbc only compile one time.
while debug.roll-xxxxx.nbc compile each time when execute ```NUMBA_DEBUG_CACHE=1 python debug.py```

my question is how to cache it correctly, Thanks!
Looking forward to your reply

**Comment by RunxingZhong** [comment]
another question.
cache = True, work correctly for another case. haha.py 
when package using setuptools, ```python setup.py bdist_egg --exclude-source```
run the pyc file ```python haha.pyc```
error as follow:
``` RuntimeError: cannot cache function 'func': no locator available for file 'build/bdist.linux-x86_64/egg/haha/roll.py' ```

**Comment by RunxingZhong** [comment]
@sklam please help, thank you

**Comment by kc611** [comment]
Hi @RunxingZhong, Thank you for raising this issue and your interest in using Numba.

> my question is how to cache it correctly, Thanks!

Your functions are being cached correctly as far as Numba usage is concerned. Using a callable as a function argument forces Numba to recompile the function every time.

> cache = True, work correctly for another case. haha.py

Could you elaborate the contents of this file, are they same as the above stated issue?
