### ISSUE TITLE
Numba requires a maximum version of 3.12 and I have 3.12.0

### ISSUE THREAD

**Issue by BojkaV** [numba/numba#9250]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I tried to use a python program that required Numba and yk i typed "pip install numba". Note that my version from running "python --version is 3.12.0". When I do this the final error message is RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
      [end of output]

I suppose that 3.12.0 and 3.12 are the same thing. Atleast I found it in the Python Docs. And because of this issue I can't use the program. The program I'm trying to use is RVC-GUI

**Comment by esc** [comment]
@BojkaV thank you for reporting this. Numba does not yet support Python 3.12: https://github.com/numba/numba/issues/9197
