### ISSUE TITLE
Numba not vectorizing string array comparisons

### ISSUE THREAD

**Issue by alanhdu** [numba/numba#9263]
If I have an array of single-character strings, numba does not seem to vectorize comparison operations appropriately:

```python
import numba as nb
import numpy as np

array = np.array(["a", "a", "a"])

@nb.njit
def is_equal(xs: np.ndarray, x):
    return xs == x

print(is_equal(array, "a"))   # False
print(is_equal.py_func(array, "a"))   # [True, True, True]
```

This is somewhat surprising to me -- I would've expected either to match NumPy's semantics or to raise an error.

This is with numba 0.57.1 and numpy 1.24.4 on both Python 3.8 and Python 3.10 (for some reason, micromamba is not letting me install numba 0.58).

**Comment by alanhdu** [comment]
Yeah, good catch. I agree that it's a duplicate. going to close this out in favor of #7859

**Comment by stuartarchibald** [comment]
Thanks for closing!
