### ISSUE TITLE
Searching `%PREFIX%\Library` for new CTK Windows packages

### ISSUE THREAD

**Issue by jakirkham** [numba/numba#9278]
In PR ( https://github.com/numba/numba/pull/7255 ) logic was added to Numba to handle the new-style CTK Conda packages on the `nvidia` channel (and now also on `conda-forge`)

In particular this added a series of `get_nvidia...` functions to search for libraries as part of `numba/cuda /cuda_paths.py`. For example

https://github.com/numba/numba/blob/a4664180ddc91e4c8a37dd06324f4e229a76df91/numba/cuda/cuda_paths.py#L82

<hr>

While it does look like these have some logic for searching for Windows libraries (like looking in `bin` instead of `lib`). It appears they start with `%PREFIX%` instead of `%PREFIX%\Library` (where Conda packages typically [put content on Windows]( https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process ))

Admittedly the `nvidia` package do use `%PREFIX%` to structure content. Though most Conda packages (include the CTK packages in `conda-forge`) do not do this using `%PREFIX%\Library` instead. In the future `nvidia` packages will match this behavior.

Given this wonder if we could search `%PREFIX%\Library` for the CTK first and then search `%PREFIX%` second. This would handle both structures seamlessly

**Comment by jakirkham** [comment]
For reference this came out of testing Numba with the new-style CTK packages on conda-forge

ref: https://github.com/conda-forge/numba-feedstock/issues/130

**Comment by jakirkham** [comment]
Also it looks like for static libraries, `%PREFIX%\lib\x64` is used as opposed to `%PREFIX%\Library\lib`

https://github.com/numba/numba/blob/a4664180ddc91e4c8a37dd06324f4e229a76df91/numba/cuda/cuda_paths.py#L74

**Comment by stuartarchibald** [comment]
Thanks for the report. CC @gmarkall is this something to fix for 0.59?

**Comment by gmarkall** [comment]
Proposed fix in #9279. This would be a good thing to fix for 0.59.
