### ISSUE TITLE
core dump when returning a list of a deferred type (even if instantiated?)

### ISSUE THREAD

**Issue by shaunc** [numba/numba#9284]
## Reporting a bug

When defining a jitclass with a static method to return a typed list of that class, I get a core dump:
```py
import numpy as np
import numba as nb  # type: ignore

foo_type = nb.deferred_type()

@nb.experimental.jitclass([('x', nb.int32)])  # type: ignore
class Foo:
    def __init__(self, x: np.int32):
        self.x = x

    @staticmethod
    def empty_list() -> list["Foo"]:
        return nb.typed.List.empty_list(foo_type)  # type: ignore
    
foo_type.define(Foo.class_type.instance_type)  # type: ignore

foo = Foo(np.int32(2))

# core dumps
foo.empty_list()
```

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I presume the problem is that the deferred type is "captured" in the compilation before it is defined. But I don't see how I can avoid that?

**Comment by esc** [comment]
@shaunc thank you for reporting this. Note that `jitclass` is part of the experimental API and therefore YMMV. For reference, here is the error I receive:

```
 💣 zsh» python issue_9284.py
Assertion failed: (Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"), function getTypeSizeInBits, file /Users/ci/miniconda3-arm64/envs/numba-builder/conda-bld/llvmdev_1684265191581/work/llvm/include/llvm/IR/DataLayout.h, line 674.
[1]    21739 abort      python issue_9284.py
```

**Comment by esc** [comment]
It looks like this issue is known for several years:

https://github.com/numba/numba/issues/6916
https://github.com/numba/numba/issues/6077

Closing as duplicate.
