### ISSUE TITLE
numba rewrites data instead of error raising

### ISSUE THREAD

**Issue by TsiVit** [numba/numba#9287]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

There is a strange behaviour  in some cases like in example below - numba eats an assignment out of size w/o error raising, rewriting existing values instead, that not so simple to catch in real more comlicated code.
That's for jit as wel as njit mode.

```
import numpy as np
from numba import jit, njit

@njit
def test_():
    out_arr = np.empty(shape=(10, 1)) # <--- ONE column
    out_arr[:, 0] = np.array([False, True]*5)
    out_arr[:, 1] = True  # <--- column out of size have to raise an error

    return out_arr

test_()
```

output:
```
array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])
```

expected behaviour:
```
---> [8] out_arr[:, 1] = True
IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by esc** [comment]
@TsiVit thank you for reporting this. This is not a bug, it's a feature. By default Numba doesn't do boundschecking, for performance reasons:

https://numba.readthedocs.io/en/stable/reference/jit-compilation.html#numba.jit

If you do the following, you will receive the behaviour you expect (at the cost of decreased execution speed):

```python
import numpy as np
from numba import jit, njit

@njit(boundscheck=True)
def test_():
    out_arr = np.empty(shape=(10, 1)) # <--- ONE column
    out_arr[:, 0] = np.array([False, True]*5)
    out_arr[:, 1] = True  # <--- column out of size have to raise an error

    return out_arr

test_()
```
