### ISSUE TITLE
[Python 3.12] [Task] Parfor test failures due to Python 3.12 bytecode changes. 

### ISSUE THREAD

**Issue by kc611** [numba/numba#9290]
Due to Python 3.12 changes the parfor test: `test_parfors.py::TestPrangeSpecific::test_prange_two_instances_same_reduction_var` and `test_parfors.py::TestPrangeSpecific::test_prange_conflicting_reduction_ops` now fail with similar error (which relates to reduction variable within parfors). The fix for this could not be accommodated in https://github.com/numba/numba/pull/9246 (Python 3.12 support update PR) due to technical constraints. 

This issue now tracks the respective test failures and discussions pertaining to it's possible solution.

**Comment by stuartarchibald** [comment]
@DrTodd13 now that the Python 3.12 support branch has been merged, please could you take a look at the above tests which are failing when run on Python 3.12? Both seems to be analysis issues relating to parallel reductions. Many thanks!

**Comment by DrTodd13** [comment]
Will look this week.

**Comment by stuartarchibald** [comment]
> Will look this week.

Thanks @DrTodd13!
