### ISSUE TITLE
Return record from structured array as part of tuple fails.

### ISSUE THREAD

**Issue by shaunc** [numba/numba#9294]
## Reporting a bug

This code fails to compile:
```py
import numba as nb  # type: ignore
import numpy as np

# NB changing to np.int64 makes no difference - so presumably not packing/alignment problem
rec_type = np.dtype(dict(names=["foo"], formats=[np.int32]))  # type: ignore


@nb.njit  # type: ignore
def foo() -> tuple[np.record, int]:
    return np.zeros(1, rec_type)[0], 0  # type: ignore


print(foo())  # raises exception
```
<details>
<summary>Error> </summary>
/home/shauncutts/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/utils.py:213: NumbaPendingDeprecationWarning: Code using Numba extension API maybe depending on 'old_style' error-capturing, which is deprecated and will be replaced by 'new_style' in a future release. See details at https://numba.readthedocs.io/en/latest/reference/deprecation.html#deprecation-of-old-style-numba-captured-errors
Exception origin:
  File "/home/shauncutts/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/datamodel/models.py", line 967, in from_data
    raise NotImplementedError("use load_from_data_pointer() instead")

  warnings.warn(msg,
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[1], line 12
      7 @nb.njit  # type: ignore
      8 def foo() -> tuple[np.record, int]:
      9     return np.zeros(1, rec_type)[0], 0  # type: ignore
---> 12 print(foo())

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:487, in _DispatcherBase._compile_for_args(self, *args, **kws)
    485             e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    486     # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 487     raise e
    488 finally:
    489     self._types_active_call = []

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:420, in _DispatcherBase._compile_for_args(self, *args, **kws)
    418 return_val = None
    419 try:
--> 420     return_val = self.compile(tuple(argtypes))
    421 except errors.ForceLiteralArg as e:
    422     # Received request for compiler re-entry with the list of arguments
    423     # indicated by e.requested_args.
    424     # First, check if any of these args are already Literal-ized
    425     already_lit_pos = [i for i in e.requested_args
    426                        if isinstance(args[i], types.Literal)]

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:965, in Dispatcher.compile(self, sig)
    963 with ev.trigger_event("numba:compile", data=ev_details):
    964     try:
--> 965         cres = self._compiler.compile(args, return_type)
    966     except errors.ForceLiteralArg as e:
    967         def folded(args, kws):

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:125, in _FunctionCompiler.compile(self, args, return_type)
    124 def compile(self, args, return_type):
--> 125     status, retval = self._compile_cached(args, return_type)
    126     if status:
    127         return retval

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:139, in _FunctionCompiler._compile_cached(self, args, return_type)
    136     pass
    138 try:
--> 139     retval = self._compile_core(args, return_type)
    140 except errors.TypingError as e:
    141     self._failed_cache[key] = e

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py:152, in _FunctionCompiler._compile_core(self, args, return_type)
    149 flags = self._customize_flags(flags)
    151 impl = self._get_implementation(args, {})
--> 152 cres = compiler.compile_extra(self.targetdescr.typing_context,
    153                               self.targetdescr.target_context,
    154                               impl,
    155                               args=args, return_type=return_type,
    156                               flags=flags, locals=self.locals,
    157                               pipeline_class=self.pipeline_class)
    158 # Check typing error if object mode is used
    159 if cres.typing_error is not None and not flags.enable_pyobject:

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler.py:770, in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    746 """Compiler entry point
    747 
    748 Parameter
   (...)
    766     compiler pipeline
    767 """
    768 pipeline = pipeline_class(typingctx, targetctx, library,
    769                           args, return_type, flags, locals)
--> 770 return pipeline.compile_extra(func)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler.py:461, in CompilerBase.compile_extra(self, func)
    459 self.state.lifted = ()
    460 self.state.lifted_from = None
--> 461 return self._compile_bytecode()

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler.py:529, in CompilerBase._compile_bytecode(self)
    525 """
    526 Populate and run pipeline for bytecode input
    527 """
    528 assert self.state.func_ir is None
--> 529 return self._compile_core()

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler.py:508, in CompilerBase._compile_core(self)
    506         self.state.status.fail_reason = e
    507         if is_final_pipeline:
--> 508             raise e
    509 else:
    510     raise CompilerError("All available pipelines exhausted")

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler.py:495, in CompilerBase._compile_core(self)
    493 res = None
    494 try:
--> 495     pm.run(self.state)
    496     if self.state.cr is not None:
    497         break

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler_machinery.py:368, in PassManager.run(self, state)
    365 msg = "Failed in %s mode pipeline (step: %s)" % \
    366     (self.pipeline_name, pass_desc)
    367 patched_exception = self._patch_error(msg, e)
--> 368 raise patched_exception

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler_machinery.py:356, in PassManager.run(self, state)
    354 pass_inst = _pass_registry.get(pss).pass_inst
    355 if isinstance(pass_inst, CompilerPass):
--> 356     self._runPass(idx, pass_inst, state)
    357 else:
    358     raise BaseException("Legacy pass in use")

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler_lock.py:35, in _CompilerLock.__call__.<locals>._acquire_compile_lock(*args, **kwargs)
     32 @functools.wraps(func)
     33 def _acquire_compile_lock(*args, **kwargs):
     34     with self:
---> 35         return func(*args, **kwargs)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler_machinery.py:311, in PassManager._runPass(self, index, pss, internal_state)
    309     mutated |= check(pss.run_initialization, internal_state)
    310 with SimpleTimer() as pass_time:
--> 311     mutated |= check(pss.run_pass, internal_state)
    312 with SimpleTimer() as finalize_time:
    313     mutated |= check(pss.run_finalizer, internal_state)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/compiler_machinery.py:273, in PassManager._runPass.<locals>.check(func, compiler_state)
    272 def check(func, compiler_state):
--> 273     mangled = func(compiler_state)
    274     if mangled not in (True, False):
    275         msg = ("CompilerPass implementations should return True/False. "
    276                "CompilerPass with name '%s' did not.")

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/typed_passes.py:468, in BaseNativeLowering.run_pass(self, state)
    466 lower.lower()
    467 if not flags.no_cpython_wrapper:
--> 468     lower.create_cpython_wrapper(flags.release_gil)
    470 if not flags.no_cfunc_wrapper:
    471     # skip cfunc wrapper generation if unsupported
    472     # argument or return types are used
    473     for t in state.args:

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/lowering.py:297, in BaseLower.create_cpython_wrapper(self, release_gil)
    292 if self.genlower:
    293     self.context.create_cpython_wrapper(self.library,
    294                                         self.genlower.gendesc,
    295                                         self.env, self.call_helper,
    296                                         release_gil=release_gil)
--> 297 self.context.create_cpython_wrapper(self.library, self.fndesc,
    298                                     self.env, self.call_helper,
    299                                     release_gil=release_gil)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/cpu.py:190, in CPUContext.create_cpython_wrapper(self, library, fndesc, env, call_helper, release_gil)
    185 wrapper_callee = ir.Function(wrapper_module, fnty,
    186                              fndesc.llvm_func_name)
    187 builder = PyCallWrapper(self, wrapper_module, wrapper_callee,
    188                         fndesc, env, call_helper=call_helper,
    189                         release_gil=release_gil)
--> 190 builder.build()
    191 library.add_ir_module(wrapper_module)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/callwrapper.py:122, in PyCallWrapper.build(self)
    119 kws.name = 'py_kws'
    121 api = self.context.get_python_api(builder)
--> 122 self.build_wrapper(api, builder, closure, args, kws)
    124 return wrapper, api

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/callwrapper.py:175, in PyCallWrapper.build_wrapper(self, api, builder, closure, args, kws)
    162     cleanup_manager = _GilManager(builder, api, cleanup_manager)
    164 # We elect to not inline the top level user function into the call
    165 # wrapper, this incurs an overhead of a function call, however, it
    166 # increases optimisation stability in that the optimised user function
   (...)
    173 # instruction stream being different from that of the instruction stream
    174 # present in the user function.
--> 175 status, retval = self.context.call_conv.call_function(
    176     builder, self.func, self.fndesc.restype, self.fndesc.argtypes,
    177     innerargs, attrs=('noinline',))
    178 # Do clean up
    179 self.debug_print(builder, "# callwrapper: emit_cleanup")

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/callconv.py:906, in CPUCallConv.call_function(self, builder, callee, resty, argtys, args, attrs)
    903 status = self._get_return_status(builder, code,
    904                                  builder.load(excinfoptr))
    905 retval = builder.load(retvaltmp)
--> 906 out = self.context.get_returned_value(builder, resty, retval)
    907 return status, out

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/base.py:656, in BaseContext.get_returned_value(self, builder, ty, val)
    652 def get_returned_value(self, builder, ty, val):
    653     """
    654     Return value representation to local value representation
    655     """
--> 656     return self.data_model_manager[ty].from_return(builder, val)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/datamodel/models.py:627, in StructModel.from_return(self, builder, value)
    624 def from_return(self, builder, value):
    625     vals = [builder.extract_value(value, [i])
    626             for i in range(len(self._members))]
--> 627     return self._from("from_data", builder, vals)

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/datamodel/models.py:561, in StructModel._from(self, methname, builder, value)
    558 struct = ir.Constant(self.get_value_type(), ir.Undefined)
    560 for i, (dm, val) in enumerate(zip(self._models, value)):
--> 561     v = getattr(dm, methname)(builder, val)
    562     struct = self.set(builder, struct, v, i)
    564 return struct

File ~/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/numba/core/datamodel/models.py:967, in RecordModel.from_data(self, builder, value)
    966 def from_data(self, builder, value):
--> 967     raise NotImplementedError("use load_from_data_pointer() instead")

NotImplementedError: Failed in nopython mode pipeline (step: native lowering)
use load_from_data_pointer() instead
</details>

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Possibly related?

https://github.com/numba/numba/issues/3711

Though that is not a compilation problem.

**Comment by shaunc** [comment]
Thanks - changed the title slightly: in fact, returning a *structured array* works - its returning an individual record that has problems. 

The work around is to return a singleton array - sort of ugly in library code. Perhaps the bug is dealing with a relatively large struct-like thing that needs to be passed by reference, but is taken out of it context in an array, but then embedding it in a tuple (another struct) which probably is passed by value?

**Comment by gmarkall** [comment]
Does this duplicate #9199?

**Comment by shaunc** [comment]
Right - sorry; didn't notice that one. Seems like you're making progress over there so I'm closing this in favor of that one.
