### ISSUE TITLE
Type of variable 'account_state.1' cannot be determined, operation

### ISSUE THREAD

**Issue by QuantFreedom1022** [numba/numba#9298]
numba = 0.58.1 numpy = 1.26.1 python = 3.10.10

@stuartarchibald you seem to have tried to help a lot of people with this variable cannot be determined problem so maybe you can help me here

I am getting this error every time i am trying to run my code ... it used to work fine then i was trying to do some updates and now for some reason numba is yelling at me about the variable can't be determined and i don't understand why.
```python
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Type of variable 'account_state.1' cannot be determined, operation: $phi1304.4, location: [E:\Coding\backtesters\QuantFreedom\quantfreedom\nb_funcs\nb_simulate.py](file:///E:/Coding/backtesters/QuantFreedom/quantfreedom/nb_funcs/nb_simulate.py) (409)

File "..\..\quantfreedom\nb_funcs\nb_simulate.py", line 409:
def nb_run_df_backtest(
    <source elided>
                            logger[LoggerFuncType.Debug]("nb_simulate.py - nb_run_backtest() - decrease_position")
                            account_state, order_result = nb_decrease_position(
```

I tried to make a smaller version of this, as in isolate the problem, but when i did it worked fine ... so i am not sure what is going on ... and it also works if i turn numba off

also if i change the name of the account_state then it works but then my entire code is screwed ... but also what is weird is that numba doesn't seem to have a problem with order_result but account state it does

it is also happening at every single time i am trying to return account_state after a function runs that returns account state

i am not sure how you would run this without installing my repo as a local install from the neo branch ... but not really sure what else to put in here besides my github repo

https://github.com/QuantFreedom1022/QuantFreedom/blob/neo/quantfreedom/nb_funcs/nb_simulate%20copy.py#L409

if you want to try to run it yourself you can run this 
https://github.com/QuantFreedom1022/QuantFreedom/blob/neo/tests/strategy/nb_tester.ipynb

let me know if you need any more information or a video of me running through the code

**Comment by QuantFreedom1022** [comment]
Actually ... it seems like i am having an issue with almost everything my functions are returning ... it seems to be that almost everything numba is saying that the type of variable can't be figured out

this is all pretty crazy ... i feel like there is just one problem that is ruining everything but i have no clue how to find it

**Comment by QuantFreedom1022** [comment]
ok ... so it seems the problem was that i was trying to set variables as functions inside a numba function which numba doesn't like ... so now i am setting the functions outside of the numba function then passing them into the the numba function and things seem to be working again ... will report back if the entire thing works by setting functions as variables outside of numba function then passing them to numba function

**Comment by QuantFreedom1022** [comment]
ok so yeah ... the problem was that i was trying to set variables as numba functions inside of a numba function which you can't do ... you have to set variables as functions outside a numba function then pass it into a numba function

**Comment by stuartarchibald** [comment]
Thanks for the report, am glad the issue is now resolved. Typically a `TypingError` like the one above means that Numba cannot work out the Numba-type of a particular variable, often because the type isn't supported or there's a code construct being used which makes it such that Numba cannot work out the type.
