### ISSUE TITLE
Numba not catching exception

### ISSUE THREAD

**Issue by QuantFreedom1022** [numba/numba#9299]
i have a for loop setup that is supposed to go from 0 to 299 and i am supposed to call an index in a numpy array for each loop in the for loop for i in range(0,299) candles[i,0]

but in a part of my code i have to do candles[i+1,0] ... and i have that wrapped in a try except because it is possible that i + 1 gets to 300 which should be an exception ... but for some reason numba isn't catching it ... it does catch it when i run regular python code but not numba ... i even tested it out and put i + 2000 and it still never catches it ... so what is returned is ... well i don't know what it is returning because it should all be impossible ... any idea what could be causing this 

this is the part of the code that isn't catching the except and i have no idea why ... i have no clue how this could be happening

with a candle length of 300 and the i + 2000 we should never ever ever be able to even once finish a loop without catching an exception ... but somehow it does ... i even set it to tell me how many times it filled the order records array and it returned that it filled it 80 times ... when it should never fill it even once

you can see the code here 
https://github.com/QuantFreedom1022/QuantFreedom/blob/neo/quantfreedom/nb_funcs/nb_sim_or.py#L451

**Comment by esc** [comment]
@QuantFreedom1022 I have a hunch you may need to use `boundschecking`:

https://numba.pydata.org/numba-doc/dev/reference/pysemantics.html#bounds-checking

**Comment by QuantFreedom1022** [comment]
@esc so would I have to use this constantly or just to figure out why it is happening? ... the note says to use this for debugging purposes but it seems like in my case I'd have to use it all the time

**Comment by esc** [comment]
If you are certain that your loops will not raise an `IndexError` you can disable it. I would recommend to activate during development to catch any logic errors and activate when your code goes into `production`. Deactivating these checks has a good chance to make your code run (even) faster.

**Comment by esc** [comment]
@QuantFreedom1022 can we close this now? Or are there any reaming questions about this?

**Comment by QuantFreedom1022** [comment]
Yeah I will close it
