### ISSUE TITLE
No python functions can't return conditional result with different dimensions of tuple

### ISSUE THREAD

**Issue by ZzEeKkAa** [numba/numba#9314]
As description says if we conditional return different dimensions of tuple function fails to compile:

```python
import numba


@numba.njit
def foo(ret):
    if ret:
        return (True, False, True)
    return (None, None)


print(foo(True))
print(foo(False))
```

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by guilhermeleobas** [comment]
Hi @ZzEeKkAa, thanks for the report. This is not actually a bug but a limitation in the typesystem. Numba is indicating that this code lacks type stability. Depending on the value of `ret`, the function may return either a `Tuple[bool x 3]` or a `Tuple[None x 2]`.

For further information, please read the page [my code has a type unification problem](https://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-has-a-type-unification-problem)
