### ISSUE TITLE
Add `float("inf")` support

### ISSUE THREAD

**Issue by Azmisov** [numba/numba#9322]
`float("inf")` is probably the widest used variant for specifying infinity, so would be nice to support. Workaround is to use `np.inf` instead, so not super important.

**Comment by w0rp** [comment]
I'll watch this issue. Pretty important to support the basic functionality of Python builtins through some means.

**Comment by guilhermeleobas** [comment]
The issue is that you cannot create `float('inf')` inside the jitted function:

```python
from numba import njit

@njit
def fn():
    return float('inf')

print(fn())
```
