### ISSUE TITLE
Bug report template points to obsolete CHANGE_LOG URL

### ISSUE THREAD

**Issue by bmerry** [numba/numba#9365]
When opening a bug report, the template contains
```
- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
```

But the content at that URL just says it has been removed and does not indicate the latest released version.

**Comment by gmarkall** [comment]
Thanks, #9369 should fix this.

**Comment by gmarkall** [comment]
("doc" seems to be the closest appropriate label here, even though it's not really docs)
