### ISSUE TITLE
Broadcasting of matmul does not work with parallel

### ISSUE THREAD

**Issue by bhalazs** [numba/numba#9391]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The following code snippet throws a TypingError error as-is, but it works perfectly fine if you deactivate 'parallel = True'. I have checked the online available resources as much as possible, did not find any hints on this. Sorry if it's a known missing feature!

```python
import numpy as np
from numba import njit

k = 2
n = 3

alpha = np.random.rand(k, n, n)
N = np.random.rand(n, n)

@njit(
    parallel = True
)
def mul(alpha, N):
    return alpha*N

res = mul(alpha, N)
```

**Comment by gmarkall** [comment]
Thanks for the report. From https://numba.readthedocs.io/en/latest/user/parallel.html#supported-operations:

> Multi-dimensional arrays are also supported for the above operations when operands have matching dimension and size. The full semantics of Numpy broadcast between arrays with mixed dimensionality or size is not supported, nor is the reduction across a selected dimension.

So I think this is a documented limitation.
