### ISSUE TITLE
Numba confuses float32 and float64 in numpy-array causing compilation failure

### ISSUE THREAD

**Issue by iv461** [numba/numba#9399]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

# Bug description

Minimal reproducing example:

```Python

import numpy as np
from numba import njit

@njit
def get_array(velocities):
    return np.zeros((3,), dtype=np.float32)

@njit
def sim_loop():
    velocities = np.zeros((3,), dtype=np.float32)

    for _ in range(10):
        velocities = 3. * get_array(velocities)

sim_loop()
```
Expected behavior: Compiles 

Obeserved behavior: Fails to compile with `Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'velocities.2'`
Full output:

<details>
<summary>Click to expand</summary>

Traceback (most recent call last):
  File "/home/user/numba_scalar_mismatch.py", line 15, in <module>
    sim_loop()
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/user/miniconda3/envs/py311/lib/python3.11/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'velocities.2', defined at /home/user/numba_scalar_mismatch.py (12)

File "numba_scalar_mismatch.py", line 12:
def sim_loop():
    <source elided>

    for _ in range(10):
    ^
During: typing of assignment at /home/user/numba_scalar_mismatch.py (12)

File "numba_scalar_mismatch.py", line 12:
def sim_loop():
    <source elided>

    for _ in range(10):
    ^

</details>

Tested with:
Python 3.11 
numpy 1.26.3
numba 0.58.1

Somehow numba thinks the array is of type float64 but actually multiplying a float32-array with a constant results in a float32-array.
Note that the compilation succeeds when replacing the function call to `get_array` with the `np.zeros((3,), dtype=np.float32)`-expression. It also succeeds when `velocities` is not passed to the function or if the scalar multiplication (or the loop) is omitted.

Seems similar to https://github.com/numba/numba/issues/9025

Thanks for having a look

**Comment by iv461** [comment]
Thanks for the insightful comment, I assumed that scalar multiplication between a float32 array and a Python scalar (which has 64-bit precision) would always result in a float32 array. Explicitly casting the scalar does indeed solve my problem, thank you.
The initial motivation for creating this issue was mostly because I was confused as to why the otherwise same example would compile if I did not pass the `velocities`-array to the `get_array`-function in the for-loop body. 
Consider these new examples which I think are equivalent to the original one, only simpler:

(1) Compiles:
```Python
@njit
def sim_loop():
    velocities = np.zeros((3,), dtype=np.float32)
    for _ in range(2):
        velocities = np.zeros((3,), dtype=np.float64)
sim_loop()
```
(2) does not compile (`Cannot unify array(float32, 1d, C) and array(float64, 1d, C)`):
```Python
@njit
def print_array(array): print(f"{array}")

@njit
def sim_loop():
    velocities = np.zeros((3,), dtype=np.float32)
    for _ in range(2):
        print_array(velocities)
        velocities =  np.zeros((3,), dtype=np.float64)
sim_loop()
```
(3) Compiles again, after unrolling the loop:
```Python
@njit
def print_array(array): print(f"{array}")

@njit
def sim_loop():
    velocities = np.zeros((3,), dtype=np.float32)
    print_array(velocities)
    velocities =  np.zeros((3,), dtype=np.float64)
    print_array(velocities)
    velocities =  np.zeros((3,), dtype=np.float64)
sim_loop()
```

After reading [this document](https://numba.readthedocs.io/en/stable/proposals/type-inference.html) about the implementation of the numba type inference, I think I understand why this happens.
Actually, numba supports that a Python variable changes its type during its lifetime, that's why (1) compiles, right ?
It also supports compiling the same function for different argument types, that's why (3) compiles, right ?
But it does not support dynamic dispatch, which would be needed to compile (2), since it depends on the iteration which of the two versions of `print_array` we have to call, is this correct ?

Many thanks !

**Comment by sklam** [comment]
> Actually, numba supports that a Python variable changes its type during its lifetime, that's why (1) compiles, right ?
> It also supports compiling the same function for different argument types, that's why (3) compiles, right ?
> But it does not support dynamic dispatch, which would be needed to compile (2), since it depends on the iteration which of the two versions of `print_array` we have to call, is this correct ?

Yes, yes and yes. 

Numba uses these typing restrictions to maximize its (and LLVM's) ability to optimize the function. It more like a performance linter at this point.

**Comment by iv461** [comment]
Ok, makes sense, thanks for answering my questions

**Comment by sklam** [comment]
closing this as casting rules will be changed due to https://github.com/numba/numba/issues/9409
