### ISSUE TITLE
module 'numpy' has no attribute 'typeDict' with numpy 1.24.4

### ISSUE THREAD

**Issue by ladrians** [numba/numba#9415]
I got the following error

```bash
  File "/home/username/.local/lib/python3.8/site-packages/numba/np/linalg.py", line 57, in ensure_blas
    import scipy.linalg.cython_blas
  File "/usr/lib/python3/dist-packages/scipy/linalg/__init__.py", line 213, in <module>
    from ._sketches import *
  File "/usr/lib/python3/dist-packages/scipy/linalg/_sketches.py", line 11, in <module>
    from scipy.sparse import csc_matrix
  File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/username/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
```
My env had numpy 1.24.4, downgrading to 1.22 could continue.

```bash
pip install numpy==1.22
```
Is it expected to updated the library to transparently support newer numpy versions?
thanks

**Comment by guilhermeleobas** [comment]
Hi @ladrians, which version of Numba are you using? I couldn't reproduce the error locally using conda + pip:

```bash
$ mamba env create --name test
# ...
$ mamba install python=3.8
# ...
$ pip install numpy==1.24.4 numba scipy
# ...
$ python
Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:25:47)
[Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> import numpy as np
>>> np.__version__
'1.24.4'
>>> def fn(x): return np.sin(x)
...
>>> cfunc = numba.njit(fn)
>>> cfunc(3)
0.1411200080598672
```

**Comment by ladrians** [comment]
Hi, I have installed

```
numba.__version__
'0.58.1'

```

**Comment by guilhermeleobas** [comment]
I just created a new environment with Numba 0.58 and NumPy 1.24.4 and Numba works just fine.

**Comment by guilhermeleobas** [comment]
@ladrians, could you try to create a fresh new environment and see if the issue still persist?

**Comment by gmarkall** [comment]
(Looks like it was removed about 4 years ago, in SciPy 1.5.0: https://github.com/scipy/scipy/commit/8bd2e85fcb1591b22075fd75a8de433629d19929)

**Comment by ladrians** [comment]
I reproduced the problem again in a new Nvidia Jetson flashed board with the Jetpack 5.1.2 which is a speciallized Ubuntu version for that board. I need to use the ROS noetic tool chain too. Frankly speaking not sure where the problem may be. For this case worked for me using numba `0.58.1`, then downgrade for numpy `1.22`.

```sh
pip install numpy==1.22
```

The case does not seems to be general, If you are agree just lets close the issue.
thanks!

**Comment by AmmanuelBekele** [comment]
I have similar problem.

**Comment by guilhermeleobas** [comment]
> I have similar problem.

As Graham suggested above, you may have an older version of SciPy floating around. Can you try to create a new environment with updated dependencies?
