### ISSUE TITLE
Support math.nextafter in nopython mode

### ISSUE THREAD

**Issue by groutr** [numba/numba#9424]
## Feature request

`math.nextafter` was added in Python 3.9. However, numba doesn't seem to support it in nopython mode. Can support please be added?

**Comment by guilhermeleobas** [comment]
If anyone wants to work on this one, I think one can reuse the same implementation of `np.nextafter` to implement this one:
https://github.com/numba/numba/blob/3edb458c69daeaaffbfc938145c367eda1cf043f/numba/np/npyfuncs.py#L1637-L1646

**Comment by groutr** [comment]
I'll try taking a stab at it.

**Comment by groutr** [comment]
I'm curious if this is a viable solution. I'm completely unable to test this though. llvmlite 0.43 simply refuses to install on my machine. 

https://github.com/groutr/numba/commit/d8b2619435b2db6a9bf746e43749ef1daf2b126c

**Comment by groutr** [comment]
@guilhermeleobas I'm not sure how to add the typing information. Is there an example I can see?

**Comment by groutr** [comment]
@guilhermeleobas Thanks. I was looking in completely the wrong place. I'll submit a PR now.

**Comment by groutr** [comment]
@guilhermeleobas Since the minimum supported version of Python is already 3.9, do we really need a version check?
