### ISSUE TITLE
The `np.size()` Function Fails

### ISSUE THREAD

**Issue by RoyiAvital** [numba/numba#9464]
## The Bug

It seems Numba support the `ndarray` property of an array (See [`numpy.ndarray.size`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html)) yet fails with the function [`np.size()`](https://numpy.org/doc/stable/reference/generated/numpy.ma.size.html).

## Code for Producing the Bug

The following works:

```python
import numpy as np
from numba import njit

@njit
def SumArrayWorks( vX : np.ndarray ) -> float:
  arrSum = 0.0
  for ii in range(vX.size):
    arrSum += vX[ii]

  return arrSum

vX = np.array([1.0, 2.0, 3.0, 4.0])
SumArrayWorks(vX) #<! Works!

```

While this will fail:

```python
import numpy as np
from numba import njit

@njit
def SumArrayFails( vX : np.ndarray ) -> float:
  arrSum = 0.0
  for ii in range(np.size(vX)):
    arrSum += vX[ii]

  return arrSum

vX = np.array([1.0, 2.0, 3.0, 4.0])
SumArrayFails(vX) #<! Fails!
```

The error is:

```python
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.size' or unsupported use of the function.
```

## System Information

1. Numba: `0.59.0`.
2. Python: `3.12`.
3. NumPy: `1.26.4`.
4. OS: Windows 11 Pro 23H2.

**Comment by sklam** [comment]
`np.size()` is so rarely used that we completely missed it for all these years.

**Comment by RoyiAvital** [comment]
@SDanielDev , The concept here is about having a native Numba support, not bypassing it.
Specifically, it is better to avoid using global variables. A simpler and better solution would be using `vX.size` instead of `np.size()` which works as shown above.

**Comment by RoyiAvital** [comment]
I still have this issue on Numba 0.61. Is it part of it?
