### ISSUE TITLE
Numba Cache is Unaware of Imports

### ISSUE THREAD

**Issue by ivme** [numba/numba#9483]
When an imported function is changed, but the file into which it is imported is not, the Numba cache is not updated.

Minimal example:
`a.py`
```
import numpy as np
from numba import cuda


from b import get_increment_size


@cuda.jit(cache=True)
def increment(array):
    pos = cuda.grid(1)
    if pos < array.size:
        array[pos] += get_increment_size()


array = np.arange(2)
d_array = cuda.to_device(array)
threadsperblock = 2
blockspergrid = (array.size + (threadsperblock - 1)) // threadsperblock
increment[blockspergrid, threadsperblock](d_array)
print(d_array.copy_to_host())
```

`b.py`
```
from numba import cuda


@cuda.jit(cache=True)
def get_increment_size():
    return 1
```

To reproduce, first run
```
python a.py
```
which outputs
```
[1,2]
```
and simultaneously generates entries in `__pycache__` directory.
Now modify `b.py` to return an increment size of 2.
```
def get_increment_size():
    return 2
```
Rerun
```
python a.py
```

Expected Result
```
[2,3]
```
Actual Result
```
[1,2]
```

Workaround: delete `__pycache__` after modifying `b.py`. Then `python a.py` produces expected result.

Using Numba 0.59.0

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a known issue and a long standing feature request xref: #1833, it's hoped that #8396 will fix this.

**Comment by ivme** [comment]
Apologies for the duplicate! I searched the issues but didn't find https://github.com/numba/numba/issues/1833. I'll keep an eye on https://github.com/numba/numba/pull/8396. Thanks!

**Comment by stuartarchibald** [comment]
@ivme no problem, there's a lot of issues in the tracker, I'll close this one as it is a duplicate. Subscribing to #8396 is probably the best place to track updates. Thanks again!
