### ISSUE TITLE
random.Generator.binomial infinite loop

### ISSUE THREAD

**Issue by japlete** [numba/numba#9493]
I noticed the `binomial` method is implemented for the numpy Generator class, even though it's not listed in the supported distributions in the documentation.

When generating numbers with a large N (the first argument = 700), the method enters into an infinite loop.
For very small N (=10), it generates exactly the same sequence as pure numpy.
For intermediate values of N (=301), the results are similar but deviate from numpy.

I'm using numba 0.59
This should reproduce the error (pick different values of n to test the 3 cases):
```python
n = 700
import numpy as np
from numba import njit, objmode

def get_bins_np(gen, n):
    return gen.binomial(n, 0.1, 100)

@njit
def get_bins_obj(gen, n):
    with objmode(x='int64[:]'):
        x = gen.binomial(n, 0.1, 100)
    return x

@njit
def get_bins(gen, n):
    return gen.binomial(n, 0.1, 100)

gens = [np.random.default_rng(0), np.random.default_rng(0), np.random.default_rng(0)]

x1 = get_bins_np(gens[0], n)
print(x1[:10])
x2 = get_bins_obj(gens[1], n)
print(x2[:10])
print(np.array_equal(x1, x2))
x3 = get_bins(gens[2], n)
print(x3[:10])
print(np.array_equal(x1, x3))
print((x1.mean() - x3.mean())/x1.mean())
```
I'm implementing [this](https://github.com/japlete/foostrap) bootstrap sampling library with numba, so I had to go with `objmode` for now.

**Comment by esc** [comment]
I can confirm the program appears to "hang". I looked at this via the `htop` tool and observed:

<img width="448" alt="Screenshot 2024-03-13 at 18 53 38" src="https://github.com/numba/numba/assets/41563/84f556be-09e9-48a4-80f2-e82f5237a78a">

**Comment by esc** [comment]
@kc611 could you kindly take a quick look here? IIRC you are the original author here and this issue will benefit from your input, thank you.

**Comment by stuartarchibald** [comment]
I think there's a bug here in the `case == 52` branch:
https://github.com/numba/numba/blob/4318ee4aeaaad99fa5965d8b723fc0c91581cab9/numba/np/random/distributions.py#L644-L676
If the branch on `(A > ...)` is false, then the execution should fall through to `case == 60` (as it does in the C code in NumPy), but it does not, the `case` remains in state `52`, and the `while(1)` loop is re-entered with this same state, the `case == 52` branch is hit _again_ and the same sequence happens repeatedly, hence it hangs.

CC @kc611 do you agree with this assessment?

**Comment by stuartarchibald** [comment]
@kc611 I agree, there are two separate problems, the bug in https://github.com/numba/numba/issues/9493#issuecomment-2079769913 and also the incorrect values which I've filed as #9734. I'm adding both to the 0.61 milestone as I have patches locally, they are thankfully just minor changes.
