### ISSUE TITLE
Numba.cloudpickle error, although numba installed

### ISSUE THREAD

**Issue by Nee-DS** [numba/numba#9500]
I am using Pyinstaller to create an exe for the model pipeline.  Following is the error I am getting. Although I did install numba.

File "joblib\numpy_pickle.py", line 648, in load
File "joblib\numpy_pickle.py", line 577, in _unpickle
File "pickle.py", line 1212, in load
File "pickle.py", line 1589, in load_reduce
File "numba\core\serialize.py", line 110, in _unpickle__CustomPickled
ModuleNotFoundError: No module named 'numba.cloudpickle.cloudpickle_fast'

Versions:
Pyinstaller 6.4.0
Python 3.10
Windows

Please let me know the cause of this error. Thanks

**Comment by esc** [comment]
This is the file:

https://github.com/numba/numba/blob/main/numba/cloudpickle/cloudpickle_fast.py

Can you perhaps check if this file is installed in the right place?

**Comment by Nee-DS** [comment]
Yes, it is at the right place. I have created a virtual environment with python==3.9 and the following are the libraries in the VM.:
uvicorn[standard]>=0.17.6,<=0.18.0
fastapi>=0.75.2,<=0.76.0
pyinstaller==6.4.0
pandas>==1.4.3
regex==2022.10.31
bertopic==0.16.0
packaging==23.1
sklearn==0.0
umap-learn==0.5.3
hdbscan==0.8.32
sentence-transformers==2.2.2
pickleshare==0.7.5
nltk==3.6.2
pathy==0.10.0
testpath==0.5.0
tqdm>=4.27
transformers==4.29.2
openpyxl
importlib_metadata
wheel
sacremoses
bpemb>=0.3.2
hydra-core == 1.3.2
datefinder
numba==0.59.0
Cython==0.29.36
hdbscan==0.8.32
joblib==1.3.1
numpy==1.25.1
scikit-learn==1.3.0
scipy==1.11.1
spacy==3.5.3

I use pyinstaller to create the exe. The exe is created, but when I launch the exe I get the error I posted in my previous post. 
Please let me know what am I missing. Thanks!

**Comment by esc** [comment]
> I use pyinstaller to create the exe. The exe is created, but when I launch the exe I get the error I posted in my previous post. Please let me know what am I missing. Thanks!

This issue was discussed during our issue triage meeting today and our guess is that this is due to a bad interaction between Numba and pyinstaller. There are no obvious solutions to this and it will require debugging, unfortunately. Would recommend to leave this open in case someone with knowledge of both Numba and pyinstaller is able to solve it.

**Comment by Nee-DS** [comment]
Thanks! I will try to debug by the time. Thanks

**Comment by Nee-DS** [comment]
Reducing numba version to 0.58.1 worked
