### ISSUE TITLE
numba's bug with prange without warning

### ISSUE THREAD

**Issue by baiyunfeiiop** [numba/numba#9518]
(Edited by maintainer to inline file attachment)

Here is a minimal code to demonstrate a bug I found.This code can run smoothly without error and warning,
but it gives an unreasonable result, with output number ‘err1’ equals ‘err2’.However, ‘err1’ and ‘err2’ should be of opposite sign. Bug code see the attachment

```python
import numba
import time
from numba import jit
from numba import prange
import numpy as np
test=np.arange(10000).reshape((100,100))

@jit(nopython=True,parallel=True)
def bug(test,pre,err1,err2):
	for k in range(0,100):
		pre=pre+test[k,0]
	for k in prange(0,100):
		err1=err1+test[k,0]
		err2=err2-test[k,0]
	return(err1,err2)

err1,err2=bug(test,0,0,0)
print(err1,err2)

```

I found there are two ways to overcome the bug.

1.not use prange
2.Delete the first loop at line 10 and line11
     But, still I’d like to know how the bug arises,in case of bugs appear without warning
 next time. By the way, Could you please send a copy of your responce to my email baiyunfei@iphy.ac.cn
Lookinng forward to your reply.
Yours sincerely

**Comment by baiyunfeiiop** [comment]
[bug.txt.txt](https://github.com/numba/numba/files/14798695/bug.txt.txt)

**Comment by sklam** [comment]
It seems that parfors is mishandling the reduction when it is written as `err2=err2-test[k,0]` but works when it's written as `err2 -= test[k,0]`.

**Comment by sklam** [comment]
(CC @DrTodd13)

`get_parfor_reductions()` is not setting `redop` when the reduction is not written with an inplace binop; e.g ` err2=err2-test[k,0]`. As a result, `_parfor_lowering_finalize_reduction()` calls `_lower_non_trivial_reduce()` and emitting 

```
$err2.2.23 = err2.2 - err2.2#init
```
which is `0 -  (-495000)`.

Should `get_parfor_reductions()` have set `redop` to `operator.isub` instead?

**Comment by DrTodd13** [comment]
> (CC @DrTodd13)
> 
> `get_parfor_reductions()` is not setting `redop` when the reduction is not written with an inplace binop; e.g ` err2=err2-test[k,0]`. As a result, `_parfor_lowering_finalize_reduction()` calls `_lower_non_trivial_reduce()` and emitting
> 
> ```
> $err2.2.23 = err2.2 - err2.2#init
> ```
> 
> which is `0 - (-495000)`.
> 
> Should `get_parfor_reductions()` have set `redop` to `operator.isub` instead?

I suppose this is common enough that we should recognize the pattern a = a - b (or a = a + b, etc.).  Storing those internally as isub (or iadd, etc) may work.  There is code in there for isub (parfor_lowering:581) such that the reduction across the individual thread results is done with addition.    I suppose in this case it doesn't know to do that for a=a-b and so it does subtraction across the threads which ends up adding due to the negative.  How do you want to solve this?  I can solve it or you can if you are interested.  Let me know.
