### ISSUE TITLE
Remove `numba.core.retarget`

### ISSUE THREAD

**Issue by sklam** [numba/numba#9538]
The module `numba.core.retarget` is for an experimental feature added in https://github.com/numba/numba/pull/6870.
It was added for DPEX, which had removed this feature in https://github.com/IntelPython/numba-dpex/pull/1041.
We now prefer users to use the `numba.core.target_extension` API.

**Comment by sklam** [comment]
CC @diptorupd

**Comment by diptorupd** [comment]
@sklam Yes, we are no longer using the feature and have moved our code to `numba.core.target_extension` API.
