### ISSUE TITLE
RAM accumulation in loops using @njit @jitclass 

### ISSUE THREAD

**Issue by sgheinemann** [numba/numba#9552]
We have encountered memory accumulation issue when using a Numba class to append arrays of floats to a list within a loop. Despite clearing the list before each iteration, the memory usage continues to grow proportionally with the loop size. Interestingly, this problem only arises when the class is implemented using Numba; it doesn't occur with a standard Python class. We were advised to report this issue here.

Any insights or suggestions on how to address this issue would be greatly appreciated. Thank you!

Here is a minimum working (or "bugging") example. the output is a positive number (i.e. more memory used after running the script). This is not the case if a normal pyhton class is used (remove the @jitclass() )

Tested for Specs:

OS: Linux SMP x86_64 | 22.04.1-Ubuntu

Numba: 0.59.1 | 0.58.1

Numpy: 1.26.4 | 1.24.1

Python:3.11.8 GCC 12.3.0 | 3.11.0 GCC 11.3.0

```
import numba.experimental.jitclass as jitclass
import numba
import random
import numpy as np
import psutil
import os

@jitclass()
class testing:
points : numba.types.List(numba.types.Array(numba.types.float64, 1, "C"))

    def __init__(self):
        # Initialize point structure
        self.points = [np.zeros(1)]
        self.points.clear()
    
    def compute(self):
    
        # Clear possible previous points
        self.points.clear()
        
        l=random.randint(0,1000)
        #l=10
        for k in range(l):
            self.points.append(np.array([np.float64(k)]))
        
        return 0

a=testing()

process = psutil.Process(os.getpid())
base_memory_usage = process.memory_info().rss
for i in range(1000):
a.compute()

memory_usage = process.memory_info().rss
loop_memory_usage = memory_usage - base_memory_usage

print('RAM Used:',loop_memory_usage/1e9)
```

**Comment by sgheinemann** [comment]
Hi @esc,
Thank you for your reply and help!

We put our heads together and found a solution to this: The problem was indeed a mixing of reflected and typed lists that cause the issue.
If we correctly define and initialize "points", the list is correctly cleared after each loop and no RAM accumulates.

by changing 
`points : numba.types.List(numba.types.Array(numba.types.float64, 1, "C"))`
to
`points : numba.types.ListType(numba.types.Array(numba.types.float64, 1, "C"))`
and 
`self.points = [np.zeros(1)]`
to        
`self.points = numba.typed.List((np.zeros(0),))`
the issue can be solved.

Here is a working example.
```
import numba.experimental.jitclass as jitclass
import numba
import random
import numpy as np
import psutil
import os

@jitclass
class testing:
    points : numba.types.ListType(numba.types.Array(numba.types.float64, 1, "C"))
    
    def __init__(self):
        # Initialize point structure
        self.points = numba.typed.List((np.zeros(0),))
        self.points.clear()
    
    def compute(self):
    
        # Clear possible previous points
        self.points.clear()
        
        l=random.randint(0,1000)
        #l=10
        for k in range(l):
            self.points.append(np.array([np.float64(k)]))
        
        return 0

a=testing()

# checking ram usage here for python  (i dont know how to check ram usage of numba)
for j in range(20):
    process = psutil.Process(os.getpid())
    base_memory_usage = process.memory_info().rss    
    for i in range(1000):
        a.compute()
    
    memory_usage = process.memory_info().rss
    loop_memory_usage = memory_usage - base_memory_usage
    
    print('RAM Used:',loop_memory_usage/1e9)
```

**Comment by esc** [comment]
> Hi @esc, Thank you for your reply and help!
> 
> We put our heads together and found a solution to this: The problem was indeed a mixing of reflected and typed lists that cause the issue. If we correctly define and initialize "points", the list is correctly cleared after each loop and no RAM accumulates.
> 
> by changing `points : numba.types.List(numba.types.Array(numba.types.float64, 1, "C"))` to `points : numba.types.ListType(numba.types.Array(numba.types.float64, 1, "C"))` and `self.points = [np.zeros(1)]` to `self.points = numba.typed.List((np.zeros(0),))` the issue can be solved.

Yeah, that does sound right! Well done!
