### ISSUE TITLE
numpy.std() results differ with and without numba

### ISSUE THREAD

**Issue by ntm** [numba/numba#9591]
Hello,

I'm using numba-0.59.1 installed via pip, on a fedora 39 system with python3-3.12.3-2.fc39.x86_64 and python3-numpy-1.24.4-2.fc39.x86_64.
I get different results with vs without @numba.njit in the following:

```
import numba
import numpy

@numba.njit
def std_jit(X):
    y = numpy.std(X)
    return(y)

def std_nojit(X):
    y = numpy.std(X)
    return(y)

rng = numpy.random.default_rng()
X = rng.random(10000)
y1 = std_nojit(X)
y2 = std_jit(X)
if y1 != y2:
    print("numba and noNumba: KO")
else:
    print("OK")
```

Running this I get:
```
$ python test.py
numba and noNumba: KO
```
I expected to get identical results with and without numba.

**Comment by brendancol** [comment]
@ntm what about with `np.isclose`?  Is this just a float comparison issue?

**Comment by ntm** [comment]
@brendancol  you are right, with this toy example math.isclose() says they're close enough.
But that depends on the data. For example if you generate X as float32's with `X = rng.random(10000, dtype=numpy.float32)`, math.isclose(y1,y2) isn't happy anymore. I noticed this while numba-izing my code because the downstream results were (signficantly) different.
It doesn't help that numpy.std() accepts a dtype= keyword, allowing to use an accumulator of high precision than the data, but this keyword isn't recognized by the numba std(). I guess if numba's std() accepted dtype= all would be OK. So maybe this issue is actually a request to add dtype= to std()? Should I rename the issue?

**Comment by ntm** [comment]
Thanks, that looks like an interesting read.
As I said, my initial issue came from numba vs no-numba discrepancies working with float32 data, where the numba std() result isn't even "close" (looking at relative error with math.isclose()) to the numpy std(). Bit digging more, it seems the numba version is actually close to the numpy std(dtype=np.float64) version! Suggesting that among the discrepant results, the nyumba version was more correct... I've now side-stepped the issues by moving the data to float64's, results look good.
Thanks again, closing this.
