### ISSUE TITLE
A tuple of uint64 (> 2**63 but < 2**64) as the key of numba Dict

### ISSUE THREAD

**Issue by ZZZZZZZ-ZZZZZ** [numba/numba#9597]
Hello,
I'm trying to make a numba dict of type `{(uint64, uint64}: int64}`.  
If I don't understand wrong, the element of the key can be within [0, 2 ** 64-1]. However, I get an OverflowError: int too big to convert, when the element is larger than  2**63-1.

Code to reproduce:
```
import numba as nb
key_type = nb.types.Tuple((nb.uint64, nb.uint64))
di = nb.typed.Dict.empty(key_type=key_type, value_type=nb.int64)
di[(nb.uint64(2**63), nb.uint64(0))] = 1
print(di)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This doesn't seem to reproduce on linux systems, was wondering if you are perhaps using Windows? The exception is probably coming from Numba's "unbox/box" code which is the part of Numba that handles the translation from Python objects to Numba's internal representation (or the reverse), I suspect a Python call to create an intermediate representation of the value is failing.

**Comment by gmarkall** [comment]
Could maybe be related (or possibly not, but worth a mention IMHO): #9576

**Comment by ZZZZZZZ-ZZZZZ** [comment]
Hello, thanks for the answer. 
Sorry, I also cannot directly reproduce this error. 

After retrying it a few times, the bug appear again. 
![image](https://github.com/numba/numba/assets/24423702/641e5a5b-7429-43cb-a583-34a19fa6d47b)

Here is the code to reproduce:

```
import numba as nb
key_type = nb.types.Tuple((nb.uint64, nb.uint64))
di = nb.typed.Dict.empty(key_type=key_type, value_type=nb.int64)
di[(nb.uint64(2**63-1), nb.uint64(2**63+1))] = 1
print(di)

key_type = nb.types.Tuple((nb.uint64, nb.uint64))
di = nb.typed.Dict.empty(key_type=key_type, value_type=nb.int64)
di[(nb.uint64(2**63+1), nb.uint64(2**63+1))] = 1
print(di)
```

I'm using 
macOS (14.4.1)
Python 3.12.3
numba (0.59.1)
