### ISSUE TITLE
using rtsys in objmode incur pickle issue

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9605]
```python
import os

import numpy as np
from numba import jit, objmode
from numba.core.runtime import rtsys

os.environ["NUMBA_NRT_STATS"] = "1"

@jit
def dump():
    with objmode():
        print(rtsys.get_allocation_stats())

@jit
def foo():
    arr = np.arange(10)
    dump()
    return arr

print(foo())
print(rtsys.get_allocation_stats())
```
Run this script, I got `TypeError: cannot pickle '_thread.RLock' object`.
If comment `dump()` calling, this is fine. This may be a bug or feature request. 
comes from https://numba.discourse.group/t/cannot-pickle-thread-rlock-object-with-objmode/2582

My intention is using this style for fine-grained debugging of numba NRT, to check if any memory leak exists.

BTW, if users can get these nrt_mstats inside jit directly, without resort to objmode, it would be much useful.

**Comment by esc** [comment]
@dlee992 maybe this can help:

https://github.com/numba/numba/blob/main/numba/core/unsafe/refcount.py

?

**Comment by esc** [comment]
@dlee992 here is an example from a test where the `get_refcount` is used:

```
    def test_str_item_refcount_replace(self):
        @njit
        def foo():
            # use some tricks to make ref-counted unicode
            i, j = 'ab', 'c'
            a = i + j
            m, n = 'zy', 'x'
            z = m + n
            l = List.empty_list(types.unicode_type)
            l.append(a)
            # This *should* dec' a and inc' z thus tests that items that are
            # replaced are also dec'ed.
            l[0] = z
            ra, rz = get_refcount(a), get_refcount(z)
            return l, ra, rz

        l, ra, rz = foo()
        self.assertEqual(l[0], "zyx")
        self.assertEqual(ra, 1)
        self.assertEqual(rz, 2)
```

**Comment by dlee992** [comment]
This is pretty nice, thanks! @esc 

Do we provide a way to get nrt_mstats using @intrinsic or etc, since I want to know the global view of NRT, not limit to several variables.

**Comment by esc** [comment]
> This is pretty nice, thanks! @esc
> 
> Do we provide a way to get nrt_mstats using @intrinsic or etc, since I want to know the global view of NRT, not limit to several variables.

Not sure, but do `grep` the code base. If not perhaps the links above would be sufficient to implement such functionality?

PS: I am not sure why you get that `TypeError`, so sorry.

**Comment by dlee992** [comment]
Hi, gently asking: I think the original error should be a bug, or feature request, more than a question?

**Comment by esc** [comment]
@dlee992 does the following resolve your issue:

```
import os
from numba import njit, objmode
import numpy as np
from numba.core.runtime import rtsys
from numba.core.serialize import PickleCallableByPath


os.environ["NUMBA_NRT_STATS"] = "1"

def call_rtsys():
    return rtsys.get_allocation_stats()

indirect_call_rtsys = PickleCallableByPath(call_rtsys)

@njit
def foo():
    np.ones(4)
    with objmode():
        print(indirect_call_rtsys())

foo()
```

**Comment by dlee992** [comment]
@esc, YES! magic! Thanks a lot!

**Comment by esc** [comment]
> @esc, YES! magic! Thanks a lot!
> 
> So `PickleCallableByPath` is the magic source?

Seems like it, yes.

> Feel free to close this.

Ok.
