### ISSUE TITLE
Can Numba use c++functions?

### ISSUE THREAD

**Issue by chen-erqi** [numba/numba#9635]
We are using CoolProp in Python, but unfortunately, this package is not implemented in Numba, and we cannot overload/overwrite it through numpy/python. 

So we think that can we write a python function to call CoolProp in C++ and we  introduce this python function into numba.

But we dont find a way to call C++ function in Numba in doc.

Can you tell us how to do this, thanks a lot!!!

**Comment by dlee992** [comment]
You can try with numba supported `ctypes` first. https://numba.readthedocs.io/en/stable/reference/pysupported.html#ctypes

**Comment by gmarkall** [comment]
As @dlee992 suggests probably `ctypes` support is the way to go here - however, note that you will need to call the mangled name of the C++ functions, and be aware of the ABI, etc. for anything complex.

If you need some more help with this, it's probably worth making a post describing more specifically what you're trying to do on the [Numba Discourse](https://numba.discourse.group) where someone might be able to point you in the right direction.

**Comment by chen-erqi** [comment]
> You can try with numba supported `ctypes` first. https://numba.readthedocs.io/en/stable/reference/pysupported.html#ctypes

thanks a lot!
I successfully make a link between dll, ctypes and numba.

**Comment by gmarkall** [comment]
Thanks for the update - would you be happy to close the issue?

**Comment by chen-erqi** [comment]
> Thanks for the update - would you be happy to close the issue?

hi! Unfortunately I have another question, Could you please give me a suggestion about that?
The question is that I want to pass a string into ctypes in Numba, but Numba seems doesnt support this operation.

**Comment by gmarkall** [comment]
You can do that with functions by wrapping them using the [Wrapper Address Protocol](https://numba.readthedocs.io/en/stable/reference/types.html#wrapper-address-protocol-wap)
