### ISSUE TITLE
unchecked out of bound when enable jit

### ISSUE THREAD

**Issue by Mskxn** [numba/numba#9638]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello, I find that when enabling jit, the bound check of `np.array` seems missing, we can construct arbitrary read and write based on this problem and hijack the control flow.
```python
from numba import jit
import numpy as np

@jit()
def r(offset):
    x = np.array([1, 2, 3])
    return x[offset] # expect IndexError but OOB

@jit()
def w(offset, value):
    x = np.array([1, 2, 3])
    x[offset] = value  # expect IndexError but OOB


# arbitrary read
for i in range(100):
    res = r(-(i))
    if res != 0:
        print(f"offset -{i}: {hex(res)}")

# arbitrary write
for i in range(10000):
    res = w(-i, 0xdeadbeef) # segmentation fault here, control flow hijack
```

I have repro it with `numba 0.60`, `numpy 1.26.x` and `2.0.0` and `python 3.10.12`

**Comment by gmarkall** [comment]
Bounds checking has a performance impact so it is disabled by default. You can turn it on with the `bounscheck=True` kwarg to the jit decorator. See https://numba.readthedocs.io/en/stable/reference/pysemantics.html#bounds-checking
