### ISSUE TITLE
Clarify nopython vs object mode in supported features documentation

### ISSUE THREAD

**Issue by seibert** [numba/numba#964]
The supported Python and NumPy features pages should make it clear whether something is supported in nopython mode.  This is probably easiest by listing things that are not supported in all modes, and then listing things that are supported in nopython mode.

**Comment by pitrou** [comment]
Right. Currently, it lists everything that's supported in nopython mode. "Supported in object mode" doesn't mean much, since by virtue of not typing anything and delegating to the actual Python objects, it supports basically everything (expect for some syntactic constructs).

**Comment by seibert** [comment]
I think the only change then is to specify that these pages describe "nopython mode" somewhere at the top.
