### ISSUE TITLE
cuInit fails also "else without an if"

### ISSUE THREAD

**Issue by joy-apexian** [numba/numba#9641]
## Reporting a bug

- [x ] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

My script is simple enough. i wanted to do cuda.detect()
which failed(obviously), now i kept debugging and found a code block which was raising an issue, i tried several different things including, installing in anaconda environment and outside in pyenv environment, using reinstalling cuda drivers and checking paths, 
My tensorflow is able to detect devices and so is pyuda 
This block of code in numba\cuda\cudadrv\driver.py seems to be the issue
```
    def ensure_initialized(self):
        if self.is_initialized:
            return

        # lazily initialize logger
        global _logger
        _logger = make_logger()

        self.is_initialized = True
        try:
            _logger.info('init')
            self.cuInit(0)
        except CudaAPIError as e:
            description = f"{e.msg} ({e.code})"
            self.initialization_error = description
            raise CudaSupportError(f"Error at driver init: {description}")
        else:
            self.pid = _getpid()

        self._initialize_extras()
```

i notice an else witout an if here but besides that `self.cuInit(0)` gives me error
`CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NO_DEVICE (100)`

python.__version__ == 3.9.19
cuda = 12.5

P.S, i dont want to mess with cuda version because it is well working for tensorflow.

**Comment by joy-apexian** [comment]
https://github.com/numba/numba/issues/6777#issuecomment-788273246

**Comment by sklam** [comment]
ping @gmarkall

**Comment by sklam** [comment]
btw, Python let's us do a `else` in `try-except`. The `else` block is for when no exception is raised.

**Comment by gmarkall** [comment]
Can you provide the output of `numba -s` please?
