### ISSUE TITLE
Change to versioning

### ISSUE THREAD

**Issue by markclare1992** [numba/numba#9648]
## Feature request

Is there any documentation on the reasoning behind the current versioning system for Numba?  It seems very difficult to integrate Numba into modern Python standards (Poetry & pyproject.toml).
For example, version 0.60.0 is a self defined Major release (and adds Numpy 2.0 support) but there is no way to prevent this version being used using pyproject.toml.
Is there any plans to migrate to more standard versioning?

**Comment by stuartarchibald** [comment]
Thanks for the report.

> ## Feature request
> 
> Is there any documentation on the reasoning behind the current versioning system for Numba?

I don't think that there is any documentation on the reasoning behind the current versioning system.

>It seems very difficult to integrate Numba into modern Python standards (Poetry & pyproject.toml). For example, version 0.60.0 is a self defined Major release (and adds Numpy 2.0 support) but there is no way to prevent this version being used using pyproject.toml.

Would something like `"numba <0.60.0"` work as a dependency constraint in `pyproject.toml`?

> Is there any plans to migrate to more standard versioning?

This issue will be discussed at the maintainer's triage meeting tomorrow, the notes of which are available from the meeting links on Numba's discourse forum and will also be published on Numba's wiki. I seem to recall it having been discussed previously and there were various concerns raised about moving to a 1.x or 2.x without there being something extremely significant about such a release.

**Comment by esc** [comment]
> ## Feature request
> Is there any documentation on the reasoning behind the current versioning system for Numba? It seems very difficult to integrate Numba into modern Python standards (Poetry & pyproject.toml). For example, version 0.60.0 is a self defined Major release (and adds Numpy 2.0 support) but there is no way to prevent this version being used using pyproject.toml. Is there any plans to migrate to more standard versioning?

Can you elaborate on what makes it very difficult to integrate? I don't really understand what the issue is. What would be a "more standard" versioning?

**Comment by markclare1992** [comment]
If I for example want to use Numpy in my project and know I need current 2.0 functionality, but also want any minor or patch updates, but no major (possibly breaking change updates) I can specify "numpy = "^2", which will allow >=2.0.0 <3.0.0.  I don't think this is possible with current Numba version specification? 
Also as 0.60.0 is a "major release", I would expect a "major" change i.e. 1.X.Y to 2.0.0

**Comment by esc** [comment]
Looking at:

https://python-poetry.org/docs/dependency-specification/#caret-requirements

You should be able to do `numba = ^0.60` this will allow `0.60.0` and `0.60.1` if it is released, but not `0.61.0` and beyond. Is that what you were wanting?
