### ISSUE TITLE
Numba njit  "parallel=True"& Function Signature & Tuple int64 

### ISSUE THREAD

**Issue by ratwolfzero** [numba/numba#9653]
##

Function  "generate_trajectory_image" and  Tuple  for "image_size " as input type in function signature

@njit('Tuple((uint32[:,:],`` float32[:]))(float32[:,:], Tuple((uint64, uint64)))', parallel=True)
def generate_trajectory_image(points, `image_size):
...

def main(image_size=(1000, 1000), color_map='hot'):
img, extents = generate_trajectory_image(points, `image_size)

The function signature above with Tuple((uint64, uint64)) for image_size will work

However, 

@njit('Tuple((uint32[:,:],`` float32[:]))(float32[:,:], Tuple((uint32, uint32)))', parallel=True)
will not work and throws the follwing error:

"AssertionError: Failed in nopython mode pipeline (step: native parfor lowering)
Storing i32 to ptr of i64 ('image_size_size0.19'). FE type int64"

This happens no matter if, where and which type (e.g. uint32) is declared for "image_size", 
or also if no type definition is made for image_size

in the function signature only int64 or uint64 is accepted as type for the tuple. 
Anything else throws an error as shown above

Full code see zip file 

- [ x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

[python_bug.py.zip](https://github.com/user-attachments/files/16237433/python_bug.py.zip)

**Comment by ratwolfzero** [comment]
Seems the issue is related to the use of "parallel=True"
Without "parallel=True" Tuple((uint32, uint32)) is working
With "parallel"True" Tuple((uint32, uint32)) is not working

**Comment by stuartarchibald** [comment]
Thanks for the report. A couple of things for the future:
1. To get code to format in a text box that supports markdown, use triple back-ticks either side of the code block, example:
   ````
   ```
   <put your code here>
   ```
   ````
2. The Numba project does not accept reproducers that cannot be inspected as plain-text (with regards to the zip file above). Thanks for making the `gist` based version available too.
 
I've taken a look and extracted the part that is seemingly causing a problem and cannot seem to reproduce. Which OS, Python and Numba version are you using? An alternative to pursuing this route is to simply remove the signatures, Numba in general doesn't need them and often does better without them. Numba has a type inference engine that will work out the type of all the arguments and propagate these through to the return type. If you are interested in seeing what types Numba used, do something like `my_jit_function.inspect_types()` and they will be printed to your terminal. Hope this helps?
