### ISSUE TITLE
Allow passing of NULL pointer in CUDA function

### ISSUE THREAD

**Issue by ed-o-saurus** [numba/numba#9655]
There is currently not a way to pass a `NULL` pointer to a C function from a compiled python function in CUDA. The value `cffi.NULL` should be valid in such functions.

**Comment by stuartarchibald** [comment]
Thanks for the report. Do you have a small code sample demonstrating the use case that you could share please? Such an example would be helpful in informing what to implement and checking a fix. Thanks again!

**Comment by ed-o-saurus** [comment]
Something like this should compile and work as expected.
```
from numba import cuda
import cffi

ffi = cffi.FFI()

func = cuda.declare_device('func', 'int32(CPointer(int32))')

@cuda.jit(link=['/content/func.cu'])
def kernel(values) :
  i_thread = cuda.threadIdx.x

  values[i_thread] = func(ffi.NULL)
```

**Comment by ed-o-saurus** [comment]
Is this still active?

**Comment by gmarkall** [comment]
Thanks for the ping, @ed-o-saurus - it will need to be implemented in https://github.com/NVIDIA/numba-cuda. I'll create an issue over there to ensure this doesn't get lost.

**Comment by gmarkall** [comment]
numba-cuda issue: NVIDIA/numba-cuda#44
