### ISSUE TITLE
Numba functions do not consider global variables from other modules as compile time constant.

### ISSUE THREAD

**Issue by Sumit112192** [numba/numba#9664]
## Reporting a bug
- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

As numba suggests, global variables are treated as compile-time constants, and it prunes branches based on the value of the global variables. However, it does not treat global variables from other modules as compile time constants. Specifically,
```
#File a.py
import numba
from numba.typed import List
import anotherGlobal

@numba.njit
def check():
  aList = List()
  if anotherGlobal.flag:
    aList.append(1)
  else:
    aList.append("a string")
  return aList
```
```
#File b.py
import anotherGlobal
def aFunc():
  anotherGlobal.flag = True
```
  
```
#File anotherGlobal.py
flag = False
```
```
#File main.py
from a import check
from b import aFunc
import anotherGlobal

aFunc()
check()
```
#The above code raises the error when main.py is executed.
```
.
.
.
impl_append(ListType[int64], unicode_type)
There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Overload in function 'impl_append': File: numba/typed/listobject.py: Line 592.
       With argument(s): '(ListType[int64], unicode_type)':
      Rejected as the implementation raised a specific error:
        TypingError: Failed in nopython mode pipeline (step: nopython frontend)
      No implementation of function Function(<intrinsic _cast>) found for signature:
        _cast(unicode_type, class(int64))
      There are 2 candidate implementations:
            - Of which 2 did not match due to:
            Intrinsic in function '_cast': File: numba/typed/typedobjectutils.py: Line 22.
              With argument(s): '(unicode_type, class(int64))':
             Rejected as the implementation raised a specific error:
               TypingError: cannot safely cast unicode_type to int64. Please cast explicitly.
        raised from /home/sam/.local/lib/python3.10/site-packages/numba/typed/typedobjectutils.py:75
      
      During: resolving callee type: Function(<intrinsic _cast>)
      During: typing of call at /home/sam/.local/lib/python3.10/site-packages/numba/typed/listobject.py (600)
      
      
      File "../../.local/lib/python3.10/site-packages/numba/typed/listobject.py", line 600:
          def impl(l, item):
              casteditem = _cast(item, itemty)
.
.
.
```
If the global variable is defined in `a.py,` it prunes the branches successfully, suggesting that it is now treated as compile time constants. It's a common practice that one would put all the config flags in one file and then want to prune branches using the config values. 

Is there a way to do this?

**Comment by esc** [comment]
Can you try using `from anotherGlobal import flag`?

**Comment by Sumit112192** [comment]
As far as I know about namespaces and global variables, this will add the flag variable to the global namespace of the module it is called in. However, the issue is that it only picks the initially defined flag's value rather than the updated value. 
I tried doing that. It runs but with the initial value and not the updated one.

**Comment by esc** [comment]
I just tried replicating the example above, there is a bug in the listing of `a.py`. The line `if antoherGlobal.flag:` should read `if anotherGlobal.flag:` ?

**Comment by esc** [comment]
I modified the code from `main.py` to read:

```
#File main.py
from a import check
#from b import aFunc
#import anotherGlobal

#aFunc()
check()
```

And I still receive the same error.

**Comment by esc** [comment]
> As far as I know about namespaces and global variables, this will add the flag variable to the global namespace of the module it is called in. However, the issue is that it only picks the initially defined flag's value rather than the updated value. I tried doing that. It runs but with the initial value and not the updated one.

Yes, I can confirm this.

**Comment by esc** [comment]
> Is there a way to do this?

Unfortunately it seems like the pattern you seek may currently not be possible with Numba.

**Comment by esc** [comment]
If it helps, the `check` function can also run without the `@njit` decorator, in this case the pattern is fine since `flag` will be interpreted dynamically.

**Comment by Sumit112192** [comment]
> I modified the code from `main.py` to read:
> 
> ```
> #File main.py
> from a import check
> #from b import aFunc
> #import anotherGlobal
> 
> #aFunc()
> check()
> ```
> 
> And I still receive the same error.

Yeah. The issue is not in the aFunc, but in the jitted function check(). aFunc is only there to change the value of the flag.

**Comment by Sumit112192** [comment]
> If it helps, the `check` function can also run without the `@njit` decorator, in this case the pattern is fine since `flag` will be interpreted dynamically.

Um, I simplified the code so a.py is looking simple. But it's complicated and runs various loops so I need to compile it with numba.

**Comment by esc** [comment]
> > If it helps, the `check` function can also run without the `@njit` decorator, in this case the pattern is fine since `flag` will be interpreted dynamically.
> 
> Um, I simplified the code so a.py is looking simple. But it's complicated and runs various loops so I need to compile it with numba.

Maybe you can split the functions into two, one that runs the types list with strings and one that runs it with integers and then use the flag predicate to decide on which to run?
