### ISSUE TITLE
RuntimeError: cannot cache function '_make_tree': no locator available

### ISSUE THREAD

**Issue by alyan111** [numba/numba#9668]
## Description

When trying to import the `rembg` library, which depends on `pymatting`, I'm encountering a RuntimeError from Numba. The error suggests that Numba is unable to locate the file for caching a function.

## Error Message

RuntimeError: cannot cache function '_make_tree': no locator available for file '/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/util/kdtree.py'

## Full Traceback

Traceback (most recent call last):
File "/home/path-to-dir/app.py", line 9, in <module>
from rembg import remove
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/rembg/init.py", line 5, in <module>
from .bg import remove
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/rembg/bg.py", line 16, in <module>
from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/init.py", line 2, in <module>
from pymatting.util import *
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/util/init.py", line 2, in <module>
from pymatting.util.kdtree import KDTree, knn
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/util/kdtree.py", line 8, in <module>
def _make_tree(
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/numba/core/decorators.py", line 225, in wrapper
disp.enable_caching()
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/numba/core/dispatcher.py", line 808, in enable_caching
self._cache = FunctionCache(self.py_func)
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/numba/core/caching.py", line 601, in init
self._impl = self._impl_class(py_func)
File "/home/path-to-dir/env-rembg/lib/python3.10/site-packages/numba/core/caching.py", line 337, in init
raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function '_make_tree': no locator available for file '/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/util/kdtree.py'

## Environment

 Operating System: Ubuntu 22.04.4 LTS
- Python version: Python 3.10.12
- Numba version: 0.60.0
- rembg version: 2.0.28
- pymatting version: 1.1.8

## Steps to Reproduce

1. Set up a virtual environment
2. Install rembg: `pip install rembg`
3. Create a Python file (e.g., app.py) with the following content:
   ```python
   from rembg import remove
4. Run the Python file

**I reinstalled the whole virtual env multiple time and it still generates the same error.**

Expected Behavior:
The import should succeed without errors.
Actual Behavior:
The import fails with the RuntimeError shown above.
Additional Context:
This error occurs in a virtual environment. It seems that Numba is unable to locate the file for caching, despite the file being present in the virtual environment's site-packages.
Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by esc** [comment]
Caching in Numba when used from packages can be a bit fickle. Can you look at:

https://github.com/numba/numba/issues/9312

perhaps this is somewhat of a duplicate of that?

**Comment by alyan111** [comment]
I tried to work around with `NUMBA_DEBUG_CACHE` and `NUMBA_CACHE_DIR` but it doesn't work, still gives the same error.

**Comment by esc** [comment]
I tried to reproduce this, but unfortunately could not. I tried the steps listed in the reproducer and received not error, so sorry.

**Comment by esc** [comment]
I would put a breakpoint somewhere in here: 

https://github.com/numba/numba/blob/main/numba/core/caching.py#L332

and try to see why non of the locators seem to be working. You can modify the installed Numba in the site-packages.

**Comment by esc** [comment]
We discussed this during the developer meeting today, our best guess is that the `site-packages` directory isn't writable. Numba will try to place the cached compiled variant of the function in `/home/path-to-dir/env-rembg/lib/python3.10/site-packages/pymatting/util/` so that directory needs to be writable by the user that is executing `python app.py`.

We are also surprised as to why `NUMBA_CACHE_DIR` doesn't work and would like to request more info. Please list the commands that you used in order to attempt this.

**Comment by hesic73** [comment]
I encountered the same issue in a docker container, which seems caused by volume mapping the host's `.cache` directory. The issue is resolved upon removing the mapping.
