### ISSUE TITLE
typed.List __repr__() 

### ISSUE THREAD

**Issue by seibert** [numba/numba#9677]
In Numba 0.60, I notice that the `__repr()__` for `typed.List` shows an ellipsis (as if there is more data) at the end of the list, even if the full array has been printed.  Example:
```
from numba.typed import List

l = List([1,2,3,4])
print(repr(l))
```
Output:
```
ListType[int64]([1, 2, 3, 4, ...])
```

This initially confused me as I thought there was more data in the list than what I put in.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce under `ipython` only. I think 77b9ffcc introduced this, seems like the logic to fix it would be to just check if the list is over 1000 elements long and only append a `...` to indicate truncation if so.

**Comment by LuniaKunal** [comment]
I tried same but have different output.
On same version.

When tried on colab shows the same bug.

```
from numba.typed import List
import numba

l = List([1,2,3,4])
print(repr(l))
print(numba.__version__)
```
![image](https://github.com/user-attachments/assets/9d1df8af-a524-4265-8763-bcca92bac519)

![image](https://github.com/user-attachments/assets/f6525226-ff50-4a5e-8141-f6cea76dbd01)

**Comment by alok-m** [comment]
@stuartarchibald Created a PR. 
This is my first issue, please let me know if I missed something. I'm interested in this project and look forward to helping out!
