### ISSUE TITLE
np.count_nonzero is incorrect when setting axis=0 for 1-dimensional array

### ISSUE THREAD

**Issue by luyiming** [numba/numba#9684]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When setting axis=0 for 1-dimensional array, `np.count_nonzero` is incorrect:
```python
import numpy as np 
import numba
@numba.njit
def count_nonzero(a, axis=None):
    nonzero = np.count_nonzero(a, axis=axis)
    return nonzero

a = np.array([1.0, 0.0, 1.0])
print(count_nonzero(a, axis=0))
print(np.count_nonzero(a, axis=0))
```

output:
```
True
2
```

However, when setting axis=None, it is correct:
```python
import numpy as np 
import numba
@numba.njit
def count_nonzero(a, axis=None):
    nonzero = np.count_nonzero(a, axis=axis)
    return nonzero

a = np.array([1.0, 0.0, 1.0])
print(count_nonzero(a, axis=None))
print(np.count_nonzero(a, axis=None))
```

output:
```
2
2
```

I believe the cause is the `np.sum` function:
```python
import numpy as np 
import numba
@numba.njit
def sum(x): 
    return x.astype(np.bool_).sum(axis=0)
a = np.array([1,0,1])
print(sum(a))
```
output:
```
True
```

**Comment by guilhermeleobas** [comment]
Hi @luyiming, thanks for the report. I can confirm this is indeed a bug in `np.sum` implementation. `np.sum(arr, axis=...)` uses the low level API and the typing decl. is missing a cast to integer (`_expand_integer(...)`) when the dtype is boolean:

https://github.com/numba/numba/blob/2001717f3321a5082c39c5787676320e699aed12/numba/core/typing/arraydecl.py#L779-L781

Would you like to send a patch fixing this bug?

**Comment by luyiming** [comment]
@guilhermeleobas Fix is sent, also added some tests for bool arrays.
