### ISSUE TITLE
Compilation failure with NumPy 2.0.1

### ISSUE THREAD

**Issue by bcbnz** [numba/numba#9687]
Trying to compile latest main (fb0caf6) with NumPy 2.0.1 fails when trying to compile `numba/_helperlib.c`:

    numba/_helperlib.c: In function ‘numba_cpowf’:
    numba/_helperlib.c:22:44: error: ‘I’ undeclared (first use in this function)
       22 |     #define _complex_float_ctor(r, i) (r + I * i)
          |                                            ^
    numba/_helperlib.c:147:12: note: in expansion of macro ‘_complex_float_ctor’
      147 |     *out = _complex_float_ctor((float) _out.real, (float) _out.imag);
          |            ^~~~~~~~~~~~~~~~~~~
    numba/_helperlib.c:22:44: note: each undeclared identifier is reported only once for each function it appears in
       22 |     #define _complex_float_ctor(r, i) (r + I * i)
          |                                            ^
    numba/_helperlib.c:147:12: note: in expansion of macro ‘_complex_float_ctor’
      147 |     *out = _complex_float_ctor((float) _out.real, (float) _out.imag);

This is due to a change in NumPy 2.0.1 to `#undef I` to avoid causing problems with other libraries, such as SymPy which generates code from user input which may contain the variable I. See the following discussions:

* Original bug report: numpy/numpy#26787
* Pull request with the change: numpy/numpy#26789
* A resulting bug report about compilation failure with some discussion about how to proceed: numpy/numpy#27083

To get numba to compile, changing

https://github.com/numba/numba/blob/fb0caf6b5a0ab00d0585cdc4aea25a0b35e3da22/numba/_helperlib.c#L22

to 

`    #define _complex_float_ctor(r, i) (r + _Complex_I * i)`

(i.e., the original constant that glibc `#defines` `I` to) allows compilation. I am not sure if this is a globally safe change or if it would need to exist within an `#if` block to select the appropriate constant for an environment. For reference, I am using Arch Linux,  GCC 14.2.1, glibc 2.40.

**Comment by gmarkall** [comment]
I think #9683 is addressing this.
