### ISSUE TITLE
TypingError when argument is None

### ISSUE THREAD

**Issue by auderson** [numba/numba#9706]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
@jit
def f(x, y=None):
    if y is not None:
        return np.add(x, y)
    else:
        y = x
        return np.add(x, y)

f(np.zeros(3), None)
```
It seems y is treated as NoneType in the ELSE branch:
![image](https://github.com/user-attachments/assets/af4b7a07-029d-4dac-80df-e364c38668c0)

The following code will work:
```python
@jit
def f(x, y=None):
    if y is not None:
        return np.add(x, y)
    else:
        # rename to _y
        _y = x
        return np.add(x, _y)

f(np.zeros(3), None)
# array([0., 0., 0.])
```

version 0.60.0

**Comment by sklam** [comment]
Yup, this is SSA related. The problem is that the argument is not counted as one of the definitions. In https://github.com/numba/numba/blob/4fc11d4169b085e904deb7d757c20ab46a99f005/numba/core/ssa.py#L158-L161, SSA is only applied to "violators", which are variables with more than one definition.
