### ISSUE TITLE
Py2.7: builtins.range not recognized

### ISSUE THREAD

**Issue by tritemio** [numba/numba#972]
When writing python 2/3 code `builtins.range` (iterator) is often used to replace `xrange` in python 2.7 and be compatible with python 3.

However numba fails to compile in `nopython` mode functions containing `builtins.range`. This makes difficult to use numba in a python 2/3 codebase.

The workaround I found to work is using in `past.builtins.xrange` that is correctly compiled by numba in both python 2 and 3.

**Comment by oyamad** [comment]
It seems like I had the same problem:
I ran simple code with `range` in nopython mode and got
```python
TypingError: Failed at nopython frontend
Untyped global name 'range'
```
But it worked with `xrange` in place of `range`.

Installed via Anaconda
* Python 2.7.9
* Numba 0.16.0

See http://nbviewer.ipython.org/gist/oyamad/6cf0ba762c304caabf93


However, this problem does not occur in my other custom Python environment:
* Python 2.7.8 (Homebrew)
* llvm 3.5.1 (Homebrew)
* llvmlite 0.2.2 (pip install)
* Numba 0.16.0 (pip install)

**Comment by oyamad** [comment]
Just to report, the problem has been resolved and `range` works perfectly now with Anaconda with Numba updated to the current version 0.18.1. Thanks.
