### ISSUE TITLE
@jit(target_backend='cpu') select loop mode for huge for loop

### ISSUE THREAD

**Issue by ganbaaelmer** [numba/numba#9721]
can i use it like:
```
# loop_mode = 'cuda' or 'cpu'
def looper(loop_mode):
     ......
    @jit(target_backend=loop_mode)
     for i in range (......
         .....
```
i mean can i use it like : 
`@jit(target_backend='cpu')`

@jit(target_backend=loop_mode)

for making library for huge for loop

**Comment by guilhermeleobas** [comment]
Hi @ganbaaelmer, I am not sure if I understood your question. Please, correct me if needed.

The `@jit` decorator is supposed to be used as a [function decorator](https://www.datacamp.com/tutorial/decorators-python). So, you cannot use it right before a for loop. However, you can move the loop into its own function and annotate it with `@jit`.

```python
@jit
def loop(args):
    for i in range(...):
        ....

def looper(loop_mode):
    r = loop(args)
```

As for the loop_mode, I understood you're trying to compile the jit function for different backends? If so, there's a `_target` option you can use:

```python
def gen_loop(loop_mode):
    @jit(_target=loop_mode)
    def loop(args):
        for i in range(...):
            ....
    return loop

def looper(loop_mode):
    r = gen_loop(loop_mode)(args)
```

**Comment by ganbaaelmer** [comment]
thank you can i use it directly on pandas dataframe?
loop like:

```
def gen_loop(loop_mode):
    @jit(_target=loop_mode)
    def loop(pandas_dataframe):
        for index, row in pandas_dataframe.iterrows()::
            df.loc[index, 'row1'] = df.loc[index, 'row2']
            ....
    return loop

def looper(loop_mode):
    r = gen_loop(loop_mode)(args)
```

**Comment by guilhermeleobas** [comment]
I'm not sure if Numba supports pandas out of the box. If that's the case, this won't work. What exactly are you trying to achieve?

**Comment by gmarkall** [comment]
If you're looking to run pandas code with CUDA, it may be worth looking at the cuDF Pandas accelerator and writing your code to the pandas API, rather than attempting to implement CPU / GPU logic yourself: https://rapids.ai/cudf-pandas/
