### ISSUE TITLE
we need native progress bar for numba @numba.jit for loop. like python tqdm library

### ISSUE THREAD

**Issue by ganbaaelmer** [numba/numba#9723]
## we need native progress bar for numba @numba.jit - "for loop".
 like python tqdm library

**Comment by gmarkall** [comment]
I did something like this for CUDA: https://github.com/gmarkall/numba-kernel-progress/blob/main/kernel_progress.py

For a CPU version you'd need a separate Python thread managing the progress bar, and some shared memory mechanism between the jitted code and the Python side to communicate the progress.

**Comment by kmnhan** [comment]
Check out https://github.com/mortacious/numba-progress

**Comment by gmarkall** [comment]
@kmnhan Thanks for pointing to that! Glad to see I guessed correctly a viable implementation strategy for a Numba-based progress bar :-)

**Comment by ganbaaelmer** [comment]
i think we need built-in progress bar for numba for loops. :)
