### ISSUE TITLE
python kernel keeps crashed

### ISSUE THREAD

**Issue by ganbaaelmer** [numba/numba#9724]
## Reporting a bug

- [ *] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ *] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```

num_iterations  = subscriber_user_id.shape[0]
num_iterations2 = billing_user_id.shape[0]
@numba.jit
def do_it_numba(subscriber_user_id, billing_user_id, subscriber_all_user_id, progress):
    for i in range(num_iterations):
        progress[0].update()

        for j in range(num_iterations2):
            if subscriber_user_id[i] == billing_user_id[j]:
                subscriber_all_user_id[j] = j
                
            else:
                pass

            progress[1].update(1)
            
        #print(i)
        # reset the second progress bar to 0
        progress[1].set(0)
        
    return subscriber_all_user_id


if __name__ == "__main__":
    # with ProgressBar(total=num_iterations) as progress:
    with ProgressBar(total=num_iterations, ncols=80) as numba_progress1, ProgressBar(total=num_iterations2, ncols=80) as numba_progress2:
        subscriber_all_user_id = do_it_numba(subscriber_user_id, billing_user_id, subscriber_all_user_id, (numba_progress1, numba_progress2))

```
python kernel keeps crashing

**Comment by ganbaaelmer** [comment]
##Jupyter [log](command:jupyter.viewOutput)
Visual Studio Code (1.93.0, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.0.
Pylance Extension Version: 2024.9.1.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\version-2024.8.1
Workspace folder ~\pandas-fast-nested-looper, Home = c:\Users\Client
16:11:30.493 [info] Starting Kernel (Python Path: ~\anaconda3\python.exe, Conda, 3.12.4) for '~\pandas-fast-nested-looper\src\pandas-fast-nested-looper\pandas-fast-nested-looper.ipynb' (disableUI=true)
16:11:34.129 [info] Process Execution: ~\anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:11:34.134 [info] Process Execution: ~\anaconda3\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.8.1-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 1568
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2024.8.1-win32-x64\pythonFiles\vscode_datascience_helpers
16:11:34.145 [info] Process Execution: ~\anaconda3\python.exe -m pip list
16:11:34.233 [info] Process Execution: ~\anaconda3\python.exe -m ipykernel_launcher --f=c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v3b8686f655cfe461fdcfd590c7474178ad665520c.json
    > cwd: ~\pandas-fast-nested-looper\src\pandas-fast-nested-looper
16:11:35.356 [info] Kernel successfully started
16:11:35.366 [info] Process Execution: ~\anaconda3\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.8.1-win32-x64\pythonFiles\printJupyterDataDir.py
16:11:46.427 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason: 
16:14:16.829 [info] Restart requested ~\pandas-fast-nested-looper\src\pandas-fast-nested-looper\pandas-fast-nested-looper.ipynb
16:14:16.831 [warn] Cancel all remaining cells due to dead kernel
16:14:16.836 [info] Process Execution: ~\anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:14:16.872 [info] Process Execution: ~\anaconda3\python.exe -m ipykernel_launcher --f=c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v39ed38761e5704aa5f8cec3f048df41c5e7763ab3.json
    > cwd: ~\pandas-fast-nested-looper\src\pandas-fast-nested-looper
16:14:17.919 [info] Restarted 235a7cfa-6ccb-45fe-b9e5-31c345d0849d
16:15:47.983 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason:

**Comment by ganbaaelmer** [comment]
i found error if there is input variable dtype is not int or float then loop failed and python kernel crashed. it didn't tell why the error occurred....

**Comment by kc611** [comment]
Hey @ganbaaelmer , Thank you for reporting the issue.

> i found error if there is function(input variable) dtype is not int or float then loop failed and python kernel crashed.

Sounds like you have a potential solution, but if the issue still isn't resolved, please do give a MWR (Minimum Working Reproducer) so that we can reproduce the issue on our side. For instance, The example you gave above does't provide context as to what the `ProgressBar` object is so it is difficult for us to reproduce/reslve from our side. Ideally the example can be directly run into a IDE and produces the same error.
