### ISSUE TITLE
TBB not found when installed with pip

### ISSUE THREAD

**Issue by cgadal** [numba/numba#9740]
Numba do not find TBB on my system while it has been installed via pip as mentioned in the documentation, and lead to the following warning 

> NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

also confirmed by running `numba -s|grep True`:

```
CUDA Device Initialized                       : True
llvmlite Using SVML Patched LLVM              : True
OpenMP Threading Layer Available              : True
Workqueue Threading Layer Available           : True
```

However, running: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/:/usr/lib/:/usr/lib64/:/home/username/.local/lib` fixes the problem:

```
CUDA Device Initialized                       : True
llvmlite Using SVML Patched LLVM              : True
TBB Threading Layer Available                 : True
OpenMP Threading Layer Available              : True
Workqueue Threading Layer Available           : True
```
I guess there is an issue in the default path numba is looking for tbb, maybe because there is another tbb version installed somewhere in my system?

Details:

- Ubuntu (20.04)
- numba (0.60.0)
- tbb: 2021.13.1

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is a known issue (or is related to), #6018. It has a long investigation, a summary of which is towards the end of the comments: https://github.com/numba/numba/issues/6108#issuecomment-675365997.

Numba's TBB based threading layer is linked against `libtbb.so.2`, how this linkage is resolved is based on the system linker's configuration etc. If a TBB version is present on the system and in a library search location that is searched ahead of the location of the desired TBB library, it will be found first and I think this is why you are seeing the problem described and also why setting the `LD_LIBRARY_PATH` fixes it.

Hope this helps?

**Comment by cgadal** [comment]
Oh Indeed, I did not see this. I'll update the system one via `apt` or set the `LD_LIBRARY_PATH` at the beginning of my scripts then.

Thanks!

**Comment by stuartarchibald** [comment]
No problem @cgadal, am glad you have found something that works!
