### ISSUE TITLE
compile error: msvc cl.exe "exit code 2"

### ISSUE THREAD

**Issue by Firestorm-253** [numba/numba#9749]
simply put, i get this error when i try to execute line 18 of below short script "cc.compile()"
i have installed the newest VC_redist.x64 (although it doesn't target it, but rather the older version).
when looking into the "cc", i also saw that according to the "target_file" it tries to aim at amd64?

![report](https://github.com/user-attachments/assets/44c3a6fe-9484-4d16-94bd-83b380dc9d35)

```py
from numba import pycc

cc = pycc.CC('my_func_module')

@cc.export('df', 'f8(f8)')
def jitted(x):
    return x ** 2

cc.compile()
```

[numba_test.py](https://github.com/user-attachments/files/17320456/numba_test.txt)

**Comment by kc611** [comment]
Hey @Firestorm-253, Thanks for reporting the issue. 

This seems like a configuration problem. Could you also post the output of 'numba -s' command from the environment in which you're working for further details, it'll be helpful to further debug the issue that you're facing.
