### ISSUE TITLE
Hybrid code: mpi4py ranks with parallel numba 

### ISSUE THREAD

**Issue by skwde** [numba/numba#9776]
There are multiple related discussion / issues going in the same direction

- [this numba issue](https://github.com/numba/numba/issues/8692) turns out to have the problem somewhere else
- [this numba discourse discussion](https://numba.discourse.group/t/limiting-number-of-numba-threads-in-mpi-hybrid-program/2517) mentions the same problem. 
 
The only suggestion in the mentioned discourse discussion is to use [`numba-mpi`](https://github.com/numba-mpi/numba-mpi/) which to my understanding does not apply to my use case because I don't want to use MPI communication inside `@jit`ed functions.
I want to run `@jit(parallel=True)`ed functions on multiple MPI ranks.

The [`mpi4py` discussion on threads in MPI nodes](https://github.com/mpi4py/mpi4py/discussions/79) suggest (at least to me) that the problem is with `numba`.

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Using the `test.py`

```py
#!/usr/bin/env python3
"""Showcase hybrid issue."""

import numba
from mpi4py import MPI


@numba.jit(parallel=True)
def parallel_sum(n):
    """Calculate the leibniz sum between the start and stop values."""
    s = 0.0
    for i in numba.prange(n):
        s = s + i
    return s


if __name__ == "__main__":
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()

    print(
        f"[{rank}]: Numba uses {numba.config.NUMBA_NUM_THREADS} thread(s). "
        f"Numba uses the '{numba.config.THREADING_LAYER}' threading layer."
    )

    n = int(1e10)

    sum = parallel_sum(n)

    print(
        f"[{rank}]: Used '{numba.threading_layer()}' threading layer "
        f"to calculate {sum}."
    )
```

and running it via 

```sh
mpiexec -n 2 python test.py
```

indicates that each `@jit(parallel=True)`ed function call only uses 1 thread.
This is also confirmed by checking e.g. via `htop`.

```out
[0]: Numba uses 1 thread(s). Numba uses the 'default' threading layer.
[1]: Numba uses 1 thread(s). Numba uses the 'default' threading layer.
[0]: Used 'tbb' threading layer to calculate 4.999999999006786e+19.
[1]: Used 'tbb' threading layer to calculate 4.999999999006786e+19.
```

So based on https://numba.readthedocs.io/en/stable/user/threading-layer.html running via

```sh
NUMBA_NUM_THREADS=8 mpiexec -n 2 python test.py
```

I expected to solve the problem.
But instead I got

```out
[1]: Numba uses 8 thread(s). Numba uses the 'default' threading layer.
[0]: Numba uses 8 thread(s). Numba uses the 'default' threading layer.
TBB Warning: The number of workers is currently limited to 0. The request for 7 workers is ignored. Further requests for more workers will be silently ignored until the limit changes.

TBB Warning: The number of workers is currently limited to 0. The request for 7 workers is ignored. Further requests for more workers will be silently ignored until the limit changes.

[1]: Used 'tbb' threading layer to calculate 4.999999999006786e+19.
[0]: Used 'tbb' threading layer to calculate 4.999999999006786e+19.
```

Ok, so why not using a different threading layer

```sh
NUMBA_THREADING_LAYER=omp NUMBA_NUM_THREADS=8 mpiexec -n 2 python test.py
```

but I observe the same behavior when looking at `htop`.

```out
[0]: Numba uses 8 thread(s). Numba uses the 'omp' threading layer.
[1]: Numba uses 8 thread(s). Numba uses the 'omp' threading layer.
[0]: Used 'omp' threading layer to calculate 4.999999999007629e+19.
[1]: Used 'omp' threading layer to calculate 4.999999999007629e+19.
```

the same is true for

```sh
NUMBA_THREADING_LAYER=workqueue NUMBA_NUM_THREADS=8 mpiexec -n 2 python test.py
```

```out
[1]: Numba uses 8 thread(s). Numba uses the 'workqueue' threading layer.
[0]: Numba uses 8 thread(s). Numba uses the 'workqueue' threading layer.
[1]: Used 'workqueue' threading layer to calculate 4.999999999007629e+19.
[0]: Used 'workqueue' threading layer to calculate 4.999999999007629e+19.
```

Based on my understanding of https://numba.readthedocs.io/en/stable/user/threading-layer.html I should see 2*8 cores (provided I have that many cores) being used when checking the `htop` output, right?

So what am I missing here?

**Comment by Konjkov** [comment]
Hello Stefan.

Leaving aside the possibility or impossibility of implementing MPI in NUMBA, what is the reason not to use MPI everywhere in the form of MPI message passing + MPI-3.0 shared memory programming?

Taking into account the arguments, I think this is a good option.
[HybridPP_Slides.pdf](https://github.com/user-attachments/files/17587954/HybridPP_Slides.pdf)

Vladimir

**Comment by skwde** [comment]
@Konjkov I am aware that there are different approaches, which depending on the problem, might be better suited.
Thanks for the PDF anyhow.

Actually this is just for an exercise idea I had for students. Since they know already how to parallelize on a single machine I figured that this is a nice way to mention hybrid programming. It also makes them aware / think about not to oversubscribe cores because parallelization can happen at multiple "levels" / software layers. 

When testing I figured that this should actually work, right?
I "merely" try to spawn threads from a mpi process.

**Comment by skwde** [comment]
Turns out, the slides you linked gave the crucial hint!

I have to tell MPI that I actually want multiple processing elements per slot.
So doing something like

```sh
NUMBA_NUM_THREADS=4 
mpiexec -n 2 --map-by slot:pe=${NUMBA_NUM_THREADS} python test.py
```

does what I want. 
It appears that `mpiexec` (from openmpi) is "smart" and ensures that `n*pe <= available cores`.

So it was not a NUMBA issue but a MPI user issue... What a surprise... ;)
Sorry for bothering and thanks for your response / help
