### ISSUE TITLE
A safe and clean wording to support Python class' static method/variables in jit function

### ISSUE THREAD

**Issue by victor-zou** [numba/numba#9788]
## A safe and clean way to support Python class' static method/variables in jit function
The need for approaching Python class' static method/variables in jit function has been put forward for years, like #5409 for example.
`Numba` still blames `Untyped global name xxx: Cannot determine Numba type of <class 'type'>` in v0.60. Main obstacle for supporting the feature lays in the side effects Python's `.`-expression may introduce by magic methods like `__get__`, `__getattribute__`, `__getattr__` etc. This issue is to suggest a wording that can cover most of use-case of Python class statics without risk of trigering side effects during compile time: **limiting/interpreting `.` expression for unrecognized types as `.__dict__["name"]`**.

```Python
class PythonClass:
    static_attr = 42

    @staticmethod
    @njit 
    def static_method():
        return 42

@njit  
def jit_function():
    # Will raise TypingError: `Untyped global name 'PythonClass': Cannot determine Numba type of <class 'type'>`
    return PythonClass.static_attr + PythonClass.static_method()
```
By introductin the wording, compiler will resolve `PythonClass.static_attr` as follows:
1. current impl of numba variable resoluion, which stops at cannot determining `PythonClass`
2. test if `PythonClass` has `__dict__` and if `static_attr` is in `PythonClass.__dict__`, if so, directly resolve `PythonClass.static_attr` as `PythonClass.__dict__["static_attr"]`
3. if cannot find the target in `__dict__`, raise `AttributeError`, not further searching `__class__`/`__mro__` as Python's `getattr`. 

We can see that, no side effect will happen during this process. The compiler does not need to evalute the dangerous `PythonClass.static_attr`.

This wording will forbidden the following use case:
1. `@property`, or other behaviors involving magic methods like `__get__`, `__getattribute__`, `__getattr__`
2. class from pyd/so that has no `__dict__`
3. name from its (base) classes. As the user may change his code resolving to them directly.

In addition, this wording will allow referencing to a compile-time const class instance's attribute, and I can think no reason to reject this like of expression.
 ```Python
class MyClass:
    def __init__(self):
        self.foo = 42

instance = MyClass()

@njit  
def jit_function2():
    return instance.foo   # compile-time const class instance's attribute
```

**Comment by sklam** [comment]
If I am understanding the request correctly, the OP requests the support of `staticmethod` for arbitrary classes by reading the `class.__dict__`. However, Numba limitation in handling compile-time static value will treat it as a compile-time constant, possibly not the intend semantic of the code. It's better to pass in the information as a parameter to the function. Or, if it is a known constant, you can make it a global of a module.

**Comment by victor-zou** [comment]
> If I am understanding the request correctly, the OP requests the support of `staticmethod` for arbitrary classes by reading the `class.__dict__`. However, Numba limitation in handling compile-time static value will treat it as a compile-time constant, possibly not the intend semantic of the code. It's better to pass in the information as a parameter to the function. Or, if it is a known constant, you can make it a global of a module.

It is a common practice to classify functions and constexpr variables into different classes. The proposition just fit the intend semantic of these codes. A class variable is not sematically more mutable than a module-level variable. It is not very likely that a user may mis-use this feature, as all numba-writers should aware that any global python constants/functions are constexpr.

I known there are workarounds, I can list at least three:
1. make them module level
    **con**: Names will get longer as have to define names with a common prefix. What is worse, you will need write a lot of tedious copy-paste if cannot change the codebase.
2. replace class definitions with small module definition
    **con**: so many source files, uneasy to navigate the codes
3. dynamically generate a module object or use exec to do the copy-paste
    **con**: it's more evil

As can be shown above, all workarounds have their drawbacks. Adding this support will make writing codes more convenient, not more error-prone.

**Comment by victor-zou** [comment]
@sklam Besides from reading `x.__dict__`, another more conservative way to support static variables/functions is, like fuction `register_jitable`, introducing a class decorator `class_statics_register_jitable`.  As the name suggests, register the class somewhere so that numba conpiler may recognize the class.

And if a user want to keep compitibility with previous numba versions, he may implement his backup version to translate a `class` as `module`.
```Python
if numba support:
      from numba import class_statics_register_jitable
else:
      def class_statics_register_jitable(cls):
          module = type(numba)  # don't know where to import it, it should be in some where
          m = module(cls.__name__)
          for k, v in cls.__dict__.items():
              if k.startswith("_"):
                  continue
                  setattr(m, k, v)
          return m
```
