### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by SlothScript** [numba/numba#9798]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I'm sure there are a lot of these, but it needs python 3.13 support. running `pip install numba` (in python3.13) will break it. This also breaks many other packages the rely on numba to not work in 3.13. Please add 3.13 release

bug.py
```python
import os
os.system("python3.13 -m pip install numba")
```

**Comment by esc** [comment]
@SlothScript was merged last week, coming in the next release. Duplicate is here: https://github.com/numba/numba/issues/9413

**Comment by esc** [comment]
@SlothScript please subscribe to the following thread for news and updates on the release: https://github.com/numba/numba/issues/9777
