### ISSUE TITLE
numba v0.61.0rc1 installation fails because missing MS Visual C++

### ISSUE THREAD

**Issue by Alpengreis** [numba/numba#9813]
I tried to install numba v0.61.0rc1 via pip on my windows 10 system. It fails as following:

```
      UPDATING build\lib.win-amd64-cpython-313\numba/_version.py
      set build\lib.win-amd64-cpython-313\numba/_version.py to '0.61.0rc1'
      running build_ext
      building 'numba._dynfunc' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
Failed to build numba
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numba)
```

Of course I have a MS Visual C++ runtime installed (system wide). Tried also with Cpython 3.12.7 - same problem.

It that known and exist a workaround?

**Comment by esc** [comment]
@Alpengreis thank you for reporting this, can you list the command you used to attempt the install? I don't think I have seen anyone report this error before.

**Comment by Alpengreis** [comment]
@esc 

Sure, it was:

`.venv\Scripts\python.exe -m pip install numba==0.61.0rc1`

That means it was within a virtual env. Just for info: I can install the v0.60 with the same command without any problem.

**Comment by suede299** [comment]
<img width="858" alt="{853F34BE-49CE-4FB4-A50F-A44F75DF9485}" src="https://github.com/user-attachments/assets/eff10dfe-8824-48f4-be96-d4bb3412e299">
I have the same problem

**Comment by Alpengreis** [comment]
Any news here?

**Comment by esc** [comment]
> Any news here?

We are currently working on producing binary artifacts for the RC, we hope that this will eliminate this issue by no longer needing any compilers during installation.

**Comment by esc** [comment]
> > Any news here?
> 
> We are currently working on producing binary artifacts for the RC, we hope that this will eliminate this issue by no longer needing any compilers during installation.

@Alpengreis the windows wheels for Numba 0.60.0rc1 have just arrived on PyPI, you should be able to `pip install` them now.

**Comment by Alpengreis** [comment]
@esc 

Was successful now, thanks very much!

**Comment by esc** [comment]
> @esc
> 
> Was successful now, thanks very much!

Wonderful, thank you for reporting back. Will close issue now, if there are still problems for anyone, please comment below and we will re-open this issue. Thank you all for helping to improve Numba.
