### ISSUE TITLE
Large overhead when launching kernel with torch tensors

### ISSUE THREAD

**Issue by materight** [numba/numba#9835]
When launching a CUDA kernel using a torch array as input, there is a significant overhead in the `as_cuda_array` call. Using this example (with `torch==2.5.1 numba==0.60.0`): 
```python
import numba.cuda
import torch
from tqdm import tqdm

N_RUNS = 10_000


@numba.cuda.jit(
    numba.void(
        numba.types.Array(numba.uint8, 3, "C"),
        numba.types.Array(numba.uint8, 3, "C", readonly=True),
        numba.types.Array(numba.boolean, 2, "C", readonly=True),
        numba.int32,
        numba.int32,
    ),
    fastmath=True,
)
def get_masked_crop(out, frame, mask, ymin, xmin):
    i, j = numba.cuda.grid(2)
    fi, fj = ymin + i, xmin + j
    if mask[fi, fj]:
        out[i, j, 0] = frame[fi, fj, 0]
        out[i, j, 1] = frame[fi, fj, 1]
        out[i, j, 2] = frame[fi, fj, 2]


def main() -> None:
    frame = torch.ones((1080, 1920, 3), dtype=torch.uint8, device="cuda:0")
    mask = torch.ones((1080, 1920), dtype=torch.bool, device="cuda:0")
    crop = torch.zeros((300, 300, 3), dtype=torch.uint8, device="cuda:0")

    # frame = numba.cuda.as_cuda_array(frame, sync=False)
    # mask = numba.cuda.as_cuda_array(mask, sync=False)
    # crop = numba.cuda.as_cuda_array(crop, sync=False)

    threads_per_block = (32, 32)
    blocks_per_grid = (
        math.ceil(crop.shape[0] / threads_per_block[0]),
        math.ceil(crop.shape[1] / threads_per_block[1]),
    )
    for _ in tqdm(range(N_RUNS)):
        get_masked_crop[blocks_per_grid, threads_per_block](crop, frame, mask, 50, 50)
        torch.cuda.synchronize()


if __name__ == "__main__":
    main()
```

When profiling with `nsys`, I get that each iteration takes around 350µs:
![image](https://github.com/user-attachments/assets/d7c1a3ef-9f0b-49b1-be5b-76c2a810e23a)
![image](https://github.com/user-attachments/assets/2c0ed8ec-ad9c-4126-8eb7-ab5a7e30a91e)

If I remove the commented lines and do the conversion once before the loop, each iteration takes ~110µs:
![image](https://github.com/user-attachments/assets/e8c8175e-05b9-4fc8-867d-42b43980b357)
![image](https://github.com/user-attachments/assets/adbf8903-f82e-4cb3-8903-3abfc4ebdab9)

Looking at the profiling trace it seems that most of the time is spent in the call to `as_cuda_array`.

**Comment by guilhermeleobas** [comment]
cc @gmarkall

**Comment by gmarkall** [comment]
Thanks for the report - as the CUDA target is moving to https://github.com/NVIDIA/numba-cuda I've linked to this issue there: https://github.com/NVIDIA/numba-cuda/issues/98

(Notes on the move: https://numba.readthedocs.io/en/latest/cuda/overview.html#cuda-deprecation-status)
