### ISSUE TITLE
indexing from ndarray

### ISSUE THREAD

**Issue by rainwoodman** [numba/numba#985]
In nopython mode, indexing from an ndarray, via tuple() raises an error:

Untyped global name 'tuple'

```
@numba.jit(nopython=True)
def func(a, b):
    a[tuple(b)] = 10
    return a
a = numpy.arange(10, dtype='f8').reshape(2, 5)
print func(a, numpy.array([1, 1], dtype='i4'))
```

However, the tuple from ndindex can index an array:

```
@numba.jit(nopython=True)
def func(a):
    for i in numpy.ndindex(a.shape):
       a[i] = 10
    return a
a = numpy.arange(10, dtype='f8').reshape(2, 5)
print func(a)
```

**Comment by seibert** [comment]
The problem here is that we do not have support for the `tuple()` function in nopython mode.  Given that nopython mode does not yet support memory allocation, we'll have to think about which uses of `tuple()` can be supported within that limitation.

**Comment by rainwoodman** [comment]
The use here doesn't need a memory allocation. 

The simplest case (and useful for indexing) is immediately the tuple is passed as a parameter to the [] operator, which can resolve the indirect indices. There is no need to allocate memory or to create a new object.
The second case is to index the tuple, which can be delegated to indexing the original array (which we may want to assert to be 1d). Also no need for new memory allocation.

**Comment by pitrou** [comment]
Well, the code from a pure Python standpoint does request the allocation of a tuple copying the second argument's contents. You are right that we could optimize that allocation away, but the current typing infrastructure wouldn't make that easy (we treat tuples as fixed-size structures, while numpy arrays are, well... arrays). I'm curious, what is your use case for this?

**Comment by rainwoodman** [comment]
Indexing a multi-dimentional mesh with an array in a cloud-in-cell approximation.
Because the dimension of the mesh is generic, a fixed size tuple can't do. 

Currently I assume the mesh is in C order and manually index in a ravelled view:
https://github.com/rainwoodman/pypm/blob/master/pypm/_cic.py#L94

I thought allowing array indexing via tuple may produce better looking code. Or is there a better way?

**Comment by rainwoodman** [comment]
semms to me, an ir.Intrinsic tuple function that returns a  UniTuple shall get the type inference stage through?

**Comment by stuartarchibald** [comment]
Closing as https://github.com/numba/numba/issues/2771 has considerable discussion on the topic of `tuple()` support.
