### ISSUE TITLE
Searching for CUDA libs: lib vs lib64?

### ISSUE THREAD

**Issue by arunoruto** [numba/numba#9852]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am currently working on NixOS and was trying to run my application using CUDA. Everything seems to be installed just fine, except numba, or so it seemed. I opened an [issue at nixpkgs](https://github.com/NixOS/nixpkgs/issues/365262), but it might be also related to how numba is searching for libs.

I have been running `numba -s` and `python -c "from numba import cuda; cuda.cudadrv.libs.test()"` to check if the libraries have been found, but no luck. I compared the directory structure of cudatoolkit on an Ubuntu and NixOS system, and the only things that differs is the lib folder:
- Ubuntu uses lib64
- Nixos uses lib
Is it possible that numba is only searching in a lib64 folder for the files? If I preprend `LD_LIBRARY_PATH=$CUDA_HOME/lib` to my commands, it detects everything fine (except the static one, since it is in a different folder).

If this issue is due to the files not being in lib64, is there a possibility to also search for the files in the `lib` folder of the cudatoolkit?

To reproduce the issue, one can execute the following commands on a system hosting the `nix` command:
```sh
nix-shell -p 'python312.withPackages(ps : with ps; [ numbaWithCuda ])'
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```
resulting in
```log
Finding driver from candidates:
        libcuda.so
        libcuda.so.1
        /run/opengl-driver/lib/libcuda.so
        /run/opengl-driver/lib/libcuda.so.1
        /usr/lib/libcuda.so
        /usr/lib/libcuda.so.1
        /usr/lib64/libcuda.so
        /usr/lib64/libcuda.so.1
Using loader <class 'ctypes.CDLL'>
        Trying to load driver...        ok
                Loaded from libcuda.so.1
        Mapped libcuda.so paths:
                /nix/store/9xyylgpsldqfbx7abjyvz42amharnm3d-nvidia-x11-565.77-6.6.64/lib/libcuda.so.565.77
Finding nvvm from Nix store
        Located at libnvvm.so
        Trying to open library...       ERROR: failed to open nvvm:
libnvvm.so: cannot open shared object file: No such file or directory
Finding nvrtc from Nix store
        Located at libnvrtc.so
        Trying to open library...       ERROR: failed to open nvrtc:
libnvrtc.so: cannot open shared object file: No such file or directory
Finding cudart from Nix store
        Located at libcudart.so
        Trying to open library...       ERROR: failed to open cudart:
libcudart.so: cannot open shared object file: No such file or directory
Finding cudadevrt from <unknown>
        Located at libcudadevrt.a
        Checking library...     ERROR: failed to find cudadevrt:
libcudadevrt.a not found
Finding libdevice from Nix store
        Located at /nix/store/3v3r8yyfrpjkwb3mzpwvz77ybpsp7wgp-cuda_nvcc-12.4.99/nvvm/libdevice/libdevice.10.bc
        Checking library...     ok
```
Feel free to check the nixpkgs issue for a more detailed comparison into the problem.
I do think it is possible to patch this problem, by creating a `lib64` symlink which points to `lib` in the cudatoolkit package, but it could take a long time due to many packages depending on it.

**Comment by gmarkall** [comment]
It looks like all the regular library search logic is patched out of Numba in NixOS, so it's difficult to suggest much from this end - looks like from the nixpkgs issue you're in a position where you have things working though?

**Comment by arunoruto** [comment]
> It looks like all the regular library search logic is patched out of Numba in NixOS, so it's difficult to suggest much from this end - 

Thanks for the information! It seems like it isn't a numba problem, so I will close the issue.

> looks like from the nixpkgs issue you're in a position where you have things working though?

I found a way to symlink the lib to lib64, and now it seems to work. If the consensus is in favor of my "fix", I will patch it up upstream :)

**Comment by gmarkall** [comment]
Thanks for following up!
