### ISSUE TITLE
Import Matlab m-files

### ISSUE THREAD

**Issue by ijstokes** [numba/numba#988]
@pzwang suggested this a few months ago, but I've just come across it.  A very cool Numba (NumbaPro?) feature would be to translate Matlab M-Files and allow imports of existing M-files, probably along these lines:

```python
func = numba.importm('/path/to/func.m')
```

Some pointers on this from Peter's email:

1. Matlab parser: https://github.com/ericharley/matlab-parser
2. PLY: http://www.dabeaz.com/ply/ (probably don't need to point you guys to this)
3. Some comments from Peter when he brought it up:

This is for both sales and devs, if ever presented with the question of how to interface between Python and Matlab or SAS.

I found this good SO link listing various options:
http://stackoverflow.com/a/23762412/246502

It looks like the top current contenders are:
http://mlabwrap.sourceforge.net/
https://code.google.com/p/pymat2/
https://github.com/ewiger/mlab
https://github.com/jaderberg/python-matlab-bridge

This last one, OMPC, looks interesting because it's actually a Matlab -> Python compiler:
http://ompc.juricap.com/

Maybe this could be a feature in NumbaPro? numba.importm("/path/to/file.m")
:-)

**Comment by seibert** [comment]
I have not done much work with Matlab, but I would have expected the biggest effort required for translating code would be the translation of calls to functions in Matlab's equivalent of the standard library.  The mappings to existing Python and Numpy functions might be fairly straightforward, but I'm not sure.

**Comment by pitrou** [comment]
Out of curiosity, what's the intended complexity of M-files that would be useful to "import"?

**Comment by seibert** [comment]
Closing because this is definitely out of scope for Numba.
