### ISSUE TITLE
Support for the buffer protocol

### ISSUE THREAD

**Issue by seibert** [numba/numba#989]
It would be very useful if Numba could handle objects that support the buffer protocol in the same way we handle Numpy arrays.

**Comment by lgautier** [comment]
I would also think that it would be good.

The current workaround is to use `numpy.asarray`, but it would be simpler and cleaner to have support for the buffer protocol.

**Comment by pitrou** [comment]
This may lead to unexpected results. For example, slicing array.array or bytearray returns a copy, not a view.
Perhaps we should only support such objects in read-only mode? And support memoryviews in read-write mode, since slicing a memoryview returns a view...
