### ISSUE TITLE
'Module' object has no attribute 'global_variables'

### ISSUE THREAD

**Issue by xmduhan** [numba/numba#992]
I just install the numba, and run code below:
---------------------------------------------------------------------
from numba import jit
from datetime import datetime

def test01(x):
    n = 0
    for i in range(x):
        for j in  range(x):
            n += 1
    return n

@jit
def test02(x):
    n = 0
    for i in range(x):
        for j in  range(x):
            n += 1
    return n

def testit(func,x):
    starttime = datetime.now()    
    func(x)    
    endtime = datetime.now()
    dt = endtime-starttime
    print 'running %f seconds' % dt.total_seconds()

#%%
testit(test01,10000)

#%%
testit(test02,10000)

----------------------------------------------------------------------------
when run "testit(test02,10000)", I get Exception, full stack is here: 

----------------------------------------------------------------------------
>>> testit(test02,10000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in testit
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 157, in _compile_for_args
    return self.compile(sig)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 277, in compile
    flags=flags, locals=self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 547, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 293, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 301, in compile_bytecode
    return self._compile_bytecode()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 534, in _compile_bytecode
    return pm.run(self.status)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 191, in run
    raise patched_exception
AttributeError: Failed at object (object mode frontend)
Failed at object (object mode backend)
'Module' object has no attribute 'global_variables'
----------------------------------------------------------------------------
Is it a bug? Or how can I solve this problem?
Thanks a lot!

**Comment by seibert** [comment]
What version of numba and llvmlite did you install?

**Comment by xmduhan** [comment]
numba (0.17.0)
llvmlite (7d571f369cc002d44640a1d72248bc75b3e9f7b5)  the newest version in github

**Comment by seibert** [comment]
Ah, those versions are not compatible due to a very recent change made to the development version of llvmlite that required a corresponding change in the development version of numba.

You should either install numba 0.17.0 and llvmlite 0.2.2 (https://pypi.python.org/pypi/llvmlite/0.2.2) or install both numba and llvmlite from github.

**Comment by xmduhan** [comment]
It works!
Thank you so much!!!!

**Comment by xmduhan** [comment]
Code running in incredible speed.Thanks to numba!

**Comment by seibert** [comment]
Thanks!  Glad it is working for you.  :)
