### ISSUE TITLE
Documentation: enumerate which features are supported on CUDA

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#997]
Things that work in nopython mode and don't require any additional support from _helperlib or anything added by `CPUContext` should work on CUDA. However, it is difficult to find out/explain exactly which features satisfy these requirements - this should be fixed by going through and listing in the documentation exactly what works.

**Comment by pitrou** [comment]
@seibert

**Comment by pitrou** [comment]
Is this still TODO?

**Comment by seibert** [comment]
I think this might still be a todo.  We don't explain in the CUDA docs what standard Python functions are available on the device (like parts of math, but only those provided in NVIDIA's device math library).

This also reminds me that we might want to support using the NumPy math functions on scalar arguments on the GPU, for convenience.

**Comment by gmarkall** [comment]
This looks done - there is a list at http://numba.pydata.org/numba-doc/latest/cuda/cudapysupported.html#standard-library-modules
